### ISSUE TITLE
Refactor how tests are run

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#10]
- Move test execution logic out of `TestResult`
  - Use `TestResult` just as a Collecting Parameter to collect test results
- Before the test execution starts
  - Use a `TestSuiteIterator` to get all tests that are to be run from the top-level `TestSuite`
    - Use `FilterIterator` implementations to filter tests based on `--filter`, `--group`, and `--exclude-group`, for instance
    - This allows the number of tests that are to be run to be calculated correctly before the tests are actually run
  - Sort the tests according to `@depends` annotations
- Delay creation of `TestCase` objects and clean them up immediately after a test has been run
  - Allows for more elegant implementation of test execution in isolated PHP processes
  - Allows for running the tests in random order
  - Reduces memory footprint

**Comment by iltar** [comment]
Before I report this as a bug, as it seems to be a design issue. Running tests with `--filter` causes _all_ data providers to run. For some reason a test was failing when running it by file name rather than with a filter, as it was influenced by a data provider.

**Comment by CC007** [comment]
> - Sort the tests according to @depends annotations

What is the status of this?

**Comment by Idrinth** [comment]
wouldn't it make sense to also delay the creation of DataProviderTestSuites when doing this? They'd still need to collect all the data  beforehand with the proposed changes, keeping them rather large.

This would obviously need the data providers to either be run twice(i.e. one for counting, one later for the data) or allow for changes to the testcase maximum count once the provider is being processed.

**Comment by sebastianbergmann** [comment]
Data providers should be run once. If that means that counting no longer works and we need to change how progress is displayed, so be it.

**Comment by keradus** [comment]
data providers can provide also a label for cases, which one can use as a value for tests filter he want to run,
this feature shall not be broken by accident

**Comment by sebastianbergmann** [comment]
Superseded by #3213.
