### ISSUE TITLE
PHP settings not recognized when using process isolation

### ISSUE THREAD

**Issue by mburtscher** [sebastianbergmann/phpunit#1013]
I configured some `$_SERVER` variables to be set for tests using the XML file:

``` xml
<phpunit>
  <php>
    <server name="SERVER_PORT" value="80" />
  </php>
</phpunit>
```

Works fine but not with process isolation. When marking a test with `@runInSeparateProcess` I get an "Undefined index: SERVER_PORT" error.

**Comment by kyale** [comment]
The related issue #757 has nothing to to with the issue described above. I have a fix for this issue and would like to submit a pull request.
