### ISSUE TITLE
Automatically rerun failed tests to test for "flaky" tests

### ISSUE THREAD

**Issue by timbozo** [sebastianbergmann/phpunit#1022]
When a test fails - particularly with integration tests - that failure may be due to many factors related to environment or code that relies on some form of global state.

In order to keep test failures completely actionable to the exact commit under test, I'm requesting PHPUnit's native ability to rerun a test "failure" any config-defined number of times, and, if any of those re-runs pass, to mark the test as suspect for abnormal behavior.

I see the potential for running a test as follows:
1 test passes = Success
1 test fails, $n reruns with 100% failure = Failure
1 test fails, $n reruns and <100% failure = Abnormal

**Comment by PieterDC** [comment]
Apache Maven Surefire has this feature: http://maven.apache.org/surefire/maven-surefire-plugin/examples/rerun-failing-tests.html 
And Jenkins has a plugin that supports it: https://wiki.jenkins-ci.org/display/JENKINS/Flaky+Test+Handler+Plugin

Looks convenient, but we would like to stick with PHPUnit ;-)
Who's up for the task?

Ps: the Python community has https://github.com/box/flaky

**Comment by PieterDC** [comment]
Initial code for an approach that builds upon the already existing `--repeat` parameter can be found at https://github.com/sebastianbergmann/phpunit/pull/1708.

**Comment by deepa2083** [comment]
is this something that we will get in the near future?

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
