### ISSUE TITLE
PHPUnit_Util_Diff::diff does not account for delta parameter for array comparisons

### ISSUE THREAD

**Issue by drock** [sebastianbergmann/phpunit#1027]
If you compare two arrays containing floating point values, you may pass a delta parameter to the assertEquals function and this will be used as an epsilon value when comparing any floating point numbers within the arrays.

This comparison appears to work correctly in terms of the actual test on the values, however, if any other elements in a tested array fail comparison, the diff that is reported on failure will still report the floating point numbers as not matching even though they pass the epsilon test.

Example:
```php
public function testDeltaPassdown()
{
        $expected = array(1.00000001, 1);
        $actual = array(1.0001, 1);

        $this->assertEquals($expected, $actual, '', 0.1);
}
```

Will correctly report that the test has passed, indicating that the delta parameter is indeed being accounted for in the actual comparisons.

However
```php
public function testDeltaPassdown()
{
        $expected = array(1.00000001, 1);
        $actual = array(1.0001, 2);

        $this->assertEquals($expected, $actual, '', 0.1);
}
```
will report with the following failure message
```
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    0 => 1.00000001
-    1 => 1
+    0 => 1.0001
+    1 => 2
 )
```

This makes it appear as if element 0 failed the comparison when it did not, only element 1 did.  This causes much added work to investigate the actual delta used and compare it to the output to find out which parts the array actually failed comparison.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
