### ISSUE TITLE
[Proposal]

### ISSUE THREAD

**Issue by GrahamCampbell** [sebastianbergmann/phpunit#1137]
PSR-4 namespacing. Could we adopt PSR-4 namespacing for phpunit 4.0, and across the other repos in their next major release? Now seems like a good time to make a move towards more modern namespacing and class names.

**Comment by LionsAd** [comment]
Just for the record, Drupal (which currently ships PHPUnit in require for various reasons) would very much love to see native namespacing as its currently quite a large part of the shipped classmap.
