### ISSUE TITLE
JSON log file that can be parsed 

### ISSUE THREAD

**Issue by robfe11** [sebastianbergmann/phpunit#1156]
Please refer to this ticket: https://github.com/sebastianbergmann/phpunit/issues/142 

Redirecting the "--log-json" output to a log file creates an invalid JSON file.  

There are use cases where the output of phpunit will need to be parsed by other processes, hence, an additional flag to create a valid JSON log file is required.

**Comment by ls-adrian** [comment]
Any ETA on this? `--log-json` doesn't actually log JSON.

In order to be consistent, I propose that `--log-junit` dump out invalid XML garbage in the same manner that `--log-json` does.

**Comment by sebastianbergmann** [comment]
I do not have an ETA on this as I will not implement this. Send a pull request and I'll review it and merge it. The only hard part should be to come up with a name for the flag as the existing commandline option and configuration setting must not change their behavior.

**Comment by hack3r3d** [comment]
I'm not sure why the --log-json outputs invalid json, but I did this to fix it.
json_decode('[' . str_replace('}{', '},{', $json) . ']');

That wraps the json object representations in an array structure and replaces }{ with },{ so that I end up with an array of objects. 

http://webdeveloper.gdemolished.com/phpunit-log-json-is-broken-heres-how-to-fix-it/

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
