### ISSUE TITLE
PHPUnit 4.0 doesn't have Runner class to get the version

### ISSUE THREAD

**Issue by bskendig** [sebastianbergmann/phpunit#1167]
My tests that ran successfully under PHPUnit 3.7.32 are failing under 4.0 because of this error, on line 23 of Zend's ControllerTestCase.php (http://framework.zend.com/svn/framework/standard/branches/release-1.12/library/Zend/Test/PHPUnit/ControllerTestCase.php):

Fatal error: require_once(): Failed opening required 'PHPUnit/Runner/Version.php'

It appears that PHPUnit 4 no longer has a PHPUnit_Runner_Version class, so therefore the previous method of programmatically getting PHPUnit's version (see http://stackoverflow.com/a/4837785/548862) will no longer work.

Having a backwards-compatible way to still use this class to avoid having to patch Zend Framework would be ideal.

**Comment by zhaoteng0526** [comment]
Got same issue when I try to perform in WIndows7 & php-5.4.45-nts-Win32-VC9-x86 & PHPUNit4.8.14. I've tried to downgrade phpunit to phpUnit3.x but no luck. Any idea about this?
