### ISSUE TITLE
PHPUnit and Generators

### ISSUE THREAD

**Issue by lcobucci** [sebastianbergmann/phpunit#1174]
I'm opening this so we can have a little discussion before changing anything.

The question is: what should be the best way to test PHP 5.5+ generators?

On the first time I needed to test them I've used the ```$this->assertCount()``` because the Generator class implements the Iterator interface and ```iterator_count()``` was doing the job.

But with the changes from 36cc20f7f7efa52947a48cd0d11de1742a28231e PHPUnit is trying to rewind the generator which throws an exception.

Should we check if is a generator and don't rewind the object or should we think a better way to test generators?

**Comment by sebastianbergmann** [comment]
We probably need to add a special case for generators.

**Comment by lcobucci** [comment]
I agree @sebastianbergmann.
Just asserting the output can do the job, but I don't think it will be enough (adding mocks and coroutines to our discussion and things can get complicated).

Do you have any idea?

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
