### ISSUE TITLE
Isolated tests don't inherit chosen php.ini

### ISSUE THREAD

**Issue by kornelski** [sebastianbergmann/phpunit#1191]
I have _one_ installation of PHP, but multiple `php.ini` configs in order to be able to enable Xdebug selectively.

Similarly to solution in #665 I launch tests via `php -c my-config.ini /usr/bin/phpunit`, but this breaks down when phpunit spawns a child process without the arguments.

I used to work around by setting `PHP_BINARY` environmental variable to point to my wrapper shell script that sets the right arguments, but the change in #1051 removed that ability by limiting it to HHVM only.

It'd be useful if you restored ability to override php binary with `PHP_BINARY` env var for regular PHP, or added another method of specifying PHP binary and/or its arguments.

**Comment by jclebreton** [comment]
A workaround is to set the `PHPRC` environment variable to point to a directory containing your custom `php.ini`.
