### ISSUE TITLE
setUpBeforeClass() should be called first, before dataProviders

### ISSUE THREAD

**Issue by Bilge** [sebastianbergmann/phpunit#1206]
Since overriding the constructor in test case classes causes PHPUnit to fail to run the test cases, the equivalent functionality provided by `setUpBeforeClass()` should actually be equivalent by running before all other code, including data providers. 

Without this capability, a data provider cannot rely on data provided by initialization code, which is a significant oversight.

I have read that data providers "need" to execute first to determine how many tests are in the case, but I don't accept that because the number of tests in the case does not determine whether `setUpBeforeClass()` runs, ergo it should always run and it should do so *before* the data providers.

**Comment by frenetic** [comment]
Isn't this discussion a duplication of this: https://github.com/sebastianbergmann/phpunit/issues/836

Note: just found both links when googling for this problem.

**Comment by jasonLwwe** [comment]
I'm also wondering about status on this, it seems like a significant limitation.

**Comment by TomasVotruba** [comment]
This has been declined before and writen to documentation, see https://github.com/sebastianbergmann/phpunit-documentation/pull/86

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
