### ISSUE TITLE
Binary Data Assertion Output

### ISSUE THREAD

**Issue by Rican7** [sebastianbergmann/phpunit#1225]
Similar to the previously fixed issue #306, I've run into issues when an assertion fails with binary data causing malformed terminal output.

It seems that the #306 fix corrected the output in `assertEquals()`, but was never fixed for `assertSame()`.

Here's a reproduction:
```php
<?php

class FooTest extends PHPUnit_Framework_TestCase
{
    protected function generateBinaryString()
    {
        // Sample 4x4 red rectangle PNG
        return base64_decode(
            'iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAYAAACp8Z5+AAAAEklEQVQIW2P8z8AARAjASLoAAD+9B/3rBEHIAAAAAElFTkSuQmCC'
        );
    }

    public function testFooEquals()
    {
        $this->assertEquals('', $this->generateBinaryString());
    }

    public function testFooSame()
    {
        $this->assertSame('', $this->generateBinaryString());
    }
}
```

Bad output:
```
1) FooTest::testFooEquals
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-''
+Binary String: 0x89504e470d0a1a0a0000000d4948445200000004000000040806000000a9f19e7e0000001249444154085b63fccfc0004408c048ba00003fbd07fdeb0441c80000000049454e44ae426082

/mnt/storage_raid/srv/www/dev/rican7/php-filemanager/phpunit-gh-issue-306.php:14

2) FooTest::testFooSame
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-
+?PNG
+
+
+IHD?IDA[c??H????AIEND?B`?

/mnt/storage_raid/srv/www/dev/rican7/php-filemanager/phpunit-gh-issue-306.php:19
```

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
