### ISSUE TITLE
Retire pear.phpunit.de

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#1229]
- [x] As of sebastianbergmann/phpunit-documentation@ed5264d the PEAR installation method is no longer listed in the documentation for PHPUnit 3.7
- [x] As of 70b02c6 PHPUnit 3.7 shows a message that the PEAR installation is no longer supported when PHPUnit was installed via PEAR. PHPUnit 3.7.35 is the last release of PHPUnit 3.7 that is made available as a PEAR package.
- [x] As of sebastianbergmann/phpunit-documentation@05bffa8, PEAR is not advertised as an installation method for PHPUnit 4.0
- [x] As of 70b02c6 PHPUnit 4.0 shows a message that the PEAR installation is no longer supported when PHPUnit was installed via PEAR. PHPUnit 4.0.17 is the last release of PHPUnit 4.0 that is made available as a PEAR package.
- [x] No new releases are published on `pear.phpunit.de`
- [x] Add a note to the PHPUnit website announcing the shutdown of http://pear.phpunit.de/
- [x] Add a note to http://pear.phpunit.de/ announcing the shutdown
- [x] Add a note to the PHPUnit documentation about the shutdown of http://pear.phpunit.de/ and provide help with migration
- [x] Shut down http://pear.phpunit.de/ (no later than December 31, 2014)

**Comment by beldougie** [comment]
Big :+1: for the move away from PEAR towards composer!

**Comment by tamal3209** [comment]
+1
