### ISSUE TITLE
Testsuite with no tests breaks junit logger

### ISSUE THREAD

**Issue by jason-yang** [sebastianbergmann/phpunit#1250]
I have testsuites where it will conditionally skip tests, this may result in a testsuite with 0 tests. This displays correctly in commandline when executed and no errors were thrown.

However, with the ```--log-junit=junit.xml``` option, the log file goes buts when there is a testsuite that has no tests:

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="Shopper">
    <testsuite name="Coupon">
      <testsuite name="CouponZaversGetOffersTest" file="/path/to/CouponeZaversGetOffersTest.class.php">
        <testsuite name="CouponBrowseSproutsTest" file="/var/lib/jenkins/jobs/API_Branches_Template/workspace/test/unit/shopper/coupon/CouponBrowseSproutsTest.class.php" tests="1" assertions="388" failures="0" errors="0" time="0.376127">
          <testcase name="testGoodMambo" class="CouponBrowseSproutsTest" file="/var/lib/jenkins/jobs/API_Branches_Template/workspace/test/unit/shopper/coupon/CouponBrowseSproutsTest.class.php" line="57" assertions="388" time="0.376127"/>
        </testsuite>
      </testsuite>
    </testsuite>
  </testsuite>
</testsuites>
```

This just an extract of the full file, but you can already see the craziness of it:
- testsuite elements missing all the attributes: tests, assertions, failures...etc.
- ```CouponZaversGetOffersTest``` and ```CouponBrowseSproutsTest``` are supposed to be at the same level, however ```CouponBrowseSproutsTest``` is somehow nested under ```CouponZaversGetOffersTest```
- I have log files with nested levels up to 20, when my max nested level should only be 3

**Comment by reinaldomendes** [comment]
Any solutions ?

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
