### ISSUE TITLE
assertSame doesn't show diffs within arrays

### ISSUE THREAD

**Issue by jacobweber** [sebastianbergmann/phpunit#1252]
If I use `assertEquals` on two arrays, and one of their elements are different, it shows a helpful line-by-line diff:
```
$this->assertEquals(array('a' => false), array('b' => 0));
```
```
1) FooTest::testFoo
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    'a' => false
+    'b' => 0
 )
```
But if I use `assertSame` instead, it doesn't indicate where the differences are. This can make it difficult to see the error, if the arrays are big.
```
$this->assertSame(array('a' => false), array('b' => 0));
```
```
1) FooTest::testFoo
Failed asserting that Array &0 (
    'b' => 0
) is identical to Array &0 (
    'a' => false
).
```

It would be nice if there were a way to get the diff using assertSame.

**Comment by jacobweber** [comment]
Tested on PHPUnit 4.4.5 -- same result.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
