### ISSUE TITLE
Running phpunit.phar generates a lot of Undefined index notices

### ISSUE THREAD

**Issue by roland-d** [sebastianbergmann/phpunit#1255]
Hello,
In an effort to try and get PHPUnit running I see a lot of these notics come by:

Notice: Undefined index: SCRIPT_NAME in phar://D:/server/php/phpunit.phar/phpunit/Util/Filter.php on line 69

Call Stack:
    0.0114     367048   1. {main}() D:\server\php\phpunit.phar:0
    0.0123     563168   2. PHPUnit_TextUI_Command::main() D:\server\php\phpunit.phar:584
    0.0123     566952   3. PHPUnit_TextUI_Command->run() phar://D:/server/php/phpunit.phar/phpunit/TextUI/Command.php:132
    1.8032   63293944   4. PHPUnit_TextUI_TestRunner->doRun() phar://D:/server/php/phpunit.phar/phpunit/TextUI/Command.php:179
    1.9561   63830200   5. PHPUnit_Framework_TestSuite->run() phar://D:/server/php/phpunit.phar/phpunit/TextUI/TestRunner.php:426
   84.4922  135775816   6. PHPUnit_Framework_TestSuite->run() phar://D:/server/php/phpunit.phar/phpunit/Framework/TestSuite.php:675
   84.9213  136167344   7. PHPUnit_Framework_TestCase->run() phar://D:/server/php/phpunit.phar/phpunit/Framework/TestSuite.php:675
   84.9214  136167312   8. PHPUnit_Framework_TestResult->run() phar://D:/server/php/phpunit.phar/phpunit/Framework/TestCase.php:753
   84.9303  136193816   9. PHPUnit_Framework_TestResult->addError() phar://D:/server/php/phpunit.phar/phpunit/Framework/TestResult.php:760
   84.9304  136193992  10. PHPUnit_Util_Log_JUnit->addError() phar://D:/server/php/phpunit.phar/phpunit/Framework/TestResult.php:275
   84.9304  136194176  11. PHPUnit_Util_Filter::getFilteredStacktrace() phar://D:/server/php/phpunit.phar/phpunit/Util/Log/JUnit.php:176

At the end when it is generating the code coverage report I get these notices:
Notice: Undefined index: REQUEST_TIME in phar://D:/server/php/phpunit.phar/php-code-coverage/CodeCoverage/Report/Clover.php on line 71
Notice: Undefined index: REQUEST_TIME in phar://D:/server/php/phpunit.phar/php-code-coverage/CodeCoverage/Report/Clover.php on line 75

I tried to suppress notices but it seems this is ignored all together making these notices problematic as reading the test results becomes very difficult.

This is running PHPUNit 4.1.0

**Comment by nibra** [comment]
I came across the same issue recently from one moment to the other after an `composer update`. As far as I can tell, there happened some mess with the autoloader. My work-around is to run the tests in a docker container.

**Comment by davidjeddy** [comment]
Same issue as @nibra but do not have the option to run in a container. App stack: CentOS6, Apache2.3, MySQL 5.6, PHP 5.6, Yii 2.0.6, CodeCeption 2.2.

```BASH
./vendor/bin/codecept run --coverage --coverage-xml --coverage-html
...
Time: 5.93 seconds, Memory: 46.50MB

OK (8 tests, 17 assertions)

                                 
  [PHPUnit_Framework_Exception]  
  Undefined index: REQUEST_TIME  
                                 

run [--report] [--html [HTML]] [--xml [XML]] [--tap [TAP]] [--json [JSON]] [--colors] [--no-colors] [--silent] [--steps] [-d|--debug] [--coverage [COVERAGE]] [--coverage-html [COVERAGE-HTML]] [--coverage-xml [COVERAGE-XML]] [--coverage-text [COVERAGE-TEXT]] [--no-exit] [-g|--group GROUP] [-s|--skip SKIP] [-x|--skip-group SKIP-GROUP] [--env ENV] [-f|--fail-fast] [--no-rebuild] [--] [<suite>] [<test>]

```

**Comment by fps01** [comment]
@davidjeddy I've same problem. Tell me please if you fix it.
Someone can help us with it?

PHP5.5.9 Ubuntu 14.04 PHPUnit 4.8.26 Codeception 2.2.3 Yii 2

Command:
`vendor/codeception/codeception/codecept run functional --coverage-html /home/user/www/report --verbose`

Part of output:
```shell
Time: 689 ms, Memory: 33.75MB

OK (1 test, 2 assertions)

                                 
  [yii\base\ErrorException (8)]  
  Undefined index: REQUEST_TIME  
                                 

Exception trace:
 () at /home/user/www/myproject/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/Text.php:121
 Codeception\Coverage\Subscriber\Printer->printConsole() at /home/user/www/myproject/vendor/codeception/codeception/src/Codeception/Coverage/Subscriber/Printer.php:62
 Codeception\Coverage\Subscriber\Printer->printResult() at /home/user/www/myproject/vendor/symfony/event-dispatcher/EventDispatcher.php:174
 ::call_user_func() at /home/user/www/myproject/vendor/symfony/event-dispatcher/EventDispatcher.php:174
 Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() at /home/user/www/myproject/vendor/symfony/event-dispatcher/EventDispatcher.php:43
 Symfony\Component\EventDispatcher\EventDispatcher->dispatch() at /home/user/www/myproject/vendor/codeception/codeception/src/Codeception/Codecept.php:226
 Codeception\Codecept->printResult() at /home/user/www/myproject/vendor/codeception/codeception/src/Codeception/Command/Run.php:271
 Codeception\Command\Run->execute() at /home/user/www/myproject/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /home/user/www/myproject/vendor/symfony/console/Application.php:821
 Symfony\Component\Console\Application->doRunCommand() at /home/user/www/myproject/vendor/symfony/console/Application.php:187
 Symfony\Component\Console\Application->doRun() at /home/user/www/myproject/vendor/symfony/console/Application.php:118
 Symfony\Component\Console\Application->run() at /home/user/www/myproject/vendor/codeception/codeception/src/Codeception/Application.php:103
 Codeception\Application->run() at /home/user/www/myproject/vendor/codeception/codeception/codecept:33

run [--report] [--html [HTML]] [--xml [XML]] [--tap [TAP]] [--json [JSON]] [--colors] [--no-colors] [--silent] [--steps] [-d|--debug] [--coverage [COVERAGE]] [--coverage-html [COVERAGE-HTML]] [--coverage-xml [COVERAGE-XML]] [--coverage-text [COVERAGE-TEXT]] [--no-exit] [-g|--group GROUP] [-s|--skip SKIP] [-x|--skip-group SKIP-GROUP] [--env ENV] [-f|--fail-fast] [--no-rebuild] [--] [<suite>] [<test>]
```

**Comment by davidjeddy** [comment]
@fps01 Not fix yet, sadly means setup on code coverage has halted :S.

**Comment by tyteen4a03** [comment]
I'm not sure if this is related to this issue, but I have [some tests here](https://travis-ci.org/tyteen4a03/OAuth/jobs/147667287) and they seem to be failing with the same error message.  I checked my code and the code involved does not modify globals.

**Comment by flowl** [comment]
I have the same problem using PHP 5.5, composer, PHPUnit 3 & 4, ZF1.

    Notice: Undefined index: SCRIPT_NAME in vendor/phpunit/phpunit/src/Util/Filter.php on line 29

I even put the following in my bootstrap.php

    $_SERVER['SCRIPT_NAME'] = __FILE__;
    $GLOBALS['_SERVER']['SCRIPT_NAME'] = __FILE__;

Without success. I the only logical reason is something (composer, xdebug, ... ) is unsetting either of those superglobals. Or could it be caused by some process isolation stuff?

**Comment by flowl** [comment]
If anyone's interested, this is what causes the behaviour:
1. Test (current class or by inheritance) is annotated with `@runInSeperateProcess`
2. Test throws (on purpose or not) an Exception
3. `PHPUnit_Util_Filter::getFilteredStacktrace()`  gets called

This seems to be the solution:
Add the annotation `@preserveGlobalState enabled` to the class that throws an exception.

**Comment by flowl** [comment]
I added the 'do not convert warnings to exceptions' to the phpunit xml:

```
<phpunit
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://schema.phpunit.de/4.8/phpunit.xsd"
        colors="true" bootstrap="bootstrap.php"
        convertNoticesToExceptions="false"
        convertWarningsToExceptions="false">
```

and REMOVED all `@runInSeperateProcess` annotations (there was only 1 in our whole code).
The Superglobals still get lost somewhere in PHPUnit! 

If I change the following line in `vendor/phpunit/phpunit/src/Util/Filter.php`, (`getFilteredStacktrace()`) it looks much better:

    $script = $GLOBALS['_SERVER']['SCRIPT_NAME']);

to: 

    $script = isset($GLOBALS['_SERVER']['SCRIPT_NAME']) ? realpath($GLOBALS['_SERVER']['SCRIPT_NAME']) : '';

**Comment by andreskrey** [comment]
Just FYI, in my case I have one test with the following assignment:

```
$_SERVER = [
    'Test-Header' => 'dummyData'
];
```

This was overwriting the $_SERVER var completely, deleting critical keys like REQUEST_TIME. I solved this by assigning keys directly instead of declaring a new array:

```
$_SERVER['Test-Header'] = 'dummyData';
```

**Comment by BafS** [comment]
Any new about this issue ? `SCRIPT_NAME` is not always set.

**Comment by andreskrey** [comment]
@BafS Then it's not PHPUnit's problem

**Comment by BafS** [comment]
@andreskrey sure but it could help a lot to handle this case in PHPUnit, it's a risk to assume that this variable will always be set imho.
