### ISSUE TITLE
PHPUnit 4.2-dev / Fatal error: Call to undefined method Mock ... ::staticExpects()

### ISSUE THREAD

**Issue by mwjames** [sebastianbergmann/phpunit#1256]
When running on a PHPUnit 3.7.37 production environment the following test runs as expected.

``` php
$store = $this->getMockBuilder( '\Store' )
    ->disableOriginalConstructor()
    ->setMethods( array( 'setupStore' ) )
    ->getMockForAbstractClass();

$store::staticExpects( $this->once() )
    ->method( 'setupStore' );
```

``` php
abstract class Store {
...
    public static function setupStore( $verbose = true ) {
        doSomething();
    }
...
}
```

However when running the test against PHPUnit 4.2-dev (details below) suddenly it complains with:

```
Fatal error: Call to undefined method Mock_Store_e62c26be::staticExpects()
```
- Installing phpunit/phpunit (dev-master f284576) Cloning f284576f0345dffe3c25330be481c6240f5aa641
- Installing phpunit/phpunit-mock-objects (dev-master 4dada9d) Cloning 4dada9d8762055e292d79142adbdde56c113b21a

**Comment by raymondjplante** [comment]
Might want to add a note to this blog as to which version this is no longer supported: https://sebastian-bergmann.de/archives/883-Stubbing-and-Mocking-Static-Methods.html
