### ISSUE TITLE
Split the assertion tool as a separate package

### ISSUE THREAD

**Issue by stof** [sebastianbergmann/phpunit#1257]
the PHPUnit assertion system is really useful. Because of that, it is common for Behat extensions to introduce a dependency on PHPUnit to reuse the assertions rather than re-implementing them (Behat wants to get an exception to mark a scenario as failed, so the PHPUnit_Framework_AssertionFailedError works out of the box).
However, depending on `phpunit/phpunit: ~4.0` means depending on at least 12 packages. But many of them are useless when only the assertions are used as they are needed by the test runner, not the assertion system.

Could it be possible to extract the assertion system as a separate package to be able to use it outside PHPUnit ? Thanks to composer, this should make almost no difference for PHPUnit users as the assertion system would be installed automatically when installing PHPUnit.

**Comment by stof** [comment]
any news about this ?

**Comment by localheinz** [comment]
@sebastianbergmann @stof 

Is this still relevant?

Because if it is, I am happy to tackle it!

**Comment by sebastianbergmann** [comment]
@localheinz and others did a lot of work on this. In the end we realized that it 1) requires even more work and 2) is not worth the effort.
