### ISSUE TITLE
PHPUnit does not report errors in XML configuration files

### ISSUE THREAD

**Issue by nconstant** [sebastianbergmann/phpunit#127]
Here is the output from a command prompt window:

```
C:\nate>phpunit --version
PHPUnit 3.5.9 by Sebastian Bergmann.


C:\nate>dir
 Volume in drive C is OS
 Volume Serial Number is 34DD-4D8B

 Directory of C:\nate

01/19/2011  01:48 PM    <DIR>          .
01/19/2011  01:48 PM    <DIR>          ..
01/19/2011  01:00 PM               142 build-number.txt
01/19/2011  10:27 AM             2,435 build.xml
01/19/2011  01:39 PM    <DIR>          htdocs
01/19/2011  01:41 PM    <DIR>          includes
01/19/2011  01:47 PM                 0 out.txt
01/19/2011  11:58 AM             2,064 phpunit.xml
01/19/2011  01:41 PM    <DIR>          test
01/19/2011  01:41 PM    <DIR>          test-reports
01/19/2011  01:41 PM    <DIR>          test2
               4 File(s)          4,641 bytes
               7 Dir(s)  13,535,272,960 bytes free

C:\nate>phpunit --configuration phpunit.xml
```

**Comment by brooksie155** [comment]
This issue is still prevalent, even upgrading to latest version, PHPUnit 4.8.6, I often end up with test scripts only running so far before exiting with code 255.

I have found this may be due to class not found, or method not found, or method parameters missing or all number of things which are potentially either notices or fatal errors. 

The question is why do you exit with code 255 leaving developers completely in the dark rather than reporting the cause of the error?

**Comment by sebastianbergmann** [comment]
What do "class not found", "method not found", etc. have to do with the XML configuration file?

**Comment by brooksie155** [comment]
I'm referring to the issue of phpunit throwing exit code 255 with no other information whenever it hits something unexpected - perhaps this should be another issue. 

FYI just noticed the problem, looks like I was trying to access a protected method. So why does phpunit not output 'PHP Fatal error: Cannot access protected method'?

**Comment by sebastianbergmann** [comment]
PHPUnit does not output errors like that, PHP does. PHPUnit does not prevent such errors from being printed, custom error handlers do that.

**Comment by brooksie155** [comment]
As far as I am aware I do not have any custom error handlers, and not only does it not print the PHP errors, phpunit also dies at that test and ceases to continue. 

However I think I have found the cause in my bootstrap I had the line:
error_reporting(E_ALL & E_STRICT & ~E_DEPRECATED);

as oppose to 
error_reporting(E_ALL & ~E_DEPRECATED);

Thanks.
