### ISSUE TITLE
Provide a way to force set an environment variable from phpunit.xml

### ISSUE THREAD

**Issue by gena01** [sebastianbergmann/phpunit#1276]
I would love to be able to override an environment variable when running unit tests. This is currently failing if that variable is already set before I run PHPUnit.

See here:
https://github.com/sebastianbergmann/phpunit/blob/master/src/Util/Configuration.php#L550

**Comment by ramsey** [comment]
I was expecting the `<env>` value set in my `phpunit.xml` file to override the one set in my `.bashrc` file in my console, but it looks like #1181 changed the behavior so that I can no longer do this. I don't want to unset my console's environment variables each time I run tests. Is there some work-around for this?

**Comment by lucacri** [comment]
Same problem for me. It definitely needs to have some sort of override since most of the environment I create have ENV variables set for the user..

**Comment by terbooter** [comment]
+1
`phpunit.xml` should override ENV vars

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
