### ISSUE TITLE
Bad coverage reports

### ISSUE THREAD

**Issue by Vicente69** [sebastianbergmann/phpunit#1299]
Hi Sebastian,

I'm facing a problem, but I don't know if it's an issue or a configuration problem.
To help reproduce this problem, I created a simple class ```MyClass``` with a static method.
Then I created a test class ```CoverageReportTest``` for this method, with one assertion.
Finally, when I look at the generated coverage reports (XML, HTML, text, ...), they are empty, the MyClass class is not mentioned, and I don't understand why.
I used PHPunit 4.1.3 PHAR archive, and I can see differences in the generated coverage reports if I use PHPunit 3.7 PHAR archive. However, none of them seems correct to me.
Could you tell what I'm doing wrong please?
Here's my PHPunit XML configuration (located in the project's root directory):
```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit backupGlobals="false"
         backupStaticAttributes="false"
         colors="true"
         convertErrorsToExceptions="true"
         convertNoticesToExceptions="true"
         convertWarningsToExceptions="true"
         processIsolation="false"
         stopOnFailure="false"
         syntaxCheck="false"
    >
    <testsuites>
        <testsuite name="Test Suite">
            <directory>test</directory>
        </testsuite>
    </testsuites>
    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory>src</directory>
        </whitelist>
    </filter>
    <logging>
        <log type="coverage-clover" target="reports/phpunit-4.1.3.coverage.xml" />
        <log type="junit" target="reports/phpunit-4.1.3.xml" />
        <log type="coverage-html" target="reports/phpunit-4.1.3.coverage.html" />
    </logging>
</phpunit>
```
Here's the MyClass.php file (located in the 'src' directory):
```
<?php
class MyClass
{
    public static function returnConstant()
    {
        return true;
    }
}
```
Here's the test class (located in the 'test' directory):
```
<?php

require "src/MyClass.php";

class CoverageReportTest extends PHPUnit_Framework_TestCase
{
    public function testErrorTest()
    {
        $this->assertTrue(MyClass::returnConstant());
    }
}
```
I start PHPunit from the command line, in the project's root directory.

Thanks in advance for your clarifications.
BR

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
