### ISSUE TITLE
Execution time increases dramatically with process isolation

### ISSUE THREAD

**Issue by Vicente69** [sebastianbergmann/phpunit#1300]
Hi,

I'm facing an important performance issue with tests execution when 'process isolation' is enabled.
The context is a web application (Symfony 2.5), and automated tests are executed with phpunit 4.1.1 in a continuous integration server (Jenkins up-to-date), on an Ubuntu 14.04 LTS 64 bits workstation.

When I enable process isolation in my phpunit XML configuration, I can see execution time dramatically increases. My test suite contains 12 tests and 148 assertions.

Without process isolation, the test suite is executed in 4 min 30 s.
With process isolation, the test suite is executed in 28 min 30 s.

I've repeated the tests with different PHPunit PHAR archives:
With PHPunit 4.1.1 and PHPunit 4.1.3, the same issue occurs.
With PHPunit 3.7.30, no issue, the test suite is executed "normally", without significant differences.

It seems to me the execution time increases at the end of each test, just like if it was very hard with process isolation to clean everything, and terminate the test's process. However, I can't tell exactly what's happening.
Moreover, on my own workstation (Windows 7), with the command line, there is no particular issue with process isolation.

Thanks in advance for your clarifications.
BR

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
