### ISSUE TITLE
testsuite support for groups

### ISSUE THREAD

**Issue by dmitrybelyakov** [sebastianbergmann/phpunit#1305]
Hi!

I just want to make a suggestion that when configuring testsuites via xml it would be really nice to allow inclusion/exclusion by group.

A simple application of this might be an ability to tell phpunit to run certain tests first (@group unit) and longest last (@group integration) and otherwise control test execution sequence.

Currently we need either manually type in each test  case file in suite or split tests for a single entity into multiple files in order to put them in separate directories which is a maintenance headache.

Thank you and have a great day :)

**Comment by fieg** [comment]
@whatthejeff the <group> configuration is not supported inside the <testsuite> element. I believe that is what @dmitrybelyakov meant (correct me if I'm wrong) and that would indeed be very helpful. For example to split tests and have them executed in a specific order (the order in which the test suites are defined).

**Comment by dmitrybelyakov** [comment]
@fieg that was exactly my point

**Comment by whatthejeff** [comment]
Sorry, I misunderstood :)

**Comment by im-denisenko** [comment]
Any progress here? :)

I was looking for the same thing: ordered groups inside one testsuite.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
