### ISSUE TITLE
PHP Notice Not Converted to Exception in DataProvider

### ISSUE THREAD

**Issue by GazEdge** [sebastianbergmann/phpunit#1316]
I seem to be having a problem with notices not being converted to exceptions. I have made sure that convertNoticesToExceptions="true".

The notice only seems to not be converted to an exception when the offending line of code is in a dataProvider. If I have an undefined index in one of my tests, an exception is thrown as expected.

PHPUnit 3.7.37
PHP Version => 5.4.10

    /**
    * @dataProvider provider
    */
    public function testSomething($something){
    }

    public function provider(){
        $array = array('defined'=>'ok');
        $test = $array['undefined'];
        return array(array('something'));
     }

Notice: Undefined index: undefined in /MyApp.php on line 32'

    public function testSomethingElse() {
        $array = array('defined'=>'ok');
        $test = $array['undefined'];
    }

PHPUnit_Framework_Error_Notice : Undefined index: undefined

**Comment by robertfausk** [comment]
Will there be any progress on this issue?

**Comment by joshuaspence** [comment]
+1

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
