### ISSUE TITLE
PHP Fatal error:  Class 'PHPUnit_TextUI_Command' not found in /usr/bin/phpunit on line 583

### ISSUE THREAD

**Issue by feridmovsumov** [sebastianbergmann/phpunit#1329]
I installed phpunit with following command on Ubuntu 13.10

```
sudo apt-get install phpunit
```

I get following error when I try to run phpunit from terminal

```
phpunit --version
```

**_PHP Fatal error:  Class 'PHPUnit_TextUI_Command' not found in /usr/bin/phpunit on line 583**_

**_Php Version**_ 5.5.3-1ubuntu2.5 (cli)

**Comment by t1gor** [comment]
Have the same issue. phpunit installed via composer: `composer require phpunit/phpunit`

php version:
```
php --version
PHP 5.6.31 (cli) (built: Jul 14 2017 06:07:30)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
```

Somehow composer is just not adding `PHPUnit_TextUI_Command` to the autoload.

```
cat vendor/composer/autoload_classmap.php | grep PHPUnit_Text
    'PHPUnit_TextUI_ResultPrinter' => $vendorDir . '/phpunit/phpunit/PHPUnit/TextUI/ResultPrinter.php',
    'PHPUnit_TextUI_TestRunner' => $vendorDir . '/phpunit/phpunit/PHPUnit/TextUI/TestRunner.php',
```

Any ideas why this might be happening?

**Comment by suab321** [comment]
Use this to let autoloader know of your changes
`composer dump autoload`
