### ISSUE TITLE
Invalid file path in configuration doesn't produce an error

### ISSUE THREAD

**Issue by dohpaz42** [sebastianbergmann/phpunit#1339]
PHPUnit: 4.1.3 on PHP 5.3.28 under Mac OS X (Mavericks) and Linux (CentOS 6)

If a file definition in a testsuite declaration points to a non-existent file (maybe a mistyped path), phpunit will silently ignore the error. 

**Expected result:**
Some sort of failure/error reporting that the file could not be found and loaded

**Current result:**
Silently ignored.

There doesn't seem to be a flag to pass to phpunit to enforce testing the existence of the defined files. I do see that `PHPUnit_Runner_StandardTestSuiteLoader::load()` does test throw a `PHPUnit_Framework_Exception` if a suite class could not be loaded, but it does not seem to be triggered. 

If I run `phpunit Foo/Bar.php` then I do get an error that the file could not be opened. It's only when running phpunit using a configuration file. For example, the following config demonstrates the problem:

```xml
<phpunit>
	<testsuites>
		<testsuite>
			<file>Foo/Bar.php</file>
		</testsuite>
	</testsuites>
</phpunit>
```

I have tried passing `--strict` and `--verbose` with no change in expected output.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
