### ISSUE TITLE
Replace Util/GetOpt with Symfony Console

### ISSUE THREAD

**Issue by sun** [sebastianbergmann/phpunit#1355]
The current CLI options/arguments parsing in `PHPUnit_Util_GetOpt` offers a suboptimal UX, because options have to be specified before arguments.

Proposal: Replace `PHPUnit_Util_GetOpt` with [Symfony Console](https://github.com/symfony/console).

Console has an excellent options/argument parser, which allows you to specify options anywhere in the command line.  Also used by [Composer](https://github.com/composer/composer).

However, for this proposal, we probably need to consider two additional aspects:
1. Similar to #1342, Console uses PHPUnit for its own tests, so what happens if Console has a bug that causes commands to not be run?  How do you debug that?
2. If PHPUnit depends on Console, then projects, which depend on PHPUnit for testing, but also on Console, will have to specify the dependency in a way that is compatible with PHPUnit's.

**Comment by sergeyz** [comment]
Considering we are moving to PSR2\PSR4 I suggest to replace arguments like class+file `phpunit [options] UnitTest [UnitTest.php]` with multiple files

**Comment by Idrinth** [comment]
I'm wondering what the allowed range of symfony/console should be.
- `^4`
- `^3|^4`
- `^2|^3|^4`

I think versions 3 and 4 are pretty much required to make any composer based installs possible.
2 is very similar to 3, so that might only be a tiny addition in workload

**Comment by sebastianbergmann** [comment]
I have decided not to do this.
