### ISSUE TITLE
@requires runtime

### ISSUE THREAD

**Issue by marcioAlmada** [sebastianbergmann/phpunit#1356]
So I have some tests that should not run against HHVM runtime and others that should run only with HHVM. This can be easily achieved with:

``` php
if(defined('HHVM_VERSION'))   $this->markTestSkipped(); // non HHVM
if(! defined('HHVM_VERSION')) $this->markTestSkipped(); // HHVM only
```

But would be nice to have a way to skip tests from being run in some contexts following the same pattern as `@requires extension <ext-name>`:

```
@requires runtime PHP
@requires runtime HHVM
@requires runtime Hippyvm
```

**Comment by keradus** [comment]
Possibility to define which tests should run only on PHP or only on HHVM would be really great!

`@skip` also would be nice!

Any news on any of that features?

**Comment by GrahamCampbell** [comment]
:+1: @keradus

**Comment by SoboLAN** [comment]
Any progress on this ? :)

**Comment by marcioAlmada** [comment]
wow, I completely forgot this thread :) I'm gonna start working on this ASAP

**Comment by keradus** [comment]
HHVM also provides PHP version, which is supposed to be compatible with used HHVM version.

It would be great to allow test run under:
* PHP compiler using at least given version, but not HHVM compiler
* HHVM compiler using at least given version, but not native PHP compiler
* PHP language using at least given version, under any compiler

**Comment by sebastianbergmann** [comment]
PHPUnit is only supported on PHP. Therefore I see no point in implementing this.
