### ISSUE TITLE
`backupStaticAttributes` doesn't work properly when class autoloaders are in use (was #1)

### ISSUE THREAD

**Issue by RichardBradley** [sebastianbergmann/phpunit#1372]
(Moved from issue #1, due to that issue repeatedly being incorrectly auto-closed by GitHub.)

# Summary

 * PHPUnit has a feature "[backupStaticAttributes](http://phpunit.de/manual/4.1/en/appendixes.annotations.html#appendixes.annotations.backupStaticAttributes)" which is documented to "[run your tests in a way where changes to \[static\] variables do not affect other tests](http://phpunit.de/manual/3.7/en/fixtures.html#fixtures.global-state)"
 * The [implementation of this feature](https://github.com/sebastianbergmann/phpunit/blob/c2d153e70aa85b51fbc77cd0404ffca180f341f2/src/Util/GlobalState.php#L296) works by enumerating all loaded classes and copying the "before" values of their static fields into an array, then restoring those values after each test has run
 * However, this doesn't work when class autoloaders are in use, because "get_declared_classes()" is called by the "backupStaticAttributes" feature before the test is run. If the test causes a new class to be auto-loaded during the test run, then its static fields will not be included in the "before" values, and any value which is added to a static field by that test will leak into all other tests for the rest of the suite run.

# Example use case

You may dismiss this by saying that the static field didn't exist before the test was run, so "backupStaticAttributes" couldn't catch it, but that does not account for how this feature appears to be intended to operate from the point of view of a PHPUnit user.

If I have a static class which looks like, for example:
```
  class MyGlobalStateHolder {
    static $scriptStartTime = time()
  }
```
... and if I want to modify this static field for the duration of a single test:
```
  class MyTimeDependentTest {
    protected function setUp() {
      // for the duration of this test only, pretend that it is 1984
      MyGlobalStateHolder::$scriptStartTime = 441763200;
    }
  }
```

Then, as things are documented I should expect the "backupStaticAttributes" feature to cause this field change to be isolated to this single test. This bug means that whichever test first loads the class in question will "win" and its static changes will leak to all other tests in the same run.

# Possible fixes and workarounds

It is not clear to me that this is easily fixable, but it is a real bug. 

I can't see a "class loaded" event to which PHPUnit could subscribe. Perhaps [@eriksencosta 's suggestion](https://github.com/sebastianbergmann/phpunit/issues/1#issue-265157) of wrapping the autoloader would work. However, any autoloaders added after the wrapping occurred would be missed, which seems quite likely to happen (e.g. Zend controller tests bootstrap Zend in the test "setup" method, at which point a lot of autoloaders are added).

Perhaps the fix should be documentation of the limitations of the "backupStaticAttributes" feature. or perhaps the "backupStaticAttributes" feature needs to be removed as not workable.

Perhaps the `restoreStaticAttributes()` method could check whether any new classes have been autoloaded in the course of the test and, if so, issue a warning that "`backupStaticAttributes`" doesn't work in the presence of autoloaders?

That wouldn't fix the issue, but at least it would give a warning when it occurred, which might save people lots of time tracking down mysterious bugs that depend on the order in which tests are run.

# Isolated test case 

See https://github.com/thehereward/phpunit-backup-static-attributes-bug

**Comment by sebastianbergmann** [comment]
Moved to https://github.com/sebastianbergmann/global-state/issues/4.
