### ISSUE TITLE
Bootstrap and dataProvider loading order

### ISSUE THREAD

**Issue by levacic** [sebastianbergmann/phpunit#1376]
I've spent a bunch of time searching for some answers to this, but couldn't find _anything_ that explains the problem. Not sure if this is the right place to ask either, but I'll give it a shot anyway.

So, unless something's wrong on my local install (v4.1.4), it seems that data providers are loaded before the bootstrap file is executed.

This caused a problem for me when PHP's default timezone (configured in the .ini file) was set to `Europe/Belgrade`, while my bootstrap script set the timezone to `UTC` (I'm using Laravel 4 if it matters).

Basically, the problem is that `DateTime` objects created in the data providers (well, actually it was `Carbon` objects, but that's just a custom extension to native `DateTime` classes) were being created with the `Europe/Belgrade` timezone, while the ones within the test methods with the `UTC` timezone.

I've "hot-fixed" the issue for me by just having date/time strings in the data provider methods, and instantiating `DateTime` objects within the tests themselves, but this seems like a quirky hack and not intended behavior.

Is this some problem specific to me, or is it expected behavior for data providers to be loaded before the bootstrap file is required?

Thanks in advance for answers!

**Comment by georgms** [comment]
@levacic Just stumbled on this issue as well. It seems to be mostly fixed but hit me when [running Laravel PHPUnit tests in parallel](https://laravel.com/docs/8.x/testing#running-tests-in-parallel) using [paratest](https://packagist.org/packages/brianium/paratest).

I fixed this by setting the default timezone in `phpunit.xml` to UTC:

```xml
<phpunit>
  <php>
    <ini name="date.timezone" value="UTC"/>
  </php>
</phpunit>
```

**Comment by levacic** [comment]
@georgms Since the time I had this problem, I've learned to just-use-UTC-everywhere™ (which includes stuff in the database, all servers, PHP and other apps, as well as third-party systems, e.g. monitoring/analytics etc.), and do timezone conversion only as needed as more of a "parsing and formatting" app layer (this doesn't imply you'll _never_ have to deal with timezones, but at least in the context of stuff I'm working on, that's become very rare for me, and I feel fortunate about that).

So while the answer to my initial problem was "use the same timezone in PHP in all environments, including when running tests" (my PHP was configured to `UTC` by default whereas my app was using `Europe/Belgrade`), today my answer would be "use UTC in PHP in all environments, including when running tests".

Your problem seems to be the other way around where your PHP process running tests was using something other than UTC so you needed to explicitly configure UTC in PHPUnit to fix the issue - but if possible, I'd recommend configuring PHP itself to use UTC (and then you can avoid the custom configuration in `phpunit.xml`).

**Comment by ettdro** [comment]
> @levacic Just stumbled on this issue as well. It seems to be mostly fixed but hit me when [running Laravel PHPUnit tests in parallel](https://laravel.com/docs/8.x/testing#running-tests-in-parallel) using [paratest](https://packagist.org/packages/brianium/paratest).
> 
> I fixed this by setting the default timezone in `phpunit.xml` to UTC:
> 
> ```
> <phpunit>
>   <php>
>     <ini name="date.timezone" value="UTC"/>
>   </php>
> </phpunit>
> ```

This was the answer for me, I was using Carbon dates in data providers in my tests, and looks like the `date_default_timezone_set` even though it was in the setUp function of TestCase, was initialized after, causing all the dates in my data providers to be set to another timezone and the dates inside my test setted to UTC causing inequality with the `equalTo` function of Carbon.

Thanks alot :)
