### ISSUE TITLE
Test run stops unexpectedly without any message or error

### ISSUE THREAD

**Issue by jrfnl** [sebastianbergmann/phpunit#1385]
I'm running a group of tests and all is fine until I add the last test file (out of 30), then suddenly things break.

**Symptoms:**
- Test run doesn't finish, doesn't give result feedback and the dots on the screen seem to not even reach the point of the earlier run without the last file (see screenshot)
- Junit and other logfiles do get written to disk and include the last tests, however this does not apply to the xml logfile which is a completely empty file.
- Even with PHP error reporting on -1, no errors are reported on screen nor in the logfile.
- Running the last file individually gives no problems at all, test run finishes without errors, failures and with results showing on screen and in the logfiles. (last bit of the screenshot)
- Running PHPUnit in `--debug` mode, makes no difference, I can see it reach the last file and things break all the same without any extra information.
- The scripts which I'm testing in the last file don't contain any strange things AFAICS, basic stuff really.
- Whether I run it in a limited group (the 30) or as part of the complete test suite, same thing happens.

**Environment:**
PHP 5.4.20, memory limit 128M
PHPUnit via Pear v4.0.17
For what it's worth: the test suite I'm running is build upon the WP Unit test framework (which extends PHPUnit).

Anyone any ideas of how to debug this further ? Or what could be going on ? Any particular code constructs I should search for in the code being tested which could be causing this ?

![screenshot](http://snag.gy/0w8UT.jpg)

**Comment by oligriffiths** [comment]
I have exactly the same issue, the tests just stop if running the full suite, but if running the specific test that it stops at, the tests complete.

The part that it is failing on is when calling a method with a typehint on an array, and not passing an argument, eg:

````php
function test_function(array $array){}
// Then in the test
test_function();
```

Nothing shows up in logs about the error, but if I pass an empty array to the function, the test suite continues on correctly...

**Comment by jrfnl** [comment]
@oligriffiths Same symptoms, not the same issue. The code I use does not use typehinting at all as it still has to be compliant with PHP5.2.

**Comment by oligriffiths** [comment]
@jrfnl Ah, right good point. Still curious as to why it just randomly stops.

**Comment by jrfnl** [comment]
@oligriffiths You and me both ;-)

**Comment by tomazahlin** [comment]
That makes three of us :-)

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
