### ISSUE TITLE
New @expectedExceptionMessageFormat

### ISSUE THREAD

**Issue by sun** [sebastianbergmann/phpunit#1415]
#### Background
1. `@expectedExceptionMessage` performs a partial string match (`strpos()`), whereas…
  * the partial match is unexpected (cf. #1414) and may even lead to false-positive passes
  * the literal string matching commonly causes assertions to fail on Windows (different `DIRECTORY_SEPARATOR`).

1. The recently added `@expectedExceptionMessageRegExp` (cf. #1328) tries to address some of the problems, but authoring a correctly `preg_quote()`'d regular expression in a docblock annotation is awkward/cumbersome.
  * Requires to use complex expressions to account for e.g. Windows filesystem differences; e.g.,

    ```
@expectedExceptionMessageRegExp /File not found: .+[\\\\/]fixtures[\\\\/]does_not_exist.txt in .+ on \d+`)/
    ```

#### Proposal
1. Add a new `@expectedExceptionMessageFormat` annotation.

  * Asserts the exception message string with [`assertStringMatchesFormat()`](http://phpunit.de/manual/current/en/appendixes.assertions.html#appendixes.assertions.assertStringMatchesFormat).

  * Asserts the full message string from start to end.  The specified format MUST match the complete message.

  * PHPT tests are using this method in `--EXPECTF--` with great success already.

#### Example
```php
/**
 * @expectedException \RuntimeException
 * @expectedExceptionMessageFormat File not found: %s%efixtures%edoes_not_exist.txt in %s on line %d
 */
public function testMissingFileList() {
  new MyDiscovery(__DIR__ . DIRECTORY_SEPARATOR . 'fixtures' . DIRECTORY_SEPARATOR . 'does_not_exist.txt');
}
```

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
