### ISSUE TITLE
Output in Util/Printer.php interrupt test with session and cookie

### ISSUE THREAD

**Issue by fwolf** [sebastianbergmann/phpunit#1416]
I have a testcase use session and cookie, the file to test includes session_start() and setcookie().

In computer A (Ubuntu 12.04.5, PHP 5.3.10), the test runs ok without any problem.

In another compute B(Debian 7 wheezy, PHP 5.4.4), the test fail with message like:

```
1) Cbtms\Auth\Test\UserSessionTest::testCommon
session_start(): Cannot send session cookie - headers already sent by (output started at phar:///usr/local/bin/phpunit/phpunit/Util/Printer.php:172)

2) Cbtms\Auth\Test\UserSessionTest::testLogout
Cannot modify header information - headers already sent by (output started at phar:///usr/local/bin/phpunit/phpunit/Util/Printer.php:172)
```

In both compute uses PHPUnit 4.2.3.

For the 1) error, I can do session_start() in bootstrap and skip test of automatic start of session. But stuck at the 2) error.

The problem is, Util/Printer.php will print something(empty string?) and open output buffer, and cause modify of html header error. If do ob_end_clean() in test method of setUp() or setUpBeforeClass(), PHPUnit will still report error:

```
1) Cbtms\Auth\Test\UserSessionTest::testLogout
Test code or tested code did not (only) close its own output buffers
```

Do ob_end_clean() at end of test method or tearDown() or tearDownAfterClass() didn't help.

So at the end, why this error shows only in my computer B? How to test session and cookie without encapsule their operation in Session/Cookie class ?

**Comment by laoneo** [comment]
Did you ever figure out why this error happens on PHP versions bigger than 5.3?

**Comment by fwolf** [comment]
@laoneo Don't know, I end with mock session manage class.
