### ISSUE TITLE
Call to undefined method.

### ISSUE THREAD

**Issue by jakon89** [sebastianbergmann/phpunit#1430]
Hi, I'm starting with phpunit so please forgive me if it's stupid question.
I have following test code (tested class included): 
https://gist.github.com/jakon89/f523da2c5d258ca0c136
It's very simple test code, I have tried with getMockBuilder() but I was getting the same error.
I use phpunit 3.7
I'm still getting:

Fatal error: Call to undefined method SomeTest::generate() in C:\Users\user\Desktop\project\vendor\phpunit\phpunit-mock-objects\src\Framework\MockObject\Generator.php on line 247

Line from 247:
        $mock = $this->generate(
          $type,
          $methods,
          $mockClassName,
          $callOriginalClone,
          $callAutoload,
          $cloneArguments,
          $callOriginalMethods
        );
I did some research in google but I didn't find anything interesting.

Could anyone help me?

**Comment by afelle1** [comment]
Those this is closed I think I might know what was going on.  I originally had phpunit 3.7.9 declared when this issue arose and changed this to 3.7.* and noticed a number of weird dependency changes:

> andrew@feller app ((no branch))$ composer show -i
> doctrine/instantiator        1.0.4  A small, lightweight utility to instantiate objects in PHP without invoking their constructors
> fzaninotto/faker             v1.4.0 Faker is a PHP library that generates fake data for you.
> phpunit/php-code-coverage    2.0.14 Library that provides collection, processing, and rendering functionality for PHP code coverage information.
> phpunit/php-file-iterator    1.3.4  FilterIterator implementation that filters files based on a list of suffixes.
> phpunit/php-text-template    1.2.0  Simple template engine.
> phpunit/php-timer            1.0.5  Utility class for timing
> phpunit/php-token-stream     1.3.0  Wrapper around PHP's tokenizer extension.
> phpunit/phpunit              3.7.9  The PHP Unit Testing framework.
> phpunit/phpunit-mock-objects 2.3.0  Mock Object library for PHPUnit
> sebastian/environment        1.2.1  Provides functionality to handle HHVM/PHP environments
> sebastian/version            1.0.4  Library that helps with managing the version number of Git-hosted PHP projects
> symfony/yaml                 v2.6.1 Symfony Yaml Component
> zendframework/zendframework1 1.12.9 Zend Framework 1
> andrew@feller app ((no branch))$ vim composer.json 
> andrew@feller app ((no branch))$ composer update --dev
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
>   - Removing phpunit/phpunit-mock-objects (2.3.0)
>   - Installing phpunit/phpunit-mock-objects (1.2.3)
>     Downloading: 100%         
> 
>   - Removing phpunit/php-token-stream (1.3.0)
>   - Installing phpunit/php-token-stream (1.2.2)
>     Loading from cache
> 
>   - Removing phpunit/php-code-coverage (2.0.14)
>   - Installing phpunit/php-code-coverage (1.2.18)
>     Downloading: 100%         
> 
>   - Removing phpunit/phpunit (3.7.9)
>   - Installing phpunit/phpunit (3.7.38)
>     Downloading: 100%         
> 
>   - Removing sebastian/environment (1.2.1)
>   - Removing sebastian/version (1.0.4)
>   - Removing doctrine/instantiator (1.0.4)
> Writing lock file
> Generating autoload files
