### ISSUE TITLE
@requires extension not applied to dataProviders

### ISSUE THREAD

**Issue by chippyash** [sebastianbergmann/phpunit#1445]
phpunit 4.2.6

I have the following code (snippet).
<pre>
/**
 * @requires extension gmp
 * @runTestsInSeparateProcesses
 */
class GMPComplexTypeFactoryTest extends \PHPUnit_Framework_TestCase
{
    public function setUp() {
        TypeFactory::setNumberType(TypeFactory::TYPE_GMP);
    }

    /**
     * @dataProvider correctParamCombinations
     * 
     */
    public function testCreateWithCorrectParamTypesReturnsComplexType($r, $i)
    {
        $c = ComplexTypeFactory::create($r, $i);
        $this->assertInstanceOf(self::CTYPE_NAME, $c);

    }

    /**
     * For some reason phpunit ignores the requires annotation at the class level
     * - it seems to process data providers first
     */
    public function correctParamCombinations()
    {
        if (!extension_loaded('gmp')) {
            return [[2,2]];
        }
        return [
            //numeric int
            [2,2],
            [2,2.3],
            [2,new GMPIntType(2)],
        ];
    }
}
</pre>
If I don't put the cut-out in the data provider, test will try to instantiate a new GMPIntType (which will bork 'cus gmp isn't installed,) even though I've set the @requires extension gmp at the class level, expecting nothing to be run if gmp is not installed.

Other tests not using data providers appear to be skipped as expected if gmp is not installed.  The observed behaviour suggests that data providers are processed before the @requires flag is obeyed. Is there any truth in that?

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
