### ISSUE TITLE
Tests run in process isolation send output to stdout

### ISSUE THREAD

**Issue by johnpbloch** [sebastianbergmann/phpunit#1452]
This is related to #1149

Code to reproduce issue here: https://gist.github.com/johnpbloch/312557aa437dc5d3d58e

When explicitly testing for the output generated for a test, I expect that PHPUnit will suppress that output, whether in process isolation or not.

Expected output from the test linked above:

```
PHPUnit 4.2.6 by Sebastian Bergmann.

Configuration read from C:\Users\John\Projects\phpunittest\phpunit.xml

..

Time: 150 ms, Memory: 3.25Mb

OK (2 tests, 2 assertions)
```

Actual output:

```
PHPUnit 4.2.6 by Sebastian Bergmann.

Configuration read from C:\Users\John\Projects\phpunittest\phpunit.xml

..Output

Time: 150 ms, Memory: 3.25Mb

OK (2 tests, 2 assertions)
```

Thanks for your time!

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
