### ISSUE TITLE
Performance regression with process isolation and code coverage in 4.2.6

### ISSUE THREAD

**Issue by jaydiablo** [sebastianbergmann/phpunit#1456]
We recently tried upgrading phpunit on a testsuite of ours that uses some process isolation, and noticed that the time to run the tests (with coverage) increased dramatically.  This seems similar to what is described in #1187, but the patch there doesn't help.

The particular suite we ran against made use of both Mockery and PHPUnit's mock objects (using latest version of mock objects, with the patch from #1187 included).  To test, I tried removing all of phpunit's Mock objects and use just Mockery, but that didn't help.  As a test, I wanted to see if Mockery was to blame at all, so I experimented with adding the `@runTestsInSeparateProcesses` annotation to the top of a suite that doesn't use any mock objects. The same performance issues were there, but only when code coverage was enabled.

Unforunately, the suites I'm running against are private projects, so I can't provide them as examples, but I do have the output of several runs, under different conditions to provide as an example of the performance issue.  I'd like to try adding that annotation to any public php test suite to see if the issue is there.  I'll follow up with the results of that.  The suite we are running does some DB testing with some large php libraries, so quite a few files are covered in each test run, which may have some bearing on this.

### No Process Isolation, No Coverage
Time: 3.36 seconds, Memory: 21.00Mb
### Just Coverage
Time: 14.21 seconds, Memory: 23.50Mb
### Just Process Isolation
Time: 9.41 seconds, Memory: 8.75Mb
### Process Isolation and Coverage
Time: 26.07 seconds, Memory: 18.00Mb

### No Process Isolation, No Coverage
Time: 3.74 seconds, Memory: 22.00Mb
### Just Coverage
Time: 15.89 seconds, Memory: 32.00Mb
### Just Process Isolation
Time: 8.36 seconds, Memory: 9.75Mb
### Process Isolation and Coverage
Time: 7.71 **minutes**, Memory: 20.25Mb

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
