### ISSUE TITLE
Coverage of phpunit.xml bootstrap file not recorded

### ISSUE THREAD

**Issue by jdufresne** [sebastianbergmann/phpunit#1463]
My `phpunit.xml` contains a `boostrap` attribute. I've configured coverage with `processUncoveredFilesFromWhitelist="true"`. When I view the HTML output from the coverage analysis, the coverage of the boostrap file is listed as 0%, no statements covered. But this file has been executed to some extent when phpunit was started.

I've resorted to excluding my bootstrap file from coverage analysis. But it would be nice if I could analyze my testing code using coverage to know what code is dead and could potentially be removed.

Thanks.

**Comment by sebastianbergmann** [comment]
This is expected behavior.
