### ISSUE TITLE
PHP Codecoverage incorrect if html coverage is not done too

### ISSUE THREAD

**Issue by dstockto** [sebastianbergmann/phpunit#1469]
I've run into an issue where I want to generate PHP coverage for multiple phpunit runs and then later merge them back into the various reports with phpcov. I've found that the file generated changes based on whether or not I'm running an HTML coverage report from phpunit at the same time.

e.g.

> phpunit --coverage-php=/path/to/my.cov

vs

> phpunit --coverage-php=/path/to/my.cov --coverage-html=/path/to/html

In my phpunit.xml I've set up filter with <whitelist processUncoveredFilesFromWhiteList="true">. In the first example without html, I get my.cov created with only the files that were directly touched by the unit tests. For the second, I get those but I also get all the other files covered by my whitelist. 

In the first example, the phpcov output for the hmtl report will not show any of the uncovered files (how could it?) and in the second it will. However I don't need or care for the individual tests' html outputs, I only care for the combined phpcov html coverage output. This means it's doing a lot more work (or at least it seems to be as the time to generate goes from ~100ms for no coverage to ~3 seconds with only php coverage to ~15 seconds with html and php coverage) which I am just discarding anyway. It would be nice to have the php coverage report be consistent and respect the whitelist and blacklist settings even if phpunit will not be generating the final reports/output.

This is with phpunit 4.3.1.

**Comment by sebastianbergmann** [comment]
Does this problem still exist with PHPUnit 4.7?

**Comment by dstockto** [comment]
There is definitely a difference still. 

PHPUnit 4.6.10
Coverage File size
292323 bytes with just --coverage-php
330204 bytes with --coverage-php and --coverage-html

PHPUnit 4.7.3
293713 bytes just --coverage-php
330594 bytes with php and html coverage

The difference in size between 4.6 and 4.7 appears to be the reported size changing from small to unknown on the tests

The difference between the coverage on its own and coverage that's generated with the html report is a number of lines that appear to not be covered:

```
>     57 =>
>     array (
>     ),
>     59 =>
>     array (
>     ),
>     60 =>
>     array (
>     ),
```

 as well as this chunk:

```
>   'UNCOVERED_FILES_FROM_WHITELIST' =>
>   array (
>     'size' => 'unknown',
>     'status' => NULL,
>   ),
```

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
