### ISSUE TITLE
PHPUnit_Util_Log_JSON listener mis-behaves with nested test suites (e.g. @dataProviders)

### ISSUE THREAD

**Issue by chimericdream** [sebastianbergmann/phpunit#1488]
If a test suite includes a test with a `@dataProvider`, any subsequent tests will have blank values for their suite name. The other loggers track the depth of the nested suites, but the JSON one simply blanks out the suite name.

I have tested a working fix for this, but I am not certain whether this covers all the edge cases.

https://gist.github.com/chimericdream/74c8e0edd9d0b32fdd39

The relevant sections are from lines 185-230. I added a pair of helper methods that check and set a new `parentTestSuiteName` variable as appropriate.

I can submit a formal pull request if you think this fix is sufficient.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
