### ISSUE TITLE
--repeat and --filter parameters doesn't work together

### ISSUE THREAD

**Issue by feridmovsumov** [sebastianbergmann/phpunit#1493]
## OK! When use only --repeat

phpunit --repeat 10  BrandTest.php 
PHPUnit 3.7.28 by Sebastian Bergmann.

...............................................................  63 / 170 ( 37%)
............................................................... 126 / 170 ( 74%)
............................................

Time: 1.88 seconds, Memory: 10.75Mb

OK (170 tests, 3640 assertions)

## OK! when use only --filter

phpunit --filter testSetAndGetTitle  BrandTest.php 
PHPUnit 3.7.28 by Sebastian Bergmann.
.
Time: 842 ms, Memory: 10.75Mb

OK (1 test, 40 assertions)

## NOT OK! When use --filter with --repeat 
```json
phpunit --filter testSetAndGetTitle --repeat 100   BrandTest.php 
PHPUnit 3.7.28 by Sebastian Bergmann.

Time: 24 ms, Memory: 3.00Mb
No tests executed!
```

## Workbech 
```
Phpunit version: 3.7.28

Os: Ubuntu 14.04

Php version: 5.5.9
```

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
