### ISSUE TITLE
Add assertBetween()

### ISSUE THREAD

**Issue by ameenross** [sebastianbergmann/phpunit#1494]
Adding this feature would allow to simplify the following:

``` php
$testFloat = 1.654845641;
$this->assertGreaterThan(1.65, $testFloat);
$this->assertSmallerThan(1.66, $testFloat);
```

to something like this:

``` php
$testFloat = 1.654845641;
$this->assertBetween(array(1.65, 1.66), $testFloat);
```

I'm not very familiar with PHPUnit, so please forgive me if I'm asking for an atrocity.

**Comment by ratatatKE** [comment]
Am not sure a direct assertBetween() would be better @sebastianbergmann ?

**Comment by someniatko** [comment]
@sebastianbergmann well, `assertTrue($testee)` is also possible using `assertSame(true, $testee)`;

**Comment by joelmellon** [comment]
This is an old, closed thread obviously, but I just wanted to point out that a `between` assertion is probably a bad idea. What does _between_ mean in this context, or more importantly, _your_ context?

Recommended reading: [What do BETWEEN and the devil have in common?](https://sqlblog.org/2011/10/19/what-do-between-and-the-devil-have-in-common) ...applies to more than just SQL.

_I came here looking for a way to create a "custom" assertion method. Yes, I can make a protected method to abstract my own logic, but the stack trace doesn't point to the line where **my** assertion actually took place. If anyone reads this, any amount of time into the future, please feel free to enlighten me. Thanks in advance._

**Comment by ameenross** [comment]
@joelmellon It's 10 years ago and my request was denied. Now I'm reading a rant of a person who doesn't understand what granularity means. I could have done without that... I agree SQL between is evil but only because it uses `[x, y]` intervals instead of the standard `[x, y)` intervals.
