### ISSUE TITLE
PHP Warning:  strpos(): Empty needle in ...phpunit/src/Util/Blacklist.php on line 114

### ISSUE THREAD

**Issue by fezfez** [sebastianbergmann/phpunit#1497]
Hi,

I have this warning when i test my application. Apparently it's only when the test fail.

	PHP Warning:  strpos(): Empty needle in /var/www/default/php/php-to-zephir/vendor/phpunit/phpunit/src/Util/Blacklist.php on line 114
	PHP Stack trace:
	PHP   1. {main}() /var/www/default/php/php-to-zephir/vendor/phpunit/phpunit/phpunit:0
	PHP   2. PHPUnit_TextUI_Command::main() /var/www/default/php/php-to-zephir/vendor/phpunit/phpunit/phpunit:56
	PHP   3. PHPUnit_TextUI_Command->run() /var/www/default/php/php-to-zephir/vendor/phpunit/phpunit/src/TextUI/Command.php:138
	PHP   4. PHPUnit_TextUI_TestRunner->doRun() /var/www/default/php/php-to-zephir/vendor/phpunit/phpunit/src/TextUI/Command.php:186
	PHP   5. PHPUnit_TextUI_ResultPrinter->printResult() /var/www/default/php/php-to-zephir/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:429
	PHP   6. PHPUnit_TextUI_ResultPrinter->printFailures() /var/www/default/php/php-to-zephir/vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php:177
	PHP   7. PHPUnit_TextUI_ResultPrinter->printDefects() /var/www/default/php/php-to-zephir/vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php:288
	PHP   8. PHPUnit_TextUI_ResultPrinter->printDefect() /var/www/default/php/php-to-zephir/vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php:233
	PHP   9. PHPUnit_TextUI_ResultPrinter->printDefectTrace() /var/www/default/php/php-to-zephir/vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php:244
	PHP  10. PHPUnit_Framework_Exception->__toString() /var/www/default/php/php-to-zephir/vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php:268
	PHP  11. PHPUnit_Util_Filter::getFilteredStacktrace() /var/www/default/php/php-to-zephir/vendor/phpunit/phpunit/src/Framework/Exception.php:108
	PHP  12. PHPUnit_Util_Blacklist->isBlacklisted() /var/www/default/php/php-to-zephir/vendor/phpunit/phpunit/src/Util/Filter.php:108
	PHP  13. strpos() /var/www/default/php/php-to-zephir/vendor/phpunit/phpunit/src/Util/Blacklist.php:114

I have only one test case.

```php
class ConvertTest extends \PHPUnit_Framework_TestCase
{
	public function testConvertCode()
	{
		$this->convert(__DIR__ . '/code/');
	}

	private function convert($dir)
	{
		$engine = EngineFactory::getInstance();

		foreach (glob($dir . '*.php') as $file) {
			$converted = $engine->convert(file_get_contents($file));

			file_put_contents(
				$dir . basename($file, '.php') . '.zep.log',
				$converted['code']
			);

			$this->assertStringEqualsFile(
				$dir . basename($file, '.php') . '.zep',
				$converted['code'],
				'test faile on file ' . $file
			);
		}

		$paths = glob($dir. '*', GLOB_MARK|GLOB_ONLYDIR|GLOB_NOSORT);
		foreach ($paths as $recursiveDir) {
			$this->convert($recursiveDir);
		}
	}
}

```

And my phpunit.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>

<phpunit backupGlobals="false"
         backupStaticAttributes="false"
         colors="true"
         convertErrorsToExceptions="true"
         convertNoticesToExceptions="true"
         convertWarningsToExceptions="true"
         processIsolation="false"
         stopOnFailure="false"
         syntaxCheck="false"
         bootstrap="vendor/autoload.php"
>
    <filter>
        <whitelist addUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">./src/</directory>
        </whitelist>
    </filter>
    <testsuites>
        <testsuite name="General">
            <directory>./tests/</directory>
        </testsuite>
    </testsuites>
</phpunit>
```

PHPUnit 4.3.4 

Thanks for your awesome work !

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
