### ISSUE TITLE
Composer install doesn't work

### ISSUE THREAD

**Issue by ghost** [sebastianbergmann/phpunit#1503]
Installing by adding phpunit to the require-dev section of composer.json does not seem to work.

```
"require-dev": {
    "phpunit/phpunit": "4.3.*"
}
```

This currently attempts to pull in phpunit 4.3.5. The composer.json file specifies that there is a binary for phpunit in the bin-dir (bin/phpunit), but the code for phpunit in GitHub does not contain such a directory, much less a phpunit file in that directory. Thus, when it attempts to symlink it into bin/phpunit on the project level, it fails since there is no file to symlink in the first place.

This is on an Ubuntu Linux system, using the latest composer PHAR, as the ErrorException thrown is on line 246 of src/Composer/Installer/LibraryInstaller.php, and the error message is "file_put_contents(/xxxxxx/bin/phpunit): failed to open stream: No such file or directory" (the project directory path is not xxxxxx, it has been redacted).

Thanks.

**Comment by helhum** [comment]
Thank you very much for the bug report though, as I ran into the exact same issue today and was able to resolve it by removing the bin dir…
