### ISSUE TITLE
Feature Suggestion: Mock more than one interface at once

### ISSUE THREAD

**Issue by fabiocarneiro** [sebastianbergmann/phpunit#1504]
```php
$this->getMock(array());
```
Sometimes there are methods in many interfaces and you must use them together to proper test something.

Nowadays we must create a test asset of an interface that extends the required interfaces and use this asset in the mock.

Alternative:
```php
$this->getExtensionMock(array());
```

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md) have been reported on the [phpunit-mock-objects](https://github.com/sebastianbergmann/phpunit-mock-objects) project instead.
