### ISSUE TITLE
Custom error messages while checking method invocation

### ISSUE THREAD

**Issue by tampe125** [sebastianbergmann/phpunit#1509]
In PhpUnit we are able to create a custom message when a test fails:

``` php
$this->assertEquals($check, $result, 
             'Class::method returned the wrong result with argument XXX');
```

However, it seems that we can't set a custom error message while testing for method invocation:

``` php
$mock->expects($this->any())->method('foobar')->with($this->equals('dummy'));
```

When the above assertion is not true, I get the standard message.
Is it possible to add custom error message for invocations, too?

**Comment by zombiesplat** [comment]
@DragonBe , I just ran across this in my testing today (2 years later) and I wasn't needing it to validate my tests ran correctly, but rather that I had several objects being mocked with the method name of "create" and It was mildly frustrating hunting down which object was actually failing.

Perhaps in this case, the error message could include a classname as well?

**Comment by DragonBe** [comment]
@zombiesplat, Yes it's a common problem if you have multiple object stubs where you mocked out the same method. It's easy to say add the ClassName::method() to your comment, but if you already have a legacy application, it can be troublesome.

A good rule-of-thumbs is to have your test focus on a single responsibility. I rather write 5 individual tests to test similar logic over 5 different classes as to write it all in a single test. I can then use the test method name to indicate which functionality I'm testing from which class. Yes, a little bit more work upfront but a lot easier to track later on.

**Comment by zombiesplat** [comment]
@DragonBe, For me, this was not about testing the functionality, but rather debugging my test that was broken. It didn't give me a line number of the failed expectation just that 'the method named create was never called' it was a mild inconvenience that took me 2 minutes to track down. But could it be simplified, it may have helped.

**Comment by rulatir** [comment]
I have a single test function that uses a data provider with two dozen entries. One of those fails in that a method that I expect to get called does not get called. The test method itself is lean and mean and already in gazillionth normal form with respect to unit testing best practices; it tests **only** for that one thing, whether the method in question gets called or not. Without the ability to set a custom message for ->expects(), I am unable to quickly determine **which** of the two dozen test cases from the data provider fails.

Please reopen.

**Comment by rawaludin** [comment]
Any news?
