### ISSUE TITLE
Set phpunit options via env variables

### ISSUE THREAD

**Issue by hashar** [sebastianbergmann/phpunit#1513]
I could use the ability to tweak phpunit options using environment variables. A use case would be in Jenkins to invoke 'composer test' (which invokes `phpunit`) and make sure that phpunit is being passed `--log-junit=build/junit.xml`

The developer composer.json would be:
```js
{
    "scripts": {
        "test": "phpunit"
    }
}
```

And Jenkins would invoke it with:

    PHPUNIT_LOG_JUNIT="build/junit.xml" composer test

Another use case would be to generate coverage:

    PHPUNIT_COVERAGE_XML=build/coverage.xml composer test

If we were to invoke `composer test -- --log=build/junit.xml` the extra arguments are passed to all the scripts defined in the 'test' section which is not going to play nice when other commands are defined such as PHP CodeSniffer.  We also need Jenkins to execute a single entry point (test), to avoid having to generate another job or update the job whenever the developer add a new test.

By tweaking options via env variables and using the 'test' entry point, we execute all the tests commands defined by the developer, but would easily tweak phpunit options.

Python `nosetests` as such behavior https://nose.readthedocs.org/en/latest/usage.html#options . Setting --verbose is:  `NOSE_VERBOSE=2 nose`

Poke @krinkle

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
