### ISSUE TITLE
Netbeans GUI Incomplete and Skipped tests

### ISSUE THREAD

**Issue by sigee** [sebastianbergmann/phpunit#1533]
Hi,

I want to use PHPUnit inside NetBeans, but the GUI doesn't shows incomplete and skipped tests.
It is because --log-junit doesnt generate them into the xml that parsed by NetBeans.

Please FIX this.
https://netbeans.org/bugzilla/show_bug.cgi?id=176157

Thx. Sigee

**Comment by chbiel** [comment]
Zhis is not only an issue to eclipse.

We see the same problem with paratest because when --log-junit option is set, no skipped/incomplete tests are shown/logged

would be very nice if someone can fix this :)

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
