### ISSUE TITLE
Coverage does not include closing curly brackets

### ISSUE THREAD

**Issue by dereuromark** [sebastianbergmann/phpunit#1539]
![unbenannt](https://cloud.githubusercontent.com/assets/39854/5508552/a7aadec6-87ae-11e4-8e21-04f9825f3b20.png)

This closing bracket should count, though, as soon as it runs into the switch statement.
Or rather be excluded (gray), similar to the opening one.

**Comment by sebastienbarre** [comment]
@dereuromark it has been a while, but I'm also seeing that in our coverage, I was wondering if this ever got addressed or resolved somehow? Thx
