### ISSUE TITLE
Class-level @testdox annotations

### ISSUE THREAD

**Issue by borekb** [sebastianbergmann/phpunit#1543]
It would be useful for our project to have the `@testdox` annotation on the class level as well as the standard method-level.

**Comment by sebastianbergmann** [comment]
I don't understand how it would be useful for all test methods of a test class to yield the same `--testdox` output.

**Comment by borekb** [comment]
The class-level `@testdox` annotation would influence the output of the class as the "header" of the tests. For example,

```
OurProject\Tests\SomeTest
 [x] First method description
 [x] Second method description
 [x] Third method description
```

would become 

```
Custom text
 [x] First method description
 [x] Second method description
 [x] Third method description
```

**Comment by sebastianbergmann** [comment]
Ah, okay.
