### ISSUE TITLE
Tests That Fail to Close Their Output Buffers Have Any Output Swallowed

### ISSUE THREAD

**Issue by chrisguitarguy** [sebastianbergmann/phpunit#1553]
The test is marked as risky as expected, but no output is shown to the user. Seems like that's not intentional and is a bit misleading.

```php
<?php

class TestOB extends \PHPUnit_Framework_TestCase
{
    public function testTestsThatDoNotCloseTheirOutputBuffersHaveOutputSwallowed()
    {
        ob_start();
        echo 'here';
    }

    public function testTestsWithoutOutputBufferingDoNotHaveTheirOutputSwallowed()
    {
        echo 'there';
    }
}
```

Output:

```
shell> ./phpunit --no-configuration t.php 
PHPUnit 4.6-g762e997 by Sebastian Bergmann and contributors.

R.there

Time: 30 ms, Memory: 3.00Mb

OK, but incomplete, skipped, or risky tests!
Tests: 2, Assertions: 0, Risky: 1.
```

Probably expected:

```
shell> ./phpunit --no-configuration t.php 
PHPUnit 4.6-g762e997 by Sebastian Bergmann and contributors.

Rhere.there

Time: 30 ms, Memory: 3.00Mb

OK, but incomplete, skipped, or risky tests!
Tests: 2, Assertions: 0, Risky: 1.
```

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
