### ISSUE TITLE
Basic Install problem

### ISSUE THREAD

**Issue by archergod** [sebastianbergmann/phpunit#1562]
I think it is basic installation issue, but maybe something else. I am first timer for PHPUnit Test [or any unit testing at all]. Based on your "Getting start" tutorial, I install "phpunit.phar". then I create a one simple test using my project based class.

It give me error in some global variable, and force me to use $GLOBALS in all case instead of global keyword in functions. I can live with that. Now, I have 2 problems

1. I have my own spl_autoload, but it is generating error that PHPUnit_Extensions_Story_TestCase class is not found. In basic installation I didn't found how to install it? 
2. Since I am ignoring this I move on to write my first test which works just fine. But as soon as I create second test within my Test Class it starting giving error on call to database mysqli object in second function [I swap the order of function and second function always gives error, second in order of writing them in test file].

I am not able to move ahead with my PHPUnit test, can you guide me as I want to learn it. I am using ubuntu 14.04 in my local machine.

**Comment by archergod** [comment]
I put other phar files in my /usr/local/bin folder but nothing change. Sorry I never use phar or composer either. I need phpUnit for multiple project all stored in /opt/htdocs  folder.

**Comment by sebastianbergmann** [comment]
Your autoloader is probably too eager, ie. it's trying to load files it's not responsible for.

**Comment by archergod** [comment]
Thanks, but what about the second case? My it is closing/nullify my second db.
