### ISSUE TITLE
Reporting code as not @used or @covered when it shoudnt

### ISSUE THREAD

**Issue by unattended-user** [sebastianbergmann/phpunit#1563]
So in short i have following in xml config file:
```
<phpunit
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://schema.phpunit.de/4.4/phpunit.xsd"
    backupGlobals="false"
    backupStaticAttributes="false"
    bootstrap="PhpUnitBootstrap.php"
    cacheTokens="false"
    colors="true"
    convertErrorsToExceptions="true"
    convertNoticesToExceptions="true"
    convertWarningsToExceptions="true"
    forceCoversAnnotation="true"
    processIsolation="false"
    stopOnError="false"
    stopOnFailure="false"
    stopOnIncomplete="false"
    stopOnSkipped="false"
    strict="true"
    verbose="true"
>
```

Running my tests, one particular test fails with this configuration saying that one line was not covered (that line being first line of mult-line if statement, in case if is true). However if on that exact line I don't have any code (for example just create new empty line), or just have a comment, everything works normally. Also, setting option

```
    processIsolation="true"
```

fixes the problem, but slows down the whole testing process.

In my composer i have
```
        "phpunit/phpunit": "~4.4",
```

with minimum-stability set on "stable"

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
