### ISSUE TITLE
Undefined class constant 'COLOR_DEFAULT'

### ISSUE THREAD

**Issue by itonics-tbeauvais** [sebastianbergmann/phpunit#1569]
After updating I received this error when running in phpStorm.

PHP Fatal error:  Undefined class constant 'COLOR_DEFAULT' in /Users/tbeauvais/Code/lebowski/vendor/phpunit/phpunit/src/TextUI/TestRunner.php on line 873
Fatal error: Undefined class constant 'COLOR_DEFAULT' in /Users/tbeauvais/Code/lebowski/vendor/phpunit/phpunit/src/TextUI/TestRunner.php on line 873
PHP Stack trace:

PHP   1. {main}() /private/var/folders/27/c4b5x6s10d33q3k18fvkn9lw0000gn/T/ide-phpunit.php:0
Call Stack:
PHP   2. IDE_Base_PHPUnit_TextUI_Command::main() /private/var/folders/27/c4b5x6s10d33q3k18fvkn9lw0000gn/T/ide-phpunit.php:516
    0.0007     350176   1. {main}() /private/var/folders/27/c4b5x6s10d33q3k18fvkn9lw0000gn/T/ide-phpunit.php:0
PHP   3. PHPUnit_TextUI_Command->run() /private/var/folders/27/c4b5x6s10d33q3k18fvkn9lw0000gn/T/ide-phpunit.php:258
    0.0114    1116600   2. IDE_Base_PHPUnit_TextUI_Command::main() /private/var/folders/27/c4b5x6s10d33q3k18fvkn9lw0000gn/T/ide-phpunit.php:516
PHP   4. PHPUnit_TextUI_TestRunner->doRun() phar:///Users/tbeauvais/Applications/phpunit.phar/phpunit/TextUI/Command.php:186
    0.0114    1117224   3. PHPUnit_TextUI_Command->run() /private/var/folders/27/c4b5x6s10d33q3k18fvkn9lw0000gn/T/ide-phpunit.php:258
PHP   5. PHPUnit_TextUI_TestRunner->handleConfiguration() /Users/tbeauvais/Code/lebowski/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:153
    0.0280    4339368   4. PHPUnit_TextUI_TestRunner->doRun() phar:///Users/tbeauvais/Applications/phpunit.phar/phpunit/TextUI/Command.php:186
    0.0280    4340848   5. PHPUnit_TextUI_TestRunner->handleConfiguration() /Users/tbeauvais/Code/lebowski/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:153

**Comment by henriquemoody** [comment]
What version are you using?

This is what I have find in the current `master` branch:

```bash
$ grep -Rn 'COLOR_DEFAULT' --include=*.php .
./src/TextUI/ResultPrinter.php:34:    const COLOR_DEFAULT = self::COLOR_NEVER;
./src/TextUI/ResultPrinter.php:117:    public function __construct($out = null, $verbose = false, $colors = self::COLOR_DEFAULT, $debug = false, $numberOfColumns = 80)
./src/TextUI/TestRunner.php:873:        $arguments['colors']                             = isset($arguments['colors'])                             ? $arguments['colors']                             : PHPUnit_TextUI_ResultPrinter::COLOR_DEFAULT;
```

Seems everything it fine to me, can you check if running this command (`grep -Rn 'COLOR_DEFAULT' --include=*.php .`) do you have a different result?

**Comment by itonics-tbeauvais** [comment]
vagrant@lebowski:~/lebowski/vendor/phpunit$ grep -Rn 'COLOR_DEFAULT' --include=*.php .
./phpunit/src/TextUI/ResultPrinter.php:34:    const COLOR_DEFAULT = self::COLOR_NEVER;
./phpunit/src/TextUI/ResultPrinter.php:117:    public function __construct($out = null, $verbose = false, $colors = self::COLOR_DEFAULT, $debug = false, $numberOfColumns = 80)
./phpunit/src/TextUI/TestRunner.php:873:        $arguments['colors']                             = isset($arguments['colors'])                             ? $arguments['colors']                             : PHPUnit_TextUI_ResultPrinter::COLOR_DEFAULT;

**Comment by whatthejeff** [comment]
@itonics-tbeauvais if you look at the paths in your stack trace, you'll see that your system seems to be mixing multiple different copies of PHPUnit.
