### ISSUE TITLE
Test that prints output is marked as failure and not as risky when --disallow-test-output is used

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#1570]
```php
<?php
class Test extends PHPUnit_Framework_TestCase
{
    public function testOne()
    {
        print "*";
    }
}
```

    $ phpunit --disallow-test-output Test
    PHPUnit 4.4.1-9-g4a1c9c8 by Sebastian Bergmann.

    F*

    Time: 21 ms, Memory: 3.00Mb

    There was 1 failure:

    1) Test::testOne
    This test printed output: *

    FAILURES!
    Tests: 1, Assertions: 0, Failures: 1.

**Comment by sebastianbergmann** [comment]
Thanks!

**Comment by whatthejeff** [comment]
No problem :)
