### ISSUE TITLE
Incomplete XSD File

### ISSUE THREAD

**Issue by pauloelr** [sebastianbergmann/phpunit#1573]
The xsd schema seen a little bit different from the docs

1. It's allowing only one `<testsuite>` inside `<testsuites>`
  - Docs say that you can inlcude as many as you like
  - Implementation points to the same direction as docs
2. the `<log>` attributes `highlight` and `charset` are also missing on xsd

**Comment by whatthejeff** [comment]
I think highlight and charset were actually removed in 4.0 (see e66b7c9 and 9736dfe).

**Comment by whatthejeff** [comment]
This should be fixed now. Thanks for the heads up!
