### ISSUE TITLE
Create mock for abstract class with abstract constructor

### ISSUE THREAD

**Issue by Aistina** [sebastianbergmann/phpunit#1574]
If I have an abstract class, or interface, that forces child classes to implement an interface, like this:

```php
interface MyInterface {
    /**
     * MyInterface implementors should have a constructor that accepts one argument.
     *
     * @param string $param
     */
    public function __construct($param);
}
```

Then I am (currently) not able to `getMockForAbstractClass('MyInterface')`, not even when I specifically add `'__construct'` to `setMethods`. The error I get is:

> Fatal error: Class Mock_MyInterface_a9a2e1c6 contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (MyInterface::__construct)

Maybe some special case can be made for this scenario?

This is on PHPUnit 4.6.

**Comment by henriquemoody** [comment]
First of all, it's not an abstract class, so I'm not surprise it's not working, have you tried `getMock()` instead, or using `getMockForAbstractClass()` on an abstract class?

Whatever, create and interface with `__construct` or an abstract class with abstract `__construct` declaration doesn't looks a good idea. There are many other languages which doesn't have constructor inheritance and looks like people doesn't complain too much about it, maybe you should review your design in itself, but that's off topic, any way...

**Comment by Aistina** [comment]
Taking a second look, it seems there was one instance where I was using `getMock` rather than `getMockForAbstractClass`. Changing it there seems to have fixed the error. My bad.
