### ISSUE TITLE
Code coverage for Hack lang

### ISSUE THREAD

**Issue by farzadghanei** [sebastianbergmann/phpunit#1575]
It would be helpful if PHPUnit could generate code coverage reports for Hack lang source files. We got parse errors while running PHPUnit code coverage on a Hack source file. So we followed a suggested answer to the [question] (http://stackoverflow.com/questions/27856697/code-coverage-tool-for-hack-language question) regarding a code coverage tool for Hack lang, and it fixed the parse errors. But the coverage report had some semantic issues, claiming some parts of the code has not been exeucted, which did not make sense. For example the code block of an ``if`` statement has been executed, but not the condition.

**Comment by whatthejeff** [comment]
Thanks for the report, @farzadghanei. 

We already have an open issue for the parse errors (see sebastianbergmann/php-token-stream#43). 

Regarding the semantic issues, normally those are quirks in the core language implementation or in the Xdebug implementation. You might want to try checking the output from Xdebug to see if this is really a phpunit problem. If the output looks correct, then please open a new issue over at [sebastianbergmann/php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage).
