### ISSUE TITLE
Parameter Count for generated Mock Method is wrong, when using Reflection

### ISSUE THREAD

**Issue by sandreas** [sebastianbergmann/phpunit#1577]
I would like to test a Method, that uses Reflection to analyse an Object passed as first argument. Mocking this argument results in an unexpected behaviour, because Reflection detects a wrong parameter count. 

Sample Code:

```php
public function testMockReflection() {
        $mock = $this->getMockBuilder('Controllers\\UserController')
            ->setMethods(array('get'))
            ->getMock();

        $mock->expects($this->once())
            ->method('get')
            ->with($this->equalTo('1'))
            ->will($this->returnValue('user 1'));


        $reflectionClass = new \ReflectionClass($mock);

        // Failed asserting that 0 matches expected 1.
        $this->assertEquals(1, $reflectionClass->getMethod('get')->getNumberOfParameters());
}  
```

The Test fails, although ->with($this->equalTo('1')) is used, which should increase the parameter count to 1.

**Comment by whatthejeff** [comment]
The class definition for the mock object is generated by `getMock()`, before `with()` is called. The parameter list should match the parameter list for the original method. The `with()` method only sets an expectation on the arguments that the method should receive for a specific call.

**Comment by sandreas** [comment]
@whatthejeff 
The Mock Class "Controllers\\UserController" is not existing as source code! It is a fully mocked class. How can i set the expected method parameters for a fully mocked class method without writing code for this class?

I would prefer not creating a dependency in this unit test.

**Comment by whatthejeff** [comment]
@sandreas Unfortunately, there is not currently a way to do this.

**Comment by sandreas** [comment]
@whatthejeff 
Ok, what a pity... Can you reopen this ticket as a feature request or should i create a new one?
