### ISSUE TITLE
Cannot mock SoapClient in phpunit > 4.2.6

### ISSUE THREAD

**Issue by djjohnjosephuk** [sebastianbergmann/phpunit#1580]
Sample code: 

    $return->CreateOrderResult = 'Error : THIS IS AN ERROR';
        
    $soap   = $this
            ->getMockBuilder('\SoapClient')
            ->disableOriginalConstructor()
            ->getMock(); // Error thrown here
    $soap
            ->expects($this->exactly(1))
            ->method('__soapCall')
            ->will($this->returnValue($return));

Fatal error: Class 'Instantiator\Instantiator' not found in C:\....\vendor\phpunit\phpunit-mock-objects\src\Framework\MockObject\Generator.php on line 295

From what I can see what's changed in that Generator.php file is the namespace reference to 'Instantiator' which previously when working was 'Doctrine/Instantiator' but this doesn't work now 'Doctrine' has been removed from the namespace.

**Comment by whatthejeff** [comment]
Sounds like your dependencies got mixed up somehow. PHPUnit 4.3+ requires PHPUnit Mock Objects 2.3+ which uses the `Doctrine` namespace.
