### ISSUE TITLE
Cannot generate coverage when global vs local phpunit version don't match

### ISSUE THREAD

**Issue by alexdomsa** [sebastianbergmann/phpunit#1581]
I recently upgraded to Yosemite and installed phpunit phar globally as specified on https://phpunit.de/manual/current/en/installation.html
```bash
~ > phpunit --version
PHPUnit 4.4.1 by Sebastian Bergmann.
```

On projects which do NOT have phpunit installed with composer, everything works as expected.
```bash
~/project1 > phpunit --coverage-html /~/coverage/ tests/
PHPUnit 4.4.1 by Sebastian Bergmann.

Configuration read from /../project1/phpunit.xml.dist

..........................................

Time: 1.81 seconds, Memory: 8.75Mb

OK (42 tests, 297 assertions)

Generating code coverage report in HTML format ... done
```

I also have some projects in which phpunit is installed with composer.  In the composer.json file of that project I have a dependency on "phpunit/phpunit": "~3.7.0". When running tests with coverage, it will not create coverage report. 
```bash
~/project2 > phpunit --coverage-html /~/coverage/ tests/
PHPUnit 3.7.38 by Sebastian Bergmann.

Configuration read from /../project2/phpunit.xml.dist

..........................................

Time: 1.81 seconds, Memory: 8.75Mb

OK (42 tests, 297 assertions)
```

After making some tests, it looks like the issue appears when version of phpunit which was installed globally (4.4.1) is different than the one installed in each project (3.7.38). If the versions match, the report is generated as expected. 

Is this a known issue?

**Comment by whatthejeff** [comment]
When a project installs PHPUnit with composer, you should use the binary that is installed by composer. For instance:

~~~
./vendor/bin/phpunit --coverage-html /~/coverage/
~~~

If not, you run the risk of composer including files which conflict with the version of PHPUnit you have installed globally.

**Comment by alexdomsa** [comment]
@whatthejeff Thanks for your fast response. I know that we can run the binary installed under composer.
Just wanted to confirm the other scenario is a known issue.

**Comment by whatthejeff** [comment]
Oh, sorry. Yeah, it's a known issue. There's a bit of discussion about the issue in #1375.
