### ISSUE TITLE
Increase in memory usage after upgrading from 4.0.* to 4.1* or 4.4*

### ISSUE THREAD

**Issue by markus-perl** [sebastianbergmann/phpunit#1584]
Hi Sebastian,

I noticed a remarkable increase in memory usage by about 60% after upgrading from phpunit 4.0.20 to 4.1.* or 4.4.* in one of my projects.

This is the memory profile before the upgrade:
>Time: 2.89 minutes, Memory: 991.50Mb
>OK (4004 tests, 13181 assertions)

And after the upgrade:
>Time: 2.91 minutes, Memory: 1581.25Mb
>OK (4004 tests, 13181 assertions)

I'm running for speed purposes my tests with a disabled garbage collector:
`php -d zend.enable_gc=0 /vagrant/vendor/phpunit/phpunit/phpunit`

The memory leak was easy to find, it's located in the file Framework/Constrain/IsEqual.php

After changing the line:
        `$comparatorFactory = new SebastianBergmann\Comparator\Factory;`
to: 
        `$comparatorFactory = SebastianBergmann\Comparator\Factory::getInstance();`

the memory seems to be fixed:

>Time: 2.88 minutes, Memory: 994.52Mb
>OK (4004 tests, 13181 assertions)

Is there any reason, why you do not use the singleton in the IsEqual Class?

Best,
Markus

**Comment by sebastianbergmann** [comment]
Already implemented in PHPUnit 4.5: https://github.com/sebastianbergmann/phpunit/blob/4.5/src/Framework/Constraint/IsEqual.php#L122
