### ISSUE TITLE
Allow suppressing output / debug info except for failures

### ISSUE THREAD

**Issue by tomasfejfar** [sebastianbergmann/phpunit#1585]
When using PHPUnit as part of the build process (I'm using it with `grunt watch`) it would be great if I could fine-tune it's verbosity (or at least hide the "debug" info - phpunit version, config used and timing). What I would like to have is output like this:
`OK (1 test, 1 assertion)`
And the full output I'm used to if any test fails. 

Is that currently possible?

**Comment by sebastianbergmann** [comment]
No, that is currently not possible.

**Comment by tomasfejfar** [comment]
Could you suggest a course of action to make it possible? I may do a PR, but I'm not sure what would be a correct way of doing it. 

cc @johnhunt

**Comment by whatthejeff** [comment]
You could just filter the output from the grunt task.

**Comment by tomasfejfar** [comment]
Yes, but I would expect the tool to offer at least `-q` cli switch in case I want to work with it in a script. Analogy would be how hard would you life be if grep would return "No results found" instead of nothing when there are no results. Or something like that.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
