### ISSUE TITLE
Class 'SebastianBergmann\Exporter\Context' not found

### ISSUE THREAD

**Issue by andreasfernandez** [sebastianbergmann/phpunit#1587]
Hello,
since version 4.4.3 (installed via composer), this error occurs when running unit tests: 
```PHP Fatal error:  Class 'SebastianBergmann\Exporter\Context' not found in phpunit/src/Framework/TestCase.php on line 1632```

As far as I can see, the directory `sebastian/exporter/src/` misses a Context.php.

**Comment by wmdbMattes** [comment]
Sponsoring is possible :)

**Comment by GrahamCampbell** [comment]
Yeh, this class was actually moved. Looks like @sebastianbergmann missed that bit.

**Comment by GrahamCampbell** [comment]
The new class name is `SebastianBergmann\RecursionContext\Context`.

**Comment by pgampe** [comment]
No unit test for this? ;)

**Comment by sebastianbergmann** [comment]
Of course there is a test for this. But for some reason it did not fail on my local machine. That is a weirdness to explore for another day ...

**Comment by whatthejeff** [comment]
I caught this in `4.5` and `master` because they were failing on travis the other day. Guess `4.4` didn't start failing on travis until right before the release today :(

@sebastianbergmann Probably the exporter dependency just needed to be updated.
