### ISSUE TITLE
Missing support for testSuffix?

### ISSUE THREAD

**Issue by ianbytchek** [sebastianbergmann/phpunit#1588]
Trying to configure the default test suffixes globally to be able to use files ending with `TestCase.php` rather than `Test.php` as the default test source. I'm able to do this via command line options and via config for a particular suite / filter, but that doesn't always work well. For example, when running with PhpStorm, I don't want to update my run configuration with extra parameters, or when specifying a directory with tests, configuration of the suite / filter gets ignored. So, it kind of works, but I always need to explicitly specify some extra parameters… Ideally, this would be done via `phpunit.xml` like this:

```xml
<phpunit testSuffix="TestCase.php">
    <!--…-->
</phpunit>
```

In fact, the documentation states:

>The XML configuration above corresponds to the default behaviour of the TextUI test runner documented in the section called “Command-Line Options”.

But that doesn't seem to be the case with `testSuffix`.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
