### ISSUE TITLE
Stabilization Phase for new releases (nightly beta-quality builds)

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#1593]
With the current [release process](https://github.com/sebastianbergmann/phpunit/wiki/Release-Process) for PHPUnit a new release branch is created every two months. Beta-quality releases are made built nightly from this release branch until the first stable version is released from it.

Given the fact that over the course of the first year of using this release process we have not received any feedback based on these nightly builds (at least as far as I am aware of) it begs the question whether having this two-month stabilization period makes sense.

**Comment by remicollet** [comment]
Hi Sebastian.

In fedora, we have Koschei which can help.
See: http://koschei.cloud.fedoraproject.org/groups/php?order_by=-state%2C-started%2Cname

This allow us to run CI on all the PHP stack (build are raised by any dependency change), and have already detects some breakage (like the minor feof() behavior change in 5.6.5RC1 which have break Horde_Imap_Client (code) and guzzle (test suite)).

So, if you tag a RC (PHPUnit and needed dep.), I will update it in rawhide to raise a run of all test suites for available package.

Could this help ?

**Comment by sebastianbergmann** [comment]
The nightly alpha and beta releases are not tagged. But this could be changed, of course.

**Comment by remicollet** [comment]
@sebastianbergmann can we talk about this in Fosdem ?

**Comment by sebastianbergmann** [comment]
Sure :-)

**Comment by penfold45** [comment]
I use the alpha builds. I do not update daily maybe every 2 to 3 weeks. Ive never had an issue with them to report.

**Comment by sebastianbergmann** [comment]
Thank you, @penfold45, that is good feedback to hear.

**Comment by TomasVotruba** [comment]
It's to much information to process before download ATM, so I use only stable with self-update when I remember.

I can think of only one reason for using alpha - when my PR would be merged, just to get it soon.

I'd probably check how many issues are related to alpha/beta, that could provide some feedback.

**Comment by sebastianbergmann** [comment]
Can you elaborate on "to much information to process before download", @TomasVotruba? All you need to do to test the current alpha or beta is to download `https://phar.phpunit.de/phpunit-alpha.phar` or `https://phar.phpunit.de/phpunit-beta.phar`, respectively.

**Comment by TomasVotruba** [comment]
@sebastianbergmann Sure. I mean to process *mentally*: to find out how they differ from each other -> find where is the changelog, or compare diff of commits -> what is the last commit in both of them etc.

As I said, I'd only use them if I knew my PR was merged to get it ASAP.

**Comment by julianseeger** [comment]
Not sure if it fits here but I just stumbled upon this: at paratest, we would like to include `@alpha` and `@beta` versions of phpunit into out travis build matrix. Unfortunately, while the stable releases are tagged following semantic versioning, the alpha and beta releases are not. And while we are using composer, it would afaik be neccessary to get "-alpha" and "-beta" tags of phpunit to have them available through composer like `"phpunit/phpunit": "@beta"`. For example we coud now have `4.6.9-beta` and `4.7.1-alpha` or something like that. That would help a lot because probably nobody wants to track and increase the alpha and beta branches manually when a new release becomes stable.

**Comment by TomasVotruba** [comment]
@julianseeger What about sth like this?

```sh
evn:
  - PHP_UNIT_PHAR_VERSION=phpunit.phar
  - PHP_UNIT_PHAR_VERSION=phpunit-beta.phar
  - PHP_UNIT_PHAR_VERSION=phpunit-alpha.phar

script:
  - wget https://phar.phpunit.de/$PHP_UNIT_PHAR_VERSION own-phpunit
  - own-phpunit tests
```

**Comment by julianseeger** [comment]
>Tagging is really time-demanding.

The CI-Server (or whatever is used to make those phpunit-nightly builds) should probably be able to tag automatically. I don't know any sort of ci-server that is not able to do that. As @sebastianbergmann said "Beta-quality releases are made built nightly from this release branch" and a shouldn't every release have a tag?

>But what about sth like this?

Not quite sure how stable this gets. The phar would run phpunit (in version A) und that would load the bootstrap for the paratest tests which would then load composers autoload.php which would load phpunit (in version B). There are direct dependencies from paratest to phpunit (at least to some subcomponents like php-code-coverage) and I don't think we can make the tests use verion A completely. So the tests wouldn't be representative for that version and thats the whole point in the build matrix.

Of course we can live with manually adjusting the version constraints for each phpunit-release but as this thread seems to be based on a whish for feedback and @sebastianbergmann [said](https://github.com/sebastianbergmann/phpunit/issues/1593#issuecomment-71604514)
>The nightly alpha and beta releases are not tagged. But this could be changed, of course.

I thought it might be useful feedback to state that there definitely is a need for more tags out there ;)
