### ISSUE TITLE
Recommend version 4.6 on Packagist does not install

### ISSUE THREAD

**Issue by Tatsh** [sebastianbergmann/phpunit#1594]
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for phpunit/phpunit 4.6.*@dev -> satisfiable by phpunit/phpunit[4.6.x-dev].
    - phpunit/phpunit 4.6.x-dev requires sebastian/exporter ~1.2 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.
```

What I see there is that *sebastian/exporter: ~1.2* is written twice. This also applies to version 4.5. Appears to the be the source of this error.

When you look at 4.4, it is written only once. *4.4.x-dev reference: d49d806*

**Comment by sebastianbergmann** [comment]
PHPUnit 4.6 is in development, as is PHPUnit 4.5. I have no idea where you or Packagist get the idea from that anything newer than PHPUnit 4.4.X would be stable at this time.
