### ISSUE TITLE
Time to use Namespace for PHPUnit?

### ISSUE THREAD

**Issue by HallofFamer** [sebastianbergmann/phpunit#1597]
In the current version I still see things like PHPUnit_Framework_TestCase, when I think it should have been TestCase in namespace PHPUnit\Framework. Is there a reason why PHPUnit refuses to use namespace? The only one I can think of is PHP 5.2 support, but I thought it was or should have been dropped? Am I missing something here?

**Comment by whatthejeff** [comment]
The reason the code still doesn't use namespaces is mostly backwards compatibility. Over time, parts of the codebase have been transitioning to namespaces. The ultimate goal is to complete this transition by PHPUnit 5 (see https://github.com/sebastianbergmann/phpunit/issues/1595#issuecomment-71826978).
