### ISSUE TITLE
Method PHPUnit_Framework_ExpectationFailedException::__toString() must not throw an exception

### ISSUE THREAD

**Issue by hollywu** [sebastianbergmann/phpunit#1598]
Occasionally, when running a test, this error comes up when a test fails: 

PHP Fatal error:  Method PHPUnit_Framework_ExpectationFailedException::__toString() must not throw an exception in phar:///usr/local/bin/phpunit/phpunit/TextUI/ResultPrinter.php on line 0

Any simple failure can trigger this error. I tried using a try/catch on my autoloader to see if there were any classes from PHPUnit that my autoloader shouldn't be trying to load, as I had a previous problem with my autoloader trying to load the now deprecated PHPUnit_Extensions_Story_TestCase, but did not catch anything. I'm not too entirely sure how to properly replicate this problem as I can't find a pattern to why the error appears. Sometimes I get the correct failed assertion message instead of the error.

Also, sometimes I get this error instead: 

PHP Fatal error:  PHP Fatal error: Method PHPUnit_Framework_ExceptionWrapper::__toString() must not throw an exception in phar:///tmp/phpunit.phar/phpunit/TextUI/ResultPrinter.php on line 0

which also came up in this previous thread: https://github.com/sebastianbergmann/phpunit/issues/1485. I tried excluding the Symfony class from my autoloader, but it didn't change anything.

**Comment by hollywu** [comment]
Also, I'm using PHPUnit 4.4.5.

**Comment by whatthejeff** [comment]
Does your autoloader throw an exception when it can't find a class?

**Comment by hollywu** [comment]
Yes, it throws Exception: include_once(nonExistantClass.php): failed to open stream: No such file or directory

**Comment by sebastianbergmann** [comment]
Your autoloader must do anything for code that it is not responsible for.

**Comment by hollywu** [comment]
Are you saying that my autoloader is trying to load a class it shouldn't to get the PHPUnit_Framework_ExpectationFailedException error? Is there a way to pinpoint this class? Because when I put my autoloader inside a try/catch, it doesn't catch anything.

**Comment by cezarpirajant** [comment]
I'm having the same problem. To fix that i had to change the line 93 of the PHPUnit_Util_Blacklist class to:

class_exists($className, false);

Why: I dont think you have to call autoload in this case, since this is only checking for the classes loaded which will be filtered.

**Comment by Tairy** [comment]
I am having the same problem. But my autoloader does not throw any exception.

**Comment by fireproofsocks** [comment]
Same issue.  I think Sebastian meant "Your autoloader must NOT do anything for code that it is not responsible for."  E.g. if your code registers an exception handler or shutdown function via set_exception_handler or register_shutdown_function and there's an exception thrown anywhere in there, that can trigger this PHPUnit error.

**Comment by peteraba** [comment]
@cezarpirajant is there PR for this?

**Comment by peteraba** [comment]
@cezarpirajant never mind, I see that there isn't.

**Comment by Malbeth81** [comment]
How come this still isn't fixed after all this time? All that's needed is a simple try-catch in https://github.com/sebastianbergmann/phpunit/blob/master/src/Util/Blacklist.php

Or to disable class auto-loading like cezarpirajant suggests.

**Comment by Malbeth81** [comment]
Since I didn't want to patch the PHPUnit library, I ended up doing this inside of my PHPUnit bootstrap instead:

`
// Remove missing classes from the PHPUnit blacklist, to prevent an exception rendering error.
// Workaround to fix the actual PHPUnit bug (see https://github.com/sebastianbergmann/phpunit/issues/1598).
if (!empty(PHPUnit_Util_Blacklist::$blacklistedClassNames)) {
  foreach (PHPUnit_Util_Blacklist::$blacklistedClassNames as $className => $parent) {
    try {
      if (!class_exists($className)) {
        unset(PHPUnit_Util_Blacklist::$blacklistedClassNames[$className]);
      }
    } catch (Exception $e) {
      unset(PHPUnit_Util_Blacklist::$blacklistedClassNames[$className]);
    }
  }
}
`

**Comment by epdenouden** [comment]
@Malbeth81 What version of PHPUnit are you running? If the fix is really this simple, pull requests for breaking bugs are still accepted for older versions. Is there a self-contained testcase?

**Comment by epdenouden** [comment]
@Malbeth81 thanks for your reply, but v5 is too far back to receive further updates. There's bugfixes for 6.x, some new features for v7 and a serious refactoring for beyond.

**Comment by xnzj** [comment]
If someone use Laravel and doesn't know how to fix it
`// /bootstrap/autoload.php
require __DIR__.'/../vendor/autoload.php';

if (env('APP_ENV') === 'testing') {
    foreach (PHPUnit_Util_Blacklist::$blacklistedClassNames as $className => $parent) {
        try {
            if (!class_exists($className)) {
                unset(PHPUnit_Util_Blacklist::$blacklistedClassNames[$className]);
            }
        } catch (\Throwable $e) {
            unset(PHPUnit_Util_Blacklist::$blacklistedClassNames[$className]);
        }
    }
}`

**Comment by precamp-io** [comment]
@xnzj I am new to Laravel not sure were to update this. Can you point me in the right direction pls?

**Comment by xnzj** [comment]
> @xnzj I am new to Laravel not sure were to update this. Can you point me in the right direction pls?

`you_project_root_path/bootstrap/autoload.php`

My laravel version is 5.4

**Comment by precamp-io** [comment]
I using Laravel 8On 2 Apr 2022 02:50, xnzj ***@***.***> wrote:

@xnzj I am new to Laravel not sure were to update this. Can you point me in the right direction pls?

you_project_root_path/bootstrap/autoload.php
My laravel version is 5.4
