### ISSUE TITLE
Composer-Installed PHPUnit is used when trying to use PHPUnit from a PHAR

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#1599]
When PHPUnit is installed via Composer and Composer's `vendor/autoload.php` is used as PHPUnit's bootstrap then the Composer-installed PHPUnit will be used instead of the one actually invoked, for instance one invoked from a PHAR:

    $ cat composer.json 
    {
        "require-dev": {
            "phpunit/phpunit": "~3.7"
        }
    }

    $ ./vendor/bin/phpunit --version
    PHPUnit 3.7.38 by Sebastian Bergmann.

    $ php phpunit.phar --version    
    PHPUnit 4.4.5 by Sebastian Bergmann.

    $ php phpunit.phar --bootstrap vendor/autoload.php tests
    PHPUnit 3.7.38 by Sebastian Bergmann.

    Configuration read from /home/sb/test/phpunit.xml

    .
    .
    .

**Comment by sun** [comment]
That's the expected behavior currently, isn't it?

It was discussed in one of the existing issues already.  The only way to "force" the code of the .phar would be to front-load all PHPUnit files into memory, so that the classloader is no longer triggered.
