### ISSUE TITLE
Globally installed phpunit might not work correctly

### ISSUE THREAD

**Issue by neomerx** [sebastianbergmann/phpunit#1605]
Globally installed phpunit gives an error of 'Cannot redeclare class' however if installed in vendor folder doesn't give such an error.

More details at https://github.com/laravel/framework/issues/7299

**Comment by BenHicks** [comment]
Maybe this has the same cause as https://github.com/sebastianbergmann/phpunit/issues/1600?

**Comment by neomerx** [comment]
@BenHicks I don't know what's the cause of the error and I can only say I don't have PEAR installed on my machine.

**Comment by jaceju** [comment]
I tried to comment the code in `vendor/nikic/php-parser/lib/bootstrap.php` and it works fine.

```php
// require __DIR__ . '/PhpParser/Autoloader.php';
// PhpParser\Autoloader::register();
```

But it is not a good idea.

**Comment by sebastianbergmann** [comment]
Cannot reproduce, closing.
