### ISSUE TITLE
Support for nested testsuite's in phpunit.xml

### ISSUE THREAD

**Issue by chbiel** [sebastianbergmann/phpunit#1610]
It would be nice to support nested testsuites:

```xml
<testsuites>
    <testsuite name="feature 1">
        <directory>some-dir</directory>
    </testsuite>
    <testsuite name="feature 2">
        <file>feature2-1Test.php</file>
        <file>feature2-2Test.php</file>
    </testsuite>
    <testsuite name="all">
        <testsuite>feature 1</testsuite>
        <testsuite>feature 2</testsuite>
    </testsuite>
</testsuites>
```

also implemented in paratest library:
https://github.com/brianium/paratest/pull/148

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
