### ISSUE TITLE
Treat risky tests as failure case

### ISSUE THREAD

**Issue by Bilge** [sebastianbergmann/phpunit#1612]
By default risky tests are still considered a pass. There does not appear to be an option to treat risky tests as failures. If there is indeed no such option then this issue is a request for such a feature.

**Comment by sebastianbergmann** [comment]
A test that is risky is not a failure and should not be treated as such.

**Comment by Bilge** [comment]
Clearly that is your sentiment but if I feel differently why shouldn't this be an option I can enable in the software?

**Comment by rap2hpoutre** [comment]
@sebastianbergmann But it could be considered as an option (should fail on risky tests or not). Could be useful for continuous delivery (I don't want to ship risky test).

**Comment by SOF3** [comment]
A simple alternative is to add a line `self::assertGreaterThan(0, self::getCount(), "Test is risky");` in the `tearDown` impl of every test case class.

**Comment by taylankasap** [comment]
@SOF3 this already exists now. Use `failOnRisky` config option or `--fail-on-risky` command line parameter.

There is also --stop-on-risky but it stops at the first risky test rather than running all tests and exiting with an error code.
