### ISSUE TITLE
AssertEquals with string with leading zero doesn't work correctly

### ISSUE THREAD

**Issue by gordenfreeman1991** [sebastianbergmann/phpunit#1614]
Hello Sebastian Bergmann

I think I found a bug in PHPUnit:

Not Correct
----------------
$telNr1 = "09";
$telNr2 = "9";
$this->AssertEquals($telNr1, $telNr2);

![image](https://cloud.githubusercontent.com/assets/10993943/6188942/ce089bee-b396-11e4-9834-ec0b5a2c7e7f.png)

= Here i expect failed - "09" is  not equals "9".

Correct
----------
$telNr1 = "9";
$telNr2 = "90";
$this->AssertEquals($telNr1, $telNr2);

![image](https://cloud.githubusercontent.com/assets/10993943/6188956/f480060e-b396-11e4-8381-14539191870f.png)

= Here is failed correct - "9" is not equals "90".

**IDE**
- PHPStorm

**PHP**
- 5.6.3

**PHPUnit (tested with)**
- 4.5
- 4.4
- 4.3
- 4.2
- 4.1
- 4.0
- 3.7.21

**Comment by larsvetter** [comment]
i have the same problem. thx for reporting!

**Comment by brunoric** [comment]
I think that is not a bug. The method [*assertEquals*][assertEquals] use the constraint [*IsEqual*][isEqual]. The description of this class is explicit about using the [PHP '==' (equal)][equalOperator] operator. As you can see [in this example][comparisonExample], this is actually the correct behavior of the PHP.

[assertEquals]: https://github.com/sebastianbergmann/phpunit/blob/b92539368bdda39ecc77a4f6c0ba2c7dae1d24e0/src/Framework/Assert.php#L480
[isEqual]: https://github.com/sebastianbergmann/phpunit/blob/master/src/Framework/Constraint/IsEqual.php
[equalOperator]: http://php.net/manual/en/language.operators.comparison.php
[comparisonExample]: http://runnable.com/VN5GKQprYnNDwoUJ/equal-comparison-demo-for-php

**Comment by krzysztof-magosa** [comment]
If you want to use === operator you should use assertSame method.
It will resolve your problem.

**Comment by GrahamCampbell** [comment]
> i have the same problem. thx for reporting!

This is NOT a bug. You want to use `assertSame` to get the result you want.
