### ISSUE TITLE
Nested trait conflict resolution (renamed methods) not honored when building mocks

### ISSUE THREAD

**Issue by bananer** [sebastianbergmann/phpunit#1618]
Consider this trait hierarchy:

```
<?php

trait T1 {
  public function foo() {
    return 1;
  }
}

trait T2 {
  use T1 {
    foo as bar;
  }

  public function foo() {
    return 2;
  }
}


class Traits {
  use T2;
}
```

This is properly supported by PHP, `(new Traits())->bar()` returns `1`.

But when I try to mock this class in PHPUnit:

```
class TraitsTest extends PHPUnit_Framework_TestCase
{
    public function testTraits()
    {
        $mockFoo = $this->getMock('\Traits');
    }
}
```

There is an error in the eval'd code:
`PHP Fatal error:  Cannot redeclare Mock_Traits_9260efaf::foo() in phar:///home/philip/src/test/phpunit.phar/phpunit-mock-objects/Framework/MockObject/Generator.php(335) : eval()'d code on line 33`

I was looking at the eval code with a debugger, and there were two declarations of `foo()` in the class. So it seems renaming the methods from traits in other traits is not honored by PHPUnit when generating mocks.

When I use both traits in the class and do conflict resolution there (like in the [official example](http://php.net/manual/en/language.oop5.traits.php#language.oop5.traits.conflict)) PHPUnit mocks the renamed method as expected.

**Comment by bananer** [comment]
I can work around the problem by manually specifying the list of methods when creating mocks.

**Comment by funkytaco** [comment]
I've run into the same problem, but I was doing something more along the lines of this with nested functions, which is legal in PHP 5.3+

    <?php

    namespace Main\Traits;

        trait QueryData {

            public function getUsers() {
                $users = [];
                function prepUserForMustache($user) { return array('name' => $user); }
                //foo
                return $users;
            }

            public function getFirstUser() {
                $users = [];
                function prepUserForMustache($user) { return array('name' => $user); }
                //foo
                return $user;
            }

        }

Trying to figure this out now.

**Comment by funkytaco** [comment]
A better example:
    <?php

    namespace Main\Mock\Traits;

        trait QueryData {

            public function appName() {
                return 'PHP Template Seed Project';
            }

            public function getLintHtmlFromTrait() {
                return '<script type="text/javascript">
                    javascript:(function(){var s=document.createElement("script");s.onload=function(){bootlint.showLintReportForCurrentDocument([]);};s.src="https://maxcdn.bootstrapcdn.com/bootlint/latest/bootlint.min.js";document.body.appendChild(s)})();
                    </script>';
            }

            public function getUsers() {

                function mustachify($user) { return array('name' => $user); }
                $users = [mustachify('@funkytaco'),mustachify('@PatrickLouys'),mustachify('@Rican7')];
                return $users;
            }
            

        }

PHP Fatal error:  Cannot redeclare Main\Mock\Traits\mustachify() (previously declared in /Users/me/GitHub/php-seed-bootstrap/src/Mock/Traits/QueryData.php:19) in /Users/me/GitHub/php-seed-bootstrap/src/Mock/Traits/QueryData.php on line 19
PHP Stack trace:
PHP   1. {main}() /Users/me/GitHub/php-seed-bootstrap/vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /Users/me/GitHub/php-seed-bootstrap/vendor/phpunit/phpunit/phpunit:36
PHP   3. PHPUnit_TextUI_Command->run() /Users/me/GitHub/php-seed-bootstrap/vendor/phpunit/phpunit/src/TextUI/Command.php:104
PHP   4. PHPUnit_TextUI_TestRunner->doRun() /Users/me/GitHub/php-seed-bootstrap/vendor/phpunit/phpunit/src/TextUI/Command.php:152
PHP   5. PHPUnit_Framework_TestSuite->run() /Users/me/GitHub/php-seed-bootstrap/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:398
PHP   6. PHPUnit_Framework_TestSuite->run() /Users/me/GitHub/php-seed-bootstrap/vendor/phpunit/phpunit/src/Framework/TestSuite.php:716
PHP   7. PHPUnit_Framework_TestCase->run() /Users/me/GitHub/php-seed-bootstrap/vendor/phpunit/phpunit/src/Framework/TestSuite.php:716
PHP   8. PHPUnit_Framework_TestResult->run() /Users/me/GitHub/php-seed-bootstrap/vendor/phpunit/phpunit/src/Framework/TestCase.php:693
PHP   9. PHPUnit_Framework_TestCase->runBare() /Users/me/GitHub/php-seed-bootstrap/vendor/phpunit/phpunit/src/Framework/TestResult.php:609
PHP  10. PHPUnit_Framework_TestCase->runTest() /Users/me/GitHub/php-seed-bootstrap/vendor/phpunit/phpunit/src/Framework/TestCase.php:737
PHP  11. ReflectionMethod->invokeArgs() /Users/me/GitHub/php-seed-bootstrap/vendor/phpunit/phpunit/src/Framework/TestCase.php:860
PHP  12. MockPDOTest->testMockGetUsers() /Users/me/GitHub/php-seed-bootstrap/vendor/phpunit/phpunit/src/Framework/TestCase.php:860
PHP  13. Main\Mock\PDO->getUsers() /Users/me/GitHub/php-seed-bootstrap/test/src/Mock/PDO_Test.php:22

Fatal error: Cannot redeclare Main\Mock\Traits\mustachify() (previously declared in /Users/me/GitHub/php-seed-bootstrap/src/Mock/Traits/QueryData.php:19) in /Users/me/GitHub/php-seed-bootstrap/src/Mock/Traits/QueryData.php on line 19

Call Stack:
    0.0002     231096   1. {main}() /Users/me/GitHub/php-seed-bootstrap/vendor/phpunit/phpunit/phpunit:0
    0.0031     581304   2. PHPUnit_TextUI_Command::main() /Users/me/GitHub/php-seed-bootstrap/vendor/phpunit/phpunit/phpunit:36
    0.0031     581528   3. PHPUnit_TextUI_Command->run() /Users/me/GitHub/php-seed-bootstrap/vendor/phpunit/phpunit/src/TextUI/Command.php:104
    0.0255    2779264   4. PHPUnit_TextUI_TestRunner->doRun() /Users/me/GitHub/php-seed-bootstrap/vendor/phpunit/phpunit/src/TextUI/Command.php:152
    0.0273    2934848   5. PHPUnit_Framework_TestSuite->run() /Users/me/GitHub/php-seed-bootstrap/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:398
    0.0344    3593136   6. PHPUnit_Framework_TestSuite->run() /Users/me/GitHub/php-seed-bootstrap/vendor/phpunit/phpunit/src/Framework/TestSuite.php:716
    0.0358    3604832   7. PHPUnit_Framework_TestCase->run() /Users/me/GitHub/php-seed-bootstrap/vendor/phpunit/phpunit/src/Framework/TestSuite.php:716
    0.0358    3604832   8. PHPUnit_Framework_TestResult->run() /Users/me/GitHub/php-seed-bootstrap/vendor/phpunit/phpunit/src/Framework/TestCase.php:693
    0.0358    3605840   9. PHPUnit_Framework_TestCase->runBare() /Users/me/GitHub/php-seed-bootstrap/vendor/phpunit/phpunit/src/Framework/TestResult.php:609
    0.0359    3626776  10. PHPUnit_Framework_TestCase->runTest() /Users/me/GitHub/php-seed-bootstrap/vendor/phpunit/phpunit/src/Framework/TestCase.php:737
    0.0359    3627544  11. ReflectionMethod->invokeArgs() /Users/me/GitHub/php-seed-bootstrap/vendor/phpunit/phpunit/src/Framework/TestCase.php:860
    0.0359    3627576  12. MockPDOTest->testMockGetUsers() /Users/me/GitHub/php-seed-bootstrap/vendor/phpunit/phpunit/src/Framework/TestCase.php:860
    0.0360    3627688  13. Main\Mock\PDO->getUsers() /Users/me/GitHub/php-seed-bootstrap/test/src/Mock/PDO_Test.php:22

**Comment by funkytaco** [comment]
I had to move the mustachify function out of the function for the test to pass, but I'd prefer to not have to do that.

**Comment by sebastianbergmann** [comment]
I am afraid that there is nothing we can do about this. What PHPUnit (phpunit-mock-objects actually) does is to generate a new class extends the `Traits` class. The Reflection API is used to query the methods of that class. For each method found a method in the generated class is generated.

The problem you are reporting stems from the fact that the Reflection API, wrongly in my opinion (see https://bugs.php.net/bug.php?id=69180), reports that the class in question has two methods named `foo`. Thus the generated code contains two methods named `foo`.

BTW: This should have been reported at https://github.com/sebastianbergmann/phpunit-mock-objects/issues
