### ISSUE TITLE
Option to suppress typehints in mocked methods

### ISSUE THREAD

**Issue by tampe125** [sebastianbergmann/phpunit#1619]
Please consider the following function:
```php
public function foobar(\Dummy\Namespace\Class $model)
{
    // Do something inside it
}
```

It would be very useful if while creating the mock for that specific method we could suppress the typehint `\Dummy\Namespace\Class`. In that way we would be free to pass whatever argument we want, for example a closure instead of an actual class.

**Comment by sebastianbergmann** [comment]
What you are asking for is not possible as the signature of a method of a child class must be compatible with the signature of the respective method in the parent class.

Also note that this [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md) have been reported on the [phpunit-mock-objects](https://github.com/sebastianbergmann/phpunit-mock-objects) project instead.
