### ISSUE TITLE
is_file(): Unable to find the wrapper "vfs" - did you forget to enable it when you configured PHP?

### ISSUE THREAD

**Issue by ianbytchek** [sebastianbergmann/phpunit#1624]
I'm using [php-vfs](https://github.com/adlawson/php-vfs) as a virtual file system for testing purposes. In selected test cases I create a new FS before each test and tear it down after. If I happen to have a php file in that virtual file system that throws an exception and that appears in the exception backtrace, the PHPUnit will fail while filtering that backtrace.

```
PHP Fatal error:  Uncaught exception 'ErrorException' with message 'is_file(): Unable to find the wrapper "vfs" - did you forget to enable it when you configured PHP?' in /dep/vendor/phpunit/phpunit/src/Util/Filter.php:72
Stack trace:
#0 [internal function]: PHPUnit_Util_Fileloader::{closure}(2, 'is_file(): Unab...', '/Users/ianbytch...', 72, Array)
#1 /dep/vendor/phpunit/phpunit/src/Util/Filter.php(72): is_file('vfs://great/mys...')
#2 /private/var/folders/w3/zytpgjm11557jppm2zbg8xmh0000gq/T/ide-phpunit.php(345): PHPUnit_Util_Filter::getFilteredStacktrace(Object(PHPUnit_Framework_ExceptionWrapper))
#3 /private/var/folders/w3/zytpgjm11557jppm2zbg8xmh0000gq/T/ide-phpunit.php(401): IDE_PHPUnit_Framework_TestListener::getDetails(Object(PHPUnit_Framework_ExceptionWrapper))
#4 /dep/vendor/phpunit/phpunit/src/Framework/TestResult.php(234): IDE_PHPUnit_Framework_TestListener->addError(Object(Com in /dep/vendor/phpunit/phpunit/src/Util/Filter.php on line 72
```

On one hand, if that filtering was done before the test tear down that exception would not happen. On another hand, the job of `getFilteredStacktrace` is to filter the stack trace, not validate / check if `$frame['file']` is a real file. If it's set, it can be assumed that it is, I don't see what value adds `is_file($frame['file'])` check inside the method that pretty much only filters strings…

**Comment by sdhepse** [comment]
Did you get any solution for this ? I am facing the same :(

**Comment by ianbytchek** [comment]
@sdhepse I did, but I can't remember the exact solution. Will get back on this in a few hours.

**Comment by sdhepse** [comment]
@ianbytchek yea.. please. I still have the same issue

**Comment by sdhepse** [comment]
@ianbytchek : I resolved this. Thanks for extending help. I was `use \org\bovigo\vfs\vfsStream;`
I was using `use org\bovigo\vfs\vfsStream;`
Initial `\` was missing.

**Comment by sun** [comment]
@sdhepse That most likely means you have a rogue second copy of PHPUnit somewhere else in your project/application/filesystem.

Most likely, this issue was ultimately resolved by updating PHPUnit to a more recent 4.x version?

**Comment by sdhepse** [comment]
@sun My PHP version is 4.2.6

**Comment by sebastianbergmann** [comment]
@sdhepse You mean that your PHPUnit version is 4.2.6, right? :-) Anyway, PHPUnit < 4.7 is not supported anymore.

**Comment by sdhepse** [comment]
Ohh yeah. My PHPUnit version is 4.2.6. Well... it does support. It worked for me.

**Comment by sun** [comment]
LOL @sebastianbergmann - hope we'll meet for a drink someday :-)

---
@ianbytchek Do you want to close this issue?

**Comment by ianbytchek** [comment]
@sebastianbergmann so… what about the original question that apparently has nothing to do with the yesterday's discussion? Can you have a look into it?

**Comment by macieklag** [comment]
You forgot to register wrapper `vfsStreamWrapper::register();`
