### ISSUE TITLE
Mark a stable version

### ISSUE THREAD

**Issue by BevanR** [sebastianbergmann/phpunit#1632]
Can stable versions be marked as "stable" in packagist so that composer can install PHPUnit more easily without needing to specify version numbers or dev-version compatibility?

**Comment by sebastianbergmann** [comment]
Stable versions are marked with tags. What further marking do you mean?

**Comment by BevanR** [comment]
Oops!  Packagist does recognise stable PHPunit releases. I was using composer incorrectly.  Sorry.  :)
