### ISSUE TITLE
expectedException annotation does not resolve use statements.

### ISSUE THREAD

**Issue by Bilge** [sebastianbergmann/phpunit#1633]
The following code works.

```php
use Exception\FooException;

    /**
     * @expectedException Exception\FooException
     */
    public function test()
    {
        throw new FooException;
    }
```

However, the following code generates the following error.
```php
use Exception\FooException;

    /**
     * @expectedException FooException
     */
    public function test()
    {
        throw new FooException;
    }
```

> ReflectionException: Class FooException does not exist

**Comment by henriquemoody** [comment]
You must use the full class name instead.

**Comment by chrisguitarguy** [comment]
If you're on PHP 5.5+ and want to use imports, you can call `setExpectedException` inside your tests:

```php
use Acme\Package\Exception\SomeException;

class SomeTest extends \PHPUnit_Framework_TestCase
{
    public function testSomething()
    {
        $this->setExpectedException(SomeException::class);
        // rest of the test here
    }
}
```

**Comment by erenhatirnaz** [comment]
@chrisguitarguy Hi, I'm also experiencing this problem. Your solution works, but I need `@expectedExceptionMessage` and `@expectedExceptionCode` annotations. This way does not work:
```php
/**
  * @expectedExceptionMessage foobar
*/
public function testPageNotFound() {
    $this->setExpectedException("Namespace\\SomeException");
    // test here
}
```
This code can not handle the annotation. How do I handle this test case?

**Comment by GrahamCampbell** [comment]
```php
$this->setExpectedException(Namespace\SomeException::class);
```

is what you want

**Comment by chrisguitarguy** [comment]
@erenhatirnaz `setExpectedException` takes some additional arguments.

```php
use Acme\Package\Exception\SomeException;

class SomeTest extends \PHPUnit_Framework_TestCase
{
    public function testSomething()
    {
        $this->setExpectedException(
            SomeException::class,
            'the message',
            101 // the code
        );

        // ...
    }
}

**Comment by erenhatirnaz** [comment]
@chrisguitarguy Ohh, sorry, I forgot to check the documentation. Thank you so much.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
