### ISSUE TITLE
Cannot modify header information - headers already sent 

### ISSUE THREAD

**Issue by euoia** [sebastianbergmann/phpunit#1634]
Commit a05200c (between 4.4.1 and 4.4.2) causes some of our tests (ones which call setcookie) to fail with this error:
```
Cannot modify header information - headers already sent by (output started at /Users/euoia/Code/phpunit/src/Util/Printer.php:137)
```

Our phpunit.xml file looks like this:
```
<phpunit
        bootstrap="core/protected/tests/phpunit/bootstrap.php"
        colors="true"
        convertErrorsToExceptions="true"
        convertNoticesToExceptions="true"
        convertWarningsToExceptions="true"
        stopOnFailure="false"
        stderr="true"
>
...
</phpunit>
```

And we run phpunit with no command line arguments.

**Comment by mpalourdio** [comment]
+1 on this, the xml parameter --stderr="true" doesn't seem to work anymore from 4.4.2. Just tried with 4.4.1, and it's ok. At least when running tests from **PhpStorm.**

Switch to 4.4.2, the errors are not sent anymore to stderr. (from **PhpStorm**)

Running the test suite from CLI works just fine. Any hint on this ?

**Comment by sebastianbergmann** [comment]
Does this problem exist outside the scope of PhpStorm?

**Comment by mpalourdio** [comment]
Not for me, it just works correctly when simply running 'phpunit' from cmd.

**Comment by sebastianbergmann** [comment]
Then I am sorry to say that I cannot help you.
