### ISSUE TITLE
PHPUnit overrides output when called programmatically

### ISSUE THREAD

**Issue by YMIndustries** [sebastianbergmann/phpunit#1635]
Hi,

I'm trying to call PHPUnit from some PHP code, as I'm running a server on my Android tablet so I can write code on the bus to work and on Android executing things on the command line is tricky to say the least.

```PHP
<!DOCTYPE html>
<html>
	<head>
		<title>Tests</title>
	</head>
	<body>
		<h1>Test results</h1>
		<pre>
<?php
			$_SERVER['argv'] = $argv = ['--', 'tests/'];

			include("PHPUnit.phar");

			echo "test1";
			
			//PHPUnit_TextUI_Command::main(false);
			$tester = new PHPUnit_TextUI_Command;
			$tester->run($argv, false);
			
			echo "test2";
?>
		</pre>
	</body>
</html>
```

The output of this received by the browser is:

```HTML

.......

Time: 242 ms, Memory: 2.00Mb

OK (7 tests, 8 assertions)
test2		</pre>
	</body>
</html>
```

As you can see, everything prior to the $tester-run() call is erased. I tried using output buffering to prevent this issue:

```PHP
<!DOCTYPE html>
<html>
	<head>
		<title>Tests</title>
	</head>
	<body>
		<h1>Test results</h1>
		<pre>
<?php
			$_SERVER['argv'] = $argv = ['--', 'tests/'];

			include("PHPUnit.phar");

			echo "test1";
			
			ob_start();
			//PHPUnit_TextUI_Command::main(false);
			$tester = new PHPUnit_TextUI_Command;
			$tester->run($argv, false);
			ob_end_clean();
			
			echo "test2";
?>
		</pre>
	</body>
</html>
```

But this code gives me a `Failed to flush buffer. No buffer to flush` error.

I'm sure there's a better way for me to be programmatically calling PHPUnit, but this still seems like unexpected behaviour.

As an aside, do you know why I need to have a '--' element in my argv array? If it's not there I just get the help text printed.

Thanks,

YM

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
