### ISSUE TITLE
Undefined method SplFileInfo::_getFilename()

### ISSUE THREAD

**Issue by bobmulder** [sebastianbergmann/phpunit#1636]
When I run any phpunit-command in my project I get the following error: `Fatal error: Call to undefined method SplFileInfo::_getFilename() in F:\xampp\htdocs\projects\project\vendor\phpunit\php-file-iterator\File\Iterator.php on line 117`.

What caused this, and how to fix this?

**Comment by sebastianbergmann** [comment]
There is no method call on that line: https://github.com/sebastianbergmann/php-file-iterator/blob/master/File/Iterator.php#L117

Which version of PHPUnit did you install? And how?

**Comment by bobmulder** [comment]
I updated phpunit and the error is gone. I think the install (via composer) was not valid...

**Comment by bobmulder** [comment]
Hey Sebastian, I am getting this error again. This is very strange. This is only caused when running `phpunit` (without path). When adding a path I have to do it including the file-name. So, testing a directory gives me the same error. I cant find a solution for this. How is this problem caused? My `phpunit.xml` contains: 

```
	<testsuites>
		<testsuite name="CakeManager">
			<directory suffix='.php'>./tests/TestCase/</directory>
		</testsuite>
	</testsuites>
```

I hope you have any sugestion... Thanks for this amazing tool :)
