### ISSUE TITLE
Expectation sequences as an alternative to at()

### ISSUE THREAD

**Issue by dracony** [sebastianbergmann/phpunit#1641]
Using ->at() programmatically adds the inconvenience of having to track the index manually, especially in some more complex cases. Consider this:

```php
$mock->expects($this->at(0))->...;
$this->addSomeExpectations($mock);
$mock->expects($this->at(?????))->...; 
```

To actallyknow which number to put in  ????? I should either check what happens in addSomeExpectations() or pass some $atCounter variable around:

```php
$atCounter = 0;
$mock->expects($this->at($atCounter++))->...;
$this->addSomeExpectations($mock, &$atCounter);
$mock->expects($this->at($atCounter++))->...; 
```

If we had an alternative that would to $at counting internally we could just do:

```php
$mock->expects($this->sequence())->...;
$this->addSomeExpectations($mock);
$mock->expects($this->sequence())->...; 
```

Does that sound like a good idea to you?

**Comment by sshymko** [comment]
I can definitely relate to the difficulty of tracking the invocation counter.

How about the alternative syntax that would keep `$this->at()`:
```php
$mock->expects($this->at($this->next()));
```

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md) have been reported on the [phpunit-mock-objects](https://github.com/sebastianbergmann/phpunit-mock-objects) project instead.
