### ISSUE TITLE
assertNotContains reports wrong message

### ISSUE THREAD

**Issue by php-denken** [sebastianbergmann/phpunit#1642]
assertNotContains reports "[haystack] does not contain [needle]" as error message if haystack contains needle. It should report something like "[haystack] does contain [needle] and should not". It is a problem with wrong usage of the negation array. Its a negation of a negation.

**Comment by sshymko** [comment]
I can confirm the issue with `PHPUnit_Framework_Constraint_Not` negating all occurrences of definitive keywords. The correct behavior would be to invert the topmost statement only.

I run into the issue when implementing #1648 that introduces assertions similar to `assert[Not]Contains[Only]`.

**Comment by ShiraNai7** [comment]
I can confirm this too. Still happens in the latest version. Can result in very confusing error messages if some assertions fail.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
