### ISSUE TITLE
Documentation formatting issue in pdf

### ISSUE THREAD

**Issue by caseypatrickdriscoll** [sebastianbergmann/phpunit#1643]
The formatting in page 23 is slightly off, columns are shifted one over.

All other pages seem fine. Thanks for such a great resource!

https://phpunit.de/manual/current/en/phpunit-book.pdf

http://i.imgur.com/bfoytjz.png

**Comment by henriquemoody** [comment]
I think it's probably better you create an issue on https://github.com/sebastianbergmann/phpunit-documentation

**Comment by caseypatrickdriscoll** [comment]
TIL thanks
