### ISSUE TITLE
Mocks created with Instantiator fail tests when mocked class raises E_NOTICE, regardless of convertNoticesToExceptions setting.

### ISSUE THREAD

**Issue by mmcnickle** [sebastianbergmann/phpunit#1645]
Version 4.2 and later use `Instantiator` for creating mocks when `disableOriginalConstructor()` is used.

If the class being mocked raises an `E_NOTICE`, an exception is raised and the test fails, regardless of the phpunit `convertNoticesToExceptions` flag. Prior to version 4.2 this was not the case.

I realise this will require a change to the Instantiator component upstream, as its custom error handler around unserialization (https://github.com/doctrine/instantiator/blob/master/src/Doctrine/Instantiator/Instantiator.php#L154-L162) is not configurable, but filing here as it's a regression in the behaviour of phpunit.

Suppressing the `E_NOTICE` in Instantiator's custom error handler allows the test to pass.

`phpunit.xml`
````xml
<phpunit convertNoticesToExceptions="false"></phpunit>
````

`NoticeTestCase.php`
````php
<?php

include 'NoticeClass.php';

class NoticeClassTestCase extends PHPUnit_Framework_TestCase {

	public function testMockNoticeClass() {
		$mock = $this->getMockBuilder('\NoticeClass')
			->disableOriginalConstructor()
			->getMock();
	}

}
````

`NoticeClass.php`

````php
<?php

class NoticeClass {

	protected $params = array(
		bad_key => 1,
		'good_key' => 2
	);

}
````

Test output (*v.4.5.0*)
````
❯ vendor/bin/phpunit NoticeTestCase.php 
PHPUnit 4.5.0 by Sebastian Bergmann and contributors.

Configuration read from /vagrant/tests/phpunit.xml

E

Time: 40 ms, Memory: 7.00Mb

There was 1 error:

1) NoticeClassTestCase::testMockNoticeClass
PHPUnit_Framework_MockObject_RuntimeException: Use of undefined constant bad_key - assumed 'bad_key'

/vagrant/tests/NoticeTestCase.php:10

FAILURES!
Tests: 1, Assertions: 0, Errors: 1.
````

Test output (*v4.1.6*)
````
❯ phpunit NoticeTestCase.php 
PHPUnit 4.1.6 by Sebastian Bergmann.

Configuration read from /vagrant/tests/phpunit.xml

.

Time: 4 ms, Memory: 6.75Mb

OK (1 test, 0 assertions)
````

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md) have been reported on the [phpunit-mock-objects](https://github.com/sebastianbergmann/phpunit-mock-objects) project instead.
