### ISSUE TITLE
Support to set a value to a protected property of a class

### ISSUE THREAD

**Issue by sandrokeil** [sebastianbergmann/phpunit#1646]
To initialize some properties to test a method I must use the \ReflectionClass in my PHPUnit test case like this:

```php
$values = array('test value');

$reflectionClass = new \ReflectionClass('My\Class\To\Test');

$reflectionProperty = $reflectionClass->getProperty('protectedPropertyName');
$reflectionProperty->setAccessible(true);
$reflectionProperty->setValue($mockObject, $values);

// other test stuff
```

It would be better if I can use something like this in PHPUnit and PHPUnit handles the code above.

```php
$this->setObjectAttribute($mockObject, $reflectionClass, 'protectedPropertyName', $values);
```

`$reflectionClass` can be a `\ReflectionClass` object or a FCQN. Is this useful for the PHPUnit core so I can create a pull request?

**Comment by sandrokeil** [comment]
Any thoughts? ping @sebastianbergmann

**Comment by shochdoerfer** [comment]
Would love to see this functionality added to PHPUnit. Just run into a similar issue where I needed to set protected property before executing the method to test.

**Comment by samsonasik** [comment]
+1

**Comment by sebastianbergmann** [comment]
Same argument as for https://github.com/sebastianbergmann/phpunit/issues/1647#issuecomment-113370156.

**Comment by sebastianbergmann** [comment]
Maybe https://github.com/sebastianbergmann/peek-and-poke makes what you want to do convenient (enough).
