### ISSUE TITLE
Support to invoke protected methods

### ISSUE THREAD

**Issue by sandrokeil** [sebastianbergmann/phpunit#1647]
I know it is not necessary to test protected methods explicitly, but I have some use cases, e.g. for complex protected methods where I want to do this. To test a protected method I must use the \ReflectionClass in my PHPUnit test case like this:

```php
$reflectionClass = new \ReflectionClass('My\Class\To\Test');

$reflectionMethod = $reflectionClass->getMethod('protectedMethodName');
$reflectionMethod->setAccessible(true);

$result = $reflectionMethod->invoke($mockObject, $param1, $param2);

// other test stuff
```

It would be better if I can use something like this in PHPUnit and PHPUnit handles the code above.

```php
$result = $this->invokeMethod($mockObject, $reflectionClass, 'protectedMethodName', $param1, $param2);
```

`$reflectionClass` can be a `\ReflectionClass` object or a FCQN. Is this useful for the PHPUnit core so I can create a pull request?

**Comment by sandrokeil** [comment]
Any thoughts? ping @sebastianbergmann

**Comment by sebastianbergmann** [comment]
It's bad enough that PHPUnit makes it convenient to access non-public attributes. Sorry, but no.

**Comment by sebastianbergmann** [comment]
Maybe https://github.com/sebastianbergmann/peek-and-poke makes what you want to do convenient (enough).

**Comment by sandrokeil** [comment]
Looks interesting. Thank you.

**Comment by githoober** [comment]
I need to both to mock an object and set one of its internal properties, how can I achieve this with Peek and Poke? Not possible. An only option left is to use Reflection every time there is a need like this. 

What is a more detailed argument against what is proposed in this PR?

**Comment by sandrokeil** [comment]
@githoober Peek and Poke works fine for this. Create the mock and inject it to the proxy like this:

```php

$stub = $this->getMock('Your Test Class');
// mock your methods

$proxy = new Proxy($stub);
$proxy->property = 2;

```

**Comment by afilina** [comment]
peek-and-poke requires PHP 5.6. Are there any alternatives for PHP 5.3?

**Comment by sandrokeil** [comment]
@afilina You can make copy and paste or you [disable the composer platforms checks](https://getcomposer.org/doc/03-cli.md#options).

**Comment by sebastianbergmann** [comment]
Sorry, Anna, but with the exception of PHPUnit 4.8 and its required dependencies I do not support PHP versions anymore that are not supported by the PHP project.

**Comment by afilina** [comment]
@sebastianbergmann No worries. I made my own quick and dirty alternative, as explained here: http://afilina.com/testing-methods-that-make-static-calls/
