### ISSUE TITLE
how to use verifyAllButtons function?

### ISSUE THREAD

**Issue by xu-lei** [sebastianbergmann/phpunit#1650]
when i use the verifyAllButtons function,I encountered a trouble:
Argument #2 (No Value) of PHPUnit_Framework_Assert::assertRegExp() must be a string

Caused by
PHPUnit_Framework_Exception: Argument #2 (No Value) of PHPUnit_Framework_Assert::assertRegExp() must be a string

function $this->getAllButtons(); return value is array,wether i have a wrong way?

e.g:$this->verifyAllButtons('su');

**Comment by sebastianbergmann** [comment]
Sounds like it should be filed at https://github.com/giorgiosironi/phpunit-selenium/issues
