### ISSUE TITLE
PHPUnit unable to find class

### ISSUE THREAD

**Issue by Baachi** [sebastianbergmann/phpunit#1651]
Hey guys, 

i discovered a bug in the phpunit mocking library. i was trying to mock the class `Doctrine\ODM\MongoDB\Mapping\ClassMetadata` but phpunit says `PHPUnit_Framework_MockObject_RuntimeException: Class  does not exist`.

Please note that this bug only occurs in php 5.3. 

Here is the travis build https://travis-ci.org/ddeboer/data-import/builds/47457455 and the PR which shows the bug https://github.com/ddeboer/data-import/pull/83.

**Comment by Baachi** [comment]
ping @sebastianbergmann @edorian

**Comment by smilesrg** [comment]
+1 for resolving this one!

**Comment by sebastianbergmann** [comment]
Tickets for the PHPUnit's mocking library must be created at https://github.com/sebastianbergmann/phpunit-mock-objects/issues

Please open a new ticket there that contains a minimal, self-contained, reproducing example.
