### ISSUE TITLE
Mock + enableProxyingToOriginalMethods + default constructor

### ISSUE THREAD

**Issue by lyrixx** [sebastianbergmann/phpunit#1652]
* When I subclass a PHP class that is defined via C
* And I override the `__construct` method
* And I call `$this->aMethod` in it
* And I mock it
* And I proxy it

Then I got an error:

```
>(9)[{..}greg/dev/debug/phpunit-proxy-amqp](master) phpunit  ExchangeTest.php
PHPUnit 4.5.0 by Sebastian Bergmann and contributors.

Configuration read from /home/greg/dev/debug/phpunit-proxy-amqp/phpunit.xml.dist

E

Time: 77 ms, Memory: 4.25Mb

There was 1 error:

1) ExchangeTest::testWeird
call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object

/home/greg/dev/debug/phpunit-proxy-amqp/Exchange.php:9
/home/greg/dev/debug/phpunit-proxy-amqp/ExchangeTest.php:26
/home/greg/dev/github.com/sebastianbergmann/phpunit/src/TextUI/Command.php:151
/home/greg/dev/github.com/sebastianbergmann/phpunit/src/TextUI/Command.php:103

FAILURES!
Tests: 1, Assertions: 0, Errors: 1.
```

**Note:** I extracted all code into a gist: https://gist.github.com/lyrixx/c943e7e046ec325308fa#file-readme-md

**Comment by lyrixx** [comment]
BTW, If I replace `$this->setName($name)`,  by `parent::setName($name)`; everything works as expected...
But obviously, I would not replace my code

**Comment by sebastianbergmann** [comment]
Mocking issues with C-defined classes usually stem from the fact that not (good (enough)) information is exposed via the Reflection API. This would make it an issue for the vendor of the extension that defines the class.

Please note that this [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md) have been reported on the [phpunit-mock-objects](https://github.com/sebastianbergmann/phpunit-mock-objects) project instead.

**Comment by XedinUnknown** [comment]
I was func-testing concretes, and didn't need to mock any methods, so instead of enabling proxying to original methods, I set the mocked methods to `null`, and it worked.
