### ISSUE TITLE
PHP Fatal error:  Call to undefined method PHPUnit_TextUI_ResultPrinter::addPossibleProblem() in Framework/TestResult.php on line 234

### ISSUE THREAD

**Issue by ribeiropaulor** [sebastianbergmann/phpunit#1653]
I'm using the new integration with Prophecy and, for some kind of errors in my tests, I'm getting this error message. 

The problem is that PHPUnit does not show the original problem. It seems to be a problem in the PHPUnit itself.

**Comment by sebastianbergmann** [comment]
The string `addPossibleProblem` does not occur in either PHPUnit's sourcecode nor in the sourcecode of any of its dependencies.
