### ISSUE TITLE
Failed asserting that two arrays are equal but shows no difference.

### ISSUE THREAD

**Issue by h0gar** [sebastianbergmann/phpunit#1654]
Here is what phpunit tells me:

    1) Asgard\Entity\Tests\EntityTest::testToArray
    Failed asserting that two arrays are equal.
    --- Expected
    +++ Actual
    @@ @@
     Array (
         'id' => null
         'title' => 'Test Title'
         'content' => 'Test Content'
         'published' => 2015-03-23T20:09:18+0000
         'comments' => Array (
             0 => Array (
                 'id' => null
                 'content' => 'foo'
                 'published' => 2015-03-23T20:09:18+0000
                 'another_property' => null
                 'news' => null
             )
             1 => Array (
                 'id' => null
                 'content' => 'bar'
                 'published' => 2015-03-23T20:09:18+0000
                 'another_property' => null
                 'news' => null
             )
             2 => Array (
                 'id' => null
                 'content' => 'baz'
                 'published' => 2015-03-23T20:09:18+0000
                 'another_property' => null
                 'news' => null
             )
         )
         'another_property' => null
     )

https://travis-ci.org/asgardphp/asgard/jobs/55541604

It randomly fails on travis with PHP 5.4, 5.5 or 5.6, for no apparent reason. I haven't come accross this error on my own computer yet though.

**Comment by h0gar** [comment]
Found the issue. Elements were not in the same order in the array. It should still be shown in the output however.

**Comment by sebastianbergmann** [comment]
What should be shown in the output? Please provide a minimal, self-contained, reproducing test case along with the output you get and the output you would expect.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
