### ISSUE TITLE
Configuration Generation

### ISSUE THREAD

**Issue by patinthehat** [sebastianbergmann/phpunit#1657]
Hello fellow PHPUnit users,

As a side project, I've created a small utility that generates a simple PHPUnit configuration file.  It is still a work in progress and it has a way to go, but I wanted to share it with everyone.  **Constructive criticism and feedback are welcome.**

http://pucg.permafrostcodingstudio.com/

Thanks,
Trick

**Comment by sebastianbergmann** [comment]
This is not a forum.
