### ISSUE TITLE
Fixtures as method arguments, Yield fixtures

### ISSUE THREAD

**Issue by ghost** [sebastianbergmann/phpunit#1660]
Pytest has an awesome feature, named [fixtures as method arguments](http://pytest.org/latest/fixture.html#fixtures-as-function-arguments). It would be great to have this feature in phpunit.

For example:

``` php
class DispatcherTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @fixture
     */
    public function dispatcher()
    {
        return new Dispatcher();
    }

    public function testDispatch(DispatcherInterface $dispatcher)
    {
        $dispatcher->dispatch(new Event());
        // ...
    }

    public function testAttachAndDetach(DispatcherInterface $dispatcher)
    {
        $subscriber = new Subscriber();
        $dispatcher->attach($subscriber);
        $dispatcher->detach($subscriber);
        // ...
    }
}

```

**Comment by Kilte** [comment]
And there is [yield fixtures](http://pytest.org/latest/yieldfixture.html).

**Comment by sebastianbergmann** [comment]
Looks to me like a special case of what data providers offer.

**Comment by Kilte** [comment]
Yes, this is very similar, but not very comfortable when you need to retrieve object only.
Of course I can just call a method or get an object from a property. Perhaps in this case it is not necessary to implement it.

> A data provider method must be public and either return an array of arrays or an object that implements the Iterator interface and yields an array for each iteration step. 

What about yield fixtures?

**Comment by sebastianbergmann** [comment]
I am not convinced enough of the usefulness of this feature to implement it myself. I will, however, consider a pull request.
