### ISSUE TITLE
phpunit slow when using code coverage

### ISSUE THREAD

**Issue by davidsoderberg** [sebastianbergmann/phpunit#1662]
Hi, why are phpunit running so slow when I add code coverage?

Without coverage: 10.65 seconds, 33 tests.
With coverage: 8.37 minutes, 33 tests.

Thanks for a great test framework :smile:

**Comment by GrahamCampbell** [comment]
Duplicate.

**Comment by GrahamCampbell** [comment]
https://github.com/sebastianbergmann/phpunit/issues/1456

**Comment by sebastianbergmann** [comment]
PHPUnit uses PHP_CodeCoverage to process code coverage data that is collected using Xdebug. Collecting code coverage data slows down program execution (usually, though, not as extreme as in your case).

You are not providing any information on the platform you are running PHPUnit on nor on the versions of PHP, PHPUnit, or Xdebug used. Without more information there is nothing we can do to help you.

**Comment by kaplun** [comment]
Hi! We are experiencing similar issues with this system configuration: 

PHP 7.2.6, XDebug v2.6.0, PHPUnit 7.2.3, and with processIsolation="false".

**Comment by keradus** [comment]
Running anything with xdebug is extremely slow.
want to speed it up?
1. drop xdebug in favor of phpdbr, way faster
2. add `@covers` annotations, so given test will collect coverage only what you intend to test, not from every single src code that was executed by given test

Some real numbers from PHP CS Fixer project:
![coverage](https://user-images.githubusercontent.com/2716794/42848323-66fba99c-8a1f-11e8-871f-4d73e66e7f6f.png)
