### ISSUE TITLE
Fatal error:  Cannot redeclare any() (PHPUnit 4.6.1 and PHP 7.0.0)

### ISSUE THREAD

**Issue by davletshin** [sebastianbergmann/phpunit#1666]
I tried to use the **PHPUnit 4.6.1** with **PHP 7.0.0**, but got the following error.

**PHP Fatal error:**  Cannot redeclare any() (previously declared in phar:///home/travis/.phpenv/versions/nightly/bin/phpunit/phpunit/Framework/Assert/Functions.php:21) in /home/travis/build/php-lab/event/vendor/phpunit/phpunit/src/Framework/Assert/Functions.php on line 24

Detailed report:
https://travis-ci.org/php-lab/event/jobs/57151378
![2015-04-04-182853_1366x768_scrot-1](https://cloud.githubusercontent.com/assets/4481981/6993308/e722788c-daf8-11e4-9283-a8f23fdfc781.png)

**Comment by sebastianbergmann** [comment]
Looks like `src/Framework/Assert/Functions.php` is included more than once.

**Comment by davletshin** [comment]
I don’t load `src/Framework/Assert/Functions.php` in my bootstrap script:
https://github.com/php-lab/event/blob/master/tests/bootstrap.php
```php
<?php
$loader = require __DIR__.'/../vendor/autoload.php';
```

**Comment by davletshin** [comment]
The error occurs only in conjunction **PHPUnit 4.6.1** and **PHP 7.0.0**.
https://travis-ci.org/php-lab/event/builds/57151372
![2015-04-04-194230_1366x768_scrot-1](https://cloud.githubusercontent.com/assets/4481981/6993638/670f4ca0-db03-11e4-86c8-c8d81c8ce79c.png)

**Comment by sebastianbergmann** [comment]
I cannot reproduce this:

    $ git remote -v
    origin	git@github.com:php-lab/event.git (fetch)
    origin	git@github.com:php-lab/event.git (push)


    $ git status   
    HEAD detached at 8ca0a1f
    nothing to commit, working directory clean


    $ /usr/local/php-7.0/bin/php --version
    PHP 7.0.0-dev (cli) (built: Apr  4 2015 19:24:55) (DEBUG)
    Copyright (c) 1997-2015 The PHP Group
    Zend Engine v3.0.0-dev, Copyright (c) 1998-2015 Zend Technologies


    $ /usr/local/php-7.0/bin/php vendor/bin/phpunit
    PHPUnit 4.6.1 by Sebastian Bergmann and contributors.

    Configuration read from /home/sb/event/phpunit.xml.dist

    ..........

    Time: 51 ms, Memory: 4.00Mb

    OK (10 tests, 40 assertions)

Maybe @travis-ci's PHP 7 environment is wonky.

**Comment by davletshin** [comment]
I'll be trying to test this error tomorrow and the following day.
Maybe @travis-ci will upgrade PHP 7 environment.

**Comment by marcioAlmada** [comment]
I've this before with other libraries. If you install a given composer package with `composer global install` and this same package is a local dependency from a project, composer tries to include files twice.

Not sure if it's the case here, but if so we might be dealing with a composer bug.

**Comment by sebastianbergmann** [comment]
ping @Seldaek

**Comment by Seldaek** [comment]
If you install phpunit as a local dependency you probably should run it as vendor/bin/phpunit and not from the globally installed  one yeah otherwise you might have conflicts since the travis phpunit will load that functions file and then your bootstrap loads composer's autoloader which will load the locally installed phpunit's functions file.

**Comment by kailam77** [comment]
The build/phar-autoload.php.in file changed with v 4.6.0 to include this line:
require __PHPUNIT_PHAR_ROOT__ . '/phpunit/Framework/Assert/Functions.php';

This loads a slew of functions in the global namespace which may collide with others in your codebase of other libraries.  This just happened to me and I had to fix on version 4.5.1 until we have time to clean up our global functions to avoid collisions.

**Comment by sebastianbergmann** [comment]
What @kailam77 wrote in https://github.com/sebastianbergmann/phpunit/issues/1666#issuecomment-89897910 I already wrote in https://github.com/sebastianbergmann/phpunit/issues/1666#issuecomment-89603625 (and since then in https://github.com/sebastianbergmann/phpunit/wiki/Release-Announcement-for-PHPUnit-4.6.0).

**Comment by marcioAlmada** [comment]
@Seldaek @sebastianbergmann thanks for clarifying this.

I've been watching several analogous issues across different libraries and these issues are not related to composer itself but to PHP not having a proper functional autoloading mechanism in place. Hopefully there will probably be a new version of the [function_autoloading](https://wiki.php.net/rfc/function_autoloading) RFC targeting PHP 7.1.
