### ISSUE TITLE
Global Functions are now loaded automatically, causing collisions

### ISSUE THREAD

**Issue by kailam77** [sebastianbergmann/phpunit#1667]
The build/phar-autoload.php.in file changed with v 4.6.0 to include this line:
require __PHPUNIT_PHAR_ROOT__ . '/phpunit/Framework/Assert/Functions.php';

This loads a slew of functions in the global namespace which may collide with others in the codebase or other libraries.  Running composer update effectively broke our ability to test since functions like 'fileExists' are declared in Functions.php and also in our code base.

We have to fix on version 4.5.1 until we have time to clean up our global functions to avoid collisions.  These functions have always been there, but were apparently not loaded automatically before 4.6.0.  If this could be reverted to the previous behavior, it would save a lot of headaches.

**Comment by sebastianbergmann** [comment]
I do not like `Framework/Assert/Functions.php` but there are many developers out there that do. To make their life easier, especially when they are using the PHAR distribution of PHPUnit, this change was made. At this point I do not think it's likely to be reverted.

**Comment by thunderer** [comment]
PHP7 build of one of my libraries failed due to error that seems related. Any comment on that? https://travis-ci.org/thunderer/Shortcode/jobs/57328462

**Comment by sebastianbergmann** [comment]
This has nothing to do with PHP 7.

**Comment by winkbrace** [comment]
When using Mockery, which loads Hamcrest, there is now a collision on the any() function (and maybe more?). This doesn't strike me as an uncommon combination, so a namespaced solution or at least a nesting of function_exists() would be much appreciated.

**Comment by sebastianbergmann** [comment]
Fixed in PHPUnit 4.6.2.

**Comment by winkbrace** [comment]
Thank you :)

**Comment by kailam77** [comment]
Great!  Thanks so much.
