### ISSUE TITLE
Idea/Question: Attachable & inheritable tests

### ISSUE THREAD

**Issue by castarco** [sebastianbergmann/phpunit#1668]
Hello, I'm wondering if it's possible to discuss here with you a "strange" idea about "special" tests.

My idea is to "attach" tests to some classes in order to automatically execute those attached tests on their subclasses, without having to explicitly code it.

Since I'm working on implementing a mathematical/theoretical library, I'll expose a use case of this feature:

Suppose we have classes called Function, Operation, Group, and Ring (and many subclasses of the previous classes). There are mathematical properties of Groups and Rings that can't be enforced with interfaces or abstract classes, but can be checked (at least in part) in "compile time" (I know PHP isn't compiled, but the idea is that the code provides enough information to know if the mathematical property is preserved without having to check it every time the code is executed).

For example, PHP hasn't self-types ( see http://cstheory.stackexchange.com/questions/20032/is-there-a-language-with-strong-typed-interfaces-where-types-resolution-are-del/20033 ), but it can be checked that the "operations" of a group or of a ring return values of the same group or ring (returning a Group instance isn't enough since we have virtually infinite Group subclasses, and returning elements of the same group or ring is part of the mathematical definition of such abstractions).

Apart from the "self-type" problem, there are other interesting use cases. Is it possible to develop a PHPUnit plugin or something similar to implement something like this? Anyone have any idea, correction or doubt about what i proposed?

I though on something like creating the following annotation (this should also be aplicable to interfaces and traits):

```php
/**
 * @forceTestOnSubclasses InheritableTest_A, InheritableTest_B
 */
class superclass { /*...*/ }

/**
 * The InheritableTest_A will be executed on this class,
 * and also the InheritableTest_B.
 */
class subclass extends superclass { /* ... */ }

class InheritableTest_A extends PHPUnit_Inheritable_TestCase
{
    // inherits the protected property $superclassName from PHPUnit_Inheritable_TestCase
    // inherits the protected property $subclassName from PHPUnit_Inheritable_TestCase

    // overrides an empty property from PHPUnit_Inheritable_TestCase,
    // used to construct the subclass instances used in the test
    protected $instanceParams = [
        // used to construct the "instance1" subclass instance.
        // call to subclass constructor with "p1",..."pn" as parameters
        "instance1" => [null, "p1", "...", "pn"],
        
        // used to construct the "instance2" subclass instance.
        // call to the sMethod static method with "p1",..."pn" as parameters
        "instance2" => ["sMethod", "p1", "...", "pn"]
    ];

    public function testSimpleProperty ()
    {
        // The "instance" objects are created per every test to ensure isolation.
        $this->assertTrue(check_property($this->subclassInstance("instance1")));
        $this->assertTrue(check_property($this->subclassInstance("instance2")));
    }
}

```

where `InheritableTest` should have a way to construct objects given the subclass, probably via common and shared static interfaces (this will need reflection), or maybe via constructors with shared common signatures.

Those tests on subclasses may be executed at the end of the typical testing process, when we have a list of loaded classes and we can infer inheritance relations in order to check which classes need to pass the "inherited tests".

I would prefer to adding the "inheritable/attached tests" features directly in PHPUnit rather than creating a plugin, but I'm not sure if this idea we'll be accepted.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
