### ISSUE TITLE
Add merge option to phpunit.xml configuration

### ISSUE THREAD

**Issue by havvg** [sebastianbergmann/phpunit#167]
# Behavior

**Given** there is a phpunit.xml.dist<br />
**And** there is a phpunit.xml<br />
**When** the phpunit.xml is set to merge changes<br />
**Then** all changes between phpunit.xml and phpunit.xml.dist should be merged into result configuration

# Goal

The goal to achieve with this enhancement: remove the need to update the phpunit.xml every time the phpunit.xml.dist changes e.g. by adding new testsuites.

# Example

## phpunit.xml.dist

    <?xml version="1.0" encoding="UTF-8"?>
    <phpunit
      colors="false"
      convertErrorsToExceptions="true"
      convertNoticesToExceptions="true"
      convertWarningsToExceptions="true"
      stopOnFailure="true">
    
      <filter>
        <blacklist>
          <directory>config</directory>
          <file>*.yml</file>
        </blacklist>
      </filter>
    
      <testsuites>
        <testsuite name="Unit Tests">
          <directory>test/unit/</directory>
        </testsuite>
      </testsuites>
    </phpunit>

## phpunit.xml

    <?xml version="1.0" encoding="UTF-8"?>
    <phpunit merge="true" colors="true">
      <logging>
        <log type="coverage-html" target="./web/coverage" charset="UTF-8" yui="false" highlight="true" lowUpperBound="65" highLowerBound="85"/>
      </logging>
    </phpunit>

## result configuration to use

    <?xml version="1.0" encoding="UTF-8"?>
    <phpunit
      colors="true"
      convertErrorsToExceptions="true"
      convertNoticesToExceptions="true"
      convertWarningsToExceptions="true"
      stopOnFailure="true">
        
      <filter>
        <blacklist>
          <directory>config</directory>
          <file>*.yml</file>
        </blacklist>
      </filter>
    
      <testsuites>
        <testsuite name="Unit Tests">
          <directory>test/unit/</directory>
        </testsuite>
      </testsuites>
    
      <logging>
        <log type="coverage-html" target="./web/coverage" charset="UTF-8" yui="false" highlight="true" lowUpperBound="65" highLowerBound="85"/>
      </logging>
    </phpunit>

**Comment by ryanneufeld** [comment]
Can you provide an example, or link to the docs for this? I've been trying to get it working, but it doesn't seem to be working for me.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
