### ISSUE TITLE
How to use @requires extension with special name

### ISSUE THREAD

**Issue by llaville** [sebastianbergmann/phpunit#1672]
While test case with extension (without blank char in name) works like a charm when extension is not loaded.
E.g:

```php
<?php
/**
 * @requires   extension amqp
 */
class AmqpExtensionTest extends PHPUnit_Framework_TestCase
{
}
```

I've a problem with the `Zend OpCache` extension.
How do I specify it ?

I've tried two syntaxt without success 

```
/**
 * @requires   extension zend opcache
 */
```
or 
```
/**
 * @requires   extension "zend opcache"
 */
```

**Comment by thunderer** [comment]
[This line](https://github.com/sebastianbergmann/phpunit/blob/master/src/Util/Test.php#L35) contains regular expression used to extract extension name, it accepts only first non-whitespace characters fragment so it matches only `Zend`. You can hotfix it by [changing named match](https://www.debuggex.com/r/TWQsy1td_Abc4Gkh) <value> from `[^ ]` to `[^\r]+` and use the extension name reported by `php -m`. I'll work on a PR for that.

**Comment by llaville** [comment]
@thunderer Thanks Tomasz : nice catch. I confirm it's works fine. 

CC @sebastianbergmann perharps this fix may be planned in next bug fixe release 4.6.7 ?

**Comment by sebastianbergmann** [comment]
TBH, I'd rather not change PHPUnit for such an edge case. Why not simply check whether the extension is loaded in the test method and call `markTestSkipped()` when it's not?

**Comment by llaville** [comment]
TBH me too, if I can't use `@requires extension` even with a such probably error in extension naming "Zend OPcache", I won't used it at all. 
Of course checking if extension  is loaded is an alternative and I already used it in first attempt.
Then I switched to `@requires extension` feature, and found this issue.

On `@requires` usage I recommand you to have a check on issue #1679

**Comment by thunderer** [comment]
@sebastianbergmann This is only a regex change to correctly match function / extension name because current implementation accepts only first non-whitespace fragment and ignores the rest (which can be considered a bug IMHO). I can implement it so that it'll accept `\w+` or `"[\w\s]+"` or even `[^\r]` as I wrote above, so that only alphanumeric value, alphanumeric with spaces enclosed in quotes value or anything up to line end will be matched. I'll add proper tests cases to catch any inconsistencies. Will you accept such PR? If so, which regex variant would you prefer?

**Comment by sebastianbergmann** [comment]
@thunderer Please send a pull request against `4.7`. Thanks.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
