### ISSUE TITLE
How to pass global variables assigned in the XML configuration to tests running in separate process

### ISSUE THREAD

**Issue by uwetews** [sebastianbergmann/phpunit#1673]
I have some configuration parameters assigned in the XML configuration. like
<var name="foo" value="bar"/>

If I run test in a separate process not preserving global state like
    /**
     * @runInSeparateProcess
     * @preserveGlobalState disabled
     */
    public function testInSeparateProcess()
    {
        // ...
    }

the global variables are unassigned.

Is there any way to get custom parameters from XML passed to the separate process?

**Comment by sebastianbergmann** [comment]
Not enough information, closing.
