### ISSUE TITLE
Global function conflicts in master branch

### ISSUE THREAD

**Issue by padraic** [sebastianbergmann/phpunit#1675]
As changed here: https://github.com/sebastianbergmann/phpunit/pull/1625 and impacting here: https://github.com/padraic/mockery/issues/464

There is a change to composer.json switching the loading of the global functions from autoload-dev to autoload. This would appear to create conflicts with Hamcrest which likewise defines similar functions, though only after a definition pre-check, so the problem would arise where Hamcrest is loaded prior to PHPUnit based on whatever wizardry in setting priorities for file loading is employed by Composer.

**Comment by sebastianbergmann** [comment]
#1625 has since been reverted.
