### ISSUE TITLE
[Composer] "bin-dir" required or considered harmful?

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#1676]
PHPUnit's `composer.json` file has the following

```json
"config": {
    "bin-dir": "bin"
},
```
(see https://github.com/sebastianbergmann/phpunit/blob/master/composer.json#L51) and I am wondering whether 1) this is required and 2) if it's not whether it's harmful. PHPUnit's repository does not have a `bin` directory.

CC @seldaek

**Comment by Seldaek** [comment]
@sebastianbergmann all this does is tell composer that your dependencie's binaries should be set up in ./bin vs the default of ./vendor/bin. So it's not an issue if it doesn't exist (it will be created, but it probably should be in .gitignore then), and it's not harmful, but maybe it's useless :)

Note that this is a root-only field so has no effect on people requiring phpunit.

**Comment by sebastianbergmann** [comment]
Thanks, @Seldaek. I shall remove it then.
