### ISSUE TITLE
createMySQLXMLDataSet memory consumption

### ISSUE THREAD

**Issue by klevin** [sebastianbergmann/phpunit#1678]
I realize that XML parsing can consume a bit of memory, but 710MB & 5.85 min run time to load a 51MB file generated by mysqldump --xml? That seems excessive.

This is running on an Arch Linux 64-bit system, php v5.6.7 and the PHPUnit v4.6.2 phar.

**Comment by sebastianbergmann** [comment]
Please report DbUnit related issues at https://github.com/sebastianbergmann/dbunit/issues
