### ISSUE TITLE
@requires extension did not provide fully qualified test names

### ISSUE THREAD

**Issue by llaville** [sebastianbergmann/phpunit#1679]
Consider, for example, the test suite on APC cache driver of Doctrine :  https://github.com/doctrine/cache/blob/master/tests/Doctrine/Tests/Common/Cache/ApcCacheTest.php

Actually if, extension apc is not loaded, with the current code implementation ( without `@requires extension apc` ), if we run the test suite in debug mode, we get somethink like 

    Starting test 'Doctrine\Tests\Common\Cache\ApcCacheTest::testBasicCrudOperations with data set "array" (array('one', 2,
    3.0))'.
    S
    Starting test 'Doctrine\Tests\Common\Cache\ApcCacheTest::testBasicCrudOperations with data set "string" ('value')'.
    S
    Starting test 'Doctrine\Tests\Common\Cache\ApcCacheTest::testBasicCrudOperations with data set "integer" (1)'.
    S
    Starting test 'Doctrine\Tests\Common\Cache\ApcCacheTest::testBasicCrudOperations with data set "float" (1.5)'.
    S
    Starting test 'Doctrine\Tests\Common\Cache\ApcCacheTest::testBasicCrudOperations with data set "object" (ArrayObject Object ())'.
    S
    Starting test 'Doctrine\Tests\Common\Cache\ApcCacheTest::testBasicCrudOperations with data set "null" (null)'.
    S
    Starting test 'Doctrine\Tests\Common\Cache\ApcCacheTest::testFetchMulti'.
    S
    Starting test 'Doctrine\Tests\Common\Cache\ApcCacheTest::testFetchMultiWillFilterNonRequestedKeys'.
    S
    Starting test 'Doctrine\Tests\Common\Cache\ApcCacheTest::testDeleteAll'.
    S
    Starting test 'Doctrine\Tests\Common\Cache\ApcCacheTest::testDeleteAllAndNamespaceVersioningBetweenCaches'.
    S
    Starting test 'Doctrine\Tests\Common\Cache\ApcCacheTest::testFlushAll'.
    S
    Starting test 'Doctrine\Tests\Common\Cache\ApcCacheTest::testFlushAllAndNamespaceVersioningBetweenCaches'.
    S
    Starting test 'Doctrine\Tests\Common\Cache\ApcCacheTest::testNamespace'.
    S
    Starting test 'Doctrine\Tests\Common\Cache\ApcCacheTest::testDeleteAllNamespace'.
    S
    Starting test 'Doctrine\Tests\Common\Cache\ApcCacheTest::testGetStats'.
    S
    Starting test 'Doctrine\Tests\Common\Cache\ApcCacheTest::testFetchMissShouldReturnFalse'.
    S
    Starting test 'Doctrine\Tests\Common\Cache\ApcCacheTest::testFalseCastedValues with data set #0 (false)'.
    S
    Starting test 'Doctrine\Tests\Common\Cache\ApcCacheTest::testFalseCastedValues with data set #1 (null)'.
    S
    Starting test 'Doctrine\Tests\Common\Cache\ApcCacheTest::testFalseCastedValues with data set #2 (array())'.
    S
    Starting test 'Doctrine\Tests\Common\Cache\ApcCacheTest::testFalseCastedValues with data set #3 ('0')'.
    S
    Starting test 'Doctrine\Tests\Common\Cache\ApcCacheTest::testFalseCastedValues with data set #4 (0)'.
    S
    Starting test 'Doctrine\Tests\Common\Cache\ApcCacheTest::testFalseCastedValues with data set #5 (0.0)'.
    S
    Starting test 'Doctrine\Tests\Common\Cache\ApcCacheTest::testFalseCastedValues with data set #6 ('')'.
    S

That is very easy to see what tests were skipped !

Now consider the same code, and replace the `ApcCacheTest::setUp()` by annotation like 

```php 
<?php

/**
 * @requires extension apc
 */
class ApcCacheTest extends CacheTest
{
} 
```
An run the test suite again. You will get all 23 tests with the same results 

    Starting test 'Doctrine\Tests\Common\Cache\ApcCacheTest'.
    S

Difficult in such condition to see what tests are skipped. Right ?

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
