### ISSUE TITLE
Testing SoapFault: unexpected PHP Fatal Error (only in PHPUnit)

### ISSUE THREAD

**Issue by Geabulek** [sebastianbergmann/phpunit#1683]
Hi,
The SoapClient error behaves differently in PHPUnit.
Following code gives "Exception catched"
```php
class demoCase
{
    static public function example()
    {
        $wsdl = 'dummy.wsdl';
        $constructParam = array(
            'login'     => 'anyLogin',
            'password'  => 'anyPassword',
            'exception' => true );

        new \SoapClient($wsdl, $constructParam);
    }
}

try {
    demoCase::example();

} catch(\SoapFault $e) {
    echo 'Exception catched';
}
```

But the following unit test : 
```php
class demoCase
{
    static public function example()
    {
        $wsdl = 'dummy.wsdl';
        $constructParam = array(
            'login'     => 'anyLogin',
            'password'  => 'anyPassword',
            'exception' => true );

        new \SoapClient($wsdl, $constructParam);
    }
}

class demoCaseTest extends PHPUnit_Framework_TestCase
{
    /**
     * @expectedException \SoapFault
     */
    public function testDemoCase()
    {
        //throw new \SoapFault('MEssae',1);
        demoCase::example();
    }
}
```

gives 
```
λ phpunit --no-configuration ./demoSoapFaultTest.php
PHPUnit 4.6.4 by Sebastian Bergmann and contributors.

PHP Fatal error:  SOAP-ERROR: Parsing WSDL: Couldn't load from 'dummy.wsdl' : failed to load external entity "dummy.wsdl"
 in C:\Users\Alexandre\www\TutoTU\tests\demoSoapFaultTest.php on line 13
.

Time: 398 ms, Memory: 9.25Mb

OK (1 test, 1 assertion)
```

The PHP Fatal error is not expected and I don't think it is a normal behaviour. 

Appart from a very old issue here (http://osdir.com/ml/php.phpunit.devel/2008-03/msg00007.html) I did not find any reference on Google.

I could silent php error with an @ but I don't think this would be a good idea for the actual production code.

Thanks for your input,
BR, 
Geabulek

**Comment by Geabulek** [comment]
Additionnaly, when writing a unit test case when communication details are not OK, code executed by PHPUnit triggers Exceptions while code executed in browser triggers SoapFault exception.
I am rather intrigued.

**Comment by sebastianbergmann** [comment]
This does not look like a PHPUnit issue, closing.

**Comment by Geabulek** [comment]
Hi, 
From a logical point of view it could be either (1) PHP that does not throw the expected exception when executed during PHPunit runtime or (2) PHPunit that does not catch this exception.

Shall I understand that you rule out the latter (2) and I should open an issue at PHP for the former (1)?

BR
