### ISSUE TITLE
Unbundle PHPUnit_Selenium

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#1686]
* [PHPUnit_Selenium](https://github.com/giorgiosironi/phpunit-selenium/) is currently bundled in the PHAR distribution of PHPUnit
* PHPUnit's XML configuration file has settings for PHPUnit_Selenium
* PHPUnit_Selenium has its own chapter in the PHPUnit documentation

The above made sense in a time where alternative PHP clients for Webdriver (or Selenium) did not exist or were hard to use with PHPUnit. Thanks to Facebook's [php-webdriver](https://github.com/facebook/php-webdriver), for instance, that is no longer the case.

I propose to "end the special treatment" for PHPUnit_Selenium and
* no longer bundle it in the PHAR distribution of PHPUnit,
* remove support for its configuration settings from PHPUnit,
* and remove its chapter from PHPUnit's documentation.

CC @giorgiosironi

**Comment by giorgiosironi** [comment]
Ah, didn't know it was included in the Phar as the main installation method is Composer.
How can an extension accept configuration settings in a generic way from the phpunit.xml? Or should it create a separate file?

**Comment by sebastianbergmann** [comment]
When the generic ways (constants, global variables) are not good enough then, I think, it would be best to go with a separate file.

**Comment by naptoon** [comment]
We use phpunit version 5.0 (phar) and in case when a test fails phpunit delivers a large stack trace and an error that tha selenium class can not be found.

**Comment by sebastianbergmann** [comment]
@naptoon Please open a new ticket for this with the complete stacktrace.
