### ISSUE TITLE
PharException - Broken signature installing PHPUnit

### ISSUE THREAD

**Issue by dam660** [sebastianbergmann/phpunit#1694]
Hm I can't find any subject talking about my problem..

I try to install PHPUnit (using this process: https://phpunit.de/getting-started.html) on my debian.

But nothing appears on my prompt when I type this:

php phpunit.phar --version

I add a breakpoint after "Phar::mapPhar('phpunit-4.6.4.phar');" on the phpunit.phar, line 17, ant then I got this error on my prompt:

PHP Fatal error:  Uncaught exception 'PharException' with message 'phar "/home/root-db/phpunit.phar" has a broken signature' in /home/root-db/phpunit.phar:16
Stack trace:
#0 /home/root-db/phpunit.phar(16): Phar::mapPhar('phpunit-4.6.4.p...')
#1 {main}
  thrown in /home/root-db/phpunit.phar on line 16

can you help me with this one?

Thank's in advance!

**Comment by sebastianbergmann** [comment]
Duplicate of #1688

**Comment by sebastianbergmann** [comment]
Do you have Suhosin enabled? If so, please have a look at https://phpunit.de/manual/current/en/installation.html#installation.phar

**Comment by dam660** [comment]
Hm didn't know that I have Suhosin enabled on this server, this solves my problem.
Really thank you!

**Comment by sebastianbergmann** [comment]
AFAIK it is enabled by default on Debian.
