### ISSUE TITLE
--verbose is more verbose than --debug

### ISSUE THREAD

**Issue by llaville** [sebastianbergmann/phpunit#1703]
To see behavior in context, consider to use example about dataprovider in current  phpunit manual, with a little add-on : a conditional  test resource   

```php
<?php
class DataTest extends PHPUnit_Framework_TestCase
{
    /**
     * @dataProvider additionProvider
     */
    public function testAdd($a, $b, $expected)
    {
        $this->assertEquals($expected, $a + $b);
    }
    
    public function additionProvider()
    {
        $res = 'Fake resource';
        
        if (true) {
            $this->markTestSkipped(
                "$res is required."
            );
        }
        
        return array(
            array(0, 0, 0),
            array(0, 1, 1),
            array(1, 0, 1),
            array(1, 1, 3)
        );
    }
}
```

On first run, use the debug mode 

    phpunit --debug DataTest.php

And have a look on output 

    PHPUnit 4.6.6 by Sebastian Bergmann and contributors.
    
    Starting test 'DataTest::testAdd'.
    S

    Time: 2.55 seconds, Memory: 2.75Mb

    OK, but incomplete, skipped, or risky tests!
    Tests: 1, Assertions: 0, Skipped: 1.

On second run, use the verbose mode (that should normally be less verbose than debug, right?)

    phpunit --verbose DataTest.php

That print something like 

    PHPUnit 4.6.6 by Sebastian Bergmann and contributors.

    S

    Time: 2.54 seconds, Memory: 2.75Mb

    There was 1 skipped test:

    1) DataTest::testAdd
    Test for DataTest::testAdd skipped by data provider
    Fake resource is required.

    OK, but incomplete, skipped, or risky tests!
    Tests: 1, Assertions: 0, Skipped: 1.

**Comment by GrahamCampbell** [comment]
PHPUnit doesn't use these words to describe levels of verbosity. "debug" means something totally different in this case. :)

**Comment by GrahamCampbell** [comment]
And the flags can be used together.

**Comment by llaville** [comment]
Thanks Graham for your answer.

Indeed, debug mode since a bit useless. I found only one occurs https://github.com/sebastianbergmann/phpunit/blob/4.6/src/TextUI/ResultPrinter.php#L480 that process what I've presented in my previous example.

In resume, use `--verbose` and never `--debug`, if you want to learn more about your unit tests suites

**Comment by GrahamCampbell** [comment]
@llaville `--debug` is useful if your test suite is crashing due to fatal php errors, and you want to locate the test that died.
