### ISSUE TITLE
Assertions mask exceptions

### ISSUE THREAD

**Issue by Bilge** [sebastianbergmann/phpunit#1709]
When an exception is thrown it is normally shown by PHPUnit. By normally, I mean when no assertions are defined. But of course, it is quite normal to define assertions. If an assertion is declared then its error message will be displayed in lieu of any other exceptions that occurred beforehand. This makes it very difficult to debug exceptions because the assertion is often not unrelated to the exception.

Exceptions should always be shown regardless of whether assertions are defined (unless the exception is explicitly expected).

**Comment by giorgiosironi** [comment]
I can't quite understand what you mean, can you post a code sample reproducing the problem?

**Comment by Bilge** [comment]
It's pretty simple. When assertions are defined in a test method, exceptions that occurred in the system under test are not shown.

**Comment by giorgiosironi** [comment]
I cannot reproduce this behavior with this code:
```
<?php

class SampleTest extends \PHPUnit_Framework_TestCase
{
    public function testExceptionsAreNotShownBecauseOfAssertions()
    {   
        some_function();
        $this->assertEquals(2, 3); 
    }   
}

function some_function()
{
    throw new InvalidArgumentException("From the System Under Test");                                                                                                   
}
```
It outputs:
```
[21:22:53][giorgio@Bipbip:~/code/phpunit]$ ./phpunit test.php 
PHPUnit 4.8-g65ae6c0 by Sebastian Bergmann and contributors.

Runtime:        PHP 5.5.9-1ubuntu4.5 with Xdebug 2.2.4
Configuration:  /home/giorgio/code/phpunit/phpunit.xml.dist

E

Time: 72 ms, Memory: 4.75Mb

There was 1 error:

1) SampleTest::testExceptionsAreNotShownBecauseOfAssertions
InvalidArgumentException: From the System Under Test

/home/giorgio/code/phpunit/test.php:14
/home/giorgio/code/phpunit/test.php:7
/home/giorgio/code/phpunit/src/Framework/TestCase.php:866
/home/giorgio/code/phpunit/src/Framework/TestCase.php:743
/home/giorgio/code/phpunit/src/Framework/TestResult.php:610
/home/giorgio/code/phpunit/src/Framework/TestCase.php:699
/home/giorgio/code/phpunit/src/Framework/TestSuite.php:731
/home/giorgio/code/phpunit/src/TextUI/TestRunner.php:430
/home/giorgio/code/phpunit/src/TextUI/Command.php:153
/home/giorgio/code/phpunit/src/TextUI/Command.php:105
```
Can you modify this code to show the problem?

**Comment by Bilge** [comment]
I would surmise that code should be sufficient to prove the point but since it does not I can only presume the issue lies elsewhere. I observed it in a Zend Framework 2 test. I did not think ZF2 was making any changes that would affect this behaviour but perhaps it was, after all.

**Comment by giorgiosironi** [comment]
This issue should probably be closed then (I don't have the rights to do so personally)
