### ISSUE TITLE
Process isolation ignores convertErrorsToExceptions="false"

### ISSUE THREAD

**Issue by beck** [sebastianbergmann/phpunit#1710]
If using a PHP environment with a deprecated config (say `magic_quotes_gpc` is on), `processIsolation` will ignore `convertErrorsToExceptions`.

To reproduce:

* enable magic quotes

* add a simple test, `$this->assertTrue(true);`.

* use `phpunit.xml`:
   ```xml
   <phpunit processIsolation="true" convertErrorsToExceptions="false">
   </phpunit>
   ```

Run test using [the above files](https://github.com/beck/sandbox/commit/eb5c887b3b48171799807f78c742c10158b8433d), get:
```
PHPUnit 4.6.6 by Sebastian Bergmann and contributors.

Configuration read from /Users/doug/Projects/sandbox/phpunit.xml

E

Time: 163 ms, Memory: 6.25Mb

There was 1 error:

1) SampleTest::testShoulAlwaysPass
PHPUnit_Framework_Exception: PHP Deprecated:  Directive 'magic_quotes_gpc' is deprecated in PHP 5.3 and greater in Unknown on line 0

Deprecated: Directive 'magic_quotes_gpc' is deprecated in PHP 5.3 and greater in Unknown on line 0

FAILURES!
Tests: 1, Assertions: 0, Errors: 1.
```

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
