### ISSUE TITLE
@uses annotation not honored in parent class

### ISSUE THREAD

**Issue by cezarykluczynski** [sebastianbergmann/phpunit#1711]
I'd like to use PHPUnit like this (with ZF2, but that's of little relevance):

```php
/**
 * @uses \SomeCommonClass
 */
abstract class TestCase extends \Zend\Test\PHPUnit\Controller\AbstractConsoleControllerTestCase {}

class SomeCommonClass {
    public static function doStuff() {}
}

class A {
    public static function stuff() {
        \SomeCommonClass::doStuff();
    }
}

class B {
    public static function stuff() {
        \SomeCommonClass::doStuff();
    }
}

class ATest extends \TestCase {
    /**
     * @covers A::stuff
     */
    public function testStuff() {
        \A::stuff();
    }
}

class BTest extends \TestCase {
    /**
     * @covers B::stuff
     */
    public function testStuff() {
        \B::stuff();
    }
}
```

But now I would get warning "This test executed code that is not listed as code to be covered or used" about ATest and BTest unintentionally covering SomeCommonClass, when checkForUnintentionallyCoveredCode="true", and the only fix seems to be this:

```php
/**
 * @uses \SomeCommonClass
 */
class ATest extends \TestCase {
    /**
     * @covers A::stuff
     */
    public function testStuff() {
        \A::stuff();
    }
}

/**
 * @uses \SomeCommonClass
 */
class BTest extends \TestCase {
    /**
     * @covers B::stuff
     */
    public function testStuff() {
        \B::stuff();
    }
}
```

Is there a way I can not define @uses in every class? Assuming that SomeCommonClass will be used every time, because it's part of application bootstrap, a lot of redundant code has to be written.

**Comment by clphillips** [comment]
I'm actually wondering the same thing. The documentation is extremely sparse with respect to **@uses**.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
