### ISSUE TITLE
Colors not displaying after changing from PHPUnit 4.1.6 to PHPUnit 4.6.6

### ISSUE THREAD

**Issue by photodude** [sebastianbergmann/phpunit#1713]
Recently changed a project from [testing with PHPUnit 4.1.6](https://travis-ci.org/joomla/joomla-cms/jobs/62381390) to [testing with PHPUnit 4.6.6](https://travis-ci.org/joomla/joomla-cms/jobs/62436833) and now the colors are no longer displaying in the Travis CI command line log.

We invoke PHPunit tests with a [XML configuration file](https://github.com/photodude/joomla-cms/blob/patch-2/travisci-phpunit.xml) with `colors="true"`. 

I have read over the [phpunit 4.6.6 documentation](https://phpunit.de/manual/current/en/appendixes.configuration.html) and change logs but I can't see a reason why the colors are suddenly not showing.

**Comment by henriquemoody** [comment]
Colors should not be displayed on non-interactive shells (like `grep --color=auto` and many others).

Luckily you can now use `--colors=always` (like `ls --color=always` and many others).

**Comment by photodude** [comment]
@henriquemoody Can you use `--colors=always` with the XML configuration file?

**Comment by henriquemoody** [comment]
No, just on CLI

**Comment by photodude** [comment]
@henriquemoody can you combine CLI `--colors=always` and an XML configuration file for colors? Maybe I've set something up wrong since I've only [gotten errors trying '--colors=always` with an XML configuration file](https://travis-ci.org/joomla/joomla-cms/jobs/62434240).

As you can see in [this example](https://travis-ci.org/joomla/joomla-cms/jobs/62381390) we had colors displaying in the non-interactive Travis CI output when we used phpunit 4.1.6. we desire that visual output to continue while using phpunit 4.6.6.

**Comment by henriquemoody** [comment]
That's because this option was introduced on 4.6 and you're using 4.5.

Also, take a look my commend: https://github.com/joomla/joomla-cms/commit/e23ec7e87dedb63ae476138b82b2e2f65d652634#commitcomment-11182584

**Comment by photodude** [comment]
@henriquemoody Thank you. using `libraries/vendor/bin/phpunit` rather than `phpunit` was the fix for the Travis CI builds. 

`colors="true"` in the XML configuration file is once again working.
