### ISSUE TITLE
assertEquals on 0 (zero) and empty string

### ISSUE THREAD

**Issue by ashleydw** [sebastianbergmann/phpunit#1717]
My understanding from the docs and these issues (like #998) are that `assertEquals` uses `==` for comparison. 

https://github.com/sebastianbergmann/phpunit/blob/master/src/Framework/Constraint/IsEqual.php#L14

However, running a test against zero and an empty string does not reflect this as the ScalarComparator converts both to strings.

https://github.com/sebastianbergmann/comparator/blob/master/src/ScalarComparator.php#L63

So the following test will fail:

```php
public function testAssertPhpUnit() {

	$this->assertTrue(false == '');
	$this->assertEquals(false, '');

	$this->assertTrue(0 == false);
	$this->assertEquals(0, false);

	$this->assertTrue(null == false);
	$this->assertEquals(null, false);

	$this->assertTrue(null == '');
	$this->assertEquals(null, '');

	$this->assertFalse(null == '0');
	$this->assertNotEquals(null, '0');
	$this->assertTrue(null == 0);
	$this->assertEquals(null, 0);

	// this will fail, as the ScalarComparator.php will convert the two variables to strings
	// making it $this->assertEquals('', '0'); which is false
	$this->assertTrue(0 == '');
	$this->assertEquals('', 0);

}
```

`Failed asserting that 0 matches expected ''.`

Is this expected? The following is true: `0 == ''`

**Comment by sebastianbergmann** [comment]
@whatthejeff Do you remember, Jeff, why you did this? I am sure there was a good reason but at first glance this does not make sense to me.

**Comment by whatthejeff** [comment]
@sebastianbergmann I think that code is from the original comparator PR (#273).

**Comment by sebastianbergmann** [comment]
So maybe @webmozart can enlighten us?

**Comment by webmozart** [comment]
The reason is that `0 == '<string>'` is `true` for any string. For example:

```php
$this->assertEquals('foobar', 0);
```

should fail (and it does), but it would succeed if we used `==`.

I personally *don't* think that an empty string should be considered equal to the integer zero. Even though that would be consistent with the behavior of `==`, I don't think this is what an average developer expects when writing a test.

**Comment by sun** [comment]
I agree with @webmozart, the behavior of native PHP comparisons is rather weird, doesn't make much sense, and isn't what I'd expect when writing tests.

---
To clarify:
```sh
$ php -r "var_dump(0 == '', '' == 0, '0' == 0, 0 == '0', 'a' == 0, 0 == 'a');"
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)

$ php -r "var_dump(1 == '', '' == 1, '1' == 1, 1 == '1', 'a' == 1, 1 == 'a');"
bool(false)
bool(false)
bool(true)
bool(true)
bool(false)
bool(false)
```

**Comment by sebastianbergmann** [comment]
Okay, so it's expected behavior. We should probably document this, though.

**Comment by starski** [comment]
```
```

**Comment by jaylon172** [comment]
@sebastianbergmann https://mariner9.github.io/UKeVAyYRwsh3Lfkm_ej2c25vZDDHjcpicPJ8TO-wHZ4PCt68VkCOa01_Ug7d/
