### ISSUE TITLE
Uncoverable Code

### ISSUE THREAD

**Issue by DasRed** [sebastianbergmann/phpunit#1720]
i have tested a class method witch contains try catch finally. Every part in the method is tested but the code coverage shows not 100%.
I reduced it to an example.

**The Class to test**
```php
class A
{
	public function abc($in)
	{
		try
		{
			if ($in === 1) { $a = 2;}
			else { throw new \Exception('A'); }
		}
		catch (\Exception $e)
		{
			// do stuff
			$a = 3;
			return false;
		}
		finally
		{
			$a = 1;
		}

		return true;
	}
}
```

**The Test Case**
```php
require_once __DIR__ . '/a.php';
/**
 * @coversDefaultClass A
 */
class ATest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @covers ::abc
	 */
	public function testAbc()
	{
		$a = new A();

		$this->assertTrue($a->abc(1));
		$this->assertFalse($a->abc(2));
	}
}
```

**The Test Configuration**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit>
    <testsuites>
        <testsuite name="A">
            <directory suffix="Test.php">./*</directory>
        </testsuite>
    </testsuites>
</phpunit>
```

**The Code Coverage Result**
![image](https://cloud.githubusercontent.com/assets/2239808/7772762/7ba90df0-00a0-11e5-90d6-e8f5be491c90.png)
The last line of method A::abc ( the closing } of function) is always uncovered

**Workaround**
If i remove the finally block and put the statement of the finally block into the try and catch block, the coverage switches to 100%.
But this is not really a workaround.

**Environment**
Windows 7
PHP 5.6.7
PHPUnit 4.6.4 und PHPUnit 4.6.6

**Comment by alexislefebvre** [comment]
IIRC, there is another workaround: put the closing `}` at the end of the previous line.

**Comment by sebastianbergmann** [comment]
This is an [edge case](https://phpunit.de/manual/current/en/code-coverage-analysis.html#code-coverage-analysis.edge-cases) due to the nature of the raw data provided by the PHP interpreter and its Xdebug extension.

Also note that this [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project instead.

**Comment by DasRed** [comment]
@sebastianbergmann okay i can put it into the php-code-coverage project. But this is not an edge case. This happends by using the finally and i think many people use the finally and a return in the exception block. So what is the reason, that this should be an edge case?

**Comment by sebastianbergmann** [comment]
"Edge Case" as in a "case where the data we have to work with is not optimal".

**Comment by DasRed** [comment]
Dies würde ich nicht als Edge Case bezeichnen. Unter einem Edge Case verstehe ich, dass diese Fall nur sehr selten unter ganz bestimmten Bedingungen auftritt. Meist sagen wir dazu auch Randfall. Die Frage die sich meiner Meinung nach hier stellt: Ist dies ein Randfall? Wie oft wird so ein Code produziert und wie oft kommt es dann vor, dass dafür keine korrekte Coverage erzeugt wird?
Wie beschrieben würde ich dies aktuell nicht als Randfall betrachten. 

Ich fände es auch eher kontraproduktiv für ein Tool, wenn es solche Fälle einfach mit "Randfall" abtut. Man kann sich dann nicht darauf verlassen, dass dieses Tool dann auch das liefert, was man erwartet. 

Das in Bezug auf das 3. Beispiele in [edge case](https://phpunit.de/manual/current/en/code-coverage-analysis.html#code-coverage-analysis.edge-cases) für den Inhalt des IF-Blocks keine Coverage erzeugt werden kann, ist eigentlich auch kein Randfall, es ist schlicht und ergreifend kein ausführbarer Code.

**Comment by sebastianbergmann** [comment]
@derickr just told me that there actually might be an issue with regards to `finally` that he can address in Xdebug.

**Comment by Wirone** [comment]
I have similar problem, in my case 2 lines are "uncovered":
- `} finally {`
- closing bracket of the class' method which contains try/catch/finally block

PHPUnit 5.4.8
PHP 5.6.14 with Xdebug 2.2.5

**Comment by acelaya** [comment]
Same as @Wirone here.
Everything in my method is covered but the } finally { line, despite the code inside the block is considered covered.

**Comment by gmillsap** [comment]
Same as @acelaya
I found that it was because a finally block was returning $this. I wound up having to use codeCoverageIgnoreStart/codeCoverageIgnoreEnd to surround the "} finally {" line.
