### ISSUE TITLE
Wierd behavior with PHP defined tests suites with filename == class name

### ISSUE THREAD

**Issue by tobyS** [sebastianbergmann/phpunit#173]
Note the following code, which has been written after the example in http://www.phpunit.de/manual/current/en/organizing-tests.html#organizing-tests.testsuite:

<?php

class TestSuite
{
    public static function suite()
    {
        $suite = new PHPUnit_Framework_TestSuite( 'TestSuite' );
        return $suite;
    }
}

?>

If you name the file containing this class "TestSuite.php" and run $ phpunit TestSuite.php, you receive
PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'Class does not extend PHPUnit_Framework_TestCase.' in /dev/PHP/phpunit/PHPUnit/Framework/TestSuite.php:186
Stack trace:
#0 /home/dotxp/Desktop/phpunit_bug/TestSuite.php(7): PHPUnit_Framework_TestSuite->__construct('TestSuite')
#1 [internal function]: TestSuite::suite('TestSuite')
#2 /home/dotxp/dev/PHP/phpunit/PHPUnit/Runner/BaseTestRunner.php(124): ReflectionMethod->invoke(NULL, 'TestSuite')
#3 /home/dotxp/dev/PHP/phpunit/PHPUnit/TextUI/Command.php(150): PHPUnit_Runner_BaseTestRunner->getTest('TestSuite', '/home/dotxp/Des...', false)
#4 /home/dotxp/dev/PHP/phpunit/PHPUnit/TextUI/Command.php(129): PHPUnit_TextUI_Command->run(Array, true)
#5 /usr/local/php/php-5.3.3/bin/phpunit(53): PHPUnit_TextUI_Command::main()
#6 {main}

  thrown in /home/dotxp/dev/PHP/phpunit/PHPUnit/Framework/TestSuite.php on line 186

Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Class does not extend PHPUnit_Framework_TestCase.' in /dev/PHP/phpunit/PHPUnit/Framework/TestSuite.php:186
Stack trace:
#0 /home/dotxp/Desktop/phpunit_bug/TestSuite.php(7): PHPUnit_Framework_TestSuite->__construct('TestSuite')
#1 [internal function]: TestSuite::suite('TestSuite')
#2 /home/dotxp/dev/PHP/phpunit/PHPUnit/Runner/BaseTestRunner.php(124): ReflectionMethod->invoke(NULL, 'TestSuite')
#3 /home/dotxp/dev/PHP/phpunit/PHPUnit/TextUI/Command.php(150): PHPUnit_Runner_BaseTestRunner->getTest('TestSuite', '/home/dotxp/Des...', false)
#4 /home/dotxp/dev/PHP/phpunit/PHPUnit/TextUI/Command.php(129): PHPUnit_TextUI_Command->run(Array, true)
#5 /usr/local/php/php-5.3.3/bin/phpunit(53): PHPUnit_TextUI_Command::main()
#6 {main}

  thrown in /home/dotxp/dev/PHP/phpunit/PHPUnit/Framework/TestSuite.php on line 186

If you rename the file to something else, the suite runs fine.

**Comment by nylen** [comment]
>I don't see that as a big issue as using test suites for organization is discouraged since at least PHPUnit 3.5 (afaik).

This is a pretty annoying issue, and difficult to track down.

Test suites are still mentioned in the manual as a valid way to organize tests:  https://phpunit.de/manual/6.5/en/organizing-tests.html#organizing-tests.xml-configuration

@tobyS @edorian @sebastianbergmann please consider reopening and fixing this.
