### ISSUE TITLE
tests/Regression/GitHub/244.phpt fails with Fedora/Remi RPM of PHP 5.6

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#1732]
## Fedora/Remi RPM

    $ php --version                       
    PHP 5.6.9 (cli) (built: May 15 2015 10:04:17) 
    Copyright (c) 1997-2015 The PHP Group
    Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
        with Xdebug v2.3.2, Copyright (c) 2002-2015, by Derick Rethans

    $ php phpunit  
    PHPUnit 4.6.8 by Sebastian Bergmann and contributors.

    Configuration read from /usr/local/src/phpunit/phpunit.xml

    .............................................................   61 / 1330 (  4%)
    .............................................................  122 / 1330 (  9%)
    .............................................................  183 / 1330 ( 13%)
    .............................................................  244 / 1330 ( 18%)
    .............................................................  305 / 1330 ( 22%)
    .............................................................  366 / 1330 ( 27%)
    .............................................................  427 / 1330 ( 32%)
    .............................................................  488 / 1330 ( 36%)
    .............................................................  549 / 1330 ( 41%)
    .............................................................  610 / 1330 ( 45%)
    .............................................................  671 / 1330 ( 50%)
    .............................................................  732 / 1330 ( 55%)
    .............................................................  793 / 1330 ( 59%)
    .............................................................  854 / 1330 ( 64%)
    .............................................................  915 / 1330 ( 68%)
    .............................................................  976 / 1330 ( 73%)
    ............................................................. 1037 / 1330 ( 77%)
    ............................................................. 1098 / 1330 ( 82%)
    ............................................................. 1159 / 1330 ( 87%)
    ............................................................. 1220 / 1330 ( 91%)
    ............................................................S 1281 / 1330 ( 96%)
    .S.........................S........F...........S

    Time: 15.02 seconds, Memory: 21.00Mb

    There was 1 failure:

    1) /usr/local/src/phpunit/tests/Regression/GitHub/244.phpt
    Failed asserting that format description matches text.
    --- Expected
    +++ Actual
    @@ @@
     PHPUnit 4.6.8 by Sebastian Bergmann and contributors.
     
    -.FFF
    +FF.F
     
     Time: 257 ms, Memory: 4.75Mb
     
     There were 3 failures:
     
    -1) Issue244Test::testFails
    -Failed asserting that '123StringCode' is equal to expected exception code 'OtherString'.
    +1) Issue244Test::testWorks
    +Failed asserting that 123 is equal to expected exception code '123StringCode'.
     
    -2) Issue244Test::testFailsTooIfExpectationIsANumber
    -Failed asserting that '123StringCode' is equal to expected exception code 123.
    +2) Issue244Test::testFails
    +Failed asserting that 123 is equal to expected exception code 'OtherString'.
     
     3) Issue244Test::testFailsTooIfExceptionCodeIsANumber
     Failed asserting that 123 is equal to expected exception code '123String'.
     
     FAILURES!
     Tests: 4, Assertions: 8, Failures: 3.

    /usr/local/src/phpunit/src/Framework/Constraint.php:117
    /usr/local/src/phpunit/src/Framework/Constraint.php:63
    /usr/local/src/phpunit/src/Framework/Assert.php:2216
    /usr/local/src/phpunit/src/Framework/Assert.php:1509
    /usr/local/src/phpunit/src/Extensions/PhptTestCase.php:144
    /usr/local/src/phpunit/src/Framework/TestSuite.php:722
    /usr/local/src/phpunit/src/Framework/TestSuite.php:722
    /usr/local/src/phpunit/src/TextUI/TestRunner.php:406
    /usr/local/src/phpunit/src/TextUI/Command.php:153
    /usr/local/src/phpunit/src/TextUI/Command.php:105

    --

    There were 4 skipped tests:

    1) /usr/local/src/phpunit/tests/TextUI/log-json-no-pretty-print.phpt
    PHP without JSON_PRETTY_PRINT is required

    /usr/local/src/phpunit/src/Extensions/PhptTestCase.php:121
    /usr/local/src/phpunit/src/Framework/TestSuite.php:722
    /usr/local/src/phpunit/src/Framework/TestSuite.php:722
    /usr/local/src/phpunit/src/TextUI/TestRunner.php:406
    /usr/local/src/phpunit/src/TextUI/Command.php:153
    /usr/local/src/phpunit/src/TextUI/Command.php:105

    2) /usr/local/src/phpunit/tests/TextUI/log-json-pre-66021.phpt
    Has PHP #66021 (Blank line inside empty JSON array/object)

    /usr/local/src/phpunit/src/Extensions/PhptTestCase.php:121
    /usr/local/src/phpunit/src/Framework/TestSuite.php:722
    /usr/local/src/phpunit/src/Framework/TestSuite.php:722
    /usr/local/src/phpunit/src/TextUI/TestRunner.php:406
    /usr/local/src/phpunit/src/TextUI/Command.php:153
    /usr/local/src/phpunit/src/TextUI/Command.php:105

    3) /usr/local/src/phpunit/tests/Regression/GitHub/1340-php7.phpt
    PHP 7 is required

    /usr/local/src/phpunit/src/Extensions/PhptTestCase.php:121
    /usr/local/src/phpunit/src/Framework/TestSuite.php:722
    /usr/local/src/phpunit/src/Framework/TestSuite.php:722
    /usr/local/src/phpunit/src/TextUI/TestRunner.php:406
    /usr/local/src/phpunit/src/TextUI/Command.php:153
    /usr/local/src/phpunit/src/TextUI/Command.php:105

    4) /usr/local/src/phpunit/tests/Regression/GitHub/873-php7.phpt
    PHP 7 is required

    /usr/local/src/phpunit/src/Extensions/PhptTestCase.php:121
    /usr/local/src/phpunit/src/Framework/TestSuite.php:722
    /usr/local/src/phpunit/src/Framework/TestSuite.php:722
    /usr/local/src/phpunit/src/TextUI/TestRunner.php:406
    /usr/local/src/phpunit/src/TextUI/Command.php:153
    /usr/local/src/phpunit/src/TextUI/Command.php:105

    FAILURES!
    Tests: 1330, Assertions: 2040, Failures: 1, Skipped: 4.

## Built from source

    $ /usr/local/php-5.6/bin/php --version
    PHP 5.6.9 (cli) (built: May 28 2015 14:13:27) (DEBUG)
    Copyright (c) 1997-2015 The PHP Group
    Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
        with Xdebug v2.3.3-dev, Copyright (c) 2002-2015, by Derick Rethans

    $ /usr/local/php-5.6/bin/php phpunit  
    PHPUnit 4.6.8 by Sebastian Bergmann and contributors.

    Configuration read from /usr/local/src/phpunit/phpunit.xml

    .............................................................   61 / 1330 (  4%)
    .............................................................  122 / 1330 (  9%)
    .............................................................  183 / 1330 ( 13%)
    .............................................................  244 / 1330 ( 18%)
    .............................................................  305 / 1330 ( 22%)
    .............................................................  366 / 1330 ( 27%)
    .............................................................  427 / 1330 ( 32%)
    .............................................................  488 / 1330 ( 36%)
    .............................................................  549 / 1330 ( 41%)
    .............................................................  610 / 1330 ( 45%)
    .............................................................  671 / 1330 ( 50%)
    .............................................................  732 / 1330 ( 55%)
    .............................................................  793 / 1330 ( 59%)
    .............................................................  854 / 1330 ( 64%)
    .............................................................  915 / 1330 ( 68%)
    .............................................................  976 / 1330 ( 73%)
    ............................................................. 1037 / 1330 ( 77%)
    ............................................................. 1098 / 1330 ( 82%)
    ............................................................. 1159 / 1330 ( 87%)
    ............................................................. 1220 / 1330 ( 91%)
    ............................................................S 1281 / 1330 ( 96%)
    .S.........................S....................S

    Time: 14.28 seconds, Memory: 31.25Mb

    There were 4 skipped tests:

    1) /usr/local/src/phpunit/tests/TextUI/log-json-no-pretty-print.phpt
    PHP without JSON_PRETTY_PRINT is required

    /usr/local/src/phpunit/src/Extensions/PhptTestCase.php:121
    /usr/local/src/phpunit/src/Framework/TestSuite.php:722
    /usr/local/src/phpunit/src/Framework/TestSuite.php:722
    /usr/local/src/phpunit/src/TextUI/TestRunner.php:406
    /usr/local/src/phpunit/src/TextUI/Command.php:153
    /usr/local/src/phpunit/src/TextUI/Command.php:105

    2) /usr/local/src/phpunit/tests/TextUI/log-json-pre-66021.phpt
    Has PHP #66021 (Blank line inside empty JSON array/object)

    /usr/local/src/phpunit/src/Extensions/PhptTestCase.php:121
    /usr/local/src/phpunit/src/Framework/TestSuite.php:722
    /usr/local/src/phpunit/src/Framework/TestSuite.php:722
    /usr/local/src/phpunit/src/TextUI/TestRunner.php:406
    /usr/local/src/phpunit/src/TextUI/Command.php:153
    /usr/local/src/phpunit/src/TextUI/Command.php:105

    3) /usr/local/src/phpunit/tests/Regression/GitHub/1340-php7.phpt
    PHP 7 is required

    /usr/local/src/phpunit/src/Extensions/PhptTestCase.php:121
    /usr/local/src/phpunit/src/Framework/TestSuite.php:722
    /usr/local/src/phpunit/src/Framework/TestSuite.php:722
    /usr/local/src/phpunit/src/TextUI/TestRunner.php:406
    /usr/local/src/phpunit/src/TextUI/Command.php:153
    /usr/local/src/phpunit/src/TextUI/Command.php:105

    4) /usr/local/src/phpunit/tests/Regression/GitHub/873-php7.phpt
    PHP 7 is required

    /usr/local/src/phpunit/src/Extensions/PhptTestCase.php:121
    /usr/local/src/phpunit/src/Framework/TestSuite.php:722
    /usr/local/src/phpunit/src/Framework/TestSuite.php:722
    /usr/local/src/phpunit/src/TextUI/TestRunner.php:406
    /usr/local/src/phpunit/src/TextUI/Command.php:153
    /usr/local/src/phpunit/src/TextUI/Command.php:105

    OK, but incomplete, skipped, or risky tests!
    Tests: 1330, Assertions: 2040, Skipped: 4.

**Comment by sebastianbergmann** [comment]
@remicollet Do you have an idea what is going on here?

**Comment by remicollet** [comment]
Very strange.
Need to dig in PHPUnit code... but don't see any reason for this (except perhap a system vs bundled library, ex pcre).

**Comment by remicollet** [comment]
Disabling XDebug effectively solves this.

**Comment by sebastianbergmann** [comment]
So the difference is between self-built Xdebug and Xdebug from an RPM?

**Comment by remicollet** [comment]
Do you build standard 2.3.2 ? or from git ?

**Comment by remicollet** [comment]
I think this could be related to https://github.com/xdebug/xdebug/commit/b6da4dad4e2410de764964b61b17bdff7fa72cd9#diff-50b7f832915ee1d6491a14aa16a90786

Removal of

       convert_to_long_ex(&code);

**Comment by remicollet** [comment]
@derickr perhaps time for a 2.3.3 ?

**Comment by GrahamCampbell** [comment]
That commit is on the master branch only though, which is 2.4.x. :(

**Comment by remicollet** [comment]
@GrahamCampbell I see it on https://github.com/xdebug/xdebug/commits/xdebug_2_3

**Comment by GrahamCampbell** [comment]
Why isn't github showing as being there then in the commit?

![image](https://cloud.githubusercontent.com/assets/2829600/7861875/94554770-054a-11e5-970f-bc54015bce44.png)

**Comment by remicollet** [comment]
$ git checkout xdebug_2_3
    $ git diff XDEBUG_2_3_2 | grep convert_to_long
    -	convert_to_long_ex(&code);
     	convert_to_long_ex(&line);

**Comment by remicollet** [comment]
For you information I have push a new build (in Fedora/remirepo) with this fix.
https://admin.fedoraproject.org/updates/FEDORA-2015-9038

**Comment by sebastianbergmann** [comment]
Thanks!
