### ISSUE TITLE
Question: why was pear installation support dropped?

### ISSUE THREAD

**Issue by eric-tucker** [sebastianbergmann/phpunit#1741]
The documentation on end of life explains what happens and how to install now, but it's not clear why pear installation was dropped.

`/usr/share/pear` is the default location that PHP looks for dependencies (`include_path`) and I believe that's where PHPUnit was installed.

Is PEAR going away?

**Comment by jmikola** [comment]
> Is PEAR going away?

This article may provide some context: http://fabien.potencier.org/the-rise-of-composer-and-the-fall-of-pear.html

**Comment by eric-tucker** [comment]
So basically composer is the new PEAR?

What about installing packages at the global level?  I have a build server that uses PHPUnit for CakePHP and Yii projects.  I'd rather not have to update all those projects to now add composer and add dependencies on the PHPUnit objects I require.

So what is the alternative?

**Comment by webmozart** [comment]
@eric-tucker You can install Composer packages globally: https://getcomposer.org/doc/03-cli.md#global
