### ISSUE TITLE
Calling $mock->expects($this->once())->method("methodIdonthave") doesnt fail.

### ISSUE THREAD

**Issue by sdwrage** [sebastianbergmann/phpunit#1744]
I know the code is being ran because if I add an assertEquals I get an error about how null doesnt equal "blah". This method never does get called yet still passes?

Here is the code: https://gist.github.com/sdwrage/8426365f0c4205578ae9

**Comment by sdwrage** [comment]
I moved the actual instancing of the mock objects in the actual test, bypassing the dataProvider, and it finally errors. Is there still a way to use dataProviders with mocks or is that a no go?

**Comment by sebastianbergmann** [comment]
I don't see how this could work.

**Comment by sdwrage** [comment]
I moved this to creating mocks via the constructor and storing as a fixture within the test object. Maybe this was ignorance on my part on how data providers worked. Could you elaborate on why this doesn't work?
