### ISSUE TITLE
Method signature for mock method fails

### ISSUE THREAD

**Issue by burzum** [sebastianbergmann/phpunit#1746]
I'm getting a signature error when mocking one of my objects in the test:

See https://travis-ci.org/burzum/cakephp-search-plugin/jobs/66534571

```
1) Burzum\Search\Test\TestCase\Controller\Component\PrgComponentTest::testInitialize
Declaration of Mock_Request_c2cdb747::method() should be compatible with Cake\Network\Http\Request::method($method = NULL)
/home/travis/build/burzum/cakephp-search-plugin/tests/TestCase/Controller/Component/PrgComponentTest.php:29
```

My test case is here https://github.com/burzum/cakephp-search-plugin/blob/develop/tests/TestCase/Controller/Component/PrgComponentTest.php#L24

```php
$this->request = $this->getMockBuilder('\Cake\Network\Http\Request')
            ->setMethods(['is'])
            ->getMock();
```

I've been told by @lorenzo that he reported this some time ago as well and it was fixed, he said it's probably a regression. See https://github.com/sebastianbergmann/phpunit-mock-objects/issues/159

The issue was fixed in **4.0**, I'm using **4.5**.

**Comment by sebastianbergmann** [comment]
Please open this at https://github.com/sebastianbergmann/phpunit-mock-objects/issues/new and include a minimal, self-contained, reproducing test case.
