### ISSUE TITLE
Drop support for PHP 5

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#1751]

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by marcioAlmada** [comment]
:tada:

**Comment by tim-bezhashvyly** [comment]
(y)

**Comment by jreinke** [comment]
:+1:

**Comment by dracony** [comment]
Drop support for PHP =)))

**Comment by quafzi** [comment]
:thumbsup:

**Comment by GrahamCampbell** [comment]
@sebastianbergmann When will all of phpunit's dependencies and phpunit itself be getting namespaced and psr4 autoloaded? v5 or v6 look like good opportunities to me? Perhaps do everything but phpunit/mockobjects/coverage for v5, then everything in v6?

**Comment by sebastianbergmann** [comment]
Eventually all code will be namespaced. I do not see any value for the end user in namespacing the code so that is not a high priority for me. I also do not see any value in PSR-X-based autoloading and will stick with the class map.

**Comment by shehi** [comment]
Uhm, what does drop support for PHP 5 mean?! As in drop supporting 5.0 and increase required level to something in range of 5.3?

**Comment by shehi** [comment]
Oh my bad, it is tagged PHPUnit 6 :) Guess its a release exclusively for PHP 7 then.

**Comment by GrahamCampbell** [comment]
> Uhm, what does drop support for PHP 5 mean?! As in drop supporting 5.0 and increase required level to something in range of 5.3?

Drop support for all 5.x.

**Comment by TheSerenin** [comment]
:+1:

**Comment by krzysiekpiasecki** [comment]
:+1:
