### ISSUE TITLE
Mocking two methods and expecting at least one of them will be called exactly once

### ISSUE THREAD

**Issue by kiler129** [sebastianbergmann/phpunit#1756]
Hello everyone.
Testing one of my projects I found one problem which I couldn't resolve. I'm expecting that method will emit warning with certain message using PSR-complaint logger. If you look at [PSR LoggerInterface](https://github.com/php-fig/log/blob/master/Psr/Log/LoggerInterface.php) you can see message can be printed using either `$logger->warning(...)` or `$logger->log(LogLevel::WARNING, ...)`.

I wish to test if method calls  `$logger->warning(...)` at exactly once OR `$logger->log(LogLevel::WARNING, ...)` exactly once.
How to test against that scenario?

**Comment by kiler129** [comment]
I've also tried mocking at least one method - it failed.

```php
$logger = $this->getMock('\Psr\Log\LoggerInterface');

        $logger
            ->expects($this->atLeastOnce())
            ->method('warning')
            ->with($this->equalTo('test'));
        $this->loggerMock->warning('test');
```
phpUnit returns error: `Expectation failed for method name is equal to <string:warning> when invoked at least once.
Expected invocation at least once but it never occurred.`.

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md) have been reported on the [phpunit-mock-objects](https://github.com/sebastianbergmann/phpunit-mock-objects) project instead.
