### ISSUE TITLE
Do not error out on invalid @covers tag

### ISSUE THREAD

**Issue by JeroenDeDauw** [sebastianbergmann/phpunit#1760]
In my projects I have a ci command that runs PHPUnit and some other stuff. This is also what TravisCI runs. The only difference is that TravisCI also runs code coverage generation (via PHPUnit) afterwards. This means the TravisCI build can fail due to a typo in an @covers tag, which will only show up when running coverage generation.

One fix is to execute `phpunit --coverage-text=/dev/null`. That will then fail as desired if a @covers tag got messed up. That however slows the command down significantly. On one project from ~850ms to ~18s.

Is there a way to have PHPUnit not error out during coverage report generating when a @covers tag is wrong? If not, consider this a feature request.

Currently using `PHPUnit 4.7.3`, though I've been running into this for years.

**Comment by orlangur** [comment]
Some `phpunit --coverage-null` which just runs fast looks like a dirty hack.

Why not simply fix such problem on an earlier stage so that invalid class/method will never appear in repository? Just check this in hook or [static test](https://github.com/magento/magento2/blob/develop/dev/tests/static/testsuite/Magento/Test/Integrity/ClassesTest.php#L531).

**Comment by sebastianbergmann** [comment]
This should be implemented in a separate tool.

**Comment by theofidry** [comment]
@sebastianbergmann I see that you already answered regarding verifying the `@cover(s)` annotations. While I agree with what you said, there still an issue: if I have a wrong `@covers` annotation, my test just fail with `'Trying to @cover or @use not existing class or interface ">my class name>".'`. The issue being that it does not display a failure message and on my Travis CI, the test is still marked as passed, even if the whole test suite has been interrupted. Could this be changed?

In case it's a bug, I'm using PHPUnit 5.2.3 on PHP 5.6.18 with Xdebug 2.3.3. My PHPUnit config is:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="http://schema.phpunit.de/5.2/phpunit.xsd"
         bootstrap="bootstrap/autoload.php"
         colors="true"
         forceCoversAnnotation="true">

    <testsuites>
        <testsuite name="App tests">
            <directory>tests</directory>
        </testsuite>
    </testsuites>

    <filter>
        <whitelist>
            <directory suffix=".php">src/</directory>
        </whitelist>
    </filter>
</phpunit>
```
