### ISSUE TITLE
before and after annotations don't work in some traits

### ISSUE THREAD

**Issue by GrahamCampbell** [sebastianbergmann/phpunit#1763]
If you use a trait in a class then extend that class then phpunit doesn't process the before and after annotations for those methods in that trait.

NB, experiencing this with phpunit 4.7.5.

**Comment by sebastianbergmann** [comment]
Can you please provide a minimal, self-contained, reproducing test case? I am afraid I don't fully understand what you are trying to do.

**Comment by GrahamCampbell** [comment]
```php
class Foo
{
    public function bar()
    {
        return 'baz';
    }
}

trait MockeryTrait
{
    /**
     * @after
     */
    public function tearDownMockery()
    {
        if ($container = Mockery::getContainer()) {
            $this->addToAssertionCount($container->mockery_getExpectationCount());
        }

        Mockery::close();
    }
}

abstract class AbstractTestCase extends PHPUnit_Framework_TestCase
{
    use MockeryTrait;
}

class FooTest extends AbstractTestCase
{
    public function testStuff()
    {
        $mock = Mockery::mock(Foo::class);
        $mock->shouldReceive('bar')->andReturn('foobarbaz');
        $mock->bar();
}
```

**Comment by GrahamCampbell** [comment]
If running in strict mode, phpunit thinks there have been no assertions because the tearDownMockery method was never called.

**Comment by GrahamCampbell** [comment]
PHPUnit will also fail without the trait, like, if we just put that method into the "AbstractTestCase" class.
