### ISSUE TITLE
Tests are omitted from JUnit xml report if previous test is skipped

### ISSUE THREAD

**Issue by zetrax** [sebastianbergmann/phpunit#1767]
If you mark a test as @depends on another test and the dependency fails, then the next test will also be skipped from the JUnit report.

How to reproduce:
```php
<?php

class TestCase extends PHPUnit_Framework_TestCase {
        function testTrigger() {
                $this->fail("This test will skip the next good test from JUnit xml report");
        }

        /**
         * @depends testTrigger
         */
        function testSkipper() {
                $this->fail("This test should be skipped from JUnit xml report");
        }

        function testShouldNotBeSkipped() {
                $this->fail("This test SHOULD NOT be skipped from JUnit xml report");
        }

        function testAreNotSkipped() {
                $this->fail("This is the next failing test showing up in JUnit xml report");
        }
}
```

Output when run:
```
phpunit --log-junit /tmp/output.xml TestCase.php
```

```
PHPUnit 5.0-g14f174e by Sebastian Bergmann and contributors.

FSFF

Time: 49 ms, Memory: 4.50Mb

There were 3 failures:

1) TestCase::testTrigger
This test will skip the next good test from JUnit xml report

/home/krc/viasat-local/sites/holiday_app_api/tests/unit/TestCase.php:5

2) TestCase::testShouldNotBeSkipped
This test SHOULD NOT be skipped from JUnit xml report

/home/krc/viasat-local/sites/holiday_app_api/tests/unit/TestCase.php:16

3) TestCase::testAreNotSkipped
This is the next failing test showing up in JUnit xml report

/home/krc/viasat-local/sites/holiday_app_api/tests/unit/TestCase.php:20

FAILURES!
Tests: 3, Assertions: 0, Failures: 3, Skipped: 1.
```

Resulting junit xml file
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="TestCase" file="/home/krc/viasat-local/sites/holiday_app_api/tests/unit/TestCase.php" tests="2" assertions="0" failures="3" errors="0" time="0.000832">
    <testcase name="testTrigger" class="TestCase" file="/home/krc/viasat-local/sites/holiday_app_api/tests/unit/TestCase.php" line="4" assertions="0" time="0.000615">
      <failure type="PHPUnit_Framework_AssertionFailedError">TestCase::testTrigger
This test will skip the next good test from JUnit xml report

/home/krc/viasat-local/sites/holiday_app_api/tests/unit/TestCase.php:5
</failure>
    </testcase>
    <testcase name="testAreNotSkipped" class="TestCase" file="/home/krc/viasat-local/sites/holiday_app_api/tests/unit/TestCase.php" line="19" assertions="0" time="0.000217">
      <failure type="PHPUnit_Framework_AssertionFailedError">TestCase::testAreNotSkipped
This is the next failing test showing up in JUnit xml report

/home/krc/viasat-local/sites/holiday_app_api/tests/unit/TestCase.php:20
</failure>
    </testcase>
  </testsuite>
</testsuites>
```

Expected result:
  - Number of tests should be 3
  - A {testcase name="testShouldNotBeSkipped" ...} section
  - with a {failure} subsection

**Comment by zetrax** [comment]
It seems the failure occurs in JUnit.php where $this->attachCurrentTestCase is not changed back to true after skipping a test.

Normally startTest() and endTest() are executed for each test where endTest() will make sure to set $this->attachCurrentTestCase to true so we are ready to process the next testCase.

This pattern is not followed when skipping tests due to dependency issues. Here only addSkippedTest() are called which sets $this->attachCurrentTestCase to false, and it is never cleaned up with endTest(), so when we process the next test after the skipped one, we still have $this->attachCurrentTestCase and this test is also skipped from the report.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
