### ISSUE TITLE
TestCase status overwritten with Error in 4.7.5

### ISSUE THREAD

**Issue by oehlschl** [sebastianbergmann/phpunit#1769]
It looks like a regression was introduced in 4.7.5 that overwrites the correct TestCase status with Error whenver an exception is thrown. See https://github.com/sebastianbergmann/phpunit/commit/16b5b198d4b73e6713eae5ffbd6da2f66b0e2ea2#diff-511c90242d5589e941582006e0485184R883

TestResults are not affected because they check the exception class in addError(), and it seems test getStatus() is seldom used otherwise (https://github.com/sebastianbergmann/phpunit/search?q=getStatus), so the impact from this change is minimal.

Just a heads up in case the change was unintentional.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
