### ISSUE TITLE
PHPUnit with Selenium, giving error

### ISSUE THREAD

**Issue by suhailrepo** [sebastianbergmann/phpunit#1770]
Hello,
I got this error while running test cases 
Argument #3 (No Value) of PHPUnit_TextUI_ResultPrinter::__construct() must be a value from "never", "auto" or "always".

I try to give manual value in constructor for the third argument, then its giving another error.
 phpunit\phpunit\src\TextUI\ResultPrinter.php 

    public function __construct($out = null, $verbose = false, $colors = self::COLOR_DEFAULT, $debug = false, $numberOfColumns = 80)

```php
require 'vendor/autoload.php';
class TestLogin extends PHPUnit_Framework_TestCase{
	
	/**
     * @var \RemoteWebDriver
     */
    protected $webDriver;

    public function setUp()
    {
        $capabilities = array(\WebDriverCapabilityType::BROWSER_NAME => 'firefox');
        $this->webDriver = RemoteWebDriver::create('http://localhost:4444/wd/hub', $capabilities);
    }
}
```

Enviroment:
Windows 7
PHPUnit 3.7.21 by Sebastian Bergmann.
PHP: PHP 5.4.19 (cli)
Selenium: selenium-server-standalone-2.46.0.jar

**Comment by sebastianbergmann** [comment]
I have no idea what you are trying to do. Please provide a full stacktrace. For instance, from the little context you provide it is impossible to determine whether PHPUnit's own code tries to create an instance of `PHPUnit_TextUI_ResultPrinter` using wrong arguments, whether it's third-party code, or your code.

Also note that `require 'vendor/autoload.php';` is not needed (and potentially harmful) in your test code. Have a look at https://phpunit.de/getting-started.html and learn about using a bootstrap script to set up your autoloader.

**Comment by suhailrepo** [comment]
Sorry about that.

This is my first try to use PHPUnit and Selenium together. So i installed
through composer, that's why i am using vendor/autoload .php.

*composer.json*
{
    "require-dev": {
        "phpunit/phpunit": "4.7.*",
        "phpunit/phpunit-selenium": "1.3.*"
    }
}

After installing i created a simple class and run the tests. After running
the tests its giving this error. If i downgrade phpunit to 4.1.* in
composer and update, its works fine.

*TestLogin.php*

require 'vendor/autoload.php';
class TestLogin extends PHPUnit_Extensions_Selenium2TestCase{

    /**
     * @var \RemoteWebDriver
     */
    protected $webDriver;

   protected function setUp()
    {
        $this->setHost('localhost');
        $this->setport(4444);
        $this->setBrowser('firefox');
        $this->setBrowserUrl('http://localhost/testsel');
    }

    public function testHasLoginForm(){
        $this->url('login.php');
        $username = $this->byId('username');
        $password = $this->byId('password');

        $this->assertEquals('suhail',$username->value());
        $this->assertEquals('tahir',$password->value());
    }

    /*public function testTitle()
    {
        $this->url('http://haystack.jobs/');
        $this->assertEquals('Free Recruiting Software For Small & Medium
Business » Haystack', $this->title());
    }*/
}

-----
*Command from CMD*
c:\xampp\htdocs\testsel>phpunit TestLogin.php
Argument #3 (No Value) of PHPUnit_TextUI_ResultPrinter::__construct() must
be a
value from "never", "auto" or "always"

On 29 June 2015 at 16:25, Sebastian Bergmann <notifications@github.com>
wrote:

> I have no idea what you are trying to do. Please provide a full
> stacktrace. For instance, from the little context you provide it is
> impossible to determine whether PHPUnit's own code tries to create an
> instance of PHPUnit_TextUI_ResultPrinter using wrong arguments, whether
> it's third-party code, or your code.
>
> Also note that require 'vendor/autoload.php'; is not needed (and
> potentially harmful) in your test code. Have a look at
> https://phpunit.de/getting-started.html and learn about using a bootstrap
> script to set up your autoloader.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sebastianbergmann/phpunit/issues/1770#issuecomment-116429684>
> .
>



-- 


Muhammad Suhail Tahir
+64 22 320 5327

**Comment by sebastianbergmann** [comment]
You have yet to provide a full stacktrace.

**Comment by suhailrepo** [comment]
This is what i got from the trace, thanks

#0  include_once() called at
[C:\xampp\php\pear\PHPUnit\Util\Fileloader.php:92]

#1  PHPUnit_Util_Fileloader::load(C:\xampp\htdocs\newTDD\TestLogin.php)
called at [C:\xampp\php\pear\PHPUnit\Util\Fileloader.php:76]

#2
PHPUnit_Util_Fileloader::checkAndLoad(C:\xampp\htdocs\newTDD\TestLogin.php)
called at [C:\xampp\php\pear\PHPUnit\Runner\StandardTestSuiteLoader.php:77]

#3  PHPUnit_Runner_StandardTestSuiteLoader->load(TestLogin,
C:\xampp\htdocs\newTDD\TestLogin.php) called at
[C:\xampp\php\pear\PHPUnit\Runner\BaseTestRunner.php
:168]

#4  PHPUnit_Runner_BaseTestRunner->loadSuiteClass(TestLogin,
C:\xampp\htdocs\newTDD\TestLogin.php) called at
[C:\xampp\php\pear\PHPUnit\Runner\BaseTestRunner.ph
p:104]

#5  PHPUnit_Runner_BaseTestRunner->getTest(TestLogin,
C:\xampp\htdocs\newTDD\TestLogin.php, Array ([0] => Test.php,[1] => .phpt))
called at [C:\xampp\php\pear\P
HPUnit\TextUI\Command.php:150]

#6  PHPUnit_TextUI_Command->run(Array ([0] => C:\xampp\php\phpunit,[1] =>
--debug,[2] => TestLogin.php), 1) called at
[C:\xampp\php\pear\PHPUnit\TextUI\Command.
php:129]

#7  PHPUnit_TextUI_Command::main() called at [C:\xampp\php\phpunit:46]
Argument #3 (No Value) of PHPUnit_TextUI_ResultPrinter::__construct() must
be a
value from "never", "auto" or "always"


*TestLogin.php*

<?php

require 'vendor/autoload.php';
debug_print_backtrace();
class TestLogin extends PHPUnit_Extensions_Selenium2TestCase{

    /**
     * @var \RemoteWebDriver
     */
    protected $webDriver;

   protected function setUp()
    {
        $this->setHost('localhost');
        $this->setport(4444);
        $this->setBrowser('firefox');
        $this->setBrowserUrl('http://localhost/newTDD');
    }

    public function testHasLoginForm(){
        $this->url('login.php');
        $username = $this->byId('username');
        $password = $this->byId('password');

        $this->assertEquals('suhail',$username);
        $this->assertEquals('tahir',$password);
    }


}


On 30 June 2015 at 17:01, Sebastian Bergmann <notifications@github.com>
wrote:

> You have yet to provide a full stacktrace.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sebastianbergmann/phpunit/issues/1770#issuecomment-116961502>
> .
>



-- 


Muhammad Suhail Tahir
+64 22 320 5327

**Comment by sebastianbergmann** [comment]
Just as I suspected, it appears that you have an old version of PHPUnit lying around that was installed using PEAR. Somehow that is pulled it which leads to the error.

**Comment by suhailrepo** [comment]
Thanks, after uninstalling from PEAR and use the PHAR one. This issue
resolved.

Thanks for helping.

On 1 July 2015 at 16:41, Sebastian Bergmann <notifications@github.com>
wrote:

> Just as I suspected, it appears that you have an old version of PHPUnit
> lying around that was installed using PEAR. Somehow that is pulled it which
> leads to the error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sebastianbergmann/phpunit/issues/1770#issuecomment-117432676>
> .
>



-- 


Muhammad Suhail Tahir
+64 22 320 5327
