### ISSUE TITLE
coverage text do not honor --colors setting

### ISSUE THREAD

**Issue by krzaczek** [sebastianbergmann/phpunit#1771]
According to doc

https://phpunit.de/manual/current/en/logging.html
```
When used from the command-line by writing to php://stdout this will honor the --colors setting
```

But it doesn't: version 4.7.5

```xml
<phpunit
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://schema.phpunit.de/4.5/phpunit.xsd"
        convertErrorsToExceptions="true"
        convertNoticesToExceptions="true"
        convertWarningsToExceptions="true"
        colors="false"
        stopOnError="true"
        stopOnFailure="true"
        bootstrap="./tests/bootstrap.php">

    <testsuite name="Unit test suite">
        <directory>./tests</directory>
    </testsuite>

    <filter>
        <whitelist>
            <directory suffix=".php">./lib</directory>
        </whitelist>
    </filter>

    <groups>
        <exclude>
            <group>ignore</group>
            <group>tests</group>
        </exclude>
    </groups>

    <logging>
        <log type="coverage-text" target="php://stdout" showOnlySummary="true" showUncoveredFiles="false" />
    </logging>

</phpunit>
```

![zrzut ekranu 2015-06-29 11 10 25](https://cloud.githubusercontent.com/assets/5773701/8404714/7ba1422e-1e4f-11e5-9ff9-bcaf9b1034ad.png)

**Comment by parkr** [comment]
Ran into this today and set me back a lot. Makes it way less parse-able.

**Comment by GrahamCampbell** [comment]
I've noticed this issues too. Even when colours are not supported by the output, they're used anyway.

**Comment by henriquemoody** [comment]
That's because the creation of the Printer is not centralized.

On #1548 there was a fix for this problem.

**Comment by mgansler** [comment]
Same issue with PHPUnit 4.8.6.

**Comment by llaville** [comment]
I used today PHPUnit 4.8.9 (phar distrib) and I got the same issue on Windows 

```
\UwAmp\bin\php\php-5.6.13\php \UwAmp\bin\php\phar\phpunit-4.8.9.phar --coverage-text --colors=never
PHPUnit 4.8.9 by Sebastian Bergmann and contributors.

....

Time: 485 ms, Memory: 12.50Mb

OK (4 tests, 2 assertions)


←[1;37;40mCode Coverage Report:     ←[0m
←[1;37;40m  2015-09-23 16:16:45     ←[0m
←[1;37;40m                          ←[0m
←[1;37;40m Summary:                 ←[0m
←[37;41m  Classes: 33.33% (1/3)   ←[0m
←[37;41m  Methods: 13.33% (2/15)  ←[0m
←[37;41m  Lines:   15.74% (17/108)←[0m

\ROL::App
  ←[37;41mMethods:  16.67% ( 2/12)←[0m   ←[37;41mLines:  20.24% ( 17/ 84)←[0m
```

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
