### ISSUE TITLE
Multiple copies of hierarchy when running --log-junit

### ISSUE THREAD

**Issue by jimmyt1988** [sebastianbergmann/phpunit#1774]
I have covered the issue here aswell if you wish to earn points:

http://stackoverflow.com/questions/31038121/phpunit-creating-weird-log-output-with-duplicate-testsuite-hierarchy-in-xml

-------------------------

**Side notes:**

*My PHPUnit version is:* "PHPUnit 4.7.4 by Sebastian Bergmann and contributors."

It came with the Laravel package from composer

---------------

**Context:**

When i call the following command line:

    phpunit --log-junit "C:\Users\James\Documents\Test Logs\log.xml" --configuration "C:\xampp\htdocs\Test\phpunit.xml"

With the following phpunit.xml defined:

    <?xml version="1.0" encoding="UTF-8"?>
    <phpunit backupGlobals="false"
             backupStaticAttributes="false"
             bootstrap="bootstrap/autoload.php"
             colors="true"
             convertErrorsToExceptions="true"
             convertNoticesToExceptions="true"
             convertWarningsToExceptions="true"
             processIsolation="false"
             stopOnFailure="false"
             syntaxCheck="false">
        <testsuites>
            <testsuite name="Application Test Suite">
                <directory>./tests/</directory>
                <exclude>./tests/vomit/</exclude>
            </testsuite>
            <testsuite name="Shooblie ma hooblie">
                <directory>./tests/vomit/</directory>
            </testsuite>
        </testsuites>
        <filter>
            <whitelist>
                <directory suffix=".php">app/</directory>
            </whitelist>
        </filter>
        <php>
            <env name="APP_ENV" value="testing"/>
            <env name="CACHE_DRIVER" value="array"/>
            <env name="SESSION_DRIVER" value="array"/>
            <env name="QUEUE_DRIVER" value="sync"/>
        </php>
    </phpunit>

I get the following output: http://pastebin.com/aD4tq7tC

**Problem:**

To save you having to look, *I'm getting multiple levels of "testsuite" which does not follow the documentation output.* What might be going wrong... or is this normal behaviour?

For example (shortened for brevity):

    <testsuites>
        <testsuite>        
            <testsuite>                 
                <testsuite>   
                    <testcase></testcase>     
                </testsuite>    
            </testsuite>
        </testsuite>
    </testsuites>

------------------------

*source:* https://phpunit.de/manual/current/en/logging.html#logging.xml

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
