### ISSUE TITLE
Coverage fails for array casted to object

### ISSUE THREAD

**Issue by Pittiplatsch** [sebastianbergmann/phpunit#1777]
I encountered a weird bug I tried to isolate.

Coverage gives false negative when testing following code:
```
$foo['bar'] = (object) [
    'phone' => 'foo',
    'plain' => 'bar',
// Note the trailing comma in last line, which seems to cause failing coverage of next line
];
```

Where the following snippets work as expected:
```
$foo['bar'] = (object) [
    'phone' => 'foo',
    'plain' => 'bar'
// Note missing trailing comma in last line
];
```

```
// Without casting to object:
$foo['bar'] = [
    'phone' => 'foo',
    'plain' => 'bar',
];
```
Tested with a straight-forward unit test with or without any assertions.

Used version: phpunit 4.7.6.

**Comment by sebastianbergmann** [comment]
PHP_CodeCoverage (and PHPUnit in turn) can only report the data provided by Xdebug and the PHP engine.

Also note that this [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project.

**Comment by Pittiplatsch** [comment]
Thank you for your response. Based on your hint I just found https://github.com/sebastianbergmann/php-code-coverage/issues/329 which describes the same problem.
