### ISSUE TITLE
ReflectionClass->getFileName() fails when run in a .phpt

### ISSUE THREAD

**Issue by asgrim** [sebastianbergmann/phpunit#1783]
I am trying to use `ReflectionClass` in a test and I need to access the filename of the class (long story, but basically using `__FILE__` is not an ideal alternative). So, after a bit of digging, it seems that `.phpt` tests are run in a separate process using `PHPUnit_Util_PHP_Default`, which actually pipes the code to whichever `php` runtime is found, rather than executing it as a file. This results in any reflection being run as not having a file, thus when you call `$reflection->getFileName()` it unexpectedly returns a string containing just a hyphen `'-'`.

Here is an isolated, reproducible testcase:

```php
--TEST--
ReflectionClass::getName()
--FILE--
<?php
class MyClass {}

var_dump(__FILE__);

$reflection = new ReflectionClass('MyClass');
var_dump($reflection->getFileName());

?>
--EXPECTF--
string(%d) "%stest.phpt"
string(%d) "%stest.phpt"
```

Simply save this content in a file named `test.phpt` and run using phpunit vs php directly, e.g.:

```
$ phpunit test.phpt
$ php test.phpt
```

### Expected result

```
string(61) "/home/james/workspace/better-reflection/test/compat/test.phpt"
string(61) "/home/james/workspace/better-reflection/test/compat/test.phpt"
```

### Actual result

```
string(21) "test/compat/test.phpt"
string(1) "-"
```

Full output can be seen in [this gist](https://gist.github.com/asgrim/910c890058903f5a4fcb).

### Plot twist

If you pipe the file directly to PHP outside of phpunit, both `__FILE__` and `$reflection->getFileName()` are empty hyphen strings (`'-'`) - bizarre!

```
$ cat test/compat/test.phpt | php --
--TEST--
ReflectionClass::getName()
--FILE--
string(1) "-"
string(1) "-"
--EXPECTF--
string(%d) "%stest.phpt"
string(%d) "%stest.phpt"
```

**Comment by asgrim** [comment]
Oh - I see now the `__FILE__` constant gets replaced by the `PhptTestCase->render` method beforehand, hence why the `__FILE__` magic constant works, but the reflection file doesn't. I wonder if there is a way of telling PHP what the filename is when piping the code to it somehow?

**Comment by beberlei** [comment]
@asgrim phpt in phpunit uses eval, that leads to the `-`. One way would be to adjust the PhptRunner to put the file on disk as `.php` next to the `.phpt` like php's original runner does as well.

**Comment by Ocramius** [comment]
`phpt` doesn't use `eval`, but uses piping. Something along the lines of:

```sh
cat path/to/the/file.phpt | php --
```

This is what I found [in the PHPUnit codebase](https://github.com/sebastianbergmann/phpunit/blob/bbcc371da7d9c7d58d62f895156a87c395695a39/src/Util/PHP/Default.php#L28-L36), at least.

Digging further, I found related problems.

First of all, it seems like piping support in the CLI SAPI is quite broken:
 * https://github.com/php/php-src/blob/539db00538baeb24ba0ca3524b7bef796430dd21/sapi/cli/php_cli.c#L920-L927
 * https://bugs.php.net/bug.php?id=43283

Additionally, following scenarios cause issues too:

```sh
echo '<?php var_dump(defined("STDIN"));' | php --
echo '<?php var_dump(defined("STDOUT"));' | php --
echo '<?php var_dump(defined("STDERR"));' | php --
```
(weirdly, all report `bool(false)`)

`php://stdin` also reports empty content all the time:

```sh
echo '<?php var_dump(stream_get_contents(fopen("php://stdin", "r")));' | php --
```

The stream is not rewindable, so we can't really read from it.

Very similar weird behavior is exposed when using `php -r "code"` (similar/related issues)

**Comment by asgrim** [comment]
Yep, I think @beberlei's solution to write a temp PHP file overcomes this, but indeed that means completely rewriting the phpt executor I think :|

**Comment by Ocramius** [comment]
> but indeed that means completely rewriting the phpt executor I think :|

Probably better than relying on broken functionality in the CLI SAPI. I don't see these bugs being fixed any soon, given that also @johannes was blocked while trying to fix them.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
