### ISSUE TITLE
Mock Objects in PHP7 with return types.

### ISSUE THREAD

**Issue by derokorian** [sebastianbergmann/phpunit#1785]
I get problems with Fatal error: declaration of x must be compatible with y: type. Code to recreate the issue below:

    <?php
    class Foo {
       public function bar() : int {
          return 1;
       }
    }
    class FooTest extends PHPUnit_Framework_TestCase {
       public function testMock() {
          $mock = $this->getMock('Foo', ['bar']);
       }
    }

And the output:

    $ phpunit test.php
    PHPUnit 4.7.6 by Sebastian Bergmann and contributors.
     
    Fatal error: Declaration of Mock_Foo_53b3d027::bar() must be compatible with Foo::bar(): int in phar:///usr/bin/phpunit/phpunit-mock-objects/Framework/MockObject/Generator.php(301) : eval()'d code on line 1

**Comment by sebastianbergmann** [comment]
This has been implemented for PHPUnit 5.

Please note that this [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-mock-objects](https://github.com/sebastianbergmann/phpunit-mock-objects) project.

**Comment by derokorian** [comment]
Thanks for such a fast response, and my apologies for reporting to the incorrect repository. I will try using version 5.

**Comment by sebastianbergmann** [comment]
No worries. Bear in mind, though, that PHPUnit 5 is still in alpha.

**Comment by derokorian** [comment]
Yup, I totally understand. Just trying to get a head start on taking
advantage of PHP7 since its in beta now.

On Sat, Jul 11, 2015 at 11:48 AM, Sebastian Bergmann <
notifications@github.com> wrote:

> No worries. Bear in mind, though, that PHPUnit 5 is still in alpha.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sebastianbergmann/phpunit/issues/1785#issuecomment-120647914>
> .
>



-- 
*Ryan D Pallas*
http://rdennispallas.com
http://derokorian.com
As much for my benefit as it is for yours.
