### ISSUE TITLE
PHPUnit code coverage memory issues

### ISSUE THREAD

**Issue by ninja-saigon** [sebastianbergmann/phpunit#1786]
Running the test suite with a large of tests.

My results:
```
PHPUnit 3.7.28 by Sebastian Bergmann.  
Time: 5.32 hours, Memory: 6232.25Mb  
OK (8353 tests, 10919 assertions)  
```
With this result, the Clover XML and HTML were not generated. It seems, the phpunit has run out of memory.

**Comment by sebastianbergmann** [comment]
PHPUnit 3.7 is no longer supported. Does the problem persist with a current version of PHPUnit?

If memory really were an issue then you would see an error message from PHP.

Also note that this [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project.
