### ISSUE TITLE
Add option to fail test run when marked risky

### ISSUE THREAD

**Issue by rabbitfang** [sebastianbergmann/phpunit#1787]
While this is a duplicate of #1612, I feel like this issue would get more visibility if it was recreated.

This is a feature request to add a configuration option to mark risky tests as failed.

My personal use case is that the `--report-useless-tests` option is enabled, and I would like the test run to fail with a non-zero exit code if a useless test (tests with no assertions) is found. Empty tests could very well be a failed test in disguise, as the test (for instance) might run assertions in a loop on each item in a given iterable. Now, there should be assertions made to check that the loop body actually runs at least once, but this might be a non-obvious thing to do for the test writer, especially for more complicated tests.

The workaround for this issue is to watch the PHPUnit output and look for tests being marked as risky, but that can be difficult to work out.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
