### ISSUE TITLE
Minor issue on error message for assertSame

### ISSUE THREAD

**Issue by mirekratman** [sebastianbergmann/phpunit#1789]
When calling assertSame expecting as a result string "ok" as a example and method fails giving back "not_defined":
```
$this->assertSame($this->classApiClient->setItemRole('price1', 'name'), 'ok');
```

the error text looks:

```
Failed asserting that two strings are identical.
Expected :not_needed
Actual   :ok
```

I think there is small issue in error printing because expected value is 'ok' not 'not_needed'.
Error message should look:

```
Failed asserting that two strings are identical.
Expected :ok
Actual   :not_needed
```

**Comment by JoeBengalen** [comment]
How about passing the arguments the other way around ...

https://phpunit.de/manual/current/en/appendixes.assertions.html#appendixes.assertions.assertSame

**Comment by mirekratman** [comment]
make sense ;).
