### ISSUE TITLE
255

### ISSUE THREAD

**Issue by brooksie155** [sebastianbergmann/phpunit#1790]
Recently, presumably due to upgrading phpunit, I often seem to run into error code 255, which is run phpunit stops running tests part way through without any explanation as to why.

First time I discovered it was because and abstract method had not been defined in a new object .
Sometimes it simply because method being tested does not exist and now it seems the following is tripping it up, commenting out the line at least gives me output, even if the output is to say the test failed.

```php
        $this->randomPasswordPartGenerated = bin2hex(mcrypt_create_iv(32, MCRYPT_DEV_URANDOM));
```

Output 
```
$> phpunit --strict --no-globals-backup --colors  --configuration tests/phpunit.xml tests/../UsersDashboardTest.php
PHPUnit 4.7.6 by Sebastian Bergmann and contributors.
Warning:        Deprecated option "--strict" used

.255
```

Is it possible to at least catch the cause of '255' and state which __METHOD__ and __CLASS__ the violation occurred in?

**Comment by sebastianbergmann** [comment]
You can use `--debug` to have PHPUnit print the name of a test before it starts executing it.

**Comment by brooksie155** [comment]
Thanks for that - so next question, what might be likely reasons phpunit would exit with code 255? 
Cheers,

**Comment by sebastianbergmann** [comment]
IIRC, you get a 255 exit code for fatal errors. Maybe you're hiding the error somehow?

**Comment by alexislefebvre** [comment]
@brooksie155 Please update the title of this issue in order to summarize your problem.

**Comment by sebastianbergmann** [comment]
Likely not a PHPUnit issue.

**Comment by piersb** [comment]
If you set `display_errors = On` in your php.ini, it will give you details on the fatal error when phpunit runs.

**Comment by Jeffliu** [comment]
If you still couldn't found the fatal error,  add more arguments to your PHP script:
`--debug -d display_startup_errors=on  -d error_reporting=22527`

example:
` /usr/local/Cellar/php@5.6/5.6.40/bin/php -d display_errors=on /Users/xxx/dev/mm/web/lib/Vendor/vendor/phpunit/phpunit/phpunit --configuration /Users/xxx/dev/mm/web/lib/Vendor/phpunit.xml /Users/xxx/dev/mm/web/tests/db/OrderCreationCompTest.php  --debug -d display_startup_errors=on  -d error_reporting=22527`
