### ISSUE TITLE
phpunit exists unexpectedly when finds @covers tag for non-existing method

### ISSUE THREAD

**Issue by Gamesh** [sebastianbergmann/phpunit#1791]
```php
/**
 * @coversDefaultClass FooBar
 */
class FooBarTest extends PHPUnit_Framework_TestCase
{

    protected $object;

    public function setUp()
    {
        $this->object = new FooBar;
    }
    /**
     * @covers ::get
     */
    public function testSetProperty()
    {
        $this->assertNull($this->object->get());
    }

    /**
     * @covers ::nonExistingMethod
     */
    public function testSomeMethod()
    {
        $this->assertEquals(0, 0);
    }
    /**
     * @covers ::set
     * @covers ::get
     */
    public function testSomeOtherTest()
    {
        $this->object->set('test');
        $this->assertEquals('test', $this->object->get());
    }

}

class FooBar
{

    private $value = null;

    public function get()
    {
        return $this->value;
    }

    public function set($value)
    {
        $this->value = $value;
    }

}
```
Expected output:
.E.

Actual ouptut:
```
PHPUnit 4.7.7 by Sebastian Bergmann and contributors.
Warning:        No whitelist configured for code coverage

.Trying to @cover or @use not existing method "FooBar::nonExistingMethod".
```
ouptut with --debug:
```
PHPUnit 4.7.7 by Sebastian Bergmann and contributors.
Warning:        No whitelist configured for code coverage


Starting test 'FooBarTest::testSetProperty'.
.
Starting test 'FooBarTest::testSomeMethod'.
Trying to @cover or @use not existing method "FooBar::nonExistingMethod".
```

so the testSomeOtherTest() is not even executed.

**Comment by Gamesh** [comment]
Tested on latest phpunit v4.7.7, and on v4.6.10 result is the same
PHP 5.5.25 (cli) (built: May 14 2015 10:02:12)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.3.2, Copyright (c) 2002-2015, by Derick Rethans
    with blackfire v0.25.1, https://blackfire.io/, by SensioLabs

**Comment by sebastianbergmann** [comment]
This is expected behavior. See #1760 for more details.

**Comment by Gamesh** [comment]
in PHPUnit 3.7 it did just printout an error, which we could fix in PHPUnit 4.7 it just dies.
At least consider adding some information like it used to have, on what test the invalid ```@covers``` annotation was found, cause now it looks like the unit test encountered a fatal error and just exited in the middle of something.

**Comment by Gamesh** [comment]
this was taken from before the upgrade, on v4.7:
```
............................................................... 882 / 882 (100%)


Time: 10.01 minutes, Memory: 175.25Mb

There was 1 error:

1) SynchroModelTest::testProcessNewTasksInStatusReadyToSendWS
PHP_CodeCoverage_Exception: Trying to @cover not existing method "SynchroModel::getSynchroItemPriority".
```
now this i understand, and i see what the problem is and i can fix it. The current v4.7 output is unacceptable as it does not provide required information to fix the problem.

**Comment by ockcyp** [comment]
@Gamesh That problem has been very annoying for me. I once had to manually check all the `@covers` tags for 1300 tests. Here's a CLI tool I made for this purpose: [ockcyp/covers-validator](https://github.com/ockcyp/covers-validator)

**Comment by paolomainardi** [comment]
thanks a lot @oradwell, this is super useful!

**Comment by sebastianbergmann** [comment]
@oradwell Haven't looked at your tool yet but https://github.com/dunkelfrosch/phpcoverfish by @dunkelfrosch also exists.

**Comment by Gamesh** [comment]
all the tools are really great, i just wish PHPUnit would at least have the courtesy to print out the Class name of the test where it found the `@covers` tag of non existing method. Because if somebody forgot to add `@coversDefaultClass` and you have lots of classes with the same method names you are screwed.
