### ISSUE TITLE
Error treatment change compatibility between PHP 5.x and 7.

### ISSUE THREAD

**Issue by TendoAki** [sebastianbergmann/phpunit#1792]
The PHP 7 engine will throw exceptions in many events that are currently handled by errors in PHP 5.x. PHP Unit currently converts all error throws to PHPUnit_Framework_Error. It would be nice to have them converted to their PHP 7 equivalents instead so that newer unit tests don't have to worry about whether they are running under 5.x or 7.

For BC maintainence these exceptions should be children of PHPUnit_Framework_Error when PHP 5.x is running, this way expectedException calls on older tests will catch them when ran on the older PHP they are written for at least.  If PHP 7 is running it will directly throw the exception in question so the adjustment code shouldn't be an issue, but older tests will fail - note though that they're going to fail anyway.

For example, currently PHP runtime assertions (for disambiguation "runtime assertions" refers to PHP's assert() statement, not the assertions that are parts of the tests themselves) trigger E_WARNING by default. Their failure causes PHP Unit tests to fail with an error as outlined above. PHP 7 will throw an AssertionException when they fail.  If I'm writing a test of an assert() fail then the expected exception changes between PHP 5 and 7.

It is possible to mitigate this by writing an runtime assertion callback, and in the Drupal project I've created traits for this purpose. But having the default behavior outlined above as part of PHPUnit's core would be useful.

**Comment by sebastianbergmann** [comment]
Sorry, but I do have no idea what you are trying to {ask|report|propose}.

**Comment by GrahamCampbell** [comment]
Errors haven't changed since php 5. They still are the same if you don't catch throwable.

**Comment by TendoAki** [comment]
PHP 7 throws more specific exceptions than the errors triggered by PHP 5.x.  A particular example is assert().  If an assert() fails in PHP 5.x and assert.warn is set (which it is by default) an E_ERROR is triggered.  In PHP 7 an AssertionException is thrown.  In Drupal 8's PHPUnit bootstrap I'm adding the following code to compensate.

// Force PHP 5.x to handle runtime assertion failures in a similar enough
// manner to PHP 7 that tests will be able to work on either.
if (version_compare('7.0.0', PHP_VERSION) === 1) {
  class AssertionException extends Exception(){};
  assert_options(ASSERT_CALLBACK, function($file, $line, $code, $message = ''){
    if (empty($message)) {
      $message = "Assertion Failure in {$file} at {$line}. Failed asserting {$code}";
    }
    throw new AssertionException($message);
  });
}

One of the other maintainers over there mentioned that it would be nice to have this moved upstream. AssertionException isn't the only error who's signature is changing in PHP 7 -- nearly all functions that used to throw errors now throw exceptions.
I realize tests will need to opt in to this behavior for BC, but without it writing tests that cover behavior between PHP 5 and 7 will be more difficult than it needs to be.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
