### ISSUE TITLE
Annotation beforeClass with setUpBeforeClass

### ISSUE THREAD

**Issue by Rey8d01** [sebastianbergmann/phpunit#1794]
Hello. It may not be a problem, but it is there

```php
<?
Yii::import('system.test.CTestCase');

abstract class ExampleTestCase extends CDbTestCase implements IConstTest
{

    public static function setUpFixtures() {
        var_dump(__METHOD__);
    }

    /**
     * @beforeClass
     */
    public static function setUpBeforeClass() {
        var_dump(__METHOD__);
        parent::setUpBeforeClass();
        static::setUpFixtures();
    }

    /**
     * @before
     */
    public function setUp() {
        var_dump(__METHOD__);
        parent::setUp();
    }
}

class ExampleTest extends ExampleTestCase
{

    /**
     * @beforeClass
     */
    public static function beforeClass1() {
        var_dump(__METHOD__);
    }

    /**
     * @beforeClass
     */
    public static function beforeClass2() {
        var_dump(__METHOD__);
    }

    public function testMethod() {
        var_dump(42);die;
    }
}

```

result via PHPUnit 4.7.5

> PHPUnit 4.7.5 by Sebastian Bergmann and contributors.
> 
> string(33) "ExampleTestCase::setUpBeforeClass"
> string(30) "ExampleTestCase::setUpFixtures"
> string(25) "ExampleTest::beforeClass1"
> string(25) "ExampleTest::beforeClass2"
> string(22) "ExampleTestCase::setUp"
> int(42)
> 
> Process finished with exit code 0

result via PHPUnit 4.7.6

duplicated call methods **setUpFixtures** and **setUp** becose it used annotation **beforeClass** and **before**

> PHPUnit 4.7.6 by Sebastian Bergmann and contributors.
> 
> string(33) "ExampleTestCase::setUpBeforeClass"
> string(30) "ExampleTestCase::setUpFixtures"
> string(25) "ExampleTest::beforeClass1"
> string(25) "ExampleTest::beforeClass2"
> string(33) "ExampleTestCase::setUpBeforeClass"
> string(30) "ExampleTestCase::setUpFixtures"
> string(22) "ExampleTestCase::setUp"
> string(22) "ExampleTestCase::setUp"
> int(42)
> 
> Process finished with exit code 0

I think that it is related with the task #1763 - where is the error?

**Comment by GrahamCampbell** [comment]
Yes the behaviour was changed so that they are now inherited.
