### ISSUE TITLE
Traits with Abstract Methods Aren't Testable

### ISSUE THREAD

**Issue by Pittiplatsch** [sebastianbergmann/phpunit#1796]
Initial note: This is no dup of #766

I am trying to directly test the following trait:
```
trait FooTrait
{
    public function returnTrue()
    {
        return true;
    }

    /**
     * @return string
     */
    abstract protected function getFoo();
}
```
This trivial test:
```
public function test_trait()
{
    $trait = $this->getObjectForTrait(FooTrait::class);
    $this->assertTrue($trait->returnTrue());
}
```
results in:
`Fatal error: Class Trait_FooTrait_40dbdc77 contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Trait_FooTrait_40dbdc77::getFoo) in .../phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php(301) : eval()'d code on line 4`

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-mock-objects](https://github.com/sebastianbergmann/phpunit-mock-objects) project.

**Comment by Pittiplatsch** [comment]
Thx for the reply, and sorry for another wrongly filed issue :-(

**Comment by sebastianbergmann** [comment]
No worries. With this issue it's not really obvious that it belongs somewhere else.
