### ISSUE TITLE
Configurable default for --enforce-time-limit

### ISSUE THREAD

**Issue by Flyingmana** [sebastianbergmann/phpunit#1799]
Currently by default all tests without large or medium annotation are considered as small for the timeout.

I would like to either configure a custom timelimit for them, or at least a configurable default behavoir so I can say all tests are large by default so i can only define some specific ones as small

**Comment by sebastianbergmann** [comment]
As of PHPUnit 4.7 that should not be the case anymore, see https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-4.7.md#changed-1

**Comment by Flyingmana** [comment]
I see, did only look into the manual https://phpunit.de/manual/4.7/en/risky-tests.html#risky-tests.test-execution-timeout

Is there an option to set a default/global Timeout?

**Comment by Flyingmana** [comment]
If I provide a PR for a default timeout, would it get accepted?
Any hints where I need to look at for?

**Comment by sebastianbergmann** [comment]
The timeouts for tests annotated with `@small`, `@medium`, and `@large` can be configured and defaults exist. I do not understand what you want.

**Comment by Flyingmana** [comment]
I want a default for tests, which are not annotated with one of them.

We have >600 of them, the limit should be for all of them. But to add `@small` to all of them is quite a heavy task.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
