### ISSUE TITLE
phar stub issu

### ISSUE THREAD

**Issue by iakoder** [sebastianbergmann/phpunit#1800]
Obviously it's not a really big problem but I just noticed that when including phpunit into another script the __PHPUNIT_PHAR__ constant doesn't have the intended value.

    $files   = get_included_files();
    $phar    = $files[0];
    $execute = false;

define('__PHPUNIT_PHAR__', str_replace(DIRECTORY_SEPARATOR, '/', $phar));

get_included_files =>
[0] => /path/to/my script
[1] => /path/to/my auto_prepend_file
[2] => /path/to/phpunit.phar

I'm guessing you'd really want $phar = $files[count($files)-1].

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
