### ISSUE TITLE
PHPT fails on PHP7, not on PHP5 - possible bug in string pattern matching?

### ISSUE THREAD

**Issue by Ocramius** [sebastianbergmann/phpunit#1803]
I'm currently scratching my head around this PHPT test, which is failing for PHP 7 and not for PHP 5.6: https://gist.github.com/Ocramius/b140bae2d8b948c82382

I can't spot any particular difference between the two outputs (that wouldn't be handled by the matcher `%a`).

Does anybody have a clue on whether this may be a bug in PHPUnit or if there was a breaking change in PHP 7 that made PHPUnit fail on converting the matcher?

I can also provide more info if anybody can point me at things to dump...

**Comment by Ocramius** [comment]
Nothing to see here: had to replace `%s` with `%a` because PHP7 has stack traces for exceptions by default.

**Comment by sebastianbergmann** [comment]
Thanks for reporting back and closing the issue.
