### ISSUE TITLE
Provide a way for Selenium and Database testing

### ISSUE THREAD

**Issue by drczuckerman** [sebastianbergmann/phpunit#1806]
Since PHP does not support multiple inheritance, It would be nice if you could provide a class that could be used for combined Selenium and Database testing

**Comment by sebastianbergmann** [comment]
It is up to @giorgiosironi (maintainer of phpunit-selenium) and @elazar (maintainer of DbUnit) to also offer the functionality provided by `PHPUnit_Extensions_Selenium2TestCase` and `PHPUnit_Extensions_Database_TestCase`, respectively, as traits.

**Comment by sebastianbergmann** [comment]
https://github.com/sebastianbergmann/dbunit/commit/c5cada74d1e9a7aa0c26f90fcac950e45e89effd is a quick attempt at achieving this from the DbUnit side of things.

**Comment by drczuckerman** [comment]
Thanks, how do I get this change? I'm pretty new to GIT, and all I have is the PHP archive file that I downloaded from your site.
