### ISSUE TITLE
Allow test cases to be dependent on other testcases

### ISSUE THREAD

**Issue by dans98** [sebastianbergmann/phpunit#1809]
I believe phpunit needs a way to make a test case dependent on another test case. Consider the following example code that uses inheritance.

```php
trait AnimalTrait
{
    // some default methods & attributes
} 

class Animal
{
    use AnimalTrait;

    // some new methods & attributes that builds on AnimalTrait
}

class Cat extends Animal
{
    // some new methods & attributes that builds on Animal
}

class Dog extends Animal
{
    // some new methods & attributes that builds on Animal
}

class BullDog extends Dog
{
    // some new methods & attributes that builds on Dog
}
```

 If the AnimalTrait test case fails all the test cases for classes that use it directly, or extend a class that use it will also likely fail. This can yield a large number of test failures that can be hard to trace back to the root problem. This is specially true if the developer making changes isn't overly familiar with the code base, or the SUT is non trivial.

Currently @depends can be used in a hacky way to make test cases interdependent, but it's not full proof, or overly clear. 

Thus I'm requesting that phpunit introduce a new annotation or some other construct that allows test cases to be dependent on the passing of other test cases.

**Comment by dans98** [comment]
While doing more digging I came across this example from David Harkness, that uses onNotSuccessfulTest to set a static variable to indicate if the test case passed or not.

http://stackoverflow.com/questions/8835607/dependent-tests-between-two-testcase-classes-in-phpunit#answer-8840803

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
