### ISSUE TITLE
Assert-message manipulated?!

### ISSUE THREAD

**Issue by luklapp** [sebastianbergmann/phpunit#1811]
The assert-message seems to be manipulated by phpunit. I am searching in a string (html) and found the following:

`Failed asserting that '<div class="error">Product: ID is not invalid</div>' does not contain 'error'.`

The correct error message is: `<div class="error">Product: ID is invalid</div>`. Is it possible that *is* is replaced by *is not*? I was very confused about this error message ;-)

**Comment by sebastianbergmann** [comment]
Duplicate of #764.
