### ISSUE TITLE
 Process 'command './vendor/bin/phpunit.bat'' finished with non-zero exit value 2

### ISSUE THREAD

**Issue by HieronyM** [sebastianbergmann/phpunit#1812]
Dear @sebastianbergmann 

I am using phpunit v 4.7.7, I think it's such a great feature for Unit test in PHP platform
But i am hitting the wall when I run command line execution task from Gradle.
I run "gradle phpunit", and my phpunit task is like here.

```groovy
task phpunit (type : Exec, dependsOn : prepare, description : "Run unit tests with PHPUnit"){
	executable "$vendorDir/phpunit.bat"
	args "--coverage-html", "src"
}
```

The error command is :

```groovy
:phpunit FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':phpunit'.
> Process 'command './vendor/bin/phpunit.bat'' finished with non-zero exit value 2
```

Please help me figuring out what's wrong in my configurations.
Thanks.

**Comment by sebastianbergmann** [comment]
I neither use Gradle nor Windows so I am afraid that I won't be able to help.

**Comment by HieronyM** [comment]
Dear @sebastianbergmann 
Is any option in the command to ignore the error?
Thanks.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
