### ISSUE TITLE
PHPUnit Truck Factor

### ISSUE THREAD

**Issue by gavelino** [sebastianbergmann/phpunit#1814]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **PHPUnit** and obtained a value of **1**.

The developer responsible for this TF is:

Sebastian Bergmann - author of 85% of the files 

To validate our results, we would like to ask **PHPUnit** developers the following three brief questions:

(a) Do you agree that the listed developer is the main developer of **PHPUnit**?

(b) Do you agree that **PHPUnit** will be in trouble if the listed developer leave the project (e.g., if he wins in the lottery, to be less morbid)?

(c) Does **PHPUnit** have some characteristics that would attenuate the loss of the listed developer (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by sun** [comment]
> (a) Do you agree that the listed developer is the main developer of PHPUnit?

Yes.

> (b) Do you agree that PHPUnit will be in trouble if the listed developer leave the project (e.g., if he wins in the lottery, to be less morbid)?

No.

> (c) Does PHPUnit have some characteristics that would attenuate the loss of the listed developer (e.g., detailed documentation)?

Yes.

**Comment by sebastianbergmann** [comment]
Guilherme,

I am aware of your study but did not have time to read it fully yet.

One question that immediately came to mind was whether contributions in recent times are ranked differently than contributions during the early years of a project. PHPUnit, for instance, is now ~ 14 years old and for a very long time it was just me working on it. Over the last couple of years, however, the number of contributions has increased. That should answer question (a).

With regards to question (b), I don't think that PHPUnit would be in trouble in case I suddenly stopped maintaining it or working on it. I talk to users of PHPUnit a lot at my customers, at conferences, at usergroup meetings etc. One of the most common responses I get when I ask why they don't contribute to Open Source in general and PHPUnit in particular is that they don't see the need as others -- in the case of PHPUnit, me -- are doing "enough".

With regards to (c) I do think that I / the PHPUnit project could do better in providing help and lending support with getting started as a contributor to the project.

**Comment by gavelino** [comment]
Hi, 

>One question that immediately came to mind was whether contributions in recent times are ranked differently than contributions during the early years of a project.

@sebastianbergmann the answer for your question is no. Our approach do not treat different recent and past contributions.


Thanks for the answers.
