### ISSUE TITLE
TDD Question

### ISSUE THREAD

**Issue by TomBZombie** [sebastianbergmann/phpunit#1817]
Apologies, this is not an issue with PHPUnit at all but I wasn't really sure the best place to ask so can you point me in the direction of somewhere relevant for an answer if it's not relevant here? Thanks.

Let's say I have a class:

```php
class XMLSerializer {
	public function serialize($object) {
		$document = new DomDocument();
		$root = $document->createElement('object');
		$document->appendChild($root);

		foreach ($object as $key => $value) {
			$root->appendChild($document->createElement($key, $value);
		}

		return $document->saveXML();
	}

	public function unserialze($xml) {
		$document = new DomDocument();
		$document->loadXML($xml);

		$root = $document->getElementsByTagName('root')->item(0);

		$object = new stdclass;
		for ($i = 0; $i < $root->childNodes->length; $i++) {
			$element = $root->childNodes->item($i);
			$tagName = $element->tagName;
			$object->$tagName = $element->nodeValue();
		}

		return $object;
	}

}
```

How do I test this in isolation? When testing this class, I am also testing the DomDocument class

I could pass in the document object:

```php

class XMLSerializer {
	private $document;

	public function __construct(\DomDocument $document) {
		$this->document = $document;
	}

	public function serialize($object) {
		$root = $this->document->createElement('object');
		$this->document->appendChild($root);

		foreach ($object as $key => $value) {
			$root->appendChild($this->document->createElement($key, $value);
		}

		return $this->document->saveXML();
	}

	public function unserialze($xml) {
		$this->document->loadXML($xml);

		$root = $this->document->getElementsByTagName('root')->item(0);

		$object = new stdclass;
		for ($i = 0; $i < $root->childNodes->length; $i++) {
			$element = $root->childNodes->item($i);
			$tagName = $element->tagName;
			$object->$tagName = $element->nodeValue();
		}

		return $object;
	}

}
```

Which seems to solve the problem, however, now my test isn't really doing anything. I need to make a mock DomDocument return the XML I'm testing in the test:

```php

$object = new stdclass;
$object->foo = 'bar';

$mockDocument = $this->getMock('DomDocument')
				->expects($this->once())
				->method('saveXML')
				->will('returnValue('<?xml verison="1.0"?><root><foo>bar</foo></rooot>');

$serializer = new XMLSerializer($mockDocument);

$xml = $serializer->serialize($object);

$this->assertEquals($xml, '<?xml verison="1.0"?><root><foo>bar</foo></rooot>');
```

Which has several problems:

1) I'm not actually testing the method at all, all I'm checking is that the method returns the result of $document->saveXML()
2) The test is aware of the implementation of the method (it uses domdocument to generate the xml)
3) The test will fail if the class is rewritten to use simplexml or another xml library, even though it could be producing the correct result

so can I test this code in isolation? It looks like I can't.. is there a name for this type of dependency that can't be mocked as its behaviour is essentially required for the method being tested?

**Comment by sebastianbergmann** [comment]
I am sorry, but this is not a discussion forum. StackOverflow may be an appropriate forum for these kinds of questions.
