### ISSUE TITLE
Latest stable version triggers an "unrecognized option --run" error

### ISSUE THREAD

**Issue by agilis1** [sebastianbergmann/phpunit#1818]
The latest stable version of PHPUnit v4.8.3 results in an 'unrecognized option --run' error when used with NetBeans v8.0.2 (Latest) integration. Downgrading to PHPUnit v4.7.7 works correctly.

Example:

C:\wamp\www\sandbox\training\Calculator\tests>phpunit "C:\Program Files\NetBeans 8.0.2\php\phpunit\NetBeansSuite.php" "--run=CalculatorTest.php"

PHPUnit 4.8.3 by Sebastian Bergmann and contributors.

unrecognized option --run

**Comment by sebastianbergmann** [comment]
`--run` has never been an option supported by PHPUnit. Please report this with the vendor of your IDE.

**Comment by agilis1** [comment]
Hello there, I understand this may be an issue with the vendor of the IDE I'm using, but like I said above, it works with PHPUnit v4.7.7. Can you offer any insight on what the issue could be? Is this a parsing error or escape issue with the path?
