### ISSUE TITLE
Add options to `@runInSeparateProcess`

### ISSUE THREAD

**Issue by rentalhost** [sebastianbergmann/phpunit#1819]
Here on Windows I have a big problem with that: it is very slow. It take 3~5 seconds to run each test that run in separated process. And I use it to Code Coverage, for instance, but too use because in some cases I need run a method on start of execution.

So I suggest to command-line options to help with that:

 * `--separate-process=skip` will skip all tests or testcases that have options `@runInSeparateProcess` or `@runTestsInSeparateProcesses` annotation;
 * `--separate-process=inline` will run all tests or testcases in same process;

Obviously, it'll help only to you limit tests without specify it one-by-one on filter to develop in current task. And you will need run tests normally before you commit a change, after develop fully it.

**Comment by sebastianbergmann** [comment]
I think I would prefer to add tests that are to be run in a separate process to a "special" group that can be selected using `--group` or excluded using `--exclude-group` instead of adding new options such as `--separate-process=skip`.

I do not think that `--separate-process=inline` makes sense. If a test is marked for execution in a separate process that usually means that it won't work when not executed in a separate process.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
