### ISSUE TITLE
Installing PHPUnit.phar as per "Getting Started" seems to fail on OS X 10.9.5

### ISSUE THREAD

**Issue by muddletoes** [sebastianbergmann/phpunit#1827]
A fresh install of PHPUnit on Macintosh OS X 10.9.5 was made (new user), following the instructions on the [Getting Started with PHPUnit](https://phpunit.de/getting-started.html) page.  (Apple provides php version 5.4.40 with this system.) `curl` was used instead of `wget`.

A test case closely following the example was constructed.  `src/autoload.php` was implemented with [`spl_autoload_register()`](http://php.net/manual/en/function.spl-autoload-register.php), rather than relying on the magic [`__autoload()`](http://php.net/manual/en/language.oop5.autoload.php) class, as recommended by the manual page of the latter, and closely following an example given on the manual page of the former.

`phpunit --version` returns `PHPUnit 4.8.4 by Sebastian Bergmann and contributors.`  (Hi!)
`phpunit --bootstrap src/autoload.php tests/[ClassName]Test` throws the following warnings:

1.  `Warning: include(PHPUnit_Extensions_Story_TestCase.class.php): failed to open stream: No such file or directory in [....]/autoload.php on line 4`

2.  `Warning: include(): Failed opening 'PHPUnit_Extensions_Story_TestCase.class.php' for inclusion (include_path='.:') in [....]/autoload.php on line 4`

3.  `Warning: include(Composer\Autoload\ClassLoader.class.php): failed to open stream: No such file or directory in [....]/autoload.php on line 4`

4.  `Warning: include(): Failed opening 'Composer\Autoload\ClassLoader.class.php' for inclusion (include_path='.:') in [....]/autoload.php on line 4`

There are essentially two incidents, and two warnings for each incident.  I have no notion one way or the other whether these are a result of an unusual `php.ini` file on OS X, or a result of an undocumented or erroneous dependency on the part of PHPUnit.  To me, the empty include path suggests one, the mention of Composer suggests the other.

I have yet to find a report of this exact situation (or a fix) online, although similar PHP warnings were thrown in instances involving the old pear package.  I'm still looking for a solution.

Obviously, I would appreciate help and/or a fix to the distribution.

However, if this is both reproducible and a can't/won't fix situation, then I would suggest mentioning it in the introduction, as generally *NIX-like installation instructions do work on OS X;  one doesn't assume that OS X install instructions are 'missing'.

**Comment by sebastianbergmann** [comment]
Your autoloader tries to load sourcecode files for classes it is not responsible for.

**Comment by muddletoes** [comment]
## Solution 

Thanks for the hint.  I was able to figure out a solution via trial and error.  I am leaving it here for others like myself who are fumbling around with autoloading for the first time and don't really know what they're doing.  As `__autoload()` seems to be headed towards depreciation, it seems possible that others will encounter the problem of adapting to the SPL method without any explicit hand-holding instructions.

According to my experimentation, when using PHP version 5.5.27 and the SPL functions the required minimum configuration for the `autoload.php` script seems to be to invoke [spl_autoload()](http://php.net/manual/en/function.spl-autoload.php) within a function registered via [spl_autoload_register()](http://php.net/manual/en/function.spl-autoload-register.php).  

The convention expects that your class definition files will have the format `[ClassName].php`.  If you wish to change the file suffix, for instance to `[ClassName].class.php` as in the examples given at [php.net](http://www.php.net/), you will need to use [spl_autoload_extensions()](http://php.net/manual/en/function.spl-autoload-extensions.php) to specify the correct suffix.  (e.g `spl_autoload_extensions('.class.php');`)

The autoloading functions do not seem to handle interfaces;  I am still including them explicitly in my class files.  It is very possible that there is a correct way to do this that is unknown to me.


`autoload.php` configured for the Getting Started page:

```php
<?php
// set suffix if different than ".php", e.g. to ".class.php":
// spl_autoload_extensions('.class.php');
spl_autoload_register(  
     function( $class ) {
          return spl_autoload( $class );  
     } );


```
