### ISSUE TITLE
Can't pass a parameter with @dataProvider + @depends

### ISSUE THREAD

**Issue by nobuf** [sebastianbergmann/phpunit#183]
I'm expecting the below code returns no failure. But on testDataReceiver(), $a will be null unexpectedly. I'm not sure if it's a bug. Can anyone test this code or correct my code? Thanks.

PHPUnit 3.5.11, PHP 5.3.3

```
<?php

class DataProviderTest extends PHPUnit_Framework_TestCase
{
    const TEST_NUM = 7;
    /**
     *  @dataProvider provider
     */
    public function testDataProvider($a)
    {
        $this->assertTrue($a === self::TEST_NUM);
        return $a;
    }
    /**
     *  @depends testDataProvider
     */
    public function testDataReceiver($a)
    {
        // somehow $a will be null
        $this->assertTrue($a === self::TEST_NUM);
    }
    public function provider()
    {
        return array(array(self::TEST_NUM));
    }
}
```

**Comment by sweiguny** [comment]
why is this closed?
I have the opinion, too, that @depends should be aware of @dataprovider of the dependet test method.

**Comment by mikolajzieba** [comment]
Anything changed in that matter? Is there any way to run @depends with @dataProvider without looping inside test?

**Comment by waleoyediran** [comment]
Can we re-open this issue?
Seem like a legitimate use case

**Comment by temple** [comment]
This issue shall not be closed.
Stills being an issue on `@depends` which provides no return data to dependent tests.
I'm facing how could I get the return of a test as the input for the dependent, but If I use a `@dataProvider` on the first test, its dependent just receives NULL as input.

**Comment by Ravim-addweb** [comment]
> This issue shall not be closed.
> Stills being an issue on `@depends` which provides no return data to dependent tests.
> I'm facing how could I get the return of a test as the input for the dependent, but If I use a `@dataProvider` on the first test, its dependent just receives NULL as input.

@temple - that is correct and I wonder there is no concrete solution for this yet.

**Comment by Stalinko** [comment]
Just started to write tests recently and immediately stepped into this bug. So weird it is still not resolved and there is no good workaround. So now I have to rewrite my tests into something ugly without data providers and with custom error messages.

My case (simplified example):

```php
class MyTest extends TestCase
{
    public function cache100(): array
    {
        return [/* 100 values here */];
    }

    /**
     * @dataProvider cache100
     * @param array $entry
     * @return array
     */
    public function testA(array $entry): array
    {
        //some heavy calculation here...
        return [/* result */];
    }

    /**
     * @dataProvider cache100
     * @param array $entry
     * @return array
     */
    public function testB(array $entry): array
    {
        //some heavy calculation here...
        return [/* result */];
    }

    /**
     * @dataProvider cache100
     * @depends      testA
     * @depends      testB
     */
    public function testC(array $entry, array $valueA, array $valueB)
    {
        $valueC = $valueA * $valueB;
    }
}
```

Now I think the only way to make it work is refuse from dataProviders in testA and testB and rewrite the code into loops. But this is ugly :(

**Comment by natsu90** [comment]
10 years later but this is still not resolved. Seems there is no workaround so I have to remove the dataProvider and put the data in a variable in the test function like a peasant :(

**Comment by PercyDwn** [comment]
I was really confused why my tests weren't working. Thank god i found this issue thread, so at least i know that it's not my fault.
But still unhappy, that this bug is already this old and as it looks won't be fixed...

**Comment by BonBonSlick** [comment]
issue still exists ;(

**Comment by AndreyChursin** [comment]
Maybe someone needs a solution (dirty solution):

     private static $dependsResultList = [];
     
     /**
     * Check test create new object and delete this one
     * @dataProvider someDataList
     * @param any $data
     */
    public function testCreate($data): void
    {
        $contragentObject = .....
        static::$dependsResultList[md5(serialize($data))] = $contragentObject;
    }
    
    /**
     * @dataProvider contragentDataList
     * @depends testCreate
     */
    public function testEdit($data): void
    {
        $contragentObject = static::$dependsResultList[md5(serialize($data))];
        ....
    }
