### ISSUE TITLE
test coverage tool doesn't report code coverage for the target production code. It reports for the test code instead.

### ISSUE THREAD

**Issue by HappyRay** [sebastianbergmann/phpunit#1830]
e.g 
Testing [this test file](https://github.com/box/TestScribe/blob/master/tests/Unit/Utils/ClassNameUtilGenTest.php)

I got:

php ~/phar/phpunit.phar --coverage-text /Users/ryang/github/TestScribe/tests/Unit/Utils/ClassNameUtilGenTest.php
PHPUnit 4.8.4 by Sebastian Bergmann and contributors.

Runtime:	PHP 5.4.37 with Xdebug 2.2.3
Configuration:	/Users/ryang/github/TestScribe/phpunit.xml

..

Time: 345 ms, Memory: 19.00Mb

OK (2 tests, 2 assertions)

Code Coverage Report:
  2015-08-18 10:28:56

 Summary:
  Classes:  0.00% (0/122)
  Methods:  0.00% (0/328)
  Lines:    0.00% (0/5080)

----

If I remove @cover annotations I got 

php ~/phar/phpunit.phar --coverage-text /Users/ryang/github/TestScribe/tests/Unit/Utils/ClassNameUtilGenTest.php
PHPUnit 4.8.4 by Sebastian Bergmann and contributors.

Runtime:	PHP 5.4.37 with Xdebug 2.2.3
Configuration:	/Users/ryang/github/TestScribe/phpunit.xml

..

Time: 324 ms, Memory: 19.00Mb

OK (2 tests, 2 assertions)

Code Coverage Report:
  2015-08-18 10:30:42

 Summary:
  Classes:  0.82% (1/122)
  Methods:  0.61% (2/328)
  Lines:    0.28% (14/5080)

\Box\TestScribe\Utils::ClassNameUtilGenTest
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% ( 14/ 14)

Notice that the file getting covered is the test file itself.

I reproduced the same with phpunit 4.5.1 too.

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project.

**Comment by HappyRay** [comment]
Done. https://github.com/sebastianbergmann/php-code-coverage/issues/379
