### ISSUE TITLE
Tests with exception expectations marked as risky

### ISSUE THREAD

**Issue by Bilge** [sebastianbergmann/phpunit#1832]
Even when a test is set up to expect an Exception type is raised it is still marked as risky. This type of test is not risky because it defines an expectation.

**Comment by sebastianbergmann** [comment]
I cannot reproduce this:

```php
<?php
class Test extends PHPUnit_Framework_TestCase
{
    /**
     * @expectedException Exception
     */
    public function testOne()
    {
        throw new Exception;
    }
}
```

```
$ phpunit --report-useless-tests Test
PHPUnit 4.8.5 by Sebastian Bergmann and contributors.

.

Time: 51 ms, Memory: 5.00Mb

OK (1 test, 1 assertion)
```

**Comment by Bilge** [comment]
It seems this only happens when the exception is thrown inside an output buffering block.

```php
<?php
class Test extends PHPUnit_Framework_TestCase
{
    /**
     * @expectedException Exception
     */
    public function testOne()
    {
        ob_start();
        throw new Exception;
        ob_end_flush();
    }
}
```

**Comment by czim** [comment]
Can confirm. I'd like to see this issue re-opened.

**Comment by flobee** [comment]
phpunit 6.5.7; php 7.0, php7.1, php7.2.2.1
```
..
$this->expectException('SomeException');
ob_start();
$object->run(  ); // outputs some data to STDOUT and then an exception is expected and thrown
ob_end_clean();
..
```
-> Test code or tested code did not (only) close its own output buffers
Marked as Risky :/ hmm
Any hints for me?
Without the output buffer the test succeed but with the output i just want to hide

Kind regards Florian
