### ISSUE TITLE
find a possible bug

### ISSUE THREAD

**Issue by omid-khd** [sebastianbergmann/phpunit#1833]
in my code i used array_filter function with ARRAY_FILTER_USE_KEY flag and run the test.
the unusual thing is when i don't follow test* convention the test pass but if i add test word before the name of my test function test fail and says that :
```
PHPUnit 4.8.3 by Sebastian Bergmann and contributors.

..E........
Time: 3.38 seconds, Memory: 10.00Mb
There was 1 error:

1) curlFatherTest::testGetOneOption
Use of undefined constant ARRAY_FILTER_USE_KEY - assumed 'ARRAY_FILTER_USE_KEY'

C:\wamp\www\Curl\src\curlFather.php:181
C:\wamp\www\Curl\src\curlFather.php:198
C:\wamp\www\Curl\tests\curlFatherTest.php:78

FAILURES!
Tests: 11, Assertions: 26, Errors: 1.
```

and this is my test subject function:
```php
    public function getOptions($options = [])	{
		$options = !is_array($options) && !empty($options) ? [$options] : $options;
		if (!empty($options)) {
			return array_filter(
				$this->optionsToSet,
				function($optionsToSetKey) use ($options){
					return in_array($optionsToSetKey, $options);
				},
				ARRAY_FILTER_USE_KEY
			);
		}
		return $this->optionsToSet;
	}
```    
so is this a bug or somewhere i making a mistake?

**Comment by GrahamCampbell** [comment]
You need php 5.6 to use that constant.

**Comment by omid-khd** [comment]
but if i delete the test word from the name of the test it will pass without having php 5.6 on my machine

**Comment by GrahamCampbell** [comment]
> but if i delete the test word from the name of the test it will pass without having php 5.6 on my machine

That's because phpunit doesn't run the test...

**Comment by GrahamCampbell** [comment]
It doesn't fail because it doesnt run.
