### ISSUE TITLE
Skipped test reported as errored since 4.7.4

### ISSUE THREAD

**Issue by OndraM** [sebastianbergmann/phpunit#1835]
Hi,
we use custom TestListener and log results of each test. But I started to notice skipped tests are in recent PHPUnit version reported as having status *4* (= `STATUS_ERROR`), instead of *1* (= `STATUS_SKIPPED`). I found the regression appears since PHPUnit 4.7.4:

SkippedTest.php:
```php
class SkippedTest extends \PHPUnit_Framework_TestCase
{
    public function testSkipped()
    {
        $this->markTestSkipped('Skipped test');
    }
}
```

TestStatusListener.php
```php
...
    public function endTest(PHPUnit_Framework_Test $test, $time)
    {
        printf("Test '%s' ended with status %d\n", $test->getName(), $test->getStatus());
    }
...
```

Output of up to version 4.7.3:
```
PHPUnit 4.7.3 by Sebastian Bergmann and contributors.

STest 'testSkipped' ended with status 1
```

Output since 4.7.4:
```
PHPUnit 4.7.4 by Sebastian Bergmann and contributors.

STest 'testSkipped' ended with status 4
```

Also tried with current PHPUnit master (0d7b83e), it still returns `4`.

I guess this is not intentional?

**Comment by GrahamCampbell** [comment]
I can't replicate this with phpunit 4.8.5?

**Comment by OndraM** [comment]
I prepared example project showing the problem: https://github.com/OndraM/phpunit-test-status-bug

And this is Travis output from it: https://travis-ci.org/OndraM/phpunit-test-status-bug/builds/76902524

**Comment by GrahamCampbell** [comment]
This looks like it's caused by `OndraM\TestStatusListener`?

**Comment by GrahamCampbell** [comment]
Or rather, other projects I see on travis that have skipped tests don't fail like this.

**Comment by GrahamCampbell** [comment]
PHPUnit's own test suite has a skipped test and it exists with the correct status code.

**Comment by OndraM** [comment]
?

The problem is that `$test->getStatus()` called inside the listener returns 4, even though the test was actually skipped and 1 should be returned. The PHPUnit output print the test as skipped in both cases - that is not the problem. Problem is the actual `status` value of the Test instance in the moment when the `endTest` is called.

**Comment by GrahamCampbell** [comment]
Oh, right, I see. Sorry I miss understood. :)

**Comment by GrahamCampbell** [comment]
Thanks for not table flipping at me. :)

**Comment by OndraM** [comment]
Ok, I found the problem and fixed it ;-).
