### ISSUE TITLE
Output coloring - make bold, or make configurable

### ISSUE THREAD

**Issue by anlutro** [sebastianbergmann/phpunit#1843]
I've configured my terminal so that the default "white" is actually grey and the red has been desaturated, as it's far easier on the eyes. As a result, white text on red background can be somewhat hard to read.

If the foreground color is bold white instead, that makes it completely white, which is far easier to read.

I'm wondering if it could be made possible to configure the output colors as defined in [ResultPrinter](https://github.com/sebastianbergmann/phpunit/blob/5.0/src/TextUI/ResultPrinter.php), or if white text on any non-black background could just be made bold by default.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
