### ISSUE TITLE
PHPUnit 3.7.29 shows colors it output, but not in test diffs

### ISSUE THREAD

**Issue by dennis-fedco** [sebastianbergmann/phpunit#1845]
I am using PHPUnit 3.7.29 using MingW64.

I can see color highlighting for output during test failures but the DIFF of test output is not highlighted.

Has there been a change in the diff output color highlighting?  Previous version I had, seemed to have it.

![testbench](https://cloud.githubusercontent.com/assets/5579367/9611398/69247130-50ad-11e5-9de6-92f1d8b0a973.png)

**Comment by sebastianbergmann** [comment]
There were never colors in the diffs.
