### ISSUE TITLE
.phpt tests fail when the expected output includes the file name

### ISSUE THREAD

**Issue by cweagans** [sebastianbergmann/phpunit#1847]
I'm running the entire mcrypt test suite from php-src for a project I'm working on, and running those tests fails for tests where the expected output includes the filename of the test (which is pretty common when a warning is expected). This is the test output:

```
There were 4 failures:

1) /Users/cweagans/Code/mcrypt-polyfill/tests/5.6/bug35496.phpt
Failed asserting that format description matches text.
--- Expected
+++ Actual
@@ @@
-Warning: mcrypt_generic(): Operation disallowed prior to mcrypt_generic_init(). in %sbug35496.php on line 3
+Warning: mcrypt_generic(): Operation disallowed prior to mcrypt_generic_init(). in - on line 3

-Warning: mdecrypt_generic(): Operation disallowed prior to mcrypt_generic_init(). in %sbug35496.php on line 4
+Warning: mdecrypt_generic(): Operation disallowed prior to mcrypt_generic_init(). in - on line 4

2) /Users/cweagans/Code/mcrypt-polyfill/tests/5.6/bug41252.phpt
Failed asserting that format description matches text.
--- Expected
+++ Actual
@@ @@
-Warning: mcrypt_generic(): Operation disallowed prior to mcrypt_generic_init(). in %sbug41252.php on line 3
+Warning: mcrypt_generic(): Operation disallowed prior to mcrypt_generic_init(). in - on line 3
 I'm alive!

3) /Users/cweagans/Code/mcrypt-polyfill/tests/5.6/bug43143.phpt
Failed asserting that format description matches text.
--- Expected
+++ Actual
@@ @@
 ECB
 CFB

-Warning: mcrypt_encrypt(): Encryption mode requires an initialization vector of size 32 in %sbug43143.php on line 9
+Warning: mcrypt_encrypt(): Encryption mode requires an initialization vector of size 32 in - on line 9
 END

4) /Users/cweagans/Code/mcrypt-polyfill/tests/5.6/bug49738.phpt
Failed asserting that format description matches text.
--- Expected
+++ Actual
@@ @@
-Warning: mcrypt_generic(): Operation disallowed prior to mcrypt_generic_init(). in %sbug49738.php on line 5
+Warning: mcrypt_generic(): Operation disallowed prior to mcrypt_generic_init(). in - on line 5
```

I'm not sure how to go about solving this in a generalized way (beyond just working with the php-src tests). I'm also not sure if this fix belongs in PHPUnit or not, as most people are likely not running the php-src tests with PHPUnit.

**Comment by henriquemoody** [comment]
That's because PHPUnit doesn't create a temporary file to run tests, like PHP test suite does, the code in the `--FILE--` section are executed in interactive mode on PHPUnit, so the filename is something like `-`.

It can be implemented on PHPUnit, but the suite will probably be slowest.

**Comment by cweagans** [comment]
@henriquemoody That makes sense. I don't think we need to write out a temp file for phpt test runs, though. That has a negative impact on everyone using it to solve a problem for a (likely) very small percentage of those people. It might be easier to just find instances where `%sbug49738.php` (or whatever) are present in the expected output, and removing it. It's weird to have a test runner modify the expected results of a test, but in this case, I think it'd be okay, especially if it's an optional thing (opt in via a command line flag or something).

**Comment by cweagans** [comment]
@henriquemoody do you happen to know if there's a way to override `PHPUnit_Extensions_PhptTestCase` inside my project (i.e. without directly modifying PHPunit)?

**Comment by cweagans** [comment]
There doesn't seem to be a way to do what I want in a clean way. Opened https://github.com/sebastianbergmann/phpunit/issues/1849 with details.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
