### ISSUE TITLE
PhpUnit periodically slow on Windows

### ISSUE THREAD

**Issue by mindplay-dk** [sebastianbergmann/phpunit#1848]
Historically, [this](http://i.imgur.com/mOD4sIq.gifv) is why I haven't used PhpUnit... 8 seconds to run a totally trivial suite of unit-tests IMO is *way* too long - these are flat, simple, local tests, no network operations involved, just plain unit-tests, no loops, nothing time-consuming.

Whether you think the time is acceptable or not, here's what's weird:

Earlier today, this test-suite turned around in about 300 milliseconds.

Then, all of a sudden, out of the blue, it slows down tremendously.

Mind you, I changed *nothing* - I was just sitting here, working, writing tests, running them every minute or so, and then, for no apparent reason, suddenly the whole thing slows down by x 100 or so.

  * I did not pull from Git - it's not changes made by anybody else.
  * I did not `composer update` or touch `php.ini`, nor did I install anything, or change any system settings.
  * It's not due to any change I made - I reverted my most recent changes, and that changes nothing.
  * It's not the code - it stalls while running many of the other tests, which were previously running without problems, I never touched any of those.
  * I didn't toggle `xdebug` or turn code coverage on/off.
  * There's no background task or anything hogging the CPU or slamming the disk.
  * It's not temporary - I rebooted my system twice to be sure.

Historically, this is how PhpUnit has always performed for me, which is why I've never used it. I'm a Windows user, and this has always been the same, under XP, Win 7, Win 8 and now Win 10, running every PHP version from 5.3 up to 7.0, on systems with completely different configurations.

The system I'm on today is an i7 with 8 GB RAM, 256 GB SSD, and was more than capable of running this test-suite just this morning, then, for no reason, it slows to a crawl. (I've never had these issues with my own plain PHP test-suites, the largest ones of which turn around in under a second.)

These past couple of weeks, after I started working with PhpUnit again, I was surprised at the speed - I was cheery about it this morning, how wonderfully fast it was, and how much work I was getting done. Then, suddenly, no more.

Please let me know how I can help. We've committed ourselves to PhpUnit, and I have to live with this probably for years to come, so frankly, I'm desperate. There has got to be a reason why it performs like this on Windows, and there must be an explanation as to why it's periodic - if it was consistently slow on Windows, that would be one thing, but at times it's totally fine; there's no logical reason it shouldn't perform at it's peak all the time - and there's certainly no reason it should be expected to slow down *that* drastically.

Can you think of any reason why performance would be so unpredictable on Windows?

Any ideas for anything I can try that would indicate any possible source of this slowness?

Anything I can do to profile or analyze this?

Thanks.

**Comment by mindplay-dk** [comment]
It appears the problem is getting worse. I'm now up to 15-20 seconds for a test run.

It's as though every added test makes *every* other test run slower - some individual tests stall for 1-2 seconds now, and it's not that any of them have been modified. Many of these tests should take just a few milliseconds to run.

**Comment by sebastianbergmann** [comment]
This is the first time I hear about this. It makes no sense to me.

**Comment by mindplay-dk** [comment]
It's something related to xdebug.

I'm now up to 25 seconds now for a test-run, and it gets slower every time I run it.

Disable xdebug, and it runs the whole suite in 0.17 sec.

Now, before you close this issue, hear me out - this does not appear to be an xdebug issue.

I just ran one of my own custom test-suites, e.g. not using php-unit, but I *do* use `phpunit/php-code-coverage`, and the whole suite runs in like 50 milliseconds, with code coverage enabled and output in clover format, same as when I run my phpunit test-suites. (This is a comparable test-suite in terms of complexity - no large datasets, no loops, no file-system operations, just a bunch of plain unit-tests.)

I forgot to mention, I'm using codeception, so php-unit is being dispatched via `codecept`, but is there any way codeception could be causing this issue? (I don't think it does anything in particular to modify code coverage or reporting.)

In fact, earlier, I had substantially faster turn-around with codeception than I ever did with bare php-unit, for some reason - that was part of the reason I started using it. In hindsight, this was probably because I was using the `.phar` distribution, and recently we started installing the whole thing as composer dependencies instead - which should account for a performance hit, and did cause a noticeable slow-down, but nothing this substantial.

I know that PHP file-system operations on on Windows are notoriously slow compared with Linux, but it went from "instant" to "less than one second", which was still totally fine.

@derickr @Naktibalda Would you be so kind as to take a look at this thread and see what you make of this?

**Comment by mindplay-dk** [comment]
I may have spotted a pattern.

It appears this issue is worsened (tremendously) by implementing "Cest" tests with Codeception.

So the issue *may* be narrowed down to "Cest" tests with Codeception, with xdebug enabled - there is a huge delay, sometimes 1-2 seconds, at the beginning of every individual test class.

@Naktibalda what do you make of this? Is there some kind of extra (expensive, possibly redundant) initialization that "Cest" tests make, that ordinary TestCase tests do not? Something related to xdebug, like code coverage maybe?

**Comment by mindplay-dk** [comment]
Okay, I replaced my PHP and xdebug installations with a different build - tests now run in ~ 3 seconds, which is acceptable. Looks like this was a bug in xdebug and/or the PHP build I had installed. Go figure.

**Comment by sebastianbergmann** [comment]
For posterity's sake, could you please provide information as to which versions of PHP and Xdebug you replaced with which other versions, @mindplay-dk? Thanks!

**Comment by mindplay-dk** [comment]
I had PHP 5.6.6 with xdebug 2.2.7 previously.

I replaced it with PHP 5.6.12 and xdebug 2.3.3.

Both the new and previous versions were 64-bit builds, both came from some release of the [WPN-XM](http://wpn-xm.org/) full-stack distribution - I don't know the precise release numbers.
