### ISSUE TITLE
It's impossible to override behaviors of `PHPUnit_Extensions_PhptTestCase`

### ISSUE THREAD

**Issue by cweagans** [sebastianbergmann/phpunit#1849]
In my scenario, I want to completely disregard the SKIPIF section of a phpt file.

I created `McryptTestSuiteLoader` (extends `PHPUnit_Runner_StandardTestSuiteLoader`), `McryptTestSuite` (extends `PHPUnit_Extensions_PhptTestSuite`), and `McryptPhptTestCase` (extends `PHPUnit_Extensions_PhptTestCase`). I created `public function run()` in my TestCase class, which is basically a copy/paste + modified version of the parent class method with the SKIPIF section removed. Unfortunately, `$this->parse()` and `$this->render()` are both private methods.

This is not good. I should be able to extend any class and override the method. Given that it's impossible to foresee all possible uses of a class method in every context, I'm wondering why these methods are private in the first place. They really ought to be protected instead.

Of course, this is probably kind of a hacky solution to do what I want. If there's a better way to approach it, I'm all ears, but I didn't see anything in the documentation that indicated there was another way.

Thoughts?

**Comment by sebastianbergmann** [comment]
* Ignoring the `SKIPIF` section makes no sense to me and is, AFAIK, not supported by the original PHPT runner
* The point of `PHPUnit_Extensions_PhptTestCase` is to be as close to the original PHPT runner as possible
* The design of PHPUnit's current test runner does not allow for swapping in custom implementations of `PHPUnit_Extensions_PhptTestCase`
* With regard to your statement about `private` vs. `protected` methods: I follow the "`private` until proven `public`" design philosophy and declare methods `private` by default and only open them up when it becomes necessary

**Comment by cweagans** [comment]
I'm writing a polyfill for ext_mcrypt. All of the photos tests in php-src for ext_mcrypt are skipped if the extension is disabled, but I want to run them even if the extension is disabled so that I can ensure that my polyfill works identically to ext_mcrypt.

The only way that I can do this with PHPunit is to just patch the PhptTestCase class. To me, this is indicative of a design flaw. As I said, I could make it work if those methods were protected.

I get that it should be as close to the original phpt runner as possible, but it seems very shortsighted to assume (and even enforce by making you methods private) that nobody will ever want it to work differently.

**Comment by sebastianbergmann** [comment]
You seem to have missed my final point in https://github.com/sebastianbergmann/phpunit/issues/1849#issuecomment-137831279.

If you are telling me that opening these methods up (declaring them `protected`) solves your problem then I will gladly do so. Before you nobody needed them to be `protected` so they were `private`.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
