### ISSUE TITLE
PHPUnit becomes much slower when installed through composer but uses less memory

### ISSUE THREAD

**Issue by marlun** [sebastianbergmann/phpunit#1851]
If I download phpunit.phar (version 4.8) from the webpage and run `phpunit tests` they are finished in Time: 490 ms, Memory: 13.25Mb. If I install it using composer and run `vendor/bin/phpunit tests` they are finished in Time: 3.14 seconds, Memory: 4.75Mb. No idea why it becomes so much slower but uses less memory? They are both the same version: 4.8.6.

**Comment by sebastianbergmann** [comment]
This is to be expected. The PHAR does not use autoloading but instead loads all classes on startup.

**Comment by marlun** [comment]
Even if you add `--bootstrap vendor/autoload.php` because it's just as fast then? Not sure I understand what you mean.
