### ISSUE TITLE
Measuring interface (and abstract method) coverage?

### ISSUE THREAD

**Issue by mindplay-dk** [sebastianbergmann/phpunit#1854]
It occurs to me, it would be possible to measure coverage of both interfaces and abstract methods - even though these are never *called*, it should be possible (and meaningful) to measure whether they've been *covered*.

Example:

```php
interface Worker {
    public function work();
}

class Controller {
    abstract public function run();
}

class Something extends Controller implements Worker {
    public function work() { ... }
    public function run() { ... }
}
```

In this example, when coverage of `Something::work()` is registered, we can tell from the `implements` clause that `Worker::work()` has been covered - and when `Something::run()` is called, we can tell from the `extends` clause that `Controller::run()` has been covered.

If no test covers the usage of e.g. the `Worker` interface or the abstract `Controller::run()` method, it's fair to say that these weren't covered by tests, is it not? Even if one of these interfaces is intended for consumers to fill in, you should probably be writing a mock implementation for testing, to assert that the interfaces/methods were called with the correct arguments.

I guess, whether you agree with this, would depend on your definition of "coverage" - if you mean, "it has been run", obviously abstract methods and interfaces are never "run", because they're declarations. The term "coverage", to me, doesn't imply execution - it implies it's "covered" by tests, which interfaces and abstract methods can be, by implementing mocks and testing how they integrate with your other code units.

What do you think?

**Comment by sebastianbergmann** [comment]
At first glance it does not make sense to me.

Please note that this [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project. Feel free to reopen it there.
