### ISSUE TITLE
error while executing PHPunit Array to string conversion

### ISSUE THREAD

**Issue by abhijeetka** [sebastianbergmann/phpunit#1856]
facing issues while running phpunit 

error message: 

 {"error":{"type":"ErrorException","message":"Array to string conversion","file":"\/home\/ajinkyab\/Docker\/workspace\/ALM_Task_Manager_Feature\/vendor\/phpunit\/php-token-stream\/src\/Token\/Stream.php","line":438}}

Building Laravel 4.* framework

**Comment by sebastianbergmann** [comment]
Fixed via https://github.com/sebastianbergmann/php-token-stream/pull/53

**Comment by abhijeetka** [comment]
Thanks Sebastian.
