### ISSUE TITLE
'uses' and 'covers' should only take a single word

### ISSUE THREAD

**Issue by KingCrunch** [sebastianbergmann/phpunit#1857]
I'd like to comment, why it's OK for a test to `@uses` a different class, or method like

```php
/**
 * @uses Foo\Bar This is a value object
 */
```
This fails with

    Trying to @cover or @use not existing class or interface "Foo\Bar This is a value object".

Because it is not possible to refer to a class, or method with a whitespace PHPUnit should only take the first word after the annotation and should leave everything else as a comment

**Comment by sebastianbergmann** [comment]
Makes sense to me. I'll gladly accept a pull request that adapts the respective regular expressions.

**Comment by KingCrunch** [comment]
@dstockto Thanks :)

**Comment by dstockto** [comment]
@KingCrunch No problem. I hope I didn't break anything :)
