### ISSUE TITLE
PHP7 (RC3): TypeError: Argument 1 passed to PHPUnit_Framework_TestCase::onNotSuccessfulTest()

### ISSUE THREAD

**Issue by alecpl** [sebastianbergmann/phpunit#1859]
TypeError: Argument 1 passed to PHPUnit_Framework_TestCase::onNotSuccessfulTest() must be an instance of Exception, instance of Error given, called in /home/alec/repos/roundcubemail/vendor/phpunit/phpunit/src/Framework/TestCase.php on line 851

I got it on one of my tests that used random_bytes() function with invalid argument and it did not catch the Error. This is related to this new RFC https://wiki.php.net/rfc/random-function-exceptions

**Comment by GrahamCampbell** [comment]
Is this issue still present on phpunit 5?

**Comment by sebastianbergmann** [comment]
No, this is not present in PHPUnit 5.
