### ISSUE TITLE
4.8 BC break

### ISSUE THREAD

**Issue by m6w6** [sebastianbergmann/phpunit#1863]
I coudn't find anything in the ChangeLogs, but 4.8 breaks PHPUnit support in NetBeans due to dropped --run command line option.

Verified with 4.8.0 and 4.8.9 -- everything's okay with <4.8, e.g. 4.0.20, 4.2.6, 4.3.5 and 4.7.7.

**Comment by sebastianbergmann** [comment]
To the best of my knowledge, there never was a `--run` commandline option.

**Comment by m6w6** [comment]
Oh :) After further investigation, that's acutally meant as an argument to the NetBeansSuite script.

Now, here's what NetBeans runs:
`"/usr/bin/php" "/usr/bin/phpunit-4.7.7.phar" "--colors" "--log-junit" "/tmp/nb-phpunit-log.xml" "/path to NetBeans/php/phpunit/NetBeansSuite.php" "--run=/path to tests"`

So it actually seems that argument interpretation has changed in PHPUnit 4.8 and I'm inclined to see it as a NetBeans issue, which should use "--" to separate args.

Sorry.

**Comment by sebastianbergmann** [comment]
No worries.
