### ISSUE TITLE
PHPUnit TextUI segmentation fault on HHVM

### ISSUE THREAD

**Issue by weierophinney** [sebastianbergmann/phpunit#1865]
We're seeing the following error happening on several repositories after successful test runs on HHVM (using PHPUnit 4.8.9):

- https://travis-ci.org/zendframework/zend-eventmanager/jobs/81773675#L229

> Notice: Array to string conversion in phpunit/phpunit/src/TextUI/Command.php on line 162
> Core dumped: Segmentation fault
> Stack trace in /tmp/stacktrace.3064.log
> /home/travis/build.sh: line 41:  3064 Segmentation fault      (core dumped) ./vendor/bin/phpunit

**Comment by sebastianbergmann** [comment]
https://github.com/sebastianbergmann/phpunit/blob/4.8.9/src/TextUI/Command.php#L162 is `exit($ret);` where `$ret` is an integer. I have no idea why HHVM thinks there is as an array to string conversion going on. Looks like a bug in HHVM to me.
