### ISSUE TITLE
Updated from 4.8.6 -> 4.8.9, now mocking does not seem to be stubbing methods.

### ISSUE THREAD

**Issue by philipobenito** [sebastianbergmann/phpunit#1866]
As said in the subject, after an update from 4.8.6 to 4.8.9 tests suddenly "call to undefined method" errors are being thrown on my mocks unless I pass the second argument with an array of defined methods. 

Just trying to ascertain if this is a known issue?

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-mock-objects](https://github.com/sebastianbergmann/phpunit-mock-objects) project. Please open a ticket there and provide a minimal, self-contained test case.
