### ISSUE TITLE
phpunit.xml - test suite name vs. class name clash

### ISSUE THREAD

**Issue by gasperk** [sebastianbergmann/phpunit#187]
If I use a name of an existing class (not a test) in the <testsuite name="SomeClass"> in the phpunit.xml, an InvalidArgumentException is thrown with a message "Class does not extend PHPUnit_Framework_TestCase."

This is somewhat documented in the documentation of PHPUnit_Framework_TestSuite constructor: it tries to construct a TestSuite for SomeClass, because the argument is a string and an existing class. But in my case, this is actually the class under test, not the actual test case, and it took me a little time to find out what's happening.

I think there are a few possible approaches to this issue: either explicitly forbid clashing naming of the <testsuite> (ie. document clearly that the name shouldn't equal to any existing class name not being a test, and provide a more specific exception message), or don't throw an exception when such clash occurs, but rather just ignore the class, if it doesn't inherit PHPUnit_Framework_TestSuite.

**Comment by curry684** [comment]
I was pretty flabberghasted to run into this issue over 5 years later. Naming a test suite after an existing class still produces extremely unhelpful fatal errors with no clue what's happening.

If the test suites were 'discouraged' since 3.x, why are they still in 5.5 and causing these issues?
