### ISSUE TITLE
Launch multiple tests

### ISSUE THREAD

**Issue by alexislefebvre** [sebastianbergmann/phpunit#1870]
According to the help of PHPUnit we can only launch tests of one file at the same time:

    $ php ./vendor/bin/phpunit --help
    PHPUnit 4.8.9 by Sebastian Bergmann and contributors.
    
    Usage: phpunit [options] UnitTest [UnitTest.php]
           phpunit [options] <directory>
    
    Code Coverage Options:
    […]

Is it possible to add the possibility to define one or more paths to PHP files at the same time? e.g.:

    phpunit [options] UnitTest [UnitTest1.php] [UnitTest2.php] [UnitTest3.php] [UnitTest[…].php]

(I know that I can use `group` or `testsuite`)

**Comment by sebastianbergmann** [comment]
Almost everything is possible but I do not think that this would be useful.

**Comment by alexislefebvre** [comment]
@sebastianbergmann:

**Comment by alexislefebvre** [comment]
@sebastianbergmann my idea was to launch several tests in parallel to speed up my test. I wanted to launch each PHPUnit instance with 2 or 3 PHP tests files, instead of one PHPUnit per PHP test file (I have more tests files than CPU threads, it uses a lot of CPU resources).

**Comment by sebastianbergmann** [comment]
Parallel test execution is outside the scope of the current PHPUnit test runner.
