### ISSUE TITLE
Add minimum coverage option to fail if coverage falls below a threshold

### ISSUE THREAD

**Issue by jdufresne** [sebastianbergmann/phpunit#1877]
When looking at coverage tools for [other languages](https://coverage.readthedocs.org/en/latest/index.html) they frequently provide a configuration option to fail if coverage falls below a threshold. In coverage.py, the [option](https://coverage.readthedocs.org/en/latest/cmd.html?highlight=fail#reporting) is `--fail-under`. I think this feature would be useful in PHPUnit as well.

Some additional option to `phpunit.xml` such that coverage below a threshold results in some kind of failure that returns a non-zero exit status.

This feature would help continuous integration systems that want to catch commits that significantly drop coverage.

**Comment by redaxmedia** [comment]
+1

**Comment by sebastianbergmann** [comment]
I do not thinks that functionality like this belongs in PHPUnit.

**Comment by sinkcup** [comment]
I find a package to do this. https://packagist.org/packages/rregeer/phpunit-coverage-check
