### ISSUE TITLE
Implementing Test other than PHPUnit_Framework_TestCase

### ISSUE THREAD

**Issue by DavertMik** [sebastianbergmann/phpunit#1881]
It looks like there is a general interface `\PHPUnit_Framework_Test` to implement tests, however on practice it is impossible to use as test something other than `\PHPUnit_Framework_TestCase`. 

Here the `PHPUnit_Framework_Test` is received:

https://github.com/sebastianbergmann/phpunit/blob/master/src%2FFramework%2FTestResult.php#L596

and here `getSize` and `runBare` methods are used: 

https://github.com/sebastianbergmann/phpunit/blob/master/src%2FFramework%2FTestResult.php#L645
https://github.com/sebastianbergmann/phpunit/blob/master/src%2FFramework%2FTestResult.php#L665

however, there are no `getSize` and `runBare` methods in `PHPUnit_Framework_Test`. 
It looks like a broken design by contract. 

PHPUnit looks like a very coupled system and it is hard to use its parts without touching rest. 
It is impossible to implement some basic test which wouldn't rely on `PHPUnit_Framework_TestCase` features like:  
- mock engine
- prophecy
- expecting exceptions
- dependencies
- handling global state
- isolation
- output handling
- hook methods

(I don't even say anything about Single Responsibility here. But I think those features can be moved to traits and if anyone needs only Prophecy they can get it by including such trait and not include Mock engine)

Is there are plans for PHPUnit refactoring or we should just replace `PHPUnit_Framework_Test` with `PHPUnit_Framework_TestCase` in `TesListener->run()`

P.S. Looks like it is possible to use something other than PHPUnit_Framework_TestCase, it is `.phpt` format. But it is still impossible to call `Result->run` on any test implementing `PHPUnit_Framework_Test`.

**Comment by sebastianbergmann** [comment]
Known issue that cannot be fixed any time soon.

**Comment by DavertMik** [comment]
Thanks. Looks like I can learn from `PHPUnit_Extensions_PhptTestCase` and make the simplest implementation. 

But what about moving TestCase features to traits? That would be useful to pick only features you need

**Comment by DavertMik** [comment]
Oh, looks like `PhptTestCase` is also coupled with the core.
https://github.com/sebastianbergmann/phpunit/blob/master/src/TextUI/ResultPrinter.php#L555
So to implement new basic test format a new ResultPrinter should be created as well.

**Comment by DavertMik** [comment]
I have created minimal implementation of possible Test for Codeception. We are going to use it for functional and acceptance tests, so we don't need most of unit-testing features, however there is a flexible Mixin system which can be used to easily add/remove functionality. 

https://github.com/Codeception/Codeception/blob/refactor-formats/src/Codeception/Lib/Test.php

With some other changes to ResultPrinter and PHPUnit_Util_Log_JUnit this class works really great.

If you are interested, we can work on getting similar minimal implementation of `PHPUnit_Framework_Test` to be included in PHPUnit.
