### ISSUE TITLE
onNotSuccessfulTest is broken on PHP 7 in PHPUnit 4.8

### ISSUE THREAD

**Issue by stof** [sebastianbergmann/phpunit#1882]
PHPUnit 4.8 is catching ``Throwable`` and then passing it to ``onNotSuccessfulTest``, which is typehinted as ``Exception``.
Given that removing the typehint is not possible (it would break BC), I suggest that instances of ``Error`` are rethrown directly instead of calling ``onNotSuccessfulTest``

See for such an error https://travis-ci.org/symfony/symfony/jobs/83059828#L3640. this makes the failure report much less useful.

**Comment by sebastianbergmann** [comment]
PHPUnit 4.8 is only supported on PHP 5.3, PHP 5.4, PHP 5.5, and PHP 5.6. PHPUnit 5.0 will be supported on PHP 5.6 and PHP 7.

**Comment by stof** [comment]
Why is it catching Throwable then, making its code broken ?

**Comment by stof** [comment]
btw, it would be good to document it on https://phpunit.de/

**Comment by stof** [comment]
@sebastianbergmann would you access a change avoiding to pas the Throwable to the method typehinted as Exception ? PHPUnit 4.8 is explicitly broken on PHP 7 because of a half implementation of PHP 7 support (if it does not want to support PHP 7 at all, it should not catch Throwable)

**Comment by sebastianbergmann** [comment]
This discussion should be kept in #1883. And of course I am open to a pull request that "cleans up" PHPUnit 4.8.
