### ISSUE TITLE
The typehint change in onNotSuccessfulTests makes it a pain to support PHPUnit 4.8 and 5.0 at the same time

### ISSUE THREAD

**Issue by stof** [sebastianbergmann/phpunit#1883]
This method is an extension point for child classes, which means they must match the signature.

Given that 4.8 does not support PHP 7 and 5.0 only supports 5.6+, it would mean that a project wanting to support PHP 5.5 and PHP 7 at the same time (Symfony for instance) would have to be able to run its testsuite against both PHPUnit 4.8 and 5.0. The typehint change means that it can do it only if it never uses the `onNotSuccessfulTests` extension point.

Wouldn't it be possible to change the way the support of `Error` is handled in the extension point ?

**Comment by sebastianbergmann** [comment]
Yes, you will have to use PHPUnit 4.8 to run your testsuite with PHP < 5.6 and PHPUnit 5 for PHP >= 7.0. I don't see how this can be avoided.

**Comment by stof** [comment]
The issue is that if I want to use the ``onNotSuccessfulTests``, I cannot make my code compatible with both 4.8 and 5.0 because of the signature change. I need to have 2 different test cases for PHPUnit 4.8 and 5.0

**Comment by sebastianbergmann** [comment]
That is correct. PHPUnit 5 is a new major version and, unfortunately, has to break this API in order to properly support PHP 7.

**Comment by stof** [comment]
Well, the question is whether it would be possible to handle this hook a bit differently for the ``throwable`` support, to avoid making it such case impossible (many projects will still be supporting PHP 5.5 while wanting to support PHP 7)

**Comment by sebastianbergmann** [comment]
And they can, by using different versions of PHPUnit. Sorry, but we are running in circles. I tried really hard to avoid this change. Maybe I am just too stupid but I could not make it work.

It also makes no sense to me to support outdated versions of PHP in the same release series as a new major version of PHP.

**Comment by sebastianbergmann** [comment]
BTW: PHPUnit 4.7 and PHPUnit 4.8 have references to `Throwable` because I tried to make PHPUnit 4.x as compatible with PHP 7 as possible. But `onNotSuccessfulTest` turned out to be a showstopper.

**Comment by stof** [comment]
> And they can, by using different versions of PHPUnit.

They can only if they never use your ``onNotSuccessfulTest``. Because the same code cannot overwrite the method as ``onNotSuccessfulTest(\Exception $e)`` and ``onNotSuccessfulTest($e)`` at the same time. You will get a signature mismatch with one of the PHPUnit version.

this makes the ``onNotSuccessfulTest`` impossible to use for any project needing to stay compatible with 4.8 and 5.0 because of the PHP requirements.
Note that I'm fine with you bumping the min PHP version in 5.0. what I would like to see is a BC way to handle ``onNotSuccessfulTest`` (maybe using a new method in case of error)

**Comment by sebastianbergmann** [comment]
Continuing the discussion from #1882: it would be great if PHPUnit 4.8 would "just work" on PHP 7 for PHP 5 code.

**Comment by sebastianbergmann** [comment]
BTW: Thank you for caring about this and bringing it to my attention. It is, however, frustrating, that this is brought up on the day before the release of PHPUnit 5.0.

**Comment by stof** [comment]
Well, the BC break of the signature change is not documented on the changelog. so I discovered this change only because of my issue with #1882 when I looked at the code in newer versions.

**Comment by stof** [comment]
A solution could be to introduce a new method (name to be determined) which would accept any throwable.
For BC reason, exceptions would then be passed to ``onNotSuccessfulTest`` where they are rethrown by default, while errors are rethrown directly in the new method.
Overwriting ``onNotSuccessfulTest`` can then be marked deprecated in favor of overwriting the new method.
The only hard here is finding a new name for the hook.

Changing the signature of an existing method subject to inheritance gives no way to implement BC layers. This is why a new method would be necessary (we did such things several times in Symfony for instance, where we fought hard for BC)

**Comment by sebastianbergmann** [comment]
@stof I take it this would go into PHPUnit 4.8 and PHPUnit 5.x with `onNotSuccessfulTest ()` getting marked as deprecated in PHPUnit 4.8. I would accept a pull request that implements this.

**Comment by sebastianbergmann** [comment]
PHPUnit 4.8 is no longer supported.
