### ISSUE TITLE
The Symfony testsuite is failing with PHPUnit 5.0 while it passes in 4.8

### ISSUE THREAD

**Issue by stof** [sebastianbergmann/phpunit#1886]
The tests of the Security component are failing in a mock-related assertion when using PHPUnit 5.0, while it works fine in 4.8. See https://travis-ci.org/symfony/symfony/jobs/83213024#L3477 for the failure.

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-mock-objects](https://github.com/sebastianbergmann/phpunit-mock-objects) project. Please open a ticket there and provide a minimal, self-contained test case.
