### ISSUE TITLE
PHAR distribution of PHPUnit 5.0.1 does not work

### ISSUE THREAD

**Issue by addshore** [sebastianbergmann/phpunit#1887]
Fatal error: Trait 'PHPUnit_Extensions_Database_TestCase_Trait' not found in phar://phpunit.phar/phar/dbunit/Extensions/Database/TestCase.php on line 19

Call Stack:
    0.0790     462440   1. {main}() phpunit.phar:0
    0.1510    3807960   2. require('phar://phpunit.phar/phar/dbunit/Extensions/Database/TestCase.php') phpunit.phar:193

Apparently 5.0.0 was working fine. (or at least more functional than the 5.0.1 build) ;)

**Comment by sebastianbergmann** [comment]
Does this also happen when PHPUnit is installed via Composer?

**Comment by sebastianbergmann** [comment]
Nevermind, looks like this is limited to the PHAR distribution of PHPUnit (and caused by a bug in PHPAB).

**Comment by JeroenDeDauw** [comment]
I saw this issue when using the phar for 5.0.1. Was not in the 5.0.0 one.

**Comment by sebastianbergmann** [comment]
The PHAR for PHPUnit 5.0.0 is not affected as it had a wrong version of DbUnit bundled.

**Comment by sebastianbergmann** [comment]
I have pulled the PHAR distribution of PHPUnit 5.0.1.

**Comment by jamesfsuk** [comment]
I have a similar issue with the 5.0.0 phar distribution:

```
$ wget -q https://phar.phpunit.de/phpunit.phar
$ chmod +x phpunit.phar
$ ./phpunit.phar --version
PHP Parse error:  syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in phar:///tmp/phpunit.phar/phar/phpunit-mock-objects/Framework/MockObject/Builder/InvocationMocker.php on line 82
PHP Stack trace:
PHP   1. {main}() /tmp/phpunit.phar:0
```

**Comment by sebastianbergmann** [comment]
@jamesfsuk That looks like you are using a version of PHP that is no longer supported.

**Comment by addshore** [comment]
many thanks!
