### ISSUE TITLE
v 5.02 : parse error, unexpected '.', InvocationMocker.php on line 82

### ISSUE THREAD

**Issue by jarnix** [sebastianbergmann/phpunit#1888]
Just launching phpunit without parameters :
```
PHP Parse error:  syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in phar:///usr/local/bin/phpunit/phar/phpunit-mock-objects/Framework/MockObject/Builder/InvocationMocker.php on line 82
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/phpunit:0
```

**Comment by sebastianbergmann** [comment]
Your version of PHP is too old for PHPUnit 5.

**Comment by james2doyle** [comment]
I'm getting something similar but with a different errors

```
my-repo ❯ phpunit

Parse error: syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in phar:///usr/local/Cellar/phpunit/5.0.0/libexec/phpunit-5.0.0.phar/phar/phpunit-mock-objects/Framework/MockObject/Builder/InvocationMocker.php on line 82

my-repo ❯ php -v           
PHP 5.5.29 (cli) (built: Sep 25 2015 13:43:55) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
```

**Comment by stripyshirtguy** [comment]
I guess it'd be a good idea for PHPUnit to check for PHP version early on, and output a helpful message rather than this one?

**Comment by GrahamCampbell** [comment]
Not possible. Your PHP version fails because the entire thing has a syntax error from it's perspective.

**Comment by stripyshirtguy** [comment]
Before you include/require InvocationMocker, you could easily check the version of PHP, and if it's not the version you support, output a meaningful and helpful message.

**Comment by sebastianbergmann** [comment]
That is what PHPUnit does: https://github.com/sebastianbergmann/phpunit/blob/master/phpunit#L15

**Comment by stripyshirtguy** [comment]
@sebastianbergmann Does that mean your original comment "Your version of PHP is too old for PHPUnit 5." was not accurate, if they did not have the version of PHP required they would not have got loaded InvocationMocker.php to get the fatal parsing error?

@GrahamCampbell As above, it is possible, they detect version before requiring/including files that contain non-backwards compatible PHP.
