### ISSUE TITLE
Set phpunit options via env variables

### ISSUE THREAD

**Issue by hashar** [sebastianbergmann/phpunit#1890]
Copy pasting from #1513 which I can not reopen :-/

I could use the ability to tweak phpunit options using environment variables. A use case would be in Jenkins to invoke 'composer test' (which invokes phpunit) and make sure that phpunit is being passed --log-junit=build/junit.xml

The developer composer.json would be:

{
    "scripts": {
        "test": "phpunit"
    }
}
And Jenkins would invoke it with:

PHPUNIT_LOG_JUNIT="build/junit.xml" composer test
Another use case would be to generate coverage:

PHPUNIT_COVERAGE_XML=build/coverage.xml composer test
If we were to invoke composer test -- --log=build/junit.xml the extra arguments are passed to all the scripts defined in the 'test' section which is not going to play nice when other commands are defined such as PHP CodeSniffer. We also need Jenkins to execute a single entry point (test), to avoid having to generate another job or update the job whenever the developer add a new test.

By tweaking options via env variables and using the 'test' entry point, we execute all the tests commands defined by the developer, but would easily tweak phpunit options.

Python nosetests as such behavior https://nose.readthedocs.org/en/latest/usage.html#options . Setting --verbose is: NOSE_VERBOSE=2 nose

**Comment by sebastianbergmann** [comment]
At the moment, commandline arguments overwrite settings made in the XML configuration file. Also adding environment variables into the mix ... makes things more complex and bloated. I do not think that this should be added to PHPUnit.
