### ISSUE TITLE
Will PHPUnit 5 use namespace? 

### ISSUE THREAD

**Issue by HallofFamer** [sebastianbergmann/phpunit#1891]
So will I see PHPUnit/Framework/TestCase, or still the old PHPUnit_Framework_Testcase?

**Comment by GrahamCampbell** [comment]
No.

**Comment by HallofFamer** [comment]
Thats disappointing.

**Comment by Ma27** [comment]
@HallofFamer there are thousands of projects in this world using phpunit. The migration from the old-school underscore namespaces to native php5.3 namespaces would be such a pain.

**Comment by sun** [comment]
```php
class PHPUnit_Framework_TestCase {
  // (empty)
}
```
```php
namespace PHPUnit\Framework;

class TestCase extends \PHPUnit_Framework_TestCase {
  // (everything here)
}
```

1. would send the right signals.
1. would grant everyone the time of an entire major release to _adapt_ (until PHPUnit 6).
1. would surely be a very promising start.

:+1:

Thanks!
sun

**Comment by klausi** [comment]
@sun the other way around: PHPUnit_Framework_TestCase must contain all code while PHPUnit\Framework\TestCase only extends \PHPUnit_Framework_TestCase and is empty.

**Comment by HallofFamer** [comment]
@klausi:

Its not that simple, PHPUnit_Framework_TestCase is just one of the many classes that uses the old fashioned underscore separator notation. If you look into the /src/framework directory, you see all the classes are named in this way. Its a pity really, I feel that a leading application like PHPUnit should send the right signals to developers, all projects from now on should use namespace. 

@Ma27:
I understand the case for backward compatibility, but the older softwares are more likely hosted on servers with outdated PHP versions, so they aint likely to use the new version of PHPUnit anyway now that it requires PHP 5.6+.

**Comment by Ma27** [comment]
no, you did'nt understand me. Every project would have to update these namespaces. When using some phpunit tools such as selenium, it will be much more work.
And frameworks using this new phpunit version and providing testcase classes (e.g. the KernelTestCase of symfony2) would have to publish a new major version as switching the phpunit base class would be a big BC break.

**Comment by BenMorel** [comment]
FWIW, I would have given my :+1: for namespaces, but it's too late for PHPUnit 5 anyway.

**Comment by GrahamCampbell** [comment]
I'd quite like to see namespaces in PHPUnit 6 tbh.

**Comment by HallofFamer** [comment]
@Ma27 
Nope, they dont have to, they can choose to use the older version. The same logic can be applied to anything else, you can remain on the old platform if you refuse to embrace new technology. I dont see how this is that difficult anyway, since modern IDEs allow you to change class name at one place and affect code in all files, its very convenient. Or PHPUnit can apply @sun 's idea, deprecate first and remove later.

**Comment by Ma27** [comment]
Deprecations or not, it'll be a lot work. And staying on older versions is absolutly no solution. When releasing PHPUnit7 or 8 with a lot of new features then they'll drop phpunit 4 very soon as supporting such an old branch wouldn't make that much sense.
ANother problem would be merging between branches: Given PHPUnit6 has namespaces. When fixing bugs in that version, you'll run into thounsands of conflicts when trying to merge/rebase to the 4.x branch as much of the code is different there, so maintenance of multiple branches would be such a pain, too.

**Comment by HallofFamer** [comment]
So you are saying that PHPUnit should just stay with the old and legacy PHP technology and standards forever, and never embrace things like namespace?

**Comment by GrahamCampbell** [comment]
I think PHPUnit 6 is a perfect time to change to using namespace since it's dropping php 5, and the scalar typehint changes are already massively breaking anyway.

**Comment by kimegede** [comment]
Would be great to have namespaces :)

**Comment by GrahamCampbell** [comment]
we do now

**Comment by GrahamCampbell** [comment]
ish: https://github.com/sebastianbergmann/phpunit/blob/master/src/ForwardCompatibility/TestCase.php
