### ISSUE TITLE
coverage text do not honor --colors setting

### ISSUE THREAD

**Issue by mgansler** [sebastianbergmann/phpunit#1892]
Issue #1771 still exists with PHPUnit 4.8.10 as well as with 5.0.3

`--coverage-text` shows colors even when `--colors=never` is used.

**Comment by sebastianbergmann** [comment]
Since I neither use `--colors` nor `--coverage-text` myself it is unlikely that I will work on a fix for thix myself. I would review and then merge a pull request that fixes this, of course.

**Comment by llaville** [comment]
@sebastianbergmann I'm sorry to tell you that PHPUnit 4.8.13 is still affected by this issue (not fixed)

https://github.com/sebastianbergmann/phpunit/blob/4.8/src/TextUI/TestRunner.php#L506-L513

**Comment by sebastianbergmann** [comment]
Nothing to be sorry about. The fix has not been backported / cherry-picked to `4.8` yet.
