### ISSUE TITLE
Mark a test as risky that does not execute the code it wants to test

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#1899]
A test that has a `@covers c::m` annotation, for instance, should be marked as risky when the `c::m()` method is not executed.

**Comment by sebastianbergmann** [comment]
Related to https://github.com/sebastianbergmann/php-code-coverage/issues/234

**Comment by belanur** [comment]
@sebastianbergmann Should this behaviour be added to the --strict-coverage flag? Or should tests always be marked as risky in this case?

**Comment by sebastianbergmann** [comment]
It should be added to the `--strict-coverage` flag.

**Comment by sebastianbergmann** [comment]
Reverted 580f71513dfa67056c8ea2f2035e3759d17485a2 until https://github.com/sebastianbergmann/php-code-coverage/issues/420 is fixed.
