### ISSUE TITLE
--self-update updates to phpunit 5.0, even on PHP < 5.6

### ISSUE THREAD

**Issue by ianfp** [sebastianbergmann/phpunit#1901]
I just ran `phpunit.phar --self-update` on my PHP 5.5 system. When that was done, I ran `phpunit --version`, to which it replied

    This version of PHPUnit requires PHP 5.6; using the latest version of PHP is highly recommended.

Presumably it self-updated to phpunit 5.x. Shouldn't `--self-update` check the PHP version and update to the most recent *supported* version?

**Comment by sebastianbergmann** [comment]
To be honest, to me that is expected behavior. While PHPUnit 4 will get bug fixes for a year it is not the current version. So: don't use `--self-update` if you are on an outdated version of PHP.

**Comment by sebastianbergmann** [comment]
I should not have disregared this issue and closed it. Sorry for that.

**Comment by ianfp** [comment]
Thanks for the fix!
