### ISSUE TITLE
Mark tests as risky when they perform assertions on a mock

### ISSUE THREAD

**Issue by spriebsch** [sebastianbergmann/phpunit#1902]
As discussed over dinner tonight: mark tests as risky that run assertions on mock objects.

If, however, an abstract class is being tested through a mock, the test should not be marked as risky.

**Comment by sebastianbergmann** [comment]
This is not exactly what you wanted as it only marks a test as risky when it only performs assertions on test doubles. If I figure out a good way to mark a test as risky when it performs any assertion on a test double then I will implement that, too.

**Comment by sebastianbergmann** [comment]
Figured it out :-) See c8ac190ae54701725e5b8bb178e99e5886e68311

**Comment by Slamdunk** [comment]
Hi, I understand the meaning of this enhancement, but what about if doubles are tested to test a real implementation?
```php
class RealImplTest extends PHPUnit_Framework_TestCase
{
    public function testRealImpl()
    {
        $mock = $this->getMock('Interface');
        
        $impl = new RealImpl();
        $impl->setDependancy($mock);
        
        $this->assertSame($mock, $impl->getDependancy());
    }
}
```
This is not easy to get along your intention, but I think this case should be separated from the commit you did.

What do you think?

**Comment by sebastianbergmann** [comment]
Reverted 22df98f7c5e2726af05f26b9d3b1ccaaf32a5224 and c8ac190ae54701725e5b8bb178e99e5886e68311 due to #2042.
