### ISSUE TITLE
Allow to specify the extension version with the @requires annotation

### ISSUE THREAD

**Issue by localheinz** [sebastianbergmann/phpunit#1912]
It would be very nice if it were possible to specify the extension version when annotating tests with `@requires`, as to mark tests (or test cases) skipped when the extension version doesn't fulfill the requirement:

```php
/**
 * @requires extension gearman 1.1.2
 */
public function testWhichRequiresSpecificGearmanExtensionVersion() {}
```

See https://phpunit.de/manual/current/en/incomplete-and-skipped-tests.html#incomplete-and-skipped-tests.skipping-tests-using-requires.

:information_desk_person: Ideally, it should be possible to use version constraints, as you're used from Composer, what do you think?

/cc @alcohol 

See https://twitter.com/localheinz/status/654400305132666880.

**Comment by alcohol** [comment]
I'm not sure why I am cc'ed? :confused:

**Comment by localheinz** [comment]
@alcohol

Maybe it makes sense to use `composer/semver` for parsing?

**Comment by alcohol** [comment]
O. Well, you don't really need my input to decide that.

But I reckon PHP's `version_compare()` would suit most --if not all-- cases here.

**Comment by sebastianbergmann** [comment]
I am not good with regular expressions. Would be great if somebody could help with https://github.com/sebastianbergmann/phpunit/blob/5.1/src/Util/Test.php#L23 and/or https://github.com/sebastianbergmann/phpunit/blob/5.1/src/Util/Test.php#L174.

**Comment by alcohol** [comment]
@sebastianbergmann is there an associated issue (e.g. what specifically do you need help with)?

**Comment by alcohol** [comment]
Never mind, I figure you mean the implementation should probably be added at the locations you linked?
