### ISSUE TITLE
Proxying to original methods except for the constructor does not work

### ISSUE THREAD

**Issue by Toflar** [sebastianbergmann/phpunit#1913]
Hi, I hope I don't create any duplicate here but I couldn't find anything similar to this in the issue tracker.
My issue is actually explained in this stackoverflow question: http://stackoverflow.com/questions/26038980/how-to-proxy-to-original-methods-and-disable-the-constructor-at-the-same-time-wi

So the problem is that I would like to mock an object to do exactly the same except for the constructor:

```php
$mock = $this->getMockBuilder('ClassName')
            ->enableProxyingToOriginalMethods()
            ->disableOriginalConstructor()
            ->getMock();
```

However, I keep getting the error

> Missing argument 1 for ClassName::__construct(), called in [...]

whenever I enable proxying to the original methods. To me this looks like a bug or what am I doing wrong here?

Thanks in advance for clarification. :-)

**Comment by sebastianbergmann** [comment]
If you proxy to the original class then an object of the original class must be instantiated. If the original class has a constructor then that constructor must be executed. Hence disableOriginalConstructor() and enableProxyingToOriginalMethods() are mutually exclusive.

This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-mock-objects](https://github.com/sebastianbergmann/phpunit-mock-objects) project. Feel free to open a ticket there to ask for PHPUnit to issue an error when these two are used together.

**Comment by Toflar** [comment]
I see. Will submit an issue. Thanks for the reply!
