### ISSUE TITLE
Whitespace characters in DOM documents

### ISSUE THREAD

**Issue by flowl** [sebastianbergmann/phpunit#1920]
public function testX()
	{
		//$this->assertHtmlStringEqualsHtmlString(
		$this->assertXmlStringEqualsXmlString(
			'<test><p>hallo</p>  <p>welt</p></test>',
			'<test><p>hallo</p>      <p>welt</p></test>');
	}

The markup / entities are identical.
But the assertion fails:

    Failed asserting that two DOM documents are equal.
    --- Expected
    +++ Actual
    @@ @@
     <?xml version="1.0"?>
    - <test><p>hallo</p>  <p>welt</p></test>
    + <test><p>hallo</p>      <p>welt</p></test>

It's probably correct to say there is a difference between 1 whitespace character and 0 whitespace characters, but there is no difference between 1 whitespace characters and n > 1 whitespace characters.

The documents to be compared get prepared with the following, but the result is the same with true or false:

    $document->preserveWhiteSpace = false;

PHPUnit Version 3.7.24

**Comment by sebastianbergmann** [comment]
PHPUnit 3.7 is no longer supported.

But even in current versions of PHPUnit, `assertEquals()` does not canonicalize XML documents by default and `assertXmlStringEqualsXmlString()` and related assertions do not have support for canonicalization (they probably should, though).

What you want to achieve should be possible by using `assertEquals()` and passing `true` for its `$canonicalize` argument (see https://github.com/sebastianbergmann/phpunit/blob/5.0/src/Framework/Assert.php#L503).
