### ISSUE TITLE
Phar distrib cannot be used with phing PHPUnitTask

### ISSUE THREAD

**Issue by llaville** [sebastianbergmann/phpunit#1924]
Sebastian,

Consider the phing PHPUnitTask used with the phar distrib of PHPUnit (I've tested myself with phing 2.12 and phpunit 5.0.6). I've opened a ticket [1222](https://www.phing.info/trac/ticket/1222) on Phing.

The conflict origin issue came from the phar-stub you used and only `require` instead of `require_one`

E.g:  rather than 
```
require 'phar://phpunit-5.0.6.phar' . '/myclabs-deep-copy/DeepCopy/DeepCopy.php';
```
replace it by 

```
require_once 'phar://phpunit-5.0.6.phar' . '/myclabs-deep-copy/DeepCopy/DeepCopy.php';
```
Thanks in advance to consider this change.

BTW, could you also consider to publish a phar distrib without the shebang  (`#!/usr/bin/env php`)

Laurent

**Comment by sebastianbergmann** [comment]
Are you telling me that Phing is not invoking PHPUnit in a separate process but inside its own?

**Comment by llaville** [comment]
I'm telling you that Phing through the PHPUnitTask invoke PHPUnit resources as it was only a phar archive with only libs to call when needed.
That meens, when calling PHPUnitTask twice (at least), Phing has already loaded PHPUnit resources libs, and stopped without any errors.

**Comment by sebastianbergmann** [comment]
If Phing does not invoke PHPUnit in a separate process then Phing is doing something stupid. Sorry for using such a harsh word.

**Comment by llaville** [comment]
Why not just thinking to use `require_one` instead of `require` to load PHPUnit resources ? 
Is there something I don't see that may produces errors on PHPUnit usages ?
Sorry to ask a simple question !

**Comment by sebastianbergmann** [comment]
This could be as simple as `require` vs. `require_once`. But since I don't how Phing's PHPUnit Task extends PHPUnit's test runner (and why) I cannot possibly know for a fact that there are no other problems stemming from the fact that PHPUnit is used in a way it is not meant to be used.

I created #1925 to track the development of a library-only PHAR distribution of PHPUnit.

If you, or the Phing developers, tell me that such a library-only PHAR that uses `require_once` instead of `require` would make you happy then I will implement that.

**Comment by llaville** [comment]
Thanks :)

**Comment by sebastianbergmann** [comment]
Can you check whether https://github.com/sebastianbergmann/phpunit/commit/3dffc9f60b65e6fd3b3a05074f3baef9acfe20ed works for you?

**Comment by llaville** [comment]
Sorry Sebastian, but I can't do it now (at work). And to be honest with you, I've rebuild your phar 5.0.6 distrib from an "horrible" method ( extract phar, add new stub with require_once, and sheband ) and then rebuild project with box.json config from https://github.com/box-project/box2

**Comment by sebastianbergmann** [comment]
Just clone PHPUnit's repository from GitHub and then `ant phar`.

**Comment by sebastianbergmann** [comment]
Discussion moved to #1925.

**Comment by theseer** [comment]
Out of pure curiosity: Why would anyone still need require_once when there is autoloading?
