### ISSUE TITLE
Additionally provide library-only PHAR

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#1925]
* Without `#!/usr/bin/env php` at the top
* Without the code that sets up `$execute`
* Without the code that is executed when `$execute` is `true`
* With `require_once` instead of `require`

**Comment by llaville** [comment]
Have tried to build it on my windows platform. Sorry it's not yet portable 

    phar-prepare:
        [mkdir] Created dir: C:\home\github\phpunit\build\phar
         [copy] Copying 1 file to C:\home\github\phpunit
         [exec] ./composer.json has been updated
         [exec] Loading composer repositories with package information
         [exec] Updating dependencies (including require-dev)
         [exec] Your requirements could not be resolved to an installable set of packages.
         [exec]
         [exec]   Problem 1
         [exec]     - phpunit/php-invoker 1.1.4 requires ext-pcntl * -> the requested PHP extension pcntl is missing from your system.
         [exec]     - phpunit/php-invoker 1.1.3 requires ext-pcntl * -> the requested PHP extension pcntl is missing from your system.
         [exec]     - phpunit/php-invoker 1.1.2 requires ext-pcntl * -> the requested PHP extension pcntl is missing from your system.
         [exec]     - phpunit/php-invoker 1.1.1 requires ext-pcntl * -> the requested PHP extension pcntl is missing from your system.
         [exec]     - Installation request for phpunit/php-invoker ~1.1 -> satisfiable by phpunit/php-invoker[1.1.1, 1.1.2,
    1.1.3, 1.1.4].
         [exec]
         [exec]
         [exec] Installation failed, reverting ./composer.json to its original content.
         [exec] Result: 2

**Comment by sebastianbergmann** [comment]
Give me an email address and I'll send you a snapshot?

**Comment by llaville** [comment]
pear [at] laurent-laville [dot] org

**Comment by llaville** [comment]
`phpunit-library-4.8.15-5-g48d2190.phar` is just fine for me, and Phing PHPUnitTask run ok 
Thanks

**Comment by sebastianbergmann** [comment]
The library-only PHAR is now available at https://phar.phpunit.de/phpunit-library.phar.

**Comment by llaville** [comment]
Cool :-), Thanks again !

**Comment by vlakoff** [comment]
I don't know if it is related to these changes, but [phpunit.de](https://phpunit.de/) still points to the previous version 4.8.15.

Direct link: https://phar.phpunit.de/phpunit-old.phar

**Comment by sebastianbergmann** [comment]
@vlakoff Sorry but I have idea what you are trying to tell me.

**Comment by vlakoff** [comment]
Using the above link a few hours ago, I got version 4.8.15 instead of 4.8.16 (With fresh browser cache). So I though of some outdated build script.

Just tried again and got 4.8.16, so... No idea. Maybe some stale mirror server in the wild.
