### ISSUE TITLE
PHPUnit 5 is not triggering __toString method on mocks

### ISSUE THREAD

**Issue by tim-bezhashvyly** [sebastianbergmann/phpunit#1929]
After upgrading from 4.8.16 to 5.0.8 setting `__toString` return value on mocks is never triggered. I'm sure I'm missing something obvious.

Configuration is rather default:

```xml
<?xml version="1.0"?>
<phpunit
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://schema.phpunit.de/5.0/phpunit.xsd"
        bootstrap="bootstrap.php">
    <testsuite name="Foo Tests">
        <directory>Suites</directory>
    </testsuite>
    <filter>
        <whitelist>
            <directory>../../src</directory>
        </whitelist>
    </filter>
</phpunit>
```

**Comment by sebastianbergmann** [comment]
Please provide a minimal, self-contained, reproducing test case.

**Comment by tim-bezhashvyly** [comment]
```php
<?php

class ClassToBeMocked
{
    public function __toString()
    {

    }
}

class SelfContainedTest extends PHPUnit_Framework_TestCase
{
    public function testStub()
    {
        $expectedValue = 'bar';

        $stub = $this->getMock(ClassToBeMocked::class);
        $stub->method('__toString')->willReturn($expectedValue);

        $this->assertEquals($expectedValue, (string) $stub);
    }
}
```

**Comment by tim-bezhashvyly** [comment]
Conversion to string in example above is superfluous ad only added for illustration of expected behaviour.

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-mock-objects](https://github.com/sebastianbergmann/phpunit-mock-objects) project.

I have created https://github.com/sebastianbergmann/phpunit-mock-objects/issues/267 for tracking this issue. Thank you for the example.
