### ISSUE TITLE
No tests executed! For a specific Folder

### ISSUE THREAD

**Issue by edwint88** [sebastianbergmann/phpunit#1930]
Hello everybody,
I'm running PHPUnit 4.7.7, target >PHP 5.3 and netbeans 8.0.2.

Short description:
I have a folder (Folder6-2) with two subfolders (Folder7 & Folder7-2). When I'm running (CLI or Netbeans) a testsuite with the path till Folder6-2 only the tests in the Folder7-2 are running. 
- when I'm creating a specific testsuite for Folder7 (testFolder7) I get "No tests executed!".
- if I run mannualy each test in Folder7 it works.
  _phpunit --bootstrap bootstrap.php testThatDontWorkTest ./Folder1/Folder2/Folder3/Folder4/Folder5/Folder6-2/Folder7/testThatDontWorkTest.php_

-if I rename the Folder7 in Folder8 the test will run with command:
*phpunit --testsuite "testFolder7"
but then everytime when I generate my testsources I have to rename this folder.

Any ideas what could be wrong here?

More: In this link (http://stackoverflow.com/questions/33284828/phpunit-4-7-7-tests-work-in-cmd-but-not-in-netbeans-8-0-2) the problem is described in more detail. 

Thanks in advance!

**Comment by sebastianbergmann** [comment]
Sorry for taking so long to respond. PHPUnit 4 is no longer supported. Please open a new ticket in case the issue still exists in PHPUnit 6.4.
