### ISSUE TITLE
Class "PHPUnit_Extension_SeleniumTestCase" not found - error

### ISSUE THREAD

**Issue by naptoon** [sebastianbergmann/phpunit#1931]
When I run a test which fails and do not catch the Exception, PHPUnit doesn't show just the result but throws a stack trace and the Error, that "PHPUnit_Extension_SeleniumTestCase can not be found.
I use version 5.0 as PHAR with PHP 7.

The whole result of the test can be found here: http://cl.ly/0D1P2u272z0r

**Comment by GrahamCampbell** [comment]
That;s because it was removed in phpunit 5.

**Comment by GrahamCampbell** [comment]
https://github.com/sebastianbergmann/phpunit/blob/5.0/ChangeLog-5.0.md#removed-1

**Comment by naptoon** [comment]
Yes I know, but this class is called somewhere within the phpunit code, otherwise there would be a normal behavior like before.

**Comment by GrahamCampbell** [comment]
Are you using the very latest vesion?

**Comment by GrahamCampbell** [comment]
ie, one that includes https://github.com/sebastianbergmann/phpunit/commit/73f0d41add653fbfe66925a1bb6ef9556845888f

**Comment by naptoon** [comment]
Not yet, it was committed just 6 hours ago, I will try it tomorrow, thanks!

**Comment by GrahamCampbell** [comment]
I'm also not sure it's even in a release yet. It's definitely on the 5.0 branch though. :)
