### ISSUE TITLE
Trying to generate code coverage report tells me: "No whitelist configured, no code coverage will be generated"

### ISSUE THREAD

**Issue by alberto56** [sebastianbergmann/phpunit#1932]
According to the documentation ["Chapter 11. Code Coverage Analysis"](https://phpunit.de/manual/current/en/code-coverage-analysis.html):

    By default, all source files that contain at least one line of code that has been executed (and only these files) are included in the code coverage report.

    ...

    It is best practice to use a whitelist instead of the blacklist mentioned above.

I understand from this that whitelists are not compulsory. My `phpunit.xml` file thus does not reference any white- or blacklist:

    <?xml version="1.0" encoding="UTF-8"?>
    <phpunit colors="true">
        <testsuites>
            <testsuite name="Application Test Suite">
                <directory>mycode/test/</directory>
            </testsuite>
        </testsuites>
    </phpunit>

When I try to get code coverage, however, I get the error:

    ./vendor/bin/phpunit --version
    PHPUnit 5.0.8 by Sebastian Bergmann and contributors.
    ./vendor/bin/phpunit --coverage-html coverage
    Error:         No whitelist configured, no code coverage will be generated

I at first thought this was due to #1872, but that change is included in version 5.0.8, which I'm using.

How can I get phpunit to just generate code coverage for "all source files that contain at least one line of code that has been executed", as is described in the documentation?

It seems that the [code which outputs this error](https://github.com/sebastianbergmann/phpunit/commit/f9882b18325d9cbfd416060abfc433dcf79df8fe) would not run if the "whitelist" argument is set. I thought I could set it to empty by adding this to my xml file:

    <filter>
      <whitelist processUncoveredFilesFromWhitelist="true">
      </whitelist>
    </filter>

But I'm still getting the same output.

Thanks!

**Comment by alberto56** [comment]
Just a note that this error can occur when XDebug is not loaded, as described in #347.

However, in my case XDebug seems to be loaded correctly:

    $ php -ini|grep 'xdebug support'
    xdebug support => enabled

**Comment by sebastianbergmann** [comment]
No clue how #347 should be related here.

**Comment by sebastianbergmann** [comment]
There was a bug in the documentation (https://github.com/sebastianbergmann/phpunit-documentation/issues/335) that has been fixed now.

**Comment by alberto56** [comment]
Much appreciated @sebastianbergmann !

Thanks for the quick response, I am no longer getting this error.

**Comment by hierony94** [comment]
Dear @sebastianbergmann 
Should I update my phpunit version?
Which version that solved this bug?

Thank You.

**Comment by BorderCloud** [comment]
I have exactly the same problem.
Howto resolve it ?
Thanks

**Comment by luisgjb** [comment]
Same here..

**Comment by diego3** [comment]
Yeah, i'am using 5.5.0
and the same problem to me too :(

How do i fix this?

Thanks!

**Comment by su-narthur** [comment]
@hierony94 @BorderCloud You need to configure a whitelist in your phpunit.xml file, [per this documentation](https://phpunit.de/manual/current/en/appendixes.configuration.html).

**Comment by xthyjdy** [comment]
sebastianbergmann commented on Nov 1, 2015
thanks
