### ISSUE TITLE
Fatal error: Class undefined: PHP_Token_HASHBANG in HHVM environment

### ISSUE THREAD

**Issue by brazorf** [sebastianbergmann/phpunit#1939]
I'm getting the following exception when running tests on HHVM 3.6.6 on Travis CI, that is running PHPUnit 4.5.0.

`PHPUnit_Framework_Exception: Fatal error: Class undefined: PHP_Token_HASHBANG in phar://phpunit-4.5.0.phar/php-token-stream/Token/Stream.php on line 185`

**Comment by sebastianbergmann** [comment]
This should have been reported at https://github.com/sebastianbergmann/php-token-stream/issues.
