### ISSUE TITLE
Coverage Issues

### ISSUE THREAD

**Issue by gdonald** [sebastianbergmann/phpunit#1941]
I have tests that exercise my app's API URLs using PHP cURL but they still shows as red, uncovered.  Is this normal?  If so what's the suggested method to make the exercised code show as green and covered?

I noticed there are no actual GET/POST testing methods.  Should I be using something besides PHP cURL to work better with coverage output?

Thanks.

**Comment by openbrian** [comment]
I have a similar issue.  phpunit_coverage.php is not normally called with curl based tests.  I extended PHPUnit_Framework_TestCase and set $coverageScriptUrl, but it's not getting called.  I even overloaded run() to make sure testID and collectCodeCoverageInformation variables were being set before calling parent::run(), and subsequently calling $result->getCodeCoverage()->append( $coverage->get(), $this );  This worked before with version 4.6.

**Comment by sebastianbergmann** [comment]
This is not a support forum, sorry.
