### ISSUE TITLE
Return types

### ISSUE THREAD

**Issue by JeroenDeDauw** [sebastianbergmann/phpunit#1946]
Looking at the code, it seems that while scalar type hints are used, there is no usage of the return type hinting feature yet. Is there a reason for that further than that nobody got to it yet, or are PRs welcome?

**Comment by sebastianbergmann** [comment]
`master` is highly experimental at this point. And nobody can help me with it :-) There might not be any work on `master` until Christmas (no time before then).

**Comment by JeroenDeDauw** [comment]
Are you saying that small contributions to master are not welcome / do not make sense before then?

**Comment by sebastianbergmann** [comment]
Yes.
