### ISSUE TITLE
unable to use .phar due unsupported signature error

### ISSUE THREAD

**Issue by glensc** [sebastianbergmann/phpunit#1948]
i'm unable to figure out what is causing this. other phar files (composer, php-cs-fixer, ..) run fine in this system.

```
➔ php56 phpunit.phar  --version
PHP Fatal error:  Uncaught exception 'PharException' with message 'phar "/tmp/phpunit.phar" has a unsupported signature' in /tmp/phpunit.phar:21
Stack trace:
#0 /tmp/phpunit.phar(21): Phar::mapPhar('phpunit-5.0.8.p...')
#1 {main}
  thrown in /tmp/phpunit.phar on line 21
```

and i do not have suhosin extension nor patch present like mentioned in #1694

extensions present:
```
➔ php -m | grep -Ei 'phar|zip|zlib|bz2|ssl'
bz2
openssl
Phar
zip
zlib
```

**Comment by sebastianbergmann** [comment]
This makes no sense to me.

**Comment by glensc** [comment]
me neither, that's why the bug. anything else i could try looking at? i tried `strace(1)`, but nothing suspicious there.

**Comment by sebastianbergmann** [comment]
The PHPUnit PHAR is not signed using a mechanism provided by the PHAR extension. I do not understand how PHP complains about an illegal signature if there is no signature for it to check.

**Comment by glensc** [comment]
maybe you know what has changed with phar making process considering that two versions mentioned above did work.

**Comment by glensc** [comment]
went through archives from https://phar.phpunit.de/

- [x] https://phar.phpunit.de/phpunit-3.7.38.phar
- [x] https://phar.phpunit.de/phpunit-4.0.20.phar
- [x] https://phar.phpunit.de/phpunit-4.1.6.phar
- [x] https://phar.phpunit.de/phpunit-4.2.6.phar
- [x] https://phar.phpunit.de/phpunit-4.3.5.phar
- [ ] https://phar.phpunit.de/phpunit-4.4.5.phar (Constant __PHPUNIT_PHAR__ already defined errors)
- [x] https://phar.phpunit.de/phpunit-4.5.1.phar
- [x] https://phar.phpunit.de/phpunit-4.6.0.phar
- [x] https://phar.phpunit.de/phpunit-4.6.5.phar
- [x] https://phar.phpunit.de/phpunit-4.6.8.phar
- [x] https://phar.phpunit.de/phpunit-4.6.9.phar 2015-05-29T08:01:15+02:00
- [ ] https://phar.phpunit.de/phpunit-4.6.10.phar 2015-06-03T09:04:00+02:00 (unsupported signature error)
- [ ] https://phar.phpunit.de/phpunit-4.7.0.phar 2015-06-05T06:17:00+02:00 (unsupported signature error)
- [ ] https://phar.phpunit.de/phpunit-4.7.7.phar (unsupported signature error)
- [ ] https://phar.phpunit.de/phpunit-4.8.0.phar (unsupported signature error)
- [ ] https://phar.phpunit.de/phpunit-4.8.16.phar  (unsupported signature error)
- [ ] https://phar.phpunit.de/phpunit-5.0.0.phar  (unsupported signature error)

**Comment by theseer** [comment]
```
theseer@nyda ~/Desktop/xx $ phar info phpunit-5.0.0.phar 
Unexpected default arguments to command info, check /usr/bin/phar help
theseer@nyda ~/Desktop/xx $ phar info -f phpunit-5.0.0.phar 
Alias:              phpunit-5.0.0.phar
Hash-type:          SHA-512
Hash:               B8AE97E12615C13B8C675D5BC0E6F62ABB26CF377B024A882DDC476D652CD138394382FBD41E14B5C72E0733530BE8D36088430E127ED75D33A342EDC09087F5
Entries:            531
Uncompressed-files: 531
Compressed-files:   0
Compressed-gz:      0
Compressed-bz2:     0
Uncompressed-size:  2686117
Compressed-size:    2686117
Compression-ratio:  100%
Metadata-global:    0
Metadata-files:     0
Stub-size:          47718
```

```
theseer@nyda ~/Desktop/xx $ wget https://phar.phpunit.de/phpunit-4.6.9.phar
--2015-11-10 15:33:52--  https://phar.phpunit.de/phpunit-4.6.9.phar
Resolving phar.phpunit.de (phar.phpunit.de)... 188.94.27.25
Connecting to phar.phpunit.de (phar.phpunit.de)|188.94.27.25|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3146137 (3,0M) [application/octet-stream]
Saving to: ‘phpunit-4.6.9.phar’

phpunit-4.6.9.phar                         100%[========================================================================================>]   3,00M   676KB/s   in 5,0s   

2015-11-10 15:33:57 (610 KB/s) - ‘phpunit-4.6.9.phar’ saved [3146137/3146137]

theseer@nyda ~/Desktop/xx $ phar info -f phpunit-4.6.9.phar 
Alias:              phpunit-4.6.9.phar
Hash-type:          SHA-1
Hash:               39AF13CA2EF8B206074B67A717412CD064520E13
Entries:            569
Uncompressed-files: 569
Compressed-files:   0
Compressed-gz:      0
Compressed-bz2:     0
Uncompressed-size:  3050389
Compressed-size:    3050389
Compression-ratio:  100%
Metadata-global:    0
Metadata-files:     0
Stub-size:          49601
```


The later PHPUnit phar's have a SHA512 hash, while the older ones have SHA1. If you have an (old?) PHP version not supporting SHA512...

**Comment by theseer** [comment]
Addtion: phpab (which is used to build the phar) checks the list of supported/preferred hash algorithms (https://github.com/theseer/Autoload/blob/master/src/PharBuilder.php#L101) and picks the best one available. It seems like the PHP environment this phpunit.phar is being executed in does not support SHA-512 yet.

I guess it would make sense to provide a switch for phpab to force a certain hashing algorithm. I'll add that to phpab.

**Comment by sebastianbergmann** [comment]
Looks like at some point SHA-512 became available as a hash for PHARs on the machine where I build the releases. Once @theseer has released a new version of phpab with a commandline option to force the usage of legacy SHA-1 hashes I will use that.

**Comment by glensc** [comment]
super!

**Comment by sebastianbergmann** [comment]
Thank you, @glensc, for bringing this to my attention. And for being persistent enough to convince me that there is something wrong :-) And thanks to @theseer for investigating the issue.

**Comment by sebastianbergmann** [comment]
What I don't get, though, is why @glensc's build of PHP 5.6 has no support for SHA-256 checksums of PHAR files.

**Comment by glensc** [comment]
because PHP is crap:

```
# - WARNING: Phar: sha256/sha512 signature support disabled if ext/hash is
#   built shared, also PHAR_HAVE_OPENSSL is false if openssl is built shared.
#   make it runtime dep and add Suggests (or php warning messages)
```

it has shared modules support, but it's crippled because some assumptions made compile time, not run time. it's perfectly fine to use symbols from other shared modules, but they do that decision at compile time. sigh.


[it has been](https://github.com/pld-linux/php/blob/c27e6c07e158e10cec6ec6cf2d0385a2440fe4c4/php.spec#L21-L24) long time in TODO and investigate and find a fix.

**Comment by theseer** [comment]
It's even documentd: http://php.net/manual/en/phar.constants.php

**Comment by glensc** [comment]
i have hash extension (shared one)!

**Comment by theseer** [comment]
Doesn't seem to have helped in terms of the phar extension and it's hash support.
Are you running the PLD's php rpm with the issue you mentioned before?

I'm already working on having phpab provide an option to specify the hash type to use. Not convinced though going back to SHA-1 only is the best option given the recent issues with said algorithm.

**Comment by glensc** [comment]
@theseer not sure i understand you question. yes i'm using that rpm package, why else would i link to that package's TODO?

**Comment by theseer** [comment]
I was just wondering if you could or did verify that the problem vanishes if a non-PLD-build of PHP is used.

**Comment by glensc** [comment]
the problem exists if hash extension is built shared (maybe openssl has to be shared too), as i said and noted, the check is compile time not run time. stupid php.

**Comment by theseer** [comment]
This was mere curiosity since the problem does not show up on fedora/redhat/centos with PHP installed from their RPMs.  So they either do not build it shared or found some other way around that issue, regardless it being stupid on the PHP end.

**Comment by theseer** [comment]
Okay, just checked remi's spec file: https://github.com/remicollet/remirepo/blob/master/php/php56/php56.spec#L1150 - so it's always static and not shared.

**Comment by glensc** [comment]
i will try to make the check runtime, but it will likely take some time depending how complicated the change would be :)

**Comment by glensc** [comment]
similar problem is with [getimagesize()](https://github.com/remicollet/remirepo/blob/db18208927eea10d3cfbaba3263f70e7ad6a0be3/php/php56/php56.spec#L1155) for which in our distro fix [was simple](https://github.com/pld-linux/php/commit/8e022175823ae2225ba7e919ffcad9beb3e74b4e)

**Comment by glensc** [comment]
confirmed fixed:

```
➔ php56 phpunit.phar --version
PHPUnit 5.0.9 by Sebastian Bergmann and contributors.

➔ php phpunit-old.phar --version
PHPUnit 4.8.17 by Sebastian Bergmann and contributors.
```

**Comment by glensc** [comment]
some background information, this is the check to make to see if ext/phar lacks the support:

```
➔ php -r 'print_r(Phar::getSupportedSignatures());'
Array
(
    [0] => MD5
    [1] => SHA-1
    [2] => OpenSSL
)
```

**Comment by theseer** [comment]
That check doesn't help for phpunit since you cannot even open the phar file in a PHP environment where the selected signature format is not available. Checking for supported types on the build maschine doesn't fix that - and by the way was what phpab was already doing anyhow (https://github.com/theseer/Autoload/blob/master/src/PharBuilder.php#L117).

**Comment by glensc** [comment]
@theseer yes, i posted info here, so if somebody else comes across this ticket, can run the check. the check wasn't intended to be incorporated to phunit phar.

**Comment by steinhaug** [comment]
I had a similar problem today, and after recompiling and building this PHAR file in all possible ways in an attemt to having it work on the server... Problem was my FTP software had been reset in its configuration so I was uploading files in ASCHII and did not use my head - PHAR files definately needs to be BINARY. After reuploading files in BINARY.. never had this error again.

Hope til solves your problem to!
