### ISSUE TITLE
PHP7 syntax error causes "must be an instance of Exception, instance of Error given" error

### ISSUE THREAD

**Issue by gmagana** [sebastianbergmann/phpunit#1953]
Due to PHP7's new parent of Exception (called "Throwable") and because syntax errors are now catchable and thrown as type "Error" (which inherits from Throwable and not from Exception), running phpunit (as of 5.0.9) on a script with a syntax error causes a rather unhelpful error message of

```
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to PHPUnit_Framework_TestResult::addError() must be an instance of Exception, instance of Error given, called in phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php on line 724 and defined in phar:///usr/local/bin/phpunit/phpunit/Framework/TestResult.php:202
Stack trace:
#0 phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php(724): PHPUnit_Framework_TestResult->addError(Object(PHPUnit_Framework_TestSuite), Object(Error), 0)
#1 phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php(747): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#2 phar:///usr/local/bin/phpunit/phpunit/TextUI/TestRunner.php(425): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#3 phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php(154): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#4 phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php(105): PHPUnit_TextUI_Command->run(Array, true)
#5 /usr in phar:///usr/local/bin/phpunit/phpunit/Framework/TestResult.php on line 202
```

Currently in order to see what the error actually is, we need to then run the code outside of phpunit to see the actual syntax error messaging.

The request for this ticket is to handle the error gracefully and output PHP's error stack so that we may fix the syntax error.  Thanks!

PS - In order to future-proof phpunit, maybe it would be good to var_dump() the error that _was_ received in case it helps the user pinpoint the problem.

**Comment by sebastianbergmann** [comment]
Which version of PHPUnit are you using?

**Comment by sebastianbergmann** [comment]
I cannot reproduce this. Please provide a minimal, self-containted, recproducing test case.

**Comment by GrahamCampbell** [comment]
Sounds like an old version of phpunit is being used here.

**Comment by gmagana** [comment]
Thanks for looking into this. I caused the error with this code in a PHP file:

```
class Abc {
  public static function FunA() {
    var_dump(static::$xxxx);
  }
}

class SomeTest extends PHPUnit_Framework_TestCase {
    public static function setUpBeforeClass() {
      Abc::FunA();
    }
}
```

The syntax error in the above snippet is that $xxxx is not declared as a static property, therefore the PHP parse/compilation step fails.

I'm not sure if this error is particular to statics, I only got my own case down to the above small example. Here is an output log:

```
$ php --version
PHP 7.0.0RC5 (cli) ( NTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0-dev, Copyright (c) 1998-2015 Zend Technologies

$ phpunit --version
PHPUnit 5.0.9 by Sebastian Bergmann and contributors.

$ phpunit abcTest.php
PHPUnit 5.0.9 by Sebastian Bergmann and contributors.

PHP Fatal error:  Uncaught TypeError: Argument 2 passed to PHPUnit_Framework_TestResult::addError() must be an instance of Exception, instance of Error given, called in phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php on line 724 and defined in phar:///usr/local/bin/phpunit/phpunit/Framework/TestResult.php:202
Stack trace:
#0 phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php(724): PHPUnit_Framework_TestResult->addError(Object(PHPUnit_Framework_TestSuite), Object(Error), 0)
#1 phar:///usr/local/bin/phpunit/phpunit/TextUI/TestRunner.php(425): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#2 phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php(154): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#3 phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php(105): PHPUnit_TextUI_Command->run(Array, true)
#4 /usr/local/bin/phpunit(513): PHPUnit_TextUI_Command::main()
#5 {main}
  thrown in phar:///usr/local/bin/phpunit/phpunit/Framework/TestResult.php on line 202
```

**Comment by sebastianbergmann** [comment]
`Error: Access to undeclared static property: Abc::$xxxx` is not a syntax but a runtime error. Will investigate the PHPUnit problem, though.

**Comment by sebastianbergmann** [comment]
Seems to only happen for errors triggered `setUpBeforeClass()`, not in `setUp()` or `test*()`.

**Comment by gmagana** [comment]
Ah thanks, sorry for my describing the problem wrong; you are correct.

**Comment by sebastianbergmann** [comment]
c3db067ba2f64843d6038c6dc9c51eca794f5e06 should fix this but it breaks backwards compatibility, meaning it cannot got into 5.x :-(

Maybe I (or somebody else) can come up with a different solution that does not break BC.

**Comment by gmagana** [comment]
I was able to get a band aid working that works on both PHP 7 and PHP 5.6. IN my example above, adding this try/catch gives me the right error message on both versions:

```
class Abc {
  public static function FunA() {
    var_dump(static::$xxxx);
  }
}

class SomeTest extends PHPUnit_Framework_TestCase {
    public static function setUpBeforeClass() {
      try {
        Abc::FunA();
      } catch (Throwable $e) {
        throw new Exception($e);
      }
    }
}
```

I was half expecting PHP 5.6 to complain that Throwable is not defined, but it ran fine...  Anyway, this is my temporary fix. Hopefully it helps people running into this.

**Comment by gmagana** [comment]
Thanks so much for fixing this!

**Comment by mfuery** [comment]
But like @gmagana said, this is a bandaid: you're just catching and ignoring the underlying error. I'm curious what the root cause is?  Unless I'm misunderstanding the issue...
Thanks

**Comment by gmagana** [comment]
@mfuery I think this has been fixed since that https://github.com/sebastianbergmann/phpunit/commit/ac2e32c1d87cd8d2689a25e344a87de93858608c commit

**Comment by imastercopy** [comment]
Looking for help on how to fix these 3 errors: Can someone provide instructions
Notice: Constant JROUTER_MODE_RAW already defined in libraries/cms/router/router.php on line 17

Notice: Constant JROUTER_MODE_SEF already defined in libraries/cms/router/router.php on line 25

Fatal error: Uncaught TypeError: Argument 1 passed to JErrorPage::render() must be an instance of Exception, instance of ParseError given in libraries/cms/error/page.php:28 Stack trace: #0 [internal function]: JErrorPage::render(Object(ParseError)) #1 {main} thrown in  libraries/cms/error/page.php on line 28

**Comment by imastercopy** [comment]
where is the solution should be for the libraries/cms/error/page.php on line 28?
