### ISSUE TITLE
@runTestsInSeparateProcesses fails when running tests with phpdbg -qrr

### ISSUE THREAD

**Issue by nicolas-grekas** [sebastianbergmann/phpunit#1955]
Running tests in a separate process does not work when run with the `phpdbg -qrr phpunit`

**Comment by sebastianbergmann** [comment]
I have merged #1956 into `4.8` and `5.0`. Can you please adapt your patch for `5.1` and send a new pull request for that? Thanks!

**Comment by nicolas-grekas** [comment]
Yep of course, I'll do that tomorrow

**Comment by sebastianbergmann** [comment]
Thanks!
