### ISSUE TITLE
XSD schema in 5.x does not validate

### ISSUE THREAD

**Issue by jonsa** [sebastianbergmann/phpunit#1961]
I'm not particular good at XSD schemas so I cannot really judge if this serious thing or not. But when I run the 5.x version of ```phpunit.xsd``` through a validator I get an error stating.

```
Not valid.
Error - Line 14, 38: org.xml.sax.SAXParseException;
lineNumber: 14;
columnNumber: 38;
cos-nonambig: whitelist and whitelist (or elements from their substitution group)
              violate "Unique Particle Attribution". During validation against 
              this schema, ambiguity would be created for those two particles.
```

**Comment by sebastianbergmann** [comment]
I am not particularly good at XSDs either, but `xmllint` has no problem:
```
$ xmllint --schema phpunit.xsd --noout phpunit.xml
phpunit.xml validates
```

**Comment by theseer** [comment]
Sax seems to be a lot stricter with XSD handling than libXML2. While having a choice of two times the same child element doesn't make any logical sense of course it shouldn't actually be a problem when verifying a document as either choice would lead to the same result.

While the PR by @kubawerlos fixes the duplication, the <xs:choice> could also be removed as it's superfluous with only one sequence to choose from.

@kubawerlos Do you want to update your PR or do you want me to make create a new one?

**Comment by sebastianbergmann** [comment]
Looks like @kubawerlos is not responding and that it is up to you, @theseer.

**Comment by kubawerlos** [comment]
@theseer updated.

**Comment by sebastianbergmann** [comment]
@kubawerlos Can you please send a pull request that only contains your changes to `phpunit.xsd`? Thanks!

**Comment by kubawerlos** [comment]
@sebastianbergmann done.

**Comment by sebastianbergmann** [comment]
I do not see a pull request for this.

**Comment by kubawerlos** [comment]
@sebastianbergmann #2122 - should I change target branch?

**Comment by sebastianbergmann** [comment]
Nevermind, I was looking in the wrong place.

**Comment by kubawerlos** [comment]
@sebastianbergmann anything to do for PR?
