### ISSUE TITLE
class 'php_token_stream' not found + PHPUnit 4.2.6

### ISSUE THREAD

**Issue by benjamin-rtblw** [sebastianbergmann/phpunit#1966]
Hi,

I'm using PHPunit 4.2.6 and I'm encountering the following issue : 
class 'php_token_stream' not found 4.2.6
When I'm trying to run the tests with coverage generation.

I already found few topics that talk about this issue but it seems to concerne an older version 3.5.
I also found a topic that exactly relates my problem but the guy fixed the problem by disabling code coverage : http://phpmyadmin.996332.n3.nabble.com/unit-testing-on-Debian-8-jessie-td15652.html.

Do you know how to fix this issue?

Best regards,
Ben

**Comment by sebastianbergmann** [comment]
* PHPUnit 4.2 is no longer supported
* The `PHP_Token_Stream` class is provided by a dependency of PHPUnit that is automatically installed when installing PHPUnit via Composer as well as bundled in the PHAR distribution of PHPUnit
* It could be that your autoloader is too eager and trying to load classes it is not responsible for
