### ISSUE TITLE
Launching PHPUnit within Netbeans cause *unrecognised option --run*

### ISSUE THREAD

**Issue by Jduret** [sebastianbergmann/phpunit#1967]
I am encountering an error calling PHPUnit within NetBeans. Netbeans use the command line below to launch tests : 
> "C:\phpqa\bin\phpunit.bat" "--colors" "--log-junit" "C:\Users\Me\AppData\Local\Temp\nb-phpunit-log.xml" "--configuration" "C:\Applications\vhosts\MyProject\tests\configuration.xml" "C:\Program Files\NetBeans 8.0\php\phpunit\NetBeansSuite.php" "--run=C:\Applications\vhosts\MyProject\trunk\tests\unitTests"

This one give me this result:
> PHPUnit 4.8.18 by Sebastian Bergmann and contributors.
>
> unrecognized option --run

I think that [this pull request](https://github.com/sebastianbergmann/phpunit/commit/e814242fe377747490ccc31e455765b7abd3d5ff) on the file __phpunit/src/Util/Getopt.php__ has changed the way PHPUnit understand this command line. As you can see, NetBeans use *--run* param to call NetBeansSuite.php.

**Comment by sebastianbergmann** [comment]
`--run` has never been an option supported by PHPUnit. Please report this with the vendor of your IDE.

**Comment by Jduret** [comment]
Yes, of course, it's a Netbeans param as I mention, used by the IDE to specify the test files to call.

But before the change (see pull request i've pasted), `--run` wasn't parsed has optional option by PHPUnit, and the given command line worked well, but now PHPUnit parse it and throw an error.
I've choosen to post the issue here because the change come from PHPUnit.
But if I'm wrong, sorry for the inconveniance.
