### ISSUE TITLE
Comparing specific columns using assertTablesEqual

### ISSUE THREAD

**Issue by spengilley** [sebastianbergmann/phpunit#1979]
Hi there,

I would like to be able to do the following;

Compare specific columns from a table and a dataset. For example;

I have some code which writes a hashed code to a table, against a specific user id. I know what the Id should be but I have no idea what the hash should be. So I only want to check that my 'user_id' column matches my expectations.

Currently assertTablesEqual tries to compare the entire table under test against my limited dataset.

I guess my first question is, is this currently possible? My second may be, how can I make this possible? :)

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported with the dbunit project.

**Comment by spengilley** [comment]
My apologies Sebastian. I also worked out how to do this since raising the ticket!
