### ISSUE TITLE
PHPT tests no longer support POST/POST_RAW etc

### ISSUE THREAD

**Issue by vbashkirtsev** [sebastianbergmann/phpunit#1980]
Since use of PEAR/RunTests was removed and PhptTestCase now parses PHPT files directly crucial PHPT functions are missing. At the moment there no way to execute tests under php-cgi which is necessary for file upload tests.

Dropping in PhptTestCase from 3.7 get the issue resolved but, of course, it is dirty hack relying on PEAR/RunTests as it was before and therefore is not good solution.

**Comment by sebastianbergmann** [comment]
I would gladly accept a pull request that implements this.

**Comment by sebastianbergmann** [comment]
No feedback, closing.
