### ISSUE TITLE
Latest phpunit.phar comes with symfony\yaml:~3.0 which breaks pre-3.0 symfony projects

### ISSUE THREAD

**Issue by scaytrase** [sebastianbergmann/phpunit#1982]
https://github.com/symfony/yaml/commit/6da0d7d6301d02086ad59c75ae38b0cbcad2b0d8

This commit within symfony 3.0 introduces new validation which immediately brokes testing of projects, which haven't updated their projects yet as phpunit's symfony\yaml version is loaded before another one.

**Comment by sebastianbergmann** [comment]
In a situation like that you cannot use PHPUnit from a PHAR. In the future this will be possible thanks to https://github.com/webmozart/php-scoper.

**Comment by scaytrase** [comment]
@sebastianbergmann thank you clarifying this
