### ISSUE TITLE
Using the option --coverage-clovers creates issue with @covers

### ISSUE THREAD

**Issue by gsouf** [sebastianbergmann/phpunit#1985]
I'm using the ``@covers`` annotation with the classname set in the use statement:

```php
use Somepackage\SomeClass;

/**
 * @covers SomeClass
 */
class SomethingTest....
```

running the test with ```phpunit --coverage-clover somepath``` will lead to the following error:

```
    Trying to @cover or @use not existing class or interface "SomeClass"
```

It works without the ``--coverage-clover``

Now if I remove the use statement and replaces the ``@cover`` value with the full class then it will work in both cases.

**Comment by gsouf** [comment]
Please not that using --coverage-clover while xdebug is not installed wont produce the error

**Comment by sebastianbergmann** [comment]
You need to use fully qualified class names in annotations.
