### ISSUE TITLE
phpunit 4.8 with php7 and xdebug 2.4.0RC3-dev coverage always 100%

### ISSUE THREAD

**Issue by samsonasik** [sebastianbergmann/phpunit#1987]
I've submitted issue in xdebug issue tracker, submitted here too if it may related with phpunit

**Comment by samsonasik** [comment]
http://bugs.xdebug.org/view.php?id=1224

**Comment by sebastianbergmann** [comment]
PHPUnit 4.8 is only supported on PHP 5.3, PHP 5.4, PHP 5.5, and PHP 5.6.

**Comment by samsonasik** [comment]
didn't try in phpunit 5, I will try to test in phpunit 5 if i have a chance
