### ISSUE TITLE
PHPUnit  null coallescing error

### ISSUE THREAD

**Issue by imamassi** [sebastianbergmann/phpunit#1992]
I tried PHPUnit 5.1.2 with a null coalescing operator on my code, here is what I got
```
Parse error: syntax error, unexpected '?' in /home/imam/carihadits/app/Template/Sidebar/Menu.php on line 34
```
And this is my line 34 code
```
$url = $this->url ?? 'javascript:;';
```

I believe this error was happened because PHPUnit doesn't support Null coalescing, or maybe I just don't do something that I required to do before/after updating my PHPUnit to latest stable release. Anyone with the same issue as me?

**Comment by GrahamCampbell** [comment]
Looks like you're running phpunit with php 5 rather than php 7?

**Comment by imamassi** [comment]
how do I change the version of php on my phpunit? I already am have PHP 7.1.0 on my linux

**Comment by GrahamCampbell** [comment]
Maybe it's a bug in PHP 7.1-dev?

**Comment by GrahamCampbell** [comment]
Trying using 7.0.0.

**Comment by imamassi** [comment]
nope, same error on both 7.0.0 and 7.1.0-dev (I use PHP 7.0.0 on my PHPBrew and PHP 7.1.0-dev as my default php version on my system)

**Comment by imamassi** [comment]
wait, I'd try to command `phpunit --version`, it said that I am currently use PHPUnit 3.7.28. But when I command with only `phpunit` it said that I used 5.1.2. What's the problem there?

**Comment by imamassi** [comment]
Well, I'd found the problem. I just have to update my PHPUnit in my system rather than only update my PHPUnit composer package. Thank you so much for trying to help:)
