### ISSUE TITLE
Argument Unpacking for Dependency Input

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#1994]
PHPUnit supports the declaration of explicit dependencies between test methods. Such dependencies do not define the order in which the test methods are to be executed but they allow the returning of an instance of the test fixture by a producer and passing it to the dependent consumers.

If the fixture that is to be passed from one test to another consists of more than one object then an array has to be used:

```php
class Test extends PHPUnit_Framework_TestCase
{
    public function testOne()
    {
        return [new Foo, new Bar];
    }

    /**
     * @depends testOne
     */
    public function testTwo(array $dependencyInput)
    {
        /** @var Foo $foo */
        $foo = $dependencyInput[0];

        /** @var Bar $bar */
        $bar = $dependencyInput[1];
    }
}
```

However, the code shown above (which is commonly used in a scenario like this) is ugly and verbose while not being explicit about the expected types for the dependency input.

It would be nice if PHPUnit would pass the elements of an array that is returned by one test not as an array to the dependent tests but as individual arguments:

```php
class Test extends PHPUnit_Framework_TestCase
{
    public function testOne()
    {
        return [new Foo, new Bar];
    }

    /**
     * @depends testOne
     */
    public function testTwo(Foo $foo, Bar $bar)
    {
    }
}
```

However, due to backwards compatibility (the fixture could actually be an array) concerns changing PHPUnit to behave as implied by the example above is not possible.

A solution could be the introduction of an option for the `@depends` annotation that enables "argument unpacking":

```php
class Test extends PHPUnit_Framework_TestCase
{
    public function testOne()
    {
        return [new Foo, new Bar];
    }

    /**
     * @depends argumentUnpacking testOne
     */
    public function testTwo(Foo $foo, Bar $bar)
    {
    }
}
```

**Comment by spriebsch** [comment]
I think creating a (custom) Fixture object (for each test with dependencies) would be better than returning an array.

**Comment by sebastianbergmann** [comment]
Stefan is right, this is not needed and should not be added.
