### ISSUE TITLE
Problem with PHP 7 return type declarations and mock objects

### ISSUE THREAD

**Issue by marklocker** [sebastianbergmann/phpunit#1995]
I've just ran into a problem when mocking an object which looks to be related to PHP 7 return type declarations.

I have an object which implements an interface like this:

    <?php

    namespace Example\Namespace;

    use Example\Collection;

    interface ExampleInterface
    {
        public function exampleMethod(int $id) : Collection;
    }

When mocking an object that implements this interface, I get the following error:

    PHP Fatal error:  Declaration of Mock_Example_62b1a36c::exampleMethod(int $id) must be compatible with Example\Namespace\ExampleInterface::exampleMethod(int $id): Example\Collection in /project/path/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php(291) : eval()'d code on line 1

Looking at the code that's being passed into `eval()`, I can see that it's the code for `Mock_Example_62b1a36c `, but it's missing the return type declaration on the `exampleMethod()` method - hence the error.

I'm hoping that someone familiar with this area of mock object generation can see a quick fix for this.

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-mock-objects](https://github.com/sebastianbergmann/phpunit-mock-objects) project.

**Comment by marklocker** [comment]
My bad, I've now raised it in the [correct place](https://github.com/sebastianbergmann/phpunit-mock-objects/issues/283).
