### ISSUE TITLE
phpunit 5 with php7 and xdebug 2.4.0RC3-dev coverage always 100%

### ISSUE THREAD

**Issue by samsonasik** [sebastianbergmann/phpunit#1996]
this is same issue of #1987 with phpunit 5. Still got 100% coverage.

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project.

**Comment by samsonasik** [comment]
Ok, created at https://github.com/sebastianbergmann/php-code-coverage/issues/411

**Comment by kegi** [comment]
I'm running xdebug 2.4.0RC4 and I'm not able to run the code coverage at all : "No whitelist configured, no code coverage will be generated", the same behaviour as if xdebug was missing. Am I missing something ?
