### ISSUE TITLE
PHPUnit 5.1.1+, PHP 7: Unexpected Token

### ISSUE THREAD

**Issue by JASchilz** [sebastianbergmann/phpunit#1997]
I'm getting the following error in Travis with PHPUnit 5.1.1/5.1.2 and PHP 7:

```
/home/travis/.phpenv/versions/7.0/bin/phpunit: line 1: html: No such file or directory
/home/travis/.phpenv/versions/7.0/bin/phpunit: phpunit: line 2: syntax error near unexpected token `<'
```

But no such error with 5.1.1/5.1.2 and PHP 5.6, and no error with 5.1.0 and PHP 7.

Example build with 5.1.0 (passes) [https://travis-ci.org/JASchilz/phpunit-bug-demo/builds/96063208](https://travis-ci.org/JASchilz/phpunit-bug-demo/builds/96063208)

Example build with 5.1.1 (fails) [https://travis-ci.org/JASchilz/phpunit-bug-demo/builds/96060799](https://travis-ci.org/JASchilz/phpunit-bug-demo/builds/96060799)

**Comment by sebastianbergmann** [comment]
Please bring this issue up with Travis CI. There is nothing wrong with PHPUnit itself that would explain this (AFAICS).

**Comment by JASchilz** [comment]
Roger. I'll eliminate PHPUnit by trying to duplicate it on my own machine.

**Comment by JASchilz** [comment]
Resolved. Must have been fixed on Travis' end.
