### ISSUE TITLE
PHPUnit 4.8 and PHP 7

### ISSUE THREAD

**Issue by tfrommen** [sebastianbergmann/phpunit#1998]
If I understand [this commit](https://github.com/sebastianbergmann/phpunit/commit/2d438255f0b87d7eb926ef15c1c7ace367df2672) correctly, you stated that PHPUnit 4.8 is not supported on PHP 7, and then changed your mind and reverted that. Is that right?

If so, you, of course, have to add PHP 7 in the [`composer.json`](https://github.com/sebastianbergmann/phpunit/blob/7438c43bc2bbb2febe1723eb595b1c49283a26ad/composer.json#L24) again.

PHPUnit 4.8.19 worked totally fine on PHP 7. With 4.8.20, it now, of course, fails.

**Comment by sebastianbergmann** [comment]
The website clearly states that PHPUnit 4.8 is not supported on PHP 7.

**Comment by tfrommen** [comment]
Then I don't seem to understand the linked commit (which **partly** reverts stuff). Sorry. I just take "PHPUnit 4.8 is not supported on PHP 7" as given then.
