### ISSUE TITLE
Missing argument 3 for PHPUnit_TextUI_TestRunner::doRun()

### ISSUE THREAD

**Issue by craue** [sebastianbergmann/phpunit#2010]
When running PHPUnit (latest master commit d9f7261789f3999778a6ad99d019790c8a0e636e) with PHP 5.6 on [Travis](https://travis-ci.org/craue/CraueConfigBundle/jobs/97215486#L284), I'm getting the error `Missing argument 3 for PHPUnit_TextUI_TestRunner::doRun(), called in phar:///home/travis/.phpenv/versions/5.6.5/bin/phpunit/phpunit/TextUI/Command.php on line 152`.

**Comment by craue** [comment]
Never mind, seems the system's (old) PHPUnit installation was used instead of my own one.

**Comment by tam5** [comment]
I am also having this error. PHPUnit 5.2.4 is being used on Travis as well as on my local machine. Travis gives the error `Missing argument 3 for PHPUnit_TextUI_TestRunner::doRun()`for PHP 5.6 as well as hhvm, but for php 7 it passes.

any ideas?
