### ISSUE TITLE
PHPUnit's PHP version check error message doesn't contain the actual version

### ISSUE THREAD

**Issue by winks** [sebastianbergmann/phpunit#2012]
Steps to reproduce:
- Have PHP 5.5 installed
- Have phpunit 5.x installed
- Run `phpunit --version`

Expected outcome:

```
This version (5.1.3) of PHPUnit requires PHP 5.6; using the latest version of PHP is highly recommended.
```

Actual output:

```
This version of PHPUnit requires PHP 5.6; using the latest version of PHP is highly recommended.
```

Yes, I only had to `vi /usr/local/bin/phpunit` to see the version in the code, but I still think this could _easily_ be fixed to be an actually helpful message.
Plus, this is not special to the 4.x -> 5.x breaking change, it applies to all breaking changes.

**Comment by GrahamCampbell** [comment]
Why not just say `PHPUnit 5.1.3 requires PHP 5.6; using the latest version of PHP is highly recommended.`

**Comment by sebastianbergmann** [comment]
@GrahamCampbell The version number is defined in `PHPUnit_Runner_Version`. By the time the error message in question needs to be printed we have not yet set up the class loader so that class and the information held by it is not available.

We could use `__FILE__`, though.

**Comment by sebastianbergmann** [comment]
Closing this in favour of #2563.
