### ISSUE TITLE
Tests get stuck if a test expects parameters but doesn't receive any

### ISSUE THREAD

**Issue by rtheunissen** [sebastianbergmann/phpunit#2017]
~~if you implement an abstract test class, and have a function that uses a data provider via `@dataProvider`, and you override that function in another class, the test suite freezes. Unless you also copy the docblock.~~

Actually this seems to be due to the fact that args are expected but never received.

**Comment by sebastianbergmann** [comment]
Can you please provide a minimal, self-contained, reproducing test case? Thanks!

**Comment by sebastianbergmann** [comment]
No feedback, closing.
