### ISSUE TITLE
Windows 10 the color coding does not work

### ISSUE THREAD

**Issue by neeravp** [sebastianbergmann/phpunit#2018]
I am on windows 10 and can run the tests using the full path. But am not able to get any color coding wven with `--colors="always" flag`. Also I have already set debug=true in my environment but still if I don't use `--debug flag` I don't get enough output.  
I am using Power Shell and running phpunit in Laravel 5.1

**Comment by sstok** [comment]
Try using ConEmu, Colors in PHPUnit are done using ANSI which is not supported in Windows.

**Comment by neeravp** [comment]
Thanks a lot for pointing me ConEmu.
It seems to be a great tool as regards to the settings options. Solved my
issue. Thanks again.


On Fri, Jan 1, 2016 at 3:55 PM, Sebastiaan Stok <notifications@github.com>
wrote:

> Try using ConEmu, Colors in PHPUnit are done using ANSI which is not
> supported in Windows.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sebastianbergmann/phpunit/issues/2018#issuecomment-168297302>
> .
>



-- 
Best Regards,
Neerav Pandya
Mb.: +91-90330 00026
