### ISSUE TITLE
Parse error in file '/vendor/phpunit/php-token-stream/tests/_fixture/class_with_method_that_declares_anonymous_class.php'

### ISSUE THREAD

**Issue by hamdon** [sebastianbergmann/phpunit#2020]
environment:
php version:PHP 5.6.16 (cli) (built: Nov 27 2015 21:46:01) 
jenkins+ant+(php-template)

Console Output :
<pre>
<code>
generate-code:
     [exec] /usr/bin/env: php
     [exec] : No such file or directory
     [exec] Result: 127
     [exec] phpab 1.14.1 - Copyright (C) 2009 - 2015 by Arne Blankerts
     [exec] 
     [exec] Scanning directory /root/.jenkins/workspace/blackboxcentera/vendor
     [exec] 
     [exec] Error while processing request:
     [exec]  - Parse error in file '/root/.jenkins/workspace/blackboxcentera/vendor/phpunit/php-token-stream/tests/_fixture/class_with_method_that_declares_anonymous_class.php' while trying to process class definition.
     [exec] 
     [exec] 
     [exec] Result: 1
</code>
</pre>

what should i do in the build.xml to solve the issue?

**Comment by sebastianbergmann** [comment]
This is not a PHPUnit issue, sorry.

**Comment by hamdon** [comment]
thx for answer
