### ISSUE TITLE
composer.json uses unbounded versions causing composer validate --with-dependencies to fail

### ISSUE THREAD

**Issue by whatsma** [sebastianbergmann/phpunit#2021]
The composer.json file uses unbounded version numbers for php-timer and phpunit-mock-objects dependencies.

This causes any project that requires phpunit and then validates itself and its dependencies using

```
composer validate --with-dependencies
```
to fail.

Reproduce by creating an empty directory containing the following composer.json file:

```
{
    "name": "example/name",
    "description": "example description",
    "license": "MIT",
    "require": {
        "phpunit/phpunit": "5.1.*"
    }
}
```

And then do a 
```
composer install
```

Then do a 
```
composer validate --with-dependencies
```

This will give the error:
```
require.phpunit/php-timer : unbound version constraints (>=1.0.6) should be avoided
require.phpunit/phpunit-mock-objects : unbound version constraints (>=3.0.5) should be avoided
```
[This Document](https://getcomposer.org/doc/faqs/why-are-unbound-version-constraints-a-bad-idea.md) explains why unbounded version constraints are a bad idea.

**Comment by GrahamCampbell** [comment]
Unfortunately, it's a bit late. Composer will just resolve an older version which still had the unbounded dependencies in order to satisfy constraints if it needed to.
