### ISSUE TITLE
Proposal: deprecate getMock*

### ISSUE THREAD

**Issue by keradus** [sebastianbergmann/phpunit#2023]
Since 4.5 PHPUnit supports Prophecy natively.
Maybe original `getMock*` could be marked as deprecated and removed in next major release?

**Comment by edsonmedina** [comment]
Prophecy doesn't support partial mocks (by design).
Will phpunit drop that feature too?

**Comment by sebastianbergmann** [comment]
PHPUnit's own test doubles implementation is not going away (anytime soon).
