### ISSUE TITLE
phpunit requires PHP 5.6, but already installed it.

### ISSUE THREAD

**Issue by demavend** [sebastianbergmann/phpunit#2025]
Hi, I'm using XAMPP 5.6.15 on OS X El Capitan. This version of XAMPP includes PHP 5.6.15.
But why phpunit says to me "This version of PHPUnit requires PHP 5.6; using the latest version of PHP is highly recommended."
Or does phpunit require the latest version of PHP CLI? This is 5.5.30.

Below code is my composer.json
```
"require-dev": {
        "phpunit/phpunit": "^5.1"
    },
"config": {
      "platform": {
        "php": "5.6.15"
      }
    }
```

**Comment by GrahamCampbell** [comment]
> Or does phpunit require the latest version of PHP CLI? This is 5.5.30.

Yes.

**Comment by GrahamCampbell** [comment]
It's the CLI version that needs to be 5.6+.

**Comment by demavend** [comment]
How to update? I tried to add symbolic link but the terminal says, "Operation not permitted". So I disable nvram rootless, It can't.

**Comment by demavend** [comment]
I've fixed. Just install php56 with homebrew. Thank you.
