### ISSUE TITLE
Deprecated options in ini_set

### ISSUE THREAD

**Issue by ivopetkov** [sebastianbergmann/phpunit#2027]
I encounter the following problem in PHPUnit v4.8, v5.1 and v5.2-beta. I'm running PHP v5.6.
My app has a custom error handler. I want to capture all errors, log them and output a nice message. But when testing PHPUnit always triggers the following error:
```
ini_set(): Use of iconv.output_encoding is deprecated in file in C:\...\Temp\PHP37B6.tmp:62
```
I think a PHP version check will be nice.

**Comment by sebastianbergmann** [comment]
That version check should be put into the test code that calls `ini_set()`.
