### ISSUE TITLE
Compatibility with Symfony 3.0?

### ISSUE THREAD

**Issue by bibeksigdel33** [sebastianbergmann/phpunit#2035]

**Comment by GrahamCampbell** [comment]
What are you actually asking?

**Comment by bibeksigdel33** [comment]
Is this library compatible with symfony 3.0. .?  Since it requires some other libraries that require symfony components .

**Comment by GrahamCampbell** [comment]
Why don't you just try installing it?

**Comment by bibeksigdel33** [comment]
I already have a project in symfony 2.8 .. And I want to upgrade it to symfony 3.0 . So I need to be sure if some libraries and bundles are supported or not. I cannot upgrade symfony to 3.0 by myself but I have to inform others about the libraries and bundles that may be supported or not. You seems like senior programmer please help me to solve my issues

**Comment by sebastianbergmann** [comment]
This is not a discussion / support forum, sorry.
