### ISSUE TITLE
still slow with --no-coverage

### ISSUE THREAD

**Issue by stopsopa** [sebastianbergmann/phpunit#2038]
I have configuration in phpunit.xml for travis-ci and coveralls.io stack containig this:

    <logging>
        <log type="coverage-clover" target="build/logs/clover.xml"/>
    </logging>

... but when i run test locally i don't need code coverage file generation, so i use --no-coverage. But as i noticed time of execution is the same with or without this switch (still long time). I guess that entire coverage analyse is still happening under the hod but only file is not generated. I think it could be done better - entire code coverage can be really omited in code after using this switch.

This cause that i need comment this configuration block to make phpunit working fast, i guess this not only affect me.

If i'm wrong just close this issue. Thx.

Samples:

test with COMMENTED block <log type="coverage-clover"....

    bash:> time phpunit
    PHPUnit 5.1.4 by Sebastian Bergmann and contributors. 
    ...
    ...
    real    0m0.172s
    user    0m0.093s
    sys     0m0.048s

test with UNCOMMENTED block <log type="coverage-clover"....

    bash:> time phpunit
    PHPUnit 5.1.4 by Sebastian Bergmann and contributors. 
    ...
    ...
    real    0m5.516s
    user    0m0.521s
    sys     0m2.245s
    

test with --no-coverage and UNCOMENTED  <log type="coverage-clover"....

    bash:> time phpunit --no-coverage
    PHPUnit 5.1.4 by Sebastian Bergmann and contributors. 
    ...
    ...
    real    0m5.287s
    user    0m0.264s
    sys     0m2.322s

**Comment by sebastianbergmann** [comment]
When `--no-coverage` is used then no code coverage data will be collected and there is no slowdown incurred by anything related to code coverage analysis.

```
$ git clone https://github.com/sebastianbergmann/money.git

$ cd money

$ phpunit -c build
PHPUnit 5.1.4 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.0.2 with Xdebug 2.4.0RC3
Configuration: /usr/local/src/money/build/phpunit.xml

.............................................                     45 / 45 (100%)

Time: 226 ms, Memory: 10.00Mb

OK (45 tests, 71 assertions)

Generating code coverage report in Clover XML format ... done

Generating Crap4J report XML file ... done

Generating code coverage report in HTML format ... done

Generating code coverage report in PHPUnit XML format ... done

$ phpunit -c build --no-coverage
PHPUnit 5.1.4 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.0.2 with Xdebug 2.4.0RC3
Configuration: /usr/local/src/money/build/phpunit.xml

.............................................                     45 / 45 (100%)

Time: 38 ms, Memory: 4.00Mb

OK (45 tests, 71 assertions)
```
