### ISSUE TITLE
Phpunit 3.7 has error with hhvm

### ISSUE THREAD

**Issue by timalive** [sebastianbergmann/phpunit#2041]
Phpunit 3.7 running as part of Cake 2.7.5 gives an error when trying to run PHPunit.  Note that PHPunit works correctly when hhvm.repo.authoritative = false is set for hhvm.   When it is set to true then PHPUnit gives this error:
`Fatal error: File not found: phar://phpunit-3.7.38.phar/phpunit/TextUI/Command.php in /var/www/Reports/app/Vendor/phpunit.phar on line 611`
Cakephp finds the phar and executes it but this error is thrown.
Any insight on how to avoid this, or a fix, would be appreciated.

**Comment by sebastianbergmann** [comment]
PHPUnit 3.7 is not supported anymore.
