### ISSUE TITLE
Is it possible to mock and inject traits?

### ISSUE THREAD

**Issue by TravisCarden** [sebastianbergmann/phpunit#2043]
I originally posted this question on Programmers Stack Exchange: [Is it possible to mock and inject traits in PHPUnit?](http://programmers.stackexchange.com/questions/307039/is-it-possible-to-mock-and-inject-traits-in-phpunit). But I didn't get an answer. Perhaps someone here can give some insight.

I need to extend a third party class I cannot modify. The class's dependencies are for the most part injected through the constructor, making them easy to mock. However the class also uses methods from a trait that call global services directly, destroying test isolation. Here's a code sample that illustrates the problem:

```php
trait SomeTrait {
  public function irrelevantTraitMethod() {
    throw new \Exception('Some undesirable behavior.');
  }
}

class SomeSystemUnderTest {
  use SomeTrait;
  public function methodToTest($input) {
    $this->irrelevantTraitMethod();
    return $input;
  }
}

class MockWithTraitTest extends \PHPUnit_Framework_TestCase {
  public function testMethodToTest() {
    $sut = new SomeSystemUnderTest();
    $this->assertSame(123, $sut->methodToTest(123)); // Unexpected exception!
  }
}
```

How does one deal with a situation like this in PHPUnit? Can traits be mocked and injected somehow? The only solution I've found is to mock the SUT itself and just nullify the troublesome methods from the trait, leaving the actual SUT methods intact:

```php
class MockWithTraitTest extends \PHPUnit_Framework_TestCase {
  public function testMethodToTest() {
    /** @var \SomeSystemUnderTest|\PHPUnit_Framework_MockObject_MockObject $sut */
    $sut = $this->getMockBuilder('\SomeSystemUnderTest')
      ->setMethods(array('irrelevantTraitMethod'))
      ->getMock();
    $this->assertSame(123, $sut->methodToTest(123)); // OK.
  }
}
```
This approach works of course, but I dislike it because I'm afraid it requires too tight coupling to the implementation and could lead to fragile tests. (What if I add another method to the trait, say for logging, and use it in the SUT? It will cause irrelevant test failures until I update all my mocks.) I would much prefer to be able to mock the whole trait. Am I thinking about the problem wrong?

**Comment by dharkness** [comment]
I think mocking the SUT is your only option, just as if you wanted to mock a method from the parent class. The traits members are effectively copied into each class that uses it. It's not a separate component.

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.
