### ISSUE TITLE
@covers should accept names based on file namespace

### ISSUE THREAD

**Issue by rentalhost** [sebastianbergmann/phpunit#2045]
It continues #1312 on 5.1/5.2 branch.

Basically, now phpunit don't accept simplified classnames on `@covers`, then you should write always the full qualified name, instead.

```
namespace My\App\Namespace;

/**
 * @covers SomeClass::method (doesn't works)
 * @covers My\App\Namespace\SomeClass::method (do works)
 */
```

**It should be:**
- `SomeClass` equals to `\My\App\Namespace\SomeClass`;
- `\My\App\Namespace\SomeClass` equals to `\My\App\Namespace\SomeClass`;
- `My\App\Namespace\SomeClass` equals to `\My\App\Namespace\SomeClass\My\App\Namespace\SomeClass`;

The last case is how PHP understand it normally, when you do it on code. But phpunit can try a fallback to avoid breaking changes, including the first backslash automatically if the first possibility fails:
- `\My\App\Namespace\SomeClass\My\App\Namespace\SomeClass` (as PHP would does);
- `\My\App\Namespace\SomeClass` (as fallback if previous fail);

Or a smart way, if `@covers` classname starts with exactly same name of current namespace, it should understand as a FQN, even if first backslash is omitted.

**Comment by sebastianbergmann** [comment]
While I think this would be useful I will not work on implementing this. Of course, I will gladly consider a pull request that implements this. Unfortunately none of the participants of #1312 seem to be interested in this anymore.

**Comment by KrunoKnego** [comment]
I'll try to work on this issue when I get time.

**Comment by sebastianbergmann** [comment]
No feedback, closing.
