### ISSUE TITLE
assertXmlStringEqualsXmlString also checks white spaces

### ISSUE THREAD

**Issue by simohammedhttp** [sebastianbergmann/phpunit#2046]
One may think that the following test will pass, this is not true at all.

$this->assertXmlStringEqualsXmlString('&lt;foo>&lt;bar/> &nbsp;  &lt;/foo>', '&lt;foo>&lt;bar/>&lt;/foo>');

Before fixing the issue in github.com/sebastianbergmann/phpunit/issues/1860, the method checks only the skeleton of the two strings.

**Comment by max-voloshin** [comment]
Use `assertEqualXMLStructure` instead of `assertXmlStringEqualsXmlString`

**Comment by Klizzy** [comment]
assertXmlStringEqualsXmlString works as intended.

@sebastianbergmann i think this can be closed
