### ISSUE TITLE
Support `@requires class`

### ISSUE THREAD

**Issue by joshuaspence** [sebastianbergmann/phpunit#2051]
The `@requires` annotation can be used as `@requires function` or `@requires extension` but there doesn't seem to be the ability to use `@requires class`. I want to use this functionality to conditionally run tests which depend on an optional dependency. The easiest way to check if the dependency is installed is to check whether a class from the package exists.

**Comment by sebastianbergmann** [comment]
This would be ambiguous with regard to extensions that declare a class that has the same name as the extension. Just use `markTestSkipped()` in the test or `setUp()` method.
