### ISSUE TITLE
Builds in the Repository not up to date.

### ISSUE THREAD

**Issue by Huskynarr** [sebastianbergmann/phpunit#2053]
The version in the current Debian 8 (jessie) repository is quite outdated.
Would it be possible to bring these times to a current status?
I think that a lot of people the Debian or Ubuntu use, thereby automatically use the old version, which is long-term ill.

At least one integration of the current version in Dotdeb would be desirable.

**Comment by sebastianbergmann** [comment]
This is out of the scope of this project. Please bring this up with either Debian or Dotdeb.
