### ISSUE TITLE
Segmentation Fault by Self Referncing of a Method

### ISSUE THREAD

**Issue by michaelscheffencaker** [sebastianbergmann/phpunit#2058]
Using: Laravel 5.2, PHP 5.6.11, ubuntu
Inside a method price() I had a typo and wrote $this->price() instead of $this->price . This lead to an segmentation fault.

**Comment by sebastianbergmann** [comment]
This is not a problem with PHPUnit.

**Comment by michaelscheffencaker** [comment]
Wow, thanks for the fast response. Where do you think should I submit this issue?

**Comment by sebastianbergmann** [comment]
There is no issue to submit. Infinite recursion leads to a segmentation fault. Period.

**Comment by michaelscheffencaker** [comment]
Okay :)
