### ISSUE TITLE
Add new lines on test result

### ISSUE THREAD

**Issue by luiscoms** [sebastianbergmann/phpunit#2059]
When I run the tests on command line some dots are visible, can you add a new line to better view?

Example:

    Release\IO\ComposerIO
    ............ [x] Load composer file content recursively
     [x] Missing composer file

    Release\Version
    ..................................... [x] Default version
     [x] To string

Can be better like this:

    Release\IO\ComposerIO
    ............ 
     [x] Load composer file content recursively
     [x] Missing composer file

    Release\Version
    ..................................... 
     [x] Default version
     [x] To string

Thanks

**Comment by sebastianbergmann** [comment]
How do you invoke PHPUnit to get the output you show above? Which version of PHPUnit are you using?

**Comment by luiscoms** [comment]
I am invoking in line command like this `phpunit -c tests/phpunit.xml` 

    PHPUnit 4.8.22 by Sebastian Bergmann and contributors.

    Runtime:	PHP 5.6.17 with Xdebug 2.3.3

The project that I'm writing is [luiscoms/release](https://github.com/luiscoms/release)

**Comment by sebastianbergmann** [comment]
You are sending TestDox output to `STDOUT` (see https://github.com/luiscoms/release/blob/master/tests/phpunit.xml#L33). That does not make sense.

You probably want to configure `PHPUnit_Util_TestDox_ResultPrinter_Text` as your result printer using the `printerClass` configuration option.

**Comment by luiscoms** [comment]
Why it does not make sense? Once I want to read the test results on the bash.

**Comment by gempir** [comment]
In the modern/new version of PHPUnit which Class would make most sense extending/overwriting so the textdox output begins with a newline?

**Comment by epdenouden** [comment]
@gempir I am working on refactoring some Listener stuff, will post details for you here tonight.

If you have the time you could look recent commits in my 'breakfast' branch. (on mobile, hard to post links)
