### ISSUE TITLE
Version 1.0 and 2.0 ?

### ISSUE THREAD

**Issue by remicollet** [sebastianbergmann/phpunit#2060]
Is-it possible to requires ~1.0 || ~2.0  (as in php-codecoverage)

I don't see any change in the API (excepted it requires PHP 5.6)

As lot of components require version ~1.0, current requirement will prevent people to upgrade to 5.2 (using composer)

**Comment by sebastianbergmann** [comment]
"Problems" like this are the reason I discourage the use of Composer to install tools such as PHPUnit.

**Comment by remicollet** [comment]
thanks.

(and I "never" use composer ;) but only dependencies information from composer.json)
