### ISSUE TITLE
Wrong EOL date for PHPUnit 5

### ISSUE THREAD

**Issue by Naktibalda** [sebastianbergmann/phpunit#2063]
https://github.com/sebastianbergmann/phpunit/wiki/Release-Announcement-for-PHPUnit-5.2.0

PHPUnit 6, which is scheduled for **February 3, 2017**, will no longer support PHP 5. 
Following our release process, PHPUnit 5 will receive bug fixes until **February 3, 2017**

According to your release process, PHPUnit 5 should receive bug fixes until **February 3, 2018**

**Comment by sebastianbergmann** [comment]
Closed in https://github.com/sebastianbergmann/phpunit/wiki/Release-Announcement-for-PHPUnit-5.2.0/dc6e38207a65249456b549cffa1c234be455ae02
