### ISSUE TITLE
report skipped and incomplete test results with --log-junit 

### ISSUE THREAD

**Issue by SimonHeimberg** [sebastianbergmann/phpunit#2064]
The log file generated with --log-junit does not contain tests with result `skipped` or `incomplete`.
I suggest to include them and add the child `<skipped/>` to the testcase.
Unfortunately the element skipped seems not to support any attribute or content. So it is not possible to distinguish between skipped and incomplete, nor to add the custom message.

The `<testsuite>` can contain the following additional attributes:
- disabled: The total number of disabled tests in the suite. optional
- skipped: The total number of skipped tests. optional

example code snipped with skipped test case

``` xml
  <testsuite name="anyApp\Tests\SomeTest" file="path\to\Test.php" tests="2" assertions="3" failures="1" errors="0" skipped="1" disabled="0" time="4.643617">
        <testcase name="testSomething" class="anyApp\Tests\SomeTest" file="path\to\Test.php" line="11" assertions="1" time="0.614055">
          <skipped/> 
        </testcase>
...
```

References:
http://help.catchsoftware.com/display/ET/JUnit+Format
http://llg.cubic.org/docs/junit/

**Comment by ryanaslett** [comment]
Was this already fixed here? https://github.com/sebastianbergmann/phpunit/commit/d5297098db6af01c52f120ccec08ec92c3137816
