### ISSUE TITLE
composer.json requiring version of php-code-coverage that does not exist

### ISSUE THREAD

**Issue by mikesoule** [sebastianbergmann/phpunit#2065]
Installing PHPUnit via composer is failing because there is a dependency on php-code-coverage ~3.2, which does not yet exist.

**Comment by sebastianbergmann** [comment]
`5.3` and `master` depend on `~3.2` both of which are as unstable as `3.2` of PHP_CodeCoverage so I do not understand what you are trying to report.

**Comment by mikesoule** [comment]
Yeah, I realized I shouldn't have installed PHPUnit as dev-master rather than specifying a version. However, if there's a dependency on PHP_CodeCoverage 3.2, shouldn't there be a branch or tag named 3.2 here?
https://github.com/sebastianbergmann/php-code-coverage

**Comment by sebastianbergmann** [comment]
No: https://github.com/sebastianbergmann/php-code-coverage/blob/master/composer.json#L50
