### ISSUE TITLE
PHP Fatal error:  Call to undefined method SebastianBergmann\Environment\Runtime::isPHPDBG()

### ISSUE THREAD

**Issue by maxca** [sebastianbergmann/phpunit#2067]
I have something wrong, Help me please
when i run: phpunit
PHP Fatal error:  Call to undefined method SebastianBergmann\Environment\Runtime::isPHPDBG()

**Comment by maxca** [comment]
PHP 5.6.7-1 (cli) (built: Mar 24 2015 12:30:15) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans

**Comment by sebastianbergmann** [comment]
How did you install PHPUnit? Which version of PHPUnit did you install?

**Comment by maxca** [comment]
Thank you sir for answer ,i have already fixed ,by update version phpunit. from 4 to 5
