### ISSUE TITLE
Restore DeepCopy in the backtrace

### ISSUE THREAD

**Issue by Slamdunk** [sebastianbergmann/phpunit#2068]
Hi, the `PHPUnit_Util_Blacklist` removes from the Error/Exception backtrace of a failing test some folders/files relative to the internals of PHPUnit.

This is ok until a project uses the same package of PHPUnit, and this is the case of DeepCopy:
https://github.com/sebastianbergmann/phpunit/blob/5.2.3/src/Util/Blacklist.php#L43

Many projects (all of mine) use this package, and if errors are encountered with or in this package, it's impossible to debug because of trace suppression.

It is not possible to distinguish the part of the trace inner to PHPUnit from an error raised within the SUT, as far as I know.

May we remove it from Blacklist and restore the backtrace of this package?

**Comment by sebastianbergmann** [comment]
The solution you propose is wrong, IMHO. I think there should be a configuration setting for the stacktrace filtering.

**Comment by Slamdunk** [comment]
You mean something like `--full-error-trace` that mimics https://github.com/sebastianbergmann/phpunit/blob/5.2.3/src/Util/Blacklist.php#L70-L72 ?

I agree. Do you want me to PR it?

**Comment by sebastianbergmann** [comment]
It will be hard to (cleanly) get the configuration flag passed to the unit of code you mention. It's probably better (and easier) to handle this earlier (in the context where `getFilteredStacktrace()` is called).

**Comment by sebastianbergmann** [comment]
Closed in favor of #2089.
