### ISSUE TITLE
assertArraySubset() bad documented or doesn't work as expected

### ISSUE THREAD

**Issue by kgkg** [sebastianbergmann/phpunit#2069]
Hi,

please consider 3 calls:
1) $this->assertArraySubset( ['a', 'b', 'c'], ['a', 'b', 'c', 'd'] );
2) $this->assertArraySubset( ['b', 'c'], ['a', 'b', 'c', 'd'] );
3) $this->assertArraySubset( ['a', 'c', 'b'], ['a', 'b', 'c', 'd'] );

1 - works
2 - doesn't work. Why? Isn't ['b','c'] a subset of ['a', 'b', 'c', 'd']?
3 - doesn't work as well. Elements must be in apriopriate order?

Should it work this way? 
Can information about this be added to docs? (3 little examples above should do)?
It's sort of confusing right now :)

**Comment by GrahamCampbell** [comment]
> Isn't ['b','c'] a subset of ['a', 'b', 'c', 'd']?

`[1 => 'b', 2 => 'c']` is though

**Comment by sebastianbergmann** [comment]
This is a question for @marcioAlmada who implemented this feature.

**Comment by kgkg** [comment]
It should be considered that some people are probably depending in their tests on this behaviour, so maybe it's not wise to change it. 
Maybe function working like I described should be added to phpunit as another assert function?

**Comment by jboffel** [comment]
Hi, I guess this function should have a flag to not consider index position.

For explicit associative array where you name the key this won't be a problem. However for dynamic index array this is indeed a problem to consider the order.


1.     $this->assertArraySubset(['World!' => 'b'], ['Hello' => 'a', 'World!' => 'b']);
2.     $this->assertArraySubset(['Hello' => 'a'], ['Hello' => 'a', 'World!' => 'b']);
3.     $this->assertArraySubset(['World!' => 'b', 'Hello' => 'a'], ['Hello' => 'a', 'World!' => 'b']);
4.     $this->assertArraySubset(['Hello' => 'a', 'World!' => 'b'], ['Hello' => 'a', 'World!' => 'b']);

1 to 4 will pass successfully regardless of the order as expected with this assertion function name.


But when it comes to dynamically assigned index 

1.     $this->assertArraySubset( ['a', 'b', 'c'], ['a', 'b', 'c', 'd'] );
2.     $this->assertArraySubset( ['b', 'c'], ['a', 'b', 'c', 'd'] );
3.     $this->assertArraySubset( ['a', 'c', 'b'], ['a', 'b', 'c', 'd'] );

As said above:

1 - works
2 - doesn't work.
3 - doesn't work.

A quick fix is to loop over the expected array subset for each key and run assertContains to the actual array to dismiss the index criteria. However you'll have issue with mixed array, partially explicit key definition and dynamic attribution.

So, either you restrict usage of this function to the only array with explicit associate key, or this function should have a flag to mention "This is an associative array" or "This is a non associative array". The mixed case will remain unsupported though.

**Comment by marcioAlmada** [comment]
Hi!

Somehow I missed the notifications on this thread.

Indeed this assertion was only discussed in the context of "associative arrays". I believe that for a pair of non associative arrays the assertion should be represented by an intersection followed by a sorted comparison:

```diff
diff --git a/src/Framework/Constraint/ArraySubset.php b/src/Framework/Constraint/ArraySubset.php
index c3cb095..d3569b6 100644
--- a/src/Framework/Constraint/ArraySubset.php
+++ b/src/Framework/Constraint/ArraySubset.php
@@ -49,12 +49,26 @@ public function __construct($subset, $strict = false)
      */
     protected function matches($other)
     {
-        $patched = array_replace_recursive($other, $this->subset);
+        if (! $this->isArrayAssociative($this->subset)) {
+            $patched = array_intersect($other, $this->subset);
 
-        if ($this->strict) {
-            return $other === $patched;
-        } else {
-            return $other == $patched;
+            sort($patched);
+            sort($this->subset);
+
+            if ($this->strict) {
+                return $this->subset === $patched;
+            } else {
+                return $this->subset == $patched;
+            }
+        } else {          
+
+            $patched = array_replace_recursive($other, $this->subset);
+
+            if ($this->strict) {
+                return $other === $patched;
+            } else {
+                return $other == $patched;
+            }
         }
     }
 
@@ -82,4 +96,9 @@ protected function failureDescription($other)
     {
         return 'an array ' . $this->toString();
     }
+
+    private function isArrayAssociative(array $subject)
+    {
+        return count(array_filter(array_keys($subject), 'is_string')) > 0;
+    }
 }
diff --git a/tests/Framework/AssertTest.php b/tests/Framework/AssertTest.php
index 984346c..b63fe2d 100644
--- a/tests/Framework/AssertTest.php
+++ b/tests/Framework/AssertTest.php
@@ -182,6 +182,10 @@ public function testAssertArraySubset()
         $this->assertArraySubset(['a' => 'item a', 'c' => ['a2' => 'item a2']], $array);
         $this->assertArraySubset(['a' => 'item a', 'd' => ['a2' => ['b3' => 'item b3']]], $array);
 
+        $this->assertArraySubset(['a', 'b', 'c'], ['a', 'b', 'c', 'd']);
+        $this->assertArraySubset(['b', 'c'], ['a', 'b', 'c', 'd']);
+        $this->assertArraySubset(['b', 'a'], ['a', 'b', 'c', 'd' => 3, 'x']);
+
         try {
             $this->assertArraySubset(['a' => 'bad value'], $array);
         } catch (PHPUnit_Framework_AssertionFailedError $e) {
```

This patch could be a starting point, I'm in transit and wasn't able to PR :airplane: but I'll be back ASAP. It would be good to have a discussion/RFC on any the other expected behaviors before proceeding.

**Comment by sebastianbergmann** [comment]
Thank you for looking into this, @marcioAlmada.

**Comment by thiagoaos** [comment]
Will this patch be applyed in 5.7 version?

**Comment by sebastianbergmann** [comment]
@marcioAlmada Is https://github.com/sebastianbergmann/phpunit/issues/2069#issuecomment-260271597 a bugfix? Can you send a pull request?

**Comment by jblotus** [comment]
Came across this issue today. Will the patch be implemented at some point @marcioAlmada ?

**Comment by sebastianbergmann** [comment]
I am still confused about `assertArraySubset()`. Could this already be fixed by #2237? In case it's not:

@marcioAlmada Is https://github.com/sebastianbergmann/phpunit/issues/2069#issuecomment-260271597 backward compatible? Can you please send a pull request with that patch? Thanks!

**Comment by sebastianbergmann** [comment]
No feedback, closing.

**Comment by skovron** [comment]
Please see [comment](https://github.com/sebastianbergmann/phpunit/pull/2781#issuecomment-362592877) on #2781:
