### ISSUE TITLE
TeamCity output generates lots of empty newlines

### ISSUE THREAD

**Issue by Majkl578** [sebastianbergmann/phpunit#2070]
When running PHPUnit inside TeamCity with `--teamcity` which, the build log contains lots of useless empty lines.
It looks like PHPUnit_Util_Log_TeamCity::printEvent generates two newlines per entry.
I'm not sure when this would be correct, maybe for testFinished, but not always.

Example:
![teamcity-output](https://cloud.githubusercontent.com/assets/144181/12916442/d678ef96-cf32-11e5-9a2d-3ba5559d908f.png)

**Comment by SvetlanaZem** [comment]
It's working this way to make sure teamcity output is separated from test output. Probably we could come up with the decision to minimize empty lines.

**Comment by SvetlanaZem** [comment]
I've investigated the problem for some time and I don't see an easy fix that will work for multi threaded tests. More complicated solution (e.g. additional buffering) may cause more harm than good.

I'll postpone the issue and get back to it later. Any ideas will be really appreciated.

**Comment by sebastianbergmann** [comment]
Any update on this? Can this be closed?

**Comment by SvetlanaZem** [comment]
@sebastianbergmann Sorry, I didn't check the issue since my last comment. @wbars will check it out in the nearest future and write here a status update.

**Comment by wbars** [comment]
@sebastianbergmann Hello! After some investigation I did not found easy general fix of this problem (indeed, there can be complicated cases like multithreaded tests). We took the issue in [our tracker](https://youtrack.jetbrains.com/issue/WI-40679) and going to work on this according to the issue priority, so, feel free to close this particular ticket.

**Comment by sebastianbergmann** [comment]
Thanks @wbars and @SvetlanaZem.
