### ISSUE TITLE
Prophecy and "This test did not perform any assertions"

### ISSUE THREAD

**Issue by etienneq** [sebastianbergmann/phpunit#2071]
I have a test that uses Prophecy (and no assertions from PHPUnit). When PHPUnit runs in strict mode, it reports for this test "This test did not perform any assertions". Is there any known solution to this?

I'm using PHPUnit 4.7.7 and Prophecy 1.5.0.

**Comment by GrahamCampbell** [comment]
Pretty sure this was fixed already. Please try with a newer version of phpunit.

**Comment by GrahamCampbell** [comment]
NB It sounds like you're missing the addition of the prophecy assertions to the assertion count.

**Comment by etienneq** [comment]
Do you mean this: https://github.com/phpspec/prophecy-phpunit ?
It states that as of PHPUnit 4.5 it should not be required anymore.

**Comment by sebastianbergmann** [comment]
No, that is not what @GrahamCampbell meant. Did you try with a supported version of PHPUnit? PHPUnit 4.7.7, which you wrote you are using, is no longer supported.

**Comment by sebastianbergmann** [comment]
Could you please provide a minimal, self-contained, reproducing test case? Thanks.

**Comment by etienneq** [comment]
I just tested with PHPUnit 4.8.23 to the same result.

Here comes an example:
```php
class ExampleTest extends PHPUnit_Framework_TestCase
{
    public function testExample() {
        $prophet = new \Prophecy\Prophet();
        $prophecy = $prophet->prophesize('DummyToMock');
        $prophecy->callMe()->shouldBeCalledTimes(1);

        $sut = new SUT();
        $sut->run($prophecy->reveal());

        $prophet->checkPredictions();
    }
}

class DummyToMock
{
    public function callMe() {
        echo "called";
    }
}

class SUT
{
    public function run($object) {
        $object->callMe();
    }
}
```

**Comment by sebastianbergmann** [comment]
Thank you, I can reproduce it now.

```
phpunit --report-useless-tests --verbose ExampleTest
PHPUnit 5.2.4 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.0.3 with Xdebug 2.4.0RC4

R                                                                   1 / 1 (100%)

Time: 31 ms, Memory: 4.00Mb

There was 1 risky test:

1) ExampleTest::testExample
This test did not perform any assertions

OK, but incomplete, skipped, or risky tests!
Tests: 1, Assertions: 0, Risky: 1.
```

@ciaranmcnulty @everzet Do you have an idea what I might be missing in PHPUnit? Thanks!

**Comment by stof** [comment]
@etienneq the issue is that you are using your own Prophet instead of using the builtin Prophecy integration. This means that your Prophet is not integrated into the count of assertions by PHPUnit.

This is how your test should look like:

```php
class ExampleTest extends PHPUnit_Framework_TestCase
{
    public function testExample() {
        $prophecy = $this->prophesize('DummyToMock');
        $prophecy->callMe()->shouldBeCalledTimes(1);

        $sut = new SUT();
        $sut->run($prophecy->reveal());
    }
}
```

If you handle the Prophet yourselves, you also have to handle reporting the number of assertions yourselves, which will make your test quite unreadable (which is precisely why there is a builtin integration to hide these details)

**Comment by sebastianbergmann** [comment]
@stof Thanks! Somehow I missed the obvious while analysing this.

**Comment by stof** [comment]
@sebastianbergmann note that I'm also one of the Prophecy maintainers. So you may also ping me when there is a Prophecy-related issue to look at. I found this issue only by chance (I opened the issue tracker to report my own ticket)

**Comment by sebastianbergmann** [comment]
@stof I pinged you on #2031 but got no response so far.

**Comment by stof** [comment]
yeah sorry, I missed it until today, and then it was already answered by another maintainer :smile:

**Comment by ciaranmcnulty** [comment]
As a point of order i've not considered myself a Prophecy maintainer but am happy to help out more in future if it helps

**Comment by etienneq** [comment]
Thanks everybody. I guess I should have read the PHPUnit manual more carefully. ;-)
