### ISSUE TITLE
Test suite naming conventions 

### ISSUE THREAD

**Issue by henrywright** [sebastianbergmann/phpunit#2075]
The manual highlights some conventions:

 - The tests for a class `MyClass` go into a class `MyClassTest`
 - The class `MyClassTest` live in file `MyClassTest.php`
 - `MyClassTest` inherits from `PHPUnit_Framework_TestCase`
 - Tests are public methods that are named `test*`

This will result in something like this folder structure:

```
├── src/
│   ├── classes/
│   │   ├── MyClass.php # Different
│   └── ...
├── tests/
│   ├── testcases/
│   │   ├── MyClassTest.php # Different
│   ├── bootstrap.php
│   └── ...
└── ...
```
... and this test case:
```
MyClassTest extends PHPUnit_Framework_TestCase {
    testMyMethod() {
        // Code here.
    }
}
```
**My question**
I'm wondering why the naming used inside the test suite can't mirror the project's source code? For example, file names can match:

```
├── src/
│   ├── classes/
│   │   ├── MyClass.php # Same
│   └── ...
├── tests/
│   ├── testcases/
│   │   ├── MyClass.php # Same
│   ├── bootstrap.php
│   └── ...
└── ...
```
And if using PHP > 5.3, namespaces can be used to allow class names to match:
```
namespace MyProject\MyTests;
MyClass extends PHPUnit_Framework_TestCase { # The class name MyClass matches the class name used in my project's source. 
    /**
     * @test
     */
    MyMethod() {  The method name MyMethod matches the method name used in my project's source. 
        // Code here.
    }
}
```
Note the `@tests` annotation is used so method names can match.

**Comment by sebastianbergmann** [comment]
This is not a discussion / support forum, sorry.

**Comment by henrywright** [comment]
:cry:
