### ISSUE TITLE
Better reporting for errors in setUpBeforeClass()

### ISSUE THREAD

**Issue by stof** [sebastianbergmann/phpunit#2080]
Currently, when an error occurs in `setUpBeforeClass`, the exception is registered in all of the tests of the class. This leads to displaying the exception with its stack trace many times (with exactly the same info as this is the same exception).
When there is lots of tests in the class (I have such a class with a data-provider returning 200 different cases), this makes the output totally unreadable (especially when you need to find a different error than this one coming from another test), and it can even reach the reporting limits of CI servers like Travis, preventing you from seeing the end of the report. It also makes it harder to identify the beginning and the end of a particular error display (seeing 4 linked exception, and then figuring out that the next block is the same list repeated).

As the error is the same for all tests, would it be possible to display the error with its stack trace only once, and then only display that it is the same error in other tests without repeating the stack trace ?

**Comment by sebastianbergmann** [comment]
Should be possible. Pull request, please :-)

**Comment by stof** [comment]
Should I mark following tests as skipped because of the failure (similar to what is done for ``@depends`` failure), or is there already a way to mark tests as errored without displaying a huge stack trace for them ?

**Comment by sebastianbergmann** [comment]
Skipping sounds like a reasonable thing to do.

**Comment by Jean85** [comment]
Making the test output a single error is not feasible?

**Comment by stof** [comment]
@sebastianbergmann in which branch should I do this change ? 5.2, 5.3 or master ?

**Comment by sebastianbergmann** [comment]
@stof `master`, please. Thanks!

**Comment by stratdes** [comment]
Is this request done already?

**Comment by stof** [comment]
@stratdes no. I haven't worked on it actually

**Comment by shivaacharjee** [comment]
working

On Tue, May 17, 2016 at 8:37 PM, Christophe Coevoet <
notifications@github.com> wrote:

> @stratdes <https://github.com/stratdes> no. I haven't worked on it
> actually
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/sebastianbergmann/phpunit/issues/2080#issuecomment-219747830>
>



-- 
Shiva Acharjee
Software Engineer @ NETechno (p) Ltd
http://shivaacharjee.com
Facebook: http://facebook.com/billshiva
Twitter: @shivaacharjee
https://about.me/shivaacharjee

Peace be on you!



***************************************************
This e-mail and any attachments may contain confidential and
privileged information. If you are not the intended recipient,
please notify the sender immediately by return e-mail, delete this
e-mail and destroy any copies. Any dissemination or use of this
information by a person other than the intended recipient is
unauthorized and may be illegal.
***************************************************

**Comment by sebastianbergmann** [comment]
@stof What is the status of this? Thanks!

**Comment by stof** [comment]
@sebastianbergmann I haven't worked on it

**Comment by MichelHartmann** [comment]
I did some research on this issue and got to the understanding that this need a little more thinking:

Marking the tests as skipped has two issues:
1. Skipped tests won't make the build fail
2. Skipped tests are only reported in verbose mode

My current idea would be to keep the tests as errors. In the report we could include the error message and stack trace only for the first test and have all others reference that test (e.g. "Calling setUpBeforeClass failed. See Foo\Bar\SomeTest::testSomething for details.")

What do you think about this approach?

**Comment by stof** [comment]
@MichelHartmann that would work for me too. But note that my suggestion was not to mark all tests of the class as skipped, but all except the first one (and keeping the first one as errored)
