### ISSUE TITLE
@small @medium @large tests does not work like the doc say it should

### ISSUE THREAD

**Issue by ztec** [sebastianbergmann/phpunit#2084]
The [documentation](https://phpunit.de/manual/current/en/appendixes.configuration.html) say: 

    timeoutForSmallTests
    If time limits based on test size are enforced then this attribute sets the timeout
    for all tests not marked as @medium or @large. 
    If a test does not complete within its configured timeout, it will fail.

The [change log of the phpUnit 4.7.0](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-4.7.md) say this : 

    Tests not annotated with @small, @medium, or @large are no longer treated as being annotated with @small

Tests I made myself say that the real behavior is the one introduced in 4.7.0 ! 

Please choose the right behavior 
 - The one that follow the documentation
 - The one introduced in 4.7  (And change the doc accordingly)

**Comment by sebastianbergmann** [comment]
The behavior of PHPUnit is correct:
```php
<?php
class Test extends PHPUnit_Framework_TestCase
{
    public function testOne()
    {
        sleep(2);
    }

    /**
     * @small
     */
    public function testTwo()
    {
        sleep(2);
    }
}
```

```
phpunit --enforce-time-limit Test
PHPUnit 5.2.9-1-g8a509b2 by Sebastian Bergmann and contributors.

.E                                                                  2 / 2 (100%)

Time: 3.02 seconds, Memory: 4.00Mb

There was 1 error:

1) Test::testTwo
PHP_Invoker_TimeoutException: Execution aborted after 1 second

FAILURES!
Tests: 2, Assertions: 0, Errors: 1.
```
This is a documentation bug that [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-documentation](https://github.com/sebastianbergmann/phpunit-documentation) project.

**Comment by afilina** [comment]
If anyone stumbles upon this issue because their annotation seems to have no effect, make sure that you run `phpunit` with `--enforce-time-limit`

**Comment by epdenouden** [comment]
@afilina there are also some (even) lesser known effects around sizes and dependency checking, plus fun like https://github.com/sebastianbergmann/phpunit/pull/3749
