### ISSUE TITLE
Documentation: Testing exceptions

### ISSUE THREAD

**Issue by henrywright** [sebastianbergmann/phpunit#2086]
On page 23 of the manual (pdf), the following line doesn't quite make sense:

> When testing that relies on php functions that trigger errors like fopen it can sometimes be useful to use error suppression while testing.

**Comment by sebastianbergmann** [comment]
This is a documentation bug that [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-documentation](https://github.com/sebastianbergmann/phpunit-documentation) project.

**Comment by henrywright** [comment]
Done :+1:
