### ISSUE TITLE
Remove filtering of stacktraces

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#2089]

**Comment by mindplay-dk** [comment]
What does this mean?

Removing the part of the stack trace that happens in php-unit itself? isn't that just noise? won't we get very long stack traces then? (and mostly noise?)

And will this fix the backwards stack trace issue?

**Comment by sebastianbergmann** [comment]
I think that I will still filter PHPUnit's own sourcecode files from the stack trace. Hopefully without doing it backwards.

**Comment by sebastianbergmann** [comment]
The problem here is really one of conflicting goals: by default, all sourcecode files of PHPUnit itself as well as its dependencies should not show up in a stacktrace. The only situation in which this is not the desired behavior is when you are testing either PHPUnit itself or one of its dependencies.
