### ISSUE TITLE
Implement assertPositive and assertNegative methods

### ISSUE THREAD

**Issue by danieliancu** [sebastianbergmann/phpunit#2090]
```php
$this->assertPositive($result); // is_int($result) && $result > 0
$this->assertNegative($result); // is_int($result) && $result < 0
```

Wanted to know your opinions before PR.

**Comment by henriquemoody** [comment]
I never thought that necessary, for that case I use `assertGreaterThan(0)` and `assertLessThan(0)`. But, if you think that's necessary perhaps you should consider that not only integers can be positive or negative, but rather any numeric value.

**Comment by danieliancu** [comment]
@henriquemoody thanks for the feedback.
Well I find them useful when you want to check the result is integer and positive/negative in one line.

**Comment by danieliancu** [comment]
@henriquemoody but I find your opinion right and it should be made to check numeric values are positive/negative.

**Comment by danieliancu** [comment]
@henriquemoody although in that case it is the same behavior as `assertGreaterThan` and `assertLessThan`, I find them more readable. Maybe we can make them as wrappers for those two functions.

**Comment by danieliancu** [comment]
@henriquemoody but I agree, in that case they're not very useful really.
