### ISSUE TITLE
Something is wrong

### ISSUE THREAD

**Issue by flik** [sebastianbergmann/phpunit#2095]
I cloned this https://github.com/sebastianbergmann/phpunit.git
but there was no file src/autoload.php 
and then I followed the page https://phpunit.de/getting-started.html

Generated files in 
phpunit/src/Money.php
phpunit/tests/MoneyTest.php

and then I run the command 
phpunit --bootstrap src/autoload.php tests/MoneyTest

There was no result. Why ???

**Comment by alexislefebvre** [comment]
Please update the title of your issue, *Something is wrong* is not an accurate title.

>  but there was no file src/autoload.php 

This file does not exist in this repository: https://github.com/sebastianbergmann/phpunit/tree/master/src

Maybe it's created by Composer?

**Comment by sebastianbergmann** [comment]
This issue tracker is for tracking issues in PHPUnit itself. It is not a discussion or support forum, sorry.

**Comment by flik** [comment]
I have installed phpunit.phar already. I was writing basic test case according to the https://phpunit.de/getting-started.html But they have issue in their article and documentation. In other words It is misguide. It could be the name of issue.
