### ISSUE TITLE
injection of environment variables for single testsuites

### ISSUE THREAD

**Issue by shinobu** [sebastianbergmann/phpunit#2097]
Heyho, I'm trying to run tests for a program that runs on different DB's and an environment variable defines which DB is used. A simplified phpunit.xml example would look like this:

```
    <testsuites>
        <testsuite name="1">
            <directory suffix="1Test.php">test/</directory>
            <php>
                <env name="test_env1" value="a"/>
            </php>
        </testsuite>
        <testsuite name="2">
            <directory suffix="2Test.php">test/</directory>
            <php>
                <env name="test_env1" value="b"/>
            </php>
        </testsuite>
    </testsuites>
```

is there a way to do this without calling all testsuites alone with
        `test_env1="x" phpunit --testsuite "y"`
or using multiple phpunit.xml files?

**Comment by sebastianbergmann** [comment]
No, this is not possible. And I do not think it should be.
