### ISSUE TITLE
Not Constraint implementation class can corrupt failure descriptions

### ISSUE THREAD

**Issue by halfer** [sebastianbergmann/phpunit#2098]
I am testing a console command with PHPUnit. At some point in development, I chose to force a failure, and was surprised to get a corrupted failure message (the failure itself is correct but the message is wrong). Here is (a simplified version of) my code:

```
public function testConsoleOutput()
{
    $text = "This is a console program to trigger processes manually.

(--find <string> is available to search sources/processes/pools)

No sources/processes/pools found";
    $this->assertNotContains("No sources/processes/pools found", $text);
}
```

Here is the message I was expecting:

> Failed asserting that 'This is a console program to trigger processes manually.
> 
>  (--find <string> is available to search sources/processes/pools)
> 
> No sources/processes/pools found' does not contain "No sources/processes/pools found"

What I actually received was:

> Failed asserting that 'This not is not a console program to trigger processes manually.
> 
>  (--find <string> is not available to search sources/processes/pools)
> 
> No sources/processes/pools found' does not contain "No sources/processes/pools found".

As you can see two lines of console text (which in practice are correctly captured from the console using the output buffering system) are corrupted:
- "This is" is changed to "This not is not"
- "&lt;string&gt; is available" is changed to "&lt;string&gt; is not available"

I traced the definition of `assertNotContains()` and it has this:

```
       $constraint = new PHPUnit_Framework_Constraint_Not(
            new PHPUnit_Framework_Constraint_StringContains(
                $needle,
                $ignoreCase
            )
        );
```

This leads me to find the problem lies in `PHPUnit_Framework_Constraint_Not`: `failureDescription()` calls `self::negate()`, which does a search and replace on the whole of the output text, rather than just the PHPUnit messages.

As far as I can tell this is just a bug in the failure reporting, so is not corrupting test results. I'm on PHPUnit 4.3.x with PHP 5.5.9.

I realised this is a rather old version of PHPUnit, so I have upgraded PHPUnit in my Composer deps to 4.8.23, and the problem persists. I was unable to easily try PHPUnit 5 or later, as this requires PHP 5.6.

**Comment by sebastianbergmann** [comment]
This is a know issue (but there does not seem to be an open ticket for it except for this one). Nevertheless it needs to be fixed so thank you for bringing this to my attention.

**Comment by giorgiosironi** [comment]
A possible solution would be to modify the failure description to avoid the smart behavior of negate() and stick to the more general composition already performed by logical operators:
```
    Failed asserting that not('This is a console program to trigger processes manually.

    (--find is available to search sources/processes/pools)

    No sources/processes/pools found' contains "No sources/processes/pools found")
```

because once a `string` is returned by the inner constraints parts of it are indistinguishable by the outer `Not`.

**Comment by halfer** [comment]
Thanks both.

@giorgiosironi - if I wanted a more reliable failure message I guess I could just have used `assertFalse()` on my own comparison expression. However, since my test actually succeeds now, the failure message doesn't currently pop up. `:-)`

I imagine `negate()` should be run only on the PHPUnit strings, perhaps before the test-specific material is injected in?

**Comment by giorgiosironi** [comment]
What happens is that negate() runs on the string produced by the inner constraints, replacing a list of hardcoded words such as "contains". The contract of the Constraints is to return an already built string, not a data structure that can be modified.

**Comment by pengi** [comment]
I'm affected by this bug too. But since it's cosmetic, it's not a blocker for me either.

I just found another little issue with the negate() method too. The `'is '` => `'is not '` replacement also triggers on `'this '`

`$this->assertNotContains("error", "this is a string with an error");`
Gives:
`this not is not a string with an error`

**Comment by fetmo** [comment]
I think this was fixed with #2688 

@sebastianbergmann 
Can you approve?

**Comment by fetmo** [comment]
#2688

**Comment by fetmo** [comment]
#2688
