### ISSUE TITLE
Option to allow empty test case?

### ISSUE THREAD

**Issue by allansun** [sebastianbergmann/phpunit#2100]
In my project we have code generator to automatically create a lot of codes by reading database scheme.

Some TableGateway classes (refer to Zend Framework 2) only need very simple CRUD operations which are provided by AbstractTableGateway (which is already throughly tested) hence no test is needed. However we still create a skeleton test case so developers can easily add new tests in it.

The problem comes if the test case doesn't have any actual tests at all a warning is thrown. Is there anyway we can disable the 'No tests found in class %s' Warning by configuration?

By now my only solution is to create a dummy test function with nothing in it. This is okay-ish but this make the test count unnecessarily incorrect.

**Comment by sebastianbergmann** [comment]
I do not think that such an option would be useful.
