### ISSUE TITLE
Output Buffer Level consumption prevents custom output buffers from working

### ISSUE THREAD

**Issue by jotiheranbnach** [sebastianbergmann/phpunit#2101]
Hi,

I noticed a weird behaviour as I wanted to wrap the output of a test run in an output buffer. It seems like the phpunit code closes all existing output buffers in the process. Even those opened by me.

Here is my test code:

```php
ob_start();
include('/home/johann/development/toolbox/lib/vendor/phpunit/phpunit.phar');
ob_end_clean();

$_SERVER['argv'] = [
    '/home/johann/development/toolbox/lib/vendor/phpunit/phpunit.phar',
    '--configuration',
    '/home/johann/development/toolbox/lib/toolbox/services/cli/unix/test/config/phpUnit.xml',
];

ob_start();
PHPUnit_TextUI_Command::main(false);
$content = ob_get_contents();
ob_end_clean();
```
The last `ob_end_clean()` call fails because all output buffers were already closed by phpunit.

The code responsible for closing ALL open output buffers is in the `phpunit.phar/phpunit/Framework/TestCase.php` file and in the `startOutputBuffering` method:

```php
private function startOutputBuffering()
{
    while (!defined('PHPUNIT_TESTSUITE') && ob_get_level() > 0) {
        ob_end_clean();
    }

    ob_start();

    $this->outputBufferingActive = true;
    $this->outputBufferingLevel  = ob_get_level();
}
```

So what it does is close output buffers till the level reaches 0. That's bad if you want use your own output buffer outside. Maybe the current level should be taken into consideration.

I found similar issues here (all closed for some reason):
#1398
#1545
#1553

**Comment by jotiheranbnach** [comment]
I found out that if I define the constant `PHPUNIT_TESTSUITE` before I launch the test, the output buffer consuming while loop breaks atomatically. While this is fine for my implementation and fixes my problems, I do not know what exactly happens if I do it like that. What does the constant mean?

```php
define('PHPUNIT_TESTSUITE', 1);
```

**Comment by TomSta** [comment]
Thank you Jo, your suggestion helped me as well... had same problem when wanting to run tests from Symfony services/controllers.

 here's code in case anyone would be having same issue.

`
        define('PHPUNIT_TESTSUITE', 1); //this line helped me with hiding output using obj_start etc.
        $_SERVER['KERNEL_DIR'] =  dirname(getcwd()) . '/app/'; //this line helped me with  ' You must override the KernelTestCase::createKernel() method.'
        $testsPath = dirname(getcwd()).'/tests/Integration/';

        ob_start();
        $phpunit = new \PHPUnit_TextUI_TestRunner;
         $suite = $phpunit->getTest($testsPath, '', 'Test.php');
        $test_results = $phpunit->doRun($suite, ['--debug' ], false);
        $output = ob_get_clean();
`

**Comment by sebastianbergmann** [comment]
`PHPUNIT_TESTSUITE` is used by PHPUnit's own test suite to tell PHPUnit not to filters its sourcecode files from stacktraces.

**Comment by jotiheranbnach** [comment]
So we can utilize this constant for our own needs as mentioned above without breaking the "rules"?

**Comment by sebastianbergmann** [comment]
No, that constant is for PHPUnit's own test suite only.

**Comment by jotiheranbnach** [comment]
Ok, got it. Then we will need another constant to hook in and disable the default output buffer consumption or another approach it seems.

**Comment by sebastianbergmann** [comment]
Does this patch solve your problem?

```
diff --git a/src/Framework/TestCase.php b/src/Framework/TestCase.php
index af0d1c5..08834ad 100644
--- a/src/Framework/TestCase.php
+++ b/src/Framework/TestCase.php
@@ -2346,10 +2346,6 @@ protected function getMockObjectGenerator()
      */
     private function startOutputBuffering()
     {
-        while (!defined('PHPUNIT_TESTSUITE') && ob_get_level() > 0) {
-            ob_end_clean();
-        }
-
         ob_start();
 
         $this->outputBufferingActive = true;
@@ -2362,7 +2358,7 @@ private function startOutputBuffering()
     private function stopOutputBuffering()
     {
         if (ob_get_level() != $this->outputBufferingLevel) {
-            while (ob_get_level() > 0) {
+            while (ob_get_level() >= $this->outputBufferingLevel) {
                 ob_end_clean();
             }
```

**Comment by jotiheranbnach** [comment]
Yes it does, well done!  :)
