### ISSUE TITLE
Question: static assertions

### ISSUE THREAD

**Issue by keradus** [sebastianbergmann/phpunit#2104]
Hi.
All assertions provided by [PHPUnit_Framework_Assert](https://github.com/sebastianbergmann/phpunit/blob/master/src/Framework/Assert.php) are defined as static methods.
On the other hand, all examples on https://phpunit.de/ says to call them with instance context .

@sebastianbergmann it would be great if you could provide some reasoning for this inconsistency.

**Comment by sebastianbergmann** [comment]
The methods of `PHPUnit_Framework_Assert` are declared static because the methods of JUnit 3.8's `Assert` class were declared static. And while I never used them statically I have seen them used statically "in the wild", even in production code.

**Comment by keradus** [comment]
> And while I never used them statically I have seen them used statically "in the wild", even in production code.

That was why I ask the question - I found a bunch of private repos that use them statically.
Thank you for reasoning. Are there any chances to make them non-static in future version of PHPUnit to keep it clean and remove that ambiguity? So declarations will actually follow recommended usages.
