### ISSUE TITLE
Feedback from taking tests using PHPUnit

### ISSUE THREAD

**Issue by markem** [sebastianbergmann/phpunit#2105]
I thought I'd leave some feedback on having just taken a test with PHPUnit.  I did do the review but wanted to recap as well as input some new problems I thought I should bring up.

1. Contrast.  Anyone setting up PHPUnit should remember contrast. In web design classes I have had this was the number one problem with most sites. Light colored text on light background is a terrible thing to do.  It makes the letters fade into the background.  Similarly, dark backgrounds with dark text can have the same effect. If you are trying to not hire someone or you are just trying to make someone fail a test - this can do it.  In PHPUnit, both tests I took had light grey backgrounds with only a slightly darker grey text.  The hidden problem here is functionality versus personal likes and dislikes.  Many times people go "I can read it so everyone can read it".  This isn't so but it is why some people do well on a test and others (myself included) do not.

2. "Everything has to have a white background". This is the Apple Computer outlook.  It is why Macintoshes all have white backgrounds.  Apple - like a lot of companies and people - are wrong. Not everyone likes having white backgrounds.  I don't. Almost all of my setups have a black background with light grey letters. When I owned a Macintosh I set it to have a black background too.  For me, trying to see light yellow on a white background is like trying to look at a light and see what is written on the light bulb.  A black background allows me to use a large range of colors for my text. That is why I use black backgrounds. PHPUnit presently does not offer this as an option.

3. "Everyone uses a mouse to edit".  Again, this is a "I do this so everyone does this" outlook.  I use VIM almost exclusively to do everything unless I am forced to use the keyboard+mouse methodology. People who do use the keyboard+mouse method constantly find themselves moving their hand from the keyboard to the mouse.  The reason I use VIM is because I can do everything in VIM without ever taking my hands from the keyboard. It would be nice if someone would come out with a plug-in editor that did VIM or at least the VIM parts to do editing. This was one of the things I struggled with during the tests.  I kept typing in things like "gg" to go to the top, then I would have to delete that and use the mouse to go back to the top.  A much more cumbersome way to get there.

4. Color. (And just when you thought I was through talking about this. :-) ) Do you think about stoplights? Those things we pass every day while driving to work? Probably not. You probably think those lights are Red, Yellow, and Green too - but they are not.  The US Government did a multi-year study on what the best colors were to use.  Each of those lights are actually two colors. The red is both red and yellow, the yellow light is really yellow and red, and the green light is actually green and blue. (I am listing the majority color first.) Why do this? Because if you are color blind and can not see red - you usually can still see yellow and if you can't see green you probably still can see blue.  The same for yellow.  When I took my tests, one of the other really hard to see things were the test results.  Not only were they in the same thin font as what I am typing in now, but they were light green on a white background and light red on a light background.  If I were color blind in - say - red - I might not have even seen that because it was pure red.  Or if I was color blind in green I might never know I had gotten something right.  Like the traffic lights, these colors should be blue-green and orange (a mixture of red and yellow) but with a predominate amount of red in it.  This would ensure that everyone could read whether or not they were getting things right or wrong.

5. Font. Although it is nice to use a very compact font - the idea is to give someone a test - not to try to make it hard or impossible to read the test. This is why teachers usually use Times Roman and not Arial or Helvetica.  Arial and Helvetica can (and do) make I's look like 1's and O's look like 0's.  Not to mention if someone (like myself) wears glasses, it can make it a lot harder to distinguish between one letter and the next. Even a good computer code font like Lucida Console is better than Arial or Helvetica because it is made to be read.  Or a better way to think about it is - we are not trying to sell someone an insurance policy and we don't need fine print.  We need print that people can see and distinguish each letter without eye strain.

6. Size.  "Size matters," as the saying goes and it does so especially on tests.  My wife is a teacher so we go out with other teachers and you get an ear full of what is good and what is not about certain techniques and methodologies.  But there is one thing all teachers say is very important. And that is to give the person taking the test a decent chance of finishing the test. One of those ways to do this is to ensure you are not using microscopic font sizes.  Staring in 1st grade, we use 60pt or 72pt fonts.  As people get older this font size is reduced down to around 10pt or 12pt in college. The question is though - your screen has an unlimited size to it.  So why are you being so cheap when it comes to the size of the font used to take tests?  On a computer screen, especially since we now are using 21" to 60" screens, a bigger font helps out a lot.  Use 14pt or 16pt so when someone looks at the computer's screen the text isn't lost in all of that white background.  Right now, on my computer screen I have six inches on either side of this text.  That is a lot of white and your eyes see all of it. When all we had were five inch or ten inch screens we really did need to conserve space by using a smaller font but in today's world - we need larger fonts on our tests.

7. Bold. When I took my tests, all of the results were in the same font as what I am typing in. So were the results of the tests. If you got something right it was displayed in a light green color and if you got something wrong it was displayed in a light red color.  Both of which faded into the background. Since PHPUnit is trying to help the person by telling them they got something right or wrong - why not use **bold face** so they actually can see the results?  Again, this is not helping the person taking the test to not be able to tell if they got the answers right or wrong.  Someone probably said "We don't want to scream it at them - so don't use bold face".  That is all nice and fine but when you are working on the test it really is a good idea to actually let the person know they did not do it right and if both the good and bad messages are in bold face - it evens out the usage of bold facing.  So it is ok to have the "Correct" and "Wrong" messages show up in bold face.

8. Obscurity. I do not know how much control PHPUnit has over its error messages but what I can tell you is - some of the error messages I got were pretty obscure.  PHPUnit most probably uses the try-catch mechanism to try out code and to catch any errors it may receive. This is both good and bad.  The error messages generated by the PHP interpreter are what most programmers use to decide what needs to be fixed. The problem with PHPUnit is - those error messages are being suppressed.  Instead, you get OTHER error messages like "In test #XYZ: Wrong percussion instrument used". So you go "Say what?" and you have to figure out what it really means.  It would be just as easy to redirect the output to a file, grab the output from that file, and display the standard PHP error messages.  (The same for any other computer language.) So one of the problems I encountered was that no standard PHP error messages were being generated which meant lost time trying to figure out what PHPUnit was trying to tell me.

9. Readability of the questions, Most people think saying something like "Make a table for customers which will have X,Y,Z." is a good thing when what they really meant was "We want you to make a table called 'Customers' and to create the following fields: X, Y, Z." This is not so much a PHPUnit problem as it is a tester problem.  Things tend to blend in when you are taking a test. This is why it is so important to state what is wanted clearly.  Again, the question is - are you helping or hurting the person taking the test? If you run everything into one sentence - then it is most probably that you are hurting.  State questions clearly and simply.  Do not put more than one request per sentence.  Break down each question into its component parts and state each part.  I can not emphasize this enough.

10. And last - this. PHPUnit is only as good as the person giving the test. It is not a person. It can not think for itself. This is why PHPUnit is not good at subjective tests.  Multiple choice - yes. Math questions - yes. But for something subjective like writing a program? - No.  I ran into this in both cases where I was tested using PHPUnit.  Because people write code just like they would write books - it means that there are a billion-billion ways to write the code.  Just like lots of other automated testing suites (and there are a few out there) - if you don't conform to how the person set it up - you are WRONG.  This can be as simple as you saying "Customer" instead of "Customers" or just "Table1" instead of "Customers". The program might do exactly what is wanted - but because it doesn't conform to what the tester wanted - it is wrong. Computers have come a long way - but they are not humans.  I failed both of the tests I took using PHPUnit.  One of the recruiters who had sent me to one of the tests e-mailed me and asked why I did not pass the test. He also informed me that every single person he had sent (and he had sent six people including me) to take the test had failed.  And this is why.  Man is not subserviant to the machine and that is exactly what is going on here. If you can't be perfect - you are going to fail.

11. Ok - I lied.  This is the last thing.  It is TIME. On the first PHPUnit test I took I was given only 40 minutes to complete the tests. There were four questions.  I was given five minutes for the first question, fifteen minutes for the second one, fifteen minutes for the third one, and five minutes for the last one.  Not enough time.  I was trying to not only take a test but learn the PHPUnit interface. It seems easy enough - until you try it under the pressure of trying to complete a question in five minutes.  From there it went downhill.  My second test though - I enjoyed a lot even though I failed it too.  I had four hours to complete five questions.  I only got to number four. Each question has something like five sub-questions.  Again, a lot of time was spent fighting with the interface as well as my having to take the test on a Macintosh (I use PCs).  So a lot of the Macintosh doing things I was not used to, the keyboard being totally different from the type of keyboard I like to use, and the set up for PHPUnit at the second test was different from the way it was set up on the first test. All of that aside - the biggest factor here was 40 minutes versus 4 hours.  I was a lot more relaxed at the 4 hour test and completed more of the test than I did with only 40 minutes.  So keep that in mind when making tests.  If what you really are trying to do is to find out if someone knows something or not - give them lots of time.  This isn't a race.  We aren't playing Jeopardy and racing against the clock to be able to answer the questions.  At least, I don't want to work some place where everyone is uptight and being rushed to do everything as quickly as possible.  That is a great way to burn out your people but it is a terrible way to get results.  Think about it.  This is just a reflection of how YOU are. By doing this you are telling everyone "I you can't do it in five seconds or less - you are fired!".  Well, I'd rather not work for you in the first place if that is how you are going to be.  Give me the four hour exam person.  They are laid back enough to let me work and work well.

**Comment by rocketpastsix** [comment]
I truly think you have got phpunit mixed up with something else.

**Comment by markem** [comment]
This is what they brought up to do the testing with.  I thought PHPUnit was a unit testing software.  What can I say?

**Comment by tvlooy** [comment]
https://en.m.wikipedia.org/wiki/Mark_V._Shaney

**Comment by markem** [comment]
Ok, on the chance that I am completely wrong about this - can we delete this then?
