### ISSUE TITLE
Prophecy prophezise assertion always true even when it should false

### ISSUE THREAD

**Issue by mpmaghribi** [sebastianbergmann/phpunit#2106]
I am testing a class with few interfaces as contructor arguments. I use prophezise to mock the interfaces and i haven't do anything to satisfy the mock object prediction, but the test runs with success foll all mock object i made when it should fail on one of few mock objects that i have on the test. Here are code example:
`       

        $firstInterface = $this->prophesize(TheInterface::class);
        $fistInterface->doSomethingOnInterface($firstValue)->shouldBeCalled();
        
        $secondInterface = $this->prophesize(TheInterface::class);
        $secondInterface->doSomethingOnInterface($secondValue)->shouldBeCalled();
        
        $theClass = new ClassToBeTested();
        $theClass->doSomething([], $firstInterface->reveal(), $secondInterface->reveal(), []);
`

The test result are success with 2 assertion when it should be 1 failure.

I ended up instantiate my own prophecy object and the result just as i expected.

**Comment by sebastianbergmann** [comment]
Please provide a complete, minimal, self-contained, reproducing test case.

**Comment by mpmaghribi** [comment]
[ProphetizeTest.php.zip](https://github.com/sebastianbergmann/phpunit/files/160366/ProphetizeTest.php.zip)

![screenshot from 2016-03-06 21 42 03](https://cloud.githubusercontent.com/assets/3497953/13554823/6e0bb8f0-e3e4-11e5-999e-48ce3009e3f7.png)

![screenshot from 2016-03-06 21 42 50](https://cloud.githubusercontent.com/assets/3497953/13554826/784fdfe4-e3e4-11e5-8456-0151326e8b6c.png)

**Comment by mpmaghribi** [comment]
Hi, i've posted code to reproduce my issue, along with phpunit result and php version i used.

The test should failed because i didn't call any mocked interface.

**Comment by sebastianbergmann** [comment]
Thank you for the minimal, self-contained, reproducing test case, @mpmaghribi.

I get the following with PHPUnit 5.2:
```
PHPUnit 5.2.10 by Sebastian Bergmann and contributors.

FF                                                                  2 / 2 (100%)

Time: 23 ms, Memory: 4.00Mb

There were 2 failures:

1) ProphetizeTest::doSomethingWithProphetize
Some predictions failed:
  Double\TheInterface\P1:
    No calls have been made that match:
      Double\TheInterface\P1->doSomethingOnInterface(exact([]))
    but expected at least one.  Double\TheInterface\P2:
    No calls have been made that match:
      Double\TheInterface\P2->doSomethingOnInterface(exact([]))
    but expected at least one.

2) ProphetizeTest::doSomethingWithNative
Expectation failed for method name is equal to <string:doSomethingOnInterface> when invoked 1 time(s).
Method was expected to be called 1 times, actually called 0 times.

FAILURES!
Tests: 2, Assertions: 3, Failures: 2.
```
And the following with PHPUnit 4.8:
```
PHPUnit 4.8.23-2-g264188d by Sebastian Bergmann and contributors.

.F

Time: 35 ms, Memory: 6.00Mb

There was 1 failure:

1) ProphetizeTest::doSomethingWithNative
Expectation failed for method name is equal to <string:doSomethingOnInterface> when invoked 1 time(s).
Method was expected to be called 1 times, actually called 0 times.

FAILURES!
Tests: 2, Assertions: 3, Failures: 1.
```
Looks like this issue only exists in PHPUnit's current "old but stable" release. Will need to investigate.

**Comment by sebastianbergmann** [comment]
I did some debugging and found out that the problem only occurs when PHPUnit 4.8 is used with PHP 7. When using PHPUnit 4.8 with PHP 5.6 I get the following:
```
PHPUnit 4.8.23-2-g264188d by Sebastian Bergmann and contributors.

FF

Time: 82 ms, Memory: 7.00Mb

There were 2 failures:

1) ProphetizeTest::doSomethingWithProphetize
Some predictions failed:
  Double\TheInterface\P1:
    No calls have been made that match:
      Double\TheInterface\P1->doSomethingOnInterface(exact([]))
    but expected at least one.  Double\TheInterface\P2:
    No calls have been made that match:
      Double\TheInterface\P2->doSomethingOnInterface(exact([]))
    but expected at least one.

2) ProphetizeTest::doSomethingWithNative
Expectation failed for method name is equal to <string:doSomethingOnInterface> when invoked 1 time(s).
Method was expected to be called 1 times, actually called 0 times.

FAILURES!
Tests: 2, Assertions: 3, Failures: 2.
```
Please understand that I won't investigate this issue further as PHPUnit 4.8 is only supported on PHP 5.3, PHP 5.4, PHP 5.5, and PHP 5.6 but not on PHP 7. If you are using PHP 7 then please use PHPUnit 5.

**Comment by mpmaghribi** [comment]
Thank you @sebastianbergmann
