### ISSUE TITLE
wrong filtering in assertArraySubset method of PHPUnit_Framework_Assert class

### ISSUE THREAD

**Issue by xilnick** [sebastianbergmann/phpunit#2108]
PHPUnit_Framework_Assert::assertArraySubset documented to accept array and subset arguments as array or ArrayAcces, but actually it only cheks array and subset arguments to be an array and don't do this for ArrayAccess.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by Johannestegner** [comment]
Adding a "minimal, self-contained, reproducing test case that shows the problem".


```php
<?php

class ExampleArrayAccessTest extends PHPUnit_Framework_TestCase {

    public function testArrayAccessStuff() {

        $arr = new ExampleArrayAccess();
        $arr[0] = 1;
        $arr[1] = 10;

        $this->assertArraySubset([1, 10], $arr);
    }
}

class ExampleArrayAccess implements ArrayAccess {

    private $array = array();

    public function offsetExists($offset) {
        return isset($offset, $this->array);
    }

    public function offsetGet($offset) {
        return $this->array[$offset];
    }

    public function offsetSet($offset, $value) {
        $this->array[$offset] = $value;
    }

    public function offsetUnset($offset) {
        unset($this->array[$offset]);
    }
}
```

First error that one will hit is:

> Argument 2 (No Value) of PHPUnit_Framework_Assert::assertArraySubset() must be a array or ArrayAccess

Which means that `is_array($arr);` returns false if its not actually a native array.  
So I tried a naïve quick fix in the Assert.php file:

```
// line ~72
if (!is_array($array) && !($array instanceof ArrayAccess)) {
    throw PHPUnit_Util_InvalidArgumentHelper::factory(
        2,
        'array or ArrayAccess'
    );
}
```
Which then produces the following error:

> array_replace_recursive(): Argument 1 is not an array

So the issue is that `array_replace_recursive()` does not work with `ArrayAccess` implementations, only with the native `array`.
