### ISSUE TITLE
Error on HHVM due "configuration" global variable

### ISSUE THREAD

**Issue by aik099** [sebastianbergmann/phpunit#2109]
PHPUnit creates `configuration` global variable, which is object of `DOMDocument` class. When running tests on HHVM and globals are backed up in the process this ends up in following error:

```
Attempted to serialize unserializable builtin class DOMDocument
```

See https://travis-ci.org/minkphp/phpunit-mink/jobs/114842726

Proposing to exclude global variable `configuration`, that PHPUnit creates for internal needs from serialization done in `Snapshot` class.

Not sure if it matters, but tests, that trigger such behavior are also marked with `@runInSeparateProcess` annotation.

**Comment by sebastianbergmann** [comment]
The only place I can find where PHPUnit creates a global variable named `$configuration` is in the template that is used for executing a test in a separate process. That variable is now unset after it has been used, see https://github.com/sebastianbergmann/phpunit/commit/a093bd87ab00a8c107db315c03df1ff614ffbbbc.

Are the tests you mention executed in process isolation? If so, does https://github.com/sebastianbergmann/phpunit/commit/a093bd87ab00a8c107db315c03df1ff614ffbbbc solve the issue for you?

**Comment by aik099** [comment]
> Are the tests you mention executed in process isolation?

Exactly. I'm using `@runInSeparateProcess` annotation.

> If so, does a093bd8 solve the issue for you?

Yes, it does. Thank you. Can you please backport this to PHPUnit 4.x release as well, because on Travis CI for HHVM the PHPUnit 4.x version only is installed.

**Comment by sebastianbergmann** [comment]
This will be in the next PHPUnit 4.8 release, yes.

**Comment by sebastianbergmann** [comment]
https://github.com/sebastianbergmann/phpunit/commit/a093bd87ab00a8c107db315c03df1ff614ffbbbc is in PHPUnit 4.8.24, closing.
