### ISSUE TITLE
Error written to stdout instead of stderr

### ISSUE THREAD

**Issue by joshuaspence** [sebastianbergmann/phpunit#2110]
In PHPUnit 4.8.23, if you attempt to `@cover` a non existing method then the error message is written to stdout rather than stderr.

```
PHPUnit 4.8.23 by Sebastian Bergmann and contributors.

Trying to @cover or @use not existing method "SomeClass;::someMethod".
```

(The real issue here was that we had specified `@coversDefaultClass SomeClass;` rather than `@coversDefaultClass SomeClass`)

**Comment by qbitza** [comment]
I had a quick look, but can't seem to reproduce this. When passing the --stderr command line option, output is passed correctly to stderr, or is the intention that errors/warnings are always sent to stderr?

**Comment by joshuaspence** [comment]
Yes, it was my expectation that error messages would always be written to stderr.

**Comment by JWZH** [comment]
It seems this has been fixed ? 

```

There was 1 warning:

1) SomeClass::someMethod
Trying to @cover or @use not existing method "SomeClass::someMethod".

WARNINGS!
Tests: 1, Assertions: 1, Warnings: 1.

Generating code coverage report in Clover XML format ... done
```

**Comment by sebastianbergmann** [comment]
All output goes to STDOUT by default. When you use `--stderr` then all output should go to STDERR.
