### ISSUE TITLE
PHP7: Coverage testing a class with a generator fails with fatal error

### ISSUE THREAD

**Issue by seva** [sebastianbergmann/phpunit#2113]
If one of the methods is a generator (contains "yield"), coverage fails with:

Class 'PHP_Token_YIELD' not found

(dev-master 5.4.x)

**Comment by sebastianbergmann** [comment]
I do not understand this report, sorry.

**Comment by sebastianbergmann** [comment]
No feedback, closing.

**Comment by seva** [comment]
Pity.
