### ISSUE TITLE
Using @codeCoverageIgnore annotations within the *Test class

### ISSUE THREAD

**Issue by twifty** [sebastianbergmann/phpunit#2117]
This is a feature request, and although it is for the code coverage component I feel it better placed here since this is where the test classes are parsed.

The `@codeCoverageIgnore` annotations are useful for excluding those lines which would otherwise hinder a 100% goal, for a single test. The biggest problem is that they litter the code being tested. In the real world, just because it may be impossible for one test to hit a line of code, it doesn't mean another test (which internally calls into the same code) also has that restriction.

Let me better explain with an example:
````php
class BeingTested {
    function __construct(CacheManagerInterface $cache = null)
    {
        $this->cache = $cache ?: new CacheManager();
    }

    private function someMethod()
    {
        if (!$this->cache->load($file)) {
            throw new \Exception(); // @codeCoverageIgnore
        }
    }
}
````
The `BeingTested` class has the option of being constructed with a custom `CacheManager`. But loading from the cache is just one line code. The tests being run will use an instance with a default `CacheManager` (which has also been tested) implying that the exception will never and can never be thrown within the context of this one test.

However, another class being tested may create an instance of `BeingTested` with a non default cache. Now, that exception may be thrown. So the line becomes eligible for coverage.

Having the annotations embedded in the source being tested, messes up the coverage reports for different tests/groups/suites.

A better method would be to define within the test class, what needs to be ignored. Very similar to the existing `@covers` annotation. How about something like:
````php
/**
* @codeCoverageIgnore namespace\BeingTested 23-28
*/
class ExampleTest extends \PHPUnit_Framework_TestCase
{
}
````
Where `23-28` would be the line number(s) to ignore?

**Comment by sebastianbergmann** [comment]
I do not think this to be useful, sorry.
