### ISSUE TITLE
test double using prophesize test result invalid

### ISSUE THREAD

**Issue by mpmaghribi** [sebastianbergmann/phpunit#2118]
Hi, I write some test using prophesize and I found that it not work as expected. The test should fail but it succeed. Here are code sample and environment I use:

[code](https://github.com/sebastianbergmann/phpunit/files/173303/ProphetizeTest.php.zip)

![environment](https://cloud.githubusercontent.com/assets/3497953/13768443/bb099530-eaa8-11e5-954f-1c976ba85eea.png)

"doSomethingWithProphetize", which using prophesize, test result is invalid
"doSomethingWithNative", which using getMockForAbstractClass test result is valid

both test should fail

**Comment by mpmaghribi** [comment]
Hi, I re run above test using php5.6, and turns out that all test result fail as expected.

![screenshot from 2016-03-15 12 57 20](https://cloud.githubusercontent.com/assets/3497953/13768898/8e34df2e-eaad-11e5-82d0-38ded7a663f7.png)

**Comment by sebastianbergmann** [comment]
Fixed in PHPUnit 5.2.12.
