### ISSUE TITLE
Data Providers used from different instantiation than test case that is executed

### ISSUE THREAD

**Issue by dstockto** [sebastianbergmann/phpunit#2120]
It appears that data providers are retrieved from a different instantiation of the test class than the one they actually run against. Test cases appear to be created once to determine how many tests there will be and from that run, the data providers are retrieved and held for the actual run.

This means the class and test that are actually executed are not the same which leads to what seems to be some pretty confusing behavior if the data provider has randomly generated values that are captured in the provided data. An example of what I mean is below:

```
<?php
class Test extends PHPUnit_Framework_TestCase
{
    private $value;

    public function setUp()
    {
        $this->value    = uniqid();
        $this->comparer = new Comparer($this->value);
    }

    /**
     * @dataProvider sameProvider
     */
    public function testIsSame($value)
    {
        $this->assertTrue($this->comparer->__invoke($value));
    }

    public function sameProvider()
    {
        return [
            [ $this->value ]
        ];
    }
}


class Comparer
{
    public function __construct($value)
    {
        $this->value = $value;
    }

    public function __invoke($value)
    {
        return $value == $this->value;
    }
}
```

I tried a few different other ways to make this work including setting the value in setupBeforeClass and in the constructor, but since the data provider comes from the initial instantiation and not the one that's actually going to be executed, it won't work that way either. Static values obviously work, but only because they are static.

**Comment by sebastianbergmann** [comment]
I am sorry, but this is expected behavior. The data provider is executed on a different object. And yes, I should have never allowed the data provider method to be part of the test case class.
