### ISSUE TITLE
Extend PHPUnit_Framework_TestListener with startTestClass and endTestClass

### ISSUE THREAD

**Issue by TiMESPLiNTER** [sebastianbergmann/phpunit#2121]
This is a feature request for future PHPUnit versions. It would be great if the `PHPUnit_Framework_TestListener` class could be extended with the following two methods:

* `startTestClass`: Gets called once before the first test of each test class is going to be executed
* `endTestClass`: Gets called once after the last test of each test class has been executed

**Comment by sebastianbergmann** [comment]
The existing `startTestSuite()` and `endTestSuite()` methods are called for these events.
