### ISSUE TITLE
Static methods and functions should be testable

### ISSUE THREAD

**Issue by tflori** [sebastianbergmann/phpunit#2123]
Of course I know the problem. Everyone knows the problem. It is not possible by **php-code**. You can not rename a class or rename a function after declaration and create a new one with the same name.

But this should be possible to a zend_extension. Even if you can't rename the functions / statics you should be able to monitor / mock them.

Let's see xdebug: I can set a breakpoint to check if a function got called and with which parameters it got called. Also I can run code at this time. For me it sounds that there is a way that you can even return something different (a mock).

**Comment by sebastianbergmann** [comment]
This is not a discussion forum, sorry.

**Comment by tflori** [comment]
@sebastianbergmann and where to discuss it?
