### ISSUE TITLE
Documentation enhancement:  Independent scroll for index

### ISSUE THREAD

**Issue by bkdotcom** [sebastianbergmann/phpunit#2124]
https://phpunit.de/manual/5.2/en/

Nitpick:

a)  I hate loosing my place in the left-hand index navigation when
 &nbsp;   i) I click on a link in the navigation or content.
 &nbsp;   ii) I scroll in the content
b)  Likewise, I hate loosing my place in the content when I want to scroll/browse the index.

I realize the docs are phpdoc generated..  Not sure how much can be done.

`</end rant>`

**Comment by sebastianbergmann** [comment]
This is a documentation bug that [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-documentation](https://github.com/sebastianbergmann/phpunit-documentation) project.

**Comment by bkdotcom** [comment]
d'oh
my bad (obviously)
and there's already an [open issue for it](https://github.com/sebastianbergmann/phpunit-documentation/issues/166)
