### ISSUE TITLE
PHPUnit coverage reports not working properly on unset()

### ISSUE THREAD

**Issue by erayalakese** [sebastianbergmann/phpunit#2125]
I'm trying to cover this code:

```
unset(
            $data['type'],
            $data['parentCompany'],
            $data['accountManager'],
            );
```

and sending this `$data` array

```
$data = [
    "name" => "x",
    "parentCompany"  => "x",
];
```

But in coverage report it's covering only `$data['type'],`line of unset() not covering other lines.

PHPUnit 5.1.2
PHP 5.6.18 with Xdebug 2.3.3

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project.
