### ISSUE TITLE
Use static instead of self for PHPUnit_Framework_Assert

### ISSUE THREAD

**Issue by spekary** [sebastianbergmann/phpunit#2131]
I would like to subclass PHPUnit_Framework_TestCase and provide my own "assertThat" function so that I can log each and every assert trial. I would like assertThat to call evaluate with true to return the result, and then log both success and fail.

The problem is that PHPUnit_Framework_Assert refers to assertThat using the "self" keyword, and so it bypasses the override. It should be using the "static" keyword so that my overrides will be called instead.

Alternatively, my particular problem could be solved by additional code so that successes would be sent to the listener as well as failures.

**Comment by spekary** [comment]
Looks like additionally, to effectively override, the private member variables in PHPUnit_Framework_Assert would need to be protected so that the override can access them. Why are they private?

**Comment by sebastianbergmann** [comment]
As of https://github.com/sebastianbergmann/phpunit/commit/064c8a53538918260fa0a5693c8d82a09f9b5498 `PHPUnit_Framework_Assert` uses `static::` instead of `self::`.

**Comment by sebastianbergmann** [comment]
With regard to `private` vs. `protected`: I prefer `private` and avoid `protected` whenever possible. This does not really show in PHPUnit as most of its code predates my decision to prefer `private`.

In the concrete case of `PHPUnit_Framework_Assert` there is only one private static attribute: `$count`. I am reluctant to open access to it. At most, I would consider a protected method that allows incrementing the counter.

**Comment by sebastianbergmann** [comment]
Closing this as the topic ("Use static instead of self for PHPUnit_Framework_Assert") has been taken care of.
