### ISSUE TITLE
Segmentation Fault when using code coverage on php7

### ISSUE THREAD

**Issue by adamtester** [sebastianbergmann/phpunit#2133]
Hello, how can I go about debugging a segmentation fault on php7?
When we run `phpunit --coverage-clover=coverage.xml` on php7 it fails, but `phpunit` works, but on php5.6 both commands work fine.

```
PHPUnit 4.8.21 by Sebastian Bergmann and contributors.
Segmentation fault (core dumped)
The command exited with code 139.
```

We are using laravel, and it seems to be failing at random lines across all our projects, even with the default test: https://github.com/laravel/laravel/blob/master/tests/ExampleTest.php#L16-L17

**Comment by GrahamCampbell** [comment]
PHPUnit 4 is not compatible with PHP 7. and anyway, any segfaults are nothing to do with PHPUnit. They're PHP bugs, or xdebug bugs.

**Comment by adamtester** [comment]
Ah thanks I didn't even think to check the PHPUnit version, I might try upgrading
