### ISSUE TITLE
PHP 7 fclose - observed variable has too many references

### ISSUE THREAD

**Issue by sergeyklay** [sebastianbergmann/phpunit#2135]
Hello!

I hope that what I shall now try to explain will be clear. Otherwise, feel free to ask any questions.

I'm creating [Beanstalkd][1] PHP-extension by using [Zephir lang][2]. Now I have started to cover it with unit tests. However, I encounter an error (Segmentation Fault: observed variable has too many references) when running tests on PHP 7.0.5. You can take a look at the detailed [description of the problem here][3].

From the beginning I thought that the problem lies in my code. Frankly I have spent more than one sleepless night to understand what it is:

```php
class ConnectTest extends \PHPUnit_Framework_TestCase
{
    public function testConnection()
    {
        $client = new \Beanspeak\Fclose;

        $client->disconnect(); // Segmentation Fault happens here
    }
}
```

But if I ran simple script:
```php
<?php

error_reporting(-1);

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);

$client = new \Beanspeak\Fclose;

var_dump($client->connect());
var_dump($client->disconnect());
```

all works ok:

```
# php tests/php7.php 
/app/tests/php7.php:10:
resource(4) of type (persistent stream)
/app/tests/php7.php:11:
bool(true)
```

You can see [real Zephir code here][4] (which throws Segmentation Fault). And [tests here][5]. I used different PHPUnit version 4.x and 5.x, with Codeception, without Codeception, I created simple class which I provided in [Zephir issue][3], I tested all possible options - Segmetation Fault happens only in PHPUnit by using PHP 7. 

Empirically I found out that this happens when PHP try to call `$client->disconnect()` inside PHPUnit tests. Frankly I'm not sure what the problem is PHPUnit, but I would like someone to help me figure it out with this.

Thanks

[1]: https://github.com/kr/beanstalkd
[2]: https://github.com/phalcon/zephir
[3]: https://github.com/phalcon/zephir/issues/1233
[4]: https://github.com/phalcongelist/beanspeak/blob/b9ec4dfea6e2d77931ce1e201f928efe0942ffde/beanspeak/client.zep#L114
[5]: https://github.com/phalcongelist/beanspeak/tree/master/tests/unit

**Comment by GrahamCampbell** [comment]
If php segfaults, then that's a php bug?

**Comment by sergeyklay** [comment]
Theoretically yes, but why everything is fine when I run the simple php script (without PHPUnit)?

**Comment by GrahamCampbell** [comment]
Still a PHP bug that it's crashing like that.

**Comment by sebastianbergmann** [comment]
If PHP segfaults then there is nothing we can do about it, sorry.

**Comment by sergeyklay** [comment]
Let me show

| PHP version  | Run simple script | Run PHPUnit |
| ------------- | ------------- | ------------- |
| 5.4.45  | OK  | OK  |
| 5.5.34  | OK  | OK  |
| 5.6.20  | OK  | OK  |
| 7.0.5  | OK  | Segmentation Fault  |
