### ISSUE TITLE
PHPStorm fails when using a custom result printer

### ISSUE THREAD

**Issue by dawehner** [sebastianbergmann/phpunit#2141]
We introduced a custom result printer for some end-to-end test class, that prints out URLs to dumps of the HTML of each visited URL.

The phpunit.xml looks like the following:
```
<phpunit bootstrap="tests/bootstrap.php" colors="true"
         beStrictAboutTestsThatDoNotTestAnything="true"
         beStrictAboutOutputDuringTests="true"
         beStrictAboutChangesToGlobalState="true"
         checkForUnintentionallyCoveredCode="false"
         printerClass="\Drupal\Tests\Listeners\HtmlOutputPrinter">
  <php>
```

Running these tests works perfectly fine from the command line, but they fatal when you run the tests directly via phpstorm:

```
/usr/local/Cellar/php56/5.6.18/bin/php /private/var/folders/9b/073w6tbx1tgfnhzsx7_4ps_w0000gn/T/ide-phpunit.php --configuration /Users/dawehner/www/d8/core/phpunit.xml.dist Drupal\Tests\simpletest\Functional\BrowserTestBaseTest /Users/dawehner/www/d8/core/modules/simpletest/tests/src/Functional/BrowserTestBaseTest.php
Testing started at 09:15 ...

Notice: Trying to get property of non-object in /private/var/folders/9b/073w6tbx1tgfnhzsx7_4ps_w0000gn/T/ide-phpunit.php on line 262
```

Long story short, the bug is in PHPStorm (https://youtrack.jetbrains.com/issue/WI-24808) but let's at least improve the docs a bit: https://github.com/sebastianbergmann/phpunit/pull/2140

**Comment by dawehner** [comment]
Let's close the issue, but posting it here maybe helps other people

**Comment by sebastianbergmann** [comment]
Maybe @SvetlanaZem can help but I am afraid that this is not a PHPUnit issue but one with PhpStorm's old wrapper for it.

**Comment by dawehner** [comment]
@sebastianbergmann 
Yeah totally, I posted a patch on their queue which should / could help
