### ISSUE TITLE
Want to look for *test.php files when I point  to a directory

### ISSUE THREAD

**Issue by kenjis** [sebastianbergmann/phpunit#2142]
When I run `phpunit` command, it runs all my tests (`*test.php`).
Because I set `<directory suffix="test.php">./</directory>` in `<testsuite>`.

But when I run `phpunit <directory>`,  it runs no tests.
Because there is a limitation:
> If you point the PHPUnit command-line test runner to a directory it will look for *Test.php files. 
https://phpunit.de/manual/current/en/organizing-tests.html

This is not consistent.

I hope I can run tests when I point a directory.

**Comment by sebastianbergmann** [comment]
You can but then you have to follow the `*Test.php` convention. If you do not want to follow the convention then you need to use the configuration file.
