### ISSUE TITLE
Missing class documentation

### ISSUE THREAD

**Issue by lusitania** [sebastianbergmann/phpunit#2143]
I completely fail to find any hints for a full class documentation or a way to build it myself. Where or how can I find/build it (for 4.8)?

ATM I have to sift through the source code to find out about `$this->once()` and the likes.

**Comment by alexislefebvre** [comment]
This is (briefly) explained in the documentation: https://phpunit.de/manual/4.8/en/test-doubles.html#test-doubles.mock-objects.examples.SubjectTest.php Does it help you?

**Comment by sebastianbergmann** [comment]
API documentation is available at https://api.phpunit.de/.
