### ISSUE TITLE
Subgrouping Tests in testdox

### ISSUE THREAD

**Issue by lukasoppermann** [sebastianbergmann/phpunit#2146]
When you have an extensive test suit it can be quite a mess. To organize your tests so that it is easier to see where you have an error, I would like to be able to group tests.

In my opinion this could be done using the already existing groups when no `--group` parameter is provided.

``` php
class FooTest
{
/**
 * @group group-name
 * @test
 */
public function test1(){}

/**
 * @group group-name
 * @test
 */
public function testTwo(){}

/**
 * @group other-group-name
 * @test
 */
public function test3(){}
}
```

Would be displayed as:

``` bash
Foo
  group-name
    [x] Test1
    [ ] TestTwo
  other-group-name
    [x] Test3
```

**Comment by sebastianbergmann** [comment]
I do not think that this would be useful, sorry.
