### ISSUE TITLE
Invalid reports structure with Warning tests for JSON and JUnit logger

### ISSUE THREAD

**Issue by edno** [sebastianbergmann/phpunit#2153]
With **PHPUnit 5.4**, Warning tests for reports `--log-junit` and `--log-json` are encapsulated in a sub testsuite element. That is generating incorrect results while parsing the report.

Report with option `--log-junit`

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="TestStatus" file="tests/_files/TestStatus.php" tests="7" assertions="5" errors="2" failures="2" skipped="2" time="0.007501">
...
    <testsuite name="TestStatus::testWarning" tests="1" assertions="0" errors="0" failures="1" skipped="0" time="0.002623">
      <testcase name="Warning" assertions="0" time="0.002623">
        <warning type="PHPUnit_Framework_Warning">Warning
The data provider specified for TestStatus::testWarning is invalid.

</warning>
      </testcase>
    </testsuite>
...
  </testsuite>
</testsuites>
```

Report with option `--log-json`

``` json
{
    "event": "suiteStart",
    "suite": "TestStatus",
    "tests": 7
}
...
{
    "event": "suiteStart",
    "suite": "TestStatus::testWarning",
    "tests": 1
}{
    "event": "testStart",
    "suite": "TestStatus::testWarning",
    "test": "Warning"
}{
    "event": "test",
    "suite": "TestStatus::testWarning",
    "test": "Warning",
    "status": "warning",
    "time": 0.0011630058288574,
    "trace": [],
    "message": "The data provider specified for TestStatus::testWarning is invalid.\n",
    "output": ""
}
...
```

Gist with the phpunit test and outputs: https://gist.github.com/edno/2532e9ff5aa74a6b9cc0ceafee32bd24

**Comment by sebastianbergmann** [comment]
@lstrojny Can you have a look, at least at the JUnit one? Thanks!

**Comment by lstrojny** [comment]
@sebastianbergmann is 5.4 master?

**Comment by sebastianbergmann** [comment]
Yes.

**Comment by lstrojny** [comment]
OK, looked into it. This is what I found so far, assume this test case:

```php
class Test extends PHPUnit_Framework_TestCase
{
    /** @dataProvider getFoo */
    public function testFoo()
    {
    }
}
```

With the case above `PHPUnit_Util_Log_JUnit::startTestSuite()` is called twice after each other without an invocation of `endTestSuite()`in between (which would also explain the problem in the JSON reporter). Am I correct to assume that this is not what a reporter should expect, @sebastianbergmann but rather that the contract is symmetric and each invocation of `startTestSuite()` must be followed by `endTestSuite()`?

**Comment by sebastianbergmann** [comment]
That is my understanding, too.

**Comment by sebastianbergmann** [comment]
Sorry for dropping the ball on this. What do you think should be done here, @lstrojny?

**Comment by lstrojny** [comment]
@sebastianbergmann we need to make sure that `endTestSuite()` is reliably called

**Comment by FrankGiesecke** [comment]
In SonarQube, the malformed report XML causes hundreds of warnings that there are testsuites without a reference to a `file`.

We often use data providers, which seems to trigger the problem. Is there any solution for this?

**Comment by sebastianbergmann** [comment]
When this bug gets fixed (pull request welcome!) then it will not be fixed for PHPUnit 4.8. Support for PHPUnit 4 ended on February 3, 2017.

**Comment by FrankGiesecke** [comment]
Ok, I'm sad to hear that but it was the answer I had expected.
What will be the oldest version, that will get the fix?

**Comment by sebastianbergmann** [comment]
PHPUnit 5.7 (as should be clear from https://phpunit.de/).

**Comment by sebastianbergmann** [comment]
@lstrojny I added a test for this in a36dd5e7572428c60bbbf372e4c6a98430f8001f. Could you have a look at whether the expected XML is correct? Thanks!

**Comment by lstrojny** [comment]
@sebastianbergmann LGTM
