### ISSUE TITLE
expectOutputString and error_log

### ISSUE THREAD

**Issue by twistofreality** [sebastianbergmann/phpunit#2155]
I've been banging my head against tests for a class involving error_log for a bit, and I'm starting to wonder if I'm running into some sort of output buffer bug in PHPUnit.  PHPUnit appears not to be capturing error_log output as I would expect.  Here's a quick-and-dirty test I wrote.

ObTest.php:

``` php
<?php
namespace Some\Test;

class ObTest
{
    public function writeToErrorLog($message)
    {
        error_log($message);
    }
}
```

The corresponding test:

``` php
<?php

namespace Some\Test;

include "ObTest.php";

class ObTestTest extends \PHPUnit_Framework_TestCase
{
    public static $error_log_config;

    public static function setUpBeforeClass()
    {
        self::$error_log_config = ini_get("error_log");

        ini_set("error_log", "/dev/stdout");
    }

    public static function tearDownAfterClass()
    {
        ini_set("error_log", self::$error_log_config);
    }

    public function testWriteToErrorLogOutputs()
    {
        $ob_test = new ObTest();

        $this->expectOutputString("Test");

        $ob_test->writeToErrorLog("Test");
    }
}
```

And the output:

```
PHPUnit 5.4-g9b5b99b by Sebastian Bergmann and contributors.

[06-May-2016 01:05:51 UTC] Test

Failed asserting that two strings are equal.
Expected :'Test'
Actual   :''
```

I've also tried setting error_log to php://output thinking that the issue had something to do with stdout not getting captured in PHPUnit's output buffering at all; PHPUnit still returns the empty string as "Actual", which is ultimately what led me to believe this might be a bug.

I get the same result with PHPUnit 5.3.2, and in general I'm running PHP 5.6.20-1+deb.sury.org~trusty+1

**Comment by sebastianbergmann** [comment]
I just verified that `error_log` can actually be configured at runtime using `ini_set()`:
```php
<?php
ini_set('error_log', 'php://stdout');
error_log('php://stdout');

ini_set('error_log', 'php://output');
error_log('php://output');

ini_set('error_log', '/dev/stdout');
error_log('/dev/stdout');
```
```
php://stdout
php://output
[14-Oct-2017 08:15:46 UTC] /dev/stdout
```
It's weird, though, that the output made using `/dev/stdout` is different from the one made using `php://stdout` and `php://output`.

**Comment by sebastianbergmann** [comment]
AFAIK, writing to `php://stdout` etc. bypasses PHP's output buffering mechanism.

I think that for testing `error_log()` a stream wrapper is needed. [vfsStream](https://github.com/mikey179/vfsStream) might just work.

**Comment by tillkruss** [comment]
```php

$capture = tmpfile();
$backup = ini_set('error_log', stream_get_meta_data($capture)['uri']);

// error_log('...')
// var_dump(stream_get_contents($capture));

ini_set('error_log', $backup);
```

**Comment by staabm** [comment]
Till Krüss suggestion works great.

@sebastianbergmann what do you think about adding such utility somehow to test `error_log` easily?
atm I have to add 3 methods boilerplate to make a test not fail because of expected output logged into `error_log`.

**Comment by sebastianbergmann** [comment]
> Till Krüss suggestion works great.

Does it also work on Windows?
