### ISSUE TITLE
Phpunit Blank

### ISSUE THREAD

**Issue by johnss** [sebastianbergmann/phpunit#2157]
Phpunit blank whatever the command are,
`phpunit --version` should return the version instead of blank, after reading minimum requirement in docs, i know problem are it did not meet minimum php version, and probably other php ext requirement, PHPunit should return exception detailing what causing error instead of blank in the command-line.

https://github.com/sebastianbergmann/phpunit/issues/1030 it should display Mockery not found error in cli instead of blank

**Comment by sebastianbergmann** [comment]
Can you please provide information on how you obtained PHPUnit, how you installed it, and how you executed it?

**Comment by johnss** [comment]
i tried executing the phar file using
`php /~/phpunit.phar --version` recently upgraded to php 7 still blank

**Comment by sebastianbergmann** [comment]
Are you using Suhosin?

**Comment by johnss** [comment]
Not .
