### ISSUE TITLE
Oracle Database connection in tests on mac osx El Capitan

### ISSUE THREAD

**Issue by XavRsl** [sebastianbergmann/phpunit#2170]
Hi,
My problem is very limited to my environment, but could be useful to others. I use an Oracle Database, with php oci8 extension on mac osx El Capitan. oci8 requires an environment variable to be available to the php process in order to use the Oracle related libraries. This variable looks like this : DYLD_LIBRARY_PATH=/opt/oracle/instantclient_11_2/
It is possible to set that variable in the mac's Library path, in a .plist file. But, phpunit doesn't use php directly, it uses a specific shebang that determines the php executable to use from the environement : 
```
#!/usr/bin/env php
```

**Comment by sebastianbergmann** [comment]
Don't see what this should have to do with PHPUnit.

**Comment by XavRsl** [comment]
Sorry, I posted my comment too quickly. I've updated it.

**Comment by XavRsl** [comment]
Sorry to insist but I do think this has something to do with PhpUnit. The fact that PhpUnit uses env to call Php leads to the problem I'm describing. So maybe you can't do anything about it but I'm just asking to know if you have any solution to get around the problem, for me and for others who may encounter the same issue.

Thanks.

Xavier
