### ISSUE TITLE
PSR-4 support on phpunit 6

### ISSUE THREAD

**Issue by Faryshta** [sebastianbergmann/phpunit#2172]
I propose to open a poll to let the users decide if they want this on the next major version.

The downside is to have to change the class names on all files and possibly some time for some projects to move to the version 6.

but since version 6 will require php7 all libraries must already work on BC breaks from php7 so I think its the perfect moment to have support for namespaced classes.

I will write two comments bellow and let the users vote using github reactions.

**Comment by Faryshta** [comment]
Add support for PSR-4 on phpunit 6

**Comment by Faryshta** [comment]
Keep the classes and autoloading as it is right now.

**Comment by sebastianbergmann** [comment]
Users should not care about how PHPUnit is implemented. But yes, PHPUnit 6 will (likely) use namespaces.
