### ISSUE TITLE
PHPUnit Slow on Windows 10

### ISSUE THREAD

**Issue by travy** [sebastianbergmann/phpunit#2173]
I was wondering if anyone else has come across this issue where unit testing runs 10x slower on Windows 10?  I have two PC's that I work on (home and office), my home PC has been Windows 10 for a few months now and I noticed the issue but accredited it to some plugin on my system and ignored it.  However, recently my office PC updated to Windows 10 and test that should have taken 1 minute to run are now taking as much as 10 minutes or longer.  I even tried some test environments where the test are simply ignored and they were still running really slow, took 5 minutes for 10 ignored unit test to finish.

I've since downgraded my work PC back to Windows 7 and the unit testing are running at regular speed again.  Has anyone else experienced this?  I use PHP 5.6 with PHPUnit 5.3.4 and xdebug turned off.

**Comment by sebastianbergmann** [comment]
This is not a discussion forum, sorry.

**Comment by travy** [comment]
Right but if others are experiencing the same issue than that would suggest a possible issue within phpunit
