### ISSUE TITLE
Problem with html in phpunit 4.8 php 5.3

### ISSUE THREAD

**Issue by henres** [sebastianbergmann/phpunit#2176]
Hello,

I don't know how to fix this. But i have a problem with phpunit.
Maybe it's not a bug but all html is considered as a red line :
![screenshot from 2016-05-27 10-30-41](https://cloud.githubusercontent.com/assets/866305/15602592/7541deb8-23f6-11e6-9a39-bebd8d8a5a2b.png)
Is it a configuration problem?
Thanks

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project.
