### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Kilgaloon** [sebastianbergmann/phpunit#2177]
Maybe this is PHP internal error, but since i came across this segfault running phpunit, i will leave it here.

This first example is of class that happens to throw segmentation fault.
Segmentation fault is happening at this method ` $this->callClassMethod($collection[2]);`

    use Phase\Router\Request\HeaderMessage;
    class RouterTest extends PHPUnit_Framework_TestCase {
        private $routeCollection = [];

       private $headerMessage;

         public function __construct() {
              array_push($this->routeCollection, [["route","default"],"POST",function() {return true;}]);
              array_push($this->routeCollection[["route","default"],"POST","RouterTest@controllerMethodTest"]);
              array_push($this->routeCollection, [["route","default"],"POST",["controller" => "RouterTest", "method" => "controllerMethodTest"]]);

             $this->headerMessage = new HeaderMessage();
         }

        public function test_run() {
                $uri = ["route","default"];
        $url = implode("/", $uri);

        foreach($this->routeCollection as $collection) {
            $coll = implode("/", $collection[0]);

            if(substr($url, 0, strlen($coll)) === $coll && $collection[1] == "POST") {
                $args = array_splice($uri, count($collection[0]));

                if(is_callable($collection[2])) {
                    $this->assertTrue(call_user_func_array($collection[2], $args));
                }

                if(is_string($collection[2])) {
                    $sep = explode("@", $collection[2]);
                    $controller = new $sep[0];
                    $method = $sep[1];

                    $this->assertTrue(call_user_func_array(array($controller,$method), $args));
                }

                if(is_array($collection[2]) && isset($collection[2]["controller"])) {
                    $this->callClassMethod($collection[2]);
                }

            }

            if($collection[1] != "POST") {
                $this->assertTrue($this->headerMessage->sendHeader405());
            }

        }

          $this->assertTrue($this->headerMessage->sendHeader404());
     }

 
       private function callClassMethod(Array $classFromCollection) {
          if(class_exists($classFromCollection["controller"])) {
              $controller = new $classFromCollection["controller"];
              $method =  $classFromCollection["method"];

              $this->assertTrue(call_user_func_array(array($controller,$method), $args));
        }
    }

Changing this line of code and omitting to call `$this->callClassMethod($collection[2])` it happends that segfault is not there anymore and tests pass.

    if(is_array($collection[2]) && isset($collection[2]["controller"])) { 
        $classFromCollection = $collection[2];
         if(class_exists($classFromCollection["controller"])) {
              $controller = new $classFromCollection["controller"];
              $method =  $classFromCollection["method"];

              $this->assertTrue(call_user_func_array(array($controller,$method), $args));
        }
    }

PHPUnit version is 5.3.1
PHP version is PHP 7.0.6-1~dotdeb+8.1 (cli) ( NTS )

**Comment by sebastianbergmann** [comment]
You have found a problem in the PHP runtime that leads to a segfault. An issue like this has to be reported at https://bugs.php.net/report.php using a minimal, self-contained, reproducing test case.

Please note that a test case that needs to be run through PHPUnit does not qualify as either "minimal" or "self-contained" when reporting bugs for the PHP runtime.

**Comment by Kilgaloon** [comment]
Reproducing same code in php and running it, it does throw messages that should throw, without segmentation fault.

**Notice: Undefined variable: args **
**Warning: call_user_func_array() expects parameter 2 to be array, null given**

PHPUnit should return this messages? insead it gives Segmentation fault, am i missing something
