### ISSUE TITLE
It not fix issue #1252

### ISSUE THREAD

**Issue by hamuhamu** [sebastianbergmann/phpunit#2178]
#1252

This problem also occurs in the latest commit even with the latest stable version.
Is better to assertSame also see the difference between the array.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by sebastianbergmann** [comment]
No feedback, closing.
