### ISSUE TITLE
Please upgrade the requirement of symfony/yaml

### ISSUE THREAD

**Issue by xkobal** [sebastianbergmann/phpunit#2180]
The new Symfony Framework 3.1.0 has been release today: http://symfony.com/blog/symfony-3-1-0-released

But the requirement in composer.json for symfony/yaml prevent to use it with phpunit: https://github.com/sebastianbergmann/phpunit/blob/master/composer.json#L32

**Comment by GrahamCampbell** [comment]
That version constraint already permits the use of 3.1. There is nothing to do.

**Comment by xkobal** [comment]
So it may be another requirement in the phpunit stack, I have to investigate that point

**Comment by xkobal** [comment]
Here is the dependency tree from composer with Symfony 3.1 and Phpunit 5.3.4:

    - Installation request for phpunit/phpunit 5.3.4 -> satisfiable by phpunit/phpunit[5.3.4].
    - Conclusion: remove symfony/symfony v3.1.0
    - phpunit/phpunit 5.3.4 requires phpspec/prophecy ^1.3.1 -> satisfiable by phpspec/prophecy[1.4.0, v1.3.1, v1.4.1, v1.5.0, v1.6.0].
    - phpspec/prophecy 1.4.0 requires phpdocumentor/reflection-docblock ~2.0 -> satisfiable by phpdocumentor/reflection-docblock[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4].
    - phpspec/prophecy v1.3.1 requires phpdocumentor/reflection-docblock ~2.0 -> satisfiable by phpdocumentor/reflection-docblock[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4].
    - phpspec/prophecy v1.4.1 requires phpdocumentor/reflection-docblock ~2.0 -> satisfiable by phpdocumentor/reflection-docblock[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4].
    - phpspec/prophecy v1.5.0 requires phpdocumentor/reflection-docblock ~2.0 -> satisfiable by phpdocumentor/reflection-docblock[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4].
    - phpspec/prophecy v1.6.0 requires phpdocumentor/reflection-docblock ~2.0 -> satisfiable by phpdocumentor/reflection-docblock[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4].
    - phpdocumentor/reflection-docblock 2.0.0 conflicts with symfony/symfony[v3.1.0].
    - phpdocumentor/reflection-docblock 2.0.1 conflicts with symfony/symfony[v3.1.0].
    - phpdocumentor/reflection-docblock 2.0.2 conflicts with symfony/symfony[v3.1.0].
    - phpdocumentor/reflection-docblock 2.0.3 conflicts with symfony/symfony[v3.1.0].
    - phpdocumentor/reflection-docblock 2.0.4 conflicts with symfony/symfony[v3.1.0].
    - Installation request for symfony/symfony 3.1.* -> satisfiable by symfony/symfony[v3.1.0].

phpspec/prophecy requirement for phpdocumentor/reflection-docblock is ~2.0, but the correct version is 3.0

**Comment by GrahamCampbell** [comment]
This is already a known issue, and they are working on it. Please see the open issues there. :)

**Comment by GrahamCampbell** [comment]
> but the correct version is 3.0

Not the correct version, just a newer version, that they'd need to change their code in order to use. That's what's causing the hold up.

**Comment by GrahamCampbell** [comment]
See https://github.com/phpspec/prophecy/issues/272.
