### ISSUE TITLE
Incompatibility with WP_Mock

### ISSUE THREAD

**Issue by insprintorob** [sebastianbergmann/phpunit#2182]
We just found an incompatibility between WP_Mock (https://github.com/10up/wp_mock) and phpunit.

WP_Mock is used to mock and set up expectaitons for wordpress function calls, i.e.
`		\WP_Mock::wpFunction('wp_cache_get', array(
`			'args' => 'user_data_'.$user['email'],
`			'return' => $userDataMocked,
`		));

Basically, the problem is with the ConfigurationGenerator::generateDefaultConfiguration() function, because its required in before Patchwork.php (which needs to be the first thing required in userspace).

PHP Warning:  Please import Patchwork from a point in your code where no user-defined function, class or trait is yet defined. ConfigurationGenerator::generateDefaultConfiguration() and possibly others currently violate this. in ...vendor/antecedent/patchwork/Patchwork.php on line 95.

Previously we simply had this as the top line in our phpunit bootstrap file
//Load Patchwork for WP_Mock, so we can mock internal Wordpress functions like get_posts() in unit tests
`if ( file_exists( __ROOT_DIR__ . '/vendor/antecedent/patchwork/Patchwork.php' ) ) {
`	require_once( __ROOT_DIR__ . '/vendor/antecedent/patchwork/Patchwork.php' );
`}

This worked fine up until recently, when ConfigurationGenerator::generateDefaultConfiguration() was introduced here (and apparently runs before the bootstrap file): https://github.com/sebastianbergmann/phpunit/blob/master/src/Util/ConfigurationGenerator.php

We could suppress the warning, but should the bootstrap always run before anything else in phpunit? I think this is the right approach, considering how other things (frameworks etc) often work with the bootstrap being the first thing to run.

**Comment by sebastianbergmann** [comment]
I am sorry to say this, but your report makes no sense. `generateDefaultConfiguration()` is only called when you invoke PHPUnit with `phpunit --generate-configuration`. And you should only ever do that if you want to generate a new configuration file.

**Comment by insprintorob** [comment]
Your right, its only called when you run `phpunit --generate-configuration`. However, the issue is that hte method is defined before Patchwork.php, rather than being run before it.

**Comment by insprintorob** [comment]
Heres a workaround for anyone that needs it (successfully tested on our ci server).

Basically, put a @ in front of the requiring in of patchwork, to suppress the warning.

@require_once( '/path/to/Patchwork.php' );

**Comment by insprintorob** [comment]
I should probably mention that this is actually a compatibility with Patchwork, which is a dependency of WP_Mock. https://github.com/antecedent/patchwork. Its used for overwriting user-space functions, WP_Mock uses this feature so that it can mock WordPress functions.

**Comment by sebastianbergmann** [comment]
There are other classes in PHPUnit that are loaded before the class you are refering to is loaded. Again: this makes no sense. Sorry, but I am closing this.
