### ISSUE TITLE
Fixture example failed

### ISSUE THREAD

**Issue by kiro112** [sebastianbergmann/phpunit#2183]
Hi,

im currently learning PHPUnit, i encounter a problem on **[FIXTURE Example 4.2](https://phpunit.de/manual/current/en/fixtures.html)**

	class TemplateMethodsTest extends \PHPUnit_Framework_TestCase {

		public static function setUpBeforeClass () {
			fwrite(STDOUT, __METHOD__ . "\n");
		}

		protected function setUp () {
			fwrite(STDOUT, __METHOD__ ."\n");
		}

		protected function assetPreConditions () {
			fwrite(STDOUT, __METHOD__ . "\n");
		}

		public function testOne () {
			fwrite(STDOUT, __METHOD__ . "\n");
			$this->assertTrue(TRUE);
		}

		public function testTwo () {
			fwrite(STDOUT, __METHOD__ . "\n");
			$this->assertTrue(FALSE);
		}

		protected function assertPostConditions () {
			fwrite(STDOUT, __METHOD__ . "\n");
		}

		protected function tearDown () {
			fwrite(STDOUT, __METHOD__ . "\n");
		}

		protected function onNotSuccessfulTest (Exception $e) {
			fwrite(STDOUT, __METHOD__ . "\n");
			throw $e;
		}
	}

i adjusted the testTwo() to pass

but the onNotSuccessfulTest() throws an error

	Argument 1 passed to phpUnitTutorial\Test\TemplateMethodsTest::onNotSuccessfulTest() must be an instance of phpUnitTutorial\Test\Exception, instance of PHPUnit_Framework_ExpectationFailedException given, called in phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php on line 993 and defined

`PHP 5.6.22-1`
`PHPUnit 5.3.4`

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-documentation](https://github.com/sebastianbergmann/phpunit-documentation) project.
