### ISSUE TITLE
Not equals arrays is equals (Different order) 

### ISSUE THREAD

**Issue by s4urp8n** [sebastianbergmann/phpunit#2184]
I write some package to work with arrays. I implement **reverse()** method, and try to test it with codeception (it uses **PHPUnit** as unit tester). If arrays have same keys and values but different order of elements it is consider as equals - but, i think it is bug

There was 1 failure:

---

1) Failed to reverse test in ArrCest::reverseTest (tests\unit\ArrCest.php)

 Step  I assert not equals {"three":3,"two":2,"one":1,"zero":0},{"zero":0,"one":1,"two":2,"three":3}
 Fail  Failed asserting that Array &0 (
    **'zero' => 0
    'one' => 1
    'two' => 2
    'three' => 3**
) is not equal to Array &0 (
    **'three' => 3
    'two' => 2
    'one' => 1
    'zero' => 0**
).

**Comment by GrahamCampbell** [comment]
Do you want `notSame`?

**Comment by s4urp8n** [comment]
assertNotSame works fine. You mean that I used wrong assertion method?

**Comment by GrahamCampbell** [comment]
> You mean that I used wrong assertion method?

Yes. ;)

**Comment by s4urp8n** [comment]
Ok. But difference in **Same** and **Equals** methods is type checking - is't it? In my example type the same - array. Both methods must works identical.

**Comment by GrahamCampbell** [comment]
> Ok. But difference in Same and Equals methods is type checking - is't it?

No, actually, as you can see here. ;)

**Comment by s4urp8n** [comment]
It's right logic?

**Comment by GrahamCampbell** [comment]
Yes, I don't believe there is a bug here.

**Comment by s4urp8n** [comment]
Ok, you win) I mark it as a feature)

**Comment by mcustiel** [comment]
@sebastianbergmann I think this can be closed. It works as described in: http://php.net/manual/en/language.operators.array.php

**Comment by robsonvn** [comment]
I wrote a test assuming that the `assertEquals` would compare the ordering too but it doesn't, I believe we should implement an `assertIdentity` in this case unless there's another method that does the same and I'm not aware.

**Comment by robsonvn** [comment]
I wrote a test assuming that the `assertEquals` would compare the ordering too but it doesn't, I believe `assertIdentity` would be a better naming for `assertSame`
