### ISSUE TITLE
Update the docs to use assertSame etc. statically

### ISSUE THREAD

**Issue by oliverklee** [sebastianbergmann/phpunit#2185]
assertSame etc. are static now, and the examples in the documentation should use self::assertSame etc. instead of $this->assertSame etc. to keep programmers from getting PHP warnings.

**Comment by sebastianbergmann** [comment]
They have always been static. And why would that lead to warnings?

**Comment by oliverklee** [comment]
Okay, even if they always have been static, we should adapt the documentation so that the examples also use the static calls:

https://phpunit.de/manual/current/en/writing-tests-for-phpunit.html

AFAIK, PHP throws a warning if a non-static method is called statically. I would expect the opposite (a warning when a static method is called non-statically) to be true as well. (At least PhpStorm complains about this.)

**Comment by sebastianbergmann** [comment]
No, we should not. And as developers, our purpose in life is not to make our IDE happy. If PhpStorm complains about valid code then that is a bug. Sorry, but I am closing this.

**Comment by oliverklee** [comment]
Just to make sure I'm not mistaken (and using an opportunity to learn something): Calling a static method in a non-static way is valid, while calling a non-static method statically is not valid?

**Comment by sebastianbergmann** [comment]
Yes.

**Comment by oliverklee** [comment]
Thanks for the clarification! :heart:
