### ISSUE TITLE
getMockBuilder now marked as protected, not public

### ISSUE THREAD

**Issue by benmatselby** [sebastianbergmann/phpunit#2186]
When upgrading to PHPUnit 5.4, getMockBuilder has become a protected method and is no longer publicly available so a substantial amount of our tests now fail based on this:

```
Error: Call to protected method PHPUnit_Framework_TestCase::getMockBuilder() from context 'BeanHelper'
```

We had some helpers that built mock objects for us, however we could get round this by using traits in our test cases if need be.

**Comment by sebastianbergmann** [comment]
PHPUnit 5.4.1 has been released with 76e6c958446b4892682f97eb34fae235baa06917 to make `PHPUnit_Framework_TestCase::getMockBuilder()` public again.

However, I have to say that I have a hard time understanding why this method has to be `public`. It only makes sense to call from a subclass of `PHPUnit_Framework_TestCase` and for that `protected` is sufficient.

Anyway: thank you for reporting this.

**Comment by benmatselby** [comment]
@sebastianbergmann So first off, thanks for 5.4.1. But to be honest, I agree with you, and am now looking to change this code, as I don't think it needs to be public either.

**Comment by ondrejmirtes** [comment]
I use this method from outside TestCase in my library: https://github.com/ondrejmirtes/mocktainer

**Comment by benmatselby** [comment]
The new createMock() function in TestCase looks to solve this issue now too. Might help you out @ondrejmites

**Comment by ondrejmirtes** [comment]
@benmatselby createMock() is protected so I cannot use it, I am stuck with getMockBuilder.
