### ISSUE TITLE
Remove getMock()

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#2194]
Deprecated since PHPUnit 5.4.

**Comment by scaytrase** [comment]
As soon as 5.4 marked stable these lines (https://github.com/sebastianbergmann/phpunit/blob/5.4/src/Framework/TestCase.php#L1557) causes all project using stable phar or `~5.x`  as composer dependency fail as soon as the default option is to convert warning to exceptions is set to true (https://github.com/sebastianbergmann/phpunit/blob/fe1336dbec3ccf4e6ff3c6b4b29dd5e83d805e0d/src/Util/Configuration.php#L630)

Is it really neccessary to forcibly add warning on call?

The interesting moment that when using php7 - tests pass well, warning is ignored (or not raised?).

**Comment by sebastianbergmann** [comment]
@scaytrase `$this->warnings[]` has nothing to do with PHP warnings that are converted to exceptions.

**Comment by scaytrase** [comment]
I'm not really sure which option leads to this (this one has caused Symfony 2.7 fail two years ago then they started to `trigger_error` on any deprecated function), but anyway test run looks like following

```
$ phpunit --colors -c phpunit.xml
PHPUnit 5.4.6 by Sebastian Bergmann and contributors.
WWWWWWWWWWWWW                                                     13 / 13 (100%)
Time: 4.35 seconds, Memory: 22.00MB
There were 13 warnings:
1) Bankiru\Api\Tests\CollectionLoadingTest::testLazyCollections
PHPUnit_Framework_TestCase::getMock() is deprecated, use PHPUnit_Framework_TestCase::createMock() or PHPUnit_Framework_TestCase::getMockBuilder() instead
```

(13 equal warnings)

```
WARNINGS!
Tests: 13, Assertions: 112, Warnings: 13.
```

**Comment by sebastianbergmann** [comment]
As you can see in https://github.com/sebastianbergmann/phpunit/blob/5.4/src/Framework/TestCase.php#L936, these deprecation warnings are only generated when the test was successful, meaning that they do not hide test failures.

**Comment by scaytrase** [comment]
The problem is on the other side. Previously successful test suite fails just because the enviorment (phpunit-stable) or dependency (~5.x) changes, so it looks like a BC-break at 5.4, not an 6.0

As far as I understand this does not comform well with semver or this project does not follow it strictly?

**Comment by sebastianbergmann** [comment]
A warning does not fail a test suite.

**Comment by scaytrase** [comment]
Yeah, you are fully correct, sorry. Cannot reproduce this on a sample test case. I'll try to search why travis' phpunit exits with 1 on 5.6 

Thank you for clarifying

**Comment by scaytrase** [comment]
I've wrote a sample demonstration. PhpUnit exits with code 1 silently with travis, php 5.6.5 and phpunit 5.4.6 

https://github.com/scaytrase/pu54-sample
https://travis-ci.org/scaytrase/pu54-sample/jobs/138289611

The php 5.6 build has the warning at the output:
https://travis-ci.org/scaytrase/pu54-sample/jobs/138289611
And the php 7.0 does not:
https://travis-ci.org/scaytrase/pu54-sample/jobs/138289612

Could you take a look? May be I do something wrong, but the sample is as simple as possible

**Comment by sebastianbergmann** [comment]
As you can see in the example below, a warning does not mark the test execution as a failure:
```
$ phpunit Test
PHPUnit 5.4.6 by Sebastian Bergmann and contributors.

W                                                                   1 / 1 (100%)

Time: 27 ms, Memory: 4.00MB

There was 1 warning:

1) Test::testOne
PHPUnit_Framework_TestCase::getMock() is deprecated, use PHPUnit_Framework_TestCase::createMock() or PHPUnit_Framework_TestCase::getMockBuilder() instead

WARNINGS!
Tests: 1, Assertions: 0, Warnings: 1.
```
```
$ echo $?                  
0
```
Exit code 0 means success.

Also note that this ticket is the wrong place to discuss your issue. This ticket is just a reminder to remove functionality for PHPUnit 6 that is deprecated in PHPUnit 5.
