### ISSUE TITLE
Test timeouts do not work on PHP 7

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#2205]
- Sebastian Bergmann: "https://github.com/sebastianbergmann/php-invoker/blob/master/src/Invoker.php is the only thing I ever used ticks for." (http://chat.stackoverflow.com/transcript/message/30991918#30991918)
- Nikita Popov: "Won't even work in PHP 7 ^^" (http://chat.stackoverflow.com/transcript/message/30991943#30991943)
- Sebastian Bergmann: "Really? That explains some things ... Damn it." (http://chat.stackoverflow.com/transcript/message/30991960#30991960)
- Sebastian Bergmann: "Is there any way I can achieve what I want in PHP 7?" (http://chat.stackoverflow.com/transcript/message/30991969#30991969)
- Nikita Popov: "I don't think so ... maybe I should ... er ... "unfix" the ticks mechanism to make it work again" (http://chat.stackoverflow.com/transcript/message/30991984#30991984)

**Comment by sebastianbergmann** [comment]
Works with PHP >= 7.1 and php-invoker >= 2.0:
```php
<?php
class Test extends PHPUnit\Framework\TestCase
{
    /**
     * @small
     */
    public function testOne()
    {
        sleep(2);
        
        $this->assertTrue(true);
    }
}
```
```
$ phpunit --enforce-time-limit Test
PHPUnit 7.0-gefedf29a3 by Sebastian Bergmann and contributors.

R                                                                   1 / 1 (100%)R

Time: 1.03 seconds, Memory: 4.00MB

There were 2 risky tests:

1) Test::testOne
Execution aborted after 1 second

2) Test::testOne
This test did not perform any assertions

OK, but incomplete, skipped, or risky tests!
Tests: 1, Assertions: 0, Risky: 2.
```

**Comment by mikolajprzybysz** [comment]
Hi I did run this test on with: `phpunit/php-invoker:2.0.0` and the result is

```
./vendor/bin/phpunit --enforce-time-limit --group small
PHPUnit 6.5.6 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.9-1+ubuntu16.04.1+deb.sury.org+1 with Xdebug 2.6.0

.                                                                   1 / 1 (100%)

Time: 3.84 seconds, Memory: 8.00MB
```
