### ISSUE TITLE
Sgementation fault when using code coverage

### ISSUE THREAD

**Issue by JJacobi13** [sebastianbergmann/phpunit#2208]
We use phpunit together with the laravel framework. When we only run the phpunit tests, all our tests succeed. When we want to generate the coverage html, we get a segmentation fault. When debugging we found using a laravel relationship inside a query gives us this segmentation fault. Moving this relation to the outside of the query solves the segmentation fault.

I have attached our [minimum test](https://github.com/sebastianbergmann/phpunit/files/306545/ExampleTest.zip) to reproduce the segmentation fault. The mimum needed classes are 2 models with a relationship (in our case an hasMany relationship). The example contains 2 tests, the first test gets a segmentation fault when running the code coverage and the second doesn't. When not generating the code coverage both tests succeed.

We often use these relationships inside a query so we hope this bug can be fixed so we can generate our code coverage again.

**Comment by sebastianbergmann** [comment]
You have found a problem in the PHP runtime that leads to a segfault. An issue like this has to be reported at https://bugs.php.net/report.php using a minimal, self-contained, reproducing test case.

Please note that a test case that needs to be run through PHPUnit does not qualify as either "minimal" or "self-contained" when reporting bugs for the PHP runtime.

**Comment by arcanedev-maroc** [comment]
Hi @sebastianbergmann,

I've the same issue and it's only on PHP 7.0.x with laravel and i have no idea how to debug it.

You can check the Travis CI jobs for more details/repos to reproduce the issue: 

  * https://travis-ci.org/ARCANEDEV/LogViewer/builds/178321197
  * https://travis-ci.org/ARCANESOFT/Auth/jobs/173564144

Best regards
