### ISSUE TITLE
Add ChangeLog to Github releases

### ISSUE THREAD

**Issue by mbrodala** [sebastianbergmann/phpunit#2209]
It would be great if the changelog entries (or at least the most important changes) where added to Github releases.

Take the [latest 5.4.4](https://github.com/sebastianbergmann/phpunit/releases/tag/5.4.4) for example. The release message only says "Tag release", thus one has to navigate to [the ChangeLog](https://github.com/sebastianbergmann/phpunit/blob/5.4.4/ChangeLog-5.4.md) in order to learn what has changed.

**Comment by sebastianbergmann** [comment]
I do not use GitHub releases, sorry.

**Comment by mbrodala** [comment]
@sebastianbergmann Ah OK, that wasn't clear from the current state.

Could you extend the message you use for tagging releases in this case? For my projects I always mention the most important changes which has the benefit of a very compact ChangeLog via `git tag -n`. ;-)
