### ISSUE TITLE
Error getting mock of class using neted traits with common methods.

### ISSUE THREAD

**Issue by rafrsr** [sebastianbergmann/phpunit#2210]
> PHP Fatal error:  Cannot redeclare Mock_Talker_26b4fbdc::talk() in .... : eval()'d code on line 34

I got the above error when use neted traits with common methods.

````php
trait A
{
    public function talk()
    {
        echo 'A';
    }
}
````

````php
trait B
{
    use A {
        A::talk as talkA;
    }

    public function talk()
    {
        echo $this->talkA() . ', B';
    }
}
````

````php
class Talker
{
    use B;
}
````

````php
class TraitTest extends \PHPUnit_Framework_TestCase
{
    public function testTalker()
    {
        $this->getMockBuilder(Talker::class)->getMock();
    }
}
`````
The above example throw the above fatal error.

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-mock-objects](https://github.com/sebastianbergmann/phpunit-mock-objects) project.
