### ISSUE TITLE
Time Format on Output

### ISSUE THREAD

**Issue by jonrwads** [sebastianbergmann/phpunit#2213]
I am trying to use the output from the tests in a script to collect the results for some monitoring and statistics, however the output format for the time varies if it is < 1s or >1s.  This causes problems for statistical collection.  For example I get:

Time: 1 second
Time: 998 ms
Time: 1.2 seconds

Is there a way to standardize the formats?  If not maybe there should be.

Thanks for any help or suggestions on this issue.

**Comment by sebastianbergmann** [comment]
You want to use the raw timing information that is provided in the JUnit XML logfile.
