### ISSUE TITLE
phpunit echoes out html and dies during test 

### ISSUE THREAD

**Issue by ArlingtonHouse** [sebastianbergmann/phpunit#2215]
Hi I'm running 5.4.4 in the command line as part of  Symfony 2.7.14 project.  Here's the output:
![screen shot 2016-06-11 at 9 10 39 am](https://cloud.githubusercontent.com/assets/762607/15985238/e345be60-2fb4-11e6-9ed0-eb4a738ba217.png)
 
There are others struggling with this [issue--](http://stackoverflow.com/questions/36863856/symfony2-functional-test-prints-out-redirect-html-and-stops-test-execution) it may be a Symfony crawler bug but wanted to see what you thought and if it was possible for phpunit to provide an error message in this situation.  Thank you.

**Comment by sebastianbergmann** [comment]
Not a PHPUnit issue, sorry.
