### ISSUE TITLE
[Suggestion] Provide multiple exception classes in @expectedException announcement

### ISSUE THREAD

**Issue by remorhaz** [sebastianbergmann/phpunit#2216]
Exceptions, like any other objects, can implement interfaces and these interfaces can be used in `catch` statement. It would be great if `@expectedException` announcement will accept a list of exception classes (`|`-separated, for example).

In my project I follow typical pattern of SPL exception usage:
```php
namespace MyModule {

    interface Exception
    {
    }
    
    class RuntimeException
        extends \RuntimeException
        implements Exception
        {
        }
}
```
So, when I throw `\MyModule\RuntimeException`, it can be catched either as `\MyModule\Exception` by some `MyModule`-aware class or as `\RuntimeException` by SPL-aware class.

Now back to the problem. As for now, when I need to test that my expected exception is both `\MyModule\Exception` and `\RuntimeException` I have to copy-paste my test method two or even more times to match every exception class/interface I need:
```php
/**
 * @expectedException \MyModule\Exception
 */
public function testCodeThrowsMyModuleException()
{
    // Code
}

/**
 * @expectedException \RuntimeException
 */
public function testCodeThrowsSplException()
{
    // Same code
}
```
That's makes test cases messy and hard to maintain, and the amount of tests increases dramatically, and so does test execution time. Another hack is to match `\MyModule\RuntimeException` itself, but it's not the subject of test. I could forget to implement one of the interfaces in exception and my test won't catch it, for example, and so on.

The obvious and convenient solution is to  combine all matches in a single annotation:
```php
/**
 * @expectedException \MyModule\Exception|\RuntimeException
 */
public function testCodeThrowsException()
{
    // Code
}
```
This would make things much easier.

**Comment by jmauerhan** [comment]
`\MyModule\Exception|\RuntimeException` does not mean BOTH of those, it means either of those.

Have you tried this? 

```
/**
 * @expectedException \MyModule\Exception
* @expectedException \RuntimeException
 */
public function testCodeThrowsExceptions()
{
    // Code
}
```

Or using the `->expectException()` for each method in the code?

**Comment by remorhaz** [comment]
@jmauerhan, of course I've tried. Second annotation is just ignored. Using second `@expectedException` seems to be more convenient syntax, though.

**Comment by jmauerhan** [comment]
`setExpectedException` is deprecated, `expectException` is not. 

Anyway, here is a way that I found that works to do what you need. However, I would suggest just testing for the actual exception you want, and having a separate test for the specific exception that determines it extends/implements anything you want.

```
<?php

class ExampleTest extends PHPUnit_Framework_TestCase
{
    public function testThrowsExceptions()
    {
        try {
            $example = new MyExample();
            $example->throwException();
            $this->fail('No Exception was thrown');
        } catch (\Exception $e) {
            $this->assertInstanceOf('RuntimeException', $e);
            $this->assertInstanceOf('MyException', $e);
            return true;
        }
    }

}

Class MyExample
{
    public function throwException()
    {
        throw new \RuntimeException();
    }
}

Class MyException extends \RuntimeException
{

}
```

**Comment by remorhaz** [comment]
No, look on `expectException()`'s code - it just overwrites the internal member variable, so first call is ignored. Try/catch works for sure, but wasn't all that `@expectedException` thing an attempt to avoid try/catch ugliness while testing exceptions?

My idea is that PHPUnit should support testing several expected classes of exception. Not several exceptions - just several classes/interfaces of the same exception. I can implement it by myself if @sebastianbergmann likes the idea.

**Comment by sebastianbergmann** [comment]
I do not like the idea. A test should test one thing. Expecting different exceptions implies different things.

**Comment by prialgauskaslt** [comment]
My suggestion would be to use **dataProvider** and test different exceptions with different data passed to your class via **_iterable_**:

```
   /**
     * @test
     *
     * @param JsonResponse $response
     * @param string       $exception
     *
     * @throws ApiQueryRateLimitException
     * @throws ApiResponseErrorException
     *
     * @dataProvider provideInvalidResponses
     */
    public function testEnsureValidResponse_invalid(JsonResponse $response, string $exception): void
    {
        $this->expectException($exception);
        $dataSource = $this->newDataSource();
        $dataSource->ensureValidResponse($response);
    }

    /**
     * Provide invalid responses for the test case
     *
     * @return iterable
     */
    public function provideInvalidResponses(): iterable
    {
        yield 'Invalid JSON data' => [
            'response' => new JsonResponseStub(null),
            'exception' => ApiResponseErrorException::class,
        ];

        yield 'Rate limit reached error response' => [
            'response' => new JsonResponseStub(['error' => ['code' => 4]]),
            'exception' => ApiQueryRateLimitException::class,
        ];

        yield 'Invalid response with error' => [
            'response' => new JsonResponseStub(['error' => ['message' => 'bad-request']]),
            'exception' => ApiResponseErrorException::class,
        ];
    }
