### ISSUE TITLE
Code Coverage: coverage-html ignoring whole blocks of code

### ISSUE THREAD

**Issue by jaccoTopVintage** [sebastianbergmann/phpunit#2217]
For our project, we have configured (local) code coverage reports using the coverage-html writer.

To our surprise, we found that some methods are marked 100% covered, **but** when looking at the method in question, *no test appears to ever have touched the code block*:

![codecoverage_snip](https://cloud.githubusercontent.com/assets/17593826/16008037/0e72b7a6-3176-11e6-9a8e-642ea0196c91.jpg)

I've tried all possible combinations for `addUncoveredFilesFromWhitelist ` and `processUncoveredFilesFromWhitelist` (as described [on stackoverflow](http://stackoverflow.com/questions/29041254/phpunit-coverage-what-is-the-difference-between-adduncoveredfilesfromwhitelist#29042391)), but those settings, unfortunately, do not seem to affect the issue described.

a. Is this caused by misconfiguration on our side?
b. Is this a known bug?
c. something else?

Our big question is:
**How can we solve this issue?**

<br><br>
<sup>
**Attached:** Our phpunit.xml file
```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit backupGlobals="false"
         backupStaticAttributes="false"
         bootstrap="tests/bootstrap.php"
         colors="true"
         convertErrorsToExceptions="true"
         convertNoticesToExceptions="true"
         convertWarningsToExceptions="true"
         processIsolation="false"
         stopOnFailure="false">
    <testsuites>
        <testsuite name="Application Test Suite">
            <directory>./tests/</directory>
        </testsuite>
    </testsuites>
    <filter>
        <whitelist processUncoveredFilesFromWhitelist="false">
            <directory suffix=".php">app/</directory>
        </whitelist>
    </filter>
    <logging>
        <log type="coverage-html" target="report" lowUpperBound="45" highLowerBound="90"/>
    </logging>
</phpunit>
```
</sup>

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project.

**Comment by jaccoTopVintage** [comment]
My apologies. I'll reopen this issue on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project.
