### ISSUE TITLE
Class 'Webmozart\Assert\Assert' not found in DocBlock.php

### ISSUE THREAD

**Issue by Soullivaneuh** [sebastianbergmann/phpunit#2219]
Related failing job with PHPUnit 5.4.5: https://travis-ci.org/sonata-project/SonataCoreBundle/jobs/137804289#L534

The `.phar` file is used.

**Comment by Soullivaneuh** [comment]
Thanks! :+1:

**Comment by sebastianbergmann** [comment]
Thank you for bringing this to my attention.
