### ISSUE TITLE
Only run tests that match two or more groups

### ISSUE THREAD

**Issue by ghost** [sebastianbergmann/phpunit#2220]
I asked a [question](http://stackoverflow.com/questions/36738631/running-tests-which-match-multiple-groups) a while ago about being able to run tests that only match multiple groups. I think it got misinterpreted so I have reworded it. However I think the answer is a no.

Therefore I think it would be a nice feature to implement an ability to only run tests where the groups specified in the command are mutually inclusive to the groups labeled on a test. (Mutually inclusive may not be correct terminology - my maths is rusty)

**Comment by sebastianbergmann** [comment]
I would consider a pull request that implements this but won't implement it myself.

**Comment by carcinocron** [comment]
I would love for `--group unit+controllers` to be implemented and behavior intuitively different from `--group unit,controllers`.
