### ISSUE TITLE
PHPUnit hides exceptions

### ISSUE THREAD

**Issue by KKSzymanowski** [sebastianbergmann/phpunit#2222]
Hi.

Using version 4.8.26, I have noticed, that phpunit hides thrown exception from a user, even in --verbose or --debug mode.

What I did was, while testing Laravel app I created a DataProvider as follows:

``` php
public function userDataProvider()
{
    return [
        [User::find(1)]
    ];
}
```

I added necessary annotation to the test method, but each time I ran the tests, message was "No tests executed".

I dug through the source code to find `Util\Test::getDataFromDataProviderAnnotation()` method.
It was called properly, but after this line

``` php
$data = $dataProviderMethod->invoke($object);
```

there was some hidden transfer of control and no line after that seemed to execute nor there was any message.

When I did:

``` php
try {
    $data = $dataProviderMethod->invoke($object);
} catch(\Exception $e) {
    echo($e->getMessage());
}
```

following text showed up: `A facade root has not been set.`. Of course that's something I need to fix, not you, but the annoying thing was, I needed to dig through the source code to get that exception message.

The peculiar thing is, when I put something like `return $foo;` and foo has not been declared or `return new Foo` and there's not class named Foo, I get a proper notice or fatal error.
However when at the top of `DataProvider` method I write `throw new Exception;` I get literally nothing except "No tests executed!".

Could you please add some better error handling to at least this particular case?
Or maybe I was doing it completely wrong. I can provide you with a complete example if that would be helpful.

**Comment by giorgiosironi** [comment]
I had a similar error while having exception or catchable syntax errors of other files (in PHP 7) in data providers. I identified the responsible code in https://github.com/sebastianbergmann/phpunit/blob/5.6/src/Framework/TestSuite.php#L524 which shows the exception message but not where it comes from, I think I'll open a PR adding line and file to the warning.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by KKSzymanowski** [comment]
Because PHPUnit 4.* is no longer supported I tried to reproduce this on 5.* and 6.* and failed.
I'll close this for now and if I come across the same bug I'll reopen with a proper report.
