### ISSUE TITLE
how about dataProvider method have codeCoverageIgnore by default.

### ISSUE THREAD

**Issue by yjqg6666** [sebastianbergmann/phpunit#2229]
if can, it's better that this feature is disabled by default and can be enabled by configuration file. Most of our dataProvider just return some array of array, no other logic involved. Oft. these methods are ignored by add annotation codeCoverageIgnore. it's good or not. Discussions are welcomed.

**Comment by jmauerhan** [comment]
Data providers should be ignored from coverage anyway because all of your tests should be ignored. You may need to give an example of what you mean because as is this doesn't make sense

**Comment by yjqg6666** [comment]
Ignore this. @jmauerhan thanks for ur reply.  

In configuration file,  directory is misconfigured. My bad.

>     <filter>
>         <whitelist addUncoveredFilesFromWhitelist="true">
>             <directory suffix=".php">test</directory>
>         </whitelist>
>     </filter>
