### ISSUE TITLE
PHPUnit_Framework_MockObject_Generator generates a lot of Text_Template calls

### ISSUE THREAD

**Issue by willemstuursma** [sebastianbergmann/phpunit#2232]
About 2.5% of our test suite time is spent creating `Text_Template` objects and executing the various `file_exists()`, `file_get_contents()` functions in the constructor of this class.

This could easily be resolved by keeping a few `Text_Template` objects in private static properties within the `PHPUnit_Framework_MockObject_Generator` class.

Would you be willing to accept a pull request that implements this change, and add it to the 5.3 branch? If so, I will arrange for it.

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-mock-objects](https://github.com/sebastianbergmann/phpunit-mock-objects) project.

And yes, a pull request would be welcome.

**Comment by willemstuursma** [comment]
Sorry! I'll create a PR there.
