### ISSUE TITLE
[FR] Method to write on unaccessible properties

### ISSUE THREAD

**Issue by rentalhost** [sebastianbergmann/phpunit#2233]
Currently we have a method that allows to read unaccessible properties by using `static::readAttribute($classOrObject, $attributeName)`.

I think that is time to implement a method that allows to write, like `static::writeAttribute($classOrObject, $attributeName, $value)`. When `$classOrObject` is a class name (string) it'll write as a static property, else as a dynamic property.

It's useful when you just need to reset some class property (generally, statics) to help to cover code fully, but it can allow some hackish methods on code, as simulates some environment conditions.

**Comment by sebastianbergmann** [comment]
Definitely not; I would rather remove `readAttribute()` etc. than expand on this functionality.
