### ISSUE TITLE
Please tell us when XDebug is NEEDED.

### ISSUE THREAD

**Issue by YamiOdymel** [sebastianbergmann/phpunit#2234]
I was trying to generate the code coverage xml file,

`junit.xml` is fine, but I just don't know why the `clover.xml` didn't generate,

and **I realized that I have to install XDebug, I wasted two days for this**, 

When I added `<log type="coverage-clover" ....>` **PHPUnit didn't tell me to install XDebug when there was no XDebug installed**,

please add the error message about this please.

**Comment by sebastianbergmann** [comment]
PHPUnit does tell you:
```
$ phpunit -c build                 
PHPUnit 5.5-g89a3277 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.0.8
Configuration: /usr/local/src/money/build/phpunit.xml
Error:         No code coverage driver is available

............................................                      44 / 44 (100%)

Time: 27 ms, Memory: 4.00MB

OK (44 tests, 70 assertions)
```
As Xdebug is not the only source of code coverage information supported, "**No code coverage driver is available**" is the best possible error message, IMHO.

**Comment by YamiOdymel** [comment]
I was using the following command though ..
```
$ phpunit -c phpunit.xml
...........................................      45 / 45 (100%)

Time: 370 ms, Memory: 12.00MB

OK (45 tests, 1 assertion)

$ ls build/logs
junit.xml

$ php coveralls.phar -v -x build/logs/clover.xml                                                             
  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  coverage_clover XML file is not readable                          
```
