### ISSUE TITLE
Exceptions in tearDown should affect $this->getStatus()

### ISSUE THREAD

**Issue by rtwo** [sebastianbergmann/phpunit#2236]
Currently if a Tests throws an Exception in its tearDown function $this->getStatus() will still be 0 and i.e. TestListeners would assume the Tests to be successful.

The following Code should be moved down until after the last occurrence of $_e = ...

https://github.com/sebastianbergmann/phpunit/blob/master/src/Framework/TestCase.php#L971

**Comment by sebastianbergmann** [comment]
The link is no longer pointing to the correct line. Can you please send a pull request that implements the change you propose? Thanks!

**Comment by sebastianbergmann** [comment]
@rtwo ping?

**Comment by rtwo** [comment]
Sorry, I missed your first reply. I am a bit busy atm but I will try to look into it.

**Comment by ekharchenko-avito** [comment]
This patch broke our cleanup logic based on knowledge of test status in tearDown method 😞

**Comment by epdenouden** [comment]
I poked around in the tearDown logic, I'll have a look
