### ISSUE TITLE
Rename PHPUnit_Runner_Filter_GroupFilterIterator to PHPUnit_Runner_Filter_Group or Group.php to GroupFilterIterator.php.

### ISSUE THREAD

**Issue by vtsao** [sebastianbergmann/phpunit#2239]
Currently PHPUnit_Runner_Filter_GroupFilterIterator doesn't conform to PSR-0 as its classname suffix of "GroupFilterIterator" doesn't match its file name of "Group.php".

This means it's not PSR-0 compatible and anybody who's not using or cannot use Composer writing their own autoload.php file needs a special case to ensure this file is required (it works with Composer b/c Composer generates a classmap for non PSR-0/4 compliant code).

We should either rename PHPUnit_Runner_Filter_GroupFilterIterator to PHPUnit_Runner_Filter_Group or Group.php to GroupFilterIterator.php.

This should be fairly straightforward as there aren't many files affected by this renaming.

**Comment by sebastianbergmann** [comment]
PHPUnit does not follow PSR-* and only supports autoloading based on class maps.

**Comment by vtsao** [comment]
Well it's pretty much compliant with PSR-0 with the exception of the naming of this one file b/c of the PSR-0 backward compatibility with old school PEAR-style pseudo-namespacing.

Even if you don't want to explicitly state it supports PSR-0, the naming of `PHPUnit_Runner_Filter_GroupFilterIterator` is still inconsistent with the other files in that folder.

Both `Include` and `Exclude` file iterators don't have the suffix `FilterIterator`.

`PHPUnit_Runner_Filter_GroupFilterIterator` should be renamed to `PHPUnit_Runner_Filter_Group` for consistency (dropping the `FilterIterator` suffix).

Obviously it's ultimately up to you, but is there a reason you wouldn't want to rename this?
