### ISSUE TITLE
No autocompletion of assert* methods with PHPStorm 2016.2

### ISSUE THREAD

**Issue by AllenJB** [sebastianbergmann/phpunit#2243]
I realize this is a tool-specific issue and I'm aware of the reasons as per #1914, but thought you may wish to be aware of this issue anyway due to the specific nature of PHPUnit.

As of PHPStorm 2016.2, static methods are filtered when auto-completing from a non-static context. This obviously breaks the recommended / documented way of writing tests for PHPStorm users.

Related issues:
https://github.com/sebastianbergmann/phpunit/issues/1914
https://youtrack.jetbrains.com/issue/WI-32493

**Comment by sebastianbergmann** [comment]
Sorry, but this is a PhpStorm issue.

**Comment by eclipxe13** [comment]
OT: Yes, it is a PhpStorm issue, just call autocomplete (Control + Space) twice and it will show static methods also.

**Comment by TomasVotruba** [comment]
@eclipxe13 Thanks a lot for a solution!

**Comment by thinkingmedia** [comment]
@eclipxe13 I wish this was added to the PhpUnit docs!

**Comment by kokspflanze** [comment]
@thinkingmedia

it should be already fixed, see https://youtrack.jetbrains.com/issueMobile/WI-32530

**Comment by ejazrasool** [comment]
@eclipxe13 
Thanks a lot for the solution.

As a note, one can also write

`self::assertEquals(...` or `static::assertEquals(...`
