### ISSUE TITLE
[4.8] Passing test omitted from CLI output when after dependency-induced skip

### ISSUE THREAD

**Issue by omegastealth** [sebastianbergmann/phpunit#2248]
A test skipped because of a failing dependency is causing the next test run to be hidden in the CLI output.

PHPUnit version 4.8.26, PHP version: 5.5.36

```
<?php
class Test extends \PHPUnit_Framework_TestCase
{
    public function test1() { $this->assertTrue(false); } //Deliberarely Fail
    /**
     * @depends test1
     */
    public function test2() { $this->assertTrue(true); } //Skip due to failing dependency
    public function test3() { $this->assertTrue(true); } //<--- Runs (as evidenced by --debug output), but not visible in output
    public function test4() { $this->assertTrue(true); } //Pass, visible in output as '.'
}
```

Observed output:

```
$ php ./phpunit --debug --verbose test.php
PHPUnit 4.8.26 by Sebastian Bergmann and contributors.

Runtime:        PHP 5.5.36


Starting test 'Test::test1'.
FS
Starting test 'Test::test3'.

Starting test 'Test::test4'.
.

Time: 49 ms, Memory: 3.75MB

There was 1 failure:

1) Test::test1
Failed asserting that false is true.

/home/dev/DefaultWorkspace/PHPUnitBugTest/test.php:4

--

There was 1 skipped test:

1) Test::test2
This test depends on "Test::test1" to pass.

FAILURES!
Tests: 3, Assertions: 3, Failures: 1, Skipped: 1.
```

Note that line 10 of the output, where test3's pass indicator should be, is blank.  Similarly passing test test4 is indicated correctly on line 12.

This is only the case when test3 passes - if test3 contained `assertTrue(false)`, `markTestIncomplete()` or `markTestSkipped()` the test is correctly shown in the CLI output as 'F', 'I' or 'S' respectively.  Likewise, if test2's `@depends` annotation is removed, but is explicitly skipped via `markTestSkipped()`, test3 is shown correctly regardless of its result.

**Comment by dsas** [comment]
I can reproduce this in phpunit 5.1.3 It appears to be the same as #843 (PHPUnit 3.6.10)

**Comment by sebastianbergmann** [comment]
PHPUnit 4.8 is no longer supported. Please open a new ticket if the error is still present in PHPUnit 5.7 / PHPUnit 6.0.

**Comment by dsas** [comment]
Just tested in phpunit 6.0.5 using php 7.0.13 and it's fixed anyway.
