### ISSUE TITLE
Adding arrayEquals assertion

### ISSUE THREAD

**Issue by gabber12** [sebastianbergmann/phpunit#2251]
I frequently want to check if two arrays are equal. This is mostly an order-insensitive assertion, but order sensitive assertion might also be useful.

Does this seem like a valuable feature?.I can implement this without much help.

**Comment by stevenbitner** [comment]
I believe https://phpunit.de/manual/current/en/appendixes.assertions.html#appendixes.assertions.assertEquals (Example A.17 - Usage of assertEquals() with arrays) already works in that manner. Perhaps I'm missing something.

**Comment by gabber12** [comment]
Well assertEquals checks for exact equal arrays. I was hoping more of arraySimilar functionality.
A less strict version of assertEquals. Where assertion like below would be true.

`$this->assertEquals([0=>1, 1=>2], [0=>1, 2=>2]);`

I understand in PHP arrays are associative but i just want to check if the keys are equal.
i could use array_keys here, but may be a simple function like arraySimilar would be more convenient.

**Comment by sebastianbergmann** [comment]
Using `array_keys()` seems like the right thing to do here.
