### ISSUE TITLE
@requires isn't inherited from parent class

### ISSUE THREAD

**Issue by johnbillion** [sebastianbergmann/phpunit#2255]
Given a test case that inherits a parent class containing a `@requires x` docblock statement, the `@requires` requirement isn't inherited or enforced.

Example:

``` php
/**
 * @requires extension fakeextension
 */
abstract class Base_Test_Class extends \PHPUnit_Framework_TestCase {}

class My_Test_Class extends Base_Test_Class {
    public function testTrue() {
        $this->assertTrue( false );
    }
}
```

The tests in `My_Test_Class` should be skipped due to the non-existence of the `fakeextension` extension, but they're not because the `@requires` requirement on the parent class isn't inherited.

**Comment by sebastianbergmann** [comment]
This is intentional as none of the annotations supported by PHPUnit are inherited from a parent class to a child class.
