### ISSUE TITLE
Listener: add text to error text?

### ISSUE THREAD

**Issue by MCMic** [sebastianbergmann/phpunit#2258]
Hello,

I wanted to create a modified version of PHPUnit_Extensions_Selenium2TestCase_ScreenshotListener to add a link to the screenshot in the error text.
But I can’t find any way to alter output using a Listener, it seems printf just outputs to the terminal, and I’m not sure if a listeners methods can return something and how it should be formatted?
How can a Listener add some text to the test result?

**Comment by sebastianbergmann** [comment]
Listeners are for listening. They should not modify anything.

**Comment by MCMic** [comment]
Then how can I add a link to the screenshot in the error text?

**Comment by sebastianbergmann** [comment]
I do not know anything about `PHPUnit_Extensions_Selenium2TestCase_ScreenshotListener` so I cannot help you. Please bring this up with the vendor of your PHPUnit extension.

**Comment by MCMic** [comment]
This is a more general question about how to add information to tests results.
This listener create a screenshot on failure which is quite useful but I have to search for which file match which failed test myself. It would be useful if I could expand the failed test text so that it contains the filename (which is generated from easily available information like test name and such things).

**Comment by sebastianbergmann** [comment]
A listener is a listener. It must only listen. If it does something more then that is wrong.

It is a mistake in the implementation of PHPUnit that listeners can manipulate `PHPUnit\Framework\Test` object. I should have fixed this mistake a long time ago. I plan to correct this for PHPUnit 7 (see #2477).

**Comment by MCMic** [comment]
You already said this, my question is what can I do to alter the test result text. I won’t use a Listener if it can’t do it, is there an other way mechanism capable of altering the text output?
