### ISSUE TITLE
Specify a group of tests to run in process isolation

### ISSUE THREAD

**Issue by mcmillenb** [sebastianbergmann/phpunit#2259]
In PHPUnit, you can annotate a test-case class (@runTestsInSeparateProcesses) or a test function (@runInSeparateProcess) to run tests in process isolation. There is also a setting in the phpunit.xml config file (processIsolation = "true") to run all tests in separate processes.

I have a group of test-case classes which all inherit from a database-related abstract test class that I need to run in process isolation. But annotations aren't inherited from parent classes. 

It would be nice if there was a way for me to mark these test-case classes to run in separate processes by @group, or directory, or some other specifier, without having to mark each test-case class with @runTestsInSeparateProcesses.

**Comment by sebastianbergmann** [comment]
Sorry for taking so long to respond. I do not think that this would be useful.

**Comment by FinesseRus** [comment]
@sebastianbergmann I face the same issue. I really need a way make a bunch of test run in isolated processes.
