### ISSUE TITLE
assertEquals doesn't consider "0" and false to be equal

### ISSUE THREAD

**Issue by alnorth** [sebastianbergmann/phpunit#2260]
I had understood that assertEquals was meant to be equivalent to `==`. However, `"0" == false` is true and `$this->assertEquals('0', false);` on 5.4.8 gets me `Failed asserting that false matches expected '0'.`

Is my understanding wrong? Where can I find full documentation on what is equal and what isn't?

**Comment by stevenbitner** [comment]
You can dig further if you please, but you'll see in https://github.com/sebastianbergmann/phpunit/blob/master/src/Framework/Constraint/IsEqual.php that the first part of the evaluate function is a strict equality comparison..

**Comment by alnorth** [comment]
Yeah, but the comment makes clear that comparison's just a shortcut. Anyway, if it was just `===` then what's the distinction between `assertEquals` and `assertSame`?

**Comment by stevenbitner** [comment]
It's all based on the variable types and whether of not each comparator accepts() the values given. You'd need to check each comparator file in https://github.com/sebastianbergmann/comparator/tree/master/src for the answer to that. The comparator types checked are listed here https://github.com/sebastianbergmann/comparator/blob/master/src/Factory.php#L31

**Comment by alnorth** [comment]
I'm happy to dig into the code in Comparator and see what's going on. Before doing that though I'd like some sense of whether this is the expected behaviour or not. Should `$this->assertEquals('0', false);` pass or fail? The documentation isn't clear. Is this a bug, or is everything fine and I just need to cope with it in my own code?

**Comment by alnorth** [comment]
Yeah, but casting `'0'` to boolean would give `false`, and in my case I'm more bothered about boolean values than I am about string values. I guess someone else's use case will be different, but it'd be good to have better documentation on this. Coming at it fresh it does seem rather arbitrary that `$this->assertEquals('3', true);` fails where `$this->assertEquals(3, true);` passes, given how lax PHP is about type coercion in its own `==`. It'd be good to add some notes to https://phpunit.de/manual/current/en/appendixes.assertions.html about where the behaviour differs from PHP's standard `==` equality operator. My mental model of "`assertSame` is `===` and `assertEquals` is `==`" was obviously too simplistic.

Anyway, I guess I'll just add a boolean cast to my code and get on with my life 😄

**Comment by stevenbitner** [comment]
If what you want is ==, you can force that behavior as well with `$this->assertTrue('0' == false);`

**Comment by alnorth** [comment]
True. Thanks for your help.

**Comment by IanVS** [comment]
According to according to https://github.com/sebastianbergmann/phpunit/issues/2865#issuecomment-345044491, it seems that `assertEquals` now uses `==` (or has always?  I can't tell if it's changed, based on the changelogs).  I'm just leaving this comment here to help future searchers, as I'm having a hard time understanding the details myself.
