### ISSUE TITLE
Missing support for Errors in PHP7.0

### ISSUE THREAD

**Issue by khelle** [sebastianbergmann/phpunit#2263]
PHPUnit does not support throwing errors in mocks or expecting errors. There should be separate methods added to throw and expect errors to be able to test logic that bases on using Errors in PHP7.0.

Example of code not being able to fully test right now:
```
try {
    $model->doSomething();
}
catch (Error $err) {
    // do smth
}
catch (Exception $ex) {
    // do smth else
}
```

What can be mocked right now:
```
$model->expects($this->once())->method('doSomething')->will($this->throwException($exception));
```

What should also be able to be mocked:
```
$model->expects($this->once())->method('doSomething')->will($this->throwError($error));
```

Also, annotation "expectedError" should be added and all additional utils to support Errors.

**Comment by GrahamCampbell** [comment]
What PHPUnit version are you using please? This works fine for me on PHPUnit 5.5.0.

**Comment by sebastianbergmann** [comment]
No feedback, closing.
