### ISSUE TITLE
Allow custom CLI options

### ISSUE THREAD

**Issue by andig** [sebastianbergmann/phpunit#2271]
This is a follow-up after grooming https://github.com/sebastianbergmann/phpunit/issues/634. The request is the same: please allow custom command line options to phpunit that can be read by test cases. There is a ton of stackoverflow questions on the same behalf. The often promoted `ENV=setting phpunit` one-liners don't work on Windows and are not portable.

Sample implementation:

```
phpunit.phar -c /path/to/phpunit.xml -- MyTest --custom-option option-value
```

Sample comment:

> It would be very useful if you could remove the check about the "unrecognized option", at the moment I have to rely on environment variables if I want to pass any option to my tests

**Comment by sdudziak** [comment]
@andig do you have any suggestions how it should be implemented? Right now handling arguments is closed type one: it requires to add another `if` statement, which is bad. Have you tried something already, which can help to add this enhacement?

**Comment by andig** [comment]
@sdudziak 

> do you have any suggestions how it should be implemented

Not really. But looking at https://github.com/sebastianbergmann/phpunit/pull/1733 and the associated discussion this would be sufficient for me and apparently also sebastian. Prefixing custom options with `--custom-` could also work- anything would be welcome imho.

**Comment by sdudziak** [comment]
@andig 
I have some idea.
I think each option should be separate class, which implements some interface. The base set of them could be hardcoded, but also you can add your own which should be defined in `phpunit.xml` file in some section. During the runtime of the phpunit these options can be parsed easly. This is big change, but can be done step by step, starting from custom option handler and then by moving one by one of base set. 
@sebastianbergmann can you tell me please if this not on which you're currently working in one of the major releases ?

**Comment by sdudziak** [comment]
Ok, I'll try to handle this

**Comment by sebastiandedeyne** [comment]
Any chance of a solution for custom CLI options to ship in 6.0?

**Comment by sebastianbergmann** [comment]
Depends on how much time I can spend on PHPUnit until February.

**Comment by jscodefix** [comment]
I have a proposed solution for which I would like to get an approval to implement, which is to:
- Add a command-line option, as --global, such that the global variable can then be accessed in the unit test code.

For example:
`$ phpunit -v --global myInt=5 --global myBool=true --global myStr="good stuff" --global myArr='["foo"=>"bar"]' MyTest`

The proposed _command line option globals_ would be similar to, **but override**, the globals specified in the phpunit.xml configuration file (using <php><var>).

**Comment by jscodefix** [comment]
I have a proposed solution for which I would like to receive approval to implement:
- Add a command-line option, --global, for which the user can add a PHP global variable that is accessible within the unit test code.

For example:
`phpunit -v --global myInt=5 --global myStr="good stuff" --global myBool=true --global myArr='["foo"=>"bar"]' myTest`

The global variables provided by the _command line global option_ are similar to, but **override**, the global variables provided by the phpunit.xml configuration file (i.e. < php > < var > ).

**Comment by jscodefix** [comment]
I have moved forward with the implementation as described above.  One minor change is that, the "--global" long-option will not be feasible, since the long-option parsing method [Getopt::parseLongOption()] does not allow for an equal sign ("=") in the user supplied command line option.  Instead, the "-g" short option will be implemented.

**Comment by jscodefix** [comment]
I have moved forward with the implementation as described above.  One minor change is that, the "--global" long-option will not be feasible, since the long-option parsing method [Getopt::parseLongOption()] does not allow for an equal sign ("=") in the user supplied command line option.  Instead, the "-g" short option will be implemented.

**Comment by jscodefix** [comment]
This is the command line test case that I am developing to:

```$ phpunit -g myGlobalBool=true -g myGlobalInt=99 -g myGlobalFloat=3.3 -g myGlobalString="mysql:host=y;dbname=z" -g myGlobalHash="['bar'=>'baz']" -g myGlobalNull=null -g myGlobalEmpty= GlobalsTest.php```

where GlobalsTest.php contains:
```
public function testGlobalsAssignments()
{
    global $myGlobalBool;   // defaults to null if not defined, so no need to first test for existence below
    global $myGlobalInt;
    global $myGlobalFloat;
    global $myGlobalString;
    global $myGlobalHash;
    global $myGlobalNull;
    global $myGlobalEmpty;

    //fwrite(STDERR, print_r( $GLOBALS, true ));    // debug output $GLOBALS array

    if (!isset($GLOBALS['myGlobalFromXml'])) {
        $GLOBALS['myGlobalFromXml'] = null; // ensure default assignment, since not declared as global above
    }

    // check that phpunit.xml has expected global defined
    $this->assertNotNull($GLOBALS['myGlobalFromXml'], "Expecting a global in phpunit.xml defined as: myGlobalFromXml");

    // check that command line has expected global defined (eg. --g myGlobalBool=true)
    $this->assertTrue($myGlobalBool, "Expecting a global to be defined: -g myGlobalBool=true");

    $this->assertEquals($myGlobalInt, 99, "Expecting a global to be defined: -g myGlobalInt=99");

    $this->assertEquals(round($myGlobalFloat, 1), round((float)3.3, 1), "Expecting a global to be defined: -g myGlobalFloat=3.3");

    $this->assertEquals($myGlobalString, "mysql:host=y;dbname=z", "Expecting a global to be defined: -g myGlobalString=\"mysql:host=y;dbname=z\"");

    $this->assertEquals($myGlobalHash["bar"], "baz", "Expecting a global to be defined: -g myGlobalHash='[\"bar\"=>\"baz\"]'");

    $this->assertNull($myGlobalNull, "Expecting a global to be defined: -g myGlobalNull=null");

    $this->assertEmpty($myGlobalEmpty, "Expecting a global to be defined: -g myGlobalNull=");
}
```

**Comment by jscodefix** [comment]
Submitted a pull request (of branch Issue 2271/allow custom cli options).

Adds new command line option (-g) that enables the user to assign global variables (... well, from the command line).  The highlights are:
- implemented with eval() in the Command class
- includes a revision to the command line help output (and revised .phpt tests of the output)
- includes a unit test of the new Command::handleGlobals() method (using reflection to test protected method)
- the command line option globals are similar to, but **override**, the globals specified in the phpunit.xml configuration file (using < php >< var >)

Example usage:
```$ phpunit -v -g myInt=5 -g myBool=true -g myValue=null -g myStr="good stuff" -g myArr='["foo"=>"bar"]' MyTest```

**Comment by sebastianbergmann** [comment]
Sorry for forgetting about this. I would consider a pull request that implements this.

**Comment by sebastianbergmann** [comment]
Nevermind, I just saw #2738.

**Comment by sebastianbergmann** [comment]
I understand the problem you are trying to solve but I think that neither more generic, custom CLI options nor a specific CLI option for setting global variables is the right solution.
