### ISSUE TITLE
--testsuite <pattern> is not an actual pattern filter

### ISSUE THREAD

**Issue by gerardroche** [sebastianbergmann/phpunit#2273]
`--testsuite <pattern> Filter which testsuite to run.`

`<pattern>` is not actually matched as a pattern by PHPUnit.

For example:

```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit>

    <testsuites>
        <testsuite name="unit">
            <directory>test/unit_tests</directory>
        </testsuite>
        <testsuite name="integration">
            <directory>test/integration_tests</directory>
        </testsuite>
    </testsuites>

</phpunit>
```

```
$ phpunit --testsuite=unit
```

Will run `test/unit_tests/*`.

```
$ phpunit --testsuite=integration
```

Will run `test/integration_tests/*`.

However.

```
$ phpunit --testsuite="unit|integration"
$ phpunit --testsuite="(unit|integration)"
$ phpunit --testsuite="/(unit|integration)/"
```

No variation of the above works.

**Comment by sdudziak** [comment]
@sebastianbergmann I would love to take care about this issue.

**Comment by sdudziak** [comment]
@gerardroche which version of PHPUnit have you used for that ?

**Comment by gerardroche** [comment]
@sdudziak Version ~4.0. I think it's the same for ~5.0 too.

**Comment by sdudziak** [comment]
@gerardroche  Yes, I agree.
There is just a simple comparison to check if the testsuite match. However I think it will be achievable to change this behavior to `<pattern>` .

**Comment by sdudziak** [comment]
@gerardroche I think I solved it. Can you check the code under the #2281 MR and give me some feedback?

**Comment by stepashka69** [comment]
I spent a lot of time to understand what is wrong with testsuite pattern in CLI before I found this issue. That's nice that someone fixed it. 
Are there any plans to include it to PHPUnit any soon?

**Comment by sebastianbergmann** [comment]
Closing after 80754cf323fe96003a2567f5e57404fddecff3bf and e60ba3b25f597a97cb26723ce36950c5c7002d2e.
