### ISSUE TITLE
PHPUnit 5.5.2 on Ubuntu issues deprecation warnings for methods not used in test case.

### ISSUE THREAD

**Issue by victorbstan** [sebastianbergmann/phpunit#2276]
Console output:

```
$ phpunit -c app/
PHPUnit 5.5.2 by Sebastian Bergmann and contributors.

......W                                                             7 / 7 (100%)

Time: 171 ms, Memory: 18.50MB

There was 1 warning:

1) XXX\Bundle\UserAccountBundle\Tests\Form\Type\RegistrationTypeTest::testSubmitValidData
PHPUnit_Framework_TestCase::getMock() is deprecated, use PHPUnit_Framework_TestCase::createMock() or PHPUnit_Framework_TestCase::getMockBuilder() instead
```

`getMock` is not used anywhere in the project file structure... 

The test area that I suspect is relevant is this:

```php
$validatorStub = $this->createMock('\Symfony\Component\Validator\Validator\ValidatorInterface');
		$validatorStub->expects($this->once())
					  ->method('validate')
					  ->will($this->returnValue(new ConstraintViolationList()));
```

I expected not to see the deprecation warning.

Alternative usage indicated using `->getMock()` even in the documentation https://phpunit.de/manual/current/en/test-doubles.html:

```php
$validatorStub = $this->getMockBuilder('\Symfony\Component\Validator\Validator\ValidatorInterface')
							  ->disableOriginalConstructor()
							  ->disableOriginalClone()
							  ->disableArgumentCloning()
							  ->disallowMockingUnknownTypes()
							  ->getMock();

		$validatorStub->expects($this->once())
					  ->method('validate')
					  ->will($this->returnValue(new ConstraintViolationList()));
```

Deprecation warning still exists. Why does the documentation show deprecated usage for current stable version? What is the correct non-deprecated way to achieve the same thing?

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-mock-objects](https://github.com/sebastianbergmann/phpunit-mock-objects) project.
