### ISSUE TITLE
Tests stop on php notices when running under HHVM in php7 compatibility mode

### ISSUE THREAD

**Issue by photodude** [sebastianbergmann/phpunit#2278]
Running php unit under `HHVM in php7 compatibility mode` I'm having the [tests halt on cases where phpunit runs into php4 style constructors](https://travis-ci.org/photodude/joomla-cms/jobs/155658477) with the error `Methods with the same name as their class will not be constructors in a future version of PHP` 

This [issue does not happen with testing under PHP7](https://travis-ci.org/joomla/joomla-cms/jobs/155677735), just when testing under HHVM in PHP7 mode
I've heard that the tests might be halting because "PHPUnit converts notices to exceptions." and that's somehow killing the tests, but I'm not sure if that is accurate.

**Comment by sebastianbergmann** [comment]
Sounds like an issue with HHVM to me. And, to be honest, I do not care about HHVM anymore.

**Comment by photodude** [comment]
Sorry to hear that you no longer care about HHVM as a platform for PHPunit to support. That may kill HHVM for our projects since we will no longer have a unit testing option to validate with.

Is there anything specific that is pushed you to move on from HHVM?
