### ISSUE TITLE
Conflict with phpunit Symfony/Yaml component in Symofony2 projects

### ISSUE THREAD

**Issue by illibejiep** [sebastianbergmann/phpunit#2285]
PHPUnit has diffirent version of the symofony-yaml component and doesn't work properly with Symfony framework. The component is loaded by simple 'require' command and phpunit fails with the "duplicate class declaration" error if an appropriate component was loaded before.

**Comment by sebastianbergmann** [comment]
Will be fixed by #2015. Until then do not use the PHAR in a situation like that.
