### ISSUE TITLE
Missing extension dependencies in composer.json

### ISSUE THREAD

**Issue by vbashkirtsev** [sebastianbergmann/phpunit#2288]
Recently I have created the tools which checks list of extensions in composer.json against actually used extensions in code. This tool is available on packagist.org as **logics/extcheck** . I have run it against PHPUnit and it gave me the following:

```
Following extensions are missing in require section of composer.json:

  ext-SPL
    Used RuntimeException in /home/mega/PHPUnit/phpunit/src/Runner/Exception.php:14
    Used SplObjectStorage in /home/mega/PHPUnit/phpunit/tests/_files/DataProviderDebugTest.php:33

  ext-date
    Used time in /home/mega/PHPUnit/phpunit/src/Util/PHP.php:328
    Used DateTime in /home/mega/PHPUnit/phpunit/tests/Framework/ConstraintTest.php:813
    Used DateTimeZone in /home/mega/PHPUnit/phpunit/tests/Framework/ConstraintTest.php:813
    Used DateTime in /home/mega/PHPUnit/phpunit/tests/Framework/ConstraintTest.php:814
    Used DateTimeZone in /home/mega/PHPUnit/phpunit/tests/Framework/ConstraintTest.php:814

  ext-Reflection
    Used ReflectionClass in /home/mega/PHPUnit/phpunit/src/TextUI/TestRunner.php:91
    Used ReflectionClass in /home/mega/PHPUnit/phpunit/src/TextUI/TestRunner.php:129
    Used ReflectionClass in /home/mega/PHPUnit/phpunit/src/TextUI/TestRunner.php:136
    Used ReflectionClass in /home/mega/PHPUnit/phpunit/src/TextUI/TestRunner.php:143
    Used ReflectionClass in /home/mega/PHPUnit/phpunit/src/TextUI/TestRunner.php:246
    Used ReflectionClass in /home/mega/PHPUnit/phpunit/src/TextUI/TestRunner.php:889

  ext-mbstring
    Used mb_convert_encoding in /home/mega/PHPUnit/phpunit/src/Util/String.php:29

  ext-xml
    Used utf8_encode in /home/mega/PHPUnit/phpunit/src/Util/String.php:31

  ext-tidy
    Used tidy_repair_file in /home/mega/PHPUnit/phpunit/src/Util/Printer.php:91

  ext-libxml
    Used libxml_use_internal_errors in /home/mega/PHPUnit/phpunit/src/Util/XML.php:65
    Used libxml_get_errors in /home/mega/PHPUnit/phpunit/src/Util/XML.php:84
    Used libxml_use_internal_errors in /home/mega/PHPUnit/phpunit/src/Util/XML.php:88

  ext-Phar
    Used Phar in /home/mega/PHPUnit/phpunit/src/TextUI/Command.php:972

Following extensions are missing in require-dev section of composer.json:

  ext-PDO
    Used PDO in /home/mega/PHPUnit/phpunit/tests/Regression/GitHub/1351/Issue1351Test.php:44
    Used PDO in /home/mega/PHPUnit/phpunit/tests/Regression/GitHub/1351/Issue1351Test.php:45
    Used PDO in /home/mega/PHPUnit/phpunit/tests/Regression/GitHub/1351/Issue1351Test.php:45

  ext-xdebug
    Used xdebug_disable in /home/mega/PHPUnit/phpunit/tests/_files/FatalTest.php:8

```

ext-SPL and ext-Reflection are in current composer.json but in lowercase which is strictly speaking not correct. The rest is clearly missing.

I have checked the code pointed out by **extcheck** and it appears that:
**ext-date** must be in **require**
Either **ext-mbstring** or **ext-xml** must be in **require** (**ext-mbstring** preferred according to the code)
**ext-tidy** should be is **suggest**
**ext-xml** must be in **require**
**ext-Phar** must be in **require**
**ext-PDO** must be in **require-dev**
**ext-xdebug** should be in **suggest**

It is easy to fix it and make a new PR. But before I do so I'd like your opinion on should we have extcheck in .travis.yml so it would check extensions on each build and fail the build if new contribution make use of just another previously not mentioned extension or just add missing extensions to composer.json? What is your view on this?

PS: Amazingly pretty much all packages I tested with extcheck have some extensions missing! That's quite spread problem...

**Comment by jmauerhan** [comment]
I honestly didn't even know you could require extensions in composer - is that a new feature? I'd used a small script in my projects to check for required extensions. Does composer give you errors if the extension isn't enabled, or what?

**Comment by vbashkirtsev** [comment]
Last paragraph at https://getcomposer.org/doc/04-schema.md#package-links says:
_require_ and _require-dev_ also support references to specific PHP versions and PHP extensions your project needs to run successfully.

I don't know for how long it was there but I guess it was there from the start.

Composer complains loudly about missing extensions and refuses to install the package. You also can put in extension dependencies in "suggest" section. In this case composer just gives you a message like:

`sebastian/global-state suggests installing ext-uopz (*)`

So if your package has a way to run without an extension but may use that extension if it is installed then "suggest" section is way to go. If your package demands an extension then you can just require an extension in composer.json and forget about checks in the code (of course you may still do them in case some one will use your code without composer).

**Comment by jmauerhan** [comment]
Thanks for letting me know, that's a really neat feature! 

Anyway, you might just open a PR for this, it'd probably get fixed fastest that way.

**Comment by vbashkirtsev** [comment]
My point is that: should we put check for extensions in .travis.yml or not? I personally think it is good idea: this way missing extension will be immediately apparent. I just seeking the opinion of community before going ahead.

**Comment by 7KVZw8C** [comment]
@vbashkirtsev i agree

**Comment by sebastianbergmann** [comment]
I honestly do not think that there is any value in listing extensions as dependencies that are built and enabled by default (and cannot even be disabled (SPL, Reflection, ...)).

**Comment by sebastianbergmann** [comment]
`ext/phar` is only used when you use the PHAR distribution of PHPUnit, no need to check for it in `composer.json`.

**Comment by vbashkirtsev** [comment]
Just checked the list of extensions which cannot be disabled. You're right: Reflection, SPL, date as well as ereg and pcre cannot be disabled. I will add it as not needed in my tool.

If Phar not really used in composer mode and there is some code guarding against incorrect use then it may be safely ignored.

The main issue which I target: ensure that all used extensions are really present and verified by composer before they used by code. At the moment nothing stops a contributor to commit a patch using some extension present on Travis but which may not be present on end-user system.

I will modify the PR taking into account your points. The rest I believe is good?

**Comment by vbashkirtsev** [comment]
@sebastianbergmann All fixed, see #2289

**Comment by luispabon** [comment]
@sebastianbergmann there's intrinsic value on listing all dependencies on composer.json, even if it's just for completeness sake, but beyond that some php distributions package mbstring separately from php itself. We didn't know mbstring was a requirement to phpunit until we updated our deps today and our builds started failing.

**Comment by tniemann** [comment]
HI,

I have an issue which is related to this discussion. I don't have the PDO Extension installed cause I am using MongoDB. How can I avoid "The requested PHP extension ext-pdo * is missing from your system. Install or enable PHP's pdo extension" without installing it. I do not think that the test environment should define how the prod system looks like.

Regards
Thomas
