### ISSUE TITLE
Question: how to run with filter test, that depends on other test

### ISSUE THREAD

**Issue by b1rdex** [sebastianbergmann/phpunit#2292]
I have `@depends` on some tests.
There is `--filter` option which might be used to run exactly one test.
If this one test depends on some other, it will be skipped.

Is there any option to automatically get and run all `depends` chain to run requested by filter test?

**Comment by Oldenborg** [comment]
What was the solution here?

**Comment by b1rdex** [comment]
AFAIK there is no solution for this.

**Comment by Oldenborg** [comment]
Ok.. thought you found a solution since you closed the issue. Never mind.

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.

**Comment by Oldenborg** [comment]
No but if two people could work together to find a solution to an issue they both encountered, and post the results here.. other people might find the issue, see the solution and be happy
