### ISSUE TITLE
Incorrect code coverage.

### ISSUE THREAD

**Issue by wcatron** [sebastianbergmann/phpunit#2293]
I can't determine the situation that is causing this but in my project [wcatron/ionic-cloud-sdk-php](https://github.com/wcatron/ionic-cloud-sdk-php) I have a class [HttpHandler](https://github.com/wcatron/ionic-cloud-sdk-php/blob/master/src/Helpers/HttpHandler.php) which has a test class [HttpHandlerTest](https://github.com/wcatron/ionic-cloud-sdk-php/blob/master/tests/Helpers/HttpHandlerTest.php) which simply tests the constructor. When I generate the coverage it has 0% coverage for my class. When I run the tests using the debugger I step right through the constructor.

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project.
