### ISSUE TITLE
Question / Feature Request: Move Mocks and Assertions to Traits?

### ISSUE THREAD

**Issue by SJrX** [sebastianbergmann/phpunit#2295]
I am trying to create a standardized fixture builder to replace some of most popular ad-hoc fixtures we are repetitively building inline. One thing that is annoying is that many of the helper methods we are accustomed to are specified in the abstract PHPUnit_Framework_TestCase (e.g., getMock(), any() , etc... ). As best I can see these methods don't really depend on the PHPUnit_Framework_TestCase at all. 

Would it be possible to move these over to a trait so that other classes can import the trait and have these methods, or alternatively is there a reason this can't be done (for the moment I have just copy and pasted some methods that I need).

**Comment by sebastianbergmann** [comment]
This might eventually happen but there is no need for a ticket for this.
