### ISSUE TITLE
phpdbg does not properly evaluate tests in isolation

### ISSUE THREAD

**Issue by JosephViolago** [sebastianbergmann/phpunit#2297]
I've created an environment to reproduce the bug [here](https://github.com/JosephViolago/phpdbg-phpunit-bug). In summary, I have:
- 2 test cases
  - un-isolated
    - assertTrue(true)
    - assertTrue(false) // not ok
  - isolated
    - assertTrue(true)
    - assertTrue(false) //XDebug: not ok; phpdbg: ok
### The concern

In `phpdbg`, **false positives** are returned; `--tap` & `--coverage-text` show that isolated tests have been run, but no assertions have been made.
### I'll just make this clear...

This is **NOT** (_just_) a code-coverage bug. There's already an issue up to discuss the effects of process-isolation on code coverage in #2019.
### In the meanwhile...

It's hard to go back to `XDebug` once you've felt the speed of `phpdbg`. To minimize the use of `XDebug`, I run `phpunit` twice. Once with `XDebug`, specifying `--group isolated`/`@group isolated` for tests known to run process-isolation - and another time with `phpdbg` for the rest of the test suite. Both runs produce php-coverage files (`.cov`) and are stitched together using `phpcov`. Sample below. It's not fun resorting to this expanded form of test execution (I've gone as far as making a `Makefile` just to encapsulate it.), but it's better than running everything in exclusively `XDebug` (slow) or `phpdbg` (inaccurate).

``` bash
vendor/bin/phpunit --group isolated $(TESTARGS) \
    --log-junit $(TEST_REPORTS)/phpunit/xdebug-junit.xml \
    --coverage-php $(TEST_ARTIFACTS)/php/xdebug-coverageData.cov \
    || $(TEST_FAIL_OK)
phpdbg -qrr vendor/bin/phpunit $(TESTARGS) \
    --log-junit $(TEST_REPORTS)/phpunit/phpdbg-junit.xml \
    --coverage-php $(TEST_ARTIFACTS)/php/phpdbg-coverageData.cov \
    || $(TEST_FAIL_OK)
vendor/bin/phpcov merge $(TEST_ARTIFACTS)/php \
    --clover $(TEST_ARTIFACTS)/xml/clover.xml \
    --html $(TEST_ARTIFACTS)/html
```

**Comment by jmauerhan** [comment]
The fact that tests pass when they should fail is a huge issue - has anyone been able to look at this? phpdbg is so much faster but it's useless if your tests don't actually fail!

The solution of running isolated tests with xdebug really only works as long as you enforce putting the right group tag on your isolated tests, it's super easy for someone to mess that up, so there's still a big risk of isolated tests passing when they should fail.

**Comment by sebastianbergmann** [comment]
I cannot reproduce this with PHP 7.1.10 and PHPUnit 5.7.22:
```patch
diff --git a/composer.json b/composer.json
index 2456df5..b00e1f5 100644
--- a/composer.json
+++ b/composer.json
@@ -1,6 +1,5 @@
 {
     "require": {
-        "php": "~7.0.0",
-        "phpunit/phpunit": "5.4.6"
+        "phpunit/phpunit": "^5.7"
     }
 }
```
```
$ phpdbg -qrr ./vendor/bin/phpunit
PHPUnit 5.7.22 by Sebastian Bergmann and contributors.

Runtime:       PHPDBG 7.1.10
Configuration: /home/sb/phpdbg-phpunit-bug/phpunit.xml

.F.F                                                                4 / 4 (100%)

Time: 104 ms, Memory: 4.00MB

There were 2 failures:

1) PhpdbgIsolatedTest::testFailingTestFails
Failed asserting that false is true.

/home/sb/phpdbg-phpunit-bug/tests/PhpdbgIsolatedTest.php:16

2) PhpdbgUnisolatedTest::testFailingTestFails
Failed asserting that false is true.

/home/sb/phpdbg-phpunit-bug/tests/PhpdbgUnisolatedTest.php:12

FAILURES!
Tests: 4, Assertions: 4, Failures: 2.
```
