### ISSUE TITLE
Issues with generating coverage

### ISSUE THREAD

**Issue by elrossco22** [sebastianbergmann/phpunit#2298]
Hi,

I'm currently experiencing problems running the following command on our CI server
`../vendor/bin/phpunit --coverage-xml $TRAVIS_BUILD_DIR/coverage --testsuite=unit`

The tests finish and then the it hangs with the output
`Generating code coverage report in PHPUnit XML format …`

We are using PHP 7 and running PHPUnit version 4.8.27

Does anyone know what might be causing this ?

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project.

Please note that PHPUnit 4.8 is not supported on PHP 7.
