### ISSUE TITLE
Undefined global constant stalls the test runner indefinitely

### ISSUE THREAD

**Issue by someone635** [sebastianbergmann/phpunit#2301]
```php
<?php
class Test extends PHPUnit\Framework\TestCase
{
    public function testOne()
    {
        $this->doSomething();
    }

    private function doSomething(string $value = UNDEFINED)
    {
    }
}
```
Running this test stalls the test runner indefinitely, instead of showing the expected error:
```
Use of undefined constant UNDEFINED_GLOBAL - assumed 'UNDEFINED_GLOBAL'
```
Removing the type hint makes the test fail as expected, as does moving the undefined global in the body of the function. Thus the error might be related to the type hint.

**Comment by sebastianbergmann** [comment]
I can reproduce this but I have no idea what is going on here.

**Comment by kelunik** [comment]
This is related to the following line: https://github.com/php/php-src/blob/php-7.1.0RC1/Zend/zend_constants.c#L397

`string $value = \UNDEFINED` doesn't hang, but `string $value = UNDEFINED` does.

**Comment by sebastianbergmann** [comment]
It hangs when Xdebug is loaded. It does not hang when Xdebug is not loaded.

@derickr I think that this might be a bug in Xdebug.

**Comment by kelunik** [comment]
@sebastianbergmann It hangs for me even if xdebug is not loaded.

**Comment by sebastianbergmann** [comment]
```
$ php -v
PHP 7.1.0RC2 (cli) (built: Sep 15 2016 07:21:57) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.5.0-dev, Copyright (c) 2002-2016, by Derick Rethans
```

```
$ /usr/local/src/phpunit/phpunit Test
PHPUnit 5.5.5-12-g61a9772 by Sebastian Bergmann and contributors.

<HANGS>
```

```
$ php -n /usr/local/src/phpunit/phpunit Test
PHPUnit 5.5.5-12-g61a9772 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 15 ms, Memory: 4.00MB

OK (1 test, 0 assertions)
```

**Comment by kelunik** [comment]
@sebastianbergmann Probably the default error reporting that does something different?

Reproduction case: https://github.com/kelunik/php-bug-2016-09-24

**Comment by nikic** [comment]
Here's an isolated reproduce case:

```php
<?php
error_reporting(E_ALL);

function doSomething(string $value = UNDEFINED_XYZ) {
}

set_error_handler(function() {
    throw new Exception;
});

doSomething();
```

So this is definitely a PHP bug, not related to phpunit or xdebug.

**Comment by nikic** [comment]
PHP bug report: https://bugs.php.net/bug.php?id=73163

**Comment by sebastianbergmann** [comment]
Thank you, @nikic and @kelunik!
