### ISSUE TITLE
Does dataProvider support params?

### ISSUE THREAD

**Issue by ke-liang** [sebastianbergmann/phpunit#2302]
Hi Guys,
Now I have the issue that below what I must add params in dataProvider, someone can help me resolve it? thanks in advance!
    /**
     * @dataProvider dataOrders
     */
    function testDataProvider($order,$channel)
    {
        echo $order.";".$channel."\n";
    }
    public function dataOrders()
    {
        $orderNo=Pingpp::$order_No; //this is a static param what i defined in some other class
        return [
            [$orderNo,"alipay"],[$orderNo,"alipay_qr"]
        ];
    }

anyway, the result what i get is below:
;alipay
;alipay_qr

NOT PRINT the orderNo!!!, can you help me? not support params in dataprovider?

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.
