### ISSUE TITLE
Limits on Code Coverage for HUGE php script files?

### ISSUE THREAD

**Issue by michaelbutler** [sebastianbergmann/phpunit#2303]
I have a large phpunit suite (over 7000 tests, over 15,000 assertions) that is working fine, with code coverage as well. I noticed however that on huge PHP files (e.g. over 8000 lines long) the code coverage report is a bit screwy. On one file, it reports as 100% coverage even though it is no where near that high -- probably around 20% is covered. It says 323/323 lines covered for the total, but this file has 10150 lines in it.

I have set the memory max to 8096M to make sure it has enough memory to process. 

Do you think this could be an xdebug limit on maximum line counts, or some other limitation?

**Comment by jmauerhan** [comment]
You're probably going to need to move this to the php-code-coverage project. :) I would wonder how it looks with phpdbg however that might help identify a cause.

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project.
