### ISSUE TITLE
No incremental output on PHPUnit 5.5

### ISSUE THREAD

**Issue by Taluu** [sebastianbergmann/phpunit#2305]
Hi,

Each time I'm running phpunit 5.5, I have the output only when the command ends, not in a type of a "progress" mode. I tried with a `phpunit: <5.5` constraint (which successfully install phpunit 5.4), and I have the incremental output, while with 5.5, it's only once the command has finished that I have everything (I thus can't interrupt as I have no clue of what tests was done).

I'll try to post a gif or two to illustrate what I mean.

**Comment by Taluu** [comment]
Note (again) : It seems related to phpunit 5.5.5, because on 5.5.4 it seems to work nicely.

**Comment by sebastianbergmann** [comment]
Probably related to 71acbc5581943f35df8dccc6f72af42ecff29eab. Are you doing something "funny" with output buffers?

**Comment by Taluu** [comment]
Not really sure, but there is a response sending

**Comment by Taluu** [comment]
Hum after a lookup, it seems there is indeed a `ob_start()` on the bootstrap file. I'll check if I can remove it then.
