### ISSUE TITLE
Colors config from xml not effective ?

### ISSUE THREAD

**Issue by Taluu** [sebastianbergmann/phpunit#2306]
Hi,

If I want some colors, I can add the `--colors` switch when running phpunit ; but after adding `colors="auto"` in my xml configuration, it seems it is not effective, and thus I always have a colorless output.

``` xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- http://www.phpunit.de/manual/current/en/appendixes.configuration.html -->
<phpunit
    backupGlobals="false"
    backupStaticAttributes="false"
    colors="auto"
    bootstrap="./tests/init.php"
    verbose="true"
    failOnRisky="true"
    failOnWarning="true"

    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://schema.phpunit.de/current/phpunit.xsd">

    <testsuites>
        <testsuite name="My test suite">
            <directory>./tests</directory>
        </testsuite>
    </testsuites>
</phpunit>
```

![image](https://cloud.githubusercontent.com/assets/239685/18922945/ddc5d7ee-85aa-11e6-9a76-6a1a5e2f65cd.png)

**Comment by Taluu** [comment]
Note ; I tried with values `always`, `true`, but to no avail.

**Comment by sebastianbergmann** [comment]
`colors="true"` works for me. `colors="auto"` and `colors="always"` are not supported. `auto` and `always` can only be used on the commandline.
