### ISSUE TITLE
Allow constants to be used to define the @exceptionCode

### ISSUE THREAD

**Issue by rquadling** [sebastianbergmann/phpunit#2307]
Currently, with a constant as the exceptionCode, you get the error ...

```
1) Assert\Tests\AssertTest::testInvalidFloat with data set #0 (1)
Failed asserting that 9 is equal to expected exception code 'Assertion::INVALID_FLOAT'.
```
9 === Assertion::INVALID_FLOAT

**Comment by sebastianbergmann** [comment]
Use the `expectExceptionCode()` method instead of the `@expectedExceptionCode` annotation.

https://thephp.cc/news/2016/02/questioning-phpunit-best-practices has details on why this is a good idea anyway.

**Comment by rquadling** [comment]
It was my fault. I'd forgot I was in a namespace and didn't use an absolute namespace.

With regard to best practise, using a deprecated method is why I'm removing the setEx...() methods in favour of annotations.

**Comment by rquadling** [comment]
Good article (just read it properly).
