### ISSUE TITLE
Better failure message when asserting that two strings are equal

### ISSUE THREAD

**Issue by sylfabre** [sebastianbergmann/phpunit#2308]
This is a feature request but I'm not sure if it's about PHPUnit or PHPStorm IDE

When using `$this->assertSame()` with strings, you may get the following failure message:
![image](https://cloud.githubusercontent.com/assets/3177556/18944680/0b7ce35e-8627-11e6-8334-44d2d2b59787.png)

It would be useful to have: 
- string length or quotes like with `var_dump` to spot a trailing space for instance
- var type in case the expected value is an empty string `''` and the actuel one is `false` or `null`

**Comment by sylfabre** [comment]
@sebastianbergmann I would happily provide a pull request if you think that my idea is worth it.

**Comment by sebastianbergmann** [comment]
```php
<?php
class Test extends PHPUnit\Framework\TestCase
{
    public function testOne()
    {
        $this->assertEquals('foo', ' foo ');
    }

    public function testTwo()
    {
        $this->assertSame('foo', ' foo ');
    }
}
```
```
phpunit Test
PHPUnit 6.0-gd71ba0a by Sebastian Bergmann and contributors.

FF                                                                  2 / 2 (100%)

Time: 37 ms, Memory: 4.00MB

There were 2 failures:

1) Test::testOne
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'foo'
+' foo '

/home/sb/Test.php:6

2) Test::testTwo
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-foo
+ foo

/home/sb/Test.php:11

FAILURES!
Tests: 2, Assertions: 2, Failures: 2.
```
So `assertEquals()` puts `'` around the strings and `assertSame()` does not. This is inconsistent and should be fixed. `assertSame()` should also put `'` around the strings.

The questions that remains is whether type information should be displayed as well.

**Comment by sylfabre** [comment]
@sebastianbergmann Type information is only useful if it's `null` or `false` or anything but a string and evaluating as an empty string

**Comment by sebastianbergmann** [comment]
Sounds reasonable. Please send a pull request :-)
