### ISSUE TITLE
PHP function not reported as completely covered by PHPUnit when calling multiple times

### ISSUE THREAD

**Issue by fcools** [sebastianbergmann/phpunit#2311]
function itDoesThingsToValue()
{
    static $value = -1;
    if ($value < 0) {
        $value = 1978;
        //Do some more stuff with $value
        //But $value keeps being > 0
    }
    return $value;
}

XDebug code coverage reports all the lines as covered when calling this function once or multiple times.

PHPUnit reports the lines as covered when calling it once.

Calling it multiple times (because of different PHPUnit tests), PHPUnit reports the lines inbetween the {} as not covered.

I know the lines between the {} execute only once because of the static variable $value, but imho executed lines should always be reported as covered, regardless if they where skipped at following calls (by following tests).

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project.

**Comment by fcools** [comment]
I apologize. 
Do you think it's a genuine issue to report? If so, I'll create an issue over there.
