### ISSUE TITLE
Upgrading PHPUnit to use preferred pattern.

### ISSUE THREAD

**Issue by rquadling** [sebastianbergmann/phpunit#2313]
Hi.

Based upon https://thephp.cc/news/2016/02/questioning-phpunit-best-practices, I took a look at changing from using annotations and remove the deprecated `setExpectedException()` calls.

As a consequence, the library I work on has can no longer run tests for older versions of PHP.

What is the recommended approach for a library that executes fine on PHP5.3+ AND wants to use PHPUnit and the preferred approach.

We use Travis to run the tests. But I'm stuck between not having tests for older versions of PHP for library or not upgrading PHP.

Ideas / recommendations please.

The library is the https://github.com/beberlei.

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.
