### ISSUE TITLE
Mandatory listener class and dev dependencies

### ISSUE THREAD

**Issue by alskold** [sebastianbergmann/phpunit#2315]
After the update (5.5.6), with the listener class being mandatory (#2261), our production build is failing. The reason being that we have listeners which rely on dev-dependencies. 

Maybe have them mandatory by default, but add an "optional"-flag?

**Comment by thePanz** [comment]
In our case, the failure of a misconfigured listener lead to no tests being executed and phpunit returning 0 as status code. Tests were silently skipped and the 0 return code wrongly interpreted as "everything is Ok".

**Comment by sebastianbergmann** [comment]
Closing after #2349 was merged.
