### ISSUE TITLE
SplTypes and phpunit

### ISSUE THREAD

**Issue by drakonli** [sebastianbergmann/phpunit#2319]
I use [SplTypes library](http://php.net/manual/en/book.spl-types.php) in my project for stricter type hints.

When I began developing tests though I bumped into a weird situtation that I'm not even able to debug.

Sample code:

```
use PHPUnit\Framework\TestCase;

class Test extends TestCase
{
    public function test1()
    {
        $someClassMock = $this->createMock(SomeClass::class);

        $someClassMock->expects($this->once())
                ->method('someMethod')
                ->with(new \SplString('someString'));
    }
}
```

Now, when executing this test an Exception is being thrown on the "with" method line:

> UnexpectedValueException: Value not a string

This is a SplTypes library exception which supposedly means that somewhere in the code something is trying to create SplString object by passing it a non-string or maybe not even passing anything. I've been able to debug it back to [this line](https://github.com/sebastianbergmann/phpunit-mock-objects/blob/master/src/Framework/MockObject/Matcher/Parameters.php#L44) - this is the line where the exception says it's been called from, but that's as far as I got. Deeper debugging didnt result to anything and I wasn't able to find out why exactly and where the exception is been thrown out. 

This problem arises only with SplTypes, but that means that in order to properly test it with phpunit I need to remove types or change them to custom-objects which is what I would want to do only as a last resort.

Any help is appriciated.

**Comment by sebastianbergmann** [comment]
SplTypes is unstable has not been maintained for years. I assume this to be a problem with SplTypes and not with PHPUnit.
