### ISSUE TITLE
PHP Fatal error:  Cannot make non abstract method PHPUnit_Framework_TestCase::getDataSet() abstract in class PHPUnit_Extensions_Database_TestCase

### ISSUE THREAD

**Issue by j0k3r** [sebastianbergmann/phpunit#2320]
Travis got updated to PHPUnit 5.6.0 today.
Since then we got only some of our build that fail using that version.

It's usually the same combination: PHP 5.6 & PostgreSQL or SQLite.
It does appear on PHP 5.6 using MySQL and even not PHP 5 or 7

The error is always:

```
1) Tests\Wallabag\CoreBundle\Command\InstallCommandTest::testRunInstallCommand
PHP Fatal error:  Cannot make non abstract method PHPUnit_Framework_TestCase::getDataSet() abstract in class PHPUnit_Extensions_Database_TestCase in phar:///home/travis/.phpenv/versions/5.6.5/bin/phpunit/dbunit/Extensions/Database/TestCase.php on line 277

Fatal error: Cannot make non abstract method PHPUnit_Framework_TestCase::getDataSet() abstract in class PHPUnit_Extensions_Database_TestCase in phar:///home/travis/.phpenv/versions/5.6.5/bin/phpunit/dbunit/Extensions/Database/TestCase.php on line 277
```

The test doesn't fail, it display a dot.

You can see the output log here:
- https://travis-ci.org/wallabag/wallabag/jobs/165793121#L330
- https://travis-ci.org/wallabag/wallabag/jobs/165726844#L327
- https://travis-ci.org/wallabag/wallabag/jobs/165735958#L783
- https://travis-ci.org/wallabag/wallabag/jobs/165738074#L327

Can this be related to something in our code?
Here is the test: https://github.com/wallabag/wallabag/blob/master/tests/Wallabag/CoreBundle/Command/InstallCommandTest.php#L63-L90

**Comment by sebastianbergmann** [comment]
This has nothing to do with your code, it's a "clash" between PHPUnit and DbUnit.
