### ISSUE TITLE
Incomplete JSON log if PHP error occurs

### ISSUE THREAD

**Issue by tmysik** [sebastianbergmann/phpunit#2325]
This report is based on NetBeans' issue [1].

The problem is that if a PHP error occurs, the generated JSON log is not complete. Try e.g. this file:

```php
class MyTest extends PHPUnit_Framework_TestCase {
    
    public function testBad() {
        $this->testBad();
        $this->assertTrue(false);
    }

    public function testGood() {
        $this->assertTrue(true);
    }

}
```

The generated JSON log file is:

```json
{
    "event": "suiteStart",
    "suite": "",
    "tests": 2
}{
    "event": "suiteStart",
    "suite": "MyTest",
    "tests": 2
}{
    "event": "testStart",
    "suite": "MyTest",
    "test": "MyTest::testBad"
}
```

Thanks!
[1] https://netbeans.org/bugzilla/show_bug.cgi?id=268447

**Comment by tmysik** [comment]
One note: my PHPUnit version is 4.8.23, will try PHP 5.x later next week.

Thanks.

**Comment by sebastianbergmann** [comment]
Expected behavior on PHP 5. Solved on PHP 7 thanks to engine exceptions.

**Comment by vanderlee** [comment]
Does that mean the JSON log is unreliable in PHP 5, as it reports some errors as success?

**Comment by sebastianbergmann** [comment]
Every log is unreliable when a fatal error occurs in PHP 5.

**Comment by tmysik** [comment]
@sebastianbergmann 

> Solved on PHP 7 thanks to engine exceptions.

Really? I am on PHP 7.0.8, using PHPUnit 5.6.1 and the JSON log seems very similar:

```json
{
    "event": "suiteStart",
    "suite": "",
    "tests": 1
}{
    "event": "suiteStart",
    "suite": "MyTest",
    "tests": 1
}{
    "event": "testStart",
    "suite": "MyTest",
    "test": "MyTest::testBad"
}
```

Thanks.
