### ISSUE TITLE
Formalise spies

### ISSUE THREAD

**Issue by neerolyte** [sebastianbergmann/phpunit#2326]
It's been possible for a while to do complex checks on arguments supplied to methods on mocks for a while, but it's never been documented (that I could find) and probably never intended.

I've been doing versions of:

```
$foo->expects($spy = $this->any())->method('bar');
[...]
$invocations = $spy->getInvocations();
$this->assertEquals(1, count($invocations));
$args = $invocations[0]->arguments;
$this->assertEquals(1, count($args));
$this->assertEquals('bar', $args[0]);
```

for quite a while, but it looks like the arguments have moved over to a new variable on the invocations objects, now I need to use `$invocations[...]->parameters` as something's changed.

The built in spy behaviour whether intentional or not was really useful, it'd be really good to formalise it, put it in documentation and lock down the API.

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-mock-objects](https://github.com/sebastianbergmann/phpunit-mock-objects) project.

**Comment by neerolyte** [comment]
Sorry, but maybe you could clarify a bit more?

It seems to me like this issue is a mixture of opinion, documentation and (possibly, but not necessarily) changing code in [phpunit-mock-objects](https://github.com/sebastianbergmann/phpunit-mock-objects/issues), i.e opinion comes in to it because you may choose to not support conventional spies at all and instead prefer to stick with ever more complex matchers (then surely it gets discussed here under "General problems"), if you're happy with the existing API (I am) and simply want to document it then surely it'd belong on the [phpunit-documentation](https://github.com/sebastianbergmann/phpunit-documentation/issues) issues or finally if you want to refactor the API to make it nicer to work with before documenting it phpunit-mock-objects makes sense.

I went through this reasoning before posting the issue originally, which is why I ended up posting it here.

I'm hesitant to blindly move the idea over to another tracker when it doesn't neatly fit in to any of the categories described in [CONTRIBUTING.md](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues).

**Comment by afilina** [comment]
This feature has been dropped and is not coming back: https://github.com/sebastianbergmann/phpunit/pull/4447
