### ISSUE TITLE
Warning on coverage HTML: PHP Warning:  date() expects parameter 2 to be integer, string given in phar:///usr/local/bin/phpunit/php-code-coverage/Report/Html/Facade.php on line 70

### ISSUE THREAD

**Issue by pshentsoff** [sebastianbergmann/phpunit#2330]
Hi All!
Got this warning on the one of my projects:

-----
PHPUnit 5.6.1 by Sebastian Bergmann and contributors.

...............................................................  63 / 215 ( 29%)
............................................................... 126 / 215 ( 58%)
............................................................... 189 / 215 ( 87%)
.........................S                                      215 / 215 (100%)

Time: 2,77 seconds, Memory: 26,00MB

OK, but incomplete, skipped, or risky tests!
Tests: 214, Assertions: 526, Skipped: 1.

Generating code coverage report in HTML format ...PHP Warning:  date() expects parameter 2 to be integer, string given in phar:///usr/local/bin/phpunit/php-code-coverage/Report/Html/Facade.php on line 70
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /usr/local/bin/phpunit:572
PHP   3. PHPUnit_TextUI_Command->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:115
PHP   4. PHPUnit_TextUI_TestRunner->doRun() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:185
PHP   5. SebastianBergmann\CodeCoverage\Report\Html\Facade->process() phar:///usr/local/bin/phpunit/phpunit/TextUI/TestRunner.php:526
PHP   6. date() phar:///usr/local/bin/phpunit/php-code-coverage/Report/Html/Facade.php:70

Warning: date() expects parameter 2 to be integer, string given in phar:///usr/local/bin/phpunit/php-code-coverage/Report/Html/Facade.php on line 70

Call Stack:
    0.0009     496928   1. {main}() /usr/local/bin/phpunit:0
    0.0588    8961400   2. PHPUnit_TextUI_Command::main() /usr/local/bin/phpunit:572
    0.0588    8961512   3. PHPUnit_TextUI_Command->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:115
    0.0919   11614624   4. PHPUnit_TextUI_TestRunner->doRun() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:185
    2.7742   20964000   5. SebastianBergmann\CodeCoverage\Report\Html\Facade->process() phar:///usr/local/bin/phpunit/phpunit/TextUI/TestRunner.php:526
    4.1498   21279008   6. date() phar:///usr/local/bin/phpunit/php-code-coverage/Report/Html/Facade.php:70

 done

-----
What am i doing wrong?

**Comment by jmauerhan** [comment]
The line of code generating that error is the last one here: 

```
        if (!isset($_SERVER['REQUEST_TIME'])) {
            $_SERVER['REQUEST_TIME'] = time();
        }

        $date = date('D M j G:i:s T Y', $_SERVER['REQUEST_TIME']);
```

So somehow your environment has that variable configured to be an invalid value.

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project.
