### ISSUE TITLE
Boolean environment variable values specified in XML get mangled

### ISSUE THREAD

**Issue by mfn** [sebastianbergmann/phpunit#2331]
An environment variable with the string value `value="false"` or `value="true"` ends up as value `""` or `"1`" in the environment.

Example:

``` XML
...
<php>
  <env name="foo" value="false"/>
  <env name="bar" value="true"/>
</php>
...
```

In the environment, retrieved via `getenv`:
- `foo` will have the value `` (i.e. empty)
- `bar` will have the value `1` (string)

I would expected that both values retain the string representation from the XML file, i.e. `"false"` and `"true"`.

**Comment by chrisguitarguy** [comment]
That's not how environment variables work -- they are always just strings. Especially if you're [using `getenv`](https://3v4l.org/43nh6).

Check out the [code here](https://github.com/sebastianbergmann/phpunit/blob/cd13b23ac5a519a4708e00736c26ee0bb28b2e01/src/Util/Configuration.php#L541-L548). Specifically the call to [`putenv`](http://php.net/manual/en/function.putenv.php). `putenv` only takes a string, and the code in PHPUnit just concatenates the name and value directly.

If checking the truthiness or falsiness doesn't work for you, use [`$_ENV`](http://php.net/manual/en/reserved.variables.environment.php) instead. Or run the value through filter var and validate it as a boolean.

```php
if (filter_var(getenv('FOO'), FILTER_VALIDATE_BOOLEAN)) {
  // ...
}
```

**Comment by mfn** [comment]
> PHPUnit just concatenates the name and value directly.

How can that be true and still a value like string "false" ends up being an empty string? I don't think this assertion is correct.

**Comment by chrisguitarguy** [comment]
> How can that be true and still a value like string "false" ends up being an empty string?

When it [loads the configuration](https://github.com/sebastianbergmann/phpunit/blob/cd13b23ac5a519a4708e00736c26ee0bb28b2e01/src/Util/Configuration.php#L476-L483) it [converts the strings `true` and `false` to booleans](https://github.com/sebastianbergmann/phpunit/blob/cd13b23ac5a519a4708e00736c26ee0bb28b2e01/src/Util/Configuration.php#L1019-L1028). That behavior is, unfortunately, not really documented.

**Comment by mfn** [comment]
Exactly, my point.

Hence the title "Boolean environment variable values specified in XML get mangled", thanks for confirming!

**Comment by hackel** [comment]
This fix was reverted due to BC concerns, but the change was never bumped up to a new major release.  Environment variables are still getting mangled.

**Comment by vsjosh** [comment]
For those finding this issue currently, I created a workaround like so:
```xml
        <env name="AUTHORISATION_ENABLED" value="0" force="true" />
```
Then converted the value like so:
```php
$enabled = env('AUTHORISATION_ENABLED', true);

if ($enabled === '0') {
    $enabled = false;
} elseif ($enabled === '1') {
    $enabled = true;
}

return 'enabled' => $enabled;
```
I needed a custom configuration setting in a Laravel application derived from an environment variable. Strings worked fine so I used 0/1 as true/false.
