### ISSUE TITLE
mocks created by `prophesize()` in data sets are not validated during test

### ISSUE THREAD

**Issue by mente** [sebastianbergmann/phpunit#2335]
[Reproduce](https://gist.github.com/mente/e2fa40d939a080ff824cc1dd8b18f6b2)

Guess the problem comes from nature how data sets are generated. Not sure what is proper fix - forbid usage of prophecy during data set generation? Or do not recycle `$this->prophet`?

**Comment by mente** [comment]
Any ideas how to fix it?

**Comment by sebastianbergmann** [comment]
I do not think that this is possible.

**Comment by sebastianbergmann** [comment]
@ciaranmcnulty @everzet What do you think?

**Comment by sebastianbergmann** [comment]
@ciaranmcnulty @everzet ping

**Comment by sebastianbergmann** [comment]
No feedback, closing.

**Comment by mente** [comment]
But issue still exists. Do you need any feedback from me?
