### ISSUE TITLE
PHP Fatal error when coverage directory does not exists

### ISSUE THREAD

**Issue by pMatviienko** [sebastianbergmann/phpunit#2341]
Here is an error I've got with phpunit 5.6.0 when tried to generate coverage to non existing directory

Generating code coverage report in HTML format ...PHP Fatal error:  Uncaught Error: Class 'SebastianBergmann\CodeCoverage\Report\Html\RuntimeException' not found in /vagrant/vendor/phpunit/php-code-coverage/src/Report/Html/Facade.php:171
Stack trace:
.......

When I checked file  - Here is contants of 171 line:

```        throw new RuntimeException(```

I guess it should be 

```        throw new \RuntimeException(```

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project.
