### ISSUE TITLE
coverage forwarding to blackfire

### ISSUE THREAD

**Issue by ermoca** [sebastianbergmann/phpunit#2342]
I've been using phpunit for some times now but since yesterday the --coverage-html(and -xml and -php..) option isn't working or at least not in a way I understand (running all the tests still works just fine though)

here is my command :

> src/lib/bin/phpunit test/ --coverage-html test/coverage/report -c test/phpunit.xml

and here is the output (I had to use ctrl-c because after 10min nothing seems to happen) :

 ```
PHPUnit 5.6.2 by Sebastian Bergmann and contributors.

 #!/usr/bin/env php
 Listening on 127.0.0.1:8383
 Forwarding to ssl://blackfire.io:443
 ^C
```

Usually the output would just display a serie of dot for each passing test, only taking more time to generate the report.

Do you know why this is happening ? Thanks for your help !

**Comment by sebastianbergmann** [comment]
Not a PHPUnit issue, sorry.

**Comment by ermoca** [comment]
ok, thank you.
