### ISSUE TITLE
It is not possible to inject a different version of Prophecy

### ISSUE THREAD

**Issue by malteriesch** [sebastianbergmann/phpunit#2345]
The other day I had to change the implementation of Prophecy with my own one (due to this issue: https://github.com/phpspec/prophecy/issues/223) but found it impossible to exchange the implementation without using my own fork of phpunit:

PHPUnit_Framework_TestCase::prophesize() is protected and can be overridden, however PHPUnit_Framework_TestCase::getProphet() and  PHPUnit_Framework_TestCase::prophet  are private, which prohibited me for changing the implementation such that all other methods in PHPUnit_Framework_TestCase also use my version.

Is there any reason why they should be private? I propose to change the visibility to protected, if agreed then I'm happy to fork, fix and do a PR.

**Comment by sebastianbergmann** [comment]
How is `PHPUnit_Framework_TestCase::getProphet()` being private a problem for using a different version of Prophecy? Simply change `composer.json` to install your version of Prophecy and it should "just work".

Re: "Is there any reason why they should be private?": The priniciple of minimal visibility. Everything should be private unless there is a good reason for it to be public.

**Comment by malteriesch** [comment]
Thanks for the quick reply :)

I used composer.json to both load my own version of PHPUnit as well as Prophecy. Would have been possible (and simpler) to just use my version of Prophecy, that's true (missed that bit, cheers - and d'oh!)

As to minimum visibility, I agree with the principle, nevertheless, I am proposing that this is in fact a good reason for it to be protected rather than private (I don't think it needs to be public). 

This way you can just use your own base test class inherited from PHPUnit_Framework_TestCase (which I usually do anyway for any project-specific custom assertions).

This way you wouldn't have to rely on the autoloading of composer to load you own version of Prophecy.
IMO It doesn't feel quite right to use composer as a dependency injection mechanism (and that's essentially what that approach is). Basically, If I use a custom version of Prophet, it should not masquerade to be one with the same namespace (Prophecy\Prophet), I would rather have it be explicitly a MyCustomProphecy\Prophet, as they are different entities.

Does that make any sense?

**Comment by sloothword** [comment]
Adding another use case to that:

I used to create my mocks in a MockFactory class (with its own Prophet). Now i found out that PHPUnit itself includes a prophet and the prophesize method.

How can i use the same Prophet instance in the MockFactory and PHPUnit? As getProphet is private i cannot pass it to my factory.

(Maybe i am doing something fundamentally wrong as i just started with unit testing)

My current workaround is to prophesize in the testcase and let the Factory add all the needed methods.

**Comment by Jean85** [comment]
@malteriesch to do that you should use composer, it works exactely that way; look at http://stackoverflow.com/questions/13498519/how-to-require-a-fork-with-composer

@sloothword you should use a factory of mocks in your tests, it seems too much complicated and with too much logic.. Who will test the logic of your tests? Try to make it more simpler.
Also, don't mix Prophecy and PHPUnit Mock creator in the same mocks, it shouldn't work!

**Comment by malteriesch** [comment]
@Jean85 Thanks, already got that far, this is exactly how I had been using it in the end, and functionally it all works. My point is more that really I do not think it's a good practice in this case, it's a workaround at best. Essentially what we are doing is using a composer feature as a dependency injection mechanism. That we need to do this tells me that some of the decisions on how the integration between prophecy and phpunit has been implemented warrant being looked at again.

**Comment by Jean85** [comment]
I'm sorry but I completely disagree. This is not hijacking a Composer feature, it's using it for its (and PSR-0/4) designed purpose. 

Prophecy is an external dependency of PHPUnit, and you want to use a different version of it, or a complete fork if you want. You're not replacing it with something different, so the DI is perfect here, especially because you're able to do all of that without changing a single line of PHPUnit's code.
