### ISSUE TITLE
ldap_set_rebind_proc not working with PHP 7.0.12 and phpunit 5.6.2

### ISSUE THREAD

**Issue by Mattie112** [sebastianbergmann/phpunit#2347]
I have a problem with the [ldap_set_rebind_proc call](http://php.net/manual/en/function.ldap-set-rebind-proc.php) with PHP 7.0.12 and phpunit 5.6.2.

PHP 5.6 "normal code" -> works
PHP 5.6 "code in testsuite" -> works
PHP 7 "normal code" -> works
PHP 7 "code in our testsuite" -> does not work

I tried to "extract" all relevant code from our codebase to make this bugreport, however as it does a LDAP call I cannot remove that piece of code so I'm not sure how crappy it is for your guys to test. However perhaps I'm lucky and someone has a hunch on this strange problem.

I think you'll need to understand the ldap_set_rebind_proc option. In short, we ask LDAP server A to do something (write an object), however this is a readonly server. So this server sends out an "referal" to server B ("please try it there"). In our phpcode we'll need to bind to that new server and that is handled by whatever we do in the callback function for ldap_set_rebind_proc.

I've attached 4 files to this ticket, please rename to .php if you want to try it. 

Here is the output:

```
vagrant@portal:phpunittest$ /usr/bin/phpunit test.php
PHPUnit 5.6.1 by Sebastian Bergmann and contributors.

.E                                                                  2 / 2 (100%)

Time: 947 ms, Memory: 4.00MB

There was 1 error:

1) LDAPTest::testLDAP
ldap_modify(): supplied argument is not a valid ldap link resource

/var/www/sites/phpunittest/test.php:22
```

ERRORS!
Tests: 2, Assertions: 0, Errors: 1.

```
vagrant@portal:phpunittest$ php nontest.php
die in rebind function
```

And now the fun part, again with php56

```
vagrant@portal:phpunittest$ php56 /usr/bin/phpunit test.php
PHPUnit 5.6.1 by Sebastian Bergmann and contributors.

.die in rebind function
```

```
phpunittest$ php56 nontest.php
die in rebind function
```

Why is there a difference when I execute this test with php7? I'm not sure if this is a phpunit problem but hey, I have to start somewhere.

Versions:

```
vagrant@portal:phpunittest$ php --version
PHP 7.0.12 (cli) (built: Oct 13 2016 18:14:53) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.12, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans
vagrant@portal:phpunittest$ php56 --version
PHP 5.6.27 (cli) (built: Oct 14 2016 13:10:36)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```

Please note that disabling xdebug has no effect and that running this on PHP56 with OPcache is also not different.

[AnotherClass.class.txt](https://github.com/sebastianbergmann/phpunit/files/572018/AnotherClass.class.txt)
[LDAP.class.txt](https://github.com/sebastianbergmann/phpunit/files/572016/LDAP.class.txt)
[nontest.txt](https://github.com/sebastianbergmann/phpunit/files/572017/nontest.txt)
[test.txt](https://github.com/sebastianbergmann/phpunit/files/572015/test.txt)

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.
