### ISSUE TITLE
Abstract Class Inheritance: Coverage is wrong, doesn't get the count of executable lines

### ISSUE THREAD

**Issue by pelallemant** [sebastianbergmann/phpunit#2348]
Hi,

I have an abstract class defined like this:

```
abstract class AbstractValidator
{
   public function __construct() {
      $a = 1;
   } 
   abstract public function validate($val);
}
```

Then I create an Integer Validator which inherits it.

```
class IntegerValidator extends AbstractValidator
{
  public function validate($val)
  {
    return is_integer($val);
  }
  
}
```

If i write 0 test on this class, the AbstractValidator, the line `$a = 1` is counted as "not executed", but the "IntegerValidator" has 100% cover, "0/0 Lines". Even the new methods of the child class are ignored.
I would be expecting to have 0% cover, and the lines considered as "not executed".

If i write a test, the "executed lines" are shown but the "non executed lines" is not updated.

Another bug I have is that the call to `throw new \Exception` in the child class, aren't which have been tested aren't shown as "executed line".

Best regards

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project.
