### ISSUE TITLE
Why does count exist in PHPUnit_Framework_TestCase

### ISSUE THREAD

**Issue by bkielbasa** [sebastianbergmann/phpunit#2350]
I found very weird implementation of count method in PHPUnit_Framework_TestCase

https://github.com/sebastianbergmann/phpunit/blame/5.6/src/Framework/TestCase.php#L329

It always returns 1. Is it a hack or something?

**Comment by sebastianbergmann** [comment]
An instance of `PHPUnit_Framework_TestCase` represents one test.
