### ISSUE TITLE
trigger_error() automatically upgraded to an Exception

### ISSUE THREAD

**Issue by CJDennis** [sebastianbergmann/phpunit#2352]
Is there a way to mark a test to **not** upgrade trigger_error() to an Exception? I agree that in principle warnings should throw Exceptions but it would be handy to say "I *expect* this *particular* test to generate a warning but still continue", i.e. the *desired* behaviour is that it should generate a warning without failing.

**Comment by sebastianbergmann** [comment]
Just use `expectException()` to expect the exception.

**Comment by CJDennis** [comment]
Warnings don't always crash the script when not run in a test. If an Exception is raised, the code has no opportunity to continue normally afterwards, but if a warning is raised, the code may ignore it if PHP is set up that way.
