### ISSUE TITLE
RFC - Streamlining PHPCS checks on pull requests

### ISSUE THREAD

**Issue by markstory** [sebastianbergmann/phpunit#2354]
I run http://stickler-ci.com which is a service aimed at improving code quality by simplifying code review by automating code style feedback in pull requests. As a fellow open source maintainer I found I was spending a significant amount of time giving feedback to contributors on how code should be formatted, and thought there had to be a better way.

Sticker-CI is my attempt at building a better way. By making code style errors as pull request comments and a build status it is easy for both maintainers and contributors to know when a pull request matches a project's style.

I wanted to know if you were interested in trying out stickler-ci. If you do, I can submit a pull request with the configuration file, but a maintainer will need to enable webhooks by logging into https://stickler-ci.com and enabling the webhook.

**Comment by sebastianbergmann** [comment]
I would accept a pull request for such a configuration file if it is equivalent to `--standard=PSR2 --exclude=Generic.Files.LineLength`.

**Comment by markstory** [comment]
Cool. I will get that together.

**Comment by GrahamCampbell** [comment]
I'm going to play devil's advocate and say there's no point in having a PR review cluttered with code style review, because it's simply just spam and nobody should care about code style at that point, only the actual code semantics.

I'd recommend instead, having another tool that just goes and fixes the code style automatically, instead of commenting on PRs.

**Comment by markstory** [comment]
@GrahamCampbell I agree that fixing style issues automatically is better than comments, as it saves contributors more time, not all PSR2 errors can be fixed automatically. While I plan on implementing automatic fixing where possible, comments are a great way to raise the visibility of coding standards issues to contributors.

**Comment by sergeyz** [comment]
Any reason not to use existing Travis integration?

**Comment by markstory** [comment]
@sergeyz Digging into PHPCS results on travis takes more time, and isn't as accessible for casual/new contributors. Having a separate build status/feedback step for code style makes the project expectations more visible and easier to understand.
