### ISSUE TITLE
Failed asserts on empty array gives Undefined offset: 1

### ISSUE THREAD

**Issue by MasterOdin** [sebastianbergmann/phpunit#2358]
When using an assert that will fail on an empty array, it throws an "Undefined offset" message instead of the expected failed assertion message.

Minimal testcase:
```
<?
class testException extends \PHPUnit_Framework_TestCase {
    public function testException() {
        $array = array();
        $this->assertNull($array);
    }
}
```

When run gives me:
```
Testing started at 2:29 PM ...
PHPUnit 5.6.3 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.0.12 with Xdebug 2.4.1
Configuration: /Users/mpeveler/Github/Submitty/tests/phpunit.xml


Undefined offset: 1
```
(my configuration file only makes PHPUnit verbose and enables logging)

**Comment by pamil** [comment]
See https://github.com/sebastianbergmann/recursion-context/issues/5.
