### ISSUE TITLE
throwing exception doesn't work on mock object

### ISSUE THREAD

**Issue by rezamarandi** [sebastianbergmann/phpunit#2359]
hi , i'm trying to create mock and throw new exception on specific inputs , but my seems like something goes wrong 
here is my code -> https://gist.github.com/rezamarandi/8f07f274610b1f5a55328715fb07967b

![screen shot 2016-11-16 at 10 01 34 am](https://cloud.githubusercontent.com/assets/1782425/20337047/d1838a12-abe3-11e6-93a0-f27a6765d1a0.png)

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-mock-objects](https://github.com/sebastianbergmann/phpunit-mock-objects) project.
