### ISSUE TITLE
Json logger not writing the test suite name

### ISSUE THREAD

**Issue by twifty** [sebastianbergmann/phpunit#2363]
The json logger is not correctly logging the test suite name when a test case uses data providers.

Simple reproduction:
````php
class funkyTest extends \PHPUnit_Framework_TestCase {
    function testSth() {} // Correctly logs
    function provider() {}
    function testUsingProvider() {} // Correctly logs
    function testAgain() {} // Everything from now on has no test suite
}
````
I've narrowed the problem down to the `PHPUnit_Framework_TestSuite_DataProvider` being itself a nested test suite. It calls on the logger to `startTestSuite` which stores the `currentTestSuiteName` (overwriting the previous), upon completion the call to `endTestSuite` sets the name to an empty string.

Perhaps the code should be refactored to implement a stack based history. `startTestSuite` should push the old name to an array, then `endTestSuite` should restore.

**Comment by Jean85** [comment]
The JSON log format has been deprecated, so it's being dropped in PHPUnit 6.0

**Comment by twifty** [comment]
While using the JSON output, IDE's are able to generate a progressive output. IE, test results can be displayed before the whole test suite is complete. Is the same possible with any of the other loggers?

**Comment by sebastianbergmann** [comment]
The TeamCity logger, used by PhpStorm, is progressive.
