### ISSUE TITLE
Mocks of interfaces with nullable return types throw an error when returning null

### ISSUE THREAD

**Issue by jbaron-gingco** [sebastianbergmann/phpunit#2372]
PHPUnit 5.6.5

Here's a minimal example:

Interface to mock:

    <?php
    declare(strict_types = 1);

    namespace Example\PhpUnitTest;

    interface ExampleInterface
    {
        public function foo(): ?\stdClass;
    }

Test:

    <?php
    declare(strict_types = 1);

    namespace Example\PhpUnitTest\Test;

    use Example\PhpUnitTest\ExampleInterface;

    class ExampleInterfaceTest extends \PHPUnit_Framework_TestCase
    {
        /**
         * @test
         */
        public function myTest()
        {
            $exampleMock = $this->createMock(ExampleInterface::class);
            $exampleMock
                ->method('foo')
                ->willReturn(null);

            static::assertNull($exampleMock->foo());
        }
    }

The test errors with this message:

>TypeError: Return value of Mock_ExampleInterface_71d23622::foo() must be an instance of stdClass, null returned

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-mock-objects](https://github.com/sebastianbergmann/phpunit-mock-objects) project.

**Comment by jbaron-gingco** [comment]
Sorry for that, opened the report again in the (hopefully) [correct place](https://github.com/sebastianbergmann/phpunit-mock-objects/issues/338).

**Comment by sebastianbergmann** [comment]
Thank you!
