### ISSUE TITLE
@covers to consider all private/protected methods of the class under test

### ISSUE THREAD

**Issue by markwatney2016** [sebastianbergmann/phpunit#2373]
If you write an unit test for `/Acme/Foo/Bar::baz()` it is good practice to use `@covers /Acme/Foo/Bar::baz` for your unit test.

You may then find yourself refactoring `/Acme/Foo/Bar::baz()` by extracting some code into private/protected methods. You still want to gather code coverage data for those methods.

Todo so you have to add some more `@covers` annotations to your unit test method – one for each of those private/protected method you just extracted.

Later, you may find yourself refactoring those private/protected methods by e.g. renaming them or splitting them up. You would then be forced to update the `@covers` annotation of the unit test method.

I think this situation is tedious and could be improved by e.g. adding support for something like a `@coversAlsoNonPublicMethods` (on the unit test case level and/or on the unit test method level).

This new annotation would then ensure that code coverage data would be considered also for all private/protected methods of the class under test that are called by the method under test.

I think this would make refactoring of unit tested code easier.

Example 1
----------

    <?php
    use PHPUnit\Framework\TestCase;
    
    /**
     * @coversDefaultClass \Foo\CoveredClass
     * @coversAlsoNonPublicMethods
     */
    class CoversDefaultClassTest extends TestCase
    {
        /**
         * @covers ::publicMethod
         */
        public function testSomething()
        {
            $o = new Foo\CoveredClass;
            $o->publicMethod();
        }
    }
    ?>

This example uses the `@coversAlsoNonPublicMethods` on the unit test case level in combination with the `@coversDefaultClass` annotation: all non public methods of `\Foo\CoveredClass` that are called by `\Foo\CoveredClass::publicMethod()` would be considered in the code coverage report.

Example 2
----------

    <?php
    use PHPUnit\Framework\TestCase;
    
    class CoversDefaultClassTest extends TestCase
    {
        /**
         * @covers \Foo\CoveredClass::publicMethod
         * @coversAlsoNonPublicMethods \Foo\CoveredClass
         */
        public function testSomething()
        {
            $o = new Foo\CoveredClass;
            $o->publicMethod();
        }
    }
    ?>

This example uses the `@coversAlsoNonPublicMethods` on the unit test level: again, all non public methods of `\Foo\CoveredClass` that are called by `\Foo\CoveredClass::publicMethod()` would be considered in the code coverage report.

I would prefer Example 1 over Example 2.

What do you think about this feature request?

**Comment by kubawerlos** [comment]
What about this:
```php
    /**
     * @covers ClassName::<!public>
     */
```
?

**Comment by markwatney2016** [comment]
How could I miss this feature? Thank you for pointing to it. This makes my feature request superfluous.
