### ISSUE TITLE
PHPUnit 5.6.5 / PHP 7.0.13 causes Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by mwjames** [sebastianbergmann/phpunit#2374]
Segmentation fault (core dumped) caused in [0] with [1] (PHPUnit 4.5.0/PHP 5.6.5) passing the respective tests.

```
> phpunit -c phpunit.xml.dist

Using the callback-container vendor autoloader ...

PHPUnit 5.6.5 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.0.13 with Xdebug 2.4.1
Configuration: /home/travis/build/onoi/callback-container/phpunit.xml.dist

......Segmentation fault (core dumped)
Script phpunit -c phpunit.xml.dist handling the phpunit event returned with error code 139
```

Any idea on what causes the segmentation fault, or how to debug this?

[0] https://travis-ci.org/onoi/callback-container/jobs/178992688
[1] https://travis-ci.org/onoi/callback-container/jobs/178993629

**Comment by sebastianbergmann** [comment]
You have found a problem in the PHP runtime that leads to a segfault. An issue like this has to be reported at https://bugs.php.net/report.php using a minimal, self-contained, reproducing test case.

Please note that a test case that needs to be run through PHPUnit does not qualify as either "minimal" or "self-contained" when reporting bugs for the PHP runtime.
