### ISSUE TITLE
Why does phpunit use $this throughout instead of static

### ISSUE THREAD

**Issue by samusenkoiv** [sebastianbergmann/phpunit#2376]
Source code defines static methods, but in documentation all examples are with $this.
Why is that?

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.

**Comment by samusenkoiv** [comment]
@sebastianbergmann got it, but still. Why is that? Is that happened historically or is there any hidden sense?

**Comment by teiling88** [comment]
@samusenkoiv see https://github.com/sebastianbergmann/phpunit/issues/1914
