### ISSUE TITLE
print complete dump of "data set #N" in the failure description?

### ISSUE THREAD

**Issue by Netmosfera** [sebastianbergmann/phpunit#2391]
Would it make sense to do that? currently it's very vague, e.g.
```
1) FooTest::testWhatever with data set #0 (Bar Object (...), Foo Object (...))
```
...and not very useful. Clearly one can peek at the data set in the code, but it's a hella lot harder when the data set is generated programmatically.

Thanks.

**Comment by sebastianbergmann** [comment]
The best practice is to use an associative array and provide useful information about the data set in the key.

**Comment by Netmosfera** [comment]
i didn't know that and it's certainly something, but it would be much more comfortable if phpunit did that automatically... :-P

```
function dataProvider(){
    foreach(.....){
        yield print_r($data, true) => $data; // sorry
    }
}
```
