### ISSUE TITLE
Behavior on empty @dataProvider

### ISSUE THREAD

**Issue by ValeriyMaslenikov** [sebastianbergmann/phpunit#2392]
Hi, there are an information [here](https://phpunit.de/manual/current/en/incomplete-and-skipped-tests.html#incomplete-and-skipped-tests.skipping-tests) about: "Not all tests can be run in every environment. Consider, for instance, a database abstraction layer that has several drivers for the different database systems it supports."

I had a data provider, which behavior can be different in according to environment, so, there are right cases when it can return an empty array and I expected that the test will be skipped, or even be succeed (cause of empty data to test). 

But in the latest stable release (PHPUnit 5.7.3) I had an error like this: `Exception: Missing argument 1 for MyTest::test()`. 

I found some workarounds, like explicit test skipping, or even returning an array of `false` arguments, and checking it in the test, but it's weird.

What do you think about it?

**Comment by Netmosfera** [comment]
I agree. If there are no parameters test must not be run, IMO.
If I returned an empty array (or even null) I'd expect the tests to not be run at all, and not even marked as skipped.
