### ISSUE TITLE
Attempted to serialize unserializables (array of unserializable objects)

### ISSUE THREAD

**Issue by JanisE** [sebastianbergmann/phpunit#2393]
Hello!

I've been trying to track down the cause of many error messages like these that makes tests fail:
"Attempted to serialize unserializable builtin class SimpleXMLElement in [..] Snapshot.php on line 355"

On line 355 there is a call to `serialize` for a variable that has just before it been tested with `canBeSerialized` as serializable.

It turned out it is an instance of class "PHPExcel_Reader_Excel2007_Theme" that contains an array as a property, that in turn contains objects of class "SimpleXMLElement", which is not serializable.

I'm not sure if the tests can still be processed if there are unserializable variables involved (and I'm not sure how they're involved either), but it seems to be at least a bug of `canBeSerialized`, too. Because it may return true for variables that are actually not serializable.

Here is an example: https://3v4l.org/PED8b

P.S. I'm running the tests with PHPUnit 4.8, but I've taken a look at the latest "Snapshot.php", and there seem to be no changes in `canBeSerialized`.

**Comment by sebastianbergmann** [comment]
You can configure a blacklist for global variables that should be excluded from the backup of global state by setting [`$backupGlobalsBlacklist`](https://github.com/sebastianbergmann/phpunit/blob/5.7/src/Framework/TestCase.php#L81). The [documentation](https://phpunit.de/manual/current/en/fixtures.html#fixtures.global-state) has details on this.
