### ISSUE TITLE
AssertionError "Undefined index: file"

### ISSUE THREAD

**Issue by Fleshgrinder** [sebastianbergmann/phpunit#2394]
Handling of `AssertionError`s was introduced in 5.5 (see [this commit](https://github.com/sebastianbergmann/phpunit/commit/a1c7fea3392eda44a741b832cd0a4bd87cad14d4)) where we have the following lines of code:

```php
        } catch (AssertionError $e) {
            // ...
            $frame   = $e->getTrace()[0];
            $e = new PHPUnit_Framework_AssertionFailedError(
                sprintf(
                    '%s in %s:%s',
                    $e->getMessage(),
                    $frame['file'],
                    $frame['line']
                )
            );
        }
```

The problem is that this code is not compatible with PHP 5 and a custom `AssertionError` that is created from the assert callback feature. We have this at our company but also for instance [Drupal 8 has it](https://github.com/drupal/drupal/blob/8.0.x/core/lib/Drupal/Component/Assertion/Handle.php#L60-L65).

The first frame in such a case does not contain a `file` nor a `line` member since that one contains a closure and the second frame is the correct one. First entries from an example stack trace:

```php
$frames = $e->getTrace();
$frames[0] = [
    'function' => '{closure}',
    'args' => [
        '/path/to/file.php',
        42,
        '',
        'assertion message',
    ],
];
$frames[1] = [
    'file' => '/path/to/file.php',
    'line' => 42,
    'function' => 'assert',
    'args' => [
        false,
        'assertion message',
    ],
];
```

A simple and supposed fix for this would be to investigate if the first frame contains `{closure}` in the `function` member and then check if the next frame is from `assert`. Of course, this is no guarantee that one just found the right frame.

What do you think how we should handle this? It is definitely a bug and makes all versions that contain the current logic incompatible with code that uses custom assertion errors via callbacks paired with PHP 5.

**Comment by sebastianbergmann** [comment]
The only solution I see is to only execute the code in question on PHP 7 where `AssertionError` is a built-in class.

**Comment by Fleshgrinder** [comment]
It would definitely mitigate all possible edge cases and you can continue accessing the first frame directly since you can be sure that it has the right format. 👍

**Comment by sebastianbergmann** [comment]
Does 3ad5426acb96617b29fb9bb56301a23bd47a33be solve the issue for you?

**Comment by Fleshgrinder** [comment]
Yes, this does solve the problem nicely and kudos for being so fast in replying to tickets. 👍

**Comment by sebastianbergmann** [comment]
Thank you for the feedback.
