### ISSUE TITLE
Notice: /Applications/MAMP/htdocs/includes/../data/themedir1 is not readable in /Applications/MAMP/htdocs/wp-includes/theme.php on line 471

### ISSUE THREAD

**Issue by mobot11** [sebastianbergmann/phpunit#2397]
I keep getting this error

Notice: /Applications/MAMP/htdocs/includes/../data/themedir1 is not readable in /Applications/MAMP/htdocs/wp-includes/theme.php on line 471

 while trying to run phpunit tests on my WordPress plugin. Any idea what may be causing it?

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.
