### ISSUE TITLE
expectedException annotation does not support project classes

### ISSUE THREAD

**Issue by Kwadz** [sebastianbergmann/phpunit#2399]
The following code gives: "Class Exception\FooException does not exist"

```php
/**
 * @expectedException Exception\FooException
 */
public function test()
{
    throw new FooException;
}
```

The following code gives: "Class FooException does not exist"

```php
use Exception\FooException
/**
 * @expectedException FooException
 */
public function test()
{
    throw new FooException;
}
```

While this code works:

```php
use Exception\FooException
public function test()
{
    $this->expectException(FooException::class);
    throw new FooException;
}
```

**Comment by sebastianbergmann** [comment]
Usage of the `@expectedException` annotation requires the usage of fully-qualified class names.

**Comment by jmauerhan** [comment]
The first example appears to be a fully qualified class name, since it's the same one being used in the working code.

**Comment by Kwadz** [comment]
@jmauerhan Assuming Exception namespace is at the root, a full qualified name in this case is: `\Exception\FooException`
