### ISSUE TITLE
assertArraySubset() feature request

### ISSUE THREAD

**Issue by claudedadude** [sebastianbergmann/phpunit#2403]
$expectedArray = array(
             'id' => 1,
             'things'=> []
);

Wouldn't it be awesome if assertArraySubset took something like this as parameter TOO:

$expectedArray = array(
             'id' => type(int),
             'things'=> []
);

Just as you can expect it to return an array for 'things', it would be great to check that 'id' is int instead of a hardcoded value. This way, for big arrays, you can have all the asserts you require in one, like 10 fields to be string, three to be int, two to be boolean, five to be arrays and under these arrays check for types straight away too, huge improvement to workflow speed.

**Comment by sebastianbergmann** [comment]
I have a hard time to understand what `assertArraySubset()` is useful for to begin with, so I am sorry to say that I don't understand what you propose.

That being said, I would rather not add additional functionality to an existing assertion.
