### ISSUE TITLE
Showing version 3.6.0 after installing version 5.7.4

### ISSUE THREAD

**Issue by obihill** [sebastianbergmann/phpunit#2405]
I've installed PHPUnit 5.7.4 on a Mac OS X 10.10 using the following commands:

```
wget https://phar.phpunit.de/phpunit.phar
chmod +x phpunit.phar
mv phpunit.phar /usr/local/bin/phpunit
```

When I get the version using this command:

```
phpunit --version
```

I get this:

```
PHPUnit 3.6.0 by Sebastian Bergmann.

```

The same thing happens when I download the [latest 5.7.4 phar tarball](https://phar.phpunit.de/phpunit-5.7.4.phar).

Is this a bug?

**Comment by sebastianbergmann** [comment]
Looks like `/usr/local/bin` is not on your `$PATH`.

**Comment by obihill** [comment]
Thanks for the feedback. `/usr/local/bin` is in my `$PATH`.

However, on careful inspection, it looks like my `$PATH` has an earlier reference to the xampp `/bin` folder, which just happens to have a phpunit binary inside it. 

So I just updated `$PATH`, but it's now reporting an error which I will post in another issue.
