### ISSUE TITLE
Parse error after installing phpunit 5.7.4 on Mac OS X

### ISSUE THREAD

**Issue by obihill** [sebastianbergmann/phpunit#2406]
I installed PHP unit on Mac OS X 10.10 using the following command

```
wget https://phar.phpunit.de/phpunit.phar
chmod +x phpunit.phar
mv phpunit.phar /usr/local/bin/phpunit
```

I believe it pulls down version 5.7.4.

However, when I run `phpunit --version`, I get the following error.

```
Parse error: parse error, expecting `'&'' or `"variable (T_VARIABLE)"' in phar:///usr/local/bin/phpunit/phpunit-mock-objects/Framework/MockObject/Builder/ParametersMatch.php on line 35
```

**Comment by sebastianbergmann** [comment]
Which version of PHP are you using?

**Comment by obihill** [comment]
PHP 5.5.29

**Comment by obihill** [comment]
What's the latest version of PHPUnit that I can use with 5.5?

**Comment by GrahamCampbell** [comment]
4.8.x.

**Comment by GrahamCampbell** [comment]
The PHPUnit 5.x series is PHP 5.6, and 6.x is PHP 7.0+.

**Comment by obihill** [comment]
Ok, I just realized that 5.7.x branch is for 5.6 and above. Stepped back down to 4.8.x and it seems to be all good now. Thanks

**Comment by sebastianbergmann** [comment]
It is weird that you get that parser error instead of a "nice" error message. Here is what I get when I try to run the PHPUnit 5.7 PHAR with PHP 5.5:

```
$ wget https://phar.phpunit.de/phpunit.phar


$ php-55 phpunit.phar 
This version of PHPUnit is supported on PHP 5.6, PHP 7.0, and PHP 7.1.
You are using PHP 5.5.38 (/usr/local/php-5.5/bin/php).
```

**Comment by sebastianbergmann** [comment]
Nevermind, d548f90a46c13125c70ac916a9fc94108de6ec5e broke something.

**Comment by obihill** [comment]
Ok. I was running phpunit based on the install instructions I posted earlier, not the way you were running it.

Glad you fixed the issue.
