### ISSUE TITLE
assertEquals('0001', '1') returns true

### ISSUE THREAD

**Issue by dsech** [sebastianbergmann/phpunit#2408]
Because both '0001' and '1' are strings, I expect assertEquals('0001', '1') to return false, just like assertSame. Right now this is not the case.

I've made this pull request https://github.com/sebastianbergmann/comparator/pull/28
Please let me know if it's ok.

**Comment by sebastianbergmann** [comment]
This is expected. `assertEquals()` "wraps" around the `==` operator and `assertSame()` wraps around the `===` operator.

**Comment by dsech** [comment]
Alright, then I can continue using `assertSame()` for string comparisons.

I just thought `assertEquals` wasn't intended to follow exactly the PHP equality rules, seeing there was extra code to treat other edge cases, like "string" == 0.

Thanks

**Comment by jcrben** [comment]
Seems like the documentation could be updated as it doesn't mention that it's doing a loose comparison: https://phpunit.de/manual/current/en/appendixes.assertions.html#appendixes.assertions.assertEquals
