### ISSUE TITLE
More friendly strict coverage configuration

### ISSUE THREAD

**Issue by theofidry** [sebastianbergmann/phpunit#2413]
As of now if you are using the `@covers` with `--strict-coverage`, you get warnings for each missing `@uses` tags:

```php
/**
  * @covers \App\Dummy
  */
class DummyTestCase extends \PHPUnit\Framework\TestCase
{
    // uses `App\AnotherDummy`
}

// will throw a warning with for `App\AnotherDummy`
```

If you don't use the `--strict-coverage` you will cover pieces of code of `App\AnotherDummy` which is not what you want. So you must write your tests with the `@uses` annotations:

```php
/**
  * @covers \App\Dummy
  *
  * @uses \App\AnotherDummy
  */
class DummyTestCase extends \PHPUnit\Framework\TestCase
{
    // uses `App\AnotherDummy`
}
```

I personally find the `@uses` tags really painful to add and keep in sync with the code. Wouldn't it be possible to simplify it? To be honest I fail to see the point of having them, if I have just `@covers`, I would expect the test not to generate additional coverage for `App\AnotherDummy`, and if I did wanted to cover `App\AnotherDummy` or some of its part as well in my tests I could always add a second `@covers` tag:

```php
/**
  * @covers \App\Dummy
  * @covers \App\AnotherDummy
  */
class DummyTestCase extends \PHPUnit\Framework\TestCase
{
    // uses `App\AnotherDummy`
}
```

**Comment by sebastianbergmann** [comment]
I do not understand what you are proposing. "flexible" and "strict" contradict each other IMO.

**Comment by theofidry** [comment]
@sebastianbergmann I'm proposing to remove the need of the `@uses` tags. I'm not familiar with the internals, but right now if you have:

```
/**
  * @covers \App\Dummy
  */
class DummyTestCase extends \PHPUnit\Framework\TestCase
{
    // uses `App\AnotherDummy`
}
```

And run the tests in strict mode, you will have a warning for `App\AnotherDummy`. I don't understand why: if you want to cover `App\AnotherDummy` you could add a second tag `@covers \App\AnotherDummy`; But if you don't, why requiring the user to add a `@uses \App\AnotherDummy`?

`@uses` tags are 1. annoying to add and 2. horrible to keep in sync with the code. So my suggestions is when running the tests in strict mode, to behave as if the user added a `@uses` tag. So in the example above, instead of throwing a warning for using `App\AnotherDummy`, it would assume `App\AnotherDummy` is used, and as such is not covered by that test.

**Comment by sebastianbergmann** [comment]
If you do not want to add `@uses` annotations then don't. Just don't use strict coverage then.

**Comment by theofidry** [comment]
@sebastianbergmann I want strict coverage, I'm simply asking why it's necessary to add `@uses` tags when instead of throwing a warning for using a class/method without `@covers` or `@uses`, to assume the class/method is being used, hence no coverage should be generated for it.

**Comment by sebastianbergmann** [comment]
Is a test has `@covers` annotations then code coverage will only be processed for the units of code listed. This is unrelated to strict coverage.

**Comment by theofidry** [comment]
I'm not sure to understand. If you have:

```php
class Dummy
{
    private $dummy;

    public function __construct(AnotherDummy $dummy)
    {
        $this->dummy = $dummy;
    }

    public function foo()
    {
        return $this->dummy->foo();
    }
}

class AnotherDummy
{
    public function foo()
    {
        return 'bar';
    }
}
```

with:


```php
/**
 * @covers \Dummy
 */
class DummyTest extends \PHPUnit\Framework\TestCase
{
    public function test_foo()
    {
        $dummy = new Dummy(new AnotherDummy());

        \PHPUnit\Framework\Assert::assertEquals('bar', $dummy->foo());
    }
}
```

Then:

```
$ phpunit --strict-coverage --coverage-text --verbose
```

will produce:

```
PHPUnit 6.0.5 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.0-dev with Xdebug 2.5.0
Configuration: /path/to/project/phpunit.xml.dist

R                                                                   1 / 1 (100%)

Time: 103 ms, Memory: 6.00MB

There was 1 risky test:

1) DummyTest::test_foo
This test executed code that is not listed as code to be covered or used:
- AnotherDummy::foo

OK, but incomplete, skipped, or risky tests!
Tests: 1, Assertions: 1, Risky: 1.


Code Coverage Report:
  2017-02-06 15:18:03

 Summary:
  Classes:  0.00% (0/2)
  Methods:  0.00% (0/3)
  Lines:    0.00% (0/4)
```

I have to add `@uses \AnotherDummy` to the test case to have:

```
PHPUnit 6.0.5 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.0-dev with Xdebug 2.5.0
Configuration: /path/to/project/phpunit.xml.dist

.                                                                   1 / 1 (100%)

Time: 115 ms, Memory: 4.00MB

OK (1 test, 1 assertion)


Code Coverage Report:
  2017-02-06 15:21:16

 Summary:
  Classes: 50.00% (1/2)
  Methods: 66.67% (2/3)
  Lines:   75.00% (3/4)

Dummy
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% (  3/  3)
```

From what I understand, with strict coverage, all the class/methods used are listed, and if they are in neither `@covers` and `@uses`, a warning is thrown and that part of the code is not added to the coverage. My suggestion is to instead do as if it was listed in `@uses`.

**Comment by theofidry** [comment]
Hm, ok I may see where the confusing is coming from, if I don't run the coverage in strict mode then I only get coverage for `Dummy` which is what I want. I remember encountering the issue of having a class covered although it wasn't specified by `@covers`. But from that small case and your comments this seemed to be a bug rather than the expected behaviour.
