### ISSUE TITLE
PHPT runner does not conform to specification

### ISSUE THREAD

**Issue by vbashkirtsev** [sebastianbergmann/phpunit#2415]
In older PHPUnit PEAR PHPT runner was used. We have bunch of tests which are conforming to PHPT specification. However these tests fail under current PHPUnit because of new PHPT test runner which does not implement full PHPT specification (such as --POST-- ).

I am OK to contribute some work towards PHPT test runner which will comply with PHPT specification.

@sebastianbergmann: what is your take on this? Should PHPUnit have complete implementation of PHPT?

**Comment by sebastianbergmann** [comment]
Pull requests that expand PHPUnit's support for PHPT are welcome.
