### ISSUE TITLE
forward compatibility layer looks incomplete

### ISSUE THREAD

**Issue by garak** [sebastianbergmann/phpunit#2418]
I see that many classes are missing from [here](https://github.com/sebastianbergmann/phpunit/tree/5.7/src/ForwardCompatibility). For example, I'd need also at least `Test` and `TestSuite`.
Is there any reason preventing such classes to be added?
If not, I can provide a PR.

**Comment by sebastianbergmann** [comment]
The forward compatibility layer will not be expanded. Its goal was/is that `PHPUnit\Framework\TestCase` can be used instead of `PHPUnit_Framework_TestCase` and test listeners can be adapted.

**Comment by garak** [comment]
My use case is just about a test listener. I can extend `PHPUnit\Framework\BaseTestListener`, but I cannot use `endTest()` and `startTestSuite()` methods, since they require `PHPUnit\Framework\Test` and `PHPUnit\Framework\TestSuite` as arguments.
