### ISSUE TITLE
[Question] Running test in separate process VS default execution

### ISSUE THREAD

**Issue by gabbydgab** [sebastianbergmann/phpunit#2422]
I was trying to reduce the execution time for my test-cases by using `@runTestsInSeparateProcesses` and it seems that it takes longer than I expected versus running it by default (without `@runTestsInSeparateProcesses`); **Should it be an async process or not**? 

Running with `@runTestsInSeparateProcesses` takes **120ms** while the default takes only **53ms**

Am I missing some configuration or did not configure it correctly? I love to hear your inputs about this matter. Thanks in advance.

Sample test-cases;
### Running with `@runTestsInSeparateProcesses`: ~120ms

```php
class Process1Test extends TestCase
{
    public function testAssertTrue()
    {
        $this->assertTrue(true);
    }
}

/**
 * @runTestsInSeparateProcesses
 * @preserveGlobalState disabled
 */
class Process2Test extends TestCase
{
    public function testAssertTrue()
    {
        $this->assertTrue(true);
    }
}
```

Test output:
```
PHPUnit 5.7.5 by Sebastian Bergmann and contributors.

..                                                                  2 / 2 (100%)

**Time: 120 ms, Memory: 4.00MB**

OK (2 tests, 2 assertions)
```

### Default Execution: ~53ms

```php
class Process1Test extends TestCase
{
    public function testAssertTrue()
    {
        $this->assertTrue(true);
    }
}

class Process2Test extends TestCase
{
    public function testAssertTrue()
    {
        $this->assertTrue(true);
    }
}
```

Test output:
```
PHPUnit 5.7.5 by Sebastian Bergmann and contributors.

..                                                                  2 / 2 (100%)

**Time: 53 ms, Memory: 4.00MB**

OK (2 tests, 2 assertions)
```

**Comment by sebastianbergmann** [comment]
This is expected behavior. `@runTestsInSeparateProcesses` is about increasing test isolation and not about reducing execution time.
