### ISSUE TITLE
PHPunit error conversions and custom error_handler

### ISSUE THREAD

**Issue by krodyrobi** [sebastianbergmann/phpunit#2425]
So I'm having `auto_prepend_file=<some-php>` in my `php.ini` that is responsible for adding a custom logger using `set_error_handler` and such. 
The thing is that because this happens before phpunit has a chance to setup its own error_handler for conversions it never performs them.

The code that does this is [here](https://github.com/sebastianbergmann/phpunit/blob/5.7/src/Framework/TestResult.php#L656).

Can I somehow still get the benefits of phpunits conversion and have my custom handler unmodified, while it being loaded first?

**Comment by sebastianbergmann** [comment]
I doubt it. IMHO, `auto_prepend_file` and `auto_append_file` are "things of the past" that should not be used.
