### ISSUE TITLE
CLI issue

### ISSUE THREAD

**Issue by solleer** [sebastianbergmann/phpunit#2430]
I seem to have an issue where if I add another test to any class I get a popup that says
> CLI has stopped working

The contents of the test don't matter and nor does the location. Just adding another test function causes the issue. I have no idea why.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by solleer** [comment]
It occurs when running the tests at https://github.com/Level-2/Maphper/tree/master/tests. The problem occurs once you add 2 or more tests to the testcase. Even if the added functions are completely empty I still get the error.

**Comment by sebastianbergmann** [comment]
That is not a minimal, self-contained, reproducing test case, sorry.

**Comment by solleer** [comment]
I found the issue
