### ISSUE TITLE
assertArraySubset doesn't support ArrayAccess although it's documented

### ISSUE THREAD

**Issue by exts** [sebastianbergmann/phpunit#2431]
So I [dug into the code](https://github.com/sebastianbergmann/phpunit/blob/5.7/src/Framework/Assert.php#L63) and it looks like someone forgot to update this method when they added `ArrayAccess` support to `assertArrayHasKey` & `assertArrayNotHasKey`

**Comment by sebastianbergmann** [comment]
Can you send a pull request against `5.7` that fixes this? Thanks!

**Comment by exts** [comment]
yeah, I can do that
