### ISSUE TITLE
Show previous exceptions as well

### ISSUE THREAD

**Issue by sylfabre** [sebastianbergmann/phpunit#2437]
If a class implements the `JsonSerializable` class and a bug throws an exception A within the `jsonSerialize` method, then PHP will throw an exception B of the `Exception` class having exception A as previous exception.

But when running the test, PHPUnit only shows the last exception, followed with the trace, like this:
```
Failed calling SomeClass::jsonSerialize()
 /var/www/html/some_file.php:763
 /var/www/html/some_file.php:0
 /var/www/html/buypacker.other_file.php:309
```

It would be very useful to have
```
Failed calling SomeClass::jsonSerialize()
PreviousExceptionClass: Previous exception message
 /var/www/html/some_file.php:763
 /var/www/html/some_file.php:0
 /var/www/html/buypacker.other_file.php:309
```

Looks like this message and trace comes from `PHPUnit_Util_Log_TeamCity::getMessage` where a loop on `$e->getPreviousWrapped()` could be implemented

**Comment by sebastianbergmann** [comment]
Changes to the TeamCity logger should be reviewed/approved by @SvetlanaZem.

**Comment by SvetlanaZem** [comment]
Thank you, I have a plan to fix this issue in nearest future.

Related: https://youtrack.jetbrains.com/issue/WI-32870
