### ISSUE TITLE
How can one run all tests excluding a <pattern>, but not by a group

### ISSUE THREAD

**Issue by krodyrobi** [sebastianbergmann/phpunit#2443]
We can exclude groups, filter patterns to include them but can't exclude specific tests using a pattern.

I'm aware there is the possibility of excluding by an annotated group name, but for my use case there isn't this possibility of changing the annotations. I run tests from a 3rd party under my context and would prefer not to inject code so to have the groups ready.

I know what I'm asking is ignoring tests from the third party (ignoring is always bad) but for our specific assumptions / use cases it is sufficient and the desired outcome.

Any ideas are greatly appreciated.

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.
