### ISSUE TITLE
Possible bug in 5.7.6

### ISSUE THREAD

**Issue by Sam-Burns** [sebastianbergmann/phpunit#2444]
Hi folks,

Is it possible that there is a bug in PHPUnit 5.7.6?  I'm looking specifically at https://travis-ci.org/slimphp/Twig-View/jobs/195254174 and http://stackoverflow.com/questions/41828479/laravel-testing-undefinied-method , which both seem to be the same error and both happened within the last couple of days.

I will do some more work on this and try to come up with a more helpful bug report shortly.

**Comment by GrahamCampbell** [comment]
Duplicate of previous reports.

**Comment by GrahamCampbell** [comment]
https://github.com/sebastianbergmann/phpunit/issues/2432

**Comment by Sam-Burns** [comment]
Closing as duplicate
