### ISSUE TITLE
getMockFromWsdl() crashes if $options (= SOAP options) contains array

### ISSUE THREAD

**Issue by annicai** [sebastianbergmann/phpunit#2445]
In Generator.php and the function
```php
public function generateClassFromWsdl($wsdlFile, $className, array $methods = [], array $options = [])
```
the SOAP options are added to a string, like this:
```php
foreach ($options as $key => $value) {
       $optionsBuffer .= $key . ' => ' . $value;
}
```
However, if the options contain an array, eg. 

```php
$soap_options = array("trace" => 1,
        'soap_version' => SOAP_1_1,
        'stream_context' => stream_context_create(array(
            'ssl' => array('ciphers'=>'SSLv3', 'verify_peer'=>false, 'verify_peer_name'=>false)
        )));
```
this will cause a crash. 

Using PHPUnit 5.7.5.

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-mock-objects](https://github.com/sebastianbergmann/phpunit-mock-objects) project.
