### ISSUE TITLE
Changed the behaviour of getenv() for env values in phpunit 4.8.33

### ISSUE THREAD

**Issue by ezimuel** [sebastianbergmann/phpunit#2447]
I just discovered this [merging a PR](https://travis-ci.org/zendframework/zend-http/jobs/195535802#L206-L213) for [zendframework/zend-http](https://github.com/zendframework/zend-http).
If we have some env values in phpunit.xml, for instance:
```xml
<env name="TESTS_BASEURI" value="false" />
```
and we get this value using `getenv('TESTS_BASEURI')` in a test case, we will get the string `"false"` in 4.8.33 and an empty string in 4.8.32.
This is a potential BC break for many unit tests.

**Comment by sebastianbergmann** [comment]
This is due to #2331.

**Comment by ezimuel** [comment]
@sebastianbergmann but this a BC break, right?

**Comment by ezimuel** [comment]
@sebastianbergmann thanks for 4.8.34 realse!
