### ISSUE TITLE
Travis build fails against PHP-nightly if using PHPUnit 5.7.9

### ISSUE THREAD

**Issue by ottlinger** [sebastianbergmann/phpunit#2453]
Thanks for your work with PHPUnit

My Travis builds against latest PHP 7.2.0-dev failed after I've got the latest updates automatically:

```
PHP Fatal error:  Declaration of SebastianBergmann\Comparator
\DOMNodeComparator::assertEquals(
$expected, $actual, $delta = 0, $canonicalize = false, $ignoreCase = false) 
must be compatible with SebastianBergmann\Comparator\ObjectComparator::assertEquals(
$expected, $actual, $delta = 0, $canonicalize = false, $ignoreCase = false, array &$processed = Array) in /home/travis/build/user/project/vendor/sebastian/comparator/src/DOMNodeComparator.php on line 0

Fatal error: Declaration of SebastianBergmann\Comparator
\DOMNodeComparator::assertEquals(
$expected, $actual, $delta = 0, $canonicalize = false, $ignoreCase = false) 
must be compatible with SebastianBergmann\Comparator\ObjectComparator::assertEquals(
$expected, $actual, $delta = 0, $canonicalize = false, $ignoreCase = false, array &$processed = Array) in /home/travis/build/user/project/vendor/sebastian/comparator/src/DOMNodeComparator.php on line 0
```

Builds against:
* 5.6
* 7.0
* 7.1
* hhvm
go through successfully.

This seems to be a regression with the new build since last day's builds with PHPUnit 5.7.8 passed.

**Comment by rlerdorf** [comment]
This is a problem in Comparator. This should fix it: https://github.com/sebastianbergmann/comparator/pull/30

**Comment by sebastianbergmann** [comment]
Thank you, @ottlinger, for bringing this to my attention. I am surprised that these signature mismatches do not lead to errors in PHP < 7.2.

Thank you, @rlerdorf, for the pull request. Before I saw it I already came up with exactly the same. I am not sure, though, that I will use this approach as I might have a better idea to approach this.

**Comment by sebastianbergmann** [comment]
Closing this here as it is a bug in Comparator.

**Comment by rlerdorf** [comment]
I was running PHP 7.1.2-dev when I hit it, so it definitely leads to errors in PHP < 7.2

**Comment by sebastianbergmann** [comment]
I was not getting the error with PHP 7.1.1 but I did not try it with 7.1.2-dev.

**Comment by ottlinger** [comment]
@rlerdorf I ran into the errors via Travis
https://travis-ci.org/ottlinger/hornherzogen/builds/196234921

At the moment I disabled builds against php-nightly.

**Comment by ottlinger** [comment]
@rlerdorf @sebastianbergmann thanks for the comparator update, this seems to have fixed the issue :+1: 

https://travis-ci.org/ottlinger/hornherzogen/builds/196403076

Thanks again for the help and fast fix :-)
