### ISSUE TITLE
PHPunit throwing error 

### ISSUE THREAD

**Issue by hi2binay** [sebastianbergmann/phpunit#2457]
Hi There, 

I am trying to learn PHPUnit and going through following https://phpunit.de/manual/current/en/writing-tests-for-phpunit.html  tutorials.

Follows all step of setting phpnit.phar setup etc as per above documentation. 

When try to run the example, getting following error ......
A:\xampp\htdocs\phpunit>phpunit ./tests/DependencyFailureTest
Argument #3 (No Value) of PHPUnit_TextUI_ResultPrinter::__construct() must be a
value from "never", "auto" or "always"

Please let me know the solution or missing any kind of setup.

Thanks 
Binay Kumar

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.
