### ISSUE TITLE
Saving standard out to junit format XML report file can create invalid XML

### ISSUE THREAD

**Issue by mpandrews2000** [sebastianbergmann/phpunit#2459]
If standard out includes some binary characters, the <system-out/> element can cause an invalid XML error. It seems that PHP7's _createTextNode()_ method does not properly encode the input data.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by sebastianbergmann** [comment]
No feedback, closing.
