### ISSUE TITLE
Performance Regression in PHPUnit 6

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#2461]
## PHPUnit 5.7
```
$ time php /home/sb/phpunit-5.7.phar -c build --no-coverage --repeat 1000 > /dev/null
php /home/sb/phpunit-5.7.phar -c build --no-coverage --repeat 1000 > /dev/nul  5.22s user 0.17s system 98% cpu 5.461 total
```
## PHPUnit 6.0
```
$ time php /home/sb/phpunit-6.0.phar -c build --no-coverage --repeat 1000 > /dev/null
php /home/sb/phpunit-6.0.phar -c build --no-coverage --repeat 1000 > /dev/nul  8.28s user 0.25s system 99% cpu 8.563 total
```

**Comment by bcremer** [comment]
I measured have a huge performance impact for our unit tests:

![phpunit](https://cloud.githubusercontent.com/assets/55820/22586933/a0b5972c-e9ff-11e6-85a7-5e8837ef98cf.png)

I prepared a branch in our codebase to reproduce:

```
git clone https://github.com/bcremer/shopware.git --depth 1 -b phpunit-repro
cd shopware
php phpunit-5.7.9.phar -c tests/phpunit_unit.xml.dist
php phpunit-6.0.0.phar -c tests/phpunit_unit.xml.dist
```

**Comment by sebastianbergmann** [comment]
## PHPUnit 5.7
![phpunit_57](https://cloud.githubusercontent.com/assets/25218/22587557/6b11d4c0-ea02-11e6-81eb-894a7635b2dd.png)
## PHPUnit 6.0
![phpunit_60](https://cloud.githubusercontent.com/assets/25218/22587569/7b9610e0-ea02-11e6-923a-e238292b73a9.png)

**Comment by sebastianbergmann** [comment]
Looks like PHPUnit 6.0 performs a backup/restore of global state although it should not.

**Comment by sebastianbergmann** [comment]
@bcremer Benjamin, can you please test with 4d320a93f399c53ac54cc8cb8726b05527e7717b? Thanks!

**Comment by bcremer** [comment]
Works like a charm:

![image](https://cloud.githubusercontent.com/assets/55820/22589497/e3b21054-ea0a-11e6-8058-72588379087a.png)

Thanks @sebastianbergmann :+1:

**Comment by sebastianbergmann** [comment]
Just to be sure, I also verified it:
```
$ php phpunit-5.7.9.phar -c tests/phpunit_unit.xml.dist           
PHPUnit 5.7.9 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.1 with Xdebug 2.5.0
Configuration: /home/sb/shopware/tests/phpunit_unit.xml.dist

...............................................................  63 / 359 ( 17%)
............................................................... 126 / 359 ( 35%)
............................................................... 189 / 359 ( 52%)
............................................................... 252 / 359 ( 70%)
............................................................... 315 / 359 ( 87%)
............................................                    359 / 359 (100%)

Time: 308 ms, Memory: 24.00MB

OK (359 tests, 545 assertions)
```
```
$ php phpunit-6.0.0-6-gcaa8dc9.phar -c tests/phpunit_unit.xml.dist
PHPUnit 6.0.0-6-gcaa8dc9 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.1 with Xdebug 2.5.0
Configuration: /home/sb/shopware/tests/phpunit_unit.xml.dist

...............................................................  63 / 359 ( 17%)
............................................................... 126 / 359 ( 35%)
............................................................... 189 / 359 ( 52%)
............................................................... 252 / 359 ( 70%)
............................................................... 315 / 359 ( 87%)
............................................                    359 / 359 (100%)

Time: 302 ms, Memory: 22.00MB

OK (359 tests, 545 assertions)
```

**Comment by sebastianbergmann** [comment]
Thank you, Benjamin, for reporting this. And while debugging this I found #2462, so two for the price of one ;-)

**Comment by Bilge** [comment]
@sebastianbergmann What do you use to produce [those performance graphics](https://github.com/sebastianbergmann/phpunit/issues/2461#issuecomment-277212652)?

**Comment by sebastianbergmann** [comment]
@Bilge I use [Xdebug](https://xdebug.org/docs/profiler) to capture the raw profiling data. Then I either explore this data interactively using [KCacheGrind](https://kcachegrind.github.io/html/Home.html) or generate a visualization using [gprof2dot](https://github.com/jrfonseca/gprof2dot) and [graphviz](http://www.graphviz.org/).
