### ISSUE TITLE
[Documentation 6.0] Dbunit in or not in phar ?

### ISSUE THREAD

**Issue by lsv** [sebastianbergmann/phpunit#2464]
From the [changelog](https://github.com/sebastianbergmann/phpunit/blob/6.0/ChangeLog-6.0.md)

> DbUnit is no longer bundled in the PHAR distribution of PHPUnit

From the [documentation](https://phpunit.de/manual/6.0/en/installation.html#installation.optional-packages)

> DbUnit port for PHP/PHPUnit to support database interaction testing.
This package is included in the PHAR distribution of PHPUnit

Which is correct?

**Comment by sebastianbergmann** [comment]
The ChangeLog is correct. The documentation needs (a lot of) updating.

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-documentation](https://github.com/sebastianbergmann/phpunit-documentation) project.
