### ISSUE TITLE
Not finding any of my test cases since 6.0.* update

### ISSUE THREAD

**Issue by synackSA** [sebastianbergmann/phpunit#2465]
Hi there

For some reason, since the update to 6.0.* phpunit is not seeing my test cases. I have not made any config changes, but when I run phpunit now, it just reports that there are no tests exectuted.

Here is my phpunit.xml file

    <?xml version="1.0" encoding="UTF-8"?>
    <phpunit backupGlobals="false"
             backupStaticAttributes="false"
             bootstrap="../../../vendor/autoload.php"
             colors="true"
             convertErrorsToExceptions="true"
             convertNoticesToExceptions="true"
             convertWarningsToExceptions="true"
             processIsolation="false"
             stopOnFailure="false">
        <testsuites>
            <testsuite name="Application Test Suite">
                <directory suffix=".php">./src/tests/*</directory>
            </testsuite>
        </testsuites>
    </phpunit>

My directory structure is as follows:

    src\
    src\tests\
    src\tests\acceptance\
    src\tests\acceptance\rpc\
    src\tests\acceptance\rpc\RpcTest.php
    src\tests\integration\
    src\tests\integration\models\
    src\tests\integration\models\ModelTest.php

These tests were running 100% fine prior to the update, but now PHPUnit doesn't even seem to be able to see them at all.

Any help greatly appreciated.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by webmailcontatos** [comment]
Which class are you extending in your unit tests?

**Comment by synackSA** [comment]
I'm using the Laravel Framework 5.2 extending the following class `\Illuminate\Foundation\Testing\TestCase`, which in turn extends `PHPUnit_Framework_TestCase`

I created the following test class in `src\tests\test\DebugTest.php`

    <?php
    
    class DebugTest extends PHPUnit_Framework_TestSuite
    {
    
        public function testDebug()
        {
            $var = false;
    
            $this->assertFalse($var);
        }
    }

running `phpunit` in the same dir as my `phpunit.xml` still produces `No tests executed!`

running `phpunit src/tests/test/DebugTest.php` I get the following:

  Class 'src/tests/test/DebugTest' could not be found in '/var/www/project/dir/to/package/src/tests/test/DebugTest.php'

The file does exist in the path.

**Comment by synackSA** [comment]
I ran the command with phpunit command that comes with the composer package for laravel 5.2, which is `PHPUnit 4.8.34` and that one is finding my test cases correctly. I'm actually not sure what version I had installed with the system however, as my vagrant machine would just pull down the latest version if there was a new one. So it should have been pretty up-to-date and the last time I pushed code and ran test cases was about 2 weeks ago and it was working perfectly.

**Comment by synackSA** [comment]
I updated my composer phpunit install to `PHPUnit 5.7.9` and ran the executable from the vendor intstall and my test cases are now working as I expected them too for the most part.

**Comment by sebastianbergmann** [comment]
`PHPUnit_Framework_TestCase` does not exist anymore in PHPUnit 6.

**Comment by sonicfive** [comment]
I had the same issue. The fix was to use the correct PHPUnit version.
