### ISSUE TITLE
[RFC] Point phpunit-old.phar to version 5.7

### ISSUE THREAD

**Issue by gabbydgab** [sebastianbergmann/phpunit#2469]
The current version of the old PHAR file is 4.8.34.

### Steps to reproduce:
1. Download the old PHAR file: `wget https://phar.phpunit.de/phpunit-old.phar`
2. Check version: `php phpunit-old.phar --version`

[gabbydgab@localhost Downloads]$ php phpunit-old.phar --version
PHPUnit 4.8.34 by Sebastian Bergmann and contributors.

**Comment by sebastianbergmann** [comment]
As written in https://github.com/sebastianbergmann/phpunit/wiki/Preparing-for-PHPUnit-6, `https://phar.phpunit.de/phpunit-old.phar` will point to PHPUnit 4.8 until that link is removed.
