### ISSUE TITLE
PHPUnit\Util\Getopt uses deprecated each() function

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#2472]
The deprecation error is suppressed since 20c70e0b72eb92367d00f7e70f1ff40d12976fd8.

PHPUnit\Util\Getopt should be refactored to not use the `each()` function.

**Comment by SpacePossum** [comment]
Is anyone working on this?
I can pick it up as I would like this out of my white list of known issues on my CI env.

**Comment by sebastianbergmann** [comment]
Go for it.

**Comment by harikt** [comment]
Hey @sebastianbergmann can we back port this to 5.x ?

I was looking at the website and looks it is still supported : `Support ends on February 2, 2018` .

Let me know if I can help with or you can cherry pick and merge ?

Thank you.

**Comment by harikt** [comment]
Oh sorry about this, I noticed it was an error on my part. It was using the flag `composer update --prefer-lowest --prefer-stable` https://travis-ci.org/harikt/psr7-asset/jobs/302542260#L476 .

Thank you.
