### ISSUE TITLE
Change the test listener interface to ensure that implementations are read-only

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#2477]

**Comment by padraic** [comment]
Just a quick question. Can we assume that this level of write access would have a replacement prior to this change? Something that can be injected in, as opposed to requiring user-level editing of tests?

**Comment by sebastianbergmann** [comment]
The whole point of this is to get rid of write access. A listener should only listen, not change things around.

What kind of write access do you need, @padraic?

**Comment by padraic** [comment]
Essentially, we're doing some basic performance management applied to mutation testing: ordering test suites by execution time (though at the individual test level is beyond our current capabilities if I recall), and some test suite elimination where not relevant to a "mutated line". We can end up doing this hundreds of times (i.e. we can literally run phpunit hundreds of times), so the benefits are unique but extremely advantageous to that sort of batch running of phpunit. Hopefully that makes sense in that we wouldn't have any access per se to how the tests are written - we're just executing phpunit with some minor manipulation.

**Comment by sebastianbergmann** [comment]
Can you please open a feature request ticket for an extension point to sort `PHPUnit\Framework\TestSuite` before test execution starts? Thanks!

**Comment by padraic** [comment]
I will do @sebastianbergmann

**Comment by sebastianbergmann** [comment]
The `TestListener` interface will be deprecated (#3388) and removed (#3389) so there is no need for this.
