### ISSUE TITLE
Scalar type declaration 'void' must be unqualified

### ISSUE THREAD

**Issue by ENM1989** [sebastianbergmann/phpunit#2481]
PHP Fatal error:  Scalar type declaration 'void' must be unqualified in /vendor/phpspec/prophecy/src/Prophecy/Doubler/Generator/ClassCreator.php(49)

Version: 6.0.5

**Comment by sebastianbergmann** [comment]
This is not an issue in PHPUnit but in Prophecy. Please report it there so that @ciaranmcnulty and @everzet can take care of it.

**Comment by ENM1989** [comment]
You are right. I will report this issue for phpspec/prophecy.
