### ISSUE TITLE
Unable to extract report on risky tests

### ISSUE THREAD

**Issue by guilhermeblanco** [sebastianbergmann/phpunit#2483]
Since I upgraded to PHPUnit 6.0, a bunch of tests are now marked as risky (R).
As a user, I wanted to extract a report (similar to failures) for the risky test (ie. `--report-risky`), so I can go through them and make the necessary adjustments. Unfortunately, there's no way to see which tests are being marked as risky since `--fail-on-risky` is not working. But even if it was, it makes sense to segregate into a separate list.

**Comment by sebastianbergmann** [comment]
Run your test suite using the `--verbose` commandline option or set `verbose="true"` in your `phpunit.xml` to see details about risky tests.

`--fail-on-risky` is unfortunately broken at the moment (see #2480) but should be fixed shortly.
