### ISSUE TITLE
Travis CI fails with 6.x to The command "vendor/bin/phpunit --coverage-clover build/logs/clover.xml" exited with 1

### ISSUE THREAD

**Issue by tarlepp** [sebastianbergmann/phpunit#2488]
This seems to happen with `6.0.x` versions and not with `5.7.x`, Travis CI builds below

[phpunit 6.x](https://travis-ci.org/tarlepp/symfony-backend/builds/198973277) Fail

[phpunit 5.x](https://travis-ci.org/tarlepp/symfony-backend/builds/199096187) Success

Any idea why `phpunit --coverage-clover build/logs/clover.xml` why this happen ?

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by sebastianbergmann** [comment]
The test runner now exits with `1` (instead of `0`) when all tests pass but there are warnings (see https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-6.0.md#changed).

**Comment by tarlepp** [comment]
Aah, ok that explains that - thanks.

**Comment by Remzi1993** [comment]
@sebastianbergmann I get the same warning, is this supposed to happen?

**Comment by escopecz** [comment]
@sebastianbergmann the link you shared goes to 404 now. Do you have some details? What is considered a waring?

Is this a warning?
```
OK, but incomplete, skipped, or risky tests!
Tests: 1492, Assertions: 4406, Skipped: 1.
```
Or this?
```
THE ERROR HANDLER HAS CHANGED!
```
Or this?
```
Remaining indirect deprecation notices (2)
```
Or all of the above? Can this new behaviour be somehow turned off?

**Comment by sebastianbergmann** [comment]
PHPUnit 6 is no longer supported. Please open a new ticket in case this still applies to a supported version of PHPUnit.

**Comment by escopecz** [comment]
Here it is: https://github.com/sebastianbergmann/phpunit/issues/4004
