### ISSUE TITLE
Version 5.7.10 coverage is 3.5 times slower than 5.7.9

### ISSUE THREAD

**Issue by mbaeuerle** [sebastianbergmann/phpunit#2489]
PHP version: 7.1.1
PHPUnit version: 5.7.10

By using version 5.7.10 the generation of coverage (in this case html, but I think it does not matter) is slowed down by a factor of 3.5 in comparison to 5.7.9. 

5.7.10:

```
PHPUnit --coverage-html coverage
PHPUnit 5.7.10 by Sebastian Bergmann and contributors.

...............................................................  63 / 162 ( 38%)
............................................................... 126 / 162 ( 77%)
....................................                            162 / 162 (100%)

Time: 18.81 minutes, Memory: 100.00MB

OK (162 tests, 559 assertions)

Generating code coverage report in HTML format ... done
```

5.7.9:

```
PHPUnit --coverage-html coverage
PHPUnit 5.7.9 by Sebastian Bergmann and contributors.

...............................................................  63 / 162 ( 38%)
............................................................... 126 / 162 ( 77%)
....................................                            162 / 162 (100%)

Time: 5.43 minutes, Memory: 98.00MB

OK (162 tests, 559 assertions)

Generating code coverage report in HTML format ... done
```

**Comment by sebastianbergmann** [comment]
Is there a speed difference when no code coverage report is generated?

**Comment by mbaeuerle** [comment]
There is no significant difference.
`5.7.9` is taking 1.33 minutes, `5.7.10` is taking 1.29 minutes.

**Comment by sebastianbergmann** [comment]
Thank you. It would seem to be related to code coverage.

This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project.

**Comment by mbaeuerle** [comment]
At first I thought that, too. But in both cases phpunit-code-coverage version 4.0.5 was used. So I concluded this is an issue with phpunit.

**Comment by sebastianbergmann** [comment]
In that case it probably belongs here.

**Comment by sawmurai** [comment]
+1

**Comment by sebastianbergmann** [comment]
I cannot reproduce this.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by sawmurai** [comment]
I just tried version 5.7.9 ... slow aswell. We run tests multiple times per day. First occurance of this was on Feb, 6. Maybe that helps.

**Comment by sebastianbergmann** [comment]
What would help would be knowing the last version that is not slow and the first version that is slow.

**Comment by mbaeuerle** [comment]
Well for me the last version which was not slow was `5.7.9` , as shown above. But maybe the perfomance decreased before but not as significantly.

**Comment by sawmurai** [comment]
Yes, that is possible. I think we should focus on the difference between 5.7.9 and 5.7.10. Right now I'm testing 5.7.9 with sebastianbergmann/php-code-coverage 4.0.4 which is the last version I have logs from with a short runtime.

**Comment by sawmurai** [comment]
Good news (at least for phpunit ;) ). This PR from Symfony fixes the issue for us:

https://github.com/symfony/symfony/pull/21556/files

Seems to be unrelated to phpunit.

**Comment by mbaeuerle** [comment]
@sawmurai I was using PHP 7.1.1 for all tests from the beginning.
The tests belong to a laravel application, which uses some symfony components.
For the tests I specifically just changed the phpUnit version from 5.7.9 to 5.7.10 and did not change any other aspect of the dependencies.

**Comment by sawmurai** [comment]
Is laravel depending on the FramworkBundle of Symfony? If so you could try to limit that to version 3.2.2 as well. Maybe that resolves the issue for you, too.

**Comment by mbaeuerle** [comment]
Laravel is just depending on some packages from symfony and it seems they are already on 3.2.
From composer:
``` json
"symfony/console": "~3.2",
"symfony/debug": "~3.2",
"symfony/finder": "~3.2",
"symfony/http-foundation": "~3.2",
"symfony/http-kernel": "~3.2",
"symfony/process": "~3.2",
"symfony/routing": "~3.2",
"symfony/var-dumper": "~3.2",
```

I just retried the tests, just changing the version of phpUnit, and I still get the same results as before.

**Comment by sawmurai** [comment]
3.2 will use the current version which is 3.2.3 and which contains the bug. Can you try and replace ~3.2 with 3.2.2 and run the tests again?

**Comment by mbaeuerle** [comment]
I just tried that, but with no success, still slow with phpUnit 5.7.10 and faster with 5.7.9

**Comment by sawmurai** [comment]
Hm, that is weird. Can you upload your composer.lock so I can compare it to ours? Maybe it is some other dependency.

**Comment by mbaeuerle** [comment]
Maybe the slowdown has something to do with changing the coverage strategy?
I don't know the details of the fix for issue #2462 (which is the only change from 5.7.9 to 5.7.10) but our code coverage changes between the two versions.
5.7.9:
<img width="1154" alt="bildschirmfoto 2017-02-16 um 10 30 54" src="https://cloud.githubusercontent.com/assets/1345394/23015453/2d98d676-f433-11e6-8fe5-05570e31daf1.png">
5.7.10:
<img width="1148" alt="bildschirmfoto 2017-02-16 um 10 31 07" src="https://cloud.githubusercontent.com/assets/1345394/23015454/2d9cfb48-f433-11e6-92fe-5f00c0aaf763.png">

**Comment by sebastianbergmann** [comment]
The fix for #2462 is comprised of two commits, c9fb2d0b48755613513124516dd21dfae9fd3d08 and 631351297cd5ec850f81aecfc3ac3f3cf7c778c9. As far as I can see, these are the only changes related to code coverage between PHPUnit 5.7.9 and PHPUnit 5.7.10.

The only thing these two commits intended to change was to not fill the whitelist when one is configured but no code coverage report is to be generated, for instance when `--no-coverage` is used.

Looking at your screenshots, @mbaeuerle, the report you get with PHPUnit 5.7.9 looks wrong to me as no details are shown for `StatsController.php`. This would be correct if you have `processUncoveredFilesFromWhitelist="false"` in your `phpunit.xml`. `false` should also be the default value for this configuration option.

The report you get with PHPUnit 5.7.10 looks correct to me as there are details shown for `StatsController.php`. "Correct" assumes, of course, that you have configured `processUncoveredFilesFromWhitelist="true"` in your `phpunit.xml` (and that `StatsController.php` is not covered by any test).

**Comment by mbaeuerle** [comment]
There is something going on with the `processUncoveredFilesFromWhitelist` parameter.
In Laravel it is set to `true` by default:
``` xml
    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">./app</directory>
        </whitelist>
    </filter>
```

I haven't changed the parameter when switching phpUnit versions and running the coverage.
But for some reason in 5.7.9 not tested files are not processed but in 5.7.10 they are.

Now comes the odd part: If I use `processUncoveredFilesFromWhitelist="false"` on both versions, untested files are processed both times.  

You can see the differences in my repo where I created two fresh Laravel apps, the only difference is the version of phpUnit in composer.json:
https://github.com/mbaeuerle/phpunit-issue/tree/master/5.7.10/coverage
https://github.com/mbaeuerle/phpunit-issue/tree/master/5.7.9/coverage

**Comment by SebastianS90** [comment]
The `processUncoveredFilesFromWhitelist` option has a positive performance impact as noted [here](https://github.com/sebastianbergmann/php-code-coverage/blob/4.0.5/src/CodeCoverage.php#L1069-L1070):
> If we are processing uncovered files from whitelist, we can initialize the data before we start to speed up the tests

But due to a regression phpunit `5.7.10` does not pass this option from the xml configuration file to `php-code-coverage`. My PR #2505 should fix that.

**Comment by SebastianS90** [comment]
@sebastianbergmann thanks for the quick merge. Can you please tag `5.7.14`?

**Comment by mbaeuerle** [comment]
Thanks for the fix ! It's working fine now again!

**Comment by REBELinBLUE** [comment]
Oh god, thanks for this! I've been trying to figure out for the last week why my code coverage was taking an hour to generate, so much faster now. 🎉
