### ISSUE TITLE
Impossibility to install 6.0.6 via Composer

### ISSUE THREAD

**Issue by o5** [sebastianbergmann/phpunit#2491]
Hello,

can you force cache (or something else) in Packagist? I can't install latest tag via Composer :/

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package phpunit/phpunit ~6.0.6 is satisfiable by phpunit/phpunit[6.0.x-dev] but these conflict with your requirements or minimum-stability.
```

![screen shot 2017-02-08 at 09 12 31](https://cloud.githubusercontent.com/assets/218562/22728565/ed80ecf4-edde-11e6-8e1e-211ae060c56c.png)

Thanks

**Comment by sebastianbergmann** [comment]
I tried to manually update Packagist by clicking on the "Update" button. This resulted in an "undefined" error.

Maybe @Seldaek can help?

**Comment by peterrehm** [comment]
Looks like it is fixed meanwhile?

https://packagist.org/packages/phpunit/phpunit

<img width="1203" alt="bildschirmfoto 2017-02-08 um 09 25 56" src="https://cloud.githubusercontent.com/assets/2010989/22728914/9f256d26-ede0-11e6-8ea5-4a74f8a5586c.png">

**Comment by o5** [comment]
Yes, it is fixed from now.
