### ISSUE TITLE
Error using PHPUnit_Extensions_Database_TestCase

### ISSUE THREAD

**Issue by rbalik** [sebastianbergmann/phpunit#2497]
We've been using phpunit with dbunit to do our unit testing and recently did an upgrade from PHP5.6 to PHP7 and phpunit 5.3 to phpunit 6.0.6 and we're now getting errors when we try to run our tests.

The issue is that it can't find the PHPUnit_Extensions_Database_TestCase class which we have extended our database tests from.
This is the class name that is used on https://phpunit.de/manual/current/en/database.html

Is this still the correct class to use? I don't see it listed in the autoload_classmap.php file in the composer directory.

We've tried installing phpunit and dbunit in the local composer setup and the global composer setup and neither works. Is this a bug or are we missing something here?

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [dbunit](https://github.com/sebastianbergmann/dbunit) project.

That being said, the name of the class is now `PHPUnit\DbUnit\TestCase`.
