### ISSUE TITLE
Is '--log-json' missing in PHPUnit 6?

### ISSUE THREAD

**Issue by marekm4** [sebastianbergmann/phpunit#2499]
As mention in manual, there is option to export logs to JSON https://phpunit.de/manual/6.0/en/logging.html#logging.json but when I run `phpuint --log-json` I get `unrecognized option --log-json`.

Was this feature intentionally removed from version 6?

I am asking because NetBeans IDE 8.2 relies on this feature, so now I can't run tests from IDE directly.

**Comment by sebastianbergmann** [comment]
Yes, this was removed. See https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-6.0.md#removed

**Comment by joshuaspence** [comment]
I am curious to know the reason that this was deprecated and removed?

**Comment by vphantom** [comment]
I suspect that this might be made available through a stand-alone translating tool instead of being built-in.

**Comment by featuriz** [comment]
Any solutions for --log-json in netbeans8.2

**Comment by gedsonmarcelino** [comment]
I have same problem with this version. Someowne has any idea how to fixed it?

**Comment by black-snow** [comment]
Well, that sux
