### ISSUE TITLE
Symfony PHPUnit6 Compatibility

### ISSUE THREAD

**Issue by peterrehm** [sebastianbergmann/phpunit#2502]
I am currently wrapping my head around making Symfony fully PHPUnit 6 compatible.

Main parts are adopted now thanks to the forward compatibility layer you provided. 
https://github.com/symfony/symfony/pull/21564

Unfortunately in the Symfony Testsuite there are several other classes used which are:

````
PHPUnit_TextUI_Command
PHPUnit_Util_ErrorHandler
PHPUnit_Util_Test
PHPUnit_Framework_Error_Notice
PHPUnit_Framework_ExpectationFailedException
PHPUnit_Util_XML
PHPUnit_Framework_MockObject_Matcher
PHPUnit_Framework_Exception
PHPUnit_Framework_Error_Warning
PHPUnit_Framework_SkippedTestError
````

Would it be possible to get a PR merged with a FC layer for those classes for the versions 4 and 5?
If so I will have a look at it.

That would be the easiest to get the TestSuite updated.

**Comment by sebastianbergmann** [comment]
No, what I have done with with PHPUnit 4.8.35 (https://github.com/sebastianbergmann/phpunit/blob/4.8/ChangeLog-4.8.md#4835---2017-02-06) is as far I want to go.

**Comment by peterrehm** [comment]
I mean we adopted to that already, just those few additional classes would have helped to make Symfony entirely compatible.

**Comment by GrahamCampbell** [comment]
> just those few additional classes would have helped to make Symfony entirely compatible.

Yeh, I think that's the point @sebastianbergmann is making. The BC layer is already as large as he wants.

**Comment by peterrehm** [comment]
I understand, but havong the FC layer should add no maintanance efforts. But okay, lets see how we can work around...
