### ISSUE TITLE
PHPUnit\Framework\Error\Warning missing in PHPUnit 5.7 forward compatibility

### ISSUE THREAD

**Issue by micgro42** [sebastianbergmann/phpunit#2503]
My goal is to make the tests of DokuWiki (https://github.com/splitbrain/dokuwiki) compatible with both PHPUnit 5.7 and PHPUnit 6.0.

**The problem:**
While the basic class `PHPUnit\Framework\TestCase` is available in PHPUnit 5.7's `ForwardCompatibility`, the class `PHPUnit\Framework\Error\Warning` isn't.

**Suggested solution:**
Add the new namespaced version of deprecated(?) class-names to the `ForwardCompatibility` of PHPUnit 5.7

**Alternative Solution:**
Add a `BackwardCompatibility` directory to PHPUnit 6 with the old class-names of PHPUnit 5.7 

**Downstream Issue:** splitbrain/dokuwiki#1837

**Comment by sebastianbergmann** [comment]
The existing forward compatibility layer in PHPUnit 4.8 and PHPUnit 5.7 will not be expanded.

A backward compatibility layer will not be added to PHPUnit 6.

**Comment by micgro42** [comment]
That is unfortunate. Would a PR be welcome/considered or are there conceptual reasons behind this decision?

**Comment by luckydonald** [comment]
So `PHPUnit_Framework_Error_Warning` simply is `PHPUnit\Framework\Error\Warning` now.
