### ISSUE TITLE
Missing typehints on PHPUnit_Framework_MockObject_MockObject

### ISSUE THREAD

**Issue by cdekok** [sebastianbergmann/phpunit#2507]
I don't have autocomplete support for the PHPUnit_Framework_MockObject_MockObject return type things like..

```php
$users = $this->createMock(UserRepo::class);        
$users->method('getUserByLogin')->willReturn(null);
```

Will work but my phpstan complains that the method function does not exists i also don't have any auto completion in my ide.
It would be nice if the available methods would be documented in the interface.

This is for phpunit 6

**Comment by sebastianbergmann** [comment]
Use
```php
/** @var PHPUnit_Framework_MockObject_MockObject|UserRepo $users */
$users = $this->createMock(UserRepo::class);
```
and your IDE will be happy.

**Comment by cdekok** [comment]
That won't work it does not have completion on `method` or `willReturn` as they are not in the returned interface.

I notice now that it's in it's own repo btw so the issue probably belongs there.
https://github.com/sebastianbergmann/phpunit-mock-objects/blob/79d768f1dd5f1416d577e4855d7cfbeac044c42b/src/MockObject.php

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-mock-objects](https://github.com/sebastianbergmann/phpunit-mock-objects) project.

**Comment by pavarnos** [comment]
I use http://confluence.jetbrains.com/display/PhpStorm/PhpStorm+Advanced+Metadata

```php
namespace PHPSTORM_META {
    override(\PHPUnit_Framework_TestCase::getMockBuilder(0),
             map(['' => '@|\PHPUnit_Framework_MockObject_MockObject']));
    override(\Mockery::mock(0),
             map(['' => '@']));
}
```
