### ISSUE TITLE
Getting started has example for PHP 5.6 but it doesn't work

### ISSUE THREAD

**Issue by malaire** [sebastianbergmann/phpunit#2524]
Page https://phpunit.de/getting-started.html has example for PHP 5.6 but it doesn't work because download instructions on that same page instructs to download phpunit which only supports PHP 7.

Either remove that example or provide instructions on how to download phpunit for PHP 5.6.

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-website](https://github.com/sebastianbergmann/phpunit-website) project.
