### ISSUE TITLE
Setting ini inside xml configuration file

### ISSUE THREAD

**Issue by Dylan-DPC** [sebastianbergmann/phpunit#2525]
PHP version: 7.0.16+deb.sury.org~trusty+1 (ubuntu 14.04)
PHPUnit version: 5.7.14

Hey

I am setting the following in my `phpunit.xml` : 
```
<includePath>.</includePath>
      <ini name="upload_max_filesize" value="1M"/>
      <ini name="post_max_size" value="4M"/>
      <ini name="file_uploads" value="On"/>
      <ini name="memory limit" value="64M"/>
  </php>
```
but I am still get this error while uploading a photo: 
> The file "photo.jpg" exceeds your upload_max_filesize ini directive (limit is 0 KiB).

Any help would be appreciated :smiley:

**Comment by sebastianbergmann** [comment]
AFAIK, `upload_max_filesize` cannot be set using `ini_set()`.

**Comment by Dylan-DPC** [comment]
Oh k. Solved the issue. The error was in one of the inputs. Thanks :)
