### ISSUE TITLE
no errors reported from dataProviders when using --filter argument

### ISSUE THREAD

**Issue by Gamesh** [sebastianbergmann/phpunit#2526]
the original issue was reported for phpunit 4.8 #1669 but was never resolved.

if phpunit is run with --filter argument and an exception is thrown in dataProvider phpunit outputs that no tests where executed but does not report what was wrong or what exception occurred:
```
phpunit --filter attendancesGet --stop-on-failure Tests/Integration/ApiSpecTest.php
PHPUnit 6.0.6 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.2-2+0~20170218111804.16+jessie~1.gbpb36eec
Configuration: /code/in/phpunit.xml.dist
Error:         No code coverage driver is available

Time: 1.88 seconds, Memory: 116.41MB

No tests executed!
```
if the same test suite is run without filter it's reported as a warning:

```
phpunit --stop-on-failure Tests/Integration/ApiSpecTest.php
PHPUnit 6.0.6 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.2-2+0~20170218111804.16+jessie~1.gbpb36eec
Configuration: /code/in/phpunit.xml.dist
Error:         No code coverage driver is available

IW                                                                  2 / 2 (100%)

Time: 20.39 seconds, Memory: 116.41MB

There was 1 warning:

1) Warning
The data provider specified for Tests\Integration\ApiSpecTest::testAllApiEndpoints is invalid.
```

**Comment by chrisguitarguy** [comment]
I wrote a regression test for this: https://github.com/chrisguitarguy/phpunit/commit/68a9700637ad553028fdf7ac38a049623c35fd0c (and submit a PR with it, @sebastianbergmann, if you think it's relevant).

But I'm not able to reproduce your issue. The only way I can reproduce it is if the `--filter` argument doesn't actually match any tests. Then PHPUnit reports no tests executed and no data provider warnings. This seems like the correct behavior -- can't report an error thrown by a data provider that was never called.

I'm guessing that's what you're running into? `testAllApiEndpoints`, the test that produced the warnings isn't matched by the `--filter attendancesGet` argument.

**Comment by Gamesh** [comment]
you are right, the filter is used to match the raml file which is loaded by the data provider, but not an actual test, that's why we specify the test file as the last argument.
there is no way to report a problem from dataProvider, $this->fail() or throwing an exception don't create any output.

**Comment by sebastianbergmann** [comment]
Sorry for not looking at this sooner. Do I understand the comments correctly that this can be closed?

**Comment by Gamesh** [comment]
@sebastianbergmann if inability to call $this->fail() or throw an exception from dataProvider is normal and expected behavior than - yes. 
Ideally i would like phpunit to at least render an exception or some output with an error.
