### ISSUE TITLE
Documented option '--log-tap' missing from version 6.0.7

### ISSUE THREAD

**Issue by vphantom** [sebastianbergmann/phpunit#2528]
Hello,

Similarly to #2499, it appears that `--log-tap` and `--tap` are missing from version 6.0.7.  I came to PHPUnit looking for a TAP-producing unit testing framework in PHP, and mistakenly thought I found it based on the 6.0 documentation's [chapter 3](https://phpunit.de/manual/current/en/textui.html) and [chapter 13](https://phpunit.de/manual/current/en/logging.html) which feature TAP output.

Is the documentation is simply a bit behind, or are these features expected to be resurrected in 6.1?

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-documentation](https://github.com/sebastianbergmann/phpunit-documentation) project.

**Comment by vphantom** [comment]
Sorry about that.  Based on #2499 I thought maybe this was a transitional feature change (i.e. migrating to a stand-alone executable, not removed entirely).
