### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by yurii-github** [sebastianbergmann/phpunit#2529]
regards for test framework

I would like to ask for versioning on url request. My current problem was on relying 
https://phar.phpunit.de/phpunit.phar , so after new 6 version came out CI started to fail.
Is it possible to make something like 
https://phar.phpunit.de/phpunit-5.x
https://phar.phpunit.de/phpunit-5.x.phar
to work? So we will be able to get updated version on CI and no composer.
Maybe it is already like this, I don't know.
Surely, I can make parser for https://phar.phpunit.de/ as last resort. 

regards

**Comment by sebastianbergmann** [comment]
This is already implemented.

`https://phar.phpunit.de/phpunit-5.7.phar`, for instance, redirects to the latest PHPUnit 5.7 release.

**Comment by yurii-github** [comment]
thanks!
