### ISSUE TITLE
Static methods called dynamically in documentation

### ISSUE THREAD

**Issue by BenMorel** [sebastianbergmann/phpunit#2532]
In PHPUnit, all assertions are static methods:

    public static function assertTrue($condition, $message = '')

But the [documentation](https://phpunit.de/manual/current/en/writing-tests-for-phpunit.html#writing-tests-for-phpunit.examples.DependencyFailureTest.php) has always suggested to call them dynamically:

    $this->assertTrue(false);

And most of the tests I've seen have been following this convention so far (including mine).

It doesn't seem to be a problem for PHP, which doesn't complain in any error reporting mode; but in addition to being a code smell, this approach triggers the static code analysis tools of my IDE, which keeps complaining about static methods called dynamically.

Is there any reason why the documentation shows dynamic calls to the assertion methods?

The whole documentation could be re-written in the following manner:

    self::assertTrue(false);

Is there any reason not to?

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.

**Comment by BenMorel** [comment]
This was a preliminary question to offer a contribution to the documentation, but it was seemingly misunderstood.

I wish you well.

**Comment by hboomsma** [comment]
@BenMorel see #1914

**Comment by BenMorel** [comment]
@hboomsma Thanks for the pointer!
