### ISSUE TITLE
Display is manipulating numbers

### ISSUE THREAD

**Issue by kevintweber** [sebastianbergmann/phpunit#2534]
Given the following setup:

`Generated by php-code-coverage 4.0.6 using PHP 7.0.15-0ubuntu0.16.04.2 with Xdebug 2.4.0 and PHPUnit 5.7.14 at Fri Feb 24 19:50:00 UTC 2017.`

with the following test case:

```php
<?php

use PHPUnit\Framework\TestCase;

class ExampleTest extends TestCase
{
    public function testExample()
    {
        $this->assertEquals(555.54, 555.54);
        $this->assertEquals(556.54, 555.54);
    }
}
```

gives the following output:

```php
PHPUnit 5.7.14 by Sebastian Bergmann and contributors.

F                                                                   1 / 1 (100%)

Time: 44 ms, Memory: 4.00MB

There was 1 failure:

1) ExampleTest::testExample
Failed asserting that 555.53999999999996 matches expected 556.53999999999996.
```
---
Obviously, both the passing test and the failure are correct.  However, the failure message threw me for a loop.  It took me a bit to determine the bug was something internal to PHPUnit.

Good luck!

Kevin

**Comment by sebastianbergmann** [comment]
There is nothing wrong here. Please read http://floating-point-gui.de/.
