### ISSUE TITLE
Use of 'use function' construct disables code coverage analysis

### ISSUE THREAD

**Issue by MadEgg** [sebastianbergmann/phpunit#2535]
I have a file that imports a function using the 'use function namespace/function' construct. 

This line prevents code coverage from working - all lines are white in the final report and the file is completely ignored. It doesn't even matter if the imported function is actually used in the code or not - it seems the code coverage system chokes on the 'use function' construction. Simply removing the line with 'use function' makes it generate code coverage information again.

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project.
