### ISSUE TITLE
Extract coverage from a PHPUnit_Framework_TestListener

### ISSUE THREAD

**Issue by pavarnos** [sebastianbergmann/phpunit#2539]
Is there a way to create a TestListener that can access the coverage summary at the end of the last suite (if not null) so i can write the log directly? Something like

```php
    public function endTestSuite(PHPUnit_Framework_TestSuite $suite)
    {
        if ($suite->getName() != self::SUITE_TO_LOG) {
            return;
        }
        // magically get $coverage from somewhere
        $report = $coverage->getReport();
        $output = [
            'Methods'        => $report->getNumMethods(),
            'Tested Methods' => $report->getNumMethods(),
            'Lines'          => $report->getNumExecutableLines(),
            'Tested Lines'   => $report->getNumExecutedLines(),
        ];
        $this->appendToReport($output);
    }
```

I've spent a few hours digging around in the code, but cannot find a way to get the global $result (which has the coverage attached) from the test suite...

Background:
Running tests with coverage takes a long time, so i don't do it often. When I do, I want to log some summary stats for later display so managers can see coverage increasing over time.

Currently the only way I can see to do this is adding a command line or config parameter to print a coverage report, then write some code to parse the report and extract the numbers i need. This seems brittle. And it is inconvenient: phpStorm has a "Run With Coverage" button but does not appear to a way to add --coverage-text (for example) so i need to have multiple configs or other extra mess. I need to make this simple for other developers...

**Comment by sebastianbergmann** [comment]
This is currently not possible and, to be honest, does not make sense / lies outside the scope of PHPUnit.

If you want to show coverage increase over time then the best way is to generate Clover XML and feed that into Jenkins, for instance. Or keep the Clover XML logfiles of individual runs and parse the information from them to create a chart.

**Comment by pavarnos** [comment]
thanks for the quick and helpful reply.

What do you think about making pluggable CoverageListener s? 
It would extract some repeated code from TextUI/TestRunner and allow other coverage listeners to be dynamically added the same way TestListeners currently are: so third party coverage listeners can be easily added.

**Comment by floplus** [comment]
Stumbled upon this ticket, because i have phpunit run in a docker container which has different paths than the local dev setup. To have the IDE pick up the right paths i want to change the paths in the created clover xml report. a listener would be helpful...

**Comment by pavarnos** [comment]
I thought the refactoring itself would be quite simple (at a quick naive first look):
- create a standard interface for code coverage Reports https://github.com/sebastianbergmann/php-code-coverage/tree/master/src/Report
- make these pluggable following the pattern used in other places in phpUnit

The Reports already appear have a pretty standard set of methods, so should not be too hard to extract an interface. Some setter injection of options post construction to handle the specifics for each existing driver will be needed, but thats no problem because the code is already in place for that. In most cases it is just a wee bit of shuffling things around.

The xml config file and command line infrastructure are excellent already and could hopefully be generalised / extended fairly easily to allow new coverage drivers to be loaded.

I thought the biggest challenge will be doing this over a series of small refactorings and the backwards compatibility breaks involved across two separate packages.
