### ISSUE TITLE
v4.8.35: assertEquals makes all tests unavailable

### ISSUE THREAD

**Issue by igronus** [sebastianbergmann/phpunit#2540]
I have working test.

![2017-03-02 11-59-52](https://cloud.githubusercontent.com/assets/4248701/23500471/47257388-ff41-11e6-87f7-2649b7d2d9d8.png)
![2017-03-02 12-00-16](https://cloud.githubusercontent.com/assets/4248701/23500472/473e8238-ff41-11e6-9a45-c2d128777c5e.png)

After changing assertNotEquals to assertEquals no tests are executed:

![2017-03-02 12-00-41](https://cloud.githubusercontent.com/assets/4248701/23500475/474e0258-ff41-11e6-8647-5fc6d8771c7c.png)
![2017-03-02 12-00-58](https://cloud.githubusercontent.com/assets/4248701/23500474/474d68ca-ff41-11e6-909c-9ca332ac1c4a.png)

PHPUnit is installed via composer update from this composer.json:

```
{
  "require": {
    "phpunit/phpunit": "*",
    "php": ">=5.3.17"
  }
}
```

What's happening?

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

Please do not post screenshots of code but instead post code as text (using proper markup).

**Comment by igronus** [comment]
I've found that this problem is about old php constructor. When class name and method name are the same, i doesn't create TestCase with it's constructor but creates TestCase with method's code.

```
class TestRegistration extends PHPUnit_Framework_TestCase {
    // phpUnit: No tests executed!
    function testRegistration() {
        $this->assertNotEquals(0, 0);
    }
}
```

If class name and method name are different, it works.

```
class TestRegistration extends PHPUnit_Framework_TestCase {
    // phpUnit: There was 1 failure
    function testRegistrationAnotherName() {
        $this->assertNotEquals(0, 0);
    }
}
```

So... This is not bug of PHPUnit. 

And the only question is why it worked in some cases and stopped working when different assertions are used.
