### ISSUE TITLE
@depends mantains objects instance

### ISSUE THREAD

**Issue by lcjury** [sebastianbergmann/phpunit#2542]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.0.7
| PHP version         | 7.0.16
| Installation Method | Composer

I have a method who test for an empty stack

    public function testEmpty() {
        $stack = new Stack();
        $this->assertEquals($stack->size(), 0);
        return $stack;
    }

and other method who `depends` on `testEmpty()` and have the a `dataProvider`

    public function testPushOnDifferentStacks($element, Array $stack, Array $emptyStack) {                                                                                                                
        $emptyStack->push($element);
        //The Stack class have a private internal array named data
        $this->assertAttributeEquals($stack, 'data', $emptyStack);
    }

And this is the `dataProvider`

    public function nonEmptyStacks() {
        return [
            'Stack with One' => [1, [1]],
            'Stack with null' => [null, [null]],
            'Stack with string' => ['hello World!', ['hello World!']]
        ];
    }

Now, the PushOnDifferentStacks test fails becouse $emptyStack instance is shared between the different test's, I expect that each execution of testPushOnDifferentStacks use a new instance of `emptyStack`. 

If instead of using the Stack object I use a plain Array (and replace push with array_push) the test pass without errores. It looks a bit inconsistent.

**Comment by sebastianbergmann** [comment]
I was just about to write that in this comment ;-)
