### ISSUE TITLE
whitelist / inconsistent coverage, problem with namespaces?

### ISSUE THREAD

**Issue by ludwig-gramberg** [sebastianbergmann/phpunit#2549]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.0
| PHP version         | 7.0.16
| Installation Method | Composer

Hi,
I get an inconsistent coverage report and couldn't find anything about this on the net.
The problem is the coverage looks incomplete, it seems to correctly recognize coverage of methods, but doesn't correctly aggregate the stats to the top.

![bildschirmfoto_2017-03-03_um_21_32_16](https://cloud.githubusercontent.com/assets/2245065/23568162/a8209c26-0059-11e7-8efa-c79bc1ecfcf8.png)

If I go a/any lever higher, I get 0/0

![bildschirmfoto_2017-03-03_um_21_32_45](https://cloud.githubusercontent.com/assets/2245065/23568200/c40ec4bc-0059-11e7-8d49-cb4174261df9.png)

hope you can help and point me in the right direction, otherwise this is a bug report ;-)

my phpunit.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit bootstrap="/var/www/project/dev/vendor/autoload.php">
    <testsuites>
        <testsuite name="API Test Suite">
            <directory suffix=".php">/var/www/project/dev/tests/</directory>
        </testsuite>
    </testsuites>
    <logging>
        <log type="coverage-clover" target="../log/coverage.xml" />
        <log type="coverage-html" target="../log/coverage" />
        <log type="coverage-text" target="php://output" />
    </logging>
    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">/var/www/project/app/lib</directory>
            <directory suffix=".php">/var/www/project/app/module</directory>
        </whitelist>
    </filter>
</phpunit>
```

xdebug.ini:

```
xdebug.max_nesting_level = 1000
xdebug.profiler_enable=1
xdebug.default_enable=1
xdebug.remote_host=192.168.200.1
xdebug.remote_enable=1
xdebug.remote_connect_back=1
xdebug.idekey=MY_IDE_KEY
xdebug.remote_autostart=1
xdebug.coverage_enable=1
```

phpunit command:

```
/usr/bin/php /var/www/project/dev/vendor/phpunit/phpunit/phpunit --configuration /var/www/project/dev/phpunit.xml --teamcity
```

**Comment by ludwig-gramberg** [comment]
using xdebug 2.5.1 its "solved" but now i get 0% coverage which is incorrect (code is being run and output is being generated)

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project.

**Comment by ludwig-gramberg** [comment]
yes, and also it was all my own fault :-/

i wrote a unit-test which was calling an api over http, so of course it can't collect coverage when whats being tested is executed outside the phpunit-run

sry for wasting your time
