### ISSUE TITLE
PHPT test case name is file name instead of test name

### ISSUE THREAD

**Issue by Bilge** [sebastianbergmann/phpunit#2553]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 5.7.15
| PHP version         | 7.1.0
| Installation Method | Composer

[PHPT requires a TEST section that describes the test](http://qa.php.net/phpt_details.php#test_section). This should be used as the display name for the test, but instead, the filename is used and the TEST section isn't even parsed by `PHPUnit_Extensions_PhptTestCase`.

**Comment by Bilge** [comment]
Something else to consider: is the "name" of a test case used to `--filter` against? If so, changing it would be a BC-breaking change.

**Comment by leedwilkins** [comment]
The convention used for the TEST section is that it describes what is implemented for the test. The name of the test should remain the name of the file (as is also a convention for all other tests). The filename identifies where the issue originates, and from there you can see (via the TEST section) what was called. Given that, and the point that --filter is based on the filename, I belive that this should remain as it is.

**Comment by sebastianbergmann** [comment]
I agree with @leedwilkins that the filename should be used as the name of the test.
