### ISSUE TITLE
PHPUnit manual command line options "--report-useless-tests" vs. "--dont-report-useless-tests"

### ISSUE THREAD

**Issue by reinholdfuereder** [sebastianbergmann/phpunit#2555]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.x

See https://phpunit.de/manual/current/en/textui.html#textui.clioptions

At the top it correctly mentions the new option:
> Test Execution Options:
> 
>   --dont-report-useless-tests Do not report tests that do not test anything.

But further down it then explains the old option:
> --report-useless-tests
>  Be strict about tests that do not test anything. See Chapter 6 for details.

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-documentation](https://github.com/sebastianbergmann/phpunit-documentation) project.

**Comment by reinholdfuereder** [comment]
Oops, sorry: I'll file this minor issue there then...
