### ISSUE TITLE
Custom printer configuration

### ISSUE THREAD

**Issue by Bilge** [sebastianbergmann/phpunit#2557]
There is currently no mechanism by which custom configuration can be passed to custom printer implementations. The printer receives some configuration, but only the prescribed parameters supported by PHPUnit, such as the debug flag and whether to use colours.

Since a printer may implement many features, a user may wish to further customize the printer to turn on or off the particular features of that printer they do or not not want to use. However, PHPUnit provides no such mechanism to enable the printer to receive custom configuration.

This ticket proposes to allow specifying custom printer configuration directly in the `phpunit.xml` file in a free-form manner specific to whichever printer implementation the user chooses to use. That is, the specific options would be undefined and implementation-dependant based on the printer implementation chosen by the user.

In this way we can create a single custom printer implementation that supports many different user needs instead of having to fork the same printer as many times as there are users with different combinations of preferences.

**Comment by Bilge** [comment]
I think this is still an important issue.

**Comment by epdenouden** [comment]
@Bilge Certainly a good idea! With so many printers already out there and the new `Extension` interface being preferred for future versions, it might be a bigger project though. It would take quite a bit of effort. Perhaps you can do a prototype pull request of what you want? ;-)

**Comment by prisis** [comment]
Is there still some interest in this ticket?

**Comment by bghira** [comment]
yes
