### ISSUE TITLE
Allow for simple static class properties as data providers

### ISSUE THREAD

**Issue by direvus** [sebastianbergmann/phpunit#2561]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | any
| PHP version         | any
| Installation Method | any

Many data provider methods just return a static map-of-arrays.  Writing a method that does nothing except return a static value adds boilerplate with no improvement to readability or functionality.

Where a data provider is a simple static value, it would be nice to just declare it as a class property.

Consider this example from the documentation:

```
class DataTest extends TestCase
{
    /**
     * @dataProvider additionProvider
     */
    public function testAdd($a, $b, $expected)
    {
        $this->assertEquals($expected, $a + $b);
    }

    public function additionProvider()
    {
        return [
            'adding zeros'  => [0, 0, 0],
            'zero plus one' => [0, 1, 1],
            'one plus zero' => [1, 0, 1],
            'one plus one'  => [1, 1, 3]
        ];
    }
}
```

If PHPUnit allowed properties to be providers, this could be written more succinctly:

```
class DataTest extends TestCase
{
    /**
     * @dataProvider additionProvider
     */
    public function testAdd($a, $b, $expected)
    {
        $this->assertEquals($expected, $a + $b);
    }

    public static $additionProvider = [
            'adding zeros'  => [0, 0, 0],
            'zero plus one' => [0, 1, 1],
            'one plus zero' => [1, 0, 1],
            'one plus one'  => [1, 1, 3]
        ];
}
```

This pattern also has the nice side-effect that all tests are methods and all methods are tests.

If this suggestion is acceptable, I would be happy to prepare a PR.  Thanks for your time.

**Comment by mcustiel** [comment]
The same can be rewritten this way:
```
class DataTest extends TestCase
{
    public static $additionProviderValues = [
            'adding zeros'  => [0, 0, 0],
            'zero plus one' => [0, 1, 1],
            'one plus zero' => [1, 0, 1],
            'one plus one'  => [1, 1, 3]
     ];

    /**
     * @dataProvider additionProvider
     */
    public function testAdd($a, $b, $expected)
    {
        $this->assertEquals($expected, $a + $b);
    }

    public function additionProvider()
    {
        return $this->additionProviderValues;
    }
}
```

Or also:

```
class DataTest extends TestCase
{
    const ADDITIONAL_PROVIDER_VALUES = [
            'adding zeros'  => [0, 0, 0],
            'zero plus one' => [0, 1, 1],
            'one plus zero' => [1, 0, 1],
            'one plus one'  => [1, 1, 3]
     ];

    /**
     * @dataProvider additionProvider
     */
    public function testAdd($a, $b, $expected)
    {
        $this->assertEquals($expected, $a + $b);
    }

    public function additionProvider()
    {
        return self::ADDITIONAL_PROVIDER_VALUES;
    }
}
```
As you can see we have several different ways of defining the values: methods, properties (static or not) and constants, they could even be callables from other classes (static or not). And I guess that if we support one, eventually we should support all, and trying to support all of them in the annotation would make performance suffer, since we are parsing the docblock comment of the test method and trying to detect what kind of provider are we defining..

**Comment by direvus** [comment]
Thanks for your reply @mcustiel.  I understand that a provider method can just return a property or const, but that's still the kind of pointless boilerplate method composition that I'm objecting to here.  The method still has no proper reason for existing, other than catering to the limitations of `dataProvider`.

I agree that if we support static properties, it makes sense to also support class constants and ordinary properties.  I'm less convinced about the case for generic callable support, but maybe somebody out there would have a use for that.

If there is a significant performance penalty, that would indeed be a fair reason for rejecting this feature, but I would find that surprising.  I'm curious about that now, so I might just write up a patch for the feature and run some performance testing.  I'll get back to you with the results.

**Comment by direvus** [comment]
Okay, I've run some performance tests, using PHPUnit's own unit tests, and PHPUnit's own timing data, 300 runs on master as of 253f1d2 and 300 runs on my branch, with static properties, non-static properties, and class constants supported for data providers.  In summary:

Revision | Fastest | Slowest | Mean | σ
----|----|----|----|----
sebastianbergmann/phpunit@253f1d2 | 10.93 | 11.10 | 10.9737 | 0.02649
direvus/phpunit@26a7a22 | 10.95 | 11.07 | 10.9842 | 0.01894

I'd say that a loss of ~10ms over 2778 assertions is not a problem.  In the case where the dataProvider annotation matches a method, the only difference in the code path is one execution of ReflectionClass->hasMethod().

Does this seem reasonable?  If so, I will go ahead and create a PR from my branch.

**Comment by mcustiel** [comment]
That's awesome! Please feel free to submit a PR.

**Comment by sebastianbergmann** [comment]
I understand that you are "objecting" to the "boilerplate method composition" that goes along with `@dataProvider` usage. Please understand that I think this approach is preferable over too many different options to achieve the same effect.

**Comment by direvus** [comment]
Well, I obviously don't agree and I'm disappointed by your response, but thanks for your time anyhow.
