### ISSUE TITLE
File / Class exceptionally removed / not showing up in coverage report

### ISSUE THREAD

**Issue by jankal** [sebastianbergmann/phpunit#2564]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.0.8
| PHP version         | PHP 7.0.6 (cli) (built: Apr 28 2016 14:12:14) ( ZTS ) Copyright (c) 1997-2016 The PHP Group Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies    with Xdebug v2.5.1, Copyright (c) 2002-2017, by Derick Rethans
| Installation Method | Composer

I recently started jankal/checked-instance where I'm now using PHPUnit for Unit Tests and Coverage.

With the first tests and features I archieved 100 % coverage on both source files (`Factory.php, Instance.php`).

After jankal/checked-instance@c02a9a7ed125c84f16a7ff0914de62998a0243fd the coverage for `Factory.php` was not displayed in my IDE anymore and the clover report contained `<metrics ... classes="0"...>` for the file.

Why is PHPUnit not generating a coverage report for `Factory.php` anymore?

It still worked fine with jankal/checked-instance@0175b71

Coverage on coveralls: [![Coverage Status](https://coveralls.io/repos/github/jankal/checked-instance/badge.svg?branch=master)](https://coveralls.io/github/jankal/checked-instance?branch=master)
Build on TravisCI: [![Build Status](https://travis-ci.org/jankal/checked-instance.svg?branch=master)](https://travis-ci.org/jankal/checked-instance)

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project.

**Comment by jankal** [comment]
Thanks @sebastianbergmann
