### ISSUE TITLE
Your HHVM version does not satisfy that requirement

### ISSUE THREAD

**Issue by antoine-pous** [sebastianbergmann/phpunit#2578]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.0.9
| PHP version         | HHVM
| Installation Method | Composer (Travis-CI)

When i run my units tests with Travis each time i got this message:
`phpunit/phpunit 6.0.9 requires php ^7.0 -> your HHVM version does not satisfy that requirement.`

I use trusty dist but nothing change. Anybody got tips about this problem?

**Comment by sebastianbergmann** [comment]
Sorry, but I cannot help you. PHPUnit is not supported on HHVM. Please open a ticket with the vendor of that alternative runtime for PHP.
