### ISSUE TITLE
Jenkins CI groups all PHPUnit test results in a single package

### ISSUE THREAD

**Issue by TK-999** [sebastianbergmann/phpunit#2579]
When executing PHPUnit tests using Jenkins CI and the JUnit output format, all PHPUnit tests are grouped up in a single package (root). This is because Jenkins groups tests into packages by parsing the optional `classname` attribute of `<testcase>` elements, and interpreting it as a fully-qualified name in the form of `packageName.className`. Since PHPUnit only adds a `class` attribute, there is no information available to Jenkins with which it could group tests, which can lead to test results quickly becoming unmanageable given a large enough test set.

This is probably as much of a Jenkins CI issue as it is a PHPUnit one, but since Jenkins CI is a relatively popular CI system (and has its own [semi-official PHPUnit template](http://jenkins-php.org/)), I'd like to ask if you guys think this is something worth working on. A `classname` attribute could be generated based on parent testsuite name, file path, or class namespace (if any). I could prepare a PR with one of the above implementations.

Thank you for your time, and thank you for PHPUnit :)

**Comment by sebastianbergmann** [comment]
Are you saying that PHPUnit should emit `class="vendor.project.FooTest` instead of `class="vendor\project\FooTest`?

**Comment by TK-999** [comment]
Yes, exactly. :)

**Comment by sebastianbergmann** [comment]
Thanks!

**Comment by TK-999** [comment]
Thanks for the quick response Sebastian, much appreciated! :)
