### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by Achilles-96** [sebastianbergmann/phpunit#2580]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 4.8.35
| PHP version         | 7.0.15
| Installation Method | Composer

I am getting error on running phpunit: `TypeError: Argument 1 passed to PHPUnit_Extensions_Selenium2TestCase_Element::fromResponseValue() must be of the type array, null given, called in $PROJ_DIR/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Element/Accessor.php on line 137`

**Comment by Achilles-96** [comment]
I noticed that it is giving 403 in `postCommand` function in `phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/CommandsHolder.php`

**Comment by Achilles-96** [comment]
This is the `var_dump($response)` - http://pastebin.com/xURH6Fpn

**Comment by sebastianbergmann** [comment]
PHPUnit 4.8 is no longer supported and this issue tracker is not the correct one for issues related to the [phpunit-selenium](https://github.com/giorgiosironi/phpunit-selenium) extension.
