### ISSUE TITLE
PHPUnit namespace causes error

### ISSUE THREAD

**Issue by samayo** [sebastianbergmann/phpunit#2583]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.0.6
| PHP version         | 7.0.16
| Installation Method | Composer and then PHAR

I have a single [uploadTest.php](https://github.com/samayo/bulletproof/blob/master/test/uploadTest.php) and in local, if try to call PHPUnit via namespace `PHPUnit_Framework_TestCase` as:  

`class uploadTest extends \PHPUnit_Framework_TestCase {}`

I get the following error. 

```
PHP Fatal error:  Class 'PHPUnit_Framework_TestCase' not found in /var/www/projects/samayo/bulletproof/test/uploadTest.php on line 4

Fatal error: Class 'PHPUnit_Framework_TestCase' not found in /var/www/projects/samayo/bulletproof/test/uploadTest.php on line 4
```

However, if I change the namespace to this: 

```
use PHPUnit\Framework\TestCase;

class uploadTest extends TestCase
{
```

It works in my machine, but if I push it it won't work on [Travis-CI](https://travis-ci.org/samayo/bulletproof/jobs/214632541)

`PHP Fatal error:  Class  PHPUnit\Framework\TestCase' not found in /home/travis/build/samayo/bulletproof/test/uploadTest.php on line 5`

Is there any solution for this?

**Comment by hboomsma** [comment]
You probably run different versions of PHPUnit local and on Travis.
I suggest that you run PHPUnit with the `-v` flag on both, so you can see the version.

To make sure you run the same version of PHPUnit as is installed in your project you can let Travis run
`vendor/bin/phpunit -v` (or from the location of your bin-folder).

Travis should prefer your installed version over their system version according to the docs. But I had trouble of the same sort before. Note that this is a Travis problem and not a PHPUnit one.
