### ISSUE TITLE
Class 'PHPUnit_Framework_Assert' not found (Behat\Testwork\Call\Exception\FatalThrowableError

### ISSUE THREAD

**Issue by taqiofficial** [sebastianbergmann/phpunit#2585]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | ^6.0
| PHP version         | 7.1
| Installation Method | Composer

I am using PHPUnit with Behat in my Symfony Project, I upgrade my symfony version with dependencies, and after upgrading i m getting below error; 

`Fatal error: Class 'PHPUnit_Framework_Assert' not found (Behat\\Testwork\\Call\\Exception\\FatalThrowableError)`

Before Upgrade 
```
 "sensio/generator-bundle": "~2.3",        
 "phing/phing": "~2.10.1",         
"phpunit/phpunit": "~4.6.4",        
 "behat/behat": "~3.0.15",         
"behat/symfony2-extension": "~2.0",        
 "behat/mink": "~1.6.1",        
 "behat/mink-extension": "~2.0.1",        
 "behat/mink-browserkit-driver": "~1.2",         
"behat/mink-goutte-driver": "~1.1",        
"nelmio/alice": "~1.7.2",         
"knplabs/friendly-contexts": "dev-master"
```
After Upgrade ;

```
        "phing/phing": "2.15.2",
        "phpunit/phpunit": "^6.0",

        "behat/behat": "^3.3",
        "behat/symfony2-extension": "^2.1",
        "behat/mink": "^1.7",
        "behat/mink-extension": "^2.2",
        "behat/mink-browserkit-driver": "^1.3",
        "behat/mink-goutte-driver": "^1.2",

        "nelmio/alice": "2.x-dev",
        "knplabs/friendly-contexts": "^0.8.0"
```

**Comment by GrahamCampbell** [comment]
Not a bug in PHPUnit?

**Comment by sebastianbergmann** [comment]
Not a PHPUnit issue.

**Comment by taqiofficial** [comment]
That's because i was using `PHPunit 6`, which uses `**namespaces**`
If so, replace it with `\PHPUnit\Framework\Assert`
Or add a use statement like `use PHPUnit\Framework\Assert;` and do `Assert::assertNotEmpty(...);`

**Comment by MasterMindNET** [comment]
I fixed this issue changing 
remove this line

> use PHPUnit_Framework_Assert as a;

to this one

> use PHPUnit\Framework\Assert as a;

YourProject\vendor\codeception\verify\src\Codeception\Verify.php
![image](https://user-images.githubusercontent.com/22347676/45373054-21000880-b5f7-11e8-9b8e-b938e5403691.png)
