### ISSUE TITLE
Test coverage summary shows 0% even if methods is being tested

### ISSUE THREAD

**Issue by mentemind** [sebastianbergmann/phpunit#2586]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 4.8.27
| PHP version         | 5.4.45
| Installation Method | Composer

I was having an strange result in tests coverage displaying 0% coverage for 1 methods and 100% for the other ones in the same class even though the report showed that all lines were being hit by a test
![0_percent_coverage](https://cloud.githubusercontent.com/assets/24942916/24375152/efc23174-12fc-11e7-9b80-ea24cb9fb4e8.png)

the only strange thing I have in my code was a deep nested array indented like this:

<pre>$array['key']
    ['foo']
    ['bar']
    ['fooz']
    ['bazz'] = "some_value";
</pre>

after making it a single like it worked

<pre>
$array['key']['foo']['bar']['fooz']['bazz'] = "some_value";
</pre>

The problem with this "solution" is the code sniffer rules who checks for max line length

this was an strange issue with a strange walkaround

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project.

**Comment by sebastianbergmann** [comment]
Also note that neither PHPUnit 4.8 nor PHP 5.4 are supported anymore.
