### ISSUE TITLE
Description of example 9.11 in manual is wrong

### ISSUE THREAD

**Issue by JKingweb** [sebastianbergmann/phpunit#2589]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.0, 6.1

The explanatory text preceding Example 9.11 does not correspond with the actual text of Example 9.11:
https://phpunit.de/manual/current/en/test-doubles.html#test-doubles.mock-objects.examples.SubjectTest.php

```
Example 9.11 shows how to use a mock object to test the interaction between Subject and Observer objects.

We first use the getMockBuilder() method that is provided by the PHPUnit\Framework\TestCase class to set up a mock object for the Observer. Since we give an array as the second (optional) parameter for the getMock() method, only the update() method of the Observer class is replaced by a mock implementation.
```

Contrary to the text, the example does not call getMock() with a second (or first!) parameter.

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-documentation](https://github.com/sebastianbergmann/phpunit-documentation) project.
