### ISSUE TITLE
Run a class in separate process.

### ISSUE THREAD

**Issue by ArturGoldyn** [sebastianbergmann/phpunit#2591]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 4.0.2
| PHP version         | 5.3.3
| Installation Method | PHAR

We can run individual tests in separate processes, but we cannot run a test class in a separate process.
It would be nice to have **@runTestsClassInSeparateProcess**, not only @runTestsInSeparateProcesses

The goal is to run setUpBeforeClass once (it takes a few seconds), then perform all tests in separate process, and then at the end lose all global variable changes that occured.
Unfortunately some of our objects collide and don't allow us to pass to the next test, but they work with --process-isolation parameter perfectly. Therefore we would like to have a **@runTestsClassInSeparateProcess** annotation to run just few classes in separate process, but use this one process for all tests in this class.

**Comment by ArturGoldyn** [comment]
I've started working on it yesterday, will finish this week.

**Comment by ArturGoldyn** [comment]
For now it fails in AppVeyor. https://github.com/sebastianbergmann/phpunit/pull/2664

**Comment by ArturGoldyn** [comment]
@sebastianbergmann I did it, and fixed that failing merge request, do you consider merging my branch to some release? Or does it need any alterations?

**Comment by kaphert** [comment]
Am I correct that this feature is implemented since 6.2 but is missing in the documentation?

**Comment by WalterWoshid** [comment]
https://github.com/sebastianbergmann/phpunit/pull/5233
