### ISSUE TITLE
Accessing the last thrown exception?

### ISSUE THREAD

**Issue by SoboLAN** [sebastianbergmann/phpunit#2595]
A lot of the unit-tests I write (and I assume this applies to most people) have to deal with exception and how the code should behave and/or fail when exceptional situations occur.

So let's assume we have the following code containing some hierarchy of exceptions that provide various features:

```
class MyException extends Exception
{
    private $errorCode;
    
    public function __construct($errorCode, $message, $code = 0, $previous = null)
    {
        parent::__construct($message, $code, $previous);
        
        $this->errorCode = $errorCode;
    }
    
    public function getErrorCode()
    {
        return $this->errorCode;
    }
}

class SomeOtherException extends MyException
{
    private $errorCode = 'INVALID_STUFF';
    private $errorMessage = 'One or multiple invalid stuff';
    private $errorsList;
    
    public function __construct(array $errorsList)
    {
        parent::__construct($this->errorCode, $this->errorMessage);
        $this->errorsList = $errorsList;
    }
    
    public function getErrorsList()
    {
        return $this->errorsList;
    }
}

class ExceptionThrower
{
    public function throwSomething()
    {
        throw new SomeOtherException(array('stuff1', 'stuff2')); 
    }
}
```

Now, I want to test the behaviour of `ExceptionThrower::throwSomething()`, more specifically closely inspect all information I can inside the thrown exception.

Right now the way I do this is like this:

```php
class ExceptionThrowerTest extends PHPUnit_Framework_TestCase
{
    public function testThrowSomething()
    {
        $obj = new ExceptionThrower();
        
        try {
            $obj->throwSomething();
        } catch (SomeOtherException $e) {
            $this->assertEquals('INVALID_STUFF', $e->getErrorCode());
            $this->assertEquals(array('stuff1', 'stuff2'), $e->getErrorsList());
            $this->assertEquals('One or multiple invalid stuff', $e->getMessage());
            return;
        }
        
        $this->fail();
    }
}
```

While this works, I find it a bit of a clumsy solution and not very elegant.

I propose a solution that would simplify this a bit by letting you retrieve the last thrown exception and doing the inspections you want on it. Something like this:

```php
class ExceptionThrowerTest extends PHPUnit_Framework_TestCase
{
    public function testThrowSomething()
    {
        $obj = new ExceptionThrower();
        
        $this->setExpectedException(SomeOtherException::class);
        
        $exceptionChecker = function($e) {
            $this->assertEquals('INVALID_STUFF', $e->getErrorCode());
            $this->assertEquals(array('stuff1', 'stuff2'), $e->getErrorsList());
            $this->assertEquals('One or multiple invalid stuff', $e->getMessage());
        };
        
        $this->assertThrownException($exceptionChecker);

        $obj->throwSomething();
    }
}
```

The new part is the new `PHPUnit_Framework_TestCase::assertThrownException()` method, which will work hand-in-hand with `setExpectedException()` and:

- will be called using the thrown exception as parameter
- will fail if there was no exception thrown

I'm not 100% sure about the method name and the entire mechanics, but I do firmly believe that having something like this is a much more elegant way of inspecting whatever you want/need about the exception your code throws.

I wanted to start working on a pull-request which would implement something like this, but I didn't want to waste time doing it if the idea will be categorically rejected.

So, what do you think? Is it something that looks promising?

Thank you.

**Comment by sebastianbergmann** [comment]
Sorry for not replying sooner. I do not think that what you propose makes sense to add to PHPUnit.
