### ISSUE TITLE
Wrong "executed code that is not listed as code to be covered or used" messages

### ISSUE THREAD

**Issue by spriebsch** [sebastianbergmann/phpunit#2633]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.0.7
| PHP version         | 7.1.3
| Installation Method | PHAR

I have green tests, using @covers and @uses. PHPUnit does not complain about any code being executed that is not marked with @covers or @uses annotations.

I remove a class from my production code, but do not yet update the @covers/@uses annotations in the tests.

When I now run the tests, PHPUnit complains about a lot of code not being annotated. And, of course and expected, it complains about annotations referencing non-existing code.

The latter is expected, the former not; it seems PHPUnit internally bails out when the first "wrong" annotation is encountered, instead of going through all of them.   

And yes: as soon as I remove the obsolete annotations (referencing the removed class), everything is fine again.

Not a serious issue, but still undesired behavior.

**Comment by sebastianbergmann** [comment]
I do not understand what you mean by "PHPUnit complains about a lot of code not being annotated".

**Comment by spriebsch** [comment]
It's probably easier when I explain to you on the phone. I'll call you some time next week.

**Comment by sebastianbergmann** [comment]
Now I understand what is going on:
* `forceCoversAnnotation="true"` is configured -> no code coverage without `@covers` annotation
* A test has at least one `@covers` annotation for which the target does not exist -> even if it has other, valid `@covers` annotations they are not used -> no `@covers` annotation -> no code coverage

#### `src/C.php`
```php
<?php
class C
{
    public function m()
    {
        return true;
    }
}
```
#### `tests/CTest.php`
```php
<?php
class CTest extends PHPUnit\Framework\TestCase
{
    /**
     * @covers C::m
     * @covers C::n
     */
    public function testOne()
    {
        $o = new C;

        $this->assertTrue($o->m());
    }
}
```
#### `phpunit.xml`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/6.0/phpunit.xsd"
         bootstrap="src/C.php"
         forceCoversAnnotation="true"
         beStrictAboutCoversAnnotation="true"
         beStrictAboutOutputDuringTests="true"
         beStrictAboutTodoAnnotatedTests="true"
         verbose="true">
    <testsuite>
        <directory suffix="Test.php">tests</directory>
    </testsuite>

    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">src</directory>
        </whitelist>
    </filter>
</phpunit>
```
#### `phpunit --coverage-html /tmp/coverage`
```
PHPUnit 6.0.13-1-g5b02194 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.3 with Xdebug 2.5.1
Configuration: /home/sb/example/phpunit.xml

W                                                                   1 / 1 (100%)R

Time: 28 ms, Memory: 4.00MB

There was 1 warning:

1) CTest::testOne
Trying to @cover or @use not existing method "C::n".

--

There was 1 risky test:

1) CTest::testOne
This test does not have a @covers annotation but is expected to have one

WARNINGS!
Tests: 1, Assertions: 1, Warnings: 1, Risky: 1.

Generating code coverage report in HTML format ... done
```
#### Screenshot
![screenshot](https://cloud.githubusercontent.com/assets/25218/24645579/004b1b38-1919-11e7-8233-e9f6da262be9.png)

**Comment by mingomax** [comment]
Hi, for me usingo PHPUnit via composer was resolved using the full qualified namespace:
` @covers \Lkd\VersionVersion::__construct`

**Comment by jawira** [comment]
Same for me, I used `phpunit.phar` and using fully qualified namespaces on `@covers` annotation solved the issue.

**Comment by olleharstedt** [comment]
I'm having this error with a `pipe` function. Weirdly, it works for all other `@covers`, but not for `pipe`. Any ideas...?

https://github.com/olleharstedt/query/blob/main/tests/KeyTest.php#L27

**Comment by sebastianbergmann** [comment]
Please do not post a potentially new/different issue as a comment to an issue from six years ago.
