### ISSUE TITLE
Tests broken by change to EOL character export

### ISSUE THREAD

**Issue by direvus** [sebastianbergmann/phpunit#2639]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.1-g253f1d2
| PHP version         | PHP 7.0.15 with Xdebug 2.4.1
| Installation Method | Composer

Seven of the PHPUnit tests are now failing in `master` and also `6.0`, which I believe is due to a change in how exporter renders the EOL characters "\r" and "\n", see sebastianbergmann/exporter@4722899.

For a full report of the failed tests, please see https://gist.github.com/direvus/5215629e690aea3bf45b51258164d8e2

It looks like the right move is to just update the expected result of the tests, to match the new output from exporter.

**Comment by sebastianbergmann** [comment]
Tests were update in 5b02194c5b1f29fae402835fc615f87505fa6799.
