### ISSUE TITLE
running phpunit returns no useful information

### ISSUE THREAD

**Issue by ja-heller** [sebastianbergmann/phpunit#2640]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.0.13
| PHP version         | 7.1.0
| Installation Method | PHAR

Running php -v returns 7.1.0. After I installed phpunit I can run phpunit from terminal, all is working fine, but when I try to trigger a test, by doing 

    phpunit LoginDataTest

I get no output to my terminal. I already tried to set a --verbose & --debug flag, still no information.

Here's my PHP file (which is called, when using php command):
/usr/local/bin/php

    #!/bin/sh

    /Applications/MAMP/bin/php/php7.1.0/bin/php "$@"

**Comment by ottlinger** [comment]
Hi @ja-heller, can you provide a link to a test repo?
Did you provide a phpunit.xml in order to configure PHPUnit?

I call a particular test with:
```
$ ./vendor/bin/phpunit MyTest
```

and do not see anything if the test does not perform any outputs via echo.

**Comment by evgpisarchik** [comment]
can it be Mac terminal related issue? since you are using MAMP
