### ISSUE TITLE
assertObjectHasAttribute doesn't allow checking for some valid properties

### ISSUE THREAD

**Issue by jnvsor** [sebastianbergmann/phpunit#2644]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 4.8.35 (And higher?)
| PHP version         | 7.0.16
| Installation Method | Composer / PHAR

It's possible to add properties of just about any binary key to an object using this syntax:

```
$object->{'1234'} = 1234;
```

`assertObjectHasAttribute` refuses these attribute names as parameters. Additionally, it's possible to get true integer properties by casting an array to an object, so supporting those would be nice too.

**Comment by sebastianbergmann** [comment]
PHPUnit should probably use https://github.com/sebastianbergmann/object-reflector for this.

**Comment by jnvsor** [comment]
Yeah but you'll need to combine reflection if you want to get the true integer properties. (And as my own CI is telling me HHVM likes to error if you reflect an int property, so there seems to be no nice way of doing this)

**Comment by sebastianbergmann** [comment]
Just to clarify: `assertObjectHasAttribute()` (and `readAttribute()` etc.) currently only allow/support attribute names that can be declared using valid syntax (`/[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*/`).

Using dynamic variable creation (without declaration) and variable variables it is possible to create attributes where the name is syntactically not valid. IMO, such code must not be used and if you do then you are on your own. IMO, support for dynamic attributes and variable variables should be removed from PHP but this is the wrong place to discuss this.

That being said, I still might add support for these invalid attributes to `assertObjectHasAttribute()`. I am very reluctant to do so, though. I will certainly not waste any time on implementing this. I may consider a pull request, though.
