### ISSUE TITLE
Enhancement: support for json data provider in phpunit

### ISSUE THREAD

**Issue by vijaynitrr** [sebastianbergmann/phpunit#2646]
I have used Json File as dataprovider so what i find it is easier to extend testcase data in json. So i want to suggest that we can use @JsonDataProvider anotation.

@JsonDataProvider JSON_FILE_PATH

So , we can use this annotation to inject data in function test. 

Example: 

     /**
     * @JsonDataProvider data.json
     */
    public function testAdd($a, $b, $expected) {
        $privateObj = new MockPrivateEnity(new Calculator());
        $result = $privateObj->add($a,$b);
        $this->assertEquals($expected, $result);
    }

and content of data.json

{
  "positive numbers operation": {
    "a": 2,
    "b": 3,
    "additionExpected": 5
  },
  "negative number operation":{
    "a": -22,
    "b": -33,
    "additionExpected": -55
  }
}

**Comment by sebastianbergmann** [comment]
I do not think that this should be added to PHPUnit itself, sorry.

**Comment by redaxmedia** [comment]
@vijaynitrr I had the same idea because separated JSON files make a test suite cleaner.

At the moment I'm using countless data providers like this:

```
public function providerForTest() : array
{
	return $this->getProvider('tests/provider/{class}/.....json');
}
```

Helper from my TestCaseAbstract that extends PHPUnit\Framework\TestCase:

```
public function getProvider(string $url = null) : array
{
	$content = file_get_contents($url);
	return json_decode($content, true);
}
```

So, this would be a nice feature. Is there a way to write a PHPUnit listener instead?

**Comment by redaxmedia** [comment]
@vijaynitrr Check this out: https://github.com/redaxmedia/phpunit-provider-autoloader
