### ISSUE TITLE
Can @depends reference a test from outside the class?

### ISSUE THREAD

**Issue by Kwadz** [sebastianbergmann/phpunit#2647]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.1.0
| PHP version         | 7.0.15
| Installation Method | Composer 

According to [this article](https://web.archive.org/web/20150217042431/https://sebastian-bergmann.de/archives/826-Test-Dependencies-in-PHPUnit-3.4.html), it seems that from PHPUnit 3.4 `@depends class::method` references the test implemented in `class::method()`.

However, when I try to execute the following tests with `phpunit --configuration phpunit.xml tests/Functional/Example` I get `This test depends on "FirstTest::testProducerFirst" to pass.`.

```php
namespace Functional\Example;

use PHPUnit\Framework\TestCase;

class FirstTest extends TestCase
{
    public function testProducerFirst()
    {
        $this->assertTrue(true);
        return 'first';
    }

    public function testProducerSecond()
    {
        $this->assertTrue(true);
        return 'second';
    }

    /**
     * @depends testProducerFirst
     * @depends testProducerSecond
     */
    public function testConsumer()
    {
        $this->assertEquals(
            ['first', 'second'],
            func_get_args()
        );
    }
}
```

```php
namespace Functional\Example;

use PHPUnit\Framework\TestCase;

class SecondTest  extends TestCase
{
    public function testProducerFirst()
    {
        $this->assertTrue(true);
        return 'first';
    }

    public function testProducerSecond()
    {
        $this->assertTrue(true);
        return 'second';
    }

    /**
     * @depends FirstTest::testProducerFirst
     * @depends testProducerSecond
     */
    public function testConsumer()
    {
        $this->assertEquals(
            ['first', 'second'],
            func_get_args()
        );
    }


}
```

**Comment by matejvelikonja** [comment]
any progress on this? I would like to know also.

**Comment by El-Sam** [comment]
I need this too, any progress ?

**Comment by GinoPane** [comment]
Yes, it can. Just make sure that test dependant test runs before your test.

**Comment by igknighton** [comment]
@GinoPane How exactly can you do that though?

**Comment by GinoPane** [comment]
@igknighton Exactly like it described in the example above. The file with "FirstTest" just need to be processed before "SecondTest" and they both must be in the same test suite. This can be achieved by XML configuration for your tests.

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.

That being said, yes, `@depends` can be used to denote a dependency on a test that is declared in another test case class.

Keep in mind, though, that PHPUnit cannot ensure that a depended-upon test is executed before the test(s) that depend(s) on it.

**Comment by Aeraphe** [comment]
First
 - You have to use  the complete namespace on: 
      @depends  Functional\Example\FirstTest::testProducerFirst
 
- Second set the execuiton of  class order phpunit.xml

`<testsuites>
    <testsuite name="sys">
      <file>./tests/Unit/FirstTest.php</file>
      <file>./tests/Unit/SecondTest.php</file>
    </testsuite>
    </testsuites>`

**Comment by epdenouden** [comment]
@Aeraphe FYi, the reason this ordering works is because of the ordering in the configuration. PHPUnit doesn't actively reorder `@depends` unless you switch on the recently introduced dependency resolver. Even then, the resolver will only reorder tests within the same `TestSuite` and will not put the suites themselves in a different order

**Comment by PatricNox** [comment]
Basically, use @Depends (note capital D) and then the class reference like so.

`@Depends ExternalClass::MethodTest`

no need to include full path as mentioned above.

**Comment by epdenouden** [comment]
FYI: I am working on `::class` based `@depends` support: #3549 

Give me 1-2 weeks as I'm changing jobs but it will be added to PHPUnit core.

**Comment by damianprzygodzki** [comment]
Looks like `@Depends` doesn't care about passing values throughout tests (like `@depends` does).

**Comment by Gemorroj** [comment]
that issue still exeist.

**Comment by igor-vasyukov** [comment]
it is possible if you import test class with use:
`
namespace Functional\Example;

use PHPUnit\Framework\TestCase;
use Functional\Example\FirstTest;

class SecondTest  extends TestCase
{
    public function testProducerFirst()
    {
        $this->assertTrue(true);
        return 'first';
    }

    public function testProducerSecond()
    {
        $this->assertTrue(true);
        return 'second';
    }

    /**
     * @depends Functional\Example\FirstTest::class
     * @depends testProducerSecond
     */
    public function testConsumer()
    {
        $this->assertEquals(
            ['first', 'second'],
            func_get_args()
        );
    }
}
`
