### ISSUE TITLE
PHPUnit_Framework_TEstCase not found

### ISSUE THREAD

**Issue by koffisani** [sebastianbergmann/phpunit#2652]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.1.0
| PHP version         | 7.0.15
| Installation Method |  PHAR

After installation, I'm getting :

> Fatal error: Class 'PHPUnit_Framework_TestCase' not found in /var/www/html/appfolder/vendor/cakephp/cakephp/src/TestSuite/TestCase.php on line 30

When downgraded `phpunit` to `5.7.19`, it got fixed. Does this seem normal ?

**Comment by GrahamCampbell** [comment]
Not a bug. This class was renamed in phpunit 6 to `PHPUnit/Framework/TestCase`.

**Comment by koffisani** [comment]
Right, Thanks @GrahamCampbell.

**Comment by DanielRuf** [comment]
@grahamc shouldn't it be `PHPUnit\Framework\TestCase` according to the docs?

**Comment by grahamc** [comment]
I guess so

**Comment by DanielRuf** [comment]
@GrahamCampbell soory, linked the wrong profile, you appeared at the top when I tried to link him here in the issue.
