### ISSUE TITLE
False negative on code coverage 

### ISSUE THREAD

**Issue by sebastianfeldmann** [sebastianbergmann/phpunit#2656]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.1.1
| PHP version         | 7.0.13, 7.1.2
| Installation Method | PHAR

If you create a map with local constant values and external constant values the lines defining the map are marked as not covered.
The external class is **not** in the whitelisted path for code coverage (vendor directory).

The map has to have more then 1 element.

```php
namespace MyName;

class Dummy
{
    const foo = 'foo';
    const bar = 'bar';
    const baz = 'baz';

    private $fooBarBazMap;

    public function __construct()
    {
        $this->fooBarBazMap = [
            self::foo  => \SomeVendorClass::FOO,
            self::bar  => \SomeVendorClass::BAR, // not covered
            self::baz  => \SomeVendorClass::BAZ  // not covered
        ];
    }
}
```

If you are using strings instead of local constants it works

```php
        $this->fooBarBazMap = [
            'foo'  => \SomeVendorClass::FOO,
            'bar'  => \SomeVendorClass::BAR, // covered
            'baz'  => \SomeVendorClass::BAZ  // covered
        ];
```

If you are using strings or local constants instead of external constants it works as well

```php
        $this->fooBarBazMap = [
            self::foo    => 'FOO',
            self::bar    => self::bar, // covered
            self::baz    => 'BAZ'      // covered
        ];
```

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project.

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another.
