### ISSUE TITLE
core dump at termination of test execution

### ISSUE THREAD

**Issue by dshorthouse** [sebastianbergmann/phpunit#2659]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 5.7.19
| PHP version         | 5.6.24
| Installation Method | Composer

Something in the clean-up of phpunit on Travis' Ubuntu Trusty is causing a core dump and I no not know where/how to go about learning what this might be. For what it's worth, I'm also using facebook/webdriver (dev-master), satooshi/php-coveralls (~1.0), chromedriver 2.29, and selenium-server-standalone 3.4.0. See Travis job log: https://travis-ci.org/dshorthouse/SimpleMappr. I have executed the same using --no-coverage and receive the same core dump. Any help would be most appreciated.

**Comment by sebastianbergmann** [comment]
You have found a problem in the PHP runtime that leads to a segfault. An issue like this has to be reported at https://bugs.php.net/report.php using a minimal, self-contained, reproducing test case.

Please note that a test case that needs to be run through PHPUnit does not qualify as either "minimal" or "self-contained" when reporting bugs for the PHP runtime.

**Comment by dshorthouse** [comment]
Thanks for the quick response, Sebastian. I appreciate what you write, but as an end-user of phpunit, it does not help me. I'd like to make sure that phpunit can be used to it greatest potential as I'm sure you do too. It's likely I'm not the only one to experience this issue. You have not provided me with instructions on how to discover what is the issue such that I can file a reproducible test case with the maintainers of PHP.

**Comment by sebastianbergmann** [comment]
I am sorry, but I do not understand your comment. I gave you a link to https://bugs.php.net/report.php and at the very top of that page is a link to https://bugs.php.net/how-to-report.php.

**Comment by sebastianbergmann** [comment]
The only advice I can give you is that you can [troubleshoot the problem locally using Docker](https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image). In that Docker container you can reproduce the segmentation fault and then debug it using [GDB](https://www.gnu.org/software/gdb/), for instance.
