### ISSUE TITLE
Allow handling of color output via environment variable

### ISSUE THREAD

**Issue by jhasse** [sebastianbergmann/phpunit#2662]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 5.7.19
| PHP version         | 7.1.4
| Installation Method | Fedora repositories

My build server logs output (therefore it is not a tty), but supports ANSI color codes. I'm using `--color=always`. Symfony on the other hand uses `--ansi`. It would be nice to have an environment variable which forces color output, so that I don't have to remember to add the command line flag to every invocation of phpunit.

In order to standardize this, I've created https://bixense.com/clicolors/ which suggest to use `CLICOLOR_FORCE` for this. This is also shared by CMake, Waf and Apple's command line utilities.

**Comment by sebastianbergmann** [comment]
I do not want to add another way of controlling this. I might be willing to add `--ansi` as an alias for `--colors` but that is as far as I am willing to go.

**Comment by jhasse** [comment]
What about the build server / continuous integration use case?

In an ideal future build servers could define this environment variable out of the box so that colors would just work.

**Comment by mtorromeo** [comment]
@sebastianbergmann I would also like to have this feature. This is not an additional way of controlling the `--color` argument but is an additional check that would be performed when `--color=auto` just like it already checks if the shell is a tty. `--color=always`/`--color=never` would still win over the variable.

`CLICOLOR_FORCE` being used by a bunch of other tools would be a good choice IMO.
