### ISSUE TITLE
TAP or Teamcity options ignored (single test, AllTests.php suite compilation, presumably not common)

### ISSUE THREAD

**Issue by padraic** [sebastianbergmann/phpunit#2665]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 5.7.19
| PHP version         | 7.1.4
| Installation Method | Composer

It's difficult to know if this is expected behaviour or not, and the scenario is using an old style AllTests.php class to compile the test suite.

From 5.2.0, certain tests show an uncaught ArgumentCountError fatal error, fixed in 5.2.11. Prior to 5.2.0, passing the --tap option would output TAP intermixed with the normal PHPUnit output (i.e. phpunit output unexpectedly output above TAP). Post 5.1, the --tap option does nothing (neither does --teamcity in later versions in this scenario) if we pass AllTests.php as an argument on the command line. Everything works as expected when it's omitted.

It's not a huge deal here, since this is one isolated case with a single test using an AllTests.php, but I threw together a quick reproducible scenario: https://github.com/padraic/p1. The command used would be: `./vendor/bin/phpunit --teamcity ./src/AllTests.php`.

**Comment by sebastianbergmann** [comment]
`AllTests.php` has not been supported for years.

**Comment by sebastianbergmann** [comment]
Do `--tap` and `--teamcity` work for you when `AllTests.php` is not used?

**Comment by padraic** [comment]
It does without AllTests. If it's not supported, then the issue can be closed.
