### ISSUE TITLE
Get original exception from ExceptionWrapper

### ISSUE THREAD

**Issue by alexbowers** [sebastianbergmann/phpunit#2677]
Please make it possible to get the original exception from the ExceptionWrapper, currently `Throwable $t` is not stored in the wrapper anywhere, so it is not possible to obtain the original exception.

This is useful for people who put their own properties within custom exceptions.

My usecase is that I want to override the `run` method, to output the actual exceptions rather than just that an exception has been thrown to make debugging simpler.

I can override and get the exception, but all that is contained is the properties `code`, etc. Not the original exception which for me has a property `errors` for validation errors.

Thanks.

**Comment by alexbowers** [comment]
Implemented in #2678

**Comment by KamilKopaczyk** [comment]
Shouldn't this issue be reopened? 
Merged pull request was later reverted, so this issue is a little bit misleading.

**Comment by alexbowers** [comment]
@KamilKopaczyk I don't currently have the time to fix this, but if  you want to take what I had as a starting point, i'm more  than happy for that to happen.

I would still like to see this inside of phpunit.

**Comment by KamilKopaczyk** [comment]
Looks like originalException is not stored on purpose, as described in #1351.
