### ISSUE TITLE
Allow configuration (without warning) of method calls handled by __call()

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#2679]
For a class such as
```php
/**
 * @method string foo()
 */
class Example
{
    public function __call($methodName, $arguments)
    {
        return 'string';
    }
}
```
using `createMock()`
```php
class ExampleTest extends PHPUnit\Framework\TestCase
{
    public function testOne()
    {
        $stub = $this->createMock(Example::class);
        
        $stub->method('foo')->willReturn('bar');
    }
}
```
results in a warning
```
Trying to configure method "foo" which cannot be configured because it does not exist, has not been specified, is final, or is static
```
"Methods" "implemented" using `__call()` (or rather messages that are handled by `__call()`) currently have to be explicitly specified:
```php
class ExampleTest extends PHPUnit\Framework\TestCase
{
    public function testOne()
    {
        $stub = $this->getMockBuilder(Example::class)->setMethods(['getString'])->getMock();

        $stub->method('getString')->willReturn('result');
        
        $this->assertEquals('result', $stub->getString());
    }
}
```
It would be nice if PHPUnit could automatically generate the parameter for `setMethods()` by looking at the information in the docblock.

Not only for BC reasons, this new functionality should be implemented in a new convenience wrapper around the mock builder.

**Comment by spriebsch** [comment]
By definition, a class implementing __call() will "accept" every method call. So I would expect the mocking library to not require me specifying any method names explicitly in this case.

**Comment by sebastianbergmann** [comment]
Good catch, @spriebsch.

**Comment by sebastianbergmann** [comment]
Moved to https://github.com/sebastianbergmann/phpunit-mock-objects/issues/367.
