### ISSUE TITLE
app/config/*.yml contains invalid YAML with phpunit version > 5.0.0

### ISSUE THREAD

**Issue by mnoivrt** [sebastianbergmann/phpunit#2682]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 5.0.0
| PHP version         | 7
| Installation Method |PHAR

I'm using php 7 , symfony  2.2, and when i'm running phpunit that is newer than 5.0.0  then I get an error saying:
`Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: The service file .../app/config/config_unittest.yml" is not valid. in .../Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php on line 258`  

Glad to any help.

**Comment by sebastianbergmann** [comment]
Closing this as it is not a PHPUnit issue.
