### ISSUE TITLE
Should Count restore positions of non-Iterator Traversables?

### ISSUE THREAD

**Issue by jmikola** [sebastianbergmann/phpunit#2690]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.1.4
| PHP version         | 7.1.5
| Installation Method | N/A

When https://github.com/sebastianbergmann/phpunit/pull/1125 implemented support for restoring an Iterator's position after counting, it neglected to handle generators (fixed in https://github.com/sebastianbergmann/phpunit/issues/2149), nested IteratorAggregate objects (fixed in https://github.com/sebastianbergmann/phpunit/pull/2689), and Traversable objects that do not implement Iterator or IteratorAggregate (fixed in https://github.com/sebastianbergmann/phpunit/pull/2642).

With the above fixes, Count now only attempts to restore positions of Iterator objects. I also made the following comment in https://github.com/sebastianbergmann/phpunit/pull/2642:

> Traversable objects that are neither an Iterator or IteratorAggregate interface may still support rewinding. In that case, we may want to compose them in an [IteratorIterator](http://php.net/iteratoriterator).

That said, the PHP documentation for IteratorIterator also states:

> It is important to understand that most classes that do not implement Iterators have reasons as most likely they do not allow the full Iterator feature set. If so, techniques should be provided to prevent misuse, otherwise expect exceptions or fatal errors.

In light of this, I would understand an argument that we should not attempt to rewind a non-Iterator Traversable and closing this issue as "Won't Fix".

Alternatively, if it is worth supporting non-Iterator Traversables by wrapping them in an IteratorIterator, we should consider to fail gracefully if rewinding is not possible. This may entail trying the [rewind](https://github.com/sebastianbergmann/phpunit/blob/d3180f13eac8d8e22d0210c6966ff3060300ed21/src/Framework/Constraint/Count.php#L79) in a try/catch block and aborting the restoration attempt on an exception.

**Comment by sebastianbergmann** [comment]
Thank you for the analysis of this issue, @jmikola. I am sorry for not replying sooner. Back in May when I first saw this issue "my head exploded".

Now I looked at this issue again ... and "my head exploded" once more. As I would rather not have my head explode, I think I am fine with "won't fix".
