### ISSUE TITLE
Risky tests are always hard errors in the junit output

### ISSUE THREAD

**Issue by mbeccati** [sebastianbergmann/phpunit#2691]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.2-dev
| PHP version         | 7.0.20-dev
| Installation Method | Composer

Regardless of the fail-on-risky configuration directive, risky tests show up as errors in the junit output, e.g: `<error type="PHPUnit\Framework\RiskyTestError">Risky Test</error>`.

whereas the console output reports `OK, but incomplete, skipped, or risky tests!`.

Even if the return code is 0, Bamboo picks them up as errors and builds are failing.

**Comment by sebastianbergmann** [comment]
The `--fail-on-risky` commandline option and the `failOnRisky` configuration setting only control whether or not the test runner should abort the execution of the test suite upon the first risky test. They have no impact on the logfiles.

**Comment by sebastianbergmann** [comment]
According to [this](http://llg.cubic.org/docs/junit/), the JUnit XML logfile format only knows (passed), disabled, error, failure, and skipped whiles PHPUnit currently knows (passed), error, failure, skipped, incomplete, warning, and risky.

A 1:1 mapping of PHPUnit's test status flags to the flags supported by the JUnit XML logfile is not possible, I am afraid. IMO, coming up with our own logfile format is not an option as that would require custom extensions to all solutions such as Jenkins, Bamboo, etc. that "just" consume PHPUnit's JUnit XML logfile.

**Comment by mbeccati** [comment]
@sebastianbergmann Yes indeed. I was just wondering if risky tests would be better mapped to a warning-like level rather than errors.

**Comment by sebastianbergmann** [comment]
As far as I know (see https://github.com/sebastianbergmann/phpunit/issues/2691#issuecomment-303321314), the JUnit XML logfile format has no "warning-like level".

IMO, a test for which PHPUnit raises a warning or which is marked as risky by PHPUnit needs to be fixed ASAP. Against that background, failing the build for warnings and risky tests is the "right thing to do" anyway.

**Comment by mbeccati** [comment]
@sebastianbergmann makes sense. Thanks.

**Comment by jeremeamia** [comment]
🤕 The problem for me is that the upgrade from PHPUnit 5 to PHPUnit 6/7 introduced all sorts of test failures in our suite on a legacy codebase, including many "risky" tests. Gonna have to stay with V5 for now, otherwise I'll just be fixing tests for the next few months. Heh.

**Comment by sebastianbergmann** [comment]
@jeremeamia The risky test checks that are enabled by default can be disabled.

**Comment by jeremeamia** [comment]
@sebastianbergmann Yeah, thanks! I have other tests that have errors and failures after upgrading, so something else is going on as well. Just don't have time to figure it out yet. We'll get there eventually.
