### ISSUE TITLE
Data providers called before setUpBeforeClass

### ISSUE THREAD

**Issue by grosch** [sebastianbergmann/phpunit#2694]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.0.7
| PHP version         | 7.1.3
| Installation Method | Homebrew

Subject says it all.    The static methods that are called once setup state.  I want to use some of that state in most of my data providers, but you're calling those data providers BEFORE the setup is able to be run, thus breaking things.

**Comment by sebastianbergmann** [comment]
This is a known issue that won't be fixed for a while. See #10.

**Comment by grosch** [comment]
Seriously?  That ticket is seven years old.
