### ISSUE TITLE
Backport recent each fix?

### ISSUE THREAD

**Issue by shmax** [sebastianbergmann/phpunit#2696]
Recently, @eclipxe13 opened this fix for a PHP 7.2 deprecation of each:
https://github.com/sebastianbergmann/phpunit/pull/2536/files

Do you have any mechanism or process for backporting this kind of thing to your other releases? I maintain a project that still supports PHP versions all the way back to 5.4, but I would also like to support PHP 7.

Let me know if there is anything I can do to help. Thank you!

**Comment by sebastianbergmann** [comment]
PHPUnit 4.8 (and older) is no longer supported. PHPUnit 5.7 is supported on PHP 5.6, PHP 7.0, and PHP 7.1. PHPUnit 6.1 is supported on PHP 7.0 and PHP 7.1.

TL;DR: There is no need to / point in backporting this fix.

**Comment by shmax** [comment]
No point? Let me explain it again:

1. I have a project that supports PHP versions 5.4 through 7.1, inclusive (and why wouldn't you?  https://w3techs.com/technologies/details/pl-php/5/all)
2. I use travis and a matrix of versions to run phpunit against each of them
3. I have to use phpunit version 4, because the higher ones require PHP 5.6 or greater; otherwise my tests fail for those versions.
4. phpunit version doesn't have the `each` fix, nor does it have the supress operator on `each`, which means my matrix fails when it gets to php 7.

I get that you're tired of the older versions of PHP, but unless you have some other suggestion for me, is doing a backport of at least the suppression operator really such a crazy idea?

**Comment by jmauerhan** [comment]
@shmax 5.4 is no longer supported by php itself. 5.6 is the oldest version supported by PHP. http://php.net/supported-versions.php

So that's a perfectly valid reason for libraries to not support it.

However, if you need to use older versions, you can use composer's || operator to use either valid version of a library that will work with your setup. You have to not use the newer features of the library in the code, but it might work for you.

**Comment by shmax** [comment]
Yes, I was going to post an update; I did indeed use the pipe operator, and had to add some `method_exists` logic around `get_mock` to avoid your own deprecation notice, but I can live with it for now. Thanks much.
