### ISSUE TITLE
RFC: `@requires OSFAMILY`

### ISSUE THREAD

**Issue by keradus** [sebastianbergmann/phpunit#2697]
Currently, `@requires OS` is checking against `PHP_OS` via regex
(`@requires OS Lin` -> `/Lin/i`).

On PHP It's tricky, as `PHP_OS` could be `WIN32`, `WINNT`, `Windows`. It would be nice to add possibility to check against `PHP_OS_FAMILY` (either by dedicated annotation or by extending what `@requires OS` checks)
WDYT?

**Comment by sebastianbergmann** [comment]
What does "WDYF" mean?

**Comment by keradus** [comment]
typo :D 
WDYT? :)

**Comment by sebastianbergmann** [comment]
Makes sense to me.

**Comment by keradus** [comment]
which way you prefer to go? new annotation or extending current one (which could be considered by some as BC Breaker)
I could help with PR, but please guide me with target branch

**Comment by sebastianbergmann** [comment]
IMO, this is not a BC break, So keeping the existing annotation is fine.

Target branch should be `master` (after tomorrow's release of PHPUnit 6.2).

**Comment by belanur** [comment]
Please be aware that `PHP_OS_FAMILY` is not available on PHP < 7.2.0 so you should either fall back to checking `PHP_OS`on those versions or move this change to a PHPUnit release that does not support earlier PHP versions anymore.

**Comment by sebastianbergmann** [comment]
Ah, of course. Good catch, @belanur!

**Comment by sebastianbergmann** [comment]
@keradus #2704 is (sort of) related to this.

**Comment by sebastianbergmann** [comment]
Version 3.1 of `sebastian/environment` will have `OperatingSystem::getFamily()`. This method returns `PHP_OS_FAMILY` (if defined (which it is on PHP >= 7.2)). Otherwise it returns a string (compatible with `PHP_OS_FAMILY`) derived from `PHP_OS`.

Using `OperatingSystem::getFamily()`, it should be pretty straightforward to implement support for

* `@requires BSD`
* `@requires Windows`
* `@requires OSX`
* `@requires BSD`
* `@requires Linux`
* `@requires Solaris`

Unlike the existing `@requires os`, this should not use regular expression matching but should instead use simple string comparison.

**Comment by keradus** [comment]
> IMO, this is not a BC break, So keeping the existing annotation is fine.
> Target branch should be master (after tomorrow's release of PHPUnit 6.2).

for that, if we go with different approach, maybe we don't need to target 6.x ?

**Comment by sebastianbergmann** [comment]
@keradus Feel free to take the code of `OperatingSystem::getFamily()` and use it for Symfony's polyfill library.

`@requires osFamily` should go into PHPUnit 6.3 (due in August).

**Comment by nicolas-grekas** [comment]
Note that "Mac" is now "Darwin", see http://git.php.net/?p=php-src.git;a=commitdiff;h=a251d9b2c11c2ab53b0214d728c40d70cd06567c;hp=ef4b2fc283ddaf9bd692015f1db6dad52171c3ce

**Comment by GrahamCampbell** [comment]
> Note that "Mac" is now "Darwin", see

What? Why was that changed!

**Comment by keradus** [comment]
> Change PHP_OS_FAMILY to "Darwin" instead of "Mac" for Darwin based systems (as suggested by Davey)

ask Davey ;P

**Comment by nicolas-grekas** [comment]
https://externals.io/thread/944#email-15548

**Comment by sebastianbergmann** [comment]
Wondering whether offering aliases such as `macOS`, `Mac`, and `OSX` for `Darwin` makes sense.

**Comment by keradus** [comment]
:-1:, those would bring confusion that they are different family and not aliases.
but in general, i don't like having 10 different names for same thing, so ... ;)

**Comment by sebastianbergmann** [comment]
Makes sense, @keradus.
