### ISSUE TITLE
@requires OS Win Broken on Mac

### ISSUE THREAD

**Issue by GrahamCampbell** [sebastianbergmann/phpunit#2704]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 5.7.20
| PHP version         | 7.1.5
| Installation Method | Composer

The annotation `@requires OS Win` still runs the test on Mac. It only avoids it on, for example, Ubuntu.

---

For reference:

```php
var_dump(PHP_OS); // string(6) "Darwin"
var_dump(php_uname('s')); // string(6) "Darwin"
var_dump(php_uname()); // string(134) "Darwin Grahams-MBP.home 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64"
```

![image](https://user-images.githubusercontent.com/2829600/27010910-aea7e9b8-4ea7-11e7-80cc-a8f078672820.png)

**Comment by sebastianbergmann** [comment]
Not sure whether this is really a bug or a usage mistake. I, for one, would not have thought of using `Win` to identify Windows.

On my Windows 10 machine, `PHP_OS` contains `WINNT`. Which, unfortunately, is not `Windows`.

A short-term solution that I see is not to use `preg_match()` for evaluating the contents of `PHP_OS`. And in PHPUnit 8 (which will require PHP 7.2) we will be able to use `PHP_OS_FAMILY`.

**Comment by dshafik** [comment]
@sebastianbergmann it should just be enough to anchor the match to the start of the string, then the `win` in `Darwin` wouldn't match, but `WINNT` or `Windows` would.

**Comment by sebastianbergmann** [comment]
@dshafik Pull Request? :-)

**Comment by dshafik** [comment]
Actually, this isn't a bug. The value for `@requires OS` is:

> A regexp matching PHP_OS

So, the correct value here is simply `^WIN`

For the record, the value is turned into a regex using:

```php
sprintf(
    '/%s/i',
    addcslashes($matches['value'][$count - 1], '/')
);
```

Resulting in: `/^WIN/i`

**Comment by sebastianbergmann** [comment]
Thank you, @dshafik, for confirming what I suspected in https://github.com/sebastianbergmann/phpunit/issues/2704#issuecomment-307641516.
