### ISSUE TITLE
Missing assert IsDisabled

### ISSUE THREAD

**Issue by savaged** [sebastianbergmann/phpunit#2709]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 5.7.19
| PHP version         | 7.1.3
| Installation Method | Composer / PHAR

Enhancement to required to allow assertion that a html field has the disabled attribute.

**Comment by sebastianbergmann** [comment]
I don't think that HTML-specific assertions belong in the PHPUnit core.
