### ISSUE TITLE
PHP Fatal error:  Call to undefined method PHPUnit_Util_Configuration::getTestdo xGroupConfiguration() in C:\xampp\htdocs\mykydsapi\vendor\phpunit\phpunit\src\Te xtUI\TestRunner.php on line 1066

### ISSUE THREAD

**Issue by madmax1111** [sebastianbergmann/phpunit#2710]
| Q     
composer.json
{
	"require": {
	},
	"require-dev": {
	"phpunit/phpunit": "*"
	},
	"autoload": {
		"psr-0": {
			"mykidsapi": ""
		}
	}
}

-------------phpunit.xml--------------

<?xml version="1.0" enoding="UTF-8"?>
<phpunit colors="true" bootstrap="vendor/autoload.php">
	<testsuites>
		<testsuite name="Application Test Suite">
			<directory>./Test/</directory>
		</testsuite>
	</testsuites>
</phpunit>

--------------------Baseball.php--------------

<?php
namespace mykidsapi;

class Baseball
{
	public function calc_avg($ab,$hits)
	{
		if($ab == 0)
		{
			$avg = "0.000";
		}
		else
		{
			$avg = $hits/$ab;
		}
		return $avg;
	}
}

-----------------BasebalTest.php------------------------

<?php

namespace mykydsapi\Test;

use mykydsapi\Baseball;

class BaseballTest extends \PHPUnit_Framework_TestCase
{
	public function testCalcAvgEquals()
	{
		$atbats = 389;
		$hits = 129;
		$baseball = new Baseball();
		$result = $baseball->calc_avg($atbats,$hits);
		$expectedresults = $hits/$atbats;
		$this->assertEquals($expectedresult,$results);
	}
}

--------------------------------------------------------------------------------
 | A
| --------------------| ---------------
| PHPUnit version     | x.y.z
| PHP version         | x.y.z
| Installation Method | Composer

**Comment by sebastianbergmann** [comment]
It appears that you have different installation of PHPUnit mixed up.

For instance, you may have used Composer to install PHPUnit and have configured the autoloader generated by Composer as PHPUnit's bootstrap script but then you invoke PHPUnit using an executable other than `vendor/bin/phpunit`.

**Comment by madmax1111** [comment]
But i have tried using vendor/bin/phpunit it is still not working.
