### ISSUE TITLE
More to #2710

### ISSUE THREAD

**Issue by madmax1111** [sebastianbergmann/phpunit#2711]
#2710 

But i have tried using vendor/bin/phpunit it is still not working.

Admin@WIN8-PC c:\xampp\htdocs\mykydsapi

phpunit

PHP Fatal error: Call to undefined method PHPUnit_Util_Configuration::getTestdo
xGroupConfiguration() in C:\xampp\htdocs\mykydsapi\vendor\phpunit\phpunit\src\Te
xtUI\TestRunner.php on line 1066

Fatal error: Call to undefined method PHPUnit_Util_Configuration::getTestdoxGrou
pConfiguration() in C:\xampp\htdocs\mykydsapi\vendor\phpunit\phpunit\src\TextUI
TestRunner.php on line 1066

Admin@WIN8-PC c:\xampp\htdocs\mykydsapi

vendor/bin/phpunit

'vendor' is not recognized as an internal or external command,
operable program or batch file.

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.

**Comment by madmax1111** [comment]
atleast give a solution sir.

**Comment by sebastianbergmann** [comment]
I do not have a solution for you, sorry. You may find one on StackOverflow or a similar forum.

**Comment by jmauerhan** [comment]
You're on windows. It's `vendor\bin\phpunit` <- fix your slashes.
