### ISSUE TITLE
test mark as skipped if argument not passed

### ISSUE THREAD

**Issue by alexbowers** [sebastianbergmann/phpunit#2712]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.2
| PHP version         | 7.1
| Installation Method | Composer

Currently I am marking some of my tests to be skipped, because they negatively hurt performance heavily. 

These tests I do not want to run for all of my test matrix, because it will take too long. Instead, I want them to only run once.

For example, my tests may run on php 7.0 and 7.1, with various database environments (mysql 5.5, 5.6, 5.7, 8.0) for example.

If my tests have no bearing on the database, but are slow, I may only want them to run for php 7.0 and 7.1 once, to ensure that the logic works, but not for them to run 8 times, only twice.

Having something that can be passed into the phpunit command to say:

`$this->markTestsSkippedIf("option is not set", "Skip Message");` 

Would be quite useful.

**Comment by alexbowers** [comment]
bump

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.

That being said, I think that you should use the `@group` annotation to group your slow tests and exclude this group from execution for the environments in which you do not want to run them.
