### ISSUE TITLE
Testing Post Parameters not working

### ISSUE THREAD

**Issue by BenjaminG1983** [sebastianbergmann/phpunit#2718]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.2.2
| PHP version         | 7.0.18
| Installation Method | Composer

I have a problem since the update to 6.2.2 from a old version 5.x.

I looked to the examples, but I found no different to my version.

My test action is:
`$sUrl = '/de/user/login';

$aPostArray = array('csrf'       => 'CSRF-CODE',
                                 'username'   => '99999999',
                                  'password'   => '12345678',
                                  'login_user' => 'Login');

$this->getRequest()
        ->setMethod('POST')
        ->setPost(new Parameters($aPostArray));

$this->dispatch($sUrl, 'POST');`

My action to test:
`public function indexAction()
{
      **if ($this->getRequest()->isPost())**
      {
          $aData = $this->params()->fromPost();
...
`

But If I add a output to my action, than I get **FALSE** from this method $this->getRequest()->isPost(). 

I think, this is not correct.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by BenjaminG1983** [comment]
I created a clean projekt, with one action and one test action. In this clean project it works. But not in my big project. I will search the differents between this projects! Thank you!
