### ISSUE TITLE
Missing Extension Points in TestSuite class

### ISSUE THREAD

**Issue by IvanChepurnyi** [sebastianbergmann/phpunit#2719]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.2.2
| PHP version         | 7.0+
| Installation Method | All

I am trying to write an extension for PHPUnit to allow running a different test class, but I got stuck because of tight coupling of `PHPUnit\Framework\TestSuite` to the loading process of test files. 
I want to make a contribution by doing the following things, but want to check first if you would agree to the following refactoring list:
* Extract Suite interface for run operations and create following classes that implement it
     * Composite Suite - for clients who expect composite (`addSuiteClass`, `addTestClass`, `addTestFile`, etc)
     * Test Case Suite - for a test suite that executes on test case classes
     * PHPT Class Suite - for a test suite that executes on PHPT tests 
* Move creation of this classes into seperate factory class (makes it extensible):
     * `createCompositeSuite($name = '');` - Just to accomulate multiple test suites.
     * `createFromTestClass($className);` - Creates TestCase suite or any other class based test case (maybe pure Test interface in feature?)
     * `createFromTestFile($testFile);` - Creates TestCase suite or PHPT suite
     * `createFromTestFiles($testFiles);` - Creates composite with Test cases and PHPT classes, depending on file type.
* Clean up code base to use factories instead of direct creation of TestSuite.
* Static methods move into independent service classes (`TestFactory` (`createTest`), `TestMethodService` (`isTestMethod`), etc)
* Rework original class as an adapter for new implementation to keep BC and mark it as deprecated. 
     * Add it to `TestListener` and mark old suite related methods as deprecated
     * Create a new `TestListener` suite specific interface that accepts new suite implementation. 
 
Please let me know if you see more refactoring opportunities in this class.

**Comment by IvanChepurnyi** [comment]
@sebastianbergmann I plan to come back to this project, would you be interested in such a contribution?

**Comment by sebastianbergmann** [comment]
Thank you for your contribution. I appreciate the time you invested in writing this proposal. However, I am not interested in the changes you proposed.
