### ISSUE TITLE
Calling mock's proxied method on null instead of original object

### ISSUE THREAD

**Issue by Wirone** [sebastianbergmann/phpunit#2720]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.2.2
| PHP version         | 7.1.4
| Installation Method | Composer

I was trying to create mock for testing core exception handler:
```
use Symfony\Component\HttpKernel\Event\GetResponseForExceptionEvent;

/** @var GetResponseForExceptionEvent|\PHPUnit_Framework_MockObject_MockObject $event */
$event = $this->getMockBuilder(GetResponseForExceptionEvent::class)
    ->enableOriginalConstructor()
    // These are 3 mocks prepared earlier
    ->setConstructorArgs([$httpKernel, $request, HttpKernelInterface::MASTER_REQUEST, $exception])
    ->enableProxyingToOriginalMethods()
    ->getMock();
```

but I was getting

```
call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object
 <project>\vendor\symfony\http-kernel\Event\GetResponseForExceptionEvent.php:48
 <project>\tests\EventListener\AuthCheckerListenerTest.php:151 --> this is "getMock()" line
```

**The real problem** was in `vendor/phpunit/phpunit-mock-objects/src/Generator/proxied_method.tpl.dist` where `$this->__phpunit_originalObject` was null. I managed to find it with a help on Symfony's Slack (thanks @sstok), **the solution** was to add `setMethods()` to mock builder and explicitly define methods to mock.

It would be good if PHPUnit library could handle it and display more user-friendly message since presented stacktrace doesn't even contain complete data to find place where error is rised.

Thanks in advance.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by Wirone** [comment]
@sebastianbergmann I have created [repo with issue-reproducable codebase](https://github.com/Wirone/PhpUnit_issue2720).

Comment [the line](https://github.com/Wirone/PhpUnit_issue2720/blob/master/tests/EventListener/AuthCheckerListenerTest.php#L54) in test case to see the described problem:

```
-> % vendor/bin/phpunit
PHPUnit 6.2.2 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.4
Configuration: PhpUnit_issue2720\phpunit.xml.dist
Error:         No code coverage driver is available

EEEE                                                                4 / 4 (100%)

Time: 118 ms, Memory: 4.00MB

There were 4 errors:

1) App\Tests\EventListener\AuthCheckerListenerTest::testOnCoreExceptionHandler with data set #0 (false, 'Exception', null, null)
call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object

PhpUnit_issue2720\vendor\symfony\http-kernel\Event\GetResponseForExceptionEvent.php:48
PhpUnit_issue2720\tests\EventListener\AuthCheckerListenerTest.php:55

2) App\Tests\EventListener\AuthCheckerListenerTest::testOnCoreExceptionHandler with data set #1 (true, 'Exception', null, null)
call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object

PhpUnit_issue2720\vendor\symfony\http-kernel\Event\GetResponseForExceptionEvent.php:48
PhpUnit_issue2720\tests\EventListener\AuthCheckerListenerTest.php:55

3) App\Tests\EventListener\AuthCheckerListenerTest::testOnCoreExceptionHandler with data set #2 (true, 'Symfony\Component\Security\Co...eption', array(true), 403)
call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object

PhpUnit_issue2720\vendor\symfony\http-kernel\Event\GetResponseForExceptionEvent.php:48
PhpUnit_issue2720\tests\EventListener\AuthCheckerListenerTest.php:55

4) App\Tests\EventListener\AuthCheckerListenerTest::testOnCoreExceptionHandler with data set #3 (true, 'Symfony\Component\Security\Co...eption', array(true), 403)
call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object

PhpUnit_issue2720\vendor\symfony\http-kernel\Event\GetResponseForExceptionEvent.php:48
PhpUnit_issue2720\tests\EventListener\AuthCheckerListenerTest.php:55

ERRORS!
Tests: 4, Assertions: 0, Errors: 4.
```

**Comment by wesolowski** [comment]
This work fine when do change this code 
[https://github.com/Wirone/PhpUnit_issue2720/blob/master/tests/EventListener/AuthCheckerListenerTest.php#L49](https://github.com/Wirone/PhpUnit_issue2720/blob/master/tests/EventListener/AuthCheckerListenerTest.php#L49)

to
```php
$event = $this->getMockBuilder(GetResponseForExceptionEvent::class)
    ->enableOriginalConstructor()
    ->setConstructorArgs([$httpKernel, $request, HttpKernelInterface::MASTER_REQUEST, $exception])
    ->enableProxyingToOriginalMethods()
    ->setMethods(['getException'])
    ->getMock();

//$event->expects($this->once())->method('getException');
//$event->expects($this->once())->method('getRequest');`
```

 `setMethods(['getException'])` is necessary when you "enableOriginalConstructor" in "getMockBuilder" have.  
Method "getException" is [inGetResponseForExceptionEvent@__construct](https://github.com/symfony/http-kernel/blob/master/Event/GetResponseForExceptionEvent.php#L48) execute

**Comment by sebastianbergmann** [comment]
No feedback, closing.

**Comment by Wirone** [comment]
@sebastianbergmann sorry for lack of feedback, I've read notification but could not answer at that moment and, sadly, forgot to do it later.

@wesolowski's comment doesn't add anything to my issue since I knew (and wrote it above) what should be done to get rid of that error message - my goal was to handle it better and display more user-friendly message in case any other developer did not do it (and would get message as in the example above which is not clear).
