### ISSUE TITLE
TestSuite names conflict with names of built-in classes

### ISSUE THREAD

**Issue by jbaron-gingco** [sebastianbergmann/phpunit#2726]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.2.3
| PHP version         | 7.1.5
| OS | XUbuntu 17.04 (PHP is not the packaged version, but self-compiled)
| Installation Method | Composer

If a testsuite name in phpunit.xml is the name of a built-in class, an exception is thrown.

Minimal example:

**composer.json**

    {
      "require": {
        "php": "^7.0",
        "roave/security-advisories": "dev-master"
      },
      "require-dev": {
        "php": "^7.0",
        "phpunit/phpunit": "^6.2.2"
      }
    }

**phpunit.xml**

    <?xml version="1.0" ?>
    <phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="http://schema.phpunit.de/5.2/phpunit.xsd">
        <testsuites>
            <testsuite name="DateTime"/>
        </testsuites>
    </phpunit>

Same issue occurs with test suite names like "Generator", "Closure" etc., but not with something like "get_class", "strlen" etc.

**Expected Result**

No tests executed!

**Actual Result**

(The backtrace was added in line 153 of `TestSuite.php` by myself)

>#0  PHPUnit\Framework\TestSuite->__construct() called at [/home/jost/projects/gingco_appserver/branches/dev_restructuring/InstallerBuilder/tmp/test/vendor/phpunit/phpunit/src/Util/Configuration.php:916]
#1  PHPUnit\Util\Configuration->getTestSuite() called at [/home/jost/projects/gingco_appserver/branches/dev_restructuring/InstallerBuilder/tmp/test/vendor/phpunit/phpunit/src/Util/Configuration.php:875]
#2  PHPUnit\Util\Configuration->getTestSuiteConfiguration() called at [/home/jost/projects/gingco_appserver/branches/dev_restructuring/InstallerBuilder/tmp/test/vendor/phpunit/phpunit/src/TextUI/Command.php:784]
#3  PHPUnit\TextUI\Command->handleArguments() called at [/home/jost/projects/gingco_appserver/branches/dev_restructuring/InstallerBuilder/tmp/test/vendor/phpunit/phpunit/src/TextUI/Command.php:152]
#4  PHPUnit\TextUI\Command->run() called at [/home/jost/projects/gingco_appserver/branches/dev_restructuring/InstallerBuilder/tmp/test/vendor/phpunit/phpunit/src/TextUI/Command.php:141]
#5  PHPUnit\TextUI\Command::main() called at [/home/jost/projects/gingco_appserver/branches/dev_restructuring/InstallerBuilder/tmp/test/vendor/phpunit/phpunit/phpunit:53]
>
>Fatal error: Uncaught PHPUnit\Framework\Exception: Class "DateTime" does not extend PHPUnit\Framework\TestCase.
>
>  thrown in /home/jost/projects/gingco_appserver/branches/dev_restructuring/InstallerBuilder/tmp/test/vendor/phpunit/phpunit/src/Framework/TestSuite.php on line 154

**Comment by sebastianbergmann** [comment]
This is a relic of how test suites used to work, back when you had to write classes that extend `TestSuite` manually to organize your tests. This can probably not be "fixed" before PHPUnit 7.

**Comment by sebastianbergmann** [comment]
I can no longer reproduce this.

```
$ cat composer.json 
{
    "prefer-stable": true,
    "minimum-stability": "dev",
    "require-dev": {
        "phpunit/phpunit": "^8"
    }
}
```
```
$ cat phpunit.xml  
<?xml version="1.0" ?>
<phpunit>
    <testsuites>
        <testsuite name="DateTime"/>
    </testsuites>
</phpunit>
```
```
$ ./vendor/bin/phpunit
PHPUnit 8.0-gdda7fcbb5 by Sebastian Bergmann and contributors.

Time: 26 ms, Memory: 4.00MB

No tests executed!
```

**Comment by epdenouden** [comment]
Yes, #3454 included a fix for this.
