### ISSUE TITLE
Consider using polyfill instead of requiring ext-mbstring

### ISSUE THREAD

**Issue by kelunik** [sebastianbergmann/phpunit#2728]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.y.z
| PHP version         | any
| Installation Method | Composer

Currently the `composer.json` declares a dependency on `ext-mbstring`. https://github.com/symfony/polyfill-mbstring could be used instead. I currently hit this issue with my Windows VM, because it doesn't have `mbstring`. Works all fine with `--ignore-platform-reqs`, because the mentioned package is loaded anyway.

**Comment by stof** [comment]
it would be better to install the extension though. The Symfony polyfill is much slower than the C extension

**Comment by kelunik** [comment]
I don't care about performance in my crappy Windows VM.

**Comment by sebastianbergmann** [comment]
IMO, using `--ignore-platform-reqs` and then bringing in the polyfill should be "good enough".

**Comment by kelunik** [comment]
@sebastianbergmann `--ignore-platform-reqs` disables all platform checks, so also the used PHP version and might install PHP 7.1 packages while the local version is PHP 7.0.

**Comment by staabm** [comment]
ran into the same issue. would be great when the polyfill would either be bundled, or at least suggested.
