### ISSUE TITLE
phpunit.xml  apply unexpected

### ISSUE THREAD

**Issue by guozhenyi** [sebastianbergmann/phpunit#2729]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 4.8.35 
| PHP version         | win10 php5.6.28cli php7.0cli / ubuntu16.04.1  php7.0.18cli
| Installation Method | Composer

I will config a differance database to run unit test.

so, I have a configuration in phpunit.xml, like this:
![2](https://user-images.githubusercontent.com/5993771/27847830-e19810d6-6172-11e7-9292-5398ca9a436b.png)

PHP framework: Laravel 5.1.*

test code:
![9](https://user-images.githubusercontent.com/5993771/27848171-b91fa382-6175-11e7-9be9-48e361d6ed33.png)

In Windows 10  PHP 5.6 CLI,   it's OK.
![4](https://user-images.githubusercontent.com/5993771/27848049-b9214242-6174-11e7-9c8c-a9c62cee5d62.png)

but, in ubuntu 16.04 CLI , it's surprised.
![5](https://user-images.githubusercontent.com/5993771/27848053-bd4ca816-6174-11e7-94c9-67f1b5d1ca81.png)

In windows10 PHP 7.0.12CLI it's OK.
![6](https://user-images.githubusercontent.com/5993771/27848488-17a7e944-6178-11e7-857e-cc01fd9b2e5f.png)

**Comment by sebastianbergmann** [comment]
I do not understand what you are trying to report.

**Comment by sebastianbergmann** [comment]
No feedback, closing.
