### ISSUE TITLE
Documentation says to call assertions non-statically, but they are static functions

### ISSUE THREAD

**Issue by gingerCodeNinja** [sebastianbergmann/phpunit#2735]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | all
| PHP version         | n/a
| Installation Method | n/a

Throughout all the various PHPUnit documentation, examples using `assertEquals` etc call it by `$this->assertEquals(..)`, but actually the functions are static functions, and should be called statically, either with `self::assertEquals()` or ideally `static::assertEquals()`.

I think the documentation requires updating to reflect this. Calling static functions non-statically causes IDEs like PHPStorm to kick up a bad code smell, because static functions should be called statically, and non-static functions called non-statically.

Code - https://github.com/sebastianbergmann/phpunit/blob/master/src/Framework/Assert.php#L531

`public static function assertEquals($expected, $actual, $message = '', $delta = 0.0, $maxDepth = 10, $canonicalize = false, $ignoreCase = false)`

Documentation -
https://phpunit.de/manual/current/en/appendixes.assertions.html#appendixes.assertions.assertEquals

`$this->assertEquals(1, 0);`

In PHP 7.x, if you call a non-static function statically, it will raise a deprecation error, in this case it's the opposite, people are calling static functions non-statically - it would be nice to resolve that inconsistency before it's deprecated in some future version of PHP.

I think the documentation just needs updating for best practice - and I'm happy to help do that.

**Comment by sebastianbergmann** [comment]
Please read https://phpunit.de/manual/current/en/appendixes.assertions.html#appendixes.assertions.static-vs-non-static-usage-of-assertion-methods.

**Comment by gingerCodeNinja** [comment]
Thanks @sebastianbergmann - I missed that!

But.. think of the kittens! (ref: https://stackoverflow.com/a/15707148/830171). If PHP ever make calling static functions non-statically deprecated or throw a warning, I'll of course return with a 'I told you so' statement. Until then, keep up the good work. ;)
