### ISSUE TITLE
Serialization of 'Closure' is not allowed exception when run tests in process isolation mode

### ISSUE THREAD

**Issue by vinterskogen** [sebastianbergmann/phpunit#2739]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 5.7.21
| PHP version         | 7.0.20
| Installation Method | Composer 

I discovered, that phpunit crashes with closure serialisation exception when run a test, that uses a data provider, which returns an object of \Closure class, as one of elements in a dataset. 

```
PHP Fatal error:  Uncaught Exception: Serialization of 'Closure' is not allowed in /tmp/wtfunit/vendor/phpunit/phpunit/src/Framework/TestCase.php:814
```

The following test is green when running in process isolation mode turned off, but causes crash in process isolation mode turned on.

Code to reproduce error: 

```
<?php

namespace Tests\Unit;

class FooTest extends \PHPUnit_Framework_TestCase
{
    /**
     * Test, that uses a data provider.
     *
     * @dataProvider foobarDataProvider
     * @return void
     */
    public function testFoobar($callback, $expected)
    {
        $actual = call_user_func($callback);
        $this->assertEquals($expected, $actual);
    }

    /**
     * Data provider, which returns an object of \Closure class, as one of
     * elements in a dataset.
     *
     * @return array
     */
    public function foobarDataProvider()
    {
        return [[
                function () { return 'foo'; },
                'foo',
            ], [
                function () { return 'bar'; },
                'bar',
            ]
        ];
    }
}
```

Output:
```
vinter@vinter-pc /tmp/wtfunit $ ./vendor/bin/phpunit tests/Unit/FooTest.php --process-isolation 
PHPUnit 5.7.21 by Sebastian Bergmann and contributors.

PHP Fatal error:  Uncaught Exception: Serialization of 'Closure' is not allowed in /tmp/wtfunit/vendor/phpunit/phpunit/src/Framework/TestCase.php:814
Stack trace:
#0 /tmp/wtfunit/vendor/phpunit/phpunit/src/Framework/TestCase.php(814): serialize(Array)
#1 /tmp/wtfunit/vendor/phpunit/phpunit/src/Framework/TestSuite.php(722): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#2 /tmp/wtfunit/vendor/phpunit/phpunit/src/Framework/TestSuite.php(722): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#3 /tmp/wtfunit/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(517): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#4 /tmp/wtfunit/vendor/phpunit/phpunit/src/TextUI/Command.php(186): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array, true)
#5 /tmp/wtfunit/vendor/phpunit/phpunit/src/TextUI/Command.php(116): PHPUnit_TextUI_Command->run(Array, true)
#6 /tmp/wtfunit/vendor/phpunit/phpunit/phpunit(52): PHPUnit_TextUI_Command::main()
#7 {main}
  thrown in /tmp/wtfunit/vendor/phpunit/phpunit/src/Framework/TestCase.php on line 814
```

May be related to:

- https://github.com/sebastianbergmann/phpunit/issues/282
- https://github.com/sebastianbergmann/phpunit/issues/223
- https://github.com/sebastianbergmann/phpunit/issues/1515
- (and more...)

Is this an expected behavior?

Are objects of a \Closure class allowed to be used as a dataset element in data providers? By now docs don't cover this details.

Hope this issue will help to fix it! ;)

--
Regards,
Vinter Skogen

**Comment by sebastianbergmann** [comment]
PHP cannot serialize anonmyous functions. The process isolation feature requires serialization, for instance of the data from a data provider. So yes, this is expected behavior for now.

The implementation could be changed to only pass along the ID of the data set from the parent to the child process in which case no serialization would be required but the data provider would be executed once for each child process.

**Comment by vinterskogen** [comment]
Thanks. Hopе this this will be at least documented to decrease a number of miscommunications in understanding of who the process isolation works.

**Comment by vinterskogen** [comment]
If there is any way to implement support for passing anonymous functions from data provider to tests while running in process isolation mode on, that would be great. It is a really useful feature. In fact, I expect to run correctly written tests successfully (without crashes) both in default and process isolation modes. Thanks. ;)

**Comment by vinterskogen** [comment]
Another way to serialize closures is to use under the hood an "uncanny" tool (yeah...) like this - https://packagist.org/packages/jeremeamia/SuperClosure. On the other hand, it is, of course, а new external dependency for the phpunit.

**Comment by GrahamCampbell** [comment]
I don't consider this a bug, just an annoyance.

**Comment by GrahamCampbell** [comment]
Would need some convincing that phpunit should pull in a closure serialization hack out of the box, personally.

**Comment by vinterskogen** [comment]
Agree, it's an annoyance. But the crash on a dummy test is caused by internal logic of framework, so, nah, it is a bug in fact, in my opinion.

**Comment by dawei101** [comment]
Actually, I think phpunit is not a good tools.
I have got same exception in 4.6 version , also 5.* version

And the most bad thing is , It could pass test in my dev machine, and could not run when in another environment.
------------

Do you think it would be a good idea  to do that:
use bash or python to execute only one TestCase class in single process

There wont be serialization issues then.

**Comment by AeonFr** [comment]
When introducing a bug of this kind in the bootstrap file, all tests fail with the same message. It would be nice to have some kind of back trace.

I'm still figuring out why phpunit fails on perform an external library's method but my web browser doesn't show any error of any kind (even after doing `error_reporting(E_ALL);ini_set('display_errors', 1);`).

Having a back trace would make this easier. I don't know if this is possible or not, but if it is, then I would propose it as a feature request.

**Comment by epdenouden** [comment]
@AeonFr You said the magic word! A backtrace surely would be handy, I will do a quick investigation and report back here. I have been adding [new code location hints](https://github.com/sebastianbergmann/phpunit/pull/3467) recently, let's do some more.

**Comment by jarnojellesma** [comment]
Is there any workaround when dealing with 3rd party code? Setting the --process-isolation to false does not solve the problem either. Thanks.

**Comment by mpyw** [comment]
I wrote the patch: [mpyw/phpunit-patch-serializable-comparison](https://github.com/mpyw/phpunit-patch-serializable-comparison)

**Comment by farpat** [comment]
Hello World!

For anyone having the problem because using dataprovider like this :

```
public function provideData(): \Generator
{
   yield 'test' => [
       'closure' => function () {}
   ]
}
```

you must convert the above code like this rather :


```
public function provideData(): \Generator
{
   $closure = function () {};
   yield 'test' => [
       'closure' => convert_closure_to_serializable_closure ($closure)
   ]
}
```

To implement `convert_closure_...` function, you can use https://opis.io/closure/3.x/serialize.html#serialize-closures.

**Comment by AlexSkrypnyk** [comment]
Here is a practical use of `Opis\Closure\SerializableClosure;` as a trait that can be added to your test so that you could call closures from your data providers.

In my case, I needed to "prepare" the SUT before test, so running some operations in the closure.

The names `fnw` and `fnu` were chosen as they are close to `fn` reserved word and are not taking too much space in code.

```php

<?php

use Opis\Closure\SerializableClosure;

trait ClosureWrapperTrait {

  /**
   * Wrap closure into serializable object.
   */
  public static function fnw(callable $closure): SerializableClosure {
    return new SerializableClosure($closure);
  }

  /**
   * Unwrap closure into serializable object.
   */
  public static function fnu(callable|null $callback): mixed {
    return $callback && $callback instanceof SerializableClosure ? $callback->getClosure() : $callback;
  }

}

```

Test

```php

// Test
public function testDiscoveredValue(null|callable $prepare_callback, mixed $expected) {
  $prepare_callback = static::fnu($prepare_callback);
  if (is_callable($prepare_callback)) {
    $prepare_callback($config_values, $answers_values);
  }

  $actual = YOUR_CODE_SUT();
  $this->assertEquals($expected, $actual);
}

// Data provider
public static function dataProviderDiscoveredValue(): array {
  return [
    [
      NULL, // No closure
      'someval',
    ],

    [
      static::fnw(fn() => MY_PREPARE_CALLBACK1),  // Closure
      'otherval',
    ],
    
    [
      static::fnw(fn() => MY_PREPARE_CALLBACK2),  // Closure
      'anotherval',
    ],    
  ]      
}

```

**Comment by insignificant18** [comment]
> [@AeonFr](https://github.com/AeonFr) You said the magic word! A backtrace surely would be handy, I will do a quick investigation and report back here. I have been adding [new code location hints](https://github.com/sebastianbergmann/phpunit/pull/3467) recently, let's do some more.





https://pythondev.space/questions/is-it-feasible-to-verify-its-viability-using-automation-with-selenium-in-python-and-php

**Comment by serious-angel** [comment]
For another example:
```php
serialize(new Error());
// Serialization of 'Closure' is not allowed.

serialize(new Exception());
// Serialization of 'Closure' is not allowed.
```
