### ISSUE TITLE
Risky / No assertions check hinders use of Hamcrest

### ISSUE THREAD

**Issue by ascii-soup** [sebastianbergmann/phpunit#2744]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.2.3
| PHP version         | 7.0.10
| Installation Method | Composer

Using the hamcrest assertions library (https://github.com/hamcrest/hamcrest-php) with PHPUnit 6 is proving tricky. All tests are being marked as Risky due to them not having any assertions.

Graze's hamcrest-test-listener (https://github.com/graze/hamcrest-test-listener) has added to the assertion count previously by using a test listener and calling

`$test->addToAssertionCount($x)` 

for the number of Hamcrest assertions made in the test.

However, in PHPUnit 6 (and perhaps 5, I've not used 5) this does not work because the risky check happens before the `endTest()` method in the listeners is called.

I had considered using `assertPostConditions()` but this would be limited by the single inheritance model - for example, Mockery provides a trait to verify its post conditions in that method, which could conflict with the usage for the above purpose.

Is there another unobtrusive way that this could be performed using the current PHPUnit 6 feature set?

**Comment by sebastianbergmann** [comment]
If you do not want the risky test check then simply disable it.

**Comment by ascii-soup** [comment]
But the risky test check is useful, in case I have forgotten to use any assertions. I think it would be nice to support other assertion libraries other than PHPUnit's - as many people have done in the past - whilst also benefiting from the risky tests feature in PHPUnit.

Can this be done?

Or will that not be a goal of PHPUnit going forward?

**Comment by doctor-beat** [comment]
+1

This last answer is the *only* correct answer and should in fact be added to the hamcrest-php documentation!
