### ISSUE TITLE
Output is buffered until end of execution running phpunit with symfony 1.4.x

### ISSUE THREAD

**Issue by mirkosteiner** [sebastianbergmann/phpunit#2747]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 5.7.20
| PHP version         | 5.6.31
| Installation Method | FreeBSD-Port

Hi,

when running phpunit with symfony 1.4.x output is buffered until the end of execution. I examined the sourcecode of phpunit and the new version is using output buffering and I think there is a conflict with with the output buffering from symfony.

**Comment by sebastianbergmann** [comment]
"new version" compared to which previous version? PHPUnit has been buffering output for quite some time.

**Comment by mirkosteiner** [comment]
Uh.... i tracked it down to Version 5.5.4 where output gets generated and starting with 5.5.5 output is buffered until the end

**Comment by sebastianbergmann** [comment]
PHPUnit 5.5.5 fixed a bug in the output buffering. See #2101 for details.

**Comment by sebastianbergmann** [comment]
I think the current behavior is correct.
