### ISSUE TITLE
Multiple open DB connections after a call of Configuration#getTestSuiteConfiguration(...)

### ISSUE THREAD

**Issue by automatix** [sebastianbergmann/phpunit#2757]
My integration/database tests are failing due to a too high number of open database connections:

    Connect Error: SQLSTATE[HY000] [1040] Too many connections

By looking for what might cause this error I noticed, that after the execution of [this line](https://github.com/sebastianbergmann/phpunit/blob/master/src/TextUI/Command.php#L786) in the `PHPUnit\TextUI\Command`

    $testSuite = $configuration->getTestSuiteConfiguration($this->arguments['testsuite'] ?? null);

the number of the currently open connections encreases from `2` to `33`.

(Of course it's not the sole cause of _my_ database problem, but maybe it's something to optimize in PHPUnit.)

Environment:

- Ubuntu `Ubuntu 14.04.3` VM
 - PHP `7.0.3`
 - Xdebug `2.4.0RC4`
 - PHPUnit `6.2.2`

**Comment by sebastianbergmann** [comment]
PHPUnit does not do anything with a database.
