### ISSUE TITLE
TestCase::addToAssertionCount() no longer has effect when called from TestListener::endTest()

### ISSUE THREAD

**Issue by havvg** [sebastianbergmann/phpunit#2758]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.3
| PHP version         | 7.0
| Installation Method | Composer

I upgraded from PHPUnit 5.7 to 6.3 and the `TestListener` are not executed in the order as before, however there is no mention about this change in behavior in the changes files.

I wrapped the Mockery listener, and got it working with 6.3, but in `TestResult::run` the `addFailure` adding `'This test did not perform any assertions'` is now run before the `TestListener::endTest`, which is used to add additional number of assertions to the result.

Please advice – what's the proper way of handling such use cases?

**Comment by sebastianbergmann** [comment]
Can you please clarify what you mean by "the `TestListener` are not executed in the order as before"?

**Comment by havvg** [comment]
What I mean by that: with 5.7 the `endTest` could call `addToAssertionCount` which was part of the result; after upgrading to 6.3 this is not true anymore, instead the test is marked `risky` with message `This test did not perform any assertions` afterwards the listener would be called and add to the assertion counts.

**Comment by sebastianbergmann** [comment]
I added a test for this issue that passes (as expected) with PHPUnit 5.7 and currently fails (as reported) with PHPUnit 6.3.

**Comment by sebastianbergmann** [comment]
The obvious solution of simply calling `TestListener::endTest()` earlier makes this new test pass with PHPUnit 6.3 but breaks other tests.

**Comment by havvg** [comment]
Yeah, I thought so. I don't think there will be a nice way to fix that without breaking ^6.0 again. Therefore I would suggest to add this BC break to the change log. Mockery added a trait using `assertPostConditions` which yields the expected result.

**Comment by sebastianbergmann** [comment]
Yes, `assertPostConditions()` is the better approach here. Okay, I'll close this and remove the test I added in 3bfbdd9a0c8510afeabee01eab3f7b98789ed072.
