### ISSUE TITLE
assertAny() and assertNone()

### ISSUE THREAD

**Issue by mattparlane** [sebastianbergmann/phpunit#2759]
I've been adding these two functions to my base test class for a while, and I wondered if they might be useful to add upstream.

    /**
     * Assert that any element of a set produces a true result when evaluated by a given function.
     *
     * @param Array    $set
     * @param Callable $cb
     * @param string   $message
     *
     * @throws PHPUnit_Framework_AssertionFailedError
     */
    public function assertAny(Array $set, Callable $cb, $message = '') {
        $hasAny = false;
        foreach ($set as $el)
            if ($cb($el) === true) $hasAny = true;
        PHPUnit_Framework_Assert::assertThat($hasAny, PHPUnit_Framework_Assert::isTrue(), $message);
    }

    /**
     * Assert that no element of a set produces a true result when evaluated by a given function.
     *
     * @param Array    $set
     * @param Callable $cb
     * @param string   $message
     *
     * @throws PHPUnit_Framework_AssertionFailedError
     */
    public function assertNone(Array $set, Callable $cb, $message = '') {
        $hasAny = false;
        foreach ($set as $el)
            if ($cb($el) === true) $hasAny = true;
        PHPUnit_Framework_Assert::assertThat($hasAny, PHPUnit_Framework_Assert::isFalse(), $message);
    }

Hopefully it's self-explanatory, but if not: my most common use case is determining whether or not a given object exists in a set returned from an ORM tool. I would use it like this:

    $call = $this->call('GET', '/media?medium=app', [], [], [], ['PHP_AUTH_USER' => 'guest', 'PHP_AUTH_PW' => 'guest']);
    $this->assertEquals(200, $call->getStatusCode());

    $items = json_decode($call->getContent());

    $this->assertAny($items, function($media) {
        if ($media->medium == 'app') return true;
    });

    $this->assertNone($items, function($media) {
        if ($media->medium == 'facebook') return true;
    });

If this would be useful to the wider community, I'd love to submit a PR once I've developed it further. Thanks!

**Comment by sebastianbergmann** [comment]
Sorry to reply only now, after @b00giZm already invested time in this. I am not sure that I would want to add this to PHPUnit. At first glance it looks like a perfect candidate for an extension.

**Comment by keradus** [comment]
big :-1: for the feature in presented form as well.
passing random callbacks to decide about outcome of assertion is sad. instead of running a concrete assertion, decision is done in callback. no control about error msg.
**if** sth like this could happen, I would advise to:
- handle not only `any` and `non`, but also `all`
- let it be a collection wrapper for any already existing assertion.

Also, I must admit that I never have to use sth like this.

**Comment by sebastianbergmann** [comment]
What @keradus describes is already possible through `assertThat()`, `assertLogicalAnd()`, `assertLogicalOr()`, etc. and constraint objects.
