### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined method PHPUnit_Util_Configuration::getTestdoxGroupConfiguration() in C:\laragon\www\forum-tdd-apps\vendor\phpunit\phpunit\src\TextUI\TestRunner.php:1066

### ISSUE THREAD

**Issue by chisumo2016** [sebastianbergmann/phpunit#2761]
Hi need some help how to resolve the below problem .I am using  laravel 5.4
C:\laragon\www\forum-tdd-apps>phpunit
PHP Fatal error:  Uncaught Error: Call to undefined method PHPUnit_Util_Configuration::getTestdoxGroupConfiguration() in C:\laragon\www\forum-tdd-apps\vendor\phpunit\phpunit\src\TextUI\TestRunner.php:1066
Stack trace:
#0 C:\laragon\www\forum-tdd-apps\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(163): PHPUnit_TextUI_TestRunner->handleConfiguration(Array)
#1 C:\xampp\php\pear\PHPUnit\TextUI\Command.php(176): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#2 C:\xampp\php\pear\PHPUnit\TextUI\Command.php(129): PHPUnit_TextUI_Command->run(Array, true)
#3 C:\xampp\php\phpunit(46): PHPUnit_TextUI_Command::main()
#4 {main}
  thrown in C:\laragon\www\forum-tdd-apps\vendor\phpunit\phpunit\src\TextUI\TestRunner.php on line 1066

Fatal error: Uncaught Error: Call to undefined method PHPUnit_Util_Configuration::getTestdoxGroupConfiguration() in C:\laragon\www\forum-tdd-apps\vendor\phpunit\phpunit\src\TextUI\TestRunner.php:1066
Stack trace:
#0 C:\laragon\www\forum-tdd-apps\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(163): PHPUnit_TextUI_TestRunner->handleConfiguration(Array)
#1 C:\xampp\php\pear\PHPUnit\TextUI\Command.php(176): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#2 C:\xampp\php\pear\PHPUnit\TextUI\Command.php(129): PHPUnit_TextUI_Command->run(Array, true)
#3 C:\xampp\php\phpunit(46): PHPUnit_TextUI_Command::main()
#4 {main}

C:\laragon\www\forum-tdd-apps>phpunit
PHP Fatal error:  Uncaught Error: Call to undefined method PHPUnit_Util_Configuration::getTestdoxGroupConfiguration() in C:\laragon\www\forum-tdd-apps\vendor\phpunit\phpunit\src\TextUI\TestRunner.php:1066
Stack trace:
#0 C:\laragon\www\forum-tdd-apps\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(163): PHPUnit_TextUI_TestRunner->handleConfiguration(Array)
#1 C:\xampp\php\pear\PHPUnit\TextUI\Command.php(176): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#2 C:\xampp\php\pear\PHPUnit\TextUI\Command.php(129): PHPUnit_TextUI_Command->run(Array, true)
#3 C:\xampp\php\phpunit(46): PHPUnit_TextUI_Command::main()
#4 {main}
  thrown in C:\laragon\www\forum-tdd-apps\vendor\phpunit\phpunit\src\TextUI\TestRunner.php on line 1066

Fatal error: Uncaught Error: Call to undefined method PHPUnit_Util_Configuration::getTestdoxGroupConfiguration() in C:\laragon\www\forum-tdd-apps\vendor\phpunit\phpunit\src\TextUI\TestRunner.php:1066
Stack trace:
#0 C:\laragon\www\forum-tdd-apps\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(163): PHPUnit_TextUI_TestRunner->handleConfiguration(Array)
#1 C:\xampp\php\pear\PHPUnit\TextUI\Command.php(176): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#2 C:\xampp\php\pear\PHPUnit\TextUI\Command.php(129): PHPUnit_TextUI_Command->run(Array, true)
#3 C:\xampp\php\phpunit(46): PHPUnit_TextUI_Command::main()
#4 {main}
  thrown in C:\laragon\www\forum-tdd-apps\vendor\phpunit\phpunit\src\TextUI\TestRunner.php on line 1066

**Comment by sebastianbergmann** [comment]
It appears that you have different installation of PHPUnit mixed up.

For instance, you may have used Composer to install PHPUnit and have configured the autoloader generated by Composer as PHPUnit's bootstrap script but then you invoke PHPUnit using an executable other than `vendor/bin/phpunit`.
