### ISSUE TITLE
Optionally mark a test as risky when an unconfigured method is called on a test double

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#2763]
This could be implemented by (optionally) throwing an exception when an unconfigured method call is detected in https://github.com/sebastianbergmann/phpunit/blob/a1b5663a426b85854e97dce080a3546907836d5a/src/Framework/TestCase.php#L1147

**Comment by sebastianbergmann** [comment]
This could be implemented that https://github.com/sebastianbergmann/phpunit-mock-objects/blob/2f789b59ab89669015ad984afa350c4ec577ade0/src/Generator/mocked_method.tpl.dist#L16 (optionally) throws an exception when no invocation is expected.

**Comment by sebastianbergmann** [comment]
This could be implemented by (optionally) throwing an exception when an unconfigured method call is detected in https://github.com/sebastianbergmann/phpunit/blob/a1b5663a426b85854e97dce080a3546907836d5a/src/Framework/TestCase.php#L1147

This would likely be less work to implement than what is outlined in https://github.com/sebastianbergmann/phpunit/issues/2763#issuecomment-324860595 with the additional benefit of being cleaner.

**Comment by ciaranmcnulty** [comment]
Would this be an option in phpunit.xml, or do you mean when using the risky tests general option?

**Comment by sebastianbergmann** [comment]
There is no "general option" for risky test checks. Each check has its own configuration flag.

**Comment by sebastianbergmann** [comment]
It's not solved in PHPUnit 7.0.3 but rather in phpunit-mock-objects 6.1.0.
