### ISSUE TITLE
TestListener forward compability

### ISSUE THREAD

**Issue by jayS-de** [sebastianbergmann/phpunit#2765]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 5.7.21
| PHP version         | 7.1.5
| Installation Method | Composer

Version 5.7.21 introduced `PHPUnit\Framework\Test` in order to be able to create TestListeners which work both with PHPUnit 5+6.

But the method signature is still invalid and fails when trying to execute a PHPUnit 6 compatible TestListener with PHPUnit 5.7.21

```
namespace MyTest;

use PHPUnit\Framework\AssertionFailedError;
use PHPUnit\Framework\BaseTestListener;
use PHPUnit\Framework\Test;

class ErrorListener extends BaseTestListener
{
    public function addError(Test $test, \Exception $e, $time)
    {
        printf("Error while running test '%s'.\n", $test->getName());
    }

    public function addFailure(Test $test, AssertionFailedError $e, $time)
    {
        printf("Test '%s' failed.\n", $test->getName());
    }
}
```

The resulting error message:

```
PHP Fatal error:  Declaration of MyTest\ErrorListener::addError(PHPUnit\Framework\Test $test, Exception $e, $time) must be compatible with PHPUnit_Framework_TestListener::addError(PHPUnit_Framework_Test $test, Exception $e, $time) in ErrorListener.php on line 12
```

Only possible workaround is atm to create one PHPUnit 5 and one PHPUnit 6 compatible listener and based on the PHPUnit version use a different listener configuration, where one could question the forward compatibility layer. ;)

**Comment by b1rdex** [comment]
See #2715

**Comment by sebastianbergmann** [comment]
I do not think that it makes sense to support different (major) versions of PHPUnit in the same test suite. And I do not know what more could be done in the forward compatibility layer.

**Comment by b1rdex** [comment]
@sebastianbergmann support of different major versions is needed in phpunit plugins, not test suite.
Please see https://github.com/mybuilder/phpunit-accelerator/pull/13 for example.
As for how to improve compability — please see #2715, `class_alias` is the only way.
