### ISSUE TITLE
code and documentation disagree about test-execution-timeout and annotation

### ISSUE THREAD

**Issue by SimonHeimberg** [sebastianbergmann/phpunit#2768]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.4-ge9d4d9281
| PHP version         | 5.3/7.0
| Installation Method | Composer

The documentation tells that tests without any size annotation (`@small`, `@medium`, `@large`, `@group small`, ...) are treated as small:
https://phpunit.de/manual/current/en/risky-tests.html#risky-tests.test-execution-timeout

But this is not how it works. When no size annotation is set (`UNKNOWN`), no timeout is enforced:
https://github.com/sebastianbergmann/phpunit/blob/400316a5c57914d47d1cc03063fba8a52b9dd423/src/Framework/TestResult.php#L675

Should we adapt the documentation or the code?

**Comment by sebastianbergmann** [comment]
The documentation needs to be updated.
