### ISSUE TITLE
bootstrap does not contain env options defined in phpunit.xml

### ISSUE THREAD

**Issue by makasim** [sebastianbergmann/phpunit#277]
I tried to define `APPLICATION_ENV` option in the phpunit.xml file:

```
<phpunit>

     ...

     <php>
         <env name="APPLICATION_ENV" value="test"/>
     </php>
</phpunit>
```

And found out that this option wouldn't avaliable in `bootsrap.php`:

```
var_dump($_ENV);
// array(0) {
//}
```

but but perfectly exist in the test. 

```
class FooTest extends PHPUnit_Framework_TestCase
{
    public function testFoo()
    {
        var_dumP($_ENV);
        //array(1) {
        //  ["APPLICATION_ENV"]=>
        //  string(4) "test"
        // }

    }
}
```

can you comment on this behavior because for me it seems right to have those options in bootstrap.php

**Comment by kanduvisla** [comment]
I'm experiencing this issue in PHPUnit 4.5.0

**Comment by rdohms** [comment]
I'm having this issue with PHPunit 5.2.11 installed via composer. Funny enough if i use a PHPunit 4.5 runtime (left over in /usr/local/bin) it will run saying "5.2.11" but will load vars.

**Comment by sebastianbergmann** [comment]
@rdohms Please open a new ticket that contains a minimal, self-contained, reproducing test case. Thanks!

**Comment by rdohms** [comment]
ok, let me give it a try
