### ISSUE TITLE
Test definition alternative to methods

### ISSUE THREAD

**Issue by Netmosfera** [sebastianbergmann/phpunit#2774]
Hello. This has likely been discussed already. I'm sorry if this request is old, but I couldn't find anything official.

It would be nice if PHPUnit had an alternative to methods for the definition of tests. The problem I and many others have with that is that they often get very long.

```
function testThat...(){} // easily goes up to 90+ columns
```

I would like to be more descriptive with test names, but I never do, because I don't want to scroll horizontally later. Test name could be just a string, and that would be great because strings can go multiline, they can be divided in smaller chunks, etc. Something like...

```
$testCase = new TestCase();
$testCase->add(
    "Test that foo is bar",
    function(){}
);

// being equivalent to:

class MyClassTest extends TestCase{
    function test_that_foo_is_bar(){}
}
```
(Note: I'm not suggesting to do exactly this, I haven't actually worked out the details... but something like that...)

Thoughts? Thank you in advance.

**Comment by sebastianbergmann** [comment]
I do not like this idea, sorry.
