### ISSUE TITLE
Could not use "PHPUnit_TextUI_ResultPrinter" as printer

### ISSUE THREAD

**Issue by ShahrokhNiakan** [sebastianbergmann/phpunit#2776]
CI unit test falling in php7

got this error  :

The command "composer update" exited with 0.
$ composer dump-autoload
Generating autoload files
The command "composer dump-autoload" exited with 0.
$ phpunit
PHPUnit 6.3.0 by Sebastian Bergmann and contributors.
Could not use "PHPUnit_TextUI_ResultPrinter" as printer.
The command "phpunit" exited with 1.
Done. Your build exited with 1.

**Comment by sebastianbergmann** [comment]
It appears that you have different installations of PHPUnit mixed up.

For instance, you may have used Composer to install PHPUnit and have configured the autoloader generated by Composer as PHPUnit's bootstrap script but then you invoke PHPUnit using an executable other than `vendor/bin/phpunit`.

**Comment by chippyash** [comment]
$ vendor/bin/phpunit --configuration ./phpunit.travis.xml test
PHPUnit 7.0.0 by Sebastian Bergmann and contributors.

Could not use "PHPUnit_TextUI_ResultPrinter" as printer: class does not exist

$ php -v
PHP 7.1.9 (cli) (built: Feb  3 2018 19:59:18) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans

so - possibly not solved

**Comment by MagicMarvMan** [comment]
I have the same problem. I am using PhpUnit 6.3.0 with PHP 7.1.9 and the following error occurs when I build my PHP application (https://github.com/contentmonkey/contentmonkey) using Travis and PHPUnit:
`PHPUnit 6.3.0 by Sebastian Bergmann and contributors.
Could not use "PHPUnit_TextUI_ResultPrinter" as printer.`

**Comment by davidyell** [comment]
I found that this issue was caused by my `phpunit.xml` file which had the following line.

`printerClass="PHPUnit_TextUI_ResultPrinter"`
