### ISSUE TITLE
@depends for classes

### ISSUE THREAD

**Issue by Netmosfera** [sebastianbergmann/phpunit#2782]
Hello. I would like to instruct PHPUnit to run tests in a TestClass before running some other tests.
Basically like `@depends`, but for classes.

```php
/** @dependsOn YourTest */
class MyTest extends TestCase{}

class YourTest extends TestCase{}

// or

class AAATest extends TestCase{}

class BBBTest extends TestCase{
    /** @dependsOn AAATest */
    function testFoo(){}
}
```

Thoughts?

**Comment by Netmosfera** [comment]
Also, if someone is nice enough to give me some pointers on how the feature should be implemented, I could attempt implementing it. Thanks

**Comment by sebastianbergmann** [comment]
It does not make sense to me for a test to depend on all tests of a test case class.

Furthermore, currently the test runner can currently not guarantee that the tests of one test case class are executed before those of another.
