### ISSUE TITLE
Malformed jUnit file with multiple Test Suite

### ISSUE THREAD

**Issue by joel-depiltech** [sebastianbergmann/phpunit#2784]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.3.1
| PHP version         | 7.1.5
| Installation Method | Composer

Hello,
When I have only one test suite the jUnit file generated start like this :
`<?xml version="1.0" encoding="UTF-8"?> <testsuites> <testsuite name="CodeIgniter Gettext Test Suite" tests="13" assertions="20" failures="0" errors="0" time="0.089406"> <testsuite name="CodeIgniterGetText\Tests\HelperTest" file="/Volumes/www/joel/codeigniter-gettext/tests/HelperTest.php" tests="3" assertions="7" failures="0" errors="0" time="0.020020"> <testcase name="testDoubleUnderscore" class="CodeIgniterGetText\Tests\HelperTest" file="/Volumes/www/joel/codeigniter-gettext/tests/HelperTest.php" line="9" assertions="2" time="0.015318"/>`

But when I have multiple Test Suite, the jUnit file start like that :
`<?xml version="1.0" encoding="UTF-8"?> <testsuites> <testsuite name="" tests="109" assertions="1387" errors="0" failures="3" skipped="0" time="295.482437"> <testsuite name="Odoo Api Php Test Suite" tests="108" assertions="1386" errors="0" failures="2" skipped="0" time="295.479753"> <testsuite name="DepilTech\OdooApiPhp\Tests\ActivityTest" file="/Volumes/www/joel/odoo-api-php/tests/ActivityTest.php" tests="2" assertions="12" errors="0" failures="0" skipped="0" time="4.353505"> <testcase name="testLaunchClassics" class="DepilTech\OdooApiPhp\Tests\ActivityTest" classname="DepilTech.OdooApiPhp.Tests.ActivityTest" file="/Volumes/www/joel/odoo-api-php/tests/ActivityTest.php" line="17" assertions="3" time="2.332940"/>`

So phpunitreport phing task doesn't work. I think the XSL stylesheet cannot parse this second XML.

Please can you help me ?

Regards,
Joël

**Comment by sebastianbergmann** [comment]
According to `http://llg.cubic.org/docs/junit`, the `<testsuites>` element can be omitted when only a single `<testsuite>` element is present. This is what PHPUnit's JUnit XML logfile writer does.

Please report this problem to Phing.
