### ISSUE TITLE
Wrong closure scope in `->will(\Closure)`, using prophecy

### ISSUE THREAD

**Issue by iltar** [sebastianbergmann/phpunit#2786]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.3.1
| PHP version         | 7.1.9
| Installation Method | composer

First of all, I'm not entirely sure this is a bug in the first place. When calling an assertion from a `Promise\CallbackPromise`, the static scope is rebound, causing all kind of buggy behavior. I don't think this is completely the way it was designed to work, but it fits our use-case.

Assume the following script:
```php
interface TestInterface
{
    public function stub();
}

class SimpleTest extends TestCase
{
    public function test()
    {
        $prophecy = $this->prophesize(TestInterface::class);
        $prophecy->stub()->will(function() {
            var_dump(static::class);
            var_dump(self::class);
        });

        $prophecy->reveal()->stub();
    }
}

// gives me the following output:
string(32) "Prophecy\Prophecy\ObjectProphecy"
string(10) "SimpleTest"
```

As you can see, the static scope has been rebound. Now when I try to make an assertion from this class, it will fail unless I use the class name directly to break out of the scope. I tried reproducing this code but I was unable to properly get this to trigger (I might have missed something).

```php
$prophecy->stub()->will(function() {
    // Error: Call to undefined method Prophecy\Prophecy\ObjectProphecy::assertThat()
    self::assertInstanceOf(SimpleTest::class, $this);

    // Prophecy\Exception\Doubler\MethodNotFoundException: Method `Double\TestInterface\P10::assertInstanceOf()` is not defined.
    static::assertInstanceOf(SimpleTest::class, $this);

    // Prophecy\Exception\Doubler\MethodNotFoundException: Method `Double\TestInterface\P10::assertInstanceOf()` is not defined.
    $this->assertInstanceOf(SimpleTest::class, $this);

    // works!
    SimpleTest::assertInstanceOf(SimpleTest::class, $this);

    // though the test fails:
    // Failed asserting that Prophecy\Prophecy\ObjectProphecy Object (...) is an instance of class "SimpleTest".
});
```
The reason this fails with `self`, is because the `TestCase` calls `static::assertThat` instead of `self::assertThat`. The other scenarios can't easily be fixed afaik, unless the scope is bound properly (which would implicitly fix the self call as well).

Found this issue after inspecting our codebase where php inspections was saying the class name could be replaced by `self`: kalessil/phpinspectionsea#564

**Comment by sebastianbergmann** [comment]
ping @everzet @stof @ciaranmcnulty

**Comment by stof** [comment]
Well, binding the callback to the ObjectProphecy was done on purpose, to make it simple to reconfigure the test double in the callback (for instance changing what `getName` will return after `setName` was called). See https://github.com/phpspec/prophecy#method-prophecies-idempotency for the documentation about it.
Removing the binding would be a BC break in Prophecy.

Btw, making PHPUnit assertions in the `->will` callback is weird, as this callback is here to define the effect of the call. They are not meant to be used to performed assertions on the arguments. Argument matchers are meant for that.

**Comment by iltar** [comment]
@stof correct, I fully agree with that. This was merely "legacy" code that I found that does some weird stuff and I was wondering if it would be a bug, or merely a side effect of doing something in a way it wasn't designed to. The full assertion:

```php
// Make sure the message is persisted, flushed with the state 'inactive' and flushed again with state 'ready'
$this->entity_manager->persist(Argument::type(AbstractMessage::class))->will(function ($arguments) {
    MessageFactoryTest::assertInstanceOf(AbstractMessage::class, $arguments[0]);
    $this->flush()->shouldBeCalledTimes(2)->will(function () use ($arguments) {
        MessageFactoryTest::assertSame(MessageState::INACTIVE, $arguments[0]->getState());
        $this->flush()->will(function () use ($arguments) {
            MessageFactoryTest::assertSame(MessageState::READY, $arguments[0]->getState());
        });
    });
});
```

If this is not a bug, but working as intended, this can be closed.

**Comment by stof** [comment]
Btw, your `assertInstanceOf` assertion is totally useless, as you used a `Argument::type(AbstractMessage::class)` matcher.

**Comment by iltar** [comment]
You're right (legacy :cry:), but the assertSame internally also calls `static::assertThat`
