### ISSUE TITLE
Coverage flag do not negate previously disabled coverage

### ISSUE THREAD

**Issue by sanmai** [sebastianbergmann/phpunit#2787]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 5.7.22, 6.3.1
| PHP version         | 7.0.22
| Installation Method | Composer / PHAR

Coverage flag do not enable coverage when it was previously disabled. E.g. this won't generate coverage:

    vendor/bin/phpunit --no-coverage --coverage-clover=build/logs/clover.xml

This could be useful in CI builds where you don't need any other type of coverage possibly enabled in `phpunit.xml`.

**Comment by sebastianbergmann** [comment]
This is expected behavior and I have no intention of changing that.

**Comment by sanmai** [comment]
Would you reject a PR for an additional flag with a different behavior?

**Comment by sebastianbergmann** [comment]
Yes.
