### ISSUE TITLE
PHPUnit does not exit on CTRL + C in Docker

### ISSUE THREAD

**Issue by nesl247** [sebastianbergmann/phpunit#2788]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.3.1
| PHP version         | PHP 7.1.10
| Installation Method | Composer

When running PHPUnit inside of docker, and running it with `run -it` inside of a php-cli container, it does not exit when hitting CTRL + C.

I filed an issue here: https://github.com/docker-library/php/issues/505 and they said it was on the individual projects to handle `SIGINT`.

Copying from the linked ticket, this is the command I am running `docker run --rm -it -v $PWD:/application -w /application php:7.1-alpine php vendor/bin/phpunit`. I run this normally through docker-compose, but this is the `docker run` equivalent, and I have tested with it too.

**Comment by sebastianbergmann** [comment]
Sorry, but I am not going to do anything about this. I do not believe that PHPUnit should do something about events such as `SIGINT`. If, at all, that would be the job of PHP itself.

That being said, I think that you should use the solution provided in https://github.com/docker-library/php/issues/505#issuecomment-334274337 and add `--init` to your Docker invocation. That way PHP won't have PID 1 and CTRL+C should not be treated specially for its process.
