### ISSUE TITLE
Testcase does not open, throws ' Cannot open file "mytest.php" '

### ISSUE THREAD

**Issue by vairav** [sebastianbergmann/phpunit#279]
Hi,
   I have installed PHPUnit 3.5.14 using the Pear package installation on my sandbox that runs CentOS 5.2

When I tried to execute my testcases located at the location:

```
    /var/www/testcases/mytest.php
```

using the terminal command:

```
    phpunit mytest.php
```

This is throwing me the following error:

PHPUnit 3.5.14 by Sebastian Bergmann.

Cannot open file "mytest.php".

I have even tried to uninstall and reinstall phpunit, but then its still throwing the same error.
The code inside mytest.php is as follows:

<?php
class mytest extends PHPUnit_Framework_TestCase
{
    public function testOne()
    {
        $this->assertTrue(FALSE);
    }

```
/**
 * @depends testOne
 */
public function testTwo()
{
}
```

}
?>

Any help would be highy appreciated.
Thanks for looking into my post.

Regards,
LoGiX

**Comment by ProfNandaa** [comment]
Ran through same issue, had not fixed path to the bootstrap.php on the phpunit.xml file...

**Comment by spidgorny** [comment]
I had ``include_path`` sections separated by comma. It has to be semicolon on Windows.

**Comment by pumamammal** [comment]
I have been trying to install PHPunit for 5days!. now its working and am having this error which might be the last I will have. 

I am geting "cannot open file filename.php"

please help!!

**Comment by sebastianbergmann** [comment]
@pumamammal I would like to understand why it took you five days to install PHPUnit as I would like to improve the documentation accordingly. Can you please open a ticket at https://github.com/sebastianbergmann/phpunit-documentation/issues/new and explain where https://phpunit.de/getting-started.html and https://phpunit.de/manual/current/en/installation.html failed you?

As for your `cannot open file filename.php` issue, @pumamammal, please understand that I can only make sense of complete output and not just random snippets, sorry.

**Comment by bpfruin** [comment]
I'm having the same error too after working through a few other nasty ones.  I've been at this for 5 days nonstop as well.  Safe mode is off, permissions are 777.  I don't have a bootstrap.php file.  Is that necessary?  If so, is there any documentation on how to create one?  I'm a novice developer.

**Comment by poldiwa** [comment]
I'm getting same error too, but when I don't specify a file it run with no problem.
I'm a newbie too.
PHPUnit 5.4.6, install via Composer 1.1.2, Windows 10 64 bit.

**Comment by lingeors** [comment]
I'm getting the same error too, and I try to solve it through the following steps
- require the autoload.php file
- I try to using the command "phpunit myFile.php",  adding ".php"
and it work. though I know nothing.
phpunit 5.5.0, windows 10 64 bit, php5.6

**Comment by mboo2005** [comment]
I'm getting the same error too. My enviroment is:
Lumen,phpunit 6.0
![screen shot 2017-03-16 at 11 56 09 am](https://cloud.githubusercontent.com/assets/533149/23981225/e2d0fea2-0a3f-11e7-9a7e-5733c6dbb8cf.png)
![screen shot 2017-03-16 at 11 56 20 am](https://cloud.githubusercontent.com/assets/533149/23981221/e2cbccb6-0a3f-11e7-9fdf-5fd41d665b15.png)
phpunit.xml:
![screen shot 2017-03-16 at 11 56 30 am](https://cloud.githubusercontent.com/assets/533149/23981220/e2cba5b0-0a3f-11e7-9881-7935984732b1.png)
![screen shot 2017-03-16 at 11 56 40 am](https://cloud.githubusercontent.com/assets/533149/23981222/e2cc3f0c-0a3f-11e7-8f13-dccb80964e99.png)
![screen shot 2017-03-16 at 11 57 58 am](https://cloud.githubusercontent.com/assets/533149/23981224/e2ce4b08-0a3f-11e7-9244-1cee6c2c4cfd.png)
![screen shot 2017-03-16 at 11 58 07 am](https://cloud.githubusercontent.com/assets/533149/23981226/e2fe439e-0a3f-11e7-9a52-ca4d8986c171.png)
![screen shot 2017-03-16 at 11 58 18 am](https://cloud.githubusercontent.com/assets/533149/23981227/e2ff8d62-0a3f-11e7-8aae-1375300ac0a6.png)

**Comment by mboo2005** [comment]
I solved the problem!!
Correct syntax:  phpunit tests/PagesTest .
Inspired by https://phpunit.de/manual/current/en/organizing-tests.html#organizing-tests.filesystem

Thank you

**Comment by AnderSouza** [comment]
In my case, just adding '.php' at the end of the filename worked.
Instead of 
'phpunit CarTest'
use 
'phpunit CarTest.php'.

I hope it helps. :D

**Comment by terdia** [comment]
if you use the full path it should be okay for example when I used unit --bootstrap "C:\xampp\htdocs\general-php\vendor\autoload.php" tests issue resolved

**Comment by Goahnary** [comment]
I am still having this issue. I call php unit on the file with and without the ".php" extension. I reference the bootstrap.php file in my xml correctly and I also have tried referencing it explicitly with "--bootstrap". I can also run another test file in the same folder just fine. All of them actually except this one. They all have the same permissions.

```
noahgary@Noahs-MBP:~/Projects/han-api/infrastructure/Testing/Unit$ ls -l
total 80
-rw-r--r--  1 noahgary  staff   2.2K Apr 12 12:59 CartTypeTest.php
-rw-r--r--  1 noahgary  staff   2.4K Apr 12 12:59 ConditionTest.php
-rw-r--r--  1 noahgary  staff   2.4K Apr 12 12:59 CountryTest.php
-rw-r--r--  1 noahgary  staff   2.2K Apr 12 12:59 FeeTypeTest.php
-rw-r--r--  1 noahgary  staff   2.6K Apr 12 12:59 OrderItemStatusTest.php
-rw-r--r--  1 noahgary  staff   2.4K Apr 12 12:59 OrderStatusTest.php
-rw-r--r--  1 noahgary  staff   2.6K Apr 12 17:05 OrganizationTest.php
-rw-r--r--  1 noahgary  staff   2.7K Apr 12 12:59 OrganizationTypeTest.php
-rw-r--r--  1 noahgary  staff   2.5K Apr 12 12:59 QuantityTypeTest.php
-rw-r--r--  1 noahgary  staff   2.3K Apr 12 16:52 UserTest.php
```

**Comment by JustAWebDev** [comment]
Same for me.  Simply adding the "--filter" flag worked.  Otherwise it didn't.
