### ISSUE TITLE
expectException() & friends should have a message parameter

### ISSUE THREAD

**Issue by joachim-n** [sebastianbergmann/phpunit#2793]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.3.0
| PHP version         | 7.0
| Installation Method | Composer

The methods for testing exception throwing such as expectException() should have a message parameter the same was that assertion methods do, so that when an expectation fails, the developer gets a meaningful message.

**Comment by sebastianbergmann** [comment]
I do not think so.

I think that the optional message parameter only makes sense for generic, unspecific assertions methods such as `assertTrue()`, for instance. Over time, something like
```php
$this->assertTrue(empty($array), 'Array should be empty');
```
evolved to
```php
$this->assertEmpty($array);
```
As the framework is now able to generate a specific failure message, the optional message parameter became less useful.
