### ISSUE TITLE
Tests with @runInSeparateProcess fail on travis with PHP 7.1.10

### ISSUE THREAD

**Issue by uwetews** [sebastianbergmann/phpunit#2795]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     |6.4.0
| PHP version         | 7.1.10
| Installation Method | Composer / PHAR

All test with @runInSeparateProcess fail on travis for 7.1.10
Error message is

Fatal error: strict_types declaration must be the very first statement in the script in /home/travis/.phpenv/versions/7.1.10/bin/phpunit on line 2
Call Stack:
    0.0002     385816   1. {main}() -:0

PHP version 7.1.9  works fine

**Comment by sebastianbergmann** [comment]
This was fixed in PHPUnit 6.4.1 (see https://github.com/sebastianbergmann/phpunit/issues/2791).
