### ISSUE TITLE
assertRessourceType()

### ISSUE THREAD

**Issue by jonathanparentlevesque** [sebastianbergmann/phpunit#2802]
By example, I want to make sure that my method (in a trait) returns an FTP resource.

```
public function testGetFTPConnection()
	{
		$errorMessage = "";
		
		$ftp = $this->getFTPConnection($errorMessage);
		
		$this->assertEmpty($errorMessage);
		
		$this->assertTrue(is_resource($ftp));
		
		$this->assertEquals(
			"FTP Buffer",
			get_resource_type($ftp)
		);
		
		ftp_close($ftp);
	}
```

Personally, I would use 2 native functions for the validation:

- `is_resource()` : http://php.net/manual/fr/function.is-resource.php
-  `get_resource_type()` : http://php.net/manual/fr/function.get-resource-type.php

Thank you

**Comment by sebastianbergmann** [comment]
I agree with what @sebastianfeldmann wrote in https://github.com/sebastianbergmann/phpunit/pull/2808#issuecomment-419648431.
