### ISSUE TITLE
expectException always checks Exception message

### ISSUE THREAD

**Issue by jordisala1991** [sebastianbergmann/phpunit#2809]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 5.7.23
| PHP version         | 7.1.10
| Installation Method | PHAR

With this new version (5.7.23) it is mandatory to define the exception message when asserting an exception. With the previous version (5.7.22) it was not needed.

Code:

```
    public function testInvalidMetas()
    {
        $page = new SeoPage();

        $this->expectException('\RuntimeException');

       // this will throw an exception
        $page->setMetas([
            'type' => 'not an array',
        ]);
    }
```

Before (5.7.22):

```
WARNINGS!
Tests: 31, Assertions: 72, Warnings: 6.

Remaining deprecation notices (2)
```

After (5.7.23):

```
1) Sonata\SeoBundle\Tests\Seo\SeoPageTest::testInvalidMetas
Failed asserting that exception message is empty but is '$metas must be an array'.

FAILURES!
Tests: 31, Assertions: 73, Failures: 1, Warnings: 6.

Remaining deprecation notices (2)
```

Possible related code: 

https://github.com/sebastianbergmann/phpunit/commit/567ca23a4c62e8b9bcefae0b39b5f33e3853c2c2#commitcomment-24975103
https://github.com/sebastianbergmann/phpunit/pull/2807

Prof PR of failing builds:

https://travis-ci.org/sonata-project/SonataPageBundle/builds/288289797

And it is failing on other Sonata projects that test exceptions

**Comment by jordisala1991** [comment]
Closing, it is on our side. https://github.com/sonata-project/SonataSeoBundle/blob/a101e6892127513607aa8b95a762b77ee9e85740/tests/Helpers/PHPUnit_Framework_TestCase.php#L31-L33

**Comment by jordisala1991** [comment]
Not really sure if it is still a BC break on phpunit or a bug fixing. Because that code worked with the old version. If I remove that interface and go directly with Phpunit testcase it works again...

**Comment by sebastianbergmann** [comment]
567ca23a4c62e8b9bcefae0b39b5f33e3853c2c2 and 182941e21951a3fa6d1cff158319746a1f8d53f4 are backward compatible bug fixes. You only ran into an issue because of your layer on top of PHPUnit.
