### ISSUE TITLE
6.4.2 breaks tests using expectExceptionMessage that worked in 6.4.1

### ISSUE THREAD

**Issue by emil-nasso** [sebastianbergmann/phpunit#2811]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | Upgraded from 6.4.1 to 6.4.2
| PHP version         | 7.1
| Installation Method | Composer 

The following test passes in `6.4.1`.

```php

    public function test_exception() {
        $this->expectExceptionMessage("hello");
        throw new \Exception("hello");
    }
```

It no longer passes in `6.4.2`. Running it in `6.4.2` produces the following output:

```
Testing started at 13:35 ...
PHPUnit 6.4.2 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.8 with Xdebug 2.5.5
Configuration: /X/phpunit.xml

hello
 /X/EncrypterTest.php:55
 
Time: 85 ms, Memory: 8.00MB

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```

**Comment by emil-nasso** [comment]
It seems like this has been an issue before that has been reintroduced:

https://github.com/sebastianbergmann/phpunit/issues/2299

**Comment by emil-nasso** [comment]
A workaround is to expect an exception before expecting the exception message.

```php
public function test_exception() {
        $this->expectExceptionMessage("hello");
        throw new \Exception("hello");
}
```

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.
