### ISSUE TITLE
PHPUnit wrong junit xml format

### ISSUE THREAD

**Issue by pravinsp26** [sebastianbergmann/phpunit#2812]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.0.3
| PHP version         | 7.0.22
| Installation Method | PHAR

Hello, 
Currently I am using below command to export unit test case result into XML and I am using phing to read this .xml and trying to generate HTML report.

phpunit --log-junit log.junit.xml --configuration phpunit.xml

However when I generate XML using above command then it add one extra parent <testsuite> tags into XML like below...

`<testsuites>
    <testsuite>  - Extra tag      
        <testsuite> - Extra tag  
            <testsuite>   
                <testcase></testcase>     
            </testsuite>    
        </testsuite>
    </testsuite>
</testsuites>`

And as per phpunit logging manual... junit format look like

`<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="ArrayTest"
             file="/home/sb/ArrayTest.php"
             tests="2"
             assertions="2"
             failures="0"
             errors="0"
             time="0.016030">
    <testcase name="testNewArrayIsEmpty"
              class="ArrayTest"
              file="/home/sb/ArrayTest.php"
              line="6"
              assertions="1"
              time="0.008044"/>
    <testcase name="testArrayContainsAnElement"
              class="ArrayTest"
              file="/home/sb/ArrayTest.php"
              line="15"
              assertions="1"
              time="0.007986"/>
  </testsuite>
</testsuites>`

Can you please help to generate proper junit XML format?

**Comment by sebastianbergmann** [comment]
I do not understand what you are trying to report.

**Comment by pravinsp26** [comment]
Sorry...XML sample was missing I have updated same.

**Comment by sebastianbergmann** [comment]
Sorry, but I still do not see what you think is wrong.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by pravinsp26** [comment]
Currently I have created sample PHPUnit project and executed following command
phpunit --log-junit log.junit.xml 

Which output following XML
`   <testsuite name="CalcultatorTest" file="/var/www/html/phpunit/test/calculator_test.php" tests="2" assertions="2" errors="0" failures="0" skipped="0" time="0.000203">
      <testcase name="testAdd" class="CalcultatorTest" classname="CalcultatorTest" file="/var/www/html/phpunit/test/calculator_test.php" line="6" assertions="1" time="0.000154"/>
      <testcase name="testSub" class="CalcultatorTest" classname="CalcultatorTest" file="/var/www/html/phpunit/test/calculator_test.php" line="11" assertions="1" time="0.000049"/>
    </testsuite>
    <testsuite name="CalcultatorTestOne" file="/var/www/html/phpunit/test/calculator_test_1.php" tests="2" assertions="2" errors="0" failures="0" skipped="0" time="0.000104">
      <testcase name="testMulti" class="CalcultatorTestOne" classname="CalcultatorTestOne" file="/var/www/html/phpunit/test/calculator_test_1.php" line="8" assertions="1" time="0.000054"/>
      <testcase name="testDiv" class="CalcultatorTestOne" classname="CalcultatorTestOne" file="/var/www/html/phpunit/test/calculator_test_1.php" line="13" assertions="1" time="0.000050"/>
    </testsuite>
  </testsuite>
</testsuites>`

And I am using following build.xml to export report into HTML

`<?xml version="1.0" encoding="utf-8"?>
<project name="testreport" default="gen-report" basedir=".">
 <target name="gen-report">
  <phpunitreport infile="log.junit.xml"
                 format="noframes"
                 todir="html"
                 styledir="/usr/share/php/data/phing/etc/"
                 />
 </target>
</project>`

And if I try to build using phing then it shows following error.
BUILD FAILED
ReflectionException: Class CalcultatorTest does not exist in /usr/share/php/phing/tasks/ext/phpunit/PHPUnitReportTask.php:228
Stack trace:

Also if i remove '<testsuite name="Tests" tests="4" assertions="4" errors="0" failures="0" skipped="0" time="0.000307">' from log.junit.xml then I am able to build using phing

Hope this is enough information to debug this.

**Comment by sebastianbergmann** [comment]
Sorry, I cannot help you.

**Comment by pravinsp26** [comment]
So is it not reproducible at you end?

**Comment by EnricoMi** [comment]
@sebastianbergmann So are you saying that `<testcase>` tags inside `<testcase>` tags is what phpunit does produce, and that the majority of JUnit XML parsers support that?

As in:
```xml
<testsuites>
  <testsuite ...>
    <testsuite ...>
      <testcase ../>
    </testsuite>
  </testsuite>
</testsuites>
```
