### ISSUE TITLE
Missing option "beStrictAboutUsesAnnotation"

### ISSUE THREAD

**Issue by lhess** [sebastianbergmann/phpunit#2813]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.4.2
| PHP version         | 7.1.10
| Installation Method | Composer

For now we have the configuration `forceCoversAnnotation` (which enables the class for code coverage reports; the name is a bit misleading btw.) and `beStrictAboutCoversAnnotation` (which makes phpunit complain if executed code is not annotated via `@covers` or `@uses`).

I would, however, like to be able to force the usage of `@covers`- and omit `@uses`-annotations for code which is being used within a `@covers`-annotated and tested class. Since I use, for instance, a lot of ValueObjects in my project, the maintenance of the `@uses` annotations is quite messy and exhausting.

I would like to see an option like `beStrictAboutUsesAnnotation`, which makes phpunit silent about missing `@uses` annotations, if it is set to `false`.

**Comment by rrelmy** [comment]
I expected the `forceCoversAnnotation` option to work independent of strict coverage.

I wish the [setCheckForMissingCoversAnnotation](https://github.com/sebastianbergmann/phpunit/blob/98d9e8d88d9403162a5a5a299a6a08e7645983cc/src/TextUI/TestRunner.php#L401) could be enabled without enabling `beStrictAboutCoversAnnotation`.
I think that would be easier to implement than `beStrictAboutUsesAnnotation`. What do you think about that?

**Comment by sebastianbergmann** [comment]
* `forceCoversAnnotation` is independent from `beStrictAboutCoversAnnotation`
* `forceCoversAnnotation=true` means that every test must have a `@covers` annotation
* `beStrictAboutUsesAnnotation=true` means that a test may only execute code that is listed using `@covers` or `@uses`

There is nothing to do here. Simply do not set `beStrictAboutUsesAnnotation=true` if you do not want that behaviour.
