### ISSUE TITLE
[PHPUnit Sprint] PHPUnit constraints split question

### ISSUE THREAD

**Issue by shrikeh** [sebastianbergmann/phpunit#2819]
@sebastianbergmann, good morning! A question: at the constraint breakaway is planned for 7, and we need to change a few things in the framework (where exceptions are pulled from etc in `Assert`, for example), how would you like to handle these PRs? Perhaps a long-term branch and appropriate labels? We can then reference the branch in our `require-dev` for now

**Comment by sebastianbergmann** [comment]
I think it would be best if you (or @localheinz) forks `sebastianbergmann/phpunit` (and adds the other as a collaborator). You can then make the required changes to PHPUnit in a new branch on the fork you control.

Once that branch of PHPUnit and the new component are "ready" you can send a pull request from your fork of `sebastianbergmann/phpunit`.
