### ISSUE TITLE
Installation using PHP 7.0 fails due to doctrine/instantiator 1.1.0 dependency

### ISSUE THREAD

**Issue by SeinopSys** [sebastianbergmann/phpunit#2823]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.4
| PHP version         | 7.0.22
| Installation Method | Composer

I'm trying to add PHPUnit as a dev dependency to a project of mine, which seems to fail on PHP 7.0 and prevents tests from succeeding. Travis CI gives me the following during the build process:

```
$ composer --version
Composer version 1.5.2 2017-09-11 16:59:25
0.27s

$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

 Problem 1
 - Installation request for doctrine/instantiator 1.1.0 -> satisfiable by doctrine/instantiator[1.1.0].
 - doctrine/instantiator 1.1.0 requires php ^7.1 -> your PHP version (7.0.22) does not satisfy that requirement.
 Problem 2
 - doctrine/instantiator 1.1.0 requires php ^7.1 -> your PHP version (7.0.22) does not satisfy that requirement.
 - phpunit/phpunit-mock-objects 4.0.4 requires doctrine/instantiator ^1.0.5 -> satisfiable by doctrine/instantiator[1.1.0].
 - Installation request for phpunit/phpunit-mock-objects 4.0.4 -> satisfiable by phpunit/phpunit-mock-objects[4.0.4].


The command "composer install" failed and exited with 2 during .

Your build has been stopped.
```

The issue can only be with PHPUnit as it's the only dependency in the repository, and it does not happen when using PHP 7.1

**Comment by kubawerlos** [comment]
Remove `composer.lock` and `vendor` directory and try again.

**Comment by localheinz** [comment]
Or run

```
$ composer remove phpunit/phpunit && require --dev phpunit/phpunit:^6.4 --update-with-dependencies
```

This should help as well without the need to remove `composer.lock` (as a subsequent `composer install` might pull in undesired updates).

**Comment by SeinopSys** [comment]
Removing `composer.lock` did it, thank you @kubawerlos!

**Comment by vsasvipul0605** [comment]
I have this same error. but I can't delete the composer.lock file as the same repository I'm deploying on heroku and build starts failing on heroku without composer.lock file

**Comment by SeinopSys** [comment]
@vsasvipul0605 It's been a while since I had this issue, but I think the idea is to delete the lock file and re-run `composer install` or `composer update` to get a fresh lock file without the issue

**Comment by vsasvipul0605** [comment]
but I told that I can't delete composer.lock file. composer.lock is must needed for heroku deployment

**Comment by kubawerlos** [comment]
@vsasvipul0605 yes you can :)

> I'm deploying on heroku and build starts failing on heroku without composer.lock file

So you can't have `composer.lock` deleted from your repository.

But you can delete the file, then run `composer update` and commit the modified `composer.lock`.

**Comment by vsasvipul0605** [comment]
I exactly did the same but _travis_ build error occurring again.
Any other _alternative_ solution?

**Comment by kubawerlos** [comment]
Have you tried Composer's flags `--update-with-dependencies` and `--update-with-all-dependencies`?

**Comment by vsasvipul0605** [comment]
Where to write these composer flags?

**Comment by kubawerlos** [comment]
In `composer require` command.

**Comment by vsasvipul0605** [comment]
i dont have composer require in my repo.
can u explain in detail.
repo details: https://github.com/vsasvipul0605/covid19-india-stats/tree/heroku

**Comment by kubawerlos** [comment]
Composer the tool itself has this command, see this comment: https://github.com/sebastianbergmann/phpunit/issues/2823#issuecomment-338506914

and use it with packages that make the trouble.

**Comment by vsasvipul0605** [comment]
still the same error. i tried this too.
