### ISSUE TITLE
print the report so far on ctrl+c

### ISSUE THREAD

**Issue by mathroc** [sebastianbergmann/phpunit#2832]
When I’m running phpunit sometimes I see that some tests I failing and I don’t want to wait until the end to see why. so I hit `ctrl+c` and I restart phpunit either on fewer tests or with `--stop-on-failure`

dependings on the tests it can takes a bit of time, so it would be nice if the first `ctrl+c` would instead print the report of the test that have already ended ( and maybe mark the current test if any as skipped because of user interruption)

**Comment by sebastianbergmann** [comment]
I do not think that this is worth implementing.

**Comment by jdufresne** [comment]
FWIW, this is a feature of Python's unittest module that I find extremely helpful. I think it would be a great addition to phpunit.

Perhaps you could explain your reasons why you think this isn't worth implementing?

**Comment by marcobuschini** [comment]
Hey @sebastianbergmann, I agree with @mathroc and @jdufresne but I am anyway moving away from PHP for this and many other reasons.
