### ISSUE TITLE
Test class loaded during data provider execution is not discovered

### ISSUE THREAD

**Issue by kubawerlos** [sebastianbergmann/phpunit#2833]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.4.3
| PHP version         | 7.1.11
| Installation Method | Composer

Having 2 test cases:
```php
<?php

class ATest extends \PHPUnit\Framework\TestCase
{
    /**
     * @dataProvider provide
     */
    public function testNothingA($x)
    {
        $this->assertTrue($x);
    }

    public function provide() : array
    {
        $a = new \ReflectionClass(BTest::class);

        return [[true]];
    }
}
```
and
```php
<?php

class BTest extends \PHPUnit\Framework\TestCase
{
    public function testNothingB()
    {
        $this->assertTrue(false);
    }
}
```
running them will result with executing only `ATest`.

It's not even listed:
```bash
vendor/bin/phpunit --list-tests
PHPUnit 6.4.3 by Sebastian Bergmann and contributors.

Available test(s):
 - Tests\ATest::testNothingA#0
```

After removing `$a = new \ReflectionClass(BTest::class);` or moving this line to `testNothingA` both classes will be executed. The problem is only with data provider.

**Comment by sebastianbergmann** [comment]
#2834 was reverted due to #2859

**Comment by kubawerlos** [comment]
So I use my test case from the first solution plus the test from https://github.com/sebastianbergmann/phpunit/issues/2859#issuecomment-344278138 and try again, right?

**Comment by sebastianbergmann** [comment]
Yes, please.

**Comment by keradus** [comment]
at PHP CS Fixer, we come across this issue as well. it will be great to addition to have this solved!
would be really great to have it solved :+1:
big :+1: for one actually working on it, we are with you @kubawerlos !
