### ISSUE TITLE
Reference (environment) variables in phpunit.xml

### ISSUE THREAD

**Issue by gempir** [sebastianbergmann/phpunit#2836]
I think It would be extremely useful and could make phpunit a lot more versatile if we could reference (environment) variables

An example:

    <testsuites>
        <testsuite name="unit">
            <directory>tests/unit</directory>
            <env name="TESTSUITE" value="unit"/>
        </testsuite>

        <testsuite name="system">
            <directory>tests/system</directory>
            <env name="TESTSUITE" value="system"/>
        </testsuite>
    </testsuites>

    <logging>
        <log type="coverage-html" target="build/coverage/${TESTSUITE}" title="rest-api" charset="UTF-8" lowUpperBound="35"
             highLowerBound="70"/>
    </logging>

Now logging logs for different testsuites into different folders. 
Another option would be to have something like
<cfg name="foo" value="bar"/>
and reference it somehow like $cfg.foo or so, this would limit the scope to the phpunit.xml and wouldn't change how code is executed (with which env variables).

**Comment by dnaber-de** [comment]
Your use case implies that these declarations are evaluated per test suite. Even though this feature looks like a good idea to me, the current test runner only allows to do these declarations once for all suites. So the earliest point to implement this is when the test runner is fundamentally refactored. But right now there's no timeline for this.
