### ISSUE TITLE
Typo about PHP 7.0 on 6.x release notes

### ISSUE THREAD

**Issue by dharkness** [sebastianbergmann/phpunit#2841]
I'm upgrading our testing framework which augments PHPUnit a bit, and I noticed this on the 6.1 release notes:

> PHPUnit 7.0, which is scheduled for February 2, 2018, will no longer support PHP 7.0.

Actually, the same line is on all 6.x release note pages.

**Comment by sebastianbergmann** [comment]
PHPUnit 7 will no longer support PHP 7.0. There is nothing wrong here.

**Comment by dharkness** [comment]
Okay, it just seemed strange since I'm upgrading to PHPUnit 6 to get PHP 7 support.

**Comment by VolCh** [comment]
PHP 7 = PHP 7.0 + 7.1 + 7.2 + ... PHPUnit 6 supports >= 7.0, PHPUnit 7 supports >= 7.1
