### ISSUE TITLE
[Question] PHPUnit executes it self

### ISSUE THREAD

**Issue by edsamonte** [sebastianbergmann/phpunit#2843]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.4.3
| PHP version         | 7.1.8
| Installation Method | composer

I freshly installed a phpunit on a Laravel project and I can't help but notice that the version ID was printed twice.
```
PHPUnit 6.4.3 by Sebastian Bergmann and contributors.

PHPUnit 6.4.3 by Sebastian Bergmann and contributors.

.....                                                               5 / 5 (100%)

Time: 580 ms, Memory: 22.00MB

OK (5 tests, 9 assertions)
```
I tried to debug it and added `getmypid()` and `posix_getppid()`, and it seems that the second time it was shown, the parent pid was the first execution process.

```
[pid:5963,ppid:1086] PHPUnit 6.4.3 by Sebastian Bergmann and contributors.

[pid:5965,ppid:5963] PHPUnit 6.4.3 by Sebastian Bergmann and contributors.

.....                                                               5 / 5 (100%)

Time: 585 ms, Memory: 22.00MB

OK (5 tests, 9 assertions)
```

Anything that might be causing it?

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.
