### ISSUE TITLE
Feature Request: @requires setting [php-setting] [value]

### ISSUE THREAD

**Issue by TendoAki** [sebastianbergmann/phpunit#2846]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 4.8.35
| PHP version         | 7.1.x
| Installation Method | Composer (Drupal 8's default)

I am currently working on a patch to Drupal 8 core that removes usage of assert_options() with the goal of getting Drupal's usage of php's assert() statement to match PHP 7 standards. Part of this rewrite deals with how assert is handled in PHPUnit.

Drupal runs unit tests against assert calls a developer might cause to fail through erroneous module code. Once the module is stable these tests incur a performance loss so turning them off is desirable. It should be noted that if the code is bad and assertions are turned off the code will still fail, just in a far more cryptic and hard to understand manner.  We test some of these assertions, particularly ones wihin code that have been giving developers difficulty.

The problem is that, subsequent to the removal of assert_options(), we have no way at runtime to turn assertions on.  Tests checking assertions should be skipped if they are turned off. This can be done, but it's sloppy:

```
if (ini_get('zend.assertions') > 0) {
 //test body
}
else {
  $this->markTestSkipped('Assertions off, skipping');
}
```

For the moment this will work - there's only around a dozen tests like this. But it would be nice to avoid the problem. I propose the following: PHPUnit already has a @requires annotation to check PHP versions, PHPUnit versions, installed extensions and so on.  I propose adding the format given in the title

@requires setting [php-setting] [value]

Our particular use case is

@requires setting zend.assertions 1

But this proposal is more flexible than our narrow use case should it be adopted.

**Comment by andypost** [comment]
Sadly this feature is missing in documentation https://docs.phpunit.de/en/10.2/annotations.html#requires
