### ISSUE TITLE
Question about compatibility for PHPUnit 6.4 with PHP 5.4

### ISSUE THREAD

**Issue by henrigolant** [sebastianbergmann/phpunit#2852]
Hello,

I just want to know if it possible to install PHPUnit 6.4 the latest version with my envronment in PHP 5.4.

Thank's 

Henri.

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry. That being said: no, PHPUnit 6 is not supported on PHP 5. The oldest version supported on PHP 5.4 is PHPUnit 4.8.
