### ISSUE TITLE
PHPUnit exits with code 139 in PHP 7.2.0 RC6

### ISSUE THREAD

**Issue by FinesseRus** [sebastianbergmann/phpunit#2853]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.4.4
| PHP version         | 7.2.0RC6
| Installation Method | Composer

I use this command to launch testing with PHPUnit:

```bash
./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml
```

It works fine in PHP 7.2.0RC5. PHP 7.2.0RC6 was released yesterday and the same command started failing:

```
The command "./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml" exited with 139.
```

You can see an example of the command execution here: https://travis-ci.org/FinesseRus/QueryScribe/jobs/299440823#L525. A few days ago that job was performed successfully.

**Comment by sebastianbergmann** [comment]
You have found a problem in the PHP runtime that leads to a [segmentation fault](https://en.wikipedia.org/wiki/Segmentation_fault). An issue like this has to be reported at https://bugs.php.net/report.php using a minimal, self-contained, reproducing test case.

Please note that a test case that needs to be run through PHPUnit does not qualify as either "minimal" or "self-contained" when reporting bugs for the PHP runtime. Best practices for reporting bugs in PHP are documented [here](https://bugs.php.net/how-to-report.php).

In the case that the segmentation fault happens during continuous integration on [TravisCI](http://travis-ci.org/) then you can [troubleshoot the problem locally using Docker](https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image).

**Comment by FinesseRus** [comment]
As you can see in [the log](https://travis-ci.org/FinesseRus/QueryScribe/jobs/299440823) everything works (e.g. Composer) except PHPUnit. Do you suggest me to locate a code that causes the error in PHPUnit?

**Comment by GrahamCampbell** [comment]
> You have found a problem in the PHP runtime that leads to a segmentation fault. An issue like this has to be reported at https://bugs.php.net/report.php using a minimal, self-contained, reproducing test case.

**Comment by remicollet** [comment]
Notice that I cannot reproduce using a recent snapshot of XDebug 2.6.0-dev

**Comment by Bilge** [comment]
@remicollet Are you suggesting this is an Xdebug issue?

**Comment by Bilge** [comment]
@remicollet [According to @banzaiman](https://github.com/travis-ci/travis-ci/issues/8746#issuecomment-344127856) (Travis staff), Travis is [already building](https://github.com/php-build/php-build/blob/af73e8d359101d89d8b0cae02b93d050f54e5557/share/php-build/definitions/7.2.0RC6#L2) the latest [dev-master for Xdebug](https://travis-ci.org/travis-ci/php-src-builder/jobs/300761864#L729).

**Comment by Bilge** [comment]
@remicollet You were correct, Travis rebuilt with the latest Xdebug master and everything is fine now.

**Comment by FinesseRus** [comment]
I confirm, it is fixed. My tests work on Travis-CI.

**Comment by Stanislav2014** [comment]
Hi! I have trooble.
Run this  "make test
composer run-script phpunit tests
> phpunit 'tests'
PHPUnit 7.5.2 by Sebastian Bergmann and contributors.

..Segmentation fault (core dumped)
Script phpunit handling the phpunit event returned with error code 139
Makefile:8: recipe for target 'test' failed
make: *** [test] Error 139"

**Comment by marianoedu22** [comment]
Hi, i have the same problem
with php 8.0.1

phpunit --coverage-clover phpunit.coverage.xml

PHPUnit 9.5.0 by Sebastian Bergmann and contributors.
Segmentation fault
Script phpunit --coverage-clover phpunit.coverage.xml handling the phpunit-xml event returned with error code 139

**Comment by Bilge** [comment]
Did you really need to necrobump this closed issue? Christ, dude.

**Comment by matthewjumpsoffbuildings** [comment]
@Bilge its clearly not resolved, not sure what the reason for your attitude is.

I am seeing the same issue running PHPUnit 10.5.16 using PHP 8.3.4 on Linux and PHP 8.3.0 on macOS

There is an open issue here https://github.com/php/php-src/issues/12373 which is a possible explanation
