### ISSUE TITLE
PHPUnit appears to segfault on PHP 7.2-RC6

### ISSUE THREAD

**Issue by Bilge** [sebastianbergmann/phpunit#2857]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 5.7.23
| PHP version         | PHP 7.2.0RC6 (cli) (built: Nov 11 2017 23:51:54) ( ZTS )
| Installation Method | Composer

PHPUnit versions 4, 5 and 6 all segfault on PHP 7.2-RC6 despite being fine on RC5, according to builds performed by several users on several different projects on Travis.

* [Example 1](https://travis-ci.org/ScriptFUSION/Mapper/jobs/301010491) (PHPUnit 4)
* [Example 2](https://travis-ci.org/Porter-connectors/FileConnector/jobs/301409829) (PHPUnit 5)
* [Example 3](https://travis-ci.org/Provider/Steam/jobs/301020920) (PHPUnit 6)

I don't know if this error lies with Travis, PHPUnit or PHP, but Travis claim it's [not their fault](https://github.com/travis-ci/travis-ci/issues/8748#issuecomment-344026121).

**Comment by GrahamCampbell** [comment]
Duplicate of https://github.com/sebastianbergmann/phpunit/issues/2853. (NB i am not saying this issue should be closed, just noting that it follows on from that other issue)

**Comment by Bilge** [comment]
[I've worked with Travis to successfully resolve this issue](https://github.com/travis-ci/travis-ci/issues/8748#issuecomment-344139329).
