### ISSUE TITLE
phpunit failed periodically with mkdir(): File exists error

### ISSUE THREAD

**Issue by dubrsl** [sebastianbergmann/phpunit#2864]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 5.7.x
| PHP version         | 7.1.x
| Installation Method | Composer

Builds periodically fail with an error
```
18:49:51 PHPUnit 5.7.21 by Sebastian Bergmann and contributors.
18:49:51 
18:49:51 mkdir(): File exists
```
https://github.com/sebastianbergmann/phpunit/blob/5.7/src/Util/Printer.php#L55
This issue is difficult to reproduce, as any of concurrency-related issues. It appears when several processes are attempting to create a directory which is not yet existing, but between is_dir() and mkdir() calls another process already managed to create a directory.
 incorrect: 
if (! @mkdir($directory, 0777, true)) {
 correct: 
if (! @mkdir($directory, 0777, true) && ! is_dir($directory)) {

**Comment by sebastianbergmann** [comment]
Please send a pull request.

**Comment by sebastianbergmann** [comment]
No feedback, closing.
