### ISSUE TITLE
Check assertEquals for different string

### ISSUE THREAD

**Issue by alexpts** [sebastianbergmann/phpunit#2865]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.4.3
| PHP version         | 7.1.11
| Installation Method | Composer / PHAR

$this->assertEquals('+9273721345', '9273721345'); // true
I expect false

**Comment by sebastianbergmann** [comment]
`assertEquals()` uses the `==` operator:
```
$ php -a
Interactive shell

php > var_dump('+9273721345' == '9273721345');
php shell code:1:
bool(true)

php > var_dump('+9273721345' === '9273721345');
php shell code:1:
bool(false)
```
As you can see, for the `==` operator the two string are equal.

If you need the `===` operator's behaviour then you need to use `assertSame()`.
