### ISSUE TITLE
@requires extension sqlite3 detects as sqlite version 3

### ISSUE THREAD

**Issue by zlikavac32** [sebastianbergmann/phpunit#2869]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.4.4
| PHP version         | 7.1.11
| Installation Method | Composer

When using `@expects extension` annotation with the `sqlite3` extension, the check is performed againt `sqlite` extension, version `3`. 

```
Extension sqlite >= 3 is required.
```

Is this the expected behaviour?

**Comment by sebastianbergmann** [comment]
I will not add a special case for an extension that has a number as the last character of its name, sorry.
