### ISSUE TITLE
Performance issue when excluding sub-directories of a whitelisted folder

### ISSUE THREAD

**Issue by j-d** [sebastianbergmann/phpunit#2870]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.4.4
| PHP version         | 7.1.11
| Installation Method | Composer

This performance issue is relevant to code coverage. 

The current strategy is to include all the whitelisted directories first: 
https://github.com/sebastianbergmann/phpunit/blob/6.4.4/src/TextUI/TestRunner.php#L479 and then remove the ones that have been excluded (Line 491). When including or excluding directories, It does so by recursively finding all the files in those directories.

This is not ideal, because if you are removing a sub-directory of an included directory, those excluded files will be scanned twice, once to be included and again to be excluded. 

There many projects where this happens, for example, the structure of all Symfony components is that there is no `src/` folder, the files are in the project root `./` and the `vendor`, `Resources` and `Test` files are in sub-directories inside. E.g. (From https://github.com/symfony/form/blob/v3.3.13/phpunit.xml.dist)

```xml
    <filter>
        <whitelist>
            <directory>./</directory>
            <exclude>
                <directory>./Resources</directory>
                <directory>./Tests</directory>
                <directory>./vendor</directory>
            </exclude>
        </whitelist>
    </filter>
```

This causes a serious performance hit when calculating code coverage. On some projects the `vendor` folder could get very large and it is being scanned twice, when there is no real need.

I believe that the right strategy should be to figure out the excluded directories first, and pass that information to the `addDirectoryToWhitelist` method. This method, makes use of `getFilesAsArray`, that is already prepared to take a fourth optional argument, with the directories that should be excluded. 

Thank you very much in advance.

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/.github/CONTRIBUTING.md#reporting-issues) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project.

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another.
