### ISSUE TITLE
getFlashBag() causes Fatal error: Maximum function nesting level of '256' reached

### ISSUE THREAD

**Issue by engharb** [sebastianbergmann/phpunit#2872]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 5
| PHP version         | 7
| Installation Method | Composer

When I start phpUnit test, I get the following error 'Fatal error: Maximum function nesting level of '256' reached'.

I have checked my code and I found that using Symfony/Session:
`$session = new \Symfony\Component\HttpFoundation\Session\Session(); `
`$surfbar_warning = $session->getFlashBag()->get('tmp_name');`
is causing such problem.

Do you have any suggestion how to deal or work around such scenario?.

Regards,

**Comment by sebastianbergmann** [comment]
This is not a place to ask questions specific to Symfony, sorry.
