### ISSUE TITLE
PHPUnit test not executing

### ISSUE THREAD

**Issue by danielMensah** [sebastianbergmann/phpunit#2873]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.4
| PHP version         | >=5.3.0
| Installation Method | Composer

I am trying to execute some test in PHPUnits but it's not getting executed.

    <?php
    require_once __DIR__ . "/../../Controllers/UserController.php";

    class UserControllerTest extends \PHPUnit\Framework\TestCase {
        private $controller;

        protected function setUp() {
             $this->controller = new UserController();
        }

        public function testThatCanGeneratePromoCode() {
            $promoCode = $this->controller->generatePromoCode();
            $this->assertEquals(20, strlen($promoCode));
        }
    }

However, if I extend the class with `\PHPUnit_Framework_TestCase` it gets executed. Why is that?

This is my `phpunit.xml`:

    <?xml version="1.0" encoding="UTF-8" ?>
    <phpunit bootstrap="vendor/autoload.php"
             colors="true"
             verbose="true"
             stopOnFailure="false">
        <testsuites>
            <testsuite name="Test suite">
                <directory>tests</directory>
            </testsuite>
        </testsuites>
    </phpunit>

Additionally, using `PHPUnit_Framework_TestCase` doesn't allow me to use `$this->getMockBuilder('UserModel')` causing an error:
`Fatal error: Uncaught TypeError: Argument 1 passed to PHPUnit_Framework_MockObject_MockBuilder::__construct() must be an instance of PHPUnit\Framework\TestCase`

**Comment by sebastianbergmann** [comment]
`>=5.3.0` is not a concrete PHP version number (and PHPUnit 6 is not supported on PHP 5). You are also not showing the complete output of PHPUnit.

That being said, it appears that you have different installations of PHPUnit mixed up.

For instance, you may have used Composer to install PHPUnit and have configured the autoloader generated by Composer as PHPUnit's bootstrap script but then you invoke PHPUnit using an executable other than `vendor/bin/phpunit`.
