### ISSUE TITLE
--textdox command not outputting when using dataproviders

### ISSUE THREAD

**Issue by fabulousduck** [sebastianbergmann/phpunit#2874]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.4.4
| PHP version         | 7.0.22
| Installation Method | PHAR

When running the following command `phpunit --testdox`, the output remains blank as the following output shows.
```bash
$ phpunit --testdox
PHPUnit 6.4.4 by Sebastian Bergmann and contributors.


```

However, when simply running the `phpunit` command from my terminal i get the following response:

```bash
$ phpunit
PHPUnit 6.4.4 by Sebastian Bergmann and contributors.

WW                                                                  2 / 2 (100%)

Time: 96 ms, Memory: 10.00MB

There were 2 warnings:

1) Warning
The data provider specified for Tests\Unit\FindTest::testIfRegexCanParseCorrectCalls is invalid.
Class 'App' not found

2) Warning
The data provider specified for Tests\Unit\FindTest::testIfRegexDoesNotParseIncorrectCalls is invalid.
Class 'App' not found

WARNINGS!
Tests: 2, Assertions: 0, Warnings: 2.
```

This tells me that the tests are indeed being ran, but simply not showing any output using the `--testdox` option.

The following code is one of the 2 tests in question:

```php
    /**
     * @dataProvider  functionNameProvider
     */
    public function testIfRegexCanParseCorrectCalls($functionNames)
    {
        $manager = \App::make(\Atabase\Localization\Manager::class);
        $this->assertTrue($this->patternCanMatchFunctionCall($manager, $functionName));
    }
```

I am wondering if this is intentional or actually a bug as there is no documentation talking about the `--testdox` flag not being triggered in the event a test is ran using a dataProvider.

I did however find #1098 talking about this but it was closed. Did this ever get fixed ?

Regards, Duck

**Comment by sebastianbergmann** [comment]
Unfortunately, there is nothing we can do about this.

**Comment by fabulousduck** [comment]
Is there any other method of getting any kind of logging like `--testdox` out of phpunit or am i better off switching to a different unit testing framework entirely if i want such features ?
