### ISSUE TITLE
Default Testsuite in XML, redux

### ISSUE THREAD

**Issue by mikeschinkel** [sebastianbergmann/phpunit#2876]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.4.4
| PHP version         | 7.0.17
| Installation Method | Composer 

I would like to add back the request for a _"[_Default Testsuite in XML_](https://github.com/sebastianbergmann/phpunit/issues/1844#issue-104252807)"_ as [originally requested](/sebastianbergmann/phpunit/issues/1844#issue-104252807) by @AydinHassan on 2015-09-01 but [closed because of the 5.0 release](/sebastianbergmann/phpunit/issues/1844#issuecomment-144911188).  I am copying his original request here:

> _"I was looking for a way to specify a default test suite in the configuration XML, but it doesn't seem it's possible. Would this be an acceptable feature?"_
> _"For example, if I have multiple test suites but when a user runs `vendor/bin/phpunit` I only want it to execute the default test suite."_
> _"Running the other test suites would require specifically running `vendor/bin/phpunit --testsuite some-slow-test-suite`"_ 

Basically I would like to set up a specific ordering of tests to be run whenever someone runs tests without them trying, failing, and wasting time and then finally discovering they have to specify a test suite in order to have the tests run correctly, or worse having them give up on testing because they think my tests are broken. I can do that with a test suite but I can't identify a way to ensure someone running the tests will not default to just trying to run everything.

_(The reason I want to order them is I want to test the abstract classes first, then the other parent classes and finally the non-parent child classes. The very nature of what I am working on requires inheritance vs. containment/aggregation so arguing for the latter won't work in my specific use-case. Basically I need dependencies between classes vs. [dependencies between methods](https://phpunit.de/manual/current/en/writing-tests-for-phpunit.html#writing-tests-for-phpunit.test-dependencies) where my justifications for dependencies are similar to what was written for methods.)_

**Comment by eclipxe13** [comment]
The default test suite has been implemented since version 6.1 https://github.com/sebastianbergmann/phpunit/pull/2533

What you are asking is a different feature to create *dependencies between test cases*.
IMHO that wont be introduced into PHPUnit since test cases should run independently one from each other.

Have you check `@group` annotations? They can be added to classes, not only methods.

**Comment by epdenouden** [comment]
Enforcing dependencies between suites is not trivial as reordering TestSuites is conceptually different from reordering tests. The list of test per suite/testcase is a flat list that can be ordered locally and everything works fine. TestSuites on the other hand can contain TestSuites which requires a more complex dependency resolver.

Have a look at #3092 and #3147 for recent work on reordering and dependencies.

**Comment by mikeschinkel** [comment]
@eclipxe13 Thanks for the comment.

I searched for default test case and did not find #2533; I think that is exactly what I was looking for.

That said, I am curious why you thought I was asking for What you are asking dependencies between test cases as I do not believe that is what I was asking for, although I could be misunderstanding.
