### ISSUE TITLE
AppVeyor configuration out of date

### ISSUE THREAD

**Issue by bscheshirwork** [sebastianbergmann/phpunit#2880]
this is issue about CI environment 

[This version of PHPUnit is supported on PHP 7.1 and PHP 7.2](https://ci.appveyor.com/project/sebastianbergmann/phpunit/build/413.master-ldvsyeia/job/1v66podqxcagu48a)

```sh
php phpunit
This version of PHPUnit is supported on PHP 7.1 and PHP 7.2.
You are using PHP 7.0.16 (c:\php\7.0.16\php.exe).
Command exited with code 1
```

I can see fresh changes of version `php` in latest commits...

**Comment by sebastianbergmann** [comment]
@helhum @IchHabRecht Can you please update `appveyor.yml` on the `6.4`, `6.5`, and `master` branches?

PHPUnit 6.4 and PHPUnit 6.5 need to be tested with PHP 7.0 and PHP 7.1. PHPUnit 7 needs to be tested with PHP 7.1 and PHP 7.2.

Thanks!

**Comment by sebastianbergmann** [comment]
Thank you, @IchHabRecht!
