### ISSUE TITLE
How to proposal new assert methods

### ISSUE THREAD

**Issue by gabriel-caruso** [sebastianbergmann/phpunit#2881]
Hello there :wave: 

If I want to propose new `assert` methods, what should I do, and in what `branch/version` of `PHPUnit`? Also, should I document it? Etc.

**Comment by gregurco** [comment]
@gabriel-caruso probably it's better to read this doc for the beginning: https://github.com/sebastianbergmann/phpunit/blob/master/.github/CONTRIBUTING.md

**Comment by sebastianbergmann** [comment]
I am reluctant to add more assertions to PHPUnit itself.

Have a look at https://github.com/ThomasWeinert/phpunit-xpath-assertions, for instance, to get an idea for how to develop and distribute assertions as a separate package.
