### ISSUE TITLE
enhancement: allow to specify test listeners on command line

### ISSUE THREAD

**Issue by SimonHeimberg** [sebastianbergmann/phpunit#2882]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.4.4
| PHP version         | 7.0.19
| Installation Method | Composer

Supporting `phpunit --listener 'Name\Of\My\Listener'` would be handy to only temporary generate test reports (without modifying an xml file).

When only specifying the class name is allowed, this is limiting, of course. Maybe something like this is better: `phpunit --listener 'class=Name\Of\My\Listener,file=path/to/listener.php'`, but `--coverage-html` and `--log-junit` are also limited compared to the functionality in the <logs> section of phpunit.xml(.dist)

**Comment by sebastianbergmann** [comment]
PHPUnit has too many CLI options already, sorry.
