### ISSUE TITLE
6.4 -> 6.5 replacing PHPUnit_Framework_MockObject_Matcher_Invocation with PHPUnit\Framework\MockObject\Matcher\Invocation considered BC breaking

### ISSUE THREAD

**Issue by malkusch** [sebastianbergmann/phpunit#2893]
Hi
I have a [phpunit extension](https://github.com/php-mock/php-mock-phpunit) which implements `PHPUnit_Framework_MockObject_MockObject`. The recent update from 6.4. to 6.5 [breaks my extension](https://github.com/php-mock/php-mock-phpunit/issues/21) as said interface was renamed. Would you consider reverting that change for PHPUnit-6?

**Comment by kubawerlos** [comment]
PHPUnit 6.4 goes phpunit/phpunit-mock-object v4 series and 6.5 with v5 - is changing then interface to PSR-4 [name](https://github.com/sebastianbergmann/phpunit-mock-objects/blob/master/src/Matcher/Invocation.php#L20) could be a solution for you?

**Comment by malkusch** [comment]
I could change my library as well. But I feel I have to support phpunit-6.[0-4] for my users. My situation is that I depent on ^phpunit-6. So if you won't revert that I will have to make two releases, one patch to add the constraint to <phpunit-6.5 and one (patch/minor/major?) with the >=phpunit-6.5 constraint plus said change. Sounds complicated? That's why I'm here at upstream.

**Comment by GrahamCampbell** [comment]
I think the problem really is that your extension forgot to depend on phpunit mock objects v4?

**Comment by malkusch** [comment]
@GrahamCampbell Hmm that's an interesting aspect. That would definetly have prevented that issue. But then I do constraint more than I like. I effectively depend on \PHPUnit\Framework\TestCase::getMockBuilder() which changed its signature. So I would love to depend only on phpunit and rely on semantic versioning.

**Comment by kubawerlos** [comment]
You can also create a backward compatibility file like this:

```php
if (!interface_exists('\PHPUnit_Framework_MockObject_MockObject') {
    interface \PHPUnit_Framework_MockObject_MockObject extends \PHPUnit\Framework\MockObject\MockObject {}
}
```

**Comment by malkusch** [comment]
@kubawerlos Thank you for that suggestion. I know I can work around that on my side, but let me ask two questions:
- Does phpunit consider TestCase::getMockBuilder() part of its public API?
- Does phpunit follow semver?

**Comment by GrahamCampbell** [comment]
> Does phpunit consider TestCase::getMockBuilder() part of its public API?

I think so. It is a public method, and neither the class or the method is annotated with `@internal`.

> Does phpunit follow semver?

Apparently, yes: https://github.com/sebastianbergmann/phpunit/wiki/Release-Process.

**Comment by GrahamCampbell** [comment]
> Does phpunit consider TestCase::getMockBuilder() part of its public API?

This is a compelling argument that this is definitely a breaking change the API, as far as I'm concerned.

**Comment by sebastianbergmann** [comment]
`PHPUnit_Framework_MockObject_MockObject` still exists for compatibility reasons.

**Comment by malkusch** [comment]
> PHPUnit_Framework_MockObject_MockObject still exists for compatibility reasons.

That's nice and that's what TestCase::getMockBuilder() returned in 6.4, not in 6.5. Ok I got your view on SemVer then.
