### ISSUE TITLE
PHP-function each() has been deprecated (PHPUnit 5)

### ISSUE THREAD

**Issue by alexgit2k** [sebastianbergmann/phpunit#2899]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 5.7.25
| PHP version         | 7.2.0
| Installation Method | Composer & PHAR

The PHP-function each() has been deprecated as of PHP 7.2.0 (https://wiki.php.net/rfc/deprecations_php_7_2#each), but is still used in PHPUnit 5.7:
```
src/Util/Getopt.php: while (list($i, $arg) = @each($args)) {
src/Util/Getopt.php: } elseif (list(, $opt_arg) = @each($args)) {
src/Util/Getopt.php: if (!strlen($opt_arg) && !(list(, $opt_arg) = @each($args))) {
```

For PHPUnit 6 each() has already been removed: https://github.com/sebastianbergmann/phpunit/commit/48930fc4782adf95037ee0ed5440b7366a048c9e

**Comment by sebastianbergmann** [comment]
PHPUnit 5.7 is not supported on PHP 7.2, see "Supported Versions" on https://phpunit.de/.

**Comment by Ibm-blockchain-glad** [comment]
I think this https://half-empty-urlsession.github.io/angular-directive/ could come in handy for you
