### ISSUE TITLE
@test annotation gets accepted no matter what

### ISSUE THREAD

**Issue by BackEndTea** [sebastianbergmann/phpunit#2902]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.5.1
| PHP version         | 7.1.12
| Installation Method | Composer 

A function is considered a test, as long as the doc block contains ```@test```, even if it is something like this:
```php
/**
 * @author me@testwebsite.com
 */
 public function itDoesSomething() {}
```

I propose to change this to only detect a function as a test if ```@test``` there is surrounded by whitespace. So the following examples should still be accepted as tests
```php
/**
 * @test
 *@test
 * @test Makes sure our code works
 */
```

But this would not
```php
/**
 * My email is Hello@testSite.com
 */
```

This breaks backwards compatibility, so, if implemented, has to wait for a major version up.

**Comment by sebastianbergmann** [comment]
https://github.com/sebastianbergmann/phpunit/blob/master/src/Framework/TestSuite.php#L911 needs to be changed.

**Comment by sebastianbergmann** [comment]
While we're at it, the (now) undocumented `@scenario` which was used by the unsupported `phpunit-story` extension should be removed.

**Comment by BackEndTea** [comment]
If i make a PR for this, should i send it to master?

**Comment by sebastianbergmann** [comment]
Yes, `master` is PHPUnit 7.0.
