### ISSUE TITLE
Missing schema for 6.5

### ISSUE THREAD

**Issue by ohartl** [sebastianbergmann/phpunit#2916]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.5
| PHP version         | doesn't matter
| Installation Method | doesn't matter

Disclaimer: I don't know where else to put this to reach @sebastianbergmann , so sorry if its in the wrong place.

Normally the xsd schema file was reachable from the schema.phpunit.de domain. The schema for 6.5 isn't, 404 at https://schema.phpunit.de/6.5/phpunit.xsd. Has anything changed?

**Comment by sebastianbergmann** [comment]
Fixed, thanks.
