### ISSUE TITLE
Missing ext-simplexml and ext-fileinfo

### ISSUE THREAD

**Issue by smcjones** [sebastianbergmann/phpunit#2918]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | any
| PHP version         | any
| Installation Method | any

Both assertions in this test fail:

    $this->assertTrue(function_exists('simplexml_load_file'));
    $this->assertTrue(function_exists('mime_content_type'));

When I add ext-simplexml and ext-fileinfo and re-compile, it succeeds.

Similarly, would be nice to have ext-mysqli installed but I can just add that in a custom build.

**Comment by sebastianbergmann** [comment]
PHPUnit does use the extensions in questions.

**Comment by smcjones** [comment]
Grr, definitely my bad. I meant to post this on Docker's phpunit adaptation. Sorry for wasting your time.
