### ISSUE TITLE
[Proposal] assertIsExecutable

### ISSUE THREAD

**Issue by carusogabriel** [sebastianbergmann/phpunit#2926]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.6.0

Following by `assertIsWritable` and `assertIsReadable`, should we have `assertIsExecutable`?

**Comment by sebastianbergmann** [comment]
I am reluctant to add new assertions to PHPUnit itself in general and in this particular case I do not think that the proposed assertion makes sense to add.
