### ISSUE TITLE
Incorrect library version outputted after `prefer-lowest` composer update

### ISSUE THREAD

**Issue by szymach** [sebastianbergmann/phpunit#2929]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 4.7+ (perhaps on lower versions as well, did not check)
| PHP version         | 5.4+
| Installation Method | Composer

Hello, 
This is a rather small issue, but I thought I would bring it up anyway. When installing `phpunit` with `composer update --prefer-lowest`, some random version of the library is being outputted. Example:

```json
"phpunit/phpunit": "^4.7|^6.5"
```
will output:
```bash
PHPUnit 1.0.1-57-g3fa6d09 by Sebastian Bergmann and contributors.
```
after calling `bin/phpunit`. Cheers.

**Comment by sebastianbergmann** [comment]
PHPUnit 4.8 is no longer supported. Please open a new ticket in case this still applies to a supported version of PHPUnit.
