### ISSUE TITLE
PHPUnit warnings hides tested code ones

### ISSUE THREAD

**Issue by remicollet** [sebastianbergmann/phpunit#2934]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 5.7.26
| PHP version         | 7.2.1RC1
| Installation Method | other

Discovered in Fedora QA **after update to 5.7.26** which fix some "each" call.

In 5.7.25 "each" calls raise a deprecation warning which is somehow hidden, so "each" calls in the tested code are not reported.

So 5.7.26 allow to catch more issues, nice.

But this seems to be an issue how a framework warning may hide same warning in the tested code.

Ex, first failure reported after update from  5.7.25 to 5.7.26 with `The each() function is deprecated. This message will be suppressed on further calls`, see
* https://apps.fedoraproject.org/koschei/package/php-horde-Horde-Mime?collection=f28
* https://apps.fedoraproject.org/koschei/package/php-horde-Horde-Text-Flowed?collection=f28
* https://apps.fedoraproject.org/koschei/package/php-horde-Horde-Text-Filter?collection=f28
etc

In the future, new deprecation may appear (PHP 7.3, ...) and will raise other issues.

**Comment by sebastianbergmann** [comment]
I am not sure this can be "fixed" and if so, how.

**Comment by sebastianbergmann** [comment]
Also note that PHPUnit 5.7 was only supported on PHP 5.6, PHP 7.0, and PHP 7.1.
