### ISSUE TITLE
Timeout despite php setup

### ISSUE THREAD

**Issue by eldy** [sebastianbergmann/phpunit#294]
On ubuntu 11.04, if you launch the code coverage on large project with the command

/usr/bin/phpunit -d memory_limit=-1 -d max_input_time=0 -d max_execution_time=0 --configuration ./phpunit/phpunittest.xml --coverage-html ./report phpunit/AllTests.php

or

php -d max_input_time=0 -d max_execution_time=0 /usr/bin/phpunit -d memory_limit=-1 -d max_input_time=0 -d max_execution_time=0 --configuration ./phpunit/phpunittest.xml --coverage-html ./report phpunit/AllTests.php

you should have PHP timeout set to infinite.
However, building code coverage html pages stop after 120 seconds. Is there something into phpunit code coverage building code that reset this timeout. This value of 120 is not the one defined on command line, nor in any PHP config file so is there somewhere you call an external pg with such timeout or you set max_execution_time ?

**Comment by rodrigorm** [comment]
You can use https://github.com/sebastianbergmann/phpcov to generate the reports from coverage-php file.
