### ISSUE TITLE
Error Parse:  parameter type ?bool 

### ISSUE THREAD

**Issue by randion** [sebastianbergmann/phpunit#2942]
https://github.com/sebastianbergmann/phpunit/blob/a19b93d75ab4901c03c8460fcab888cdb6339041/src/Framework/Assert/Functions.php#L190

Some lines (three or four) have parameter type   '?bool'
Run and ...
PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in /var/www/dwes/PhpUnit/pruebas/Functions.php on line 190

It's necessary change   '?boo'l  by  'bool'
or not parse.

**Comment by sebastianbergmann** [comment]
Which branch of PHPUnit do you use? Which version of PHP do you use?

Please note that `master` requires PHP 7.1 (or later).

**Comment by randion** [comment]
I download  PHP Unit branch master, run with  PHP 7.0

In (github) master/src/Framework/Assert/Functions.php

Lines   190, 221, 236 and 254

you can see the parameter type  '?bool'  -->  ERROR PARSE

It's ok if I change '?bool'  by   'bool'



thanks for your code


2017-12-27 6:34 GMT+01:00 Sebastian Bergmann <notifications@github.com>:
