### ISSUE TITLE
expectExceptionMessage assert that message startsWith instead of full match

### ISSUE THREAD

**Issue by FallDi** [sebastianbergmann/phpunit#2943]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.5.5
| PHP version         | 7.1.9
| Installation Method | Composer

Following test is successfully passed.

```
<?php declare(strict_types=1);

require_once '../vendor/autoload.php';

use PHPUnit\Framework\TestCase;

class ExceptionTest extends TestCase
{
    public function testExceptionMessage()
    {
        $this->expectExceptionMessage('First second');
        throw new Exception('First second third');
    }
}
````
Looks that `expectExceptionMessage` assert that message startsWith expected message instead of made full string comparison. I can't find this behaviour in documentation.

**Comment by winkbrace** [comment]
You're right, this is by design. The failed assertion message when a mismatch occurs is 

> Failed asserting that exception message 'First second third' contains 'First second fourth'.

I've made a [PR](https://github.com/sebastianbergmann/phpunit-documentation/pull/503) on the documentation to add a note about this.
