### ISSUE TITLE
Kind request to re-enable log json option

### ISSUE THREAD

**Issue by creativeworkx** [sebastianbergmann/phpunit#2948]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.5.5
| PHP version         | 7.0.8
| Installation Method | Composer

 If I want to run my tests via Netbeans, i get the following output:

```
PHPUnit 6.5.5 by Sebastian Bergmann and contributors.

unrecognized option --log-json
Done.

```
This option was removed in 6.0, see   #2499 . To my understanding , such API changes are perfectly fine and understandable in a new major version. So in fact, I can't argue here...

..however, Netbeans is being transitioned from Oracle to Apache and the release of Netbeans 9.x  seems to be a MAJOR effort. Still no release date has been published yet. See [Roadmap](https://netbeans.org/community/releases/roadmap.html) 

So, I **kindly** wanted to ask if it is possible to re-introduce the option **"--log-json"**.

If not appropriate for you, perfectly understanable :) But I just wanted to ask.

Thanks!

**Comment by sebastianbergmann** [comment]
Sorry, but no.

**Comment by webmasterlv** [comment]
I solved it by using custom .bat file (if you're on Windows):

```
@ECHO OFF
SETLOCAL enabledelayedexpansion
SET args=%*
SET args=%args:--log-json=%
php "%~dp0phpunit.phar" %args%
```
and must be saved as phpunit.bat in the same folder with phpunit.phar.
