### ISSUE TITLE
Increasing memory usage from 6.2 -> 6.5

### ISSUE THREAD

**Issue by Trainmaster** [sebastianbergmann/phpunit#2949]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.5.5
| PHP version         | 7.1.12
| Installation Method | Composer

After updating from `6.2.4` to `6.5.5` I observed a slight increase in memory usage:
```
6.2.4 - 214.00MB
6.4.4 - 216.00MB
6.5.5 - 244.00MB
```
Unfortunately it's an internal project and therefore I can't provide any code examples. But I did some tests with `laravel/framework` (running `./vendor/bin/phpunit` in root dir) and got similar results:
```
6.2.4: 112.00MB
6.4.4: 114.00MB
6.5.5: 122.00MB
```

Can anybody confirm this? And if so, is this intended behavior?

**Comment by sebastianbergmann** [comment]
Increased resource consumption is never intentional. I will not invest time, however, to profile PHPUnit's memory consumption to figure out where and how now more memory is consumed in an effort to reduce this.
