### ISSUE TITLE
Class extending PHPUnit\Framework\TestSuite does not extend PHPUnit\FrameworkTestCase

### ISSUE THREAD

**Issue by giorgiosironi** [sebastianbergmann/phpunit#2950]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.5.5
| PHP version         | 7.0.26
| Installation Method | Composer

```
PHP Fatal error:  Uncaught PHPUnit\Framework\Exception: Class "PHPUnit_Extensions_SeleniumBrowserSuite" does not extend PHPUnit\Framework\TestCase.
/home/travis/build/giorgiosironi/phpunit-selenium/vendor/phpunit/phpunit/src/Framework/TestSuite.php:159
/home/travis/build/giorgiosironi/phpunit-selenium/vendor/phpunit/phpunit/src/Framework/TestSuite.php:290
/home/travis/build/giorgiosironi/phpunit-selenium/vendor/phpunit/phpunit/src/Framework/TestSuite.php:377
/home/travis/build/giorgiosironi/phpunit-selenium/vendor/phpunit/phpunit/src/Framework/TestSuite.php:403
/home/travis/build/giorgiosironi/phpunit-selenium/vendor/phpunit/phpunit/src/Runner/BaseTestRunner.php:65
/home/travis/build/giorgiosironi/phpunit-selenium/vendor/phpunit/phpunit/src/TextUI/Command.php:169
/home/travis/build/giorgiosironi/phpunit-selenium/vendor/phpunit/phpunit/src/TextUI/Command.php:148
```

References:
- Build output at https://travis-ci.org/giorgiosironi/phpunit-selenium/jobs/324969702#L630
- Class that gives trouble https://github.com/giorgiosironi/phpunit-selenium/blob/master/PHPUnit/Extensions/SeleniumBrowserSuite.php

May be related to https://github.com/sebastianbergmann/phpunit/issues/2859 If it's not that, I can try to reduce the test case to something smaller and pastable here.

**Comment by sebastianbergmann** [comment]
* I do not understand what you are trying to report
* `PHPUnit\Framework\TestSuite` never extended `PHPUnit\Framework\TestSuite`
* Sooner or later, `PHPUnit\Framework\TestSuite` will be gone. Hopefully with PHPUnit 8

**Comment by giorgiosironi** [comment]
`PHPUnit_Extensions_SeleniumBrowserSuite` has been working as an extension of `PHPUnit_Framework_TestSuite` (now `PHPUnit\Framework\TestSuite`). It looks like it was able to run transparently as a `PHPUnit\Framework\TestCase` in [PHPUnit 6.3.0](https://travis-ci.org/giorgiosironi/phpunit-selenium/jobs/269158805#L449), but from [6.5.5](https://travis-ci.org/giorgiosironi/phpunit-selenium/jobs/324969702#L497) (or possibly earlier).

When the class is gone as part of a new major version, `phpunit-selenium` should rewrite its dynamic generation of test cases not to use this class.
