### ISSUE TITLE
Switch cases not being covered

### ISSUE THREAD

**Issue by injitools** [sebastianbergmann/phpunit#2953]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.5.5
| PHP version         | 7.2.0 windows
| Installation Method | PHAR

the problem is that lines with the switch case are not covered, the switch cases themselves are being executed.

![2018-01-06_22-13-01](https://user-images.githubusercontent.com/9765406/34646841-3498e908-f3a5-11e7-96a7-31ef1d066daa.png)

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/.github/CONTRIBUTING.md#reporting-issues) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project.

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another.

**Comment by sebastianbergmann** [comment]
This is probably an Xdebug issue, see https://github.com/xdebug/xdebug/pull/398.

CC @derickr

**Comment by derickr** [comment]
Looks like it. But that issue is already fixed in Xdebug's master branch.

**Comment by eghojansu** [comment]
I am using phpdbg and get this issue too.

PHPUnit 7.5.1
phpdbg 0.5.0 (built: Sep 13 2018 13:45:02)
PHP 7.2.10-0ubuntu0.18.04.1, Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.10-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies

**Comment by l0gicgate** [comment]
@eghojansu experiencing same issue, Xdebug has this fixed but phpdbg doesn't

**Comment by pablorsk** [comment]
any ideas for a possible solution with *phpdbg*?

**Comment by dmlogic** [comment]
I'm also getting this when using phpdbg / phpunit 8.4.3.

Workaround is to move the case statements onto one line (which fortunately is practical in this case).

Can we re-open this or should I post a new issue?

**Comment by pablorsk** [comment]
Hi @dmlogic, is a temprary solution. On my company we solve with `EnumClass`. More options and information here: https://stackoverflow.com/a/58766230/860878

Also, @sebastianbergmann post on [my question](https://stackoverflow.com/questions/58683190/phpunit-coverage-with-phpdbg-uncovered-case-lines-on-switch-statement) this: 

> Do yourself a favor and do not use PHPDBG for code coverage. Use PCOV oder Xdebug instead
