### ISSUE TITLE
Testclasses starting with "App" forcing PHPUnit to fail

### ISSUE THREAD

**Issue by D4rkMindz** [sebastianbergmann/phpunit#2957]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     |  6.5.5
| PHP version         | 7.1.1
| Installation Method | Composer

**TL;DR** A class named AppControllerTest forces all tests to fail, renamed to IAppControllerTest, it works perfectly. Have to be extended by [BaseControllerTest](https://github.com/TekkCraft/atomtime/blob/e61fea438afd8c9893a145144a4882fb663edad5/tests/Controller/BaseControllerTest.php) 

**Problem**
I always name my tests like MailServiceTest or UserControllerTest. My Controllertests are extended from a BaseControllerTest (setUp methods, helpers, etc) and this [BaseControllerTest](https://github.com/TekkCraft/atomtime/blob/e61fea438afd8c9893a145144a4882fb663edad5/tests/Controller/BaseControllerTest.php) is extended from a BaseTest wich is extended from TestCase (for further details, see [tekkcraft/atomtime Project](https://github.com/TekkCraft/atomtime/tree/e61fea438afd8c9893a145144a4882fb663edad5)). 

My goal was to create a AppControllerTest to test the AppController. I wrote the test (and it worked, proved afterwards) and executed the `ant phpunit`-command ([@see build.xml](https://github.com/TekkCraft/atomtime/blob/e61fea438afd8c9893a145144a4882fb663edad5/build.xml#L266)) with following result (even with --debug parameter):
```
C:\xampp\htdocs\atomtime>ant phpunit
Buildfile: C:\xampp\htdocs\atomtime\build.xml

phpunit:

BUILD FAILED
C:\xampp\htdocs\atomtime\build.xml:268: exec returned: 255

Total time: 0 seconds
```
J4F i changed the AppControllerTest-class to IAppControllerTest and it worked perfectly without any error. 
This error also occurs, if there is a class called AppTest or something like that. But it have to be extended by the [BaseControllerTest](https://github.com/TekkCraft/atomtime/blob/e61fea438afd8c9893a145144a4882fb663edad5/tests/Controller/BaseControllerTest.php).

**Comment by sebastianbergmann** [comment]
I cannot reproduce this:
```php
<?php
use PHPUnit\Framework\TestCase;

class AppControllerTest extends TestCase
{
    public function testOne()
    {
        $this->assertTrue(true);
    }
}
```
```
$ phpunit AppControllerTest     
PHPUnit 6.5.5 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 49 ms, Memory: 8.00MB

OK (1 test, 1 assertion)
```

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by D4rkMindz** [comment]
@sebastianbergmann the class have to be extended by my own [BaseControllerTest](https://github.com/TekkCraft/atomtime/blob/e61fea438afd8c9893a145144a4882fb663edad5/tests/Controller/BaseControllerTest.php). This is a very rare bug and there is no urge to fix this bug instantly.
Maybe it is a problem in the BaseControllerTest. 
P.S: thanks for the quick response.

**Comment by sebastianbergmann** [comment]
As I wrote earlier: please provide a minimal, self-contained, reproducing test case that shows the problem you are reporting.

**Comment by D4rkMindz** [comment]
Can not reproduce this failure with a **minimal**, **self-contained** test. Also recognized that i failed to mock a request object from a framework correctly. My bad, sorry for bothering you.
