### ISSUE TITLE
doesNotPerformAssertions shall report warning when assertion is executed

### ISSUE THREAD

**Issue by keradus** [sebastianbergmann/phpunit#2958]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.5.5, yet affects first version that introduced annotation
| PHP version         | 7.2.1, yet not related
| Installation Method | Composer / PHAR

```
    /**
     * @doesNotPerformAssertions
     */
    public function testFoo()
    {
        $this->assertTrue(true);
    }
```

This shall raise warning, as test was supposed to not perform assertion.

**Comment by sebastianbergmann** [comment]
Makes sense.

**Comment by keradus** [comment]
awesome.
It was introduced in 5.6, and actually I treat it as a bug, could I target 5.x with a fix ?

**Comment by sebastianbergmann** [comment]
I do not think that this is a bug.

The `@doesNotPerformAssertions` prevents a test without assertions etc. from being considered risky.

Now we are talking about an additional, optional check that marks a test as risky when `@doesNotPerformAssertions` is used but the test performs an assertion.

**Comment by keradus** [comment]
Very well, it's not documented so there is no spec what is shall do :D 
I will propose a PR for 6.x this weekend hopefully ;)

**Comment by localheinz** [comment]
@sebastianbergmann 

When you are saying

> Now we are talking about an additional, optional check that marks a test as risky when `@doesNotPerformAssertions` is used but the test performs an assertion.

do you mean this should be configurable?
