### ISSUE TITLE
JUnit output doesn't pass XSD validation

### ISSUE THREAD

**Issue by byatis** [sebastianbergmann/phpunit#2964]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.5.5
| PHP version         | 7.0.25
| Installation Method |  PHAR

After following steps provided here:
https://phpunit.de/getting-started-with-phpunit.html

If I run:
`./phpunit --bootstrap src/autoload.php --log-junit results.xml tests/EmailTest`

and then

`xmllint --noout --schema JUnit.xsd results.xml` 

```
results.xml:3: element testsuite: Schemas validity error : Element 'testsuite', attribute 'file': The attribute 'file' is not allowed.
results.xml:3: element testsuite: Schemas validity error : Element 'testsuite', attribute 'assertions': The attribute 'assertions' is not allowed.
results.xml:3: element testsuite: Schemas validity error : Element 'testsuite', attribute 'skipped': The attribute 'skipped' is not allowed.
results.xml:3: element testsuite: Schemas validity error : Element 'testsuite': The attribute 'package' is required but missing.
results.xml:3: element testsuite: Schemas validity error : Element 'testsuite': The attribute 'id' is required but missing.
results.xml:3: element testsuite: Schemas validity error : Element 'testsuite': The attribute 'timestamp' is required but missing.
results.xml:3: element testsuite: Schemas validity error : Element 'testsuite': The attribute 'hostname' is required but missing.
results.xml:4: element testcase: Schemas validity error : Element 'testcase': This element is not expected. Expected is ( properties ).
results.xml fails to validate
```

This means that for example "Publish test results" task in VSTS doesn't work with PHPUnit.

JUnit XSD is from:
https://raw.githubusercontent.com/windyroad/JUnit-Schema/master/JUnit.xsd

**Comment by sebastianbergmann** [comment]
IIRC, there are multiple XSDs for JUnit's XML format (which is not even JUnit's XML format but that of the Apache Ant task for JUnit). PHPUnit's JUnit XML logger was updated to confirm with http://llg.cubic.org/docs/junit/.

**Comment by byatis** [comment]
Thank you for your reply. I tested this a bit further and the problem seems to happen only with specific test sets.
For some reason running all unit tests for Magento Commerce 2.2 as in here:
http://devdocs.magento.com/guides/v2.0/test/unit/unit_test_execution_cli.html

will produce a file which can't be read by VSTS. Not yet found out what is wrong with this file though.

[TEST-UnitTests.xml.zip](https://github.com/sebastianbergmann/phpunit/files/1637996/TEST-UnitTests.xml.zip)

Here's what VSTS task says about the file:
2018-01-16T14:08:23.1082462Z Timestamp is not available for one or more testsuites. Total run duration is being calculated as the sum of time durations of detected testsuites
2018-01-16T14:08:23.1140134Z ##[warning]Invalid results file. Make sure the result format of the file '/opt/vsts/work/1/s/deploy/testresults/TEST-UnitTests.xml' matches 'JUnit' test results format.

Here's what xmllint says:
```
./../TEST-UnitTests.xml:3: element testsuite: Schemas validity error : Element 'testsuite', attribute 'assertions': The attribute 'assertions' is not allowed.
../../TEST-UnitTests.xml:3: element testsuite: Schemas validity error : Element 'testsuite', attribute 'skipped': The attribute 'skipped' is not allowed.
../../TEST-UnitTests.xml:3: element testsuite: Schemas validity error : Element 'testsuite': The attribute 'package' is required but missing.
../../TEST-UnitTests.xml:3: element testsuite: Schemas validity error : Element 'testsuite': The attribute 'id' is required but missing.
../../TEST-UnitTests.xml:3: element testsuite: Schemas validity error : Element 'testsuite': The attribute 'timestamp' is required but missing.
../../TEST-UnitTests.xml:3: element testsuite: Schemas validity error : Element 'testsuite': The attribute 'hostname' is required but missing.
../../TEST-UnitTests.xml:4: element testsuite: Schemas validity error : Element 'testsuite': This element is not expected. Expected is ( properties ).
../../TEST-UnitTests.xml fails to validate
```

**Comment by byatis** [comment]
Could the problem be that there is  child testsuites produced like this
```
<testsuites>
  <testsuite name="/var/www/html/vendor/magento/module-rss/Test/Unit" tests="14" assertions="65" errors="0" failures="0" skipped="0" time="0.070642">
    <testsuite name="Magento\Rss\Test\Unit\App\Action\Plugin\BackendAuthenticationTest" file="/var/www/html/vendor/magento/module-rss/Test/Unit/App/Action/Plugin/BackendAuthenticationTest.php" tests="1" assertions="6" errors="0" failures="0" skipped="0" time="0.026407">
      <testcase name="testAroundDispatch" class="Magento\Rss\Test\Unit\App\Action\Plugin\BackendAuthenticationTest" classname="Magento.Rss.Test.Unit.App.Action.Plugin.BackendAuthenticationTest" file="/var/www/html/vendor/magento/module-rss/Test/Unit/App/Action/Plugin/BackendAuthenticationTest.php" line="10" assertions="6" time="0.026407"/>
    </testsuite>
 </testsuite>
</testsuites>
```
Is this behaviour caused by PHPUnit or Magento's broken configuration of it? If I read the cubic XSD correctly,  testsuite shouldn't contain another testsuite.

**Comment by byatis** [comment]
Ok, this seems to be problem also with other build tools like TeamCity. Fortunately, there seems to be workaround available.

Here is an xslt script modified for xsltproc, to make output file compatible with JUnit:

```
<?xml version="1.0" encoding="UTF-8"?>
<!--

PHPUnit does not output valid junit files. This XSLT file transforms the
output it does have to be valid.

Found here on a jetbrains Teamcity issue (they added an exception to their
junit parser since PHPUnit shows no inclination to change):
https://youtrack.jetbrains.com/issue/TW-17249#comment=27-231993

-->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0"   xmlns:exsl="http://exslt.org/common"
                extension-element-prefixes="exsl">
<xsl:output method="xml"/>
<xsl:template match="/">
<xsl:for-each select="//testsuite[@file]">
    <xsl:variable name="filename" select="concat('JTEST-',@name,'.xml')" />
    <exsl:document href="{$filename}" method="xml">
        <xsl:copy-of select="." />
    </exsl:document>
</xsl:for-each>
</xsl:template>
</xsl:stylesheet>
```

Got it from here and modified a bit:
https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services/suggestions/17985361-include-support-for-phpunit-test-results-and-code

**Comment by sebastianbergmann** [comment]
Thanks to @jenschude for https://gist.github.com/jenschude/9619ba13a9e7743368ed07b21dad6179#gistcomment-2328139:
```java
import org.junit.Test;

import static org.assertj.core.api.Assertions.assertThat;


public class FooTest
{
    @Test
    public void one() {
        Foo foo = new Foo();

        assertThat(foo.bar(1, 2));
        assertThat(!foo.bar(1, 1));
    }
}
```
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="FooTest" tests="1" skipped="0" failures="0" errors="0" timestamp="2018-01-22T10:30:46" hostname="Jenss-MacBook-Pro-2.local" time="0.058">
  <properties/>
  <testcase name="one" classname="FooTest" time="0.058"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
```
Unfortunately, though, what I asked for in https://gist.github.com/sebastianbergmann/6d5e15e9e638c6a0650f003ff3fb8ad5 was not sufficient. We need the JUnit XML for a more extensive example.

**Comment by belanur** [comment]
In order to not introduce a breaking change, the existing JUnit XML output will not be changed.

However, we started working on a new log writer that outputs JUnit 5 XML which can be validated against https://github.com/junit-team/junit5/blob/master/platform-tests/src/test/resources/jenkins-junit.xsd - this should solve issues like the one described here.

In the long run it probably makes sense to introduce a PHPUnit XML log format together with an XSD, since some of PHPUnit 's features are not available in JUnit (e.g. warnings, incomplete and risky tests) and therefore not reflected in the JUnit XML and vice versa.

**Comment by sebastianbergmann** [comment]
Closing this in favour of #3162.

**Comment by nfalco79** [comment]
@belanur the XSD you are referring is not defined by JUnit5 it is only something copy for test purpose by jenkins xunit plugin.
