### ISSUE TITLE
Make PHPUnit\Framework\Assert a trait

### ISSUE THREAD

**Issue by TiMESPLiNTER** [sebastianbergmann/phpunit#2969]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | any
| PHP version         | any
| Installation Method | Composer / PHAR

It would be great if the class `PHPUnit\Framework\Assert` could be converted to a `trait` and then be used in the `PHPUnit\Framework\TestCase` class. That way one is way more flexible to write own traits with custom `assert...` methods which then can be used in a TestCase instead of extending `TestCase`s of `TestCase`s.

What do you think?

**Comment by sebastianbergmann** [comment]
Making `PHPUnit\Framework\Assert` a trait does not solve anything. Without a major rewrite, `PHPUnit\Framework\TestCase` must be extended by test case classes.
