### ISSUE TITLE
PhpUnit stops executing at random times

### ISSUE THREAD

**Issue by abbood** [sebastianbergmann/phpunit#2971]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 5.7.26
| PHP version         | 7.1.8
| Installation Method | Composer 

I have a large suite of PHPUnit tests. I've executed the tests many times, I've identified db [race conditions][1], so I simply annotated those with the a `RaceCondition` [group][2] and avoided testing them. 

However the other set of tests that fail fail randomly, and in this case the php unit simply _stops_ executing.. compare out output of these two **identical** commands:

    $ phpunit --exclude-group RaceCondition,Jams,MultiCity
    PHPUnit 5.7.26 by Sebastian Bergmann and contributors.
    
    ...............................................................  63 / 652 (  9%)
    ............................................................... 126 / 652 ( 19%)
    ............................................................... 189 / 652 ( 28%)
    ............................................................... 252 / 652 ( 38%)
    ............................................................... 315 / 652 ( 48%)
    ...............................^C
    $ phpunit --exclude-group RaceCondition,Jams,MultiCity
    PHPUnit 5.7.26 by Sebastian Bergmann and contributors.
    
    ...............................................................  63 / 652 (  9%)
    ............................................................... 126 / 652 ( 19%)
    ............................................................... 189 / 652 ( 28%)
    ............................................................... 252 / 652 ( 38%)
    ..........................................................

  [1]: https://stackoverflow.com/questions/48403252/how-to-avoid-race-conditions-with-php-unit-testing/48403384?noredirect=1#comment83825471_48403384
  [2]: https://phpunit.de/manual/current/en/appendixes.annotations.html#appendixes.annotations.group

so in both cases they simply stop executing. Initially I'd simply put the `@Jams` group on those tests that "jam".. however I later realized that these tests were jamming very randomly.. I couldn't find any pattern to avoid jamming. 

What can I do to further investigate this or prevent the jamming all together?

**Comment by abbood** [comment]
i realized that running this command (and without even avoiding the previously jammed methods).. it works much better!:

```
phpunit --exclude-group RaceCondition,MultiCity --process-isolation
```

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by sebastianbergmann** [comment]
No feedback, closing.
