### ISSUE TITLE
phpunit --log-junit generates invalid xml file when test output contains binary data

### ISSUE THREAD

**Issue by SimonHeimberg** [sebastianbergmann/phpunit#2974]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.5.5
| PHP version         | 7.0/7.1
| Installation Method | Composer

### Problem
running phpunit --log-junit `/some/file_junit.xml` generates an invalid xml file when a test produces output with binary data.

shortened example output:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="Project Test Suite" tests="552" assertions="548" errors="7" failures="3" skipped="208" time="156.086893">
    <testsuite name="AppBundle\Tests\Controller\PageLoadingTest" file="/home/me/src/proj/src/AppBundle/Tests/Controller/PageLoadingTest.php" tests="424" assertions="239" errors="6" failures="3" skipped="186" time="106.122545">
      <testsuite name="AppBundle\Tests\Controller\PageLoadingTest::testSimplePageLoading" tests="173" assertions="162" errors="3" failures="2" skipped="11" time="50.862405">
	    <testcase name="testSimplePageLoading with data set #91" class="AppBundle\Tests\Controller\PageLoadingTest" classname="AppBundle.Tests.Controller.PageLoadingTest" file="/home/me/src/proj/src/AppBundle/Tests/Controller/PageLoadingTest.php" line="26" assertions="1" time="0.325804">
          <system-out>PK</system-out>
        </testcase>
    </testsuite>
  </testsuite>
</testsuites>
```
The illegal characters are after `<system-out>PK`, this element reads as
`<system-out>PK\x03\x04\x14</system-out>` (\xNN is hex encoded).

As file do download: [illegal_xml_from_phpunit_junit.xml.txt](https://github.com/sebastianbergmann/phpunit/files/1668522/illegal_xml_from_phpunit_junit.xml.txt)

### Notes
about allowed characters in xml: https://stackoverflow.com/a/28152666/4124767

I do not know what replacements does the xml writer of php (hopefully & and > and similar).

Somewhere (on stackoverflow?) I found the following code to replace illegal characters. I do not yet an Idea if this helps.

```
$r = '∎';
$validContent = preg_replace('/[^\x{9}\x{A}\x{D}\x{20}-\x{D7FF}\x{E000}-\x{FFFD}]+/u', $r, $invalidContent);
```

**Comment by ryanaslett** [comment]
This is the code we've been using in drupalci to defend our xml against invalid chars:
`$validContent = preg_replace('/[^\x{0009}\x{000A}\x{000D}\x{0020}-\x{D7FF}\x{E000}-\x{FFFD}\x{10000}-\x{10FFFF}]/u', '�', $validContent);`

**Comment by sebastianbergmann** [comment]
A pull request would be appreciated.

**Comment by mkasberg** [comment]
I was able to reproduce it and found a simple fix for the problem.

This test case should help if you're trying to reproduce:

**BadJunitXMLTest.php**

```
<?php

use PHPUnit\Framework\TestCase;

class BadJUnitXMLTest extends TestCase {
    
    public function testBadXML() {
        print "Bad Chars: \u{03} \u{04} \u{14}";
        print "  Escaped: & < >";
        assertTrue(true);
    }

}
```

**Comment by ppazos** [comment]
PK is a Zip file header
