### ISSUE TITLE
enhancement: add xml config timeoutForUnmarkedTests 

### ISSUE THREAD

**Issue by SimonHeimberg** [sebastianbergmann/phpunit#2975]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.5.5
| PHP version         | 7.0/7.1
| Installation Method | Composer

By running phpunit with `--test-execution-timeout`, a timeout is set for tests marked with `@small`, `@medium` and `@large`. Tests without such an annotation do not get any timeout limit (doc is not up to date).
I suggest to introduce the xml attribute `timeoutForUnmarkedTests` to allow to set a timeout for such tests. It's default value is infinit, as the current behaviour is. (The xml attributes `timeoutForSmallTests`, `timeoutForMediumTests` and `timeoutForLargeTests` already exist.)

Doc about `--test-execution-timeout`: https://phpunit.de/manual/current/en/risky-tests.html#risky-tests.test-execution-timeout

**Comment by sebastianbergmann** [comment]
I think that only tests annotated with `@small`, `@medium` and `@large` should have a timeout that gets enforced.
