### ISSUE TITLE
Ability to log some messages and print on --debug

### ISSUE THREAD

**Issue by kenorb** [sebastianbergmann/phpunit#2988]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 5.3.5
| PHP version         | 7.1.7
| Installation Method | Composer

I would like to run my tests with `--debug`, however I don't see any [logging](http://phpunit.readthedocs.io/en/latest/logging.html) ability during the execution time. I would expect something like: `$this->logDebug('Some msg');`. Is this possible?

I'm aware of the workaround described in [here](https://stackoverflow.com/q/7493102/55075), but even `fwrite()` stopped working. But my goal is to log something into PHPUnit instance while in debug mode, so it can be printed later on.

**Comment by sebastianbergmann** [comment]
This is not possible. `--debug` only shows additional information such as which test is being executed.
