### ISSUE TITLE
Return types are undocumented breaking change

### ISSUE THREAD

**Issue by taylorotwell** [sebastianbergmann/phpunit#2989]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.0.0
| PHP version         | 7.2.0
| Installation Method | Composer

Just wanted to raise an issue that adding return type hints to various things like Constraints is a breaking change that is not noted in any change log. We have to add the type hints to our code or will get errors.

See this PR for reference: https://github.com/laravel/framework/pull/23005/files

**Comment by sebastianbergmann** [comment]
It's documented in https://phpunit.de/announcements/phpunit-7.html.
