### ISSUE TITLE
PHPUnit 7 conflicts with phpcov 4.0.5 because of sebastian/diff

### ISSUE THREAD

**Issue by acelaya** [sebastianbergmann/phpunit#2990]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.0.0
| PHP version         | 7.1.8
| Installation Method | Composer

I'm trying to update to phpunit 7 in my project, which also requires phpcov, but it throws an error because they both require the package `sebastian/diff` in different versions.

phpcov 4.0.5 requires version `^1.0 || ^2.0`, while phpunit 7.0.0 requires version `^3.0`.

**Comment by sebastianbergmann** [comment]
This should have been reported on the [phpcov](https://github.com/sebastianbergmann/phpcov) project.

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another.

**Comment by acelaya** [comment]
Ok, I'll reopen it there. Thanks.
