### ISSUE TITLE
phpunit7.0.0 test suffix not working that include the Non-Test.php files

### ISSUE THREAD

**Issue by baykier** [sebastianbergmann/phpunit#2992]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     |7.0.0
| PHP version         |7.2.0
| Installation Method | PHAR

my config file is like below:

```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/7.0/phpunit.xsd"
         bootstrap="vendor/autoload.php"
         forceCoversAnnotation="true"
         beStrictAboutCoversAnnotation="true"
         beStrictAboutOutputDuringTests="true"
         beStrictAboutTodoAnnotatedTests="true"
         verbose="true">
    <testsuite name="php-algorithms-test">
        <directory suffix="Test.php">tests</directory>
    </testsuite>
    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">src</directory>
        </whitelist>
    </filter>
</phpunit>
```

and my tests dir like below:

```
|-- tests
         |----- Sort
                 |------ AbstractSortTestCase.php
                 |------ InserttionSortTest.php
                 
```
while run phpunit command.outpu like this:
![phpunit](https://user-images.githubusercontent.com/12169649/35847227-a7c61cc2-0b54-11e8-8134-894ee84079dc.png)

as  expected! the __AbstractSortTestCase.php__  shoud not be included. does that right?

**Comment by sebastianbergmann** [comment]
I do not understand what you are trying to report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by baykier** [comment]
@sebastianbergmann  sorry, i just collecting some php alogrithms  and the repository is [demo](https://github.com/baykier/php-algorithmsl) !  as expected! the Abstract*-TestCase.php should not be inclued on test running ! because at the config fie, the file suffix  is *Test.php* ,i don't khnow that’s right or not? thanks for help!

**Comment by baykier** [comment]
sorry，i pasted a wrong demo repository link yesterday  and i updated it now ,thanks

**Comment by sebastianbergmann** [comment]
Your `AbstractSortTestCase` is not declared `abstract`.

**Comment by baykier** [comment]
yeah ! that’s worked ,thanks !
