### ISSUE TITLE
Permission denied 

### ISSUE THREAD

**Issue by hanwenbo** [sebastianbergmann/phpunit#2994]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.5.5
| PHP version         | 7.2.1
| Installation Method | Composer / PHAR
PHAR
mac
Warning: fopen(/tests/tmp/testdox.html): failed to open stream: Permission denied in phar:///usr/local/bin/phpunit/phpunit/Util/Printer.php on line 60
PHP Warning:  fopen(/tests/tmp/testdox.html): failed to open stream: Permission denied in phar:///usr/local/bin/phpunit/phpunit/Util/Printer.php on line 60
    <body>PHP Warning:  fopen(/tests/tmp/testdox.txt): failed to open stream: Permission denied in phar:///usr/local/bin/phpunit/phpunit/Util/Printer.php on line 60
PHP Warning:  fopen(/tests/tmp/logfile.xml): failed to open stream: Permission denied in phar:///usr/local/bin/phpunit/phpunit/Util/Printer.php on line 60

**Comment by sebastianbergmann** [comment]
The user executing PHPUnit does not seem to have permission to create the directory or file in question.

**Comment by hanwenbo** [comment]
thanks，Set sudo to execute.
