### ISSUE TITLE
PSR-4 support

### ISSUE THREAD

**Issue by dmifedorenko** [sebastianbergmann/phpunit#3001]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.0.0
| PHP version         | 7.2.2
| Installation Method | Composer

Hello. Composer version of phpunit use autoload classmap. This solution makes vendor/composer/autoload_classmap.php bigger. Big size of autoload_classmap.php slow down work of composer dumpautoload in Docker For Mac because it have issues with performance of file system.

The command below count 392 (!!!) files inside autoload_classmap.php:
cat vendor/composer/autoload_classmap.php | grep "/phpunit/" | wc -l 

Can you please replace autoload classmap inside composer.json to psr-4 support?

**Comment by sebastianbergmann** [comment]
No.

**Comment by dmifedorenko** [comment]
Bad day? Thank you any way.
