### ISSUE TITLE
FR: Ability to change method modifier from protected to public

### ISSUE THREAD

**Issue by speller** [sebastianbergmann/phpunit#3017]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.0.1

I want to test protected methods of a class without making them visible for class users. The only thing I need - is to change argument value in the `Generator::generateMockedMethodDefinition(... $modifier...)` from protected to public. Please add this feature. Or at least make the `Generator`'s methods and the `TestCase::getMockObjectGenerator` method protected to allow me to make my own addon.

**Comment by sebastianbergmann** [comment]
Solutions like https://github.com/sebastianbergmann/peek-and-poke exist, there is no need to add functionality for something that is 1) not required and 2) bad practice to PHPUnit.

**Comment by speller** [comment]
I don't need to just access them. I need to TEST them in the same way as public methods:

```
class A {
  public function B() {
    return $this->C() + $this->D();
  }
  protected function C() {
    return 5;
  }
  protected function D() {
    return 6;
  }
}

$testA = $this->createMock('A');
$testA
  ->expects($this->once())
  ->method('A')
  ->will($this->callOriginalMethod());
$testA
  ->expects($this->once())
  ->method('C')
  ->willReturn(1);
$testA
  ->expects($this->once())
  ->method('D')
  ->willReturn(1);

$this->assertEquals(
  2,
  $testA->a()
);
```

In this schematic example we can test particular parts of the internal logic separately, emulating return values of the protected methods. The `callOriginalMethod()` method ismy own implementation to call originals instead of mocked ones. In works great with the 4.x version for 3 years for me, but do not work with fresh versions because you've changed all the PHPUnit's methods and properties to private.

**Comment by speller** [comment]
@sebastianbergmann ?

**Comment by speller** [comment]
@sebastianbergmann ?

**Comment by sebastianbergmann** [comment]
I do not understand what you expect from me as you are mixing different topics in one issue.

I stopped reading your original ticket after "I want to test protected methods of a class without making them visible for class users". This makes no sense to me. Any non-public method is an implementation detail of a public method. Test that public method and you are fine. Testing non-public methods in isolation from the public method(s) that use(s) them is a bad idea.

Then you "complain" about the fact that I cleaned up some of PHPUnit's own code to follow the best practice of minimal visibility. I am sorry to say this, but I will not make a method that is -- and should be -- non-public public so that a problem that does not exist can be solved.

**Comment by speller** [comment]
@sebastianbergmann If a customer will decide to split its large complex method into submethods he will have to make submethods public just to be able to test them separately. And he will have to brake coding best practice of minimal visibility just because of testing framework. Why testing framework sets restrictions and brakes main code best practices?

Let's imagine following complex method:

```
class OrderProcessing
{
    public method createOrder($customer, $cartItems, $orderParameters)
    {
        $this->checkCustomerBalance($customer);
        $this->checkOrderItemsAvailability($customer, $cartItems);
        if ($orderParameters->isInstant()) {
            $order = $this->doCreateInstantOrder($customer, $cartItems, $orderParameters);
        } else {
            $order = $this->doCreateRegularOrder($customer, $cartItems, $orderParameters);
        }
        $this->updateCustomerBalance($customer, $order);
        $this->sendOrderCreatedNotifications($order);
    }
    ...
}

```

All the called methods in this code are protected. What if we need to test how the order creation notifications are sent without invoking the rest of the code? My technique allows to write just something like this:

```
function testSendNotifications()
{
    $this->allowProtectedMethod($mock, 'sendOrderCreatedNotifications');
    $this->notificationService
        ->expects(...)
        ->method(...)
        ->with(...)
        ->willReturn(...)

    $this->assertTrue(
        $this->service->sendOrderCreatedNotifications($order)
    );
}

```

Just imagine, how much testing code we will have to write currently. We will have to iterate over all the logic not related to the notifications until we will be able to test notifications itself. And when we will change something in the first method `checkCustomerBalance` we will have to change ALL of other tests not related to the `checkCustomerBalance` method. I think this is really bad practice and lead to massive amount of coding and changes in tests. As a valued developer I don't want to waste time for massive tests rewriting on each minor change. I want to change only a bit of tests and spend time on the main development.

We can not split this sample code into separate classes just for testing purposes. Testing framework shold not bring its own architecture rules into the project. We should not make these methods public to follow best coding pratices to minimize visibility. But we want to split the whole complex logic into submethods for more simplicity, more readability and easier testing. When a small submethod is changed we will have to change only the tests that really relate to this submethod. How you think, is it a bad practice or nonsense?

I'm asking for a minor changes in the PHPUnit that primarily about a possibility to change method modifiers from protected to public when creating a mock. It will allow PHPUnit to be more flexible. If you wish I can create a merge request with the changes.

**Comment by speller** [comment]
@sebastianbergmann ?

**Comment by speller** [comment]
@sebastianbergmann ?

**Comment by sebastianbergmann** [comment]
Please stop pinging me. I said all I am going to say in https://github.com/sebastianbergmann/phpunit/issues/3017#issuecomment-370701877.

**Comment by speller** [comment]
@sebastianbergmann I'm trying to discuss about this suggestion and I'm explaining whay I think this is good. Why do you just reject me? I'm sorry if I was not so clear in my first post but I explained more clearly in my next post. Why not to discuss?

**Comment by speller** [comment]
At this point:
You are closed for suggestions.
You are closed for discussions.
The framework is closed for extension.
The framework applies architectural restrictions to the client code.

I don't understand why so? I'm trying to ask respectfully and arguing why I'm thinking in my way. Why it is not enough to get your attention?

**Comment by speller** [comment]
I didn't expect so arrogant style of communication from the author...

**Comment by mgrechanik** [comment]
@speller  Have you come to any understanding how to test such cases properly?

Now it looks for me  that phpunit testing  is about objects to behave expected way. 
Not about inner quality of implementation.
