### ISSUE TITLE
catching ExpectationFailedException does not work with fail()

### ISSUE THREAD

**Issue by joachim-n** [sebastianbergmann/phpunit#3022]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.5.5
| PHP version         | 7.0.0
| Installation Method | Composer

I have a helper class for my tests which uses static assertion calls. In particular, for some cases where there is no suitable assertion method, it calls:

```
Assert::fail()
```

In order to test that this class itself is working properly, I tried creating some unit tests for it.

However, when I try to catch PHPUnit\Framework\ExpectationFailedException to verify that my test helper correctly fails, the Assert::fail() fails the unit test.

This problem is demonstrated by a simpler example:

```
  function testCatchAssert() {
    try {
      $this->assertTrue(FALSE);
    }
    catch (\PHPUnit\Framework\ExpectationFailedException $e) {
      // catches this.
    }
  }

  function testCatchFail() {
    try {
      $this->fail();
    }
    catch (\PHPUnit\Framework\ExpectationFailedException $e) {
      // should catch this, but doesn't
    }
  }

```

**Comment by mkasberg** [comment]
`assertTrue()` throws an `ExpectationFailedException`, but `fail()` throws an `AssertionFailedError`.

`ExpectationFailedException` actually extends `AssertionFailedError`. You can simply catch `AssertionFailedError` to get the behavior you want.

**Comment by joachim-n** [comment]
Thanks!
