### ISSUE TITLE
Cannot run with right menu "run ..." when upgrade to phpunit 6

### ISSUE THREAD

**Issue by ke-liang** [sebastianbergmann/phpunit#3027]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.5.7
| PHP version         | 7.0.13
| Installation Method | Composer / PHAR

Test code as below:

namespace PHPUnit\Framework;
class Unit65Test extends TestCase
{
    function testUnit65()
    {
        $this->assertEquals(65, 65);
    }
}

but when I try to run with "Run .." menu in PHPstrom, it show me error "PHP Fatal error:  Class 'PHPUnit\Framework\TestCase' not found in";

Anyway, run "phpunit test/Unit65Test.php" is fine for me via terminal, so could you please help me to solve this problem?

config phpunit as External Libraries
![image](https://user-images.githubusercontent.com/15868713/36833773-803a9560-1d6b-11e8-8bc3-696d6f962c31.png)

**Comment by sebastianbergmann** [comment]
This issue tracker is for the Open Source project that provides the PHPUnit testing framework as well as the CLI tool for executing tests.

Please report issues with regards to IDE integration to the vendor of your IDE.
