### ISSUE TITLE
Class 'PHPUnit_Framework_TestCase' not found

### ISSUE THREAD

**Issue by renanrosalojasmm** [sebastianbergmann/phpunit#3029]
I am trying to use phpunit in CentOS but the following error occurs:

**[phpunit] PHP Fatal error:  Class 'PHPUnit_Framework_TestCase' not found in /var/lib/jenkins/workspace/MyApp/Tests/SearchTest.php on line 5**

I need that PHPUnit be installed locally and not per-project.
I have installed phpunit in ubuntu, and it is working well. I checked the diferences between CentOS and Ubuntu instalations. So I figured out that, there is a folder in Ubuntu (/usr/share/php/PHPUnit) and in CentOS there is not.
May this be a link to the error?

| --------------------| ---------------
| PHPUnit version     | 6.5.7
| PHP version         | 7.0.28
| Installation Method | PHAR

**Comment by sebastianbergmann** [comment]
PHPUnit 6 no longer has `PHPUnit_Framework_TestCase`, see the [release announcement](https://phpunit.de/announcements/phpunit-6.html) for details.
