### ISSUE TITLE
Consider reading config from .phpunit.xml (with leading dot, for visibility)

### ISSUE THREAD

**Issue by skyrpex** [sebastianbergmann/phpunit#3030]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | -
| PHP version         | -
| Installation Method | -

It's pretty common to use hidden files (aka leading dot filenames) for configuration files (see eslint and editorconfig).

* The config file will be hidden in UNIX systems.
* The config file will be naturally grouped with other config files whose name starts with dots (.editorconfig, .env, .gitattributes, .gitignore, .phpcs.xml, etc...).

PS. PHPCS already implemented that [here](https://github.com/squizlabs/PHP_CodeSniffer/issues/1566) :)

**Comment by sebastianbergmann** [comment]
I do not think that the PHPUnit configuration file should be "hidden".
