### ISSUE TITLE
Use of undefined constant

### ISSUE THREAD

**Issue by renanrosalojasmm** [sebastianbergmann/phpunit#3032]
When I set PHPUnit to create Clover reports, I get the following error:

Use of undefined constant WSDL_CACHE_BOTH - assumed 'WSDL_CACHE_BOTH'
Result: 2

| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 5.7.27
| PHP version         | 7.0.28
| Installation Method | PHAR

**Comment by sebastianbergmann** [comment]
PHPUnit 5.7 is no longer supported. Please open a new ticket in case this still applies to a supported version of PHPUnit.
