### ISSUE TITLE
PHPUnit won't install via Composer on PHP7.2

### ISSUE THREAD

**Issue by TXC** [sebastianbergmann/phpunit#3036]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.0.2
| PHP version         | 7.2.2-3+ubuntu16.04.1+deb.sury.org+1
| Installation Method | Composer

```
vagrant@homestead:~/Code/project$ composer require --dev phpunit/phpunit ^7
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for sebastian/diff (locked at 2.0.1) -> satisfiable by sebastian/diff[2.0.1].
    - phpunit/phpunit 7.0.0 requires sebastian/diff ^3.0 -> satisfiable by sebastian/diff[3.0.0].
    - phpunit/phpunit 7.0.1 requires sebastian/diff ^3.0 -> satisfiable by sebastian/diff[3.0.0].
    - phpunit/phpunit 7.0.2 requires sebastian/diff ^3.0 -> satisfiable by sebastian/diff[3.0.0].
    - Conclusion: don't install sebastian/diff 3.0.0
    - Installation request for phpunit/phpunit ^7 -> satisfiable by phpunit/phpunit[7.0.0, 7.0.1, 7.0.2].


Installation failed, reverting ./composer.json to its original content.
vagrant@homestead:~/Code/project$
```

**Comment by sebastianbergmann** [comment]
You have `sebastian/diff` locked to a version that is not compatible with the version of PHPUnit you are trying to install. This is not a PHPUnit issue.

**Comment by dpauli** [comment]
As @sebastianbergmann says the issue creator locked *sebastian/diff* to *2.0.1*. Just remove the line with *sebastian/diff* in the *composer.json*.

**Comment by mvuajua** [comment]
I had the same problem, even though `sebastian/diff` was not locked down anywhere (and only required to be ^2 by phpunit itself according to `composer why`). 

Only solution for me was to uninstall phpunit (triggering an uninstall of `sebastian/diff` as well) and then to reinstall phpunit.

**Comment by connor11528** [comment]
Thanks @mvuajua! I got this error when trying to upgrade my phpunit by requiring it again. Solution for me was to uninstall phpunit and reinstall it:

```
$ composer remove phpunit/phpunit --dev
$ composer require phpunit/phpunit --dev
```

**Comment by Andre-Sekou** [comment]
> You have `sebastian/diff` locked to a version that is not compatible with the version of PHPUnit you are trying to install. This is not a PHPUnit issue.

No response and nothing to add nethertheless...

**Comment by olleharstedt** [comment]
> Solution for me was to uninstall phpunit and reinstall it:

This seem to not keep the same PHPUnit version, am I right? So the heart of the issue is that diff is no longer compatible with PHPUnit 6.5?

**Comment by versha000** [comment]
This update other related sebastian dependencies as well so this solution works
$ composer remove phpunit/phpunit --dev
$ composer require phpunit/phpunit --dev

**Comment by sabbirshawon** [comment]
composer require --dev phpunit/phpunit-selenium
Using version ^7.0 for phpunit/phpunit-selenium
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
- Installation request for phpunit/phpunit-selenium ^7.0 -> satisfiable by phpunit/phpunit-selenium[7.0.0].
- phpunit/phpunit-selenium 7.0.0 requires phpunit/phpunit >=7.0,<8.0 -> satisfiable by phpunit/phpunit[7.0.0, 7.0.1, 7.0.2, 7.0.3, 7.1.0, 7.1.1, 7.1.2, 7.1.3, 7.1.4, 7.1.5, 7.2.0, 7.2.1, 7.2.2, 7.2.3, 7.2.4, 7.2.5, 7.2.6, 7.2.7, 7.3.0, 7.3.1, 7.3.2, 7.3.3, 7.3.4, 7.3.5, 7.4.0, 7.4.1, 7.4.2, 7.4.3, 7.4.4, 7.4.5, 7.5.0, 7.5.1, 7.5.10, 7.5.11, 7.5.12, 7.5.13, 7.5.14, 7.5.15, 7.5.16, 7.5.2, 7.5.3, 7.5.4, 7.5.5, 7.5.6, 7.5.7, 7.5.8, 7.5.9, 7.5.x-dev] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.


I face these issues while installing selenium

**Comment by lugus** [comment]
If it can help someone: 

If you want for example upgrade to phpunit ^9 without remove/require:

`composer require --dev --update-with-dependencies phpunit/phpunit:^9`

**Comment by ehsanbigzad** [comment]
I solved by running 
`sudo apt-get update
sudo apt install php-xml`

**Comment by AntonyZ89** [comment]
I solved with:
`sudo apt install php7.3-curl`

**Comment by mohammadreza-hashemi** [comment]
i solved with
first updated my composer  to last version
than composer remove phpunit/phpunit --dev

**Comment by pravin067** [comment]
Hi,
I am trying to upgrade PHPUnit 4.5.1in my current project running on CodeIgniter 2.1.0 having PHP 7.2.x, to PHPUnit  to 4.8.x, so as to install CIUnit that seems to work for CodeIgniter 2.1.0 as given through this github link : https://github.com/kitsunde/CIUnit. However, i am unable to upgrade PHPUnit through composer.

From the documentation : https://phpunit.de/getting-started/phpunit-4.html, it mentions PHPUnit is compatible with PHP v5.3, 5.4 and 5.5.

So does that mean that the requirement to upgrade to PHPUnit 4.8.x won't work, since my current project is running on CodeIgniter 2.1.0 having PHP 7.2.x? Do I need to upgrade my project to CodeIgniter 3.x and then upgrade PHPUnit from 4.5.1 to 8.x?

**Comment by Junior-Shyko** [comment]
> $ composer remove phpunit/phpunit --dev

Somente em rodar o comando $ composer remove phpunit/phpunit --dev, já funcionou para mim.

**Comment by nikzad-avasam** [comment]
i solved by this : 
`sudo apt update`
`sudo apt install php-xml`
and finally running apache

**Comment by pravin067** [comment]
Thanks @nikzad-avasam
