### ISSUE TITLE
Assert::assertSame() count twice in statistics when bool is given

### ISSUE THREAD

**Issue by simara-svatopluk** [sebastianbergmann/phpunit#3037]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.0.2
| PHP version         | 7.2.2
| Installation Method | Composer

If we call `Assert::assertSame(true, true)`, it count twice in statistics.
This was done in commit:
https://github.com/sebastianbergmann/phpunit/commit/852e5405df1f3f8b46ae54963472b6226f8559e5

Is this behavior intended?

**Comment by EikeNiebuhr** [comment]
Hi,

what do you mean by statistics? Can you maybe provide an example?

**Comment by sebastianbergmann** [comment]
Yes, this is intended.

**Comment by simara-svatopluk** [comment]
Thanks for the answer :-)
