### ISSUE TITLE
Unexpected memory leaks when assigning objects to class properties

### ISSUE THREAD

**Issue by rreynier** [sebastianbergmann/phpunit#3039]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | all
| PHP version         | all
| Installation Method | all

When assigning objects to the a test class as properties, those objects are never cleared and will build up and use memory over time.

See: https://gist.github.com/rreynier/9c41267cd07223b46a8a167b158c059e

I assumed phpunit would clean up itself after each class is ran through?

**Comment by sebastianbergmann** [comment]
You are describing the reason why `tearDown()` exists.

**Comment by rreynier** [comment]
That makes sense @sebastianbergmann .  I have added the following in base test class teardown to auto-handle this:

```        
foreach($this as $key => $value) {
    $this->$key = null;
}
```
Initially I had the expectation that PHPUnit would destroy/unset its classes as it looped through.
