### ISSUE TITLE
StringMatchesFormatDescription fails when matching multiline with \r\n

### ISSUE THREAD

**Issue by jjeising** [sebastianbergmann/phpunit#3040]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.0.1
| PHP version         | 7.1.12
| Installation Method | PHAR (via homebrew/php)

`StringMatchesFormatDescription` seems to have issues when matching line breaks with carriage return:

```
$this->assertStringMatchesFormat("\r\n", "\r\n");
```
The diff is not helpful in this case:
```
PHPUnit 7.0.1 by Sebastian Bergmann and contributors.
Runtime:       PHP 7.1.12 with Xdebug 2.5.5

There was 1 failure:

1) Test::test
Failed asserting that string matches format description.
--- Expected
+++ Actual

…/test.php:10
```

This may be related to this replacement:

https://github.com/sebastianbergmann/phpunit/blob/3e2ff3bb45b13f11b8fd958fb30068e6e11a4f7e/src/Framework/Constraint/StringMatchesFormatDescription.php#L32

**Comment by mkasberg** [comment]
I opened up a pull request with a proposed solution.

There are several potential ways to fix this (assuming we regard it as a bug); this should at least get the discussion started...

**Comment by bkdotcom** [comment]
> assuming we regard it as a bug

I just racked my head for quite some time wondering why my assertion was failing..

why wouldn't this be a bug?
