### ISSUE TITLE
Second argument of assertInstanceOf does not check for object

### ISSUE THREAD

**Issue by carusogabriel** [sebastianbergmann/phpunit#3045]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | latest
| PHP version         | latest
| Installation Method | Composer

Hi,

While refactoring some tests (https://github.com/zendframework/zend-expressive/pull/590), we've discovered that the second argument of `assertInstanceOf` does not check if the given value is actually an `object`. Should we check it, or maybe extend the `assertInstanceOf` functionality to also accept a `string` and instantiate it if is an `object`?

**Comment by dnaber-de** [comment]
For what I see, `assertInstanceOf()` fails if the  actual argument is a string. From the name of the method I would exactly expect that as a string is not an _instance_. Changing the behavior to the one of `is_a('stdClass', 'stdClass', true)` would thus be not a good idea, in my opinion.

**Comment by sebastianbergmann** [comment]
The `IsInstanceOf` constraint is -- and is supposed to be -- "just" a wrapper for the `instanceof` operator.
