### ISSUE TITLE
PHPUnit settings incorrectly set when tests are run in isolation

### ISSUE THREAD

**Issue by theofidry** [sebastianbergmann/phpunit#3047]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.0.0
| PHP version         | 7.2.2
| Installation Method | Composer & PHAR

For [Box](https://github.com/humbug/box) I'm running the tests with `phar.readonly=0`. For security reasons this ini setting cannot be changed at runtime if is at `1`|`On`. As a result setting this ini setting in the config like so:

```xml
<php>
    <ini name="phar.readonly" value="0"/>
</php>
```

Is not working. For this reason I'm passing it down via PHP: `php -d phar.readonly=0 ...`.

However when you annotate a test to be run in a separate process, e.g. with `@runTestsInSeparateProcesses`, the `-d phar.readonly=0` option is not passed down: PHPUnit relies on `GlobalState` to get all the ini settings and set them with `ini_set()` which will not work.

Maybe an alternative approach that would work better is dumping those settings in a file and use that file with php, i.e. something like `php -c /path/to/tmp-file` like done with the XDebugHandler in Composer

**Comment by sebastianbergmann** [comment]
I do not want to add more {bloat|complexity} to the implementation of test isolation, especially not for an edge case like this.

If what you propose makes the existing code simpler and allows what you describe above: great!, lets do it.

**Comment by theofidry** [comment]
I don’t think I’ll have a solution for it soon enough so I feel it’s a
limitation that should be documented for now at least.

I understand your position and would agree with it, but I really don’t like
the fact that any person contributing to box needs to change their PHP
config to run the tests. So I’ll try to investigate a solution as soon as I
can :)
