### ISSUE TITLE
PHPUnit can't find model in Yii2 Framework

### ISSUE THREAD

**Issue by TomaIvanovTomov** [sebastianbergmann/phpunit#3049]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.5
| PHP version         | 7.2
| Installation Method | Composer 

I am trying to test my model by very basic case. If it has a static field. Don't want to use Yii2 tests but the installed by me PHPUnit. In the root directroy I made folder `PHPUnit` in which I`ve installed it via composer. This is my composer file:
```
{
  "require-dev": {
    "phpunit/phpunit": "^6.5",
    "phpunit/phpunit-selenium": "^4.1"
  }
}
```
When I try to execute the test I get an error:
```
phpunit TestLogin.php
PHP Fatal error:  Class 'dektrium\user\models\LoginForm' not found in Z:\toma\toma-metropizza\htdocs\frontend\models\LoginForm.php on line 8

Fatal error: Class 'dektrium\user\models\LoginForm' not found in Z:\toma\toma-metropizza\htdocs\frontend\models\LoginForm.php on line 8
```
I am requiring the model this way because it seems it can't be found by the `autoload.php`:
```
<?php

require_once "vendor/autoload.php";
require_once "../frontend/models/LoginForm.php";

class TestLogin extends PHPUnit\Framework\TestCase
{
    public function setUp()
    {
        $login =  new LoginForm;
    }

    public function testStatic()
    {
        $this->assertClassHasStaticAttribute('test', "LoginForm");
    }
}
```
What I should do in this situation? The dekrium user model is in the right place but can't be found by the test. This is the directory of my project:
```
app/
   /frontned
      /models
         LoginForm.php
   /PHPUnit
      /vendor
      composer.json
      conposer.lock
      TestLogin.php
   /vendor 
   etc.
```
Thank you in advance!

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.

**Comment by TomaIvanovTomov** [comment]
OK. Where should I post it ? Sorry about the mistake.
