### ISSUE TITLE
Phpunit does not appear to automatically require the composer autoloader when installed with phive

### ISSUE THREAD

**Issue by djmattyg007** [sebastianbergmann/phpunit#3050]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.0.2
| PHP version         | 7.2.1
| Installation Method | PHAR (Phive)

When phpunit is installed using composer, it automatically requires the composer autoloader if it is being run from a directory with a vendor directory in it. This doesn't seem to happen with the phar distribution (which is installed with phive).

**Comment by sebastianbergmann** [comment]
Of course. This is what the `--bootstrap` commandline option (and the respective XML configuration file directive) is for.
