### ISSUE TITLE
$this->runTestInSeparateProcess always returns null

### ISSUE THREAD

**Issue by Cayan** [sebastianbergmann/phpunit#3053]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.5.6
| PHP version         | 7.1.15
| Installation Method | Composer

I'm writing some tests that are required to be executed on a different process. From what I found on both the code and on stackoverflow, it seems that it should be accessible through this variable but no matter what I try, it always returns null.

It also seems that it is not simple to check for other configurations as well.

**Comment by sebastianbergmann** [comment]
I do not understand what you are trying to report / ask.

**Comment by Cayan** [comment]
The property runClassInSeparateProcess is always null on the methods setUp and createApplication.

I was looking for a way to prevent or skip some tests based on that.
I decided to create a Listener and it is working properly with it.

I'm using Laravel 5.5 on my project and it doesn't seem like their abstract TestCase class would be the cause of it.

**Comment by sebastianbergmann** [comment]
Test code must be oblivious to whether or not it is executed in isolation. That is why `setUp()` does not need to know about that.
