### ISSUE TITLE
why the phunit code coverage report create css dir or js dir or fonts dir is .css dir  .js dir  .fonts dir ?

### ISSUE THREAD

**Issue by kinyou** [sebastianbergmann/phpunit#3056]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     |5.7.21 
| PHP version         | 7.2.3
| Installation Method | Composer 

![qq 20180329193332](https://user-images.githubusercontent.com/7870804/38086756-2a244738-3388-11e8-9cca-ff2cd4728246.png)
![qq 20180329193352](https://user-images.githubusercontent.com/7870804/38086757-2a595afe-3388-11e8-8a77-beb1b04a987b.png)

**Comment by sebastianbergmann** [comment]
I do not understand what you are trying to ask/report.

**Comment by Mohammadtrabelsi** [comment]
Hi; 
I have the same problème here :
after runnig teste and generating --debug/dashboard.html file i tried To open him in browser but it have a css file under the .css folder witch is inaccessible-debug  /.css/style.css
