### ISSUE TITLE
Uncovered code marked as covered

### ISSUE THREAD

**Issue by guytomer** [sebastianbergmann/phpunit#3057]
When running test on a piece of code that should not be covered,
it is marked as covered.
| PHPUnit version     | 7.0.3
| PHP version         | 7.2.4
| Installation Method | Composer

Composer info:
doctrine/instantiator              1.1.0  A small, lightweight utility to instantiate objects in PHP without invoking their constructors
mikey179/vfsStream                 v1.6.5 Virtual file system to mock the real file system in unit tests.
myclabs/deep-copy                  1.7.0  Create deep copies (clones) of your objects
phar-io/manifest                   1.0.1  Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                    1.0.1  Library for handling version information and constraints
phpdocumentor/reflection-common    1.0.1  Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock  4.3.0  With this component, a library can provide support for annotations via DocBlocks or otherwise ...
phpdocumentor/type-resolver        0.4.0
phpspec/prophecy                   1.7.5  Highly opinionated mocking framework for PHP 5.3+
phpunit/dbunit                     4.0.0  PHPUnit extension for database interaction testing
phpunit/php-code-coverage          6.0.1  Library that provides collection, processing, and rendering functionality for PHP code coverag...
phpunit/php-file-iterator          1.4.5  FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template          1.2.1  Simple template engine.
phpunit/php-timer                  2.0.0  Utility class for timing
phpunit/php-token-stream           3.0.0  Wrapper around PHP's tokenizer extension.
phpunit/phpunit                    7.0.3  The PHP Unit Testing framework.
phpunit/phpunit-mock-objects       6.0.1  Mock Object library for PHPUnit
sebastian/code-unit-reverse-lookup 1.0.1  Looks up which function or method a line of code belongs to
sebastian/comparator               2.1.3  Provides the functionality to compare PHP values for equality
sebastian/diff                     3.0.0  Diff implementation
sebastian/environment              3.1.0  Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 3.1.0  Provides the functionality to export PHP variables for visualization
sebastian/global-state             2.0.0  Snapshotting of global state
sebastian/object-enumerator        3.0.3  Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector         1.1.1  Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context        3.0.0  Provides functionality to recursively process PHP variables
sebastian/resource-operations      1.0.0  Provides a list of PHP built-in functions that operate on resources
sebastian/version                  2.0.1  Library that helps with managing the version number of Git-hosted PHP projects
symfony/yaml                       v4.0.6 Symfony Yaml Component
theseer/tokenizer                  1.1.0  A small library for converting tokenized PHP source code into XML and potentially other formats
webmozart/assert                   1.3.0  Assertions to validate method input/output with nice error messages.

Code:
```php
public function execute()
{
    $this->email = $this->get_email_html_from_repository($this->directory);
    $this->mail_infos = $this->get_mail_infos();
    $this->websites = $this->get_websites_for_mail_infos();
    foreach ($this->mail_infos as $mail_info)
    {
        $email = $this->create_mail_for_mail_info($mail_info);
        $this->mail_sender->send($email);
        $send_result = $this->mail_sender->get_last_send_result();
        $was_mail_sent = $send_result->result = "success";
        $does_after_send_function_exist = \method_exists($this, "after_send");
        if(false)
        {
            $this->after_send($mail_info, $email);
        }
    }
}
```

This line should not be covered:
$this->after_send($mail_info, $email);

but marked as covered
<img width="784" alt="screen shot 2018-03-30 at 12 18 47" src="https://user-images.githubusercontent.com/1851054/38133069-47ca8f2a-3416-11e8-8b42-a95817846f36.png">

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/.github/CONTRIBUTING.md#reporting-issues) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project.

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another.
