### ISSUE TITLE
assertContains doesn't show you what the tested array was

### ISSUE THREAD

**Issue by joachim-n** [sebastianbergmann/phpunit#3061]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.5.5
| PHP version         | 7.2
| Installation Method | Composer 

It would be useful if assertContains() could say what was actually found in the array.

As the docs say, the output when this fails is:

> Failed asserting that an array contains 4.

**Comment by mihailogajic** [comment]
You could use $message parameter for this purpose.

`$this->assertContains(5, $array, print_r($array, true));`

**Comment by sebastianbergmann** [comment]
I do not think it makes sense (or is feasible) to display the actual array.
