### ISSUE TITLE
[Feature request] Asserting the exit code with the phpt runner

### ISSUE THREAD

**Issue by greg0ire** [sebastianbergmann/phpunit#3063]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.0.0
| PHP version         | 7.2.3
| Installation Method |  PHAR

I plan to write a few contributions to Symfony's phpunit-bridge that will alter the exit code depending on the nature of deprecation errors triggered during the test suite. I want to test that code using `.phpt` file, that are a great way to test the output IMO, but seem to lack a section to describe and assert what the exit code should be. Would you be open to such an addition, or should this first be proposed elsewhere [here](https://qa.php.net/phpt_details.php) ?

It would be great to have the following test pass, for instance:

```
--TEST--
Test exit code
--FILE--
<?php
exit(1);
--EXIT_CODE--
1
```

**Comment by sebastianbergmann** [comment]
I do not want features in PHPUnit's PHPT implementation that are not in the PHP project's PHPT test runner. So yes, please propose that there first.
