### ISSUE TITLE
TestListener::startTestSuite is called with DataProviderTestSuite

### ISSUE THREAD

**Issue by malhar-trivedi** [sebastianbergmann/phpunit#3075]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.1.0
| PHP version         | 7.1.8
| Installation Method | Composer

I have question regarding when `TestListner::startTestSuite` should be called.

I am extending `PHPUnit\Framework\TestListener` for my project. I override `startTestSuite` method to keep track of which test suite is running.
If a test case in Test suite is using dataProvider annotation, I noticed `startTestSuite` is called again with `DataProviderTestSuite` (even though technically I am in the same Test suite)

Is this intended behavior?

Thank you

**Comment by sebastianbergmann** [comment]
Yes.
