### ISSUE TITLE
Deleted file in whitelist causes slowdown and memory exhaustion when using code coverage

### ISSUE THREAD

**Issue by Ryangr0** [sebastianbergmann/phpunit#3084]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.0.3
| PHP version         | 7.2.3
| Installation Method | PHAR

I'm doing some refactoring on our Helper classes which resulted in one of our other classes becoming redundant. After deleting it and doing some more refactoring, and finally running `php phpunit/phpunit-7.phar phpunit/Helper/Color --coverage-html test` on my docker container I got this error.

```
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 150994944 bytes) in phar:///var/www/html/phpunit/phpunit-7.phar/php-code-coverage/CodeCoverage.php on line 371

Call Stack:
    0.0131     854272   1. {main}() /var/www/html/phpunit/phpunit-7.phar:0
    0.4893    9047504   2. PHPUnit\TextUI\Command::main() /var/www/html/phpunit/phpunit-7.phar:574
    0.4893    9047616   3. PHPUnit\TextUI\Command->run() phar:///var/www/html/phpunit/phpunit-7.phar/phpunit/TextUI/Command.php:153
    0.5616   10253024   4. PHPUnit\TextUI\TestRunner->doRun() phar:///var/www/html/phpunit/phpunit-7.phar/phpunit/TextUI/Command.php:205
    0.5777   10262360   5. PHPUnit\Framework\TestSuite->run() phar:///var/www/html/phpunit/phpunit-7.phar/phpunit/TextUI/TestRunner.php:508
    0.5785   10262552   6. PHPUnit\Framework\TestSuite->run() phar:///var/www/html/phpunit/phpunit-7.phar/phpunit/Framework/TestSuite.php:760
   85.9529   14785376   7. PHPUnit\Framework\DataProviderTestSuite->run() phar:///var/www/html/phpunit/phpunit-7.phar/phpunit/Framework/TestSuite.php:760
  113.8588   87932544   8. BrightnessTest->run() phar:///var/www/html/phpunit/phpunit-7.phar/phpunit/Framework/TestSuite.php:760
  113.9660  115118088   9. PHPUnit\Util\PHP\DefaultPhpProcess->runTestJob() phar:///var/www/html/phpunit/phpunit-7.phar/phpunit/Framework/TestCase.php:677
  119.7733  129388952  10. PHPUnit\Util\PHP\DefaultPhpProcess->processChildResult() phar:///var/www/html/phpunit/phpunit-7.phar/phpunit/Util/PHP/AbstractPhpProcess.php:200
  119.8945  209441792  11. SebastianBergmann\CodeCoverage\CodeCoverage->merge() phar:///var/www/html/phpunit/phpunit-7.phar/phpunit/Util/PHP/AbstractPhpProcess.php:324
  119.8945  209441792  12. array_merge() phar:///var/www/html/phpunit/phpunit-7.phar/php-code-coverage/CodeCoverage.php:371

```

An abridged version of our whitelist:
```
<whitelist>
    <file>./include/class/Hex/Value.php</file>
    <directory suffix=".php">./include/class/Helper</directory>
</whitelist>
```
After I removed `./include/class/Hex/Value.php` from the whitelist it went back to normal performance.

I would expect some kind of error popping up relating to the missing file instead of memory exhaustion (presumably) due to this issue.

I don't even know if this is a problem that applies to this project or the coverage project itself. If someone could point me in the right direction I would appreciate it.

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/.github/CONTRIBUTING.md#reporting-issues) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project.

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another.
