### ISSUE TITLE
Add functionality to change test running order to help find dependencies

### ISSUE THREAD

**Issue by epdenouden** [sebastianbergmann/phpunit#3089]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.2.x
| PHP version         | 7.2.2
| Installation Method | Composer

As a developer I would like the option to reorder tests to help me find side-effects and implicit dependencies of tests.

A first version would provide the following functionality:
- run tests and suites in **reverse order**
- run tests and suites in **random order**
- provide a way to 'pin' the random order using a seed
- automatic reordering to resolve dependencies between tests (`depends` annotation)

I already have working code for the above in my forked repository. Currently doing some refactoring and writing proper unit tests. 

These changes also provide the basic infrastructure for further test reordering features, for example re-run failed and skipped tests first. Already have some basic work done for that.

**Comment by sebastianbergmann** [comment]
I am curious how you have implemented that.

**Comment by localheinz** [comment]
Sounds interesting!

**Comment by keradus** [comment]
@epdenouden , shall this be closed, as #3092 is already merged ?

**Comment by epdenouden** [comment]
@keradus yes! Today ill finish writing the PR for the 'order defects first' feature

**Comment by keradus** [comment]
:+1:

please, consider defining option for it also in phpunit.xml config file

**Comment by epdenouden** [comment]
Already in there, used the same logic as for the options for the other reorderings.
