### ISSUE TITLE
Subject not unset completely between tests

### ISSUE THREAD

**Issue by BobMali** [sebastianbergmann/phpunit#3091]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 5.7.27
| PHP version         | 7.0.28
| Installation Method | Composer

I am trying to test a method which uses the static keyword on an array within the method. As far as i am aware static is supposed to keep the assigned value intact over multiple method calls, but NOT over the lifecycle of the object itself. Strangely exactly that is happening.
Two tests testing different paths within the method run green if run separately. If i run the whole test-class the second test fails, because the subject still contains the values from the previous test. I confirmed this by debugging the tests.

I tried using an "unset" on the subject in the tearDown-method, but it seems to have no effect.

Here is the output of the "composer info":

| package | version | description
|---------------|--------------------|-----------
| cogpowered/finediff                | 0.3.1              | PHP implementation of a Fine granularity Diff engine
| composer/semver                    | 1.4.2              | Semver library that offers utilities, version constraint parsing and validation.
| dmitryd/typo3-dd-googlesitemap     | 2.1.4              | Google sitemaps for TYPO3
| dmitryd/typo3-realurl              | 2.3.1              | Speaking URLs for TYPO3
| doctrine/annotations               | v1.4.0             | Docblock Annotations Parser
| doctrine/cache                     | v1.6.2             | Caching library offering an object-oriented API for many cache backends
| doctrine/collections               | v1.4.0             | Collections Abstraction library
| doctrine/common                    | v2.7.3             | Common Library for Doctrine projects
| doctrine/dbal                      | v2.5.13            | Database Abstraction Layer
| doctrine/inflector                 | v1.2.0             | Common String Manipulations with regard to casing and singular/plural rules.
| doctrine/instantiator              | 1.0.5              | A small, lightweight utility to instantiate objects in PHP without invoking the...
| doctrine/lexer                     | v1.0.1             | Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
| friendsofphp/php-cs-fixer          | v2.10.3            | A tool to automatically fix PHP code style
| gridelementsteam/gridelements      | 8.0.0              | This extension integrates the grid layout concept also to regular content eleme...
| guzzlehttp/guzzle                  | 6.3.0              | Guzzle is a PHP HTTP client library
| guzzlehttp/promises                | v1.3.1             | Guzzle promises library
| guzzlehttp/psr7                    | 1.4.2              | PSR-7 message implementation that also provides common utility methods
| helhum/typo3-console               | 4.9.3              | A reliable and powerful command line interface for TYPO3 CMS
| helhum/typo3-console-plugin        | 2.0.4              | Installer plugin for helhum/typo3-console, to ease usage without the need to sp...
| mikey179/vfsStream                 | v1.6.5             | Virtual file system to mock the real file system in unit tests.
| mso/idna-convert                   | v1.1.0             | A library for encoding and decoding internationalized domain names
| myclabs/deep-copy                  | 1.7.0              | Create deep copies (clones) of your objects
| paragonie/random_compat            | v2.0.11            | PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
| php-cs-fixer/diff                  | v1.3.0             | sebastian/diff v2 backport support for PHP5.6
| phpdocumentor/reflection-common    | 1.0.1              | Common reflection classes used by phpdocumentor to reflect the code structure
| phpdocumentor/reflection-docblock  | 4.3.0              | With this component, a library can provide support for annotations via DocBlock...
| phpdocumentor/type-resolver        | 0.4.0             | 
| phpspec/prophecy                   | 1.7.5              | Highly opinionated mocking framework for PHP 5.3+
| phpunit/php-code-coverage          | 4.0.8              | Library that provides collection, processing, and rendering functionality for P...
| phpunit/php-file-iterator          | 1.4.5              | FilterIterator implementation that filters files based on a list of suffixes.
| phpunit/php-text-template          | 1.2.1              | Simple template engine.
| phpunit/php-timer                  | 1.0.9              | Utility class for timing
| phpunit/php-token-stream           | 2.0.2              | Wrapper around PHP's tokenizer extension.
| phpunit/phpunit                    | 5.7.27             | The PHP Unit Testing framework.
| phpunit/phpunit-mock-objects       | 3.4.4              | Mock Object library for PHPUnit
| psr/http-message                   | 1.0.1              | Common interface for HTTP messages
| psr/log                            | 1.0.2              | Common interface for logging libraries
| roave/security-advisories          | dev-master 940eb3d | Prevents installation of composer packages with known security vulnerabilities:...
| sebastian/code-unit-reverse-lookup | 1.0.1              | Looks up which function or method a line of code belongs to
| sebastian/comparator               | 1.2.4              | Provides the functionality to compare PHP values for equality
| sebastian/diff                     | 1.4.3              | Diff implementation
| sebastian/environment              | 2.0.0              | Provides functionality to handle HHVM/PHP environments
| sebastian/exporter                 | 2.0.0              | Provides the functionality to export PHP variables for visualization
| sebastian/global-state             | 1.1.1              | Snapshotting of global state
| sebastian/object-enumerator        | 2.0.1              | Traverses array structures and object graphs to enumerate all referenced objects
| sebastian/recursion-context        | 2.0.0              | Provides functionality to recursively process PHP variables
| sebastian/resource-operations      | 1.0.0              | Provides a list of PHP built-in functions that operate on resources
| sebastian/version                  | 2.0.1              | Library that helps with managing the version number of Git-hosted PHP projects
| squizlabs/php_codesniffer          | 3.2.3              | PHP_CodeSniffer tokenizes PHP, JavaScript and CSS files and detects violations ...
| swiftmailer/swiftmailer            | v5.4.9             | Swiftmailer, free feature-rich PHP mailer
| symfony/console                    | v3.4.4             | Symfony Console Component
| symfony/debug                      | v3.4.4             | Symfony Debug Component
| symfony/event-dispatcher           | v3.4.4             | Symfony EventDispatcher Component
| symfony/filesystem                 | v3.4.4             | Symfony Filesystem Component
| symfony/finder                     | v3.4.4             | Symfony Finder Component
| symfony/options-resolver           | v3.4.4             | Symfony OptionsResolver Component
| symfony/polyfill-mbstring          | v1.7.0             | Symfony polyfill for the Mbstring extension
| symfony/polyfill-php70             | v1.7.0             | Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
| symfony/polyfill-php72             | v1.7.0             | Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
| symfony/process                    | v3.4.4             | Symfony Process Component
| symfony/stopwatch                  | v3.4.4             | Symfony Stopwatch Component
| symfony/yaml                       | v3.4.4             | Symfony Yaml Component
| teamtnt/tntsearch                  | v1.3.1             | A fully featured full text search engine written in PHP
| typo3/class-alias-loader           | 1.0.0              | Amends the composer class loader to support class aliases to provide backwards ...
| typo3/cms                          | 8.7.10             | TYPO3 CMS is a free open source Content Management Framework initially created ...
| typo3/cms-cli                      | 1.0.2              | TYPO3 command line binary
| typo3/cms-composer-installers      | 1.4.5              | TYPO3 CMS Installers
| typo3fluid/fluid                   | 2.5.0              | The TYPO3 Fluid template rendering engine
| typo3/testing-framework            | 1.0.9              | The TYPO3 testing framework provides base classes for unit, functional and acce...
| webmozart/assert                   | 1.3.0              | Assertions to validate method input/output with nice error messages.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by BobMali** [comment]
Thank you for your quick reply.

As requested i produced a minimal testcase of the issue:
```
<?php
declare(strict_types=1);

class CacheTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Cache
     */
    protected $subject;

    protected function setUp()
    {
        parent::setUp();

        $this->subject = new Cache();
    }

    protected function tearDown()
    {
        parent::tearDown();

        unset($this->subject);
    }

    /**
    * @test
    */
    public function assignToCacheShouldReturnTrueIfProvidedCacheValueHasBeenAssignedToCacheArray()
    {
        $this->assertTrue($this->subject->assignToCache(1, 'foobar'));
    }

    /**
    * @test
    */
    public function assignToCacheShouldReturnTrueIfDifferentProvidedCacheValueHasBeenAssignedToCacheArray()
    {
        $this->assertTrue($this->subject->assignToCache(1, 'foobar2'));
    }
}
```

And for the sake of completeness here is the tested class:
```
<?php
declare(strict_types=1);

class Cache
{
    public function assignToCache(int $cacheId, string $cacheValue): bool
    {
        static $cacheArrray = [];

        if (!isset($cacheArrray[$cacheId])) {
            $cacheArrray[$cacheId] = $cacheValue;
        }

        return in_array($cacheValue, $cacheArrray, true);
    }
}
```

**Comment by sebastianbergmann** [comment]
The state of method-local static variables cannot be reset. This one of the reasons why any decent coding standard prohibits their use.

**Comment by BobMali** [comment]
And it should. Sadly i am testing and refactoring legacy-code, so i am trying to find a way to test with minimal changes first. But this seems to be a necessary refactoring then.

The question still remains: why is not the whole subject unset? 
As far as i understand the static variables they are supposed keep their values between method calls, but certainly not beyond the lifecycle of an object.
Is the tearDown not supposed to unset the test-oject between tests thus ending the lifecycle of the object?
