### ISSUE TITLE
 Fatal error: Cannot declare class Less_Version, because the name is already in u se in C:\d\htdocs\you.com\app\code\Plazathemes\Layout\Block\lib\Less\Version.php  on line 9

### ISSUE THREAD

**Issue by shenmusam** [sebastianbergmann/phpunit#3099]
![m 2fr75 jyc nv_9if_qt5g](https://user-images.githubusercontent.com/37282394/38913552-eb9fb8f4-430d-11e8-8a89-c6fbbd66d537.png)
what should I do?

**Comment by sebastianbergmann** [comment]
This has nothing to do with PHPUnit.
