### ISSUE TITLE
Mocked methods mangle arguments named "&$result"

### ISSUE THREAD

**Issue by h3xx** [sebastianbergmann/phpunit#3102]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 88373b53cf48e8a280e4a2a8449c0412183b77a5
| PHP version         | 7.1.0
| Installation Method | Git clone of this repo, then composer to pull the dependencies

Observed with phpunit versions as far back as 5.7.27, thru the current master@HEAD of this repo.

Mocked methods will destroy arguments passed in using a reference, but *only* if the parameter in the signature of the method being mocked is named `&$result` - naming the parameter anything else doesn't exhibit the behavior.

Given the following class and test, it will fail with the following message:

	PHPUnit 7.2-g88373b53c by Sebastian Bergmann and contributors.

	Runtime:       PHP 7.1.0 with Xdebug 2.5.5
	Configuration: /home/dchurch/_temp/phpunit/phpunit.xml

	.F                                                                  2 / 2 (100%)

	Time: 96 ms, Memory: 6.00MB

	There was 1 failure:

	1) PHPUnit\Framework\FooTest::testmangler
	Failed asserting that two strings are equal.
	--- Expected
	+++ Actual
	@@ @@
	-'array'
	+'NULL'

	/home/dchurch/_temp/phpunit/src/Framework/Constraint/IsEqual.php:114
	/home/dchurch/_temp/phpunit/src/Framework/Assert.php:2209
	/home/dchurch/_temp/phpunit/src/Framework/Assert.php:556
	/home/dchurch/_temp/phpunit/tests/Framework/FooTest.php:50
	/home/dchurch/_temp/phpunit/src/Framework/TestCase.php:1151
	/home/dchurch/_temp/phpunit/src/Framework/TestCase.php:846
	/home/dchurch/_temp/phpunit/src/Framework/TestResult.php:645
	/home/dchurch/_temp/phpunit/src/Framework/TestCase.php:803
	/home/dchurch/_temp/phpunit/src/Framework/TestSuite.php:776
	/home/dchurch/_temp/phpunit/src/TextUI/TestRunner.php:544
	/home/dchurch/_temp/phpunit/src/TextUI/Command.php:198
	/home/dchurch/_temp/phpunit/src/TextUI/Command.php:151

	FAILURES!
	Tests: 2, Assertions: 2, Failures: 1.

## Complete example

    <?php

    namespace PHPUnit\Framework;

    class Foo {

        public function safeCaller() {
            $arr = [];
            $this->safe($arr);
            return $arr;
        }

        public function safe(&$param_not_called_result) {
        }

        public function manglerCaller() {
            $arr = [];
            $this->mangler($arr);
            return $arr;
        }

        public function mangler(&$result) {
        }

    }

    class FooTest extends TestCase {

        public function testsafe() {
            $mock = $this->getMockBuilder(Foo::class)
                ->setMethods([
                    'safe',
                ])
                ->disableOriginalConstructor()
                ->getMock();

            $arr = $mock->safeCaller();
            $this->assertEquals('array', gettype($arr));
        }

        public function testmangler() {
            $mock = $this->getMockBuilder(Foo::class)
                ->setMethods([
                    'mangler',
                ])
                ->disableOriginalConstructor()
                ->getMock();

            $arr = $mock->manglerCaller();
            $this->assertEquals('array', gettype($arr));
        }

    }

**Comment by h3xx** [comment]
I investigated further and it appears the following variable names are also subject to mangling:

- `&$arguments`
- `&$i`
- `&count`

It has to do with local assignments within the mock method template clobbering arguments that were passed by reference.

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/.github/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-mock-objects](https://github.com/sebastianbergmann/phpunit-mock-objects) project.

I have moved this issue to https://github.com/sebastianbergmann/phpunit-mock-objects/issues/418.
