### ISSUE TITLE
irc://chat.freenode.net : community support channel needs chanops.

### ISSUE THREAD

**Issue by Amgine0** [sebastianbergmann/phpunit#3106]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | x.y.z
| PHP version         | x.y.z
| Installation Method | Composer / PHAR

The irc channel to which official documentation directs people has no managers who can perform minor tasks (such as updating the /topic, which currently announces the release of PHPUnit 4.0.9) Freenode staff are unwilling to either perform topic updates or add nicks to the access list as the channel is 'official', and might be reclaimed at some point.

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/.github/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-documentation-english](https://github.com/sebastianbergmann/phpunit-documentation-english) project.

I have created a ticket [here](https://github.com/sebastianbergmann/phpunit-documentation-english/issues/43).
