### ISSUE TITLE
CliTestDoxPrinter::addError() cannot handle errors in setUpBeforeClass()

### ISSUE THREAD

**Issue by stanolacko** [sebastianbergmann/phpunit#3107]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.1.2
| PHP version         | 7.2.2
| Installation Method | PHAR

If you made error in TestCase, like calling non_existing_function(), you get error, which tells you nothing. In this case, I'm not able to find, that problem is non_existing_function().

class CombiPneuTestSnazzyBee extends PHPUnit\Framework\TestCase {
	
	public static function setUpBeforeClass() {
		non_existing_function();
	}
}

Produce:
PHP Fatal error:  Uncaught Error: Call to a member function fail() on null in phar://REAL_PATH/phpunit.phar/phpunit/Util/TestDox/CliTestDoxPrinter.php:116
Stack trace:
#0 phar://REAL_PATH/phpunit.phar/phpunit/Framework/TestResult.php(265): PHPUnit\Util\TestDox\CliTestDoxPrinter->addError(Object(PHPUnit\Framework\TestSuite), Object(PHPUnit\Framework\ExceptionWrapper), 0)
#1 phar://REAL_PATH/phpunit.phar/phpunit/Framework/TestSuite.php(754): PHPUnit\Framework\TestResult->addError(Object(PHPUnit\Framework\TestSuite), Object(PHPUnit\Framework\ExceptionWrapper), 0)
#2 phar://REAL_PATH/phpunit.phar/phpunit/TextUI/TestRunner.php(529): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#3 phar://REAL_PATH/phpunit.phar/phpunit/TextUI/Command.php(198): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#4 phar://REAL_PATH/phpunit.phar/phpunit/TextUI/Command.php( in phar://REAL_PATH/phpunit.phar/phpunit/Util/TestDox/CliTestDoxPrinter.php on line 116

Fatal error: Uncaught Error: Call to a member function fail() on null in phar://REAL_PATH/phpunit.phar/phpunit/Util/TestDox/CliTestDoxPrinter.php:116
Stack trace:
#0 phar://REAL_PATH/phpunit.phar/phpunit/Framework/TestResult.php(265): PHPUnit\Util\TestDox\CliTestDoxPrinter->addError(Object(PHPUnit\Framework\TestSuite), Object(PHPUnit\Framework\ExceptionWrapper), 0)
#1 phar://REAL_PATH/phpunit.phar/phpunit/Framework/TestSuite.php(754): PHPUnit\Framework\TestResult->addError(Object(PHPUnit\Framework\TestSuite), Object(PHPUnit\Framework\ExceptionWrapper), 0)
#2 phar://REAL_PATH/phpunit.phar/phpunit/TextUI/TestRunner.php(529): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#3 phar://REAL_PATH/phpunit.phar/phpunit/TextUI/Command.php(198): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#4 phar://REAL_PATH/phpunit.phar/phpunit/TextUI/Command.php( in phar://REAL_PATH/phpunit.phar/phpunit/Util/TestDox/CliTestDoxPrinter.php on line 116

**Comment by sebastianbergmann** [comment]
```php
<?php declare(strict_types=1);
use PHPUnit\Framework\TestCase;

class Test extends TestCase
{
    public static function setUpBeforeClass(): void
    {
        does_not_exist();
    }
    
    public function testOne(): void
    {
        $this->assertTrue(true);
    }
}
```
```
$ phpunit --testdox Test
PHPUnit 7.1.4 by Sebastian Bergmann and contributors.

PHP Fatal error:  Uncaught Error: Call to a member function fail() on null in /usr/local/src/phpunit/src/Util/TestDox/CliTestDoxPrinter.php:116
```

**Comment by sebastianbergmann** [comment]
CC @rpkamp
