### ISSUE TITLE
Add Stub_ReturnCallback with invocation object bound to closure

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#3124]
Moved here from https://github.com/sebastianbergmann/phpunit-mock-objects/issues/379.

**Comment by SilverFire** [comment]
So would you like me to do a Pull Request?

**Comment by SilverFire** [comment]
I am occurring a random activity :)

**Comment by SilverFire** [comment]
I make some activity

**Comment by SilverFire** [comment]
No, it's still active

**Comment by SilverFire** [comment]
Nope

**Comment by SilverFire** [comment]
Nope, it's not stale

**Comment by SilverFire** [comment]
No, it's not :)

**Comment by SilverFire** [comment]
Remove stale, please

**Comment by sebastianbergmann** [comment]
I am not convinced that this would be useful.
