### ISSUE TITLE
Raise warning when trying to configure deprecated methods

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#3126]
Moved here from https://github.com/sebastianbergmann/phpunit-mock-objects/issues/307.

**Comment by nicolas-grekas** [comment]
Up. This is quite important for the deprecation framework the php ecosystem needs. Maybe something to look at during the hackathon?

**Comment by sebastianbergmann** [comment]
This was unintentionally marked as stale earlier today. The stale bot has been removed so that something like this does not happen again.
