### ISSUE TITLE
File loader removes and sets back values from $GLOBALS

### ISSUE THREAD

**Issue by pretzlaw** [sebastianbergmann/phpunit#3132]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.3

Within `\PHPUnit\Util\Fileloader::load` new variables will be attached to old variables in global scope.
But if some code already used `global` the Fileloader would remove the bootstrapped variables and bring the system to an invalid state.

Before: `$GLOBALS = [ 'thing' => 123 ]`;

now the bootstrap.php is loaded:
```php
<?php
$thing = 0;

function  foo() {
   global $thing; // Here it goes to the correct scope already.

  $thing = 456;
}

foo();
```

Now `$GLOBALS` is correctly `['thing' => 456]`.
But after the bootstrap file is done `\PHPUnit\Util\Fileloader::load`falsely sets it back to the previous value.

Possible solution (copy $GLOBALS before including bootstrapping / check if things changed already):
```php
foreach ($newVariableNames as $variableName) {
  if ($GLOBALS[$variableName] != $oldVariables[$variableName]) {
    // Already correctly changed by bootstrapping so we skip this
    continue;
  }
            if ($variableName != 'oldVariableNames') {
                $GLOBALS[$variableName] = $newVariables[$variableName];
            }
        }
```

**Comment by sebastianfeldmann** [comment]
I agree with @sebastianbergmann you should not do this in your bootstrap file.
Instead you should set and restore your global state within your test classes.

**Comment by sebastianfeldmann** [comment]
I understand the feeling but the intention of bootstrap is mainly to setup your autoloader or require classes / functions you need during your tests.

To set up globals you need for a test you should use the `setup` or `beforeClass` methods. I hope you don’t need global state for alle your tests, but if you need it in several, you can create a `TestCase` base class or delegate the global state setup to a trait.
This way your tests depending on global state is implicit and not hidden in some dubious bootstrap that is never mentioned in your test.

This may be more work at first, but everybody working on that test after you (even you 6 month from now) will be thankful to you.
