### ISSUE TITLE
Class 'PHPUnit\Framework\BaseTestListener' not found 

### ISSUE THREAD

**Issue by BonBonSlick** [sebastianbergmann/phpunit#3139]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.1
| PHP version         | 7.2
| Installation Method | Composer 

I got some issues with multiple PhPUnits. OS Debian 9, so i removed one from OS, and left only that one from composer. Trying to run test ins PhPStorm 2018.  Everything configured to load phpunit  from vendors, through vendor/autoload.php
https://blog.jetbrains.com/phpstorm/2013/03/phpunit-installation-via-composer-in-phpstorm/

```
run -> ./vendor/bin/phpunit

PHP Fatal error:  Class 'PHPUnit\Framework\BaseTestListener' not found in /var/www/sitename/vendor/mockery/mockery/library/Mockery/Adapter/Phpunit/TestListener.php on line 29
PHP Stack trace:
PHP   1. {main}() /var/www/sitename/vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit\TextUI\Command::main() /var/www/sitename/vendor/phpunit/phpunit/phpunit:53
PHP   3. PHPUnit\TextUI\Command->run() /var/www/sitename/vendor/phpunit/phpunit/src/TextUI/Command.php:151
PHP   4. PHPUnit\TextUI\TestRunner->doRun() /var/www/sitename/vendor/phpunit/phpunit/src/TextUI/Command.php:198
PHP   5. PHPUnit\TextUI\TestRunner->handleConfiguration() /var/www/sitename/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:151
PHP   6. class_exists() /var/www/sitename/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:942
PHP   7. spl_autoload_call() /var/www/sitename/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:942
PHP   8. Composer\Autoload\ClassLoader->loadClass() /var/www/sitename/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:942
PHP   9. Composer\Autoload\includeFile() /var/www/sitename/vendor/composer/ClassLoader.php:322
PHP  10. include() /var/www/sitename/vendor/composer/ClassLoader.php:444
```

Before removing PhPUnit from OS, it test was working but not through PhPStorm. Bu command ./vendor/bin/phpunit was working. Now it is not, after i removed from OS with `sudo apt-get remove --auto-remove phpunit`

Thank you for your help

**Comment by sebastianbergmann** [comment]
`BaseTestListener` was removed in PHPUnit 7, please read the ChangeLog.

**Comment by BonBonSlick** [comment]
Thanks
