### ISSUE TITLE
processIsolation weirdness with constants in the bootstrap

### ISSUE THREAD

**Issue by Tyrael** [sebastianbergmann/phpunit#314]
today I noticed, that if I have a constant definition in my bootstrap file, the test execution will fail with an Constant xy already defined PHP Notice.

I stumbled upon this blogpost: http://css.dzone.com/news/process-isolation-phpunit-0 and I figured out, that phpunit tries to preserve the original global state for the isolated tests, but it seems that it does a little bit too much magic.

What I also found weird, that I also have includes in my bootstrap, which contains class declarations, and it seems that that won't trigger the "Cannot redeclare class" fatal error, so I don't really get it how exactly does the preservation works (didn't checked the source yet).

I created a github repo for the problem:

https://github.com/Tyrael/phpunit-processIsolation-bug

if you clone this repo, and run phpunit, it will fail with the Constant already defined error, if you change the processIsolation to "false" in the phpunit.xml.dist, then it will succeed.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
