### ISSUE TITLE
disableOriginalConstructor & enableProxyingToOriginalMethods exception doesn't account for manual proxyTarget

### ISSUE THREAD

**Issue by TimothyBJacobs** [sebastianbergmann/phpunit#3140]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.5.8
| PHP version         | 7.0.25
| Installation Method | PHAR

I mentioned this in sebastianbergmann/phpunit-mock-objects#264, but I think that repo is shutdown now. But it seems to me this section of code should check if a `$proxyTarget` has been passed, and if so, not throw the exception since phpunit won't have to manually create the originalObject.

```
if ($callOriginalConstructor === false && $callOriginalMethods === true) {
	throw new PHPUnit_Framework_MockObject_RuntimeException(
		'Proxying to original methods requires invoking the original constructor'
	);
}
```

**Comment by TimothyBJacobs** [comment]
_bump_. Happy to submit a PR if my assumptions here are correct.

**Comment by sebastianbergmann** [comment]
Can you provide a **minimal**, **self-contained**, reproducing test case that shows the problem? Thanks!

**Comment by mhsdesign** [comment]
yes i can confirm this, you need to set also `disableOriginalClone`
