### ISSUE TITLE
Expect PHP's `\assert()` similar to `->expectException()`

### ISSUE THREAD

**Issue by afoeder** [sebastianbergmann/phpunit#3146]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 5.7.27
| PHP version         | 7.2.6
| Installation Method | Composer

Hi,
I have an occurrence of `\assert()` in my code in order to achieve some type safety when using a foreign library (the actual code line is 
```php
$payload = $originalBacklog->getPayload();
\assert(\is_array($payload));
```

How can I verify this working in a unit test?

Differently worded, the following would be 

### Method 1
```php
public function someCode($foreignEntity)
{
  if (!is_array($foreignEntity->getPayload()) {
    throw new InvalidTypeException();
  }
  // …
}

// … according test

public function testSomeCodeThrowsExceptionIfPayloadNotAnArray()
{
    $this->assertException(InvalidTypeException::class);
    $foreignEntityMock =
        $this->createMock(…)->method('getPayload')->willReturn('notanarray');
    $…->someCode($foreignEntityMock);
}
```

### Method 2: `assert()` instead `throw Exception`

```php
public function someCode($foreignEntity)
{
  assert(is_array($foreignEntity->getPayload());
}

// --> how might the according Unit Test look in order to achieve the same?

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.

That being said, simply set `zend.assertions=1` and `assert.exception=On` and you will be able to use `expectException()` to expect that `assert()` is triggered in the tested code.
