### ISSUE TITLE
Global constants as default parameter values are not handled correctly in namespace 

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#3154]
Moved here from https://github.com/sebastianbergmann/phpunit-mock-objects/issues/420.

**Comment by InvisibleSmiley** [comment]
Any chance of getting this backported to PHPUnit 6?

**Comment by sebastianbergmann** [comment]
If somebody sends a pull request, sure.

**Comment by epdenouden** [comment]
@sebastianbergmann I'll do it this weekend, since I am not going to be having my HHVM fun

**Comment by sebastianbergmann** [comment]
Thanks!

**Comment by weeman1337** [comment]
@epdenouden I could take this one over.  
I did first open a backport PR in the mock objects repository since the mock objects are decoupled in PHPUnit 6.   After merging this change we can update the composer file for PHPUnit 6.

**Comment by epdenouden** [comment]
@weeman1337 Nice one, thanks! I will spend my time on some docs updating then :)

**Comment by sebastianbergmann** [comment]
Nevermind: 36101dc9c31b9c49ad41f20de48fc1af8c34e5f8
