### ISSUE TITLE
Make сonvenient to read error output when test JSON structure

### ISSUE THREAD

**Issue by solofeed** [sebastianbergmann/phpunit#3173]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.2.4
| PHP version         | 7.1.18
| Installation Method | Composer

I propose to give control on error output when tests fail for comfortable reading errors.

For example, when I testing my rest API and my structure of JSON is invalid, I see JSON as a string, but  I want to have the possibility to print beauty JSON in the command line when an error has occurred.

**Comment by epdenouden** [comment]
@solofeed Thank you for your suggestion. Are there any Printer plugins/extensions for PHPUnit that you already like to use?

@sebastianbergmann I am thinking about doing a next project regarding Printer/Listener improvements, would you be interested in have work done on this? (for 7.x/8.x)

**Comment by sebastianbergmann** [comment]
@solofeed Do you use `assertJsonStringEqualsJsonString()`? That should print "prettified" JSON in case of failure.

**Comment by sebastianbergmann** [comment]
@epdenouden I do not think that this is related to result printers or test listeners.

**Comment by solofeed** [comment]
@epdenouden Yes, right now I am using https://github.com/mikeerickson/phpunit-pretty-result-printer

**Comment by solofeed** [comment]
@sebastianbergmann I am using laravel, so it was the problem in assertJsonFragment method
I will create an issue in the correct place for it.
Thank you
