### ISSUE TITLE
PHPUnit test suite is taking 1.5 times faster to execute with code coverage report.

### ISSUE THREAD

**Issue by sirishaggk** [sebastianbergmann/phpunit#3175]
Hi,

When we run  the whole test suite with coverage report, the tests are taking nearly ```20mins``` to execute. Where are if we add the option ```--no-coverage``` to the ```vendor/bin/phpunit``` command, the tests getting executed in around ```8minutes```.

I'm using following versions

| PHPUnit version     | 6.4.*
| PHP version         |7.1.16
| Installation Method | Composer 

Could you please suggest me what is wrong in this?

**Comment by sebastianbergmann** [comment]
This is normal and expected behaviour. The collection and processing of code coverage information is time and memory consuming.
