### ISSUE TITLE
Case sensitivity for --filter

### ISSUE THREAD

**Issue by stof** [sebastianbergmann/phpunit#3181]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.2.4
| PHP version         | 7.2.6
| Installation Method | Composer

Currently, the matching of tests for `--filter` is case sensitive. It happens a lot to me that no tests are running at all, due to writing the filter all in lowercase rather than putting capital letters matching the test name.
Would it make sense to perform a case-insensitive match instead ?

**Comment by sebastianbergmann** [comment]
Maybe. You can also pass a regular expression that works in a case insensitive way.

**Comment by stof** [comment]
passing a regular expression is more complex. I still think that being case insensitive for the simple matching would make more sense.

**Comment by evgpisarchik** [comment]
what if to pass **--case-insensitive** option to phpunit command
