### ISSUE TITLE
How to get private property from phpUnit Mock object

### ISSUE THREAD

**Issue by fanatov37** [sebastianbergmann/phpunit#3192]
```
class Car
{
   private $color='red';
}
```
After I do mock object

$carMock = $this->getMockBuilder(Car::class)->getMock();
So now I wanna get private property color of CarMock object

How to do it?!

I can do public method like getCar and it will work, but I wanna look for another way.

I tried use ReflectionClass for it but it was wrong.

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.
