### ISSUE TITLE
@covers / @uses annotations for interfaces

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#3195]
Suggested by @spriebsch:

- [X] `@covers AnInterface` should raise a warning (as there is no point in trying to cover an interface)
- [ ] `@uses AnInterface` should allow any implementation of the specified interface

**Comment by sebastianbergmann** [comment]
`@uses AnInterface` probably depends on https://github.com/sebastianbergmann/php-code-coverage/issues/519

**Comment by garak** [comment]
Since 7.4 is out, I guess that this should be moved to milestone 7.5

**Comment by sebastianbergmann** [comment]
Superseded by #5734.
