### ISSUE TITLE
Remove code for HHVM

### ISSUE THREAD

**Issue by epdenouden** [sebastianbergmann/phpunit#3207]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.x latest
| PHP version         | 7.x

Proposal: while digging through the internals, I found references to HHVM in the PHPUnit core. In https://github.com/sebastianbergmann/phpunit/issues/2578 you stated HHVM is no longer supported. I'll remove the legacy code and send in a pull request over the weekend.

**Comment by sebastianbergmann** [comment]
Thanks!

**Comment by epdenouden** [comment]
ha, yes I figures as much :) I which case I don't think there is much if any HHVM cleanup to do in PHPUnit itself. If you know of any ticket for this just shove it my way, otherwise we can close this one. I'll go back to digging through the internals regarding #10 :)
