### ISSUE TITLE
"Error: Call to a member function sub() on null" while mocking DateTimeImmutable or DateTime

### ISSUE THREAD

**Issue by dinamic** [sebastianbergmann/phpunit#3208]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.2.6
| PHP version         | 7.2.7
| Installation Method | Composer

I have a case with ClassA invoking ClassC using some parameters from ClassB. Seems like something is wrong there. I managed to narrow it down to mocking instances of `DateTimeImmutable` objects.

I have heard that argument that they are value objects before. However, I am keen on doing unit testing and not functional testing. So I would like to assert that a certain method was called a number of times and would return a certain result.

Resources:
- TestCase: [https://pastebin.com/ywydbxtk](https://pastebin.com/ywydbxtk)
- `composer info | sort`: [https://pastebin.com/Ur1KumT1](https://pastebin.com/Ur1KumT1)

```
PHPUnit 7.2.6 by Sebastian Bergmann and contributors.

Testing PhpunitTest
E                                                                   1 / 1 (100%)

Time: 311 ms, Memory: 14.00MB

There was 1 error:

1) PhpunitTest::testPhpunitTest
Error: Call to a member function sub() on null

/home/jiminny/tests/unit/PhpunitTest.php:64
/home/jiminny/tests/unit/PhpunitTest.php:100

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```

**Comment by dinamic** [comment]
This one seems related https://github.com/phpspec/phpspec/issues/887

**Comment by sebastianbergmann** [comment]
This works as expected, I would say. And yes, if at all, the problem would be in the comparator component.

**Comment by dinamic** [comment]
@sebastianbergmann, I don't get how's this an expected behaviour. Could you elaborate, please?

**Comment by dinamic** [comment]
How about checking whether the certain object is the same using `spl_object_hash()` and then to default to what the current algorithm does. Do you think this could work?
