### ISSUE TITLE
Allow to skip tests using annotations

### ISSUE THREAD

**Issue by undertext** [sebastianbergmann/phpunit#3220]
Junit has `@Ignore` annotation for a long time, and sometimes I find it quite useful.
https://github.com/junit-team/junit4/wiki/ignoring-tests

What do you think about adding `@Ignore` annotation to phpunit?

**Comment by epdenouden** [comment]
Hello @undertext ! Would `markTestSkipped()` fit your use case? https://phpunit.readthedocs.io/en/7.1/incomplete-and-skipped-tests.html?highlight=skipped#skipping-tests

**Comment by undertext** [comment]
Hi @epdenouden.
Yeaah, l can use `markTestSkipped ` in `setUp()` method so all tests from testcase will be skipped.
That is exactly what I want. 
But still, it will be much more convenient for me just mark test with 
```php
/**
* @ignore Old test that needs rewriting
*/
 class TestSkipped extends TestCase 
 { 
}
```
and do not modify the class methods directly, just provide the metainformation that test should be skipped.

**Comment by sebastianbergmann** [comment]
I would rather not add new annotations.

**Comment by keradus** [comment]
Randomly marking test as skipped without any reason is bad practice to me.

I can understand conditional skipping test, but that's either done with `@require` or calling `markTestSkipped` method under some condition.

Skipping test **always** is bad idea, if you ask me.

**Comment by martijn80** [comment]
I was looking for a way to skip tests via annotations, but then I realised I could as well alter the method name from **test**ThisAndThat() to **skip**ThisAndThat or just anything just remove the "test" prefix

This will skip the test.

**Comment by bits-of-static** [comment]
A `@dataProvider` annotation has no way of getting information on the runtime logic which calls `markTestSkipped()`. So the data provider is always ran - there is no good way of turning a test on/off.

Having to ignore a test or a whole test unit is nothing extraordinary.

**Comment by hashimaziz1** [comment]
> 

Disagree, way too blanket a statement to be true. As just one example, here's a good usecase for skipping a test:

https://softwareengineering.stackexchange.com/a/131009/314870

**Comment by hashimaziz1** [comment]
> Randomly marking test as skipped without any reason is bad practice to me.
> 
> I can understand conditional skipping test, but that's either done with `@require` or calling `markTestSkipped` method under some condition.
> 
> Skipping test **always** is bad idea, if you ask me.

Disagree, way too blanket a statement to be true. As just one example, here's a good usecase for skipping a test:

https://softwareengineering.stackexchange.com/a/131009/314870
