### ISSUE TITLE
PHPUnit error while running the test

### ISSUE THREAD

**Issue by syedmurtaza** [sebastianbergmann/phpunit#3228]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | PHPUnit 5.7.27
| PHP version         | PHP 7.2.7-0ubuntu0.18.04.2 (cli) (built: Jul  4 2018 16:55:24) ( NTS )
| Installation Method | Composer

I am getting the following error while i run the test:

PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/html/civi/wp-content/plugins/civicrm/civicrm/packages/DB.php on line 793
PHP Fatal error:  Uncaught RuntimeException: Command failed (cv php:boot --level=full):

Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/html/civi/wp-content/plugins/civicrm/civicrm/packages/DB.php on line 793
/*BEGINPHP*/
if (PHP_SAPI === "cli") {
$_SERVER["SCRIPT_FILENAME"] = '/var/www/html/civi/index.php';
$_SERVER["REMOTE_ADDR"] = '127.0.0.1';
$_SERVER["SERVER_SOFTWARE"] = NULL;
$_SERVER["REQUEST_METHOD"] = 'GET';
$_SERVER["SCRIPT_NAME"] = '/home/murtaza/buildkit/bin/cv';
putenv("CIVICRM_UF=" . 'UnitTests');
$_ENV["CIVICRM_UF"] = 'UnitTests';
}
$GLOBALS['_CV'] = array (
);
define("CIVICRM_SETTINGS_PATH", '/var/www/html/civi/wp-content/uploads/civicrm/civicrm.settings.php');
$error = @include_once CIVICRM_SETTINGS_PATH;
if ($error == FALSE) {
  throw new \Exception("Could not load the CiviCRM settings file: {$settings}");
}
require_once $GLOBALS["civicrm_root"] . "/CRM/Core/ClassLoader.php";
\CRM_Core_ClassLoader::singleton()->register();\CRM_Core_Config::singleton();\CRM_Util in /var/www/html/civi/wp-content/plugins/civicrm/civicrm/Civi/Test/CiviTestListener.php on line 229

While PHPUnit4 gives the following error when we give the Unit test path or simpley write the PHPUnit
PHP Fatal error:  Declaration of SebastianBergmann\Comparator\DateTimeComparator::assertEquals($expected, $actual, $delta = 0, $canonicalize = false, $ignoreCase = false) must be compatible with SebastianBergmann\Comparator\ObjectComparator::assertEquals($expected, $actual, $delta = 0, $canonicalize = false, $ignoreCase = false, array &$processed = Array) in phar:///~/buildkit/extern/phpunit4/phpunit4.phar/sebastian-comparator/DateTimeComparator.php on line 80

Please help

**Comment by sebastianbergmann** [comment]
PHPUnit 5 was never supported on PHP 7.2 and is no longer supported at all.

**Comment by syedmurtaza** [comment]
While PHPUnit4 gives the following error when we give the Unit test path or simpley write the PHPUnit
PHP Fatal error: Declaration of SebastianBergmann\Comparator\DateTimeComparator::assertEquals($expected, $actual, $delta = 0, $canonicalize = false, $ignoreCase = false) must be compatible with SebastianBergmann\Comparator\ObjectComparator::assertEquals($expected, $actual, $delta = 0, $canonicalize = false, $ignoreCase = false, array &$processed = Array) in phar:///~/buildkit/extern/phpunit4/phpunit4.phar/sebastian-comparator/DateTimeComparator.php on line 80

**Comment by keradus** [comment]
PHPUnit 4 (and PHPUnit 5, actually), is not supported anymore
