### ISSUE TITLE
Writing tests for CIVICRM hooks

### ISSUE THREAD

**Issue by syedmurtaza** [sebastianbergmann/phpunit#3229]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | PHPUnit 5.7.27
| PHP version         | PHP 7.2.7-0ubuntu0.18.04.2 (cli) (built: Jul 4 2018 16:55:24) ( NTS )
| Installation Method | Composer

Hi, What is the best way to write tests for CIVICRM's BuildForm and PostProcess hooks? Please give an example if possible.

**Comment by keradus** [comment]
after seeing this post, I now understand the next comment of yours, @sebastianbergmann ...

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.

Also note that PHPUnit 5 is no longer supported by the PHPUnit Project.
