### ISSUE TITLE
Assertions after exception is thrown

### ISSUE THREAD

**Issue by dallincoons** [sebastianbergmann/phpunit#3230]
It would be helpful if we could have assertions after checking that an exception was thrown:

```
this->expectException(Exception::class);
//something that throws an error

//assert something after an exception is thrown to make sure it was handled properly
```

Thoughts?

**Comment by keradus** [comment]
big :-1: on that one

exceptions are cutting the execution flow, after exception is thrown no further assertions shall be executed (or in fact, any flow).

what kind of code you have, that side to throwing an error, it's also causing side effects that you want check?
it looks like `try {} catch {}` shall be your solution, if you ask me

**Comment by dallincoons** [comment]
Database transactions for example..

**Comment by keradus** [comment]
without concrete code sample, all I can tell that if `try/catch` of test wont help you (Agree not cleanest solution ever), the separation of layers could - layer that only interacts with db, layer that brings some model/repository logic
