### ISSUE TITLE
Listener method endTestSuite runs after finishing tests in a directory , not the test suite

### ISSUE THREAD

**Issue by ChangePlaces** [sebastianbergmann/phpunit#3232]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.2.7
| PHP version         | 7.2
| Installation Method | applies to composer and apt-get

I have a listener that is set up to run code at the end of a testsuite. This at the basic level is functioning. I have a test suite set up as such:
```
        <testsuite name="e2e">
            <directory>tests/e2e</directory>
        </testsuite>
```
When running with `phpunit --testsuite e2e`, at the end of each sub directory inside this suite, the code inside `endTestSuite` is executed. Surely this is incorrect, as a directory is not considered a 'suite'?

**Comment by ChangePlaces** [comment]
not stale

**Comment by epdenouden** [comment]
@ChangePlaces I'd have to look into the implementation details in the main test runner, but I wouldn't be surprised if every [subdirectory + tests] is handled by creating a `TestSuite` for it with the individual test(suite)s as child nodes.

**Comment by sebastianbergmann** [comment]
@epdenouden That is the case IIRC.

**Comment by epdenouden** [comment]
@ChangePlaces could you share a bit more of the directory structure and the actual output? I want to look at this for the upcoming logger and TestHook refactoring

**Comment by ChangePlaces** [comment]
I'd love to but this was a long time ago for me! I seem to recall I had a directory with 1 level of sub-directories which contained tests inside and I was expecting to be able to run the parent directory as a test suite, instead of each separate dir as a test suite
