### ISSUE TITLE
assertArraySubset with $strict=true doesn't display differences properly

### ISSUE THREAD

**Issue by crhg** [sebastianbergmann/phpunit#3234]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.2.7
| PHP version         | 7.2.5
| Installation Method | Composer

The following test will fail but no differences will be displayed.

```php
<?php
use PHPUnit\Framework\TestCase;

class FooTest extends TestCase
{
    public function testFoo()
    {
        $this->assertArraySubset(['foo' => 1], ['foo' => '1'], true);
    }
}
```

```console
% ./vendor/bin/phpunit FooTest.php
PHPUnit 7.2.7 by Sebastian Bergmann and contributors.

F                                                                   1 / 1 (100%)

Time: 28 ms, Memory: 4.00MB

There was 1 failure:

1) FooTest::testFoo
Failed asserting that an array has the subset Array &0 (
    'foo' => 1
).
--- Expected
+++ Actual

/Users/matsui/src.nobk/phpunit-test/FooTest.php:8

FAILURES!
Tests: 1, Assertions: 1, Failures: 1.
```

**Comment by lsfiege** [comment]
+1

**Comment by lsfiege** [comment]
+1 with PHPUnit 7.3.0

**Comment by sebastianbergmann** [comment]
I am not sure whether displaying a diff is useful here to begin with. Is
```
Failed asserting that an array has the subset Array &0 (
    'foo' => 1
).
```
not sufficient? If it is, then we should simply remove the diff completely.

**Comment by crhg** [comment]
If the information is only it, I can not know what kind of problem was with the actual value.

Displaying the following information at the same time makes debugging more efficient.

* Which key has a problem
* Whether element of that key exists or not
* If an element of that key exists, what was the actual value?

**Comment by 1blankz7** [comment]
The input for the diff is currently generated with `r_print`. The result for `['foo' => '1']` is `([foo] => 1)`. If we use `var_export` the correct type would be more present in the output and the diff is more usable.

**Comment by crhg** [comment]
This fix is ​​valid for this issue, but I think there is a problem when `$strict` is false.

When `$strict` is false, the number `1` and the string `'1'` are treated as equal, so the `print_r` used in the original code is better.

It is good to use `print_r` and `var_export` differently depending on whether `$strict` is true or false.

**Comment by 1blankz7** [comment]
Can you explain why using `var_export` is an issue when `$strict` is false? In my understanding the code is not executed at all if the check passes.

**Comment by crhg** [comment]
When expected is

```php
[
    'foo' => 1,
    'bar' => 2,
]
```

and actual is

```php
[
    'foo' => '1',
    'bar' => '3',
]
```

the check doesn't pass and the diff is shown.

If `var_export` is used, both `foo` and `bar` is different, but `$strict` is false, `foo` is ok and only `bar` should be included in diff.
