### ISSUE TITLE
Public API

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#3236]
In order to define a [Backward Compatibility Promise](http://symfony.com/doc/current/contributing/code/bc.html) we need to make it explicit which parts of PHPUnit's API are considered to be public.

We should start by adding `@internal` to all classes, interfaces, and traits. Then we need to figure which units of code must be public (and remove `@internal` from them) for being able to use PHPUnit.

**Comment by keradus** [comment]
just in case - i can help with adding @internal everywhere with PHP CS Fixer

**Comment by sebastianbergmann** [comment]
I know, thanks.

**Comment by DavertMik** [comment]
Hi, Sebastian. 
There are quite a lot o projects which may use PHPUnit via its current API and it would be nice to keep it stable. Codeception is one of them. I'd kindly ask to make all APIs used here https://github.com/Codeception/phpunit-wrapper to be considered as public API. 

Also, I know that JetBrains also heavily relies on PHPUnit internals to make their integration working. 
Not sure of issues on their side but I think we can invite them for the discussion.

**Comment by sebastianbergmann** [comment]
JetBrains does not rely on PHPUnit internals, not since the TeamCity test listener was added to PHPUnit.

**Comment by keradus** [comment]
Nice thing with public API is that if sth is not marked as part of it, it can always become part of it.
But if it's already marked as public, taking it down is BC breaker.

Saying that - if we will make public API too narrow, we can always make it wider with any release (minor or even patch)

**Comment by wbars** [comment]
I confirm, starting with PHPUnit 5.0 PhpStorm integration relies only on _output_ of TeamCity.php atm

**Comment by keradus** [comment]
nice, @sebastianbergmann !
