### ISSUE TITLE
result cache file created by default

### ISSUE THREAD

**Issue by kubawerlos** [sebastianbergmann/phpunit#3237]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.3.0
| PHP version         | 7.2.8
| Installation Method | Composer

After upgrading from PHPUnit 7.2 when running tests the `.phpunit.result.cache` was created. Shouldn't be check [here](https://github.com/sebastianbergmann/phpunit/blob/7.3.0/src/Util/TestResultCache.php#L76) for not defined?

**Comment by sebastianbergmann** [comment]
@epdenouden *ping*

**Comment by epdenouden** [comment]
@sebastianbergmann @kubawerlos will look into it this weekend!

**Comment by keradus** [comment]
the variable is hack/trick to NOT save cache file when running tests for PHPUnit itself during PHPUnit development (maybe a comment there would be nice, for now it's hidden knowledge, and each hack deserves a comment)

By default, the new caching feature is enabled: https://github.com/sebastianbergmann/phpunit/blob/00d26bb6c5ada299716fe85163b2be39100c8af1/src/TextUI/TestRunner.php#L1160 , as it's hard to discover the feature by users if you don't track the changes, while starting taking benefits from it is super nice

**Comment by kubawerlos** [comment]
[Changelog](https://github.com/sebastianbergmann/phpunit/blob/7.3.0/ChangeLog-7.3.md) claims it's disabled by default.

**Comment by epdenouden** [comment]
@kubawerlos Quick question: would you be fine with a revised changelog or you have a use case where the creation of the cachefile causes trouble? We would like to have the feature enabled if it doesn't interfere with use cases I didn't think of during development.

**Comment by kubawerlos** [comment]
@epdenouden it's totally fine to have it enabled by default, only it came as surprise after reading Changelog.

**Comment by dmitry-ivanov** [comment]
+1

What is the reason to have that `.phpunit.result.cache` file not deleted by default?
I think that for most of users - we don't need it, as it was before. No?

**Comment by epdenouden** [comment]
@dmitry-ivanov The answer to your question has two parts:
1. the file is _not deleted_ as it is a cache to store information about test results between runs.
2. it is currently _created_ by default as it takes up little space and the cache needs to be active to support the 'run failed tests first' (`--order-by=defects`) feature. See #3147 for more details

**Comment by dmitry-ivanov** [comment]
@keradus "possibility to execute tests faster"? How do results from the previous run can help to execute tests faster?

The file is used for the new feature to run failed tests first, as @epdenouden mentioned.
Nice feature, thanks guys! Now I get it.

**Comment by epdenouden** [comment]
@dmitry-ivanov During development I often use `--order-by=depends,defects --stop-on-defect` to quickly halt PHPUnit when getting tests green. Some IDEs like IntelliJ have this feature built into their user interface:

![image](https://user-images.githubusercontent.com/26651359/43633934-0e5a5bd2-970b-11e8-83af-6ae45afc1392.png)

**Comment by RinkAttendant6** [comment]
@epdenouden Regarding

> Quick question: would you be fine with a revised changelog or you have a use case where the creation of the cachefile causes trouble? We would like to have the feature enabled if it doesn't interfere with use cases I didn't think of during development.

It works fine in PhpStorm as you mentioned, but when I run the tests using the command line on a read-only filesystem then it will fail trying to write the cache file. Example of a read-only filesystem include shared folders on a Vagrant dev environment.

**Comment by rtek** [comment]
@epdenouden I love the feature and just enabled it for my tests, but agree with @RinkAttendant6 that it should be disabled by default since it could be a BC break depending on where phpunit is executed.

**Comment by dpauli** [comment]
@dmitry-ivanov I did not get it: In the IDE you mentioned here its easy to rerun only failed tests. There is a button for doing this.

The new implemented ticket says

> Support for running tests first that failed in a previous run

(saying: Run all test, but in another order). This does no increase execution time of running test.

**Comment by dmitry-ivanov** [comment]
> In the IDE you mentioned here its easy to rerun only failed tests.

@dpauli Can you please show me where I wrote this? :)

PS: @epdenouden said, that you can use `--order-by=depends,defects --stop-on-defect` to run failed tests *first*. And if there are still some failed tests - your execution will stop.

And some IDEs have even a button in their UI for that.

**Comment by dpauli** [comment]
@dmitry-ivanov Sorry for the missing comma (I updated it) and the wrong person I mentioned :) Its too warm today:

@epdenouden argued with a feature which is already implemented in the IntelliJ IDE.

**Comment by oniice** [comment]
So is this file supposed to be generated by default or not?
When running in PhpStorm it is creating in the project root or in the /tests dir if running a suite in isolation.
Also storm ignores the cacheResult="false" as it passes --no-configuration when it runs

**Comment by epdenouden** [comment]
@oniice Yes, the `--no-configuration` issue came up in the office, too. I think taking _don't use a configuration_ as a request to mean _be as defensive as possible_ would be good. In other words: no config = no cache writing/reading

**Comment by keradus** [comment]
no config === default configuration
default on v7 is no cache, default on v8 will be with cash
