### ISSUE TITLE
Run all tests even if group is excluded in phpunit.xml

### ISSUE THREAD

**Issue by kunicmarko20** [sebastianbergmann/phpunit#3239]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | w/e
| PHP version         | w/e
| Installation Method | w/e

Is there a way to run all tests even if you have some group excluded in phpunit.xml? 

Not sure if this is a right place to ask a question, sorry if not.

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry. To answer your question: no, that is not possible.
