### ISSUE TITLE
PHP Fatal error when an exception can't be serialized in __phpunit_run_isolated_test

### ISSUE THREAD

**Issue by realmfoo** [sebastianbergmann/phpunit#324]
Hi,

When I run my tests with the process isolation., some exceptions lead to fatal arrors. For example:

"RuntimeException: PHP Fatal error:  Uncaught exception 'PDOException' with message 'You cannot serialize or unserialize PDO instances' in -:34"

How could I deal with this?

**Comment by Raaghu** [comment]
This is because of a large Objects saved in the TestCase, 

when there is a assertion failures , the trace is generated and serialized ,
so serialization breaks if there is huge data in traces.

in my case i was saving dataset in the test case , which generated a 239555 bytes of data in trace
