### ISSUE TITLE
Enable result cache by default

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#3244]

**Comment by keradus** [comment]
shall we also change order execution to `depends,defects` ?
the thing is, without that, cache file would be created, but not used, thus no benefits of creating it

**Comment by sebastianbergmann** [comment]
Makes sense.

**Comment by sebastianbergmann** [comment]
@epdenouden I started to work on this in 36ed9fefd3672592e4c36e5f53e07f1db1efe229.

One thing I noticed that if I run PHPUnit's own test suite with `--do-not-cache-result` then a cache file will still be written. This does not come from PHPUnit's own test suite itself but from one of the test suites used by it. Without `--do-not-cache-result` this cache file will be overwritten at the end by the cache file for PHPUnit's own test suite.

We probably have to disable the cache for all test suites executed by PHPUnit's own test suite.

**Comment by epdenouden** [comment]
@sebastianbergmann Yes, unfortunately that is a known issue with (some of?) the PHPT tests. I have never looked that up in detail, however I am aware of it. The saving grace for PHPUnit's own test suite is that it overwrites the other caches at the end.

I think at some point there was a development version that looked at the `PHPUNIT_TESTSUITE` constant being defined. Complicating factors I found but never fully explored:
- the working directory of some tests results in caches being littered in subdirectories
- caches in the working directory being left lying around when I CTRL-`C` the run

In newer tests I actively work around the issue by explicitly copying the cache to a temporary file somewhere else and deleting it afterwards. This works really well; example:
https://github.com/sebastianbergmann/phpunit/blob/4de2605d7e48ee6372f24f1dcf3daefca60c3ad6/tests/end-to-end/regression/GitHub/3396/issue-3396-test.phpt#L1-L18

I am not sure what the best solution is that works in _all cases_, honestly. Wish I had a better answer for you already :-(
