### ISSUE TITLE
Warning in console when phpunit.xml exclusions are not sorted properly

### ISSUE THREAD

**Issue by lunfel** [sebastianbergmann/phpunit#3248]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.3.1
| PHP version         | 7.2.8
| Installation Method | Composer

I recently updated my version of PHPUnit. I don't know exactly which version I was running before. Now that I have updated it, I get this warning

```
PHPUnit 7.3.1 by Sebastian Bergmann and contributors.

  Warning - The configuration file did not pass validation!
  The following problems have been detected:

  Line 21:
  - Element 'directory': This element is not expected. Expected is ( file ).

  Test results may not be as expected.
```
With my long unchanged phpunit.xml. (From standard Laravel 5.6)

```
<filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">./app</directory>
            <exclude>
                <file>./app/Http/routes.php</file>
                <directory>./app/Exceptions</directory>  <-- This is line 21 in my phpunit.xml
                <directory>./app/Providers</directory>
            </exclude>
        </whitelist>
    </filter>
```

Everything works fine, but the warning is quite annoying. So I tried to fix it. I checked if the way to exclude directory was different. Apparently, from the latest doc, it hasn't changed. So I started to mess around with my config. It ended up that moving the nodes around made the warning disappear.

```
<whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">./app</directory>
            <exclude>
                <directory>./app/Exceptions</directory>
                <directory>./app/Providers</directory>
                <file>./app/Http/routes.php</file>
            </exclude>
        </whitelist>
```

I don't really know if this is bug or a validation rule. But as far as I know, usually the order of nodes in an XML file should not be relevant. So I am posting this here to validate if it is a bug or validation rule?

**Comment by theseer** [comment]
That's a bug in the XSD schema file.

XML itself does not have any understanding of order. It's just nodes and children.
But of course depending on how such a structure is process, the order may be relevant. That's why the XSD schema language has <xs:sequence> to enforce a given order.

For this case, the way we use <xs:sequence> though is lacking the information to tell the order is _not_ relevant.

Nice catch!

PR coming up.

**Comment by gsouf** [comment]
@theseer still seeing similar message (`Element 'blacklist': This element is not expected.`) with phpunit 8 and this xml content:

```xml
	<filter>
		<whitelist processUncoveredFilesFromWhitelist="true">
			<directory suffix=".php">./</directory>
		</whitelist>
		<blacklist>
			<directory>./.coverage</directory>
			<directory>./doc</directory>
			<directory>./Tests</directory>
		</blacklist>
	</filter>
```

**Comment by theseer** [comment]
That's correct and expected.

The `<blacklist>` Element has been removed since [PHPUnit 5.0](https://phpunit.de/announcements/phpunit-5.html). You probably want to use `<exclude>` (see https://phpunit.readthedocs.io/en/8.1/configuration.html#whitelisting-files-for-code-coverage).

**Comment by gsouf** [comment]
@theseer I understand, thanks for details and sorry for my ignorance on the subject

**Comment by whatthefrog** [comment]
@lunfel  I got the same warning, and manage to get rid of it by simply wrapping the `phpunit.xml` content with 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit>

</phpunit>
```
