### ISSUE TITLE
Support .phpunit.xml and .phpunit.xml.dist

### ISSUE THREAD

**Issue by GaryJones** [sebastianbergmann/phpunit#3249]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | -
| PHP version         | -
| Installation Method | Composer / PHAR

PHP_CodeSniffer supports config files with leading periods in the name, so that they can be grouped with other "hidden" / system files, such as `.gitignore`, `.editorconfig` `.travis.yml` etc.

The order of preference is:
 - `.phpcs.xml`
 - `phpcs.xml`
 - `.phpcs.xml.dist`
 - `phpcs.xml.dist`

Would it be possible to have the same auto filename support for PHPUnit config files please?

**Comment by sebastianbergmann** [comment]
I do not think that "hiding" configuration files is useful.
