### ISSUE TITLE
Infer data provider's name automatically - with a prefix?

### ISSUE THREAD

**Issue by Netmosfera** [sebastianbergmann/phpunit#3257]
For example, I would like to omit the `/** @dataProvider */` here since the methods' name matches.

```
public function data_bar(){}

/** @dataProvider data_bar */
public function test_bar($v1, $v2){}
```

In other words, if the test method name is `test$n` and a method exist as `data$n`, then phpunit would use it as data provider for `test$n`, unless overridden by the `@dataProvider` annotation.

Would this be feasible?

Thank you in advance.

**Comment by Netmosfera** [comment]
Alternatively, #1093

**Comment by sebastianbergmann** [comment]
Not interested, sorry.
