### ISSUE TITLE
Testing methods that implements interface

### ISSUE THREAD

**Issue by belwase** [sebastianbergmann/phpunit#3261]
I'm working on a Magento2 project. I need to write unit test for a module.
 I've a Quote class as :

    use Magento\Quote\Api\Data\CartInterface;
    class Quote{

       public function __construct(...) {....}
 
       public function get(): CartInterface
        {
          $quote = $this->getFactory()
            ->create()
          ;
        }

My mock code is like :

    $this->quote = $this->createMock(Quote::class);
    $this->quote->method('get')->willReturn($this->quote);

But when I try to  run I get following error:

`TypeError: Return value of Mock_Quote_a73f433b::get() must implement interface Magento\Quote\Api\Data\CartInterface, instance of Mock_Quote_a73f433b returned`

So, any idea on how to mock such methods ?

**Comment by keradus** [comment]
create mock using `$this->prophesize(...)` instead

**Comment by vsouz4** [comment]
Your example is very incomplete, but I'll assume you have this class:

```php
<?php

namespace Some\Namespace;

use Magento\Quote\Api\Data\CartInterface;

class Quote
{
    ...
    public function get(): CartInterface
    {
        ...
    }
}
```

and the class you want to test (since you're mocking the `Quote` class):

```php
<?php

namespace Some\Namespace;

class MyClass
{
    public function handle(Quote $quote)
    {
        $cart = $quote->get();
        // do something with $cart
    }
}
```

the test would be:

```php
<?php

namespace Some\Namespace;

use PHPUnit\Framework\TestCase;

class MyClassTest extends TestCase
{
    private $myClass;

    public function setUp(): void
    {
         $this->myClass = new MyClass();
    }

    public function testHandle(): void
    {
        $quote = $this->createMock(Quote::class);
        $cart = $this->createMock(CartInterface::class);
        $quote
            ->expects(static::once())
            ->method('get')
            ->willReturn($cart);
        // ... $cart->expects ...
        $this->myClass->handle($quote);
    }
}
```

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.
