### ISSUE TITLE
php7 Compatibility problem

### ISSUE THREAD

**Issue by oasfuyou** [sebastianbergmann/phpunit#3262]
vendor/phpunit/phpunit/src/Util/Getopt.php
---------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 3 WARNINGS AFFECTING 3 LINES
---------------------------------------------------------------------------------------------------------
  35 | WARNING | Function each() is deprecated since PHP 7.2; Use a foreach loop instead
  92 | WARNING | Function each() is deprecated since PHP 7.2; Use a foreach loop instead
 137 | WARNING | Function each() is deprecated since PHP 7.2; Use a foreach loop instead

vendor/phpunit/phpunit/src/Util/GlobalState.php

 169 | WARNING | INI directive 'register_long_arrays' is deprecated since PHP 5.3 and removed since PHP 5.4

**Comment by hboomsma** [comment]
@oasfuyou these deprecations have been removed in all currently maintained versions of phpunit. Did you upgrade to one of the supported versions? 

PHPUnit 7 | PHP 7.1, PHP 7.2, PHP 7.3 | February 2, 2018 | Support ends on February 7, 2020
PHPUnit 6 | PHP 7.0, PHP 7.1, PHP 7.2 |	February 3, 2017 | Support ends on February 1, 2019

Taken from phpunit.de
