### ISSUE TITLE
PHP Warning:  Declaration of PHPUnit_Extensions_Selenium2TestCase::onNotSuccessfulTest(Exception $e)

### ISSUE THREAD

**Issue by champseo2017** [sebastianbergmann/phpunit#3269]
C:\xampp\htdocs\test_01>phpunit google_test.php
PHP Warning:  Declaration of PHPUnit_Extensions_Selenium2TestCase::onNotSuccessfulTest(Exception $e) should be compatible with PHPUnit\Framework\TestCase::onNotSuccessfulTest(Throwable $t) in C:\xampp\php\pear\PHPUnit\Extensions\Selenium2TestCase.php on line 208

Warning: Declaration of PHPUnit_Extensions_Selenium2TestCase::onNotSuccessfulTest(Exception $e) should be compatible with PHPUnit\Framework\TestCase::onNotSuccessfulTest(Throwable $t) in C:\xampp\php\pear\PHPUnit\Extensions\Selenium2TestCase.php on line 208
PHPUnit 7.3.2 by Sebastian Bergmann and contributors.

E                                                                   1 / 1 (100%)

Time: 2.6 seconds, Memory: 8.00MB

There was 1 error:

1) Example::testTitle
TypeError: Argument 1 passed to PHPUnit_Extensions_Selenium2TestCase::onNotSuccessfulTest() must be an instance of Exception, instance of ArgumentCountError given, called in phar://C:/xampp/php/phpunit.phar/phpunit/Framework/TestCase.php on line 941

C:\xampp\php\pear\PHPUnit\Extensions\Selenium2TestCase.php:129

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.

Please help me.................................................................................................................................................................
![screenshot_5](https://user-images.githubusercontent.com/32265715/44973598-4782cb80-af87-11e8-997e-01007787485c.png)
![screenshot_6](https://user-images.githubusercontent.com/32265715/44973602-4c477f80-af87-11e8-987a-9fbd3dbc368c.png)

**Comment by sebastianbergmann** [comment]
Please open issues for `PHPUnit_Extensions_Selenium2TestCase` with the correct project.
