### ISSUE TITLE
Reorder tests based on execution time

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#3284]
Thanks to the [caching of test results](https://github.com/sebastianbergmann/phpunit/pull/3147), we know how long it took to execute each test the last time.

It could make sense to reorder tests based on execution time: fast tests first, slow tests last.

@epdenouden What do you think?

**Comment by epdenouden** [comment]
Technically that is super easy, the current sorter will already use the time when it the 'defect severity' is the same.

Personally I have never found a use case for just sorting by time. The quickest tests are always these loooong lists of `@dataprovider` tests for input validation, parsers and minor logic building blocks. These tests all count as _one per data row_ which makes them super fast and you're still stuck with this huge `testMyInputAgainstAllUTFWeirdness` as `@dataprovider`-driven tests become a `DataproviderTestSuite` when running.

But hey, it's a simple thing that might help somebody out IRL. :)
