### ISSUE TITLE
mysql fulltext index support

### ISSUE THREAD

**Issue by kalymnred** [sebastianbergmann/phpunit#3307]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.3.5
| PHP version         | 7.2.7
| Installation Method | Composer 

Greetings, 
I have an application that requires the creation of  fulltext indexes between columns and these indexes are created with a alter table statement. Is there any way to make phpunit working with this types of queries?
I use sqlite_testing in memory.

**Comment by sebastianbergmann** [comment]
PHPUnit has nothing to do with databases.
