### ISSUE TITLE
error_reporting() :: suggestion

### ISSUE THREAD

**Issue by flobee** [sebastianbergmann/phpunit#3308]
| PHPUnit version     | 7.3.5
| PHP version         | 7.2.9-1+0~20180910100512.5+stretch~1.gbpdaac35
| Installation Method | Composer + PHAR + github :)

This is a hint:
i'v seen that error_reporting(-1) exists in the sources. 
When suspress (e.g. pdo warnings) like error_reporting( error_reporting() & ~E_WARNING ); and restore the previous value, followups of test can work with -3 as reporting level for example.
```php -r 'error_reporting(-1); echo error_reporting(); error_reporting( -1 & ~E_WARNING );echo error_reporting();'; // -3```

I think phpunit should give a warning that this can give very strange side effects when using -1 and not E_ALL

Kind regards

**Comment by sebastianbergmann** [comment]
`-1` includes everything. There is no point in doing something like `-1 & ~E_WARNING`.
