### ISSUE TITLE
Testing exceptions using callables

### ISSUE THREAD

**Issue by mschop** [sebastianbergmann/phpunit#3313]
Hi,

this is a feature request regarding testing exceptions.

I often have the case, where I would like to test multiple simple Exceptions. I would find it much better if I would not have to create a new test class method for every exception I am testing. Instead it would be nice, if I could pass a callable to an assertion that gets called by phpunit and if this callable throws an Exception, the further execution of the test method could execute further assertions.

I would like to reduce this code:

```
class SomeTest extends \PHPUnit\Framework\TestCase
{
    public function test_1()
    {
        $obj = new MyClass();
        // do some initialization stuff
        $this->expectedException(ValueTooLowException::class);
        $obj->setX(10);
    }

    public function test_2()
    {
        $obj = new MyClass();
        // do some initialization stuff
        $this->expectedException(ValueTooHighException::class);
        $obj->setX(100);
    }

    public function test_3()
    {
        $obj = new MyClass();
        // do some initialization stuff
        $this->expectedException(\InvalidArgumentException::class);
        $obj->setX("Hello World");
    }
}
```

To this code:

```
class SomeTest extends \PHPUnit\Framework\TestCase
{
    public function test_boundaries()
    {
        $obj = new MyClass();

        // do some initialization stuff

        $this->assertException(ValueTooLowException::class, function() use ($obj) {
            $obj->setX(10);
        });
        $this->assertException(ValueTooHighException::class, function() use ($obj) {
            $obj->setX(100);
        });
        $this->assertException(\InvalidArgumentException::class, function() use ($obj) {
            $obj->setX("Hello World");
        });
    }
}
```

This would be 100% compatible with the current solution but would provide a more functional approach to this problem.
I would prefer this way of testing a lot.

Thanks right now for your feedback!

Best Regards
mschop

**Comment by mschop** [comment]
Well something I forgot to mention. It would enable easier clean up, if a test e.g. created a file.

```
public function test_something()
{
    file_put_contents('test.txt', 'Hello World');
    $this->assertException(function() { ... });
    unlink('test.txt');
}
```

**Comment by mschop** [comment]
@sebastianbergmann I would like to keep the discussion open. Your only argument in the article against this approach is "a test should only test one thing". I partially agree on that, but sometimes this is just impractical. E.g. when testing some disallowed function parameter values, this leads to unnecessary verbose code.

The second argument for such approach is the ease of clean up. Yes, you can use post function to clean up. But if you have three different test functions in the TestCase, this gets really ugly to program.

People use tools different than intended by the developer. I would strongly prefer this approach. I think there are many developers, who would like this, too. I can implement it by myself and send you a PR if there is any chance, that you will merge the PR.

**Comment by keradus** [comment]
your test methods looks almost the same - logic is the same, while data are different (different input for `setX`, different expectation class) - write your test as single method yet with data provider that provides 3 cases.

**Comment by EtienneBruines** [comment]
To continue this discussing, and the point @keradus raised:

This way you're basically using the `result` parameter for a place you can also put `Exception` classes. Which makes somewhat sense, since it is the result you're looking for. 

```php
	/**
	 * @dataProvider additionProvider
	 *
	 * @param int $a
	 * @param int $b
	 * @param int|Exception $result
	 */
	public function testAdditions($a, $b, $result)
	{
		if (is_subclass_of($result, Exception::class))
		{
			$this->expectException($result);
		}
		
		static::assertEquals($result, $this->add($a, $b));
	}

	public function additionProvider()
	{
		return [
			'adding zeros' => [0, 0, 0],
			'adding strings' => ['', 0, InvalidArgumentException::class]
		];
	}
```

Alternatively, a forth parameter could be used to indicate the exception:

```php
	/**
	 * @dataProvider additionProvider
	 *
	 * @param int       $a
	 * @param int       $b
	 * @param int       $result
	 * @param Exception $exception
	 */
	public function testAdditions($a, $b, $result, $exception = null)
	{
		
		if (is_subclass_of($exception, Exception::class))
		{
			$this->expectException($exception);
		}
		
		static::assertEquals($result, $this->add($a, $b));
	}
	
	public function additionProvider()
	{
		return [
			'adding zeros'   => [0, 0, 0],
			'adding strings' => ['', 0, null, InvalidArgumentException::class]
		];
	}
```

This way you have a clearer separation of results and exceptions, but do have more `null`.

**Comment by mschop** [comment]
@EtienneBruines Ok. That solution makes sense. Even if I would still prefer the callable approach ;-) your solution makes abolutely sense.

Thanks you!

**Comment by keradus** [comment]
I am writing one with separated `$expectedResult` and `\Exception? $expectedException` indeed
