### ISSUE TITLE
how to skip from specific code in original code

### ISSUE THREAD

**Issue by ilya33000** [sebastianbergmann/phpunit#3318]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 5.7.27
| PHP version         | 5.6.14
| Installation Method | Composer / PHAR

Hi Mr Sebastian
I'm beginner in PHPUnit. 
I have this code for substr function for test:
/**
if ($start >= $strlen) {
    $result = '';
} 
else if (function_exists('mb_substr')) {
    mb_internal_encoding("UTF-8");
    $result = mb_substr($str, $start, ($length === NULL ? NULL : ($length - $break_strlen)));
} 
else {
    if ($length === NULL) {
        $length = '*';
    } else {
        $length = '{' . ($length - $break_strlen) . '}';
    }

    preg_match('/^.{' . $start . '}(.' . $length . ')/us', $str, $matches);

    if (isset($matches[1])) {
        $result = $matches[1];
    }
**/
and i tested code in PHPUnit with for example this code:
/**
self::assertEquals('aj-', \Virtu\Text::substr('Majid',1,3,'-'));
self::assertEquals('Maj-', \Virtu\Text::substr('Majid',0,4,'-'));
self::assertEquals('مج-', \Virtu\Text::substr('مجید',0,3,'-'));
self::assertEquals('داو-', \Virtu\Text::substr('داوود',0,4,'-'));
**/

this test function will test the code with mb_sustr function if exists.
I want to know how can I skip from this if(even if, function mb_substr is exists)
and test else block. in fact I want to test all conditions in this 
code.
best regards.

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.
