### ISSUE TITLE
Make ExceptionMessage constraint strict

### ISSUE THREAD

**Issue by keradus** [sebastianbergmann/phpunit#3325]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | ?
| PHP version         | not related
| Installation Method | not related

Heavily descried in:
https://github.com/sebastianbergmann/phpunit/pull/3309#discussion_r219665621

`Constraint\ExceptionMessage`, used under the hood by `expectExceptionMessage` and `@expectedExceptionMessage` is not strict about expected message.

Constraint does not check if expected message is same as actual one, but only if it's somewhere present in actual one.
Making those two calls equivalent:
```
$this->expectExceptionMessage('variadic');
$this->expectExceptionMessageRegExp('/^.*variadic.*$/');
```

Which is not obvious for developer and actually most of them are not aware about this.

I would like to change behaviour of Constraint to use `===` comparison instead of `strpos`.

For me, personally, it's a bug, yet I can understood that requested change may be considered as bigger one and treated as BC breaker.

If this request will be approved, I'm all in implementing this change myself - either to lowest supported branch, if this would be treated as a bugfix, or later for 8.0 branch (which is not yet existing).

Thanks !

**Comment by keradus** [comment]
fyi @TomasVotruba

**Comment by sebastianbergmann** [comment]
I would consider this a bugfix, too, and would appreciate a pull request for `6.5` (which will be merged to `7.4` and `master`).

**Comment by pscheit** [comment]
My 2 cents: this makes the (already screwed up) exception api so much more worse... 
now I have to write a regexp for every "contains" check of my exception message?
Why would I want to test thee FULL assertion message in exceptions? Someone corrects a typo and the tests will fail.

at least add something like: 
expectedExceptionMessageContains() or s.th.

**Comment by pscheit** [comment]
imho this is a BC break and must not go to branch 6.5.x-dev right?

**Comment by pscheit** [comment]
I don't want to use annotations and still: i need to write a regexp for "contains". I'm just saying: this issue will decrease developer experience

**Comment by TomasVotruba** [comment]
I don't use annotations neither, as they're [not recommended](https://thephp.cc/news/2016/02/questioning-phpunit-best-practices).

There is method:

```php
public function test()
{
    $this->expectExceptionMessageRegExp('...');
    // ...
}
```

But still I prefer specific 100% exception match. Otherwise it has no value to test that exception contains some text.

**Comment by sebastianbergmann** [comment]
I have reverted the change(s) in the `6.5` branch.

**Comment by keradus** [comment]
`stale`, go away
request for `Constraint\ExceptionMessage` is still valid

**Comment by epdenouden** [comment]
And stale bread is still good for croutons or bread pudding :D

**Comment by sebastianbergmann** [comment]
As I wrote in https://github.com/sebastianbergmann/phpunit/issues/3325#issuecomment-428501525, support for expecting exceptions through annotations will be removed in PHPUnit 9 (see #3332 and #3333). I am not sure how to properly address this before the annotation is issue is gone.
