### ISSUE TITLE
Specializations of assertEquals() and assertNotEquals()

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#3340]
Implement the following methods

* `assertEqualsCanonicalizing()`
* `assertEqualsIgnoringCase()`
* `assertEqualsWithDelta()`
* `assertNotEqualsCanonicalizing()`
* `assertNotEqualsIgnoringCase()`
* `assertNotEqualsWithDelta()`

to replace the respective optional parameters for `assertEquals()` and `assertNotEquals()`.

**Comment by stof** [comment]
What about combinations of this flags:

- asserting that 2 arrays contains the same case-insensitive values without a constraint on the order (canonicalize + ignore case)
- asserting that 2 arrays contains the same floats (with delta) without a constraint on the order (canonicalize + delta) 

The new methods don't account for all combinations of it (and the comparator library still has them as optional parameters AFAICT, so these combinations would still be supported by the lower-level code, unless the goal is to change these APIs too)
