### ISSUE TITLE
Deprecate optional parameters of assertEquals() and assertNotEquals()

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#3341]
These optional parameters of `assertEquals()` and `assertNotEquals()` should be deprecated:

* `$delta` (use `assertEqualsWithDelta()` or `assertNotEqualsWithDelta()` from #3340 instead)
* `$maxDepth` (respective functionality was removed)
* `$canonicalize` (use `assertEqualsCanonicalizing()` or `assertNotEqualsCanonicalizing()` from #3340 instead)
* `$ignoreCase` (use `assertEqualsIgnoringCase()` or `assertNotEqualsIgnoringCase()` from #3340 instead)

**Comment by TomasVotruba** [comment]
Anyone looking for upgrade path: https://github.com/rectorphp/rector/pull/825/files#diff-de1172102c1d09f6d2910b0571e5f546
