### ISSUE TITLE
$mock->expects->at(0)->method('methodName') is green, event if the method name is different

### ISSUE THREAD

**Issue by dominikzogg** [sebastianbergmann/phpunit#3345]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.1.5
| PHP version         | 7.2.10
| Installation Method | Composer

I've build a mock helper on top of phpunit mock. To test as strict as possible i work with ->at(). The tests are green even if i put the wrong method name as long there is a at() exists.

https://github.com/chubbyphp/chubbyphp-mock/blob/master/src/MockByCallsTrait.php#L31

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by dominikzogg** [comment]
@sebastianbergmann with a simple example i cannot reproduce it, it seems it depends on the mocked class, the original test mocks the symfony ContainerBuilder

```php
<?php

use PHPUnit\Framework\TestCase;

class BlaTest extends TestCase
{
    public function testBla()
    {
        $mock = $this->getMockBuilder(Bla::class)
            ->disableOriginalConstructor()
            ->disableOriginalClone()
            ->getMock();

        $mock->expects(self::at(0))->method('methodB')->with('test')->willReturn('');

        $mock->methodA('test');
    }
}

class Bla
{
    /**
     * @param string $argument1
     * @return string
     */
    public function methodA(string $argument1): string
    {
        return $argument1;
    }

    /**
     * @param string $argument2
     * @return string
     */
    public function methodB(string $argument2): string
    {
        return $argument2;
    }
}
```

**Comment by dominikzogg** [comment]
@sebastianbergmann got a example that breaks, as explained

```php
<?php

use PHPUnit\Framework\TestCase;
use Symfony\Component\Config\FileLocator;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Loader;
use Symfony\Component\HttpKernel\DependencyInjection\Extension;

class MyExtensionTest extends TestCase
{
    public function testLoad()
    {
        $containerBuilder = $this->getMockBuilder(ContainerBuilder::class)
            ->disableOriginalConstructor()
            ->disableOriginalClone()
            ->getMock();

        $containerBuilder->expects(self::at(0))->method('fileExists');
        $containerBuilder->expects(self::at(1))->method('hasDefinition'); // should be setDefintion

        $extension = new MyExtension();
        $extension->load([], $containerBuilder);
    }
}

class MyExtension extends Extension
{

    /**
     * @param array            $config
     * @param ContainerBuilder $container
     * @return void
     */
    public function load(array $config, ContainerBuilder $container): void
    {
        $loader = new Loader\XmlFileLoader($container, new FileLocator(__DIR__));
        $loader->load('services.xml');
    }
}
```

**Comment by sebastianbergmann** [comment]
Then I cannot help you, sorry.

**Comment by sebastianbergmann** [comment]
That is not minimal and self-contained, sorry.

**Comment by dominikzogg** [comment]
@sebastianbergmann if i replace self::at(0) with self::once(), self::at(1) with self::once() it behaves as expected, so this problem only apears with at()

**Comment by dominikzogg** [comment]
@nicolas-grekas do you have an idea, why mocking the ContainerBuilder leads to this issue?
@sebastianbergmann have this issue not the first time (also mocking other objects), but can't remember and example, so i try to find other ones to find similarities
