### ISSUE TITLE
Requesting less than 16 columns of output results in an error

### ISSUE THREAD

**Issue by marcelloh** [sebastianbergmann/phpunit#3353]
I was looking for a way to skip the process info, and only deal with the end information about failing tests, so Isaw the columns param for the command-line.

When set to zero, it brakes :-(

(btw:: is there a possibility to skip the dots and percentage parts of the output?)

| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.4.0
| PHP version         | 7.2.11
| Installation Method | Composer

**Comment by sebastianbergmann** [comment]
No, there is no way to skip the dots and percentage parts of the output.
