### ISSUE TITLE
Constraints as own package

### ISSUE THREAD

**Issue by ScreamingDev** [sebastianbergmann/phpunit#3363]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | I am here since ~4
| PHP version         | 6
| Installation Method | yes

The constraints like "IsEqual" or "StringMatches" are so great for using them in other projects. Right now I would have the need to write configurations using those classes like

```
return [
  'foo' => new LogicalOr(new IsTrue(), new RegularExpression()),
  'id' => new IsUuid(),
]
```

And even extend them like the IsUuid above is just a regular expression.

Right now it needs the whole phpunit with all dependencies and this is a bit much for having just the comparison and well formed sentences (::toString) for error messages etc.

**Comment by sebastianbergmann** [comment]
This was attempted in the past and abandoned because it is not worth the effort.

**Comment by ScreamingDev** [comment]
Ok. I extract this then and put it on packagist.org even if I could be the only one using it ^^
