### ISSUE TITLE
Want Util::registerGlobalFunctions() like Hamcrest has

### ISSUE THREAD

**Issue by lathspell** [sebastianbergmann/phpunit#3365]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 5.7.27
| PHP version         | 7.0.30
| Installation Method | Composer 

I like to use the short global function syntax like "assertNull()" without "self::" so I have to write ` require_once __DIR__ . '/../../../../vendor/phpunit/phpunit/src/Framework/Assert/Functions.php';` which looks ugly and breaks whenever I move the bootstrap.php file.

Can we get a \Phpunit\Framwork\Assert::registerGlobalFunctions(); like hamcrest-php has? It would just consist of a `require __DIR__ . '/Functions.php';`.

**Comment by keradus** [comment]
:-1:

please don't make it easy to pollute global php namespace

**Comment by sebastianbergmann** [comment]
No.
