### ISSUE TITLE
MySQL bit(1) inserts nothing for Database test using YAML Dataset

### ISSUE THREAD

**Issue by Chad-Krause2** [sebastianbergmann/phpunit#3366]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.0.0
| PHP version         | 7.1
| Installation Method | Composer 

When I go to test my models, I have mock rows stored as a YAML file. I insert the rows using the built in GetDataSet() function from TestCase class. I have some columns (such as enabled or confirmed) that are booleans (bit(1)). The unit tests fail because the database will throw an error when the column is not nullable. Setting it to nullable allows the tests to continue, but they fail because the column gets set to null.

doctrine/instantiator              1.1.0  A small, lightweight utility to instantiate objects in PHP without invoking their constructors
firebase/php-jwt                   v5.0.0 A simple library to encode and decode JSON Web Tokens (JWT) in PHP. Should conform to the current spec.
myclabs/deep-copy                  1.8.1  Create deep copies (clones) of your objects
phar-io/manifest                   1.0.1  Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                    1.0.1  Library for handling version information and constraints
phpdocumentor/reflection-common    1.0.1  Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock  4.3.0  With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver        0.4.0 
phpspec/prophecy                   1.7.6  Highly opinionated mocking framework for PHP 5.3+
phpunit/dbunit                     4.0.0  PHPUnit extension for database interaction testing
phpunit/php-code-coverage          6.0.5  Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator          1.4.5  FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template          1.2.1  Simple template engine.
phpunit/php-timer                  2.0.0  Utility class for timing
phpunit/php-token-stream           3.0.0  Wrapper around PHP's tokenizer extension.
phpunit/phpunit                    7.0.0  The PHP Unit Testing framework.
phpunit/phpunit-mock-objects       6.1.2  Mock Object library for PHPUnit
sebastian/code-unit-reverse-lookup 1.0.1  Looks up which function or method a line of code belongs to
sebastian/comparator               2.1.3  Provides the functionality to compare PHP values for equality
sebastian/diff                     3.0.1  Diff implementation
sebastian/environment              3.1.0  Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 3.1.0  Provides the functionality to export PHP variables for visualization
sebastian/global-state             2.0.0  Snapshotting of global state
sebastian/object-enumerator        3.0.3  Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector         1.1.1  Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context        3.0.0  Provides functionality to recursively process PHP variables
sebastian/resource-operations      1.0.0  Provides a list of PHP built-in functions that operate on resources
sebastian/version                  2.0.1  Library that helps with managing the version number of Git-hosted PHP projects
symfony/polyfill-ctype             v1.8.0 Symfony polyfill for ctype functions
symfony/yaml                       v4.1.1 Symfony Yaml Component
theseer/tokenizer                  1.1.0  A small library for converting tokenized PHP source code into XML and potentially other formats
webmozart/assert                   1.3.0  Assertions to validate method input/output with nice error messages.

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/.github/CONTRIBUTING.md#reporting-issues) have been reported on the [dbunit](https://github.com/sebastianbergmann/dbunit) project.

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another.
