### ISSUE TITLE
Annotation @runTestsInSeparateProcesses makes false positives

### ISSUE THREAD

**Issue by drugs-4-3** [sebastianbergmann/phpunit#3367]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.4.3
| PHP version         | 7.2.9
| Installation Method | PHAR

https://stackoverflow.com/questions/52965511/phpunit-false-positives-when-running-tests-in-separate-processes

```
/**
 * @runTestsInSeparateProcesses
 */
class ProfileTest extends TestCase
{
    public function testFalsePositive()
    {
        $this->assertFalse(true);
    }
}
```

In short: thiscode returns all tests passed, when there is annotation @runTestsInSeparateProcesses.
Without the annotation, test correctly fails. 
Checked in PHPUnit v.5, with or without annotation, tests fail.

**Comment by drugs-4-3** [comment]
Well, that is strange. 

```
$ cat ProfileTest.php 
<?php declare(strict_types=1);

use \PHPUnit\Framework\TestCase;

/**
 * @runTestsInSeparateProcesses
 */
class ProfileTest extends TestCase
{
    public function testFalsePositive()
    {
        $this->assertFalse(true);
    }
}
```
```
$ phpunit ProfileTest.php 
PHPUnit 7.4.3 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 152 ms, Memory: 10.00MB

OK (1 test, 0 assertions)

```

**Comment by sebastianbergmann** [comment]
Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting and include how you install and invoke PHPUnit.

Without this information I will not be able to investigate this issue further.

**Comment by williamdes** [comment]
@sebastianbergmann 
```php
<?php

use PHPUnit\Framework\TestCase;

class crashTest extends TestCase
{

        //public function testThatTrueIsStillTrue(): void {
        //      $this->assertTrue(true);
        //}

        /**
          * @runInSeparateProcess
          */
        public function testThatTrueIsStillTrueInSepProcess(): void {
                exit(1);
        }

        //public function testThatTrueIsStillTrueExited(): void {
        //        exit(1);
        //}
}
```

### Output
```
PHPUnit 6.5.5 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 85 ms, Memory: 4.00MB

OK (1 test, 0 assertions)
```

Everthing is NOT okay

**Comment by milhomem** [comment]
I'm facing the same issue, and I find out that my bootstrap file is causing issues.
```
<phpunit
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://schema.phpunit.de/3.7/phpunit.xsd"
        bootstrap="src/Tests/bootstrap.php"
        convertErrorsToExceptions="true"
        convertNoticesToExceptions="true"
        convertWarningsToExceptions="true"
        stopOnError="true"
        colors="true">
```
@drugs-4-3 are you using a custom bootstrap too?

I didn't get to the bottom of it yet, but I can see that my bootstrap file is required twice when running on a separated process.

I'll make a case and post another issue. Once I get rid of this bootstrap noise, I will update this issue if my issue persists.

**Comment by williamdes** [comment]
@sebastianbergmann can you please have a look at my comment?

**Comment by sebastianbergmann** [comment]
Can you reproduce the issue with a version of PHPUnit that is still supported?

**Comment by williamdes** [comment]
@sebastianbergmann Reproduced using phpunit `8.0.2` (latest)

**Comment by epdenouden** [comment]
Still not stale, dear bot. Currently trying to get on-demand dataproviders to work

**Comment by williamdes** [comment]
Hi @sebastianbergmann 
Did my example help reproducing ?
See: https://github.com/sebastianbergmann/phpunit/issues/3367#issuecomment-445218837
