### ISSUE TITLE
Implement specialized alternatives to assertInternalType() and assertNotInternalType()

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#3368]
Implement
* `assertIsArray()`
* `assertIsBool()`
* `assertIsFloat()`
* `assertIsInt()`
* `assertIsNumeric()`
* `assertIsObject()`
* `assertIsResource()`
* `assertIsString()`
* `assertIsScalar()`
* `assertIsCallable()`
* `assertIsIterable()`
* `assertIsNotArray()`
* `assertIsNotBool()`
* `assertIsNotFloat()`
* `assertIsNotInt()`
* `assertIsNotNumeric()`
* `assertIsNotObject()`
* `assertIsNotResource()`
* `assertIsNotString()`
* `assertIsNotScalar()`
* `assertIsNotCallable()`
* `assertIsNotIterable()`

**Comment by TomasVotruba** [comment]
What will happen to same checks just for arrays?

```php
$this->assertContainsOnly('string', $types);
```

**Comment by glensc** [comment]
what phpunit min version has the new assertions?

**Comment by sebastianbergmann** [comment]
These assertions were implemented for PHPUnit 7.5.

**Comment by glensc** [comment]
what's the replacement for such code:

```php
        $this->assertInternalType(gettype($algo), $res['algo']);
```

**Comment by nelson6e65** [comment]
> what's the replacement for such code:
> 
> ```
>         $this->assertInternalType(gettype($algo), $res['algo']);
> ```


 @glensc Maybe... 
```php
$assertIsType = 'assertIs'.gettype($algo);

$this->$assertIsType($res['algo']);
```

But... if you need this dynamic, you may need a redesign of the test. :sweat_smile:

**Comment by JeroenDeDauw** [comment]
Is there a way to make these available in PHPUnit 6?

I'd be tempted to reply to my own question with "just use a modern version of PHPUnit", so here some background of why this change sucks for me. I maintain a number of MediaWiki extensions. The development version of MediaWiki uses PHPUnit 8, so no problems there. However the latest LTS uses PHPUnit 6. Which means I cannot use the new assertion methods introduced in PHPUnit 7.5. So I'm forced to either write instant legacy assertions and live with a pile of warnings, or to drop testing against a very relevant version of MediaWiki from the CI.

**Comment by nelson6e65** [comment]
> Is there a way to make these available in PHPUnit 6?
> 
> I'd be tempted to reply to my own question with "just use a modern version of PHPUnit", so here some background of why this change sucks for me. I maintain a number of MediaWiki extensions. The development version of MediaWiki uses PHPUnit 8, so no problems there. However the latest LTS uses PHPUnit 6. Which means I cannot use the new assertion methods introduced in PHPUnit 7.5. So I'm forced to either write instant legacy assertions and live with a pile of warnings, or to drop testing against a very relevant version of MediaWiki from the CI.

Well... there is the changes in https://github.com/sebastianbergmann/phpunit/commit/a406c85c51edd76ace29119179d8c21f590c939e#diff-9ae7a972d07df5f73629d5d315bf405a

Yo can create a `trait` with that methods and try to `use` it in your tests classes.

**Comment by JeroenDeDauw** [comment]
Yes, I could copy these methods into my project. I asked here in the hope there already is a package that provides a copy.

**Comment by joelmellon** [comment]
> what's the replacement for such code:
> 
> ```
>         $this->assertInternalType(gettype($algo), $res['algo']);
> ```

```
	$this->assertEquals(gettype($algo), gettype($res['algo']));
```
