### ISSUE TITLE
@runInSeparateProcess and generated coverage HTML issue

### ISSUE THREAD

**Issue by csisy** [sebastianbergmann/phpunit#3371]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.4.3
| PHP version         | 7.2.3
| Installation Method | PHAR

The generated coverage HTML does not count the tests ran in separate process.
If I remove the @runInSeparateProcess annotation, then the coverage HTML result is updated properly (however the test itself fails because the framework printed some output before the headers are sent - this is why I'm using the @runInSeparateProcess annotation)

The phpunit.xml file:

    <?xml version="1.0" encoding="UTF-8"?>
    <phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/5.2/phpunit.xsd"
             bootstrap="vendor/autoload.php"
             backupGlobals="false"
             backupStaticAttributes="false"
             beStrictAboutCoversAnnotation="true"
             beStrictAboutOutputDuringTests="true"
             beStrictAboutTestsThatDoNotTestAnything="false"
             beStrictAboutTodoAnnotatedTests="true"
             forceCoversAnnotation="true"
             verbose="true">
        <testsuite name="HTTP">
            <directory suffix="Test.php">tests</directory>
        </testsuite>
        <logging>
            <log type="coverage-html" target="build/log/coverage"/>
            <log type="testdox-html" target="build/log/unit_tests.html"/>
        </logging>
        <filter>
            <whitelist processUncoveredFilesFromWhitelist="true">
                <directory suffix=".php">src</directory>
            </whitelist>
        </filter>
    </phpunit>

I'm using a separate process because I want to test header() calls. Here is the simple test function:

    /**
     * @runInSeparateProcess
     * @covers Vendor\Http\Response
     */
    public function testHeadersSentAndOnlyOnce(): void
    {
        $r = new Response('');

        $r->setHeader('foo', 'bar');
        $r->setHeader('foo', 'baz');
        $r->setHeader('bar', 'baz');
        $r->unsetHeader('bar');
        $r->sendHeaders();
        $r->send();

        $headers = xdebug_get_headers();

        $this->assertEquals(2, count($headers));
        $this->assertEquals('Content-type: text/html; charset=UTF-8', $headers[0]);
        $this->assertEquals('foo: baz', $headers[1]);
    }

The command line:

    $ php build/phpunit-7.4.3.phar
    PHPUnit 7.4.3 by Sebastian Bergmann and contributors.

    Runtime:       PHP 7.2.3 with Xdebug 2.6.0
    Configuration: [...]\Http\phpunit.xml

    .............                                                     13 / 13 (100%)

    Time: 1.32 seconds, Memory: 12.00MB

    OK (13 tests, 32 assertions)

    Generating code coverage report in HTML format ... done

In the meantime the generated coverage HTML does not reflect the sendHeaders() and send() function calls.

[![coverage.png](https://i.postimg.cc/1Xk0VhbW/coverage.png)](https://postimg.cc/PvMv0cXZ)

**Comment by csisy** [comment]
Made a sample project to easily reproduce the issue. Usage:

    - unzip
    - run "composer update"
    - run "php phpunit-7.4.3.phar"
    - check log/unit_tests.html
    - check log/coverage/index.html

[test.zip](https://github.com/sebastianbergmann/phpunit/files/2519397/test.zip)

**Comment by csisy** [comment]
Cannot be reproduced by Composer install.

**Comment by s3b4stian** [comment]
Same issue, with phar, test count works, assertions not.

OK (676 tests, 1174 assertions) with PHAR.
OK (676 tests, 1337 assertions) with PhpUnit composer installation.


```
sebastian@ubuntuvirtual18:~/html/framework$ phpunit
PHPUnit 7.4.3 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.2.12-1+ubuntu18.04.1+deb.sury.org+1 with Xdebug 2.6.1
Configuration: /home/sebastian/html/framework/phpunit.xml

...............................................................  63 / 676 (  9%)
............................................................... 126 / 676 ( 18%)
............................................................... 189 / 676 ( 27%)
............................................................... 252 / 676 ( 37%)
............................................................... 315 / 676 ( 46%)
............................................................... 378 / 676 ( 55%)
............................................................... 441 / 676 ( 65%)
............................................................... 504 / 676 ( 74%)
............................................................... 567 / 676 ( 83%)
............................................................... 630 / 676 ( 93%)
..............................................                  676 / 676 (100%)

Time: 1.02 minutes, Memory: 24.00MB

OK (676 tests, 1174 assertions)

Generating code coverage report in Clover XML format ... done
sebastian@ubuntuvirtual18:~/html/framework$ ./vendor/bin/phpunit
PHPUnit 7.4.3 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.2.12-1+ubuntu18.04.1+deb.sury.org+1 with Xdebug 2.6.1
Configuration: /home/sebastian/html/framework/phpunit.xml

...............................................................  63 / 676 (  9%)
............................................................... 126 / 676 ( 18%)
............................................................... 189 / 676 ( 27%)
............................................................... 252 / 676 ( 37%)
............................................................... 315 / 676 ( 46%)
............................................................... 378 / 676 ( 55%)
............................................................... 441 / 676 ( 65%)
............................................................... 504 / 676 ( 74%)
............................................................... 567 / 676 ( 83%)
............................................................... 630 / 676 ( 93%)
..............................................                  676 / 676 (100%)

Time: 56.45 seconds, Memory: 16.00MB

OK (676 tests, 1337 assertions)

Generating code coverage report in Clover XML format ... done
sebastian@ubuntuvirtual18:~/html/framework$
```

**Comment by sebastianbergmann** [comment]
Does the problem still exist in PHPUnit 7.4.4?

**Comment by csisy** [comment]
> Does the problem still exist in PHPUnit 7.4.4?

No, it seems that the problem is solved, thank you!

Two minor things:
- it takes a bit longer to run the separated test (it's totally fine)
- the html is changed from a narrow centered view to a full-width view (this might be intentional)

**Comment by s3b4stian** [comment]
With 7.4.4, it works!

```
sebastian@ubuntuvirtual18:~/html/framework$ phpunit
PHPUnit 7.4.4 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.2.12-1+ubuntu18.04.1+deb.sury.org+1 with Xdebug 2.6.1
Configuration: /home/sebastian/html/framework/phpunit.xml

...............................................................  63 / 676 (  9%)
............................................................... 126 / 676 ( 18%)
............................................................... 189 / 676 ( 27%)
............................................................... 252 / 676 ( 37%)
............................................................... 315 / 676 ( 46%)
............................................................... 378 / 676 ( 55%)
............................................................... 441 / 676 ( 65%)
............................................................... 504 / 676 ( 74%)
............................................................... 567 / 676 ( 83%)
............................................................... 630 / 676 ( 93%)
..............................................                  676 / 676 (100%)

Time: 1.35 minutes, Memory: 24.00MB

OK (676 tests, 1337 assertions)

Generating code coverage report in Clover XML format ... done
sebastian@ubuntuvirtual18:~/html/framework$ ./vendor/bin/phpunit
PHPUnit 7.4.4 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.2.12-1+ubuntu18.04.1+deb.sury.org+1 with Xdebug 2.6.1
Configuration: /home/sebastian/html/framework/phpunit.xml

...............................................................  63 / 676 (  9%)
............................................................... 126 / 676 ( 18%)
............................................................... 189 / 676 ( 27%)
............................................................... 252 / 676 ( 37%)
............................................................... 315 / 676 ( 46%)
............................................................... 378 / 676 ( 55%)
............................................................... 441 / 676 ( 65%)
............................................................... 504 / 676 ( 74%)
............................................................... 567 / 676 ( 83%)
............................................................... 630 / 676 ( 93%)
..............................................                  676 / 676 (100%)

Time: 51.63 seconds, Memory: 16.00MB

OK (676 tests, 1337 assertions)

Generating code coverage report in Clover XML format ... done
sebastian@ubuntuvirtual18:~/html/framework$
```
