### ISSUE TITLE
CodeCeption not working in PhpStorm

### ISSUE THREAD

**Issue by DBX12** [sebastianbergmann/phpunit#3385]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.1.x-dev (67289aa)
| PHP version         | 7.2.11
| Installation Method | Composer

As listed [here](https://github.com/justcoded/yii2-starter/issues/25) and [here](https://github.com/Codeception/Codeception/issues/4476) a bug prevents phpunit being used with codeception in PhpStorm. A simple fix by @yujin1st fixes this bug. I'm not sure how phpunit works internally, but I thought fixing this here would be good. A PR is on the way.

**Comment by sebastianbergmann** [comment]
Looking at https://github.com/Codeception/Codeception/issues/4476#issuecomment-368946638, I do not think that this workaround should be added to PHPUnit. This issue needs to be addressed either in Codeception or PhpStorm.
