### ISSUE TITLE
Add a Hook that fires after each test, regardless of result

### ISSUE THREAD

**Issue by rpkamp** [sebastianbergmann/phpunit#3391]
I currently have a TestListener that resets a service after each has run. This must be done regardless of the result of the test.

With the TestListener this is easy, implement `TestListener::endTest()` and done. However, with the new extension system no such hook exists and it seems I'd need to implement `AfterIncompleteTestHook`, `AfterRiskyTestHook`, `AfterSkippedTestHook`, `AfterTestErrorHook`, `AfterSuccessfulTestHook`, `AfterTestFailureHook` and `AfterTestWarningHook`. All with the same function body. That seems a bit overkill.

Is there another way to do this with an extension currently? If not, would you mind a PR that adds such a Hook?

**Comment by sebastianbergmann** [comment]
I would not mind a pull request that adds an `AfterTestHook`.

**Comment by maples3** [comment]
For anyone reading this in the future, as of PhpUnit 11 this is now done by writing an extension (implementing `PHPUnit\Runner\Extension\Extension`) to register a class that implements `PHPUnit\Event\Test\FinishedSubscriber`.
