### ISSUE TITLE
Process Isolation does not work when PHPUnit is used as PHAR

### ISSUE THREAD

**Issue by bugreportuser** [sebastianbergmann/phpunit#3394]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.4.3
| PHP version         | 7.2.10
| Installation Method | PHAR

This is related to https://github.com/sebastianbergmann/phpunit/issues/3367 and https://github.com/sebastianbergmann/phpunit/issues/3306.

When `--process-isolation` is added, no assertions run using the PHAR. If composer is used, the output is correct with or without process isolation.

Class isolation has the same output because of https://github.com/sebastianbergmann/phpunit/issues/3258.

FailTest.php:

```php
<?php
class FailTest extends PHPUnit\Framework\TestCase {
    public function testFail () {
        $this->assertTrue(false);
    }
}
```

No process isolation:
```
$ ./phpunit FailTest.php
PHPUnit 7.4.3 by Sebastian Bergmann and contributors.

F                                                                   1 / 1 (100%)

Time: 52 ms, Memory: 10.00MB

There was 1 failure:

1) FailTest::testFail
Failed asserting that false is true.

/home/.../phpunit/FailTest.php:4

FAILURES!
Tests: 1, Assertions: 1, Failures: 1.
```

Process isolation:
```
$ ./phpunit FailTest.php --process-isolation
PHPUnit 7.4.3 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 123 ms, Memory: 10.00MB

OK (1 test, 0 assertions)
```

**Comment by sebastianbergmann** [comment]
I was able to reproduce the issue.
