### ISSUE TITLE
Test that a set_exception_handler actually works

### ISSUE THREAD

**Issue by TiMESPLiNTER** [sebastianbergmann/phpunit#3395]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.4.3
| PHP version         | 7.2
| Installation Method | Composer

A simplified code sample to demonstrate the "problem":

```php
class Test extends TestCase
{
    public function testExceptionHandler()
    {
        $value = null;
        $exception = new \Exception('foo');

        set_exception_handler(function (\Throwable $e) use (&value) {
            $value = $e;
        });

        self::assertNull($value);

        throw $exception;

        self::assertSame($exception, $value);
    }
}
```

This will output:

> 1) Test::testExceptionHandler
> Exception: foo

I guess it's because PHPUnit wraps each test method call in a `try/catch` block and the exception gets handled there and never reaches my exception handler.

Is there any chance to test the code above. What would be the right approach to test it?

**Comment by sebastianbergmann** [comment]
I would test that using PHPT.
