### ISSUE TITLE
Add support for registering comparators in XML

### ISSUE THREAD

**Issue by marcospassos** [sebastianbergmann/phpunit#3397]
Consider adding support for registering comparators using XML. The lack of such configuration is the only reason why we need a custom bootstrap file instead of using the autoload file in our projects

```xml
<comparators>
  <comparator class="Acme\PhpUnit\CustomComparator" file="/optional/path/to/CustomComparator.php">
</comparators>
```
It would extinguish boilerplate bootstrap files such as:

```php
use Acme\PhpUnit\CustomComparator;
use SebastianBergmann\Comparator\Factory;

require_once __DIR__ . '/../vendor/autoload.php';

Factory::getInstance()->register(new CustomComparator());
```

**Comment by sebastianbergmann** [comment]
I do not think that this would be a good idea. Registering comparators using the respective idea on a test-by-test basis is the right approach, IMO.
