### ISSUE TITLE
filter flag changes outcome of test

### ISSUE THREAD

**Issue by aruku** [sebastianbergmann/phpunit#3406]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 5.3.5
| PHP version         | 7.0.31
| Installation Method | PHAR

This fails:
```
# php /srv/www/neo/current/vendor/phpunit/phpunit/phpunit -c /srv/www/neo/current/tests/phpunit.xml tests/application/controllers/administration/Reports_Test.php --filter Reports_Test
PHPUnit 5.3.5 by Sebastian Bergmann and contributors.

.E..                                                                4 / 4 (100%)

You should really fix these slow tests (>500ms)...
 1. 1944ms to run Reports_Test:testGetPdf


Time: 3.71 seconds, Memory: 22.00MB

There was 1 error:

1) Reports_Test::testGetPdfReturns400WhenInvalidPermissions
Missing argument 1 for Reports_PHAKE5bed698f64be01::getPdf(), called in /srv/www/neo/current/tests/application/controllers/administration/Reports_Test.php on line 90 and defined

/srv/www/neo/current/tests/application/controllers/administration/Reports_Test.php:90

FAILURES!
Tests: 4, Assertions: 5, Errors: 1.
```
But this passes:
```
# php /srv/www/neo/current/vendor/phpunit/phpunit/phpunit -c /srv/www/neo/current/tests/phpunit.xml tests/application/controllers/administration/Reports_Test.php --filter "/(::testGetPdfReturns400WhenInvalidPermissions)( .*)?$/"
PHPUnit 5.3.5 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

You should really fix these slow tests (>500ms)...
 1. 1754ms to run Reports_Test:testGetPdfReturns400WhenInvalidPermissions


Time: 2.52 seconds, Memory: 20.00MB

OK (1 test, 2 assertions)
```
I don't even know what outcome is the right one, because the syntax error that PHPUnit complains about is done in the first test of that class too and that one doesn't fail.
Can anybody explain this? We are banging our heads trying to understand this issue and others.

**Comment by epdenouden** [comment]
Hello @aruku!

Immediately I noticed `Reports_PHAKE5bed698f64be01` which tells me Phake is generating (temporary) mocks in the background. I'd wager you have a hidden dependency that only shows up when you run a different subset of tests.

Withouth access to the full code this is near impossible to debug or give advice on. Something to try is experimenting with the test execution reordering features, which were designed for debugging such cases.

Suggestion: include `--order-by=reverse` to your command line and see if you get different output. If the output is very different depending on the test execution order you just might have some (hidden) dependencies in your test suite.

**Comment by aruku** [comment]
Thank you, @epdenouden. What version was that option introduced? I can't find reference for it.

**Comment by epdenouden** [comment]
@aruku Oops. My apologies, I imagined reading a 7.x version for PHPUnit. The execution reordering features were only recently introduced in version 7.2. I realize this is not as easy to try for you now.

Something you could try is moving the offending test methods around in the file itself. Or look inside the tests with your IDE+Xdebug to have a look at the runtime environment of the tests.

**Comment by sebastianbergmann** [comment]
PHPUnit 5 is no longer supported. Please open a new ticket in case this still applies to a supported version of PHPUnit.
