### ISSUE TITLE
Abstract class PHPUnit_Framework_TestCase

### ISSUE THREAD

**Issue by solcre-at** [sebastianbergmann/phpunit#3407]
An abstract class should have at least one abstract method declared. 
So the classes that extend of this abstract class could define the logic of the function.

Why are not these methods declared as abstract?

Some of them:
- public static function setUpBeforeClass(){}
- protected function setUp(){}

I hope the explanation. 

Regards.

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.
