### ISSUE TITLE
Method annotation @runInSeparateProcess not working

### ISSUE THREAD

**Issue by hollodotme** [sebastianbergmann/phpunit#3409]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.4.4
| PHP version         | 7.2.12 (But also PHP >= 7.1)
| Installation Method | PHAR

[This test](https://github.com/openmetrics-php/exposition-text/blob/master/tests/Unit/HttpResponseTest.php#L24) fails since PHPUnit 7.4.4.

The [`respond()` method](https://github.com/openmetrics-php/exposition-text/blob/master/tests/Unit/HttpResponseTest.php#L42) sends headers which then are read and checked via `headers_list()`.

The test passes in PHPUnit 7.4.3 and lower.
See travis-ci builds:
* [Failing build with PHPUnit 7.4.4](https://travis-ci.org/openmetrics-php/exposition-text/builds/455491065)
* [Succeeding build with PHPUnit 7.4.3](https://travis-ci.org/openmetrics-php/exposition-text/builds/454984056)

**Comment by epdenouden** [comment]
@hollodotme Thank you for the detailed failure report! Makes debugging a lot easier. I will look into this tomorrow and report back here.

@sebastianbergmann If the repo settings allow it, can you please assign this issue to me for keeping track?

**Comment by epdenouden** [comment]
@hollodotme the correct way to run the tests is:
```
./vendor/bin/phpunit.phar -c build/phpunit.xml
```
correct?

**Comment by hollodotme** [comment]
Yes.

**Comment by epdenouden** [comment]
Testing notes:
- installed required Python modules with:
  ```
  pip install prometheus_client
  pip install path.py
  ```

**Comment by epdenouden** [comment]
@hollodotme I do not know yet what the root cause of the problem is. Maybe it has been a change between 7.4.3 and 7.4.4. Maybe it has to do with how the PHAR is put together.

If I switch off the `@runInSeperateProcess` the problem appears to be 'catching' the actual HTTP output that is written with the builtin `header()`/`echo`/`flush` without the use of mocked or injected output handler. The PHPUnit default output printer has already written something to `STDOUT` at that point, causing the error:
```
1) OpenMetricsPhp\Exposition\Text\Tests\Unit\HttpResponseTest::testCanRespondMetrics
Cannot modify header information - headers already sent by (output started at phar:///Users/ewout/proj/exposition-text/vendor/tm/tooly-composer-script/bin/phpunit.phar/phpunit/Util/Printer.php:109)
```

I quickly tried a bit to get it working along the lines of
```php
$response = HttpResponse::fromMetricCollections( $gaugeCollection, $counterCollection );
// $headers = headers_list();
$this->assertArraySubset(['Content-Type' => ['application/openmetrics-text; charset=utf-8']], $response->getHeaders());
```
but that only got me `$expectedOutput` errors still, because everything just `echo`s to standard output.

As a solution I would propose using another method of catching the HTTP-headers and content body, specifically one that doesn't use the default output.

**Comment by sebastianbergmann** [comment]
I recently changed how the PHAR works in 1bb3ca072ba1bac126530aed42c2027e9f1679e3.

**Comment by hollodotme** [comment]
@epdenouden First of all thank you for your time & investigation. I had a look at some other tests of mine where I check for sent headers. In all of them I use `xdebug_get_headers()` (instead of `headers_list()`) together with `@runInSeparateProcess`. 

In general I'd prefer to use the `headers_list()` function as it is (always) bundled with PHP's network functions while the `xdebug_get_headers()` requires a 3rd party extension. (Of course I love Xdebug and have it installed in most cases!)

I actually don't know how the change @sebastianbergmann mentioned is related to this changed behaviour.

However, when I replace `headers_list()` with `xdebug_get_headers()` in the test, it works with PHPUnit 7.4.4 without any further change. (This was also "recommended" by @sebastianbergmann [here](https://github.com/sebastianbergmann/phpunit/issues/720#issuecomment-10421092).) 

TBH I'm still clueless why it worked with `headers_list()` before or what the actual difference is now in 7.4.4. But I also found [this 1 year old comment](http://php.net/manual/en/function.headers-list.php#120539) on php.net:
>This function won't work for when you're running PHP from the command line. If will always return an empty array. This can be an issue when testing your project using PHPUnit or Codeception.
>
>To solve this, install the xdebug extension and use `xdebug_get_headers` when on the cli.
>
```php
<?php
$headers = php_sapi_name() === 'cli' ? xdebug_get_headers() : headers_list();
?>
```

Tests are passing now on travis-ci:  https://travis-ci.org/openmetrics-php/exposition-text/builds/460965301

I'm closing this issue.
