### ISSUE TITLE
Branch 5.7 seems to be deleted but still is used by simple-phpunit from Symfony

### ISSUE THREAD

**Issue by sqrt-1764** [sebastianbergmann/phpunit#3411]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 5.7
| PHP version         | 7.1
| Installation Method | Composer / PHAR

I am using phpunit via the simple-phpunit script from symfony.
This script for my current configuration requests phpunit 5.7 from github.
As I run this test on a Gitlab Runner in a fresh docker container, I have to download this on every test.

Since one hour or so, the 5.7 branch seems to be deleted which breaks my tests.

Any chance to restore the 5.7 branch until the Symfony-guys were able to fix this?

**Comment by sqrt-1764** [comment]
I was able to update my project to php 7.2.
Then simple-phpunit does not require phpunit 5.7 but then uses 6.5

So for me the problem is solved, but there might be others out there, who can not switch so easily.

**Comment by sebastianbergmann** [comment]
Sorry if the deletion of the `5.7` branch cause[s|d] problems. I do not understand why somebody would depend on a branch (and a dead one at that) instead of a tag.

**Comment by sqrt-1764** [comment]
Never mind! 
So I was forced to move to current versions ;-)

Regarding simple-phpunit - they download the zip Archive and do not use git for this.
I now will put some effort into my docker-images and harden them so that those components are already installed in them.

**Comment by mitch10593** [comment]
Symfony phpunit bridge use hard coded phpunit version (with manual zip download).
It uses 5.7.zip for php < 7.2.

Here, the phpunit version regarding php version:
https://github.com/symfony/phpunit-bridge/blob/4.1/bin/simple-phpunit#L53

And here the direct url from 'branche version'.
https://github.com/symfony/phpunit-bridge/blob/4.1/bin/simple-phpunit#L96 

There is no issue tracker on the symfoby phpunit bridge project to declare this problem...

**Comment by mitch10593** [comment]
In fact, there is an easy solution: force the phpunit version with ENV vars:

```shell
SYMFONY_PHPUNIT_VERSION=7.4.4 ./vendor/bin/simple-phpunit
```
