### ISSUE TITLE
PHPUnit Version 5.7 Removed

### ISSUE THREAD

**Issue by gellis** [sebastianbergmann/phpunit#3413]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 5.7
| PHP version         | 7.1
| Installation Method | Composer

We are using the Symfony PHPUnit Bridge and as of yesterday afternoon we are getting the following error: `RuntimeException: Could not find https://github.com/sebastianbergmann/phpunit/archive/5.7.zip`

It does indeed appear that version 5.7 has been removed from the archive but the Symfony PHPUnit Bridge requires that version for users on PHP 7.1.

Would it be possible to re-upload version 5.7 to the archive?

**Comment by nicolas-grekas** [comment]
Reported also in https://github.com/symfony/symfony/issues/29264 and https://github.com/symfony/symfony/pull/29263
The reason is that the corresponding branches have been removed.
Please bring them back...

**Comment by sebastianbergmann** [comment]
Please do not depend on implementation details you do not control, in this case branches in PHPUnit's version control system.

**Comment by nicolas-grekas** [comment]
The whole internet relies on things we don't control: GitHub URLs, google APIs, etc. Could you please consider reconsidering: this breaks legitimate CIs that were just fine. I suppose you won't anytime remove tags. You could though. Branches are the same to me: they're part of history and should be kept forever.

**Comment by rvanlaak** [comment]
FYI: phpunit v6.3 started throwing a 404

https://github.com/sebastianbergmann/phpunit/archive/6.3.zip
