### ISSUE TITLE
New @iterableProvider annotation

### ISSUE THREAD

**Issue by ro0NL** [sebastianbergmann/phpunit#3415]
In addition to `@dataProvider` it could be useful to provide an out-of-the-box `@iterableProvider` based on top of that. That could simplify variance testing IMHO.

```php
/**
 * @iterableProvider provideIterable()
 * @iterableProvider Some::getStatuses()
 */
public function testVariance($value[, $key])
{
}
```

Thoughts?

**Comment by sebastianbergmann** [comment]
I do not understand what you are trying to propose here. A data provider can be an array or an `Iterator` implementation, even generators work.

**Comment by ro0NL** [comment]
You cannot return $someIterable as-is and with that provide the actual key/values as arguments. You need to map each row to array(value, key)

**Comment by sebastianbergmann** [comment]
Makes no sense to me, sorry.
