### ISSUE TITLE
Proposal: split assertContains for iterables and non-iterables

### ISSUE THREAD

**Issue by keradus** [sebastianbergmann/phpunit#3422]
currently, one can do both with a single assertion:
```php
$this->assertContains('b', ['a', 'b', 'c']);
$this->assertContains('b', 'abc');
```

which is confusing if someone use it like the following, and for that error prone due to accidental lack of types control
```
$this->assertContains('b', $haystack);
```

what about splitting the responsibility of that assertion, to have one for strings and one for iterables ?

ref https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4061

**Comment by sebastianbergmann** [comment]
Going further, we probably want to get rid of the optional parameters and introduce

* `assertStringContainsString()`
* `assertStringContainsStringIgnoringCase()`
* `assertStringNotContainsString()`
* `assertStringNotContainsStringIgnoringCase()`

etc.

**Comment by sebastianbergmann** [comment]
@keradus Can you please have a look at 77d079f8c216d23179b1ab9ac56f2e7f930175aa? Thanks!

**Comment by keradus** [comment]
Hi ! First of all, glad you like the idea !

> Deprecate (soft) `assertContains()` in PHPUnit 7.5
> Deprecate (hard) `assertContains()` in PHPUnit 8.0

can you elaborate how you define difference of `hard` and `soft` deprecation? if hard is removal of functionality, then that's how I would see this to happen indeed ;)

> `assertIterableContains()` (uses `new TraversableContains($needle, false, false)`)
> `assertIterableContainsSame()` (uses `new TraversableContains($needle, true, true)`)

I would rather promote strict comparison by default. Language itself is promoting to be strict about types now, let's not promote (by more convenient way) being not strict.
that saying, I would suggest following naming instead:
`assertIterableContains` to check strict
`assertIterableContainsEqual` to check non-strict

> Can you please have a look at master...686d153? Thanks!

can you raise it as a PR? with link provided, I can't do the comments :(

**Comment by sebastianbergmann** [comment]
1. [Soft Deprecation](https://github.com/sebastianbergmann/phpunit/wiki/Release-Process#stage-1-soft-deprecation) in PHPUnit 7.5
2. [Hard Deprecation](https://github.com/sebastianbergmann/phpunit/wiki/Release-Process#stage-2-deprecation) in PHPUnit 8
3. [Removal](https://github.com/sebastianbergmann/phpunit/wiki/Release-Process#stage-3-removal) in PHPUnit 9

**Comment by sebastianbergmann** [comment]
Sorry, but I do not send myself pull requests.

**Comment by sebastianbergmann** [comment]
I agree with promoting strict comparison, but the naming as-is makes more sense to me somehow.

**Comment by ilyachase** [comment]
@sebastianbergmann did you decide to not add `assertIterableContains`? Because there's only "contains" method about strings.
