### ISSUE TITLE
Clean up assertContains() and assertNotContains()

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#3426]
* Remove support for using `assertContains()` and `assertNotContains()` on `string` haystacks
* Remove the optional parameters `$ignoreCase`, `$checkForObjectIdentity`, and `$checkForNonObjectIdentity` of `assertContains()` and `assertNotContains()`
* Remove `Assert::contains()`
* Eliminate code duplication in `TraversableContainsEqual` and `TraversableContainsIdentical` by inheriting from `TraversableContains` (which becomes an abstract base class for these two concrete classes)
* Use `TraversableContainsIdentical` in `Assert::assertContains()` and `Assert::assertNotContains()` (this means that `assertContains()` and `assertNotContains()` will perform strict comparisons starting with PHPUnit 9 where non-strict comparisons were performed in PHPUnit 8 and earlier; use `assertContainsEqual()` and `assertNotContainsEqual()` if you need non-strict comparison)

**Comment by stof** [comment]
@sebastianbergmann the PHPUnit 9 changelog does not document the behavior change of `assertContains` (moving from `Equal` to `Identical`).

**Comment by sebastianbergmann** [comment]
The ChangeLog has

> Implemented #3426: Clean up assertContains() and assertNotContains()

which links to this ticket where this is explained.

**Comment by stof** [comment]
but if you don't click on the link, you don't have any indication that `assertContains` is now stricter in its matching. As this can break existing testsuites (it broken mine when upgrading), it should be more visible IMO.

**Comment by driesvints** [comment]
Hey @sebastianbergmann. We got bitten by this change as well in Laravel. I agree with @stof that this should be added to the changelog. If you can point me to where I need to make it I'll be happy to send in a PR.
