### ISSUE TITLE
How can a Listener conditionally skip a test?

### ISSUE THREAD

**Issue by blockjon** [sebastianbergmann/phpunit#3427]
I'm very excited about the ability to implement PHPUnit\Framework\TestListener in order to add a custom behavior.

In my case, I want to execute some custom logic to determine which of the tests in my suites should be skipped.

Specifically, I want to download a list of tests that should be skipped and then enforce that skip list at runtime.

How should I do this? I would prefer to not have to change all of my test classes to extend from some new class or to put annotations all over.

Pytest has a similar option where you can hook into the moment just before a test executes and set the test to be skipped just before it would otherwise actually run the test. Can I do that? It would make my life great!

**Comment by blockjon** [comment]
@epdenouden Thank you for your reply! Yes I would like to either skip tests or not play them at all... either option will work.

I'm trying to create PHP support for https://www.flaptastic.com/ which has a checkbox that allows you to instantly disable a test in CI. Here's what I've got so far: https://packagist.org/packages/blockjon/flaptastic

To "disable" a test in CI means to either skip it, or to not execute it in the first place.

![image](https://user-images.githubusercontent.com/1198745/49242026-68a85c00-f3be-11e8-98f4-d1658c168e80.png)

The goal here is to be able to skip certain tests at *runtime*. This is made to be possible because the test runner (PHPUnit in this case) downloads a list of file names and test function names that are to be skipped ... so I need some smart "PHPUnit way" to programmatically skip whichever tests are in that dynamic list which changes over time from within the PHPUnit test run in the simplest way as possible.

Here's what I've got so far:
https://packagist.org/packages/blockjon/flaptastic

**Comment by sebastianbergmann** [comment]
This will likely be possible once #3387 has been implemented.

**Comment by blockjon** [comment]
I think I have found what might be the simplest way to do it given the current PHPUnit architecture - to have them add a trait to their own abstract TestCase file. I assume most projects implement some kind of common TestCase that it could be added to.

https://github.com/blockjon/phpunit-flaptastic/blob/master/README.md#integrating-with-your-codebase
