### ISSUE TITLE
Strange error in tests after update to phpunit 7.5

### ISSUE THREAD

**Issue by VikaM95** [sebastianbergmann/phpunit#3431]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.4.4
| PHP version         | 7.2
| Installation Method | Composer

One of my tests was green in 7.4 now is reds

public function testTreatmentUrlRouter()
    {
        $router = new Router();
        $checkArray = $router->treatmentUrl([], '');
        $this->assertArrayHasKey('nameClass', $checkArray);
        $this->assertArrayHasKey('nameMethod', $checkArray);
        $this->assertArrayHasKey('properties', $checkArray);
    }

error

PHP Fatal error:  Declaration of PHPUnit\Util\Log\TeamCity::printResult(PHPUnit\Framework\TestResult $result) must be compatible with PHPUnit\TextUI\ResultPrinter::printResult(PHPUnit\Framework\TestResult $result): void in /usr/share/php/PHPUnit/Util/Log/TeamCity.php on line 31

**Comment by VikaM95** [comment]
@epdenouden I use TestCase.

**Comment by epdenouden** [comment]
@VikaM95 Can you provide us with a stand-alone example of the above problem, especially with exact steps to reproduce?

I just had a try with the latest 7.5 branch I do not see this error. Also the method signatures for both the default printer as well as the TeamCity printer is `public function printResult(TestResult $result): void`.

I'm not familiar with TestCase other than `TestCase` so I cannot help you there. When used standalone PHPUnit does not generate this error.

**Comment by VikaM95** [comment]
@epdenouden 
I am sorri, there is eroor when instal phpunit ( sudo apt install phpunit )
When i started "sudo apt-get remove phpunit", error is gone

**Comment by sebastianbergmann** [comment]
PHPUnit 7.5 has not been released yet. And I hardly doubt that `sudo apt install phpunit` installs a development version of PHPUnit.

**Comment by epdenouden** [comment]
@VikaM95 In your bug report you mention `PHPUnit version | 7.4.4` so I am not sure where the confusion comes from. Check if you are using some APT repository that uses nightly or development builds.

**Comment by kinow** [comment]
I just had the same issue, but for the record, my project was using `7.5.10`, but I had a `phpunit` installed in the operating system with version `6.5.5`.

Running `phpunit` version 7.5 fixed it :+1:
