### ISSUE TITLE
Critical error

### ISSUE THREAD

**Issue by AndriySvirin** [sebastianbergmann/phpunit#3440]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.5.13
| PHP version         | 7.2.10
| Installation Method | Composer

Have a wrong preg_repalce result
http://prntscr.com/ls01gf

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting. Please do not post screenshots of production code, test code, or PHPUnit output.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by AndriySvirin** [comment]
Hi, Sorry, for my short description. I think that you can reproduce by generating base64 encoded string with enough long lenght. I think that i had made mistake, wheh passed such large parameter by path. So i changed passing parameter from by path to by query and fixed my issue.
so i have fixed my problem by did not explored detailed behaviour of function preg_replace in PHP.

i think you can encounter such incorrect behaviour (when added \n chrqacter in the end) if you will use php 7.2.10 or 7,2,12 with config from the box on debian and random generated string 20-40 chracters encoded by base64.

PS: i tried to use such regex mask on another popular site (based on JS) and it did not respond exceed character (\n).

**Comment by sebastianbergmann** [comment]
PHPUnit 6.5 is no longer supported. Please open a new ticket in case this still applies to a supported version of PHPUnit.
