### ISSUE TITLE
@depends doesnt work with @testWith

### ISSUE THREAD

**Issue by Niko9911** [sebastianbergmann/phpunit#3450]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.5
| PHP version         | 7.1
| Installation Method | Composer

There is issue when returning value from depended-upon test. It will always return null when using data sets.

Fix will be introduced in #3449

**Comment by Niko9911** [comment]
This issue can be closed when #3449 is merged.

**Comment by epdenouden** [comment]
@Niko9911 What is the exact issue here? In case it is a variant of the issue demonstrated below, the TL;DR is that this is a result of the current architecture and cannot be changed easily. If you search the github issues for 'dataprovider' and 'depends' you will find quite a lot of discussion.

The code below shows that depending on a dataprovidered tests _will not_ automatically rerun the test for every dataprovider row of the test referenced in `@depends`.

```php
<?php
class DataproviderAsDependencyParameterTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @testdox testA($value)
     * @depends testB
     */
    public function testA($value): void
    {
        $this->assertTrue(true);
    }

    /**
     * @testdox testB($value)
     * @dataProvider someProvider
     */
    public function testB($value): void
    {
        $this->assertTrue(true);
    }

    public function someProvider()
    {
        return [
            [1],
            [2],
            [3],
        ];
    }
}
```

**Comment by sebastianbergmann** [comment]
Can this be closed?

**Comment by epdenouden** [comment]
I think so, yes. It is a request that pops up every now and then. Having looked at the way dataproviders work it won't be a simple change to get this working.
