### ISSUE TITLE
No error on traits collisions

### ISSUE THREAD

**Issue by BonBonSlick** [sebastianbergmann/phpunit#3455]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.3.3
| PHP version         | 7.2.12
| Installation Method | Composer 

```
phpunit/php-code-coverage                      6.0.7              Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator                      2.0.1              FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template                      1.2.1              Simple template engine.
phpunit/php-timer                              2.0.0              Utility class for timing
phpunit/php-token-stream                       3.0.0              Wrapper around PHP's tokenizer extension.
phpunit/phpunit                                7.3.3              The PHP Unit Testing framework.
```

```
use PHPUnit\Framework\TestCase;

final class EpisodeTest extends TestCase{
  use EpisodeDetailsDummyTestDataTrait, EpisodeDummyTestDataTrait;

trait EpisodeDummyTestDataTrait{
  use DummyTestsDataTrait;

trait  EpisodeDetailsDummyTestDataTrait{
  use DummyTestsDataTrait;

bonbon@debian:/var/www/test$ phpunit
bonbon@debian:/var/www/test$ 
```

When traits used which use same trait, phpunit fails without any errors.
Would be nice to have any error shown or logged to understand why it fails. Logs are not generated, no exceptions.

Like PhP does when any class use same traits

`PHP Fatal error:  Trait method dummyUtf8Video has not been applied, because there are collisions with other trait methods on App\Entity\Episode in /var/www/test/src/Entity/Episode.php on line 26

`

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by BonBonSlick** [comment]
Found solution,
<ini name="error_reporting" value="-1" />
and
<ini name="display_errors" value="On" />

should be -1 not 1

From docs http://php.net/manual/ru/function.error-reporting.php


Thank you for your time.
