### ISSUE TITLE
Remove setMethods from MockBuilder

### ISSUE THREAD

**Issue by gmponos** [sebastianbergmann/phpunit#3458]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | ^7

Lately we see a lot of changes happening to PHPUnit towards the direction of being even more strict.

I would like to make a suggestion.... Take for instances this:

```php
class MyLogger
{
    public function log($message, array $params)
    {
        ...
        $this->doLog($message, $params);
        ....
    }

    private function doLog($message, array $params)
    {
        ....
    }
}
```

Now my test

```php
class MyLoggerTest extends TestCase
{
    public function testLog()
    {
        $logger = $this
            ->getMockBuilder('MyLogger')
            ->setMethods(['doLog'])
            ->getMock();

        $logger
            ->expects($this->once())
            ->method('log')
            ->with($message, $params);

        $logger->log($message, $params);
    }
}
```

I hope you can see the misconcept in the above case... because
- I am mocking the class that it is under testing which shouldn't happen.
- I am manipulating private methods..

I am not aware if `setMethods` is in anyway anymore helpful. Personally I never use it since I always do something like:

If I remove `setMethods` from the above example I get:

`Trying to configure method "doLog" which cannot be configured because it does not exist has not been specified, is final, or is static`

although the function exists if I check with a reflection

```php
        $class = new \ReflectionClass($logger);
        $methods = $class->getMethods();
        var_dump($methods);
```

```php
$logger = $this->getMockBuilder('MyLogger')->getMock();
$logger->expects($this->once())->method('')
```

**Comment by gmponos** [comment]
Now that I think of it setMethods might be useful for `magic` methods.. I am not sure if there could be a work around there if you do accept to remove `setMethods`

**Comment by sebastianbergmann** [comment]
It's also required for partial mocking which is in rare cases required to test what you want to test.

**Comment by DFoxinator** [comment]
@gmponos I'm having the same issue. I was under the incorrect impression that you could use setMethods to declare methods to be mocked, but that if you declared a non-existent/private method you would get a warning/error. Since that's not the case, I can't figure out how to accomplish that with PHPUnit. Have you found any workaround for this issue?
