### ISSUE TITLE
@requires function swallows digits at the end of function name

### ISSUE THREAD

**Issue by MaxSem** [sebastianbergmann/phpunit#3459]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.5.1
| PHP version         | 7.2.13
| Installation Method | PHAR

If a required function name ends with a digit, PHPUnit misses the digit(s).

Example:
```
<?php
/**
 * @requires function hash_pbkdf2
 */
class DummyTest extends PHPUnit\Framework\TestCase {
}
```
Current behavior:
```
$ php phpunit-7.5.1.phar --verbose test.php
PHPUnit 7.5.1 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.2.13

S                                                                   1 / 1 (100%)

Time: 84 ms, Memory: 10.00MB

There was 1 skipped test:

1) Warning
Function hash_pbkdf is required.

OK, but incomplete, skipped, or risky tests!
Tests: 1, Assertions: 0, Skipped: 1.
```

Expected behavior: test is not skipped because `hash_pbkdf2()` is present.

**Comment by epdenouden** [comment]
I will have a look!

**Comment by epdenouden** [comment]
@MaxSem Thanks for taking the time to submit the issue! I have reproduced it in the self-test collection and... fireworks! A solid start to 2019, I say. Will submit a pull request with a fix.

**Comment by epdenouden** [comment]
@MaxSem PHPUnit 6.5.14 has just been released and I noticed the Mediawiki `composer.json` picking it up as expected:

![image](https://user-images.githubusercontent.com/26651359/52132295-1fcf8680-263f-11e9-9d1d-082ec653a240.png)
