### ISSUE TITLE
opcache.save_comments warning when not enabled

### ISSUE THREAD

**Issue by fire015** [sebastianbergmann/phpunit#3463]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.5.1
| PHP version         | 7.2.13
| Installation Method | Composer

I have opcache.save_comments set to 0 in my php.ini however I have disabled the whole of opcache from running. 

```
opcache.enable => Off => Off
opcache.enable_cli => Off => Off
opcache.save_comments => 0 => 0
```

In this case PHPUnit should probably check for the value of opcache.enable or opcache.enable_cli before showing the warning:

Warning: opcache.save_comments=0 set; annotations will not work

This is irrelevant when not enabled and leads to confusion.

**Comment by sebastianbergmann** [comment]
This is not a bug in PHPUnit itself.

**Comment by fire015** [comment]
@sebastianbergmann this is a feature request, is there somewhere I can put this?

**Comment by fire015** [comment]
Thanks :)

**Comment by sebastianbergmann** [comment]
The new implementation of `Runtime::discardsComments()` in https://github.com/sebastianbergmann/environment/blob/master/src/Runtime.php#L34 should solve this issue.
