### ISSUE TITLE
Feature Request: Max Test Duration

### ISSUE THREAD

**Issue by lofye** [sebastianbergmann/phpunit#3465]
It would be handy to be able to set a max-test-duration in the phpunit.xml, either globally or on a particular test suite. If a test takes longer than max-test-duration to run, it should automatically fail.
This can be used to ensure that all tests run quickly.

What inspired this was seeing the milliseconds of each test, as output by: https://github.com/LimeDeck/phpunit-detailed-printer/

**Comment by sebastianbergmann** [comment]
This functionality was implemented years ago. Have a look at `--enforce-time-limit` and related options and configuration settings.
