### ISSUE TITLE
Allow expected exception inspection

### ISSUE THREAD

**Issue by matthieu88160** [sebastianbergmann/phpunit#3468]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.5.x-dev
| PHP version         | 7.2.10
| Installation Method | Composer

Could be useful to be able to make more advanced validation on the thrown exceptions. Currently testing some exceptions in a library, I'm experiencing some difficulties to validate that an exception is successfully injected as the previous exception.

```PHP
// The component to test
// ...
    function getMapping() {
        foreach ($this->getMappingConfiguration() as $key => $definition) {
            try {
                $mapping[$key] = $optionsResolver->resolve($definition);
            } catch (InvalidArgumentException $surroundedException) {
                throw new MappingConfigurationFormatException(
                    sprintf(/* ... */),
                    0,
                    $surroundedException
                );
            }
        }
    }
// ...
```
What I can do is to validate the exception type, message and code, but it's not actually possible to perform a programmatic validation on the third parameter (the $previous one).

**Comment by sebastianbergmann** [comment]
I do not think that this would be useful, sorry.
