### ISSUE TITLE
Alternative to the now-abandoned dbunit extension?

### ISSUE THREAD

**Issue by daveh** [sebastianbergmann/phpunit#3477]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.5.1
| PHP version         | 7.2.10
| Installation Method | Composer

I just installed the dbunit extension using Composer, and I get the following message:

`Package phpunit/dbunit is abandoned, you should avoid using it. No replacement was suggested.`

I've seen the issue on the extension being abandoned, and people talk of rolling your own database testing code, but they don't go into any more details. Is there a recommended way to test database code, or a example available at all?

**Comment by sebastianbergmann** [comment]
No, there is not.

**Comment by olleharstedt** [comment]
What's the rational behind abandon dbunit?
