### ISSUE TITLE
Error running on console

### ISSUE THREAD

**Issue by k-gun** [sebastianbergmann/phpunit#3489]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.5.2
| PHP version         | 7.2.13 (7.2.13-1+ubuntu16.04.1+deb.sury.org+1)
| Installation Method | PHAR

Running like that, OK;

`/usr/share/php# ./phpunit --version`
`/usr/share/php# ./phpunit`

But that;
`/usr/share/php# phpunit --version`
`/usr/share/php# phpunit`

So, when I run `phpunit` without `./` in console, got this message;

<b>
PHP Fatal error:  Declaration of SebastianBergmann\Comparator\DOMNodeComparator::assertEquals($expected, $actual, $delta = 0, $canonicalize = false, $ignoreCase = false) must be compatible with SebastianBergmann\Comparator\ObjectComparator::assertEquals($expected, $actual, $delta = 0, $canonicalize = false, $ignoreCase = false, array &$processed = Array) in phar:///usr/local/bin/phpunit/sebastian-comparator/DOMNodeComparator.php on line 110
</b>

**Comment by sebastianbergmann** [comment]
It appears that you have different installations of PHPUnit mixed up.

For instance, you may have used Composer to install PHPUnit and have configured the autoloader generated by Composer as PHPUnit's bootstrap script but then you invoke PHPUnit using an executable other than `vendor/bin/phpunit`.
