### ISSUE TITLE
PHPUnit not executing in Drupal Pipeline

### ISSUE THREAD

**Issue by Macaret** [sebastianbergmann/phpunit#3496]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.5.13
| PHP version         | 7.2.4
| Installation Method | Composer

I'm trying to execute unit tests in a Drupal Gitlab-CI Pipeline.

```
bin/phpunit --version
PHPUnit 6.5.13 by Sebastian Bergmann and contributors.
```

```
bin/phpunit -c core modules/custom/hello_world
PHPUnit testing framework version 6 or greater is required when running on PHP 7.0 or greater. Run the command 'composer run-script drupal-phpunit-upgrade' in order to fix this.
```

Or if I do the following:

```
bin/phpunit --bootstrap vendor/autoload.php -c core modules/custom/hello_world
An error 255 occurred while running the command...
```

I've tried anything could come to mind, of course running the command upgrade, installing phpunit by phar, etc.

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.
