### ISSUE TITLE
Unable to chain a @dataProvider in method a with a @depends in method b

### ISSUE THREAD

**Issue by D43M0NT00L5** [sebastianbergmann/phpunit#3498]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.5.2
| PHP version         | 7.2
| Installation Method | Composer
|System |Ubuntu 18.10
|DE |PHPStorm
|doctrine/instantiator              |1.1.0
|myclabs/deep-copy                 |1.8.1
|phar-io/manifest                   |1.0.3
|phar-io/version                    |2.0.1
|phpdocumentor/reflection-common    |1.0.1
|phpdocumentor/reflection-docblock  |4.3.0
|phpdocumentor/type-resolver        |0.4.0     
|phpspec/prophecy                   |1.8.0     
|phpunit/php-code-coverage          |6.1.4 
|phpunit/php-file-iterator         |2.0.2
|phpunit/php-text-template          |1.2.1
|phpunit/php-timer                  |2.0.0
|phpunit/php-token-stream           |3.0.1    
|phpunit/phpunit                    |7.5.2      
|sebastian/code-unit-reverse-lookup |1.0.1    
|sebastian/comparator               |3.0.2      
|sebastian/diff                     |3.0.1      
|sebastian/environment              |4.0.1     
|sebastian/exporter                 |3.1.0      
|sebastian/global-state             |2.0.0     
|sebastian/object-enumerator        |3.0.3
|sebastian/object-reflector         |1.1.1
|sebastian/recursion-context        |3.0.0 
|sebastian/resource-operations      |2.0.1 
|sebastian/version                  |2.0.1
|symfony/polyfill-ctype             |v1.10.0 
|theseer/tokenizer                  |1.1.0
|webmozart/assert                   |1.4.0

Good day, I tried to play around with dataproviders and dependencies till I recognized an older issue occurring again now.

Its the Same Issue like in April 2018: Unable to chain a @dataProvider in method a with a @depends in method b #3093(https://github.com/sebastianbergmann/phpunit/issues/3093)

now a little test code for reproduction:

```<?php

use PHPUnit\Framework\TestCase;

class TestTest extends TestCase
{
    public function testEmpty()
    {
        $stack = [];
        $this->assertEmpty($stack);

        return $stack;
    }

    public function dataprovider()
    {
        $stack = [1];

        return [[$stack]];
    }

    /**
     * @depends testEmpty
     * @dataProvider dataprovider
     */
    public function testPush(array $stack)
    {
        var_dump($stack);
        array_push($stack, 'foo');
        $this->assertEquals('foo', $stack[count($stack) - 1]);
        $this->assertNotEmpty($stack);

        return $stack;
    }

    /**
     * @depends testPush
     */
    public function testPop(array $stack)
    {
        var_dump($stack);
        $this->assertEquals('foo', array_pop($stack));
        $this->assertEmpty($stack);
    }

}
```
if I try the shown code, I get an exception message.  TestPop is waiting for the parameter "stack" an array, but TestPush can't return a correct value to TestPop. So on the exception massage says "null" was given by TestPush.

The example should show three things I recognized:
First: all functions get called.
Second: in TestPush the dataprovider sets the parameter "stack" of TestPush not the dependency
Third: TestPop gets "null" passed by the dependency of TestPush not an array

I tried my best to explain it in english.
I hope you can help me out.

**Comment by epdenouden** [comment]
@D43M0NT00L5 Thanks for the report. If you can clean up the code example above a bit, I will have a look later today.

**Comment by epdenouden** [comment]
@D43M0NT00L5 Can you please explain the example a bit? Both `testEmpty` and `dataprovider` provider return something that you call a stack. Myself I hardly ever `return` values from a test, although I know `@depends` can be used to pass return values from one test to the next.

What do you want your example to output?

**Comment by D43M0NT00L5** [comment]
if I try the shown code, I get an exception message.  TestPop is waiting for the parameter "stack" an array, but TestPush can't return a correct value to TestPop. So on the exception massage says "null" was given by TestPush.

The example should show three things I recognized:
First: all functions get called.
Second: in TestPush the dataprovider sets the parameter "stack" of TestPush not the dependency
Third: TestPop gets "null" passed by the dependency of TestPush not an array

I tried my best to explain it in english.

**Comment by D43M0NT00L5** [comment]
> if I try the shown code, I get an exception message. TestPop is waiting for the parameter "stack" an array, but TestPush can't return a correct value to TestPop. So on the exception massage says "null" was given by TestPush.
> 
> The example should show three things I recognized:
> First: all functions get called.
> Second: in TestPush the dataprovider sets the parameter "stack" of TestPush not the dependency
> Third: TestPop gets "null" passed by the dependency of TestPush not an array
> 
> I tried my best to explain it in english.

**Comment by epdenouden** [comment]
@D43M0NT00L5 Yes, I did see your explanation and tried the example locally. I do see the same errors  but I am not completely sure what the expected use result _should be_. Maybe @sebastianbergmann can also chime in here.

The simple reason the code throws an error right now is a result of the design of the runner: `testPush` is a test with a `@dataprovider` which get transformed into a `DataproviderTestSuite` with a `TestCase` for every row. This results in the the `@depends testPush` not working, as there is no _single, individual_ test called `testPush` anymore.

Of course the next questions would be: should PHPUnit automagically expand this type of relationship into mulitple runs for `testPush[0...n] => testPop()`? Should there be an error, but a nicer one? Do we only honor the `@depends` for some sort of combined result from `testPush` and what would that look like?

These questions are very good ones and people keep bumping into them. There are few easy answers here, because as soon as build a test runner that can do stackable/chainable `@dataprovider` there will be nasty consequences for continuous integration. Somebody will write a `testAllDatabaseAndQueryTypeCombinationsForAllPlatformsEverywhere`. 🤐

**Comment by D43M0NT00L5** [comment]
@epdenouden i see the issue. So, as you said chaining `@dataprovider` would be very nasty, are we talking about one test calling the `@dataprovider` and the other `@depends` are only waiting for the return value or all following tests with `@depends` also calling a `@dataprovider`? 
As example:
"calling"->testPop + `@depends`->"call dependency first"->`@dataprovider` + testPush ->"do one run/row of testPop with return values of testPush"->testPop->"safe result"->"do next run/row if exists"->...->"end testPop and show results"

Is it possible in the `DataproviderTestSuite` to run one row each and then the `@depends` after calling a test with a dependency? Or did you mean if we are starting `testPop` which has no `@dataprovider`, calling his dependency `@depends testPush` and this one let the runner creates another `@dataprovider` as a result of `testPush` return values. Would this end up in that "nasty consequences" you noticed?
As example:
"calling"->testPop + `@depends`->"call dependency first"->`@dataprovider` + testPush ->"do all runs and if testPush succeed save the result in a 'temporary' dataprovider"->dp->"run testPop with 'temporary' dataprovider"->`@dataprovider`+testPop->"save and show result"

so if the second example would be your "nasty consequences" of course in combination of an extra `@dataprovider`of testPop, why wouldn't it be possible to add a kind of priority variable to the test config?

I hope you understand my intention.

**Comment by D43M0NT00L5** [comment]
Heyho, how is it going? Haven't heard from you guys in a while...

**Comment by D43M0NT00L5** [comment]
@epdenouden hello, I would be amused, if someone could answer me the question I did 2 months ago ;). I know you guys are hard working on bugs and features, but leaving me alone with no statement made me impatient.

**Comment by XedinUnknown** [comment]
Any news on this? Sure is stale. Still a big issue, though.

**Comment by sebastianbergmann** [comment]
I do not think that a test should use data passed to it by both `@dataProvider` and `@depends`.

**Comment by CC007** [comment]
There is a difference between if it should be done and if it should be possible
