### ISSUE TITLE
Numeric @ticket or @group annotations no longer work

### ISSUE THREAD

**Issue by SergeyBiryukov** [sebastianbergmann/phpunit#3502]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.5.2
| PHP version         | 7.2.14
| Installation Method | PHAR

In WordPress project, a lot of tests include a [`@ticket` annotation with a numeric ticket ID](https://make.wordpress.org/core/handbook/testing/automated-testing/writing-phpunit-tests/#annotations), for example:
```
/**
 * @ticket 21117
 */
```
A test with this annotation could previously be executed by running `phpunit --group 21117`.

This no longer works in PHPUnit 7.2+ due to a strict `in_array()` check introduced in 39294df.

`phpunit list-groups` does include `21117`, however running `phpunit --group 21117` results in a `No tests executed!` message.

The [documentation for `@group`](https://phpunit.readthedocs.io/en/7.4/annotations.html#group) has an example of `@group bug2204`, but it does not say that group cannot be numeric, so I'm assuming a numeric group is still valid.

Looking at `GroupFilterIterator::__construct()`, `$group` is an integer there, however `$groups` is an array of strings, so `in_array($group, $groups, true)` returns false.

Could we either cast `$group` to a string or remove the strict check?

**Comment by sebastianbergmann** [comment]
@willemstuursma Can you have a look, please?

**Comment by epdenouden** [comment]
@sebastianbergmann @willemstuursma if Willem is busy with other things I can make a fix

**Comment by epdenouden** [comment]
Okidoki, will do!

**Comment by willemstuursma** [comment]
Thanks @epdenouden!
