### ISSUE TITLE
Process Isolation does not work with phpunit.phar

### ISSUE THREAD

**Issue by olemartinorg** [sebastianbergmann/phpunit#3509]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.0.0
| PHP version         | Both 7.3.1 and 7.2.14
| Installation Method | PHAR

Steps to reproduce:

1. Install PHPUnit 8.0.0 via phar:  
`wget https://phar.phpunit.de/phpunit-8.0.0.phar && chmod a+x phpunit-8.0.0.phar`

2. With any test file:
```php
<?php
class Test extends PHPUnit\Framework\TestCase {
    public function testTrue(): void {
        $this->assertTrue(true);
    }
}
```

3. Run it with process isolation:  
`./phpunit-8.0.0.phar --process-isolation test.php`

Observe the failure:

```
PHPUnit 8.0.0 by Sebastian Bergmann and contributors.

E                                                                   1 / 1 (100%)

Time: 124 ms, Memory: 10.00MB

There was 1 error:

1) Test::testTrue
PHPUnit\Framework\Exception: PHP Fatal error:  strict_types declaration must be the very first statement in the script in /path/phpunit-8.0.0.phar on line 2
PHP Stack trace:
PHP   1. {main}() Standard input code:0

Fatal error: strict_types declaration must be the very first statement in the script in /path/phpunit-8.0.0.phar on line 2

Call Stack:
    0.0008     511120   1. {main}() Standard input code:0

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```

**Comment by sebastianbergmann** [comment]
It seems that there is a bug in PHP that when a PHAR is `include()`d or `require()`d and the PHAR's bootstrap script has a shebang such as `#!/usr/bin/env php` on its first line followed by `<?php declare(strict_types=1);` on its second line then PHP wrongly triggers a

> strict_types declaration must be the very first statement in the script

compiler error.

**Comment by sebastianbergmann** [comment]
The PHP bug is tracked in https://bugs.php.net/bug.php?id=77561.
