### ISSUE TITLE
Question about Mock-classes

### ISSUE THREAD

**Issue by N3XT0R** [sebastianbergmann/phpunit#3512]
Hello Guys,
i have a simple Question about mocking objects and hope that anyone can give me an answer on it. 

I've trying to mock an object, that already exists and was already factored over a factory-class, with all needed arguments and parameters.

On this factored class i want to mock some methods with specific return values. 
So i had tried to mock that object on this way:

`

$mockBuilder = $this->getMockBuilder($className);
$objectMock = $mockBuilder->setProxyTarget($classObject)->getMock();
$objectMock->method('showAgb')->willReturn(true);
`

but it seems that this way is not the right one, to clone all properties into the mock object. Is there any other way to do that?

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.
