### ISSUE TITLE
Testdox spinner cannot be disabled (and can be too verbose)

### ISSUE THREAD

**Issue by BafS** [sebastianbergmann/phpunit#3513]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.0.1
| PHP version         | 7.2
| Installation Method | Composer

Since PHPUnit 8 I have pages of "running tests ◓" (introduced by https://github.com/sebastianbergmann/phpunit/pull/3497) with the testdox option on my CI (it does support ANSI codes but it cannot clear all output). Could we have an option to disable the spinner (eg. `--no-progress`) or to detect if the output support it ? I want to keep the colors.

The current workaround is to extends CliTestDoxPrinter.php.

![image](https://user-images.githubusercontent.com/588205/52277819-e2783b00-2955-11e9-95d1-ccaae35d040d.png)

Thanks in advance

**Comment by epdenouden** [comment]
@BafS Of course! The spinner should never get in your way. I will gladly make it more optional, I will start working on a config option and get a pull request tomorrow.

Question: what type of terminal/`$TERM` does this happen in and what CLI-options or `phpunit.xml` flags do you use? I'm guessing the terminal supports color but not all rendering or interactive features.

Thank you for taking the time to file an issue about this, by the way. Good to have it fixed.

**Comment by BafS** [comment]
@epdenouden Thank you for your message ! The "terminal" the default gitlab web terminal.

```sh
[root@runner-5dda6155-project-56-concurrent-0 /]# echo $TERM;
xterm
```

The "problem" is just that it outputs the stream directly without clearing anything. It's not an interactive terminal but more an STDOUT stream.

I simply use `--testdox --no-cover` and the xml options are

```ini
 backupGlobals="false"
 backupStaticAttributes="false"
 verbose="true"
 colors="true"
 convertErrorsToExceptions="true"
 convertNoticesToExceptions="true"
 convertWarningsToExceptions="true"
 processIsolation="false"
 stopOnFailure="false"
```

Thanks for your help
