### ISSUE TITLE
PHP's auto_globals_jit=1 makes the PHAR unusable on some runtimes

### ISSUE THREAD

**Issue by dkarlovi** [sebastianbergmann/phpunit#3514]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.x, 8.x
| PHP version         | 7.2
| Installation Method | PHAR

If you run with `auto_globals_jit=1` (which seems to be the default in PHP 7.2), you might get an error

```
[Uncaught TypeError in /tools/phpunit on line 18]
TypeError: realpath() expects parameter 1 to be a valid path, null given in /tools/phpunit:18
Stack trace:
#0 /tools/phpunit(18): realpath(NULL)
#1 {main}
```

or a notice about missing `_SERVER` in `$GLOBALS` (depening on the PHP's current error level, I guess).

It looks like it's because of https://github.com/sebastianbergmann/phpunit/blob/ae06eafd42900b5119f444fcb94a94d2db9d784a/build/binary-phar-autoload.php.in#L18

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by dkarlovi** [comment]
Here is a reproducer repo:
https://github.com/dkarlovi/reproducer-phpunit-3514

Sorry about it being in a Docker image, it's the only way I've managed to reproduce it for sure. Not sure why it's not longer outputting the exact error as before.

The PHAR used is downloaded like this:
https://github.com/jakzal/toolbox/blob/0d3710c9a0a02df61a265ea10d32b315df27a3f3/resources/tools.json#L561-L585

**Comment by dkarlovi** [comment]
I understand, feel free to close the issue if no value was created here. :+1:

**Comment by dkarlovi** [comment]
FYI duplicate of #3352.
