### ISSUE TITLE
security issue 

### ISSUE THREAD

**Issue by almi9** [sebastianbergmann/phpunit#3516]
Dear

After I scan the code, there is a security alert, can anyone example for me what is that, please 

security description: 

Improper Neutralization of Directives in Dynamically Evaluated Code ('Eval Injection') (CWE ID
95)(5 flaws)
Description
The software allows untrusted input to be fed directly into a function (e.g. "eval") that dynamically evaluates and
executes the input as code, usually in the same interpreted language that the product uses.

line : eval('?>' . \file_get_contents('php://stdin'));

**Comment by sebastianbergmann** [comment]
I can only repeat what I wrote in https://github.com/sebastianbergmann/phpunit/issues/3112#issuecomment-386430232.
