### ISSUE TITLE
Issues with getMockFromWsdl

### ISSUE THREAD

**Issue by mhabibi** [sebastianbergmann/phpunit#3530]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | PHPUnit 7.5.4 
| PHP version         | PHP 7.2.15
| Installation Method | Composer

I am trying to use `getMockFromWsdl` with the following WSDL (`$soapClientMock = $this->getMockFromWsdl('path/to/my_file.xml');`):

> 
>     ...
>     <message name="Information_Input">
>         <part name="Input_Message" type="xsdLocal0:Element" />
>     </message>
>     <message name="Information_Output">
>         <part name="Id" type="xsd:string" />
>         <part name="Code" type="xsd:string" />
>         <part name="Message" type="xsd:string" />
>     </message>
>     <portType name="Information">
>         <operation name="Information">
>             <input message="tns:Information_Input" />
>             <output message="tns:Information_Output" />
>         </operation>
>     </portType>
>     ...
> 

But I get `ParseError: syntax error, unexpected '$Id' (T_VARIABLE)`.
The problem is that in \PHPUnit\Framework\MockObject\Generator::generateClassFromWsdl, `$client->__getFunctions()` returns `list(string $Id, string $Code, string $Message) Information(Element $Input_Message)`. So `$nameStart = \strpos($method, ' ') + 1;` does not locate the function name proprly.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by mhabibi** [comment]
@sebastianbergmann Please run:
```
git clone git@github.com:mhabibi/phpunit-soap-bug.git
cd phpunit-soap-bug/
composer install
vendor/bin/phpunit 
```

Then you should see:

```
There was 1 error:
1) Test\Test::test
ParseError: syntax error, unexpected '$Response_Code' (T_VARIABLE)
/phpunit-soap-bug/test/Test.php:10

```

**Comment by sebastianbergmann** [comment]
This is the PHP code that is generated for the WSDL in question:
```php
class Test extends \SoapClient
{
    public function __construct($wsdl, array $options)
    {
        parent::__construct('/usr/local/src/phpunit/tests/end-to-end/mock-objects/generator/../../../_files/3530.wsdl', $options);
    }

    public function $Response_Code, string $Response_Message) Contact_Information(string $Con($Response_Code, $Response_Message)
    {
    }
}
```
Obviously, this is completely broken.
