### ISSUE TITLE
Update cacheResult default value in phpunit.xsd 

### ISSUE THREAD

**Issue by mhujer** [sebastianbergmann/phpunit#3532]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.0.3
| PHP version         | 7.2.15
| Installation Method | Composer

The default value of `cacheResult` was changed to `true` in https://github.com/sebastianbergmann/phpunit/commit/9bead3fdbf5c54741cb688689f892ec1848b0bda and I suppose it should be updated in `phpunit.xsd` as well: https://github.com/sebastianbergmann/phpunit/blob/b3f1fa46d10ac568c6554a8ca7158cf09f352635/phpunit.xsd#L239

**Comment by epdenouden** [comment]
Will do! :)
