### ISSUE TITLE
Add support for stubbing and mocking closures

### ISSUE THREAD

**Issue by HeahDude** [sebastianbergmann/phpunit#3536]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.1
| PHP version         | 7.x
| Installation Method | Composer / PHAR

Would you accept a PR to support mocking closure, to ease checking that one is called?

I.e : https://3v4l.org/Yaq5A

```php
public function testClosureIsCalled()
{
    $callback = function () {};

    $this->assertClosureWillBeCalled($callback);

    SomeBusiness:caller($callback);
}
```

**Comment by sebastianbergmann** [comment]
I cannot promise acceptance of such a pull request but would, of course, consider it.

**Comment by morozov** [comment]
This is already possible by mocking `__invoke()` on `stdClass` in one line:
```php
public function testClosureIsCalled() : void
{
        $closure = $this->createPartialMock(stdClass::class, ['__invoke']);

        $closure->expects(
            $this->exactly(2)
        )->method('__invoke');

        $closure();
        $closure();
}
```
Unlike this workaround, the proposed API is not really flexible, however, it'd be nice if the workaround was formalized as a feature.

**Comment by veewee** [comment]
@morozov 
The provided solution results in:

> createPartialMock() called with method(s) __invoke that do not exist in stdClass. This will not be allowed in future versions of PHPUnit.

An API for this might be nice indeed!

**Comment by ChrisHSandN** [comment]
After some experimentation there still seems to be a method which works:

```js
$mock = $this
  ->getMockBuilder(\stdclass::class)
  ->addMethods(['__invoke'])
  ->getMock();

$mock
  ->expects(self::once())
  ->method('__invoke'));
```

(Tested on PHPUnit 9 / PHP 7.3)

**Comment by mnapoli** [comment]
Following up on this: https://github.com/sebastianbergmann/phpunit/pull/5759
