### ISSUE TITLE
Update resolveDependencies default value in phpunit.xsd

### ISSUE THREAD

**Issue by egoisticalgoat** [sebastianbergmann/phpunit#3539]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | ^8.0
| PHP version         | *
| Installation Method | *

Since resolving dependencies is now the default this should be true now too.

https://github.com/sebastianbergmann/phpunit/blob/b62028f7edcbb6503f4d28382c126df8b5d89325/phpunit.xsd#L283

**Comment by epdenouden** [comment]
@egoisticalgoat Thank you, had overlooked this one.
