### ISSUE TITLE
addTestFile() ignore suffix setting

### ISSUE THREAD

**Issue by SailorMax** [sebastianbergmann/phpunit#3541]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.5.1
| PHP version         | 7.3.2
| Installation Method | Composer

User can setup config file with `suffix` option, for example = "Test.php".
phpunit found all required test files by this rule, and collect them via `TestSuite::addTestFile()` method.
But inside `addTestFile()` it trying to find more tests via
```
$newClasses = \array_diff(\get_declared_classes(), $this->declaredClasses);
```
And this additional search ignore our rule about prefix!
In result phpunit can try to use not ready for tests files as tests.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by sebastianbergmann** [comment]
No feedback, closing.
