### ISSUE TITLE
Consider adding composer/xdebug-handler

### ISSUE THREAD

**Issue by morozov** [sebastianbergmann/phpunit#3544]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.0.0
| PHP version         | 7.3.2
| Installation Method | Composer

It's a known fact that Xdebug slows down code execution even if the extension is just loaded. Before I started using PCOV for code coverage, it was not obvious to me that the difference in performance is so substantial. For instance, the default Doctrine DBAL test suite takes 7-9 seconds with Xdebug and under 2 seconds without it.

As a developer and PHPUnit user, on the one hand, I want Xdebug to be loaded by default in order to be able to debug code; on the other, I want tests to run faster if I don't intend to debug them.

Of course, one could say that as a developer I can turn Xdebug on and off depending on whether I need it but it's barely convenient. At the same time, [composer/xdebug-handler](https://github.com/composer/xdebug-handler) helps automate this routine. It's used by such well-established projects like Composer, Infection, PHPStan, Vimeo Psalm and others.

Would it make sense if PHPUnit had a similar logic? By default, it would disable Xdebug unless an environment variable `PHPUNIT_ALLOW_XDEBUG` is set. Otherwise, it would work as it works today.

**Comment by keradus** [comment]
actually, I'm :+1: for it.
using xdebug for collecting coverage in age of phpdbg is such waste of time

**Comment by sebastianbergmann** [comment]
I am against adding such unnecessary complexity. If you do not want Xdebug loaded then do not load it.
