### ISSUE TITLE
Trash trash trash

### ISSUE THREAD

**Issue by solarengineering** [sebastianbergmann/phpunit#3546]
My experience: 
Fresh install of phpunit 7 existing in a fresh laravel project.
I run the example feature test after renaming-

```
    /** @test */
    public function anyone_can_see_the_index_page()
    {
        $response = $this->get('/');
        $response->assertStatus(200);
    }
```

failure based on server responding with 500... WHAT?!

Certainly I have an index, I'm looking at it in the browser, but the error logging of phpunit is worth NOTHING. So where do I go from here? After a few trys I realize my database was deleted entirely. Fucking awesome phpunit.

After rebuilding my database (a few times), I try a few other things like cache:clear and $response->dump() to try to get some headway, but to no avail.

I try to update this package to 8 and get a plethora of errors basically telling me to uninstall phpunit completely before reinstalling.

Now I am at phpunit 8, and unable to get any testing accomplished based on new errors with setUp and tearDown.

Ugh, I can NOT believe this is such a popular package. It is TRASH and has literally helped me NONE. 

Might as well manually input shit every time, just as efficient.

**Comment by epdenouden** [comment]
![image](https://user-images.githubusercontent.com/26651359/53559181-e01a9280-3b49-11e9-9104-45ded757ddd8.png)

@solarengineering Writing software is complex and often frustrating, I feel you. It looks like you're working on doing end-to-end testing on a whole webstack and that is not trivial at all. Hang in there.

If you want to see more error logging, have a look at running PHPUnit with the `--testdox --colors=always --verbose` flag. This gives you a lot more output and the v8 implementation adds a lot of new legibility features and extra details: #3439

**Comment by spriebsch** [comment]
Is the purpose of your post seeking advice or complaining about PHPUnit? If the latter, please bear in mind that actual people spend their valuable time developing and maintaining PHPUnit (and the other software you have probably used there). You are aware that those people are human, have feelings, and might feel offended by your post?

Other than that, there are thousands of developers out there using PHPUnit (and the other software you have probably used there) quite successfully. Are you sure that you did everything right?

On a personal note: it has taken me days, if not weeks in total to get into test automation. It is, as was mentioned before, a complex topic. You should not put the pressure on you to expect that everything will work right out of the box.
