### ISSUE TITLE
inconsistent order of summary output for success/failure cases

### ISSUE THREAD

**Issue by martinforsyth** [sebastianbergmann/phpunit#3547]
|Q                      |A
| --------------------| ---------------
| PHPUnit version     | 8.0.4
| PHP version         | 7.2.15-0
| Installation Method | PHAR

As end user, seeing slightly frustrating discrepancy between the order of name/count in summary output for succcess and failure cases.

**Example ...**
Using  Ex 2.1 from https://phpunit.readthedocs.io/en/8.0/writing-tests-for-phpunit.html, first as is, then edited to fail, the outputs from `phpunit --verbose` are ...

**Output in success case ...**
` ...`
`OK (1 test, 5 assertions)`
`...`
 
**Output in failure case ...**
` ...`
`FAILURES!`
`Tests: 1, Assertions: 5, Failures: 1.`
`...`

**Request ...**
Could one or the other of these (prob the success case as it's less code - see below) be changed to match the name/number order and formatting of the other? Such that the success case looked something more like ...

` ...`
`OK (Tests 1, Assertions: 5)`
`...`

Thanks

**Relevant code ...** is in `src/TextUI/ResultPrinter.php -> printFooter()`

**Success case ...**  `around line 414`

    `if ($result->wasSuccessful() &&`
        `$result->allHarmless() &&`
        `$result->allCompletelyImplemented() &&`
        `$result->noneSkipped()) {`
        `$this->writeWithColor(`
            `'fg-black, bg-green',`
            `\sprintf(`
                `'OK (%d test%s, %d assertion%s)',              <------` 
                     `...`

**Failure case ...** `around line 460`

            `$this->writeCountString(\count($result), 'Tests', $color, true);`
            `$this->writeCountString($this->numAssertions, 'Assertions', $color, true);`
            `$this->writeCountString($result->errorCount(), 'Errors', $color);`
            `$this->writeCountString($result->failureCount(), 'Failures', $color);`
            `...`

**Comment by epdenouden** [comment]
@martinforsyth Agreed, the output format can definitely be improved. Do you use the default output printer or another variant, like `--testdox`?

**Comment by sebastianbergmann** [comment]
The reasoning here is that "all tests should pass all the time" and if that is the case the only (really) important thing is "OK". I can see why you perceive this as inconsistent but I would rather not change it.

**Comment by martinforsyth** [comment]
> @martinforsyth Agreed, the output format can definitely be improved. Do you use the default output printer or another variant, like `--testdox`?

I'm new to PHPUnit - just a few hours (though i used CUnit  a lot some years ago). So far i've just used the default output printer :-)

**Comment by martinforsyth** [comment]
> The reasoning here is that "all tests should pass all the time" and if that is the case the only (really) important thing is "OK". I can see why you perceive this as inconsistent but I would rather not change it.

Fair enough - thx for quick response. 

Just to clarify though ... I appreciate that 'OK' is key and that part of the output string should remain at the start of the line and shouldn't change at all, particularly for reasons of backwards compatibility. My point, as a new user of PHPUnit was fairly trivial and based simply on the way i scan the output and the mental effort required when absorbing the info written in lines similar to the following in relatively quick succession. 

`tests 1 assertions 5`
`1 test 5 assertions`

It's the lack of symmetry i was getting at - but no matter, it's a relatively trivial point.  

Thx
