### ISSUE TITLE
Code factoring request : \PHPUnit\Framework\TestCase::runTest()

### ISSUE THREAD

**Issue by exteon** [sebastianbergmann/phpunit#3551]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | head
| PHP version         | all
| Installation Method | all

I'm working on a TestCase wrapper for PHPUnit and Codeception that does a different kind of process isolation run, using pcntl_fork. You can see it here: https://github.com/exteon/WithIsolation

In order for this to work, we need to wrap around the actual test running as it is performed by PHPUnit, in `\PHPUnit\Framework\TestCase::runTest()`, line `$testResult = $this->{$this->name}(...\array_values($testArguments));` . At the moment we are achieving this by using a hack: overriding runTest() and hijacking $this->name to trick it into running a wrapper. Since this is obviously wrong in the long run, it would help us to have the `$testResult = $this->{$this->name}(...\array_values($testArguments));` factored out in a method that can be overridden.

**Comment by sebastianbergmann** [comment]
Please send a pull request against `master` for me to look at.

**Comment by epdenouden** [comment]
@exteon I find your ideas intriguing and would like to subscribe to your newsletter. Thanks for the work you have already put into this.

I did some experiments around this on at a hackathon and had something working with containers that did something like the above. It worked like a charm as long as the tests were simple. Also have a branch with 99% working lazy-loading `@dataprovider` which is also impacted by this and vice-versa.

There is a lot to going on around process isolation, just to name a few things:
- #2739: process isolation + `@dataprovider`+ closures
- #3258: process isolation + running a whole class in a process
- lazy loading `@dataprovider` has been a request for forever and is closely tied to how tests and process are isolated from eachother

**Comment by exteon** [comment]
@epdenouden Well, that is hy we started this, because the fork preserves the state and doesn't need to be reinitialized. Which is all the more important to run with Codeception, which adds a whole deal of wrapping around PHPUnit that seems pretty difficult to reinitialize from zero. But with the downside that some libraries, even if threadsafe, may not be fork-safe (i.e. some DB clients, we are exploring this). It works for what we set out to do, but for all intents and purposes there seems it remains still a lot more work to do.

**Comment by sebastianbergmann** [comment]
@exteon Still waiting for the pull request.

**Comment by exteon** [comment]
Hi @sebastianbergmann , sorry for the late reply: we've patched PHPUnit with https://github.com/exteon/WithIsolation/blob/master/Codeception/codeception.patch
The changes are pretty small; but I see two patches don't run against the PHPUnit head, as i.e. `TestCase::setUseErrorHandlerFromAnnotation()` seems to be gone now.

Unfortunately I can't find the time ATM to upgrade everything (Codecept/PHPUnit/WithIsolation) and make everything work again; however, as a principle (since I see you're rewriting the code anyway): all we need is method/property/readers visible such that the `AbstractProcess::processChildResult()` and its wrapping calling code can be replicated in a class derived from TestCase (as you can see in https://github.com/exteon/WithIsolation/blob/master/Codeception/tests/_support/Test/WithIsolation.php method `run()`)

I'm sorry I can't find the time to provide a more precise pull request at this point, but I hope it helps for the code rewrites I see advertised everywhere in the current code as coming for V9.
