### ISSUE TITLE
setUpBeforeClass() seems to not be covered php-code-coverage

### ISSUE THREAD

**Issue by geraldo-netto** [sebastianbergmann/phpunit#3552]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.5.2
| PHP code coverage     | 6.1.4
| Xdebug         | 2.7.0
| PHP version         | 7.3.1
| Installation Method | brew (macos)

Dear @sebastianbergmann / Friends,

For some reason, it seems the code coverage module is not reporting the coverage properly
when I have a static setUpBeforeClass() as described on PHPUnit manual

This is the table showing the values when setUpBeforeClass() is static
(method signature: public static function setUpBeforeClass() { ... })
<img width="366" alt="screenshot 2019-03-06 at 23 10 02" src="https://user-images.githubusercontent.com/20527108/53917529-0cac3e00-4065-11e9-9f00-b9db343ee06a.png">

This is the table showing the values when setUpBeforeClass() is not static and is been called as a test:
(method signature: public function testSetUpBeforeClass() { ... })
<img width="372" alt="screenshot 2019-03-06 at 23 09 31" src="https://user-images.githubusercontent.com/20527108/53917633-4d0bbc00-4065-11e9-83f1-b74e90f10e5c.png">

As we can see, the parts of the report increases significantly after I change the method signature
Do you think it's a bug? if yes, how can I help fixing it?
Otherwise, I'll workaround it by changing setUpBeforeClass() signature to another one
I think even a constructor might do for my case

Thank You Very Much/Kind Regards,
Geraldo Netto

**Comment by sebastianbergmann** [comment]
This is not a bug but expected behaviour.

**Comment by geraldo-netto** [comment]
Dear @sebastianbergmann ,

Would be okay if I document it?
If yes, let me know how


Thank You Very Much/Kind Regards,
Geraldo Netto

**Comment by charrondev** [comment]
@sebastianbergmann Could you elaborate a bit more on why this is the case?

An example I can give is that we use setupBeforeClass() in our integration tests to define our MySQL table structure and configure our dependency injection container. This is the same code run in our production environment and as such we want them to be covered.

They happen to get covered (normally far more than once) in the setup for all the related tests, but the coverage isn't tracked. Instead we have to create tests specifically for this setup (which every other test requires) with some note of "PHPUnit doesn't track covered code from static setup, so we need to test this on it's own here".

**Comment by cperezabo** [comment]
This is the only framework I've used that behaves like this. Why @sebastianbergmann? It's not funny to be forced to put  `@codeCoverageIgnore` in every method used in setUpBeforeClass in order to get a 100% coverage, a complete no-sense.
