### ISSUE TITLE
Same instance returned for each call to getMockBuilder

### ISSUE THREAD

**Issue by zaifastafa** [sebastianbergmann/phpunit#3553]
| Q                   | A
| --------------------| ---------------
| PHPUnit version  | 5.7.27
| PHP version         | 7.1.21
| Installation Method | Composer (default installation of Shopware v.5.5.6)

If I have previously used for e.g `$this->getMockBuilder(Zend_Http_Client::class)` to create a mock client, using it the second time for another test gives me the same instance of the object, so the `expectations` fail for my second object as it keeps checking for the `expectations` from the previous instance.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by zaifastafa** [comment]
```
class ExampleTest extends TestCase {

    public function setUp()
    {
        $this->httpResponse = new Zend_Http_Response(200, [], 'alive');

        $httpClientMock = $this->getMockBuilder(Zend_Http_Client::class)
            ->setMethods(['request'])
            ->getMock();
        $httpClientMock->expects($this->atLeastOnce())
            ->method('request')
            ->willReturn($this->httpResponse);

        $this->httpClient = $httpClientMock;
    }

    public function testExample() 
    {

    	$httpClientMock = $this->getMockBuilder(Zend_Http_Client::class)
            ->setMethods(['request'])
            ->getMock();
        $httpClientMock->expects($this->once())
            ->method('request')
            ->willReturn($httpResponse);
}
```

**Expected Result:**
Throws error: `Expectation failed for method name is equal to <string:request> when invoked 1 time(s). Method was expected to be called 1 times, actually called 0 times.`

**What happens instead:**
Throws error: `Expectation failed for method name is equal to <string:request> when invoked at least once. Expected invocation at least once but it never occurred.`

Upon debugging, the instance `$this->httpClient` and `$httpClientMock` both are same (`\Mock_Zend_Http_Client_eeda5606`), whereas it should have created a new instance.

**Comment by sebastianbergmann** [comment]
They are objects of the same class (`\Mock_Zend_Http_Client_eeda5606`). That does not mean they are the same object.

**Comment by sebastianbergmann** [comment]
No feedback, closing.
