### ISSUE TITLE
Zero code coverage when using guzzle

### ISSUE THREAD

**Issue by redayoub** [sebastianbergmann/phpunit#3554]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.5.14
| PHP version         | 7.2.15
| Installation Method | Composer 

Phpunit generates a code coverage files with 0 coverage when using guzzle for sending requests. I'm using symfony 4 for writing functional tests.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by redayoub** [comment]
Hi,

This is an example of code that generates 0 coverage.

``` php
<?php

namespace App\Controller\Tests;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use App\Entity\Category;
use GuzzleHttp\Client;
use Faker\Factory;

class CategoryControllerTest extends WebTestCase
{
	/** @var Client */
    private $client;

    private $faker;

    protected function setUp()
    {
        $this->client = new Client([
            'base_uri' => 'http://localhost/',
        ]);

        $this->faker = Factory::create();
    }

    protected function tearDown()
    {
        $this->client = null;
    }

    /**
     * Test Get Categories.
     */
    public function testGetCategories()
    {
        try {
            $response = $this->client->get('/ad/categories');

        	$this->assertSame(200, $response->getStatusCode());
        } catch (\Exception $e) {
            echo $e->getResponse()->getBody(true);
        }
    }

    /**
     * Test Create Category.
     */
    public function testCreateCategory()
    {
        try {
            $response = $this->client->post(
                '/ad/categories',
                [
                    'json' => [
                        'name' => $this->faker->name,
                        'rank' => rand(1, 100),
                        'enabled' => rand(0, 1),
                        'shopCategory' => rand(0, 1)
                    ]
                ]
            );

            $this->assertSame(200, $response->getStatusCode());

            $category = json_decode($response->getBody()->getContents(), true);
            
            return $category;

        } catch (\Exception $e) {
            echo $e->getResponse()->getBody(true);
        }
    }

    /**
     * Test Get Category
     * 
     * @depends testCreateCategory
     */
    public function testGetCategory($category)
    {
    	try {
            $response = $this->client->get('/ad/categories/' . $category['uuid']);

        	$this->assertSame(200, $response->getStatusCode());
        } catch (\Exception $e) {
            echo $e->getResponse()->getBody(true);
        }
    }

    /**
     * Test Update Category.
     * 
     * @depends testCreateCategory
     */
    public function testUpdateCategory($category)
    {
        try {
            $response = $this->client->put(
                '/ad/categories/' . $category['uuid'],
                [
                    'json' => [
                        'name' => $this->faker->name,
                        'rank' => rand(1, 100),
                        'enabled' => rand(0, 1),
                        'shopCategory' => rand(0, 1)
                    ]
                ]
            );

        	$this->assertSame(200, $response->getStatusCode());
        } catch (\Exception $e) {
            echo $e->getResponse()->getBody(true);
        }
    }

    /**
     * Test Partial Update Category.
     * 
     * @depends testCreateCategory
     */
    public function testPartialUpdateCategory($category)
    {
        try {
            $response = $this->client->patch(
                '/ad/categories/' . $category['uuid'],
                [
                    'json' => [
                        'shopCategory' => rand(0, 1)
                    ]
                ]
            );

        	$this->assertSame(200, $response->getStatusCode());
        } catch (\Exception $e) {
            echo $e->getResponse()->getBody(true);
        }
    }

    /**
     * Test Remove Category.
     * 
     * @depends testCreateCategory
     */
    public function testRemoveCategory($category)
    {
        try { 
            $response = $this->client->delete('/ad/categories/' . $category['uuid']);

        	$this->assertSame(204, $response->getStatusCode());
        } catch (\Exception $e) {
            echo $e->getResponse()->getBody(true);
        }
    }
}
```

**Comment by sebastianbergmann** [comment]
This is not self-contained.

**Comment by redayoub** [comment]
what do you mean?

**Comment by epdenouden** [comment]
> what do you mean?

The example starts with a list of dependencies:
```php
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use App\Entity\Category;
use GuzzleHttp\Client;
use Faker\Factory;
```

@sebastianbergmann is wondering if the bug/issue also shows up when you make a test that relies **only** on Guzzle. On other words: is it a Guzzle-problem, or Guzzle in combination with any of the other libraries?

Can you come up with an example like...

```php
<?php
use GuzzleHttp\Client;

class CategoryControllerTest extends WebTestCase
{
   public function testMakeGuzzleCry() {
       // do testing here that requires Guzzle
       $this->assertGuzzleIsVerySad();
   }
}

**Comment by redayoub** [comment]
I don't get any issue, all the tests pass with and without guzzle. The problem is that when I run this code using guzzle the code coverage is 0% but when I run it with the default client it gives me correct code coverage.

**Comment by epdenouden** [comment]
@redayoub Thanks for the additional clarification. That makes the 'self-contained example' even more important, since debugging the whole tooling stack (PHPUnit + Symfony testing components + Symfony + kitchen sink) would be very time consuming.

I noticed the test is not a standard PHPUnit testcase, but rather `extends WebTestCase`. Happy to help out with any PHPUnit issues, but this sounds like the issue is with the Symfony testing harness combined with Guzzle. Personally I lack the in-depth knowledge to look into this quickly.

**Comment by rightwayround** [comment]
@redayoub did you manage to resolve this issue?

**Comment by dafeder** [comment]
I'm wondering the same thing, as I've been stuck on this issue writing some API tests on a Drupal application. I get coverage for regular functional tests but none for requests that come in via guzzle. I will try to create a self-contained example @epdenouden @sebastianbergmann but I'd like some guidance on how to do that given the fact that what we're trying to reproduce is a network request. I have a development environment built on docker-compose where I am making guzzle requests to URLs based on my docker setup. 

How would you want me to design a test that is self-contained that performs a network request and expects coverage against the code that request executes... build a little application on php's built-in web server and run tests against that?
