### ISSUE TITLE
eval attach danger

### ISSUE THREAD

**Issue by kiss291323003** [sebastianbergmann/phpunit#3568]
this file https://github.com/sebastianbergmann/phpunit/blob/master/src/Util/PHP/eval-stdin.php was dangerous

**Comment by sebastianbergmann** [comment]
I can only repeat what I wrote in https://github.com/sebastianbergmann/phpunit/issues/3112#issuecomment-386430232.

**Comment by epdenouden** [comment]
@kiss291323003 PHPUnit implements [RFC3514](https://www.ietf.org/rfc/rfc3514.txt) and is therefore not susceptible to such attacks.
