### ISSUE TITLE
type assertions as functions

### ISSUE THREAD

**Issue by marcosh** [sebastianbergmann/phpunit#3573]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.1
| PHP version         | 7.3
| Installation Method | `git clone`

I noticed that all the assertions `assertIsArray`, `assertIsBool`, ... regarding the type of a variable are implemented only as static methods and not as functions. Is there a reason for this? Could it be useful to add them?

**Comment by sebastianbergmann** [comment]
Duplicate of #3570.
