### ISSUE TITLE
Testsuite name being instantiated without namespace

### ISSUE THREAD

**Issue by redaxmedia** [sebastianbergmann/phpunit#3574]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.0.5
| PHP version         | 7.2.15
| Installation Method | Composer

I have a testsuite named bootstrap that seems to run on each test. I wondered why PHPUnit 8 was freaking slow and caused countless bugs on my testing suite as most of the tests ain't working after running the bootstrap classes of the app before. Everything worked well in PHPUnit 7.

Here comes the example:

```
<testsuite name="bootstrap">
	<directory>tests/unit/Bootstrap</directory>
</testsuite>
```

Renaming it to `_bootstrap` is an workaround - this reminds me on an similar [naming conflict](https://github.com/sebastianbergmann/phpunit/issues/2013) I reported some years ago.

You can see the [errored](https://travis-ci.org/redaxscript/redaxscript/jobs/509878983) and [fixed](https://travis-ci.org/redaxscript/redaxscript/jobs/510131182) build run on Travis CI and related [commit](https://github.com/redaxscript/redaxscript/commit/5cb8e3e6a91fc551641519169ddf70d6b03f1de5).

**Comment by epdenouden** [comment]
Another weird internal runner issue, you say! Delicious, can I play with it?

PHPUnit relies heavily on reflection to make the testing code feel like 'normal' everyday code. The runner code doesn't contain a 'Bootstrap' class that could overlap with the [naming conflict](#2013) you mentioned.

If anything a user warning message would be nice.

**Comment by redaxmedia** [comment]
I managed to isolate the issue and found out that it was introduced in PHPUnit 7.5.2...

Even an empty `<testsuite name="bootstrap"></testsuite>` is causing this - it turns out that not the test to be called were the issue.

PHPUnit seems to use something like `ReflectionClass` on the testsuite names without a proper namespace causing my [Autoloader](https://github.com/redaxscript/redaxscript/blob/develop/includes/Autoloader.php#L73-L83) to load [boostrap.php](https://github.com/redaxscript/redaxscript/blob/develop/includes/bootstrap.php) that is causing my testing suite to malfunction.

## Debug

Debbuging the [load](https://github.com/redaxscript/redaxscript/blob/develop/includes/Autoloader.php#L73-L83) function with `var_dump($className);` gives this output:

PHPUnit 7.5.1: https://pastebin.com/MGwAyEDK
PHPUnit 7.5.2: https://pastebin.com/dDuQxunB (search for bootstrap.php)

## Example

```
<testsuites>
	<testsuite name="a"></testsuite>
	<testsuite name="b"></testsuite>
	<testsuite name="b"></testsuite>
</testsuites>
```

Is going to load `a.php`, `b.php` and `c.php` as of missing namespacing.

**Comment by sebastianbergmann** [comment]
Yay!, just what we need, another problem caused by the legacy crap that is `TestSuite`. Really hope we'll be able to remove `TestSuite` and just work with a collection of `Test` objects in time for PHPUnit 9.

**Comment by epdenouden** [comment]
@sebastianbergmann It's `TestSuites` all the way down. Upgrading some internals for v9 would be lovely. On-demand loading of dataproviders would also be much cleaner, instead of manually managing side-effects.
