### ISSUE TITLE
Scoped PHAR prophecy issue

### ISSUE THREAD

**Issue by TimoBakx** [sebastianbergmann/phpunit#3578]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.0.6
| PHP version         | 7.3.3
| Installation Method | PHAR scoped

Using Prophecy `TypeToken` causes some problems when using the scoped PHAR. Running the same test with the regular PHAR of the same version does not cause any exception or failure.

**Source classes:**
```
namespace App;

class ServiceToMock
{
    public function performAction(string $string): void
    {
    }
}
```

```
namespace App;

class MyService
{
    /**
     * @var ServiceToMock
     */
    private $serviceToMock;

    public function __construct(ServiceToMock $serviceToMock)
    {
        $this->serviceToMock = $serviceToMock;
    }

    public function doSomething(): void
    {
        $this->serviceToMock->performAction('Some string');
    }
}
```

**Test case:**
```
namespace App\Tests;

use App\MyService;
use App\ServiceToMock;
use PHPUnit\Framework\TestCase;
use Prophecy\Argument\Token\TypeToken;

final class MyServiceTest extends TestCase
{
    public function testDoSomething(): void
    {
        $mock = $this->prophesize(ServiceToMock::class);

        $mock->performAction(new TypeToken('string'))
            ->shouldBeCalledOnce();

        $subject = new MyService($mock->reveal());

        $subject->doSomething();
    }
}
```

**Output scoped:**
```
$ php ~/Downloads/phpunit-scoped-8.0.6.phar 
PHPUnit 8.0.6 by Sebastian Bergmann and contributors.

Testing Project Test Suite
E                                                                   1 / 1 (100%)

Time: 86 ms, Memory: 12.00 MB

There was 1 error:

1) App\Tests\MyClassTest::testGetSomeString
Error: Class 'Prophecy\Argument\Token\TypeToken' not found

/Users/timobakx/workspace/opensource/tests/tests/MyClassTest.php:17

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```

**Output unscoped:**
```
$ php ~/Downloads/phpunit-8.0.6.phar  -v
PHPUnit 8.0.6 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.3.3 with Xdebug 2.7.0RC2
Configuration: /Users/timobakx/workspace/opensource/tests/phpunit.xml.dist

Testing Project Test Suite
.                                                                   1 / 1 (100%)

Time: 88 ms, Memory: 12.00 MB

OK (1 test, 1 assertion)
```

**Output scoped with prophecy installed**:
After running `composer req phpspec/prophecy` and trying the scoped phar again.
```
$ php ~/Downloads/phpunit-scoped-8.0.6.phar 
PHPUnit 8.0.6 by Sebastian Bergmann and contributors.

Testing Project Test Suite
E                                                                   1 / 1 (100%)

Time: 89 ms, Memory: 12.00 MB

There was 1 error:

1) App\Tests\MyClassTest::testGetSomeString
PHPUnit\Prophecy\Exception\Call\UnexpectedCallException: Unexpected method call on Double\App\ServiceToMock\P1:
  - performAction(
        "Some string"
    )
expected calls were:
  - performAction(
        exact(Prophecy\Argument\Token\TypeToken:0000000027578044000000005bb2bf46 Object (
            'type' => 'string'
        ))
    )

/Users/timobakx/workspace/opensource/tests/src/MyService.php:20
/Users/timobakx/workspace/opensource/tests/tests/MyClassTest.php:22

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```

**Comment by sebastianbergmann** [comment]
@sebastianfeldmann @theofidry **ping**

**Comment by theofidry** [comment]
Hm I supposed Prophecy should be part of the "shared API", hence completely whitelisted. @sebastianfeldmann I think you can leverage the namespace whitelisting feature for that one.

**Comment by stof** [comment]
Well, maybe not all Prophecy, but at least the `Prophecy\Argument\Token`, `Prophecy\Promise` and `Prophecy\Prediction` namespaces, as these are the public API of configuring test doubles, which can be used in tests

**Comment by stof** [comment]
And the `\Prophecy\Argument` class too, which is an entrypoint to `Prophecy\Argument\Token` with helper methods.

**Comment by stof** [comment]
Also `\Prophecy\Doubler\DoubleInterface` should be whitelisted, to avoid breaking code trying to detect the fact that it is a test double (the symfony/debug component will skip warning about extending `@final` or `@deprecated` classes when the child class is a known test double for instance)

**Comment by sebastianfeldmann** [comment]
I'm not entirely sure what the reasonable thing to do would be.
For simplicity reasons I'm tempted to leave the `Prophecy\*` Namespaces as is, since it belongs to the testing API. Even if not provided by PHPUnit itself.

And prefixing some Prophecy stuff and whitelisting some other can cause problems the Prophecy developers would no experience in their development process.

Any objections?

**Comment by stof** [comment]
yeah, I agree that whitelisting Prophecy entirely is safer here, if that's OK for you.
Being one of the maintainers who might get reports for broken code, I have absolutely no objection for a full whitelisting :smile:

**Comment by sebastianbergmann** [comment]
I have uploaded an updated scoped PHAR to `https://phar.phpunit.de/phpunit-scoped-8.0.6-1-g3faa14214.phar` that was built with 3faa14214cb017d0901380c99bf3fb8eb9f75c21.

Can you please check whether this solves your problem? Thanks!

**Comment by TimoBakx** [comment]
That link gives me a redirect loop.

**Comment by sebastianbergmann** [comment]
Fixed. Thanks!

**Comment by sebastianfeldmann** [comment]
The xdebug issue is fixed

**Comment by TimoBakx** [comment]
The new scoped PHAR works well with both prophecy installed locally (through composer) and not installed. No errors or unexpected failures in my live project either. Thanks for the fix!
