### ISSUE TITLE
[Feature request] Disable colors for report

### ISSUE THREAD

**Issue by BafS** [sebastianbergmann/phpunit#3579]
We use PHPUnit with gitlab CI and it's recommended to disable the colors in order to grep the coverage result (their recommandation is: `phpunit --coverage-text --colors=never` (PHP) - `^\s*Lines:\s*\d+.\d+\%`).

It would be a useful feature to be able to disable colors only for the report (like tap: `tap --coverage-report=text-summary`), specially in CI environment.

Thanks in advance

**Comment by sebastianbergmann** [comment]
I think we have enough arguments, parameters, and options already. If you need a different configuration for CI then use a different configuration file for CI.

**Comment by BafS** [comment]
The problem is not about arguments but, as far as I know, it's currently not possible to disable the colors for the coverage, you need to disable colors for the whole suite (`--colors=never`).

**Comment by Wirone** [comment]
@BafS I had the same issue, what I did is changing test coverage parsing regex to `^.*Lines:\s*(\d+\.\d+)\%` which works with colored PHPUnit output: 

![image](https://user-images.githubusercontent.com/600668/98543863-65e55f80-2293-11eb-9f4c-ae3f3b5f5333.png)

**Comment by BafS** [comment]
Thanks @Wirone !
I would still like to see this option in PHPUnit thought. @sebastianbergmann any feedback regarding the last comments ?
