### ISSUE TITLE
Fatal error triggered in PHPUnit data provider of a test without stacktrace

### ISSUE THREAD

**Issue by SailorMax** [sebastianbergmann/phpunit#3582]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.5.6
| PHP version         | 7.3.2
| Installation Method | Composer

Data provider function can has few include() commands. In any of them we can got Fatal Error. But current error message do not allow to detect where is the problem.

Sample of test (taken from #765):
``` php
<?php
class PhpunitAnnotationsBugTest extends \PHPUnit_Framework_TestCase
{
    public function testDependee()
    {
        $this->assertTrue(true);
    }

    /**
     * @depends testDependee
     * @dataProvider dependentProvider
     */
    public function testDependent($a)
    {
        $this->assertTrue(true);
    }

    public function dependentProvider()
    {
        return include("file1.php") + include("file2.php");
    }
}
```

Sample of file1.php
``` php
<?php
return array(false);
```

Sample of file2.php
``` php
<?php
throw new \Exception;
```

Actual result:
```
1) Warning
The data provider specified for PhpunitAnnotationsBugTest::testDependent is invalid.
```

Expected result:
```
1) Warning
The data provider specified for PhpunitAnnotationsBugTest::testDependent is invalid because of fatal error:
[stacktrace from file2.php line 2]
```

**Comment by epdenouden** [comment]
@SailorMax To clarify: you want the **stacktrace added** to the current error message, I think?

**Comment by SailorMax** [comment]
@epdenouden Yes.

**Comment by epdenouden** [comment]
@SailorMax thx for the update. I have swapped _actual_ and _expected_ in your description.

**Comment by epdenouden** [comment]
This change has been on my to-do list for location hints quite a while. I am currently experimenting with lazy loading of dataproviders, where this specific issue becomes very noticeable.

Note: see also e.g. #3191 and #3493
