### ISSUE TITLE
[8.1.0] MockBuilder Type-Hints broken for PHPStorm/PHPStan

### ISSUE THREAD

**Issue by possi** [sebastianbergmann/phpunit#3589]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.1.0
| PHP version         | 7.2.15
| Installation Method | Composer
| PHPStan version         | 0.10.8

As commented here: https://github.com/sebastianbergmann/phpunit/commit/60db5344ebfeea2212d58273c92dc63a5488e320#r33047915

Type hints for MockBuilder -> getMock() -> method() are broken.
This affects static analysis of IDEs like PHPStorm as well as phpstan. No runtime issue so; phpunit runs fine and _all_ tests pass

**Comment by sebastianbergmann** [comment]
Duplicate of #3588.
