### ISSUE TITLE
./vendor/bin/phpunit cannot find autoload.php

### ISSUE THREAD

**Issue by keithy** [sebastianbergmann/phpunit#3593]
The script is run from `./vendor/bin/phpunit` in /srv/project in this script is: __DIR__

`__DIR__ is /srv/project/vendor/bin`

The search path:

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {

evaluates to: 
```
/srv/project/vendor/bin/../../autoload.php = /srv/project/autoload.php
/srv/project/vendor/bin/../vendor/autoload.php = /srv/project/vendor/vendor/autoload.php
/srv/project/vendor/bin/vendor/autoload.php
```
none of which find autoloader!

Am I missing something? 
I am thinking that my phpunit was copied rather than symbolically linked in, but even so.

**Comment by sebastianbergmann** [comment]
Looks like a Composer issue to me. Which platform are you on? Which version of PHPUnit are you trying to install? How did you install it?

**Comment by keithy** [comment]
I used a remote file upload/sync from Netbeans, from my mac. This means that
### on the mac:
`<project>/vendor/bin/phpunit ->  <project>/vendor/bin/phpunit/../phpunit/phpunit/phpunit`
In this instance `__DIR__` is `<project>/vendor/bin/phpunit/phpunit` and the  first item in the search path find it's mark.
### on the server:
The symbolic link has been replaced with a real copy of the file, so
`__DIR__` is `<project>/vendor/bin` and nothing matches.

The three options appear to cover the first case where phpunit script is run from the vendor package, the last case the phpunit script is the project directory, or in the middle case any first level directory such as <project>/public or <project>/tests.

My situation doesnt appear to be handled, yet it is not exactly a failure mode. I do not want to run composer install on the server every time I sync to get a working system, since I am syncing and running the tests every 3 seconds.

**Comment by sebastianbergmann** [comment]
Probably a NetBeans issue.

**Comment by keithy** [comment]
No its not a net beans issue.

**Comment by keithy** [comment]
The issue is that the search path is WRONG.
