### ISSUE TITLE
Extending the TestRunner not longer possible

### ISSUE THREAD

**Issue by alexander-schranz** [sebastianbergmann/phpunit#3594]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.0 - current (8.1.0)
| PHP version         | 7.3.4
| Installation Method | Composer / PHAR

In Symfony the [TestRunner](https://github.com/sebastianbergmann/phpunit/blob/8.1.0/src/TextUI/TestRunner.php) is currently [extended](https://github.com/symfony/symfony/blob/v4.2.5/src/Symfony/Bridge/PhpUnit/Legacy/TestRunnerForV7.php) to add automatically the SymfonyTestsListener to it.

I tried to make the current [symfony phpunit bridge](https://github.com/symfony/symfony/tree/v4.2.5/src/Symfony/Bridge/PhpUnit) compatible with PhpUnit 8 but the [current solution](https://github.com/symfony/symfony/pull/30085/commits/353ba542b58de42ac5a1c41504f4f3ebc85d1a3b) would remove the final keyword which is really hacky. So is there another way how we could automatically add the SymfonyListener to phpunit?

**Comment by sebastianbergmann** [comment]
Automatically? No. This should be done through the configuration file.

**Comment by alexander-schranz** [comment]
Thank you for your fast response and also for your answer at the symfony issue.
If you don't want to keep this issue in this repository feel free to close this one.
Seems its really the best as you suggested to meet with nicolas to discuss the current issues and what the symfony bridge is doing.
