### ISSUE TITLE
Weird issues with percent encoding

### ISSUE THREAD

**Issue by AliceWonderMiscreations** [sebastianbergmann/phpunit#3597]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.1.0
| PHP version         | 7.3.4
| Installation Method | Composer

When using phpunit to test a class for percent (URI/URL) encoding, when a string contain a single '=' or '=&' the `$this->assertSame($expected, $actual)` function fails.

var_dump of `$actual` from within the unit test script shows that it is in fact what is expected but it looks like `$this->assertSame` does a urldecode on those two characters before doing the comparison.

https://gitlab.com/Pipfrosch/swpress is where my project is.
commit `6bb828b3ecf829b8c16ad95c6db59ff5f1c42ecc` has the class I'm testing as well as the phpunit test for it. I'll try not to push for a little while but I may need to.

code (including vardump that shows `$actual` is correct)

    public function testAlwaysPercentEncodeNonControlCharacters()
    {
        $fixme = '=&';
        $string = '% {}\\^`#!$' . "'" . '()*;<>' . $fixme;
        $expected = '%25%20%7B%7D%5C%5E%60%23%21%24%27%28%29%2A%3B%3C%3E%3D%26';
        $actual = UrlEncode::fragmentEncode($string);
        var_dump($actual);
        $this->assertSame($expected, $actual);
        $actual = UrlEncode::queryEncode($string);
        $this->assertSame($expected, $actual);
        $actual = UrlEncode::pathEncode($string);
        $this->assertSame($expected, $actual);
    }

Not that `urlencode` is my class and is what the unit test is for.
https://gitlab.com/Pipfrosch/swpress/blob/master/psr4/Pipfrosch/NetCom/UrlEncode.php is the class.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by kubawerlos** [comment]
@AliceWonderMiscreations your test is failing on the 2nd assertion - do `var_dump($actual);` before it (but after the `$actual = UrlEncode::queryEncode($string);` to see that at this point `$actual` is not the same as `$expected`.

**Comment by sebastianbergmann** [comment]
No feedback, closing.
