### ISSUE TITLE
setUp doesnt work at all

### ISSUE THREAD

**Issue by keithy** [sebastianbergmann/phpunit#3598]
Well it didnt work, NO CLUE why not, I just get 

"ERROR: application encountered an error and can not continue. Unable to log error."

After a couple of hours of fighting I found out that I need to put a : void thing in!

I feel no need whatsoever for type hinting, I cant see that it serves a purpose in this context, and now its causing problems.

**Comment by sebastianbergmann** [comment]
This is an issue tracker. Not a forum for ranting about things you do not like.
