### ISSUE TITLE
myclabs/deep-copy requires php 7.2 on 1.9.0

### ISSUE THREAD

**Issue by meurissemaPro** [sebastianbergmann/phpunit#3601]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.2.4
| PHP version         | 7.1.X
| Installation Method | Composer / PHAR

The dependance myclabs/deep-copy require php7.2 on the new tag 1.9.0. It's blocking to use phpunit with magento 2 for example.

**Comment by sebastianbergmann** [comment]
PHPUnit 6.5 has reached its end of life, sorry.

**Comment by meurissemaPro** [comment]
Thanks for you reply.

Possible to tag a version with myclabs/deep-copy in 1.8.1 ?
Magento 2 require "phpunit/phpunit": "~6.2.0" but it's not compatible with php 7.2.

**Comment by SlyDave** [comment]
This also affects 7.5.8 - https://github.com/sebastianbergmann/phpunit/issues/3603

deep-copy was updated to 1.9 yesterday, bumping the required version it needs to 7.2, which in effect forces PHPUnit to now require 7.2, when that isn't the case.
