### ISSUE TITLE
How to achieve what assertArraySubset is expected to do?

### ISSUE THREAD

**Issue by goldingdamien** [sebastianbergmann/phpunit#3608]
I was expecting to work like below. It seems that this causes confusion with other people too. How should this be achieved?
```
$this->assertArraySubset([1,2,3], [4,1,5,3,2]) // true
$this->assertArraySubset(["a" => 1, "b" => 2], ["c" => 3, "b" => 2, "a"=> 1]) // true
```

**Comment by sebastianbergmann** [comment]
`assertArraySubset()` is [deprecated and will be removed](https://thephp.cc/news/2019/02/help-my-tests-stopped-working#assertarraysubset).

**Comment by goldingdamien** [comment]
@sebastianbergmann I am sorry, this did not answer my question.
