### ISSUE TITLE
Remove "hack" in JUnit logger

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#3611]
I just stumbled upon

https://github.com/sebastianbergmann/phpunit/blob/e5cf7828f463ebc970d041ef75af643ca56f9f7b/src/Util/Log/JUnit.php#L372-L379

Can @mrook (or somebody else from @phingofficial) provide feedback whether this method is still needed? Ideally I would like to remove it. At the very least I would like to change `/*bool*/ $flag` to `bool $flag`. The latter would not be a BC break as the class in question is not covered by the backward compatibility promise for PHPUnit.

**Comment by mrook** [comment]
Thanks for raising this! As of right now we are still using it. I'll see if we can drop "our" end of the hack, changing it to `bool $flag` would not be a problem for us.

**Comment by mrook** [comment]
Tagging @siad007 from @phingofficial.

**Comment by epdenouden** [comment]
@sebastianbergmann looks like itt can be `bool` without any fear of breakage:

![image](https://user-images.githubusercontent.com/26651359/56672648-16424180-66b7-11e9-8573-beda297422e2.png)

@mrook @siad007 looks safe to you, too?

**Comment by sebastianbergmann** [comment]
Already is `bool` as of 21ee615b3e8ce3f3e7282956555b1491debb55a6.

**Comment by siad007** [comment]
@sebastianbergmann feel free to remove the method entirely. It is not needed any longer. See https://github.com/phingofficial/phing/commit/8da0c5441061721a871aa1d9ca1871d1ed3c5e73
