### ISSUE TITLE
Deprecate support for "ClassName<*>" as values for @covers and @uses annotations

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#3630]
PHPUnit 9 should raise a warning for the following annotations:
* `@covers ClassName::<public>`
* `@covers ClassName::<protected>`
* `@covers ClassName::<private>`
* `@covers ClassName::<!public>`
* `@covers ClassName::<!protected>`
* `@covers ClassName::<!private>`
* `@uses ClassName::<public>`
* `@uses ClassName::<protected>`
* `@uses ClassName::<private>`
* `@uses ClassName::<!public>`
* `@uses ClassName::<!protected>`
* `@uses ClassName::<!private>`

**Comment by andrewnicols** [comment]
Is there any documentation or information about what these will be replaced by?

**Comment by sebastianbergmann** [comment]
There will be no replacement.
