### ISSUE TITLE
The requirement of having one test class per source file is not properly enforced

### ISSUE THREAD

**Issue by dmitri--** [sebastianbergmann/phpunit#366]
According to issue #364, a source file is not allowed to have more than one test case class. Hence there two related  problems:
1) this requirement is not documented
2) this requirement is not properly enforced
it can be enforced like below:

    PHPUnit_Util_Class::collectStart();
    $filename   = PHPUnit_Util_Fileloader::checkAndLoad($filename, $syntaxCheck);
    $newClassesFound = PHPUnit_Util_Class::collectEnd();
    $newClasses = array();
    $baseName   = str_replace('.php', '', basename($filename));

    foreach ($newClassesFound as $className) {
        if (substr($className, 0 - strlen($baseName)) == $baseName) {
            $class = new ReflectionClass($className);

            if ($class->getFileName() == $filename) {
                $newClasses = array($className);
                break;
            }
        }
    }

btw (just fyi), some other people were not awaqre of this requirement too, and for example PEAR/tests/HTTP_Request2/Request2/Adapter/SkippedTests.php contains 3 test classes

also I have to add that the following line is not exactly correct:

    $baseName   = str_replace('.php', '', basename($filename)); .

What if file name is "abra.phpcarabra.php" ? then it will set $baseName to  "abracadabra" instead of "abra.phpcarabra" (which I think is supposed to happen)

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
