### ISSUE TITLE
Add @covers annotations to all tests

### ISSUE THREAD

**Issue by oliverklee** [sebastianbergmann/phpunit#3671]
I'd like to tackle this so the code coverage report is more accurate.

@sebastianbergmann  Any objections? Or things I'll need to take into consideration when doing this?

**Comment by sebastianbergmann** [comment]
I am afraid that this will not be as easy as it should be. You may want to start with the tests for the `PHPUnit\Util` classes. Most of them should be isolated enough for this to be not as frustrating as I expect `PHPUnit\Framework` to be, for instance.

**Comment by oliverklee** [comment]
.
