### ISSUE TITLE
PHP segfault tests marked as passed with process isolation

### ISSUE THREAD

**Issue by vedadkajtaz** [sebastianbergmann/phpunit#3690]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.1.4
| PHP version         | 7.3.5
| Installation Method | FreeBSD port

Some of my tests are crashing the php process (SIGSEGV) due to xdebug + opcache interoperability issues.

However, when running phpunit with process isolation, those tests are reported as successfully passed. I guess an exception should be thrown should proc_close() return nonzero exit status.

This occurs with PHPUnit 6.* as well.

**Comment by sebastianbergmann** [comment]
Likely a duplicate of #3677.

**Comment by vedadkajtaz** [comment]
Indeed!

**Comment by sebastianbergmann** [comment]
Independent of when the segfault occurs, when PHP segfaults then the child process does not pass a valid result to the parent process. As far as I am concerned, this is a duplicate of #3677.
