### ISSUE TITLE
phpunit produces segfault

### ISSUE THREAD

**Issue by Phillip85** [sebastianbergmann/phpunit#3695]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.1.5
| PHP version         | 7.3.5, 7.2.17
| Installation Method | Composer 

Not sure if it is a bug in PHP or a bug in phpunit, 
But running phpunit is the only way how I can reproduce it.

Class:

```
class SegfaultClass
{
    function test()
    {
        $a = new ArrayObject();
        $a->append(new TestObject());
        $a->append(new TestObject());
        $a->append(new TestObject());

        $a->uasort([$this, 'order']);
    }

    function order($a, $b)
    {
        if ($a == $b) {
            throw new Exception("order failed");
        }
        return ($a > $b ? 1 : -1);
    }
}
```

Test:

```
use PHPUnit\Framework\TestCase;

class bugClassTest extends TestCase
{
    function test_segfault()
    {
        $this->expectException(Exception::class);
        $t = new SegfaultClass();
        $t->test();
    }
}
```

Output:
```
~/PhpstormProjects/test_bug_phpunit$ php7.3 vendor/bin/phpunit 
PHPUnit 8.1.5 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.3.5-1+ubuntu18.04.1+deb.sury.org+1
Configuration: /home/pg/PhpstormProjects/test_bug_phpunit/phpunit.xml

Segmentation fault (core dumped)
```

Same Test with other expectException  does not produce a segfault:

```
use PHPUnit\Framework\TestCase;

class bugClassTest extends TestCase
{

    function test_no_segfaults()
    {
        $this->expectException(ErrorException::class);
        $t = new SegfaultClass();
        $t->test();
    }
}
```
Output:

```
php7.3 vendor/bin/phpunit 
PHPUnit 8.1.5 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.3.5-1+ubuntu18.04.1+deb.sury.org+1
Configuration: /home/pg/PhpstormProjects/test_bug_phpunit/phpunit.xml

F                                                                   1 / 1 (100%)

Time: 19 ms, Memory: 6.00 MB

There was 1 failure:

1) bugClassTest::test_segfault
Failed asserting that exception of type "Exception" matches expected exception "ErrorException". Message was: "order failed" at
/home/pg/PhpstormProjects/test_bug_phpunit/src/SegfaultClass.php:18
/home/pg/PhpstormProjects/test_bug_phpunit/src/SegfaultClass.php:13
/home/pg/PhpstormProjects/test_bug_phpunit/tests/bugClassTest.php:12
.

FAILURES!
Tests: 1, Assertions: 1, Failures: 1.
```

When I change the Exeption in SegfaultClass to ErrorException the first example works, but the second one crashes.

**Comment by sebastianbergmann** [comment]
You have found a problem in the PHP runtime that leads to a [segmentation fault](https://en.wikipedia.org/wiki/Segmentation_fault). An issue like this has to be reported at https://bugs.php.net/report.php using a minimal, self-contained, reproducing test case.

Please note that a test case that needs to be run through PHPUnit does not qualify as either "minimal" or "self-contained" when reporting bugs for the PHP runtime. Best practices for reporting bugs in PHP are documented [here](https://bugs.php.net/how-to-report.php).

In the case that the segmentation fault happens during continuous integration on [TravisCI](http://travis-ci.org/) then you can [troubleshoot the problem locally using Docker](https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image).
