### ISSUE TITLE
Split composer.json for PHARs

### ISSUE THREAD

**Issue by theofidry** [sebastianbergmann/phpunit#3696]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.0+
| PHP version         | N/A
| Installation Method | Composer & PHAR

As of now, PHPUnit uses a single `composer.json` without a `composer.lock`.

Regarding committing the `composer.lock`: I think in general it's a good practice for projects publishing a PHAR since like for a regular application, you may want to have a firmer control on your dependencies and which ones you update for the next release. It's however not a requirement by any means and if there is enough checks to guarantee that the PHAR just works with non-locked dependencies, why not.

That small parenthesis aside, the main point: having only one `composer.json` is a bit inconvenient since it requires to ship dependencies used only for the PHPUnit PHAR, which are useless if you are installing PHPUnit as a package. Maybe a relatively simple solution would be to:

- Keep the current `composer.json` but trim it down from non library specific settings (e.g. the platform setting) and unnecessary dependencies
- Add a new `composer.json` which with the help of a plugin such as [wikimedia/composer-merge-plugin](https://github.com/wikimedia/composer-merge-plugin) can contain the PHAR specific settings/dependencies and "inherit" from the root `composer.json`

What do you think?

**Comment by sebastianbergmann** [comment]
There are no dependencies that are "used only for the PHPUnit PHAR" and there is nothing specific to `phpunit.phar` in `composer.json`.

**Comment by theofidry** [comment]
Aren't the phar-io dependencies used only for the PHAR?

**Comment by sebastianbergmann** [comment]
Not really.

**Comment by theofidry** [comment]
Well, if there is none it's a non-issue then :)
