### ISSUE TITLE
testdox - Better Logging

### ISSUE THREAD

**Issue by Goahnary** [sebastianbergmann/phpunit#3704]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.5.11
| PHP version         | 7.2.17
| Installation Method | Composer / PHAR

I have a feature request. Currently I'm running into an issue when using [paratest](https://github.com/paratestphp/paratest) to run tests in parallel. Since the tests are run in parallel the log file is truncated by the last test and you only get the result of the last test. Basically a race condition. It is outlined in [this issue here](https://github.com/paratestphp/paratest/issues/273).

One solution would be to add an option to log individual files for each test. Then maybe you could concatenate the results at the end with paratest. I wanted to get input from the team though. What could we do to alleviate this issue? Is there a workaround I'm not thinking of?

**Comment by Goahnary** [comment]
So, in order to allow a user to request timestamps be prepended to the logfile name I have added this code to the Configuration.php line (+ indicates an added line):
```php
public function getLoggingConfiguration(): array
    {
        $result = [];

        foreach ($this->xpath->query('logging/log') as $log) {
            \assert($log instanceof DOMElement);

            $type   = (string) $log->getAttribute('type');
+            if ($log->getAttribute('timestamps') == true){
+                $target = (string) time() . "-" . $log->getAttribute('target');
+            } else {
                $target = (string)$log->getAttribute('target');
+            }
```

However I am getting an error: 
```
 Warning - The configuration file did not pass validation!
 The following problems have been detected:

  Line 19:
  - Element 'log', attribute 'timestamps': The attribute 'timestamps' is not allowed.

 Test results may not be as expected.
```
How can I allow this attribute?

**Comment by sebastianbergmann** [comment]
The validation of `phpunit.xml` is based on `phpunit.xsd`.

**Comment by sebastianbergmann** [comment]
I do not think that this problem should be addressed in PHPUnit. If you wrap a tool for parallel execution around PHPUnit then PHPUnit should only generate machine-readable output such as the XML logfiles generated by `--log-junit` and `--coverage-clover`, for instance. Personally, I would prefer the combined (test result and code coverage) XML report genereated by `--coverage-xml`.

The tool that wraps PHPUnit should then aggregate the XML genereated by the individual (and parallely executed) PHPUnit processes and generate human-readable output such as TestDox.

**Comment by Goahnary** [comment]
Thanks for your insight @sebastianbergmann. 

The issue I was running into was the overwriting of the log file. Reading that output and saving it seems to be a harder task to accomplish than allowing an option for unique log files in phpunit and then stitching the logs together with paratest. I am no expert programmer by any means though. I also understand if you do not want bloat for specific situations.

I have not tried `--log-junit`, `--coverage-clover`, or `--coverage-xml`. I will look into this and see if I can get this working. 

I have the code for this already written and I have put in a [pull request](https://github.com/sebastianbergmann/phpunit/pull/3711) for review. It only changes 14 lines. If you do not want to include it that is fine I will look into other solutions.

This was my first time working on an open source project ^_^ I'm pretty happy with the experience.

**Comment by sebastianbergmann** [comment]
Closing (see https://github.com/sebastianbergmann/phpunit/pull/4037#issuecomment-584144345 for details).
