### ISSUE TITLE
Add phpunit --init option

### ISSUE THREAD

**Issue by jwage** [sebastianbergmann/phpunit#3705]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | x.y.z
| PHP version         | x.y.z
| Installation Method | Composer / PHAR

Would you consider a new feature to help with new users getting started with `phpunit` that works like this:

```bash
$ mkdir newproject
$ cd newproject
$ composer require phpunit/phpunit
```

User runs phpunit for the first time:

```bash
$ ./vendor/bin/phpunit
Could not locate a config XML file in path /data/repositories/newproject. Have you run 'phpunit --generate-configuration' ?
```

Then user runs `phpunit` again with `--generate-configuration`:

```bash
$ ./vendor/bin/phpunit --generate-configuration
```

Or could even make it have less friction for a brand new user and offer an `--init` option that doesn't prompt the user for anything and uses sane modern defaults:

```bash
$ ./vendor/bin/phpunit --init
```

The `--init` option would do the following:

- Generates the `phpunit.xml.dist`
- Creates a `tests` directory with an example test

Now the user can run `phpunit` again and see it in action. It is a small thing, but I think it would improve the developer experience. I got the idea from https://github.com/vimeo/psalm. I have been helping a few people start some new projects and the `--generate-configuration` gets me most of what I need but most people don't know it is a thing when getting started so telling them about it right after `composer require` at a minimum would help.

**Comment by sebastianbergmann** [comment]
Please open two separate tickets for the enhancements you propose. Thanks!
