### ISSUE TITLE
Self-referencing PHP array in data provider has different serialized value

### ISSUE THREAD

**Issue by ntzm** [sebastianbergmann/phpunit#3707]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.1.5
| PHP version         | 7.3.5
| Installation Method | Composer

Given this test case:

```php
<?php

class Test extends \PHPUnit\Framework\TestCase
{
    /** @dataProvider provideThings */
    public function testThing($value, $serialized)
    {
        $this->assertSame($serialized, serialize($value));
    }

    public function provideThings()
    {
        $a = [];
        $a[0] = &$a;

        return [
            [
                $a,
                serialize($a),
            ]
        ];
    }
}
```

It fails, where you would expect the serialized value to be the same as when it was serialized in the data provider

```diff
-'a:1:{i:0;a:1:{i:0;R:2;}}'
+'a:1:{i:0;N;}'
```

**Comment by UBERPHP** [comment]
this  http://webreflection.blogspot.com/2009/09/php-serialization-and-recursion.html
and this link might be helpful: https://code.google.com/archive/p/formaldehyde/source/default/source

personally, I never use references. It's possible to fix it, but it would lead to huge performance degradation.

**Comment by kubawerlos** [comment]
@sebastianbergmann this is no longe happening, both values from `assertSame` are `'a:1:{i:0;a:1:{i:0;R:2;}}'` on the latest`10.5` branch.
