### ISSUE TITLE
Boilerplate in code documentation ?

### ISSUE THREAD

**Issue by albert-github** [sebastianbergmann/phpunit#3712]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | x8.6.1
| PHP version         | ---
| Installation Method | source tree

On a lot of places in the code I see in the code documentation:
```
  * @throws ExpectationFailedException
  * @throws \SebastianBergmann\RecursionContext\InvalidArgumentException
  * @throws Exception

```

This looks like it is boilerplate code to me.

- is this boilerplate code or not?

**Comment by sebastianbergmann** [comment]
The `@throws <type>` annotation is used to document the fact that an exception of type `<type>` can be raised by a method.

**Comment by albert-github** [comment]
Sorry I don't understand why it says
```
* @throws \SebastianBergmann\RecursionContext\InvalidArgumentException
```
the part :
```
* @throws Exception
```
as I found this in a (by head) `invalidArgumentFactory`.

(Note I'm not a php programmer, I'm looking at it from the documentation point of view).
