### ISSUE TITLE
assertEquals fails to compare objects : Object of class () could not be converted to string

### ISSUE THREAD

**Issue by KarlisJ** [sebastianbergmann/phpunit#3716]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.5.11
| PHP version         | 7.1.17
| Installation Method | Composer

`assertEquals` fails to compare two objects with error message:
```
 PHPUnit\Framework\ExceptionWrapper  : Object of class App\Products\NestedProductProperties\ProductPlan could not be converted to string
```

The code:
```
protected function assertProductProperty($key, $value, Product $product)
{
    $actual_value = $product->{$key};
    dump($actual_value);
    dump($value);
    Assert::assertEquals($value, $actual_value, "The {$key} should be <{$value}>");
}
```
I have put the dump to make sure that the object are as expected - objects and equal.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by kubawerlos** [comment]
It looks like the problem is not with the assertion, but with the message: `"The {$key} should be <{$value}>"` - PHP tries to cast `$value` to string and it's an object.
