### ISSUE TITLE
Clear unsupported version tags from packagist

### ISSUE THREAD

**Issue by finwe** [sebastianbergmann/phpunit#3724]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 5.0.0
| PHP version         | *
| Installation Method | Composer

Currently, with composer version constraint set to `^5.0`, the last 5.x version is installed. But, given that lower 5.x versions are no longer present as tags in PHPUnit repository, running `composer update --prefer-lowest` produces weird results - sometimes installing even `v8.0.2-1-ge82a4db` version.

Cleanup of packagist tags would clear things up in this regard

**Comment by sebastianbergmann** [comment]
I do not know what you are talking about. No tags have been deleted. For instance, the PHPUnit 5.* tags are still there:
```
$ git tag | grep ^5
5.0.0
5.0.1
5.0.10
5.0.2
5.0.3
5.0.4
5.0.5
5.0.6
5.0.7
5.0.8
5.0.9
5.1.0
5.1.1
5.1.2
5.1.3
5.1.4
5.1.5
5.1.6
5.1.7
5.2.0
5.2.1
5.2.10
5.2.11
5.2.12
5.2.2
5.2.3
5.2.4
5.2.5
5.2.6
5.2.7
5.2.8
5.2.9
5.3.0
5.3.1
5.3.2
5.3.3
5.3.4
5.3.5
5.4.0
5.4.1
5.4.2
5.4.3
5.4.4
5.4.5
5.4.6
5.4.7
5.4.8
5.5.0
5.5.1
5.5.2
5.5.3
5.5.4
5.5.5
5.5.6
5.5.7
5.6.0
5.6.1
5.6.2
5.6.3
5.6.4
5.6.5
5.6.6
5.6.7
5.6.8
5.7.0
5.7.1
5.7.10
5.7.11
5.7.12
5.7.13
5.7.14
5.7.15
5.7.16
5.7.17
5.7.18
5.7.19
5.7.2
5.7.20
5.7.21
5.7.22
5.7.23
5.7.24
5.7.25
5.7.26
5.7.27
5.7.3
5.7.4
5.7.5
5.7.6
5.7.7
5.7.8
5.7.9
```

**Comment by finwe** [comment]
Oh, sorry, got confused by GitHub search which doesn't show 5.0.0. I've got composer installation with 5.0.0, but I am unsure if that's not composers fault. Will investigate more.
