### ISSUE TITLE
PhpUnit stopped throwing \PhpUnit\Error in PHP 7.4

### ISSUE THREAD

**Issue by Danon** [sebastianbergmann/phpunit#3725]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.5.12
| PHP version         | 7.4.0
| Installation Method | Composer

I noticed my library build failed: https://travis-ci.org/T-Regx/T-Regx

The reason is:
```bash
1) Test\Integration\TRegx\CleanRegex\Match\Details\NotMatchedTest::shouldNotCastToString
Failed asserting that exception of type "Error" matches expected exception "PHPUnit\Framework\Error\Error". Message was: "Object of class TRegx\CleanRegex\Match\Details\NotMatched could not be converted to string" at
/home/travis/build/T-Regx/T-Regx/test/Integration/TRegx/CleanRegex/Match/Details/NotMatchedTest.php:33
```

normally, when I forced the error (by casting to string an object without `__toString()`) i received in fact `PHPUnit\Framework\Error\Error`. In PHP 7.4. i receive `\Error`.

Is this a bug?

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by Danon** [comment]
@sebastianbergmann Just a quick question. Exactly when would PhpUnit throw `PHPUnit\Framework\Error\Error` by design? Anytime when a php error is raised during test case execution? Or are the more subtle rules for the phpunit error?

**Comment by sebastianbergmann** [comment]
PHPUnit's error handler throws `PHPUnit\Framework\Error\Error` when it handles an `E_ERROR` or `E_USER_ERROR` (see https://github.com/sebastianbergmann/phpunit/blob/8.2.3/src/Util/ErrorHandler.php#L74).

**Comment by redaxmedia** [comment]
Hello,

I have similar issue using `php 7.4 snapshot` on Travis CI using PHPUnit 8.1.x and `convertWarningsToExceptions`.

```
Function ReflectionType::__toString() is deprecated
```

It only happens in tests using `getMockBuilder` so this must be related to the deprecation:
https://php.net/manual/de/reflectiontype.tostring.php

**Comment by nikic** [comment]
This is due to https://wiki.php.net/rfc/tostring_exceptions. PHP now throws `Error` exception instead of `E_RECOVERABLE_ERROR`.

**Comment by sebastianbergmann** [comment]
Thank you, @nikic.
