### ISSUE TITLE
Fatal in CliTestDoxPrinter.php when test case is of instance of TestSuite

### ISSUE THREAD

**Issue by Owersun** [sebastianbergmann/phpunit#3730]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.5.13
| PHP version         | 7.2.19
| Installation Method | Composer

On line 110 of CliTestDoxPrinter.php $test is evaluated to be either TestCase or PhpTestCase or TestSuite.
On following line 118 condition assigns values only for cases of $test being TestCase or PhpTestCase due to if/elseif without else clause.
This leads to $this->className be null
This leads to fatal failure on line 248 at the time of call to $this->formatTestSuiteHeader() with second parameter "$this->className" being null and the method accepting non-nullable string as second parameter.

Repro steps:
- have any test be something else than TestCase or PhpTestCase, for example DataProviderTestSuite
- run phpunit with --testdox option

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by Owersun** [comment]
`<?php

class someTest extends PHPUnit\Framework\TestCase {

    public static function setUpBeforeClass() {
        self::markTestSkipped('this is what\'s going to make it fail');
    }

    /**
     * @dataProvider theDataProviderThatIsRequiredToBeInTheTest
     */
    public function testThatHasToHaveDataProvider($a, $b, $c, $d, $e) {
    }

    public function theDataProviderThatIsRequiredToBeInTheTest() {
        return [
            ['never', 'going', 'to', 'test', 'anything']
        ];
    }

}
`

**Comment by epdenouden** [comment]
@Owersun A nice little edge case on the Mondaymorning! I'll check into it.
@sebastianbergmann I'm knee-deep in `DataProviderTestSuite` at the moment, I can make a fix for this tonight.
