### ISSUE TITLE
SegFault in set upping test in \PHPUnit\Framework\TestSuite:574 

### ISSUE THREAD

**Issue by JacksonGH** [sebastianbergmann/phpunit#3732]
more information in pull request #3731.

**Comment by sebastianbergmann** [comment]
You have found a problem in the PHP runtime that leads to a [segmentation fault](https://en.wikipedia.org/wiki/Segmentation_fault). An issue like this has to be reported at https://bugs.php.net/report.php using a minimal, self-contained, reproducing test case.

Please note that a test case that needs to be run through PHPUnit does not qualify as either "minimal" or "self-contained" when reporting bugs for the PHP runtime. Best practices for reporting bugs in PHP are documented [here](https://bugs.php.net/how-to-report.php).

In the case that the segmentation fault happens during continuous integration on [TravisCI](http://travis-ci.org/) then you can [troubleshoot the problem locally using Docker](https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image).
