### ISSUE TITLE
forceCoversAnnotation does not behave as documented

### ISSUE THREAD

**Issue by andrewnicols** [sebastianbergmann/phpunit#3733]
The [documentation](https://phpunit.readthedocs.io/en/8.2/configuration.html) for `forceCoversAnnotation` states:

> Code Coverage will only be recorded for tests that use the `@covers` annotation documented in `@covers`.

Therefore I'd argue that it the presence of the configuration setting is entirely relevant to whether code coverage data should be collected.

However with this setting enabled, code coverage is still recorded, and then at the end of the test during the filtering stage that coverage data is thrown away.

I'd argue that PHPUnit should really respect the setting and not even attempt to _record_ coverage data if there is no `@covers` annotation when the `forceCoversAnnotation` configuration setting is enabled. However @sebastianbergmann has also stated in #3701 that:

> The @forceCoversAnnotations should not have anything to with whether or not code coverage data is collected.

So either the documentation is wrong, or there is a bug in the code.

Personally I feel that the code is wrong as it makes no sense to generate coverage only to throw it away.

This has a potentially huge impact on larger codebases.

**Comment by sebastianbergmann** [comment]
The documentation was fixed in https://github.com/sebastianbergmann/phpunit-documentation-english/commit/a4c37d3e62b10f1ca5f0dfcf6a04e2b9988600c1.
