### ISSUE TITLE
verifyMockObjects() is now private

### ISSUE THREAD

**Issue by sylfabre** [sebastianbergmann/phpunit#3734]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.1.6
| PHP version         | 7.2.15
| Installation Method | Composer

We are migrating from PHPUnit 5 to PHPUnit 8.
And we have discovered that `verifyMockObjects()` is now a private method.

We use it a lot in our tests like this:
- set up some context for the test
- mock some objects
- run some user-land code
- assert it works well with `verifyMockObjects()`
- mock some more objects
- run some user-land code
- assert it works well with `verifyMockObjects()`
- ...

An example would be an iterator: 
- we check it once set up
- we check it after the first loop
- we check it after the second loop
- ...

Using `verifyMockObjects()` helps us to set up some milestone in the test.
Is there a workaround or a best practice we should be aware of since `verifyMockObjects()` is now private?

Thanks!

**Comment by sylfabre** [comment]
@sebastianbergmann would you accept a PR to make this method protected instead of private?

**Comment by sebastianbergmann** [comment]
I am sorry that this causes you grief but this will stay `private`.

**Comment by sylfabre** [comment]
@sebastianbergmann any workaround or best practice on how to use it in my use case (see my first message about iterator)?

**Comment by clement-fleury-assoconnect** [comment]
> 
> 
> @sebastianbergmann any workaround or best practice on how to use it in my use case (see my first message about iterator)?

@sebastianbergmann any answer to this question ?
