### ISSUE TITLE
[FEATURE] Provide a way to immediately show test warnings/errors during run

### ISSUE THREAD

**Issue by mfn** [sebastianbergmann/phpunit#3737]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.2.3
| PHP version         | 7.3.6
| Installation Method | Composer / ~PHAR~

I'm creating this issue to gather feedback on the following topic:
- have a way to immediately report warnings/errors during test run
  - do **not** collect and report them at the end
- do **not** report successful executions, only warnings/errors

The application for this would be:
- long running test suites
- for example in CI environments with realtime logging
- so the developers can react earlier and already look into fixes for failed tests instead of having to wait for the end of the run

Existing solutions:
- Inspired by this project which does exactly this: https://github.com/ScriptFUSION/PHPUnit-Immediate-Exception-Printer
  - The current release does not work with the latest and greatest PHPUnit
  - Development seems stalled
  - Contributing/Forking is certainly possible but maybe phpunit itself is interested in getting this feature
- Both `--teamcity` and `--testdox` work in the way that they immediately report warnings/errors **but** they also report positives which can be a _lot of noise_.

The idea is that instead of having to stare at a million `.` and wait for the feedback, see it as soon as it happens.

The output should be condensed to only failures, to be consumed by humans. The existing/default error format (personally) is fine as long as I would be able to see it ASAP.

Would the phpunit project be willing to consider such an feature being an integral part of it?

**Comment by sebastianbergmann** [comment]
I am not convinced that this should be added to PHPUnit itself and think that it should be implemented in a custom test listener / test result printer.

**Comment by mfn** [comment]
> I am not convinced that this should be added to PHPUnit itself and think that it should be implemented in a custom test listener / test result printer.

Makes sense!

I initially wrote:
> Inspired by this project which does exactly this: https://github.com/ScriptFUSION/PHPUnit-Immediate-Exception-Printer
> - The current release does not work with the latest and greatest PHPUnit

I thus created an adapted version, which works with the latest and greatest PHPUnit version => https://github.com/mfn/phpunit-immediate-exception-printer

It also has a configuration option to truly _only_ show errors/failures during the runtime of the tests so, especially for CI, it's reduced to the minimum.
