### ISSUE TITLE
Must provide `--whitelist` even when Xdebug whitelist script is used

### ISSUE THREAD

**Issue by rask** [sebastianbergmann/phpunit#3740]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.*
| PHP version         | 7.3
| Installation Method | Any

When using Xdebug coverage filter via the `--prepend` argument, PHPUnit still requires the `--whitelist` argument in order to generate code coverage.

```sh
$ cat ./filter.php
<?php

\xdebug_set_filter(
    \XDEBUG_FILTER_CODE_COVERAGE,
    \XDEBUG_PATH_WHITELIST,
    ['/path/to/project/src']
);

```

```sh
$ phpunit --prepend=./filter.php ./tests/suite --coverage-html=./coverage
> ...
> Error: Incorrect whitelist config, no code coverage will be generated.
> ...
```

When I provide the `--whitelist` argument, it works:

```sh
$ phpunit --dump-xdebug-filter=./filter.php
$ phpunit --prepend=./filter.php ./tests/suite --coverage-html=./coverage --whitelist=/path/to/project/src
> ...
```

---

Or is this the way it is intended to work?

**Comment by sebastianbergmann** [comment]
At the moment, yes, this is the way it must be. Not sure we can remove the need for the redundancy here (in a robust way).

**Comment by sebastianbergmann** [comment]
I am closing this because of #4226 (and #4227).
