### ISSUE TITLE
Add option to sort tests based on information from @small, @medium, and @large

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#3748]
* Tests annotated with `@small` should be run before tests annotated with `@medium`
* Tests annotated with `@medium` should be run before tests annotated with `@large`
* Tests annotated with `@large` should be run before tests not annotated with `@small`, `@medium`, or `@large`

**Comment by localheinz** [comment]
Should this be an additional sorting strategy, or the default?

**Comment by sebastianbergmann** [comment]
Additional sorting strategy, of course. Sorry for not being clear.

**Comment by epdenouden** [comment]
I'll make this tomorrow. It's a nice little reprieve from the data providers

**Comment by epdenouden** [comment]
Something is wrong with the execution sorting as `--order-by=depends,reverse' brings up the whole `TestCaseTest::testGlobalsBackup[Pre|Post]` again and `tests/end-to-end/execution-order/test-order-reversed-with-dependency-resolution.phpt` doesn't seem to catch it.

**Comment by epdenouden** [comment]
Let me know if you'd rather have a pull request based on `8.2` :)
