### ISSUE TITLE
PHP Unit testing fails to pass all test

### ISSUE THREAD

**Issue by naumanjkhan** [sebastianbergmann/phpunit#3759]
## Unit Test
```
class OffsetTest extends \PHPUnit\Framework\TestCase
{
   public function testIllegalParameters($offset)
    {
        new \Offset($offset);

        $this->fail('Exception should be thrown');
    }
   /**
     * Data provider for {@link OffsetTest::testIllegalParameters()}
     * @return array
     */
    public function getIllegalOffsets()
    {
        return [
            [-1],
        ];
    }
}
```
## My Class
```
class Offset
{
    public function __construct(int $offset = 13)
    {
       try {
            if ($offset < 0) {
                throw new Exception('Exception should be thrown');
            }
        } catch (Exception $e) {
            return $e->getMessage();
        }
        $this->offset = $offset;
    }
}
```

This how the test progress go
![Capture](https://user-images.githubusercontent.com/6325503/61353105-67ae3700-a888-11e9-8fdd-1e89120c2d40.PNG)
I want all to be passed

I run it via composer test getIllegalOffsets() provides the feed -1 for the test

**Comment by sebastianbergmann** [comment]
Is `getIllegalOffsets()` supposed to be a data provider?

**Comment by naumanjkhan** [comment]
@sebastianbergmann  yes

**Comment by sebastianbergmann** [comment]
Then `testIllegalParameters()` is missing the `@dataProvider` annotation.

**Comment by naumanjkhan** [comment]
@sebastianbergmann updated

**Comment by sebastianbergmann** [comment]
You need
```php
/**
 * @dataProvider getIllegalOffsets
 */
public function testIllegalParameters($offset)
```
not the other way around.

**Comment by naumanjkhan** [comment]
I can't change the test file as it is provided by the team to test against?

Test gives the following output
There were 1 failure:
1) OffsetTest::::testIllegalParameters with data set #0 (-1)
Exception should be thrown

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.

**Comment by naumanjkhan** [comment]
Ok, sorry to bother you, just let me know what does the following do?
```$this->fail('Exception should be thrown');```

**Comment by epdenouden** [comment]
@naumanjkhan it marks the running test as a failure with the mesage you give it.
