### ISSUE TITLE
Show message "This test did not perform any assertions" in IDE when the asserts in another function

### ISSUE THREAD

**Issue by ke-liang** [sebastianbergmann/phpunit#3764]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.5.9
| PHP version         | 7.1.13
| Installation Method | manual install PHAR
| IDE | PHPStorm

I update PHPUnit version from 5.7 to 7.5.9 in my MAC, and then run one unit test case in IDE, the case like below, the asserts in another function

```
/**
 * 创建 job
 * @throws \Exception
 */
function testCreateJob()
{
    $data = array(
        'id' => time()
    );
    echo "===============Create job===============\n";
    $createRes = HttpRequest::curlHttpRequest(false, 'POST', '/v1/jobs', $data);
    JobChk::createJobCheck($data, $createRes);
}
```
unfortunately, I see the message "This test did not perform any assertions" in IDE, it mark this case as failed, but in fact it pass! so do you have any ideas for this problem? 

P.S.
Run phpunit.xml is ok, since I add beStrictAboutTestsThatDoNotTestAnything="false"

**Comment by sebastianbergmann** [comment]
This issue tracker is for the Open Source project that provides the PHPUnit testing framework as well as the CLI tool for executing tests.

Please report issues with regards to IDE integration to the vendor of your IDE.

**Comment by ke-liang** [comment]
> This issue tracker is for the Open Source project that provides the PHPUnit testing framework as well as the CLI tool for executing tests.
> 
> Please report issues with regards to IDE integration to the vendor of your IDE.

Thanks for your reply!
If I downgrade phpunit to 5.7.9, it mark the same case succeeded, and not show the message "This test did not perform any assertions" in the same IDE, and I find out that the var "beStrictAboutTestsThatDoNotTestAnything" is set to "false" in phpunit 5.7.9, but set to "true" in  phpunit 7.5.0, is this the reason why it mark the case failed?
