### ISSUE TITLE
whitespace in results

### ISSUE THREAD

**Issue by TriplePro** [sebastianbergmann/phpunit#3767]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.2.5
| PHP version         | 7.3.5
| Installation Method | PHAR

in phpstorm 2019.2 there is a lot of whitespace ( newline characters ) printed between:

"PHPUnit 8.2.5 by Sebastian Bergmann and contributors."
and
"Time: 999ms, Memory: 16.00 MB"

**Comment by sebastianbergmann** [comment]
This issue tracker is for the Open Source project that provides the PHPUnit testing framework as well as the CLI tool for executing tests.

Please report issues with regards to IDE integration to the vendor of your IDE.
