### ISSUE TITLE
libpng warning: iCCP: known incorrect sRGB profile

### ISSUE THREAD

**Issue by pararang** [sebastianbergmann/phpunit#3768]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.5.14
| PHP version         | 7.2.19
| Installation Method | Composer

Hi,

running PHPUnit on my laravel project with this command `vendor/bin/phpunit tests/Feature/V2/DeleteUser.php --filter testWithEmptyHeader`
got this error:           

> PHPUnit 6.5.14 by Sebastian Bergmann and contributors.
> 
> E                                                                   1 / 1 (100%)
> 
> Time: 12.88 seconds, Memory: 8.00MB
> 
> There was 1 error:
> 
> 1) Tests\Feature\V2\DeleteUser::testWithEmptyHeader
> PHPUnit\Framework\Exception: libpng warning: iCCP: known incorrect sRGB profile
> libpng warning: Interlace handling should be turned on when using png_read_image
> libpng warning: iCCP: known incorrect sRGB profile
> libpng warning: Interlace handling should be turned on when using png_read_image

tried to set `convertNoticesToExceptions="false"` and `convertWarningsToExceptions="false"` on my `phpunit.xml` but still got the same error.

**Comment by sebastianbergmann** [comment]
PHPUnit 6.5 is no longer supported. Please open a new ticket in case this still applies to a supported version of PHPUnit.

That being said, you have an issue with your PHP environment that is outside the scope of PHPUnit.

**Comment by pararang** [comment]
Ok. Thank you, Sir, @sebastianbergmann. I'll try to check my PHP env
