### ISSUE TITLE
Remove MockBuilder::setMethods() and MockBuilder::setMethodsExcept()

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#3769]
See https://github.com/sebastianbergmann/phpunit/pull/3687#issuecomment-492537584 for details.

**Comment by lpd-au** [comment]
`setMethods` was replaced by `onlyMethods` (to mock existing methods) & `addMethods` (to add new methods), but what replaces `setMethodsExcept`? (Not mentioned in https://github.com/sebastianbergmann/phpunit/pull/3687#issuecomment-492537584).

**Comment by leighman** [comment]
Also interested in this ^
You can transform it to `onlyMethods` of anything you do mock but it's nice to explicitly mock everything except the method under test for futureproofness

**Comment by olinox14** [comment]
I usually mock the whole SUT, except the method I'm testing.  

The removal of `setMethodExcept` is a real regression for us, leaving us stuck with the v9...
Explicitly mocking every involved method with `onlyMethods` would represent a lot of work, increase the risk of error while mocking, and add an unnecessary verbosity to the tests...  

Restoring this functionality would be a real plus.
