### ISSUE TITLE
Laravel + PHPUnit given Fatal Error in basic first simpe test

### ISSUE THREAD

**Issue by shinseihasu** [sebastianbergmann/phpunit#3771]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.3.2
| PHP version         | 7.2.19
| Installation Method | apt-get
| Laravel version | 5.2.45

Hello, guys. I'm new in this test stuff. I'm trying to starting to use this kind of thing and learn more about tests and TDD.
So I'm trying to execute my first test using phpunit in Laravel. When I execute the phpunit command in console, I receive this error:

> PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PHPUnit\Runner\BaseTestRunner::getTest() must be of the type string, object given, called in /usr/share/php/PHPUnit/TextUI/Command.php on line 180 and defined in /usr/share/php/PHPUnit/Runner/BaseTestRunner.php:59
> Stack trace:
> #0 /usr/share/php/PHPUnit/TextUI/Command.php(180): PHPUnit\Runner\BaseTestRunner->getTest(Object(PHPUnit\Framework\TestSuite), '', Array)
> #1 /usr/share/php/PHPUnit/TextUI/Command.php(159): PHPUnit\TextUI\Command->run(Array, true)
> #2 /usr/bin/phpunit(34): PHPUnit\TextUI\Command::main()
> #3 {main}
>   thrown in /usr/share/php/PHPUnit/Runner/BaseTestRunner.php on line 59

My first test is a basic template, as seen below:

```
namespace Tests\Unit;

use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;

class ExampleTest extends TestCase
{
    /**
     * A basic test example.
     *
     * @return void
     */
    public function testBasicTest()
    {
        $this->assertTrue(true);
    }
}
```

This code are in **Tests** directory, where the _TestCase_ class is.

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.
