### ISSUE TITLE
PHP errors, notices, etc. cannot be tested anymore with PHPUnit 8.3

### ISSUE THREAD

**Issue by ADmad** [sebastianbergmann/phpunit#3774]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.3.0
| PHP version         | N/A
| Installation Method | Composer / PHAR

Class `PHPUnit\Framework\Error\Error` has been removed in 8.3.0.

The removed class was marked as `@internal` but the [Testing PHP Errors](https://phpunit.readthedocs.io/en/8.2/writing-tests-for-phpunit.html#testing-php-errors) mentions uses of that class.  So what's the alternative?

Docs for 8.3 don't seem to be up yet.

**Comment by sebastianbergmann** [comment]
The removal of this functionality was not intentional.

**Comment by sebastianbergmann** [comment]
PHPUnit 8.3.1 has been released with a fix for this.

**Comment by ADmad** [comment]
Thank you.

**Comment by sebastianbergmann** [comment]
No, thank you for bringing this to my attention :-)

**Comment by ADmad** [comment]
I had no choice when our test suite broke :stuck_out_tongue_closed_eyes:.

I initially thought it was our fault for using classes marked as `@internal` only to realize that is the documented way.

So maybe the `@internal` tag should be removed?

**Comment by sebastianbergmann** [comment]
It has already been removed.

**Comment by ADmad** [comment]
Oh good, sorry I didn't notice.

**Comment by ADmad** [comment]
Umm it's still present

https://github.com/sebastianbergmann/phpunit/blob/21461ce5b162d0f1a0fa658e27f975517c5d4234/src/Framework/Error/Error.php#L15

**Comment by sebastianbergmann** [comment]
It's not: https://github.com/sebastianbergmann/phpunit/blob/8.3/src/Framework/Error/Error.php

**Comment by ADmad** [comment]
I checked the `8.3.1.` tag, I guess you removed if after tagging :).

**Comment by ADmad** [comment]
In `8.3.1` you added class `PHPUnit\Framework\Error\Deprecation` but that class is named `PHPUnit\Framework\Error\Deprecated` in `8.2`.

**Comment by sebastianbergmann** [comment]
PHPUnit 8.3.2 has been released with a fix for this.
