### ISSUE TITLE
Explicit API for expecting PHP errors, warnings, and notices

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#3775]
The following methods should be added to `TestCase`:

* `expectDeprecation()` for `E_DEPRECATED` and `E_USER_DEPRECATED`
* `expectNotice()` for `E_NOTICE`, `E_USER_NOTICE`, and `E_STRICT`
* `expectWarning()` for `E_WARNING` and `E_USER_WARNING`
* `expectError()` for everything else

Then

```php
<?php declare(strict_types=1);
use PHPUnit\Framework\TestCase;

final class Test extends TestCase
{
    public function testOne()
    {
        $this->expectNotice();

        $a = $b;
    }
}
```

can be used instead of

```php
<?php declare(strict_types=1);
use PHPUnit\Framework\TestCase;
use PHPUnit\Framework\Error\Notice;

final class Test extends TestCase
{
    public function testOne()
    {
        $this->expectException(Notice::class);

        $a = $b;
    }
}
```

to expect the code to trigger an `E_NOTICE`, for instance.

**Comment by alfredbez** [comment]
There is now a rector for this change: https://github.com/rectorphp/rector/blob/master/docs/AllRectorsOverview.md#explicitphperrorapirector
