### ISSUE TITLE
With MockBuilder::setMethods() deprecated it's no longer possible to set MockBuilder::$methods to null.

### ISSUE THREAD

**Issue by ADmad** [sebastianbergmann/phpunit#3778]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.3.1
| PHP version         | N/A
| Installation Method | Composer / PHAR

Default value of `$methods` argument is `null` hence calling `MockBuilder::setMethods()` without argument sets `MockBuilder::$methods` property to `null`.

With `setMethods()` deprecated and default value of `MockBuilder::$methods` being `[]` it's no longer possible to set it to `null` with the new methods `onlyMethods()` or `addMethods()`.

**Comment by sebastianbergmann** [comment]
The behaviour of `setMethods()` has not been changed and tests that use it should continue to work as-is.

**Comment by sebastianbergmann** [comment]
CC @DFoxinator

**Comment by ADmad** [comment]
True but we want to be future proof and avoid seeing messages related to deprecated methods usage when running tests :slightly_smiling_face:.

So only option is to change our usage?

**Comment by DFoxinator** [comment]
We actually had a discussion around this here: https://github.com/sebastianbergmann/phpunit/pull/3687#discussion_r283092106

I was on the fence, but I though it was a good argument that the behavior of passing null didn't really seem valuable/to make sense so going forward it seemed better to simplify it I think.

**Comment by ADmad** [comment]
@DFoxinator In that case `MockObject\Generator::getMock()` should also no accept `null` for it's `$methods` argument?

**Comment by sebastianbergmann** [comment]
@ADmad You should not care about `getMock()` as it is internal.

**Comment by ADmad** [comment]
Okay :)

**Comment by DFoxinator** [comment]
@ADmad because of a small oversight on my part (sorry!), there was a bug with onlyMethods/addMethods in 8.3.(0-2) that made them not behave correctly when you pass a blank array. Now (in 8.3.3), passing a blank array to onlyMethods([])  the same behavior as passing null, so it's really an easy drop-in replacement where if you need to you can just pass [] instead of null.

**Comment by DFoxinator** [comment]
Just to add, I still recommend looking on a case-by-case basis though. This onlyMethods/addMethods change is revealing so many code/test smells in the tests I work on (some legacy stuff going back many years) it's crazy haha. So many methods removed from the code years ago still mocked, mocks where you don't need a mock at all, etc.

**Comment by ADmad** [comment]
@DFoxinator Thanks for the update.
