### ISSUE TITLE
@coverFolder annotations

### ISSUE THREAD

**Issue by VincentLanglet** [sebastianbergmann/phpunit#3779]
Actually the cover annotation only take a className.
It will be great to handle regex (or create a new annotation for it).

This way it will be possible to use
```
/**
 * @covers \Path\To\Folder\
 */
```
To restrict the coverage generated by this function to the entire folder.

Actually I have to add every class of the folder

**Comment by sebastianbergmann** [comment]
The `@covers` annotations will not be changed to work with something other than code units.

**Comment by VincentLanglet** [comment]
What about creating another annotation @sebastianbergmann ?
