### ISSUE TITLE
Don't use realpath()

### ISSUE THREAD

**Issue by stancl** [sebastianbergmann/phpunit#3782]
This code results in phpunit crashing when process substitution is used (`vendor/bin/phpunit --configuration <(cat phpunit.xml)`).

https://github.com/sebastianbergmann/phpunit/blob/54dc71f30e055632fb8c19c58ff176171da1d115/src/Util/Configuration.php#L51-L67

`realpath()` returns false for `/proc/self/fd/xx`.

With the following changes, I got this output:

```php
public static function getInstance(string $filename): self
{
    dump($filename);
    $realPath = \realpath($filename);
    dump($realPath);
    die();
```

```
"/proc/self/fd/24"
false
```

My use case for process substitution is that I would like to dynamically generate phpunit config files (to run my tests with multiple configurations, such as different Redis drivers) in my test script and pass them to phpunit.

**Comment by sebastianbergmann** [comment]
I do not think that this would be useful.

**Comment by stancl** [comment]
I do.

From [`realpath`](https://www.php.net/manual/en/function.realpath.php) docs:

> The running script must have executable permissions on all directories in the hierarchy, otherwise realpath() will return FALSE.

I can't even use a config file from /tmp.

**Comment by sanmai** [comment]
> must have executable permissions on all directories in the hierarchy

That is correct. You can't be reading a file from a directory for which you don't have an executable permission.

```
$ mkdir /tmp/example
$ echo OK > /tmp/example/foo
$ chmod -x /tmp/example
$ cat /tmp/example/foo
cat: /tmp/example/foo: Permission denied
```

**Comment by stancl** [comment]
cat can read from /proc/self/fd/xx without an issue, yet realpath returns false.

**Comment by sanmai** [comment]
```php
var_dump(realpath('/proc/self/fd/1'));
```
Outputs:
```
string(10) "/dev/pts/2"
```
Well, it doesn't.

**Comment by sanmai** [comment]
It actually may return false, but then the `realpath` utility would also return error:

```
$ realpath $(realpath /proc/self/fd/3)
realpath: /proc/46596/fd/3: No such file or directory
```

**Comment by sanmai** [comment]
OK, please never mind what I just said. With this example script:
```
<?php
var_dump($argv[1]);
var_dump(realpath($argv[1]));
var_dump(is_readable($argv[1]));
```
We get the following:
```
$ php example.php <(cat phpunit.xml)
string(10) "/dev/fd/63"
bool(false)
bool(true)
```
Even though we totally have a write permission on `/dev/fd/`:
```
$ ls -ld /dev/fd/
dr-x------ 2 ...
```

I think you may have better luck reporting this bug against PHP.

**Comment by stancl** [comment]
> The function realpath() will not work for a file which is inside a Phar as such path would be a virtual path, not a real one.

Couldn't it be that `/dev/fd/` is a "virtual" path?

**Comment by sanmai** [comment]
It is definitely not virtual as are files inside a Phar. Either way I feel like PHPUnit is not in a position to work around PHP bugs.

**Comment by stancl** [comment]
I'll try reporting it to PHP. Thanks.
