### ISSUE TITLE
Error : Call to undefined method PHPUnit\Util\ErrorHandler::handleError()

### ISSUE THREAD

**Issue by Spomky** [sebastianbergmann/phpunit#3784]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.3
| PHP version         | 7.3
| Installation Method | Composer 

Hi,

when running my tests, I have the error `Error : Call to undefined method PHPUnit\Util\ErrorHandler::handleError()`.
I downgraded PHPUnit from 8.3.3 to 8.3.0 and the error still occures.
It is gone when setting 8.2.5 or lower.

Any idea?

**Comment by sebastianbergmann** [comment]
The `ErrorHandler` class is not covered by the backward compatibility promise for PHPUnit. Your tests should not rely on PHPUnit implementation details such as this.

**Comment by Spomky** [comment]
Thank you for the prompt answer.

I don’t rely on that class in my tests.
In the meantime, I've figured out that [the issue is caused by a symfony component](https://github.com/symfony/symfony/issues/32879).

Regards.
