### ISSUE TITLE
Enable strict interpretation of scalar type declarations in process isolation code templates

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#3785]
69e61bb1463803d5016ea57cb09a021fd50b4a82 enabled the strict interpretation of scalar type declarations in the code templates used by process isolation. This caused a problem with PHPDBG detailed in #3772.

We need to investigate which statement(s) in these templates cause a problem when scalar type declarations are interpreted strictly. After fixing {this|these} issue(s) we can then enable the strict interpretation of scalar type declarations in the code templates again.

**Comment by sanmai** [comment]
It appears adding a strict types declaration makes PHPDBG drop all what it's doing and stop. E.g. consider this example without strict types:
```
$ cat example.php 
<?php
echo "OK!\n";
$ cat example.php | phpdbg -qrrs=
OK!
```
And now the same example with strict types:
```
$ cat example2.php 
<?php
declare(strict_types=1);
echo "OK!\n";
$ cat example2.php | phpdbg -qrrs=
[Nothing to execute!]
```

Might this be a PHP bug? 

```
$ phpdbg --version
phpdbg 0.5.0 (built: Aug  7 2019 09:50:45)
PHP 7.3.8-1, Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.8, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.8-1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.7.0RC2, Copyright (c) 2002-2019, by Derick Rethans
```

**Comment by Danack** [comment]
> Might this be a PHP bug?

Yes. Please can you open an issue on https://bugs.php.net/ ?

Possibly after disabling xdebug while re-running the test, just to make sure it's a problem in just PHP, rather than an artefact of running it with Xdebug also loaded.

**Comment by sanmai** [comment]
Done.

https://bugs.php.net/bug.php?id=78424

**Comment by DanielRuf** [comment]
Interestingly I always get the `[Nothing to execute!]` result. For both examples.
