### ISSUE TITLE
Expose file include blacklist to userland

### ISSUE THREAD

**Issue by rask** [sebastianbergmann/phpunit#3786]
Would it be possible to expose the file include blacklist system to PHPUnit users via XML and similar configurability?

I'm talking about the `@runInSeparateProcess` file include blacklist. There are situations where a file being included automagically at process start just does not work. One of those situations are includes that rely on the scope of the inclusion. This includes some routing config systems, some view template systems, etc.

**Comment by sebastianbergmann** [comment]
No, sorry.

**Comment by rask** [comment]
Okay, so currently the most sensible approach to tackling this would be to run all tests that include files this way in a separate process? Would it be sensible to add some official documentation regarding this?
