### ISSUE TITLE
PHP 7.2 segfault with circular reference in dataprovider

### ISSUE THREAD

**Issue by jderusse** [sebastianbergmann/phpunit#3790]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.3 (same issue from 6.5 to 8.3)
| PHP version         | 7.2.21 (work fine with 7.1, 7.3, 7.4)
| Installation Method | Composer

when a dataprovider return a ciruclar reference and have to display someting (ie. warning), PHP 7.2 segfault.

Minimal reproduct case:
```php
class FooTest extends TestCase
{
    /**
     * @dataProvider provideData
     */
    public function testTriggerNotAssertion($value)
    {
    }

    public function provideData()
    {
        $a = [];
        $a[0] = &$a;

        yield [$a];
    }
}
```

This error is triggered when the method `TestCase::toString` is called which try to stringify the data, with the `sebastian/exporter` component. Which use the `sebastian/recursion-context` component to detect recursion. 

From my investigation, the `Context` is filling up, but always returns false when the exporter call `$context->contains($data[$key]`.

I'm not able to reproduce the bug by using directly Exporter, It's probably a combination of Exporter + Generator + state in TestSuite (due to dataProvider)

**Comment by sebastianbergmann** [comment]
You have found a problem in the PHP runtime that leads to a [segmentation fault](https://en.wikipedia.org/wiki/Segmentation_fault). An issue like this has to be reported at https://bugs.php.net/report.php using a minimal, self-contained, reproducing test case.

Please note that a test case that needs to be run through PHPUnit does not qualify as either "minimal" or "self-contained" when reporting bugs for the PHP runtime. Best practices for reporting bugs in PHP are documented [here](https://bugs.php.net/how-to-report.php).

In the case that the segmentation fault happens during continuous integration on [TravisCI](http://travis-ci.org/) then you can [troubleshoot the problem locally using Docker](https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image).

**Comment by jderusse** [comment]
Hi @sebastianbergmann thank you for your suggestion and your advices.

Here is a link to the bug https://bugs.php.net/78397. And the minimal reproduct case https://3v4l.org/6AASB 

Maybe you'll be interested by the originator of the issue in your framework.
