### ISSUE TITLE
Show timing information next to each debug output

### ISSUE THREAD

**Issue by johnbillion** [sebastianbergmann/phpunit#3792]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.3.4
| PHP version         | 7.3.5
| Installation Method | Composer

When running PHPUnit in debug mode with `--debug`, it would be handy to see timing information next to each of the "started" and "ended" statements to easily identify slow tests without using a test listener.

**Comment by sebastianbergmann** [comment]
The XML logfile contains timing information. That can be parsed, sorted, etc.

**Comment by sebastianbergmann** [comment]
No feedback, closing.
