### ISSUE TITLE
Collect code coverage for test annotated with @coversNothing

### ISSUE THREAD

**Issue by Slamdunk** [sebastianbergmann/phpunit#3796]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.3.8
| PHP version         | 8.3.4

Hi, https://github.com/sebastianbergmann/phpunit/pull/2560 introduced a performance improvement to skip code coverage collection when a test is marked with `@coversNothing`, but this generates a mixed report with `processUncoveredFilesFromWhitelist="true"`.

The real world example is when tests are executed in parallel, code coverage collected separately and merged back together in the end:

#### `src/MyClass.php`
```php
class MyClass
{
    public function foo()
    {
        return true;
    }
}
```
#### `tests/FirstTest.php`
```php
/**
 * @coversNothing
 */
class FirstTest extends PHPUnit\Framework\TestCase
{
    public function testOne()
    {
        static::assertTrue(true);
    }
}
```
#### `tests/SecondTest.php`
```php
/**
 * @covers MyClass
 */
class SecondTest extends PHPUnit\Framework\TestCase
{
    public function testOne()
    {
        static::assertTrue((new MyClass())->foo());
    }
}
```
#### `phpunit.xml`
```xml
<phpunit
    bootstrap="./vendor/autoload.php"
    backupGlobals="false"
    backupStaticAttributes="false"
    colors="true"
>
    <testsuite name="bug">
        <directory>./tests</directory>
    </testsuite>

    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">./src</directory>
        </whitelist>
    </filter>
</phpunit>
```

### Actual result with a single full run
![phpunit-full](https://user-images.githubusercontent.com/152236/63346937-5c9e6900-c356-11e9-8580-bacbb411229d.png)

### Actual result with the two tests executed on separate runs, merged together
![phpunit-parallel-merge](https://user-images.githubusercontent.com/152236/63346971-69bb5800-c356-11e9-9a7f-1a34514fc47a.png)

The reason should be that the lonely run of `FirstTest` never triggers `\SebastianBergmann\CodeCoverage\CodeCoverage::start`.

Side note: the reason behind https://github.com/sebastianbergmann/phpunit/pull/2560 can be considered superseded when PCOV is used, imho.

**Comment by sebastianbergmann** [comment]
I think this is outside the scope of PHPUnit itself and, if at all, should be addressed in the tool/library/code (php-code-coverage, I would assume) where the merging happens.
