### ISSUE TITLE
Use dedicated Docker images for GitHub actions 

### ISSUE THREAD

**Issue by localheinz** [sebastianbergmann/phpunit#3821]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | n/a
| PHP version         | all of them
| Installation Method | Composer

Following 

* #3809 
* #3820 

we should use dedicated Docker images we control to ensure that we are using the appropriate versions of PHP. For example, we currently use [`composer:1.9.0`](https://github.com/composer/docker/blob/8595a2016b538e0f6945b8c2113ec85dcf04868c/1.9/Dockerfile#L1) to install dependencies using `composer`, and this image uses

```Dockerfile
FROM php:7-alpine
```

That is, this image - if I understand correctly - will install the latest stable PHP version, which might not be the version we actually need, and thus install different dependencies.

**Comment by sebastianbergmann** [comment]
We do not get different dependencies because our `composer.json` has
```javascript
"config": {
    "platform": {
        "php": "7.2.0"
    }
}
```
