### ISSUE TITLE
Deprecating class name as CLI option

### ISSUE THREAD

**Issue by flow-control** [sebastianbergmann/phpunit#3859]
Hello there,

i like to propose to deprecate calling a test on CLI with only it's class name or with it's class name and a file path to the class in the next minor release and remove it in PHPUnit 9 (as we already discussed at the code sprint September 2019).

The documentation states:

> phpunit [options] UnitTest [UnitTest.php]
> Runs the tests that are provided by the class UnitTest. This class is expected to be declared in the specified sourcefile.

I would change this to:

> phpunit [options] UnitTest.php
> Runs the tests that are provided by the class `UnitTest` in the file `UnitTest.php`

The `UnitTest` argument was not enforced until #3830. While digging deep into the code i found, that this feature leads to a lot of conditional code and a lot of confusion when trying to understand whats going on while loading. Loading and parsing this CLI option is spread over at least three classes and refactoring this should be easier if we deprecate and remove the option stated above.

And while fixing a lot of bugs, i found that ultimately it doesn't matter what you give as `UnitTest` argument, couse if this is not found in the `UnitTest.php` the `StandardSuiteLoader` just checks if there is any class, that is not abstract and extends from `TestCase` and just uses this.

Let me know if you have questions.

/Flo

**Comment by sebastianbergmann** [comment]
Makes sense to me. I think it would be safe to deprecate this in PHPUnit 8.4 or PHPUnit 8.5 and then remove it in PHPUnit 9.

**Comment by ahocquard** [comment]
In that case, would it be possible to return filepath in the command `--list-tests` instead of the name?
Otherwise, it would be impossible to execute any test listed in the command (if I understand correctly this issue).

**Comment by sebastianbergmann** [comment]
The output of `--list-tests` is to be used with `--filter`, for instance.
