### ISSUE TITLE
--list-tests list all tests without excluding tests that are in excluded groups

### ISSUE THREAD

**Issue by ahocquard** [sebastianbergmann/phpunit#3862]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.1.6
| PHP version         | 7.2
| Installation Method | Composer

#### Summary

`list-tests` should list all the tests by excluding tests that are in excluded groups.
This is not the current behavior.

#### Current behavior

`list-tests` lists all the tests *without* excluding tests that are in excluded groups.

It does not work both for exclusion in `phpunit.xml` and command line option (`vendor/bin/phpunit --list-tests --exclude-group one,two`).

#### How to reproduce

```
➜  cat Test.php

<?php

use PHPUnit\Framework\TestCase;

class Test extends TestCase
{
    /**
     * @group one
     */
    public function testOne()
    {
    }

    /**
     * @group two
     */
    public function testTwo()
    {
    }
}

➜ cat phpunit.xml

<phpunit>
 <testsuite name="My Test Suite">
  <file>Test.php</file>
 </testsuite>

 <groups>
  <exclude>
   <group>one</group>
  </exclude>
 </groups>
</phpunit>

➜ vendor/bin/phpunit

PHPUnit 8.1.6 by Sebastian Bergmann and contributors.

R                                                                   1 / 1 (100%)

Time: 83 ms, Memory: 6.00 MB

There was 1 risky test:

1) Test::testTwo
This test did not perform any assertions

/home/ahocquard/Workspace/akeneo/pim/ped/vendor/akeneo/pim-community-dev/Test.php:17

OK, but incomplete, skipped, or risky tests!
Tests: 1, Assertions: 0, Risky: 1.

➜ vendor/bin/phpunit --list-tests

PHPUnit 8.1.6 by Sebastian Bergmann and contributors.

Available test(s):
 - Test::testOne
 - Test::testTwo

➜ vendor/bin/phpunit --list-tests --exclude-group one

PHPUnit 8.1.6 by Sebastian Bergmann and contributors.

Available test(s):
 - Test::testOne
 - Test::testTwo
```

#### Expected behavior

`list-tests` should not list tests that are in an excluded groups.
Also, I think the same rule as raised into the issue https://github.com/sebastianbergmann/phpunit/issues/322 should apply: `--group` commandline option should override group/exclude setting in phpunit.xml.

```
➜ vendor/bin/phpunit --list-tests --exclude-group one

PHPUnit 8.1.6 by Sebastian Bergmann and contributors.

Available test(s):
 - Test::testTwo
```

**Comment by sebastianbergmann** [comment]
> `list-tests` should list all the tests by excluding tests that are in excluded groups.

Is this your assumption or is this documented somewhere? I am asking because I can see arguments for both behaviours and do not know of the top of my head on which I decided when this was implemented.

**Comment by ahocquard** [comment]
This is my assumption. I didn't see any documentation for the expected behavior. 

But otherwise, the list of the tests to execute is not identical to the list of tests that are really executed. A real use-case where it's problematic is when you try to partition the list of tests to execute. The tests that are part of an excluded group will be partitioned. At the end, each partition will not execute the same number of tests.

https://github.com/sebastianbergmann/phpunit/issues/3387

**Comment by tomasluken** [comment]
I'm currently splitting a large set of tests into several partitions and had the same assumption using "--group" in combination with "--list-tests".
I assumed that both arguments would be applied (or some warning).

--list-tests-xml includes testnames as well as groupnames. So I started using that.

**Comment by kubawerlos** [comment]
Since [The --exclude-group and --list-tests options cannot be combined](https://github.com/sebastianbergmann/phpunit/blob/10.5/src/TextUI/Command/Commands/ListTestsAsTextCommand.php#L78) this is no longer an issue.
