### ISSUE TITLE
Non-iterable parameter groups are rejected in `->withConsecutive()` calls

### ISSUE THREAD

**Issue by ndench** [sebastianbergmann/phpunit#3867]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.3.5
| PHP version         | 7.3
| Installation Method | symfony/phpunit-bridge (which uses composer, but separately to the main project composer)

#### Summary

We receive the following error in a few tests after upgrading from 8.3.4 to 8.3.5:

```
PHPUnit\Framework\InvalidParameterGroupException: Parameter group #0 must be an array or Traversable, got object 
```

This is caused by creating a mock like this:

```php
$parameters = ['foo', 'bar', 'baz'];
$mock = $this->createMock(MyClass::class);

$mock->expects(static::exactly(3))
    ->method('generateFoos')
    ->withConsecutive(...$parameters)
;
```

The change was introduced [here](https://github.com/sebastianbergmann/phpunit/commit/72098d80f0cfc06c7e0652d331602685ce5b4b51).

I actually think this was a good change to make, it pointed out areas of our tests that technically incorrect, and it wasn't hard to fix. But still good to report it because others might get caught and not have it so easy.

#### Previous Behavior

Each item in the `$parameters` array was treated as a single parameter being passed to the method on consecutive calls.

#### Current Behavior

Exception being thrown because the `$parameters` array is meant to be an array of arrays, where each second level array contains the parameters expected to be passed to the method.

#### How to reproduce

- Create a mock using the code shown above.
- Run the test on 8.3.5

**Comment by sebastianbergmann** [comment]
I do not consider this a backward compatibility break. Before 72098d80f0cfc06c7e0652d331602685ce5b4b51 your test code was broken, you simply did not know it. After 72098d80f0cfc06c7e0652d331602685ce5b4b51 your test code is still broken, but you are made aware of it.
