### ISSUE TITLE
Support stub instances as values for createConfiguredMock

### ISSUE THREAD

**Issue by christeredvartsen** [sebastianbergmann/phpunit#3872]
When using `createConfiguredMock` it's not possible to use objects that implement the `PHPUnit\Framework\MockObject\Stub\Stub` interface as values in the configuration, since all values are returned as `ReturnStub` instances from the `willReturn` method:

```php
// Does not work
$mock = $this->createConfiguredMock(SomeClass::class, [
    'doSomething' => new PHPUnit\Framework\MockObject\Stub\ReturnSelf,
]);
```

Would it be possible for the `willReturn` method to check if the value is already an instance of the said interface, and simply return them, or return the value wrapped in a `ReturnStub` if not?

**Comment by sebastianbergmann** [comment]
Can you provide a pull request?
