### ISSUE TITLE
Mocking callables by mocking __invoke() on stdClass

### ISSUE THREAD

**Issue by morozov** [sebastianbergmann/phpunit#3873]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.3.0
| PHP version         | 7.3.8
| Installation Method | Composer

As of https://github.com/sebastianbergmann/phpunit/commit/20b0b2150b2890eb647be2418c62535c83bd2996, PHPUnit triggers a warning when a partial mock is created with a non-existing method. While this behavior looks reasonable per se, it breaks the [technique](https://github.com/sebastianbergmann/phpunit/issues/3536#issuecomment-493599948) of mocking callables which is not natively supported by PHPUnit:
```php
public function testClosureIsCalled() : void
{
    $closure = $this->createPartialMock(stdClass::class, ['__invoke']);

    $closure->expects(
        $this->exactly(2)
    )->method('__invoke');

    $closure();
    $closure();
}
```
While I'm not proposing any specific solution to the problem, I'd like the developers to be aware of it. Escalating this warning to a failure in a future PHPUnit version will break existing tests without a known way to rework them.

**Comment by sebastianbergmann** [comment]
If at all, this should be taken care of in #3536.
