### ISSUE TITLE
When ran globally and redirected to composer-installed version PHPUnit skips PHP version check

### ISSUE THREAD

**Issue by Amunak** [sebastianbergmann/phpunit#3875]
When you have PHPUnit installed globally - say, version 5.7 that supports even PHP 5.6 - there is a check in the executable that makes sure you are running the correct version. Now consider you have PHP 7.1 installed so that check is okay, and phpunit runs. Except it then sees that there is PHPUnit installed locally in ./vendor/, and redirects there. But instead of doing something like calling `require('./vendor/bin/phpunit')` it directly autoloads vendors and then runs the command directly.

The issue is that the PHPUnit version that's installed locally can be literally any other version, and when it has different version requirements (say it's 8.0 so it needs PHP 7.2 or higher) those requirements are not checked again. So it "happily" runs even on your PHP 7.1 even though it should just exit.

The end result is that the test(s) appear broken depending on what they call, PHPUnit has strange behaviors and it appears broken.

I suggest that you do not skip this additional check when redirecting to the "local" PHPUUnit version. Either call the executable directly or implement some other method of re-checking PHP version.

**Comment by sebastianbergmann** [comment]
It appears that you have different installations of PHPUnit mixed up.

For instance, you may have used Composer to install PHPUnit and have configured the autoloader generated by Composer as PHPUnit's bootstrap script but then you invoke PHPUnit using an executable other than `vendor/bin/phpunit`.

**Comment by Amunak** [comment]
Well yeah, as described - the issue *is* different versions of PHPUnit installed. However if you support "offloading" usage of one (global) PHPUnit to the project's PHPUnit, you should also make sure that the PHP version check works properly.

In my case, PHPUnit was installed globally from a repository package (that I have little control of), and in most cases was just used to redirect to the project's vendors' PHPUnit... Which then didn't check the running PHP version correctly. And that doesn't seem like intended behavior.
