### ISSUE TITLE
startTestSuite is call on every unit test

### ISSUE THREAD

**Issue by fezfez** [sebastianbergmann/phpunit#3877]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.3.5, 8.2.5, 8.1.6, 8.0.6, 7.5.16, 7.4.5, 7.3.5, 7.2.7, 7.1.5
| PHP version         | 7.3.4, 7.4RC1, 7.2.25
| Installation Method | Composer

#### Summary

i have added 
```php 
var_dump(__METHOD__.' '.$suite->getName()); 
```

on 

https://github.com/sebastianbergmann/phpunit/blob/4d2e3f801b316766fbfc3431f6fda6137b63fab0/src/Framework/TestResult.php#L381-L383

and

```php 
var_dump(__METHOD__.' '. $result->count());
```
on

https://github.com/sebastianbergmann/phpunit/blob/4d2e3f801b316766fbfc3431f6fda6137b63fab0/src/Framework/TestSuite.php#L516

#### Current behavior

```
PHPUnit 8.3.5 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.4.0RC1
Configuration: /var/www/phpunit.xml.dist
Random seed:   1570011937

string(34) "PHPUnit\Framework\TestSuite::run 0"
string(45) "PHPUnit\Framework\TestResult::startTestSuite "
string(34) "PHPUnit\Framework\TestSuite::run 0"
string(49) "PHPUnit\Framework\TestResult::startTestSuite unit"
string(34) "PHPUnit\Framework\TestSuite::run 0"
string(103) "PHPUnit\Framework\TestResult::startTestSuite RoaveUnitTest\NoLeaks\PHPUnit\EmptyBaselineMemoryUsageTest"
.string(34) "PHPUnit\Framework\TestSuite::run 1"
string(115) "PHPUnit\Framework\TestResult::startTestSuite RoaveUnitTest\NoLeaks\PHPUnit\CollectTestExecutionMemoryFootprintsTest"
......string(34) "PHPUnit\Framework\TestSuite::run 7"
string(104) "PHPUnit\Framework\TestResult::startTestSuite RoaveUnitTest\NoLeaks\PHPUnit\MeasuredTestRunMemoryLeakTest"
.......string(35) "PHPUnit\Framework\TestSuite::run 14"
string(109) "PHPUnit\Framework\TestResult::startTestSuite RoaveUnitTest\NoLeaks\PHPUnit\MeasuredBaselineTestMemoryLeakTest"
......                                              20 / 20 (100%)

Time: 32 ms, Memory: 6.00 MB

OK (20 tests, 27 assertions)

```

#### How to reproduce

run https://github.com/Roave/no-leaks unit

#### Expected behavior

```
PHPUnit 8.3.5 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.4.0RC1
Configuration: /var/www/phpunit.xml.dist
Random seed:   1570011937

string(34) "PHPUnit\Framework\TestSuite::run 0"
string(49) "PHPUnit\Framework\TestResult::startTestSuite unit"
string(34) "PHPUnit\Framework\TestSuite::run 0"
.string(34) "PHPUnit\Framework\TestSuite::run 1"
......string(34) "PHPUnit\Framework\TestSuite::run 7"
.......string(35) "PHPUnit\Framework\TestSuite::run 14"
......                                              20 / 20 (100%)

Time: 32 ms, Memory: 6.00 MB

OK (20 tests, 27 assertions)

```

related : https://github.com/Roave/no-leaks/issues/22

**Comment by epdenouden** [comment]
This is one to investigate, also in light of the upcoming dataprovider improvements. Providers are wrapped in a suite, too 

Might be just the logging. We'll have a looksy during the hackathon this weekend

**Comment by fezfez** [comment]
Maybe repeat option buggy too because he is considering testsuite has test (addTest instead of addTestSuite if it's testsuite)

https://github.com/sebastianbergmann/phpunit/blob/4d2e3f801b316766fbfc3431f6fda6137b63fab0/src/TextUI/TestRunner.php#L191-L202

**Comment by sebastianbergmann** [comment]
For each test method of a test case class an object of that test case class is created. These objects are aggregated in a `TestSuite` object. It is that `TestSuite` object which is repeatedly executed when `--repeat` is used. Therefore this is working as expected.
