### ISSUE TITLE
8.4 Break the namespace/folder structure

### ISSUE THREAD

**Issue by StudioKris** [sebastianbergmann/phpunit#3880]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.4.0

#### Summary
The commit : https://github.com/sebastianbergmann/phpunit/commit/7f664ffd558ba68031963f63d3e23a951ba441fc

Change the namespace `PHPUnit\Framework\MockObject\Matcher\` to `PHPUnit\Framework\MockObject\Rule\` but the folder structure still use 'Matcher' that create error during the usage of PHPUnit by framework like `CodeCeption`.

`[Error] Class 'PHPUnit\Framework\MockObject\Matcher\AnyInvokedCount' not found`

**Comment by sebastianbergmann** [comment]
PHPUnit uses classmap-based autoloading and does not follow any "standard" that uses a relationship between namespaces and filesystem structure.

**Comment by sebastianbergmann** [comment]
That being said, I renamed the directory in 7edd37b7df9694562179d060b4737db2e2cd3ff0. This was a leftover from 7f664ffd558ba68031963f63d3e23a951ba441fc. Thank you for bringing this to my attention.

**Comment by dpauli** [comment]
So, its a bug, you forgot to rename it? Why its closed right now?
