### ISSUE TITLE
Error: Call to undefined method Mock_SampleInterface_8dc42d9c::__phpunit_getInvocationMocker()

### ISSUE THREAD

**Issue by dominikzogg** [sebastianbergmann/phpunit#3883]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.4.0
| PHP version         | 7.3.9
| Installation Method | Composer

#### Summary

```
1) Chubbyphp\Tests\Mock\MockByCallsTraitTest::testInterfaceWithToManyCalls
Error: Call to undefined method Mock_SampleInterface_8dc42d9c::__phpunit_getInvocationMocker()

/vagrant/chubbyphp-mock/tests/MockByCallsTraitTest.php:152

2) Chubbyphp\Tests\Mock\MockByCallsTraitTest::testInterfaceWithToLessCalls
Error: Call to undefined method Mock_SampleInterface_8dc42d9c::__phpunit_getInvocationMocker()

/vagrant/chubbyphp-mock/tests/MockByCallsTraitTest.php:187
```

https://github.com/chubbyphp/chubbyphp-mock/issues/4

Related to: https://github.com/sebastianbergmann/phpunit/pull/3849

Other vendors with issues:

https://github.com/php-mock/php-mock-phpunit/issues/39

#### Previous Behavior

tests are up and running

#### Current Behavior

tests are broken as mentioned

#### How to reproduce

git clone git@github.com:chubbyphp/chubbyphp-mock.git && cd chubbyphp-mock && composer install && vendor/bin/phpunit

**Comment by sebastianbergmann** [comment]
You must not depend on implementation details of PHPUnit.

**Comment by dominikzogg** [comment]
Well to test a mock helper, I have to test if phpunit behaves as expected, when break constraints, so I have to depend on "implementation details" as you call them

**Comment by dominikzogg** [comment]
https://github.com/chubbyphp/chubbyphp-mock/commit/e02989790edb6bcc34a072260719e979e48b24a6
