### ISSUE TITLE
Can not set methods with setMethodsExcept when only one method exist

### ISSUE THREAD

**Issue by ViniTou** [sebastianbergmann/phpunit#3886]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.3.5
| PHP version         | 7.3.2
| Installation Method | Composer

#### Summary

I want to use not mocked method with `setMethodsExcept`, when only one public method is provided in class.

#### Current behavior

When setting methods which should not be mocked, when class in question have only one public method, that method is still mocked. Adding additional method to class solves problem.
#### How to reproduce

Create class with only one public method, then use MockBuilder
```
        return $this
            ->getMockBuilder(ClassWithOnePublicMethod::class)
            ->setMethodsExcept(['methodName'])
            ->getMock();
```
#### Expected behavior

Method in question is not mocked.

I think that problem, (if it truly exist, and it is not some misuse of api on my side) comes from array_diff returning and passing empty array to `setMethods` in `setMethodsExcept` instead of null. But not sure, if just doing in wouldn't break other things.

**Comment by sebastianbergmann** [comment]
Superseded by #3911.
