### ISSUE TITLE
Not running testsuit/folder on Ubuntu

### ISSUE THREAD

**Issue by rfmacedoshosp** [sebastianbergmann/phpunit#3892]
| Q                          | A
| --------------------| ---------------
| PHPUnit version   | 8.3.4
| PHP version         | 7.2
| Installation Method | PHAR

#### Summary

PHPUnit is not running testsuits (phpunit.xml) or folders directly passed as argument on Ubuntu

#### Current behavior

When executing the `./phpunit` (so that the `phpunit.xml` will be used) or `./phpunit tests` (where "tests" is the folder) no tests are executed.

#### How to reproduce

1. On ubuntu, download the PHAR file.
2. Run the PHPUnit command with a folder containing tests: `./phpunit <test-folder>`

#### Expected behavior

It's expected that PHPUnit find all test files (pattern: *Test.php) into the provided folder, then execute them all at once.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by rfmacedoshosp** [comment]
I cannot provide the test code itself because it contains sensitive information, but for sure I can give a more detailed step by step.

**Context**:
I'm using PHPUnit since version 5 on Windows and everything works fine, for whatever method I'll mention below in this comment.

Now I want to create a CI/CD pipeline, and the tool uses docker containers to run the pipeline steps, so I need to run PHPUnit on a Linux environment.

**Prerequisites:**
- Use Ubuntu 18 as docker container
- PHP 7.2 installed
- PHPUnit 8 installed by PHAR, exactly as mentioned [here](https://phpunit.de/getting-started/phpunit-8.html)
- PHPUnit PHAR located at project root folder

**Directory structure:**
```
. (project root)
|__phpunit
|__phpunit.xml
|__tests
   |__module1
   |  |__Class1Module1Test.php
   |  |__Class2Module1Test.php
   |  .
   |  .
   |  .
   |__module2
      |__Class1Module2Test.php
      |__Class2Module2Test.php
      .
      .
      .
```

Where `phpunit.xml` contains:
``` xml
<phpunit
    convertErrorsToExceptions="true"
    convertNoticesToExceptions="true"
    convertWarningsToExceptions="true"
    processIsolation="false"
    stopOnError="false"
    stopOnFailure="false"
    verbose="true"
>
    <testsuites>
        <testsuite name="TestSuite">
            <directory>tests</directory>
        </testsuite>
    </testsuites>
</phpunit>
```

But I've already tried with:
``` xml
<directory suffix="Test.php">tests</directory>
<directory suffix=".php">tests</directory>
```

**How to reproduce:**
1. Running PHPUnit without arguments, so the configuration from `phpunit.xml` will be used
    `$ ./phpunit`
2. Running PHPUnit passing the `tests` folder as argument
    `$ ./phpunit tests`
    `$ ./phpunit tests/`
3. Running PHPUnit passing a module folder as argument
    `$ ./phpunit tests/module1`
    `$ ./phpunit tests/module1/`
    `$ ./phpunit tests/module2`
    `$ ./phpunit tests/module2/`

PS: Running PHPUnit passing a folder as argument don't work even if the `phpunit.xml` file to be deleted.

**How to make it work:**
1. Running PHPUnit with a test file directly
    `$ ./phpunit tests/module1/Class1Module1Test.php`
    `$ ./phpunit tests/module1/Class2Module1Test.php`
    `$ ./phpunit tests/module2/Class1Module2Test.php`
    `$ ./phpunit tests/module2/Class2Module2Test.php`

**Other setups:**
I'm currently using PHP 7.2 + PHPUnit 8 on Ubuntu 18, so this is the setup I more want a solution, but I've already tested some other setups and the same behaviour remains:

| OS             | PHP | PHPUnit |
|-------------|------|----------|
| Ubuntu 18 | 7      | 7            |
| Ubuntu 18 | 7      | 6            |
| Ubuntu 18 | 7      | 5            |
| Ubuntu 18 | 5      | 8            |
| Debian       | 7      | 8            |
| Debian       | 7      | 5            |

If you need something more specific feel free to ask and I'll try to provide as soon as possible.

Thank you very much.

**Comment by sebastianbergmann** [comment]
I was not able to reproduce the issue.
