### ISSUE TITLE
ErrorException: Notice: ob_end_clean(): failed to delete buffer.

### ISSUE THREAD

**Issue by sebastianblum** [sebastianbergmann/phpunit#390]
Hello!

I'am using symfony 2.0.4 and the example was working with phpunit 3.5.15.

Since the upgrade to phpunit 3.6 i get the following output:

phpunit -c app
# !/usr/local/Cellar/php/5.3.6/bin/php

PHPUnit 3.6.0 by Sebastian Bergmann.

Configuration read from /Users/sebiprivat/Downloads/Symfony/app/phpunit.xml.dist

.E

Time: 1 second, Memory: 25.50Mb

There was 1 error:

1) Acme\DemoBundle\Tests\Controller\DemoControllerTest::testInvalidName
ErrorException: Notice: ob_end_clean(): failed to delete buffer. No buffer to delete in /usr/local/Cellar/php/5.3.6/lib/php/PHPUnit/Framework/TestCase.php line 833

/Users/sebiprivat/Downloads/Symfony/vendor/symfony/src/Symfony/Component/HttpKernel/Debug/ErrorHandler.php:65
/usr/local/Cellar/php/5.3.6/bin/phpunit:46

FAILURES!
Tests: 2, Assertions: 2, Errors: 1.
MacPro:Symfony sebiprivat$ 

---

Steps to reproduce the error:
1. Download Symfony v2.0.4 with vendors
   http://symfony.com/download?v=Symfony_Standard_Vendors_2.0.4.tgz
2. Go into the directory and run phpunit -c app 
   There should be one test in the Acme Demo Bundle
3. Now I want to test, that symphony throws a NotFoundException (will display a 404 error page) if no name was given

I edited in src/Acme/DemoBundle/Controller/DemoController.php to

public function helloAction($name)
{
    if (!$name) {
        throw new NotFoundHttpException("No Name!");
    }
    return array('name' => $name);
}

and added a new test in src/Acme/DemoBundle/Tests/Controller/DemoControllerTest.php

 public function testInvalidName()
 {
    $client = $this->createClient();
    $crawler = $client->request('GET', '/demo/hello/');
    $this->assertTrue($client->getResponse()->isNotFound());
}

Now running phpunit -c app will get the following output:

phpunit -c app
# !/usr/local/Cellar/php/5.3.6/bin/php

PHPUnit 3.6.0 by Sebastian Bergmann.

Configuration read from /Users/sebiprivat/Downloads/Symfony/app/phpunit.xml.dist

.E

Time: 1 second, Memory: 25.50Mb

There was 1 error:

1) Acme\DemoBundle\Tests\Controller\DemoControllerTest::testInvalidName
ErrorException: Notice: ob_end_clean(): failed to delete buffer. No buffer to delete in /usr/local/Cellar/php/5.3.6/lib/php/PHPUnit/Framework/TestCase.php line 833

/Users/sebiprivat/Downloads/Symfony/vendor/symfony/src/Symfony/Component/HttpKernel/Debug/ErrorHandler.php:65
/usr/local/Cellar/php/5.3.6/bin/phpunit:46

FAILURES!
Tests: 2, Assertions: 2, Errors: 1.
MacPro:Symfony sebiprivat$

**Comment by christoferd** [comment]
For what it's worth I fixed it in my case. Laravel 4.2, PHPUnit 3.7.28

Issue: One of my blade view files had an extra useless **@stop** at the end.

PS: Like sebastianbergmann said, it's something the framework is doing that's causing that error.
