### ISSUE TITLE
Allow failure message to be replaced

### ISSUE THREAD

**Issue by BackEndTea** [sebastianbergmann/phpunit#3903]
In the [webmozart/assert](https://github.com/webmozart/assert) library we use PHPUnit to make sure the readme, and the doc comment of the `Assert` class are up to date.

This is done by checking that every assertion method is present in the readme and the doc comment, which is using PHPUnit and `assertContaints`. We provide a custom error message that explains to the user they need to add the assertions documentation in those places.

The problem is that if it is not present the entire content of the readme or doc comments get printed out. Which makes the actual error message somewhat difficult to spot.

So i'd like my custom assertion message to replace the one provided by PHPUnit.

**Comment by sebastianbergmann** [comment]
In case you are suggesting an override for the assertion failure message generated by PHPUnit the answer is no, this will not be implemented.

**Comment by BackEndTea** [comment]
That was what i was asking. Thanks for the answer.
