### ISSUE TITLE
Wrong TestCase executed with TestCase-inheritance

### ISSUE THREAD

**Issue by arnegroskurth** [sebastianbergmann/phpunit#3922]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.4.2
| PHP version         | 7.3.11
| Installation Method | Composer

#### Summary

Having a TestCase inherit from another TestCase within a deeper Namespace results in the parent TestCase being executed when trying to selectively execute only the child TestCase.

#### Current behavior

The parent TestCase is executed.

#### How to reproduce

[https://github.com/arnegroskurth/phpunit-bug](https://github.com/arnegroskurth/phpunit-bug)

#### Expected behavior

The child TestCase should be executed.

**Comment by sebastianbergmann** [comment]
Should be fixed by #3919.

CC @flow-control

**Comment by flow-control** [comment]
correct, I already added a test case for this regression
