### ISSUE TITLE
Make mock expectation `with()` more strict

### ISSUE THREAD

**Issue by FloEberle** [sebastianbergmann/phpunit#3924]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.2.2
| PHP version         | 7.3.11
| Installation Method |  PHAR

I'm wonding why this expectation does not fail, because the second parameter $bar ist not expected in the `with` clause. I would have expected a more strict behaviour (failing on missing).
Is there a way to make phpunit behave more strictly? I did not find anything related in the official docs and internet.
What is the reason for this behaviour in the first place?

Thanks!

```
    class Demo
    {
        public function execute(string $foo, string $bar): void
        {

        }
    }

    class UnitTest extends \PHPUnit\Framework\TestCase
    {
        public function testDemo(): void
        {
            $demo = $this->createMock(Demo::class);
            $demo->expects($this->once())->method('execute')->with('foo');

            $demo->execute('foo', 'bar');
        }
    }
```

**Comment by sebastianbergmann** [comment]
This would be a backward compatibility break.

**Comment by sebastianbergmann** [comment]
This should be handled as part of #3158.
