### ISSUE TITLE
PHP Unit looks for a test in file named *Test*.php.

### ISSUE THREAD

**Issue by Proxxx23** [sebastianbergmann/phpunit#3930]
As for 8.4.1 PHPUnit was looking for a tests only in files that names ends with "Test". As for 8.4.2 I realized, that it looks for a tests also in files with "Test" anywhere in name. 

We have class NwtTestCase that extends TestCase from PHPUnit framework, and then our tests extends NwtTestCase. PHPUnit looks for a tests in NwtTestCase class. Why? Up to 8.4.1 it was looking for a tests only in classes with "Test" at the end. Now it has changed and I get: 

> No tests found in class "Tests\NwtTestCase".

**Comment by sebastianbergmann** [comment]
CC @flow-control

**Comment by flow-control** [comment]
Hey @Proxxx23,
could you try with the `8.4` or `master` branch? This should be fixed in the upcomming `8.4.3` release.
/Flo

**Comment by flow-control** [comment]
For reference: PR #3919 should fix this

**Comment by Proxxx23** [comment]
> Hey @Proxxx23,
> could you try with the `8.4` or `master` branch? This should be fixed in the upcomming `8.4.3` release.
> /Flo

I've checked on 8.4.1 - it works with no problem.

**Comment by sebastianbergmann** [comment]
PHPUnit 8.4.3 has been released with #3919.
