### ISSUE TITLE
Wrong message

### ISSUE THREAD

**Issue by NareshVadhavana** [sebastianbergmann/phpunit#3933]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8
| PHP version         | x.y.z
| Installation Method | Composer / PHAR

#### Summary

I use assertDontSeeText('Hi') function in laravel that time when test is fail that time message is displayed :     Failed asserting that 'Hi i am Naresh' does not contain "Hi".
but i think this is not proper message i think for that type of function suitable message is like :
Failed asserting that 'Hi i am Naresh' does contain "Hi".

so, remove "not" word from message  

#### Current behavior
This is wrong message.

Failed asserting that 'Hi i am Naresh' does not contain "Hi".

#### Expected behavior
Correct message is : 
Failed asserting that 'Hi i am Naresh' does contain "Hi"

**Comment by sebastianbergmann** [comment]
`assertDontSeeText` is not part of PHPUnit.

**Comment by NareshVadhavana** [comment]
Okay. then fine you make nice tool
