### ISSUE TITLE
JUnit's logging of risky tests is inconsistent with other types

### ISSUE THREAD

**Issue by oprypkhantc** [sebastianbergmann/phpunit#3937]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.4.3
| PHP version         | 7.3
| Installation Method | Composer/PHAR

#### Summary

JUnit's logger error output is inconsistent between an error and a risky test. Real errors include test name in body of `<error>` XML tag, while risky tests don't.

This is a problem as tools like `paratest` rely on that output to display the information. It's almost impossible to detect the source of a risky test when using paratest (which relies on JUnit's logs). 

#### Current behavior

```
<error type="PHPUnit\Framework\RiskyTestError">Risky Test
</error>
```

#### How to reproduce

1. Create an empty test case with an empty test in it.
2. Run phpunit with `--log-junit` option.
3. Open the produced XML file.

#### Expected behavior

Risky tests should either also dump test name or "error", "failure", "warning" should not.
```
<error type="PHPUnit\Framework\RiskyTestError">Tests\Super\Test\Namespace\SomeTest::testSomething
Risky Test
</error>
```
to be consistent with
```
<error type="LogicException">Tests\Super\Test\Namespace\SomeTest::testSomething
LogicException: asdaddsa

/var/www/html/tests/Super/Test/Namespace/SomeTest.php:129
</error>
```

**Comment by Fedcomp** [comment]
When using phpunit with paratest with option to stop tests with timeout (`@small @medium @big` etc) phpunit fails to provide any additional info in JUnit other than "risky test". Can this be reviewed?
