### ISSUE TITLE
phpunit 6.5.5 grabs deep-copy 1.8.0 with syntax error

### ISSUE THREAD

**Issue by scottw-finao** [sebastianbergmann/phpunit#3939]
I needed to install phpunit 6.5.5 to work on some old code but when doing a composer updates, it seems to ask for myclabs/deep-copy ^1.6.1 and ended up grabbing v1.8.0 which includes a extra bareword which was subsequently fixed in v1.8.1 ( https://github.com/myclabs/DeepCopy/issues/122 )

Perhaps increase the requirement to ^1.8.1?

**Comment by sebastianbergmann** [comment]
PHPUnit 6.5 is no longer supported.

**Comment by scottw-finao** [comment]
well, for the record, adding a require for myclabs/deep-copy ^1.8.1 to composer.json does solve the issue
