### ISSUE TITLE
Make the expect* methods for PHP errors support an optional error message

### ISSUE THREAD

**Issue by christeredvartsen** [sebastianbergmann/phpunit#3947]
The explicit API expecting PHP errors could support optional error messages and internally call the`expect*Message()` methods to make them slightly easier to use. I'll use warnings as an example below, but the feature is related to the other PHP error types as well.

Currently I'm doing this:

```
$this->expectWarning();
$this->expectWarningMessage('some message');
```

It would be great if `expectWarning` would support an optional error message directly, so I could do this instead:

```
$this->expectWarning('some message');
```

An alternative approach would be to have `expectWarningMessage()` and `expectWarningMessageMatches()` call `expectWarning()` internally.

If this is interesting I can add a pull request for it.

**Comment by sebastianbergmann** [comment]
I prefer the API the way it is, sorry.
