### ISSUE TITLE
assertEquals does not check class type on date time objects.

### ISSUE THREAD

**Issue by pjordaan** [sebastianbergmann/phpunit#3948]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | at least latest, but older version have this too
| PHP version         | 7.2.24
| Installation Method | Composer

#### Summary
My test succeeded, but actually something was broken because the returned object was not a DateTimeImmutable, but a DateTime instance. I can reproduce it with a small setup:

```php

class A {};

class B extends A {};

class TestAssert extends \PHPUnit\Framework\TestCase
{
    public function testEquals()
    {
        $this->assertEquals(new DateTime('1970-01-01 0:00:00'), new DateTimeImmutable('1970-01-01 0:00:00'));
    }

    public function testEquals2()
    {
        $this->assertEquals(new B, new A);
    }
}

```
For some reason the test testEquals succeeds. The same applies if I have a class that extends DateTime or DateTimeImmutable. For some reason it does not check if it is the same class. This is unexpected behaviour to me.

#### Current behavior
assertEquals ignores that the expected value is of a different class than the actual value when it is a datetime object.

#### How to reproduce

See test above.

#### Expected behavior

AssertEquals should fail when a different class is being used just like it is the case with regular class objects just like the test testEquals2 does....

**Comment by sebastianbergmann** [comment]
This is expected behaviour. `assertEquals()` only looks at the value, not the type.

**Comment by pjordaan** [comment]
but DateTime is a class, so it is weird and unexpected behaviour that is different from other classes. 

The other example where I compare new A() with new B() does throw an error because the class does not match, besides both are 2 classes with no properties and are an instance of class A.

What does DateTime have what a custom class does not have?
