### ISSUE TITLE
Deprecate support for doubling multiple interfaces

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#3955]
The methods

* `getMockBuilder()`
* `createMock()`
* `createConfiguredMock()`
* `createPartialMock()`

currently support the creation of test doubles that implement multiple interfaces that are passed as an array of interface names for their first argument.

This functionality should be deprecated as "having to use it" is almost always a symptom of bad design. More importantly, though, the support for the creation of test doubles that implement multiple interfaces resulted in code that is hard to maintain.

**Comment by someniatko** [comment]
@sebastianbergmann I think this feature should stay. For example, there could be an interface which extends `Traversable`. However, if you mock this interface only, you have no option of actually implementing its Traversable behavior. Therefore, your mock must implement both the given interface, AND either `Iterator` or `IteratorAggregate`.

Second reason for this to stay is that in future PHP will most probably have intersection types (it already has union types in PHP 8.0)

**Comment by mkroeders** [comment]
Perhaps it is an idea for the `Traversable` auto add `IteratorAggregate` as an interface. This adds the `getIterator` as a method to make a successful mock.

Although `Iterator` would provide more customazation, it is possible to create a mock that is returned with the `getIterator` so this could be done but the behaviour is difficult to do in the other way around.
