### ISSUE TITLE
Is there option to set runTestsInSeparateProcesses from the code, not from the DOCBlock ?

### ISSUE THREAD

**Issue by fico7489** [sebastianbergmann/phpunit#3959]
currently : 

```
/**
 * @runTestsInSeparateProcesses
 * @preserveGlobalState disabled
 */
```

I want something like that : 

    public function testCharge(): void
    {
        $this->isolateProccess();
        //...
    }

**Comment by sebastianbergmann** [comment]
No, there is no such option. And an option like that cannot be implemented.
