### ISSUE TITLE
`assertEqualsCanonicalizing` not working as expected

### ISSUE THREAD

**Issue by aand18** [sebastianbergmann/phpunit#3964]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.5.15
| PHP version         | 7.3.6
| Installation Method | Composer 

#### Summary

I'm expecting `assertEqualsCanonicalizing` to respect PHP type conversions, especially string `"0"`  to boolean `FALSE`.

Since "Canonicalizing" is expected to be the lax comparison function, I'd expect it to do the lax PHP comparison which is `==` and, implicitly, respect the type conversions of PHP  ([PHP boolean casting](https://www.php.net/manual/en/language.types.boolean.php#language.types.boolean.casting)).

If one needs strict comparison, there is always `assertEquals`.

#### Current behavior

String `"0"` is not considered equal to boolean `FALSE` when comparing with `assertEqualsCanonicalizing`.

#### How to reproduce

```
\PHPUnit\Framework\Assert::assertEqualsCanonicalizing(false, '0', 'boolean boo-boo');
```
        
#### Expected behavior

`assertEqualsCanonicalizing` should be able to do the same type conversions as PHP, particularly for String `"0"` to boolean (maybe implemented as a flag for backwards compatibility).

Thank you for looking into this.
A

**Comment by mkdesignn** [comment]
I would like to work on this ticket, is't okay?

**Comment by sebastianbergmann** [comment]
`assertEqualsCanonicalizing()` was never intended to perform type conversions. Implementing them now would constitute a break of backward compatibility.
