### ISSUE TITLE
Undefined index warning

### ISSUE THREAD

**Issue by WBDC** [sebastianbergmann/phpunit#3987]
Hi Sebastian, 

| Q                   | A        |
|---------------------|----------|
| PHPUnit version     | 8.2.8    |
| PHP version         | 7.2.14   |
| Laravel Version     | 6.0.4    |
| Installation method | Composer |

#### Summary

When running `phpunit` I get `Notice: Undefined index: warnings in C:\wamp64\www\wbd\vendor\phpunit\phpunit\src\TextUI\TestRunner.php on line 334` warning message.

#### Current behavior

Getting warning message in the console when running `phpunit` command. The test are running, but this warning message showing every time. Tried with `--filter=xxx` with the same result. 

#### How to reproduce

Run `phpunit`. 

#### Expected behavior

Not to show this warning

#### Potential fix
I've dig down to `C:\wamp64\www\wbd\vendor\phpunit\phpunit\src\TextUI\TestRunner.php on line 334` which is  
`foreach ($arguments['warnings'] as $warning) { `  
     `     $this->writeMessage('Warning', $warning);`  
 `}`  

I've wrapped this `foreach` in `if (isset($arguments['warnings'])) {` and when I run `phpunit` in my console the warning message no longer showing and the tests are running too. 

This is the full message from console:  
`PHPUnit 8.5.0 by Sebastian Bergmann and contributors.

Notice: Undefined index: warnings in C:\wamp64\www\wbd\vendor\phpunit\phpunit\src\TextUI\TestRunner.php on line 334

Call Stack:
    0.0004     400464   1. {main}() C:\Users\afeher\AppData\Roaming\Composer\vendor\phpunit\phpunit\phpunit:0
    0.0165    1203216   2. PHPUnit\TextUI\Command::main() C:\Users\afeher\AppData\Roaming\Composer\vendor\phpunit\phpunit\phpunit:61
    0.0166    1212008   3. PHPUnit\TextUI\Command->run() C:\Users\afeher\AppData\Roaming\Composer\vendor\phpunit\phpunit\src\TextUI\Command.php:160
    0.2192    8506648   4. PHPUnit\TextUI\TestRunner->doRun() C:\Users\afeher\AppData\Roaming\Composer\vendor\phpunit\phpunit\src\TextUI\Command.php:201

Warning: Invalid argument supplied for foreach() in C:\wamp64\www\wbd\vendor\phpunit\phpunit\src\TextUI\TestRunner.php on line 334

Call Stack:
    0.0004     400464   1. {main}() C:\Users\afeher\AppData\Roaming\Composer\vendor\phpunit\phpunit\phpunit:0
    0.0165    1203216   2. PHPUnit\TextUI\Command::main() C:\Users\afeher\AppData\Roaming\Composer\vendor\phpunit\phpunit\phpunit:61
    0.0166    1212008   3. PHPUnit\TextUI\Command->run() C:\Users\afeher\AppData\Roaming\Composer\vendor\phpunit\phpunit\src\TextUI\Command.php:160
    0.2192    8506648   4. PHPUnit\TextUI\TestRunner->doRun() C:\Users\afeher\AppData\Roaming\Composer\vendor\phpunit\phpunit\src\TextUI\Command.php:201

.                                                                   1 / 1 (100%)

Time: 13.19 seconds, Memory: 48.00 MB

OK (1 test, 1 assertion)

Generating code coverage report in HTML format ... done [5.06 seconds]`

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by sebastianbergmann** [comment]
Also note what I wrote in https://github.com/sebastianbergmann/phpunit/pull/3977#issuecomment-562815411 as I think that this is the same issue.

**Comment by WBDC** [comment]
> Thank you for your report.
> 
> Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.
> 
> Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

Hi Sebastian, 

When I run `phpunit` this warning shows. This is nothing to do with any of my test cases.

**Comment by sebastianbergmann** [comment]
I do not get the warning with any of my test suites. This makes me think that it has something to do with the tests being run. I will investigate this next week.

**Comment by tvercruysse** [comment]
@WBDC can you check your actual phpunit version with `phpunit --version` ?
It is possible that your composer global requirement is set to `7.x`

what happens if you run `C:\wamp64\www\wbd\vendor\bin\phpunit`

if this fixes the problem, i'd suggest opening
`C:\Users\afeher\AppData\Roaming\Composer\composer.json`

and updating the phpunit major version accordingly.

**Comment by voidgraphics** [comment]
@tvercruysse that worked for me. Updating the global phpunit version got rid of the warnings. Thanks 👍

**Comment by WBDC** [comment]
@tvercruysse The phpunit in composer is `"phpunit/phpunit": "^8.0"`

Just by typing `phpunit` gives `PHPUnit 8.5.0 by Sebastian Bergmann and contributors` (image below)
![image](https://user-images.githubusercontent.com/50083290/70911649-39d14800-200a-11ea-8b31-6b43b8fdd741.png)
![image](https://user-images.githubusercontent.com/50083290/70911731-67b68c80-200a-11ea-8c2a-1f4add15bb5b.png)

The global composer for the phpunit was `^8.2`. The warning not showing anymore after doing a global composer update. 

Many thanks for the help! Its silly mistake, but learned something today. Thank you!

**Comment by WBDC** [comment]
@sebastianbergmann Could you please close this ticket as it is resolved. Maybe worth to put this in the documentation? Even if this wasn't phpunit fault, (purely  my mistake), but I'm sure others would find it useful. 
Thanks for looking into it though!

**Comment by sebastianbergmann** [comment]
[You do not want to install PHPUnit globally.](https://phpunit.readthedocs.io/en/8.5/installation.html#global-installation)

**Comment by COil** [comment]
I had the same problem, it was I wan running the phpunit script of the Symfony bridge I think in `./bin` instead of using: `./vendor/bin/phpunit`.
