### ISSUE TITLE
Website Backdoor-Webshell File Found

### ISSUE THREAD

**Issue by lb491798689** [sebastianbergmann/phpunit#3989]
<img width="702" alt="WX20191217-115518@2x" src="https://user-images.githubusercontent.com/21698323/70963689-3d290a00-20c4-11ea-84b3-e09c6385c089.png">

https://github.com/sebastianbergmann/phpunit/blob/master/src/Util/PHP/eval-stdin.php#L14

This code is considered a Trojan horse in Aliyun Server, can i ignore the notice.

**Comment by sebastianbergmann** [comment]
[You do not want to put PHPUnit onto your webserver.](https://phpunit.readthedocs.io/en/8.5/installation.html#webserver)
