### ISSUE TITLE
PHP 7.4 fixtures

### ISSUE THREAD

**Issue by dpauli** [sebastianbergmann/phpunit#4001]
There are some little changes in PHP 7.4 with could break the normal usage of PHPUnit. Perhaps these things can be fixed:

- Failure return values of `fread()` is now `false` and not `''`, see https://github.com/sebastianbergmann/phpunit/blob/master/src/Util/PHP/DefaultPhpProcess.php#L147

**Comment by sebastianbergmann** [comment]
A pull request for this would be appreciated.
