### ISSUE TITLE
Option to catch "opt-in" deprecations

### ISSUE THREAD

**Issue by kamazee** [sebastianbergmann/phpunit#4003]
Recently, triggering deprecation messages using `@trigger_error('Deprecation message', E_USER_DEPRECATED)` (note the silencing operator) has become a de-facto standard way to deal with deprecations, and it would be nice if PHPUnit had a convenient way to report them. It doesn't happen due to [this](https://github.com/sebastianbergmann/phpunit/blob/05ef7aed05e2ef6866301086e6041c9dc7af197f/src/Util/ErrorHandler.php#L81), which seems to be perfectly reasonable in general (e.g. there's no other good way to make `mkdir` work safely other than calling it with `@`, and PHPUnit definitely shouldn't raise such errors); so I propose to add a configuration option that makes error handler handle an error of `E_USER_*` type regardless of `error_reporting` (i.e. without respect to whether silencing has been used or not).

Symfony implemented this in their phpunit-bridge: they [gather deprecations](https://github.com/symfony/phpunit-bridge/blob/master/Legacy/SymfonyTestsListenerTrait.php#L303), then run matching against an expectation; however, it's not a symfony-specific thing: Doctrine [does it](https://github.com/doctrine/orm/blob/2.8.x/lib/Doctrine/ORM/Mapping/UnderscoreNamingStrategy.php#L64), too, and I think it makes sense to add possibility for PHPUnit to be more strict towards such deprecations (and user defined errors in general). Also, the Symfony bridge itself is a controversial thing that I'd personally avoid while it's possible.

I volunteer to work on it if such addition is welcome. @sebastianbergmann , what do you think? My original plan was to introduce a new configuration option, `unsilenceUserDefinedErrors`, and make `E_USER_*` fall below [this check](https://github.com/sebastianbergmann/phpunit/blob/05ef7aed05e2ef6866301086e6041c9dc7af197f/src/Util/ErrorHandler.php#L81) as long as the option is set to `true` while letting it be `false` by default.

**Comment by sebastianbergmann** [comment]
This makes sense to me and I look forward to your pull request.
