### ISSUE TITLE
The command "bin/phpunit" exited with 1 even though no test failed

### ISSUE THREAD

**Issue by escopecz** [sebastianbergmann/phpunit#4004]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | ~7.5.0
| PHP version         | 7.2.25
| Installation Method | Composer

#### Summary

I created a PR for Mautic (open source project) where I [updated several dependencies](https://github.com/mautic/mautic/pull/8291/files?file-filters%5B%5D=.json&file-filters%5B%5D=.lock&file-filters%5B%5D=.yml#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780). Only minor version upgrades. But PHPUNIT started to fail with no obvious reason. Here is Travis CI:

https://travis-ci.org/mautic/mautic/jobs/633670035#L875

#### Current behavior

PHPUNIT exists with 1 which marks the Travis job as failed even though no tests are failing.

#### How to reproduce
1. `git clone git@github.com:mautic/mautic.git`
2. `git checkout -b escopecz-composer-minor-versions-update 3.x`
3. `git pull https://github.com/escopecz/mautic.git composer-minor-versions-update`
4. `composer install`
5. `composer.test`
6. `echo $?` (will echo 1, I'd expect 0)

#### Expected behavior

Follow the reproduction steps, it should exit with 0.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by escopecz** [comment]
Ok, so we had to disable the deprecation notices. I was hoping we could have those in the CI so we'd be constantly reminded that there is some tech debt to fix.

So if you get `Remaining indirect deprecation notices` in your PHPUNIT output, the command will return 1 and the CI will fail the job. This phpunit.xml configuration fixes CI for us:

```xml
    <php>
        <env name="SYMFONY_DEPRECATIONS_HELPER" value="disabled" />
    </php>
```
