### ISSUE TITLE
255 exit code on circleci job run on docker 

### ISSUE THREAD

**Issue by krushn** [sebastianbergmann/phpunit#4007]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.8
| PHP version         | 7.3.9 
| Installation Method | Composer  

#### Summary
 
Framework: Yii2 

Getting 255 error on running circleci job in docker for unit testing

<img width="429" alt="Screenshot 2020-01-07 at 11 00 30 PM" src="https://user-images.githubusercontent.com/10800870/71966306-589cb600-3227-11ea-856b-33c8f4464dc6.png">

#### How to reproduce
 

1.  install packages in yii2 project with below composer.json 

Our composer.json 
`
{
    "name": "pogi",
    "description": "Pogi",
    "version": "0.9.0",
    "keywords": ["platform"],
    "homepage": "https://localhost.io",
    "type": "project",
    "minimum-stability": "stable",
    "require": {
        "php": ">=5.4.0",
        "yidas/yii2-composer-bower-skip": "~2.0.0",
        "yiisoft/yii2": "~2.0.6",
        "yiisoft/yii2-bootstrap": "~2.0.0",
        "yiisoft/yii2-swiftmailer": "~2.0.0",
        "yiisoft/yii2-httpclient": "dev-master",
        "yiisoft/yii2-redis": "~2.0.0",
        "openbuildings/swiftmailer-css-inliner": "*",
        "yiisoft/yii2-jui": "*",
        "yiisoft/yii2-authclient": "^2.1",
        "yiisoft/yii2-imagine": "^2.1",
        "kartik-v/yii2-mpdf": "dev-master",
        "notamedia/yii2-sentry": "^1.3",
        "cloudinary/cloudinary_php": "^1.8",
        "stripe/stripe-php": "^6.6",
        "symfony/css-selector": "^3.4", 
        "yiisoft/yii2-shell": "^2.0",
        "understeam/yii2-slack": "v0.3.0",
        "aws/aws-sdk-php": "^3.67",
        "willdurand/email-reply-parser": "^2.8",
        "algolia/algoliasearch-client-php": "^2.4",
        "codeception/codeception": "^4.0",
        "codeception/specify": "^1.2",
        "codeception/verify": "^1.2",
        "phpunit/phpunit": "^8.5"
    },
    "require-dev": {
        "yiisoft/yii2-debug": "~2.0.0",
        "yiisoft/yii2-gii": "~2.0.0",
        "yiisoft/yii2-faker": "~2.0.0",
        "elisdn/yii2-gii-fixture-generator": "^1.1",
        "codeception/module-filesystem": "^1.0",
        "codeception/module-yii2": "^1.0",
        "codeception/module-rest": "^1.0",
        "codeception/module-asserts": "^1.1"
    },
    "config": {
        "process-timeout": 1800,
        "fxp-asset":{
            "installer-paths": {
                "npm-asset-library": "vendor/npm",
                "bower-asset-library": "vendor/bower"
            }
        }
    }
}
`

2. add unit test 
3. set up circleci and docker 
4. add circleci to project and add below code in .circleci.yml

`
# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - master
        - develop
    docker:
      # specify the version you desire here
      - image: circleci/php:7.3-apache-stretch-node-browsers

      - image: circleci/mysql:5.7
        environment:
          MYSQL_DATABASE: pogi_test
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: true
        command:
            mysqld --sql-mode=NO_ENGINE_SUBSTITUTION --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --innodb-large-prefix=true

    # Specify Server Type. Keep it as small as possible to reduce costs
    resource_class: small

    working_directory: ~/pogi

    steps:
      - checkout

      - run:
          name: Install things we need
          command: |
            sudo apt-get update
            sudo apt-get install -y libpng-dev libmcrypt-dev libreadline-dev mysql-client zip zlib1g-dev

      - run:
          name: Install PHP exts
          command: |
            sudo docker-php-ext-install zip
            sudo docker-php-ext-install gd
            sudo apt-get install
            sudo docker-php-ext-install pdo_mysql && sudo docker-php-ext-enable pdo_mysql
        # sudo docker-php-ext-configure intl
        # sudo docker-php-ext-install intl

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Dependencies
          command: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run:
          name: Configure secondary database for Analytics
          command: mysql -h 127.0.0.1 -u root -e "CREATE DATABASE pogi_analytics_test"

      - run:
          name: Initialize Dev Environment
          command: ./init --env=Circle-CI --overwrite=All

      - run:
          name: Install DB Migrations
          command: ./yii_test migrate --interactive=0

      - run:
          name: Run Codeception tests and store result output
          command: cd ./admin && ../vendor/bin/codecept run --debug --xml --html --fail-fast

      #- store_test_results:
      #    path: /tmp

      #- store_artifacts:
      #    path: /tmp/report.html
      #    destination: report
 `

5. run circleci job in docker 

#### Expected behavior
 
circleci job should be success in docker

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by krushn** [comment]
Unit tests working in command prompt but not in docker after updating Yii2 project/composer packages

**Comment by sebastianbergmann** [comment]
If it works without Docker and does not work with Docker then this is likely not a PHPUnit issue.
