### ISSUE TITLE
Inconsisten behaviour between at() and excactly() invocation constrantits

### ISSUE THREAD

**Issue by Redominus** [sebastianbergmann/phpunit#4009]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.5.1
| PHP version         | 7.3.11
| Installation Method | Composer

#### Summary

Mocking a class method with params by reference generates an inconsistent behaviour of expects constraints. at() and any() behaves differently than exactly() and atLeast().

#### Current behavior

Mocking consecutive calls to a method with arguments by reference and different value have two outcomes depending on the used constraint in the expects method:
Using at() and verifying the expected values using with($this->equalsTo('foo')) or any() and withConsecutive() the test passes. 
But using exactly() or atLeast() and verifying the expected values using withConsecutive() the test fails.

#### How to reproduce
Micro project with composer, the test, class to be tested with the iteration calling the mokced class the problematic method.
[bug_testcode.zip](https://github.com/sebastianbergmann/phpunit/files/4034571/bug_testcode.zip)

Commenting the last expects() of the test makes it green.
#### Expected behavior

A consistent behaviour.

**Comment by sebastianbergmann** [comment]
`at()` has been removed.

**Comment by waaeabad** [comment]
Disculpa podrían avisarle cualquier cosa a
Iram Jaramillo
Su Gmail es
***@***.***
Gracias

**Comment by waaeabad** [comment]
https://secure.avaaz.org/community_petitions/es/todos_una_oportunidad_mas/?cSADDsb&utm_source=sharetools&utm_medium=copy&utm_campaign=petition-1320264-una_oportunidad_mas&utm_term=cSADDsb%2Bes

**Comment by waaeabad** [comment]
Responde mi encuesta: https://es.surveymonkey.com/r/8XVSVHV
