### ISSUE TITLE
Cannot disable deprecated exceptions (Magento 2.3.3)

### ISSUE THREAD

**Issue by paul-gene** [sebastianbergmann/phpunit#4014]
I have tried following the advice here https://stackoverflow.com/a/43759738 to stop PHPUnit breaking on deprecated functions.

I'm running PHP 7.1.33 and PHPUnit 6.5.14.

I tried adding `\PHPUnit\Framework\Error\Deprecated::$enabled = false;` to the bootstrap file that is included, but no matter where I put it, PHPUnit breaks when it throw the deprecated exception.

I also tried using `convertDeprecationsToExceptions` and setting it to false, but that doesn't work either.

**Comment by sebastianbergmann** [comment]
PHPUnit 6.5 is no longer supported. Please open a new ticket in case this still applies to a supported version of PHPUnit.
