### ISSUE TITLE
Allow Symfony 5 in PHPUnit 5.7

### ISSUE THREAD

**Issue by peter-gribanov** [sebastianbergmann/phpunit#4016]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 5.7.x
| PHP version         | 7.4
| Installation Method | Composer

I understand that version 5.7 has not been supported for a very long time, but i wonder if it is possible to add support for Symfony 5 to it?
I understand that the answer will most likely be **No**, but just in case i wanted to ask.

**Comment by sebastianbergmann** [comment]
No.

**Comment by peter-gribanov** [comment]
Thanks :satisfied:
