### ISSUE TITLE
Do I need always write @cover annotations for code coverage?

### ISSUE THREAD

**Issue by zeyser** [sebastianbergmann/phpunit#4018]
Can't find any information about this. If I have whitelisted filter with directory of tests, do I need for every class set @cover annotation. Because I thought all classes in whitelisted directory would be in code coverage.

**Comment by sebastianbergmann** [comment]
Only if you enforce the usage of `@covers` annotations in your `phpunit.xml`.

**Comment by zeyser** [comment]
> Only if you enforce the usage of `@covers` annotations in your `phpunit.xml`.

Thank you! It was my case.
