### ISSUE TITLE
PHPUnit Does not recognise PHP sodium library predefined constant

### ISSUE THREAD

**Issue by pavrip** [sebastianbergmann/phpunit#4021]
I am using PHPUnit for the first time and this is probably the first time I am posting an issue here, so please forgive me if I do not do this the right way.
 I am getting a strange error with PHPUnit.

PHP Unit is not picking up PHP sodium constants even though it is part of the PHP core and I have tested all the code without PHP unit and it works fine, there are no errors.

I have a simple Token Class (Tested before using PHPUnit and works),
code:

class Token
{

	public $formats = ['bin', 'hex', 'base64'];

	protected $token;

	protected $mac;

	protected $key;

	protected $format;

	protected $bytes;
	

	function __construct(string $format, int $bytes=32)
	{
		if ($this->check_format($format)) {

			$this->format = $format;
			$this->bytes = $bytes;

			$this->token = $this->generate($this->format, $this->bytes);
			$this->mac_gen();
			$this->format_mac_gen($this->format);
					
		}else{
			$this->format = false;
		}
	}

       protected function mac_gen()
	{
		$this->key = random_bytes(SODIUM_CRYPTO_AUTH_KEYBYTES);
		$this->mac = sodium_crypto_auth($this->token, $this->key);
		return $this;
	}

       //Test Function:

      class TokenTest extends TestCase
     {
	public function test_token_constructor()
	{
		//Checks that the right value has been set
		$token = new Token('hex');
		$this->assertEquals('hex', $token->get_format());
		
		//Checks the bytes
		$token2 = new Token('bin', 36);
		$this->assertEquals($token2->get_bytes(), 36);

		$token3 = new Token('base64');
		$this->assertEquals($token3->get_format(), false);
	}	
    }

Result:
E                                                                   1 / 1 (100%)

Time: 119 ms, Memory: 4.00 MB

There was 1 error:

1) tests\tokens\TokenTest::test_token_constructor
Use of undefined constant SODIUM_CRYPTO_AUTH_KEYBYTES - assumed 'SODIUM_CRYPTO_AUTH_KEYBYTES' (this will throw an Error in a future version of PHP)

/Users/peshotanpavri/Sites/MAP-1/root/map/token/Token.php:150
/Users/peshotanpavri/Sites/MAP-1/root/map/token/Token.php:34
/Users/peshotanpavri/Sites/MAP-1/tests/tokens/TokenTest.php:14

**Comment by pavrip** [comment]
Just to confirm:
Works perfectly in the actual script:
//index.php

$token = new map\token\Token('hex');//Choosing a
var_dump($token);

**Comment by pavrip** [comment]
Actually it does not seem to be an issue with Sodium specifically, It does not even like the sodium_crypto_auth() function, says method not defined,
I have a config file which is declared in index.php with some predefined constants,

It does not even pick that up, even when I include the file directly it cant pick it,

Am I missing something?

**Comment by sebastianbergmann** [comment]
You are missing the fact that you PHP interpreter does not have the Sodium extension loaded.

**Comment by pavrip** [comment]
How is this possible?, Im using php7.3, its a core extension and it works outside of php-unit
I was struggling to find it, I used PHP Storm to ensure I added the file path to the executable, I checked the phpini and it shows all loaded extensions, I saw sodium there

**Comment by pavrip** [comment]
It seems like it works in PHPStorm, but when I use my terminal it does not work properly

**Comment by pavrip** [comment]
The PHP interpreter has the extension loaded, Im using it in my project and even PHPStorm shows it as a loaded extension.
I cant understand why this is happening, this should not even be an issue as it is a core extension.
Even PHP's built in function getallheaders() is not working
