### ISSUE TITLE
Remove @internal annotation from TestCase::setName()?

### ISSUE THREAD

**Issue by webignition** [sebastianbergmann/phpunit#4025]
I need the ability to programmatically set the name of a test to something other than the method name. I'm happy to go into the details of why but don't want to go off on a tangent just yet.

I can achieve this by calling `setName()` within a test method. This currently works as expected.

`TestCase::setName()` is marked as `@internal` and as such there are no guarantees that this method will always be publicly callable from within a test method.

Can we remove the `@internal` annotation from `TestCase::setName()`?

 I'm open to any alternative that will continue to allow me to set the name of a test from within the test method and which is covered by the backward compatibility promise.

**Comment by sebastianbergmann** [comment]
Please explain your use case.

**Comment by webignition** [comment]
Having had a closer look at what I need and how I can achieve it, I have found an alternative way of handling this.

Sorry to have wasted your time!
