### ISSUE TITLE
When I refer to the execution of PHPUnit, it only recognizes the first singleton,

### ISSUE THREAD

**Issue by lifeblood** [sebastianbergmann/phpunit#4028]
When I refer to the execution of PHPUnit with Lumen web framework , it only recognizes the first singleton,
/agentrank
/getvipinfo
  public static function getInstance ($ serviceName)
     {
         if (is_null (static :: $ instance)) {
             static :: $ instance = static :: $ classPath. $ serviceName;
         }

         Log :: error ('getInstance:'. Static :: $ instance);

         return static :: $ instance;
     }

======

[2020-01-29 19:57:31] testing.ERROR: getInstance: App\Http\Services\GameWeb\agentRank  
[2020-01-29 19:57:32] testing.ERROR: getInstance: App\Http\Services\GameWeb\agentRank  

WHY?

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.

**Comment by lifeblood** [comment]
where have a support forum?

**Comment by epdenouden** [comment]
@lifeblood The PHPUnit project doesn't have its own support forum, afaik. Developers will ask their questions in PHP communities on StackOverflow, Reddit, Slack etc.

**Comment by epdenouden** [comment]
> WHY?

An additional tip: the problem you want to discuss is very dependent on the context. You already mention Lumen, two different singletons that you expect to see on two different endpoints... I'm guessing?

You might consider checking with the Lumen community first, as this must be a common issue people run into when API/web testing.
