### ISSUE TITLE
ioctl error when running from git hook

### ISSUE THREAD

**Issue by SunflowerFuchs** [sebastianbergmann/phpunit#4029]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.5.2
| PHP version         | 7.4.2 & 7.3.14
| Installation Method | Composer ([`composer info` output](https://github.com/sebastianbergmann/phpunit/files/4133398/composer.info.txt))

#### Summary

Running phpunit from within git hooks throws an error message (does not seem to affect the actual tests being run).

#### Current behavior

Whenever phpunit gets run from within a git hook, it gives me the following error message: `stty: 'standard input': Inappropriate ioctl for device`.
This happens no matter what phpunit actually does, even on the `--help` output.

#### How to reproduce

Minimal example with nothing but phpunit and the git hook.

```
mkdir test
cd test
git init
composer require phpunit/phpunit
echo "./vendor/bin/phpunit" > .git/hooks/pre-commit
chmod +x .git/hooks/pre-commit
git commit -au
```

#### Expected behavior

No error message

**Comment by sebastianbergmann** [comment]
This is not a PHPUnit issue AFAICS.

**Comment by SunflowerFuchs** [comment]
Thanks for the quick response!

You're right, I've debugged myself into the code a bit and I've found out that it's not PHPUnit itself, but one of the libraries. 
I'll go open an issue there (which is also your library, so I'll see you in a bit haha)
