### ISSUE TITLE
PHP 8 coverage

### ISSUE THREAD

**Issue by absalomedia** [sebastianbergmann/phpunit#4031]
Running PHP nightly (8.0.0-dev) on Travis for forward compatibility for PHP extension tests & phpunit is failing

> 
> $ php --version
> 
> PHP 8.0.0-dev (cli) (built: Jan 30 2020 10:49:58) ( ZTS )
> 
> Copyright (c) The PHP Group
> 
> Zend Engine v4.0.0-dev, Copyright (c) Zend Technologies
> 
>     with Zend OPcache v8.0.0-dev, Copyright (c), by Zend Technologies
> 
> $ composer --version
> 
> Composer version 1.9.2 2020-01-14 16:30:31
> 
> before_install.1
> 
> 0.00s$ echo $LANG
> before_install.2
> 
> 0.00s$ echo $LC_ALL
> 
> 16.85s$ composer require satooshi/php-coveralls --dev
> 
> Using version ^1.0 for satooshi/php-coveralls
> 
> ./composer.json has been updated
> 
> Loading composer repositories with package information
> 
> Updating dependencies (including require-dev)
> 
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
> 
>     - Installation request for phpunit/phpcov ^3.1 -> satisfiable by phpunit/phpcov[3.1.0].
> 
>     - phpunit/phpcov 3.1.0 requires php ^5.6 || ^7.0 -> your PHP version (8.0.0-dev) does not satisfy that requirement.
> 
>   Problem 2
> 
>     - phpunit/phpunit 5.7.9 requires php ^5.6 || ^7.0 -> your PHP version (8.0.0-dev) does not satisfy that requirement.
> 
>     - phpunit/phpunit 5.7.8 requires php ^5.6 || ^7.0 -> your PHP version (8.0.0-dev) does not satisfy that requirement.
> 
>     - phpunit/phpunit 5.7.7 requires php ^5.6 || ^7.0 -> your PHP version (8.0.0-dev) does not satisfy that requirement.
> 
>     - phpunit/phpunit 5.7.6 requires php ^5.6 || ^7.0 -> your PHP version (8.0.0-dev) does not satisfy that requirement.

https://travis-ci.org/absalomedia/sassphp/jobs/644146987

**Comment by sebastianbergmann** [comment]
Please read your Composer output again (there is no PHPUnit issue here).
