### ISSUE TITLE
Ability to assert object equality while ignoring specified keys

### ISSUE THREAD

**Issue by raceybe** [sebastianbergmann/phpunit#4034]
I'm trying to compare object properties recursively, while ignoring keys that are expected or known to be different. I couldn't find any PHPUnit implementation, but a few people (including myself) seem to be looking for it:

https://www.reddit.com/r/PHP/comments/8t7vht/phpunit_assert_equals_doctrine_entity/

https://stackoverflow.com/questions/43589561/phpunit-getting-equalto-assertion-to-ignore-property/60122496#60122496

The following as a private method on my test case, but I think it would be useful in the core code. If the functionality is there, then a pointer in the right direction would be helpful:

```
private function assertObjectsEqualWithIgnore($refObject, $testObject, $ignoreKeys = ['id', 'password']): void
{
    foreach ($refObject as $key => $value) {
        if (is_array($refObject->$key)){
            // array, so iterate elements
            for ($i=0; $i < count($refObject->$key); $i++){
                $this->assertObjectsEqualWithIgnore($refObject->$key[$i], $testObject->$key[$i], $ignoreKeys);
            }
        } else if (is_object($refObject->$key)) {
            // object, so iterate keys
            $this->assertObjectsEqualWithIgnore($refObject->$key, $testObject->$key, $ignoreKeys);
        }else {
            // ignore the ID and password fields
            if (!in_array($key, $ignoreKeys)){
                echo "{$key}\n";
                $this->assertEquals($refObject->$key, $testObject->$key);
            }
        }
    }
}
```

**Comment by sebastianbergmann** [comment]
I do not hink that this belongs in PHPUnit. And may I suggest that instead you implement a custom comparator.
