### ISSUE TITLE
Annotations for ignoring code from code coverage are unintentionally ignored by default

### ISSUE THREAD

**Issue by kukulich** [sebastianbergmann/phpunit#4036]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.0.0
| PHP version         | 7.4.2
| Installation Method | Composer

#### Summary

`@codeCoverageIgnoreStart` annotation does not work.

#### Current behavior

![coverage](https://user-images.githubusercontent.com/260445/74130917-82a91580-4be3-11ea-8760-a5e3dc9c0a43.png)

#### How to reproduce

https://github.com/slevomat/coding-standard/blob/master/SlevomatCodingStandard/Helpers/TypeHelper.php#L24

#### Expected behavior

The ignored line should not be marked as not covered.

**Comment by sebastianbergmann** [comment]
This is a bug in PHPUnit itself after all: due to a mistake I made while working on #3914, the processing of annotations such as `@codeCoverageIgnoreStart` is ignored by default in PHPUnit 9.0.0.

**Comment by curry684** [comment]
Funny how I just ran into this to find it fixed 3 hours ago  :)

However - 'ignored by default' implies I should be able to fix it by adding `         disableCodeCoverageIgnore="false"` to the `phpunit.xml`, but that doesn't change a thing. Don't you mean they are always ignored, not just by default?
