### ISSUE TITLE
Fatal Error: cannot redeclare assertArrayHasKey()

### ISSUE THREAD

**Issue by LeonardoCor** [sebastianbergmann/phpunit#4038]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.0.0
| PHP version         | 7.4.2
| Installation Method | PHAR

#### Summary

Running PHPUnit in Windows 8.1 command line, I get a fatal error, even if tests are executed
![Immagine](https://user-images.githubusercontent.com/46627003/74144640-6a45f480-4bfd-11ea-9d36-48c2da978931.png)
.

#### Current behavior

I get the following Fatal Error:
cannot redeclare PHPUnit\Framework\assertArrayHasKey()

#### How to reproduce

Execute PHPUnit in command line for any test suite.

#### Expected behavior

No PHP error thrown.

**Comment by sebastianbergmann** [comment]
Looks to me like you have PHPUnit installed using Composer, too.

**Comment by LeonardoCor** [comment]
Got it. Thanks.

**Comment by rajeshr101** [comment]
I also installed the PHPUnit in symfony by using composer I am also getting the same error. How to fix it,
![image](https://user-images.githubusercontent.com/66621966/92359918-a85eb480-f109-11ea-9766-74fbaf5db3a2.png)

and I installed the PHPUnit by using this command - 
C:\xampp\htdocs\NASLAApps\naslaapps-scorecard-mtd-merge>composer require --dev phpunit/phpunit ^9.2 

and after running the PHPunit - I am getting this error -
C:\xampp\htdocs\NASLAApps\naslaapps-scorecard-mtd-merge>phpunit --filter testCalculatesPassForAllPassingScores

PHP Fatal error:  Cannot redeclare PHPUnit\Framework\assertArrayHasKey() (previously declared in phar://C:/xampp/php/phpunit.phar/phpunit/Framework/Assert/Functions.php:87) in C:\xampp\htdocs\NASLAApps\naslaapps-scorecard-mtd-merge\vendor\phpunit\phpunit\src\Framework\Assert\Functions.php on line 79

How to resolve this can you help me.
