### ISSUE TITLE
Deprecate custom TestSuiteLoader

### ISSUE THREAD

**Issue by flow-control** [sebastianbergmann/phpunit#4039]
Hi there,

as we started with refactoring the `StandardTestSuiteLoader` in #3859 it is now time to go even further and deprecate the possibility to have a custom `TestSuiteLoader` at all. This would mean to deprecate the Interface, the `StandardTestSuiteLoader` and the `testSuiteLoaderClass` and `testSuiteLoaderFile` configuration settings.

I would be happy to provide a PR for this.

/Flo

This originates from https://github.com/sebastianbergmann/phpunit/pull/4037#issuecomment-584133301

**Comment by sebastianbergmann** [comment]
Yes, please.

**Comment by sebastianbergmann** [comment]
@flow-control This can be closed, right?

**Comment by flow-control** [comment]
@sebastianbergmann yes
