### ISSUE TITLE
Add an option to merge coverage with an existing one instead of replacing it

### ISSUE THREAD

**Issue by jclaveau** [sebastianbergmann/phpunit#4041]
Presently `--coverage-html` or `--coverage-clover` always erase the coverage of the previous run. 
Adding the possibility to merge coverage results would allow developers to test scripts using shell_exec for example or have the real coverage while filtering tests. It would also help to cover code that has specific parts by php version for example.

A lighter solution could be to provide a `--cover-custom` to specify a custom Report class handling merging for those who need it.

Thanks for all your work!

**Comment by sebastianbergmann** [comment]
This is outside the scope of PHPUnit.
