### ISSUE TITLE
Expose random seed value

### ISSUE THREAD

**Issue by Bilge** [sebastianbergmann/phpunit#4044]
For tests which also introduce an element of randomness, their seed should be synchronized with the PHPUnit seed for the tests to be predictable and reproducible. However, it seems PHPUnit only prints its seed but does not expose it programmatically to tests, so synchronizing the seed is not currently possible.

**Comment by sebastianbergmann** [comment]
@epdenouden What do you think?

**Comment by sebastianbergmann** [comment]
I thought about this and have to say that while I can imagine that this could be useful I do not really like the fact that an implementation detail of PHPUnit would be used in a test.

**Comment by Bilge** [comment]
We could also just forward the seed to `mt_srand` so it does not need to be exposed. That would require randomness in tests to always come from `mt_rand` and would not permit any other implementations.

**Comment by epdenouden** [comment]
Honestly I had not thought about this scenario @Bilge. I agree with @sebastianbergmann that exposing runner internals to tests causes more headaches than it solves. I will give this some more thought.

A workaround that makes the random seed external to both PHPUnit and the tests: put the random seed in the environment and feed it to PHPUnit by way of `--random-order-seed=$RANDOM` and access in the tests and fixtures with `getenv()`. This way it is not an implementation detail but simply part of the context the tests are run in.

The randomizer itself is no more complex than a `mt_srand` and `shuffle` combo.

**Comment by epdenouden** [comment]
@Bilge Does the above solution work for you?

Whether it does or not, I am still quite curious about the details of your scenario. I had not considered it before and curious to learn what _exactly_ you want to happen. :)

**Comment by epdenouden** [comment]
Haven't heard anything, closing ticket.
@Bilge still curious about your exact use case, let me know if you like to discuss this further! :)
