### ISSUE TITLE
"willReturn" cannot be re defined ?

### ISSUE THREAD

**Issue by johndodev** [sebastianbergmann/phpunit#4046]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     |8.3.0
| PHP version         | 7.4
| Installation Method | Composer 

Hello,

I don't understand this behavior : 

```
$mock = $this->createMock('SomeClass');

$mock->method('someMethod')->willReturn(false);
$mock->method('someMethod')->willReturn(true);

// will always return false
$mock->someMethod();
```

Why is it not possible to re call "willReturn" with another value ? 
And why there is no error if we do it, since there will not work ?

The use case is when I create some mocks on the setUp(), but for one of many tests I need to redefine a return value.

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.

**Comment by johndodev** [comment]
Someone : A basic progamming incoherence in this library ?
Phpunit : *deleting the "support" issue template* 

![oops](https://user-images.githubusercontent.com/2741956/74256338-7d3af080-4cf3-11ea-875c-8cde81d50a80.png)

> no support !


👌
