### ISSUE TITLE
Make willReturn behavior logical

### ISSUE THREAD

**Issue by johndodev** [sebastianbergmann/phpunit#4048]
Hello, 

There is a behavior which anywone reading it will consider as a bug : 

```
$mock = $this->createMock('SomeClass');

$mock->method('someMethod')->willReturn(false);
$mock->method('someMethod')->willReturn(true);

// will always return false but should return true ?
$mock->someMethod();
```

I suggest to fix it.

:trollface:

**Comment by sebastianbergmann** [comment]
"Fixing" this would break backward compatibility.

**Comment by mfn** [comment]
@johndodev not a solution to your problem with MockObject directly, but that's one of the reasons I use https://github.com/mockery/mockery

In your case it would allow you to specify different return values on multiple invocations:
```php
$mock = \Mockery::mock(SomeClass::class);
$mock->shouldReceive('someMethod')->andReturn(false)->once();
$mock->shouldReceive('someMethod')->andReturn(true)->once();
```
Specifying a quantifier is important here (same approach doesn't work with MockObject).

Another big difference is default mocked expectations: MockObject by default swallows all calls and returns null => Mockery OTOH does not accept "unspecified expectations". I find that behaviour more useful in practice to avoid forgetting that certain methods might even have been called (more "strict").

**Comment by sebastianbergmann** [comment]
This should be taken care of in #3158.
