### ISSUE TITLE
Tests for assertStringNotEqualsFileCanonicalizing()

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#4055]

**Comment by Diraneh** [comment]
Try to use TestNG with  assertStringEquals to see if that is  false and then use your  assertStringNotEquals in your file

**Comment by sebastianbergmann** [comment]
> Try to use TestNG with assertStringEquals to see if that is false and then use your assertStringNotEquals in your file

This repository is for PHPUnit (a PHP testing framework) and not about TestNG (a Java testing framework). And this is issue is about adding tests to PHPUnit's own test suite and not a question, for instance.

**Comment by alecsmrekar** [comment]
#4645
