### ISSUE TITLE
Remove assertEqualXMLStructure()

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#4092]
I have never understood the use case for this assertion and have never seen it used in the wild.

**Comment by mitch292** [comment]
Hi - @sebastianbergmann  - I'd be happy to take a stab at some of these assertion deprecations for v10.  Will there be a 10.X branch that we should submit PRs against?

**Comment by toriqo** [comment]
never had to text XML data? Twilio, for example, and its SDK. When you respond to Twilio's requests to your own server, you do it using XML...
