### ISSUE TITLE
Cannot run tests with globally installed PHPUnit 9-phar

### ISSUE THREAD

**Issue by mvoelker** [sebastianbergmann/phpunit#4094]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.0.1
| PHP version         | 7.4.2
| Installation Method | Composer (in the project) / PHAR (globally)

#### Summary

We've upgraded the dependency in composer.json in our project to:
`"phpunit/phpunit": "9.*"`

Running the tests via `vendor\bin\phpunit` works without any problems.
Running the tests via phpunit-9.phar does NOT work anymore.
Working on Windows 10.

#### Current behavior

Running the tests via the globally installed `phpunit-9.phar` does not work and emits a fatal error:
`
Fatal error: Cannot redeclare PHPUnit\Framework\assertArrayHasKey() (previously declared 
in phar://C:/phpTools/phpunit9.phar/phpunit/Framework/Assert/Functions.php:85) in 
D:\project\vendor\phpunit\phpunit\src\Framework\Assert\Functions.php on line 84
`

#### How to reproduce

Have a project with `"phpunit/phpunit": "9.*"` dependency.
Run the tests with `phpunit-9.phar`.

#### Expected behavior

We never had this problem and we can run this setup with `phpunit-8.phar` (= PHPUnit 8.5.2) or `phpunit-7.phar` (= PHPUnit 7.5.20).
We use PHPUnit as phar installation on our Jenkins-CI (on Ubuntu 16.04) setup. Never had any problems. Same problem with phpunit-9.phar there.

We would expect that running the testsuite with PHPUnit 9 (installed as phar) works too.

**Comment by sebastianbergmann** [comment]
It appears that you have different installations of PHPUnit mixed up.

For instance, you may have used Composer to install PHPUnit and have configured the autoloader generated by Composer as PHPUnit's bootstrap script but then you invoke PHPUnit using an executable other than `vendor/bin/phpunit`.

**Comment by fizzka** [comment]
+1, it wasn't a problem before phpunit9.
maybe, functions have to be placed in conditon? `if (function_exists)` ? 

tightenco/collect (laravel collections) doing this way:
https://github.com/tightenco/collect/blob/laravel-7-ongoing/src/Collect/Support/helpers.php#L8

**Comment by picfab** [comment]
HI
Sorry for my english and my level in dev. I have the same problem and I resolve with this trick, but after a "composer dump" it's erase and I have to restart the trick.
• Go to the file : "vendor/composer/autoload_static.php"
• find the line "__DIR__ . '/..' . '/phpunit/phpunit/src/Framework/Assert/Functions.php'" and comment it.

After you can do your tests.

Without I have this error : 

`PHP Fatal error:  Cannot redeclare PHPUnit\Framework\assertArrayHasKey() (previously declared in phar:///usr/local/bin/phpunit/phpunit/Framework/Assert/Functions.php:80) in /......./vendor/phpunit/phpunit/src/Framework/Assert/Functions.php on line 79
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/phpunit:0
PHP   2. PHPUnit\TextUI\Command::main() /......../local/bin/phpunit:739
PHP   3. PHPUnit\TextUI\Command->run() phar:///......../local/bin/phpunit/phpunit/TextUI/Command.php:65
PHP   4. PHPUnit\TextUI\Command->handleArguments() phar:///......../local/bin/phpunit/phpunit/TextUI/Command.php:72
PHP   5. PHPUnit\TextUI\Command->handleBootstrap() phar:///......../local/bin/phpunit/phpunit/TextUI/Command.php:272
PHP   6. PHPUnit\Util\FileLoader::checkAndLoad() phar:///......../local/bin/phpunit/phpunit/TextUI/Command.php:389
PHP   7. PHPUnit\Util\FileLoader::load() phar:///......../local/bin/phpunit/phpunit/Util/FileLoader.php:37
PHP   8. include_once() phar:///usr/local/bin/phpunit/phpunit/Util/FileLoader.php:46
PHP   9. ComposerAutoloaderInit8b623678a2c808038f414247d123f415::getLoader() /......../vendor/autoload.php:7
PHP  10. composerRequire8b623678a2c808038f414247d123f415() /........./vendor/composer/autoload_real.php:59

Fatal error: Cannot redeclare PHPUnit\Framework\assertArrayHasKey() (previously declared in phar:///....../local/bin/phpunit/phpunit/Framework/Assert/Functions.php:80) in /....../vendor/phpunit/phpunit/src/Framework/Assert/Functions.php on line 79

Call Stack:
    0.0039     530160   1. {main}() /..../local/bin/phpunit:0
    0.0890   10678736   2. PHPUnit\TextUI\Command::main() /..../local/bin/phpunit:739
    0.0890   10678848   3. PHPUnit\TextUI\Command->run() phar:///..../local/bin/phpunit/phpunit/TextUI/Command.php:65
    0.0890   10678848   4. PHPUnit\TextUI\Command->handleArguments() phar:///..../local/bin/phpunit/phpunit/TextUI/Command.php:72
    0.0937   10686720   5. PHPUnit\TextUI\Command->handleBootstrap() phar:///..../local/bin/phpunit/phpunit/TextUI/Command.php:272
    0.0937   10686720   6. PHPUnit\Util\FileLoader::checkAndLoad() phar:///..../local/bin/phpunit/phpunit/TextUI/Command.php:389
    0.0938   10686992   7. PHPUnit\Util\FileLoader::load() phar:///..../local/bin/phpunit/phpunit/Util/FileLoader.php:37
    0.0942   10688816   8. include_once('/Applications/MAMP/htdocs/php/DesignPatternsPHP-main/vendor/autoload.php') phar:///..../local/bin/phpunit/phpunit/Util/FileLoader.php:46
    0.0946   10702192   9. ComposerAutoloaderInit8b623678a2c808038f414247d123f415::getLoader() /Applications/MAMP/htdocs/php/DesignPatternsPHP-main/vendor/autoload.php:7
    0.0983   11125200  10. composerRequire8b623678a2c808038f414247d123f415() /Applications/MAMP/htdocs/php/DesignPatternsPHP-main/vendor/composer/autoload_real.php:59`
