### ISSUE TITLE
strict_types declaration must be the very first statement in the script

### ISSUE THREAD

**Issue by oojacoboo** [sebastianbergmann/phpunit#4096]
[13-Feb-2020 17:56:55 UTC] PHP Fatal error:  strict_types declaration must be the very first statement in the script in /srv/www/vendor/phpunit/phpunit/phpunit on line 2

The code style that's being used here, while not a bad style, isn't what the interpreter expects (it seems).  Can this just be updated to conform instead of trying to go against the grain?

**Comment by sebastianbergmann** [comment]
Which version of PHPUnit and PHP are you using?

**Comment by oojacoboo** [comment]
So, it seems the issue is that I'm trying to `include` the CLI script.  Since it's not executed via a shell, the interpreter is complaining.  That's unfortunate though since I have a direct need to wrap PHPUnit, in order to execute code before and after the process.

**Comment by sebastianbergmann** [comment]
The script is not meant to be included.

**Comment by sebastianbergmann** [comment]
If you need to run code before the first test and/or after the last test then you should write an extension that hooks into PHPUnit's test runner.

**Comment by oojacoboo** [comment]
I'll look into that.  Thanks.
