### ISSUE TITLE
Test annotations unavailable on a test skipped by the data provider

### ISSUE THREAD

**Issue by morozov** [sebastianbergmann/phpunit#4099]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.0.1
| PHP version         | 7.4.2
| Installation Method | Composer

#### Summary

If a test is skipped by the data provider, its annotations are unavailable by the moment when `TestListener::endTest()` is invoked.

#### How to reproduce

Consider the following test:
```php
<?php

namespace Example\Tests;

use PHPUnit\Framework\TestCase;

/**
 * @coversNothing
 */
final class SomethingTest extends TestCase
{
    /**
     * @dataProvider somethingProvider
     */
    public function testSomething(bool $value) : void
    {
        $this->assertTrue($value);
    }

    public static function somethingProvider() : iterable
    {
        self::markTestSkipped();

        yield [true];
    }
}
```
And the following test listener:
```php
<?php

namespace Example\Tests;

use PHPUnit\Framework\AssertionFailedError;
use PHPUnit\Framework\Test;
use PHPUnit\Framework\TestCase;
use PHPUnit\Framework\TestListener;
use PHPUnit\Framework\TestListenerDefaultImplementation;

final class AnnotationListener implements TestListener
{
    use TestListenerDefaultImplementation;

    public function endTest(Test $test, float $time) : void
    {
        if (!$test instanceof TestCase) {
            return;
        }

        $annotations = $test->getAnnotations();

        if (empty($annotations['class']['covers']) &&
            empty($annotations['class']['coversNothing']) &&
            empty($annotations['method']['covers']) &&
            empty($annotations['method']['coversNothing'])
        ) {
            $test->getTestResultObject()->addFailure(
                $test,
                new AssertionFailedError('Missing @covers annotation'),
                $time
            );
        }
    }
}
```

The listener is meant to enforce `@covers*` annotation on each test for proper test coverage. It's taken from a real project, so I don't know why it checks the annotations at the end of the test.

The listener is registered in the PHPUnit configuration:
```xml
<listeners>
    <listener class="Example\Tests\AnnotationListener"/>
</listeners>
```

#### Current behavior

```
PHPUnit 9.0.1 by Sebastian Bergmann and contributors.

S                                                                               1 / 1 (100%)F

Time: 36 ms, Memory: 6.00 MB

There was 1 failure:

1) Example\Tests\SomethingTest::testSomething
Missing @covers annotation

/home/morozov/listener/tests/AnnotationListener.php:30

FAILURES!
Tests: 1, Assertions: 0, Failures: 1, Skipped: 1.
```

#### Expected behavior

```
PHPUnit 9.0.1 by Sebastian Bergmann and contributors.

S                                                                               1 / 1 (100%)

Time: 40 ms, Memory: 6.00 MB

OK, but incomplete, skipped, or risky tests!
Tests: 1, Assertions: 0, Skipped: 1.
```

**Comment by sebastianbergmann** [comment]
If there is a bug here (not time right now to investigate and reproduce, hopefully tomorrow) then it should be fixed. But I have one question and one remark:

Question: Why do you need a test listener to enforce the `@covers` annotation? PHPUnit does that for you, of out the box, with the `forceCoversAnnotation` configuration setting. Having `forceCoversAnnotation="true"` in your `phpunit.xml` has been a best practice for years.

Remark: When `TestListener` is removed there will likely no longer be access to this type of information. Unless there a valid use cases that warrant exposing this information, of course.

**Comment by morozov** [comment]
> Why do you need a test listener to enforce the `@covers` annotation?

Most likely, I don’t. It's an existing project where I tried to add a new test and stumbled upon this issue. I should be able to rework the test suite to use `forceCoversAnnotation` instead. Thank you for the suggestion.

**Comment by sebastianbergmann** [comment]
You're welcome. Nevertheless, I will investigate this issue.

**Comment by morozov** [comment]
Speaking of the use case for the listeners. There's another listener in this project that forbids risky and incomplete tests. I see that there is a way to forbid risky tests by configuration (i.e. `failOnRisky`) but there's no way to forbid incomplete tests. The only relevant option is `stopOnIncomplete` that doesn't seem to fail the suite. Would it be reasonable to introduce `failOnIncomplete`?

**Comment by sebastianbergmann** [comment]
`failOnIncomplete` sounds reasonable to me.

**Comment by sebastianbergmann** [comment]
Same for `failOnSkipped`.

**Comment by morozov** [comment]
Judging by the code of `CodeCoverage::applyCoversAnnotationFilter()`, the `forceCoversAnnotation` parameter is only effective if `strictCoverage` is enabled which in turn reports unintentionally covered code. However the [documentation](https://phpunit.readthedocs.io/en/8.5/configuration.html#the-forcecoversannotation-attribute) doesn't mention that.

Is it possible to force the specification of `@covers*` annotations as the listener above does but not enforce strict coverage?

**Comment by kubawerlos** [comment]
Test listeners were removed in PHPUnit 10, so this problem too.
