### ISSUE TITLE
Deprecate multiple test case classes in a single file

### ISSUE THREAD

**Issue by flow-control** [sebastianbergmann/phpunit#4105]
Hey there,

it is stated in the [ChangeLog-9.0.md](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-9.0.md) file that

> Multiple test case classes (classes that extend TestCase) that are declared in a single sourcecode file are no longer supported

This is only true for files included directly as in:
```bash
$ phpunit path/to/FooTest.php
```
but it is still possible to have multiple and randomly named test classes in that `FooTest.php` when invoked via
```bash
$ phpunit path/to/
```
This is because invoking with a directory (or suite from `config.xml`) the `StandardSuiteLoader` is not used.

Proposal: I would create a PR that deprecates this behavior and prints out warnings if the file has more than one test case class in it or the test case class is not named like the filename as it is already behaving when invoking with a filename.

Very curious on your opinion.

/Flo

**Comment by sebastianbergmann** [comment]
Go ahead. Thanks!
