### ISSUE TITLE
Allow slicing tests into chunks to run them in parallel

### ISSUE THREAD

**Issue by spawnia** [sebastianbergmann/phpunit#4121]
## Motivation

As testsuites grow, they get slow. A great way to improve the speed of running them is to split the tests into smaller chunks and run them in parallel.

## Proposal

Add a single new option `--slice` to the test runner CLI. It allows defining how many chunks the test suite should be sliced into and which of those chunks to run. For example, `1/2` will slice the testsuite into 2 chunks and run the first.

Test parallelization is a tricky subject, depending on the nature of the tests and where they are executed, different strategies may be optimal. This feature provides a simple building block upon which further abstractions can be built.

## Implementation

This feature is inspired by https://github.com/wizaplace/phpunit-slicer. Because of API changes starting from PHPUnit v8, it is no longer functional. There is not much code involved in making this work, and i think it would be a valuable addition.

I would be willing to provide a PR and implement this feature. The name of the option and its exact semantics are up for debate, of course.

**Comment by localheinz** [comment]
Probably related to #3605.

**Comment by sebastianbergmann** [comment]
I do not believe that this functionality belongs into PHPUnit and would rather see #3387 implemented.

**Comment by mfn** [comment]
I can see the value of https://github.com/sebastianbergmann/phpunit/issues/3387 , however I'm with @spawnia (and https://github.com/sebastianbergmann/phpunit/pull/3605 already looks like there's a start) => in most cases in practice you "just want to slice", you don't want to fiddle around with generating the list, then chunking, then feeding back. Needs yet-another step in your pipeline. And, not sure how easy it is to e.g. correctly chunk XML to be formally correct, this would probably need more then bash magic to do correctly.

I'm also very interested in this. Having a private test suite of 7k tests, currently I use test `testsuites` feature but it's cumbersome and directory-focus which doesn't reflect the reality to "just chunk".

Thanks for considering.

**Comment by spawnia** [comment]
@sebastianbergmann PHPUnit offers a lot of great options for organizing tests and running them selectively. Test suites and grouping are a nice way of grouping tests logically. What's currently lacking is a built-in way of splitting tests by size. Many users have come forward with such use cases, as evidenced by the issues and PR's created.

I think that pushing this to external tools makes it unnecessarily hard for users to discover and set up.  Simplicity in tools matters a great deal and ultimately is what makes them useful.

Of course, adding features raises complexity and maintenance  concerns. However, i think this use case is common enough and the implementation simple enough (judging from #3605, about 200 LOC).

The proposal in #3387 looks like a great feature, too - it will offer a great deal of flexibility for plugins or additional tooling around PHPUnit. I don't see a reason why we can not have both.
