### ISSUE TITLE
Cannot expect exception of type "ClassMirrorException"

### ISSUE THREAD

**Issue by Pherserk** [sebastianbergmann/phpunit#4123]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.0
| PHP version         | 7.4.1
| Installation Method | Composer

#### Summary

Cannot expect exception of type "ClassMirrorException" when mocking a final class with Prophecy

#### Current behavior
Given that a ClassMirrorException is thrown during test execution.
If the exception is expected test fails because the exception is never thrown.

#### How to reproduce

Prophetize a final class with prophecy and expect the exception:

class FinalClassMockingExampleTest extends TestCase
{
    public function testNotAllowedFinalClassCannotBeMocked()
    {
        static::expectException(ClassMirrorException::class);

        static::prophesize(NotAllowedSimpleFinalClass::class);
    }
}

#### Expected behavior

The test does not fails.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue. A test case that involves Prophecy is not minimal, sorry.

**Comment by Pherserk** [comment]
Thank you @sebastianbergmann for the very quick answer.
I have prepared a full self contained and isolated environemnt to reproduce the problem here:
https://github.com/Pherserk/final-class-mocking-examples

If something more is needed let me know.

**Comment by Pherserk** [comment]
`<?php

namespace pherserk\FinalClassMockingExamples\test;

use pherserk\FinalClassMockingExamples\AllowedSimpleFinalClass;
use pherserk\FinalClassMockingExamples\NotAllowedSimpleFinalClass;
use PHPUnit\Framework\TestCase;
use Prophecy\Exception\Doubler\ClassMirrorException;

/**
 * Class FinalClassMockingExampleTest
 * @package pherserk\FinalClassMockingExamples\test
 */
class FinalClassMockingExampleTest extends TestCase
{
    public function testAllowedFinalClassCanBeMocked()
    {
        static::prophesize(AllowedSimpleFinalClass::class);

        static::expectNotToPerformAssertions();
    }

    public function testNotAllowedFinalClassCannotBeMocked()
    {
        static::expectException(ClassMirrorException::class);

        static::prophesize(NotAllowedSimpleFinalClass::class);
    }
}`

Here is the full test code.

**Comment by sebastianbergmann** [comment]
I have to repeat myself: a test case that involves Prophecy is not minimal, sorry.

**Comment by Pherserk** [comment]
Got it.
Sorry I'm not so pratical with this workflow, I have just opened a PR with a regression test.
Hoping it could help.

https://github.com/sebastianbergmann/phpunit/pull/4124

And thanks again for the time.

**Comment by sebastianbergmann** [comment]
#4124 still uses Prophecy. Please reproduce the issue you want to report without Prophecy.

**Comment by Pherserk** [comment]
Of course @sebastianbergmann .
In the next weeks I will find time to run the debugger in my local environment to follow the exception raise path.
Really sorry I cannot contribute immediatly, I need to study the internals first.
Thanks again.
