### ISSUE TITLE
Error: Incorrect whitelist config, no code coverage will be generated.

### ISSUE THREAD

**Issue by MehdiZox** [sebastianbergmann/phpunit#4125]
I am a beginner on phpunit, and I encounter this problem, after several searches, no solution seems to work yet I have my whitelist of the test folder in my config file at the root.

```shell
$ php -v
PHP 7.3.5 (cli) (built: May  1 2019 13:17:17) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.5, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.9.2, Copyright (c) 2002-2020, by Derick Rethans
```
```shell
$ vendor/bin/phpunit -v
PHPUnit 9.0.1 by Sebastian Bergmann and contributors.
```

![Capture](https://user-images.githubusercontent.com/36897560/75253936-c99c2b00-57df-11ea-9fbb-134ab59a3a3a.JPG)

```shell
PHPUnit 9.0.1 by Sebastian Bergmann and contributors.

Error:         Incorrect whitelist config, no code coverage will be generated.

.........                                                           9 / 9 (100%)

Time: 109 ms, Memory: 6.00 MB

OK (9 tests, 9 assertions)
```

Anyone have a solution?

**Comment by sebastianbergmann** [comment]
Make sure that the directory you want to whitelist exists. And do not whitelist the directory that contains your tests. You want to whitelist the directory that contains the code you are testing.

**Comment by MehdiZox** [comment]
Thank u !
