### ISSUE TITLE
Register extensions via CLI

### ISSUE THREAD

**Issue by Jean85** [sebastianbergmann/phpunit#4131]
Hi there. I'm the maintainer of https://github.com/facile-it/paraunit/, which is a tool that runs PHPunit tests in parallel.

In the past, I've used a printer as a way to obtain results from PHPUnit subrocesses; it doesn't seem a perfect way so, while working on PHPUnit 9 support for Paraunit, I've tried to migrate towards using `TestHook`s. 

They seem great, but I'm lacking a single thing: I cannot inject them without touching the XML config file. This isn't ideal for me, because to do that I would need to change the XML config on the fly; so I have only 2 options:
 * mangle the original config file, with the risk of leaving a dirty situation on the user's config file;
 * create a copy of the config, with the right modifications.

Here comes another limitation: all paths in the config are relative. So I cannot rewrite the config somewhere else, like in `/dev/shm` as I would've likely done, without having to do further modifications to compensate for this issue.

Is there any other way to do this? Can I inject those extensions with a CLI parameter? Or this is a missing feature?

**Comment by sebastianbergmann** [comment]
Extensions currently cannot be registered using a CLI option. I would consider a pull request that implements this.

**Comment by Jean85** [comment]
Thanks, I'll try to look into it! Is it possible that this feature would be backported to 8.x, so that we would have some overlap between the two approaches? (printer/hooks).

**Comment by sebastianbergmann** [comment]
No new features for PHPUnit 8, sorry.

**Comment by Jean85** [comment]
633898a47212e5339261022749afa8748f494aea (coming from 9.0.1) broke this functionality. My bad for not including enough tests. PR with the fix incoming.

**Comment by Jean85** [comment]
Fix pushed in  #4138.
