### ISSUE TITLE
Comparing objects strictly, but not too strictly

### ISSUE THREAD

**Issue by JKingweb** [sebastianbergmann/phpunit#4132]
Currently (as of PHPUnit 9.0) you can either compare two instances of the same class with `assertEquals` and not get the benefits of strict scalar comparisons for their properties, or you can compare them with `assertSame` and... not get a useful comparison.

Basically, is there a way to do...

```php
$this->assertSame(get_class($obj1), get_class($obj2));
$this->assertSame((array) $obj1, (array) $obj2);
```

... but recursively, so that properties which are themselves objects are not rejected for being different instances of the same class? Is this already possible and I've missed how? As things stand I had tests erroneously passing because strings are considered equals to instances of classes with `__toString()` methods which return those strings---a patently nonsensical result.

**Comment by sebastianbergmann** [comment]
Sounds like implementing a custom `Comparator` for use with `assertEquals()` is your best course of action.

**Comment by JKingweb** [comment]
After spending a little while digging through PHPUnit's code, that sounds pretty onerous for functionality that PHPUnit arguably should have available to the programmer as a matter of course. 

First of all, I think your suggestion is too simplistic to actually meet the use case. As far as I can tell I would have to not only write a custom strict comparator for objects, but one for arrays as well (for arrays which contain objects, or arrays that contain arrays that contain objects, etc.). 

Further, if I don't want to lose the ability to loosely compare arrays (or objects), wouldn't I _also_ have to write a custom asserter (or override `assertSame`) rather than use the comparator factory's custom registry in conjunction with `assertEquals`? I can't simply swap out custom comparators as needed, because there's no way to register a comparator lower in the stack than whatever is already registered. Assuming I don't want to clobber comparators which deal with more specific combinations of data.

I can't be the first person who has ever wanted to do this, and it sounds like a really complicated wheel for everyone to reinvent as they need it. Isn't this, at its core, functionality which PHPUnit is missing i.e. a bug?
