### ISSUE TITLE
Option --prepend only works, if supplied as first option

### ISSUE THREAD

**Issue by soerenbernstein** [sebastianbergmann/phpunit#4137]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.5.20 - affected version probably 7.4 and newer (since #3290)
| PHP version         | 7.2.24
| Installation Method | Composer 

#### Summary

Providing the prepend option to phpunit only works, if provides as first option.

The getopt call in phpunit.php:51  will return an empty array, if the prepend option is not the first option. 

#### Current behavior

If the prepend option is provided as first option, the supplied source file will be included. If it is not the first option, the additional source file will be ignored.

#### How to reproduce

Use prepend option in any other position then the first one. 
I tried to get the xdebug filter to work with TeamCity. Didn't work, because prepend is not the first provided option.

#### Expected behavior

Options should always be processed regardless of supplied order

**Comment by sebastianbergmann** [comment]
This is working as intended. And quite frankly, I would rather remove `--prepend` than change it at this point. It is an ugly hack that is no longer required thanks to the existence of PCOV. And "soon" Xdebug 3 will also make this superfluous.

**Comment by soerenbernstein** [comment]
OK, I understand. But some documentation regarding this odd behaviour of the prepend option would be nice.
