### ISSUE TITLE
Qsn: Is it possible to check from one test if another test is already ran?

### ISSUE THREAD

**Issue by adhocore** [sebastianbergmann/phpunit#4140]
Example:

```php
class SomethingTest
{
    public function testSomething(){}
}

class SomethingElseTest
{
    public function testSomethingElse()
    {
        // is it possible to know here if we already ran SomethingTest::testSomething
    }
}
```

Thanks in advance

**Comment by mfn** [comment]
I don't know about any official (curious to learn about it), but you an use `static` properties to keep state of this. This works as long as you don't run each test in process isolation and also works cross test-classes.

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry. That being said, no, there is no official way for this. And there should not be.
