### ISSUE TITLE
cannot open file ...

### ISSUE THREAD

**Issue by gaoxiangbo9527** [sebastianbergmann/phpunit#4143]
My Environment:
    PHP            7.3.15
    PHPUnit     9.0.1
    Windows   10

When i run this command:

D:/WampServer/bin/php/php7.3.15/php.exe D:/WampServer/www/PHPUnit/vendor/phpunit/phpunit/phpunit --no-configuration EmailTest D:\WampServer\www\PHPUnit\tests\ch0\EmailTest.php

I got a wrong result:

Cannot open file "EmailTest".

But,when i run another similar command:

D:/WampServer/bin/php/php7.3.15/php.exe D:/WampServer/www/PHPUnit/vendor/phpunit/phpunit/phpunit --no-configuration D:\WampServer\www\PHPUnit\tests\ch0\EmailTest.php

I got a right result:

...                                                                 3 / 3 (100%)
Time: 90 ms, Memory: 4.00 MB
OK (3 tests, 3 assertions)

I think may be there is a bug at 791 line of this file:

phpunit\phpunit\src\TextUI\Command.php

I'm not sure I'm right, Please help me, Thanks!

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.
