### ISSUE TITLE
Pass exception to tearDown()

### ISSUE THREAD

**Issue by fbrnc** [sebastianbergmann/phpunit#415]
A testcase's tearDown() method always gets called before the onNotSuccessfulTest() method in case an exception has been thrown somewhere. 

If you need the current testenvironment in onNotSuccessfulTest() you must not "clean" it in tearDown(), but inside onNotSuccessfulTest(). Currently this is only possible using some workarounds. 

Passing the exception to tearDown() would enable you to decide inside that method what to do.

Example Usecase: I use tearDown() to close the connection to a Selenium2 server (I'm not using PHPUnit_Selenium...). If an execption occured I'd like to take a screenshot in onNotSuccessfulTest(), so session needs to be closed inside onNotSuccessfulTest() and not in tearDown(). But if no exception occured session needs to be closed inside tearDown().

Another nice approach would be to have a template method that will be called at the very end (after tearDown and onNotSuccessfulTest).

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
