### ISSUE TITLE
Method to generate classmap autoloader

### ISSUE THREAD

**Issue by GuillaumeSeren** [sebastianbergmann/phpunit#4159]
Hey,
I am working on package phpunit + test suite on gentoo,
I am generating an autoload.php file, with composer like:

``` sh
$ composer dump-autoload --optimize
```

It works but the output is a bit messy because it mix phpunit classes with external projects,
and it is on several files (classmap and static), and it require a lot of manual changes.

So my question is there a easyer method to generate the classmap ?

Thank you.

**Comment by sebastianbergmann** [comment]
I use [PHPAB](https://github.com/theseer/Autoload/#php-autoload-builder) for generating autoloader scripts.

That being said, [I do not think that it is a good idea to install PHPUnit globally](https://phpunit.readthedocs.io/en/9.0/installation.html#global-installation). This includes installing PHPUnit using the operating system's package manager.

**Comment by GuillaumeSeren** [comment]
Hey @sebastianbergmann 
thank you for the reply, I will try phpab.

> That being said, I do not think that it is a good idea to install PHPUnit globally. This includes installing PHPUnit using the operating system's package manager.

I understand , but aside the debate language package vs distro,
I want to point the benefit of review and issue reporting by that process,

If you want to elaborate a bit more on why it is a not a good idea to install phpunit globally I am curious (not trolling).

**Comment by sebastianbergmann** [comment]
Using such a global installation of PHPUnit is almost always a bad idea as the different projects you work on may require different versions of PHPUnit, for instance. It is therefore a best practice to use a project-local installation of the version of PHPUnit that should be used for the project at hand.

**Comment by GuillaumeSeren** [comment]
Hello @sebastianbergmann
Thank you for the reply.

Here this use case of packaging all the php base tools (composer, phpunit, etc),
so in a way, it is a dependency of composer or any test of php package.

User are free to use those or use any other version / provider if needed.

Gentoo support several concurrent version of given package, but most big package
does not require a specific version, but just a minimal version.

So here I need phpunit to be able to run the composer test suite,
but ideally all php package, that provide test suite can run it to be sure,
it works same in the package, ci / upstream.

I understand this use case, is not common,
and I thank you for taking the time to reply and talk about it.
