### ISSUE TITLE
v8.5.3 calls undefined method "wasSuccessfulAndNoTestIsRiskyOrSkippedOrIncomplete"

### ISSUE THREAD

**Issue by annuh** [sebastianbergmann/phpunit#4160]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.5.3
| PHP version         | 7.3
| Installation Method | Composer

#### Summary

The latest PHPUnit version (v8.5.3) triggers the following error:
```
Passing an array of interface names to getMockBuilder() for creating a test double that implements multiple interfaces is deprecated and will no longer be supported in PHPUnit 9.
112 | Symfony\Component\ErrorHandler\Error\UndefinedMethodError {#62079
113 | #message: "Attempted to call an undefined method named "wasSuccessfulAndNoTestIsRiskyOrSkippedOrIncomplete" of class "PHPUnit\Framework\TestResult"."
114 | #code: 0
115 | #file: "./vendor/bin/.phpunit/phpunit-8-0/src/TextUI/ResultPrinter.php"
116 | #line: 407
117 | trace: {
118 | ./vendor/bin/.phpunit/phpunit-8-0/src/TextUI/ResultPrinter.php:407 { …}
119 | ./vendor/bin/.phpunit/phpunit-8-0/src/TextUI/ResultPrinter.php:174 { …}
120 | ./vendor/phpunit/phpunit/src/TextUI/TestRunner.php:632 { …}
121 | ./vendor/bin/.phpunit/phpunit-8-0/src/TextUI/Command.php:200 { …}
122 | ./vendor/bin/.phpunit/phpunit-8-0/src/TextUI/Command.php:159 { …}
123 | ./vendor/bin/.phpunit/phpunit-8-0/phpunit:17 { …}
124 | ./vendor/symfony/phpunit-bridge/bin/simple-phpunit.php:343 { …}
125 | ./vendor/symfony/phpunit-bridge/bin/simple-phpunit:13 { …}
126 | }
127 | }
128
```

This method was removed here: https://github.com/sebastianbergmann/phpunit/compare/8.5.3..8.5.2#diff-acc5cd7b9ae2919b44be2417b88f5d42L1171-L1174

But it looks like this method is still called from here: 
https://github.com/sebastianbergmann/phpunit/blob/8.5/src/TextUI/ResultPrinter.php#L407

**Comment by sebastianbergmann** [comment]
As you can see [here](https://github.com/sebastianbergmann/phpunit/blob/8.5.3/src/Framework/TestResult.php#L1171), PHPUnit 8.5.3 has the `PHPUnit\Framework\TestResult::wasSuccessfulAndNoTestIsRiskyOrSkippedOrIncomplete()` method. It was not removed. In fact, it was introduced in PHPUnit 8.5.3.

It appears that you have different installations of PHPUnit mixed up.

For instance, you may have used Composer to install PHPUnit and have configured the autoloader generated by Composer as PHPUnit's bootstrap script but then you invoke PHPUnit using an executable other than `vendor/bin/phpunit`.
