### ISSUE TITLE
Call to undefined method assertAttributeEmpty() and assertAttributeNotEmpty() phpunit v9

### ISSUE THREAD

**Issue by viksts** [sebastianbergmann/phpunit#4161]
Hi,

When i am running phpunit i am getting error like call to undefined method assertAttributeEmpty() and assertAttributeNotEmpty(). However i cannot find any alternate functions. Could you please tell me if is there any alternate function through which i can replace them.

**Comment by kubawerlos** [comment]
See https://github.com/sebastianbergmann/phpunit/issues/3339#issuecomment-445168829

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.
