### ISSUE TITLE
"PHPUnit\TextUI\Configuration" vs autoloader

### ISSUE THREAD

**Issue by ghnp5** [sebastianbergmann/phpunit#4163]
Hello,

I'll probably get some hate because I **don't** use Composer,
but this file:

https://github.com/sebastianbergmann/phpunit/blob/5a3b8a9d2a4b71ca251fc8b616cca642e4a46bc4/src/TextUI/Configuration/PHPUnit/ExtensionHandler.php#L10

Is under the folder "Configuration/PHPUnit",
yet the namespace is:

namespace PHPUnit\TextUI\Configuration;

(I see the same applies to other files under that folder)

Therefore, these classes become "non-automatically findable", by having my version of the autoloader find the file directly in "PHPUnit\TextUI\Configuration".

Is there a reason the namespace isn't "PHPUnit\TextUI\Configuration\PHPUnit" ?

This wasn't a problem before 9.1.0.

Thank you.

**Comment by sebastianbergmann** [comment]
If you do not 1) use Composer to install PHPUnit or 2) use PHPUnit from a PHAR then you are on your own.
