### ISSUE TITLE
assertNull run out of memory.

### ISSUE THREAD

**Issue by VincentLanglet** [sebastianbergmann/phpunit#4167]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.2.5
| PHP version         | 7.4
| Installation Method | Composer

#### Summary

I know the Phpunit version is kinda old and this won't be fixed in phpunit 8.2, but I was thinking that maybe this issue is still present in Phpunit 9 and I would be good to report it. I didn't succeed to install a newer version of phpunit. If you think this issue is irrelevent, I'll understand.

I'll re-try to update the phpunit version if my company offer me time for.

I get out of memory when using `assertNull` on an object.

#### Current behavior

![image](https://user-images.githubusercontent.com/9052536/78674945-a7b8bc80-78e4-11ea-8fed-3970b3c13b5a.png)

#### How to reproduce

```
$support = $this->supportRepository->findExistingSupportByIsinAndName($isinCode, $name);
$this->assertNull($support);
```

If I `dump` support and `die` in the test, I get
```
AssuranceVie\Entity\Support {#87
  -id: 3
  -code: "TESTSUPPORT"
  -name: "Test support"
  -euroFund: false
  #contractSupports: Doctrine\ORM\PersistentCollection {#1202
    -snapshot: []
    -owner: AssuranceVie\Entity\Support {#87}
    -association: array:15 [ …15]
    -em: Doctrine\ORM\EntityManager {#157 …11}
    -backRefFieldName: "support"
    -typeClass: Doctrine\ORM\Mapping\ClassMetadata {#85 …}
    -isDirty: false
    #collection: Doctrine\Common\Collections\ArrayCollection {#66
      -elements: []
    }
    #initialized: false
  }
  -insuranceCompanySupports: Doctrine\ORM\PersistentCollection {#1236
    -snapshot: []
    -owner: AssuranceVie\Entity\Support {#87}
    -association: array:15 [ …15]
    -em: Doctrine\ORM\EntityManager {#157 …11}
    -backRefFieldName: "support"
    -typeClass: Doctrine\ORM\Mapping\ClassMetadata {#1126 …}
    -isDirty: false
    #collection: Doctrine\Common\Collections\ArrayCollection {#1122
      -elements: []
    }
    #initialized: false
  }
  -contractTypeSupports: Doctrine\ORM\PersistentCollection {#1185
    -snapshot: []
    -owner: AssuranceVie\Entity\Support {#87}
    -association: array:15 [ …15]
    -em: Doctrine\ORM\EntityManager {#157 …11}
    -backRefFieldName: "support"
    -typeClass: Doctrine\ORM\Mapping\ClassMetadata {#1114 …}
    -isDirty: false
    #collection: Doctrine\Common\Collections\ArrayCollection {#1094
      -elements: []
    }
    #initialized: false
  }
  -assetManagementCompany: Proxies\__CG__\AssuranceVie\Entity\AssetManagementCompany {#1146
    +__isInitialized__: false
    -id: 3
    -name: null
    -supports: null
     …2
  }
}
```

#### Expected behavior

A failure without errors.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please do not use screenshots to show output and provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by VincentLanglet** [comment]
> Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.
> 
> Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

Yeah, I understand that.

Unfortunally, the code is from a big private repository... so I don't really know how to do. 
I discover this old issue: https://github.com/sebastianbergmann/phpunit/issues/419, and I think it's related.

So if it's because my entity is a "big object", I feel like a small repository won't create the bug, and it'll take a lot of time for nothing.

I tried,
```
$this->assertNull(new Support());
```
And it works.

I discover this old issue: https://github.com/sebastianbergmann/phpunit/issues/419, and I think it's related.

My entity have relations, with `Doctrine\ORM\PersistentCollection`, 

I also tried,
```
$this->assertEqual(null, $support);
```
And it works.

But
```
$this->assertNull($support);
```
throw me a memory error.

I don't know how bad my idea is but 
```
public static function assertNull($actual, string $message = ''): void
{
    static::assertEqual(null, $actual, $message);
}
```
would fix the bug 😅

Will see if I find time for a repository to reproduce the bug in the week.

**Comment by sebastianbergmann** [comment]
`assertEqual()` performs a lot more work (due to Chain of Responsibility application for built-in `Comparator`s as well as custom `Comparator`s whereas `assertNull()` is merely a wrapper for `=== null`.

**Comment by VincentLanglet** [comment]
> `assertEqual()` performs a lot more work (due to Chain of Responsibility application for built-in `Comparator`s as well as custom `Comparator`s whereas `assertNull()` is merely a wrapper for `=== null`.

Yes but then is weird to get a memory error for a `=== null` wrapper when the assertEqual succeed to make the checks. Anyway, that's not the point.

**Comment by VincentLanglet** [comment]
I didn't succeed creating a minimal repository to reproduce the bug.
With small entities, there is no issue.

**Comment by UCIS** [comment]
While my test did not run out of memory, I did receive a uselessly long output from an assertNull check. One way to reproduce this situation (and depending onthe memory_limit, OOM) is this simple test:
```
<?php
use PHPUnit\Framework\TestCase;
class test extends TestCase {
  public function testNotNull() {
    $str = str_repeat('a', 1024 * 1024);
    $arr = array_fill(0, 1024, $str);
    $this->assertNotNull($arr);
    $this->assertNull($arr);
  }
}
```

Because of the use of CoW by PHP the initial array allocation does not consume a lot of memory, but the assertNull check tries to print the full array contents and can run out of memory depending on PHP configuration - it seems to need more than 2GB of memory on my system.

The same thing would likely happen with an object containing references to other large objects.

**Comment by VincentLanglet** [comment]
This issue was closed 4 years ago ; you might consider opening a new one instead
