### ISSUE TITLE
deprecated method does not throw exception

### ISSUE THREAD

**Issue by sveneld** [sebastianbergmann/phpunit#4170]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.5.0
| PHP version         | 7.3.10
| Installation Method | Composer 

#### Summary

using of deprecated method doe not throw an exception

#### Current behavior

test OK

#### How to reproduce
Two classes
```
class DeprecatedClass
{
    /**
     * @deprecated do not use it
     */
    public function run()
    {
        echo 1;
    }
}

class UsualClass
{
    /**
     * @var DeprecatedClass
     */
    private $deprecatedClass;

    public function __construct(DeprecatedClass $deprecatedClass)
    {
        $this->deprecatedClass = $deprecatedClass;
    }

    public function run()
    {
        $this->deprecatedClass->run();
    }
}
```
Test for it
```
class UsualClassTest extends \PHPUnit\Framework\TestCase
{

    public function testRun()
    {
        $test = new UsualClass(
            $this->createMock(DeprecatedClass::class)
        );

        $test->run();
        $this->assertTrue(true);
    }
}
```

#### Expected behavior

The DeprecatedClass::run method is deprecated (do not use it).
components/UsualClass.php:17
/tests/UsualClassTest.php:12
 
Time: 342 ms, Memory: 62.50 MB

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.

Process finished with exit code 2

I think the problem is in this commit https://github.com/sebastianbergmann/phpunit/commit/2e3c5ea127d1a632bd5af003992d01e9b597ee35
because deprecation trigger in mock class is written as @trigger_error({deprecation}, E_USER_DEPRECATED);

**Comment by sebastianbergmann** [comment]
I do not understand what you are trying to report, sorry.

**Comment by sveneld** [comment]
i expect that using of deprecated method in mocked class will throw an exception and test will fail

**Comment by sebastianbergmann** [comment]
This is expected behavior. `trigger_error()` is executed but the error it triggers is suppressed by default. A custom error handler can trap this and act on it.
