### ISSUE TITLE
Element 'groups': This element is not expected. Expected is ( exclude )

### ISSUE THREAD

**Issue by viksts** [sebastianbergmann/phpunit#4171]
Hi 
I am using phpunit version 9.1.1 and in my phpunit.xml i have node like
<testsuite>
<directory>./functional</directory>
          <groups>
                <include>
                    <group>abc</group>
                </include>
            </groups>
</testsuite> 

but when i run test suit it gives error
Element 'groups': This element is not expected. Expected is ( exclude )
Is groups inside testsuite not supported?

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.
