### ISSUE TITLE
Array-style access of non-arrays not always throw an exception

### ISSUE THREAD

**Issue by bartoszpotmalnik** [sebastianbergmann/phpunit#4172]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.1.1
| PHP version         | 7.4
| Installation Method | Composer 

#### Summary

In php 7.4 incorrect usage of value as an array will throw exception. [Details](https://www.php.net/manual/de/migration74.incompatible.php#migration74.incompatible.core.non-array-access)

During update one of the packages to php 7.4 all the tested passed but production enviroment thrown exception mentioned above.  

#### How to reproduce
```
    public function method2()
    {
        return current([])['test'] ?? [];
    }

    /** @test */
    public function passing_test()
    {
        $this->assertIsArray($this->method2());
    }
```

#### Expected behavior

Test should fail as `current([])` is false. 

#### Additional observations  

If you change example above, so failing part will be variable, test will throw exception as expected.

```
public function method1()
    {
        $test = current([])['test'];

        return $test ?? [];
    }

    /** @test */
    public function failing_test()
    {
        $this->assertIsArray($this->method1());
    }
```

I've created a [reproduction repo](https://github.com/bartoszpotmalnik/phpunit-reproduction-repo) if it will help. 

Thanks

**Comment by sebastianbergmann** [comment]
`assertIsArray()` is just a wrapper for `is_array()`.

**Comment by bartoszpotmalnik** [comment]
Okey, I understand. 

But I am more interested why phpunit is not throwing an exception in this: 
```
return current([])['test'] ?? [];
```
And it is throwing using this
```
$test = current([])['test'];

 return $test ?? [];
```

In production exception will be thrown in both cases. 

I've used assertIsArray just of passing test example.

**Comment by bartoszpotmalnik** [comment]
If you look at this [test](https://github.com/bartoszpotmalnik/phpunit-reproduction-repo/blob/master/tests/ExampleTest.php) all the test should fail, but for some reason they are passing even if syntax like ` return false['test'] ?? [];` is invalid and should throw an exception. (Acording to [this](https://www.php.net/manual/de/migration74.incompatible.php#migration74.incompatible.core.non-array-access))

If this is no a bug so maybe you have idea why it is happening? 

Thanks
@sebastianbergmann
