### ISSUE TITLE
Determine coverage from multiples reports

### ISSUE THREAD

**Issue by baptistedonaux** [sebastianbergmann/phpunit#4177]
I can found no options to determine a final code coverage from many code coverage reports.

In my case, I execute tests in two CI jobs. Potentially, these jobs can covered the same code so I would like crossed reports to determine the coverage of my application.

The options `--coverage-<format>` seem produced report but I can't found option to read a list of reports and determine a final coverage.

**Comment by sebastianbergmann** [comment]
You are looking for [phpcov](https://github.com/sebastianbergmann/phpcov).
