### ISSUE TITLE
Full data provider parameter information is not displayed

### ISSUE THREAD

**Issue by lyrixx** [sebastianbergmann/phpunit#4179]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.3.5
| PHP version         | 7.3.11
| Installation Method | symfony/phpunit-bridge (so via composer.json)

Hello

#### Summary

I tested many flags `--verbose` and `--debug` and both of them, and I can not see te full data provider parameters 

#### Current behavior

```
$ ./bin/simple-phpunit tests/Functional/Api/Crawler/SectionTest.php  --filter testSection#57 --verbose --debug

PHPUnit 8.3.5 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.3.11-1+0~20191026.48+debian10~1.gbpf71ca0 with PCOV 1.0.6
Configuration: /home/rio/rio/server/backend/phpunit.xml.dist

Testing Tests\Functional\Api\Crawler\SectionTest
Test 'Tests\Functional\Api\Crawler\SectionTest::testSection with data set #57 ('distribution-of-defined-meta-...-depth')' started
Test 'Tests\Functional\Api\Crawler\SectionTest::testSection with data set #57 ('distribution-of-defined-meta-...-depth')' ended


Time: 913 ms, Memory: 62.50 MB

There was 1 failure:

1) Tests\Functional\Api\Crawler\SectionTest::testSection with data set #57 ('distribution-of-defined-meta-...-depth')
Failed asserting that 500 is identical to 200.

/home/rio/rio/server/backend/tests/Functional/Api/Crawler/SectionTest.php:32

```

As you can see, the `distribution-of-defined-meta-...-depth` string is truncated. :/ 

#### How to reproduce

```php
    public function provideTests(): \Generator
    {
        yield [str_repeat("x", 1000)];
    }

    /** @dataProvider provideTests */
    public function test()
    {

    }
```

#### Expected behavior

With the `--verbose` flag, data should not be truncated

**Comment by sebastianbergmann** [comment]
This has nothing to do with `--verbose`.

**Comment by lyrixx** [comment]
@sebastianbergmann Usually, `--verbose` means "display all information". That's why I thought it will display full data provider parameter information.

I'm sorry about that!

**Comment by mvorisek** [comment]
Is there currently any possibility to enable display of the full dataset value?
