### ISSUE TITLE
Cannot determine time at which the request started

### ISSUE THREAD

**Issue by marcelloh** [sebastianbergmann/phpunit#4183]
I know this was on older issue, but I have the same issue with php 7.2.28 and PHPUnit  8.5.3.
I have tried everything (I think).

I'm not a fan of globals, but this is software that was from someone else :-(

phpunit --globals-backup -d xdebug.profiler_enable=on -c phpunit_all.xml
no effect

put the extra attributes in my xml:
backupGlobals="true" backupStaticAttributes="true" 
no effect

I even have this in my setup:
$_SERVER['REQUEST_TIME_FLOAT'] = microtime(TRUE);
no effect

but I was wondering, why $_SERVER if unit-testing  is commandline? Couldn't I skip the timing of tests?
I'm more interested in getting one test to run a.t.m.

**Comment by sebastianbergmann** [comment]
I am sorry but the timing of tests cannot be skipped and `$_SERVER['REQUEST_TIME_FLOAT']` should not be messed with.

**Comment by marcelloh** [comment]
ok, but how should I test then, since both "normal" solutions don't work?

**Comment by tomasfejfar** [comment]
[omvy9.zip](https://github.com/sebastianbergmann/phpunit/files/8843861/omvy9.zip)
Here is a minimum replicable case where the following is the culprit:

```
    /** @backupGlobals  */
    public function testThis(): void
    {
        $_SERVER = [];
    }
```
To me this seems like it should be supported, but is not. 

I *think* you could work around this by backing up the globals yourself.
