### ISSUE TITLE
Support adding directories to blacklist (of files that PHPUnit filters from stacktraces)

### ISSUE THREAD

**Issue by Jean85** [sebastianbergmann/phpunit#4186]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.1.2
| PHP version         | 7.3+
| Installation Method | Composer

#### Summary
As reported in https://github.com/symfony/symfony/issues/36499, 2b4d7b8bb3fd052095e64999990cc36b63aa0771 broke the Symfony PHPUnit bridge. The bridge was relying on the `Blacklist` class, which is `internal`, so it would be expected. The issue here is that there isn't any other way to do the same operation, adding new classes to the blacklist to exclude them from error stack traces.

Is it possible to have any kind of extension point to obtain the same result without relying on an internal class?

#### Current behavior
Crash like this: https://github.com/symfony/symfony/issues/36499#issuecomment-616365995
```
Error: Access to undeclared static property: PHPUnit\Util\Blacklist::$blacklistedClassNames
```

#### How to reproduce
 * Use PHPUnit 9.1.2 with the PHPUnit bridge
 * run any test
 * get a 

#### Expected behavior
No issues

**Comment by sebastianbergmann** [comment]
This is not a bug.

**Comment by sebastianbergmann** [comment]
Would this help?

```patch
diff --git a/src/Util/Blacklist.php b/src/Util/Blacklist.php
index 8767a5d18..fcb71243f 100644
--- a/src/Util/Blacklist.php
+++ b/src/Util/Blacklist.php
@@ -145,6 +145,20 @@ final class Blacklist
      */
     private static $directories;
 
+    public static function addDirectory(string $directory): void
+    {
+        if (!\is_dir($directory)) {
+            throw new Exception(
+                \sprintf(
+                    '"%s" is not a directory',
+                    $directory
+                )
+            );
+        }
+
+        self::$directories[] = \realpath($directory);
+    }
+
```

**Comment by nicolas-grekas** [comment]
@sebastianbergmann yes, that would help, since we basically need a way to add to this list. Thanks for considering!
