### ISSUE TITLE
 Could not scan for classes

### ISSUE THREAD

**Issue by kaufmannmax** [sebastianbergmann/phpunit#4194]
I'm Getting 
RuntimeException]
   Could not scan for classes inside "" which does not appear to be a file nor a folder
when updating PHPUnit via Composer to Version 9.1.3, downgrading to v9.1.2 works fine

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by sebastianbergmann** [comment]
`Could not scan for classes ...` is not a message that comes from PHPUnit. My guess is that it comes from Composer.

**Comment by kaufmannmax** [comment]
Sorry, was a typeerror in the title before :-(
Yes it's a message from composer, but it only appears when I try to install PHPUnit 9.1.3
Clearing cache, removing directories, composer.lock etc. didn't work, only downgrading to 9.1.2 made it work again.

Here's the configuration I'm using in composer.json content:
{
  "require": {
    "symfony/http-foundation": "*",
    "sentry/sdk": "*",
    "twig/twig": "*",
    "ext-simplexml": "*",
    "ext-json": "*"
  },
  "require-dev": {
    "phpunit/phpunit": "*",
    "phpstan/phpstan": "*",
    "squizlabs/php_codesniffer": "*",
    "friendsofphp/php-cs-fixer": "*"
  },
  "config": {
    "platform": {
      "php": "7.3.12"
    }
  },
  "autoload": {
    "psr-4": {
      XXX
    }
  }
}

**Comment by sebastianbergmann** [comment]
I cannot help you with this, sorry.
