### ISSUE TITLE
Improper @covers annotation halts the entire test suite

### ISSUE THREAD

**Issue by morozov** [sebastianbergmann/phpunit#4196]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.1.3
| PHP version         | 7.4.5
| Installation Method | Composer

#### Summary

If a method is annotated with a `@covers` annotation that cannot be resolved to a code unit, then the entire test suite halts with an error message that doesn't tell what the problem is.

#### Current behavior

```
phpunit --coverage-php coverage.php
PHPUnit 9.1.3 by Sebastian Bergmann and contributors.

"@covers ::whatever" is invalid
```

#### How to reproduce

```php
<?php declare(strict_types=1);

class SomeTest extends TestCase
{
    /**
     * @test
     * @covers ::whatever
     */
    public function invoke() : void
    {
        self::assertTrue(true);
    }
}
```

#### Expected behavior

PHPUnit emits a warning containing the class/method information and ignores the code coverage produced by the test with the invalid annotation but doesn't halt. Otherwise, it's impossible to identify all invalid annotations in an existing large test suite.

**Comment by sebastianbergmann** [comment]
This is not really a bug, IMO, but something that can be improved.
