### ISSUE TITLE
Make the documentation explicit on whether the assert messages should be 'positive' or 'negative'

### ISSUE THREAD

**Issue by Chi-teck** [sebastianbergmann/phpunit#4198]
That comes from https://www.drupal.org/project/drupal/issues/3131946.

> PHPUnit itself is un-opinionated on whether these messages should be written in a "positive" (aka "confirmative") way (what we're expecting to be true, which was violated if the assertion fails) or a "negative" one (what went wrong that caused the assertion to fail). All PHPUnit itself gives us is this:

https://github.com/sebastianbergmann/phpunit/blob/9.1.3/src/Framework/Constraint/Constraint.php#L94

     * @param string            $description       Additional information about the test

I think that parameter needs some explanation in PHPDoc or somewhere else.

**Comment by sebastianbergmann** [comment]
I do not think so. In fact, I have never used the optional `$message` argument and would rather remove it completely than invest additional time in it (if only for documentation).

**Comment by dww** [comment]
No problem that you don't want to document it.  I don't believe PHPUnit itself needs to care about this point.  But please don't remove custom assertion messages entirely.  If you have to do a bunch of assertions for a given test, and doing them inside a loop makes more sense than using a dataProvider, a custom assertion message is sometimes the only way for a failed assertion to tell the developer which iteration they were on when the assertion failed.

Thanks,
-Derek
