### ISSUE TITLE
Add support for conditional inclusion of test files based on PHP version

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#42]
The example below will only add the `/path/to/*Test.php` files and `/path/to/MyTest.php` file if the PHP version is at least 5.3.0.

```
<testsuite name="My Test Suite">
  <directory phpVersion="5.3.0" phpVersionOperator=">=">/path/to/*Test.php files</directory>
  <file phpVersion="5.3.0" phpVersionOperator=">=">/path/to/MyTest.php</file>
</testsuite>
```

The `phpVersionOperator` attribute is optional and defaults to `>=`.

The comparison will be implemented as

```
version_compare(PHP_VERSION, <phpVersion>, <phpVersionOperator>)
```

**Comment by nelson6e65** [comment]
Hmm... If I use `<` I get an syntax error: 
```xml
<file phpVersion="7.2"  phpVersionOperator="<">tests/TestCase/ObjectTest.php</file>
```

> Unescaped '<' not allowed in attributes values

Just in case, I had to use `&lt;` in order to work (5.7).

**Comment by nelson6e65** [comment]
Can I use this for `<exclude>` too, @sebastianbergmann?
