### ISSUE TITLE
Show array contents with `assertEmpty()`

### ISSUE THREAD

**Issue by Danon** [sebastianbergmann/phpunit#4204]
Currently, `assertEmpty()` works like this - doesn't provide a way to show actual elements.
![image](https://user-images.githubusercontent.com/13367735/80921474-e96b4480-8d76-11ea-8178-c726a9fe3c29.png)

Because of that, I need to use `assertEquals([], )` in order for my tests to provide a convenient way for me to pre-validate a test, without using debugger.

![image](https://user-images.githubusercontent.com/13367735/80921508-1fa8c400-8d77-11ea-8076-c82c152e88f4.png)

I would love if `assertEmpty()` could provide a similar feature.

**Comment by sebastianbergmann** [comment]
This issue tracker is for the Open Source project that provides the PHPUnit testing framework as well as the CLI tool for executing tests. Also please do not post screenshots but instead provide the actual output of PHPUnit as text.

**Comment by Danon** [comment]
Ok, sorry about that. With `assertEmpty()` and `--teamcity` flag used phpunit outputs
```
##teamcity[testFailed name='shouldNotTestTheSameFeatureTwice' message='Failed asserting that an array is empty.' details=' C:\Users\Danon\PhpstormProjects\T-Regx\test\Utils\ValidateFeatureTestNamingConventionT
est.php:43|n ' duration='53' flowId='9056']
```

I'm asking if it could return
```
##teamcity[testFailed name='shouldNotTestTheSameFeatureTwice' message='Failed asserting that two arrays are equal.' details=' C:\Users\Danon\PhpstormProjects\T-Regx\test\Utils\ValidateFeatureTestNamingConventi
onTest.php:43|n ' duration='52' type='comparisonFailure' actual='Array (|n    |'xd|' => |'a|'|n)' expected='Array (|n)' flowId='11112']
```

**Comment by sebastianbergmann** [comment]
Superseded by #4209.
