### ISSUE TITLE
@coversDefaultClass Inheritance

### ISSUE THREAD

**Issue by crstauf** [sebastianbergmann/phpunit#4218]
# Context
## Functional Classes

|Name|Test class name|
|:---|:---|
|`Properties`|`Properties_Test`|
|`Attributes`|`Attributes_Test`|
|`Settings`|`Settings_Test`|

```
Properties
├── Attributes
└── Settings
```

## Tests Classes

|Name|Abstract|Data Providers|Tests|`@covers ::method()`|`@coversDefaultClass`|
|:---|:---:|:---:|:---:|:---:|:---|
|`Properties_Base`|✓||Generic|✓||
|`Properties_Tests`|✓|✓||||
|`Properties_Test`||✓|Specific|✓|`Properties`|
|`Attributes_Test`||✓|Specific|✓|`Attributes`|
|`Settings_Test`||✓|Specific|✓|`Settings`|

```
Properties_Base
└── Properties_Tests
    ├── Properties_Test
    ├── Attributes_Test
    └── Settings_Test
```

## Configuration

Initially generated by [WordPress `scaffold` CLI command](https://developer.wordpress.org/cli/commands/scaffold/plugin-tests/).

<details>
<summary>phpunit.xml.dist</summary>

```
<?xml version="1.0"?>
<phpunit
	bootstrap="tests/bootstrap.php"
	backupGlobals="false"
	colors="true"
	convertErrorsToExceptions="true"
	convertNoticesToExceptions="true"
	convertWarningsToExceptions="true"
	forceCoversAnnotation="true"
	beStrictAboutTestsThatDoNotTestAnything="true"
	beStrictAboutOutputDuringTests="true"
>

	<testsuites>

		<testsuite name="properties">
			<file>./tests/properties/properties.php</file>
			<file>./tests/properties/attributes.php</file>
			<file>./tests/properties/settings.php</file>
		</testsuite>

	</testsuites>

	<filter>
		<whitelist processUncoveredFilesFromWhitelist="true">
			<file>Properties.php</file>
			<file>Attributes.php</file>
			<file>Settings.php</file>
		</whitelist>
	</filter>

	<logging>
		<log type="coverage-html" target="./report" />
	</logging>

</phpunit>
```
</details>

## Written Explanation
On the tests in the abstract class `Properties_Base`, I'm using the `@covers ::method()` annotation and intending to partner with `@coversDefaultClass` on the actual (child) test classes. My expectation was that by setting `@coversDefaultClass` on `Properties_Test`, `Attributes_Test`, and `Settings_Test`, they would all inherit the `@covers` annotations on the methods.

# Feature Request

## The "Problem"
Specifying `@coversDefaultGroup` on inheriting test classes does not seem to work. I do see code in `Properties` being marked as covered, but I've no understanding as to why: I changed the loading order, removed the `@coversDefaultGroup Properties` annotation, and no change.

## The Solution
It would be really helpful if `@coversDefaultGroup` were applied to any tests that were inherited. I can of course accomplish this by defining the test methods in the children, adding the annotation, and calling the parent method from within the child, but that's definitely not ideal, as the whole point of this structure was to have general tests separate from specific tests.

# Disclaimer
It's entirely possible that what I'm describing is already possible and I'm just not aware of it and did not find it in my Googling; I'm still learning PHPUnit (really, really enjoying it), so I apologize and mean no annoyance if this is already possible, or if I'm doing something foolish. If so, please let me know.

Happy to help however I can and answer any questions, as well as receive recommendations or constructive feedback. :)

**Comment by sebastianbergmann** [comment]
`@coversDefaultClass` is a kludge that is no longer required when [attributes](https://github.com/sebastianbergmann/phpunit/issues/4502) are used. Annotations are closed for further development.
