### ISSUE TITLE
How to disable or ignore Phpunit Asset deprecation warning

### ISSUE THREAD

**Issue by chandon** [sebastianbergmann/phpunit#4228]
With phpunit 8.5, i got warnings like this:

> Using assertContains() with string haystacks is deprecated and will not be supported in PHPUnit 9. Refactor your test to use assertStringContainsString() or assertStringContainsStringIgnoringCase() instead.

Test end in a "warning " status.

How to disable Phpunit deprecation warnings (i've checked the Assert.php file and the createWarning static function, i don't see any way to disable it with a parameter)

**Comment by sebastianbergmann** [comment]
You "disable" this warning by migrating your test code. In other words: there is (intentionally) no way to disable this warning.

**Comment by chandon** [comment]
or by downgrading phpunit... or by commenting the line in the Assert.php file
thanks

**Comment by natural411** [comment]
I've added a deprecation error to my source code for users.  but our unit tests now fail on this.  so, there needs to be a way to ignore it so that we can have the warning there for our users but still run our own unit tests.

**Comment by asiby** [comment]
In my case, I have silenced the error using what I call the mute operator (the @ character).

In your test case, When you need to call the method which is deprecated, say `YourClass::yourMethod`, then you can use the syntax `@YourClass::yourMethod()`.

I know that suppressing errors this way is very dated and not recommended in a production code. But if you are only using it in your test code and have other test cases for testing errors conditions, it should be fine.
