### ISSUE TITLE
coverage-html Undefined variable: group

### ISSUE THREAD

**Issue by mbretter** [sebastianbergmann/phpunit#4231]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.1.4
| PHP version         | 7.4.6
| Installation Method | Composer 

#### Summary

when generating the coverage html report, the following error is shown:
Undefined variable: group

#### Current behavior

html report is not generated

#### How to reproduce

```
phpunit --testsuite="unit tests" --configuration phpunit.xml --bootstrap test/unit/bootstrap.php --coverage-html reports/coverage --coverage-clover reports/clover.xml --coverage-crap4j reports/crap4j.xml --log-junit reports/junit.xml
PHPUnit 9.1.4 by Sebastian Bergmann and contributors.
```
When adding the group commandline arg, the error disappears.

#### Expected behavior

the html coverage report should be generated.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by mbretter** [comment]
By trying to provide an isolated test case, I found the issue, it is not phpunit related, it's simply a problem of some of the source files and how they are invoked by phpunit.
