### ISSUE TITLE
Create GitHub release when a new version is out

### ISSUE THREAD

**Issue by williamdes** [sebastianbergmann/phpunit#4239]
Create GitHub release when a new version is out in order to notify people that they can enjoy reading the CHANGELOG like their favorite newspaper :newspaper: 

Or provide a beautiful RSS feed

@sebastianbergmann What are your opinions on this one ?
I can work on this one if some scripts to automate this are needed

**Comment by sebastianbergmann** [comment]
TL;DR: I am not interested in "GitHub releases".

The `ChangeLog-X.Y.md` files are in Git and can be viewed on GitHub. `https://phar.phpunit.de/releases.rss` exists. Releases are announced on the [website](https://phpunit.de/announcements/) and on [Twitter](https://twitter.com/phpunit).

**Comment by williamdes** [comment]
Could you add the changes into the RSS feed ?

![image](https://user-images.githubusercontent.com/7784660/82666086-629ede80-9c35-11ea-8e93-5478a7f7ee75.png)


There is nothing to read ..
Not even a link to some good content

Can I contribute somewhere to improve this ?

**Comment by williamdes** [comment]
@sebastianbergmann Can I contribute somewhere to improve this ?
