### ISSUE TITLE
Not able to run phpunit coverage report when parsoid is used 

### ISSUE THREAD

**Issue by QATesterIOS** [sebastianbergmann/phpunit#4243]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     |  9.1.4 
| PHP version         | 7.4.6
| Installation Method | Composer
[composer-info-output.zip](https://github.com/sebastianbergmann/phpunit/files/4680552/composer-info-output.zip)

#### Summary

I am not able to run phpunit with coverage report when parsoid is enabled and used 

#### Current behavior

 getting the following error when running phpunit with coverage unit

PHP Warning:  Uncaught require_once(/var/www/projects/aqlamy-backend-services/app/Libraries/parsoid/bin/../vendor/autoload.php): failed to open stream: No such file or directory

/var/www/projects/aqlamy-backend-services/app/Libraries/parsoid/bin/domdiff.test.php:5
/var/www/projects/aqlamy-backend-services/app/Libraries/parsoid/bin/domdiff.test.php:5

  thrown in /var/www/projects/aqlamy-backend-services/app/Libraries/parsoid/bin/domdiff.test.php on line 5
PHP Stack trace:
PHP   1. {main}() /var/www/projects/aqlamy-backend-services/vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit\TextUI\Command::main() /var/www/projects/aqlamy-backend-services/vendor/phpunit/phpunit/phpunit:61
PHP   3. PHPUnit\TextUI\Command->run() /var/www/projects/aqlamy-backend-services/vendor/phpunit/phpunit/src/TextUI/Command.php:68
PHP   4. PHPUnit\TextUI\TestRunner->run() /var/www/projects/aqlamy-backend-services/vendor/phpunit/phpunit/src/TextUI/Command.php:108
PHP   5. PHPUnit\Framework\TestSuite->run() /var/www/projects/aqlamy-backend-services/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:653
PHP   6. PHPUnit\Framework\TestSuite->run() /var/www/projects/aqlamy-backend-services/vendor/phpunit/phpunit/src/Framework/TestSuite.php:639
PHP   7. PHPUnit\Framework\TestSuite->run() /var/www/projects/aqlamy-backend-services/vendor/phpunit/phpunit/src/Framework/TestSuite.php:639
PHP   8. Tests\Feature\Api\ArticleImage\ArticleFeaturedImageCreateIntegTest->run() /var/www/projects/aqlamy-backend-services/vendor/phpunit/phpunit/src/Framework/TestSuite.php:639
PHP   9. PHPUnit\Framework\TestResult->run() /var/www/projects/aqlamy-backend-services/vendor/phpunit/phpunit/src/Framework/TestCase.php:772
PHP  10. SebastianBergmann\CodeCoverage\CodeCoverage->start() /var/www/projects/aqlamy-backend-services/vendor/phpunit/phpunit/src/Framework/TestResult.php:642
PHP  11. SebastianBergmann\CodeCoverage\CodeCoverage->initializeData() /var/www/projects/aqlamy-backend-services/vendor/phpunit/php-code-coverage/src/CodeCoverage.php:239
PHP  12. include_once() /var/www/projects/aqlamy-backend-services/vendor/phpunit/php-code-coverage/src/CodeCoverage.php:955
PHP Fatal error:  SebastianBergmann\CodeCoverage\CodeCoverage::main(): Failed opening required '/var/www/projects/aqlamy-backend-services/app/Libraries/parsoid/bin/../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/projects/aqlamy-backend-services/app/Libraries/parsoid/bin/domdiff.test.php on line 5
PHP Stack trace:
PHP   1. {main}() /var/www/projects/aqlamy-backend-services/vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit\TextUI\Command::main() /var/www/projects/aqlamy-backend-services/vendor/phpunit/phpunit/phpunit:61
PHP   3. PHPUnit\TextUI\Command->run() /var/www/projects/aqlamy-backend-services/vendor/phpunit/phpunit/src/TextUI/Command.php:68
PHP   4. PHPUnit\TextUI\TestRunner->run() /var/www/projects/aqlamy-backend-services/vendor/phpunit/phpunit/src/TextUI/Command.php:108
PHP   5. PHPUnit\Framework\TestSuite->run() /var/www/projects/aqlamy-backend-services/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:653
PHP   6. PHPUnit\Framework\TestSuite->run() /var/www/projects/aqlamy-backend-services/vendor/phpunit/phpunit/src/Framework/TestSuite.php:639
PHP   7. PHPUnit\Framework\TestSuite->run() /var/www/projects/aqlamy-backend-services/vendor/phpunit/phpunit/src/Framework/TestSuite.php:639
PHP   8. Tests\Feature\Api\ArticleImage\ArticleFeaturedImageCreateIntegTest->run() /var/www/projects/aqlamy-backend-services/vendor/phpunit/phpunit/src/Framework/TestSuite.php:639
PHP   9. PHPUnit\Framework\TestResult->run() /var/www/projects/aqlamy-backend-services/vendor/phpunit/phpunit/src/Framework/TestCase.php:772
PHP  10. SebastianBergmann\CodeCoverage\CodeCoverage->start() /var/www/projects/aqlamy-backend-services/vendor/phpunit/phpunit/src/Framework/TestResult.php:642
PHP  11. SebastianBergmann\CodeCoverage\CodeCoverage->initializeData() /var/www/projects/aqlamy-backend-services/vendor/phpunit/php-code-coverage/src/CodeCoverage.php:239
PHP  12. include_once() /var/www/projects/aqlamy-backend-services/vendor/phpunit/php-code-coverage/src/CodeCoverage.php:955

#### How to reproduce

run the command vendor/bin/phpunit --coverage-html "tests/coverage"

#### Expected behavior

run unit tests with coverage 
[phpunit.zip](https://github.com/sebastianbergmann/phpunit/files/4680595/phpunit.zip)

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by QATesterIOS** [comment]
Thank you  for your quick response, I will try to find such a test case and get back to you

**Comment by QATesterIOS** [comment]
Hello Sebastian,
While we unfortunately not be able to share our code base I am not sure if there is a workaround to skip this plugin from being loaded by phpunit , the problem occurs when parsoid files are being loaded by CodeCoverage.php ? please help us to find a  workaround if there is .

**Comment by sebastianbergmann** [comment]
What is parsoid?

**Comment by QATesterIOS** [comment]
Parsoid is an application that allows for converting back and forth between wikitext and HTML.
Please see more here https://www.mediawiki.org/wiki/Parsoid

**Comment by sebastianbergmann** [comment]
It looks to me like you have code on your code coverage whitelist that should not be loaded by PHPUnit (set `processUncoveredFilesFromWhitelist="false"`) and should not be on your whitelist to begin with (because it's not yours).

**Comment by QATesterIOS** [comment]
working for me now many thanks
