### ISSUE TITLE
Add ArrayHasDeepKey Constraint and Assertion

### ISSUE THREAD

**Issue by naciriii** [sebastianbergmann/phpunit#4248]
### Summary :
While I was Writing some tests, I've run through a test case where I wanted to stub a method that accepts a nested array as argument, and based on some of the deep arguments I wanted to return different results.

I've tried using **ArrayHasKey** constraint as show in the code samples below but figured out that **ArrayHasKey** doesn't perform a deep search in the passed nested array, and if the searched key exists deeply the assertion will be falsey.
 I've looked in the API if there's something like **ArrayHasDeepKey** or something like ChaiJS [**containsAllDeepKeys**  ](https://www.chaijs.com/api/assert/#method_containsalldeepkeys) ,but It wasn't there.

 I ended up using a workaround in my case, and I figured out It'd be nice to have something like that in PHPUnit so I decided to contribute with one.
#### Actual Method Calls
```php
/**
* I wanted to retrun different result based on existence of 
* either deepKey1 or deepKey2 in the inner payload array
*/
$firstCall = $this->client->method(
            'simpleStringParam',
            [
            "payload" => [
            "deepKey1" => "Foo"
                            ]
            ]
        );
$secondCall = $this->client->method(
            'simpleStringParam',
            [
            "payload" => [
            "deepKey2" => "Bar"
                            ]
            ]
        );
```
#### Attempted Stubbing
```php
// Initialize the stub
$clientStub = $this->stub(Client::class);

/**
* Stub the method to return  deepKey1 existence based response 
* Returns false Since the Argument doesn't have deepkey1 key directly in its keys
*/
 $clientStub->method('method')
                   ->with("simpleStringParam", $this->arrayHasKey('deepKey1'))
                   ->willReturn($this->getDeepKeyOneBasedResponse());

/**
* Stub the method to return  deepKey2 existence based response
*  Returns false Since the Argument doesn't have deepkey2 key directly in its keys
*/
 $clientStub->method('method')
                   ->with("simpleStringParam", $this->arrayHasKey('deepKey2'))
                   ->willReturn($this->getDeepKeyTwoBasedResponse());

```
#### Issue
**ArrayHasKey** Constraint will perform _**array_has_key(haystack, needle)**_ function which search for the key existence in a high level without searching deeply if the haystack is a nested array.

#### Fix
It would be great to have a constraint that search deeply in the array argument, It'll be something like this : 
```php
/**
* Stub the method to return  deepKey1 existence based response
*  Returns true Since the Argument  have deepkey1 key  in the inner payload array keys
*/
 $clientStub->method('method')
                   ->with("simpleStringParam", $this->arrayHasDeepKey('deepKey1'))
                   ->willReturn($this->getDeepKeyOneBasedResponse());

// Stub the method to return  deepKey2 existence based response
 $clientStub->method('method')
                   ->with("simpleStringParam", $this->arrayHasDeepKey('deepKey2'))
                   ->willReturn($this->getDeepKeyTwoBasedResponse());
```
I 'll create a pull request that close this issue later today.

**Comment by sebastianbergmann** [comment]
I am not interested in adding this constraint and/or assertion to PHPUnit.
