### ISSUE TITLE
Class 'PHPUnit\TextUI\Configuration\TestDirectory' not found

### ISSUE THREAD

**Issue by o5** [sebastianbergmann/phpunit#4256]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.1.5
| PHP version         | 7.4.6
| Installation Method | Composer

#### Summary
Running from global installation does not work in latest version (I tried version 8.5.5 (same phpunit.xml) and works as expected)

#### Current behavior

```
[root@9ef5bd8d29b3 /var/www]$ phpunit
PHP Warning:  include(/root/.composer/vendor/composer/../phpunit/phpunit/src/TextUI/Configuration/TestSuite/TestDirectory.php): failed to open stream: No such file or directory in /root/.composer/vendor/composer/ClassLoader.php on line 444
PHP Warning:  include(): Failed opening '/root/.composer/vendor/composer/../phpunit/phpunit/src/TextUI/Configuration/TestSuite/TestDirectory.php' for inclusion (include_path='.:/usr/local/lib/php') in /root/.composer/vendor/composer/ClassLoader.php on line 444
Class 'PHPUnit\TextUI\Configuration\TestDirectory' not found
```

#### How to reproduce

```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.1/phpunit.xsd"
         bootstrap="tests/bootstrap.php"
         executionOrder="depends,defects"
         forceCoversAnnotation="true"
         beStrictAboutCoversAnnotation="true"
         beStrictAboutOutputDuringTests="true"
         beStrictAboutTodoAnnotatedTests="true"
         verbose="true">
    <testsuites>
        <testsuite name="default">
            <directory suffix="Test.php">tests</directory>
        </testsuite>
    </testsuites>

    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">src</directory>
        </whitelist>
    </filter>
</phpunit>
```

#### Expected behavior

No PHP Warnings

**Comment by sebastianbergmann** [comment]
It appears that you have different installations of PHPUnit mixed up.

For instance, you may have used Composer to install PHPUnit and have configured the autoloader generated by Composer as PHPUnit's bootstrap script but then you invoke PHPUnit using an executable other than `vendor/bin/phpunit`.

**Comment by o5** [comment]
PHPUnit is installed by Composer in global scope (this is the reason why executable is just only `phpunit` - using `PATH=/root/.composer/vendor/bin:$PATH`. It's because PHPUnit is installed in Docker base image for easier development - instead of installing "locally" in application `composer.json` and `require_dev`)

I spent 2 hours of debugging this weird behaviour and finally caught it. If I change version of globally installed PHPUnit in docker base image from `9.1.5` to `8.5.5` then bootstrap file `tests/bootstrap.php` is be used and it works as expected. 

Looks similar like weird behaviour with `doctrine/instantiator` which I had in past in this same setup (PHPUnit installed using `composer global require`)
