### ISSUE TITLE
Add configuration option for branch coverage and path coverage

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#4260]

**Comment by dvdoug** [comment]
Hello @sebastianbergmann 

This or the refactor you did I think has broken reading data from the configuration file. With a new-format config file that contains the `<coverage><report>` keys and passes validation, no reports are being generated when I execute `vendor/bin/phpunit`. I can still get a report using CLI configuration.

```
$ git rev-parse HEAD
8dbba713fd445411096f5a15dbf5ff44f4784b2c
```

```
diff --git a/phpunit.xml b/phpunit.xml
index 59a06bc..76e7fd4 100644
--- a/phpunit.xml
+++ b/phpunit.xml
@@ -12,10 +12,15 @@
         </testsuite>
     </testsuites>
 
-    <coverage processUncoveredFiles="true">
+    <coverage pathCoverage="true" processUncoveredFiles="true">
         <include>
             <directory suffix=".php">src</directory>
         </include>
+
+        <report>
+            <text outputFile="php://stdout" showUncoveredFiles="true"/>
+            <html outputDirectory="build/coverage"/>
+        </report>
     </coverage>
 
     <php>
```

**Comment by sebastianbergmann** [comment]
Thank you for brininging this to my attention. To be exact, reading from the configuration file worked just fine. Configuration for code coverage reports was just ignored in the test runner :-)

**Comment by dvdoug** [comment]
👍
