### ISSUE TITLE
TestCase.php missing from API source page

### ISSUE THREAD

**Issue by sfsccn** [sebastianbergmann/phpunit#4263]
I just wanted to point out that `Framework/TestCase.php` seems to be missing from the API source page https://api.phpunit.de/source/Framework/index.html (tag: 9.1.5-99-g27f0f15). I'm not sure if it has something to do with the fact that the class is abstract. That page does include the abstract `Assert` class. Note also that the API's class page for `Assert` is missing the `abstract` keyword (and the word "abstract" doesn't appear anywhere on that page):

``` php
class Assert {
// members
private static integer $count = 0;
```

So not really a feature request or a bug. These may simply be phpdox issues. Or maybe I'm misunderstanding how phpdox is supposed to work.

**Comment by sebastianbergmann** [comment]
CC @theseer

**Comment by sebastianbergmann** [comment]
Closing because this is not a PHPUnit issue.

**Comment by theseer** [comment]
Can we "migrate" this issue to phpDox?

**Comment by epdenouden** [comment]
"Donate"
