### ISSUE TITLE
Option to enforce 100% coverage of @covers classes and methods

### ISSUE THREAD

**Issue by still-dreaming-1** [sebastianbergmann/phpunit#4265]
I really like the way the `@covers` annotation clarifies that coverage is not "accidental" and should be considered actual coverage. I also like that there are some strict settings in regards to how coverage is enforced that you can place in your phpunit.xml file. However, there is one thing missing in all of this that I would really like to have. I would like to have an option that causes a test to fail, if what it is covering does not end up with 100% coverage as a result. Let me explain more how I want to use these features.

I don't want to have to log coverage results in files in order to use this feature. I'm not interested in seeing what did get covered, or what the overall coverage percentage is. I'm not trying to achieve 100% coverage throughout the entire code base. What I want to do is, as I begin to write a new class, if and when I am doing TDD, I want to start out with 100% coverage enforced from the beginning, for that class. Over time, the programmers might decide this is no longer practical/helpful for that class, but I want this to be a concious decision. They should have to change something about the test code to indicate it is no longer required to achieve complete coverage. So let's say there is a MyClass and a MyClassTest, and at the top of the test, it has an `@covers` annotation specifying it covers MyClass. If this TestCase fails to, entirely without the aid of other tests, cover 100% of MyClass, the test should fail, and an output of which lines did not get covered should show up in the test fail output. If code coverage is somehow failing to be tracked at all, these tests should also fail in that case.

I realize this might seem impractical to enforce to some people, but I have actually implemented this myself in my simpletest tests for one project I work on. It analyzes the in memory results (php variables) from php-code-coverage (not a report it generates), and works as described above. It turned out to be very practical and useful in practice. There are certain types of classes, like reusable, immutable or pure classes, that have no side effects, that are somewhat algorithmically intense, where you want to achieve 100% coverage on them, even if you don't bother to test any of your other code. This way, as soon as your coverage drops, the person running the tests will see this, and will hopefully be motivated to add some tests. For me this often happened when I added a new method to one of these classes without using TDD. Then after the test failed, I had to decide if I was really going to exclude it from requiring 100% coverage, or go ahead and write the test. So I may not have had enough discipline to do TDD every time I worked with this code, but I had enough to add the test after the fact when not having a test for it made the TestCase fail.

I think this would work nicely with the way `@covers` can be used either to clarify a covered class, or to clarify a covered method. If it specified a method, it should achieve 100% coverage of that method. I'm not sure if each individual test using an `@covers` annotation for a particular method should achieve 100% coverage of that method on its own, or if it is okay to get help from other test methods in that same TestCase that also `@covers` that same method. Probably the latter..

Alternatively, this could be a new annotation called `@totallyCovers` or something like that.

**Comment by sebastianbergmann** [comment]
I do not think that this would be useful.
