### ISSUE TITLE
Unexpected JSON Results when using @depends

### ISSUE THREAD

**Issue by KOGI** [sebastianbergmann/phpunit#428]
I have the following tests where one test depends on another:

```php
<?php

class PhpTest extends PHPUnit_Framework_TestCase
{
	public function testImapInstalled( )
	{
		/* ... */

		$this->assertTrue( false, 'IMAP not installed.' );
	}

	/**
	 * @depends testImapInstalled
	 */
	public function testImapVersion( )
	{
		/* ... */
	}
}
```

When looking at the JSON output (generated with `--log-json path/to/save`), I see this (converted to PHP arrays/objects):

```
0 => 
    object(stdClass)[1]
      public 'event' => string 'testStart' (length=9)
      public 'suite' => string 'PhpTest' (length=7)
      public 'test' => string 'PhpTest::testImapInstalled' (length=26)
1 => 
    object(stdClass)[2]
      public 'event' => string 'test' (length=4)
      public 'suite' => string 'PhpTest' (length=7)
      public 'test' => string 'PhpTest::testImapInstalled' (length=26)
      public 'status' => string 'fail' (length=4)
      public 'time' => float 0.022887945175171
      public 'trace' => 
        array
          empty
      public 'message' => string 'IMAP not installed.' (length=19)
2 => 
    object(stdClass)[3]
      public 'event' => string 'test' (length=4)
      public 'suite' => string 'PhpTest' (length=7)
      public 'test' => string 'PhpTest::testImapInstalled' (length=26)
      public 'status' => string 'error' (length=5)
      public 'time' => int 0
      public 'trace' => 
        array
          empty
      public 'message' => string 'Skipped Test' (length=12)
```

You can see that:

1. array item 0
   * `testImapInstalled( )` is run and fails as "not installed"

2. array item 1
   * (inferred) `testImapVersion( )` depends on `testImapInstalled` and thus runs it again (again failing) 

3. array item 2
   * because the dependency failed, `testImapVersion` fails with "Skipped Test"

However, if you look closely at array item 2, you can see the test is listed as `public 'test' => string 'PhpTest::testImapInstalled'` which is actually the dependency test.

Expected behavior would be to list `testImapVersion` as the test name, and possibly list `testImapInstalled` as the dependency or mention it in the failure message. Possibly like the below:

```
0 => 
    object(stdClass)[1]
      public 'event' => string 'testStart' (length=9)
      public 'suite' => string 'PhpTest' (length=7)
      public 'test' => string 'PhpTest::testImapInstalled' (length=26)
1 => 
    object(stdClass)[2]
      public 'event' => string 'test' (length=4)
      public 'suite' => string 'PhpTest' (length=7)
      public 'test' => string 'PhpTest::testImapInstalled' (length=26)
      public 'status' => string 'fail' (length=4)
      public 'time' => float 0.022887945175171
      public 'trace' => 
        array
          empty
      public 'message' => string 'IMAP not installed.' (length=19)
2 => 
    object(stdClass)[1]
      public 'event' => string 'testStart' (length=9)
      public 'suite' => string 'PhpTest' (length=7)
      public 'test' => string 'PhpTest::testImapVersion' (length=24)
3 => 
    object(stdClass)[3]
      public 'event' => string 'test' (length=4)
      public 'suite' => string 'PhpTest' (length=7)
      public 'test' => string 'PhpTest::testImapVersion' (length=24)
      public 'dependency' => string 'PhpTest::testImapInstalled' (length=26)
      public 'status' => string 'error' (length=5)
      public 'time' => int 0
      public 'trace' => 
        array
          empty
      public 'message' => string 'Skipped Test due to Failed Dependency' (length=12)
```

**Edit to add:**

When using CLI, this is the output from the above (as expected):

```
There was 1 skipped test:

1) PhpTest::testImapVersion
This test depends on "PhpTest::testImapInstalled" to pass.
```

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
