### ISSUE TITLE
Backport commandline and xml config whitelist/blacklist replacements

### ISSUE THREAD

**Issue by GrahamCampbell** [sebastianbergmann/phpunit#4280]
PHPUnit 9 isn't actually that widely used yet, because of its aggressive dropping of PHP versions. PHPUnit 8, 7, 6 and 5 still have more monthly downloads (each, separately!)

![image](https://user-images.githubusercontent.com/2829600/84023105-6776c880-a97f-11ea-9d15-156322899bd0.png)

*Source: https://packagist.org/packages/phpunit/phpunit/stats*

For this reason, we should backport the user-facing changes so that people using older versions can update their config files and CI scripts to use the new terminology. Without this, people may be forced to use the old, offensive terminology for years, just because they want to test their packages on PHP 7.1, for example.

**Comment by sebastianbergmann** [comment]
PHPUnit 7 is no longer maintained and PHPUnit 8 receives bug fixes only.

**Comment by GrahamCampbell** [comment]
I think we have to make an exception for this, if you are serious about removing racist terminology from the codebase. One has to acknowledge PHPUnit 9 has low adoption (less than 10% of installs!), and so this needs to be fixed in more versions. Only changing in PHPUnit 9 is effectively not doing anything for 90% of people.
