### ISSUE TITLE
Incorrect exit code (false positive)

### ISSUE THREAD

**Issue by healerz** [sebastianbergmann/phpunit#4285]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.2.1 + 9.2.2
| PHP version         | 7.4.6
| Installation Method | Composer

#### Summary

Exit code of PHPUnit is not always correct. Depending on the filter it may or may not be correct. Even though we have failing tests, the exit code returned by PHPUnit is 0.

#### Current behavior

Without any filter and failing tests returned exit code is 0.
With filter "phpunit /folder1/folder2" and failing tests returned exit code is 0.
With filter "phpunit /folder1/folder2/folder3" and the same failing tests exit code is 1.

It works fine in our case with PHPUnit v9.2.0 and v9.1.5

#### How to reproduce

I'm sorry for not providing precise steps to reproduce it.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by sebastianbergmann** [comment]
No feedback, closing.
