### ISSUE TITLE
PHPUnit fails with error Non-static method SebastianBergmann\Timer\Timer::start() should not be called statically

### ISSUE THREAD

**Issue by Cypaubr** [sebastianbergmann/phpunit#4290]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.2.2
| PHP version         | 7.4
| Installation Method | Composer

#### Summary

I use the phpunit script provided in the Symfony project. On my local environment, all tests are passing, on Gitlab CI, it fails with an error.

#### Current behavior

Tests on Gitlab CI are failing with error:
`Non-static method SebastianBergmann\Timer\Timer::start() should not be called statically`

#### Expected behavior

PHPUnit running finely and tests passing.

**Comment by sebastianbergmann** [comment]
It appears that you have different installations of PHPUnit mixed up.

For instance, you may have used Composer to install PHPUnit and have configured the autoloader generated by Composer as PHPUnit's bootstrap script but then you invoke PHPUnit using an executable other than `vendor/bin/phpunit`.

**Comment by Cypaubr** [comment]
@sebastianbergmann I have not PHPUnit entry or library related to PHPUnit installed by my composer.json file, as I said, the only thing I do in the Gitlab CI runner is:

- composer install -o --dev --no-cache
- php bin/phpunit

I am kinda lost on this issue

**Comment by manzolo** [comment]
Same problem here @sebastianbergmann 
https://travis-ci.com/github/ComuneFI/BiCoreBundle/builds/192649211
I released various commits today and it worked. From the last commit on php 7.2 is ok, while on php 7.3 and php 7.4 same problem of @Cypaubr  https://github.com/ComuneFI/BiCoreBundle/commit/921eba7ebcbfaf1aeb962c65f1d346afd9936ecb
I suspect it's something related to php 7.3+ ..

**Comment by manzolo** [comment]
I find this difference @sebastianbergmann 

https://github.com/sebastianbergmann/php-timer/blob/2.1.2/src/Timer.php

private static $startTimes = [];

    public static function start(): void
    {
        self::$startTimes[] = \microtime(true);
    }



https://github.com/sebastianbergmann/php-timer/blob/5.0.2/src/Timer.php
    private $startTimes = [];

    public function start(): void
    {
        $this->startTimes[] = (float) hrtime(true);
    }

**Comment by manzolo** [comment]
Removing "sebastian/phpcpd": "^6.0" is back to work , Could it be an incompatibility between phpunit 7.5+ and phpcpd 6.x @sebastianbergmann ?

**Comment by fr4ngus** [comment]
It's not recommended to install tools for static code analysis with composer due to this kind of problem. Cf. https://twitter.com/s_bergmann/status/999635212723212288

**Comment by billizzard** [comment]
How to resolve this problem?
