### ISSUE TITLE
Deprecate at() matcher

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#4297]
The behaviour of `at()` is confusing. Using `at()` leads to brittle tests at best and lying tests at worst. The documentation even states:

> The `$index` parameter for the `at()` matcher refers to the index, starting at zero, in all method invocations for a given mock object. Exercise caution when using this matcher as it can lead to brittle tests which are too closely tied to specific implementation details.

Furthermore, the implementation of `at()` impedes improvements to other aspects of the test doubles support in PHPUnit, see https://github.com/sebastianbergmann/phpunit/issues/4291#issuecomment-644947020 for example.

We should therefore deprecate

* `PHPUnit\Framework\TestCase::at()` (as well as the `PHPUnit\Framework\at()` wrapper)
* `PHPUnit\Framework\MockObject\Rule\InvokedAtIndex`

in PHPUnit 9 and [remove](https://github.com/sebastianbergmann/phpunit/issues/4298) it in PHPUnit 10.

If we realize that a mechanism for specifying the order in which expected invocations occur then, and only then, shall we think about how to best implement this. A replacement for `at()` is explicitly outside the scope of this deprecation.

**Comment by Levivb** [comment]
I agree with the deprecation of this unholy method. Mostly `withConsecutive` and `willReturnMap` will suffice.

But what about this scenario?

```
        $this->pageBuilder
            ->expects($this->exactly(3))
            ->method('create')
            ->withConsecutive([$this->collection[0]], [$this->collection[1]], [$this->collection[2]]);

        $this->pageBuilder
            ->expects($this->at(1)) // the middle creation will error
            ->method('create')
            ->willThrowException($exception);
```

At which the second `create` call (index 1) should throw an exception?

Maybe something with `$this->callback` in combination with `withConsecutive`.. can't quite figure this one out

**Comment by allcode** [comment]
@Levivb This will work:

```php
$this->pageBuilder
    ->expects($this->exactly(3))
    ->method('create')
    ->withConsecutive([$this->collection[0]], [$this->collection[1]], [$this->collection[2]]);
    ->willReturnOnConsecutiveCalls(
        null,
        $this->throwException(new RuntimeException('Some message')),
        null
    );
```

The only downside is that you'll have to define an explicit (and valid) return value for all calls.

**Comment by Levivb** [comment]
@allcode Thanks for your suggestion!

I did consider that. It's just that the method in question has typehint `: void` and it feels a bit awry to change the return type in production code to some nonsensical value just for the sake of a test

**Comment by yyaremenko** [comment]
it would be extraordinary nice if you guys could create some sort of documentation about how to properly migrate from using this method (what methods to use instead of the deprecated one).

**Comment by pwellingelastique** [comment]
I could not agree more with @ossinkine, Sometimes I exactly want to test if a function is called on a specific position.

For instance I have this code:
```
class SomeClass
{
    /**
     * @var ContainerInterface
     */
    protected $container;

    public function __construct(ContainerInterface $container)
    {
        $this->container = $container;
    }

    function someName()
    {
        $input = [1, 2, 3];
        foreach ($input as $value) {
            if ($this->container->get('someService')->functionNameA($value)) {
                $this->container->get('someService')->functionNameB();
            }
        }
    }
}

class SomeService
{
    function functionNameA(int $value)
    {
        return $value == 2;
    }

    functionNameB()
    {
        // Do something
    }
}
```
If I wanted to test that functionNameB has been called as 3rd when testing this first method, I would have a very difficult time, since I want to test that it has been called for that specific value. (value == 2) and not value == 1 or  value == 3
And that would also go for any other scenario I might think of

Having tested that it is called one thing, but knowing the order of execution is in some cases as important as knowing it has been called

Please reconsider

**Comment by artjomsimon** [comment]
@ossinkine what would happen if a client would call the `begin` and `commit` functions in the wrong order?
Would you throw an exception? Or is that a valid use case?

If throwing an exception, you could explicitly expect the exception to be thrown if you cann `commit` before `begin`.
If it's a valid use case, why test for the order? The returned value should be enough to test, no?

After all, you're testing *your* code, and how it reacts to being called with functions out-of-order.
You can't guarantee that a client will call the code in the correct order.

@pwellingelastique where does your `$input = [1, 2, 3];` come from?
What if it becomes `$input = [0, 1, 2, 3];`, would you then want to change each `->at(n)` to `->at(n+1)`?
What if you introduce a `dataProvider`, testing different `$input`s, like `[-1, false, PHP_INT_MAX, null, true, 3]`?
What are you testing here - how your code reacts to different inputs? Or the exact order in which some instructions are executed?

The idea of removing `at()` is to make people stop writing tests that are brittle. Tests that have to be changed when your actual code changes.

Your example is such a brittle example: Let's say you refactor and introduce a new function `SomeService::functionNameBWhenAIsTrue()` as a convenience function that does the `if (...)` check inside.

Now you have to change your tests for `SomeClass`. But you didn't change the logic in any way, you simply refactored the `if ()` into `SomeService`. Changing the test for `SomeClass` should not be necessary.

Deprecating `at(...)` makes us think harder: What behavior am I *actually* testing when testing `someName()`?
And that's a Good Thing.

**Comment by ossinkine** [comment]
@artjomsimon My code calls the functions in certain order. I want to write a test which check the order is still correct. If I change my code where order was changed I want the test fails. If the code with wrong function calls run on production the exception will be thrown.

**Comment by artjomsimon** [comment]
@ossinkine it sounds like checking if function A was called is a responsibility of the class containing the two functions that need to be called in order:

```
class SomeService
{
    private bool $hasABeenCalled = false;

    function functionNameA(int $value)
    {
        $this->hasABeenCalled = true;
        return $value == 2;
    }

    functionNameB()
    {
        if ($this->hasABeenCalled === false) {
            throw new RuntimeException('You cannot call B before calling A. Call A first.');
        }
        // Do something
        $this->hasABeenCalled = false;
    }
}
```

Now, in your tests, you can test this behavior:

```
public test testSomeClassThrowsExceptionWhenCallingFunctionsInWrongOrder() : void {
        $this->expectException(RuntimeException::class);

    $service = new SomeService();
    $service->functionNameB();
    $service->functionNameA();
}
```

With the exception, you will make sure that *anyone* (you, your colleague, your end users, people who will work on your code after you leave) gets the `RuntimeException` when calling the functions in a wrong order.

Your Tests for the other class (`SomeClass`) should *not* test the implementation details for `SomeService`. That's what the tests for `SomeService` is for.

What if you refactor the `SomeClass` and use a new service that does the work in only one function call? You would have to change your test.. but you didn't change the logic, you just used another service! Changing the Tests should not be necessary.

Again, deprecating `->at(...)` is showing design flaws in our code, and it's a very good thing.

**Comment by ossinkine** [comment]
@artjomsimon I don't want to test `SomeService`, this is third party class, it's all ok with this. I want to test my code which uses `SomeService` (which is mocked in tests) calls `functionNameA` and `functionNameB` in right order. For example:
```php
class MyService
{
    private SomeService $service;
    public function __construct(SomeService $service)
    {
        $this->service = $service;
    }

    public function doSomething(): void
    {
        $this->functionNameA();
        $this->functionNameB();
    }
}

class MyServiceTest extends TestCase
{
    public function testSomething(): void
    {
        $service = $this->createMock(SomeService::class);
        $myService = new MyService($service);

        $service->expects($this->at(1))->method('functionNameA');
        $service->expects($this->at(2))->method('functionNameB');

        $myService->doSomething();
    }
}
```

**Comment by pwellingelastique** [comment]
I do agree that you do not want to test the lines of a method, and that if you change the method, your test would fail. But as @ossinkine states, I do not want to test the other service, but I want to be sure it has been called in a specific order (based on my scenario) or that the method has not been called at all. What if there is a 3 method called right after the if-statement in my example? I would want to be sure that only in case of $input == 2 (or to be more exact, $input === 2) service function B has been called, and not in all the other cases.

Having said that, writing too complex methods, and the difficulty of having these tested, does force you to rewrite them so they are less complex. But sometimes you just can't avoid complex methods where other methods (in other objects) are called in a specific order based on the input. And I do sometimes want to be very sure that a method that for instance sends out an email or sets a very important switch elsewhere, has been called if it has to be art the right moment.

Does my tested method have too much responsibilities? It might, but sometimes you just can't avoid that. And with the at() method, you have an extra tool just to make sure.

The outcome of my test might just be that some things are called in a specific order. That might just be the result of the called function. And when I change the lines of the function, which causes the order to change, when that shouldn't happen, my unit test should fail, just to prevent that. And if it is intentional, then I should also change my test.
So in my opinion, the at() method should not be removed, since it is a handy tool to just to monitor the behaviour.

**Comment by Pi-George** [comment]
How would something like this be re-written? I'm having some trouble with understanding the alternative syntax that should be replacing usage of at. Many of the mentioned functions aren't in the documentation as far as I can tell.

```
        $this->workspaceDao->expects($this->at(0))
            ->method('getWorkspace')
            ->with("1")
            ->willReturn($singleWorkspace);

        $this->workspaceDao->expects($this->at(1))
            ->method('getWorkspace')
            ->with("2")
            ->willReturn($singleWorkspace2);

        $this->keywordGroupDao->expects($this->at(0))
            ->method('getAllKeywordsInGroups')
            ->with(["1001", "1002", "1003"], TrackingPeriod::current($singleWorkspace->getTrackingFrequency()))
            ->willReturn([]);
```

**Comment by kdambekalns** [comment]
> How would something like this be re-written?

The first two can be rewritten like this:
```
        $this->workspaceDao->method('getWorkspace')
            ->withConsecutive(["1"], ["2"])
            ->willReturnOnConsecutiveCalls($singleWorkspace, $singleWorkspace2);
```

For the last it depends on how important the `at(0)` really is. Use `atLeastOnce()`, `once()`, excatly(…)` as needed or simple leave `expects(…)` out completely:
```
        $this->keywordGroupDao->method('getAllKeywordsInGroups')
            ->with(["1001", "1002", "1003"], TrackingPeriod::current($singleWorkspace->getTrackingFrequency()))
            ->willReturn([]);
```

**Comment by kdambekalns** [comment]
Another example for the (common?) usecase of testing method call order:

```
$calls = [];
$subject = $this->getMockBuilder(Subject::class)->setMethods(['a', 'b', 'c'])->getMock();
$subject->expects(self::atLeastOnce())->method('a')->willReturnCallback(function () use (&$calls) { $calls[] = 'a'; });
$subject->expects(self::atLeastOnce())->method('b')->willReturnCallback(function () use (&$calls) { $calls[] = 'b'; });
$subject->expects(self::atLeastOnce())->method('c')->willReturnCallback(function () use (&$calls) { $calls[] = 'c'; });

$subject->someMethod();

self::assertEquals(['a', 'b', 'c'], $calls);
```

**Comment by alex-pravdin-sn** [comment]
To solve this issue I wrote my own matcher that counts only calls of the specified method, not all calls of the mock. This makes sense because other matchers like "method X expected `once`" or "method Y expected `never`" have the same meaning - they relate to the number of calls of the specified method, not to all calls on the mock. The current `at` behavior contradicts `once`, `never`, and others. So adding a matcher that counts only calls of the specific method worked for me for years.

The issue with the `at` method is multiplied by the absence of the ability to mock protected methods. Mocking separated code blocks could effectively decrease the requirement to count particular calls and endlessly edit big tests on minor changes in complex business logic.

**Comment by alex-pravdin-sn** [comment]
As a bright example of why a matcher that matches particular hits of the specified method is needed - try to test a class that implements an Iterator in addition to its own methods. Like `Elastica\ResultSet`. It leads to a [nightmare](https://stackoverflow.com/questions/15907249/how-can-i-mock-a-class-that-implements-the-iterator-interface-using-phpunit) with the standard matchers set especially when the number of testing iterations changes from time to time. But with a matcher that matches particular hits of particular methods - tests become really straight forward and more clear.

**Comment by carlobeltrame** [comment]
Another case: I have a CLI command that runs some logic and then cleans up some intermediary files (Doctrine proxies in this case, so a temporary directory is not a solution). I'd like to test that the cleanup happens after the rest of the expected logic. I see no good way to do this without `at()`.

Mockito in Java has [InOrder](https://www.javadoc.io/doc/org.mockito/mockito-core/2.6.9/org/mockito/InOrder.html) for this purpose, which is more flexible in its matching behaviour than specifying brittle, fixed indexes. I don't know much about phpunit internals, but maybe it's possible to implement something similar?

**Comment by alex-pravdin-sn** [comment]
> The only downside is that you'll have to define an explicit (and valid) return value for all calls.

How to workaround this? PHPUnit allows passing predefined test data to test methods where the number of items in an array may vary. How to define consecutive calls mocking in this case when the exact number of calls can not be hard coded?

**Comment by GlennBags** [comment]
I see that this is closed, but at the same time, I, like Alex Pravdin would like to know the best method for replacing `at`, as we're in the process of updating our code.

**Comment by NamelessCoder** [comment]
> I see that this is closed, but at the same time, I, like Alex Pravdin would like to know the best method for replacing `at`, as we're in the process of updating our code.

I believe that `withConsecutive` and `willReturnOnConsecutiveCalls` is the solution to aim for. The former should be called like `$subject->method($method)->withConsecutive($firstArgumentsArray, $secondArgumentsArray) ;` and the latter should be called like `$subject->method($method)->willReturnOnConsecutiveCalls($firstReturn, $secondReturn);` and so on. Other options for returns include `willReturnMap` and `willReturnCallback` which let you specify either an input-arguments-to-return-value map, or a callback function that takes the input argument(s) and returns something.

**Comment by GlennBags** [comment]
> > I see that this is closed, but at the same time, I, like Alex Pravdin would like to know the best method for replacing `at`, as we're in the process of updating our code.
> 
> I believe that `withConsecutive` and `willReturnOnConsecutiveCalls` is the solution to aim for. The former should be called like `$subject->method($method)->withConsecutive($firstArgumentsArray, $secondArgumentsArray) ;` and the latter should be called like `$subject->method($method)->willReturnOnConsecutiveCalls($firstReturn, $secondReturn);` and so on. Other options for returns include `willReturnMap` and `willReturnCallback` which let you specify either an input-arguments-to-return-value map, or a callback function that takes the input argument(s) and returns something.

OK, thanks for the feedback

**Comment by alex-pravdin-sn** [comment]
Any estimations of when `withConsecutive` and `willReturnOnConsecutiveCalls` methods will be documented?

**Comment by kdambekalns** [comment]
> Any estimations of when `withConsecutive` and `willReturnOnConsecutiveCalls` methods will be documented?

The first has an example at https://phpunit.readthedocs.io/en/9.5/test-doubles.html?highlight=withConsecutive#mock-objects and the latter behaves like `willReturn()` (see https://phpunit.readthedocs.io/en/9.5/test-doubles.html?highlight=willReturn#stubs) but returning different values per call (as given.)

But yeah, documentation is sketchy in places, especially when digging deeper… 😬

**Comment by garethellis36** [comment]
I have a legacy project with more than 500 uses of the `at()` matcher. The tests are indeed brittle but the code under test is pretty stable (bug fixes only). The tests have been useful for detecting regressions with PHP upgrades. The next upgrade is 8.1, which requires PHPUnit 9, so I'm running up against this issue.

If I copy the phpunit  matcher class and add an alias for `at()` in our base test class, am I likely to cause anything else to break? Doing 500 updates to replace the `at()` matcher by hand is rather daunting!

**Comment by alaqill22** [comment]
I have the same issue The at() matcher has been deprecated
the code is

 
        //create iceptrax model mock
        $iceptraxModelMock = $this->getMockBuilder(\Firstwap\Altamides\Modules\Iceptrax\Http\IceptraxModel::class)
                                  ->disableOriginalConstructor()
                                  ->setMethods($modelMethods)
                                  ->getMock();
    
        foreach($method as $methods => $returnVal)
        {
            if ($returnVal === 'exception')
            {
                $iceptraxModelMock->expects($this->any())
                                  ->method($methods)
                                  ->will($this->throwException(new \Exception()));
            }
            elseif ($multipleMethodSame)
            {
                foreach ($modelMethods as $value)
                { 
                    $iceptraxModelMock->expects($this->at($methods))
                    ->method($value)
                    ->willReturn($returnVal);
  
                    
                }
            }
            else //without parameter
            {
                $iceptraxModelMock->expects($this->any())
                                  ->method($methods)
                                  ->will($this->returnValue($returnVal));
            }
        }
    
        return $iceptraxModelMock;
    }

**Comment by 66Ton99** [comment]
Just for everyone `at()` can be replaced by `exactly()`

**Comment by thamerbelfkihthamer** [comment]
@66Ton99 `exactly()` is taking an argument of how many times the method was invoked not at which index it was executed.

**This will pass**
 ```
  $posts = [$postObject1, $postObject2];
   foreach ($posts as $post) {
         $this->service->save($post);
   }
```

`$this->service->expects(self::exactly(2))->method('save')`: method save is invoked 2 times.


**This will fails**
   ```
$posts = [$postObject1, $postObject2];
   foreach ($posts as $post) {
         $this->service->save($post);
   }
```

`$this->service->expects(self::at(0))->method('save')->with($postObject2)` : method save is invoked at index 0
`$this->service->expects(self::at(1))->method('save')->with($postObject1)` :  method save is invoked at index 1
