### ISSUE TITLE
TestCase::$backupGlobals is declared as boolean but its initial value is NULL

### ISSUE THREAD

**Issue by morozov** [sebastianbergmann/phpunit#4307]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.2.3
| PHP version         | 7.4.7
| Installation Method | Composer

#### Summary

In a project that uses PHPUnit and Psalm, Psalm detects the issue in PHPUnit that cannot be fixed in the project and therefore have to be suppressed.

#### Current behavior

```
ERROR: PropertyNotSetInConstructor - tests/ExampleTest.php:7:7 - Property 
Test\ExampleTest::$backupGlobals is not defined in constructor of Test\ExampleTest and in any 
methods called in the constructor (see https://psalm.dev/074)
class ExampleTest extends TestCase
```
The above is caused by a boolean property being non-initialized:
1. https://github.com/sebastianbergmann/phpunit/blob/61f7c75a11eb1c6908c87235757a428de2bae6d1/src/Framework/TestCase.php#L63-L66
2. https://github.com/sebastianbergmann/phpunit/blob/61f7c75a11eb1c6908c87235757a428de2bae6d1/src/Framework/TestCase.php#L389-L397

#### How to reproduce

```php
<?php declare(strict_types=1);

namespace Test;

use PHPUnit\Framework\TestCase;

class ExampleTest extends TestCase
{
    /**
     * @test
     */
    public function testExample() : void
    {
        $this->assertTrue(true);
    }
}
```

See the full demo project in the [gist](https://gist.github.com/morozov/189e817c9ca8eee4d225f1d3475bc230):
```
$ composer install
$ vendor/bin/psalm
```

Since the project's tests extend and use the PHPUnit test classes, suppressing errors in the `vendor/` directory doesn't help.

#### Expected behavior

The value of `$backupGlobals` is always within its declared type constraints.

**Comment by sebastianbergmann** [comment]
Can you please open separate issues? Thanks!

**Comment by morozov** [comment]
Please see #4309.

**Comment by sebastianbergmann** [comment]
> Please see #4309.

Thanks!
