### ISSUE TITLE
PHPUnit exposes an internal API to the userland

### ISSUE THREAD

**Issue by morozov** [sebastianbergmann/phpunit#4309]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.2.3
| PHP version         | 7.4.7
| Installation Method | Composer

#### Summary

In a project that uses PHPUnit and Psalm, Psalm detects the issue in PHPUnit that cannot be fixed in the project and therefore has to be suppressed.

#### Current behavior

```
ERROR: InternalMethod - tests/ExampleTest.php:17:12 - The method 
PHPUnit\Framework\MockObject\Builder\InvocationMocker::method has been marked as internal 
(see https://psalm.dev/175)
        )->method('test');
```
The above is caused by the interface returning a class marked as `@internal`:
1. https://github.com/sebastianbergmann/phpunit/blob/7f664ffd558ba68031963f63d3e23a951ba441fc/src/Framework/MockObject/MockObject.php#L24
2. https://github.com/sebastianbergmann/phpunit/blob/cb135993b214d87d1cc10359201d23b8ab2057bc/src/Framework/MockObject/Builder/InvocationMocker.php#L29-L32

This issue was already brought up in https://github.com/sebastianbergmann/phpunit/issues/3742#issuecomment-559682132.

#### How to reproduce

```php
<?php declare(strict_types=1);

namespace Test;

use PHPUnit\Framework\TestCase;

class ExampleTest extends TestCase
{
    /**
     * @test
     */
    public function testExample() : void
    {
        $t = $this->createMock(T::class);
        $t->expects(
            $this->never()
        )->method('test');
    }
}

interface T
{
    public function test() : void;
}
```

See the full demo project in the [gist](https://gist.github.com/morozov/189e817c9ca8eee4d225f1d3475bc230):
```
$ composer install
$ vendor/bin/psalm
```

Since the project's tests extend and use the PHPUnit test classes, suppressing errors in the `vendor/` directory doesn't help.

#### Expected behavior

PHPUnit doesn't expose the internal parts of its API to the userland.

**Comment by ostrolucky** [comment]
Ref https://github.com/sebastianbergmann/phpunit/issues/3236. Looks like we  just need to create PR to remove `@internal` from this class.

**Comment by morozov** [comment]
@ostrolucky, thanks for the pointer. I thought of adding an interface that extends `InvocationStubber` and `MethodNameMatch`. Then, instead of returning an `InvocationMocker`, the method could return an instance of that interface.

But just removing `@internal` may be an acceptable short-term solution.
