### ISSUE TITLE
Exit code with no tests changed in bugfix release 8.5.7 (probably also 9.x)

### ISSUE THREAD

**Issue by dominikzogg** [sebastianbergmann/phpunit#4312]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.5.7
| PHP version         | 7.2.15,  7.3.19 , 7.4.7
| Installation Method | Composer

#### Summary

Since PHPUnit 8.5.7 its a problem it there are no tests and the exit code is 1. Before that the return value was 0.
All my newer libraries have a testsuite for unit tests and one for integration test. Not every library has integration tests. Until 8.5.6 this wasn't an issue.

#### Current behavior

No tests => exit code: 1

#### How to reproduce

setup any project with a testsuite without tests

https://travis-ci.org/github/chubbyphp/chubbyphp-container/builds/700689350

https://travis-ci.org/github/chubbyphp/chubbyphp-container/jobs/700689357
https://travis-ci.org/github/chubbyphp/chubbyphp-container/jobs/700689360
https://travis-ci.org/github/chubbyphp/chubbyphp-container/jobs/700689363

#### Expected behavior

No tests => exit code: 0

**Comment by sebastianbergmann** [comment]
It was a bug that PHPUnit exited with `0` when it should have exited with `1`.

**Comment by sebastianbergmann** [comment]
See https://github.com/sebastianbergmann/phpunit/issues/4299#issuecomment-647324709

**Comment by dominikzogg** [comment]
@sebastianbergmann thanks

**Comment by dominikzogg** [comment]
@sebastianbergmann thank you
