### ISSUE TITLE
Please allow some way to communicate with code in TestListener from CLI

### ISSUE THREAD

**Issue by hparadiz** [sebastianbergmann/phpunit#4324]
I noticed some old feature requests where people wanted custom CLI switches. It's fair that you don't want to allow people to define their own I suppose but consider this.

I regularly will want to skip the Mock phase of the test. Especially when I'm rapidly iterating on one specific test that might not even edit anything or need anything in the database.

Typically this Mocking happens in TestListener like so
```php
	public function startTestSuite(TestSuite $suite): void
	{
		//printf("TestSuite '%s' started.\n", $suite->getName());
		if ($suite->getName() == 'all') {
			$app = new App(realpath(__DIR__.'/../../webapp/'));
			fwrite(STDERR, 'Starting Mock Environment for PHPUnit'."\n");
			Mock::setUp();
		}
	}
```

However in recent months I've taken to using a file on the file system to tell it to skip the mock phase like so:
```php
	if (file_exists('tests/.NoMock')) {
		fwrite(STDERR, 'Skipping setup.'."\n");
		return;
	}
```

So my request is to add some CLI switch that could signify that you would like to skip the mock phase or somehow modify it.

However, if there are better way to do this I am all ears.

**Comment by sebastianbergmann** [comment]
The `TestListener` system is [scheduled for removal](https://github.com/sebastianbergmann/phpunit/issues/3389).
