### ISSUE TITLE
Interfaces should not force final-classes in type hints

### ISSUE THREAD

**Issue by ScreamingDev** [sebastianbergmann/phpunit#4341]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.5.8
| PHP version         | 7.3
| Installation Method | Composer

#### Summary

Extending PHPUnit became harder or possibly impossible due to interfaces forcing final classes

#### Current behavior

```php
<?php

use PHPUnit\Framework\MockObject\MockObject;

class Foo extends MockObject {
  public function expects(InvocationOrder $invocationRule)
  {
    return MyOwnInvocationMocker();
  }
}
```

This fails because `expects` does not return `PHPUnit\Framework\MockObject\Builder\InvocationMocker` as defined by the `MockObject` interface. Unfotunately ...

```php
<?php

class MyOwnInvocationMocker extends PHPUnit\Framework\MockObject\Builder\InvocationMocker {
}
```

... is not possible because the InvocationMocker is a final class.

#### Expected behavior

Defined interfaces should not force usage of final classes.
If a class is final and (currently) forced to be used in an interface, then an interface should be derived from this final class.

Example:

```php
<?php

interface MockObject extends Stub
{
    public function __phpunit_setOriginalObject($originalObject): void;

    public function __phpunit_verify(bool $unsetInvocationMocker = true): void;

    public function expects(InvocationOrder $invocationRule): InvocationMockerInterface;
}
```

and

```php
<?php

interface InvocationMockerInterface {
  public function id($id): self;
  public function will(Stub $stub): Identity
  public function willReturn($value, ...$nextValues): self
  public function willReturnReference(&$reference): self
  public function willReturnMap(array $valueMap): self
  public function willReturnArgument($argumentIndex): self
  public function willReturnCallback($callback): self
  public function willReturnSelf(): self
  public function willReturnOnConsecutiveCalls(...$values): self
  public function willThrowException(\Throwable $exception): self
  public function after($id): self
  public function with(...$arguments): self
  public function withConsecutive(...$arguments): self
  public function withAnyParameters(): self
  public function method($constraint): self 
}
```

**Comment by sebastianbergmann** [comment]
This is not a bug as this is not an intended extension point.

**Comment by ScreamingDev** [comment]
Thanks. Please have a look at the workaround because the more I look the less there is an alternative.

---

I had some further thoughts about this that I like to add. First of all I looked up some usages:

* createConfiguredMock
* createMock
* createPartialMock
* createTestProxy
* getMockForAbstractClass
* getMockForTrait
* getMockFromWsdl

Mostly the things that developer use for testing. As MockObject is not an intended extension point those methods may be hard to customize.

---

Looking at `TestCase::runBare` a bit more I see the following steps for test-doubles currently:

1. `::registerMockObjectsFromTestArguments`
2. ... (other stuff)
3. `::assertPreConditions`
4. `::runTest` (one single test)
5. `::verifyMockObjects` 
6. `::assertPostConditions`
7. `->status = BaseTestRunner::STATUS_PASSED` (the result of the test is set at this point)
8. Run "@after" methods (if `::checkRequirements` was successful)

Lets say we have some custom MockObjects (with the initial mentioned problem) and try to place them somewhere else:

* (1) `::registerMockObjectsFromTestArguments` does not allow injection of custom mocks via arguments unless they follow the MockObject-Interface
* (5) `::verifyMockObjects` would be simple by just calling `::registerMockObject`,
  but it forces the current MockObject-Interface again which we try to extend
* (6) We could not use `::assertPostConditions` if we are developing a package that should integrate well
* (8) Having a custom "@after" method would work but instead of a proper `BaseTestRunner::STATUS_FAILURE` all failing "@after" always shows an `BaseTestRunner::STATUS_ERROR` to the user.

So all in all we would need to make `$mockObjects` protected to extend it with a MockObject-Interface-Like thing.

<IMHO>
While custom MockObjects were easy to implement in PHPUnit 7 they are no longer doable within the PHPUnit 8 interfaces (and perhaps in v9 too). This "feature-brake" may be okay in a rigid SemVer logic but I would not have expected a limitation for test-doubles in a Testing-Framework.
</IMHO>

---

Workaround?

Lifting mockObjects to protected via trait does not work (see https://3v4l.org/Tk6AN ).

A possible solution would be to use `ReflectionProperty` (in some @ before method), make `::$mockObjects` accessible and append custom MockObject-Like stuff to the array. A bit risky but allows custom MockObjects without the final `PHPUnit\Framework\MockObject\Builder\InvocationMocker` class as long as `TestCase::verifyMockObjects` does not check for the type (like `::registerMockObjectsFromTestArguments` does).

**Comment by stof** [comment]
As of PHPUnit 9.1, the features of `assertPostConditions` are also available through a `@postCondition` annotation on methods (this has been added when working on extracting the Prophecy integration from the core, precisely to solve that use case of asserting mocking conditions from another library without highjacking the `assertPostConditions` method)

**Comment by ScreamingDev** [comment]
I love this but it sounds like it can't or won't be applied to previous PHPUnit versions, right?
Thanks for implementing this solution. It may be easier especially because I need less BC layer from 9.1 on :) 

I still wonder how to access other private things like `::shouldInvocationMockerBeReset()` to go along with the current state and `::$numAssertions` to reflect the user that the custom mock actually did test something. A package with custom mocks would mostly be a copy of `::verifyMockObjects()` within the `@postCondition` hook, so please allow some kind of access to all the needed internals (e.g. `::increaseNumAssertions()` etc. ) and to reflect the outcome.

see https://github.com/sebastianbergmann/phpunit/blob/9.1.5/src/Framework/TestCase.php#L181
or https://github.com/sebastianbergmann/phpunit/blob/9.1.5/src/Framework/TestCase.php#L2272
for example and possibly there are more things to consider for custom mocks.

I didn't investigate that deep right now, just scratched the surface with quick tests:

* https://3v4l.org/0iF5t , the hooked method has to be protected which may be unintended especially to not vomit all the internal stuff in the devs IDE autocompletion (even though I could mark the method as `@internal` )
* https://3v4l.org/clICI , $numAssertions is not accessible
* https://3v4l.org/4M3if , same for `::shouldInvocationMockerBeReset()` 
* https://3v4l.org/g1JMu , this workaround feels a bit brutal
