### ISSUE TITLE
Option --testdox doesn't allow an argument

### ISSUE THREAD

**Issue by VincentLanglet** [sebastianbergmann/phpunit#4348]
If the phpunit.xml has the `textdox: false` value, I can still use it thanks to the argument `--testdox`.

But if the phpunit.xml has the `textdox: true` value, I cannot disable it with `--testdox=false`.
Indeed, I get
```
option --testdox doesn't allow an argument
```

For boolean configuration, allowing true/false argument could be nice.

**Comment by epdenouden** [comment]
Hi @VincentLanglet , thanks for your suggestion.

The lack of override for config file toggles is something I'd like to see improved, too.

This is already in the upcoming Testdox output buffering change, which offers explicit enable/disable cli flags.

**Comment by sebastianbergmann** [comment]
I am sorry, but I do not want boolean flags for CLI options.

**Comment by cGuille** [comment]
Hello!

Is there a way to override the `testdox="true"` configuration option using a CLI flag?

Because with the default configuration, you can still enable testdox for a single run using `--testdox`, but I cannot find a flag to enable the default output when another one is configured.
