### ISSUE TITLE
Static and non-static method on TestCase class.

### ISSUE THREAD

**Issue by Marcin-TA** [sebastianbergmann/phpunit#4349]
Hi!

I integrated Phinx library into a project I work on. It's the lib to help with database migrations and seeding. I created a class with `TestDatabase` which extends `TestCase`. I set up DB con and run migration and seeds from `TestDatabase` class. However, I noticed that setUp/tearDown methods are non-static when setUpBeforeClass/tearDownAfterClass are static. In that case, I can't run any of the methods from my `TestDatabase` class. Any idea why these two methods are static when rest are not? How to work around that issue?

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.
