### ISSUE TITLE
Element 'filter': This element is not expected

### ISSUE THREAD

**Issue by jamielsharief** [sebastianbergmann/phpunit#4361]
I am just upgrading to PHPUnit 9 and its throwing an error, it works on older versions of PHPUnit and i did not see any deprecation notice. The PHPUnit manual says this is how to do it. So i am a little bit confused.

```
PHPUnit 9.3-g58bf4a0 by Sebastian Bergmann and contributors.

  Warning - The configuration file did not pass validation!
  The following problems have been detected:

  Line 27:
  - Element 'filter': This element is not expected.

  Test results may not be as expected.
```

This is the XML which is under `phpunit` node. 

```
    </listeners>
    <filter> <!-- line 27 -->
        <whitelist>
            <directory suffix=".php">app/</directory>
        </whitelist>
    </filter>
</phpunit>
```

**Comment by jamielsharief** [comment]
Note i add the `<!-- line 27 -->` after to make it clear which line the error is caused on.

**Comment by sebastianbergmann** [comment]
PHPUnit 9.3 has not been released yet. It will still process the old `<filter><whitelist>` format but will warn about it since it is deprecated. This change is documented in the PHPUnit 9.3 changelog.
