### ISSUE TITLE
Remove tools folders from all packages

### ISSUE THREAD

**Issue by xepozz** [sebastianbergmann/phpunit#4366]
On weak processors the indexing of project may have to long time and needs to more resources.
As I noticed, each dependent package have folder `tools`, that takes over 10 MB.
I suggest remove any `tools` folders from each packages. You can use these tools as a independent package, but not as a standalone file in each package.

![image](https://user-images.githubusercontent.com/6815714/86820807-3a0e5f00-c092-11ea-85f6-4df1ea6b978d.png)

<details><summary>Size of vendor/phpunit</summary>

`ls`
`php-code-coverage  php-file-iterator  php-invoker  php-text-template  php-timer  php-token-stream  phpunit`

`du -sh .`
`288M	.`

`find . -type d -name "tools" -exec rm -rf "{}" +;`

`du -sh`
`157M	.`
**Removed 130 MB (!!!!)**
</details>

<details><summary>Size of vendor/sebastian</summary>

`ls sebastian/`
`code-unit                 diff         global-state       recursion-context    version
code-unit-reverse-lookup  environment  object-enumerator  resource-operations
comparator                exporter     object-reflector   type`

`du -sh sebastian/`
`327M	sebastian/`

`find sebastian/ -type d -name "tools" -exec rm -rf "{}" +;`

`du -sh sebastian/`
`138M	sebastian/`

**Removed 190 MB (!!!!)**
</details>

**Comment by sebastianbergmann** [comment]
You need to configure PhpStorm to ignore the `tools` folder.

**Comment by xepozz** [comment]
It's not for phpstorm only.
1. It's takes extra internet traffic
2. It's takes extra time to download it
4. It's takes more disk space
5. Docker containers are bloat


It's no problem to extract your tools to one package and reuse it. 
Do you have arguments to do it?

**Comment by samdark** [comment]
Can't it be included into .gitattributes?

**Comment by samdark** [comment]
Wait... it's already export-ignored. @xepozz how do you install it?

**Comment by xepozz** [comment]
To reproduce you can try the next snippet
```bash
mkdir -p /tmp/phpunit && cd /tmp/phpunit && echo '{"minimum-stability": "dev"}' > composer.json && composer req phpunit/phpunit -v 2>/dev/null && du -hs vendor/phpunit
```

In other projects I do just `composer install` without any flags. 

I think it's important part, because many developers install dependencies without any flags.

**Comment by samdark** [comment]
That is correct. Majority of developers I know do not use `--prefer-dist` or `--prefer-stable`.

**Comment by xepozz** [comment]
@sebastianbergmann ?

**Comment by sebastianbergmann** [comment]
> I think it's important part, because many developers install dependencies without any flags.

I fail to see why it should be my problem that other people do not use Composer correctly.

I will not change the way I work, sorry.

**Comment by BoShurik** [comment]
@xepozz if you use `"minimum-stability": "dev"` you probably always need `"prefer-stable": true`

```php
mkdir -p /tmp/phpunit && cd /tmp/phpunit && echo '{"minimum-stability": "dev", "prefer-stable": true}' > composer.json && composer req phpunit/phpunit -v 2>/dev/null && du -hs vendor/phpunit
```

**Comment by xepozz** [comment]
> > I think it's important part, because many developers install dependencies without any flags.
> 
> I fail to see why it should be my problem that other people do not use Composer correctly.
> 
> I will not change the way I work, sorry.

The problem not only about using Composer. 
I don't understand the purpose of using copy-pasting instead of reusing the dev dependencies.

**Comment by mvorisek** [comment]
Is there any reason to not move into composer `require-dev`?
