### ISSUE TITLE
Wrong format result.

### ISSUE THREAD

**Issue by rpereira-tae** [sebastianbergmann/phpunit#4367]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.5.8
| PHP version         | 7.4.7
| Installation Method | Composer 
| OS | Ubuntu 18.4

#### Summary

When I try to use `./vendor/bin/phpunit` I get random format response in terminal. It seems that the result is correct but I don't understand why the '.EVm' prints. It only happens when I use phpunit.

#### Current behavior

_PHPUnit 8.5.8 by Sebastian Bergmann and contributors._

_..............EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm_ _.EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm_ _.EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .  63 / 204 ( 30%)_
_EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm_ _.EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm_ _.EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm_ _. 126 / 204 ( 61%)_
_EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm IEVm IEVm_ _IEVm IEVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm IEVm IEVm IEVm IEVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm_ _.EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm_ _. 189 / 204 ( 92%)_
_EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .EVm .                                                 204 /_ _204 (100%)EVm_ 

_Time: 6.65 seconds, Memory: 58.50 MB_

_OK, but incomplete, skipped, or risky tests!_
_Tests: 204, Assertions: 521, Incomplete: 8._

#### How to reproduce

Using `./vendor/bin/phpunit` on terminal

#### Expected behavior

_PHPUnit 8.5.8 by Sebastian Bergmann and contributors._

_...............................................................  63 / 204 ( 30%)_
_............................................................... 126 / 204 ( 61%)_
_..................IIII........IIII............................... 189 / 204 ( 92%)_
_...............                                                 204 /204 (100%)_

_Time: 6.65 seconds, Memory: 58.50 MB_

_OK, but incomplete, skipped, or risky tests!_
_Tests: 204, Assertions: 521, Incomplete: 8._

**Composer Info** 
|Packages|Version|Description
|----------------------------------------|----------|------------------------------------------------------------
|asm89/stack-cors                        |1.3.0     |Cross-origin resource sharing library and stack middleware
|aws/aws-sdk-php                         |3.145.2   |AWS SDK for PHP - Use Amazon Web Services in your PHP project
|brick/math                              |0.8.15    |Arbitrary-precision arithmetic library
|cloudinary/cloudinary_php               |1.17.0    |Cloudinary PHP SDK
|dnoegel/php-xdg-base-dir                |v0.1.1    |implementation of xdg base directory specification for php
|doctrine/inflector                      |2.0.3     |PHP Doctrine Inflector is a small library that can perform string manipulations with regard to upper/lowercase and singular/plural for...
|doctrine/instantiator                   |1.3.1     |A small, lightweight utility to instantiate objects in PHP without invoking their constructors
|doctrine/lexer                          |1.2.1     |PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
|dragonmantank/cron-expression           |v2.3.0    |CRON for PHP: Calculate the next or previous run date and determine if a CRON expression is due
|egulias/email-validator                 |2.1.18    |A library for validating emails against several RFCs
|evenement/evenement                     |v3.0.1    |Événement is a very simple event dispatching library for PHP
|facade/flare-client-php                 |1.3.2     |Send PHP errors to Flare
|facade/ignition                         |2.0.7     |A beautiful error page for Laravel applications.
|facade/ignition-contracts               |1.0.0     |Solution contracts for Ignition
|fideloper/proxy                         |4.4.0     |Set trusted proxies for Laravel
|filp/whoops                             |2.7.3     |php error handling for cool kids
|fruitcake/laravel-cors                  |v1.0.6    |Adds CORS (Cross-Origin Resource Sharing) headers support in your Laravel application
|fzaninotto/faker                        |v1.9.1    |Faker is a PHP library that generates fake data for you.
|guzzlehttp/guzzle                       |6.5.5     |Guzzle is a PHP HTTP client library
|guzzlehttp/promises                     |v1.3.1    |Guzzle promises library
|guzzlehttp/psr7                         |1.6.1     |PSR-7 message implementation that also provides common utility methods
|hamcrest/hamcrest-php                   |v2.0.0    |This is the PHP port of Hamcrest Matchers
|hollodotme/fast-cgi-client              |v3.1.2    |A PHP fast CGI client to send requests (a)synchronously to PHP-FPM.
|laravel/framework                       |v7.19.0   |The Laravel Framework.
|laravel/sanctum                         |v2.4.2    |Laravel Sanctum provides a featherweight authentication system for SPAs and simple APIs.
|laravel/tinker                          |v2.4.1    |Powerful REPL for the Laravel framework.
|laravel/vapor-cli                       |v1.7.0    |The Laravel Vapor CLI
|laravel/vapor-core                      |v2.8.0    |The kernel and invokation handlers for Laravel Vapor
|league/climate                          |3.5.2     |PHP's best friend for the terminal. CLImate allows you to easily output colored text, special formats, and more.
|league/commonmark                       |1.5.1     |Highly-extensible PHP Markdown parser which fully supports the CommonMark spec and Github-Flavored Markdown (GFM)
|league/flysystem                        |1.0.69    |Filesystem abstraction: Many filesystems, one API.
|league/flysystem-aws-s3-v3              |1.0.25    |Flysystem adapter for the AWS S3 SDK v3.x
|mockery/mockery                         |1.4.0     |Mockery is a simple yet flexible PHP mock object framework
|monolog/monolog                         |2.1.0     |Sends your logs to files, sockets, inboxes, databases and various web services
|mtdowling/jmespath.php                  |2.5.0     |Declaratively specify how to extract elements from a JSON document
|myclabs/deep-copy                       |1.10.1    |Create deep copies (clones) of your objects
|nesbot/carbon                           |2.36.1    |An API extension for DateTime that supports 281 different languages.
|nikic/php-parser                        |v4.6.0    |A PHP parser written in PHP
|nunomaduro/collision                    |v4.2.0    |Cli error handling for console/command-line PHP applications.
|nyholm/psr7                             |1.3.0     |A fast PHP7 implementation of PSR-7
|opis/closure                            |3.5.5     |A library that can be used to serialize closures (anonymous functions) and arbitrary objects.
|phar-io/manifest                        |1.0.3     |Component for reading phar.io manifest information from a PHP Archive (PHAR)
|phar-io/version                         |2.0.1     |Library for handling version information and constraints
|phpdocumentor/reflection-common         |2.2.0     |Common reflection classes used by phpdocumentor to reflect the code structure
|phpdocumentor/reflection-docblock       |5.1.0     |With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in...
|phpdocumentor/type-resolver             |1.3.0     |A PSR-5 based resolver of Class names, Types and Structural Element Names
|php-http/message-factory                |v1.0.2    |Factory interfaces for PSR-7 HTTP Message
|phpoption/phpoption                     |1.7.4     |Option Type for PHP
|phpspec/prophecy                        |1.11.0    |Highly opinionated mocking framework for PHP 5.3+
|phpunit/php-code-coverage               |7.0.10    |Library that provides collection, processing, and rendering functionality for PHP code coverage information.
|phpunit/php-file-iterator               |2.0.2     |FilterIterator implementation that filters files based on a list of suffixes.
|phpunit/php-text-template               |1.2.1     |Simple template engine.
|phpunit/php-timer                       |2.1.2     |Utility class for timing
|phpunit/php-token-stream                |3.1.1     |Wrapper around PHP's tokenizer extension.
|phpunit/phpunit                         |8.5.8     |The PHP Unit Testing framework.
|psr/container                           |1.0.0     |Common Container Interface (PHP FIG PSR-11)
|psr/event-dispatcher                    |1.0.0     |Standard interfaces for event handling.
|psr/http-factory                        |1.0.1     |Common interfaces for PSR-7 HTTP message factories
|psr/http-message                        |1.0.1     |Common interface for HTTP messages
|psr/log                                 |1.1.3     |Common interface for logging libraries
|psr/simple-cache                        |1.0.1     |Common interfaces for simple caching
|psy/psysh                               |v0.10.4   |An interactive shell for modern PHP.
|ralouphie/getallheaders                 |3.0.3     |A polyfill for getallheaders.
|ramsey/collection                       |1.0.1     |A PHP 7.2+ library for representing and manipulating collections.
|ramsey/uuid                             |4.0.1     |A PHP library for generating and working with universally unique identifiers (UUIDs).
|react/child-process                     |v0.6.1    |Event-driven library for executing child processes with ReactPHP.
|react/event-loop                        |v1.1.1    |ReactPHP's core reactor event loop that libraries can use for evented I/O.
|react/promise                           |v2.8.0    |A lightweight implementation of CommonJS Promises/A for PHP
|react/stream                            |v1.1.1    |Event-driven readable and writable streams for non-blocking I/O in ReactPHP
|riverline/multipart-parser              |2.0.8     |One class library to parse multipart content with encoding and charset support.
|scrivo/highlight.php                    |v9.18.1.1 |Server side syntax highlighter that supports 185 languages. It's a PHP port of highlight.js
|sebastian/code-unit-reverse-lookup      |1.0.1     |Looks up which function or method a line of code belongs to
|sebastian/comparator                    |3.0.2     |Provides the functionality to compare PHP values for equality
|sebastian/diff                          |3.0.2     |Diff implementation
|sebastian/environment                   |4.2.3     |Provides functionality to handle HHVM/PHP environments
|sebastian/exporter                      |3.1.2     |Provides the functionality to export PHP variables for visualization
|sebastian/global-state                  |3.0.0     |Snapshotting of global state
|sebastian/object-enumerator             |3.0.3     |Traverses array structures and object graphs to enumerate all referenced objects
|sebastian/object-reflector              |1.1.1     |Allows reflection of object attributes, including inherited and non-public ones
|sebastian/recursion-context             |3.0.0     |Provides functionality to recursively process PHP variables
|sebastian/resource-operations           |2.0.1     |Provides a list of PHP built-in functions that operate on resources
|sebastian/type                          |1.1.3     |Collection of value objects that represent the types of the PHP type system
|sebastian/version                       |2.0.1     |Library that helps with managing the version number of Git-hosted PHP projects
|seld/cli-prompt                         |1.0.3     |Allows you to prompt for user input on the command line, and optionally hide the characters they type
|spatie/laravel-collection-macros        |6.1.0     |A set of useful Laravel collection macros
|spatie/laravel-json-api-paginate        |1.7.0     |A paginator that plays nice with the JSON API spec
|spatie/laravel-query-builder            |2.8.2     |Easily build Eloquent queries from API requests
|swiftmailer/swiftmailer                 |v6.2.3    |Swiftmailer, free feature-rich PHP mailer
|symfony/console                         |v5.1.2    |Symfony Console Component
|symfony/css-selector                    |v5.1.2    |Symfony CssSelector Component
|symfony/deprecation-contracts           |v2.1.3    |A generic function and convention to trigger deprecation notices
|symfony/error-handler                   |v5.1.2    |Symfony ErrorHandler Component
|symfony/event-dispatcher-contracts      |v2.1.3    |Generic abstractions related to dispatching event
|symfony/event-dispatcher                |v5.1.2    |Symfony EventDispatcher Component
|symfony/finder                          |v5.1.2    |Symfony Finder Component
|symfony/http-foundation                 |v5.1.2    |Symfony HttpFoundation Component
|symfony/http-kernel                     |v5.1.2    |Symfony HttpKernel Component
|symfony/mime                            |v5.1.2    |A library to manipulate MIME messages
|symfony/polyfill-ctype                  |v1.17.1   |Symfony polyfill for ctype functions
|symfony/polyfill-iconv                  |v1.17.1   |Symfony polyfill for the Iconv extension
|symfony/polyfill-intl-grapheme          |v1.17.1   |Symfony polyfill for intl's grapheme_* functions
|symfony/polyfill-intl-idn               |v1.17.1   |Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
|symfony/polyfill-intl-normalizer        |v1.17.1   |Symfony polyfill for intl's Normalizer class and related functions
|symfony/polyfill-mbstring               |v1.17.1   |Symfony polyfill for the Mbstring extension
|symfony/polyfill-php72                  |v1.17.0   |Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
|symfony/polyfill-php73                  |v1.17.1   |Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
|symfony/polyfill-php80                  |v1.17.1   |Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
|symfony/process                         |v5.1.2    |Symfony Process Component
|symfony/psr-http-message-bridge         |v2.0.1    |PSR HTTP message bridge
|symfony/routing                         |v5.1.2    |Symfony Routing Component
|symfony/service-contracts               |v2.1.3    |Generic abstractions related to writing services
|symfony/string                          |v5.1.2    |Symfony String component
|symfony/translation-contracts           |v2.1.3    |Generic abstractions related to translation
|symfony/translation                     |v5.1.2    |Symfony Translation Component
|symfony/var-dumper                      |v5.1.2    |Symfony mechanism for exploring and dumping PHP variables
|symfony/yaml                            |v5.1.2    |Symfony Yaml Component
|theseer/tokenizer                       |1.1.3     |A small library for converting tokenized PHP source code into XML and potentially other formats
|tijsverkoyen/css-to-inline-styles       |2.2.2     |CssToInlineStyles is a class that enables you to convert HTML-pages/files into HTML-pages/files with inline styles. This is very usefu...
|vlucas/phpdotenv                        |v4.1.7    |Loads environment variables from `.env` to `getenv()`, `$_ENV` and `$_SERVER` automagically.
|voku/portable-ascii                     |1.5.2     |Portable ASCII library - performance optimized (ascii) string functions for php.
|wackystudio/laravel-test-watcher        |1.0.13    |A test file watcher for Laravel that automatically runs specific test cases based on a @watch annotation
|webmozart/assert                        |1.9.0     |Assertions to validate method input/output with nice error messages.
|wyrihaximus/react-child-process-promise |2.0.2     |Wrapping ticks into a promise
|wyrihaximus/ticking-promise             |1.6.3     |Wrapping ticks into a promise
|yosymfony/resource-watcher              |v2.0.1    |A simple resource watcher using Symfony Finder

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by rpereira-tae** [comment]
I managed to fix it, not in the cleanest way but it worked. I am on a project using Laravel, I deleted the project locally, cloned the repository again, used `composer install` and tried again with `./vendor/bin/phpunit` . 

Thank you very much for answering!! @sebastianbergmann
