### ISSUE TITLE
Logic in MockMethod.php wrong for PHP 8's ReflectionUnionType

### ISSUE THREAD

**Issue by ondrejmirtes** [sebastianbergmann/phpunit#4370]
Hi, I ran [PHPStan](https://phpstan.org) on PHPUnit's codebase and it yielded this error:

```
 ------ ------------------------------------------------------------------------------------------------ 
  Line   src/Framework/MockObject/MockMethod.php                                                         
 ------ ------------------------------------------------------------------------------------------------                                           
  377    Strict comparison using === between ReflectionType and 'self' 
```

The offending line is here: https://github.com/sebastianbergmann/phpunit/blob/4d850e3af4859b0a37f183b343bac3b371bac9d1/src/Framework/MockObject/MockMethod.php#L372-L386

In PHP you cannot compare an object with string using `===` even if the object has `__toString` method:

* https://3v4l.org/UltD2
* Demonstration of the logic with ReflectionUnionType: https://3v4l.org/Bgshq

I suspect this line of code isn't actually tested.

**Comment by sebastianbergmann** [comment]
The method is tested: 
![Screenshot from 2020-07-09 11-13-57](https://user-images.githubusercontent.com/25218/87021559-aa71c900-c1d5-11ea-954f-2e81f3124e90.png)

But the `true` case for `$type === 'self'` is not tested. I'll have a look, thank you for bringing this to my attention.

**Comment by ondrejmirtes** [comment]
Cool, glad to help 😊
