### ISSUE TITLE
PHPUnit\Framework\Exception: Fatal error: Uncaught Error: Class 'SebastianBergmann\CodeCoverage\CodeCoverage' not found

### ISSUE THREAD

**Issue by drewblin** [sebastianbergmann/phpunit#4375]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.4.3
| PHP version         | 7.4.1
| Installation Method | PHAR

#### Summary

When i run phpunit with @covers and @runTestsInSeparateProcesses annotations i run into exception

#### Current behavior

PHPUnit\Framework\Exception: Fatal error: Uncaught Error: Class 'SebastianBergmann\CodeCoverage\CodeCoverage' not found in Standard input code on line 302

#### How to reproduce

run
```sh
/usr/local/bin/php -dxdebug.var_display_max_depth=3 -dxdebug.coverage_enable=1 /usr/local/bin/phpunit --coverage-clover /usr/home/drewblin/cover_xml --configuration /usr/home/drewblin/phpunit.xml /usr/home/drewblin/1.php
```

Both 1.php and phpunit.xml attached

#### Expected behavior

No exception

[files.zip](https://github.com/sebastianbergmann/phpunit/files/4908363/files.zip)

**Comment by sebastianbergmann** [comment]
PHPUnit 8.4.3 is not supported anymore. Can you reproduce the issue with the latest version of PHPUnit 8.5 or PHPUnit 9.2?

**Comment by drewblin** [comment]
There is no problems on 9.2.
I'm sorry to trouble you
