### ISSUE TITLE
Undefined variable $rootDir when using separate process

### ISSUE THREAD

**Issue by enumag** [sebastianbergmann/phpunit#4377]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.2.5
| PHP version         | 7.4.7
| Installation Method | Composer

#### Summary

When I use PHPUnit's feature to run some tests in separate process, I started to get an undefined variable error. There was no stacktrace so it was quite difficult to nail down the exact place.

It turned out to be [this line](https://github.com/dompdf/dompdf/blob/6782abfc090b132134cd6cea0ec6d76f0fce2c56/lib/fonts/dompdf_font_family_cache.dist.php#L2) in the DomPDF. This file is supposed to be included only in [certain scope](https://github.com/dompdf/dompdf/blob/6782abfc090b132134cd6cea0ec6d76f0fce2c56/src/FontMetrics.php#L132) where the variable is declared. PHPUnit however seems to include it in a global scope which of course causes the error. How can I avoid this?

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by enumag** [comment]
`@preserveGlobalState disabled` seems to have fixed the issue for me.
