### ISSUE TITLE
PHPUnit\Util\Test::parseTestMethodAnnotations() handles a lot of exceptions

### ISSUE THREAD

**Issue by joshua-bn** [sebastianbergmann/phpunit#4379]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.5.8
| PHP version         | 7.4.7
| Installation Method | Composer

#### Summary

While trying to diagnose an issue with my tests I have run Xdebug. It keeps stopping on an exception that is thrown in `PHPUnit\Util\Annotation\Registry::forMethod()` because forMethod is passed an empty string and ReflectionMethod() can't find `MyClassName::()`

#### Current behavior

This throws a lot of exceptions that are caught. We can improve that.

#### How to reproduce

Call `PHPUnit\Util\Test::parseTestMethodAnnotations()` without a second argument

#### Expected behavior

Don't allow an empty string to be passed to `PHPUnit\Util\Annotation\Registry::forMethod()`. `if ($methodName !== null) {` on line 308 should be `if (!empty($methodName)) {`.

**Comment by joshua-bn** [comment]
Sorry, this is an enhancement and not really a bug.

**Comment by joshuaadickerson** [comment]
@sebastianbergmann just wondering why it was closed. 

Thank you for all that you do.

**Comment by vemod** [comment]
This is a bug, 
```
public static function parseTestMethodAnnotations(string $className, ?string $methodName = '') : array
    {
        $registry = Registry::getInstance();
        if ($methodName !== null) {
            try {
                return ['method' => $registry->forMethod($className, $methodName)->symbolAnnotations(), 'class' => $registry->forClassName($className)->symbolAnnotations()];
            } catch (\PHPUnit\Util\Exception $methodNotFound) {
                // ignored
            }
        }
        return ['method' => null, 'class' => $registry->forClassName($className)->symbolAnnotations()];
    }
```

`method = ''` is not a valid default value

either default value should be null or `if` statement should be `!empty($methodName)`. 
Throwing 
```
PHP ReflectionException:  Method MyTest::() does not exist in phar:///home/davava/bin/phpunit-9.5.phar/phpunit/Util/Annotation/Registry.php on line 70
```
is not a valid workflow. 

Please reopen.
Thanks a lot in advance
