### ISSUE TITLE
Syntax error on Code Coverage

### ISSUE THREAD

**Issue by npbtrac** [sebastianbergmann/phpunit#4381]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.2.6
| PHP version         | 7.2.19
| Installation Method | Composer / PHAR

#### Summary
Syntax error
```
PHP Parse error:  syntax error, unexpected ')' in ./vendor/phpunit/php-code-coverage/src/Report/Text.php on line 131
```

#### Current behavior
- Failed to execute code-coverage

#### How to reproduce
- Run codeception with code-coverage `./vendor/bin/codecept run --coverage`

**Comment by sebastianbergmann** [comment]
PHPUnit 9 is not supported on PHP 7.2.
