### ISSUE TITLE
"Type mixed cannot be marked as nullable since mixed already includes null" when Mocking reflection class with PHP 8

### ISSUE THREAD

**Issue by greg0ire** [sebastianbergmann/phpunit#4393]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.2.6
| PHP version         | PHP 8.0.0-dev (cli) (built: Jul 30 2020 05:19:37) ( ZTS )
| Installation Method | Composer

#### Summary

```php
$class = $this->getMockBuilder(ReflectionClass::class)
                ->disableOriginalConstructor()
                          ->getMock();
```
crashes.

It seems to come from this `eval()`:

https://github.com/sebastianbergmann/phpunit/blob/9e202b52bc63ddca3d86c374b2f6c726561d9cbb/src/Framework/MockObject/MockClass.php#L45

I don't know where PHPunit gets `mixed|null` from, as it does not appear here: https://3v4l.org/OBYYO

#### Current behavior

PHP Fatal error:  Type mixed cannot be marked as nullable since mixed already includes null in /home/travis/build/doctrine/annotations/vendor/phpunit/phpunit/src/Framework/MockObject/MockClass.php(42) : eval()'d code on line 756

#### How to reproduce

```
git clone git@github.com:doctrine/annotations.git
composer update -v
vendor/bin/phpunit
```

or just use the code sample above.

#### Expected behavior

No errors

**Comment by sebastianbergmann** [comment]
PHPUnit 9.2 is not compatible with PHP 8 and will not be made compatible with PHP 8. Please test with PHPUnit 9.3.

**Comment by sebastianbergmann** [comment]
> ```
> git clone git@github.com:doctrine/annotations.git
> composer update -v
> vendor/bin/phpunit
> ```

That repository has `"phpunit/phpunit": "^7.5"` in its `composer.json` on `master`.

**Comment by greg0ire** [comment]
> That repository has "phpunit/phpunit": "^7.5" in its composer.json on master.

My bad, I just merged https://github.com/doctrine/annotations/pull/342 to allow 9.1 .

1.10.x is the default branch, so that's what you should be on after cloning unless maybe there is some special configuration that states otherwise.

> Please test with PHPUnit 9.3.

Doing so at https://github.com/doctrine/annotations/pull/343

**Comment by greg0ire** [comment]
>     Please test with PHPUnit 9.3.

That fixed the issue, thanks for pointing this out :slightly_smiling_face: 

We are fooling composer into thinking this is PHP 7.4, that's why it still allowed installing 9.1.

Thanks again and sorry for the noise.
