### ISSUE TITLE
Imports of externalized data providers are not supported - FQNs only

### ISSUE THREAD

**Issue by codekandis** [sebastianbergmann/phpunit#4394]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.2.6
| PHP version         | 7.4.6
| Installation Method | Composer (Packagist)

#### Summary

To increase the readabilty of my test cases I externalized my data providers. PHPUnit supports the invocation of externalized data providers but with their FQN only. Imports are not supported - the data providers cannot be found.

#### Current behavior

Data provider
```php
<?php declare( strict_types = 1 );
namespace Vendor\Project\Tests\DataProviders;

use Vendor\Project\FooBarInterfaceImplementation;

abstract class FooBarInterfaceTestDataProvider
{
	public static function provider(): array
	{
		return [
			0 => [
				'instance'      => new FooBarInterfaceImplementation(),
				'expectedValue' => 'foobar'
			]
		];
	}
}
```

Working test case
```php
<?php declare( strict_types = 1 );
namespace Vendor\Project\Tests\Units;

use Vendor\Project\FooBarInterface;
use PHPUnit\Framework\TestCase;

class FooBarInterfaceTest extends TestCase
{
	/**
	 * @dataProvider Vendor\Project\Tests\DataProviders\FooBarInterfaceTestDataProvider::provider()
	 */
	public function test__toStringReturnsClassName( FooBarInterface $instance, string $expectedValue ): void
	{
		static::assertSame( $expectedValue, 'foobar' );
	}
}
```

Failing test case
```php
<?php declare( strict_types = 1 );
namespace Vendor\Project\Tests\Units;

use Vendor\Project\FooBarInterface;
use Vendor\Project\Tests\DataProviders\FooBarInterfaceTestDataProvider;
use PHPUnit\Framework\TestCase;

class FooBarInterfaceTest extends TestCase
{
	/**
	 * @dataProvider FooBarInterfaceTestDataProvider::provider()
	 */
	public function test__toStringReturnsClassName( FooBarInterface $instance, string $expectedValue ): void
	{
		static::assertSame( $expectedValue, 'foobar' );
	}
}
```

#### Expected behavior

Data providers are invoked without FQNs and respecting imports.

**Comment by sebastianbergmann** [comment]
This is not a bug but rather expected behaviour due to limitations of how annotations work. What you desire will be possible with PHP 8 and its attributes syntax once PHPUnit has support for it.

**Comment by codekandis** [comment]
Acknowledged. Thx.

Yes, indeed ... the Attribute Syntax is my personal favorite. So looking forward ...
