### ISSUE TITLE
Add CLI flag to generate only one type of CC & Logging regardless of phpunit.xml

### ISSUE THREAD

**Issue by Slamdunk** [sebastianbergmann/phpunit#4401]
Hi, I'm the current maintainer of https://github.com/paratestphp/paratest, a tool to run PHPUnit in parallel, leveraging sub-processes.

A feature we must provide is to generate code-coverage and logging accordingly to `phpunit.xml` specifications.

Our tool should:

1. Read `phpunit.xml` `<filter/coverage>` and `<logging>` sections, which may all set to all the available configurations
1. Disable all of them during ParaTest process
1. Enable **only** `coverage-php` and `log-junit` into PHPUnit sub-processes
1. Wait for sub-processes to finish and to generate the only two cc+log above
1. Merge everything together within ParaTest process
1. Generate the desired cc/logs respecting again `phpunit.xml` `<filter/coverage>` and `<logging>` sections

As of yet this can't be done because if `<filter/coverage>` and `<logging>` sections are specified in `phpunit.xml`, cc and logs are always generated except with `--no-coverage`/`--no-logging` active, but with `--no-coverage`/`--no-logging` active no cc nor logs are generated at all.

The workaround we are using right now is suggesting *not* to have any section in `phpunit.xml` except the `<whitelist>` one, and specify each option in the CLI, so ParaTest can easily rewrite them as wish, but of course this is sub-optimal.

So I'm asking something like `vendor/bin/phpunit --no-coverage --coverage-php tmp.php --no-logging --log-junit tmp.log`.

If you so kind to  write down few instructions to how and where implement such feature, I'm happy to propose a PR.

**Comment by sebastianbergmann** [comment]
> `vendor/bin/phpunit --no-coverage --coverage-php tmp.php --no-logging --log-junit tmp.log`

The above makes sense to me and I will implement this for PHPUnit 9.4.

**Comment by Slamdunk** [comment]
Ping @Jean85 as this may help your https://github.com/facile-it/paraunit too

**Comment by Jean85** [comment]
Thanks for the ping but I follow a different approach, without altering the original XML config; I only use CLI options.

**Comment by sebastianbergmann** [comment]
As I mentioned [here](https://github.com/infection/infection/issues/1283#issuecomment-670330697): IMO, XML configuration manipulation should be avoided by tools that wrap PHPUnit. Please let me know, as @Slamdunk did with this ticket, if you are missing CLI options.

**Comment by Slamdunk** [comment]
> Thanks for the ping but I follow a different approach, without altering the original XML config; I only use CLI options.

This is going OT, by the way we don't manipulate anything. @Jean85 if you run `phpunit` bare binary in a sub-processes, it will generate any cc/log written in `phpunit.xml`, (currently) regardless if you add more or less options, except for `--no-*` ones.

**Comment by sebastianbergmann** [comment]
@Slamdunk Thank you for the clarification!

**Comment by sebastianbergmann** [comment]
I think this should be done after #4292.

**Comment by sebastianbergmann** [comment]
Supersed by #4446.
