### ISSUE TITLE
assertEquals doesn't respect MAX_FLOAT_DIFF

### ISSUE THREAD

**Issue by TeBoring** [sebastianbergmann/phpunit#4408]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.3.2
| PHP version         | 8.0.0-alpha-1
| Installation Method | PHAR

**Provide a summary describing the problem you are experiencing.** 

assertEquals doesn't respect MAX_FLOAT_DIFF

**What is the current (buggy) behavior?**
MAX_FLOAT_DIFF = 0.000001;
$this->assertEquals(1.1, 1.100000023841858, '', MAX_FLOAT_DIFF);
Failed asserting that 1.100000023841858 matches expected 1.1.

**Provide steps to reproduce the bug.**

Same as above

**What was the expected (correct) behavior?**
No error

**Comment by sebastianbergmann** [comment]
The signature of `assertEquals()` is `assertEquals($expected, $actual, string $message = '')`. There is no fourth parameter. You are probably looking for `assertEqualsWithDelta()`.
