### ISSUE TITLE
Uncaught Error: Class 'PhpParser\Parser\Php7' not found...

### ISSUE THREAD

**Issue by ColonelBlimp** [sebastianbergmann/phpunit#4410]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.3.3
| PHP version         | 7.4.9
| Installation Method | Composer

#### Summary

Error when using code coverage.

#### Current behavior

Fails to run tests with error:

     [exec] PHP Fatal error:  Uncaught Error: Class 'PhpParser\Parser\Php7' not found in C:\Users\####\Documents\####\####\vendor\nikic\php-parser\lib\PhpParser\ParserFactory.php:28

     [exec] Stack trace:

     [exec] #0 C:\Users\####\Documents\####\####\vendor\phpunit\php-code-coverage\src\StaticAnalysis\IgnoredLinesFinder.php(111): PhpParser\ParserFactory->create()

     [exec] #1 C:\Users\#####\Documents\####\####\vendor\phpunit\php-code-coverage\src\StaticAnalysis\IgnoredLinesFinder.php(46): SebastianBergmann\CodeCoverage\StaticAnalysis\IgnoredLinesFinder->findLinesIgnoredByDocBlockAnnotations()

     [exec] #2 C:\Users\####\Documents\####\####\vendor\phpunit\php-code-coverage\src\CodeCoverage.php(460): SebastianBergmann\CodeCoverage\StaticAnalysis\IgnoredLinesFinder->findIgnoredLinesInFile()

     [exec] #3 C:\Users\####\Documents\####\####\vendor\phpunit\php-code-coverage\src\CodeCoverage.php(254): SebastianBergmann\CodeCoverage\CodeCoverage->applyIgnoredLinesFilter()

     [exec] #4 C:\Users\####\Documents\####\####\vendor\ in C:\Users\####\Documents\####\####\vendor\phpunit\phpunit\src\TextUI\Command.php on line 98

#### How to reproduce
```
  <coverage includeUncoveredFiles="true"
          processUncoveredFiles="true"
          pathCoverage="false"
          ignoreDeprecatedCodeUnits="true"
          disableCodeCoverageIgnore="false">
    <include>
      <directory suffix=".php">system</directory>
    </include>
    <report>
      <clover outputFile="./build/logs/clover.xml"/>
      <html outputDirectory="./build/coverage" lowUpperBound="50" highLowerBound="80"/>
    </report>
  </coverage>
```
Comment out the above, and the tests are executed just fine.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by ColonelBlimp** [comment]
I was unable to reproduce in a **minimal, self-contained, reproducing test case**.  So, I deleted the content of the _vendor_ folder, and deleted the _composer.lock_ file and reinstalled every dependency - all is working again.
