### ISSUE TITLE
Question about undefined constants when defined in bootstrap.phpunit.php

### ISSUE THREAD

**Issue by lamtranb** [sebastianbergmann/phpunit#4413]
Hi everyone,

I defined some constants in bootstrap.phpunit.php
`define('PHPFOX', true);`

And in per test, I used like this but it return false
`public function testFormInThreadFloodError(): void
    {
        var_dump(defined(PHPFOX));
    }`

This is my phpunit.xml settings.

<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/5.7/phpunit.xsd"
         bootstrap="bootstrap.phpunit.php"
         backupGlobals="true"
         beStrictAboutCoversAnnotation="true"
         beStrictAboutOutputDuringTests="true"
         beStrictAboutTestsThatDoNotTestAnything="true"
         beStrictAboutTodoAnnotatedTests="true"
         verbose="true"
         colors="true"
         stopOnFailure="true"
         stopOnError="true"
         stderr="true"
         testdox="true"
         processIsolation="false"
>

My environment:
PHP 7.4
PHPUnit 9.2

Anyone know about this issue and how to fix it? Many thanks.

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.
