### ISSUE TITLE
Migration failed: whitelist element has unexpected children

### ISSUE THREAD

**Issue by emodric** [sebastianbergmann/phpunit#4419]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.3.5
| PHP version         | 7.4.9
| Installation Method | Composer

#### Summary

Running `vendor/bin/phpunit --migrate-configuration` results in a `Migration failed` message with the following XML file which is valid on PHPUnit 9.2:

```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.2/phpunit.xsd"
>
    <filter>
        <whitelist>
            <directory suffix=".php">lib</directory>
            <exclude>
                <file>bundles/MyBundle/MyBundle.php</file>
            </exclude>
            <exclude>
                <directory>bundles/*Bundle/Controller</directory>
            </exclude>
        </whitelist>
    </filter>
</phpunit>
```

#### Current behavior

Migration fails. Additionaly, no detailed error message is given when it happens. I tried using `vendor/bin/phpunit --migrate-configuration -v` but it didn't help.

#### How to reproduce

Run the migration command with the above XML config.

#### Expected behavior

I expect the migration to complete.

**Comment by theseer** [comment]
Makes sense: The `MoveWhitelistExcludesToCoverage` Migration does not expect there to be more than one `<exclude>` node.

Is that valid? If so, I'd have to update the Migration to deal with it. If not, the XSD should complain about it.

**Comment by longwave** [comment]
Similarly Drupal uses this filter config, which fails to migrate:

```
  <filter>
    <whitelist>
      <directory>./includes</directory>
      <directory>./lib</directory>
      <!-- Extensions can have their own test directories, so exclude those. -->
      <directory>./modules</directory>
      <exclude>
        <directory>./modules/*/src/Tests</directory>
        <directory>./modules/*/tests</directory>
      </exclude>
      <directory>../modules</directory>
      <exclude>
        <directory>../modules/*/src/Tests</directory>
        <directory>../modules/*/tests</directory>
        <directory>../modules/*/*/src/Tests</directory>
        <directory>../modules/*/*/tests</directory>
      </exclude>
      <directory>../sites</directory>
     </whitelist>
  </filter>
```

It might also be useful if "Migration failed" included the exception message as this can give a hint as to what went wrong.

**Comment by theseer** [comment]
Same reason though: there are multiple `<exclude>` nodes in `<whitelist>` container. The Migration code does not support that.

Question remains for @sebastianbergmann: __Is that valid?__

**Comment by sebastianbergmann** [comment]
> Is that valid?

Apparently it is supported, although I would consider this to be "unintentionally supported".

**Comment by theseer** [comment]
At least the XPATH used in the [XMLoader](https://github.com/sebastianbergmann/phpunit/blob/8c908255db023c3861a8f3adc2cad1ed61dc4690/src/TextUI/XmlConfiguration/Loader.php#L659) (silently) supports that. So that means the migration code should support it as well.

Do we want to keep this or should the Migrator merge the contents of the `<exclude>` nodes?

**Comment by sebastianbergmann** [comment]
> Do we want to keep this or should the Migrator merge the contents of the `<exclude>` nodes?

We should merge into a single `<exclude>` node.

**Comment by sebastianbergmann** [comment]
Cherry-picked into `9.3`.
