### ISSUE TITLE
symbolicly linked phpunit.xml is not handled properly

### ISSUE THREAD

**Issue by arderyp** [sebastianbergmann/phpunit#4428]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.5.20
| PHP version         | 7.4.9
| Installation Method | Composer

```
$ composer info | sort | grep phpunit
symfony/phpunit-bridge               v5.1.3  Symfony PHPUnit Bridge

$ bin/simple-phpunit --version
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.
```

#### Summary

When phpunit.xml is a symbolic link, phpunit follows the link to the source, and tries to execute from the source location.

#### Current behavior

Below is the file structure.

```
/
    var/
        www/
            shared/
                phpunit.xml
            repo/
                phpunit.xml -> /var/www/shared/phpunit.xml
```

This is a common structure used by many deployment systems, including [PHP Deployer](https://deployer.org/). When trying to execute phpunit from `/var/www/repo`, it fails because it looks for `/var/www/shared/vendor/autoload.php` instead of `/var/www/repo/vendor/autoload.php`.  The problem is resolved by swapping the real file in for the symbolic link:

```
rm /var/www/repo/phpunit.xml
cp /var/www/shared/phpunit.xml /var/www/repo/phpunit.xml
```

#### How to reproduce

Within a project you already have with phpunit setup and working properly, simply move the `phpunit.xml` file somewhere else, and replace the original with a link to the new location, then run tests how your normally would.

#### Expected behavior

Execute phpunit from location of `phpunit.xml` (even if it is a link).  Just trust the found location of `phpunit.xml`, and don't follow to its target location if it is link.

**Comment by sebastianbergmann** [comment]
PHPUnit 7.5 is not supported anymore.

**Comment by arderyp** [comment]
I will try to test on phpunit 8 and report back.  I'm nearly certian this affects all versions of phpunit.

**Comment by arderyp** [comment]
I just confirmed this affects the defualt version symfony feeds up: `9.3.7`

I have updated the main issue accordingly.

```
## phpunit.xml content, we reference this later in the process
<?xml version="1.0" encoding="UTF-8"?>
<!-- https://phpunit.de/manual/current/en/appendixes.configuration.html -->
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.3/phpunit.xsd" backupGlobals="false" colors="true" bootstrap="vendor/autoload.php">
  <coverage>
    <include>
      <directory>./src/</directory>
    </include>
  </coverage>
  <php>
    <ini force="true" name="error_reporting" value="-1"/>
  </php>
  <testsuites>
    <testsuite name="symbolic link fails demo">
      <directory>tests/</directory>
    </testsuite>
  </testsuites>
</phpunit>


## Reproduce the issue
$ mkdir phpunit

$ mkdir phpunit/shared

$ mkdir phpunit/repo

$ cd phpunit/repo

$ composer init
...

$ composer require phpunit/phpunit
...

# create phpunit.xml using the example block above

$ vendor/bin/phpunit 
PHPUnit 9.3.7 by Sebastian Bergmann and contributors.

No tests executed!

$ mv phpunit.xml ../shared && ln -s ../shared/phpunit.xml .

$ vendor/bin/phpunit 
PHPUnit 9.3.7 by Sebastian Bergmann and contributors.

Cannot open file "/home/arderyp/phpunit/shared/vendor/autoload.php".
```
