### ISSUE TITLE
symbolicly linked phpunit.xml is not handled properly

### ISSUE THREAD

**Issue by arderyp** [sebastianbergmann/phpunit#4430]
ORIGINAL ISSUE WAS CLOSED: https://github.com/sebastianbergmann/phpunit/issues/4428

| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.3.7 (tested against 8.5.8 too with same results)
| PHP version         | 7.4.9
| Installation Method | Composer

```
$ composer info | sort | grep phpunit
phpunit/php-code-coverage          9.1.4   Library that provides collection, processing, and rendering functionality for PHP code coverage...
phpunit/php-file-iterator          3.0.4   FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-invoker                3.1.0   Invoke callables with a timeout
phpunit/php-text-template          2.0.2   Simple template engine.
phpunit/php-timer                  5.0.1   Utility class for timing
phpunit/phpunit                    9.3.7   The PHP Unit Testing framework.
```

#### Summary

When phpunit.xml is a symbolic link, phpunit follows the link to the source, and tries to execute from the source location.

#### Current behavior

Below is the file structure.

```
/
    home/
        arderyp/
            phpunit/
                shared/
                    phpunit.xml
                repo/
                    phpunit.xml -> /var/www/shared/phpunit.xml
```

This is a common structure used by many deployment systems, including [PHP Deployer](https://deployer.org/). When trying to execute phpunit from `/var/www/repo`, it fails because it looks for `/var/www/shared/vendor/autoload.php` instead of `/var/www/repo/vendor/autoload.php`.  The problem is resolved by swapping the real file in for the symbolic link:

```
cd /home/arderyp/phpunit/repo
rm phpunit.xml && cp ../shared/phpunit.xml .
```

#### How to reproduce

```
## phpunit.xml content, we reference this later in the process
<?xml version="1.0" encoding="UTF-8"?>
<!-- https://phpunit.de/manual/current/en/appendixes.configuration.html -->
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.3/phpunit.xsd" backupGlobals="false" colors="true" bootstrap="vendor/autoload.php">
  <coverage>
    <include>
      <directory>./src/</directory>
    </include>
  </coverage>
  <php>
    <ini force="true" name="error_reporting" value="-1"/>
  </php>
  <testsuites>
    <testsuite name="symbolic link fails demo">
      <directory>tests/</directory>
    </testsuite>
  </testsuites>
</phpunit>


## Reproduce the issue
$ mkdir phpunit

$ mkdir phpunit/shared

$ mkdir phpunit/repo

$ cd phpunit/repo

$ composer init
...

$ composer require phpunit/phpunit
...

# create phpunit.xml using the example block above

$ vendor/bin/phpunit 
PHPUnit 9.3.7 by Sebastian Bergmann and contributors.

No tests executed!

$ mv phpunit.xml ../shared && ln -s ../shared/phpunit.xml .

$ vendor/bin/phpunit 
PHPUnit 9.3.7 by Sebastian Bergmann and contributors.

Cannot open file "/home/arderyp/phpunit/shared/vendor/autoload.php".
```

#### Expected behavior

Execute phpunit from location of `phpunit.xml` (even if it is a link).  Just trust the found location of `phpunit.xml`, and don't follow to its target location if it is link.

**Comment by sebastianbergmann** [comment]
I am not sure what the correct behaviour is. I am almost certain, though, that changing it would be unexpected for at least some users.

**Comment by arderyp** [comment]
For someone somewhere? Perhaps. But, more generally speaking, I disagree, if you'll allow me to explain.

If you created a symbolic link to an externally located `phpunit.xml` file in you current directory (or any directory, for that matter), the most obvious reason for doing so would be because you believe PHPUnit expects to find it in said directory and operate on it as if it were located in said directory.  The purpose is defeated when PHPUnit then decides to follow the link to the source from which you linked it.  If you wanted to execute PHPUnit against the file in its original location, then you would not link the file, because you could instead simply call  `phpunit` with the standard built in CLI option designed to do exactly that:


```
-c|--configuration <file>   Read configuration from XML file
```


https://phpunit.readthedocs.io/en/9.3/textui.html

```
# In my case
phpunit -c ../shared/phpunit.xml
```

**Comment by arderyp** [comment]
closed for what reason @sebastianbergmann
