### ISSUE TITLE
Add expectNoException()?

### ISSUE THREAD

**Issue by DivineDominion** [sebastianbergmann/phpunit#4432]
I was thinking about how to approach a test that verifies a defensive check: if an associative array doesn't have a key, just return, but don't try to access the element with the key. Aka abort silently.

With PHPUnit it's pretty simple to test that a method call _will_ throw, but it's apparently impossible to verify that a method call does _not_ throw anything.

`$this->expectNoException();` would be helpful. But if it boils down to

```php
        try {
            // Call the code
        } catch (Exception $e) {
            $this->fail("Expected no exception but got: ${e}");
        }

```

... then there'd be no assertions for the successful path and PHPUnit will report the test as suspicious.

Even if the suspicious test flag was avoided, I wonder if this is a good design idea. Because we don't want to encourage people to litter their tests with `$this->expectNoException();` everywhere they don't expect an error. This is an implicit assumption for all tests, as unhandled errors eventually surface as test failures.

What do you think about adding an expectation like this?

**Comment by sebastianbergmann** [comment]
The default expectation is that no exception is raised that is not handled either by the code under test or by the test code. Therefore something like `expectNoException()` does not make sense IMO and will not be added.
