### ISSUE TITLE
Add a way to expect log items

### ISSUE THREAD

**Issue by joachim-n** [sebastianbergmann/phpunit#4437]
In an application that logs errors, the logging of errors sometimes needs to be tested. For example:

- When there is a problem, we need to test that an error was logged.
- When there isn't a problem, we should verify that no error was logged.

This is something that's being worked on in Drupal's PHPUnit tests in this issue https://www.drupal.org/project/drupal/issues/2903456.

Quick summary of that issue's development:

- We made test classes implement Psr\Log\LoggerInterface and then register them as loggers with the service container. That means that when a log event happens, the test class can throw an exception and fail the test. But that approach means that there is then no coverage of how the system behaves after the error is logged, such as asserting that the user sees some sort of fallback.
- So we're now thinking we need some sort of expectLog() and expectLogMessage() methods in the test, which would work the same way as expectException() and be checked for at the end of the test.

Given that the LoggerInterface is a PSR standard, that has me wondering whether this is all something that should be implemented in PHPUnit rather than Drupal. Hence this feature request :)

**Comment by sebastianbergmann** [comment]
This is not something that should be part of PHPUnit.

**Comment by joachim-n** [comment]
I really think this belongs in PHPUnit, because there is a case that can't be handled properly in consumer test code.

Consider the case where the SUT outputs a log within a try/catch blog:

```
    try {
      // SUT logs an error - we want this to fail the test.
      $this->logger->error('error');
    }
    catch (\Exception $e) {
      // This will catch any attempt at failing the test from within the logger.
    }
```

Within our listening logger, all we can do is cause a test failure in response to the logged error:

```
  public function log($level, $message, array $context = array()) {
    Assert::fail('Log error!');
  }
```

However, Assert::fail() works by throwing an exception, AssertionFailedError. And that gets caught by the SUT, and so the error is not seen by PHPUnit.

The only way I've found to make this case work is to track the occurrence in a class property, $this->logErrorCausedFailure, and then check for it in tearDown():

```
  protected function tearDown(): void {
    // Ensure that if the test produced logs, it actually fails.  This is to
    // cover the case where the error was logged in the SUT from inside a
    // try/catch block.
    // TODO: Give the backtrace of the logged error.
    if ($this->logErrorCausedFailure) {
      if ($this->status()->isFailure()) {
        if (!str_contains($this->status()->message(), 'Log error')) {
          $this->fail("The test failed but the failure obscured a log error.");
        }
      }
      else {
        $this->fail("The test passed, but there were errors logged.");
      }
    }
```

This works, but it's not ideal, as the output from PHPUnit is confusing in this case -- if the test method also failed an assertion, then two failures are shown instead of one. 

I've made a simple test repo that demonstrates this case: https://github.com/joachim-n/test-2903456-test-logging

If this were handled within PHPUnit, it could properly handle this case.

Furthermore, it seems to me that this is a feature that would be useful to all applications of PHPUnit, so I don't understand why it shouldn't be part of it.

**Comment by Schrank** [comment]
I wrote about a similiar case and imho is your problem your generic catch. Although convenient, does it break your tests

maybe this helps
https://winkelwagen.de/2024/02/28/php-phpunit-dont-catch-exception-because-you-dont-handle-them-properly/

**Comment by Crell** [comment]
@joachim-n The [log-test](https://github.com/php-fig/log-test) package from FIG includes a test logger that has all kinds of introspection for testing purposes.

**Comment by joachim-n** [comment]
@Schrank I get what you mean about the problem of catching the root \Exception class. But one of the use cases in Drupal is the queue system, which needs to catch any exception thrown by whatever the worker is trying to do, so that failures in the worker don't affect the queue system. Hence it catches \Exception. To fix that, we'd need to use a domain-specific DrupalException, and get *all* Drupal code to use exceptions that inherit from that. Though even then that wouldn't work, as the queue worker could call code in another package.

**Comment by Schrank** [comment]
Understood. The alternative would be to have an extra catch for phpunit exceptions and throw them again, which is not nice as all, I know.

but yea, get the problem but agree with Sebastian on this.

**Comment by joachim-n** [comment]
@Schrank Could you explain why you don't think it belongs in PHPUnit? 

AFAICT, the double failure problem could be handled properly if PHPUnit internas were aware of this case.

Furthermore, this feature would be useful to any project or library which uses logging.

**Comment by Schrank** [comment]
Because Logging is something which is not part of PHP and therefore an app-specific thing which doesn't belong here.

Did you think about a phpunit plugin? I'm not totally into it, but I guess based on the event system what you want could be easily implemented? 🤔

**Comment by joachim-n** [comment]
True, it's not part of PHP, but there's a PSR standard for it, so that makes it semi-official, right?

When you say a plugin, do you mean something reacting to the events that PHPUnit fires? Do those allow the result of the test to be modified? We need to remove a failure from PHPUnit's record of the test run in the case of an over-eager catch().

**Comment by Schrank** [comment]
I'm talking about https://docs.phpunit.de/en/10.5/extending-phpunit.html# and I don't know. I remember something about not changing test results, but maybe I'm remembering wrong.

@sebastianbergmann @localheinz Maybe you want to add a few notes to help here?

**Comment by Schrank** [comment]
I just stumbled over this idea, maybe it helps - code is untested.

```php
private function setupLogger(): void
{
    $this->loggerMock = (new class implements LoggerInterface {
        private int $i = 1;
        public function emergency($message, array $context = array())
        {
            $this->log('emergency', $message, $context);
        }

        public function alert($message, array $context = array())
        {
            $this->log('alert', $message, $context);
        }

        public function critical($message, array $context = array())
        {
            $this->log('critical', $message, $context);
        }

        public function error($message, array $context = array())
        {
            $this->log('error', $message, $context);
        }

        public function warning($message, array $context = array())
        {
            $this->log('warning', $message, $context);
        }

        public function notice($message, array $context = array())
        {
            $this->log('notice', $message, $context);
        }

        public function info($message, array $context = array())
        {
            $this->log('info', $message, $context);
        }

        public function debug($message, array $context = array())
        {
            $this->log('debug', $message, $context);
        }

        public function log($level, $message, array $context = array())
        {
            $message = array_shift(UpdateCustomerWithConsentTest::$logMessages);
            
            Assert::assertSame($message, [$level, $message, $context], 'Message number ' . $this->i . ' is not as expected.');
            $this->i++;
        }
    });
}

public function testSomething(): void
{
    self::$logMessages = [
        ['debug', 'Handling Message', []],
        ['warning', 'Message not handled', []],
    ];
}

**Comment by joachim-n** [comment]
@Crell It doesn't look like the test logger in php-fig/log-test has methods to verify that there were NO logs of a certain severity, which doesn't make it useful here.

**Comment by Crell** [comment]
`self::assertFalse($testLogger->hasRecords('debug'))` ?
