### ISSUE TITLE
Use strcmp for string comparison

### ISSUE THREAD

**Issue by udf2457** [sebastianbergmann/phpunit#4445]
At the moment you appear to be recommending the use of `assertEquals()` for both strings and numbers.

However surely strings should be compared with `strcmp()` (and `strcasecmp()` for case insensitive).  

Regarding the "why?", my understanding:

`strcmp()` is binary safe, meanwhile using `===` on strings results in an ASCII value comparison, and `==` for string comparisons should simply be not trusted at all.

**Comment by Danon** [comment]
This benchmark illustrate the great performance (0.2s vs 0.06s), in favour of `===`: https://snipplr.com/view/758.

Don't know whether that's an issue, thought I'd just post it here for reference.

**Comment by Danon** [comment]
@udf2457 Out of curiosity, can you provide examples illustrating difference between `strcmp()` and `===`?

**Comment by ComiR** [comment]
The only benefit of using `strcmp()` over `===` is that it also returns which string is "lesser"/"greater" (int <0/0/>0). But that is not needed if we only want to know if these strings are equal.
Using `===` also has the added benefit of gracefully returning `false` if the actual value would f.e. be an integer.

`==` should never be used (use `(string)$a === (string)$b` instead).
