### ISSUE TITLE
Make PHPUnit 8 pseudo-PHP8 compatible

### ISSUE THREAD

**Issue by Hackwar** [sebastianbergmann/phpunit#4450]
Hello, I have a teeny-tiny feature request: Could you please backport this issue #4373/this PR #4374 into PHPUnit 8? 

I'm coming from Joomla (https://github.com/joomla/joomla-cms) and we are trying to get our codebase PHP8 compatible, at the same time we are using some assertions, which have been deprecated and removed in PHPUnit 9. I know that we need to upgrade to PHPUnit 9 eventually, but to be honest, the number of people working on tests are few and those few are swamped with work. If you could backport that one-line-change to PHPUnit 8, our tests would work in PHP8 again and we could get some progress there. The way it is now, this issue resulted in us applying a hot-patch each time we run the tests in PHP8.

**Comment by sebastianbergmann** [comment]
Sorry, no. This is not the only issue that makes PHPUnit 8 incompatible with PHP 8. PHPUnit will not be adapted for PHP 8.

**Comment by mfn** [comment]
@Hackwar for when the time calls for it, there is https://github.com/cweagans/composer-patches ( or even https://github.com/vaimo/composer-patches , but I used neither) which allows applying local patches and distribute this. I've seen projects using this to solve such problems. HTH, YMMV

**Comment by Hackwar** [comment]
@sebastianbergmann Ok, it was worth a try. Still thank you for all the work you are doing here.

@mfn thanks, will have a look.
