### ISSUE TITLE
Don't know how to write testcase to run "doctrine:schema:update" command in symfony.

### ISSUE THREAD

**Issue by MahorShekhar** [sebastianbergmann/phpunit#4452]
I'm an absolute beginner in symfony. I've assigned a task to create a test class.

I’ll need to create a new test class:tests/AppBundle/Command/EntitiesAndAnnotationsCheckCommandTest.php

This test class will have a test that will run the doctrine:schema:update --dump-sql command.

We need to test that this command ends up properly (does not ends with error)Also check that the command output has no exception nor error on its description.

Can somebody give me a hint please ?

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.
