### ISSUE TITLE
"Migration failed" message shown when trying to migrate XML configuration file that does not need migration

### ISSUE THREAD

**Issue by mvorisek** [sebastianbergmann/phpunit#4454]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.3.7
| PHP version         | 7.4
| Installation Method | Composer

#### Summary & Current behavior

![image](https://user-images.githubusercontent.com/2228672/92978397-ea805100-f48f-11ea-9c38-f1b1ce464bf1.png)

#### How to reproduce

save
```
<phpunit bootstrap="vendor/autoload.php" printerClass="atk4\core\AtkPhpunit\ResultPrinter" colors="true">
    <php>
        <var name="DB_DSN" value="sqlite::memory:" />
        <var name="DB_USER" value="" />
        <var name="DB_PASSWD" value="" />
        <var name="DB_DBNAME" value="" />
    </php>
    <testsuites>
        <testsuite name="tests">
            <directory>tests</directory>
        </testsuite>
    </testsuites>
    <coverage processUncoveredFiles="true">
        <include>
            <directory suffix=".php">src</directory>
        </include>
        <report>
            <php outputFile="build/logs/clover.cov" />
        </report>
    </coverage>
</phpunit>
```
as `phpunit.xml.dist` and run `phpunit --migrate-configuration`

#### Expected behavior

migration completes

**Comment by sebastianbergmann** [comment]
> ![image](https://user-images.githubusercontent.com/2228672/92978397-ea805100-f48f-11ea-9c38-f1b1ce464bf1.png)

Please do not post screenshots of code or output. Instead post the code or output as text using the appropriate markup.

> #### Expected behavior
> migration completes

The XML document you provided is a valid PHPUnit 9.3 XML configuration file. Therefore there is nothing to migrate. While your expectation is wrong, you still have discovered something I consider a bug.
