### ISSUE TITLE
Improperly marked "risky" tests due ONLY to --coverage-text

### ISSUE THREAD

**Issue by hopeseekr** [sebastianbergmann/phpunit#4459]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.5.8 *and* 9.3.10 [latest]
| PHP version         | 7.2.33, 7.3.22, and 7.4.10 [latest]
| Installation Method | composer

## The Problem

As part of my Bettergist Collective project, I have been running phpunit (and a host of other utilities) against (eventually) the entire catalog of PHP packages in the Composer / Packagist.org universe. I currently maintain the PHP Packagist Archive, which already contains quarterly backups of every single package.

As such, I have run thousands and thousands of phpunits across tens of thousands of projects (currently ~50,000+), which (tell @sebastianbergmann !) is probably a better test suite of PHPUnit itself over anything on the planet (even more than what you guys must have!). I even test every package against PHPUnit 7.2 through 8.0 (if composer manages to install for each) ;_)

This is a new one for me. 

**I have never seen this in 23 years as a PHP developer and 20 year-user of PHPUnit, so that is why I'm reporting it.** It seems like it might be related tangentally to #2633.

#### Current behavior

Tests run normally without any flags.
![image](https://user-images.githubusercontent.com/1125541/93643621-0327c400-f9c6-11ea-9965-f013f81dd3bd.png)

However, when any of the `--coverage` options is used, phpunit will report basically every test as "Risky".

![image](https://user-images.githubusercontent.com/1125541/93643893-7c271b80-f9c6-11ea-9e0b-c5d4177dbcf1.png)

#### How to reproduce

I discovered this when I got to the `h`s of PHP projects.

```bash
git clone https://github.com/box-project/box humbug-box
cd humbug-box
composer install
phpunit --coverage-text
```

It may very well have to do with arcane settings in their [**`phpunit.xml.dist`**](https://github.com/box-project/box/blob/master/phpunit.xml.dist):

```
         beStrictAboutChangesToGlobalState="true"
         beStrictAboutOutputDuringTests="true"
         beStrictAboutResourceUsageDuringSmallTests="true"
         beStrictAboutCoversAnnotation="true"
```

I have never seen any of those out in the wild before...
#### Expected behavior

I would expect PHPUnit to run in a manner where tests are not marked as `Risky`, or otherwise fail, **just** because a `--coverage` option was used.

### Thank you!

PHPUnit has been an absolutely wonderful piece of life for the last 20 years. I absolutely love writing tests and I believe you have extremely positively benefited past, present and future humanity with your contributions!!

I mainly submitted this report because I hadn't seen this error in over 50,000+ PHP projects we've been able to run PHPUnit on to date.

Cheers!

**Comment by sebastianbergmann** [comment]
> ![image](https://user-images.githubusercontent.com/1125541/93643621-0327c400-f9c6-11ea-9965-f013f81dd3bd.png)

Please post output as text (using proper markup). Do not post screenshots of output.

> It may very well have to do with arcane settings in their [**`phpunit.xml.dist`**](https://github.com/box-project/box/blob/master/phpunit.xml.dist):
> 
> ```
>          beStrictAboutChangesToGlobalState="true"
>          beStrictAboutOutputDuringTests="true"
>          beStrictAboutResourceUsageDuringSmallTests="true"
>          beStrictAboutCoversAnnotation="true"
> ```

There is nothing arcane here. Some of these are even recommended. For reference:

```
$ phpunit --generate-configuration
PHPUnit 9.3.10 by Sebastian Bergmann and contributors.

Generating phpunit.xml in /home/sb

Bootstrap script (relative to path shown above; default: vendor/autoload.php): 
Tests directory (relative to path shown above; default: tests): 
Source directory (relative to path shown above; default: src): 

Generated phpunit.xml in /home/sb
```
```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.3/phpunit.xsd"
         bootstrap="vendor/autoload.php"
         executionOrder="depends,defects"
         forceCoversAnnotation="true"
         beStrictAboutCoversAnnotation="true"
         beStrictAboutOutputDuringTests="true"
         beStrictAboutTodoAnnotatedTests="true"
         failOnRisky="true"
         failOnWarning="true"
         verbose="true">
    <testsuites>
        <testsuite name="default">
            <directory suffix="Test.php">tests</directory>
        </testsuite>
    </testsuites>

    <coverage processUncoveredFiles="true">
        <include>
            <directory suffix=".php">src</directory>
        </include>
    </coverage>
</phpunit>
```

> I would expect PHPUnit to run in a manner where tests are not marked as `Risky`, or otherwise fail, **just** because a `--coverage` option was used.

AFAICS, PHPUnit is behaving exactly as expected: `beStrictAboutCoversAnnotation="true"` is set in `phpunit.xml`, a test that has a `@covers` annotation is executing code that is not expected to be executed, PHPUnit marks the test as risky.

**Comment by hopeseekr** [comment]
So you're saying that using `--coverage-text` adds extra code to be tested? I don't quite understand but you're so far beyond me. if you think this should be closed, it shall stay closed.

I still have no idea what you're saying tho ;-)
