### ISSUE TITLE
Allow users to configure how deprecation warnings are triggered

### ISSUE THREAD

**Issue by alexpott** [sebastianbergmann/phpunit#4461]
At the moment PHPUnit deprecates code by calling `TestCase::addWarning()` for example https://github.com/sebastianbergmann/phpunit/blob/c82c932d0d665ffa3dc1e78e2b2776a1b1b93aa6/src/Framework/TestCase.php#L582

Triggering these warnings is great because it helps people upgrade their code and get ready for the next version of PHPUnit. In Symfony-land deprecations are handled using `@trigger_error('message', E_USER_DEPRECATED);` - this allows the PHPUnit-Bridge component to manage deprecations triggered by code. It allows the projects to choose when they tackle the technical debt on their own terms. Drupal has also adopted this way of managed deprecated code.

It'd be great if there was a option in PHPUnit to trigger silenced deprecations instead of a warning. I propose that we add a `TestCase::addDeprecation()` method that depending on a flag in PHPUnit's configuration either calls  `TestCase::addWarning()` or `@trigger_error('message', E_USER_DEPRECATED);`. The default should be to continue to use the warning system but then projects such as Drupal can set the flag to use their existing tools to manage how they cope with deprecations.

**Comment by helhum** [comment]
I would support that feature. If any of the options are supported, I'd be happy to create a PR for it

**Comment by sebastianbergmann** [comment]
> It'd be great if there was a option in PHPUnit to trigger silenced deprecations instead of a warning.

My experience is: if something can be silenced, it will be silenced. And at the time when something is removed that was deprecated before and warned about the developers who silenced the warning will scream: we never saw this coming! So, no, I am against adding an option to silence these warnings.

**Comment by alexpott** [comment]
@sebastianbergmann I can see how an option to ignore these errors might be too tempting. Good point. How about adding a method alongside `addWarning()` to add PHPUnit deprecations - something like `addDeprecation` so that project like Drupal can override this method to trigger a silenced deprecation. Note that using `@trigger_error('message', E_USER_DEPRECATED);` does not cause the deprecation to be silenced when running a test with Symfony's PHPUnitBridge - it causes the deprecation to be reported in a different way.
