### ISSUE TITLE
wrapper tearUp/tearDown wrong exception handling

### ISSUE THREAD

**Issue by iamrekas** [sebastianbergmann/phpunit#4465]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.3.10
| PHP version         | 7.4.9
| Installation Method | Composer

#### Summary

Wrapping testcase with custom tearDown (i think same with others methods) and made mistake, exception handler doesn't show any information about that error, what doesn't except show as phpunit error.

#### Current behavior

```
Fatal error: Uncaught ParseError: syntax error, unexpected '}', expecting '(' in /workspace/vendor/phpunit/phpunit/src/TextUI/Command.php on line 103

PHPUnit\TextUI\Exception: syntax error, unexpected '}', expecting '(' in /workspace/vendor/phpunit/phpunit/src/TextUI/Command.php on line 103

Call Stack:
    0.0007     409232   1. {main}() /workspace/vendor/phpunit/phpunit/phpunit:0
    0.0103    1567704   2. PHPUnit\TextUI\Command::main() /workspace/vendor/phpunit/phpunit/phpunit:61
````

#### How to reproduce

```
// TestCase.php
<?php 
use PHPUnit\Framework\TestCase as OrginalTestCase;

class TestCase extends OrginalTestCase
{
    protected function setUp(): void
    {
        invalidCode;
    }
    protected function tearDown(): void
    {
    }
}
```
```
// ExampleTest.php
<?php 

class ExampleTest extends TestCase {
    public function testExample() {
        $this->assertTrue(true);
    }
}
```

#### Expected behavior

```
Exception: SOME ERRROR in **TestCase.php** on line **9**

Call Stack:
    0.0007     409232   1. {main}() /workspace/vendor/phpunit/phpunit/phpunit:0
    0.0103    1567704   2. PHPUnit\TextUI\Command::main() /workspace/vendor/phpunit/phpunit/phpunit:61
````

#### UPDATE:
I was little testing. So **this behavior are same if error is any here in test file.**
And it's not interupt others testings.

**Comment by epdenouden** [comment]
Hi @iamrekas!

I am not sure what exactly you want changed?

The error you show in _Current behaviour_ is exactly what I would expect to happen: PHP itself exits with an error about invalid syntax, causing PHPUnit itself to crash out before the test run begins.

In theory PHPUnit could also wrap parsing exceptions by doing more complex exception handling around autoloading of classes. However I am not sure why you even would want PHPUnit to start if the code isn't even valid.
