### ISSUE TITLE
Custom code coverage drivers

### ISSUE THREAD

**Issue by leocavalcante** [sebastianbergmann/phpunit#4469]
Just checking, but it is not possible to use custom code coverage drivers, right? I saw [`Selector`](https://github.com/sebastianbergmann/php-code-coverage/blob/master/src/Driver/Selector.php) and it looks tied to the provided drivers.
Or this feature already exists?
Would be better to provide a mechanism for custom drivers or to PR new drivers to [`php-code-coverage`](https://github.com/sebastianbergmann/php-code-coverage)?

**Comment by sebastianbergmann** [comment]
PHPUnit will only support what php-code-coverage supports. But to be honest, I am reluctant to add support for another driver. Xdebug and PCOV are good enough for me, and I would like to remove support for PHPDBG sooner rather than later.
