### ISSUE TITLE
Non test method `testimonial` gets executed as test

### ISSUE THREAD

**Issue by sebastiansulinski** [sebastianbergmann/phpunit#4471]
I've just came across a problem with non test methods starting with `test...` - in my particular case it was a trait that generates either a single or multiple records for the `Testimonial` model. Here's the trait:

```php
trait TestimonialTrait
{
    /**
     * Get Testimonial instance.
     *
     * @param  array  $props
     * @param  mixed  ...$states
     * @return \App\Models\Testimonial
     */
    protected function testimonial(array $props = [], ...$states): Testimonial
    {
        //...
    }

    /**
     * Get Testimonial collection.
     *
     * @param  int  $count
     * @param  array  $props
     * @param  mixed  ...$states
     * @return \Illuminate\Support\Collection
     */
    protected function testimonials(int $count, array $props = [], ...$states): Collection
    {
        //...
    }
}
```

When used with the test class I get two warnings at the end:

```bash
Test method "testimonial" in test class "Tests\Feature\Admin\Testimonial\TestimonialTest" is not public.

Test method "testimonials" in test class "Tests\Feature\Admin\Testimonial\TestimonialTest" is not public.
```

When changed visibility of both of the methods to public, I get:

```bash
This test did not perform any assertions

/Users/sebastian/code/valet/chichester-park-hotel/tests/Traits/TestimonialTrait.php:19

ArgumentCountError : Too few arguments to function Tests\Feature\Admin\Testimonial\TestimonialTest::testimonials(), 0 passed in /Users/sebastian/code/valet/chichester-park-hotel/vendor/phpunit/phpunit/src/Framework/TestCase.php on line 1533 and at least 1 expected
 /Users/sebastian/code/valet/chichester-park-hotel/tests/Traits/TestimonialTrait.php:32
```

I can obviously try to change method name, but I wonder if this has been reported before and can be fixed by detecting either camel / snake case method naming for the `test` prefix. If it's an overkill then not too worry, but I just thought I'll mention in case you could do a quick fix for it.

**Comment by sebastianbergmann** [comment]
[The documentation is clear](https://phpunit.readthedocs.io/en/9.3/writing-tests-for-phpunit.html):
> The tests are public methods that are named `test*`
I think changing this to "name must begin with `test` followed by either an uppercase character or `_`" may be confusing and/or introduce unintended side effects.

**Comment by sebastiansulinski** [comment]
You say it's clear, but it's not really because if you have a protected method starting with `test*` then you have the first warning I've shown in the original example so no, I don't think it's completely clear.

![Screenshot 2020-09-27 at 14 25 03](https://user-images.githubusercontent.com/2211203/94366046-4de3c300-00cd-11eb-80aa-6675b1590f42.png)

**Comment by sebastianbergmann** [comment]
> I don't think it's completely clear

I agree, this could be clearer.

**Comment by epdenouden** [comment]
@sebastianbergmann the TestDox Refactoring Team does appreciate it :)
