### ISSUE TITLE
Misleading vararg phpDoc annotation

### ISSUE THREAD

**Issue by Danon** [sebastianbergmann/phpunit#4473]
Currently, `InvocationMocker.with()` method contains phpDoc: `@param array ...$arguments`, which kinda suggests variadic arguments of type `array` (so, `with([], [], [], [], [])`).

That's probably the reason why PhpStorm issues a warning (there are types other than `array` in the list of variadic arguments).

![image](https://user-images.githubusercontent.com/13367735/94374165-ac7b6200-010a-11eb-82fa-6a666f3f926b.png)

I understand that the intetion of `with()` is that any type of argument can be passed to `InvocationMocker.with()`, like `with(1, "hello", true, null)`, etc.

So the phpDoc should state
```php
@param mixed ...$arguments
```
or simply
```php
@param ...$arguments
```

No stricter typehint can be provided, since `with()` can be used to mock a method with any signature.

It can't even be `mixed[] ...$arguments`, since that would suggest only arrays of type `mixed[]` can be passed as variadic argument.

**Comment by Danon** [comment]
In other words, type `array` of `$arguments` is deducted from varargs `...` themselves, and the type in `@param` I imagine is used for  the elements inside the array.

**Comment by sebastianbergmann** [comment]
This is what `InvocationMocker::with()` looks like in both [PHPUnit 9.3.11](https://github.com/sebastianbergmann/phpunit/blob/9.3.11/src/Framework/MockObject/Builder/InvocationMocker.php#L160) and [PHPUnit 8.5.8](https://github.com/sebastianbergmann/phpunit/blob/8.5.8/src/Framework/MockObject/Builder/InvocationMocker.php#L154) (these are the only two supported versions of PHPUnit as of today):
```php
/**
 * @throws RuntimeException
 *
 * @return $this
 */
public function with(...$arguments): self
{
    $this->canDefineParameters();

    $this->matcher->setParametersRule(new Rule\Parameters($arguments));

    return $this;
}
```
As you can see, there is no `@param` annotation in the method's docblock. I can only assume that you are using an unsupported version of PHPUnit that had a wrong `@param` annotation in the method's docblock.

**Comment by drealecs** [comment]
Hey @sebastianbergmann,
I guess you added it back 1 month later: https://github.com/sebastianbergmann/phpunit/commit/d3b55c36f95329c062e69f6c10441106cf712f7f

Can we re-open this issue to fix it. The PhpStorm users are compaining 😄.

**Comment by sebastianbergmann** [comment]
Sorry, I am confused right now and am not sure what you would like me to do. Can I bother you to open a pull request with the proposed change (against the oldest relevant branch, either `8.5`, `9.5`, or `master`)? Thanks!

**Comment by drealecs** [comment]
Was trying to do that but I got confused as well 😄.
The changes in master and recent branches are actually correct.
Sorry for the noise.
