### ISSUE TITLE
NotFoundHttpException POST http://localhost/: error

### ISSUE THREAD

**Issue by pixsolution** [sebastianbergmann/phpunit#4476]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.5
| PHP version         | 7.2.5
| Laravel version        | 7.0
| Installation Method | Composer 

#### Summary

Hi! All my tests were working fine and after updating the version of php, phpunit and laravel it gives me an error that I following attach. Has anyone been presented with this error? my whole project is working perfectly except all tests same error

#### Current behavior

![image (19)](https://user-images.githubusercontent.com/47191848/94781241-d7470e00-03c9-11eb-9140-c356031eddd3.png)
I don't know where it's getting that localhost url from? because it is not the url of the project that I have configured in my env

#### How to reproduce

Everytime I run the tests

#### Expected behavior

The tests should run well

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.
