### ISSUE TITLE
Double comparison default delta makes tests fail

### ISSUE THREAD

**Issue by isfs** [sebastianbergmann/phpunit#448]
Defaulting the delta for numerical comparisons to 0.0000000001 (Framework/Comparator/Double.php:65, 96-98) causes problems. Numbers may differ by amounts much smaller than this but the difference still be very significant, because the magnitudes of the numbers may be small. For instance, this test fails, but it really should pass.

<pre>
class DoubleTest extends PHPUnit_Framework_TestCase {
	public function test() {
		$this->assertNotEquals(1e-20,2e-20);
	}
}
</pre>

It is also, as far as I can tell, impossible to specify a delta of zero, because zero is defaulted to 0.0000000001. This makes it impossible to even override the default and make the test pass without modifying the PHPUnit source. I.e. this doesn't work:

<pre>
class DoubleTest extends PHPUnit_Framework_TestCase {
	public function test() {
		$this->assertNotEquals(1e-20,2e-20,"",0);
	}
}
</pre>

PHPUnit does not use the specified delta of zero, but uses 0.0000000001.

IMHO, it would be best not to default the delta at all, as that makes a pretty big assumption about the kinds of numbers the user is comparing, and it's unhelpful; it is better just to use zero and let the user provide an appropriate delta if they find their tests are failing. More importantly, though, if a non-zero default delta is used, overriding it by providing a delta of zero as a parameter must work.

**Comment by sebastianbergmann** [comment]
If I implement the change proposed by @nikic in the Comparator component

```
diff --git a/src/NumericComparator.php b/src/NumericComparator.php
index a3453a9..248ad27 100644
--- a/src/NumericComparator.php
+++ b/src/NumericComparator.php
@@ -59,6 +59,8 @@ class NumericComparator extends ScalarComparator
             return;
         }
 
+        $delta = max($expected, $actual) * $delta;
+
         if ((is_infinite($actual) xor is_infinite($expected)) ||
             (is_nan($actual) or is_nan($expected)) ||
             abs($actual - $expected) > $delta) {
```

then quite a few tests start failing

```
PHPUnit 4.7.4 by Sebastian Bergmann and contributors.

Runtime:	PHP 5.6.10 with Xdebug 2.3.2
Configuration:	/usr/local/src/comparator/phpunit.xml.dist

...............FFF.............................................  63 / 293 ( 21%)
.......................FF...................................... 126 / 293 ( 43%)
...................................F...................FF...... 189 / 293 ( 64%)
.........F..................................................... 252 / 293 ( 86%)
.........................................

Time: 2.7 seconds, Memory: 12.25Mb

There were 9 failures:

1) SebastianBergmann\Comparator\ArrayComparatorTest::testAssertEqualsFails with data set #5 (array(2.3), array(4.2), 0.5)
Failed asserting that exception of type "SebastianBergmann\Comparator\ComparisonFailure" is thrown.

2) SebastianBergmann\Comparator\ArrayComparatorTest::testAssertEqualsFails with data set #6 (array(array(2.3)), array(array(4.2)), 0.5)
Failed asserting that exception of type "SebastianBergmann\Comparator\ComparisonFailure" is thrown.

3) SebastianBergmann\Comparator\ArrayComparatorTest::testAssertEqualsFails with data set #7 (array(SebastianBergmann\Comparator\Struct Object (...)), array(SebastianBergmann\Comparator\Struct Object (...)), 0.5)
Failed asserting that exception of type "SebastianBergmann\Comparator\ComparisonFailure" is thrown.

4) SebastianBergmann\Comparator\DoubleComparatorTest::testAssertEqualsFails with data set #5 (2.3, 2.5, 0.2)
Failed asserting that exception of type "SebastianBergmann\Comparator\ComparisonFailure" is thrown.

5) SebastianBergmann\Comparator\DoubleComparatorTest::testAssertEqualsFails with data set #6 (3, 3.05, 0.04)
Failed asserting that exception of type "SebastianBergmann\Comparator\ComparisonFailure" is thrown.

6) SebastianBergmann\Comparator\MockObjectComparatorTest::testAssertEqualsFails with data set #4 (Mock_Struct_ebaf5783 Object (...), Mock_Struct_ebaf5783 Object (...), 'Failed asserting that two obj...equal.', 0.5)
Failed asserting that exception of type "SebastianBergmann\Comparator\ComparisonFailure" is thrown.

7) SebastianBergmann\Comparator\NumericComparatorTest::testAssertEqualsFails with data set #3 (1337, 1339, 1)
Failed asserting that exception of type "SebastianBergmann\Comparator\ComparisonFailure" is thrown.

8) SebastianBergmann\Comparator\NumericComparatorTest::testAssertEqualsFails with data set #4 ('1337', 1340, 2)
Failed asserting that exception of type "SebastianBergmann\Comparator\ComparisonFailure" is thrown.

9) SebastianBergmann\Comparator\ObjectComparatorTest::testAssertEqualsFails with data set #4 (SebastianBergmann\Comparator\Struct Object (...), SebastianBergmann\Comparator\Struct Object (...), 'Failed asserting that two obj...equal.', 0.5)
Failed asserting that exception of type "SebastianBergmann\Comparator\ComparisonFailure" is thrown.

FAILURES!
Tests: 293, Assertions: 361, Failures: 9.

Generating code coverage report in HTML format ... done
```

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
