### ISSUE TITLE
Methods with "static" return type (introduced in PHP 8) are not handled correctly by test double code generator

### ISSUE THREAD

**Issue by davidbyoung** [sebastianbergmann/phpunit#4480]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.4.0
| PHP version         | 8.0.0rc1
| Installation Method | Composer

#### Summary

The `static` return type isn't fully supported in mocks in PHP 8.0.

#### Current behavior

I get the following error when running a test:

```
Method getInstance may not return value of type Mock_IFoo_54e9358a, its return declaration is "static"
```

#### How to reproduce

```php
interface IFoo
{
    public function getInstance(): static;
}

class FooTest extends TestCase
{
    public function testFoo(): void
    {
        $mockFoo = $this->createMock(Foo::class);
        $mockFoo->method('getInstance')
            ->willReturn($mockFoo);
        $this->assertSame($mockFoo, $mockFoo->getInstance());
    }
}
```

#### Expected behavior

The above test should pass.

#### Additional notes

On a related note, although I cannot create a _simple_ repro for the following error, [here's a link to the broken unit test](https://github.com/aphiria/aphiria/blob/8228529fdd2c891d3fdc594dababf6d7f2516bb8/src/Framework/tests/Application/AphiriaComponentsTest.php#L54) and [output](https://github.com/aphiria/aphiria/runs/1203118994?check_suite_focus=true#step:5:50) for a possibly-related issue with supporting `static` return types.  When dumping the eval'd code [here](https://github.com/sebastianbergmann/phpunit/blob/3e541657ad6c1104935f6a6d3924b7226083aceb/src/Framework/MockObject/MockClass.php#L45), I noticed that some of my tests are resulting in code like the following being generated:

```php
class static
{
}

class Mock_static_5832468d extends static implements PHPUnit\Framework\MockObject\MockObject
{
    use \PHPUnit\Framework\MockObject\Api;
    use \PHPUnit\Framework\MockObject\Method;
    use \PHPUnit\Framework\MockObject\MockedCloneMethod;
}
```

It looks like `static` is being treated like the actual name of a return type rather than a special type.

**Comment by sebastianbergmann** [comment]
Here is a corrected and cleaned up version of the example:
```php
<?php
use PHPUnit\Framework\TestCase;

interface Foo
{
    public function getInstance(): static;
}

class FooTest extends TestCase
{
    public function testFoo(): void
    {
        $foo = $this->createMock(Foo::class);

        $foo->method('getInstance')
            ->willReturn($foo);

        $this->assertSame($foo, $foo->getInstance());
    }
}
```

I am happy to report that I am already able to run it:
```
PHPUnit 9.4.0-1-g7646ea0ce by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 00:00.024, Memory: 6.00 MB

OK (1 test, 1 assertion)
```

I hope to have these changes ready for commit/push soon.

**Comment by sebastianbergmann** [comment]
This requires the [fix](http://git.php.net/?p=php-src.git;a=commitdiff;h=dee802498e25e22afb35e550dea1f7b3a8aa0129) for [PHP bug 80190](https://bugs.php.net/bug.php?id=80190).
