### ISSUE TITLE
[question] Can you extend testdox?

### ISSUE THREAD

**Issue by commentatorboy** [sebastianbergmann/phpunit#4482]
Hey. I have a quick question regarding the testdox html output.

I know that you can extend TextUI/ResultPrinter, and make a custom ResultPrinter for the console output.

But I would like a way to Extend testdox, specifically the html version.

Any ideas on how to do that? Because I tried to extend the HtmlResultPrinter, but that did not work.

I would appreciate any ideas.

**Comment by sebastianbergmann** [comment]
You probably want to use the TestDox XML output and transform that using XSLT, for instance.

**Comment by commentatorboy** [comment]
Ah I see. Thanks for the quick answer :).
