### ISSUE TITLE
Emit error when (configured) test directory does not exist

### ISSUE THREAD

**Issue by bytestream** [sebastianbergmann/phpunit#4493]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.5.8
| PHP version         | 7.3.21
| Installation Method | Composer

#### Summary

`--testsuite` does not error when directory does not exist.

#### Current behavior

```
PHPUnit 8.5.8 by Sebastian Bergmann and contributors.

No tests executed!
```

#### How to reproduce

phpunit.xml
```xml
<testsuite name="cache">
    <directory>test/cache</directory>
</testsuite>
```

Create `test/Cache` - note difference in capitalisation, and run:
`./vendor/bin/phpunit --testsuite=cache --stop-on-failure`

#### Expected behavior

phpunit should error:
```
Suite path test/cache could not be found 
```

**Comment by bytestream** [comment]
See https://github.com/bytestream/phpunit-4493 for minimal repository.

**Comment by sebastianbergmann** [comment]
This is consistent with what happens when `--testsuite` is not used.

**Comment by bytestream** [comment]
It makes sense to error if an argument is invalid - otherwise it's difficult for people to debug. Paratest for example, throws a configuration exception in this case.

**Comment by bytestream** [comment]
Thanks! 🎉
