### ISSUE TITLE
a catchException method inside TestCase

### ISSUE THREAD

**Issue by GPierre-Antoine** [sebastianbergmann/phpunit#4496]
a catchException method, returning ?\Exception.

Implementation and tests written here : https://gitlab.com/pierreantoine.guillaume/testcase

The rationale is to avoid using expectException, and get to test the exceptions this way :

```php
   public function testThrow(): void
    {
        # Given
        // $this is the tested object
        # When
        $exception = $this->catchException(fn() => $this->wrapThrow());

        # Then
        $this->assertEquals(new RuntimeException('Message', 13), $exception);
        // here, assertSame fails but assertEquals succeeds
    }

    protected function wrapThrow(): void
    {
        throw new RuntimeException('Message', 13);
    }
```

If no exception is thrown, $exception is null.
It allows the test to keep it's original format, and decreases the chances of an user missusing the test, for instance like this : 

```php
    public function testThrow(): void
    {
        $this->expectException('Message');
        $this->wrapThrow();
        $this->assertTrue(true); // this assertion is not reached ; but no message can be fed back ; though this is bad practice
    }

```

**Comment by sebastianbergmann** [comment]
I believe the existing `expectException()` mechanism to be sufficient and "good enough".
