### ISSUE TITLE
Allow the --test-suffix argument to be configured @ phpunit.xml

### ISSUE THREAD

**Issue by stronk7** [sebastianbergmann/phpunit#4503]
First of all, my excuses if this has been requested before, I've been searching within all previous issues and failed to find it!

For historical reasons/coding style... we have all our test files suffixed: `_test.php`, and we have a huge (autogenerated) `phpunit.xml`file where we create test suites for all our components, all them using the `<directory suffix="_test.php">...`. So, yes, we are able to run `vendor/bin/phpunit --testsuite xxxx` and it works ok.

More yet, we have an option in our phpunit init script that creates `phpunit.xml` in the parents of all directories having tests. All them using ` <directory suffix="_test.php">.</directory>`. So, yes, we are able to run `vendor/bin/phpunit -c path/to/dir/with/conf/file`

And finally, we also can run, without testsuites or distributed `phpunit.xml` files, all the tests in a directory using `vendor/bin/phpunit —test-suffix _test.php path/to/dir`

So, yes, we are plenty of options!

The only little detail is why that `—test-suffix` argument (that defaults to `Test.php` basically) cannot be configured in the `phpunit.xml` file itself. And then phpunit execution takes it into account if defined (argument > config > default). That way we could execute, simply `vendor/bin/phpunit path/to/dir` and done. No testsuites, no distributed configuration files or extra argument on each execution.

The rationale beyond asking about this is that 1) the directory elements already support it (prefix and suffix) hence 2) it wouldn't be crazy to have a configured default for them, specially because it's already configurable via command-line argument too.

And this is the question/request. Again, sorry of this has been asked already.

Thanks for all the hard work! Ciao :-)

**Comment by sebastianbergmann** [comment]
[This is already possible.](https://github.com/sebastianbergmann/phpunit/blob/master/phpunit.xsd#L140)

**Comment by stronk7** [comment]
Hi @sebastianbergmann ,

thanks for your feedback... I'm not sure if that (testsuite -> directory -> suffix) is what I was asking for, or maybe I haven't understood your link above.

1. We are [already using that (testsuite -> directory -> suffix)](https://github.com/moodle/moodle/blob/master/phpunit.xml.dist#L33) intensively for all our suites (one for each subsystem/api or plugin). And they work great using `--testuite`.
2. What I'm asking, to show it with other words, is about the possibility of configure, vía `phpunit.xml`, exactly this, because I've not been able to imagine how to do so:
```
diff --git a/src/TextUI/Command.php b/src/TextUI/Command.php
index 61db7b786..9cf768c31 100644
--- a/src/TextUI/Command.php
+++ b/src/TextUI/Command.php
@@ -267,7 +267,7 @@ protected function handleArguments(array $argv): void
         $this->handleCustomTestSuite();
 
         if (!isset($this->arguments['testSuffixes'])) {
-            $this->arguments['testSuffixes'] = ['Test.php', '.phpt'];
+            $this->arguments['testSuffixes'] = ['_test.php', '.phpt'];
         }
 
         if (!isset($this->arguments['test']) && $arguments->hasArgument()) {
```
3. With that change applied, we are able to run here `vendor/bin/phpunit any/path` without the need to specify `—test-suffix` (like it works for "normal" `Test.php` or `.phpt` suffixes). I've been looking to your link and also to all the `test-suffix` and `testSuffixes` occurrences in codebase and have been unable to imagine how to change that default.

Again, thanks. And sorry if I'm missing something obvious. Ciao :-)
