### ISSUE TITLE
Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by willmot** [sebastianbergmann/phpunit#451]
Although $GLOBAL Closures are no longer serialised since 01aa34783c9b19d39e568641f3f2dd0fc983b11a & #352 a `$GLOBAL` arrays which contain a Closure as a value will still cause the "Serialization of 'Closure' is not allowed" error.

```php
$GLOBALS[] = array( 'foo' => function() { return 'bar'; }  );
```

**Comment by rawaludin** [comment]
Just adding my experience. Basically whenever you put anonymous function or class as test class attribute, phpunit will throw `Serialization of 'Closure' is not allowed` or `Serialization of 'class@anonymous' is not allowed`. So, if you need to use anonymous function or class, make sure its one time variable, not test class attribute.

**Comment by mpyw** [comment]
I wrote the patch: [mpyw/phpunit-patch-serializable-comparison](https://github.com/mpyw/phpunit-patch-serializable-comparison)
