### ISSUE TITLE
Allow passing environment data

### ISSUE THREAD

**Issue by rentalhost** [sebastianbergmann/phpunit#4512]
I need pass some environment data via CLI. It is currently possible, but is OS dependent. So I think that phpunit could implements a default way to do that.

```
phpunit --env AUTH_KEY 123456 --env SECRET_KEY abcdef
```

So

```php
$_ENV['AUTH_KEY'] === '123456';
$_ENV['SECRET_KEY'] === 'abcdef';
```

It will be very useful when some tests requires credentials that is not public. For instance, I have a package that supports two ways to get data, via crawler (when auth is not set) or via official API (when auth is set). 

Currently, on Windows, I need use in a hackish way, and each OS it works differently.

```powershell
$env:AUTH_KEY = "123456";
$env:SECRET_KEY = "abcdef";
phpunit
```

Other option is set via `phpunit.xml`, but if I need test differents auths in the same project, I will need create differents `phpunit.xml` files. But in general, I will need create an `phpunit.xml.example` and the user will need rename it manually before run `phpunit`.

Reference: https://stackoverflow.com/questions/8491437/pass-variable-to-phpunit

**Comment by sebastianbergmann** [comment]
I do not see any value in implementing a CLI option such as `--env` when the following just works:

#### `Test.php`
```php
<?php declare(strict_types=1);
use PHPUnit\Framework\TestCase;

final class Test extends TestCase
{
    public function testOne(): void
    {
        $this->assertSame('bar', $_ENV['foo']);
    }
}
```
```
$ foo=bar phpunit Test.php
PHPUnit 9.5.0 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 00:00.020, Memory: 4.00 MB

OK (1 test, 1 assertion)
```

**Comment by rentalhost** [comment]
@sebastianbergmann set environment variables depends of each kind of terminal. On powershell, for instance, it is like the example that I did:

```powershell
$env:AUTH_KEY = "123456";
$env:SECRET_KEY = "abcdef";
phpunit
```

In the case of powershell, the syntax is quite complex, as you can see.

So is a bit hard you doc the testing method, because you need shows how enviroment should be set in each kind of terminal or depend on the dev to know exactly how to do. The `--env` is more generic way, so I just need shows one example:

```
phpunit --env AUTH_KEY 123456 --env SECRET_KEY abcdef
```
