### ISSUE TITLE
enableProxyingToOriginalMethods() with either an include or exclude array parameter

### ISSUE THREAD

**Issue by bplus** [sebastianbergmann/phpunit#4522]
Would it be possible to make a function similar to enableProxyingToOriginalMethods, for example...

`enableProxyingToOriginalMethodsOnly(array('i', 'really', 'want', 'to', 'proxy', 'just', 'these'))`

or 

`enableProxyingToOriginalMethodsExcept(array('do', 'not', 'proxy', 'these', 'specific', 'methods'))`

?

Or is there another existing method of overriding the enableProxyingToOriginalMethods() to 'ignore' a few methods? 

Specifically, in my case, I want to proxy all methods except for some noisy output in a specific function.  I am doing this right now with 

`$this->setOutputCallback(function() {}); `

This is fine for me for now since it's just STDOUT messages, but it wouldn't help me with other proxy overrides.

I am unsure if there are technical reasons this wouldn't work, or if there just hasn't been anyone who requested and/or looked into building it.

**Comment by sebastianbergmann** [comment]
This is outside the scope of what test proxies are used for.
