### ISSUE TITLE
--coverage-html with additional flag to delete old files

### ISSUE THREAD

**Issue by LocalHeroPro** [sebastianbergmann/phpunit#4523]
When I run
```php
vendor/bin/phpunit --coverage-html=/var/www/html/coverage/app-name
```
it would be nice to have ability to delete old files. Old files it's mean that if for example some controller/observer is deleted in the project, the next run of PHPUnit with the same output path will override only tested files and old - deleted - files will still be in output directory. I want to have ability to clean up directory before sore new results.

**Comment by sebastianbergmann** [comment]
IMO, deleting existing files is outside the scope. If you want a clean directory then you need to delete it yourself before you invoke PHPUnit.
