### ISSUE TITLE
Refactor test suite loading

### ISSUE THREAD

**Issue by flow-control** [sebastianbergmann/phpunit#4524]
Hey there :vulcan_salute: 

this is a follow up to #4039 (Deprecate custom TestSuiteLoader). To be able to refactor the loading of tests, we deprecated the feature to have a custom test suite loader at all. The goal of this issue is to finally remove the deprecated test suite loader and build a new clean way to load test case classes.

I would be happy to provide the pull requests for the upcoming `v10`, I will try to provide multiple smaller pull requests if this okay for you and keep track here in this ticket.

Todos

- [x] remove `--loader` argument and `testSuiteLoaderClass`/`testSuiteLoaderFile` config settings - #4531 
- [x] remove `TestSuiteLoader` Interface and usage
- [ ] refactor `StandardTestSuiteLoader` and usage

/Flo

**Comment by sebastianbergmann** [comment]
YES!, please. :)

**Comment by sebastianbergmann** [comment]
@flow-control Is there anything left to do here? Thanks!

**Comment by flow-control** [comment]
Hey @sebastianbergmann,
I would like to refactor parts of the `TestSuiteLoader` and parts of `Runner/BaseTestRunner::getTest` as these have a lot in common, but I guess this can be done in a separate PR and without further BC breaks.
Thanks for merging
/Flo

**Comment by sebastianbergmann** [comment]
I have removed the `static function suite(): TestSuite` functionality in 36354a9cdc69ecabd20ac505b07541cfdde50aaa and `BaseTestRunner` is much simpler now. I plan to move the remaining code somewhere else soon and then delete the class.
