### ISSUE TITLE
Using emoji in compared strings leads to random space occurance on difference dumper 

### ISSUE THREAD

**Issue by klkvsk** [sebastianbergmann/phpunit#4525]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.4.3
| PHP version         | 7.4.11
| Installation Method | Composer

#### Summary

When asserting on strings, if the assertion fails, expected and actual values are shown. 
With some conditions, there is a random space character added within expected string.
I noticed those conditions are: 
1) there are emojis in "expected" string
2) and `--teamcity` output mode used

#### Current behavior

Whitespace added randomly (random place each time) into dumped expected string.

#### How to reproduce

This is my sample file:
```
Lorem ipsum dolor sit amet
🐱‍🏍
Lorem ipsum dolor sit amet
```

This is a test:
```
$a = file_get_contents(__DIR__ . '/file.txt');
$b = file_get_contents(__DIR__ . '/file.txt');
$this->assertEquals($a, $b . "\nFOO");
```
I purposely add FOO into assertion to break it so diff will be shown.

Here's a screenshot from IDEA:
![Comparison Failure (testFile) 2020-11-26 16 57 18](https://user-images.githubusercontent.com/1466771/100359409-8be75f80-3008-11eb-9f0b-8519dd79ca3b.png)
This is confirmed not being an IDEA's issue by running same test suite with same arguments from CLI.

#### Expected behavior

Expected string shown as is.

**Comment by sebastianbergmann** [comment]
Are you sure that this is a problem in PHPUnit and not in PhpStorm?

**Comment by klkvsk** [comment]
I am sure.
Here is a part of raw output:
```
##teamcity[testFailed name='testFile' message='Failed asserting that two strings are equal.' details=' /home/me/dev/json-decode-stream/tests/TokenizerTest.php:165|n ' duration='4' type='comparisonFailure' actual='|'Lorem ipsum dolor sit amet\r\n|n�‍�\r\n|nLorem i
psum dolor sit amet\n|nFOO|'' expected='|'Lorem ipsum dolor sit amet\r\n|n�‍�\r\n|nLorem ipsum dol or sit amet|'' flowId='11702']
```
You can notice the same behavior in the last sententce almost at the end of the string. It is "dol or" instead of "dolor".

**Comment by sebastianbergmann** [comment]
@SvetlanaZem @wbars @epdenouden Can you have a look, please? Thanks!

**Comment by wbars** [comment]
<img width="1400" alt="Screen Shot 2020-12-07 at 09 23 52" src="https://user-images.githubusercontent.com/5152749/101316636-ed5fc780-386d-11eb-841b-dacfa7df396c.png">
Can't reproduce it using suggested setup + PhpStorm 2020.3

**Comment by sebastianbergmann** [comment]
Thank you, @wbars.

**Comment by klkvsk** [comment]
The bug is NOT related to JetBrains IDEA, I posted raw output before. The problem however can be platform-related. I'm running under ubuntu in WSL2 under Windows.
