### ISSUE TITLE
Parse Error for named Arguments in test with annotation @requires PHP >= 8.0 

### ISSUE THREAD

**Issue by simon-schubert** [sebastianbergmann/phpunit#4528]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.4.3
| PHP version         | 7.4.12
| Installation Method | Composer

#### Summary

If i use named Arguments in a test and add @requires PHP >= 8.0, i get a Parse Error. 

#### Current behavior

```sh
Fatal error: Uncaught ParseError: syntax error, unexpected ':', expecting ')' in /app/vendor/phpunit/phpunit/src/TextUI/Command.php on line 103

PHPUnit\TextUI\Exception: syntax error, unexpected ':', expecting ')' in /app/vendor/phpunit/phpunit/src/TextUI/Command.php on line 103

Call Stack:
    0.0026     396880   1. {main}() /app/vendor/phpunit/phpunit/phpunit:0
    0.2351    4506504   2. PHPUnit\TextUI\Command::main() /app/vendor/phpunit/phpunit/phpunit:61
```

#### How to reproduce

```php
class ValueObject
{
    public function __construct($value){ //... }
}

class ValueObjectTest extends TestCase
{
    /**
     * @requires PHP >= 8.0
     */
    public function testShouldCreateValueObject()
    {
        $vo = new ValueObject(value: 'myString');
    }
}
```

#### Expected behavior

No parse error, as the code under test is valid php 7.4 syntax, the test code is not. Not 100% sure, if this is a bug or just "not possible at all". If so, is there any way out of this?

#### Output from composer info | sort

amphp/amp                                        v2.5.1    A non-blocking concurrency framework for PHP applications.
amphp/byte-stream                                v1.8.0    A stream abstraction to make working with non-blocking I/O simple.
composer/package-versions-deprecated             1.11.99.1 Composer plugin that provides efficient querying for installed package versions (no runtime IO)
composer/semver                                  3.2.4     Semver library that offers utilities, version constraint parsing and validation.
composer/xdebug-handler                          1.4.5     Restarts a process without Xdebug.
dnoegel/php-xdg-base-dir                         v0.1.1    implementation of xdg base directory specification for php
doctrine/annotations                             1.11.1    Docblock Annotations Parser
doctrine/inflector                               2.0.3     PHP Doctrine Inflector is a small library that can perform string manipulations with regard to upper/lowercase and ...
doctrine/instantiator                            1.4.0     A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                                   1.2.1     PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
felixfbecker/advanced-json-rpc                   v3.1.1    A more advanced JSONRPC implementation
felixfbecker/language-server-protocol            v1.5.0    PHP classes for the Language Server Protocol
friendsofphp/php-cs-fixer                        v2.16.7   A tool to automatically fix PHP code style
infection/abstract-testframework-adapter         0.3.1     Abstract Test Framework Adapter for Infection
infection/extension-installer                    0.1.1     Infection Extension Installer
infection/include-interceptor                    0.2.4     Stream Wrapper: Include Interceptor. Allows to replace included (autoloaded) file with another one.
infection/infection                              0.20.2    Infection is a Mutation Testing framework for PHP. The mutation adequacy score can be used to measure the effective...
jean85/pretty-package-versions                   1.5.1     A wrapper for ocramius/package-versions to get pretty versions strings
justinrainbow/json-schema                        5.2.10    A library to validate a json schema.
matthiasnoback/symfony-config-test               4.2.1     Library for testing user classes related to the Symfony Config Component
matthiasnoback/symfony-dependency-injection-test 4.2.1     Library for testing user classes related to the Symfony Dependency Injection Component
migrify/migrify-kernel                           0.4.2     Kernel for small CLI applications
migrify/php-config-printer                       0.4.2     Print Symfony services array with configuration to to plain PHP file format thanks to this simple php-parser wrapper
myclabs/deep-copy                                1.10.2    Create deep copies (clones) of your objects
netresearch/jsonmapper                           v2.1.0    Map nested JSON structures onto PHP classes
nette/finder                                     v2.5.2    🔍 Nette Finder: find files and directories with an intuitive API.
nette/robot-loader                               v3.3.1    🍀 Nette RobotLoader: high performance and comfortable autoloader that will search and autoload classes within yo...
nette/utils                                      v3.1.3    🛠 Nette Utils: lightweight utilities for string & array manipulation, image handling, safe JSON encoding/decodin...
nikic/php-parser                                 v4.10.2   A PHP parser written in PHP
ondram/ci-detector                               3.5.1     Detect continuous integration environment and provide unified access to properties of current build
openlss/lib-array2xml                            1.0.0     Array2XML conversion library credit to lalit.org
phake/phake                                      v3.1.8    The Phake mock testing library
phar-io/manifest                                 2.0.1     Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                                  3.0.2     Library for handling version information and constraints
php-cs-fixer/diff                                v1.3.1    sebastian/diff v2 backport support for PHP5.6
phpdocumentor/reflection-common                  2.2.0     Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock                5.2.2     With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information ...
phpdocumentor/type-resolver                      1.4.0     A PSR-5 based resolver of Class names, Types and Structural Element Names
phpspec/prophecy                                 1.12.1    Highly opinionated mocking framework for PHP 5.3+
phpstan/phpdoc-parser                            0.4.9     PHPDoc parser with support for nullable, intersection and generic types
phpstan/phpstan                                  0.12.57   PHPStan - PHP Static Analysis Tool
phpstan/phpstan-phpunit                          0.12.16   PHPUnit extensions and rules for PHPStan
phpunit/php-code-coverage                        9.2.3     Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator                        3.0.5     FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-invoker                              3.1.1     Invoke callables with a timeout
phpunit/php-text-template                        2.0.4     Simple template engine.
phpunit/php-timer                                5.0.3     Utility class for timing
phpunit/phpunit                                  9.4.3     The PHP Unit Testing framework.
psr/cache                                        1.0.1     Common interface for caching libraries
psr/container                                    1.0.0     Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher                             1.0.0     Standard interfaces for event handling.
psr/log                                          1.1.3     Common interface for logging libraries
psr/simple-cache                                 1.0.1     Common interfaces for simple caching
rector/rector                                    0.8.56    Instant upgrade and refactoring of your PHP code
sanmai/pipeline                                  v5.1.0    General-purpose collections pipeline
sebastian/cli-parser                             1.0.1     Library for parsing CLI options
sebastian/code-unit                              1.0.8     Collection of value objects that represent the PHP code units
sebastian/code-unit-reverse-lookup               2.0.3     Looks up which function or method a line of code belongs to
sebastian/comparator                             4.0.6     Provides the functionality to compare PHP values for equality
sebastian/complexity                             2.0.2     Library for calculating the complexity of PHP code units
sebastian/diff                                   4.0.4     Diff implementation
sebastian/environment                            5.1.3     Provides functionality to handle HHVM/PHP environments
sebastian/exporter                               4.0.3     Provides the functionality to export PHP variables for visualization
sebastian/global-state                           5.0.2     Snapshotting of global state
sebastian/lines-of-code                          1.0.2     Library for counting the lines of code in PHP source code
sebastian/object-enumerator                      4.0.4     Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector                       2.0.4     Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context                      4.0.4     Provides functionality to recursively process PHP variables
sebastian/resource-operations                    3.0.3     Provides a list of PHP built-in functions that operate on resources
sebastian/type                                   2.3.1     Collection of value objects that represent the types of the PHP type system
sebastian/version                                3.0.2     Library that helps with managing the version number of Git-hosted PHP projects
seld/jsonlint                                    1.8.3     JSON Linter
symfony/cache                                    v5.1.8    Symfony Cache component with PSR-6, PSR-16, and tags
symfony/config                                   v5.1.8    Symfony Config Component
symfony/console                                  v5.1.8    Symfony Console Component
symfony/contracts                                v2.3.1    A set of abstractions extracted out of the Symfony components
symfony/dependency-injection                     v5.1.8    Symfony DependencyInjection Component
symfony/error-handler                            v5.1.8    Symfony ErrorHandler Component
symfony/event-dispatcher                         v5.1.8    Symfony EventDispatcher Component
symfony/filesystem                               v5.1.8    Symfony Filesystem Component
symfony/finder                                   v5.1.8    Symfony Finder Component
symfony/http-foundation                          v5.1.8    Symfony HttpFoundation Component
symfony/http-kernel                              v5.1.8    Symfony HttpKernel Component
symfony/options-resolver                         v5.1.8    Symfony OptionsResolver Component
symfony/polyfill-ctype                           v1.20.0   Symfony polyfill for ctype functions
symfony/polyfill-intl-grapheme                   v1.20.0   Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-normalizer                 v1.20.0   Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring                        v1.20.0   Symfony polyfill for the Mbstring extension
symfony/polyfill-php70                           v1.20.0   Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-php72                           v1.20.0   Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73                           v1.20.0   Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80                           v1.20.0   Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/process                                  v5.1.8    Symfony Process Component
symfony/property-access                          v5.1.8    Symfony PropertyAccess Component
symfony/property-info                            v5.1.8    Symfony Property Info Component
symfony/serializer                               v5.1.8    Symfony Serializer Component
symfony/serializer-pack                          v1.0.4    A pack for the Symfony serializer
symfony/stopwatch                                v5.1.8    Symfony Stopwatch Component
symfony/string                                   v5.1.8    Symfony String component
symfony/validator                                v5.1.8    Symfony Validator Component
symfony/var-dumper                               v5.1.8    Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter                             v5.1.8    A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/yaml                                     v5.1.8    Symfony Yaml Component
symplify/autowire-array-parameter                8.3.48    Autowire array parameters for your Symfony applications
symplify/composer-json-manipulator               8.3.48    Package to load, merge and save composer.json file(s)
symplify/console-color-diff                      8.3.48    Package to print diffs in console with colors
symplify/easy-testing                            8.3.48    Testing made easy
symplify/package-builder                         8.3.48    Dependency Injection, Console and Kernel toolkit for Symplify packages.
symplify/set-config-resolver                     8.3.48    Resolve config and sets from configs and cli opptions for CLI applications
symplify/smart-file-system                       8.3.48    Sanitized FileInfo with safe getRealPath() and other handy methods
symplify/symplify-kernel                         8.3.48    Internal Kernel for Symplify packages
thecodingmachine/safe                            v1.3.3    PHP core functions that throw exceptions instead of returning FALSE on error
theseer/tokenizer                                1.2.0     A small library for converting tokenized PHP source code into XML and potentially other formats
vimeo/psalm                                      3.18.2    A static analysis tool for finding errors in PHP applications
webmozart/assert                                 1.9.1     Assertions to validate method input/output with nice error messages.
webmozart/glob                                   4.1.0     A PHP implementation of Ant's glob.
webmozart/path-util                              2.3.0     A robust cross-platform utility for normalizing, comparing and modifying file paths.

**Comment by sebastianbergmann** [comment]
An annotation such as `@requires PHP >= 8.0` can only prevent a test from being run. By the time that decision is made the test is already loaded. In your case it cannot be loaded with PHP 7.4 because it uses PHP 8 syntax.

You need to prevent that test code which uses PHP 8 syntax from being loaded when PHP 7 is used. This can be achieved by using the [`phpVersion` and `phpVersionOperator` attributes on the `<testsuite/directory>` element in PHPUnit's XML configuration file](https://phpunit.readthedocs.io/en/9.3/configuration.html#the-testsuite-element).

**Comment by simon-schubert** [comment]
Thank you very much!
