### ISSUE TITLE
 PHPunit test fails with `date string and stdout P`

### ISSUE THREAD

**Issue by adhocore** [sebastianbergmann/phpunit#4532]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.4.2
| PHP version         | 7.4.12
| Installation Method | Composer
| Opcache CLI         | On

The failed test is running on docker container extended from official `php:7.4.12-fpm-alpine3.12`.

#### Current behavior

PHPUnit fails and aborts with such output:
```
Testing 
2020-11-29T12:39:48.352939105Z stdout P .....................................
```

#### How to reproduce

--

#### Expected behavior

Should not fail/abort. For reference, the same codebase with the same test cases pass on PHP7.4.11!

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by adhocore** [comment]
it is not an issue when opcache is off. so while it still persists with opcache on, im closing for now as not sure it has to do with phpunit

**Comment by mikhailov012** [comment]
> it is not an issue when opcache is off. so while it still persists with opcache on, im closing for now as not sure it has to do with phpunit

how did you fix it?

**Comment by adhocore** [comment]
not using opcache in tests
