### ISSUE TITLE
Using --testdox with excluded test groups can cause the printer to "hang" until end of tests

### ISSUE THREAD

**Issue by baohx2000** [sebastianbergmann/phpunit#4538]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.0
| PHP version         | 7.4.10
| Installation Method | Composer / PHAR

#### Summary

When running multiple suites of tests and configuring certain groups to be excluded, the testdox printer eventually "hangs" and buffers the rest of the results until the tests are completely finished.

#### Current behavior

See summary.

I did try including the testdoxGroups element in the phpunit.xml file, but it still happened. To fix I had to extend the CliTestDoxPrinter and override the writeProgress method to always pass forceFlush=true to flushOutputBuffer.

#### How to reproduce

I will try to write a PR or phpt which duplicates the issue, but may not be til this weekend. The overall issue is the excluded tests still end up in the `originalExecutionOrder` property, and when it is time to print the test result when the result test index does not match up because of that, the printer just buffers until the final flush() call.

#### Expected behavior

Printer outputs test results as they happen through the entire set.

**Comment by i-bajrai** [comment]
I fixed this by moving the excluded groups to a different folder but I would like to know why its "hanging".

Is this a feature or a bug?

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by sebastianbergmann** [comment]
No feedback, closing.

**Comment by BafS** [comment]
Same issue here, I think it's related to https://github.com/sebastianbergmann/phpunit/issues/3567 and apparently fixed in PHPUnit 10, but I didn't test it

**Comment by Bilge** [comment]
I confirm this problem as well, but it's when combining `--group` and `--exclude-group` _together_, not just using `--exclude-group` alone.
