### ISSUE TITLE
PHPunit not expect generic exception?

### ISSUE THREAD

**Issue by yangzizhe** [sebastianbergmann/phpunit#454]
InvalidArgumentException: You must not expect the generic exception class，
when I test 

class MyTest extends PHPUnit_Framework_TestCase
{
    /**
     \* @expectedException        Exception
     \* @expectedExceptionMessage Some Message
     */
    public function testExceptionHasRightMessage()
    {
        throw new Exception('Some Message', 20);
    }
}

with PHPUnit3.6.7
why ? 

IF PHPunit not expect generic exception , why the document has this example?

**Comment by jtsternberg** [comment]
@srcspider sorry, where would I use that? In the test itself? and if so, what is the `$proc` variable in your example?
