### ISSUE TITLE
PHPunit 9+ when run inside docker can no longer force override env using the XML config

### ISSUE THREAD

**Issue by oppiansteve** [sebastianbergmann/phpunit#4540]
Sorry if this is a known limitation of running PHP unit in Docker since the config parsing restructuring.

| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.0 (and later dev)
| PHP version         | 7.3.24
| Installation Method | Composer

#### Summary

With phpunit 8 we could use config xml such as:
```
<phpunit>
  <php>
    <env name="APP_ENV" value="testing" force="true"/>
  </php>
</phpunit>
```

...and even if the docker instance had `APP_ENV` configured in its environment, we could override it with a new value - as long as `force` is `true`.

Since 9.5 (and I assume 9), this no longer works and we need to change the env on the command line before running phpunit.

(Outside of docker phpunit works as expected)

#### Current behavior

Environment variable is not overwritten.

#### How to reproduce

Need a docker instance such as `composer:1` and install phpunit.
Configure docker to have an env setting and try to override it in a phpunit.xml file.
Have a test that checks/dumps the env setting.

#### Expected behavior

Env setting is overridden

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by oppiansteve** [comment]
sorry, I pressed submit before I had a chance to finish the report in itself.
I'll try to add a dockerfile that reproduces this, but I can't right now

**Comment by sebastianbergmann** [comment]
Please open a new ticket if you can reproduce your problem without Docker.

**Comment by oppiansteve** [comment]
nope, only happens in docker with phpunit 9 and phpunit 8 works fine

**Comment by pablorsk** [comment]
The problem is related to Laravel >= 5.8. And is related with [getenv() and env() returns different results](https://github.com/laravel/framework/issues/16743)

A simple example:

`phpunit.xml`
```
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         bootstrap="tests/autoload.php"
>
    <php>
        <env name="QUEUE_CONNECTION" value="value_on_phpunit_xml" force="true"/>
    </php>
</phpunit>
```

Do, on bash:
```bash
export QUEUE_CONNECTION=value_from_bash
```

Then, you can test on `tests/autoload.php`

```php
<?php
dd(
    getenv('QUEUE_CONNECTION'),
    env('QUEUE_CONNECTION')
);
```

Returns
```
^ "value_on_phpunit_xml"
^ "value_from_bash"
```

Expected behavior
```
^ "value_on_phpunit_xml"
^ "value_on_phpunit_xml"
```

Because Laravel uses env() on config, <env><php> are unuseful.

**Comment by GrahamCampbell** [comment]
Because this is not a bug. It's a feature of Laravel's `env` function. It's not meant to be the same as `getenv`.

**Comment by GrahamCampbell** [comment]
Probably you need to actually set `<server name="APP_ENV" value="testing" force="true"/>` not `env` to see the value.

**Comment by pablorsk** [comment]
It may not necessarily be a bug, but its a problem migrating to Laravel 8 on some scenarios. And the loss of an important advantage of PHPUnit+Laravel.

Using `force=true` flag, dont work. Its used on my previous example.

Also, I try changing `<env>` to `<server>` on `phpunit.xml` like you suggest, but dont work. Even keeping the force flag.

The only solution I have found for now, is force replace config() on `TestCase::setUp()`:

```php
        parent::setUp();
        if ($this->mocks_enabled) {
            $this->mockMarketValues();
        }
        config([
            'queue.default' => 'sync',
        ]);
```

**Comment by judgej** [comment]
I hope this is helpful. It seems that `env()` looks in different places to get its env vars from L7 to L8. In L7 it looks in `$_ENV` and in L8 it looks in `$_SERVER`.

Those two superglobals can be set in `phpunit.xml` using these two engtries in the `<php>` element:

```xml
    <env name="DB_CONNECTION" value="sqlite" force="true"/>
    <server name="DB_CONNECTION" value="sqlite" force="true"/>
```

Protect yourself from upgrades by using *both of these* in your `phpunit.xml`.

* The `getenv()` PHP built-in reports on `$_ENV`.
* The `env()` Laravel function reports on `$_SERVER` from L8, but `$_ENV` up to L7. Your `phpunit.xml` sets these completely independently.

This is really poorly documented IMO.

**Comment by arjenvanoostrum** [comment]
Hi, 

When you use a local docker container, make sure you don't set the "env_file" key in docker-compose.yml to point to your .env file (or have it overwritten with an environment key). These container-level environment variables take precedence over the values loaded by Laravel (i.e. from .env.testing).

So **don't** do the followin in your docker-compose.yml:
```
phpfpm:
  env_file: .env
```
or 
```
phpfpm 
  environment:
    APP_ENV: "testing"
```

or, unset them before running tests:
`unset DB_CONNECTION OR_OTHERS && php artisan config:cache --env=testing && php artisan test`

**Comment by yu-ichiro** [comment]
Adding to @judgej, actually $_ENV is still being read. But the priority between $_SERVER and $_ENV has been changed between Laravel 7→8
(see my comment @ laravel/framework linked above for details)

so basically, if you're using laravel, 

```
<env ... force="true />
```
has to be re-written as 
```
<server ... />
```
in order to achieve preventing of overrides from outer environment variables.

*Notice*  PHPUnit currently only has a feature of forcing `<env>` but not `<server>` (It's actually the opposite for server. **Everything** is forced and environment variables are always overridden.)

**Comment by adamndev** [comment]
Nice one @arjenvanoostrum, helped me figure out why our new docker config had borked out tests.
