### ISSUE TITLE
Replacement for TestListeners

### ISSUE THREAD

**Issue by gjuric** [sebastianbergmann/phpunit#4541]
Since TestListeners are deprecated and are to be removed in version 10 ( #3389 ) I am looking for a suitable replacement.

The newly added TestHooks only notify about the name of the test that is currently being run and not the Test instance itself.

This makes it impossible to hook into the test running process to inject dependencies to a Test instance the way it was used for example in https://github.com/jakzal/phpunit-injector/

Is there another way to hook into this process in version 10?

**Comment by sebastianbergmann** [comment]
No, this is not possible. By design.
