### ISSUE TITLE
assertSame/IsIdentical constraint doesn't compare array keys types

### ISSUE THREAD

**Issue by Danon** [sebastianbergmann/phpunit#4542]
I don't know whether that's intended or not; but I think words like "same" and "identical" should mean it. 

This is totally fine, when array contains `int` vs `string` containing numeric string.

```php
$this->assertSame([1 => '1'], [1 => '1']); // passes
$this->assertSame([1 => '1'], [1 => 1]); // fails
```

But, when the values in question are numeric strings as keys, then the `assertSame()` can't distniguish them.

```php
$this->assertSame([1 => 'foo'], [1 => 'foo']); // passes
$this->assertSame([1 => 'foo'], ['1' => 'foo']); // passes
```

That's because `===` doesn't compare key types

```php
[1 => 'foo'] === ['1' => 'foo'] // that's true
```

You can verify it by calling `array_keys`.
```php
$a = [1 => 'foo'];
$b = ['1' => 'foo'];

$a === $b && array_keys($a) === array_keys($b);
```

**Comment by mfn** [comment]
Are you sure?

I thought it's rather because of PHP itself coercing e.g. integer-looking string keys to integers directly? 🤔

See https://3v4l.org/06XR3

**Comment by Danon** [comment]
Oh, I performed the checks on PHP 7.1, in which it was still possible to get it. In PHP 7.3+ it's not possible anymore, and it always casts to `int`. Sorry, my bad.
