### ISSUE TITLE
Mocking methods with union types on PHP 8 in PHPUnit 8 triggers an error

### ISSUE THREAD

**Issue by driesvints** [sebastianbergmann/phpunit#4543]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.5.12
| PHP version         | 8.0.0
| Installation Method | Composer 

#### Summary

The `deriveReturnType` method in PHPUnit's `MockMethod` class isn't handling PHP 8's new `ReflectionUnionType` properly. The exact place where this bug is happening is here: https://github.com/sebastianbergmann/phpunit/blob/8.5/src/Framework/MockObject/MockMethod.php#L348

Memcached is now included in PHP 8's runtime on GitHub Actions which started running our the Memcached tests for `laravel/framework`. You can see a failing build here: https://github.com/laravel/framework/pull/35647/checks?check_run_id=1571646358#step:8:99

I wanted to look into writing a patch but it seems that the related `sebastian/type` library will need to be patched as well. I thought it might be best to check in here first.

PS: as a side note, would you maybe know why PHPUnit is hiding the stacktrace for the error from the failing build above? It took me quite some time to pinpoint the spot where the bug was happening. A stacktrace would have helped greatly here.

#### Current behavior

`MockMethod` doesn't work when the method has a union return type.

#### How to reproduce

Try to write a test with the following and make sure Memcached is bundled in PHP 8 (and install dependencies using `--prefer-lowest`):

```php
$memcached = $this->getMockBuilder(\Memcached::class)->setMethods(['increment'])->getMock();
```

You'll get the following error: `Error: Call to undefined method ReflectionUnionType::getName()`.

#### Expected behavior

When mocking methods with union return types it's expected that the code doesn't fail on PHP 8.

**Comment by sebastianbergmann** [comment]
This is expected behavior. PHPUnit 8 has been updated to work on PHP 8 for PHP 7 code. It does not and will not support PHP 8 features such as union types.

**Comment by driesvints** [comment]
Hey @sebastianbergmann, understood. I was going to suggest to update https://phpunit.de/supported-versions.html to reflect this but it seems you were ahead of me 😄 https://github.com/sebastianbergmann/phpunit-website/commit/49a44a8ee688d65dc3dcd1ccc9fd8f437a5669d4

**Comment by Krinkle** [comment]
I'd like to note that this errors occurs within a codebase that I would describe as (unmodified) "PHP 7 code".

For example:

```php
        $pdo = $this->createMock(PDO::class);
        $pdo->expects($this->once())->method('prepare')
            ->with('USE `testwiki`;')
            ->willReturn($this->createMock(PDOStatement::class));
```

This is a test in a PHP 7 code base, using PHPUnit 8, and has passed for many years on PHP 7, but started failing on PHP 8 now because `PDO` is a native class that PHP 8 itself has begun defining with native union types on some methods.

These tests fail in a confusing manner:

```
There were 8 errors:

1) AppTest::testGetDB
Error: Call to undefined method ReflectionUnionType::getName()

/Users/krinkle/Development/guc/tests/AppTest.php:12

```

**Comment by sebastianbergmann** [comment]
@Krinkle This is discussed in the comments of https://github.com/sebastianbergmann/phpunit/issues/4879.
