### ISSUE TITLE
PHPUnit feels very slow on Apple Silicon

### ISSUE THREAD

**Issue by marbuser** [sebastianbergmann/phpunit#4560]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.0 (with Laravel)
| PHP version         | 7.4.13
| Installation Method | Composer

#### Summary

I'm not really sure if this qualifies as a bug, but essentially ever since swapping from Intel to Apple Silicon my tests take absolutely forever to run. I'm not sure if there is any compatibility issues, or if this is something on my end (perhaps my install method or something? I have a striking suspicion phpunit might somehow be running through rosetta and that's what's causing the slowdown, but from my searching I've been unable to find anything that says it's running through rosetta).

So I was hoping perhaps there was some kind of benchmark I could run to get an idea of how/why my tests are taking so long or something like that, so I can perhaps try narrow down the problem.

Happy to provide any logs needed or anything like that if this isn't a known compatibility issue. (Couldn't seem to find anything in the issues really.)

#### Current behavior

Tests take absolutely forever to run on apple silicon. Even unit tests I've found take upwards of 5 seconds, where as previous on Intel they would have run in about 5ms 😅 If this is just a compatibility issue so be it, at least I know what it is. What's driving me crazy is knowing whether I can do anything to fix this or not or if it's an issue on my end.

#### How to reproduce

I'm not entirely sure really. Sorta explained most of what I know above. On my old Intel mac tests would run fairly fast. After moving my stuff over to the new one I noticed instantly before I even touched anything that my tests were running a lot slower than before. I sorta just put up with up but I've realised it's really not viable, since if each test takes 5-10 seconds and in some projects I have like 500+ tests, I'm gonna be sitting there all-day 😅 

#### Expected behavior

Faster tests! 😄 (Or I guess normal/expected performance? 🤔 )

**Comment by sebastianbergmann** [comment]
PHPUnit is written in PHP. So what you are trying to report would be: PHP is slow on Apple Silicon.
