### ISSUE TITLE
Introduce trait assertions for Unit 8/9

### ISSUE THREAD

**Issue by exteon** [sebastianbergmann/phpunit#4562]
There is the `assertInstanceOf()` assertion, but it requires `$expected` to be a class or interface; hence it cannot be used to check if an object has a specific trait. Could not find another function that will assert if an object has a specific trait.

I would also like to point out a vulnerability in the current implementation of `assertInstanceOf`: 
It calls `class_exists` and `interface_exists` functions with `$autoload=true` (the default value): https://www.php.net/manual/en/function.class-exists.php
This can cause hidden side-effects by triggering loader actions (especially if one is unit-testing a class loader), which are completely unnecessary and avoidable. If class A was not loaded yet, obviously no instances of it can exist either. I would set `$autoload=false` to avoid the performance overhead and hidden side-effects.

Implementation for traits: https://www.php.net/manual/en/function.class-uses.php - note however, that it does not recursively resolve traits, that has to be implemented

Relevance: much like the current instanceOf assertion: in the context of abstract factories or dependency injection resolutions, one cannot be sure of the built object type, so one might check that an object with the correct traits is properly instanced.

**Comment by sebastianbergmann** [comment]
You do not seem to understand the concept of traits: there is no notion of traits at runtime (embedding classes are oblivious to traits).
