### ISSUE TITLE
Introduce static $actual instanceOf assertion

### ISSUE THREAD

**Issue by exteon** [sebastianbergmann/phpunit#4563]
Much like https://www.php.net/manual/en/function.is-a.php 3rd parameter, it's sometimes useful to probe a class hierarchy without actually instancing the `$actual` class (especially if it is a static-only `abstract` singleton). I know it looks like an anti-pattern, however, it should be testable IMO, I could argue the case for it if needed.

**Comment by sebastianbergmann** [comment]
I do not think that this would be useful.
