### ISSUE TITLE
Deprecate withConsecutive()

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#4564]
See https://github.com/sebastianbergmann/phpunit/issues/4255#issuecomment-636422439 for details.

**Comment by mondrake** [comment]
withConsecutive() is now going from fully available in 9.5 to fully removed in 10.0, with no deprecation process in between to allow projects to react. Shall a deprecation be added to 9.5?

Also see https://www.drupal.org/project/drupal/issues/3306554

**Comment by oleg-andreyev** [comment]
workaround: https://gist.github.com/oleg-andreyev/85c74dbf022237b03825c7e9f4439303

**Comment by TomasVotruba** [comment]
There are around ~10 variations of how PHPUnit `withConsecutive()` can be upgraded. If there is a reference, followed by `willReturn*()` or by `willReturnOnConsecutive()` and more.

Instead of creating answer that fits only one specific quesition, I've put down an article that explains, how to upgrade all kind of combinations.

See:
https://tomasvotruba.com/blog/how-to-upgrade-deprecated-phpunit-with-consecutive

Hopefully you'll find it useful.

It includes PHP 7.* ready code (no `match`), that can be used in PHPUnit 9 (that requires 7.3+)

**Comment by oldy777** [comment]
@TomasVotruba unfortunately your method doesn't work:
```php
->willReturnCallback(function ($parameters) use ($invokedCount) {
        if ($invokedCount->getInvocationCount() === 1) {
            $this->assertSame(['first'], $parameters);
        }

        if ($invokedCount->getInvocationCount() === 2) {
            $this->assertSame(['second'], $parameters);
        }
    });
```
if you have try catch in code:
```php
try{
   weWantMockThisFunction();
} catch (Throwable){}

**Comment by TomasVotruba** [comment]
@oldy777 I see. How do you upgrade your code then?

**Comment by oldy777** [comment]
@TomasVotruba Unfortunately I didn't find good solution :( 
Currently I'm considering 3 options:
1. [Don't use mocks at all](https://blog.frankdejonge.nl/testing-without-mocking-frameworks/)
2. Use mockery
3. Quick fix:
```php
final class UsersUnitTest extends TestCase

    private array $errors = []; // clean after test

    public function testDeleteUsers(): void
    {
        $this->mockFindAndSendData();
        $this->handler->handle($this->createDeleteMessage());

        if($this->errors){
            $this->fail(join(PHP_EOL, $this->errors));
        }
    }
   
   public function mockFindAndSendData(): void
   {
        $invokedCount = self::exactly(2);
        $this->repository->expects($invokedCount)
            ->method('remove')
            ->willReturnCallback(function ($userId) use ($invokedCount, $users) {
                if ($invokedCount->getInvocationCount() === 1) {
                    if ($users[1]->userId() !== $userId) {
                        $this->errors[] = 'remove call 1: Parameter userId expected ' . $users[1]->userId() . ' but got ' . $userId;
                    };
                }

                if ($invokedCount->getInvocationCount() === 2) {
                    if ($users[0]->userId() !== $userId) {
                        $this->errors[] = 'remove call 2: Parameter userId expected ' . $users[0]->userId() . ' but got ' . $userId;
                    };
                }
            });
   }
```

**Comment by TomasVotruba** [comment]
Thanks for sharing 

I personally go always for option 1, as mocks are needed in 1 % of time.
