### ISSUE TITLE
Remove withConsecutive()

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#4565]
Follows #4564.

**Comment by pvandommelen** [comment]
Do I understand the comment correctly that this removal will not be implemented anytime soon?
https://github.com/sebastianbergmann/phpunit/issues/4026#issuecomment-825453794

That would also mean that the deprecation should be reverted from https://github.com/sebastianbergmann/phpunit/commit/dbba41d241cd40edca7f88f9ef42a38fb2455995

**Comment by iammattcoleman** [comment]
Removal of this feature makes it difficult to use PHPUnit to write unit/integration tests that test the code's ability to handle external intermittent failure.

**Comment by sebastianbergmann** [comment]
Moved forward to PHPUnit 10.
