### ISSUE TITLE
Remove code for deprecated functiontionality from TestSuite

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#4566]
In `TestSuite.php` we have this code:

```php
if (count($this->tests) > ++$numTests) {
    $this->addWarning(
        sprintf(
            "Multiple test case classes per file is deprecated\n               in %s",
            $filename
        )
    );
}
```

It is not clear to me from reading the method's code where this fragment is from what code needs to be removed.

**Comment by sebastianbergmann** [comment]
@flow-control Can you help me out here? Thanks!

**Comment by flow-control** [comment]
@sebastianbergmann I can have a look and send a PR remove the functionality

**Comment by sebastianbergmann** [comment]
Thank you!

**Comment by flow-control** [comment]
Hey @sebastianbergmann,

I had a look and found out the following. For the things we deprecated already (multiple test classes per file, test case class not matching file name) I gave deprecation warnings only in `Runner/TestSuiteLoader::load()`, not in `Framework/TestSuite::addTestFile()`, but both functions basically do the same thing. I would like to prepare a PR to remove this duplication and use the `TestSuiteLoader` from the `TestSuite::addTestFile()` method if this okay for you.
Only question left for me is: It would be the polite thing to give a deprecation warning about this also in the the `TestSuite::addTestFile()` method, should I provide an additional PR to PHPUnit 9 for this deprecation warning?
If you like to, we could also have a quick chat about this.

/Florian

**Comment by sebastianbergmann** [comment]
> I had a look and found out the following. For the things we deprecated already (multiple test classes per file, test case class not matching file name) I gave deprecation warnings only in `Runner/TestSuiteLoader::load()`, not in `Framework/TestSuite::addTestFile()`, but both functions basically do the same thing. I would like to prepare a PR to remove this duplication and use the `TestSuiteLoader` from the `TestSuite::addTestFile()` method if this okay for you.

Of course I am okay with that.

> Only question left for me is: It would be the polite thing to give a deprecation warning about this also in the the `TestSuite::addTestFile()` method, should I provide an additional PR to PHPUnit 9 for this deprecation warning?
> If you like to, we could also have a quick chat about this.

Yes, I think we should add that deprecation warning for PHPUnit 9.

Thanks!

**Comment by flow-control** [comment]
> > Only question left for me is: It would be the polite thing to give a deprecation warning about this also in the the `TestSuite::addTestFile()` method, should I provide an additional PR to PHPUnit 9 for this deprecation warning?
> > If you like to, we could also have a quick chat about this.
> 
> Yes, I think we should add that deprecation warning for PHPUnit 9.

Sorry for the inconvenience, I looked in the wrong branch :disappointed: 
The [`9.5` branch already](https://github.com/sebastianbergmann/phpunit/blob/9.5/src/Framework/TestSuite.php#L494) has this deprecation warning.

I created #4570 for the rest :smile:
