### ISSUE TITLE
PHPUnit 8.5 incompatibility with PHP 8.1

### ISSUE THREAD

**Issue by nikic** [sebastianbergmann/phpunit#4575]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.5
| PHP version         | 8.1-dev
| Installation Method | Composer

#### Summary

https://github.com/sebastianbergmann/phpunit/blob/957aaf33dcfb8f0173adb9da1199cffcb16311d8/src/Util/Configuration.php#L443 throws a compile-time error as a result of https://wiki.php.net/rfc/restrict_globals_usage. This issue only exists in PHPUnit 8 and lower, not in PHPUnit 9.

If I understand the purpose of the code right, I think this would be a good way to fix the issue:

```php
foreach ($configuration[$array] as $name => $data) {
    $GLOBALS[$name] = $data['value'];
    $_SERVER[$name] = $data['value'];
    $_POST[$name] = $data['value'];
    $_GET[$name] = $data['value'];
    $_REQUEST[$name] = $data['value'];
    $_COOKIE[$name] = $data['value'];
    $_FILES[$name] = $data['value'];
}
```

In this case the code that tries to abstract over the different arrays makes things more complicated than just directly assigning all of them, due to the special cases that need to be handled.

**Comment by sebastianbergmann** [comment]
Thank you for bringing this to my attention, I will work on this as soon as possible.
