### ISSUE TITLE
Parse @covers of parent-classes too

### ISSUE THREAD

**Issue by ScreamingDev** [sebastianbergmann/phpunit#4576]
PHPUnit has the feature to be strict about covers annotation.
Test subjects may use multiple very commonly used methods.
which would force you to write every single commonly used method in a `@covers` doc-comment.

_(Note: We only talk about methods that can not be mocked for the test)_

Example:

* An abstract class (e.g. `Constraint`) is template for multiple other classes (test subject).
* Several other classes (e.g. test subjects like `IsAnything`, `IsFalse` and 20 more) reuse this abstract class.
* The abstract itself uses tons of commonly used methods (e.g. the `Constraint::__construct` is one).
* With strict coverage you would need to repeat tons of methods in each single test as `@covers` doc-comment.

```php
<?php

/** @covers Constraint::__construct */
class IsAnythingTest extends ConstraintTestCase {}

/** @covers Constraint::__construct */
class IsFooTest extends ConstraintTestCase {}

/** @covers Constraint::__construct */
class IsBarTest extends ConstraintTestCase {}

/** @covers Constraint::__construct */
class IsBazTest extends ConstraintTestCase {}
```

_Note: This example does not ignore the fact that `@covers` can mark a complete class for coverage. But it does not use this to create a scenario where `@covers` need to be repeated way to often in each single test when using the "beStrictAboutCoversAnnotation" feature._

Possible solution:

* `\PHPUnit\Util\Test::getLinesToBeCoveredOrUsed` should not only parse the current test-class but also all it's parents
* By doing this it would also parse the traits of the parents (see `\PHPUnit\Util\Test::parseTestMethodAnnotations` )

Advantage:

```php
<?php

/** @covers Constraint::__construct */
class ConstraintTestCase {}

class IsAnythingTest extends ConstraintTestCase {}
class IsFooTest extends ConstraintTestCase {}
class IsBarTest extends ConstraintTestCase {}
class IsBazTest extends ConstraintTestCase {}
```

The often used methods can be centralized instead of repeating it every time.
It is way easier to make use of the "beStrictAboutCoversAnnotation"-feature with this enhancement.

**Comment by sebastianbergmann** [comment]
It is by design that metadata is not inherited and I would rather not change that.
