### ISSUE TITLE
Confusing situation regarding --testsuite usage

### ISSUE THREAD

**Issue by uuf6429** [sebastianbergmann/phpunit#4578]
Apologies for not filling out the template, but it is not very relevant to the issue.

I read the documentation [here](https://phpunit.readthedocs.io/en/9.3/textui.html) (applies to 9.3, 9.5 and probably earlier) regarding the usage of --testsuite.
Under this [section](https://phpunit.readthedocs.io/en/9.3/textui.html#command-line-options), one sees:
```
Test Selection Options:
  --filter <pattern>          Filter which tests to run
  --testsuite <name>          Filter which testsuite to run
```
But further down, one sees:
<img src="https://user-images.githubusercontent.com/230049/104229011-f3882b80-544b-11eb-8244-d23757e2c642.png" width="400"/>

So one gives the impression that only a name is allowed, and the other that a pattern is allowed. I tried various forms of the pattern unsuccessfully.

After that, I searched in the issues here and found #2273, which gave the impression that either I'm doing something wrong or it's a bug. I've followed the trail to #2281 and #2351 which explains the situation.

To be honest, the approach in #2351 is a bit weird (there are different and more common ways to repeat parameters in cli eg `--arg param1 param2` or `--arg param1 --arg param2`).

But the main point of confusion is the documentation. One says _pattern_, the other says _name_ and in practice it is basically _csv_. 😆

**Comment by kubawerlos** [comment]
> It would be great to have at least wildcard syntax support like `--testsuite=*.unit`

Could be, but as a feature

As a bug it is no longer valid as the `runs the test suite whose name matches the given pattern` was removed in https://github.com/sebastianbergmann/phpunit-documentation-english/commit/a7a5c5b3686ca84158da6e8ea9467224a790da74.

**Comment by uuf6429** [comment]
@kubawerlos thanks for the heads-up, it looks like the description is unambiguous now:

> Only run tests from the specified list of comma-separated test suites that are
> defined in the XML configuration file. See :ref:`organizing-tests.xml-configuration`
> for an example.
