### ISSUE TITLE
PHPUnit 10-dev: previous version cache raises "Argument 2 passed to PHPUnit\Runner\DefaultTestResultCache::setStatus() must be an instance of PHPUnit\Framework\TestStatus\TestStatus, int given, called in ./vendor/phpunit/phpunit/src/Runner/DefaultTestResultCache.php on line 174"

### ISSUE THREAD

**Issue by Slamdunk** [sebastianbergmann/phpunit#4580]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.0.x-dev
| PHP version         | 7.4.14
| Installation Method | Composer

#### Summary

After upgrading to PHPUnit 10-dev with a PHPUnit 9 cache present in `.phpunit.result.cache`, the run fails immediately

#### Current behavior

```
$ vendor/bin/phpunit
Argument 2 passed to PHPUnit\Runner\DefaultTestResultCache::setStatus() must be an instance
of PHPUnit\Framework\TestStatus\TestStatus, int given, called in
./vendor/phpunit/phpunit/src/Runner/DefaultTestResultCache.php on line 174
```

#### Expected behavior

I suggest to either:

1. Check the cache version before using it, and dismiss it if not matching with current runtime
2. Pinpoint to clear the cache in the [ChangeLog-10.0.md](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-10.0.md)

**Comment by Slamdunk** [comment]
Note: we should also check that `php-code-coverage` cache version upgrade works seamlessly.

**Comment by sebastianbergmann** [comment]
I have [changed](https://github.com/sebastianbergmann/phpunit/commit/3e3aecdeb1160de5500fa7715436e73689cc11a3) the implementation of `DefaultTestResultCache` to not use `serialize()` / `unserialize()` at all.
