### ISSUE TITLE
xpected parameter of type 'int', 'false' provided

### ISSUE THREAD

**Issue by applibs** [sebastianbergmann/phpunit#4587]
In Assert.php is code:
use PHPUnit\Framework\Constraint\IsEqual;
...
public static function equalTo($value): IsEqual
    {
        return new IsEqual($value, 0.0, false, false);
    }

and IsEqual from Constraint is like:
public function __construct($value, float $delta = 0.0, int $maxDepth = 10, bool $canonicalize = false, bool $ignoreCase = false)

3. parametr is int and not bool.

**Comment by sebastianbergmann** [comment]
I do not know what version you're looking at, but PHPUnit 9.5 has

```php
public static function equalTo($value): IsEqual
{
    return new IsEqual($value, 0.0, false, false);
}
```

and

```php
final class IsEqual extends Constraint
{
    // ...

    public function __construct($value, float $delta = 0.0, bool $canonicalize = false, bool $ignoreCase = false)
```
