### ISSUE TITLE
"--coverage-text" CLI option is documented wrong

### ISSUE THREAD

**Issue by mvorisek** [sebastianbergmann/phpunit#4590]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.1
| PHP version         | 7.4
| Installation Method | Composer

#### Summary

`--coverage-text <file>` as per https://phpunit.readthedocs.io/en/9.5/textui.html should accept `<file>`. But when `<file>` is set, phpunit fails.

Other formats work well with `<file>` option set.

#### Current behavior

```
PHPUnit 9.5.1 by Sebastian Bergmann and contributors.
Cannot open file "/builds/coverage_phpunit.txt".
```

#### How to reproduce

`phpunit --coverage-text "/builds/coverage_phpunit.txt"`

#### Expected behavior

phpunit does not fail with `Cannot open file "/builds/coverage_phpunit.txt"` message and coverage text output is saved to the given file.

**Comment by sebastianbergmann** [comment]
This was a documentation issue. You need to use `--coverage-text=file` instead of `--coverage-text file`.

**Comment by mvorisek** [comment]
Thanks - other options remain without `=`, right? Is this welcomed to be normalized or you want to keep it like that for BC?

**Comment by sebastianbergmann** [comment]
`--coverage-text` is special in that its parameter is optional. There is nothing to be normalized here.
