### ISSUE TITLE
Deprecate Test Hooks

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#4595]
Deprecate the `PHPUnit\Runner\AfterIncompleteTestHook`, `PHPUnit\Runner\AfterLastTestHook`, `PHPUnit\Runner\AfterRiskyTestHook`, `PHPUnit\Runner\AfterSkippedTestHook`, `PHPUnit\Runner\AfterSuccessfulTestHook`, `PHPUnit\Runner\AfterTestErrorHook`, `PHPUnit\Runner\AfterTestFailureHook`, `PHPUnit\Runner\AfterTestHook`, `PHPUnit\Runner\AfterTestWarningHook`, `PHPUnit\Runner\BeforeFirstTestHook`, `PHPUnit\Runner\BeforeTestHook`, `PHPUnit\Runner\Hook`, `PHPUnit\Runner\TestHook` interfaces and related functionality.

**Comment by IgorSilvSilv** [comment]
can I remove all of them?

**Comment by sebastianbergmann** [comment]
Thank you for offering to help, but I do not need help with this.

**Comment by kelunik** [comment]
@sebastianbergmann Why did you deprecate them and is there any replacement for them? I looked for a replacement of [our event loop reset](https://github.com/amphp/phpunit-util/blob/0c82cb48683e21d5bdf2f2c5a82216aa96182f80/src/AsyncTestCase.php#L42-L57), so not every class needs to extend `AsyncTestCase` and was happy to see extensions are a thing, but then realized they're deprecated now.

**Comment by sebastianbergmann** [comment]
They will be replaced by the new event system.

**Comment by amcsi** [comment]
In case anyone's looking for how to rewrite e.g. BeforeFirstTestHook and AfterLastTestHook to PHPUnit 10...

Before:

```php
use PHPUnit\Runner\AfterLastTestHook;
use PHPUnit\Runner\BeforeFirstTestHook;

class Bootstrap implements BeforeFirstTestHook, AfterLastTestHook
{
    public function executeBeforeFirstTest(): void
    {
        // ...
    }

    public function executeAfterLastTest(): void
    {
        // ...
    }
}
```

After:
```php
use PHPUnit\Event\TestRunner\Finished;
use PHPUnit\Event\TestRunner\FinishedSubscriber;
use PHPUnit\Event\TestRunner\Started;
use PHPUnit\Event\TestRunner\StartedSubscriber;
use PHPUnit\Runner\Extension\Extension as PhpunitExtension;
use PHPUnit\Runner\Extension\Facade as EventFacade;
use PHPUnit\Runner\Extension\ParameterCollection;
use PHPUnit\TextUI\Configuration\Configuration;

class Bootstrap implements BeforeFirstTestHook, AfterLastTestHook
{
    public function executeBeforeFirstTest(): void
    {
        // ...
    }

    public function executeAfterLastTest(): void
    {
        // ...
    }

    public function bootstrap(Configuration $configuration, EventFacade $facade, ParameterCollection $parameters): void
    {
        $facade->registerSubscriber(new class($this) implements StartedSubscriber {
            public function __construct(private Bootstrap $thisClass)
            {
            }

            public function notify(Started $event): void
            {
                $this->thisClass->executeBeforeFirstTest();
            }
        });
        $facade->registerSubscriber(new class($this) implements FinishedSubscriber {
            public function __construct(private Bootstrap $thisClass)
            {
            }

            public function notify(Finished $event): void
            {
                $this->thisClass->executeAfterLastTest();
            }
        });
    }
}
```

**Comment by Luc45** [comment]
https://www.youtube.com/watch?v=VvPaEsuz-tY
