### ISSUE TITLE
Remove Test Hooks

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#4596]
Remove the `PHPUnit\Runner\AfterIncompleteTestHook`, `PHPUnit\Runner\AfterLastTestHook`, `PHPUnit\Runner\AfterRiskyTestHook`, `PHPUnit\Runner\AfterSkippedTestHook`, `PHPUnit\Runner\AfterSuccessfulTestHook`, `PHPUnit\Runner\AfterTestErrorHook`, `PHPUnit\Runner\AfterTestFailureHook`, `PHPUnit\Runner\AfterTestHook`, `PHPUnit\Runner\AfterTestWarningHook`, `PHPUnit\Runner\BeforeFirstTestHook`, `PHPUnit\Runner\BeforeTestHook`, `PHPUnit\Runner\Hook`, `PHPUnit\Runner\TestHook` interfaces and related functionality.

**Comment by IgorSilvSilv** [comment]
I will do it

**Comment by sebastianbergmann** [comment]
Thank you for offering to help, but I do not need help with this.

**Comment by IgorSilvSilv** [comment]
Ok

**Comment by remorhaz** [comment]
@sebastianbergmann, I see that Test Hooks will be deprecated in PHPUnit 10 and removed in PHPUnit 11. My extensions are currently using Test Hooks, so I'm wondering what will be the right way of extending the test runner?

**Comment by sebastianbergmann** [comment]
That will be the new event system that will be introduced in PHPUnit 10.
