### ISSUE TITLE
An ability to conditionally repeat current test

### ISSUE THREAD

**Issue by remorhaz** [sebastianbergmann/phpunit#4597]
Sometimes while running a test we can discover a situation when the test should be repeated. For example, Selenium API call returns 503 because of redeployment, or some other temporary state that ruins our test occurs. In such case it would be very convenient to re-run this particular test. This ability could greatly increase the stability of test runs in fragile environments!

PHPUnit runner has `--repeat` option, but it's not effective in this case because it just runs each test several times non-conditionally and if any of attempts fail - all the test run fails.

Technically this probably could be done by adding `TestCase::repeatCurrentTest()` method that will throw some special exception that could be caught within `TestResult::run()` method. The handling of that exception should include repeated invocation of `$test->runBare()` until either test runs successfully or hits the limit of allowed amount of attempts.

If you find this idea helpful, I can try to experiment with an implementation to research a practical possibility of adding this behavior to PHPUnit.

**Comment by sebastianbergmann** [comment]
I do not think that this type of functionality should be implemented in PHPUnit itself.
