### ISSUE TITLE
Unify cache configuration

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#4599]
A `phpunit.xml` configuration file that uses best practice defaults (as generated using `--generate-configuration`) for PHPUnit 9.5 looks like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.5/phpunit.xsd"
         bootstrap="vendor/autoload.php"
         cacheResultFile=".phpunit.cache/test-results"
         executionOrder="depends,defects"
         forceCoversAnnotation="true"
         beStrictAboutCoversAnnotation="true"
         beStrictAboutOutputDuringTests="true"
         beStrictAboutTodoAnnotatedTests="true"
         failOnRisky="true"
         failOnWarning="true"
         verbose="true">
    <testsuites>
        <testsuite name="default">
            <directory suffix="Test.php">tests</directory>
        </testsuite>
    </testsuites>

    <coverage cacheDirectory=".phpunit.cache/code-coverage"
              processUncoveredFiles="true">
        <include>
            <directory suffix=".php">src</directory>
        </include>
    </coverage>
</phpunit>
```

The `cacheResultFile` attribute of the `<phpunit>` root element (as well as the `--cache-result-file <file>` CLI option) is used to configure the file where the PHPUnit test runner stores its test result cache.

The `cacheDirectory` attribute of the `<coverage>` element (as well as the `--coverage-cache <dir>` CLI option) is used to configure the directory where static analysis results for code coverage are cached.

In the future, there will be more "things" we would like to cache. I therefore propose the following:

* Deprecate the  `cacheResultFile` attribute of the `<phpunit>` root element (as well as the `--cache-result-file <file>` CLI option) in PHPUnit 10 ([and remove support for it in PHPUnit 11](https://github.com/sebastianbergmann/phpunit/issues/4600))
* Deprecate the `cacheDirectory` attribute of the `<coverage>` element (as well as the `--coverage-cache <dir>` CLI option) in PHPUnit 10 ([and remove support for it in PHPUnit 11](https://github.com/sebastianbergmann/phpunit/issues/4600))
* Introduce the `cacheDirectory` attribute on the `<phpunit>` root element (as well as the `--cache-directory <dir>` CLI option) for configuring a single root directory for cache directories and cache files used by the PHPUnit test runner in PHPUnit 10
* Change `--generate-configuration` to generate the following

```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/10.0/phpunit.xsd"
         bootstrap="vendor/autoload.php"
         cacheDirectory=".phpunit.cache"
         executionOrder="depends,defects"
         forceCoversAnnotation="true"
         beStrictAboutCoversAnnotation="true"
         beStrictAboutOutputDuringTests="true"
         beStrictAboutTodoAnnotatedTests="true"
         failOnRisky="true"
         failOnWarning="true"
         verbose="true">
    <testsuites>
        <testsuite name="default">
            <directory suffix="Test.php">tests</directory>
        </testsuite>
    </testsuites>

    <coverage processUncoveredFiles="true">
        <include>
            <directory suffix=".php">src</directory>
        </include>
    </coverage>
</phpunit>
```

**Comment by awslabspl** [comment]
Agrred
