### ISSUE TITLE
Remove support for old cache configuration

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#4600]
* Remove the  `cacheResultFile` attribute of the `<phpunit>` root element (as well as the `--cache-result-file <file>` CLI option)
* Remove the `cacheDirectory` attribute of the `<coverage>` element (as well as the `--coverage-cache <dir>` CLI option)

**Comment by awslabspl** [comment]
@sebastianbergmann why would you want to remove old config? Someone may want to use it.....
