### ISSUE TITLE
Remove assertions that operate on class/object properties

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#4602]
The following methods of `PHPUnit\Framework\Assert` will be removed in PHPUnit 11:

* `assertClassHasAttribute()`
* `assertClassNotHasAttribute()`
* `assertClassHasStaticAttribute()`
* `assertClassNotHasStaticAttribute()`
* `assertObjectHasAttribute()`
* `assertObjectNotHasAttribute()`
* `classHasAttribute()`
* `classHasStaticAttribute()`
* `objectHasAttribute()`

The following classes will be removed in PHPUnit 11:

* `PHPUnit\Framework\Constraint\ClassHasAttribute`
* `PHPUnit\Framework\Constraint\ClassHasStaticAttribute`
* `PHPUnit\Framework\Constraint\ObjectHasAttribute`

This follows #4601.

**Comment by jrfnl** [comment]
Just checking: is the "PHPUnit 10" in the above issue correct or should this be "PHPUnit 11" ?

**Comment by sebastianbergmann** [comment]
> Just checking: is the "PHPUnit 10" in the above issue correct or should this be "PHPUnit 11" ?

Thank you for pointing this out. I have updated the issue to say "PHPUnit 11".

**Comment by sebastianbergmann** [comment]
Moved forward to PHPUnit 10.
