### ISSUE TITLE
Adding more details to --testdox-html output

### ISSUE THREAD

**Issue by vjandrea** [sebastianbergmann/phpunit#4605]
Right now the result of a test in the HTML testdox report is binary: success / failure, while I think it might be useful to distinct between failures, errors, skipped, incomplete, risky.
May I propose a PR for this ?

**Comment by sebastianbergmann** [comment]
To be honest, I would rather not expand the existing HTML report. The TestDox XML report should have all relevant information and HTML could be generated from that, using XSLT, for instance.

**Comment by vjandrea** [comment]
Ok I'll give a shot to the XSLT route then. Thanks @sebastianbergmann

**Comment by vjandrea** [comment]
By the way, @sebastianbergmann  do you have a suggested XSLT toolchain on Windows? Looks like the available open source tools are quite outdated if not abandoned, stuck to XSLT 1.0.

**Comment by vjandrea** [comment]
Unfortunately the limited open-source XSLT toolkit available on Windows, and the way the XML output is organized, require too many workarounds.
As an example, since the test results are not grouped by test class, and the open source XSLT transform binaries available support only XSLT 1.0, the template becomes too verbose because advanced features as `xsl:for-each-group` are unavailable.

I am still convinced that we could have more information in the testdox HTML output itself, instead of looking for workarounds if they're not universally available.
