### ISSUE TITLE
Feature request: assertStrictEquals 

### ISSUE THREAD

**Issue by BackEndTea** [sebastianbergmann/phpunit#4611]
## The problem

Currently, phpunit has two ways of making sure variables are the same. `assertEquals`, and `assertSame`. Doing `==` and `===` checks respectively.

The problem comes when we are comparing objects. We can't always use assertSame, as we may not be able to provide the desired object beforehand. So we use `assertEquals` there. This however leads to problems in code where the properties of a class may not be a single type. Which can be due to union types, or just because of legacy code.

```php
// https://3v4l.org/PpqMI
class Problem
{
    public function __construct(
        private bool|string $issue
    ) {}
}

var_dump(new Problem(true) == new Problem('There is a problem')); // true
```

## The solution

I'd like to propose a new assertion: `assertStrictEqals`. Which would check every property to be exactly the same. on the two objects. This is already featured in other test frameworks like [jest](https://jestjs.io/docs/en/expect#tostrictequalvalue).

Is this something that could be implemented in PHPUnit? If so i'd be happy to provide a PR for it

**Comment by sebastianbergmann** [comment]
I do not think that a generic comparison of objects based on properties is useful and PHPUnit already has two ways for comparing objects: `assertEquals()` with custom comparators and [assertObjectEquals](https://github.com/sebastianbergmann/phpunit/issues/4467#issue-707434038).

**Comment by BackEndTea** [comment]
Turns out i've misunderstood how assertEquals operates. And it basically does what i wanted it to do for object all along 😅 .

**Comment by webmozart** [comment]
@BackEndTea IMO `assertEquals()` is very helpful for these kinds of comparisons, as its output is much more helpful when comparisons fail compared to `assertObjectEquals()`. If you want to continue using `assertEquals()` but with type safety, I recommend using my [StrictPHPUnitExtension](https://github.com/webmozarts/strict-phpunit).
