### ISSUE TITLE
Remove final modifier from the TestRunner class

### ISSUE THREAD

**Issue by raszi** [sebastianbergmann/phpunit#4613]
Hi,

I am working on a PHPUnit bisect feature, similar to [RSpec bisect](https://relishapp.com/rspec/rspec-core/docs/command-line/bisect). I have a working version but I would like to use the current codebase as much as possible. And while I was doing the refactoring I ran into an issue.

I wanted to extend the `TestRunner` class to add the bisect functionality around it but unfortunately that class is marked as `final`. Is there any chance that you could remove that modifier so I could extend it in my codebase?

**Comment by sebastianbergmann** [comment]
I do not want to remove the `final` modifier at this time. Also note that this class is annotated with `@internal This class is not covered by the backward compatibility promise for PHPUnit`. In the future, once the test runner has been refactored more (or even rewritten), I will be open to allow extension such as the one you have in mind. Until then: sorry!

**Comment by raszi** [comment]
Well that sucks, since then I cannot add my functionality properly. Could you please provide me some insight about when you are going to refactor/rewrite the `TestRunner`?

Thank you!
