### ISSUE TITLE
PHP 8.0: Deprecate required parameters after optional parameters in function/method signatures

### ISSUE THREAD

**Issue by romanstingler** [sebastianbergmann/phpunit#4615]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.2
| PHP version         | 8.0.3
| Installation Method | Composer

#### Summary

when runnig tests via phpunit I don't get php8 deprecation warnings. 
With paratest the test fails immediately.
<a href="https://ibb.co/8d95F5L"><img src="https://i.ibb.co/8d95F5L/Screenshot-from-2021-03-09-08-58-43.png" alt="Screenshot-from-2021-03-09-08-58-43" border="0"></a>
#### How to reproduce

try code example from 
https://php.watch/versions/8.0/deprecate-required-param-after-optional

#### Expected behavior

display php deprecation warnings

**Comment by romanstingler** [comment]
I found out that the default paratest doesn't display any issues but the laravel wrapper does. 
https://laravel.com/docs/8.x/testing#running-tests-in-parallel

I added a .zip just extract go into the test folder and run 
`phpunit`   
or 
`./artisan test --parallel`
also the command
`./artisan test` misses the deprecation
![Screenshot from 2021-03-09 13-33-25](https://user-images.githubusercontent.com/5576250/110471705-b99a7500-80dc-11eb-853c-be80e6efb58b.png)



[deprecation.zip](https://github.com/sebastianbergmann/phpunit/files/6108503/deprecation.zip)

**Comment by sebastianbergmann** [comment]
Sorry, but a ~ 11 MB ZIP archive is not what I consider to be minimal.

**Comment by sebastianbergmann** [comment]
No feedback, closing.
