### ISSUE TITLE
Support for generators in assertCount() etc. is not marked as deprecated in PHPUnit 9.6

### ISSUE THREAD

**Issue by eigan** [sebastianbergmann/phpunit#4618]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 2bc4a059f3de2ab93eab26c0b82e1e33f11c4dae
| PHP version         | 7.4.16
| Installation Method | Git clone

## Summary

I am aware that using generators in count related assertions is deprecated, but there seems to be some cases where it has not been deprecated properly(?)

### assertNotEmpty with empty generator, no warning

```php
self::assertNotEmpty((fn(): Generator => yield [])());
#> Success
```
:x: _Should trigger warning as this doesn't even work._

### assertNotEmpty with non-empty generator

```php
self::assertNotEmpty((fn(): Generator => yield from ['ok'])())
#> Success
```
:x: _Should trigger warning._

### assertEmpty with empty generator
```php
self::assertEmpty((fn(): Generator => yield [])());
#> Failed asserting that an object is empty.
```
🆗 _Could argue that this is ok as it sort-of says that Generators are not supported._

### assertCount with empty generator
```php
self::assertCount(0, (fn() => yield [])());
#> Failed asserting that actual size 0 matches expected size 0.
```
❓ Weird.

### assertCount with generator where assertion fails
This is just weird and might not be relevant.
```php
self::assertCount(0, (fn() => yield from ['foo'])());
#> Failed asserting that actual size 0 matches expected size 0.
```
🆗 _Asserting count is 1 will make this test pass and a warning will be sent._

## Expected behavior

Warning with the message:
> Passing an argument of type Generator for the $haystack parameter is deprecated. Support for this will be removed in PHPUnit 11.

Related to #4568

**Comment by sebastianbergmann** [comment]
These depecations were originally planned for PHPUnit 10 with removal of support for generators in the functionality in question planned for PHPUnit 11. However, this functionality was now already removed in PHPUnit 10.

This functionality needs to be marked as deprecated in PHPUnit 9.6.
