### ISSUE TITLE
Please, do not deprecate test case class not matching filename

### ISSUE THREAD

**Issue by d3ce1t** [sebastianbergmann/phpunit#4621]
In my team we have tests and regular classes living together in the same PHP namespace and file system tree.

Something like this:

Class file at `app/Domain/Order.php`
```php
namespace App\Domain;

class Order {
   // Business logic
}
```

Test file at `app/Domain/Order.test.php`
```php
namespace App\Domain;

use PHPUnit\Framework\TestCase;

class OrderTest extends TestCase  {
    public function testSomethingImportant()
    {
         $order = new Order(...);
         // Do something and test order
    }
   // More tests
}
```

It works very well for us. Tests are first-class citizens in our code base and it's very handy to have them in the same place where the logic of your application is (besides it reduces source tree navigation). We also use tests as examples about how to use a class or what expectations/assumptions are done.

However, as you can see, test filename (`Order.test.php`) doesn't match the name of the test class (`OrderTest`). We need this to avoid collision between test case class and our business logic class. That way we can use `Order` class from `OrderTest` class with no pain.

As of PHPUnit 9.5.2, this is what you get (pay attention to the warning):

```console
/app $ ./vendor/bin/phpunit --filter OrderTest:: --test-suffix ".test.php" ./app/Orders/Domain
PHPUnit 9.5.2 by Sebastian Bergmann and contributors.


Warning:       Test case class not matching filename is deprecated
               in /app/app/Orders/Domain/Order.test.php
               Class name was 'OrderTest', expected 'Order'

.                                                                   1 / 1 (100%)

Time: 00:00.146, Memory: 28.00 MB

OK (1 test, 1 assertion)
```

**Comment by sebastianbergmann** [comment]
The decision has been made, the functionality was deprecated in PHPUnit 9 and removed in PHPUnit 10.

**Comment by d3ce1t** [comment]
Could you give us a clue about how to support this scenario in PHPUnit 10?

**Comment by mfn** [comment]
> Test file at `app/Domain/Order.test.php`

Maybe it's too obvious 🤪 but can you just name this file `app/Domain/OrderTest.php`?

And with the `testsuites` XML it should be possible to define a filter definition to only consider `**/*Test.php` files or so? 🤔

**Comment by d3ce1t** [comment]
> > Test file at `app/Domain/Order.test.php`
> 
> Maybe it's too obvious  but can you just name this file `app/Domain/OrderTest.php`?
> 
> And with the `testsuites` XML it should be possible to define a filter definition to only consider `**/*Test.php` files or so?

Thank for your question! The reason why we need both `Order.test.php` and `Order.php` to have the same name is just visibility:

For instance, compare this:

![image](https://user-images.githubusercontent.com/3706385/110975259-cda1d900-835f-11eb-93f0-661bdd18b951.png)

And this:

![image](https://user-images.githubusercontent.com/3706385/110975150-a2b78500-835f-11eb-8c68-82e32d750a95.png)

They are together or separated depending on other's filenames.

**Comment by mfn** [comment]
You can try `_` as a separator, maybe it gets sorted similar to `.` _and_ you can use it part of the test name. Though this might trigger other issues, IDK. 

With your naming schema you're not concerned about PSR-4 anyway.

No matter how you put it, the ship definitely has sailed.

**Comment by d3ce1t** [comment]
> You can try `_` as a separator, maybe it gets sorted similar to `.` _and_ you can use it part of the test name. Though this might trigger other issues, IDK.

I will give it a try. At least it keeps them together

![image](https://user-images.githubusercontent.com/3706385/110976307-08584100-8361-11eb-982b-2bd65df7456b.png)

**Comment by d3ce1t** [comment]
@mfn Thanks! It works :)

Just an example in case it helps somebody:

Class file at `app/Domain/Order.php`
```php
namespace App\Domain;

class Order {
   // Business logic
}
```

Test file at `app/Domain/Order_test.php`
```php
namespace App\Domain;

use PHPUnit\Framework\TestCase;

class Order_Test extends TestCase  {
    public function testSomethingImportant()
    {
         $order = new Order(...);
         // Do something and test order
    }
   // More tests
}
```

**Comment by mfn** [comment]
Happy it works for you!

One more suggestion: 
> Test file at `app/Domain/Order_test.php`
…

> class Order_Test extends TestCase  {

I really, highly, suggest to name the file `Order_Test.php` (uppercase `Test`) like in the class.

I think down the road having a match between the class and the file name will be less troublesome.

Anyway: 🤞
