### ISSUE TITLE
Tests fail with PHP 8.1 on GitHub Actions

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#4622]
The builds with PHP 8.1 on GitHub Actions currently fail because PHP prints
```
malloc_consolidate(): invalid chunk size
Aborted (core dumped)
```
which leads to PHPT test failing as their assertions operate on PHP output:

* https://github.com/sebastianbergmann/phpunit/runs/2093832283#step:12:75
* https://github.com/sebastianbergmann/phpunit/runs/2093832283#step:12:95
* https://github.com/sebastianbergmann/phpunit/runs/2093832283#step:12:115
* ...

I cannot reproduce this locally using PHP 8.1 built from source by myself.

I do not know whether this is an issue in PHP 8.1 itself, whether this is an issue in @shivammathur / `setup-php`, or whether something weird is going on in the Linux container used on GitHub Actions.

**Comment by shivammathur** [comment]
@sebastianbergmann I have added the commit hash in logs for PHP 8.1 on ubuntu (shivammathur/setup-php#433)
PHP 8.1 is build from master branch without any patches. The libraries used are from `ppa:ondrej/php`.
So the bug should be in PHP 8.1 or some library incompatibility that got introduced recently.

I have rebuilt PHP 8.1 with debugging symbols, so please try to generate the traceback in your workflow.

**Comment by shivammathur** [comment]
@sebastianbergmann 
This is failing when pcov is enabled.
https://github.com/shivammathur/test-setup-php/runs/2104382772?check_suite_focus=true#step:7:75

I'm not familiar with pcov internals, so not sure how to patch this. I would suggest reporting this upstream and switching to Xdebug for coverage on PHP 8.1 till this is fixed.

**Comment by sebastianbergmann** [comment]
CC @krakjoe

**Comment by sebastianbergmann** [comment]
> This is failing when pcov is enabled.

Thanks! I am now able to reproduce this locally.

**Comment by sebastianbergmann** [comment]
@krakjoe Would you like me to open a ticket for PCOV? If so, what information do you need beside what's already here? Thanks!

**Comment by sebastianbergmann** [comment]
I opened https://github.com/krakjoe/pcov/issues/59.
