### ISSUE TITLE
Test passes regardless real return value

### ISSUE THREAD

**Issue by awslabspl** [sebastianbergmann/phpunit#4627]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.2
| PHP version         | 7.4
| Installation Method | PHAR
#### Summary

Unable to test REAL return value

#### Current behavior

See above + no matter what I put as an assertion, test always passes
```php
 self::assertIsString("Test resul", "Passed");
```
#### How to reproduce

```php
 public function testListAllBuckets()
    {
        require '../../Utils/php/libs/s3/ListBuckets.php';
        $lb = new ListBuckets();
/*        $mcom = $this->createMock(ListBuckets::class);
        $mcom->method('ListAllBuckets')->willReturn("Test result");*/
        self::assertIsString("Test resul", "Passed");
    }
```
just try running this code

#### Expected behavior

Test returning OK ( pass ) when provided value equals value returned, or fail if values are not equal

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.

**Comment by awslabspl** [comment]
> This is not a discussion or support forum, sorry.

If so, where to get support?
