### ISSUE TITLE
Support for named arguments in test double configuration/expectations

### ISSUE THREAD

**Issue by thiagocordeiro** [sebastianbergmann/phpunit#4628]
Currently using named properties work just fine on method call assertions, but random order is ignored and parameters are asserted by the sequential order.

Would be good to be able to assert params values regardless of their order, the examples above show different param orders that could be recognized by phpunit.

Ex 1.
```php
$this->foo
    ->expects($this->once())
    ->method('bar')
    ->with(foo: 'foo', bar: 'bar'); // foo placed first
```
Ex 2.
```php
$this->foo
    ->expects($this->once())
    ->method('bar')
    ->with(bar: 'bar', foo: 'foo'); // foo placed after
```

**Comment by sebastianbergmann** [comment]
While I agree that named arguments can help with writing code that uses old/weird APIs, especially that of some built-in functions in PHP, I do not think that named parameters should be used in (new) PHP code. Therefore I will not work on this myself, but, of course, I will consider a pull request that implements this functionality.

**Comment by sebastianbergmann** [comment]
No feedback, closing.
