### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function each()

### ISSUE THREAD

**Issue by skfahad** [sebastianbergmann/phpunit#4629]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.3 
| PHP version         | 8.0
| Installation Method | Composer / PHAR

#### Summary

Upon executing `phpunit` which should show me test results, I get error instead stating

`Fatal error: Uncaught Error: Call to undefined function each() in C:\xampp\php\pear\PHPUnit\Util\Getopt.php:80`

I have mentioned phpunit version from composer.lock file. When I try to run `phpunit --version` to get phpunit version I get the same error.

I found this command `composer exec phpunit` which worked for me and tested my function.

I have installed orchestra through composer using `composer require --dev "orchestra/testbench` command then I configure my `phpunit.xml` as follows

`<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="./vendor/phpunit/phpunit/phpunit.xsd"
         bootstrap="vendor/autoload.php"
         colors="true"
>
    <testsuites>
        <testsuite name="Unit">
            <directory suffix="Test.php">./tests/Unit</directory>
        </testsuite>
        <testsuite name="Feature">
            <directory suffix="Test.php">./tests/Feature</directory>
        </testsuite>
    </testsuites>
    <coverage processUncoveredFiles="true">
        <include>
            <directory suffix=".php">./src</directory>
        </include>
    </coverage>
</phpunit>`

But `phpunit` is not working

**Comment by sebastianbergmann** [comment]
It appears that you have different installations of PHPUnit mixed up.

For instance, you may have used Composer to install PHPUnit and have configured the autoloader generated by Composer as PHPUnit's bootstrap script but then you invoke PHPUnit using an executable other than `vendor/bin/phpunit`.
