### ISSUE TITLE
 processIsolation="true" leads to: Uncaught SebastianBergmann\CodeCoverage\NoCodeCoverageDriverAvailableException

### ISSUE THREAD

**Issue by aqua-calc** [sebastianbergmann/phpunit#4631]
PHPUnit 9.5.4 by Sebastian Bergmann and contributors.
PHP Version 7.4.14; CentOS 8.3
How to reproduce: Specify processIsolation="true" in phpunit.xml

Error:
Uncaught SebastianBergmann\CodeCoverage\NoCodeCoverageDriverAvailableException: No code coverage driver available in .../vendor/phpunit/php-code-coverage/src/Driver/Selector.php:53

Syntax used:
vendor/phpunit/phpunit/phpunit \
--prepend build/xdebug-filter.php \
--stderr \
--bootstrap bootstrap.php \
--configuration phpunit.xml \
--teamcity

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by aqua-calc** [comment]
Thank you for your reply.

I'll see what I can do to provide the requested information.
