### ISSUE TITLE
[Feature Request] Assert::markTestSuccessful()

### ISSUE THREAD

**Issue by MalteWunsch** [sebastianbergmann/phpunit#4640]
The problem: Sometimes when you have failing tests, you just want to get rid of the red. Currently, we only have Assert::markTestSkipped or markTestIncomplete for that, but these methods make the tests either yellow or some kind of turquoise. That's suboptimal.

Suggested solution: Introduce a new method Assert::markTestSuccessful() that makes the test green. As a side benefit, this may speed up a lot of slow running tests.

WDYT?

**Comment by sebastianbergmann** [comment]
Sorry, but this makes no sense to me.

**Comment by MalteWunsch** [comment]
Just to be clear: today, on the SECOND of april, this doesn't make any sense to me either ;-)

Thanks and I hope you had a great April Fools' day.

**Comment by epdenouden** [comment]
`Date`-handling is already marked Risky in our books, so we did not dare laugh for fear of breaking some barely maintained library somewhere.

Also, we prefer immutable value objects, so if you want to do this properly you'd to make a new ticket and refer this one. We are a bit picky about these sorts of things.

In conclusion I would suggest I implement `ComplexTestStatus` which will allow for your silliness to be marked _Incomplete_, _Skipped_ and dare I say _Failed_. No worries though: if you enable reordering by defects it will speed up your runs even more!
