### ISSUE TITLE
PHPUnit --version results in a parse error: syntax error, unexpected token "match" on Windows 10 Pro PC

### ISSUE THREAD

**Issue by Novocastrian** [sebastianbergmann/phpunit#4654]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.5
| PHP version         | 8.0.3
| Installation Method | PHAR

#### Summary
I installed PHPUnit via [these instructions](https://perials.com/installing-phpunit-windows/). `phpunit --version` results in the following error:
`Parse error: syntax error, unexpected token "match", expecting identifier in phar://C:/bin/phpunit.phar/phpunit-mock-objects/Builder/Match.php on line 15`. I don't know how to open this directory, so can't help here. Sorry!

This device is not behind a VPN or Proxy. 

#### Current behavior

`phpunit --v` errors with `Parse error: syntax error, unexpected token "match", expecting identifier in phar://C:/bin/phpunit.phar/phpunit-mock-objects/Builder/Match.php on line 15`.

#### How to reproduce

1. Install PHPUnit via [these instructions](https://perials.com/installing-phpunit-windows/)
2. Open CMD with admin rights
3. run `phpunit --version`
![image](https://user-images.githubusercontent.com/4601813/115327291-02604600-a1d2-11eb-9045-55f4f529d5af.png)

#### Expected behaviour

Install PHPUnit successfully.

**Comment by sebastianbergmann** [comment]
PHPUnit 6 is not supported on PHP 8.

**Comment by Novocastrian** [comment]
Ah, didn't think to test that. Thanks for the clarification.

**Comment by htazad** [comment]
Using the PHPUnit 9.5.1 version solved the issue.
