### ISSUE TITLE
Can not get HTTP Status code in WP_Ajax_UnitTestCase

### ISSUE THREAD

**Issue by skydev2020** [sebastianbergmann/phpunit#4659]
#### Summary

I am using PHPUnit /WP_Ajax_UnitTestCase.
And Rest Api is defined in wordpress.

In Api Side I am sending status code along with message like this.

`wp_send_json_error( 'Keyword already exists.', 409 ); // Meaning it has conflict.`

And in PhpUnit, I created Text class extending WP_Ajax_UnitTestCase. I am trying to get the message using this code.

```
try {
    $this->_handleAjax('action_name');
} catch ( WPAjaxDieContinueException $e ) {
}
 error_log($this->_last_response);
error_log("\n");

$response = json_decode( $this->_last_response );
```
_last_response only contains data not status code like this. {"success":false,"data":"Keyword already exists."}

Any Idea how to catch the status code? When I test in browser I can get 409 status.

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry. Please raise `WP_` issues with the respective vendor.

**Comment by skydev2020** [comment]
@sebastianbergmann 
You mean WP_Ajax_UnitTestCase is not part of PHPUnit framework?

**Comment by sebastianbergmann** [comment]
No, it is not.
