### ISSUE TITLE
error: mod_fcgid: stderr: PHP Fatal error: strict_types declaration must be the very first statement in the script in 

### ISSUE THREAD

**Issue by EvWoDev** [sebastianbergmann/phpunit#4660]
I get this error: mod_fcgid: stderr: PHP Fatal error: strict_types declaration must be the very first statement in the script in /var/www/vhosts/MYCOMPANY.nl/public_html/wp-content/plugins/woocommerce/lib/packages/League/Container/Container.php on line 1

What can i do i only cant access the site from my IP other IP`s can acces the site
PHP On (version: 7.4.16

**Comment by daanvw073** [comment]
Before it i get this error 

Error | MY IP| 500 | GET / HTTP/1.0
-- | -- | -- | --

**Comment by sebastianbergmann** [comment]
This has nothing to do with PHPUnit.
