### ISSUE TITLE
How to hide the spinner when using --group?

### ISSUE THREAD

**Issue by BenMorel** [sebastianbergmann/phpunit#4667]
I'm using PHPUnit with `--testdox`:

    vendor/bin/phpunit --testdox --testsuite integration

This works fine, and outputs tests as they are executed. If, however, I restrict the tests to a particular `@group`:

    vendor/bin/phpunit --testdox --testsuite integration --group external-api

then I only see a spinner while the tests are being executed:

> PHPUnit 9.5.4 by Sebastian Bergmann and contributors.
> 
> Testing 
> 
> ◐ running tests

and the output from all tests is shown all at once, when all tests have passed.

**Can I prevent this buffering when using `--group`?**

**Comment by sebastianbergmann** [comment]
The TestDox output is buffered (and you see a spinner) when the order in which tests are executed is modified, for instance when you execute tests in random order.

**Comment by BenMorel** [comment]
Thanks for your reply, @sebastianbergmann. I don't get it, though: I'm not modifying the order in which tests are executed, I'm just restricting tests to a particular group. Is there a solution to get the realtime output back?
