### ISSUE TITLE
Event System for extending PHPUnit

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#4676]
### The `TestListener` Interface

[First](http://svn.php.net/viewvc/pear/packages/PHPUnit/tags/RELEASE_0_3/PHPUnit_TestListener.php?revision=88454&view=markup&pathrev=319096), there was the `PHPUnit\Framework\TestListener` interface:

```php
interface TestListener
{
    public function addError(Test $test, Throwable $t, float $time): void;

    public function addWarning(Test $test, Warning $e, float $time): void;

    public function addFailure(Test $test, AssertionFailedError $e, float $time): void;

    public function addIncompleteTest(Test $test, Throwable $t, float $time): void;

    public function addRiskyTest(Test $test, Throwable $t, float $time): void;

    public function addSkippedTest(Test $test, Throwable $t, float $time): void;

    public function startTestSuite(TestSuite $suite): void;

    public function endTestSuite(TestSuite $suite): void;

    public function startTest(Test $test): void;

    public function endTest(Test $test, float $time): void;
}
```

The `TestListener` interface violates the Interface Segregation Principle, the "I" in "SOLID". This means that it requires the implementation of many methods, even if the client is not interested in the events they represent.

But the `TestListener` interface also has a fundamental design flaw: it passes around the `Test` and `TestSuite` objects, allowing clients to manipulate the outcome of a test run, for instance. To make things worse, client implementations of `TestListener` exist that bypass the public API of `Test` and `TestSuite` to perform such manipulation. In short, `TestListener` implementations were use to do more than "just listen".

The `TestListener` interface is deprecated since PHPUnit 8, it will be removed in PHPUnit 10.

### The `Hook` Interfaces

Back in 2018 and with PHPUnit 7.1, we attempted to [make extending PHPUnit's test runner easier](https://github.com/sebastianbergmann/phpunit/issues/3002) with the introduction of the `PHPUnit\Runner\Hook` interfaces. Here is an example of one of these interfaces:

```php
interface AfterSuccessfulTestHook
{
    public function executeAfterSuccessfulTest(string $test, float $time): void;
}
```

As you can see, we learned from the painful experience we made with the `TestListener` interface. The `PHPUnit\Runner\Hook` interfaces follow the Interface Segregation Principle and clients no longer get access to the real test objects that are used by PHPUnit to run the tests.

However, we did not "think big enough" and the `PHPUnit\Runner\Hook` interfaces were too limited. Even we did not manage to migrate PHPUnit's own `TestListener` implementations to the `PHPUnit\Runner\Hook` interfaces. They were a step in the right direction, but they fell short of actually being useful.

The `PHPUnit\Runner\Hook` interfaces will be deprecated in PHPUnit 10, they will be removed in PHPUnit 11.

## The New Event System

At the [EU-FOSSA 2 Hackathon](https://github.com/eufossa/eu-hackathon-2019/blob/master/achievements/phpunit.md) in October 2019, [Sebastian Bergmann](https://github.com/sebastianbergmann), [Ewout Pieter den Ouden](https://github.com/epdenouden), [Andreas Möller](https://github.com/localheinz), [Arne Blankerts](https://github.com/theseer), and [Stefan Priebsch](https://github.com/spriebsch) got together and designed a new system for extending PHPUnit based on events.

---
> ![Arne Blankerts, Andreas Möller, and Ewout Pieter den Ouden](https://live.staticflickr.com/65535/48852925447_23ec0795bc_c.jpg)
> 
> Photo: Arne Blankerts, Andreas Möller, and Ewout Pieter den Ouden work on the new event system for PHPUnit
---

Since then, Arne Blankerts and Andreas Möller worked on implementing this new event-based system in a branch. This issue is created as we are getting close to be able to merge this branch.

**Comment by Naktibalda** [comment]
Hi Sebastian,

Factory methods for value objects of TestSuite and TestCase classes make TestCase and TestSuite non-extensible.
https://github.com/sebastianbergmann/phpunit/blob/1c56cf3b18906109ebc4d78077eb7e3ad3e99181/src/Event/Value/TestSuite/TestSuite.php#L55-L145
https://github.com/sebastianbergmann/phpunit/blob/1c56cf3b18906109ebc4d78077eb7e3ad3e99181/src/Event/Value/Test/TestMethod.php#L43-L67

Would it be possible to implement mechanism for extending class to provide factory method for value objects?

**Comment by sebastianbergmann** [comment]
Please explain why you want to extend these classes.

**Comment by top-master** [comment]
I don't think this can help for situations like https://github.com/sebastianbergmann/phpunit/issues/4960

**Comment by Jean85** [comment]
@sebastianbergmann this closing means that the event system is now stable? I saw that you heavily refactored it, creating a distinction between outcomes and other events (good choice!), is that permanent now? Can we start building on top of that?

**Comment by sebastianbergmann** [comment]
I have closed this issue because the initial work has been completed by @theseer and @localheinz a long time ago and their work has been merged a long time ago. Since then, with the exception of #5040, everything in PHPUnit itself has been migrated from `TestListener` to the event system.

I am reluctant to call the current situation "stable", though, and cannot guarantee that there will be no major changes until we approach a release.

**Comment by BafS** [comment]
Shall we still use hooks in the meantime? I didn't find documentation regarding the new event system, if I understand correctly

- `TestListener` is deprecated and will be remote in PHPUnit 10
- `Hook` will be deprecated in PHPUnit 10 and removed in PHPUnit 11
- The new event system is not stable and not documented (?)

**Comment by sebastianbergmann** [comment]
The `TestListener` interface as well as the `Hook` interfaces have been removed in PHPUnit 10. The new system will be documented before PHPUnit 10 is released.

In the meantime, you can look at, for instance, these examples:

* [default progress printer](https://github.com/sebastianbergmann/phpunit/blob/main/src/TextUI/Output/Default/ProgressPrinter/ProgressPrinter.php)
* [JUnit XML logfile writer](https://github.com/sebastianbergmann/phpunit/blob/main/src/Logging/JUnit/JunitXmlLogger.php)
* [TeamCity logfile writer](https://github.com/sebastianbergmann/phpunit/blob/main/src/Logging/TeamCity/TeamCityLogger.php)

**Comment by BafS** [comment]
Okay, thank you for those information!

**Comment by arderyp** [comment]
@sebastianbergmann you mentioned that the new event system would be documented before 10 was released.

I see some documentation here: https://phpunit.readthedocs.io/en/10.0/extending-phpunit.html#phpunit-s-event-system

However, it seems to be missing the basic example of how to use these new events.

How does one refactor:

```
use PHPUnit\Runner\BeforeFirstTestHook;
use PHPUnit\Runner\AfterLastTestHook;

class MyCustomeExtension implements BeforeFirstTestHook, AfterLastTestHook
{
```

I'm guessing it has something to do with:

```
PHPUnit\Event\Test\AfterLastTestMethodCalled;
PHPUnit\Event\Test\BeforeFirstTestMethodCalled;
```

But the implementation is not clear to me.  They don't look like attributes... so?

**Comment by sebastianbergmann** [comment]
[The documentation has not been updated for PHPUnit 10 yet.](https://github.com/sebastianbergmann/phpunit-documentation-english/issues/273) The [JUnit logger](https://github.com/sebastianbergmann/phpunit/tree/10.0/src/Logging/JUnit) is a good starting point to see how events are used.

**Comment by arderyp** [comment]
okay, i'll have a look at JUnit logger

**Comment by bilogic** [comment]
I think it is safe to say that this is a topic for 90% of us because of removed functionality that we relied upon. This will probably help too https://docs.phpunit.de/en/10.3/extending-phpunit.html#extending-the-test-runner

**Comment by oleg-andreyev** [comment]
As for me the biggest issue with New Event System, is that event is immutable and I cannot alter results.

Example:
- We have huge test suite
- I want to parallel it using amqp
- I want to send tests into queue
- I want to consume test from queue

and fortunately or unfortunately... it's impossible.
So need to override entire TestRunner...

**Comment by Jean85** [comment]
@oleg-andreyev what you probably want to try is [Paraunit](https://github.com/facile-it/paraunit) (mine) or [Paratest](https://github.com/paratestphp/paratest/).
