### ISSUE TITLE
Consecutive parameter state issue

### ISSUE THREAD

**Issue by Maxsh** [sebastianbergmann/phpunit#4677]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.4
| PHP version         | 7.4.15
| Installation Method | Composer

#### Summary

If an object changes its state after performing the test, `withConsecutive` invocation mocker fails on the changed state. 

#### Current behavior

I'm not aware of the need evaluate assert again after the test is run, but it fails exactly there - `verifyMockObjects` method.

[TestCase.php](https://github.com/sebastianbergmann/phpunit/blob/master/src/Framework/TestCase.php#L719)
```php
$this->testResult = $this->runTest();
$this->verifyMockObjects();
```

The tests has passed successfully in `runTest` method and in [the ConsecutiveParamater apply](https://github.com/sebastianbergmann/phpunit/blob/master/src/Framework/MockObject/Rule/ConsecutiveParameters.php#L71). 
But after finishing test, it tries for some reason `verifyMockObjects` and fails in [the ConsecutiveParamater apply](https://github.com/sebastianbergmann/phpunit/blob/master/src/Framework/MockObject/Rule/ConsecutiveParameters.php#L81) due to the state was changed in the runTest method.

#### How to reproduce

1. Create a State class
```php
class State {
    public string $state;
}
```
2. Create a class which should be mocked
```php
class Persister {
    public function persist(State $st) {
        // persist object
    }
}
```
3.  In the test an invoker class calls the mocked method and change the state of the property after that
```php
    public function testConsecutiveCall(): void
    {
        $changer = new class {
            public function invoke(Persister $changer, State $state) {
                $changer->persist($state);
                $state->state = 'B';
            }
        };
        $stateA = new State();
        $stateA->state = 'A';

        $mocker = $this->createMock(Persister::class);

        $mocker->expects(self::once())
            ->method('persist')
            ->withConsecutive([self::callback(function (State $state) {
                $this->assertSame('A', $state->state);
                return true;
            })]);

        $changer->invoke($mocker, $stateA);
    }
```
4. The test fails with the message. However at that moment the state is still `A`
```text
PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

Expectation failed for method name is "persist" when invoked 1 time(s).
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'A'
+'B'
```

**The interesting fact 1**, if we change state to B in the assertSatement `$this->assertSame('B', $state->state);`. It will **again** fails, but now is expected in the `runTest` method with the stack trace
```text
PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

Expectation failed for method name is "persist" when invoked 1 time(s)
Failed asserting that two strings are identical.
Expected :'B'
Actual   :'A'
<Click to see difference>

 /var/www/tests/integration/Import/TestTest.php:25
 /var/www/tests/integration/Import/TestTest.php:47
```
**The interesting fact 2**, `with` method works as expected
```php
        $mocker->expects(self::once())
            ->method('persist')
            ->with(self::callback(function (State $state) {
                $this->assertSame('A', $state->state);
                return true;
            }));
```

#### Expected behavior

The test should be passed with `withConsecutive` method, because state at that moment is still `A`
```php
        $mocker->expects(self::once())
            ->method('persist')
            ->withConsecutive([self::callback(function (State $state) {
                $this->assertSame('A', $state->state);
                return true;
            })]);
```

**Comment by sebastianbergmann** [comment]
No changes will be made to `withConsecutive()`, it is schedules for deprecation and removal.

**Comment by sebastianbergmann** [comment]
Rewrite your tests and/or your production code to not require this feature. Maybe this [article](https://thephp.cc/articles/do-not-mock-what-you-do-not-own) can help.

**Comment by Maxsh** [comment]
Agree with all the above, but sometimes, when the old application is being migrated to the latest PHP and PHPUnit, have come up with the following workaround (in order to avoid refactoring the old app for a quite trivial place, like logging.

```php
            ->with(self::callback(function (string $message) {
                static $i = 0;
                return match (++$i) {
                    1 => $message === 'Removing audio files started.',
                    2 => $message === "Removing audio files that older than '2018-01-01 00:00:00'.",
                };
            }));
```
