### ISSUE TITLE
Tests are slow and stuck on exceptions or errors on Windows machines

### ISSUE THREAD

**Issue by khooz** [sebastianbergmann/phpunit#4686]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.4
| PHP version         | 8.0.6
| Installation Method | Composer

#### Summary

While using PHPUnit just fine in WSL (WSL2 with Ubuntu LTS from MS Store) using PHP 7.4, when I try to use PHPUnit on the Windows itself, using PHP 8.0.6, it hangs and stucks.

#### Current behavior

It stucks like this:
![image](https://user-images.githubusercontent.com/8382714/119192416-60b06b00-ba95-11eb-8ce6-866b1c7a6c7d.png)

#### How to reproduce

Run a test that would fail due to some exception or failed assertion.

#### Expected behavior

To run and show the errors of my ways.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by sebastianbergmann** [comment]
No feedback, closing.
