### ISSUE TITLE
Provide access to number of test assertions in hooks

### ISSUE THREAD

**Issue by jeremyjcpaul** [sebastianbergmann/phpunit#4691]
I'm beginning to use the test hooks to record test failures etc. but I'd like to include the number of assertions stat. I find it really useful to know this as it can highlight a problematic test quickly, if the count is about a certain threshold for instance. I wouldn't mind if it was added to the $test string after the data set info or if it was a separate parameter sent to the hook's executor. I know the next version of PHPUnit will include an update to the test runner but I'm not sure if getting the number of assertions, for a test, will be possible with that implementation? Thanks!

**Comment by sebastianbergmann** [comment]
[The test hooks are deprecated](https://github.com/sebastianbergmann/phpunit/issues/4595) and no changes will be made to them before they are removed.
