### ISSUE TITLE
Annotations in single-line doc-comments are not handled correctly

### ISSUE THREAD

**Issue by ostrolucky** [sebastianbergmann/phpunit#4692]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | master
| PHP version         | any
| Installation Method | git

#### Summary

PHPUnit seems to require multiline docblocks for its annotations, eg. `@requires`. Some users prefer single line docblocks though and this [is also now set in doctrine/coding-standard](https://github.com/doctrine/coding-standard/pull/252). We had this problem in https://github.com/doctrine/DoctrineBundle/pull/1365/files#diff-6c0dba5076ce8a2e9ff3e1e07f6661e095a18f80e32ad9766945f55c0414f8a2.

This seems to be because in your regexes you don't expect `/**` to be on same line as meat of the regex at https://github.com/sebastianbergmann/phpunit/blob/dba1e6c84373e749b3a5ee37ecbcc8f3b290a959/src/Util/Annotation/DocBlock.php#L73-L87

#### How to reproduce

```php
/** @requires PHP 8 */
public function test(): void
{
}
```

Doesn't have any effect. Test case is not skipped on PHP < 8.

But with
```php
/**
 * @requires PHP 8
 */
public function test(): void
{
}
```

It works.

#### Expected behavior

Both examples should work the same way.

**Comment by sebastianbergmann** [comment]
This is due to the [expected and documented behaviour](https://www.php.net/manual/en/reflectionclass.getdoccomment.php) of how PHP's Reflection API handled "doc comments". This cannot be changed. Furthermore, annotations are closed for further development in PHPUnit and will, over time, be superseded by [attributes](https://github.com/sebastianbergmann/phpunit/issues/4502).

**Comment by sebastianbergmann** [comment]
I replied too quickly, sorry. I thought you were refering to `/**` versus `/*`, which is an issue that is brought up frequently.

I agree that
```php
/** @requires PHP 8 */
```
should work just like
```php
/**
 * @requires PHP 8
 */
```
and consider the fact that is does not to be a bug.

A patch that fixes this would be appreciated.

**Comment by ostrolucky** [comment]
I could fix it, but can you tell me where should the test case go? I'm not familiar with your setup.

**Comment by sebastianbergmann** [comment]
For PHPUnit 10 (`master`) this is easy to answer: https://github.com/sebastianbergmann/phpunit/blob/master/tests/unit/Metadata/Parser/AnnotationParserTest.php For PHPUnit 8.5 and PHPUnit 9.5 it is not that easy, unfortunately.

I suggest you send a pull request against `master` and I backport it from there.
