### ISSUE TITLE
Support dates for PHPUnit 9

### ISSUE THREAD

**Issue by stof** [sebastianbergmann/phpunit#4718]
The website still lists PHPUnit 9 as being supported until February 2020 on https://phpunit.de/supported-versions.html, based on the rule of ending 2 years after its initial release. However, that rule was based on a yearly major release, and PHPUnit 10 was _not_ released in February 2021.

What is the plan now ? Will this date stay as is (providing very little overlap between PHPUnit 9 and 10 to perform the migration) or will the date change to be "release of PHPUnit 10 + 1 year" instead ?

**Comment by sebastianbergmann** [comment]
I will have an answer for this when we are closer to the release of PHPUnit 10.

**Comment by GrahamCampbell** [comment]
Is there a release date (range) in mind for PHPUnit 10.0? Are there any specific tasks that you'd like help with?
