### ISSUE TITLE
Question: How to disable/enable additional stack trace?

### ISSUE THREAD

**Issue by jokaorgua** [sebastianbergmann/phpunit#4722]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.6
| PHP version         | 8.0.7
| Installation Method |  PHAR

#### Summary

I'm trying to disable additional trace. This part.
```
/app/vendor/phpunit/phpunit/src/Framework/TestResult.php:722
/app/vendor/phpunit/phpunit/src/Framework/TestSuite.php:677
/app/vendor/phpunit/phpunit/src/Framework/TestSuite.php:677
/app/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:670
```

#### Current behavior

When I run a test the additional trace is being printed. I need to disable it because PhpStorm does not understand such a trace and on double click on the failed test goes to TestRunner.php
Here is bug in phpStorm https://youtrack.jetbrains.com/issue/WI-57458#focus=Comments-27-4960597.0-0

#### How to reproduce

I do not know. I've created a new project with symfony 5.3 with the same docker container and this additional trace is not shown.
So I wonder which setting can enable disable such a trace so I can disable it in my current project and help jetbrains to reproduce the situation

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.

**Comment by jokaorgua** [comment]
@sebastianbergmann thank you for the help. should I post it like a bug?

**Comment by Setest** [comment]
@jokaorgua  This is because 9.5 version have printDefectTrace() method which invoked from printDefects in any printErrors, failtures etc. And 9.6 have similar code.

![image](https://github.com/sebastianbergmann/phpunit/assets/4029273/5f364ad8-57d6-4cca-8202-580a931701aa)
