### ISSUE TITLE
setupBeforeClass is not called before class is being instantiated

### ISSUE THREAD

**Issue by boesing** [sebastianbergmann/phpunit#4723]
Hey there,

I am experiencing some behavior I would not expect. As that seems to be like that since forever, I'd rather add this as a feature request than a bug report.

So I have a test where I want to execute something before the class is instantiated. So I am using `setupBeforeClass` public static method to ensure that.

Sadly, when having data providers, this method is not executed even tho, the class is being instantiated.

```php
<?php
declare(strict_types=1);

use PHPUnit\Framework\TestCase;

final class SetupBeforeClassTest extends TestCase
{
    /**
     * @var bool
     */
    private static $test = false;

    public static function setUpBeforeClass(): void
    {
        parent::setUpBeforeClass();
        self::$test = true;
    }

    /**
     * @dataProvider setupBeforeClassValue
     */
    public function testWithDataProvider(bool $foo): void
    {
        self::assertTrue(self::$test, 'Static property should be true');
        self::assertTrue($foo, 'Passed argument from data provider should be true');
    }

    public function setupBeforeClassValue(): array
    {
        return [
            'true' => [self::$test],
        ];
    }
}
```

```
PHPUnit 9.5.6 by Sebastian Bergmann and contributors.


Passed argument from data provider should be true
Failed asserting that false is true.
SetupBeforeClassTest.php:25
 


Time: 00:00.157, Memory: 8.00 MB


FAILURES!
Tests: 1, Assertions: 2, Failures: 1.

Process finished with exit code 1
```

----

Interesting here is, that if I set the static property within the `__construct`, everything works as expected but it is marked as `internal` and thus should not be inherited...

```php
<?php
declare(strict_types=1);

use PHPUnit\Framework\TestCase;

final class SetupBeforeClassTest extends TestCase
{
    /**
     * @var bool
     */
    private static $test = false;

    public function __construct(?string $name = null, array $data = [], $dataName = '')
    {
        parent::__construct($name, $data, $dataName);
        self::$test = true;
    }

    /**
     * @dataProvider setupBeforeClassValue
     */
    public function testWithDataProvider(bool $foo): void
    {
        self::assertTrue(self::$test, 'Static property should be true');
        self::assertTrue($foo, 'Passed argument from data provider should be true');
    }

    public function setupBeforeClassValue(): array
    {
        return [
            'true' => [self::$test],
        ];
    }
}
```

```
PHPUnit 9.5.6 by Sebastian Bergmann and contributors.



Time: 00:00.208, Memory: 8.00 MB

OK (1 test, 2 assertions)

Process finished with exit code 0
```

----

Any thoughts on this?

**Comment by jrfnl** [comment]
@boesing This is documented behaviour as per the second note at the end of the "data providers" section:

> All data providers are executed before both the call to the `setUpBeforeClass()` static method and the first call to the `setUp()` method. Because of that you can’t access any variables you create there from within a data provider. This is required in order for PHPUnit to be able to compute the total number of tests.

https://phpunit.readthedocs.io/en/stable/writing-tests-for-phpunit.html#data-providers

**Comment by boesing** [comment]
@jrfnl thanks for pointing me to the documentation. So there is no way to share logic between data providers and test cases?

**Comment by jrfnl** [comment]
Well, I imagine you could encapsule certain logic in a static function in the same class which you call from both your data provider as well as your `setUpBeforeClass()`... ?

**Comment by boesing** [comment]
TBH, I have to see if I find the real use-case I had to see if a static method might work. 
I'll give that a try then. But just to understand this: is there a technical reason on why the data providers are called before `setupBeforeClass`?

**Comment by jrfnl** [comment]
As it says in the text I quoted above:

> This is required in order for PHPUnit to be able to compute the total number of tests.

**Comment by boesing** [comment]
Okay, so thats a feature. gonna close this then. Thanks for clarification.
