### ISSUE TITLE
--no-coverage should only affect XML configuration

### ISSUE THREAD

**Issue by Slamdunk** [sebastianbergmann/phpunit#4726]
Hi, I'm keeping up-to-date on ParaTest with `master`, and I noticed https://github.com/sebastianbergmann/phpunit/commit/3527db8c61b1f24b69c3254a72a42a6d1a35de21 broke part of functionality fixed in https://github.com/sebastianbergmann/phpunit/pull/4446

As mentioned in https://github.com/sebastianbergmann/phpunit/pull/4446#discussion_r483442617, sadly I have no idea how to properly test `--no-coverage` here on PHPUnit, so https://github.com/sebastianbergmann/phpunit/pull/4446 landed without a test and the https://github.com/sebastianbergmann/phpunit/commit/3527db8c61b1f24b69c3254a72a42a6d1a35de21 refactor couldn't notice it broke it.

**Comment by Slamdunk** [comment]
If you can give me any hint on how to test `--no-coverage` I'm more than happy to create a PR with it.

**Comment by sebastianbergmann** [comment]
The new [Configuration](https://github.com/sebastianbergmann/phpunit/blob/master/src/TextUI/Configuration/Configuration.php) class will get tests, hopefully soon. Being able to tests aspects such as the one discussed here, thanks! btw for noticing/reporting, was one of the motivations for cleaning up this mess. The `Configuration` objects is still too big and still needs to be broken down into smaller objects, but at least it already is the canonical "PHPUnit runtime configuration" in one place, created by reading the XML configuration (if it exists / should be read) and applying CLI options on top.

My best bet would be

* load an XML configuration file into a ` PHPUnit\TextUI\XmlConfiguration\Configuration` object
* parse CLI options into a `PHPUnit\TextUI\CliArguments\Configuration` object
* merge those two objects using `PHPUnit\TextUI\Configuration\Merger::merge()` into a `PHPUnit\TextUI\Configuration\Configuration` object
* and finally assert that this object has the correct information

**Comment by Slamdunk** [comment]
Nice approach, the less we need to test on PHPT files the better :+1:

**Comment by sebastianbergmann** [comment]
> Nice approach, the less we need to test on PHPT files the better 👍

Exactly.

**Comment by sebastianbergmann** [comment]
> If you can give me any hint on how to test `--no-coverage` I'm more than happy to create a PR with it.

Just checking: are you still going to work on this? Thanks!

**Comment by Slamdunk** [comment]
I was waiting for the cli objects to be refactored and ready for this challenge.
If they are, I can send a PR in the next week

**Comment by sebastianbergmann** [comment]
> I was waiting for the cli objects to be refactored and ready for this challenge.
> If they are, I can send a PR in the next week

They should be :)
