### ISSUE TITLE
Mock of Imagick triggers PHP warnings

### ISSUE THREAD

**Issue by JensGraefe** [sebastianbergmann/phpunit#4728]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.6
| PHP version         | 8.0.8
| Installation Method | PHAR

#### Summary

Mocking the Imagick class triggers the following PHP warnings
PHP Warning:  "resource" is not a supported builtin type and will be interpreted as a class name. Write "\resource" to suppress this warning in phar:///usr/local/bin/phpunit-9/phpunit/Framework/MockObject/MockClass.php(48) : eval()'d code on line 75
PHP Warning:  "resource" is not a supported builtin type and will be interpreted as a class name. Write "\resource" to suppress this warning in phar:///usr/local/bin/phpunit-9/phpunit/Framework/MockObject/MockClass.php(48) : eval()'d code on line 999
PHP Warning:  "resource" is not a supported builtin type and will be interpreted as a class name. Write "\resource" to suppress this warning in phar:///usr/local/bin/phpunit-9/phpunit/Framework/MockObject/MockClass.php(48) : eval()'d code on line 1021
PHP Warning:  "resource" is not a supported builtin type and will be interpreted as a class name. Write "\resource" to suppress this warning in phar:///usr/local/bin/phpunit-9/phpunit/Framework/MockObject/MockClass.php(48) : eval()'d code on line 3923

I guess this is related to the ongoing change from the resource types to the new resource objects. I have no clue if there is a clean possibility for phpunit to handle this. 

#### Current behavior
warnings are triggered

#### How to reproduce

`$imagickMock      = $this->getMockBuilder(Imagick::class)
                                 ->disableOriginalConstructor()
                                 ->getMock();`
[example.zip](https://github.com/sebastianbergmann/phpunit/files/6801779/example.zip)

#### Expected behavior

no warning should be triggered

**Comment by sebastianbergmann** [comment]
Sorry, I do not think that there is anything that can be done. I usually advise not to double builtins anyway.
