### ISSUE TITLE
Test Doubles: Allow to set default dummy implementation of (not specified) methods

### ISSUE THREAD

**Issue by kohlerdominik** [sebastianbergmann/phpunit#4729]
Hi there

We switched from Mockery to PHPUnit test doubles quite a while ago, and I'm very happy with it. But i regulary run in an issue that was solved better by Mockery imo:
When creating a mock with phpunit, the mock builder clones all methods and replaces them with a "return null implementation". Meanwhile, in mockery not expected method calls instead throw an exception. For me, this is more desired behaviour, as it basically hightlights a test, for example after a refactor. But it seems like there's no way enable this behaviour, for example by overriding the default dummy implementation.

---
### Detailed explanation
In the [phpunit docs](https://phpunit.readthedocs.io/en/9.5/test-doubles.html) is stated, that:

> By default, all methods of the original class are replaced with a dummy implementation that returns null (without calling the original method). Using the will($this->returnValue()) method, for instance, you can configure these dummy implementations to return a value when called.

But there's no way explained, how to replace this default behaviour. For me, i'd rather have a default behaviour of throwing a `NotMatchedExpectationException`. 

With the default behaviour, mostly the tests fail at the assertation, where for example an empty string will not match the expected string. Then it's neccessary to track the whole test, until you actually find out that you forgot to add expectations for a method call.

**But why not use `onlyMethods()`?** you might ask. Well, because i don't like the idea of having to specify the method twice, once at the builder level and once on the mock. It's seems counter-intuitive for me.

### Behaviour in Mockery
In Mockery instead, by default a [MockeryExceptionNoMatchingExpectationException ](http://docs.mockery.io/en/latest/mockery/exceptions.html#mockeryexceptionnomatchingexpectationexception) is thrown if the expectation was not specified

> The exception class is used when a method call does not match any known expectation. All expectations are uniquely identified in a mock object by the method name and the list of expected arguments.

But it's possible to disable this behaviour:

> You can disable this exception and opt for returning NULL from all unexpected method calls by using the earlier mentioned `shouldIgnoreMissing()` behaviour modifier.

### Feature Request
It would be great if we can somehow specify the default behaviour of unexpected method calls. For backwards-compatibility, this would obviously still be `return null`. But if I wanted another behaviour, i could overwrite the `createMock()`-method on `TestCase`, and do something like:

```php
$this->getMockBuilder($className)
    ->noMatchingExpectationWillReturnCallback(
        function (string $method, array $arguments) {
            throw new NotMatchedExpectationException($method, $arguments);
        }
    );

```

**Comment by sebastianbergmann** [comment]
Won't implement.
