### ISSUE TITLE
Extract Assert/constraints from the testing framework package?

### ISSUE THREAD

**Issue by wouterj** [sebastianbergmann/phpunit#4731]
_This is by any means just a suggestion. I'm not sure if the idea is at all feasible (or adds extra workload on the maintainers). Feel free to close if it's just not worth it._

**The problem**
PHPunit has one of the greatest, most feature-complete assertion libraries in PHP. Also, IIUC, you need the `AssertionFailedException` from the framework itself if you want your assertion to be discovered correctly in PHPunit.

This poses some issues for test generic packages (like [zenstruck/foundry](https://github.com/zenstruck/foundry) and [zenstruck/browser](https://github.com/zenstruck/browser/)). They need to write a custom assert package (ref: https://github.com/zenstruck/browser/pull/1) to support both PHPunit and e.g. Behat.
Interestingly, Behat even has a [dev requirement on PHPunit](https://github.com/Behat/Behat/blob/master/composer.json#L32), just to be able to use the great assertions.

**Possible solution**
If the assert/constraints are extracted from this package into a separate one, it would allow packages like Foundry and Behat to require e.g. `phpunit/assert` and always use that package (in both PHPunit and Behat). Would it be possible to achieve this?

**Comment by sebastianbergmann** [comment]
This was attempted in the past and turned out to now work: not for PHPUnit, not for other possible consumers.

**Comment by wouterj** [comment]
Thanks for your answer! We'll continue with the abstraction approach then.
