### ISSUE TITLE
diff which only differentiate in indent/space/tab chars are hard to read

### ISSUE THREAD

**Issue by staabm** [sebastianbergmann/phpunit#4733]
while working on rector windows compat, I stumbled over a test failing on windows CI only with

```diff

1) Rector\Tests\CodingStyle\Rector\ClassMethod\NewlineBeforeNewAssignSetRector\NewlineBeforeNewAssignSetRectorTest::test with data set #0 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
rules-tests/CodingStyle/Rector/ClassMethod/NewlineBeforeNewAssignSetRector/Fixture/fixture.php.inc
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
     {
         $value = new Value;
         $value->setValue(5);
-
+
         $value2 = new Value;
         $value2->setValue(1);
     }

```

I was wondering what the difference was, because phpunit did not show the hint about different line endings.
to find out, I had to add additional debug print statements.

using the symfony var-dump I finally had a chance to output the expected vs. actual strings in a way which showed the actual difference:

actual
```
'<?php\n
 \n
 namespace Rector/Tests/CodingStyle/Rector/ClassMethod/NewlineBeforeNewAssignSetRector/Fixture;\n
 \n
 final class Multiple\n
 {\n
     public function run()\n
     {\n
         $value = new Value;\n
         $value->setValue(5);\n
 \n
         $value2 = new Value;\n
         $value2->setValue(1);\n
 \n
         $value3 = new Value;\n
         $value3->setValue(1);\n
     }\n
 }\n
 \n
 ?>\n'
```

expected
```
'<?php\n
 \n
 namespace Rector/Tests/CodingStyle/Rector/ClassMethod/NewlineBeforeNewAssignSetRector/Fixture;\n
 \n
 final class Multiple\n
 {\n
     public function run()\n
     {\n
         $value = new Value;\n
         $value->setValue(5);\n
         \n
         $value2 = new Value;\n
         $value2->setValue(1);\n
         \n
         $value3 = new Value;\n
         $value3->setValue(1);\n
     }\n
 }\n
 \n
 ?>\n'
```

note: the difference between these 2 strings are the spaces before 2 of the newlines.

so the point of my issue is: is there some room for improvement to make the phpunit diff indicate the actual problem easier, without the need for hacking the sources to print all the details?

maybe it would make sense to make phpunit print whitespaces characters like `\n`, `\t` and similar?

**Comment by sebastianbergmann** [comment]
> maybe it would make sense to make phpunit print whitespaces characters like `\n`, `\t` and similar?

PHPUnit already does exactly that:

```php
<?php declare(strict_types=1);
use PHPUnit\Framework\TestCase;

final class Test extends TestCase
{
    public function testOne(): void
    {
        $this->assertEquals("foo\n", "foo\r\n");
    }
}
```
```
$ ./tools/phpunit Test.php
PHPUnit 9.5.6 by Sebastian Bergmann and contributors.

F                                                                   1 / 1 (100%)

Time: 00:00.018, Memory: 4.00 MB

There was 1 failure:

1) Test::testOne
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'foo\n
+'foo\r\n
 '

/home/sb/Test.php:8

FAILURES!
Tests: 1, Assertions: 1, Failures: 1.
```

**Comment by staabm** [comment]
thx for the feedback. it doesn't work for me.

we are using `PHPUnit 9.5.6 by Sebastian Bergmann and contributors.`

is there some kind of switch/flag which needs to be turned on/off to make this work?

**Comment by sebastianbergmann** [comment]
> is there some kind of switch/flag which needs to be turned on/off to make this work?

No.

**Comment by staabm** [comment]
could you give me a hint, where this feature inside phpunit is implemented so I can try to debug why it doesn't kick in in our case?

**Comment by sebastianbergmann** [comment]
Sure: https://github.com/sebastianbergmann/exporter/blob/master/src/Exporter.php#L222 should be the place.

**Comment by staabm** [comment]
after looking into Exporter.php I now have a feeling that we are talking of different things.

the actual problem at hand is a actual vs. expected string which only has differences in space-characters.
these are not part of the whitespace handling in https://github.com/sebastianbergmann/exporter/blob/4a6270bf3bcaf524b91ae268080ad0bc72ba385e/src/Exporter.php#L232-L235 yet

but I am not yet sure how to improve this situation.

maybe we can check whether a diff only contains of space characters and in this case also add `\s` and `\t` and similar into account?

**Comment by sebastianbergmann** [comment]
I do not know what to do here, sorry.
