### ISSUE TITLE
Add support for multiple printers

### ISSUE THREAD

**Issue by wdoug** [sebastianbergmann/phpunit#4734]
First of all, thanks for your work on this project!

I would like the ability to run multiple printers for the output of a test suite. Specifically, I would like to be able to have both the default printer for logging test progress and [this GitHub action printer](https://github.com/mheap/phpunit-github-actions-printer) so we can see failures inline on GitHub.

After seeing how jest [supports multiple test "reporters"](https://jestjs.io/docs/cli#--reporters), I wanted to see if that might be possible for phpunit as well.

**Comment by sebastianbergmann** [comment]
This is something we will have a look at after PHPUnit 10 is stable and the new event system, which is the foundation for printers going forwards, is in place.

**Comment by sebastianbergmann** [comment]
This is not needed with PHPUnit 10 anymore.
