### ISSUE TITLE
Do something after all tests have passed

### ISSUE THREAD

**Issue by adiletmaks** [sebastianbergmann/phpunit#4742]
I couldn't find way to do something after all tests passed. I used to `TestSuite` instance to get tests count, but now it's unsupported.

In my old project I solved problem like this

```php
$currentTestCount = $this->getTestResultObject()->count();
$allTestCount = $this->getTestResultObject()->topTestSuite()->count();

if (($currentTestCount == $allTestCount) && (!$this->hasFailed())) {
    // do something
}
```

**Comment by sebastianbergmann** [comment]
This is outside the scope of PHPUnit, do this in your build automation after you have invoked PHPUnit.

**Comment by shirokovnv** [comment]
Hello. 

Sorry for reopening question.

I have found that topTestSuite() is unsupported. 

```$currentTestCount = $this->getTestResultObject()->count();
$allTestCount = $this->getTestResultObject()->topTestSuite()->count();
```

How can I get total count of all tests ? Is it possible inside the PHPUnit scope for now?

Thanks.

**Comment by adiletmaks** [comment]
I just found this way

```php
    private function getAllTestsCount(): int
    {
        return (int) exec('./vendor/bin/phpunit --list-tests -d memory_limit=1G tests/Feature | grep --regexp="::test" --count');
    }
```

**Comment by talismandev** [comment]
> I just found this way
> 
> ```
>     private function getAllTestsCount(): int
>     {
>         return (int) exec('./vendor/bin/phpunit --list-tests -d memory_limit=1G tests/Feature | grep --regexp="::test" --count');
>     }
> ```

Aha, thanks!

I have found 2 possible solutions too (did it with laravel framework):

1.  ```$output = "";
        exec("vendor\bin\phpunit --list-tests", $output);

        $collection = collect($output);

        $collection = $collection->filter(function($item){
            return Str::contains($item, "::test");
        });

        $allTestCount = $collection->count();```

2. ```$allTestCount = -1;
        $that = $this->getTestResultObject();

        $listeners = function ($that) {
            return $that->listeners;
        };

        $listeners = Closure::bind($listeners, null, $that);
        $listeners = $listeners($that);

        foreach ($listeners as $listener)
        {
            if ($listener instanceof \NunoMaduro\Collision\Adapters\Phpunit\Printer) {
                $state = function ($that) {
                    return $that->state;
                };
                
                $state = Closure::bind($state, null, $listener);
                $allTestCount = $state($listener)->suiteTotalTests;
            }
        }```

The second solution depends on some private state data, collected by listeners, defined when PHPUnit starts. 
The state data extracted by Closure bind hack...

So, it seems very unstable solution.
