### ISSUE TITLE
Unknown option "-q"

### ISSUE THREAD

**Issue by FranciscoCaldeira** [sebastianbergmann/phpunit#4746]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | PHPUnit 9.5.6 
| PHP version         | PHP 7.4.9 
| Installation Method | Composer

#### Summary

By doing `php artisan test -h` it shows a list of options and one is like: `-q, --quiet               Do not output any message`, but when I do `php artisan test --quiet` it gives an error.

#### Current behavior

An error that option is invalid.

#### How to reproduce
On console `php artisan test --quiet` the output is the error.

#### Expected behavior
The expected is to do the tests and don't show the fail asserts erros.

**Comment by sebastianbergmann** [comment]
You are confusing `phpunit` with `artisan`: PHPUnit does not have a `-q` or `--quiet` CLI option.
