### ISSUE TITLE
Only load PHP extensions that are documented to be required in GitHub Actions pipeline

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#4747]
See https://github.com/sebastianbergmann/phpunit/blob/master/.github/workflows/ci.yml#L65.

**Comment by sebastianbergmann** [comment]
@localheinz Did we implement this on our end (and can this ticket be closed)?

**Comment by sebastianbergmann** [comment]
@localheinz **ping**

**Comment by localheinz** [comment]
Yes, we did, @sebastianbergmann!
