### ISSUE TITLE
Mocking of `Memcached` class on PHP 8.0 results in fatal error

### ISSUE THREAD

**Issue by boesing** [sebastianbergmann/phpunit#4752]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.8
| PHP version         | 8.0.5
| Installation Method | Composer

#### Summary

When mocking `Memcached` from `ext-memcached`, I'll get a [fatal error](https://github.com/laminas/laminas-cache-storage-adapter-memcached/runs/3273925255?check_suite_focus=true):

```
PHP Fatal error:  Cannot use int as default value for parameter $with_cas of type bool in /github/workspace/vendor/phpunit/phpunit/src/Framework/MockObject/MockClass.php(51) : eval()'d code on line 141
```

#### Current behavior

Fatal error as decribed above. To work around this, I've moved to `TestCase#createPartialMock` instead.

#### How to reproduce

1st of all, add the `Memcached` extension for PHP 8.0 (`pecl install memcached`)
After that, simply mock the `Memcached` class as follows:

```
class MemcachedTest extends TestCase
{
    public function testCanMockMemcachedWithoutFatalError(): void
    {
        $this->createMock(\Memcached::class);
    }
}
```

**Disclaimer: I've done that on my local machine (MacOS 11.2) with PHP 8.0 installed via Homebrew (shivammathur) and memcached extension installed via PECL and I don't receive this error.**

#### Expected behavior

Mocking works as expected.

**Comment by sebastianbergmann** [comment]
I consider having to double classes provided by PHP or a PHP extension a problem that is best avoided. Declare an interface that you own and implement an adapter that implements your interface using `Memcached` and the problem no longer exists. Doubling classes implemented in C works in general, but there are many edge cases that are tedious to debug. I also do not like to add workarounds for missing/incomplete/wrong Reflection API metadata to PHPUnit's test double code generator.

That being said, I agree that this should be fixed. But your disclaimer

> I've done that on my local machine (MacOS 11.2) with PHP 8.0 installed via Homebrew (shivammathur) and memcached extension installed via PECL and I don't receive this error.

already tells me that I do not want to spend time on debugging this issue. I will gladly review a pull request, but I won't work on this myself.

**Comment by boesing** [comment]
Thanks for feedback here. 
Will see what I can do in future versions of the cache library.
Anyhow, glad you had a look on it. Thats very appreciated.
