### ISSUE TITLE
Testing a library against a runtime without mbstring is not longer possible in 8.5.18 and newer

### ISSUE THREAD

**Issue by stof** [sebastianbergmann/phpunit#4755]
https://github.com/sebastianbergmann/phpunit/commit/bf56acb31b5e26c213832bfc61cf2d072705d061 introduced an early check aborting if `mbstring` is missing (alongside other extensions for which I don't have issues as they are necessary for PHPUnit to work).
However, the `mbstring` dependency of PHPUnit is a bit special: it is only necessary for the `--testdox` output. Using a different output (the default one for instance) does not need it.

We were relying on that in the scssphp project to run a CI job with mbstring disabled, to ensure that our library was still compatible with runtimes that don't have mbstring (using `--ignore-platform-req=mbstring` in Composer to skip this requirement), which was working fine on older versions.

Would it be possible to change the `mbstring` to happen only if the testdox output is used instead ? The original issue https://github.com/sebastianbergmann/phpunit/issues/4720 was only requesting a check in that case too.

**Comment by sebastianbergmann** [comment]
> However, the `mbstring` dependency of PHPUnit is a bit special: it is only necessary for the `--testdox` output. Using a different output (the default one for instance) does not need it.

That is not correct:

* https://github.com/sebastianbergmann/phpunit/blob/8.5.19/src/Util/Xml.php#L25
* https://github.com/sebastianbergmann/phpunit/blob/8.5.19/src/Framework/Constraint/StringContains.php#L12

To me, the mbstring extension is not optional.

**Comment by stof** [comment]
hmm, indeed, I forgot that our testsuite also does not use the StringContains constraint (and that we use UTF-8 for our XML config file so we don't need the encoding conversion)
