### ISSUE TITLE
Union types are only allowed since PHP 8.0

### ISSUE THREAD

**Issue by applibs** [sebastianbergmann/phpunit#4762]
I downloaded master version and I see error:
Union types are only allowed since PHP 8.0 
at:
function assertArrayHasKey(int|string $key, array|ArrayAccess $array, string $message = ''): void
but I see support > 7.3 for PHPUnit 9:
https://phpunit.de/supported-versions.html

**Comment by sebastianbergmann** [comment]
`master` is what will be released as PHPUnit 10, PHPUnit 10 will not support PHP 7.
