### ISSUE TITLE
Remove support for `forceCoversAnnotation` and `beStrictAboutCoversAnnotation` attributes in XML configuration file

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#4779]

**Comment by sebastianbergmann** [comment]
See 0c65a47607d44f9d1bad3f9415e808c01e4507e1 for context.

**Comment by jrfnl** [comment]
Just checking - am I right that `requireCoverageMetadata` (PHPUnit 10+) is a one-on-one replacement for `forceCoversAnnotation` ?

**Comment by sebastianbergmann** [comment]
Yes.
