### ISSUE TITLE
Mocking `Serializable` interface emits deprecation

### ISSUE THREAD

**Issue by remorhaz** [sebastianbergmann/phpunit#4783]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.10
| PHP version         | 8.1.0 RC2
| Installation Method | Composer

#### Summary

Interfaces extending `Serializable` (in my case - `Ramsey\Uuid\UuidInterface` from `ramsey/uuid` package of version 4.2.2) emit deprecation if mocked.

Issue #4764 probably reports same problem.

#### Current behavior

PHPUnit emits deprecation like this:
```
PHP Deprecated:  The Serializable interface is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in  on line 3
```

#### How to reproduce

`composer require ramsey/uuid:^4.2.2`

And create a stub or mock:

```
$this->createStub(Ramsey\Uuid\UuidInterface::class);
```

#### Expected behavior

Mock is created without emitting deprecations.

**Comment by sebastianbergmann** [comment]
I do not think that this is an issue that can/should be fixed in PHPUnit.
