### ISSUE TITLE
Mark tests with deprecations, notices, or warnings as risky (instead of errored)

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#4784]
## Status Quo

PHPUnit currently supports the following attributes that can be set in the XML configuration file:

* `convertNoticesToExceptions` (default: `true`)
* `convertWarningsToExceptions` (default: `true`)
* `convertDeprecationsToExceptions` (default: `false` since PHPUnit 8.5.21 and PHPUnit 9.5.10, `true` before that)
* `convertErrorsToExceptions` (default: `true`)

Using a [custom error handler](https://www.php.net/manual/en/function.set-error-handler.php) and based on the configuration options listed above, PHPUnit converts

* `E_NOTICE` (controlled by `convertNoticesToExceptions`)
* `E_USER_NOTICE` (controlled by `convertNoticesToExceptions`)
* `E_STRICT` (controlled by `convertNoticesToExceptions`)
* `E_WARNING` (controlled by `convertWarningsToExceptions`)
* `E_USER_WARNING` (controlled by `convertWarningsToExceptions`)
* `E_DEPRECATED` (controlled by `convertDeprecationsToExceptions`)
* `E_USER_DEPRECATED` (controlled by `convertDeprecationsToExceptions`)
* all other `E_*` not explicitly listed (controlled by `convertErrorsToExceptions`)

to an exception which in turn aborts the execution of a test and marks it as "errored".

### Notices

The `convertNoticesToExceptions` configuration option should be removed.

A new configuration option, `markNoticesAsRisky` (default: `true`) should be added.

A test that does not fail but executes code which emits `E_NOTICE`, `E_USER_NOTICE`, or `E_STRICT` should be marked as "risky" when `markNoticesAsRisky="true"` is configured.

### Warnings

The `convertWarningsToExceptions` configuration option should be removed.

A new configuration option, `markWarningsAsRisky` (default: `true`) should be added.

A test that does not fail but executes code which emits `E_WARNING` or `E_USER_WARNING` should be marked as "risky" when `markWarningsAsRisky="true"` is configured.

### Deprecations

The `convertDeprecationsToExceptions` configuration option should be removed.

A new configuration option, `markDeprecationsAsRisky` (default: `false`) should be added.

A test that does not fail but executes code which emits `E_DEPRECATED` or `E_USER_DEPRECATED` should be marked as "risky" when `markDeprecationsAsRisky="true"` is configured.

### Errors

The `convertErrorsToExceptions` configuration option should be removed.

Errors should be always converted to exceptions, abort the execution of a test, and mark it as "errored".

**Comment by mvorisek** [comment]
Currently, when a notice, a warning or a deprecation (until 9.5.10) is triggered, phpunit by default:

- logs a full stack trace
- exits with non-zero code

Unexpected warnings should not happen in a production code and very often corrupts machine-readable outputs (like API) when emitted.

I belive phpunit should keep the old behaviour as described by the two bullet points and always fail with a non-zero exit code - `failOnRisky` is disabled by default, thus with this proposal it won't.

**Comment by stof** [comment]
AFAICT, the implementation of `->expectWarning` relies on the conversion to exception (as it is implemented as expecting the Warning exception). So this should be re-implemented first before removing those options in the error handler.

**Comment by sebastianbergmann** [comment]
> AFAICT, the implementation of `->expectWarning` relies on the conversion to exception (as it is implemented as expecting the Warning exception). So this should be re-implemented first before removing those options in the error handler.

You're right, and this has already been taken care of. Also note that deprecations, notices, or warnings will not mark the test as risky but instead as having triggered deprecations, notices, or warnings.
