### ISSUE TITLE
convertDeprecationsToExceptions change is BC break

### ISSUE THREAD

**Issue by remicollet** [sebastianbergmann/phpunit#4786]
The change introduces in 8.5.21 / 9.5.10 is a BC break for all projects testing deprecation notices are properly raised by code.

(previous discussion on https://github.com/laminas/laminas-di/pull/30)

Please revert, or, at least, dynamically enable this option when a test adds an expectation on such exception.

**Comment by sebastianbergmann** [comment]
> The change introduces in 8.5.21 / 9.5.10 is a BC break for all projects testing deprecation notices are properly raised by code.

I can only repeat what I wrote [here](https://github.com/laminas/laminas-di/pull/30#issuecomment-927585210):

> I am sorry that reducing friction for the majority of users causes friction for projects such as [laminas-di].
