### ISSUE TITLE
Ensure that deprecations are converted to exceptions when expectDeprecation() is used

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#4789]
As proposed in https://github.com/sebastianbergmann/phpunit/issues/4786#issue-1007809863, to help in situations such as #4788. It may be possible, I will look into this as soon as I get a chance.

**Comment by sebastianbergmann** [comment]
Unfortunately this is not possible without significant changes to PHPUnit's custom error handling.

**Comment by mvorisek** [comment]
What is the best way now to test a deprecation warnings?

**Comment by sebastianbergmann** [comment]
Use `expectDeprecation()` in your test and make sure that `convertDeprecationsToExceptions="true"` is configured in your `phpunit.xml`.
