### ISSUE TITLE
[PROPOSAL] Add flag to the CLI command to skip few tests.

### ISSUE THREAD

**Issue by rosamarsky** [sebastianbergmann/phpunit#4790]
It would be great if you add a flag to the CLI command to skip few tests; 

Something like `phpunit  --skip=8`.

This will be more helpful than trying to find which test failed by counting points and then counting test methods (and lines of dataproviders) because there are still many tests ahead.

And also would be nice the command will works with other flags. For example:
`phpunit  --group=groupName --filter=someFilter --skip=8`. 

I think this feature should have been added a long time ago. Thank you.

**Comment by sebastianbergmann** [comment]
Thank you for your proposal. However, I do not think that this should be added.
