### ISSUE TITLE
Test for dangling error handler registrations?

### ISSUE THREAD

**Issue by lolli42** [sebastianbergmann/phpunit#4801]
Hey. We stumbled upon a scenario in our test suites and think it might be a useful feature for phpunit.

When a test registers an own error handler using `set_error_handler()` and fails to unset this error handler again (eg. in a `tearDown()`), this registered error handler may "eat" errors raised by subsequent unrelated tests, since they may not bubble up into the default phpunit error handler anymore, depending on implementation of that error handler.

Phpunit already implements a similar sanity check in TestCase `stopOutputBuffering()` where it verifies a test did not leave a dangling output buffer. It marks a test that fails to do so as 'risky'.

We'd suggest a similar thing for error handlers. Unfortunately, there is no method like `ob_get_level()` for error handling, but it's still possible to verify if a test added an own error handler, since `set_error_handler()` returns the *previous* one from the stack. We came up with code like that in our general `tearDown()`:

```
            // Register a dummy error handler to retrieve the previous one
            $previousErrorHandler = set_error_handler(function () {});
            // Drop dummy error handler again
            restore_error_handler();
            // Previous *must* be the phpunit ErrorHandler
            if (!$previousErrorHandler instanceof ErrorHandler) {
                throw new \RuntimeException(
                    'tearDown() check: A dangling error handler setup has been found. Use restore_error_handler() to unset it.',
                    1410633510
                );
            }
```

We register a dummy error handler and see if the 'previous' error handler is the phpunit one. If not, we throw an exception, but we could of course throw RiskyTestError() or similar.

Do you think a feature like that would be generally useful for phpunit? If so, we may try to implement something, hoping it's not too complicated ;)

**Comment by sebastianbergmann** [comment]
I do not think that this is worth pursuing, sorry.
