### ISSUE TITLE
`printerClass` deprecated on PHPUnit 10

### ISSUE THREAD

**Issue by nunomaduro** [sebastianbergmann/phpunit#4807]
On the PHPUnit 10 changelog, I've just saw the following entry: 

```
Removed the printerClass and printerFile attributes on the <phpunit> XML configuration element
```

At Laravel, and Pest PHP, we use this option to provider our own printer. Any workaround? If not, could you consider to revert this deprecation? Thank you!

**Comment by epic-64** [comment]
After upgrading to phpunit 10, I'm at a loss finding any good result printer. Could anyone share some links? 

I'm currently using `"robiningelbrecht/phpunit-pretty-print": "^1.4"` with this bit in my phpunit.xml:
```php
<extensions>
    <bootstrap class="RobinIngelbrecht\PHPUnitPrettyPrint\PhpUnitExtension">
        <parameter name="displayProfiling" value="true"/>
    </bootstrap>
</extensions>
```

It is serviceable, but not really what we are used to. For example, it is weird that the duration is shown in seconds in the end (e.g. 1187 seconds). Also, on errors, we do not actually get the name of the method that failed, rather the output is cut off, like this
```
   FAILED  Tests\Feature\Api\DeviceBulkUpdateTest > de…  AssertionFailedError   
```

So I'm looking for professional alternatives.
