### ISSUE TITLE
PHP 8.1: Deprecation error leads to fatal error

### ISSUE THREAD

**Issue by ondrejmirtes** [sebastianbergmann/phpunit#4811]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.4
| PHP version         | 8.1.0RC5
| Installation Method | Composer

#### Summary

When a test loads a class that triggers some of the deprecation errors new to PHP 8.1 (about missing covariant return type), the registered PHPUnit error handler converts the deprecation to an exception.

I originally reported this as a PHP bug but they pointed me to the error handler: https://bugs.php.net/bug.php?id=81571

#### Current behavior

PHP Fatal error:  During inheritance of ArrayAccess: Uncaught Return type of Hoa\Protocol\Node\Node::offsetExists($  
  name) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChan  
  ge] attribute should be used to temporarily suppress the notice     

#### How to reproduce

Try to load a class with deprecated features when running PHPUnit on PHP 8.1.

#### Expected behavior

Deprecation error stays a deprecation error and doesn't crash the PHP process.

**Comment by sebastianbergmann** [comment]
Please update to PHPUnit 9.5.10.
