### ISSUE TITLE
Do not enforce time limits when a debugging session through DBGp is active

### ISSUE THREAD

**Issue by wikando-ck** [sebastianbergmann/phpunit#4812]
I frequently run into test timeouts when step debugging tests.
This effectively ruins step debugging, as a TimeoutException is thrown after the first step.

We enforce timeouts via config and run tests in strict mode.
My workaround is to change the test to `@large` manually.

I have researched setting the timeout via cli, which could be set in PHPStorm test runner configuration for debugging.
However, `--enforce-time-limit` has no param and only allows the opposite.
`--default-time-limit <sec>` - only for tests without @small, @medium or @large annotations.

I'd love to contribute a listener but have found no way to change the timeout configuration from inside a listener.
Any hints towards that would be appreciated.

**Comment by sebastianbergmann** [comment]
@derickr Can I detect in userland whether Xdebug's debugging is active?

**Comment by sebastianbergmann** [comment]
However, the best course of action would probably be to add a `--do-not-enforce-time-limit` CLI option.

**Comment by wikando-ck** [comment]
> @derickr Can I detect in userland whether Xdebug's debugging is active?

That's possible using [xdebug_is_debugger_active](https://xdebug.org/docs/all_functions#xdebug_is_debugger_active)

**Comment by sebastianbergmann** [comment]
> That's possible using [xdebug_is_debugger_active](https://xdebug.org/docs/all_functions#xdebug_is_debugger_active)

Thank you. Sorry for the noise, @derickr.

**Comment by sebastianbergmann** [comment]
I have updated all maintained branches to check `xdebug_is_debugger_active()` and if there is an active debugging session through DBGp then execution timeouts will not be enforced.
