### ISSUE TITLE
Enum member names cannot be keywords

### ISSUE THREAD

**Issue by ricardoboss** [sebastianbergmann/phpunit#4813]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.10
| PHP version         | 8.1.0RC6-dev
| Installation Method | Composer

#### Summary

I am trying out the new PHP 8.1 enums and stumbled upon an inconsistency regarding enum member names. As it seems, neither PhpUnit or 3v4l allow PHP keywords as enum member names, whereas they are allowed as class constants. Since enums and cases are mostly handled like classes and constants, I think there is an inconsistency.

I already reported it at PhpStorm, because I thought they where to blame (their editor didn't warn me about using a keyword as a member name). There I learned, that this seems to be the correct way to handle this. YouTrack issue: https://youtrack.jetbrains.com/issue/WI-63788

#### Current behavior

The current behaviour spits out this error when using `Continue` as an enum member name during testing:

```
Cannot parse ResponseCode.php: Syntax error, unexpected T_CONTINUE, expecting T_STRING on line 7
```

#### How to reproduce

Write a test covering this piece of code and test it: https://3v4l.org/K8ksR#v8.1rc3

#### Expected behavior

No parsing errors, since the PHP interpreter itself also doesn't warn about this.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by sebastianbergmann** [comment]
@nikic Could this be PHP-Parser related?

**Comment by ricardoboss** [comment]
I actually think this was related to https://github.com/nikic/PHP-Parser/issues/807, since I cannot reproduce it now. I tried using this source code: https://github.com/ricardoboss/phpunit-enum-keyword-parse-error
