### ISSUE TITLE
fail and stop on any

### ISSUE THREAD

**Issue by steamboatid** [sebastianbergmann/phpunit#4815]
while developing at localhost,
despite of finishing all test and see the result, I want to be as strict as possible, find the problematic code, then fixing it.
for that, 
I enable temporarily all arguments
> phpunit -v --stop-on-defect --stop-on-error --stop-on-failure --stop-on-warning --stop-on-risky --stop-on-skipped --stop-on-incomplete --fail-on-incomplete --fail-on-risky --fail-on-skipped --fail-on-warning

Is it possible to ma ke it shorter ?
something like :
> phpunit -v --fail-stop-any
> phpunit -v --fail-on-any
> phpunit -v --stop-on-any
> phpunit -v --strict

or maybe any shorter argument that combine many, many other arguments into.
simply like rsync arguments.

thank you so much.

**Comment by sebastianbergmann** [comment]
The `--stop-on*` options instruct the PHPUnit test runner to stop the execution of all tests when a test does not pass (for a specific reason). `--stop-on-error`, `--stop-on-failure`, and `--stop-on-warning` are redundant when you use `--stop-on-defect` as their effect is included in that.

The `--fail-on*` options control the shell exit code of the PHPUnit test runner. The shell exit code should not matter in the scenario you describe.
