### ISSUE TITLE
Unsupported Unicode character in XML

### ISSUE THREAD

**Issue by nikolay-jobiqo** [sebastianbergmann/phpunit#4816]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | master
| PHP version         | 7.2
| Installation Method | not installed

#### Summary

I was searching for working solution to escape all unsupported XML symbols and I find Xml::prepareString().
But looks like chars FFFE, FFFF is not get escaped. Can somebody confirm this?

#### Current behavior

Looks like chars FFFE, FFFF is not get escaped

#### How to reproduce
```
$fffe = hex2bin('efbfbe');
Xml::prepareString($fffe);
$ffff = hex2bin('efbfbf');
Xml::prepareString($ffff);
```

#### Expected behavior

Any Unicode character is allowed, excluding the surrogate blocks, FFFE, and FFFF (not even as character reference).
https://www.w3.org/TR/xml/#charsets

**Comment by sebastianbergmann** [comment]
Why do you want to use `Xml::prepareString()`? Also note that this class is marked `@internal`.

**Comment by nikolay-jobiqo** [comment]
Thanks Sebastian.
I was working on issue https://www.drupal.org/project/apachesolr/issues/1819312.
And I was searching for working solution how to remove unsupported Unicode character in XML.
I find this solution you have at Xml::prepareString(). And in comment I think it should also handle case with FFFE, FFFF.

> Any Unicode character is allowed, excluding the surrogate blocks, FFFE, and FFFF (not even as character reference).

I test it, and FFFE, FFFF are not excluded.
I am not sure is it a bug or a feature, and don't know how Xml::prepareString() is using inside PHPUnit.
Maybe just need to update comment.
