### ISSUE TITLE
expectException doesn't print filename and line number

### ISSUE THREAD

**Issue by Geraint** [sebastianbergmann/phpunit#4819]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.10
| PHP version         | 7.4.3
| Installation Method | Composer

#### Summary

In contrast to most assertions, `expectException` doesn't print the filename or line number, making it harder to locate failing tests.

#### Current behavior

```
$ tree -I vendor .
.
├── composer.json
├── composer.lock
├── phpunit.xml
├── tags
└── tests
    └── Test.php

1 directory, 5 files
```

`phpunit.xml`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.2/phpunit.xsd"
         forceCoversAnnotation="true"
         verbose="true">
    <testsuites>
        <testsuite name="default">
            <directory suffix="Test.php">tests</directory>
        </testsuite>
    </testsuites>
</phpunit>
```

`tests\Test.php`:

```php
<?php

declare(strict_types=1);

require __DIR__ . '/../vendor/autoload.php';

use PHPUnit\Framework\TestCase;

final class Test extends TestCase
{
    public function testOne(): void
    {
        $this->expectException(Exception::class);
    }
}
```

#### Actual

```
./vendor/bin/phpunit
PHPUnit 9.5.10 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.4.3
Configuration: /home/geraint/workspace/sandbox/expect-exception-bug/phpunit.xml

F                                                                   1 / 1 (100%)

Time: 00:00.002, Memory: 6.00 MB

There was 1 failure:

1) Test::testOne
Failed asserting that exception of type "Exception" is thrown.

FAILURES!
Tests: 1, Assertions: 1, Failures: 1.
```

#### Expected

```
./vendor/bin/phpunit
PHPUnit 9.5.10 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.4.3
Configuration: /home/geraint/workspace/sandbox/expect-exception-bug/phpunit.xml

F                                                                   1 / 1 (100%)

Time: 00:00.002, Memory: 6.00 MB

There was 1 failure:

1) Test::testOne
Failed asserting that exception of type "Exception" is thrown.

/path/to/project/tests/Test.php:13

FAILURES!
Tests: 1, Assertions: 1, Failures: 1.
```

#### How to reproduce

Create any test file with a failing call to `expectException` and run `phpunit`.

#### Expected behavior

The filename and line number where `expectException` is called is printed out.

**Comment by sebastianbergmann** [comment]
It's an expectation, not an assertion. Therefore there is not really a location to point to.

**Comment by Geraint** [comment]
> 
> 
> It's an expectation, not an assertion. Therefore there is not really a location to point to.

I'm surprised by this.

If an assertion fails, PHPUnit prints the location of the assertion.

If an expectation fails, it seems logical (to me, at least) that PHPUnit could print the location of the expectation.

There is real value in having the output - using a tool like [vim-phpunit](https://github.com/afternoon/vim-phpunit) allows a developer to very quickly get to the location of a failing test - but it doesn't work for `expectException()`, which means the developer is compelled to find the failing test manually.

I imagine all IDE's/plugins that have PHPUnit integration will suffer from the same issue.

Being a heavy user of PHPUnit, I find myself having to manually locate failing tests of this sort reasonably frequently - its a small frustration, but it seems unnecessary, so I don't understand why the location of `expectException()` can't be printed.

Perhaps there are compelling reasons why not.  If so, can you help me understand, please?
