### ISSUE TITLE
Remove dependency on abandoned project phpunit/phpunit-mock-objects.

### ISSUE THREAD

**Issue by rositis** [sebastianbergmann/phpunit#4821]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 4.8.36
| PHP version         | 7.3.31
| Installation Method | Composer

#### Summary

The Composer package phpunit/phpunit currently requires phpunit/phpunit-mock-objects, which is apparently abandoned.

#### Current behavior

Upon updating using Composer 2, the following message was given:
"Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested."

#### Proposed solution
Remove phpunit/phpunit-mock-objects from the requirement list for phpunit/phpunit or provide an alternative.

**Comment by sebastianbergmann** [comment]
PHPUnit 4.8 has not been supported for years and will not be updated.
