### ISSUE TITLE
PHP 8.1:  PHPUnit\Framework\Exception: Aborted (core dumped)

### ISSUE THREAD

**Issue by ostrolucky** [sebastianbergmann/phpunit#4822]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.x, 10.x
| PHP version         | 8.1.0-dev (389b2a446370f8391cedd598bfd27f8120778722)
| Installation Method | Composer

#### Summary

Looks like doctrine-bundle tests under PHP 8.1 usually fail. See https://github.com/doctrine/DoctrineBundle/runs/4203967904?check_suite_focus=true

Problem is sometimes gone when I rebuild the job

Possibly related: https://github.com/sebastianbergmann/phpunit/issues/4622

**Comment by sebastianbergmann** [comment]
You have found a problem in the PHP runtime that leads to a [segmentation fault](https://en.wikipedia.org/wiki/Segmentation_fault). An issue like this has to be reported at https://bugs.php.net/report.php using a minimal, self-contained, reproducing test case.

Please note that a test case that needs to be run through PHPUnit does not qualify as either "minimal" or "self-contained" when reporting bugs for the PHP runtime. Best practices for reporting bugs in PHP are documented [here](https://bugs.php.net/how-to-report.php).

In the case that the segmentation fault happens during continuous integration on [TravisCI](http://travis-ci.org/) then you can [troubleshoot the problem locally using Docker](https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image).

**Comment by ostrolucky** [comment]
Could be also issue in pcov, setup-php, some weird thing phpunit does and so on, like you mentioned here https://github.com/sebastianbergmann/phpunit/issues/4622 I am not going to do the work of creating minimal reproducer at the moment, but thought it would still be good to have a bug report about this somewhere.

**Comment by ostrolucky** [comment]
Looks like it's this bug https://bugs.php.net/bug.php?id=81612 and there is a fix for it here https://github.com/krakjoe/pcov/pull/75

**Comment by ezraobiwale-obb** [comment]
Removing `processIsolation` attribute in phpunit.xml fixed it for me.

![image](https://github.com/sebastianbergmann/phpunit/assets/144131029/7b37a113-836f-4c40-ad26-c1cdf1bb72a1)
