### ISSUE TITLE
AssertEqualsCanonicalizing sorting doesn't work well with null values

### ISSUE THREAD

**Issue by ralphjsmit** [sebastianbergmann/phpunit#4824]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.9
| PHP version         | 8.0.12
| Installation Method | **Composer** / **PHAR**

#### Summary

I'm trying to test whether two arrays are equal, except for the order, which doesn't matter. I've always learned that `assertEqualsCanonicalizing()` is the go-to method for this use case, because it does sorting etc.

I'm trying to compare two arrays, but it looks like `assertEqualsCanonicalizing` applies a different sorting mechanism on the $expected and $output arrays.

#### Current behavior

I'm trying to compare two relatively simple arrays:
<img width="1439" alt="Schermafbeelding 2021-11-17 om 13 28 57" src="https://user-images.githubusercontent.com/59207045/142200812-61763fa9-fa8b-4005-82d5-528ff858a1dd.png">

You can immediately see that those arrays are the same. However, when I do `assertEqualsCanonicalizing`, it gives this result:

<img width="1439" alt="Schermafbeelding 2021-11-17 om 13 29 11" src="https://user-images.githubusercontent.com/59207045/142200932-9db89b2d-f330-4519-9e53-842e607328fc.png">

It looks like it adds the `null` value at the original position in the expected array, whilst putting it on top in the second array.

Shouldn't the sorting be the same for both the expected and the output?
#### How to reproduce

```php
        $input = [
            'object' => 'user',
            'id' => 'ID',
            'type' => 'bot',
            'bot' => [],
            'name' => null,
            'avatar_url' => 'https://secure.notion-static.com/BOT',
        ];

        $output = [
            'object' => 'user',
            'id' => 'ID',
            'type' => 'bot',
            'name' => null,
            'bot' => [],
            'avatar_url' => 'https://secure.notion-static.com/BOT',
        ];

        $this->assertEqualsCanonicalizing($input, $output);
```
#### Expected behavior

`AssertEqualsCanonicalizing()` asserts true.

**Comment by kiler129** [comment]
@sebastianbergmann I think this is actually a bug as `assertEqualsCanonicalizing()` doesn't really apply the sorting correctly:

```php
        $expected = [
            'typeFloat' => 3.0,
            'typeString' => 'foo bar',
            'data' => 'foobar',
            'typeInt' => 42,
            'typeBool' => true,
        ];

        $given = [
            'data' => 'foobar',
            'typeBool' => true,
            'typeFloat' => 3.0,
            'typeInt' => 42,
            'typeString' => 'foo bar',
        ];

        $expectedSorted = $expected;
        $givenSorted = $expected;
        \ksort($expectedSorted);
        \ksort($givenSorted);
        var_dump($expectedSorted === $givenSorted); //bool(true)

        $this->assertEqualsCanonicalizing($expected, $given);
```

<img width="757" alt="image" src="https://user-images.githubusercontent.com/1227834/157399939-c37f9e8e-dc1f-450f-bd79-e7ef1c7b12ee.png">

**Comment by kubawerlos** [comment]
@ralphjsmit @kiler129 is it still an issue for you? I cannot reproduce it from the example here in PHPUnit 10 (lowest supported, currently).
