### ISSUE TITLE
`assertEquals` diff render is incorrect with otherwise passing array items

### ISSUE THREAD

**Issue by mvorisek** [sebastianbergmann/phpunit#4826]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.10
| PHP version         | 7.4.10
| Installation Method | Composer

#### Summary

`assertEquals` diff render is incorrect with otherwise passing array items, when it fails, some extra diff items may be displayed even if these items will otherwise pass the non-strict (aka equals) comparison.

#### Current behavior

```
--- Expected
+++ Actual
@@ @@
 Array (
     'id' => 4
     'name' => 'My Projects'
-    'count' => 3
+    'count' => '3'
     'parent_id' => 1
-    'parent' => 'Desktop'
     'is_deleted' => false
 )
```

#### How to reproduce

```
        $this->assertEquals([
            'id' => 4,
            'name' => 'My Projects',
            'count' => 3,
            'parent_id' => 1,
            'parent' => 'Desktop',
            'is_deleted' => false,
        ], [
            'id' => 4,
            'name' => 'My Projects',
            'count' => '3',
            'parent_id' => 1,
            'is_deleted' => false,
        ]);
```

#### Expected behavior

```
--- Expected
+++ Actual
@@ @@
 Array (
     'id' => 4
     'name' => 'My Projects'
     'count' => 3
     'parent_id' => 1
-    'parent' => 'Desktop'
     'is_deleted' => false
 )
```

**Comment by sebastianbergmann** [comment]
Won't fix, sorry. While I understand that this may be confusing, it also happens to be correct. The comparison itself is performed "not strict", but the visualization uses PHP's `var_export()` function (in `sebastian/exporter`, which in turn is used from `sebastian/comparator`).
