### ISSUE TITLE
New `#[CoversClass()]` does not have corresponding `forceCoversAttribute` setting

### ISSUE THREAD

**Issue by rbaarsma** [sebastianbergmann/phpunit#4827]
We love `@covers` ever since SymfonyCon 2019 and are now migrating to PHP 8 with the new attributes. We found that https://github.com/sebastianbergmann/phpunit/issues/4502 was already closed and introduced a new `#[CoversClass]` that seems to do the same as `@covers` (we always used it only for classes anyway)

Before we used the `forceCoversAnnotation="true"` in the `phpunit.xml` settings to enforce only coverage is calculated that has this annotation. There no longer seems to be such a setting and the `CoversClass` attribute does not seem to do this by default?

I may be missing something here, as I did not really find any documentation on CoversClass yet and it's probably pretty new, so perhaps I should be using it differently?

**Comment by sebastianbergmann** [comment]
While #4502 may be closed, this functionality has not made it into a release yet. PHPUnit 10 is still work in progress. I appreciate any feedback you might have on this work in progress, but I can only advise against using PHPUnit "in production" at this point in time.

That being said, the `forceCoversAnnotation` configuration was renamed to `requireCoverageMetadata` as you can see in the ChangeLog for PHPUnit 10.
