### ISSUE TITLE
Support for Composer 2.2 _composer_autoload_path global

### ISSUE THREAD

**Issue by Seldaek** [sebastianbergmann/phpunit#4835]
Composer 2.2.0 (releasing early December hopefully) will [introduce](https://github.com/composer/composer/pull/10137) a new $_composer_autoload_path global variable which is defined when running a Composer binary. See [docs for the new feature](https://getcomposer.org/doc/articles/vendor-binaries.md#finding-the-composer-autoloader-from-a-binary).

Essentially when running `vendor/bin/phpunit`, instead of running a symlink to `vendor/phpunit/phpunit/phpunit`, Composer will add an intermediate PHP proxy file which looks like this:

```
#!/usr/bin/env php
<?php

/**
 * Proxy PHP file generated by Composer
 *
 * This file includes the referenced bin path (../phpunit/phpunit/phpunit)
 *
 * @generated
 */

$GLOBALS['_composer_autoload_path'] = __DIR__ . '/..'.'/autoload.php';

include __DIR__ . '/..'.'/phpunit/phpunit/phpunit';
```

This means these lines could be changed to support the new variable if present: https://github.com/sebastianbergmann/phpunit/blob/9b18457e015823cf319b3a9cb2edfd8744364a36/phpunit#L61-L67

But the main reason I wanted to point this out is that this will define a new global variable, so any test relying on a given global state might see differences. I'm hoping there aren't too many of these out there, but who knows.

One thing PHPUnit could do is unset the global variable in the bootstrap to ensure it's back to a clean state.

**Comment by sebastianbergmann** [comment]
Initial idea (untested):

```patch
diff --git a/phpunit b/phpunit
index d9e4f7250..360bffbe7 100755
--- a/phpunit
+++ b/phpunit
@@ -58,15 +58,21 @@ if (!ini_get('date.timezone')) {
     ini_set('date.timezone', 'UTC');
 }
 
-foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
-    if (file_exists($file)) {
-        define('PHPUNIT_COMPOSER_INSTALL', $file);
+if (isset($GLOBALS['_composer_autoload_path'])) {
+    define('PHPUNIT_COMPOSER_INSTALL', $GLOBALS['_composer_autoload_path']);
 
-        break;
+    unset($GLOBALS['_composer_autoload_path']);
+} else {
+    foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
+        if (file_exists($file)) {
+            define('PHPUNIT_COMPOSER_INSTALL', $file);
+
+            break;
+        }
     }
-}
 
-unset($file);
+    unset($file);
+}
 
 if (!defined('PHPUNIT_COMPOSER_INSTALL')) {
     fwrite(
```

**Comment by Seldaek** [comment]
Yup that looks good enough :)

**Comment by sebastianbergmann** [comment]
Thank you for the quick feedback, Jordi.
