### ISSUE TITLE
use hasMethod() instead of catching a ReflectionException when checking for SUITE_METHODNAME

### ISSUE THREAD

**Issue by joachim-n** [sebastianbergmann/phpunit#4837]
BaseTestRunner does this:

```
        try {
            $suiteMethod = $testClass->getMethod(self::SUITE_METHODNAME);
            // SNIP
        } catch (ReflectionException $e) {
            $test = new TestSuite($testClass);
        }
```

The exception means that when running a test with Xdebug, an IDE's default configuration to break on exceptions will cause execution to pause at this point in the test. It's not very convenient, since it's not at all interesting to a developer debugging their test.

Using if(hasMethod()) instead would be better.

**Comment by sebastianbergmann** [comment]
The code in question no longer exists in PHPUnit 10 (`master`) and I do not want to unnecessarily (in my opinion) change the existing code in PHPUnit 8.5 and PHPUnit 9.5 for this.

**Comment by joachim-n** [comment]
I saw it doesn't exist in PHPUnit 10, but that has no due date AFAICT.

If it's that you don't have time to work on it rather than you don't want the change to happen, I'll happily make a PR.
