### ISSUE TITLE
Add support for Union Types

### ISSUE THREAD

**Issue by gersonfs** [sebastianbergmann/phpunit#4839]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.5.21
| PHP version         | 8.1.0
| Installation Method | Composer

#### Summary

I'm trying to create a mock of a class that has methods with returns of type "union type"

#### Current behavior

Error: Call to undefined method `ReflectionUnionType::getName()`

#### How to reproduce

I created a test that reproduces the problem: https://github.com/gersonfs/phpunit8-union-type-mock/blob/main/tests/CreateMockTest.php

#### Expected behavior

Test should pass.

I debugged the code and arrived at this line: https://github.com/sebastianbergmann/phpunit/blob/8.5/src/Framework/MockObject/MockMethod.php#L388

But I don't have enough knowledge today to do a pull request to fix it.

**Comment by sebastianbergmann** [comment]
The fact that a version of PHPUnit supports a specific PHP version means that this version of PHPUnit works on that PHP version for PHP code that is compatible with the version of PHP required by the PHPUnit version in question. For example, PHPUnit 8.5 requires PHP 7.2. PHPUnit 8.5 works for PHP code compatible with PHP 7.2 on PHP 8. However, PHPUnit 8.5's test double code generator does not support PHP 8's union types syntax, for example.

**Comment by gersonfs** [comment]
Ok, thanks for clarifying.
