### ISSUE TITLE
Discussion about mainaining a phpunit 4.8 branch

### ISSUE THREAD

**Issue by giftnuss** [sebastianbergmann/phpunit#4841]
Phpunit 4.8 is still widely used because of support for PHP 5. For my project I also still want to support this version.
What is the preferred way to keep phpunit 4.8?
In https://github.com/xinc-develop/phpunit48/ I've updated this branch, so it passes the test suite with recent PHP. Sorry, but my git foo is not good enough, to make a pull request out of this, without a little advice.
Alternative to maintaining this here, it could be published under packagist as _whatever/phpunit48_ ?

Purpose of this branch would be to have a Phpunit workable under PHP from 5.5 up to 8, because a Phpunit without the last features is better than no phpunit. Thank you very much, for all the good things, made done.

**Comment by sebastianbergmann** [comment]
Feel free to maintain PHPUnit 4.8 somewhere else, but offical support here and/or from me is out of the question.
