### ISSUE TITLE
Allow coverage to be declared programatically

### ISSUE THREAD

**Issue by andrewnicols** [sebastianbergmann/phpunit#4845]
In some situations it is desirable to write unit tests where the code under test is provided by a data provider. In this situation it is not possible to use attributes to declare the code coverage becuase the list of classes being tested is perhaps generated dynamically.

To give a more specific example, we have a Privacy API which ensures that all installed plugins meet minimum requirements for our GDPR implementation (e.g. metadata for userid fields in the database are described, deleted users do not break the plugin, etc.).

The list of plugins comes from an API and we use a dataProvider to turn these into a list of plugins to test for different tests.

These are testing real code, but if we want to be strict about coverage, we have to declare these as `@coversNothing`, even though they do in fact test functionality.

Ideally we should be able to use an API to programaticlly declare that a test will be testing a particular class or method, for example:
```
/**
 * ...
 * @dataProvider metadata_provider_provider
 */
public function test_metadata_provider($component, $classname) {
    $this->covers("{$classname}::get_metadata");

    // ...
}
```

I realise that this is a slightly unusual situation in some ways, but it is also perfectly valid.

The above also applies for abstract testcases where some standard tests are run for all child testcases testing standard behaviours of a particular class.

**Comment by sebastianbergmann** [comment]
Won't implement.
