### ISSUE TITLE
Allow addMethods on unknown type mock

### ISSUE THREAD

**Issue by alamirault** [sebastianbergmann/phpunit#4852]
Since https://github.com/sebastianbergmann/phpunit/pull/3687 `setMethods` is deprecated in favor of `onlyMethods` and `addMethods`

It was possible to do this 

```php
$this->getMockBuilder('UnknownClass')
            ->allowMockingUnknownTypes()
            ->setMethods(['execute'])
            ->getMock();
```

but with 

```php
$this->getMockBuilder('UnknownClass')
            ->allowMockingUnknownTypes()
            ->addMethods(['execute'])
            ->getMock();
```

An exception is thrown `PHPUnit\Framework\MockObject\ReflectionException: Class UnknownClass does not exist`.

So is not possible to mock unknown types. 

A possibility is to check `allowMockingUnknownTypes` in mockBuilder and if is true not thrown exception (as suggested here https://github.com/sebastianbergmann/phpunit/pull/3687#issuecomment-756766099)

What do you think ? Or how can I mock methods on unknown type ? (if you are ok, I can make a PR)

**Comment by sebastianbergmann** [comment]
I would gladly consider a pull request. Thanks!

**Comment by sebastianbergmann** [comment]
`getMockBuilder()` will be soft-deprecated (`@deprecated` annotation) in PHPUnit 10.1, deprecated (triggering a deprecation warning) in PHPUnit 11, and removed in PHPUnit 12. Therefore no changes should be made to it anymore.
