### ISSUE TITLE
Bug report in PHPUnit_Extensions_Database_TestCase class in phpunit 9.5.10  - dbunit package

### ISSUE THREAD

**Issue by mahbodsh** [sebastianbergmann/phpunit#4853]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.10
| PHP version         | 7.4.19
| Installation Method | Composer / PHAR

#### Summary

To be able to test my  software, i installed PHPUnit in my laravel project using the composer command " composer require phpunit/phpunit " and to be able to write an integration test with PHPUnit, i had to install the package dbunit, after facing some errors
about incompatibility of the current PHPUnit version and dpunit version, i installed dbunit finally succesfully by putting "phpunit/dbunit": "*" in the composer.json file of the project to install the most compatible version of dbunit with the current PHPUnit version automatically.

While developing an integration test with PHPUnit, i faced some problems which i considered as a simple but important bug.
At first, i created an abstract class which extended PHPUnit_Extensions_Database_TestCase. I created then all required related functions
which a child of this abstract class required. 

**After running the test, i faced following error:**

#### current  behavior
 Class 'PHPUnit_Framework_TestCase' not found.

#### How to reproduce

replacing parent name " PHPUnit\Framework\TestCase " instead of  " PHPUnit_Framework_TestCase " in PHPUnit_Extensions_Database_TestCase class.

#### Expected behavior
finding the prent class " PHPUnit\Framework\TestCase" without not found exception

**After repeating the test run, i faced also the following error:**

#### current  behavior

 Declaration of PHPUnit_Extensions_Database_TestCase::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void in 
\phpUnit\vendor\phpunit\dbunit\PHPUnit\Extensions\Database\TestCase.php 

#### How to reproduce

I solved this error by defining the declaration of setUp function in  " PHPUnit_Extensions_Database_TestCase " class as "void":
 protected function setUp():void

#### Expected behavior

Ruuning the setUp function of " PHPUnit_Extensions_Database_TestCase " class without any error

**After repeating the run test, i faced also the following error:**

#### current  behavior

Declaration of PHPUnit_Extensions_Database_TestCase::tearDown() must be compatible with PHPUnit\Framework\TestCase::tearDown(): void in phpUnit\vendor\phpunit\dbunit\PHPUnit\Extensions\Database\TestCase.php

#### How to reproduce

I solved this error by defining the declaration of tearDown function in  " PHPUnit_Extensions_Database_TestCase " class as "void":
 protected function tearDown():void

#### Expected behavior

Ruuning the tearDownfunction of " PHPUnit_Extensions_Database_TestCase " class without any error

**Comment by sebastianbergmann** [comment]
This is not a bug. Please read release announcements, ChangeLogs, etc. when you upgrade a dependency such as PHPUnit in your project.

This [article](https://thephp.cc/articles/help-my-tests-stopped-working) from 2019 should be a good starting point for you.
