### ISSUE TITLE
execute phpunit 9.5.11 in Github actions

### ISSUE THREAD

**Issue by benblub** [sebastianbergmann/phpunit#4855]
Since yesterday evening without any code changes run `php bin/phpunit`failed in Github actions. I checked the dir where the command is executed and its in root dir where composer.json is listed and phpunit is allready installed.
Error 
```
No composer.json found in the current directory, showing available packages from packagist.org
Creating a "phpunit/phpunit" project at "./phpunit-9.5-0"
Installing phpunit/phpunit (9.5.11)
Plugins have been disabled.
  - Installing phpunit/phpunit (9.5.11): Extracting archive
Created project in /home/runner/work/XXX/bin/.phpunit/phpunit-9.5-0
```

A fix is running instead `php vendor/bin/phpunit`

Dunno this is related to phpunit, looks more related to the action package but if others run in same issues it maybe helps.

| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.11
| PHP version         | 8.1.x
| Installation Method | Composer

**Comment by sebastianbergmann** [comment]
This is not an issue in PHPUnit.
