### ISSUE TITLE
Cannot get contents (ob_get_contents) in TestCase.php in method stopOutputBuffering

### ISSUE THREAD

**Issue by rafalswierczek** [sebastianbergmann/phpunit#4856]
PHPUnit version - **9.5.11**
PHP version - **8.1.1**
Installation Method - **Composer**

#### Summary

I have installed PHPUnit in docker container without xdebug and with following php.ini setting:
```
error_reporting = E_ALL
memory_limit = -1
log_errors_max_len=0
zend.assertions=1
assert.exception=1
xdebug.show_exception_trace=0
```

#### Current behavior

Console freezes when tests has been started.
Docker container works as expected as well as overwriting php.ini settings.
It freezes in **ob_get_contents** function in src/Framework/TestCase.php:
![image](https://user-images.githubusercontent.com/37018158/148581451-def987a9-bcdd-447f-94fb-f9ee57ad6564.png)

#### How to reproduce

Run build project with docker-compose and run `docker-compose exec php vendor/bin/phpunit`
Well I don't believe it's PHPUnit's fault but I feel like I did nothing wrong so this Issue might help someone if we find the solution.

#### Expected behavior

Tests should pass as everything worked before I moved very simple project to the docker

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by rafalswierczek** [comment]
Problem solved. It was my fault.

The problem was that my test case failed due to strange infinite loop behavior on different operation system!
So due to my infinite loop PHPUnit couldn't get content as described.

Sorry for this Issue but maybe someone will resolve similar problem by searching the Google.
