### ISSUE TITLE
Getting blank and no process after updating 9.5.11 version

### ISSUE THREAD

**Issue by creativedevs** [sebastianbergmann/phpunit#4868]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.11
| PHP version         | 7.3
| Installation Method | Composer

#### Summary

Getting blank screens after executing below command

$ ./vendor/bin/phpunit
PHPUnit 9.5.11 by Sebastian Bergmann and contributors.

testcase are not running

#### Expected behavior

Added details in previous ticket https://github.com/sebastianbergmann/phpunit/issues/4863

**Comment by sebastianbergmann** [comment]
There is no point in opening a new ticket without any new information. I cannot reproduce your problem, sorry.
