### ISSUE TITLE
change junit testcase name via annotation

### ISSUE THREAD

**Issue by gimler** [sebastianbergmann/phpunit#4875]
I would like to change the `name` attribute from `<testcase>` in the junit xml via annotation.

We have a company wide component that reads jira issues from the `name` attribute.
Actually i can only name my test method testXJIRA-4342JIRA-23423423JIRA-34343 that is not very useful.

The code to detect the name is here
https://github.com/sebastianbergmann/phpunit/blob/e4d18b9365f79987d8a70064776ea35f4304e9cd/src/Logging/JUnit/JunitXmlLogger.php#L396

Options:
a. use `@test` to fill the `name`attribute
b. use `@testdox` to fill the `name`attribute
c. new `@name` to fill the `name`attribute

Would a PR that implement one of the options be accepted? Which is the preferred option?

**Comment by sebastianbergmann** [comment]
I think should be done using XSLT, for instance, outside of PHPUnit.

**Comment by gimler** [comment]
@sebastianbergmann
When the junit.xml is generated i did not have the information in it. I did not want use stupid test method names. 

I must reparse the php annotations and change the testcase elements in the xml.
