### ISSUE TITLE
Pipeline failing when merging develop into master

### ISSUE THREAD

**Issue by K2ouMais** [sebastianbergmann/phpunit#4876]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.13
| PHP version         | 7.4
| Installation Method | Composer

When commiting to my develop branch everything seems to run properly and all tests pass.
When I try to merge develop into the master branch my pipeline fails with the following error.
![Pipeline](https://user-images.githubusercontent.com/52510455/151795459-b03f2fd6-a1b6-4657-b721-e14d99e47141.png)

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.

**Comment by K2ouMais** [comment]
Can you point in the right direction, when I could get some help?

Thank you in advance

**Comment by sebastianbergmann** [comment]
Looks like you might have superfluous `<` characters in sourcecode files in your `vendor` directory. Maybe a merge conflict? I do not know, I cannot debug your environment for you. Sorry.
