### ISSUE TITLE
No stack trace shown when an error occurs during bootstrap

### ISSUE THREAD

**Issue by ShaneOH** [sebastianbergmann/phpunit#4877]
Hey there, I noticed there was a recent commit that added some helpful debug info when the bootstrap script fails:

https://github.com/sebastianbergmann/phpunit/commit/ef1b6b112512788895ad64f167768ce3b4ed166b

I found in my case, I have a large bootstrap file that's somewhat complex, and the output I got was:

```
./vendor/bin/phpunit --bootstrap system/bootstrap.php testing
PHPUnit 9.5.13 by Sebastian Bergmann and contributors.

Error in bootstrap script: Error:
Call to a member function query() on null
```

Given the complexity, this still wasn't too useful in tracing down the issue until I went in and manually added a stack trace to the error output. 

Is there a reason to omit a stack trace? If not, I will happily open a PR to add it!

**Comment by sebastianbergmann** [comment]
Feel free to send a PR.

**Comment by ShaneOH** [comment]
@sebastianbergmann Great -- just opened one here! https://github.com/sebastianbergmann/phpunit/pull/4878
