### ISSUE TITLE
Setting Env Variables With $_ENV[keyName] Issue

### ISSUE THREAD

**Issue by crc-sstubbs** [sebastianbergmann/phpunit#4882]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.10
| PHP version         | 8.0.15
| Installation Method | Composer

#### Summary

Setting env variables with $_ENV[keyName] does not seem to be working.

#### Current behavior

On a project where setting environment variables using $_ENV[keyName] in unit tests has worked in the past. I've been doing a bit of checking on it and it appears these variables are remaining unchanged. force="true" is being used in the test.xml

#### How to reproduce

- Create a project with a single unit test and a single variable in tests.xml with force="true". 
- Try override this by setting the variable with $_ENV[keyName]
- var_dump the variable

#### Expected behavior

The variable should be change

**Comment by sebastianbergmann** [comment]
I cannot reproduce this.
