### ISSUE TITLE
MockBuilder respect namespace

### ISSUE THREAD

**Issue by bumbummen99** [sebastianbergmann/phpunit#4883]
Related: https://github.com/sebastianbergmann/phpunit-mock-objects/issues/134

I am trying to mock DNS resolution in my project kinda like in this example:
https://github.com/symfony/phpunit-bridge/blob/5.3/DnsMock.php

The issue is that i am trying to do that for a class that i am Mocking. The MockBuilder does create the class in the global namespace, therefore monkey patching global functions using namespace resolution is not possible.

Is there any good way to do what i am trying to do?

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.
