### ISSUE TITLE
data provider collision not reported

### ISSUE THREAD

**Issue by theofidry** [sebastianbergmann/phpunit#4884]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.13
| PHP version         | 7.4.2 - 8.1.1
| Installation Method | Composer

#### Summary

The following case is a simple and standard usage of a data provider:

```php
class Test extends TestCase {
  /** @dataProvider valueProvider */
  function test_it_tests_smth($value): void { ... }

  static function valueProvider(): iterable {
    yield 'key1' => [...];
  }
}
```

And if by mistake I yield several times the key `key1` I will get an error:

```
1) Error
The data provider specified for Acme\Test::test_it_tests_smth is invalid.
PHPUnit\Framework\InvalidDataProviderException: The key "key1" has already been defined in the data provider "valueProvider".
...
```

How this is no longer true when using multiple providers:

```php
class Test extends TestCase {
  /**
    * @dataProvider valueProviderA
    * @dataProvider valueProviderB
    */
  function test_it_tests_smth($value): void { ... }

  static function valueProviderA(): iterable {
    yield 'key1' => [...];
  }

  static function valueProviderB(): iterable {
    yield 'key1' => [...];
  }
}
```

As: only one set will be take and no warning is given.

#### Current behavior

With the example above, only one test will be executed.

#### How to reproduce

See example above.

#### Expected behavior

I would either expect 2 tests or a `InvalidDataProviderException` exception to be thrown.

**Comment by sebastianbergmann** [comment]
Superseded by #5039, I think.
