### ISSUE TITLE
SebastianBergmann\CodeCoverage\Data\RawCodeCoverageData Moved

### ISSUE THREAD

**Issue by bartholdbos** [sebastianbergmann/phpunit#4895]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.15
| PHP version         | 8.0.7
| Installation Method | Composer

#### Summary

When running PHPUnit through the PHPUnit Bridge simple-phpunit script the newest version of PHPUnit is installed. In this version an error occurs due to a change in namespaces. Unit tests are not executed after this

#### Current behavior

```SebastianBergmann\CodeCoverage\CodeCoverage::append(): Argument #1 ($rawData) must be of type SebastianBergmann\CodeCoverage\Data\RawCodeCoverageData, SebastianBergmann\CodeCoverage\RawCodeCoverageData given, called in /app/vendor/bin/.phpunit/phpunit-9.5-0/vendor/phpunit/php-code-coverage/src/CodeCoverage.php on line 224```

#### How to reproduce

`vendor/bin/simple-phpunit --testsuite unit --coverage-text --coverage-clover /tmp/reports/clover-coverage.xml --coverage-cobertura /tmp/reports/Cobertura.xml --colors=never --log-junit /tmp/reports/junit_unit.xml`

#### Expected behavior

Normal execution of tests

**Comment by bartholdbos** [comment]
It looks like the problem is in PHPUnit Bridge, the bridge script does a clean install of PHPUnit in its own directory but also also seems to include phpunit files from the parent project. And because phpunit in the parent project was not the latest version it did not have the recent namespace changes.

**Comment by sebastianbergmann** [comment]
* I have [yanked](https://github.com/sebastianbergmann/php-code-coverage/blob/9.2.13/ChangeLog.md#9212---2022-02-23-yanked) phpunit/php-code-coverage 9.2.12, the corresponding tag has been deleted
* I have [yanked](https://github.com/sebastianbergmann/phpunit/blob/9.5.16/ChangeLog-9.5.md#9515---2022-02-23-yanked) phpunit/phpunit 9.5.15, the corresponding tag has been deleted
* I have [released](https://github.com/sebastianbergmann/php-code-coverage/blob/9.2.13/ChangeLog.md#9213---2022-02-23) phpunit/php-code-coverage 9.2.13
* I have [released](https://github.com/sebastianbergmann/phpunit/blob/9.5.16/ChangeLog-9.5.md#9516---2022-02-23) phpunit/phpunit 9.5.16

**Comment by bartholdbos** [comment]
Thanks, this should fix the issue for now. I was also trying to make a bug project for the Symfony PHPUnit Bridge because I don't think the bridge script should use the phpunit/php-code-coverage from the parent project.
