### ISSUE TITLE
Test that phpunit.phar is scoped

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#4896]
Inspired by https://github.com/box-project/box/pull/632. Thanks, @theofidry!

**Comment by sebastianbergmann** [comment]
@localheinz Maybe this is something for you to explore, Andreas?

**Comment by localheinz** [comment]
@sebastianbergmann 

Apologies for the delay, will take a 👀 on Friday this week!

**Comment by sebastianbergmann** [comment]
No worries!
