### ISSUE TITLE
Is commenting docs supported in phpUnit?

### ISSUE THREAD

**Issue by Danon** [sebastianbergmann/phpunit#4899]
I had a test like that in my [T-Regx](https://github.com/T-Regx/T-Regx) library

```php
/**
 * @test
 * @depends shouldUsePlaceholder_PatternExtended_Reset
 * @depends shouldUsePlaceholder_SubpatternExtended_Reset
 */
public function shouldUsePlaceholderInComment_ResetOtherSubpattern()
{
    // when
    $pattern = Pattern::inject("(?x:(?^))#@\n", ['Foo']);

    // then
    $this->assertConsumesFirst("#Foo\n", $pattern);
    $this->assertSamePattern("/(?x:(?^))#Foo\n/", $pattern);
}
```

I wanted to temporarily disable the `@depends` clause; I'm using PhpStorm, so I selected the lines and pressed <kbd>Ctrl+/</kbd>, and that's what PhpStorm did what's seen below, but it didn't work.

```php
    /**
     * @test
//     * @depends shouldUsePlaceholder_PatternExtended_Reset
//     * @depends shouldUsePlaceholder_SubpatternExtended_Reset
     */
    public function shouldUsePlaceholderInComment_ResetOtherSubpattern()
    {
        // when
        $pattern = Pattern::inject("(?x:(?^))#@\n", ['Foo']);

        // then
        $this->assertConsumesFirst("#Foo\n", $pattern);
        $this->assertSamePattern("/(?x:(?^))#Foo\n/", $pattern);
    }
```

And I'm wondering, is this supposed to be supported by PhpUnit? Is there even such a thing as commenting out phpDocs? Should PhpUnit handle such a thing?

Or is this clearly PhpStorm bug and it should comment the PhpUnit annotations differently?

**Comment by sebastianbergmann** [comment]
"Commenting out" annotations is not supported.

**Comment by Danon** [comment]
Thanks for clarification.
