### ISSUE TITLE
Arrays with different keys do not fail equality, with canonicalization

### ISSUE THREAD

**Issue by benbankes** [sebastianbergmann/phpunit#4902]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | Same as CI/CD (currently 10.0-dev, 389c49782d68847d84826d78157a9c678091caf4)
| PHP version         | Same as CI/CD (currently PHP 8 & 8.1)
| Installation Method | Managed by CI/CD

This screenshot from the [CI/CD Run](https://github.com/sebastianbergmann/phpunit/runs/5408899525?check_suite_focus=true) show the versions of PHPUnit, PHP, and have the installation method codified within CI/CD...

![image](https://user-images.githubusercontent.com/2132746/156591982-17c26243-607c-4609-8645-1a740737bc17.png)

#### Summary

Assertions for equality of associative arrays (with canonicalizing) unexpectedly succeeds when two arrays with different keys are compared.

Based on the documentation for [assertEqualsWithCanonicalizing](https://phpunit.readthedocs.io/en/9.5/assertions.html#assertequalscanonicalizing) I expect to be able to assert that associative arrays are not equal (when canonicalizing) if their keys are not equal.

#### Current behavior

The following assertion succeeds, even though their keys are not equal.
```
$this->assertEqualsCanonicalizing(
    ['a' => 2, 'bb' => 3], 
    ['a' => 2, 'b' => 3]
);
```

I suspect that a check for the equality of the keys has been overlooked.

#### How to reproduce

This has been reproduced adequately by tests in
- [PR #4901]

See screenshot of the failed test, after adding the following lines to `PHPUnit\Framework\AssertTest`.

```
 public function testAssociativeArraysCanBeComparedForEqualityWithCanonicalization(): void
    {
        $this->assertEqualsCanonicalizing(['a' => 2, 'b' => 3], ['b' => 3, 'a' => 2]);

        $this->assertNotEqualsCanonicalizing(['aa' => 2, 'b' => 3], ['a' => 2, 'b' => 3]);
    }
```

![image](https://user-images.githubusercontent.com/2132746/156595703-52d68327-de79-4edd-8690-8c611c4fa32e.png)

#### Expected behavior

I expect this assertion (for equality) to fail.
```
$this->assertEqualsCanonicalizing(
    ['a' => 2, 'bb' => 3], 
    ['a' => 2, 'b' => 3]
);
```

and this assertion (for INequality) to succeed.
```
$this->assertNotEqualsCanonicalizing(
    ['a' => 2, 'bb' => 3], 
    ['a' => 2, 'b' => 3]
);
```

Note the "not" added to the 2nd assertion.

**Comment by sebastianbergmann** [comment]
Different keys means different array, this is not something that canonicalization is intended to "fix".

**Comment by benbankes** [comment]
Ah.  Ok.  🤷 Thanks for taking the time to go through it!  Are PRs to the documentation welcome?  Is this something that could use some additional documentation?
