### ISSUE TITLE
Test Double code generator does not handle new expressions inside parameter default values

### ISSUE THREAD

**Issue by maxm86545** [sebastianbergmann/phpunit#4929]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.18
| PHP version         | 8.1.2
| Installation Method | Composer

#### Summary

**createMock** is not working with [new in initializers](https://www.php.net/manual/en/migration81.new-features.php#migration81.new-features.core.new-in-initializer)

#### Current behavior
Tests fail with an incomprehensible error:

`PHP Fatal error:  Constant expression contains invalid operations in /var/www/html/app/vendor/phpunit/phpunit/src/Framework/MockObject/MockClass.php(51) : eval()'d code on line 9`

#### How to reproduce

````php
class MyClass {
    public static function create(Example $example = new Example()) {
    // ...
    }
}
````

````php
    // ...

    public function testSome(): void
    {
        $this->createMock(MyClass::class); // <--- PHP Fatal error
    }

    / ...
````

#### Expected behavior

Mock is created successfully.

**Comment by sebastianbergmann** [comment]
@nikic Am I missing something or are [string operations on the return value of `ReflectionParameter::__toString()`](https://github.com/sebastianbergmann/phpunit/blob/fef420d8d81c1b5082c07472c83a95be4983db87/src/Framework/MockObject/MockMethod.php#L385) really the only way to access the information we need here through the Reflection API?
