### ISSUE TITLE
Disabling cache results still generates coverage cache files.

### ISSUE THREAD

**Issue by ooobii** [sebastianbergmann/phpunit#4941]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.19
| PHP version         | 7.3.33
| Installation Method | `Composer`

#### Summary

Code coverage cache files are being generated when the flag for not cacheing results is in use. Maybe i'm missing a command line option for coverage caches, but I feel the `--do-not-cache-result` flag should prevent **all** cache files from being generated.

#### Current behavior

PHPUnit coverage tests are generating cache files when a command-line flag is specified that should disable caching results.

#### How to reproduce

1. In your `phpunit.xml` file, add a `coverage` element, and set a value for the `cacheDirectory` attribute.
2. In bash, execute the following:
```
XDEBUG_MODE=coverage ./vendor/bin/phpunit --do-not-cache-result --coverage-html tests/results/coverage
```
3. Even though the `--do-not-cache-result` flag is specified, cache files are still generated within the directory specified in the `cacheDirectory` attribute in `phpunit.xml`

#### Expected behavior

The `--do-not-cache-result` value should not only apply to test results, but also to coverage results as well 😄

**Comment by kubawerlos** [comment]
> Code coverage cache files

There is no such thing. There are:
- code coverage report files (not a cache in any way, each PHPUnit run ignores previous reports and writes new one fully) that you generate when using `--coverage-html` param
- cache result file, which you can configure via [these](https://phpunit.readthedocs.io/en/9.5/configuration.html?highlight=cache#the-cacheresult-attribute) options

**Comment by ooobii** [comment]
> There is no such thing.

There is indeed such a thing. [See the coverage configuration documentation here](https://phpunit.readthedocs.io/en/9.5/configuration.html#the-cachedirectory-attribute).

**Comment by sebastianbergmann** [comment]
The test result cache and the code coverage static analysis cache are two different systems that are controlled by separate configuration options.

**Comment by ooobii** [comment]
> The test result cache and the code coverage static analysis cache are two different systems that are controlled by separate configuration options.

so how do you disable the coverage static analysis cache without modifying the configuration XML? there is no documented command line switch that disables it...

Thanks for closing the issue abruptly.... i'll just figure it out a different way 🙄

**Comment by WalterWoshid** [comment]
Same issue, it definitely gets cached, because the debugger never jumps in some constructors, but class methods are still called
