### ISSUE TITLE
The "verbose" setting controls too much

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#4956]
The configuration setting controlled by the `--verbose` CLI option and the `<phpunit verbose="true"/>` XML configuration attribute controls too much.

There are at least three additional pieces of information that are printed when verbose output is active:

1. Information about the PHP runtime and the path to the PHPUnit XML configuration file used
2. Details about incomplete and skipped tests
3. Execution time of a test in TestDox output

Going forward, I think that 1) should always be printed and 2) and 3) should be controlled by separate configuration settings.

**Comment by jrfnl** [comment]
>     3. Execution time of a test in TestDox output
> 
> Going forward, I think that 1) should always be printed and 2) and 3) should be controlled by separate configuration settings.

@sebastianbergmann Was a replacement for 3) ever implemented ? I can't seem to find it and am noticing that I really miss the test execution time information in the TestDox output when using PHPUnit 10/11.

**Comment by sebastianbergmann** [comment]
> Was a replacement for 3) ever implemented?

No.

**Comment by jrfnl** [comment]
@sebastianbergmann Is it still being considered ? Should I open an issue as a reminder that part of this issue was never addressed ?

**Comment by sebastianbergmann** [comment]
Feel free to open an issue for this. As I do not need this myself, I cannot promise that I will implement this.
