### ISSUE TITLE
withContext(...) feature reuqest

### ISSUE THREAD

**Issue by top-master** [sebastianbergmann/phpunit#4960]
In our project's `testRoutes_shouldDenyCustomersAccessToAdminPages()` test, we have a for-loop that iterates each and every "admin" prefixed route of our `PHP` App.

Now **sometimes an error is thrown**, or the assertion fails, and we would like to know for which route exactly, for that, said for-loop stores the **context** in `lastRoute` instance-variable of test-case, and `TestListener` prefixes the logged `message` with said context, like:
```php
public function addError(Test $test, \Throwable $t, float $time): void
{
    $this->onThrow($test, $t);
}
public function addFailure(Test $test, AssertionFailedError $error, float $time): void
{
    $this->onThrow($test, $error);
}

private function onThrow(Test $test, \Throwable $error)
{
    if ($test instanceof MyTest) {
        if ($test->lastRoute !== null) {
            self::prefixMessage($error, 'While testing route = ' . $test->lastRoute . ":\n");
        }
    }
}

private static function prefixMessage($obj, $prefix)
{
    try {
        $reflection = new \ReflectionClass($obj);
        $property = $reflection->getProperty('message');
        $property->setAccessible(true);
        $property->setValue($obj, $prefix . $property->getValue($obj));
    } catch (\ReflectionException $e) {
    }
}
```

---

@sebastianbergmann How can we achive above with the new `TestHook` API?  
Which looks like:
```php
interface AfterTestErrorHook extends TestHook
{
    public function executeAfterTestError(string $test, string $message, float $time): void;
}

interface AfterTestFailureHook extends TestHook
{
    public function executeAfterTestFailure(string $test, string $message, float $time): void;
}
```
>I mean, we could Make the `lastRoute` a static-variable (instead of instance-variable).  
>But how can we alter the `$message`?
>

## Solutions
As you deprecated our side of handling this,
please consider implementing one of below solutions into `PHPUnit` API.

**# 1** You could change your existing API's `$message` to `&$message`, I mean, to a reference, then use reflection like above (to update message).

**# 2** Or, like some other frameworks, provide `withContext(...)` method, and the next failure (no matter if error or assert) should log the `context` before actual `message`, then clear context.
>Also, test-runner should clear `context` after each test-method (of course).

**Comment by sebastianbergmann** [comment]
1) The `TestHook` API is not new and it will be removed. The background is explained [here](https://github.com/sebastianbergmann/phpunit/issues/4676#issue-896325929).

2) I do not understand the problem you are trying to solve, therefore I cannot help you.

From the example code you shared, I get the impression that you are coupling your test code too tightly to your production code. For instance, you're testing private implementation details. I get the feeling that you are investing a lot of time and effort into testing infrastructure that would be far better invested into refactoring your production code to be easier to test.

Please understand that this topic is outside the scope of an issue tracker.

**Comment by top-master** [comment]
@sebastianbergmann 

**First of all,** thanks for soon-removing `TestHook` thing, was not useful for me at least.

**Secondly,** let's ignore the well explained "situation and background", and don't try not help ;-)

**Last but not least,** please add some-way (feature) to log a custom-message, and that right at top of the next failure's log:
* We **can't** (even if we wanted) edit the message of exceptions all over the application.
* I don't want to change each assert's message manually.

**Comment by top-master** [comment]
**Note** that someone already suggested [data-provider](https://phpunit.readthedocs.io/en/9.5/writing-tests-for-phpunit.html#data-providers), and here is my answer:

**First of all,** that would make the message look something like:
```
1) Tests\MyTest::testRoutes_shouldDenyCustomersAccessToAdminPages with data set #3 ('/admin/users/edit')
Failed asserting that ...
```
Instead of:
```
1) Tests\MyTest::testRoutes_shouldDenyCustomersAccessToAdminPages
While testing route = /admin/users/edit:
Failed asserting that ...
```

And someone later running the tests would get confused (as we don't write tests for ourselves).

**Secondly,** storing each and every route in `array` is not always possible, for example:
* If each route (or data-set) requires some additional data.
* The data-provider would need to pass (i.e. return) those, too.
* Which all go into our logs, making the already confusing data-provider-log even more unreadable.

**Last *and least***, rewritting logic to create `array` with specific structure, instead of simply iterating would take time.

**Comment by top-master** [comment]
# Coupling

In object oriented design, Coupling refers to the degree of direct knowledge that one element has of another. In other words, how often do changes in class A force related changes in class B.\
**There are two types of coupling:**

1.  **Tight coupling :** In general, Tight coupling means the two classes often change together. In other words, if A knows more than it should about the way in which B was implemented, then A and B are tightly coupled.\
    **Example :** If you want to change the skin, you would also have to change the design of your body as well because the two are joined together -- they are tightly coupled. The best example of tight coupling is RMI(Remote Method Invocation).


```java
// Java program to illustrate
// tight coupling concept
class Subject {
	Topic t = new Topic();
	public void startReading()
	{
		t.understand();
	}
}
class Topic {
	public void understand()
	{
		System.out.println("Tight coupling concept");
	}
}
```

**Explanation:** In the above program the Subject class is dependents on Topic class. In the above program Subject class is tightly coupled with Topic class it means if any change in the Topic class requires Subject class to change. For example, if Topic class understand() method change to gotit() method then you have to change the startReading() method will call gotit() method instead of calling understand() method.

```java
// Java program to illustrate
// tight coupling concept
class Volume
{
	public static void main(String args[])
	{
		Box b = new Box(5,5,5);
		System.out.println(b.volume);
	}
}
class Box
{
	public int volume;
	Box(int length, int width, int height)
	{
		this.volume = length * width * height;
	}
}
```

Output:
>125

**Explanation:** In the above example, there is a strong inter-dependency between both the classes. If there is any change in Box class then they reflects in the result of Class Volume.

1.  **Loose coupling :** In simple words, loose coupling means they are mostly independent. If the only knowledge that class A has about class B, is what class B has exposed through its interface, then class A and class B are said to be loosely coupled. In order to over come from the problems of tight coupling between objects, spring framework uses dependency injection mechanism with the help of POJO/POJI model and through dependency injection its possible to achieve loose coupling.\
    **Example :** If you change your shirt, then you are not forced to change your body -- when you can do that, then you have loose coupling. When you can't do that, then you have tight coupling. The examples of Loose coupling are Interface, JMS.

```java
// Java program to illustrate
// loose coupling concept
public interface Topic
{
	void understand();
}
class Topic1 implements Topic {
public void understand()
	{
		System.out.println("Got it");
	}
} class Topic2 implements Topic {
public void unserstand()
	{
		System.out.println("understand");
	}
} public class Subject {
public static void main(String[] args)
	{
		Topic t = new Topic1();
		t.understand();
	}
}
```

**Explanation:** In the above example, Topic1 and Topic2 objects are loosely coupled. It means Topic is an interface and we can inject any of the implemented classes at run time and we can provide service to the end user.

```java
// Java program to illustrate
// loose coupling concept
class Volume
{
	public static void main(String args[])
	{
		Box b = new Box(5,5,5);
		System.out.println(b.getVolume());
	}
}
final class Box
{
	private int volume;
	Box(int length, int width, int height)
	{
		this.volume = length * width * height;
	}
	public int getVolume()
	{
		return volume;

	}
}
```

Output:
>125

**Explanation:** In the above program, there is no dependency between both the classes. If we change anything in the Box classes then we dont have to change anything in Volume class.

**Which is better tight coupling or loose coupling?**

In general, Tight Coupling is bad in but most of the time, because it reduces flexibility and re-usability of code, it makes changes much more difficult, it impedes test ability etc. loose coupling is a better choice because A loosely coupled will help you when your application need to change or grow. If you design with loosely coupled architecture, only a few parts of the application should be affected when requirements change.\
**Lets have a look on the pictorial view of tight coupling and loose coupling:**
![Coupling in Java](Coupling-in-Java.png)

**Difference between tight coupling and loose coupling**

-   Tight coupling is not good at the test-ability. But loose coupling improves the test ability.
-   Tight coupling does not provide the concept of interface. But loose coupling helps us follow the GOF principle of program to interfaces, not implementations.
-   In Tight coupling, it is not easy to swap the codes between two classes. But it's much easier to swap other pieces of code/modules/objects/components in loose coupling.
-   Tight coupling does not have the changing capability. But loose coupling is highly changeable.

**Comment by top-master** [comment]
# Cohesion
cohesive types and `cohesion` in codebase makes maintenance easy since it means:

writing functions related to the same subject in one single class instead of multiple places all over the project

while `loose coupling` is very good design pattern, `cohesion` means putting together what should not be separated

**Comment by remorhaz** [comment]
You can use string keys in data providers, so you can receive any text you wish instead of `#3` in error message.

> rewritting logic to create `array` with specific structure, instead of simply iterating would take time.

You don't need to create an array: data provider can be a generator, so you can just `yield` data sets from within iteration cycle.

**Comment by top-master** [comment]
I already found a solution, which is far more human-readable as well:
https://github.com/sebastianbergmann/phpunit/issues/4961#issuecomment-1153083605

No need to **hack** Data-provider to log pretty messages.

However, Data-provider is enabled through doc-comment, which I never did like,
and all that Data-provider offers seems to be logging index and values-provided.
