### ISSUE TITLE
Ukraine banner unreadable on white background

### ISSUE THREAD

**Issue by flack** [sebastianbergmann/phpunit#4962]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.20
| PHP version         | 7.4.28
| Installation Method | Composer

#### Summary

The Ukraine banner shown has black text on dark blue background

#### Current behavior

![Screenshot_20220421_133233](https://user-images.githubusercontent.com/425166/164449324-3536f700-738b-42ee-89a7-647fc51a7d05.png)

pretty unreadable

#### How to reproduce

Just run PHPunit

#### Expected behavior

Compare that to the Ukraine banner from Packagist:

![Screenshot_20220421_133308](https://user-images.githubusercontent.com/425166/164449406-3a3bce0c-06c8-4caf-8cec-7c7325973027.png)

pretty readable

**Comment by fabswt** [comment]
A while ago I had a question about removing the banner. I don't see it anymore. I take it it was removed. Could anyone confirm?
