### ISSUE TITLE
Maybe a strange behavior of withConsecutive when method has try and catch

### ISSUE THREAD

**Issue by Gildo-Sargi-Neto** [sebastianbergmann/phpunit#4963]
I'm having a problem where i am using the withConsecutive to test if a method is beeing called 2 times with the right params, but these 2 method calls are inside a try and catch, and when the first one receives the wrong params it does not display the "Failed asserting that two objects are equal." error message, instead it returns the exception that it expected to be called 2 times and was called only 1 time

example:
```
function foo() 
{
    try {
        $this->get($wrongParams)
    
        $this->get($rightParams)
    } catch ($e) {
        return $e;
    } 
}
```
Mock testing example:
```
  $mock->expects($this->exactly(2))
      ->method($method)
      ->withConsecutive(...$params);
```
Since phpunit will throw an exception when the first one receives the wrong params the second one will not be called and the "expects to be called..." error happens, am i missing something or this should not happen?

The "Failed asserting that two objects are equal" is much more understandable and usefull

**Comment by sebastianbergmann** [comment]
No changes will be made to `withConsecutive()`, it is scheduled for deprecation and removal.

Rewrite your tests and/or your production code to not require this feature. Maybe this [article](https://thephp.cc/articles/do-not-mock-what-you-do-not-own) can help.
