### ISSUE TITLE
Unable to Download phar from https://phar.phpunit.de/

### ISSUE THREAD

**Issue by DennisXH** [sebastianbergmann/phpunit#4969]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | x.y.z
| PHP version         | x.y.z
| Installation Method | Composer / PHAR

#### Summary

Unable to Download phpunit phar from https://phar.phpunit.de/

#### Current behavior

phpunit server is no response and giving a 503

#### Expected behavior
Be able to download phpunit phar from https://phar.phpunit.de/

**Comment by sebastianbergmann** [comment]
`phar.phpunit.de` is currently [under attack](https://twitter.com/s_bergmann/status/1526857002030354432).
