### ISSUE TITLE
PHPT test has unexpected "Standard input code:" added to its output

### ISSUE THREAD

**Issue by dbrumann** [sebastianbergmann/phpunit#4971]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.20
| PHP version         | 8.1.5
| Installation Method | Composer

#### Summary

I have a some phpt-tests. In Github Actions they produce the expected output and work fine, but locally the produce different output. The output contains the added line "Standard input code:5:\n" with the number changing between tests. The bug occured, when we switched from phive to using composer. Here is a composer info output from my reproducer:

```
composer info | sort

doctrine/instantiator              1.4.1   A small, lightweight utility to instantiate objects in PHP without invoking their constructors
myclabs/deep-copy                  1.11.0  Create deep copies (clones) of your objects
nikic/php-parser                   v4.13.2 A PHP parser written in PHP
phar-io/manifest                   2.0.3   Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                    3.2.1   Library for handling version information and constraints
phpdocumentor/reflection-common    2.2.0   Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock  5.3.0   With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded ...
phpdocumentor/type-resolver        1.6.1   A PSR-5 based resolver of Class names, Types and Structural Element Names
phpspec/prophecy                   v1.15.0 Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage          9.2.15  Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator          3.0.6   FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-invoker                3.1.1   Invoke callables with a timeout
phpunit/php-text-template          2.0.4   Simple template engine.
phpunit/php-timer                  5.0.3   Utility class for timing
phpunit/phpunit                    9.5.20  The PHP Unit Testing framework.
sebastian/cli-parser               1.0.1   Library for parsing CLI options
sebastian/code-unit                1.0.8   Collection of value objects that represent the PHP code units
sebastian/code-unit-reverse-lookup 2.0.3   Looks up which function or method a line of code belongs to
sebastian/comparator               4.0.6   Provides the functionality to compare PHP values for equality
sebastian/complexity               2.0.2   Library for calculating the complexity of PHP code units
sebastian/diff                     4.0.4   Diff implementation
sebastian/environment              5.1.4   Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 4.0.4   Provides the functionality to export PHP variables for visualization
sebastian/global-state             5.0.5   Snapshotting of global state
sebastian/lines-of-code            1.0.3   Library for counting the lines of code in PHP source code
sebastian/object-enumerator        4.0.4   Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector         2.0.4   Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context        4.0.4   Provides functionality to recursively process PHP variables
sebastian/resource-operations      3.0.3   Provides a list of PHP built-in functions that operate on resources
sebastian/type                     3.0.0   Collection of value objects that represent the types of the PHP type system
sebastian/version                  3.0.2   Library that helps with managing the version number of Git-hosted PHP projects
symfony/polyfill-ctype             v1.25.0 Symfony polyfill for ctype functions
theseer/tokenizer                  1.2.1   A small library for converting tokenized PHP source code into XML and potentially other formats
webmozart/assert                   1.10.0  Assertions to validate method input/output with nice error messages.
```

#### Current behavior

Locally phpt-tests contain unexpected output "Standard input code:..."

#### How to reproduce

I have created a minimal reproducer: https://github.com/dbrumann/phpt-reproducer

Test file (tests/Example.phpt):

```
--TEST--
Reproduce phpt adding output locally
--FILE--
<?php

var_dump('test');

--EXPECT--
string(4) "test"
```

phpunit.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="vendor/phpunit/phpunit/phpunit.xsd"
    bootstrap="vendor/autoload.php"
    colors="true"
>
    <testsuites>
        <testsuite name="phpt">
            <directory suffix=".phpt">./tests</directory>
        </testsuite>
    </testsuites>
    <coverage>
        <include>
            <directory>./src</directory>
        </include>
    </coverage>
</phpunit>
```

#### Expected behavior

Test passes, but instead I get an error because of the added output:

```
1) /Users/dbr/Projects/phpt-reproducer/tests/Example.phpt
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'string(4) "test"'
+'Standard input code:3:\n
+string(4) "test"'
```

**Comment by anzago** [comment]
I had the same problem when executing tests for the phpunit project, I later realised this was added by Xdebug with the `xdebug.mode` option  set to `develop` (see https://xdebug.org/docs/develop#improved_var_dump).
Removing it fixed it for me.

**Comment by dbrumann** [comment]
Thanks for the info @anzago. I will check if I can confirm this and close, if necessary

**Comment by sebastianbergmann** [comment]
@dbrumann Any update on this? Thanks!

**Comment by dbrumann** [comment]
I just checked out my reproducer and ran it and I can't reproduce the issue, neither with `XDEBUG_MODE=off` nor `XDEBUG_MODE=develop`. I consider this resolved for me. Thanks.

**Comment by cweiske** [comment]
I would consider this a bug.
As soon as xdebug3 is installed and `xdebug.mode=develop` is configured in the `.ini` file, `.phpt` tests break if they use `var_dump()`. 

Adjusting `phpunit.xml` by adding `<php><ini name="xdebug.mode" value="off"/></php>` does not work
Adding the setting in an `--INI--` section of the `.phpt` file itself does also not work.

The only workaround is to add `<php><env name="XDEBUG_MODE" value="off"/></php>` to `phpunit.xml`.

----

When debugging the problem I see that phpunit's `PhpTestCase::settings()` tries to set `xdebug.mode=off`, but the resulting command to launch the php process also contains values from the current `php.ini` - which includes `xdebug.mode=develop`:

> [pid 36286] execve("/usr/bin/php8.2", ["/usr/bin/php8.2", "-d", "allow_url_fopen=1", "-d", "auto_append_file=", "-d", "auto_prepend_file=", "-d", "disable_functions=", "-d", "display_errors=1", "-d", "docref_ext=.html", "-d", "docref_root=", "-d", "error_append_string=", "-d", "error_prepend_string=", "-d", "error_reporting=-1", "-d", "html_errors=0", "-d", "log_errors=0", "-d", "open_basedir=", "-d", "output_buffering=Off", "-d", "output_handler=", "-d", "report_memleaks=0", "-d", "report_zend_debug=0", "-d", **"xdebug.mode=off"**, "-d", "xdebug.auto_trace=This setting h"..., "-d", "xdebug.client_discovery_header=H"..., "-d", "xdebug.client_host=localhost", "-d", "xdebug.client_port=9003", "-d", "xdebug.collect_includes=This set"..., "-d", "xdebug.collect_params=This setti"..., "-d", "xdebug.collect_vars=This setting"..., "-d", "xdebug.connect_timeout_ms=200", "-d", "xdebug.coverage_enable=This sett"..., "-d", "xdebug.default_enable=This setti"..., "-d", "xdebug.dump_globals=1", "-d", "xdebug.dump_once=1", "-d", "xdebug.gc_stats_enable=This sett"..., "-d", "xdebug.gc_stats_output_dir=This "..., "-d", "xdebug.gc_stats_output_name=gcst"..., "-d", "xdebug.log_level=7", "-d", "xdebug.max_nesting_level=256", "-d", "xdebug.max_stack_frames=-1", "-d", **"xdebug.mode=develop"**, "-d", "xdebug.output_dir=/tmp", "-d", "xdebug.overload_var_dump=This se"..., "-d", "xdebug.profiler_enable=This sett"..., "-d", "xdebug.profiler_enable_trigger=T"..., "-d", "xdebug.profiler_enable_trigger_v"..., "-d", "xdebug.profiler_output_dir=This "..., "-d", "xdebug.profiler_output_name=cach"..., "-d", "xdebug.remote_autostart=This set"..., "-d", "xdebug.remote_connect_back=This "..., "-d", "xdebug.remote_enable=This settin"..., "-d", "xdebug.remote_host=This setting "..., "-d", "xdebug.remote_log=This setting h"..., "-d", "xdebug.remote_log_level=This set"..., "-d", "xdebug.remote_mode=This setting "..., "-d", "xdebug.remote_port=This setting "..., "-d", "xdebug.remote_timeout=This setti"..., "-d", "xdebug.show_mem_delta=This setti"..., "-d", "xdebug.start_upon_error=default", "-d", "xdebug.start_with_request=defaul"..., "-d", "xdebug.trace_enable_trigger=This"..., "-d", "xdebug.trace_enable_trigger_valu"..., "-d", "xdebug.trace_output_dir=This set"..., "-d", "xdebug.trace_output_name=trace.%"..., "-d", "xdebug.var_display_max_children="..., "-d", "xdebug.var_display_max_data=512", "-d", "xdebug.var_display_max_depth=3"]

The additional ini values get added by `AbstractPhpProcess::getCommand()`.
