### ISSUE TITLE
phpunit deprecation notices only displayed when defining source directory

### ISSUE THREAD

**Issue by wickedOne** [sebastianbergmann/phpunit#4978]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.20
| PHP version         | 7.4.24
| Installation Method | Composer

#### Summary

when running phpunit without defining a source directory at the end of your command it does not display phpunit's (deprecation) warnings
#### Current behavior
this does not display phpunit's (deprecation) warnings
```bash
vendor/bin/phpunit --testsuite=Foo
```
while this does (e.g. `Warning:       Test case class not matching filename is deprecated`)
```bash
vendor/bin/phpunit --testsuite=Foo tests/
```

#### How to reproduce

rename one of your class names of an existing test without changing the filename itself

#### Expected behavior

i'm not quite sure what is to be expected (i.e. is this expected behaviour or a bug). personally i'd expect the (deprecation) warnings to be shown regardless or perhaps have a flag to have them displayed

#### composer info | sort output
[out.txt](https://github.com/sebastianbergmann/phpunit/files/8786064/out.txt)

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by sebastianbergmann** [comment]
No feedback, closing.

**Comment by wickedOne** [comment]
apologies for the late reply...
minimal, self-contained test case can be found over [here](https://github.com/wickedOne/phpunit-4978)
