### ISSUE TITLE
Deprecations converted to exceptions during autoload result in fatal error

### ISSUE THREAD

**Issue by rtek** [sebastianbergmann/phpunit#4980]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.20
| PHP version         | 8.1.4
| Installation Method | Composer

#### Summary

Converting a deprecation warning generated during class autoload to an exception causes an unrelated fatal error.

See https://github.com/rtek/phpunit-deprecation-to-exception for test case
```
$ vendor/bin/phpunit --verbose
PHPUnit 9.5.20 #StandWithUkraine

Runtime:       PHP 8.1.4
Configuration: phpunit-deprecation-to-exception/phpunit.xml.dist

PHP Fatal error:  Class "PHPUnit\Framework\TestFailure" not found in phpunit-deprecation-to-exception/src/BadIterator.php on line 0
```

#### Current behavior

The test suite fatals out since the autoloader fails to get the various required classes in `PHPUnit\Framework\Exception`

#### How to reproduce

See https://github.com/rtek/phpunit-deprecation-to-exception for test case

#### Expected behavior

The test suite should catch the deprecation exception and continue.

#### Discussion

It appears that PHP is not invoking the autoloader to fetch the required PHP unit classes. Im not sure if this can be "fixed" since throwing an exception from an autoloader interrupts the autoload process.

**Comment by sebastianbergmann** [comment]
> throwing an exception from an autoloader interrupts the autoload process

Correct.
