### ISSUE TITLE
phpUnit

### ISSUE THREAD

**Issue by mendozabernillanilsen10** [sebastianbergmann/phpunit#4981]
<?php declare(strict_types=1);
 use PHPUnit\Framework\TestCase;
 include ('C:\xampp\htdocs\hotel_hemely\core\app\model\VentaData.php');
class ventaTest extends TestCase {
    /** test */
    public function add_venta() {
		$venta = new VentaData();  
		$venta->id_tipo_comprobante="1";
		$venta->id_tipo_pago="1";
		$venta->total= 12; 
		$venta->id_proveedor="1";
		$venta->id_usuario = "1";
		$venta->id_caja = "1";

        $htis->assertTrue($venta->addVenta());
    }
}

?>

PS C:\xampp\htdocs\hotel_hemely\phpUnit> ./vendor/bin/phpunit tests
PHPUnit 9.0.0 by Sebastian Bergmann and contributors.

Time: 00:00.076, Memory: 4.00 MB

No tests executed!

**Comment by sebastianbergmann** [comment]
I do not understand what you're trying to report.
