### ISSUE TITLE
Optional test directory

### ISSUE THREAD

**Issue by shyim** [sebastianbergmann/phpunit#4984]
Hey,

I would like to have an optional test directory in my phpunit.xml.dist testsuite. Due licensing, this code is not always present there.

Currently, this line seems to blocked by only https://github.com/sebastianbergmann/phpunit/blob/main/src/TextUI/Configuration/Xml/TestSuiteMapper.php#L78

So I would propose to have a flag like ignore-if-missing="true" in the xml

```
<directory ignore-when-missing="true">src/xx/tests</directory>
```

**Comment by sebastianbergmann** [comment]
I do not think that this would be useful.
