### ISSUE TITLE
Double events when test is risky

### ISSUE THREAD

**Issue by Jean85** [sebastianbergmann/phpunit#4987]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.1.6
| PHP version         | 10.0-dev
| Installation Method | Composer

#### Summary
This is not exactly a bug, more of a question: while still working on https://github.com/facile-it/paraunit/pull/162, I stumbled on an issue that is making me scratch my head: https://github.com/facile-it/paraunit/pull/162#issuecomment-1155761666

> when a test outcome is risky, both `Passed` and `ConsideredRisky` events are fired, and with the current architecture of my code, coming from supporting PHPUnit 9.x, this means doubling the captured tests outcome.

So, while listening to these events, it starts to be harder to obtain a single outcome for a single test. Is this by design? Do I have to code around this particular choice?

**Comment by sebastianbergmann** [comment]
I am currently working on this and am in the middle of changing some events to resolve issues I encounter(ed) while working on the `ResultPrinter`.

The `ConsideredRisky` event will be made consistent with the recently introduced events for deprecations, notices, etc. The only "outcomes" will be:

- Skipped
- Incomplete
- Failed
- Errored

In addition to that, events will be emitted for failed risky test checks, usage of deprecated PHPUnit features, warnings from PHPUnit, `E_NOTICE`, `E_STRICT`, `E_DEPRECATED`, `E_USER_DEPRECATED`, etc.

I hope that helps?

**Comment by sebastianbergmann** [comment]
The progress printer is more or less ready, see https://github.com/sebastianbergmann/phpunit/blob/main/src/TextUI/ProgressPrinter/ProgressPrinter.php
