### ISSUE TITLE
Missing schema for 9.5 version

### ISSUE THREAD

**Issue by zeleznypa** [sebastianbergmann/phpunit#4991]
When I install the phpunit via composer and it use the github prebuilded archive, there is no schema `9.5.xsd`.
Look at the last current tag archive content https://github.com/sebastianbergmann/phpunit/releases/tag/9.5.21

**Comment by sebastianbergmann** [comment]
I do not understand what you are trying to report.

**Comment by zeleznypa** [comment]
I have tried to install the PhpUnit via composer

```json
    "require": {
        "php": "~8.1",
        "phpunit/phpunit": "~9.5"
    }
```
and run it with configuration
```xml
<?xml version="1.0"?>
<phpunit
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.5/phpunit.xsd"
    colors="true"
    convertErrorsToExceptions="true"
    convertNoticesToExceptions="true"
    convertWarningsToExceptions="true"
    stopOnError="false"
    stopOnFailure="false"
    stopOnIncomplete="false"
    stopOnSkipped="false"
    stopOnRisky="false"
    verbose="true">
    <coverage processUncoveredFiles="true">
        <include>
            <directory suffix=".php">src</directory>
        </include>
    </coverage>
    <testsuites>
        <testsuite name="All tests">
            <directory>tests</directory>
        </testsuite>
    </testsuites>
</phpunit>
```
But the PhpUnit fail with error
```
Schema for PHPUnit 9.5 is not available
```

Because the composer install the PHPUnit from the zip archive: https://github.com/sebastianbergmann/phpunit/archive/refs/tags/9.5.21.zip

That does not contain the file https://github.com/sebastianbergmann/phpunit/blob/main/schema/9.5.xsd

And the expectation is that the PHPUnit work well :)

**Comment by sebastianbergmann** [comment]
There is no `schema/9.5.xsd` in PHPUnit 9.5. The file you are referencing is part of what will become PHPUnit 10.

**Comment by zeleznypa** [comment]
@sebastianbergmann it is a little bit confusing, that `9.5.xsd` is not for branch `9.5`, but I understand. Thanks for your patience, time and such a great tool.

**Comment by sebastianbergmann** [comment]
The XSDs in the `schema` directory are for previous versions than the one being used. They are used for the `--migrate-configuration` functionality.
