### ISSUE TITLE
Add `assertArrayHasKeys` and `assertArrayNotHasKeys` Functions

### ISSUE THREAD

**Issue by TheDevick** [sebastianbergmann/phpunit#4994]
# Context 
 Have an Array:
```php
[
    "id" => 1,
    "name" => "Official Author",
    "description" => "Author Description"
]
```

And have to ***Assert if Array Has the Keys***: `id`, `name` and `description`
And have to ***Assert if Array Not Has the Keys***: `email`, `avatar`, `twitter`, `password`, `created_at` and  `updated_at`

The PHPUnit provide the `assertArrayHasKey` and `assertArrayNotHasKey` function to assert, but the functions just accept one key each

I Have to do an Foreach to assert all the values:

```php
$has = ['id', 'name', 'description'];
$except = ['email', 'avatar', 'twitter', 'password', 'created_at', 'updated_at'];

foreach ($has as $item) {
    $this->assertArrayHasKey($item, $data);
}

foreach ($except as $item) {
    $this->assertArrayNotHasKey($item, $data);
}
```

## The Feature Request
Add an `assertArrayHasKeys` and `assertArrayNotHasKeys` function to assert an ***Array of Keys***
Example:
```php
$has = ['id', 'name', 'description'];
$except = ['email', 'avatar', 'twitter', 'password', 'created_at', 'updated_at'];

$this->assertArrayHasKeys($has, $data);
$this->assertArrayNotHasKeys($except, $data);

```

**Comment by ale94lko** [comment]
@TheDevick @sebastianbergmann I have created [#5014](https://github.com/sebastianbergmann/phpunit/pull/5014) to solve this.

**Comment by TomasVotruba** [comment]
Just needed this one. Current workaround is to simply spam the test with singles:

```php
        Assert::assertArrayHasKey('first', $jsonResponse);
        Assert::assertArrayHasKey('second', $jsonResponse);
        Assert::assertArrayHasKey('third', $jsonResponse);
       // 20 more
```
