### ISSUE TITLE
Possible issue with dataProvider persisting data to DB, but is not used in the test run

### ISSUE THREAD

**Issue by OskarStark** [sebastianbergmann/phpunit#4995]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.21
| PHP version         | 8.1
| Installation Method | Composer

#### Summary & current behavior

I have two functional test classes which contain one test each. One without using a data provider and one which is using a data provider. I created a code example with dummy classes to be more descriptive.

```php
<?php

declare(strict_types=1);

namespace App\Tests\Functional\Controller;

use PHPUnit\Framework\TestCase;

final class MyClassFunctionalTest extends TestCase
{
    /**
     * @group temp
     */
    public function testWithoutDataProvider(): void
    {
        $this->createAndPersistOneEntity('foo');

        self::assertSame(1, $this->repository->countEntities());
    }
}

final class MyOtherClassFunctionalTest extends TestCase
{
    /**
     * @dataProvider persistedEntitiesProvider
     */
    public function testWithDataProvider($entity): \Generator
    {
        // do some assertions here
    }

    public function persistedEntitiesProvider(): \Generator
    {
        yield [$this->createAndPersistOneEntity('bar')];
        yield [$this->createAndPersistOneEntity('baz')];
    }
}
```

If I am correct, running the following command `vendor/bin/phpunit --configuration=phpunit.xml.dist --group=temp`, should only execute the first test and it should pass. But it doesn't. The count in the database is not 1 but 3 ❗ It took me and my colleagues long time to find out why. Even if the `MyOtherClassFunctionalTest::persistedEntitiesProvider()` data provider is not in use while calling `--group=temp` it gets executed and therefore persist 2 entities in the database 👀  

Shouldn't it only gets executed if the `MyOtherClassFunctionalTest::testWithDataProvider()` test is called/used/executed? And in this case it should be executed one bye one? I mean a data provider with 2 items is basically a matrix of 2 isolated tests. So test one with data provider item 1 should not know anything about the data/existence of data provider item 2.

Maybe I am missing sth. and its not a bug but a feature.

Please let me know, thank you!

#### How to reproduce

Use the code snippet I provided.

#### Expected behavior

* A data provider's code should only be executed and used right before it is needed and used by a test case.
* A data provider item should not know anything about another data provider item.

I hope you understand my case.

Cheers

EDIT: I guess the same error should happen if all tests (with and without data provider) are within one class.

**Comment by sebastianbergmann** [comment]
For now, this is expected behaviour. Before the first test is run, all test objects are created, which includes executing data providers. Then these test objects are filtered and sorted, then they are run. Once we have the event system in place and PHPUnit 10 out of the door, the next major change will be how tests are discovered and run. This will address this any many other issues.

**Comment by OskarStark** [comment]
Thanks for your feedback 😃👍🏻
