### ISSUE TITLE
ReflectionClass::getMethods fails with a null parameter

### ISSUE THREAD

**Issue by deannagarcia** [sebastianbergmann/phpunit#4997]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.5.27
| PHP version         | 7.2.13
| Installation Method | Composer

#### Summary

When compiling code I get an error that `ReflectionClass::getMethods()` fails because of a null parameter. This properly compiles on other PHP versions and other PHPUnit versions.

#### Current behavior

Logs:
```
Fatal error: Uncaught TypeError: ReflectionClass::getMethods() expects parameter 1 to be integer, null given in /tmp/protobuf/protobuf/php/vendor/phpunit/phpunit/src/Util/Reflection.php:45
Stack trace:
#0 /tmp/protobuf/protobuf/php/vendor/phpunit/phpunit/src/Util/Reflection.php(45): ReflectionClass->getMethods(NULL)
#1 /tmp/protobuf/protobuf/php/vendor/phpunit/phpunit/src/Util/Reflection.php(35): PHPUnit\Util\Reflection->filterMethods(Object(ReflectionClass), NULL)
#2 /tmp/protobuf/protobuf/php/vendor/phpunit/phpunit/src/Util/Test.php(513): PHPUnit\Util\Reflection->methodsInTestClass(Object(ReflectionClass))
#3 /tmp/protobuf/protobuf/php/vendor/phpunit/phpunit/src/Framework/TestSuite.php(551): PHPUnit\Util\Test::getHookMethods('ArrayTest')
#4 /tmp/protobuf/protobuf/php/vendor/phpunit/phpunit/src/Framework/TestSuite.php(619): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#5 /tmp/protobuf/protobuf/php/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(659): PHPUnit\Framework\TestSuite->run(Object(PHPU in /tmp/protobuf/protobuf/php/vendor/phpunit/phpunit/src/Util/Reflection.php on line 45
```

#### How to reproduce

Run a test case with the combination of PHP version 7.2.13 and PHPUnit version 8.5.27

#### Expected behavior

Code should compile

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by deannagarcia** [comment]
While trying to reproduce this, I saw the error: `This version of PHPUnit requires PHP >= 8.1`. Is this intended? I might have just missed that PHP 7.2 isn't supported anymore since it's so old...

**Comment by sebastianbergmann** [comment]
PHP 8.1 will be required by PHPUnit 10, no currently released/supported version of PHPUnit requires PHP 8.1.

**Comment by Sun-FreePort** [comment]
Right, I has this error again, If we still use PHP 7.2 + PHPUnit 8.0+, How to fix it?

@sebastianbergmann thanks.

**Comment by Sun-FreePort** [comment]
Append a demo (this my demo composer package):

https://github.com/Sun-FreePort/global-config/tree/main
