### ISSUE TITLE
Add `TestCase.pass()` method

### ISSUE THREAD

**Issue by Danon** [sebastianbergmann/phpunit#4999]
I'm using PhpUnit, and I'm loving it. Sometimes, I write tests that don't require any assertions, for example this one:

```php
/**
 * @test
 */
public function shouldNotIterate_onUnmatchedSubject()
{
    // given
    $matcher = Pattern::of('Foo{2,3}')->match('Bar');
    // when
    foreach ($matcher as $detail) {
        $this->fail();
    }
    // then
    $this->pass();
}
```

`$this->pass()` is a `trait` I wrote, that I use:
```php
trait TestCasePasses
{
    public function pass(): void
    {
        Assert::assertTrue(true);
    }
}
```

if I don't call `$this->pass()`, then the test fails with `This test did not perform any assertions`. This exception is useful, when someone actually forgot to add assertions or exception expectations. But in some cases, assertions aren't required. 

In that case I use this `$this->pass();` (as opposed to `$this->fail();`). This is a 3rd project I copy-and-paste this trait, perhaps it would be a good idea to add a method to the framework?

Of course the implementation doesn't matter, `$this->pass();` would simply suppress error `This test did not perform any assertions` in any way you find suitable.

**Comment by sebastianbergmann** [comment]
The `@doesNotPerformAssertions` annotation already exists for this exact use case.

**Comment by Danon** [comment]
Are you sure the annotation is the way to go? 

I would also like to use it like so:
```php

        try {
            $function();
            Assert::fail();
        } catch (Exception $exception) {
            if (\str_starts_with($exception->getMessage(), 'T-Regx')) {
                Assert::assertSame($className, \get_class($exception));
            } else {
                $this->pass();
            }
        }
```

**Comment by kubawerlos** [comment]
The assertion is like "do not care at all if anything in that test was run".

If I cannot came with any assertion I prefer to use `$this->addToAssertionCount(1);` to make sure the expected place in code was executed.
