### ISSUE TITLE
Add `$previous` to `ExpectationFailedException`

### ISSUE THREAD

**Issue by vincenzo-mennella-shippypro** [sebastianbergmann/phpunit#5017]
Hi,
there are some cases where it's useful to check what the previous exception was when an `ExpectationFailedException` is thrown.

For example, I've overwritten my `runTest` method to handle some custom exceptions globally and perform some operations accordingly but, when a `ExpectationFailedException` is thrown (a test expect an exception but gets another one) I'm unable to get the original exception (the one that I'm trying to handle in my custom `runTest` method).

I see that `ExpectationFailedException` already accepts `$previous` as parameter. It would be enough to add `$other` as third param when it gets thrown into `src/Framework/Constraint/Constraint.php`

**Comment by sebastianbergmann** [comment]
I am sorry, but this does not make sense to me.

**Comment by vincenzo-mennella-shippypro** [comment]
Hi @sebastianbergmann 
thank you for you reply!

We're only talking of adding `$previous` when throwing an `ExpectationFailedException`, could you please explain why this not makes sense?

Thank you!
