### ISSUE TITLE
allow ampersand in env value

### ISSUE THREAD

**Issue by arderyp** [sebastianbergmann/phpunit#5018]
As per the [symfony documentation](https://symfony.com/doc/current/components/phpunit_bridge.html#making-tests-fail), I'd like to do the following, but the ampersand causes an error:

```
<env name="SYMFONY_DEPRECATIONS_HELPER" value="max[direct]=0&verbose=0" />
```

This works, but no ampersands means no complex configuration:

```
<env name="SYMFONY_DEPRECATIONS_HELPER" value="max[direct]=0" />
```

**Comment by kubawerlos** [comment]
20 seconds of [googling](https://docs.oracle.com/cd/A97335_02/apps.102/bc4j/developing_bc_projects/obcCustomXml.htm):

```
<env name="SYMFONY_DEPRECATIONS_HELPER" value="max[direct]=0&#38;verbose=0" />
```

**Comment by arderyp** [comment]
Sorry, thank you.
