### ISSUE TITLE
DataProvider Generator compatibility. 

### ISSUE THREAD

**Issue by Legion112** [sebastianbergmann/phpunit#5024]
Version: `"phpunit/phpunit": "8.5.15"`
I have a test that time sensitive. 
Test example.:

```
    /**
     * @dataProvider getFormattedDateTimeRelativeProvider
     */
    public function testGetFormattedDateTimeRelative($dateTime, string $expected): void
    {
        $this->assertStringContainsString($expected, HtmlHelper::getFormattedDateTimeRelative($dateTime));
    }

    /**
     * @return array
     */
    public function getFormattedDateTimeRelativeProvider(): \Generator
    {
        yield [null, '-'];
        yield [new DateTime('2000-08-26 12:20:25'), 'ago'];
        yield [Carbon::parse('2100-08-26 12:20:25'), 'from now'];
        yield [(new DateTime())->modify('-1 hour -3 minutes'), '1h 3m ago'];
        yield [(new DateTime())->modify('-1 day -2 hour'), '1d 2h ago'];
        yield [(new DateTime())->modify('-1 year -1 month -5 day'), '1y 1m ago'];
    }
 ```
 
 Now I periodically getting error due to fact that time has passed
 Example of error: `Failed asserting that '1h 6m ago' contains "1h 3m ago".`
 
 The reason behind the lug in 3 minutes is that `Generator` is converted to array under the hood and all data time class created instantly. 
 Would be nice to keep generator to not create all test data at once.

**Comment by sebastianbergmann** [comment]
> Would be nice to keep generator to not create all test data at once

That would be nice, yes, but will not be possible until the way tests are run is fundamentally changed.

**Comment by Legion112** [comment]
As I understand [here](https://github.com/sebastianbergmann/phpunit/blob/3aacfdf555218222c978b686ce0a5b17c38c3506/src/Util/Annotation/DocBlock.php#L501-L520) the place where Generator converted to array. 
Do we really need to do that here? 
@sebastianbergmann

**Comment by sebastianbergmann** [comment]
Yes; all test objects are created before the first test is run.

**Comment by Legion112** [comment]
@sebastianbergmann what if dataProvider fetched from pretty large file?
Would be more elegant to not load it into memory all at once. 
Hm... but maybe file read will require a lot of disk usage and not an optimal way to run test that way... 

When why do we need to create all data at once? I don't see any point to support generator here. 
Why it's not force to use array when? To only have a nice syntax to describe test data?

**Comment by mfn** [comment]
> Now I periodically getting error due to fact that time has passed

You seem to _also_ use Carbon, how this is usually solved:
- in your `setUp` you call `Carbon::setTestNow()`
- your data provider does not return instances (because they are created upfront, as you saw) but only the instruction for the absolute or relative time and you construct it based on these facts _in your test_
