### ISSUE TITLE
Dummy

### ISSUE THREAD

**Issue by LlZARD** [sebastianbergmann/phpunit#5029]
Kudos for extracting `Stub` interface out of `MockObject`. Creating `Stub`s instead of `Mock`s reveals the intent of the test much better. 

I suggest going one step further and extract `Dummy` out of `Stub` Interface. So in fact `Dummy` will be have no `method` method (pun intended) on it.

I could volunteer myself in implementing this.

Possibly related to #4729.

**Comment by sebastianbergmann** [comment]
Won't implement.
