### ISSUE TITLE
assertEquals() Line Ending Differences Are Obscure

### ISSUE THREAD

**Issue by ghost** [sebastianbergmann/phpunit#503]
When using `assertEquals("Windows EOL", "Unix EOL")` with multi-line text, assertEquals() properly displays a failure, but does not show why in the difference report.

```
1) Namespace\ClassName::testCreateResponse
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 Parameter: parameter value
 Context: context value
 URL: http://localhost/test?key=value

/path/to/test/file.php:55
```

**Comment by keradus** [comment]
For anyone who would have the issue in the future.
A little helper approach that will also display a debug statement showing the difference:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2221/commits/d60e963e80f45e2050085964f67c6769f347381f

output is not pretty, but at least sth is displayed so it's possible to find where the wrong character is.

**Comment by jmauerhan** [comment]
As a die-hard windows user, thank you :)
