### ISSUE TITLE
Provide the list on newly marked items with @internal in the changelog

### ISSUE THREAD

**Issue by mialex** [sebastianbergmann/phpunit#5032]
In our project, we were heavily using `\PHPUnit\Framework\MockObject\Matcher\InvokedRecorder::getInvocations` as it was extremely useful and helpful to us. When we were migrating to the new version we found out that it was removed. 

In the https://github.com/sebastianbergmann/phpunit/pull/4447 it was mentioned that it was marked as `@internal`, but un 7.5.20 https://github.com/sebastianbergmann/phpunit/blob/7.5.20/src/Framework/MockObject/Matcher/InvokedRecorder.php there was nothing about this. With the new releases we were checking what has been changed and if that will affect us late, but it appears that there is nothing about this and it become a **HUGE** surprise for us.

As an improvement, it would be great to add to the change log the information about classes that were marked with `@internal` so then people can get prepared in advance and get rid of such class usage.

**Comment by sebastianbergmann** [comment]
I will try to do better in the future.
