### ISSUE TITLE
Deprecate InvocationMocker::withConsecutive() in PHPUnit 9

### ISSUE THREAD

**Issue by mondrake** [sebastianbergmann/phpunit#5035]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.0.0
| PHP version         | n/a
| Installation Method | n/a

#### Summary

#4564 has removed `InvocationMocker::withConsecutive()`. Initially it was meant to be deprecated in PHPUnit 10 for removal in PHPUnit 11, but then removal was moved forward.

Right now the method is fully supported in 9.5, and not at all in 10.

Can we have a deprecation in PHPUnit 9?

**Comment by sebastianbergmann** [comment]
There will be a PHPUnit 9.6 release with this deprecation before PHPUnit 10.
