### ISSUE TITLE
Test exited unexpectedly

### ISSUE THREAD

**Issue by LocalHeroPro** [sebastianbergmann/phpunit#5043]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.24
| PHP version         | 8.1.9
| Installation Method | Composer

#### Summary
Tests exited without exception, info. In `phpunit.xml` file I have set 600 to max execution time and memory limit to 512 M, but even in 128 M tests pass run.

#### Current behavior
Sometime all tests are executed normally with less than 200'. Sometimes in next run - even after few seconds - tests are exited after 15' and shell script are continued. Sometimes in even 10 times in row tests exited in radom time.

#### How to reproduce
```bash
//
$ XDEBUG_MODE=coverage php8.1 -d short_open_tag=off vendor/bin/phpunit -v --debug --coverage-clover=phpunit-coverage-result.xml --log-junit=phpunit-execution-result.xml --coverage-html=/var/www/html/coverage/here
//
```

#### Expected behavior
1. All tests ended.
2. Show exception on exit.
3. How to track exception if even `--debug` option don't show anything.

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.

**Comment by LocalHeroPro** [comment]
I thing it is bug, because of random unexpected exits.
BTW: where I can search help?
