### ISSUE TITLE
Allowing configuration of environment variables in phpunit testsuite xml configuration.

### ISSUE THREAD

**Issue by Porthorian** [sebastianbergmann/phpunit#5049]
### Summary
I wanna be able to identify which testsuite is currently being executed during the execution of my bootstrap script.

### Problem
So I am encountering a scenario where I would like to do certain environment variables based on the testsuite that is being ran at a giving time. It seems phpunit does not support this functionality? After looking around for a few hours at last wasn't really able to find anything.

I could work around this problem by obviously doing duplicate phpunit.xml configurations and just specify the configuration I wanna use.

But I simply do not wanna do that as I like the convenience of having 1 phpunit.xml. I could do a makefile of some sorts or use composer scripts to hardcode the configuration. But again I'd be maintaining 2 configuration files which I neccessarily do not wanna do.

### Solution
So how do I solve this problem?

Well.

Lets take this xml configuration for example.

Adding the environment variable to a specific Testsuite would be beautiful and solve my problem. From that point on my bootstrap script could handle the environment variables based the testsuite that is executing it.

```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.5/phpunit.xsd"
         bootstrap="include/init_script.php"
         cacheResultFile=".phpunit.cache/test-results"
         executionOrder="depends,defects"
         forceCoversAnnotation="false"
         beStrictAboutCoversAnnotation="false"
         beStrictAboutOutputDuringTests="true"
         beStrictAboutTodoAnnotatedTests="true"
         convertDeprecationsToExceptions="true"
         failOnRisky="true"
         failOnWarning="true"
         verbose="true">

    <php>
        <ini name="memory_limit" value="512M" />
    </php>

    <testsuites>
        <testsuite name="unit">
            <env name="hello" value="world"/>
            <directory>tests/Unit/Suite</directory>
        </testsuite>
        <testsuite name="e2e">
            <directory>tests/EndToEnd/Suite</directory>
        </testsuite>
    </testsuites>

    <coverage cacheDirectory=".phpunit.cache/code-coverage"
              processUncoveredFiles="true">
        <report>
            <html outputDirectory=".phpunit.cache/html"/>
            <clover outputFile=".phpunit.cache/clover.xml" />
            <text outputFile="php://stdout"/>
        </report>

        <include>
            <directory suffix=".php">src</directory>
        </include>
    </coverage>
</phpunit>
```

Note the environment variable in 1 of the testsuites.
```
<testsuite name="unit">
    <env name="hello" value="world"/>
    <directory>tests/Unit/Suite</directory>
</testsuite>
```

Will this necessarily work? I am not entirely sure as I am not familiar with when the bootstrap script in this phpunit xml configuration is executed on the underlying stack in phpunit.

Example clarification.

Steps:
1. XML Configuration is Loaded in.
2. Bootstrap Script is executed
3. Testsuite Execution
4. Testsuite Execution
5. Output results

If the execution layout is similar to the above. Than this environment variable thing will necessarily not be at all backwards compatible and the result of this issue should be closed. Maybe we could allow a flag configuration so it could be configurable by the developer for this type of functionality to allow for the step execution shown below.

Or is the execution layout more similar to this.

Steps:
1. XML Configuration is Loaded in.
2. Bootstrap Script is executed
3. Testsuite Execution
4. Bootstrap Script is executed
5. Testsuite Execution
7. Output results

If the execution layout is similar to this most recent step provided. Than this issue may be more tangible in being completed without implementing breaking changes for everyone or this could be implemented in a way that allows developers/users to configure this desired affect.

**Comment by Porthorian** [comment]
Come to think about it, my use case was really dumb for this type of feature.

But I do think it would be nice to be able to specify https://phpunit.readthedocs.io/en/9.5/configuration.html?highlight=environment#the-env-element

Some of the php global variables on a per testsuite basis. I think that would be a nice quality of life feature?

**Comment by nikophil** [comment]
hey @sebastianbergmann 

I'd like very much to have this feature, would you consider a PR regarding it?
