### ISSUE TITLE
Deprecate expect*() methods that have been removed in PHPUnit 10

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#5062]
* `expectDeprecation()`, `expectDeprecationMessage()`, and `expectDeprecationMessageMatches()`
* `expectError()`, `expectErrorMessage()`, and `expectErrorMessageMatches()`
* `expectNotice()`, `expectNoticeMessage()`, and `expectNoticeMessageMatches()`
* `expectWarning()`, `expectWarningMessage()`, and `expectWarningMessageMatches()`

**Comment by jrfnl** [comment]
Just wondering where I can find information on what this will be replaced with ?

**Comment by sebastianbergmann** [comment]
There are no replacements. PHPUnit 10 no longer converts `E_*` to exceptions, therefore `E_*` can no longer be expected.

**Comment by InvisibleSmiley** [comment]
The situation is quite confusing right now since version 9.5's `expectException` suggests to switch to these methods...

**Comment by thbley** [comment]
@jrfnl I changed my test code like this:

```
    public function testSendEmailFailure(): void
    {
        set_error_handler(function(int $errno, string $errstr): bool {
            throw new Exception($errstr, $errno);
        }, E_USER_WARNING);

        // phpunit 9.5
        //$this->expectWarning();
        //$this->expectWarningMessage('failed to send');

        // phpunit 10.0
        $this->expectExceptionMessage('failed to send');

        // run some code that produces E_USER_WARNING

        restore_error_handler();
    }

```

**Comment by jrfnl** [comment]
@thbley Thanks. I think it's good to have such an example in this thread.
It won't help the usecase I was trying to solve, but that's another matter.

**Comment by alexpott** [comment]
@sebastianbergmann what is the recommended way of testing that an error is triggered in PHPUnit 10? If you want to assert that an E_USER_WARNING is thrown by your code what is the best way to do this? Should you replace the error handler as above or is there a better way?

**Comment by anton-vlasenko** [comment]
I just want to comment on the [proposed solution above](https://github.com/sebastianbergmann/phpunit/issues/5062#issuecomment-1416362657):
In my tests,
```php
restore_error_handler();
```
is never executed because the exception gets thrown before it.
`restore_error_handler()` has to be called in the custom error handler instead:
```php
public function testSendEmailFailure(): void
{
    set_error_handler(static function (int $errno, string $errstr): never {
        restore_error_handler();
        throw new Exception($errstr, $errno);
    }, E_USER_WARNING);

    // phpunit 9.5
    //$this->expectWarning();
    //$this->expectWarningMessage('failed to send');

    // phpunit 10.0
    $this->expectExceptionMessage('failed to send');

    // run some code that produces E_USER_WARNING


}
```

**Comment by epitre** [comment]
In my case, I did this :
```
    public function setUp(): void
    {
        set_error_handler(
            static function ( $errno, $errstr ) {
                throw new \Exception( $errstr, $errno );
            },
            E_ALL
        );
    }

    public function tearDown(): void
    {
        restore_error_handler();
    }

```

and then, in each test :
```
$this->expectException(MyException::class);
```

**Comment by BafS** [comment]
Be careful to reset the handler, as @epitre did, many example don't do it.

It's really unfortunate to have no information about why it got removed and no official explanation about how to upgrade, the upgrade path to v10 is really complex for big codebases.

**Comment by jrfnl** [comment]
@BafS You can find an explanation about the why in the Release announcement: https://phpunit.de/announcements/phpunit-10.html

**Comment by BafS** [comment]
@jrfnl thank for the link, great to have something official, I didn't see it mentioned before

**Comment by nmeri17** [comment]
> @sebastianbergmann what is the recommended way of testing that an error is triggered in PHPUnit 10? If you want to assert that an E_USER_WARNING is thrown by your code what is the best way to do this? Should you replace the error handler as above or is there a better way?

I don't understand why he is uncharacteristically mute and unresponsive to suddenly unplugging a widely used method with neither explanation nor an alternative. If I'm expecting a warning, odds are that that is the subject of the test. The example in the version 10 release notes show further assertion that `testSomething` returns a value. What is the recommended way for the library developer to verify a code block warns its consumer when certain action is performed? Disabling the action altogether is directly antithetical to my original intention. But this is just a powerless rant since feature is removed already, sadly. I expect the thread to be locked soon

**Comment by sebastianbergmann** [comment]
> What is the recommended way for the library developer to verify a code block warns its consumer when certain action is performed?

This is a use case that I do not consider worth supporting. I understand that this is frustrating, and I am sorry for that.

**Comment by nmeri17** [comment]
> > What is the recommended way for the library developer to verify a code block warns its consumer when certain action is performed?
> 
> This is a use case that I do not consider worth supporting. I understand that this is frustrating, and I am sorry for that.

I guess in my case, the deliberate warning can be relocated to a mockable method. But I'm not sure it's possible for all object types and SUTs

**Comment by nmeri17** [comment]
> This is a use case that I do not consider worth supporting. I understand that this is frustrating, and I am sorry for that.

I guess in my case, the deliberate warning can be relocated to a mockable method. It's a workaround like trying to test register shutdown function. In this case, however, I'm not sure it's possible for all object types and SUTs

**Comment by davisngl** [comment]
> @BafS You can find an explanation about the why in the Release announcement: https://phpunit.de/announcements/phpunit-10.html

There's, unfortunately, no details on what should be the alternative way of testing these things that we would've tested with expect* methods.

**Comment by gustavo-olegario-lawnstarter** [comment]
If you want to keep a similar implementation but also looking for moving on with PHPUnit updates, you can implement this method in your common test class:

```php
protected function assertThrowableMessage(
    string $message,
    callable $callback,
    ...$args
): void
{
    try {
        $callback(...$args);
    } catch (Throwable $e) {
        $this->assertEquals($message, $e->getMessage());
    }
}
```

This way you can assert the exception was properly thrown during runtime and don't have to deal with the `set_error_handler` madness.

**Comment by davisngl** [comment]
> If you want to keep a similar implementation but also looking for moving on with PHPUnit updates, you can implement this method in your common test class:
> 
> ```
> protected function assertThrowableMessage(
>     string $message,
>     callable $callback,
>     ...$args
> ): void
> {
>     try {
>         $callback(...$args);
>     } catch (Throwable $e) {
>         $this->assertEquals($message, $e->getMessage());
>     }
> }
> ```
> 
> This way you can assert the exception was properly thrown during runtime and don't have to deal with the `set_error_handler` madness.

Thank you!
I am just not sure why would their users have to implement something that we use a lot when testing for exceptions.
The reasoning isn't even there, no answer in sight.

**Comment by Sopamo** [comment]
Just want to add, that for folk who come from google and are using Laravel, you can use the `assertThrows` method that Laravel provides:

```
$this->assertThrows(function () use ($news) {
    // Code that should throw
});
```
There is also an optional second parameter which accepts the class name of the throwable that should get thrown and a third with the error message you expect.

**Comment by davisngl** [comment]
> Just want to add, that for folk who come from google and are using Laravel, you can use the `assertThrows` method that Laravel provides:
> 
> ```
> $this->assertThrows(function () use ($news) {
>     // Code that should throw
> });
> ```
> 
> There is also an optional second parameter which accepts the class name of the throwable that should get thrown and a third with the error message you expect.

![image](https://github.com/sebastianbergmann/phpunit/assets/11065768/15d09af0-8799-44c7-919b-0078824ebc44)
Updated to the latest composer dependencies but there's no `$this->assertThrows(...` method.

**Comment by alexeyp0708** [comment]
I always use this approach and don’t have to dance with a tambourine (calling Exception);
```php
$check=false;
set_error_handler(funciton(...$args)use(&$check){
// your code
$check=true;
// your code
},E_NOTICE);
// trigger error your code
restore_error_handler();
unset($check):

$this->assert($check);
```

**Comment by Konamiman** [comment]
> This is a use case that I do not consider worth supporting
That's not a very community-friendly response... 😕 Sure, it's your project and you do whatever you want with it. But it might be worth considering that your library is used by a lot of people, and _maybe_ there are some legitimate use cases out there that haven't crossed your mind.
