### ISSUE TITLE
Unable to proper test of Exceptions

### ISSUE THREAD

**Issue by zeleznypa** [sebastianbergmann/phpunit#5066]
When the tested code thrown an object that can do something more (like contain some additional data), there is no possibility to test it. Unfortunately the `\PHPUnit\Framework\TestCase::checkExceptionExpectations` is marked as `private` so there is no possibility to extend the `TestCase` functionalities.

It will be nice, that the Exception that was caught in `runTest` will be available somewhere for `postCondition` methods.

**Comment by sebastianbergmann** [comment]
If you need further verification of exceptions then just `try`/`catch` them yourself in your test method and do not rely on PHPUnit's out-of-the-box functionality.

**Comment by mfn** [comment]
One of the pitfalls with try/catch is that if you have your assertions in catch and for some reason your code DOES NOT throw an exception, depending on how the test is set up, you might miss this.

Couple of years ago I therefore created this helper (e.g. in your top level TestCase extending from PHPUnits one):
```php
    /**
     * @phpstan-param class-string $expectedExceptionClass
     */
    public static function assertCaptureException(
        callable $fn,
        string $expectedExceptionClass,
        string $expectedExceptionMessage = null
    ): Throwable {
        $exception = null;

        try {
            $fn();
        } catch (Throwable $exception) {
            // Deliberately empty
        }

        if (null === $exception) {
            throw new ExpectationFailedException(
                "Expected to catch exception of type $expectedExceptionClass but none was caught"
            );
        }

        $exceptionClass = \get_class($exception);

        $msg = "Expected to catch $expectedExceptionClass but caught "
            . \get_class($exception) . ' instead: '
            . $exception->getMessage()
            . "\n"
            . $exception->getTraceAsString()
            . "\n";
        self::assertSame($expectedExceptionClass, $exceptionClass, $msg);

        if (null !== $expectedExceptionMessage) {
            self::assertSame($expectedExceptionMessage, $exception->getMessage());
        }

        return $exception;
    }
```
This way it's not possible to "miss" it.

HTH

**Comment by zeleznypa** [comment]
@sebastianbergmann There is possibility to override the `TestCase::runTest` like you described that method, but there is absolutely no possibility to add additional logic for exception handling.

For example, it would be sufficient to set the `checkExceptionExpectations` method as protected, or add the caught exception to an object property.

This `private` and `final` kill the open-source :(
