### ISSUE TITLE
Set data provider by convention

### ISSUE THREAD

**Issue by ipundit** [sebastianbergmann/phpunit#5067]
Right now, test methods are identified by the prefix **test**, but data providers are specified by the annotation **dataProvider**. It would save a lot of broiler plate code if we could specify data providers by a **provider** prefix too. eg)

    public function testAdd(int $a, int $b, int $expected): void
    {
        $this->assertSame($expected, $a + $b);
    }
    public function providerAdd(): array
    {
        return [
            [0, 0, 0]
        ];
    }

For backwards compatibility, we could keep the **dataProvider** annotation functionality as-is, allowing for an arbitrary name for the data provider. But if that annotation does not exist as in the example above, then assume the name of the data provider is **provider**Method because the test name is **test**Method. If such a method does not exist and the test method has parameters, then emit an error as is currently done.

**Comment by sebastianbergmann** [comment]
I do not think that this would be useful.
