### ISSUE TITLE
beStrictAboutResourceUsageDuringSmallTests requires xdebug to work, but doesn't note it's missing

### ISSUE THREAD

**Issue by dkarlovi** [sebastianbergmann/phpunit#5071]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.25
| PHP version         | 8.1.10
| Installation Method | Composer

#### Summary

If you enable `beStrictAboutResourceUsageDuringSmallTests=true`, PHPUnit should at least warn about xdebug being unavailable and the flag ignored.

#### Current behavior

Currently it just does nothing, the flag is behaving as if ignored.

#### How to reproduce

Enable the flag and run tests without xdebug being available.

#### Expected behavior

It would warn the user about xdebug (and the function exec tracking feature) being unavailable.

**Comment by sebastianbergmann** [comment]
Won't fix, this feature has been / will be removed.
