### ISSUE TITLE
--no-extensions CLI option only prevents extension PHARs from being loaded

### ISSUE THREAD

**Issue by wickedOne** [sebastianbergmann/phpunit#5073]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.25
| PHP version         | 8.1
| Installation Method | Composer

#### Summary
the --no-extensions cli option does not apply to the `<extension>` element configured in the `phpunit.xml`

#### Current behavior
while passing the `--no-extensions` cli option, extensions configured in the [extension element](https://phpunit.readthedocs.io/en/9.5/configuration.html#the-extensions-element) of `phpunit.xml` are loaded when running phpunit.

i'm not sure whether this is intended behaviour or an oversight tho (happens here)
https://github.com/sebastianbergmann/phpunit/blob/6770c48195052ecdeaac40eca9204b5bfbc5722b/src/TextUI/Configuration/Merger.php#L164-L183

#### How to reproduce

minimal, self-contained test case to reproduce can be found over [here](https://github.com/wickedOne/phpunit-5073)

#### Expected behavior

the extensions configured in the extension element are not loaded like the ones from the `pharDirectory`

**Comment by wickedOne** [comment]
added minimal, self-contained test case to reproduce

**Comment by wickedOne** [comment]
thank you @sebastianbergmann !

**Comment by nightio** [comment]
@sebastianbergmann It's not working on version 9.x (at least) as it still seems to have the same issue. Upon checking the code, I noticed that the `$this->arguments` variable used isn't defined. There is no `$this->arguments` variable, only `$arguments`. Please refer to this link for more details: https://github.com/sebastianbergmann/phpunit/blob/241c4aa189ef1f3b7608de2da5510a59f1d22a01/src/TextUI/TestRunner.php#L1009

I tried fixing it locally, and when I replaced the undefined variable with $arguments, it worked correctly under both scenarios: when the option is provided in the CLI - the extensions are not loaded. Conversely, if the option is not provided, the extensions are loaded. 

Could you take a look and possibly make this fix?

**Comment by sebastianbergmann** [comment]
> Could you take a look and possibly make this fix?

Please open a new issue, thanks.
