### ISSUE TITLE
phpunit deprecation notices only displayed when defining source directory

### ISSUE THREAD

**Issue by wickedOne** [sebastianbergmann/phpunit#5074]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.25
| PHP version         | 7.4.24
| Installation Method | Composer

#### Summary

when running phpunit without defining a source directory at the end of your command it does not display phpunit's (deprecation) warnings
#### Current behavior
this does not display phpunit's (deprecation) warnings
```bash
vendor/bin/phpunit --testsuite=Foo
```
while this does (e.g. `Warning:       Test case class not matching filename is deprecated`)
```bash
vendor/bin/phpunit --testsuite=Foo tests/
```

#### How to reproduce

minimal, self-contained test case to reproduce can be found over [here](https://github.com/wickedOne/phpunit-4978)

#### Expected behavior

i'm not quite sure what is to be expected (i.e. is this expected behaviour or a bug). personally i'd expect the (deprecation) warnings to be shown regardless or perhaps have a flag to have them displayed

**Comment by sebastianbergmann** [comment]
Can you reproduce the issue with PHPUnit 9.5.25?

**Comment by wickedOne** [comment]
sorry for that, updated the ticket for completeness

**Comment by joakimbo** [comment]
Not sure its as easy as this but I also came across this issue and guessing they have the same origin one possible solution is to add the warnings from the suite to the result from the TestSuiteMapper map() function i.e.
```
// TextUI\TestSuiteMapper:89
...
if (!$testSuiteEmpty) {
    $result->addTest($testSuite);
    foreach ($testSuite->warnings() as $warning) {
        $result->addWarning($warning);
    }
}
...
```

**Comment by sebastianbergmann** [comment]
I am sorry for not getting to this before the end of bugfix support for PHPUnit 9.
