### ISSUE TITLE
Test Runner does not warn about conflicting options

### ISSUE THREAD

**Issue by joachim-n** [sebastianbergmann/phpunit#5076]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.20
| PHP version         | 8.9
| Installation Method | Composer 

#### Summary

I ran `vendor/bin/phpunit path/to/tests/ --filter=methodName --list-tests`.

#### Current behavior

I got the list of ALL tests in `path/to/tests/`.

#### Expected behavior

Show only tests matching methodName:

- multiple methods in different classes with the same name
- methods that match the given name
- data provider IDs if any of those methods have a data provider.

Alternatively, if this is by design warn that --list-tests and --filter options are not compatible.

**Comment by sebastianbergmann** [comment]
This is working as intended. However, it was unclear that any filtering is ignored when tests or suites are listed. Hope it's better now.
