### ISSUE TITLE
TestDox console output with color on shows formatting characters instead of tabs and spaces

### ISSUE THREAD

**Issue by jnsrnhld** [sebastianbergmann/phpunit#5081]
When using data providers with named datasets and running PHPUnit with --testdox and --colors=always, the named datasets are printed with cyan color and formatting characters shown:
<img width="243" alt="Bildschirmfoto 2022-10-16 um 21 52 02" src="https://user-images.githubusercontent.com/85998450/196055205-b5f94c55-c1d9-4e45-83c9-213bbc76f7a6.png">

Without color option switched on, the output omits the formatting characters, like expected:
<img width="337" alt="Bildschirmfoto 2022-10-16 um 21 57 54" src="https://user-images.githubusercontent.com/85998450/196055432-9031f88d-ff29-445d-b443-b54fa6206664.png">

From my point of view, there is no obvious reason nor benefit of showing tabs and spaces as formatting characters in CLI output. Instead, from my point of view it clutters the output. If this is the desired behavior, I would suggest to add a configuration parameter that enables users to turn this of.

**How to reproduce:** 
PHP with Version 8.1, PHPUnit 9.5.25  
```PHP
class FooTest extends TestCase
{

	/**
	 * @dataProvider testFooProvider
	 */
	public function testFoo(bool $input): void
	{
		$this->assertTrue($input);
	}

	public function testFooProvider(): array
	{
		return [
			'Named set Nr. 1' => [true],
			"\tNamed set Nr. 2" => [false],
		];
	}

}
```

**Comment by sebastianbergmann** [comment]
Both colors and formatting characters are controlled by the same configuration setting. This is not a bug and works as intended.
