### ISSUE TITLE
PHP Unit test case showing indirect error not showing exact line number in file.

### ISSUE THREAD

**Issue by ashetkar011** [sebastianbergmann/phpunit#5082]
PHP UNIT VERSION: 9.5.25
PHP VERSION: 8.1
installed method: composer

**Summary**
While running phpunit test case getting indirect error like below 
1x: strtr(): Passing null to parameter #1 ($string) of type string is deprecated
Using Command: /vendor/bin/phpunit -c core modules/custom/custom module/tests/src/Unit/Form/filename.php 

**Problem**
Is there any way to get exact error line number or complete stack trace via command ?

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by ashetkar011** [comment]
Is there any general way to debug issue or get full stack trace via command?

**Comment by sebastianbergmann** [comment]
I cannot help you without a minimal, self-contained, reproducing test case that shows the problem you are reporting. You are not even showing a complete message. If `1x: strtr(): Passing null to parameter https://github.com/sebastianbergmann/phpunit/issues/1 ($string) of type string is deprecated` is part of the output you see then I have to tell you that this does not come from PHPUnit. Are you using Symfony and its PHPUnit Bridge perhaps?

**Comment by ptomulik** [comment]
I bet it was [bug in PHP 8.1](https://github.com/php/php-src/issues/8810).
