### ISSUE TITLE
Add a `willNowReturn()` for simple resetting of `willReturn()`

### ISSUE THREAD

**Issue by kouralex** [sebastianbergmann/phpunit#5088]
I would very much like to have a simple way to reset the return value of `willReturn()` method with. e.g., `willNowReturn()` in order to be able to easily run test doubles in the same test with slightly changed input. I believe that introducing this new method would be a simpler method than reorganizing the test setting, especially now that `withConsecutive()` will be gone in the next major release (it did not work in my case anyway as the same method could have been called X times in later call stacks). This way I could update a single mocked method value in an otherwise convoluted setup.

Code example:
```
$mockObject = $this->getMockBuilder('MultiParamSetup')->disableOriginalConstructor()->getMock();
$mockObject->method('getParamA')->willReturn('a');
$mockObject->method('getParamB')->willReturn('b');
// and so on for multiple methods..
$actual = $classToBeTested->runSomeMethod($mockObject);
// run tests against $actual

$mockObject->method('getParamA')-willNowReturn('abc'); // reset the getParamA() to now return 'abc'
$actual2 = $classToBeTested->runSomeMethod($mockObject);
// run tests against $actual2 which now has different output now that the getParamA() return value has been updated.
```
If there is an alternative/recommended way of doing the same with already existing methods, I would be happy to hear about it.

**Comment by sebastianbergmann** [comment]
Not going to happen, sorry. I am very reluctant when it comes to changing or adding to the API for test doubles.

**Comment by kouralex** [comment]
It could also have been so that the already existing `willReturn()` would on subsequent calls change the output (so no need for new API methods), but this will do. Thanks for the swift response and good product.
