### ISSUE TITLE
Numeric data provider names are renumbered

### ISSUE THREAD

**Issue by Bilge** [sebastianbergmann/phpunit#5091]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.26 
| PHP version         | 8.1.3
| Installation Method | Composer 

#### Summary

Data providers whose name is a numeric string are treated as having no name at all.

#### Current behavior

Numeric names are renumbered as the contiguous integer sequence `0, ..., N`.

#### How to reproduce

```php
    public static function provideNames(): iterable
    {
        yield '101' => [];
        yield '202' => [];
    }
```

#### Expected behavior

Names are unaltered in output.

**Comment by sebastianbergmann** [comment]
I do not think that there is any benefit in implementing special treatment for string that contain integers.

**Comment by Bilge** [comment]
No? No benefit whatsoever? What about: _software that does the expected thing_, or _software that does not betray user expectations by doing the unexpected thing?_ Not considered benefits in your book?
