### ISSUE TITLE
Revert #StandWithUkraine

### ISSUE THREAD

**Issue by AndriiLukianets** [sebastianbergmann/phpunit#5095]
Hello Sebastian, Contributors.

I give thanks to you for standing with Ukraine.
War is still going and people in Ukraine are still dying from russian aggression.
Revert please #StandWithUkraine banner to show your support to Ukraine and keep focus on this problem terror. 
Thank you.

**Comment by sebastianbergmann** [comment]
I still [stand with Ukraine](https://phpunit.de/stand-with-ukraine.html), just not in PHPUnit's output anymore.
