### ISSUE TITLE
Re consider adding a minum coverage option

### ISSUE THREAD

**Issue by BackEndTea** [sebastianbergmann/phpunit#5096]
The last issue i found about this was #1877, which is also the first result on google when searchign for "phpunit minimum coverage". This was closed some 6 years ago, so i was hoping, that maybe in the mean time the opinion on this has changed.

In our code bases we have configured a minimum code coverage for [jest](https://jestjs.io/docs/configuration#coveragethreshold-object). And we'd like to do the same for PHPUnit, without having to install other dependencies, or maintain a script to parse the coverage report.

Just an option 'minimum coverage' would be fine for us. But it would be even better if it could be split out per directory for example.

**Comment by sebastianbergmann** [comment]
My opinion has not changed.

**Comment by BackEndTea** [comment]
Fair enough, thanks for the quick reply
