### ISSUE TITLE
Better enum support in `@testdox`

### ISSUE THREAD

**Issue by OskarStark** [sebastianbergmann/phpunit#5097]
While its more and more common to use native PHP enums in data providers, it would be nice if the `@testdox` annotation not just print the class, but the value.

Lets use the following example:
```php
    /**
     * @test
     *
     * @dataProvider colorProvider
     * 
     * @testdox Color by string "$string" is $expected 
     */
    public function color(Color $expected, string $string): void
    {
        self::assertSame($expected, Color::byString($string);
    }

    public function colorProvider(): iterable
    {
        yield 'red' => [Color::RED, 'red'];
        yield 'blue' => [Color::RED, 'blue'];
    }
```

with the following enum:
```php
namespace App\Enum;

enum Color: string
{
    case RED = 'red';
    case RED = 'blue';

    public function byString(string $string): self
    {    
        return match($string) {
            'red' => self::RED,
            'blue' => self::BLUE,
        };
    }
}
```

Right now the output of the `@testdox` annotation is:
`Color by string "red" is App\Enum\Color`

in case of a `\BackedEnum`, the following output would be more helpful:
```diff
- Color by string "red" is App\Enum\Color
+ Color by string "red" is App\Enum\Color::RED
```

I am willing to provide a PR if you can point me in the right direction

cc @localheinz as we talked about this already

**Comment by OskarStark** [comment]
Thank you very much @sebastianbergmann 🙏

That was fast 🥰

**Comment by rcsofttech85** [comment]
@OskarStark  enum Color is invalid .
![carbon](https://github.com/sebastianbergmann/phpunit/assets/17738213/2fe23b46-d6a4-4b79-b239-ad6ae6306f33)
