### ISSUE TITLE
Proper way to add a property to a mock object?

### ISSUE THREAD

**Issue by come-nc** [sebastianbergmann/phpunit#5099]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.26
| PHP version         | 8.2 RC
| Installation Method | Composer

#### Summary

When setting a public property on a mock object with `$object->prop = 'value';`, PHP >= 8.2 complains about a dynamic var.

#### Current behavior

`Creation of dynamic property Mock_IRequest_a01db3a3::$server is deprecated`

#### How to reproduce

```
		$this->request = $this->createMock(IRequest::class);
		$this->request->server['PHP_AUTH_USER'] = 'clientId';
```

#### Expected behavior

No error, or some other way to ask a mock object to return a given value for a public property.

**Comment by sebastianbergmann** [comment]
This is not a PHPUnit issue.

**Comment by come-nc** [comment]
> This is not a PHPUnit issue.

What do you mean?
What is the correct way to do that then?
createMock comes from https://github.com/sebastianbergmann/phpunit/blob/main/src/Framework/TestCase.php#L1121

I searched and could not find a documented way of adding a property to a MockObject, I only found solutions for methods, and related stackoverflow topics all recommend setting the property dynamically, which is deprecated in PHP 8.2.

**Comment by anomiex** [comment]
I came here looking for the same thing, after not finding a way to set the attribute when creating the mock class. Sad to see no solution, just a "not my problem" response.
