### ISSUE TITLE
Possible bug with backupStaticAttributes/Properties & Data Providers

### ISSUE THREAD

**Issue by beryllium** [sebastianbergmann/phpunit#5103]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.26
| PHP version         | 8.1.6
| Installation Method | Composer

#### Summary

Classes that are set to `@backupStaticAttributes enabled` do not seem to be protected when a static attribute change occurs within the data provider. This also occurs if the backupStaticAttributes flag is set in the XML file.

Encountered this issue today where a data provider, while mocking an object, called its constructor - deep down in the codebase, that constructor then set a protected static class variable to an unexpected value. Subsequent tests failed because of this, even though the `@backupStaticAttributes enabled` docblock declaration was present. While this primarily resulted from issues in our own codebase, I think it also revealed a bug or misunderstanding around using static attribute backups.

#### Current behavior

* A static class variable modified in a data provider is not backed up/restored properly even though `@backupStaticAttributes enabled` has been set.

#### How to reproduce

1. Have a mature PHP codebase with a lot of static class variables
2. Unintentionally update one of those variables in a data provider while assembling mock objects & not disabling original constructors
3. A subsequent test (in a different test class) that expects the "clean" version of that variable should then fail

#### Expected behavior

1. Serialization of static attributes/properties would occur when processing data providers
2. That same serialized backup would be restored when running the actual test cases for that class
3. The tests would be better isolated from each other when they need to be, allowing them to pass without requiring full process isolation
4. (or some variation of the above that fits with any planned updates to data provider implementation)

**Comment by beryllium** [comment]
Attached: A zip file containing a sample of the issue. While building this, I also noticed that processIsolation causes data provider actions to be isolated from the test runs, at least from a static class variable perspective.

[issue-5103.zip](https://github.com/sebastianbergmann/phpunit/files/10080982/issue-5103.zip)

**Comment by sebastianbergmann** [comment]
A data provider method must not have side effects. It must only generate and return data. It must not create stubs or mocks, etc.

**Comment by beryllium** [comment]
Makes sense. Thank you.
