### ISSUE TITLE
Proper way to share test methods and data providers between testCases

### ISSUE THREAD

**Issue by vladtooo** [sebastianbergmann/phpunit#5105]
### Context
We have multiple drivers that use same interface.
```php
interface DriverInterface {
    public function doJob($arg);
}

class DriverA {
    public function doJob($arg){
        // does job in A manner
    }
}

class DriverB {
    public function doJob($arg){
        // does job in B manner
    }
}
```
We need a way to ensure they return same result based on provided input.

We create common DriverTestCase, and then extend it for each concrete driver:
```php
class DriverTestCase extends TestCase {
   /**
     * @dataProvider doJobProvider
     */
    public function testDoJob($arg,$expected){
        $this->assertEquals($expected,$this-driver->doJob($arg));
    }
   
    public function doJobProvider(){
        //...
    }
}

class DriverATest extends DriverTestCase{
    public function setUp():void {
        $this-driver = new DriverA();
    }
}

class DriverBTest extends DriverTestCase{
    public function setUp():void {
        $this-driver = new DriverB();
    }
}
```

Then we want to test driverA, and run phpunit (i use phpStorm, it generates command automatically, but it looks like this):
```
/usr/bin/php vendor/phpunit/phpunit/phpunit --filter "/DriverATest::testDoJob)( .*)?$/" --test-suffix DriverTestCase.php /path/to/dir 
```

It worked.
Now this behavior is deprecated:

```
Test case class not matching filename is deprecated
```

### Questions

1. How should we cover this use-case using phpunit since "Test case class not matching filename is deprecated"? 
2. Is it expected to copy-paste test method ```testDoJob($arg,$expected)``` and data provider ```doJobProvider()``` to DriverATest, DriverBTest ... DriverZTest?

Thank you in advance.

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.

However, have a look at [LongestCommonSubsequenceTestCase](https://github.com/sebastianbergmann/diff/blob/main/tests/LongestCommonSubsequenceTestCase.php) and its subclasses.

**Comment by vladtooo** [comment]
@sebastianbergmann Sebastian, I do understand that this is not support forum.
Look from my side: functionality of product i use is declared deprecated, and no alternative suggested. I ask you to suggest alternative here. I really don't see anything except copy-pasting or meta-programming (like generating concrete test-classes before execution).

At least, this issue can be one we can refer to.
I'm sorry for inconvenience, but this is what we really need.
