### ISSUE TITLE
Question: Any good insight about replacing overridden runBare() implementations in PHPUnit 10

### ISSUE THREAD

**Issue by stronk7** [sebastianbergmann/phpunit#5107]
Hi,

just have started prospecting the changes coming with PHPUnit 10 and the very first one we've faced here is:

> The public methods of `PHPUnit\Framework\Assert` and `PHPUnit\Framework\TestCase` are now `final`

So it's not possible anymore to override methods like `runBare()` that we used to hyper-charge with a lot of custom stuff, specifically, all the reseting of the site between tests when needed to. For example, this is our simplest case (in our basic_testcase):

https://github.com/moodle/moodle/blob/0ea3d45e04/lib/phpunit/classes/basic_testcase.php#L60

I've been looking in various issues and comments but haven't been able to find a recommendation about how to replace uses. If something, all those changes seem to be a final step towards the changes planned in https://github.com/sebastianbergmann/phpunit/issues/3213 , but that's all I've been able to infer.

So, the very basic question here is... how should we be replacing those overridden `runBare()` methods? Maybe using hooks as specified @ https://phpunit-document-english.readthedocs.io/en/latest/extending-phpunit.html#extending-the-testrunner ? Is that a potentially correct approach?

It would be great to have some public statement about that (maybe we have been doing it wrongly since 10 years ago, heh, but it just was possible and worked), because I can imagine that others may be well impacted because of this new (and good) restriction.

Ciao :-)

**Comment by sebastianbergmann** [comment]
The documentation for extending the test runner is 1) out of date and 2) will be rewritten in time for the release of PHPUnit 10.

`runBare()` should not be overwritten for "reseting of the site between tests", for example. Instead, `setUp()` and `tearDown()` should be used.

**Comment by stronk7** [comment]
Thanks for the quick response, @sebastianbergmann . Looking forward to the test runner 10 docs, and analysing if the `setUp()` / `tearDown()` is a viable alternative for us.

Ciao :-)
