### ISSUE TITLE
Mocking a class results in TypeError when a method parameter name ends up being null

### ISSUE THREAD

**Issue by bbaga** [sebastianbergmann/phpunit#5111]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | >=9.5.25
| PHP version         | 7.4.27
| Installation Method | Composer

#### Summary
After upgrading to `9.5.25` (and `9.5.26`) we started to see the following error:

`TypeError: Argument 1 passed to SebastianBergmann\Type\Parameter::__construct() must be of the type string, null given, called in /app/vendor/sebastian/type/src/ReflectionMapper.php on line 35`

The error is triggered by this line:
```php
$this->createMock(\Aerospike::class);
```

We have the following Aerospike module installed:
```shell
$ php -m
aerospike

aerospike support => enabled
client version => 7.4.2
```

Tried to look at the parameter that causes the error, this is all I found:
```
vendor/sebastian/type/src/ReflectionMapper.php:41:
class ReflectionParameter#413 (1) {
  public $name =>
  NULL
}
```

Thus far the issue seems to be related to the Aerospike client, at least we haven't encountered the problem with other classes.
Looking at the changes between 9.5.24 and 9.5.25 makes me think [one of the removed null checks may have been preventing this issue](https://github.com/sebastianbergmann/phpunit/compare/9.5.24...9.5.25#diff-c05d1d0f924588a481d55045a4cfcfdf411fb19cf94466223e5240710a5f4005L288-L338) to happen, but it is just guessing at this point.

#### Expected behavior

This setup worked fine in previous releases, we'd expect it to continue working.

#### Example project

https://github.com/bbaga/phpunit-issue-5111#phpunit-issue-5111

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by bbaga** [comment]
I prepared an example project that demonstrates the issue:
https://github.com/bbaga/phpunit-issue-5111#phpunit-issue-5111

Let me know if this doesn't suffice.

**Comment by sebastianbergmann** [comment]
This appears to not be an issue in PHPUnit, but rather in the PHP extension you are using. Please bring this up with the maintainer of this extension as they need to provide valid and complete Reflection API information.
