### ISSUE TITLE
Using phpunit without composer

### ISSUE THREAD

**Issue by BSarmady** [sebastianbergmann/phpunit#5112]
I'm trying to use phpunit without composer.

My folder structure is as below
```
-Root
    + library
        lib1.php
    +Test
        + testsuit1
            test1_test.php
        + testsuit2
        phpunit.bat
        phpunit.phar
autoloader.php
```

`lib1.php` contains a class called lib1
```php
class lib1{}
```
autoloader.php contains
```php
<?php
spl_autoload_register(function ($name) {
    echo "--->" . $name .'<---';
    if (file_exists('.\\' . $name . '.php')) {
        require_once $name . '.php';
        return true;
    }
    return false;
});
```

`phpunit.bat` contains
```console
php phpunit-9.5.26.phar --bootstrap ../autoload.php --colors=always --test-suffix=_test.php %*
```

`test1_test.php` contains
```php
<?php declare(strict_types=1);

use PHPUnit\Framework\TestCase;
use \library\lib1;

final class roles_test extends TestCase {

    public function test1(): void {
        $param = new lib1();
        ...
    }
}
```

Running test with ```phpunit .```

I get following output

```console
...
1) test1_test::test1
--->PHPUnit\Composer\Autoload\ClassLoader<---Error: Class "\library\lib1" not found
...
```
Obviously my class loader is loaded and working since the text between `--><--` is from there but the issue is phpunit is looking for Autoloader in composer which I don't have

How do I fix this?

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.

**Comment by BSarmady** [comment]
Did you notice the error that is **"PHPUnit\Composer\Autoload\ClassLoader"** when there is no composer available in project?
