### ISSUE TITLE
If test does not contain assert then test coverage is always empty

### ISSUE THREAD

**Issue by Tetragramat** [sebastianbergmann/phpunit#5114]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.26
| PHP version         | 7.4.9
| Installation Method | Composer

#### Summary

Test coverage is always empty (nothing is covered) when test does not contain at least single assert. Using `doesNotPerformAssertions` annotation has no effect.

If it is intended behavior, then it should be at least documented. I haven't found anything saying that code coverage will be always empty if test does not contain any assert.

#### Current behavior

If test does not contain assert, then test coverage is empty.
If test contains at least `assertTrue(true)`, then test coverage contains expected coverage.

#### How to reproduce

Make any test that does not have any assert and run phpunit with code coverage.

#### Expected behavior

Code coverage should not be empty, but should contain covered lines. Even if for some reason risky test without assertions is problem then annotation `doesNotPerformAssertions` or function `expectNotToPerformAssertions`  should fix the issue.

**Comment by sebastianbergmann** [comment]
This works as intended.
