### ISSUE TITLE
Allow attribute customization

### ISSUE THREAD

**Issue by remorhaz** [sebastianbergmann/phpunit#5118]
Attributes are a powerful feature, and sometimes it would be very convenient to implement custom attributes that implement standard PHPUnit behavior.

### Example:
Let's imagine that we use custom attribute to set up test case ID, like this: `#[MyTestId('API123')]`. The ID format allows us to detect test group automatically, instead of writing down both `MyTestId` and `Group`; but how do we assign it?

### Soultion 1 (bad):
If PHPUnit used an `interface GroupInterface` instead of `final class Group` while parsing attributes, we could just implement this interface in our custom attribute and simplify our work. But what if we want to assign group conditionally? What if we implement several interfaces and they have collisions?

### Solution 2 (good):
We can declare an "attribute provider" interface which returns a list of attributes, that should be processed by PHPUnit just as they were declared explicitly, like this:

```php

// namespaces omitted for simplicity

interface AttributeProvider
{
    public function getAttributesForClass(): array;

    public function getAttributesForMethod(): array;
}

#[Attribute(Attribute::TARGET_CLASS | Attribute::TARGET_METHOD)]
final class MyTestId implements AttributeProvider
{
    public function __construct(private string $id) {
    }

    public function getAttributesForMethod(): array
    {
        return str_starts_with($this->id, 'API') ? [new Group('api')] : [];
    }

    // ...
}
```
It's easy to implement processing of such an attribute in `AttributeParser`.

**Comment by sebastianbergmann** [comment]
I think that PHPUnit should be oblivious to attributes that it does not own, just as it is oblivious to annotations it does not own.

**Comment by remorhaz** [comment]
> I think that PHPUnit should be oblivious to attributes that it does not own

Of course. The proposition is that PHPUnit might own not only attribute, but attribute interface, too.
