### ISSUE TITLE
Emit an event before calling hook method

### ISSUE THREAD

**Issue by remorhaz** [sebastianbergmann/phpunit#5119]
I write an integration for [Allure reporting framework](https://github.com/allure-framework) and try to support PHPUnit 10.

What I want to do: for each `before` hook I want to capture some activities that happens in hook method and then add them in a separate block to report. And if there are no such hooks in test case - I don't want to create any blocks.

The problem is that I didn't found any event that is emitted _before_ the hook method is called - to start capturing. We have `BeforeTestMethodCalled` (called _after_ the `before` hook method) and `BeforeTestMethodFinished` (called after all `before` hook methods), but for some reason we don't have something like `BeforeTestMethodCalling`. And we don't have even `BeforeTestMethodStarted` that could be emitted before all the `before` hooks.

It would be great if PHPUnit could emit events not only after each hook method / hook group, but also before.

**Comment by sebastianbergmann** [comment]
An event must only be emitted after something has happened.

**Comment by remorhaz** [comment]
> An event must only be emitted after something has happened.

I totally agree, and, for example, `Test\PreparationStarted` follows this rule; so what logic allows us to have `Test\PreparationStarted`, but forbids to have `Hook\PreparationStarted`?
