### ISSUE TITLE
Document return type for createStubForIntersectionOfInterfaces() and createMockForIntersectionOfInterfaces()

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#5122]
The methods [`createStubForIntersectionOfInterfaces()`](https://github.com/sebastianbergmann/phpunit/blob/75aa7157530ca63f39b7f7a1b88369391c543921/src/Framework/TestCase.php#L1113) and [`createMockForIntersectionOfInterfaces()`](https://github.com/sebastianbergmann/phpunit/blob/75aa7157530ca63f39b7f7a1b88369391c543921/src/Framework/TestCase.php#L1149) accept a list of interfaces (`list<class-string>`) and return an intersection of these interface plus `Stub` or `MockObject`, respectively.

This fact needs to be document through annotations that can be understood by static analysis tools.

**Comment by sebastianbergmann** [comment]
@Ocramius provided information on how this should be done in https://phpc.social/@ocramius@mastodon.social/109556817611785580:

* https://psalm.dev/r/2f042afb74
* https://3v4l.org/kmY3u#v8.2.0

**Comment by Ocramius** [comment]
The problem with having a `list<class-string<T>>` as input is that a single `T` can be bound as an input type there: that's why the builder approach may be better, although a change in API is obviously painful for downstream.
