### ISSUE TITLE
Missing data provider index in testdox output

### ISSUE THREAD

**Issue by fefas** [sebastianbergmann/phpunit#5125]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.27
| PHP version         | 7.3, 7.4, 8.0, 8.1, 8.2
| Installation Method | Composer

#### Summary

Testdox does not output the data provide index if an argument is "empty".

#### How to reproduce

> I have created a [project](https://github.com/fefas/phpunit-testdox-bug) to reproduce this bug and all details such as output in all PHP versions and `composer install` logs can be seen in the [pipeline](https://github.com/fefas/phpunit-testdox-bug/actions/runs/3807142792/jobs/6476552736).

```php
// tests/ReproduceTest.php
<?php

use PHPUnit\Framework\TestCase;

class ReproduceTest extends TestCase
{
    public function iterableDataProvider(): iterable
    {
        yield 'no arg' => []; // will not have "no arg" printed out when using `--testdoz`
        yield 'one arg' => [1];
        yield 'two args' => [1, 2];
    }

    /**
     * @test
     * @dataProvider iterableDataProvider
     */
    public function reproduceWithIterableDataProvider(int ...$args): void
    {
        self::assertTrue(true);
    }

    public function arrayDataProvider(): array
    {
        return [
            'no arg' => [],
            'one arg' => [1],
            'two args' => [1, 2],
        ];
    }

    /**
     * @test
     * @dataProvider arrayDataProvider
     */
    public function reproduceWithArrayDataProvider(int ...$args): void
    {
        self::assertTrue(true);
    }
}
```

#### Current behavior

```
$ composer exec phpunit -- tests/ReproduceTest.php --testdox
PHPUnit 9.5.27 by Sebastian Bergmann and contributors.

Reproduce
 ✔ Reproduce with iterable data provider
 ✔ Reproduce with iterable data provider with one·arg
 ✔ Reproduce with iterable data provider with two·args
 ✔ Reproduce with array data provider
 ✔ Reproduce with array data provider with one·arg
 ✔ Reproduce with array data provider with two·args
```

#### Expected behavior

```
$ composer exec phpunit -- tests/ReproduceTest.php --testdox
PHPUnit 9.5.27 by Sebastian Bergmann and contributors.

Reproduce
 ✔ Reproduce with iterable data provider with no·arg
 ✔ Reproduce with iterable data provider with one·arg
 ✔ Reproduce with iterable data provider with two·args
 ✔ Reproduce with array data provider with no·arg
 ✔ Reproduce with array data provider with one·arg
 ✔ Reproduce with array data provider with two·args
```

**Comment by fefas** [comment]
Actually, I was wondering exactly what you mentioned. However, I still don't see our use case as an invalid dataset. Let me give a bit more context of a sample behavior where an empty data set could make sense and be valid.

> Let's suppose there is an aggregate that has a collection of items. This collection may be empty and an item may be in one of two states (`A` and `B`). An exception must always be thrown when a method on the aggregate is called unless the collection has at least one item in state `A`.

This is basically the scenario I had that led me to create an empty data set.

In the end, I could have handled it by adding another test like `throwExceptionIfThereIsNoItem`, but having all _throwing exception_ scenarios together with one data provided seemed cleaner for me in the given situation.

Anyway, if you still make the decision empty data sets are invalid even in such cases, I could also agree and commit to that. Btw, thanks for maintaining PHPUnit :)

Here is a sample code to illustrate my case:

```php
<?php

class MyTest extends PHPUnit\Framework\TestCase
{
    public function dataProviderForThrowingExceptionCase(): iterable
    {
        yield 'no items' => [];
        yield 'one item in state B' => [ Item::inStateB() ];
        yield 'two items in state B' => [ Item::inStateB(), Item::inStateB() ];
    }

    /** @test */
    public function throwExceptionIfThereIsNoItemInStateA(Item ...$items): iterable
    {
        $aggregate = Aggregate::reconstituteWith(items: $items);

        $this->expectException(...);

        $aggregate->do();
    }

    public function dataProviderForNormal(): iterable
    {
        yield 'one item in state A' => [ Item::inStateA() ];
        yield 'two items in state A' => [ Item::inStateA(), Item::inStateA() ];
        yield 'one item in state A and another in B' => [ Item::inStateA(), Item::inStateB()];
    }

    /** @test */
    public function doIfThereIsAtLeastOneItemInStateA(Item ...$items): iterable
    {
        $aggregate = Aggregate::reconstituteWith(items: $items);

        $aggregate->do();

        self::assertTrue($aggregate->wasDone());
    }
}
```

**Comment by jrmajor** [comment]
> Let's suppose there is an aggregate that has a collection of items.

@fefas If you have a collection, I'd suggest passing it as an array instead of a variadic arguments:

```php
public function dataProviderForThrowingExceptionCase(): iterable
{
    yield 'no items' => [[]];
    yield 'one item in state B' => [[Item::inStateB()]];
    yield 'two items in state B' => [[Item::inStateB(), Item::inStateB()]];
}

/**
 * @test
 * @param list<Item> $items
 */
public function throwExceptionIfThereIsNoItemInStateA(array $items): iterable;
```

**Comment by fefas** [comment]
@jrmajor that indeed works, but the entire idea is to use type hint instead of array with docblock.

**Comment by jrmajor** [comment]
Using variadic arguments to get a typed collection is a bit ”hacky“ though, so you're probably going to run into more issues like this.

**Comment by fefas** [comment]
@jrmajor not sure if type-hinting arrays with docblocks may be considered a less hacky solution. Or aren't docblocks basically hacks? 😅

In my point of view, choosing between both options is more of a prefered style for a given codebase. I prefer types explicit by the syntax over docblocks.

Therefore, I am fine with running into this kind of problem because of (1) the reason same mentioned above (since it is a fine trade-off) and (2) I guess that is also how things get improved over time.

Anyway, feel free to close the issue if I am mistaken and this should not be seen as a bug.
