### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by EVCV** [sebastianbergmann/phpunit#5127]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.0.0
| PHP version         | 8.2.0
| Installation Method | Composer

C:\Users\XXXXX>composer require --dev phpunit/phpunit ^9
The "9" constraint for "phpunit/phpunit" appears too strict and will likely not match what you want. See https://getcomposer.org/constraints
./composer.json has been created
Running composer update phpunit/phpunit
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires phpunit/phpunit 9 -> satisfiable by phpunit/phpunit[9.0.0].
    - phpunit/phpunit 9.0.0 requires php ^7.3 -> your php version (8.2.0) does not satisfy that requirement.

Installation failed, deleting ./composer.json.

I have PHP 8.2 but it says I need a version greater than 7.3 which I have

**Comment by sebastianbergmann** [comment]
This is not a PHPUnit issue, but an issue with Composer (you are using it wrong, sorry).

**Comment by EVCV** [comment]
Im following the instruction on your GitHub page and it gives me that issue.
