### ISSUE TITLE
PHPUnit v10 release date

### ISSUE THREAD

**Issue by nunomaduro** [sebastianbergmann/phpunit#5129]
Hi Sebastian,

My name is Nuno and I am the creator of Pest. I was wondering if you have any information about the release date of PHPUnit v10. I ask because Pest is built on top of PHPUnit and I am preparing the release of Pest v2, which is also built on PHPUnit v10. In addition, Laravel v10 is coming out in February and we are discussing internally which versions of PHPUnit to support.

**Comment by klaoun** [comment]
2023 - 02 - 03 so soon :⁠-⁠)

**Comment by nunomaduro** [comment]
I also I've seen that date on the website. However, I would like to verify this with @sebastianbergmann directly to ensure accuracy.

**Comment by sebastianbergmann** [comment]
First Friday of February is the plan, yes.
