### ISSUE TITLE
Make expected and actual value available in Test\Failed event

### ISSUE THREAD

**Issue by olivernybroe** [sebastianbergmann/phpunit#5131]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.x
| PHP version         | 8.2
| Installation Method | Composer

#### Summary

I am trying to implement the TeamCity logger for PestPHP 2.x which is build on PHPUnit 10.x and I am stuck on us not being able to get the underlying exception on the `FailedSubscriber`. 

TeamCity has a special type for comparison failures which allows IntelliJ to show a diff dialog. 
Some proposals for solving
- And interface which allows for injecting metadata into PhpUnit Throwable and make `ExpectationFailedException` implement it.
- Give us access to the actual exception instance
- Create a special `Throwable` class for comparison failures. (prob. the simplest)

This issue is not only limited to PestPHP, I looked at the `TeamCityLogger` for PHPUnit 10, and this special comparison failure type has been removed from the code.

**Comment by sebastianbergmann** [comment]
The `Failed` event that is passed to a `FailedSubscriber`'s `notify()` method provides access to a `PHPUnit\Event\Code\Throwable`. Are you saying that `PHPUnit\Event\Code\Throwable` does not have all the information you need?

**Comment by olivernybroe** [comment]
@sebastianbergmann yes.
The `PHPUnit\Event\Code\Throwable` tells me what the exception message and class was, however we need to know the `actual` and `expected` strings.
![image](https://user-images.githubusercontent.com/5870441/211263826-e7abe38b-150b-475d-ac9a-4cc98ea6a157.png)

What we did before was checking for the `\PHPUnit\Framework\ExpectationFailedException` exception and then calling `\PHPUnit\Framework\ExpectationFailedException::getComparisonFailure` to get the `expected` and `actual` as strings from it.

**Comment by sebastianbergmann** [comment]
I will think about this, thank you for bringing this up.

**Comment by olivernybroe** [comment]
@sebastianbergmann no problem. 

Just wanna note that this is also relevant for phpunit 10 itself. In phpunit 9 you were able to get the diff window in phpstorm when doing comparisons, however that won't work in phpunit 10.

**Comment by sebastianbergmann** [comment]
That would mean that PHPUnit's end-to-end tests for TeamCity output are not sufficient.

**Comment by olivernybroe** [comment]
Yes, just double checked the E2E test and there are no `teamcity` events with `type='comparisonFailure'` in them.

A simple comparison check like `$this->assertEquals(true, false);` is sufficient. (using bool for also checking that it is casting to strings)

**Comment by sebastianbergmann** [comment]
Does https://github.com/sebastianbergmann/phpunit/commit/a06635903e3f50fad271d30777660b08b6de6232 make the data available you need?

**Comment by sebastianbergmann** [comment]
> Yes, just double checked the E2E test and there are no `teamcity` events with `type='comparisonFailure'` in them.

Thanks!

The `8.5` and `9.5` branches now have such a test: https://github.com/sebastianbergmann/phpunit/commit/3084c105230e0d24fe890d3f60cce173b0e4210c

Locally, I have already merged this to `main`. `Now to make it work on `main` ...

**Comment by sebastianbergmann** [comment]
> Does [a066359](https://github.com/sebastianbergmann/phpunit/commit/a06635903e3f50fad271d30777660b08b6de6232) make the data available you need?

After https://github.com/sebastianbergmann/phpunit/commit/f22c8b2df7c6bcd866f51d15c7f19e655e24be72, this should work :)

**Comment by olivernybroe** [comment]
I have tested it out and this solved our issue also :) 

Thank you for the amazing work and quick response time.

Closing the issue, but feel free to open if you have a different process for when to close.
