### ISSUE TITLE
Results Printer uses error coloring for skipped test

### ISSUE THREAD

**Issue by KevinBKozan** [sebastianbergmann/phpunit#5133]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.10
| PHP version         | 8.1.13
| Installation Method | Composer

#### Summary

Results Printer outputs error colloring to console when executing tests (see screenshot)

#### Current behavior

Test name is output in red/white in console

#### How to reproduce

* Mark test as skipped for phpunit
* Run Test

#### Expected behavior

Test name is output with skipped coloring (yellow/black)

**Comment by KevinBKozan** [comment]
<img width="1440" alt="Screenshot 2023-01-03 at 12 17 29 PM" src="https://user-images.githubusercontent.com/28712019/211650144-2d3076d8-90bf-42a1-8964-2d0b46b800dc.png">

Overall output is colors are correct, but note the `Test` text is using the wrong colors.
This should be a fairly simple fix 👍

**Comment by sebastianbergmann** [comment]
Your screenshot does not show the default output emitted by PHPUnit 9.5:

#### `tests/ExampleTest.php`
```php
<?php declare(strict_types=1);
use PHPUnit\Framework\TestCase;

final class ExampleTest extends TestCase
{
    public function testOne(): void
    {
        $this->markTestSkipped('message');
    }
}
```
![grafik](https://user-images.githubusercontent.com/25218/211710118-fccdc547-c70d-4eb6-884f-9e51c519ffc8.png)

I assume you are using a custom test result printer.
