### ISSUE TITLE
Warnings do not appear in output or in JUnit logfiles

### ISSUE THREAD

**Issue by Slamdunk** [sebastianbergmann/phpunit#5136]
Warnings in PHPUnit 10 appear in the stats at the bottom of summary `Tests: 1, Assertions: 1, Warnings: 1.` but without details neither in `STDOUT` nor in JUnit logs.

### Test

```php
class MyWarningTest extends TestCase
{
    public function testWarning(): void
    {
        trigger_error('MyWarning', E_USER_WARNING);
        self::assertCount(1, [1]);
    }
}
```

#### Output
```
PHPUnit 9.5.28 by Sebastian Bergmann and contributors.

E                                                                   1 / 1 (100%)


Time: 00:00.038, Memory: 8.00 MB

There was 1 error:

1) MyWarningTest::testWarning
MyWarning

/MyWarningTest.php:34

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```

#### JUnit log

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="MyWarningTest" file="/MyWarningTest.php" tests="1" assertions="0" errors="1" warnings="0" failures="0" skipped="0" time="0.001784">
    <testcase name="testWarning" class="MyWarningTest" classname="MyWarningTest" file="/MyWarningTest.php" line="32" assertions="0" time="0.001784">
      <error type="PHPUnit\Framework\Error\Warning">MyWarningTest::testWarning
MyWarning

/MyWarningTest.php:34</error>
    </testcase>
  </testsuite>
</testsuites>
```

#### Output

```
PHPUnit 10.0-g6333dfcaa by Sebastian Bergmann and contributors.

Runtime:       PHP 8.2.1

.                                                                   1 / 1 (100%)

Time: 00:00.059, Memory: 6.00 MB

OK, but some tests have issues!
Tests: 1, Assertions: 1, Warnings: 1.
```

#### JUnit log

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="MyWarningTest" file="/MyWarningTest.php" tests="1" assertions="1" errors="0" failures="0" skipped="0" time="0.001341">
    <testcase name="testWarning" file="/MyWarningTest.php" line="32" class="MyWarningTest" classname="MyWarningTest" assertions="1" time="0.001341"/>
  </testsuite>
</testsuites>
```

**Comment by sebastianbergmann** [comment]
The fact that warnings do not appear in the output is by design and intentional: you have to use `--display-warnings` or `displayDetailsOnTestsThatTriggerWarnings="true"`.

I am not sure whether warnings should be included in the JUnit XML logfile.

**Comment by Slamdunk** [comment]
> The fact that warnings do not appear in the output by default is by design and intentional: you have to use `--display-warnings` or `displayDetailsOnTestsThatTriggerWarnings="true"`.

Oh I see, nice then :+1: 

> I am not sure whether warnings should be included in the JUnit XML logfile.

I've seen that warnings are missing from Teamcity logs too.
Tools leverage log files to collect and consume PHPUnit results, so I'd say that log files should contain everything needed to report any feedback available.

**Comment by Slamdunk** [comment]
I understand the impedance mismatch.
`<error type="PHPUnit\Framework\Error\Warning">` are more than enough by me, just like `Risky` tests.

> One things I want to tackle after the PHPUnit 10.0.0 release is to implement a new XML-based logfile format that we own. Warnings will certainly be included there.

Awesome :rocket: 

Just please understand that we need *something* until then :pray:

**Comment by sebastianbergmann** [comment]
Classes such as `PHPUnit\Framework\Error\Warning` no longer exist in PHPUnit 10.

**Comment by Slamdunk** [comment]
Neither does `PHPUnit\Framework\RiskyTest`, but it's the only way I can recognise  risky tests in logs:

https://github.com/sebastianbergmann/phpunit/blob/6333dfcaa698a020e8a7c437857dbdc4203fbc63/src/Logging/JUnit/JunitXmlLogger.php#L341

You can pick any string you want, maybe `PHPUnit\Framework\WarningTest`, we just need to be specific

**Comment by sebastianbergmann** [comment]
> Just please understand that we need _something_ until then 🙏

No, we do not.

With PHPUnit 9, `E_(USER_)WARNING`, `E_(USER_)NOTICE`, `E_(USER_)DEPRECATED`, etc. were converted by PHPUnit's error handler to exceptions. These exceptions 1) aborted the execution of a test and 2) made PHPUnit consider the test to have errored. In this context, using `<error type="PHPUnit\Framework\Error\Warning">` to document a warning makes sense.

PHPUnit 10's error handler no longer converts `E_(USER_)WARNING`, `E_(USER_)NOTICE`, `E_(USER_)DEPRECATED` to exceptions. Therefore, the execution of a test is no longer aborted when an `E_WARNING` is triggered, for instance. Consequently, such a test is no longer considered to have errored.

PHPUnit 10 has a clear separation between the [outcome](https://github.com/sebastianbergmann/phpunit/tree/dd745dadb3d7c748f79488c0e982c992e5f4b52a/src/Event/Events/Test/Outcome) (errored, failed, incomplete, skipped, or passed) of a test and the [issues](https://github.com/sebastianbergmann/phpunit/tree/dd745dadb3d7c748f79488c0e982c992e5f4b52a/src/Event/Events/Test/Issue) (considered risky, triggered a warning, ...) of a test.

I believe that only information about outcome should be logged in JUnit XML format. The new XML-based logfile format that I mentioned in https://github.com/sebastianbergmann/phpunit/issues/5136#issuecomment-1383707313 will also include information about issues, of course.

**Comment by Slamdunk** [comment]
> I believe that only information about outcome should be logged in JUnit XML format.

I understand and agree.

This means that until the new XML-based logfile doesn't go live, the only ways to gather issues are the `STDOUT` or custom `\PHPUnit\Event\Subscriber`s. Am I right?

**Comment by sebastianbergmann** [comment]
The clean/best way would be to register your own event subscriber(s). You probably could use the (`@internal` marked) class `PHPUnit\TestRunner\TestResult\TestResult` instead, but I would advise against that.

**Comment by Slamdunk** [comment]
> One things I want to tackle after the PHPUnit 10.0.0 release is to implement a new XML-based logfile format that we own. Warnings will certainly be included there.

At the end, for ParaTest v7 the solution I chose to minimize code duplication and maintenance cost is to serialize the `\PHPUnit\TestRunner\TestResult\TestResult` of each subprocess, and in the main process merge them together.

What I'd like to share with you is that `\PHPUnit\TestRunner\TestResult\TestResult` seems a really good candidate for an official proprietary log format. Converting that object from and to XML seems fine to me to have all the info anyone can need. /cc @Jean85

**Comment by Jean85** [comment]
Thanks for the heads up @Slamdunk. My approach with Paraunit was going in the opposite direction, and I'm registering subscribers to hook into PHPUnit. This is slower and has code duplication, but should be sturdier on the long run.

Right now I'm having an issue with warnings though, because I'm receiving the event AFTER the `Test\Finished` event, so I'm failing at considering it a test that generated a warning... Am I missing something?

**Comment by rvanlaak** [comment]
This comment https://github.com/sebastianbergmann/phpunit/issues/5136#issuecomment-1383691721 helped me when coming here via Google.

It might be valuable for PHPUnit to actually in the final output close to "OK,  but with warnings" also give a hint on how to start showing these warnings when a value for `displayDetailsOnTestsThatTriggerWarnings` is not explicitly set. Maybe only when there isn't any other output from the test at all?

**Comment by ballidev** [comment]
anyone else hitting this thread

I found that testdox output seems to prevent warnings info from being displayed. This seems to be the case if its either via XML config or CLI flag

disabling testdox allows warnings etc to be displayed

**Comment by sammarshallou** [comment]
It's a shame that this isn't being considered; our CI setup uses an integration that relies on the jUnit format output, and we would like to not completely ignore all warnings or risky tests, which is the current behaviour. Risky tests are especially valuable for spotting deprecated errors in new PHP versions.

While I understand that it's not appropriate to extend the junit log format, it doesn't need extending for this use case. With a flag such as:

--treat-risky-as-failure

they could be written into the junit log using exactly the same format as other failures. It would not be possible to distinguish between a failure for some other reason, and a failure due to text output, but that is the behaviour that we would like.

From what I understand we have the chance to implement this ourselves using event subscribers to write out our own custom jUnit format log file, which would work in the way I described. So while it's a shame that this change won't be made to PHPunit, anyone who wants does have an option to implement it.

**Comment by xy2z** [comment]
My warning did not show up when using --display-warnings, even without --testdox (it was because I was using `@unlink($path);`)

So for others who might run into this, if you add the `--debug` flag you can see which then shows if any PHP warnings are suppresed, example: `Test Triggered PHP Warning ...`
