### ISSUE TITLE
Parameter --order-by has no effect

### ISSUE THREAD

**Issue by oliworx** [sebastianbergmann/phpunit#5144]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.28 
| PHP version         | 8.0, 8.1, 8.2
| Installation Method | Composer

#### Summary

The option `--order-by` seems to have no effect, at least if combined with `--testdox` 

#### Current behavior

Test are always executed in the same order (as the methods appear in the class)

#### How to reproduce

Run phpunit with the parameters `--testdox --order-by=random` multiple times.  
The output is always the same:

````
php8.0 vendor/bin/phpunit --testdox --order-by=random tests/Feature/Commands/SendRecommendToPeersEmailTest.php
PHPUnit 9.5.28 by Sebastian Bergmann and contributors.

Random Seed:   1673948348

Send Recommend To Peers Email (Tests\Feature\Commands\SendRecommendToPeersEmail)
 ✔ Send email to user five days after registration
 ✔ No email to user registered more than five days ago
 ✔ No email to user registered less than five days ago
 ✔ Email to user with role member only
 ✔ Email to user five days after inquery confirmation or deletion with data set 0
 ✔ Email to user five days after inquery confirmation or deletion with data set 1

Time: 00:00.452, Memory: 38.50 MB

OK (6 tests, 26 assertions)
````

Other values for order-by have no effect either:

````
php8.0 vendor/bin/phpunit --testdox --order-by=duration tests/Feature/Commands/SendRecommendToPeersEmailTest.php
PHPUnit 9.5.28 by Sebastian Bergmann and contributors.

Send Recommend To Peers Email (Tests\Feature\Commands\SendRecommendToPeersEmail)
 ✔ Send email to user five days after registration
 ✔ No email to user registered more than five days ago
 ✔ No email to user registered less than five days ago
 ✔ Email to user with role member only
 ✔ Email to user five days after inquery confirmation or deletion with data set 0
 ✔ Email to user five days after inquery confirmation or deletion with data set 1

Time: 00:00.466, Memory: 38.50 MB

OK (6 tests, 26 assertions)
````

Order by size:

````
php8.0 vendor/bin/phpunit --testdox --order-by=size tests/Feature/Commands/SendRecommendToPeersEmailTest.php
PHPUnit 9.5.28 by Sebastian Bergmann and contributors.

Send Recommend To Peers Email (Tests\Feature\Commands\SendRecommendToPeersEmail)
 ✔ Send email to user five days after registration
 ✔ No email to user registered more than five days ago
 ✔ No email to user registered less than five days ago
 ✔ Email to user with role member only
 ✔ Email to user five days after inquery confirmation or deletion with data set 0
 ✔ Email to user five days after inquery confirmation or deletion with data set 1

Time: 00:00.447, Memory: 38.50 MB

OK (6 tests, 26 assertions)
````

#### Expected behavior

The order of the executed tests should change.

**Comment by sebastianbergmann** [comment]
The tests are executed in the selected order, but the TestDox printer reorders the output.

**Comment by oliworx** [comment]
what about the order of the test classes, if all tests are run?  
Seems like the files are always processed in the same order.  

Context: I would like to run all tests in complete random order to detect flaky tests early.

**Comment by oliworx** [comment]
> The tests are executed in the selected order, but the TestDox printer reorders the output.

To me this appears to be confusing. Wouldn't it be better to print the tests in the order they are actually run?

**Comment by sebastianbergmann** [comment]
There is conflict of objectives between "running tests in random order" and TestDox output. This is why the TestDox output reorders the tests in the output.

**Comment by oliworx** [comment]
> There is conflict of objectives between "running tests in random order" and TestDox output. This is why the TestDox output reorders the tests in the output.

OK, I see.  
Is there a way to run the test classes in random order too?
