### ISSUE TITLE
DX: Add Docker dev setup

### ISSUE THREAD

**Issue by Trusted97** [sebastianbergmann/phpunit#5158]
Hello everyone!
My name is Gianluca and I work for @immobiliare.
I want to thank you so much for the amazing work done on phpunit.
I really appreciate your work and would like to suggest adding docker to improve the contributions from the whole community.

To give you an idea of ​​what I mean I leave you a link to PHP-CS-FIXER that have already implemented this [feature](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/5234)

Best regards

P.s. If you think it's something useful, I'll be happy to send my PR to add this feature!

**Comment by sebastianbergmann** [comment]
I am not interested in adding this.
