### ISSUE TITLE
Making Metadata parser extendable

### ISSUE THREAD

**Issue by olivernybroe** [sebastianbergmann/phpunit#5159]
Currently for getting the parser for metadata the class `\PHPUnit\Metadata\Parser\Registry` is used. It would be very nice if we could extend this class with more parsers or if we could extend the `AttributeParser` with more attributes to pass. 

This could allow plugins to add extra metadata into a testCase for them to use when printing out information. At the same time, having this extendable could also clean up the `AttributeParser` which currently contains a 300 lines long switch statement.

The reason why I stumbled upon this and why I would like this feature is for PestPHP. 
As PestPHP generates it's test files on the go, getting the file name and lines via reflection API will result in the file location not being correct. My current hack to get the correct path is to use `testDox` tags to store the metadata I need. 
Another possible solution for our specific problem could of course also be to replace the reflection API usage when test suites are generated with a extendable/replaceable logic, so PestPHP can override it with it's way to resolve the correct file name.
The reason why I am suggesting the metadata approach, is because I could see the use-case of other plugins wanted to extend on this.

**Comment by sebastianbergmann** [comment]
The metadata parser is an implementation detail of PHPUnit that I do not think should be extendable by extensions for / wrappers around PHPUnit's test runner.

**Comment by olivernybroe** [comment]
Hmm fair. 

Do you have another good idea for us to solve this issue if this is not a thing that you would like to have part of/maintain in PHPUnit?
