### ISSUE TITLE
Turn off colors on command line

### ISSUE THREAD

**Issue by ghost** [sebastianbergmann/phpunit#516]
Can you add `--no-colors` please so we can turn off colors that might have been set in the phpunit.xml.dist?

REF: Solved by installing ANSI driver with [ANSICON](http://softkube.com/blog/ansi-command-line-colors-under-windows/)

**Comment by olleharstedt** [comment]
Would be nice if `colors=never` would also turn off colours in exceptions. Right now, the line number is yellow, which is impossible to read with white background.
