### ISSUE TITLE
PHPUnit 9.6 misses deprecations for assertions and constraints removed in PHPUnit 10

### ISSUE THREAD

**Issue by verfriemelt-dot-org** [sebastianbergmann/phpunit#5160]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.0.1
| PHP version         | 8.2.2
| Installation Method | Composer

#### Summary

i have no deprecations warnings about that method in 9.5 nor 9.6 but tests break with 10 :thinking: 
shouldn't there be at least a deprecation warning?

maybe this was missed due to being planned for phpunit 11 previously?

https://github.com/sebastianbergmann/phpunit/issues/4602

thank you for you great effort :) really appreciate it!

**Comment by verfriemelt-dot-org** [comment]
thanks for your quick fix :)

**Comment by stronk7** [comment]
Hi,

I've commented in a few issues about the same, sorry for the spam... isn't it a little bit useless to get the warnings in the 9.x series without getting also the replacements?

There are a lot of people still needing to run tests for php <= 80 and these new warnings are generating all that noise without any way to get it sorted out other than changing tests to an interim solution (`assertTrue(property_exists(...))` or implementing the "assertions" in own testcase classes... or other hacks.

Ideally, the versions where a warning is created should get, always, the new counterparts (when available). And, in this case, there are new counterparts (`assertObjectHas[Not]Property(), ...`) to move the assertions to.

Just my 2 cents, surprised with some good hundreds of unexpected warnings after updating composer dependencies here, heh.

Ciao :-)
