### ISSUE TITLE
Cannot register subscriber that implements multiple interfaces

### ISSUE THREAD

**Issue by Jean85** [sebastianbergmann/phpunit#5161]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.0.1
| PHP version         | 8.1
| Installation Method | Composer

#### Summary

A subscriber that implements multiple subscriber interfaces gets registered only for the first declared interface.

#### Current behavior
Only one kind of event is received.

#### How to reproduce
Write a subscriber like this:
```
class TestWarning extends AbstractTestHook implements WarningTriggeredSubscriber, PhpWarningTriggeredSubscriber
{
    public function notify(WarningTriggered|PhpWarningTriggered $event): void
    {
        // ...
    }
}
```
and register it.

#### Expected behavior
Both kind of events are received.

I'll try to follow up with a PR shortly.

**Comment by sebastianbergmann** [comment]
This is not a bug, but rather works as we intended it to work: a subscriber should be specific to one event (single responsibility).

For the very special case of subscribing to all events, we have created the concept of a [`Tracer`](https://github.com/sebastianbergmann/phpunit/blob/10.0.1/src/Event/Tracer.php).

**Comment by Jean85** [comment]
Well, in my use case, I just wanted to group the `Test\WarningTriggered`, `PHPWarningTriggered` and `TestSuite\WarningTriggered` events that, from my PoV, are the same.

Still, no problem, I'll split my subscribers, I understand your concern.
