### ISSUE TITLE
"No code coverage driver available" with phpdbg and phpunit 10

### ISSUE THREAD

**Issue by acelaya** [sebastianbergmann/phpunit#5173]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.0.4
| PHP version         | 8.2.2
| Installation Method | Composer

#### Summary

I'm updating a project to PHPUnit 10 where I use `phpdbg` to generate coverage reports via the next script:

`phpdbg -qrr vendor/bin/phpunit --coverage-clover=build/clover.xml --coverage-xml=build/coverage-xml --log-junit=build/junit.xml`.

Everything works fine with PHPUnit 9.6, but after updating to v10 it always complains there's no code coverage driver available.

#### Current behavior

Running phpunit via phpdbg in order to generate code coverage reports fails due to driver not available

#### How to reproduce

This command produces the warning:

`phpdbg -qrr vendor/bin/phpunit --coverage-clover=build/clover.xml --coverage-xml=build/coverage-xml --log-junit=build/junit.xml`

#### Expected behavior

PHPUnit detects phpdbg and is able to generate code coverage reports.

**Comment by sebastianbergmann** [comment]
PHPDBG is no longer supported by php-code-coverage, you need PCOV or Xdebug 3 now.

**Comment by acelaya** [comment]
I believe the docs need an update then? They still mention phpdbg https://phpunit.readthedocs.io/en/10.0/code-coverage-analysis.html

**Comment by acelaya** [comment]
Also, I didn't find any mention in the changelog https://github.com/sebastianbergmann/phpunit/blob/main/ChangeLog-10.0.md

**Comment by sebastianbergmann** [comment]
> Also, I didn't find any mention in the changelog https://github.com/sebastianbergmann/phpunit/blob/main/ChangeLog-10.0.md

It is in the ChangeLog for php-code-coverage.

**Comment by sebastianbergmann** [comment]
> I believe the docs need an update then? They still mention phpdbg https://phpunit.readthedocs.io/en/10.0/code-coverage-analysis.html

The documentation has not been updated for PHPUnit 10 yet.

**Comment by acelaya** [comment]
> It is in the ChangeLog for php-code-coverage.

Maybe some kind of referencing would make sense? Updating to php-code-coverage:10 is a side effect of PHPUnit 10, not something done on purpose, so it's not obvious for the end user who's following the changelog of the tool that he/she is actively updating.

**Comment by sebastianbergmann** [comment]
> Maybe some kind of referencing would make sense? Updating to php-code-coverage:10 is a side effect of PHPUnit 10, not something done on purpose, so it's not obvious for the end user who's following the changelog of the tool that he/she is actively updating.

https://github.com/sebastianbergmann/phpunit/commit/fd7f8e9597712a53776a90958f5fc85600ac2cfd
