### ISSUE TITLE
Testsuites are duplicated

### ISSUE THREAD

**Issue by keithbrink** [sebastianbergmann/phpunit#5189]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.0.07
| PHP version         | 8.1.13
| Installation Method | Composer

#### Summary

In PHPUnit 9, you could have nested test suites configured:

```
<testsuite name="Unit.App">
      <directory suffix="Test.php">./tests/Unit/App</directory>
</testsuite>
<testsuite name="Unit.App.Models">
      <directory suffix="Test.php">./tests/Unit/App/Models</directory>
</testsuite>
```

Running PHPUnit would run the tests for all the test suites, but each test would only run once.

Now, in version 10, each test suite seems to be handled individually, so it will run all the tests inside Unit/App, and then run all the tests inside Unit/App/Models, so the tests for Unit/App/Models will be run twice.

#### Current behavior

Tests inside of nested test suites are run multiple times.

#### How to reproduce

Use the above XML configuration with a test inside Unit/App/Models - the test will run twice when running PHPUnit.

#### Expected behavior

The test will run once.

**Comment by sebastianbergmann** [comment]
I do not see a bug here, this works as intended.

**Comment by keithbrink** [comment]
For anyone else that comes across this, you can use the `defaultTestSuite` attribute to only run a single test suite by default that runs all your tests while not running the rest of the test suites.
