### ISSUE TITLE
Error when using same method with different arguments

### ISSUE THREAD

**Issue by carlospauluk** [sebastianbergmann/phpunit#5190]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.6.3
| PHP version         | 8.1.14
| Installation Method | Composer

#### Summary

When I use the pattern:
"$mock->method('thatMethod')->with($arg1, $arg2)->willReturn('X')"
and then...
"$mock->method('thatMethod')->with($arg3, $arg4)->willReturn('Y')"

I am getting the error "Failed asserting that two variables reference the same object".

#### Current behavior

The current (buggy) behavior is that PHPUnit should realize that I'm using different arguments, but intead, InvocationHandler after pass through "$match->matches($invocation)", gives me an exception on "$value = $match->invoked($invocation);".

#### How to reproduce

I created a project https://github.com/carlospauluk/SameMethodWithDifferentsArgsTest . Just download, composer install and run ./vendor/bin/phpunit tests

#### Expected behavior

PHPUnit should realize that it's not the same invocation, since I'm using a different pair of arguments.

I've read the docs on https://phpunit.readthedocs.io/en/9.5/test-doubles.html#test-doubles-mock-objects-tables-matchers, but can't find if this is a bug or not. Maybe I'm the one missing something.

Thanks

**Comment by carlospauluk** [comment]
I tried to simplify, without using objects, only strings and ints. Same result:

```
<?php

namespace App\Tests;

use PHPUnit\Framework\TestCase;

class SameMethodWithDifferentsArgsTest extends TestCase
{

    function testSameMethodWithDifferentsArgs()
    {

        $mockedCompetitionRepository = $this->createMock(CompetitionRepository::class);

        $mockedCompetitionRepository
            ->method('findPosition')
            ->with('abc', 123)
            ->willReturn(1);

        $mockedCompetitionRepository
            ->method('findPosition')
            ->with('def', 456)
            ->willReturn(2);

        $processor = new CompetitionProcessor($mockedCompetitionRepository);

        $check1 = $processor->checkAthlete('abc', 123);
        $this->assertLessThan(11, $check1);
        $check2 = $processor->checkAthlete('def', 456);
        $this->assertLessThan(11, $check2);
    }


}


class CompetitionProcessor
{

    private CompetitionRepository $repository;

    public function __construct(CompetitionRepository $repository)
    {
        $this->repository = $repository;
    }

    public function getRepository(): CompetitionRepository
    {
        return $this->repository;
    }

    public function checkAthlete($competition, $athlete): int
    {
        $position = $this->repository->findPosition($competition, $athlete);
        return $position;
    }

}

class CompetitionRepository
{

    public function findPosition($competition, $athlete): int
    {
        return 0;
    }

}

```


Expectation failed for method name is "findPosition" when invoked zero or more times
Parameter 0 for invocation App\Tests\CompetitionRepository::findPosition('abc', 123): int does not match expected value.
Failed asserting that two strings are equal.
Expected :'def'
Actual   :'abc'

**Comment by sebastianbergmann** [comment]
You should use `willReturnMap()` for your use case:

```php
<?php declare(strict_types=1);
use PHPUnit\Framework\TestCase;

interface I
{
    public function m(int $x, int $y): int;
}

final class Test extends TestCase
{
    public function testOne(): void
    {
        $i = $this->createStub(I::class);
        
        $i->method('m')
          ->willReturnMap(
            [
                [1, 2, 3],
                [4, 5, 6],
            ]
        );

        $this->assertSame(3, $i->m(1, 2));
        $this->assertSame(6, $i->m(4, 5));
    }
}
```

It looks like you do not need a mock object, just a test stub, as you are not configuring any expectations. This is why I used `createStub()` instead of `createMock()` in the example above.

**Comment by carlospauluk** [comment]
All right, thank you Sebastian. Do you think we could change it to a more clean code in the future?
