### ISSUE TITLE
Display PHPUnit deprecations when TestDox output is used

### ISSUE THREAD

**Issue by adamcameron** [sebastianbergmann/phpunit#5198]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.0.7
| PHP version         | 8.2.2
| Installation Method | Composer

#### Summary

Deprecations are mentioned in the results summary when `testdox=true` in `phpunit.xml.dist`, but the list of what they are is not emitted. If I set `testdox=false` then the list is emitted as I would expect:

```
There were 4 PHPUnit deprecations:

1) my\namespace\test\SomeTest::testThis
Data Provider method my\namespace\SomeTest::provideForThisTests() is not static

/var/www/tests/SomeTest.php:42

[etc for three other cases of the same deprecation]
```

#### Current behavior
Deprecations mentioned:

```
Tests: 83, Assertions: 219, Failures: 1, Warnings: 1, Deprecations: 4, Skipped: 1.
```

But no detailed listing.

#### How to reproduce

Have a data provider that is not static.
Set `testdox=true` in `phpunit.xml.dist`
Run test using that DP
Note that no deprecation details are displayed

#### Expected behavior

The list of deprecation details should be displayed whether `testdox=true` or`testdox=false`

**Comment by sebastianbergmann** [comment]
I understand that you think this is a bug because PHPUnit does not behave as you expect it to behave. However, the current behaviour is the intended one: I did not want to "clutter" the TestDox output with deprecations.

I now think that deprecations coming from PHPUnit should also be displayed in TestDox output.

**Comment by adamcameron** [comment]
Thanks for the quick feedback on this. NB: now that I know how to get the feedback (and the deprecations dealt with: my bad!) it's not a significant concern for me. Perhaps a note in the docs might help ppl understand what's currently going on?

Cheers for all your hard work pal.

**Comment by odan** [comment]
I have a similar issue in this phpunit test method:

```php
// ...
$response = $this->app->handle($request);
```

Output: 

```
OK, but some tests have issues!
Tests: 10, Assertions: 32, Deprecations: 1.
```

When I remove this line, the deprecation warning is gone. This happens only in phpunit 10.
Is there a way to get more details about this deprecation issue? Is this a bug in phpunit 10?

**Comment by sebastianbergmann** [comment]
> Is there a way to get more details about this deprecation issue?

Please do not update to a new version, a new major version no less, without reading the [ChangeLog](https://github.com/sebastianbergmann/phpunit/blob/10.0.0/ChangeLog-10.0.md#added). You are looking for `--display-deprecations`.

**Comment by odan** [comment]
Ok, thanks for pointing that out. In my specific case, it was this warning:

```
Since symfony/validator 6.2: The "loose" mode is deprecated. The default mode will be changed to "html5" in 7.0.
```

This is a really nice feature. Thanks :-)

**Comment by sneakyvv** [comment]
> I understand that you think this is a bug because PHPUnit does not behave as you expect it to behave. However, the current behaviour is the intended one: I did not want to "clutter" the TestDox output with deprecations.
> 
> I now think that deprecations coming from PHPUnit should also be displayed in TestDox output.

Does the same logic apply to why Errors, Warnings etc are not shown when using `--testdox`?

The errors (e.g. `TypeError`) are shown in my config if I run phpunit without the `--testdox` option.

I might be using that option outside of its intent, but I like the verbosity it gives (listing up each test with a ✔or ✘ in front of them) over the default progress indicator. Now there's seems to be no way debug those Errors without changing my composer script every time, or is there another way?

**Comment by adamcameron** [comment]
Thanks for addressing this, @sebastianbergmann :-)

**Comment by bizmate** [comment]
My understanding based on the issues,also https://github.com/sebastianbergmann/phpunit/issues/5198 and comments linked to this is that now phpunit should actually show deprecation messages even when testDox is `true``   however they are still hidden for me even if using the last version 10.1.3 and using all the configurations or command line options to indeed show the deprecation messages. 
Here is a self contained example that shows this error. I did not open another ticket to ensure I am not adding anything redundant so please let me know if you think I missed something.

https://github.com/bizmate/phpunittest

**Comment by zolex** [comment]
it works as follows with testdox and deprecation details:

```
<phpunit displayDetailsOnTestsThatTriggerDeprecations="true">
  <source ignoreSuppressionOfDeprecations="true">
    ...
  </source>
</phpunit>
```
