### ISSUE TITLE
`TestCase::setLocale()` resets `LC_ALL` locale without respecting format

### ISSUE THREAD

**Issue by SiebelsTim** [sebastianbergmann/phpunit#5200]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | main, 9.6.3
| PHP version         | 8.1
| Installation Method | Composer 

#### Summary

When using `TestCase::setLocale` in combination with `\LC_ALL`, PHPUnit does not reset the locale properly.
In the worst case, it throws a warning which stops the test:

> setlocale(): Specified locale name is too long

#### Current behavior

Here, PHPUnit saves the currently used locale with `setlocale($category, 0)`.

https://github.com/sebastianbergmann/phpunit/blob/e00f0fe9220172ca867b2a3ff0bc2b291d07dfc3/src/Framework/TestCase.php#L1080

Then, it tries to reset the locale based on what was saved.

https://github.com/sebastianbergmann/phpunit/blob/e00f0fe9220172ca867b2a3ff0bc2b291d07dfc3/src/Framework/TestCase.php#L1790

However, when we use `\LC_ALL` and it contains something other than `C`, `setlocale(\LC_ALL, 0)` returns a list of key-value pairs separated by semicolons. 

https://3v4l.org/BNNQu

Therefore, PHPUnit tries to reset the locale for `\LC_ALL` with an invalid value. 

#### How to reproduce

```php
class MyTest extends TestCase {
  function testStuff(): void {
    setlocale(\LC_NUMERIC, 'en_US.utf8'); // To get a list of key-value pairs

    $this->setLocale(\LC_ALL, 'en_US.utf8');
  }
}
```

#### Expected behavior

No error. 
Locale reset to the previous value.

**Comment by sebastianbergmann** [comment]
When you `master` you mean `main`, I assume. So the problem exists in both PHPUnit 9.6 and PHPUnit 10.0. Correct?

**Comment by sebastianbergmann** [comment]
Thank you for reporting this issue. However, I am afraid that I won't be able to dedicate time to debugging/fixing it. I will, of course, review and consider a pull request that addresses this.

Here is why I am reluctant to look into this: I am considering to deprecate functionality such as `TestCase::setLocale()` in a future release, and then remove it in the next major version after that. I consider this functionality to be "niche" as I have not seen used it being used so far.

**Comment by sebastianbergmann** [comment]
The `TestCase::setLocale()` method is deprecated and scheduled for removal, see #5216 for details.
