### ISSUE TITLE
Exceptions raised in TestCase::tearDown() are not handled correctly

### ISSUE THREAD

**Issue by adalessa** [sebastianbergmann/phpunit#5210]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.0.7
| PHP version         | 8.2.2
| Installation Method | Composer

#### Summary

Any exception thrown during the tear down is not reflected as an error on the test result nor the test is mark as failed.
I detected this due the use of the tear down to perform the check for Mockery with the `Mockery::close()` even when I expected the test to fail, the test is still passing which is wrong. After investigating detected that is not a mockery issue since is throwing the exception as expected but phpunit is not reporting the error.

#### Current behavior

Test are passing even when during the `tearDown` of the test an exception is throw.

#### How to reproduce

Create a simple test which during the tear down throw an exception
```php
    public function test_it_should_fail(): void
    {
        $this->assertTrue(true);
    }

    protected function tearDown(): void
    {
        throw new \Exception('test');
    }

```

#### Expected behavior

The tests should fail with the message provided by the exception.

**Comment by sebastianbergmann** [comment]
I can reproduce this:

#### `Test.php`
```php
<?php declare(strict_types=1);
use PHPUnit\Framework\TestCase;

final class Test extends TestCase
{
    public function testOne(): void
    {
        $this->assertTrue(true);
    }

    protected function tearDown(): void
    {
        throw new \Exception('test');
    }
}
```
#### PHPUnit 10.0.7
```
PHPUnit 10.0.7 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.2.3

.                                                                   1 / 1 (100%)

Time: 00:00.076, Memory: 6.00 MB

OK (1 test, 1 assertion)
```
#### PHPUnit 9.6.3
```
PHPUnit 9.6.3 by Sebastian Bergmann and contributors.

E                                                                   1 / 1 (100%)

Time: 00:00.020, Memory: 6.00 MB

There was 1 error:

1) Test::testOne
Exception: test

/home/sb/Test.php:13

ERRORS!
Tests: 1, Assertions: 1, Errors: 1.
```

By the way: `tearDown()` should only be used to clean up after a test. You probably want to use the `assertPostConditions()` method instead for your use case.

**Comment by adalessa** [comment]
Thanks for the quick response. I understand the point of using `assertPostConditions` I have seen the use of the `teardown` is recommended on the mockery documentation and also is implemented in this way in Laravel. I of course understand that is not up to phpunit to determine how others will use it, I am just providing context of what I found during the investigation of this issue.
