### ISSUE TITLE
Make `TestCase` methods `protected` that should have been `protected` all along

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#5213]
* `any()` (should also not be static)
* `never()` (should also not be static)
* `atLeast()` (should also not be static)
* `atLeastOnce()` (should also not be static)
* `once()` (should also not be static)
* `exactly()` (should also not be static)
* `atMost()` (should also not be static)
* `returnValue()` (should also not be static)
* `returnValueMap()` (should also not be static)
* `returnArgument()` (should also not be static)
* `returnCallback()` (should also not be static)
* `returnSelf()` (should also not be static)
* `throwException()` (should also not be static)
* `onConsecutiveCalls()` (should also not be static)
* `getActualOutputForAssertion()`
* `expectOutputRegex()`
* `expectOutputString()`
* `expectException()`
* `expectExceptionCode()`
* `expectExceptionMessage()`
* `expectExceptionMessageMatches()`
* `expectExceptionObject()`
* `expectNotToPerformAssertions()`
* `getMockBuilder()`

**Comment by InvisibleSmiley** [comment]
The fact that some of the methods are not static anymore did not make it to the changelog.

It's not a big deal (I don't mind the change) but I wonder what the reasoning behind that was. Seems random to me. Care to explain?

**Comment by allentje** [comment]
> The fact that some of the methods are not static anymore did not make it to the changelog.
> 
> It's not a big deal (I don't mind the change) but I wonder what the reasoning behind that was. Seems random to me. Care to explain?

I agree. It would have been great to have had these changes referenced in the changelog for more awareness.
