### ISSUE TITLE
Deprecate `TestCase::iniSet()`

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#5214]
- soft deprecation in PHPUnit 10.3 (add `@deprecated` annotation to the method declaration)
- deprecation in PHPUnit 11 (using the method will trigger a deprecation)
- removal in PHPUnit 12

**Comment by derrabus** [comment]
What is the recommended course of action for a codebase that uses this feature currently?

**Comment by sebastianbergmann** [comment]
Use `ini_get()` to get the current value, use `ini_set()` to set the value you need, use `ini_set()` to restore.

**Comment by derrabus** [comment]
Thank you!
