### ISSUE TITLE
Add `assertObjectHasProperty()` and `assertObjectHasNotProperty()`

### ISSUE THREAD

**Issue by jasverix** [sebastianbergmann/phpunit#5220]
The assertObjectHasAttribute() is deprecated because the word "attribute" means something different in the PHP world now. But it was deprecated without any replacement, stating that it is bad code causing this assertion, one should use classes etc instead.

The problem is that I am using PhpUnit to unit-test my JSON API, and I cannot see a replacement for just checking the JSON structure. Of course, `assertTrue(property_exists())` works, but the error message yielded is not nearly as good as assertObjectHasAttribute was.

Can we consider making assertObjectHasProperty()? That name will never be wrong, because it is the exact same word as in property_exists().

**Comment by sebastianbergmann** [comment]
I think this can be done, but it should target `main` (which will become PHPUnit 10.1).

**Comment by westerp** [comment]
So the solution is to downgrade to 9.6.0 as all minor updates after that breaks since AFAIK there is no way to supress this ans it fails the tests.

**Comment by stronk7** [comment]
Yeah, **if the warnings were backported to 9.6.x (by #5160).... then the new methods should be also available there**, so cases can be fixed in 9. Without the methods... the warnings are just useless noise and only solutions are:
- Or you stay with 9.6.0 (before the warnings were added).
- Or you convert to interim `assertTrue(property_exists(....))` or implement them as custom method ... or some other hack.

Both far from ideal, I'd say, sigh. Ciao :-)

**Comment by raziel057** [comment]
In my mind the methods should be added from same release the deprecation have been added to provide an upgrade path. It's not always possible to update to phpunit 10 (if you are using the symfony/phpunit-bridge for example) you are stuck on phpunit 9.6.x.

@sebastianbergmann I can create a PR that targets the 9.6 branch if you are agree with that.

**Comment by sebastianbergmann** [comment]
> I can create a PR that targets the 9.6 branch if you are agree with that.

I would like to avoid changing PHPUnit 9. You can use [yoast/phpunit-polyfills](https://github.com/Yoast/PHPUnit-Polyfills/) to work around this issue.

**Comment by sebastianbergmann** [comment]
@jrfnl Would your polyfills have a problem if PHPUnit 9.6 would get `assertObjectHasProperty()` and `assertObjectHasNotProperty()`? If not then I would backport them. It's the least I can do to remedy this mess I created :-(

**Comment by jrfnl** [comment]
> @jrfnl Would your polyfills have a problem if PHPUnit 9.6 would get `assertObjectHasProperty()` and `assertObjectHasNotProperty()`? If not then I would backport them. It's the least I can do to remedy this mess I created :-(

@sebastianbergmann Shouldn't be a problem at all. The autoloader does a check for the methods before loading the polyfill.
Let me know if you do/have done the backport and I'll run the tests just to be sure, but I don't expect any problems (and if there are any, I'll release a patch version).

https://github.com/Yoast/PHPUnit-Polyfills/blob/c758753e8f9dac251fed396a73c8305af3f17922/phpunitpolyfills-autoload.php#L338-L353

**Comment by sebastianbergmann** [comment]
@jrfnl Thank you!

**Comment by jrfnl** [comment]
@sebastianbergmann FYI: I've just released [PHPUnit Polyfills 1.1.0](https://github.com/Yoast/PHPUnit-Polyfills/releases/tag/1.1.0), which backports the polyfill for these methods to the 1.x (PHPUnit 4.x - 9.x) series.
As I expected, PHPUnit Polyfills 2.x (PHPUnit 5.x - 10.x) is fine, just needed a couple of test tweaks.

**Comment by raziel057** [comment]
@sebastianbergmann @jrfnl Thanks for the consideration of this topic an the solution.
