### ISSUE TITLE
PHPUnit\Framework\TestFailure Class is missing in version 10

### ISSUE THREAD

**Issue by MiroslavRusev** [sebastianbergmann/phpunit#5227]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.0.9
| PHP version         | 8.1.16
| Installation Method | Composer / PHAR

#### Current behavior

 When using assertions in my class, if the assertion is false the error above is thrown. Comparing different PHPUnit versions and checking the code in /Testwork/Exception/Stringer/PHPUnitExceptionStringer.php line 38 seems that the problem is that TestFailure.php file is completely missing in version 10 - https://github.com/sebastianbergmann/phpunit/blob/9.6.3/src/Framework/TestFailure.php

#### How to reproduce

Use for example Assertions::assertEquals($val1,$val2) and provide different values for val1 and val2

#### Expected behavior

 Not throwing php fatal error and instead returning formatted response like before.

**Comment by sebastianbergmann** [comment]
The class was removed, there is no bug here.

**Comment by MiroslavRusev** [comment]
Thanks for the answer, I just didn't see it in - https://github.com/sebastianbergmann/phpunit/blob/main/ChangeLog-10.0.md
