### ISSUE TITLE
CodeCoverageIgnore attribute adds a dependency on PHPUnit to production code

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#5235]
I wrote in https://phpc.social/@sebastian/109912412209293923:

> It only occurred to me the other day that implementing the CodeCoverageIgnore attribute might have been a bad idea: it adds a dependency on PHPUnit to production code.

To which @ramsey replied in https://phpc.social/@ramsey/109912775638797532:

> I noticed that dependency while I'll was working through this earlier today. Since it's an attribute that's not being used, I think it would just be ignored, so not having PHPUnit in production wouldn't hurt anything. The only problem is if something else tries to iterate over attributes on a method/class and instantiate them.

We could move [all attributes](https://github.com/sebastianbergmann/phpunit/tree/10.0.11/src/Framework/Attributes) to a separate package and have PHPUnit depend on this package. If you use the `CodeCoverageIgnore` attribute in your production code (and have production code that looks at attributes of your production code) then you need to explicitly add this separate package as a regular dependency to your project (`require`, not `require-dev`, if you manage your dependencies with Composer). This should be safe/simple to do as all attributes are self-contained and immutable without any dependency on other parts of PHPUnit's internals.

We could deprecate `CodeCoverageIgnore` and remove it later and only support `@codeCoverageIgnore*` annotations for use in production code comments.

**Comment by sebastianbergmann** [comment]
@crell wrote in https://phpc.social/@Crell/109912986199999912:

> Yeah, Attributes are designed to degrade gracefully. Unless someone does something dumb like try to instantiate all attributes unconditionally, it shouldn't cause an issue.

**Comment by spriebsch** [comment]
Some thoughts:

We do not put the information "this code is tested by test x" into the production code. We put this information into the test, where we say "this test tests production code x" by using CoversClass or UsesClass.

So why would we put the information "this code is deliberately not tested" (which essentially is what CodeCoverageIgnore says) into the production code, and not into the tests?

I'm thinking some kind of "ignore this class or method for code coverage" attribute in the test might work. Yes, specifying individual lines to ignore would be a tad ugly, but if we are honest, then putting everything to be ignored into a separate method has always been a best practice that we just never made explicit.

As always, I'm not into the implementation, but I have a gut feeling that putting that information into the tests would make it much easier to report/not report and reason about coverage-ignored code.

**Comment by sebastianbergmann** [comment]
> specifying individual lines to ignore would be a tad ugly

Not just ugly, it would be not feasible: every time the code to be ignored changes line numbers, the information in the test(s) has to be updated.

**Comment by sebastianbergmann** [comment]
> I have a gut feeling that putting that information into the tests would make it much easier to report/not report and reason about coverage-ignored code

I assume what you mean by "putting that information into the tests" is putting that information into one central place, most likely into the XML configuration file. Just to be clear: we are not talking about putting this information as metadata to each and every test.

**Comment by spriebsch** [comment]
To make clearer what my above statement only hinted at: I'd actually suggest to drop the "ignore specific lines for coverage" feature altogether, and just offter "ignore this class for coverage" and possibly "ignore this method for coverage"  features.

**Comment by sebastianbergmann** [comment]
> To make clearer what my above statement only hinted at: I'd actually suggest to drop the "ignore specific lines for coverage" feature altogether, and just offter "ignore this class for coverage" and possibly "ignore this method for coverage" features.

Yes, this makes sense. We will also need "ignore this function for coverage" and maybe "ignore this file for coverage" as well as "ignore this directory for coverage". However, the latter two could be achieved with existing functionality by simply excluding files/directories from code coverage altogether.

**Comment by spriebsch** [comment]
> I assume what you mean by "putting that information into the tests" is putting that information into one central place, most likely into the XML configuration file. Just to be clear: we are not talking about putting this information as metadata to each and every test.

I actually think it shoud be sufficient to put the information into *one* test as an attribute similar to CoversClass.

**Comment by sebastianbergmann** [comment]
> I actually think it shoud be sufficient to put the information into one test as an attribute similar to CoversClass.

While that would technically be possible, I think it's unintuitive. Putting this information into the XML configuration makes much more sense to me.

**Comment by M1ke** [comment]
I agree, it seems strange that a test would say "this test doesn't cover this code" because that's true of all tests for most code except what is covered. Other tests may well cover the code in question. So I can see why inline in the code made sense, but so does central configuration.

**Comment by sebastianbergmann** [comment]
Here is what I think we should do:

- Add a warning to the documentation of the `CodeCoverageIgnore` attribute about the issue described in this ticket
- Implement `IgnoreClassForCodeCoverage`, `IgnoreMethodForCodeCoverage`, and `IgnoreFunctionForCodeCoverage` attributes that can be used on test classes (PHPUnit 10.1)
- When at least one test class has a `IgnoreClassForCodeCoverage`, `IgnoreMethodForCodeCoverage`, or `IgnoreFunctionForCodeCoverage` attribute then the specified code unit will be ignored for code coverage (PHPUnit 10.1)
- Deprecate the `@codeCoverageIgnore*` annotations and the `CodeCoverageIgnore` attribute that are currently supported in production code (PHPUnit 10.1)
- Remove support for the `@codeCoverageIgnore*` annotations and the `CodeCoverageIgnore` attribute (PHPUnit 11)
- Ignoring code for code coverage with line granularity will no longer be supported once support for the `@codeCoverageIgnore*` annotations has been removed (PHPUnit 11)

**Comment by wouterj** [comment]
Attributes are never dependencies, but instead they are metadata like annotations.

The whole attribute API is designed around this, with the explicit method call to initialize a single attribute and getters based on FQCN instead of instances.

It of course can still make sense to say "I want to do something about adding testing metadata to code", but "we're adding a prod dependency" should not be the reason as PHPUnit isn't adding one 😉
