### ISSUE TITLE
Remove support for the `@codeCoverageIgnore` annotation and the `CodeCoverageIgnore` attribute

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#5238]
Follows https://github.com/sebastianbergmann/phpunit/issues/5235#issuecomment-1441559663.

- [ ] Remove (support for) `CodeCoverageIgnore` attribute
- [ ] https://github.com/sebastianbergmann/php-code-coverage/issues/1006
- [X] Keep `@codeCoverageIgnore*` inline annotations for ignoring lines from code coverage

**Comment by anomiex** [comment]
Regarding the intended replacement for the feature being removed here,

> When at least one test class has a `IgnoreClassForCodeCoverage`, `IgnoreMethodForCodeCoverage`, or `IgnoreFunctionForCodeCoverage` attribute then the specified code unit will be ignored for code coverage (PHPUnit 10.1)

This "spooky action at a distance" seems like a poor design. One test class somewhere has one of these attributes and the referenced code is globally ignored for coverage?

If you really don't want to support the inline comments anymore, perhaps you should remove coverage ignoring entirely and recommend people have PHPUnit write the coverage data to a machine-readable format and use some more capable post-processor that still understands the inline comments to generate the report.

**Comment by sebastianbergmann** [comment]
Superseded by #5513.
