### ISSUE TITLE
Deprecate `TestCase::getMockForTrait()`

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#5243]
PHPUnit can automatically generate test stubs and mock objects (test doubles) based on interfaces and classes.

For quite a while, PHPUnit has offered the `createStub()` and `createMock()` methods for creating test stubs and mock objects with best practice defaults. Furthermore, alternatives such as `getMockForTrait()` exist, but not all of them offer the same clear separation between test double and mock object. For instance, no method named `getStubForTrait()` exists. Such an inconsistency can lead to confusion.

The `getMockForTrait()` method returns a mock object for an otherwise empty class that uses a specified trait. All abstract methods of the given trait are mocked. This allows for testing the concrete methods of a trait.

Having to use `getMockForTrait()` to test something is almost always a code smell: something is not quite right with the software design of the system-under-test.

To promote better software design, improve the readability of test code, and to reduce complexity inside PHPUnit's test double functionality, `TestCase::getMockForTrait()` will be deprecated and then removed:

- soft deprecation in PHPUnit 10.1 (add `@deprecated` annotation to the method declaration)
- deprecation in PHPUnit 11 (using the method will trigger a deprecation)
- removal in PHPUnit 12

**Comment by MegaChriz** [comment]
To convert existing tests without requiring a redesign of your code, adding a class that implements the trait and mock that seems to work.

Before:
```php
namespace MyProject\Tests;

use PHPUnit\Framework\TestCase;

class MyTest extends TestCase {

  public function test() {
    $mock = $this->getMockForTrait('\MyProject\MyTrait');
  }

}
```
After:
```php
namespace MyProject\Tests;

use MyProject\MyTrait;
use PHPUnit\Framework\TestCase;

class MyTest extends TestCase {

  public function test() {
    $mock = $this->createMock(MyTraitMock::class);
  }

}

/**
 * Mock for MyTrait.
 */
class MyTraitMock {

  use MyTrait;

}
```

**Comment by ralflang** [comment]
I think createMock won't like being handed an anonymous class. It wants a string class name.

**Comment by XedinUnknown** [comment]
What @ralflang is pointint out is exactly the problem: I don't want to add unnecessary and named things to my application, just to make it play nice with the unit testing framework. IMHO the latter should get out of the way until it's necessary - like a good VCS.

My solution (from [here](https://github.com/Dhii/services/pull/23/changes#diff-40289d70d51f77d63157b630ed17b451380692fec8e25f22d87535774c97641f)):

```php
class ClassBuilder
{
    /** @var ?class-string  */
    protected ?string $extends = null;
    /** @var array<interface-string> */
    protected array $implements = [];
    /** @var array<trait-string>  */
    protected array $uses = [];

    /**
     * @param class-string $classNamePrefix
     */
    public function __construct(
        protected string $classNamePrefix = 'Class_',
        protected bool $isAutoload = false,
    ) {
    }

    public function createClass(): string
    {
        $className = $this->createUniqueClassName($this->extends ? (string) $this->extends : $this->classNamePrefix);
        $classCode = $this->buildClassCode($className, $this->extends, $this->implements, $this->uses);
        eval($classCode);

        return $className;
    }

    public function __toString(): string
    {
        return $this->createClass();
    }

    /**
     * @param ?class-string $extends
     */
    public function withExtends(?string $extends = null): static
    {
        $that = clone $this;
        $that->extends = $extends;

        return $that;
    }

    /**
     * @param array<interface-string> $implements
     */
    public function withImplements(array $implements = []): static
    {
        $that = clone $this;
        $that->implements = $implements;

        return $that;
    }

    /**
     * @param array<trait-string> $uses
     */
    public function withUses(array $uses = []): static
    {
        $that = clone $this;
        $that->uses = $uses;

        return $that;
    }

    /**
     * @param class-string $className
     * @param class-string|null $extends
     * @param array<interface-string $implements
     * @param array<trait-string> $uses
     */
    protected function buildClassCode(
        string $className,
        ?string $extends = null,
        array $implements = [],
        array $uses = [],
    ) {
        $extendsClause = !is_null($extends)
            ? "extends $extends"
            : '';
        $implementsClause = count($implements)
            ? sprintf('implements %1$s', implode(', ', $implements))
            : '';
        $useClause = implode(' ', array_map(fn(string $fqcn) => "use $fqcn;", $uses));

        return "class $className $extendsClause $implementsClause { $useClause }";
    }

    /**
     * Creates a unique classname.
     */
    protected function createUniqueClassName(string $prefix = '', bool $isAutoload = false): string
    {
        $prefix = trim($prefix);
        $prefix = empty($prefix) ? 'Class_' : $prefix;

        $nameExists = fn(string $name) => class_exists($name, $isAutoload)
            || interface_exists($name, $isAutoload)
            || trait_exists($name, $isAutoload)
            || enum_exists($name, $isAutoload);

        do {
            $className = uniqid($prefix);
        } while ($nameExists($className));

        return $className;
    }
}
```

```php
// In your test
$mock = $this->getMockBuilder((string) (new ClassBuilder())->withUses([MyTrait::class]))->getMock();
```

This class allows you to do much more. For example, let's say you want to throw an exception that implements some interface in your test:

```php
public function testContainerStuff()
{
    $services = [
        'foo' => 'bar',
    ];
    $container = $this->getMockBuilder(ContainerInterface::class)->getMock();

    $container->method('get')
        ->willReturnCallback(function (string $key) use ($services) {
            if (!array_key_exists($key, $services)) {
                throw new ((string) (new ClassBuilder())
                    ->withExtends(Exception::class)
                    ->withImplements([NotFoundExceptionInterface::class])
                )("Service '$key' not found");
            }

            return $services[$key];
        });

    // Throws in compliance with PSR-11
    $this->expectException(NotFoundExceptionInterface::class);
    $container->get('non-existing-key');
}
```

Years ago, when I wondered how PHPUnit works on the inside, I saw codegen logic there, which was responsible for generating all these doubles when you use the Mock Builder. If it's still in there, maybe some of it could be exposed to the test cases (e.g. `TestCase::getClassBuilder(): ClassBuilder`), so that people wouldn't have to solve this problem in userland, over and over again, in every repo they maintain, or have to rely on yet another package just for something that I have always (for 20 years now) felt should be there. That - and [access to "private" members](https://github.com/gmazzap/Andrew).
