### ISSUE TITLE
Make `TestCase` methods `final` that should have been `final` all along

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#5254]
- `runTest()`
- `iniSet()`
- `setLocale()`
- `createStub()`
- `createStubForIntersectionOfInterfaces()`
- `createMock()`
- `createMockForIntersectionOfInterfaces()`
- `createConfiguredMock()`
- `createPartialMock()`
- `createTestProxy()`
- `getMockForAbstractClass()`
- `getMockFromWsdl()`
- `getMockForTrait()`
- `getObjectForTrait()`

**Comment by driesvints** [comment]
I'm begging you not to do this. Laravel very much relies on these methods, especially `runTest` which handles so much of the internal exception throwing: https://github.com/laravel/framework/blob/cc3ccc3d68d112ff6e88eb36314fa8c75592311f/src/Illuminate/Foundation/Testing/TestCase.php#L168

**Comment by sebastianbergmann** [comment]
> I'm begging you not to do this. Laravel very much relies on these methods, especially `runTest` which handles so much of the internal exception throwing: https://github.com/laravel/framework/blob/cc3ccc3d68d112ff6e88eb36314fa8c75592311f/src/Illuminate/Foundation/Testing/TestCase.php#L168

Allowing to override `runTest()` is just "too much". But I am sure that what you need can be accomplished in another way, even if that way is not implemented yet.

Can you explain why you currently override `runTest()`? If that is a use case worth supporting, than I am open to implementing a specific API for it.

**Comment by driesvints** [comment]
Thank you for considering it! For Laravel's HTTP testing we check if there's a latest response:

https://github.com/laravel/framework/blob/cc3ccc3d68d112ff6e88eb36314fa8c75592311f/src/Illuminate/Foundation/Testing/TestCase.php#L175

If that's the case we'll transform the exception to provide more info depending on what type of response it is:

https://github.com/laravel/framework/blob/cc3ccc3d68d112ff6e88eb36314fa8c75592311f/src/Illuminate/Testing/TestResponse.php#L1566-L1593

**Comment by crynobone** [comment]
@sebastianbergmann yes that would be useful. Previously we using `onNotSuccessfulTest` but it no longer exists in PHPUnit 10 and the reason why we need to override `runTest()` at the moment.

**Comment by driesvints** [comment]
@sebastianbergmann yes that would solve this! Thank you 🙂

**Comment by sebastianbergmann** [comment]
> Previously we used `onNotSuccessfulTest` but it no longer exists in PHPUnit 10 and the reason why we need to override `runTest()` at the moment.

`onNotSuccessfulTest()` still exists, but can no longer be (ab)used for this.

**Comment by taylorotwell** [comment]
Reconsider? If your concern with these not being final is people's application's breaking if they override them, create a GitHub saved reply explaining you override those methods at your own risk and any breakages from doing so are not your problem and close the issue?

**Comment by bram-pkg** [comment]
```php
#[Override]
protected function runTest(): mixed
{
    // CI systems like GitHub Actions set the CI environment variable
    if (getenv('CI')) {
        return retry(3, function () {
            return parent::runTest();
        });
    }

    return parent::runTest();
}
```

We were using `runTest()` to provide automatic "retry" functionality to flaky tests while we attempt to fix them.

Do you have any suggestions on what we can override now to have this behaviour? I have dug into the source code of PHPUnit 11 and have not found any methods to override easily to achieve this.

**Comment by roxblnfk** [comment]
I also use `runTest()` in many projects. It seems I'll have to stay on 10.x forever.
Hope this version will support PHP 9 😄

**Comment by zebaroni** [comment]
Yep, same use case here @bram-pkg , hope you guys can reconsider the Final decision.

**Comment by lk77** [comment]
For anyone having issues, you can bypass the final keyword with : https://github.com/dg/bypass-finals

**Comment by roxblnfk** [comment]
Any ideas why the `runTest` method was [made private](https://github.com/sebastianbergmann/phpunit/commit/8f0f8205e3a38675392da55afc573c6bb6a43f4e) in patch [10.5.46](https://github.com/sebastianbergmann/phpunit/releases/tag/10.5.46)?
