### ISSUE TITLE
Improve error message when `proc_open()` is disabled and a test is to be run in a separate process

### ISSUE THREAD

**Issue by mvorisek** [sebastianbergmann/phpunit#5256]
When I run phpunit on https://github.com/PHP-CS-Fixer/PHP-CS-Fixer repo I get:

```
...
.......................................................... 11310 / 31700 ( 35%)
................................
Notice: Undefined variable: pipes in C:\...\forks\PHP-CS-Fixer\vendor\phpunit\phpunit\src\Util\PHP\DefaultPhpProcess.php on line 102

Warning: proc_open() has been disabled for security reasons in C:\...\forks\PHP-CS-Fixer\vendor\phpunit\phpunit\src\Util\PHP\DefaultPhpProcess.php on line 104
Unable to spawn worker process
```

output when `proc_open` function is disabled using `disable_functions` php.ini.

I would expect the test to fail as obviously it cannot run, but no php fatal error/immediate exit.

**Comment by sebastianbergmann** [comment]
Does this happen in both PHPUnit 9 and PHPUnit 10?

**Comment by mvorisek** [comment]
```
.\vendor\phpunit\phpunit\phpunit --version
PHPUnit 9.5.4 by Sebastian Bergmann and contributors
```

**Comment by sebastianbergmann** [comment]
While I agree that this error (c|sh)ould be communicated better, I am reluctant to add `function_exists()` safeguards. IMO, using `disable_functions` in a development environment is an edge case that we should not have to care about.

**Comment by mvorisek** [comment]
I agree, check of `disable_functions` should not be needed, as calling unknown function can be caught: https://3v4l.org/akePA

The current error message is enought to understand the problem quickly, but from this feature request I expect PHPUnit to finish (for some reasons, PHPUnit currently exists in middle of the testing).

**Comment by mvorisek** [comment]
@sebastianbergmann please do not just close this issue without fixing it, as when unhandled, it is hard/time consuming to locate the test that causes the issue
