### ISSUE TITLE
Class "PHPUnit\Util\Annotation\Registry" not found

### ISSUE THREAD

**Issue by haodudecao** [sebastianbergmann/phpunit#5257]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.0.12
| PHP version         | 8.1.13
| Installation Method | Composer / PHAR

#### Summary

when i run phpunit when a test with @runInSeparateProcess ,it report a message :
Error: Class "PHPUnit\Util\Annotation\Registry" not found

#### Current behavior

<img width="486" alt="image" src="https://user-images.githubusercontent.com/34431537/221400585-cb6b3f78-4850-4698-8ed9-fe1c036fc239.png">

<img width="909" alt="image" src="https://user-images.githubusercontent.com/34431537/221400603-891c5479-e21f-4409-971b-b44e1e66a893.png">

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by sebastianbergmann** [comment]
At first glance, it appears that you have different installations of PHPUnit mixed up. The class `PHPUnit\Util\Annotation\Registry` no longer exists in PHPUnit 10 and, obviously, PHPUnit 10 itself does not use this class anymore.

**Comment by haodudecao** [comment]
Thank you.according your reply  I find Laravel 9.* doesn't support PHPUnit 10 .
