### ISSUE TITLE
Do not emit Test\AssertionSucceeded and Test\AssertionFailed events when they do not have subscribers

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#5261]
For instance, in `PHPUnit\Framework\Assert::assertThat()` we have:
```php
Event\Facade::emitter()->testAssertionSucceeded(
    $value,
    $constraint,
    $message,
);
```
The code shown above calls `PHPUnit\Event\DispatchingEmitter::testAssertionSucceeded()` to emit the `PHPUnit\Event\Test\AssertionSucceeded` event.

This is what `PHPUnit\Event\DispatchingEmitter::testAssertionSucceeded()` looked like before c2fcb8f1bec7773ac1d745078ba9eb4570868e11:
```php
public function testAssertionSucceeded(mixed $value, Constraint\Constraint $constraint, string $message): void
{
    $this->dispatcher->dispatch(
        new Test\AssertionSucceeded(
            $this->telemetryInfo(),
            (new Exporter)->export($value),
            $constraint->toString(),
            $constraint->count(),
            $message,
        )
    );
}
```

The `(new Exporter)->export($value)` and `$constraint->toString()` operations are expensive (for (very) complex types, such as large object graphs, for intance). These operations are necessary, though, to ensure that event objects such as `PHPUnit\Event\Test\AssertionSucceeded` are immutable and do not allow subscribers of the respective event to mess with original values.

So far, two performance issues have been reported related to this:

* https://github.com/sebastianbergmann/phpunit/issues/5183
* https://github.com/sebastianbergmann/exporter/issues/18#issuecomment-1446375509

Both of these issues concern the `PHPUnit\Event\Test\AssertionSucceeded` and `PHPUnit\Event\Test\AssertionFailed` events.

Unless `--log-events-text` or `--log-events-verbose-text` is used, PHPUnit itself does not subscribe to either of these two events. They only exist to allow authors of test runner extensions even more insight into how tests are run. This means that by default, the result of the expensive operations mentioned is not used.

PHPUnit's event system only allows subscribers to be registered before the actual tests are run. When we seal the event facade, ie. when we no longer allow subscribers to be registered, we know which events have been subscribed to. We should be able to use this information so that `PHPUnit\Event\DispatchingEmitter` does not emit events that have no subscribers.

When this change is implemented then c2fcb8f1bec7773ac1d745078ba9eb4570868e11 should be reverted.

**Comment by sebastianbergmann** [comment]
I implement a short-term solution in 0e3868b8639c6f058d01ae5bd9127c0cd3dd93af that should be good enough for PHPUnit 10.0.

0e3868b8639c6f058d01ae5bd9127c0cd3dd93af was already reverted in 868ea886714b6f1042f4474ea620b6e2c33660f1 for `main` (what will become PHPUnit 10.1).

**Comment by sebastianbergmann** [comment]
As `Test\AssertionSucceeded` and `Test\AssertionFailed` are the only event objects that are expensive to create, I do not think that we need a generic solution here (and check for every event whether there are subscribers before it is emitted).

**Comment by sebastianbergmann** [comment]
The specific solution for `Test\AssertionSucceeded` and `Test\AssertionFailed` has been implemented in 20dca4ae213a04a8cae849e2c03bffeb36a555d7 for PHPUnit 10.0.

**Comment by sebastianbergmann** [comment]
@davedevelopment @Slamdunk Can you please verify that the current state of `10.0` (still) solves the performance issues you reported? Thank you!

**Comment by Slamdunk** [comment]
@sebastianbergmann I can confirm that https://github.com/sebastianbergmann/phpunit/commit/8ba721f67c61e7cb3126ccb184e9ac872bec5dba is still good at performance level, but I can't find any safeguard clause against  the slowness being reintroduced in the future.
I would expect anything anywhere inside PHPUnit self-tests that tells:

"Hey hey hey, you added a `AssertionSucceededSubscriber` \ `AssertionFailedSubscriber` in the subscribers **default** list, that will kill the performances if you release it! :no_entry_sign: "

**Comment by sebastianbergmann** [comment]
> I can confirm that 8ba721f67c61e7cb3126ccb184e9ac872bec5dba is still good at performance level

Thank you.

> I can't find any safeguard clause against the slowness being reintroduced in the future

I agree that we should add a test that the `DirectDispatcher` does not perform the expensive event object creation when there are no subscribers for the two events in question. Beyond that, I do not think that we need a safeguard.

**Comment by sebastianbergmann** [comment]
> I can confirm this 👏 👍

Thank you.
