### ISSUE TITLE
TeamCityLogger is not showing time, memory and results

### ISSUE THREAD

**Issue by madman-81** [sebastianbergmann/phpunit#5263]
OS: Windows
PHP: 8.1.3
PHPUnit: 10.0.14
Command: C:\"Program Files"\php-8.1.3-Win32-vs16-x64\php.exe C:/Webroot/project/vendor/phpunit/phpunit/phpunit --configuration C:\Webroot\project\phpunit.xml --teamcity

Since version 10, the `--teamcity` options isn't showing the time, memory at the end. 

I noticed PhpStorm was only showing 'Process finished with exit code 0'. Digging in a bit deeper, I noticed that the output comes directly from PHPunit and was missing since the upgrade to version 10. PhpStorm uses the TeamCity output.

When running PHPunit manually on the command line with 9.6.4:
```
//lots of output here

##teamcity[testSuiteFinished name='Features' flowId='19484']

Time: 00:42.940, Memory: 76.00 MB

OK (249 tests, 947 assertions)
```

With 10.0.14
```
// lots of output here

##teamcity[testFinished name='testGetLocationWithCountryCode' duration='25' flowId='21428']
```

Note: Testdox does show time, memory and results at the end

Is this intended behaviour? Or should it perhaps be omitted if the `--no-results` option is used?

If this was intended, is there an option to show the summary at the end so I can still see it if I use PhpStorm for running unit tests?

**Comment by sebastianbergmann** [comment]
This was an intentional change: when TeamCity output is requested then only log messages in TeamCity format should be emitted.

**Comment by madman-81** [comment]
Ok fair enough, but is there a way to restore the output in PhpStorm? What would be needed for that?

**Comment by sebastianbergmann** [comment]
The idea here is to only produce output needed by PhpStorm when `--teamcity` is used. I would assume that PhpStorm can provide you with the information you're interested in.
