### ISSUE TITLE
Remove support for non-integer exception codes in `TestCase::expectExceptionCode()`

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#5273]
Exception code used to be `mixed`, then `int|string`, now they are only `int`. `TestCase::expectException()` still allows `int|string`.

**Comment by oprypkhantc** [comment]
Hey. We use string codes across our codebase and it seems like nothing changed even on `master` of `php-src`. Here's a link: https://3v4l.org/GuhA7/rfc#git.master

```php
<?php

class MyException extends Exception
{
    public function __construct(string $message = "", int $code = 0, ?Throwable $previous = null)
    {
        parent::__construct($message, $code, $previous);

        $this->code = 'my code';
    }
}

var_dump((new MyException)->getCode());
```

outputs `string(7) "my code"`. So technically string exception codes are still supported and even some of the internal exceptions (like `PDOException`) still use string error codes, which makes sense as those are more verbose and easier to understand.

PHP may deprecate string in exception codes, but so far it doesn't seem like that's the case. Is there anything I'm missing here?
