### ISSUE TITLE
Adding PHP 8 polyfills to a testing framework that supports PHP 7.3 is unhelpful

### ISSUE THREAD

**Issue by timhunt** [sebastianbergmann/phpunit#5275]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.26
| PHP version         | 7.3.33 (or 7.4..x)
| Installation Method | Composer

#### Summary

PHPUnit cannot detect errors caused by code running in PHP 7.3 that calls functions that do not exist in PHP 7.3, because it has added a polyfill to the global namespace of functions.

#### Current behavior

I am developing on a codebase that needs to support PHP 7.3 - 8.0. I carelessly wrote some code using str_starts_with (added in PHP 8) and it worked on my local machine (which has PHP 8.0). Forunately, I have unit tests, and when pushed it to github, Github actions ran them with all the PHP versions. The tests passed, so I am good, right? No, PHPUnit has failed to find the bug in my code.

#### How to reproduce

Make a simple test class like:
```php
class StringTestcase extends PHPUnit\Framework\TestCase {
    public function testStrings() {
        $this->assertTrue(str_starts_with('PHPUnit', 'PHP'));
    }
}
```

Run the test with PHP 7.3 or 7.4.

Acutal result: the test passes with all supported PHP versions.

#### Expected behavior

Expected result: the test errors with a undefined function message.

**Comment by sebastianbergmann** [comment]
PHPUnit does not have a polyfill for `str_starts_with()` (or any other polyfill).

**Comment by timhunt** [comment]
Thank you for the speedy response, and sorry to waste your time.

[Just to expalain, in our (Moodle) composer.json we install PHPunit and some other things. It must be one of the other dependencies that is installing symfony/polyfill-php80 (v1.27.0). I am sorry, I should have thought about this before.]
