### ISSUE TITLE
dataProvider annotation rejects previously valid method name style

### ISSUE THREAD

**Issue by Crell** [sebastianbergmann/phpunit#5288]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.0.17
| PHP version         | 8.1.14
| Installation Method | Composer

#### Summary

In PHPUnit 10, the `@dataProvider` annotation got unexpectedly stricter.  Specifically, in previous versions I commonly wrote this:

```php
/**
 * @dataProvider provider()
 */
public function testThing(int $a, int $b) { ... }

public function provider(): iterable { ... }
```

The `()` on the end of the provider method was ignored.  As of v10, it is no longer ignored.  This is going to create... a lot of drudge work changing all of my provider references to remove the ().

Ideally they'd convert to attributes at some point, but annotations are still supported for now and this was an unexpected snag.

#### Current behavior

The code example above gives an error along the lines of:

```
1) Crell\Tutorials\RectangleTest::testThing
The data provider specified for Crell\Tutorials\RectangleTest::testThing is invalid
Method Crell\Tutorials\RectangleTest::negativeSizeRectangleProvider()() does not exist
```

(Note the double `()` in what it thinks is the method name, indicating that v10 thinks the `()` is part of the method name.)

#### How to reproduce

See code example above.

#### Expected behavior

As in v9, the `()` should be stripped off and ignored.  Or if that's not feasible, this would be something to mention in the upgrading docs as it's an unexpected break.

**Comment by Crell** [comment]
Now that's an impressive turnaround!  Thanks, @sebastianbergmann! <3

**Comment by sebastianbergmann** [comment]
Thank you, Larry, for reporting this. I was not aware (anymore) that `@dataProvider method()` was supported and we did not have any tests for that. Now we do :)
