### ISSUE TITLE
Add events for code coverage

### ISSUE THREAD

**Issue by robiningelbrecht** [sebastianbergmann/phpunit#5301]
The new event system allows us to write plugins and react to certain events. Even though we already have a lot of useful events, I think there are still a few missing. To be specific, there are currently no events available for code coverage.

It would be nice to have for example

```php
namespace PHPUnit\Event\CodeCoverage\Started;
namespace PHPUnit\Event\CodeCoverage\Stopped;
namespace PHPUnit\Event\CodeCoverage\ReportProcessed;
...
```
I can think of a lot of useful plugins that could use the code coverage percentage...

**Comment by sebastianbergmann** [comment]
PHPUnit itself does not know anything about code coverage data and the data is currently not held/exposed by php-code-coverage (the library that collects and processes code coverage data) in a way that would support what you propose.

**Comment by robiningelbrecht** [comment]
Too bad, would be very nice. Nevertheless, thanks for putting a lot of your time into this!

**Comment by robiningelbrecht** [comment]
@sebastianbergmann Checked the code, and correct me if I'm wrong, but PHPUnit does know when code coverage started stopped and when the reports have been processed?

Am I missing something here?

```php
namespace PHPUnit\TextUI;

final class Application
{
     public function run(array $argv): int
    {
        ....
        CodeCoverage::instance()->generateReports($printer, $configuration);
    }
}

```

And

```php
namespace PHPUnit\Framework;

final class TestRunner
{
    public function run(TestCase $test): void
    {
        ...
        if ($collectCodeCoverage) {
            CodeCoverage::instance()->start($test);
        }

        ...
        CodeCoverage::instance()->stop(
           $append,
           $linesToBeCovered,
           $linesToBeUsed
        );
    }
}
```

**Comment by sebastianbergmann** [comment]
PHPUnit knows the "when", but not the result(s). I do not see any point in adding events for "code coverage report generation started", "code coverage report generation finished", etc.
