### ISSUE TITLE
Configurarable ErrorLevel supressing configuration for ErrorHandler

### ISSUE THREAD

**Issue by sbuerk** [sebastianbergmann/phpunit#5302]
PHPUnit v10 changed how it handles notices, warnings, errors and
deprecations. Therefore, converting them to exception has been
removed in favour of display/fail options per type. Recently, the
last missing piece for notices and deprecation has been added with:

  #5196: Optionally (fail|stop) on (notice|deprecation) events

PHPUnit v9 (and eventually earlier versions) did not converted
suppressed error levels to exceptions, if the corresponded old
and removed option has been set. With PHPUnit v10, only native
php error level (notices/strict,warnings,deprecated) are not
handled if suppressed using the "@" suppress operator or by
error_reporting() configuration.

User error levels (notices,warnings,deprecation,error) are no
longer suppressable.

It's impossible to have only one defined set, which should be
suppressable AND suppressed state regonized to suite all needs
for framework, packages and applications using PHPUnit to test
things. This **must** be configurable for users of the PHPUnit.

Therefore, adding configuration options to the xml configuration,
which controls the behavior in the `ErrorHandler`, should be added,
for example:

* (bool) errorHandlerIgnoreSuppressedPhpDeprecations [default: true]
* (bool) errorHandlerIgnoreSuppressedPhpNotices [default: true]
* (bool) errorHandlerIgnoreSuppressedPhpWarnings [default: true]
* (bool) errorHandlerIgnoreSuppressedUserDeprecations [default: false]
* (bool) errorHandlerIgnoreSuppressedUserNotices [default: false]
* (bool) errorHandlerIgnoreSuppressedUserWarnings [default: false]

This would give user (packages, projects) some control back to controll
which should be suppressed and which not. Would also help with
3rd Party deprecation strategies (e.g. dotrine/deprecation trigger_error()
etc ...).

**Comment by sebastianbergmann** [comment]
> User error levels (notices,warnings,deprecation,error) are no longer suppressable.

I think the previous behaviour should be restored instead of making the handling of suppressed errors configurable.

Also not that PHPUnit 10.1 introduces the `<source>` XML configuration to configure "the code that you are interested in". This allows you to tell PHPUnit to only act on `E_*` triggered in your `src` directory but not on `E_*` triggered in your `vendor` directory, for instance. With this in mind, do you still think that the handling of suppressed errors should be configurable?

**Comment by sbuerk** [comment]
@sebastianbergmann Thanks for pointing out the new `<source>` option. I tested it out without much success for our constellations.

> I think the previous behaviour should be restored instead of making the handling of suppressed errors configurable.

To be short, for now it would be better to remove the `in_array()` check in the `ErrorHandler` again - and let silenced `E_USER_DEPRECATION` be silenced again.

There is no way to control this otherwise, even with the `<source>` tag. The point is
to disable it for 3rd party code.

Only allowing `E_DEPRECATED` to be silenced, ignoring enforced silenced `E_USER_DEPRECATED` is not a good way, from my point of view (which may be wrong). I would say, that should either be the way around or handling both the same way.

Not sure if this has been done to get the silenced `@trigger_error()` deprecations created by
the MockBuilder, if a `@deprecated` annotation is found for a method, to be detected (and failing if `fail-on-deprecation` is set).

The culprit now is, that 3rd party code which is mocked to test own code, having these
deprecation annotation, are now triggereing deprecations and thus failing. Sure, code
should be refactored to not use deprecated 3rd party code - but there are cases where
this is not possible in a still supported version without beeing breaking to the own
user base. Maybe a option to control this on a per mocked class if a trigger error should
be created or not could be a option.

My proposed but closed pull-request target to make it configurable if silenced E_USER_DEPRECATION should fail or not on a usage way. Maybe I have it overdone 
to let all levels be configurable.

From my point of view I would suggest for now:

* close this issue and pr for now
* reverting the `in_array()` check in the `ErrorHandler` again and let suppressed user deprecations be silenced again (if `@` has been used) - not sure if this could be properly detected if @ is used or E_USER_DEPRECATION is not set as error reporting level.
* rethink the `@deprecation annotation` to silenced `@trigger_error()` in class method mocking (for an option or whatever). 

I have talked with a maintainer team colleague in the open source framework we mainly discovers issues now, and we will provide a full descriptions about what our requirements
for testing are with things in a dedicated issue. So we can sort out piece by piece,
what can be done. Other use-cases may be welcome there also.

At least for the next release. That way we would be able to switch finaly to PHPUnit v10 and having quard in place that own code does not call own deprecated stuff. (non-silenced deprecations) but allowing silenced 3rd party trigger_errors OR let 3rd party classes be mocked without triggering errors.

Beside this, we have also the need to have methods annotated to be `@deprecated` without triggering an `E_USER_DERPECATED` error (not silenced) - but method should be callable, and having mocks to convert it to failing depraction would not be good.

So let me now if it is okay to provide a PR for removing the in_array() in the error handler for now.

As already mentioned, we will come up with a full description of our needs, culprits, how we setup tests (Unit <-> UnitDeprecated and so on) - and are open to discuss ways how it could be archieved.

I'm also open to have some call, mail, chat then to discuss things (quicker), after providing the full needs description. And maybe we could also provide some PR's then for the one or other thing.

This should not be a complaint about your absolutly honorable work, just a try to get somehow togheter. 

The suggestion with the configurable level options which could be configured was a innocent suggestion without being into the internals. Maybe there are other and better ways, instead of adding a full bunch of additional options. Let's discuss that than in a bigger picture.

Our biggest concern was, not beeing able to let deprecation fail. That's included now (**thank you** for this :heart: ). Just not usable because of the @depreaction to silenced `E_USER_DEPRECATED` transformation in mocked classes - own and 3rd party code.

**Comment by sebastianbergmann** [comment]
>     * reverting the `in_array()` check in the `ErrorHandler` again and let suppressed user deprecations be silenced again (if `@` has been used) - not sure if this could be properly detected if @ is used or E_USER_DEPRECATION is not set as error reporting level.

Can you send a PR for that? I am not sure what exactly you mean.

>     * rethink the `@deprecation annotation` to silenced `@trigger_error()` in class method mocking (for an option or whatever).

PHPUnit does not interpret `@deprecated` annotations in any way.

**Comment by sbuerk** [comment]
> Can you send a PR for that? I am not sure what exactly you mean.

Working on it, just created another issue for the PR then.

> PHPUnit does not interpret @deprecated annotations in any way.

That's not true. The `MockBuilder` reads @deprecated docblocks for methods and adds a `@trigger_error($deprectedDocBlockMessage, E_USER_DEPRECATED)` to the mocked method code.

See:

https://github.com/sebastianbergmann/phpunit/blob/fcff1c55669c22708f0370133eaa60bc206fe3df/src/Framework/MockObject/MockMethod.php#L75

https://github.com/sebastianbergmann/phpunit/blob/fcff1c55669c22708f0370133eaa60bc206fe3df/src/Framework/MockObject/Generator/deprecation.tpl#L2

https://github.com/sebastianbergmann/phpunit/blob/fcff1c55669c22708f0370133eaa60bc206fe3df/src/Framework/MockObject/MockMethod.php#L182

In PHPUnit v9 this did not had a effect, because silenced `E_USER_DEPRECATED` errors has been silenced in any circumstances. In v10 `E_USER_*` errors are not silencable at all. That's one extreme to the other. Generally, I would say it's okay that silenced `E_USER_*` should fail - or should be able to fail. On the other hand, I would say converting the `@deprecated` anotation to a ignored silenced `E_USER_DEPRECATED` error is not good at all.

To get all the pieces working peacefull, I guess it's good to revert the silenced/suppress ignore filter for `E_USER_*` .. not finally, just for now.
