### ISSUE TITLE
Show summary only for `--testdox`

### ISSUE THREAD

**Issue by bilogic** [sebastianbergmann/phpunit#5304]
1. If `--testdox` is specified, a failed test will be reported as it fails and also in the summary
2. The result is seeing the a failed test twice
3. For reporting purposes, is it possible to just output the summary?
4. The use case is when examining a github action, it would be clearer and easier to read.

Thank you.

**Comment by sebastianbergmann** [comment]
I am sorry, but I do not understand what you're asking for.

**Comment by bilogic** [comment]
Sure, let me get some outputs to explain. Thank you.

**Comment by bilogic** [comment]
Borrowing this from #5318

![image](https://user-images.githubusercontent.com/946010/235035359-6e19ffb9-250e-4792-ad39-f7f1813c83ef.png)

My point is that 

1. We are seeing the same thing twice (green and red), it increases the cognitive load when trying to understand what happened
2. My request is that, can we have an option to just see the red, i.e. just the failed tests and show the default test output while testing or something less noisy
  ```
  ....EEEIIII...
  ```

Hope it is clearer now. Thank you.

**Comment by Ilyes512** [comment]
> Borrowing this from #5318
> 
> ![image](https://user-images.githubusercontent.com/946010/235035359-6e19ffb9-250e-4792-ad39-f7f1813c83ef.png)
> 
> My point is that
> 
> 1. We are seeing the same thing twice (green and red), it increases the cognitive load when trying to understand what happened
> 2. My request is that, can we have an option to just see the red, perhaps `--testdoxsummary` i.e. just the failed tests and show the default test output while testing or something less noisy
> 
> ```
> ....EEEIIII...
> ```
> 
> Hope it is clearer now. Thank you.

I wish we would see failed tests reported twice. Since PHPUnit 10 it's only reported once as it fails. We had to disable testdox as it became unusable for us.

**Comment by sebastianbergmann** [comment]
PHPUnit 9 is closed for behaviourial changes like that.

**Comment by Minhyme** [comment]
@Ilyes512 I resorted to adding this to my CI
`phpunit --testdox > test ; cat test ; cat test | grep "│\|✘" ; rm test`
It mostly achieves the goal of reporting all the errors at the end in a human readable format.

**Comment by bilogic** [comment]
Why did `--testdox-xml` disappear from PHPUnit 10??
