### ISSUE TITLE
Deprecate `MockBuilder::enableProxyingToOriginalMethods()`, `MockBuilder::disableProxyingToOriginalMethods()`, and `MockBuilder::setProxyTarget()`

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#5307]
See #5240 for details.

- soft deprecation in PHPUnit 10.1 (add `@deprecated` annotation to the method declaration)
- deprecation in PHPUnit 11 (using the method will trigger a deprecation)
- removal in PHPUnit 12

**Comment by sebastianbergmann** [comment]
No replacement is offered for this.

**Comment by itelmenko** [comment]
Why?

**Comment by Arkemlar** [comment]
Yep, why? That's kind of useful thing.
