### ISSUE TITLE
DataProviders (with attributes) DX

### ISSUE THREAD

**Issue by OskarStark** [sebastianbergmann/phpunit#5317]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.0.19
| PHP version         | 8.2.4
| Installation Method | Composer

#### Summary

Better DX for `#[DataProvider(...])` attribute

#### Current behavior

I am currently switching from annotations to attributes and before I used the following annotation quite often:

```php
/**
 * @test
 * @dataProvider fooProvider()
 **/
public function fooIsTrue(): void
{}
```

or

```php
/**
 * @test
 * @dataProvider \App\Tests\Provider\FooProvider::provideFooValues()
 **/
public function fooIsTrue(): void
{}
```

Rewriting this with attributes will look the following:
```diff
-/**
- * @test
- * @dataProvider fooProvider()
- **/
+ #[Test]
+ #[DataProvider('fooProvider')]
public function fooIsTrue(): void
{}
```

and

```diff
+ use App\Tests\Provider\FooProvider;
-/**
- * @test
- * @dataProvider \App\Tests\Provider\FooProvider::provideFooValues()()
- **/
+ #[Test]
+ #[DataProvider(FooProvider::class .'::provideFooValues()')]
public function fooIsTrue(): void
{}
```

I am "complaining" about this part (external DataProviders):
```php
#[DataProvider(FooProvider::class .'::provideFooValues()')]
```

#### Expected behavior

"A better DX", not sure how this can be achieved in an elegant an BC way. I am open for working on a PR, if a conclusion can be found.

Thanks for your time

cc
@localheinz as we talked about this topic
@mvhirsch you may find this interesting, @silasjoisten as well

**Comment by sebastianbergmann** [comment]
What is wrong with `PHPUnit\Framework\Attributes\DataProviderExternal`?

**Comment by OskarStark** [comment]
Oh 😍 
I checked the [documentation](https://docs.phpunit.de/en/10.0/writing-tests-for-phpunit.html#data-providers) and it is missing. I will provide a PR 👍 

Thanks for the feedback

**Comment by sebastianbergmann** [comment]
It is documented [here](https://docs.phpunit.de/en/10.0/attributes.html#dataproviderexternal).

**Comment by ghostwriter** [comment]
https://docs.phpunit.de/en/10.0/attributes.html#dataproviderexternal

**Comment by OskarStark** [comment]
Ok, but as `DataProvider`s and the attribute are more explained on another page. I added a paragraph:
* https://github.com/sebastianbergmann/phpunit-documentation-english/pull/303

**Comment by sebastianbergmann** [comment]
No. I want to avoid nullable parameters as much as possible.
