### ISSUE TITLE
Deprecate `MockBuilder::addMethods()`

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#5320]
To reduce complexity inside PHPUnit's test double functionality, `MockBuilder::addMethods()` will be deprecated and then removed:

- soft deprecation in PHPUnit 10.1 (add `@deprecated` annotation to the method declaration)
- deprecation in PHPUnit 11 (using the method will trigger a deprecation)
- removal in PHPUnit 12

**Comment by g105b** [comment]
In one of my projects, I wanted to use PHPUnit mocks to check that an anonymous function was being called X times. I mocked `stdClass` and used `addMethods()` to add the `__invoke` method, then I could use `MockObject::expects()` to do the checking.

To fix this deprecation message, I've introduced a new class into my tests directory called `MockedCaller`, which does the same thing but more explicitly. Here's an example:

```php
class MockedCaller {
	public function __invoke():void {}
}

class ExampleTest extends MyTestCase {
	public function testAnonFuncIsCalled10Times():void {
		$sut = new MyObject();
// this will pass in a callable to `doSomething10Times` that must be called 10 times with the provided parameters
		$sut->doSomething10Times(self::mockCallable(10, "example param"));
	}
}

class MyTestCase extends TestCase {
	/** @return MockObject|callable */
	protected function mockCallable(int $numCalls = null, ...$expectedParams):MockObject {
		$mock = self::createMock(MockedCaller::class);

		if(!is_null($numCalls)) {
			$expectation = $mock->expects(self::exactly($numCalls))
				->method("__invoke");

			if(!empty($expectedParameters)) {
				foreach($expectedParameters as $p) {
					$expectation->with(self::identicalTo($p));
				}
			}
		}

		return $mock;
	}
}
```

Hope this helps someone!

**Comment by pkly** [comment]
I was wondering, what is the correct way of handling this deprecation/removal?
Calling `onlyMethods` with a method that does not exist produces an exception.

I'm referring to cases where you're mocking an interface which contains a method listed as a phpdoc method for backwards compatibility reasons, and does not exist within the interface itself. I understand it's somewhat of a weird scenario, but still technically valid.

**Comment by LordSimal** [comment]
@pkly We use either an anonymous class like this
```
$entity = new class extends Entity {
    protected function _setName(?string $name): string
    {
        return 'Dr. ' . $name;
    }
};
```
or straight up another class ([inside the TestCase class](https://github.com/cakephp/cakephp/pull/17246/files#diff-74627551f5d8571cc382e41d272d7613aa595d47e59007e49a81403dbc74b8a2R1436-R1441) or [in a separate file](https://github.com/cakephp/cakephp/pull/17246/files#diff-89b1a6d9041ee613207e4d4c13dd1d95e1a57cc8c3ba34c5d3e8fab5894e15ff))

**Comment by derrabus** [comment]
> I'm referring to cases where you're mocking an interface which contains a method listed as a phpdoc method for backwards compatibility reasons, and does not exist within the interface itself.

Declare a new interface that extends that interface and materialize the virtual method.

```php
/**
 * @method void foo(string $a)
 */
interface MyInterface {}

interface MyMockableInterface extends MyInterface
{
    public function foo(string $a): void;
}

$this->createMock(MyMockableInterface::class);
```

**Comment by DanielBadura** [comment]
Is there some other way to mock e.g. calls to `PDO::pgsqlGetNotify`? Without `addMethods` I get `PHPUnit\Framework\MockObject\MethodCannotBeConfiguredException: Trying to configure method "pgsqlGetNotify" which cannot be configured because it does not exist, has not been specified, is final, or is static`. 

Or some other suggestions for this case?

**Comment by mdetzner-godaddy** [comment]
How will it be possible to mock methods from a trait in the future if I can no longer specify them with addMethods()?

**Comment by MattesDe** [comment]
How will it be possible to mock methods from a trait in the future if I can no longer specify them with addMethods()?

**Comment by NanoSector** [comment]
A slightly more flexible solution to @g105b 's MockedCaller class is defining it as a simple generic interface:

```
/**
 * @see https://github.com/sebastianbergmann/phpunit/issues/5320
 *
 * @template T
 */
interface CallableMock
{
    /**
     * @return T
     */
    public function __invoke();
}
```

This does not force a void return type, and makes tools like PHPStan happier because you can type hint the callable return type:

```
        /** @var MockObject&CallableMock<\stdClass> $callableMock */
        $callableMock = $this->createMock(CallableMock::class);

        $callableMock->expects($this->once())
            ->method('__invoke')
            ->willReturnCallback(function (): \stdClass {
                return new \stdClass();
            });

        // Assuming method() has @param callable(): \stdClass $argument
        $result = $someSubject->method($callableMock->__invoke(...));
```

**Comment by ChrisHSandN** [comment]
@NanoSector answer can be extended with a `__call` interface function to allow arbitrary named methods to be mocked:

```php
interface CallableMock
{
	/**
	 * @return T
	 */
	public function __invoke();

	/**
	 * @return T
	 */
	public function __call(string $name, array $arguments);
}
```

The best way I have found to handle them is with a `match()` as this provides built in error triggering if an unhandled method is called:
```php
$callableMock = $this->createMock(CallableMock::class);

$callableMock->expects($this->any())
	->method('__call')
	->willReturnCallback(fn(string $name): string => match ($name) {
		'a' => 'foo',
		'b' => 'bar',
	});

echo $callableMock->a(); // foo
echo $callableMock->b(); // bar
echo $callableMock->c(); // UnhandledMatchError
```

**Comment by den4j** [comment]
Looks like `MockBuilder::onlyMethods()` should allow to mock any method when method `__call` implemented.
That's not weird, as we have seen people looking for workaround on current limitations.
PHP's `__call` magic method widely used to implement integration libraries, so it's a common need to mock them.

**Comment by llegaz** [comment]
@den4j  ofc but replacing a functional API with gas factories give work to a lot of developers that have to justify their salary.

**Comment by bghenne** [comment]
@cjhewett Great thanks for your solution, it helped a lot!

**Comment by danrod96-new** [comment]
@cjhewett Thanks, your solution worked like a charm

**Comment by mcapinha-mxp** [comment]
I've just migrated our tests to PHPUnit v10 and got it with some `MethodCannotBeConfiguredException`s. I've fixed those with `addMethods`, but am left wondering what the way forward is?

For instance, how can we supporting mocking Doctrine's magic find mehods, like findBy<WhateverAttribute>?
I undestand these are evil and we should refactor the original code but the question remains :)

**Comment by llegaz** [comment]
@mcapinha-mxp I am not sure but I think you will have to work on intermediary classes that really implement your findBy methods

a real classe implementing the EntityManagerInterface for instance..

**Comment by derrabus** [comment]
> For instance, how can we supporting mocking Doctrine's magic find mehods, like findBy?

You can mock the magic `__call()` method instead.

**Comment by mcapinha-mxp** [comment]
Ended up going that way, although it doesn't feel very elegant.
But, at the end of the day, this just enforces not using magic methods, so fine by me.
Thx @derrabus !

**Comment by zeleznypa** [comment]
> Looks like `MockBuilder::onlyMethods()` should allow to mock any method when method `__call` implemented. That's not weird, as we have seen people looking for workaround on current limitations. PHP's `__call` magic method widely used to implement integration libraries, so it's a common need to mock them.

Thanks for this suggestion. It is perfect, until you need to test more than one magic method call... For example, if you want to make a unit test for [Dibi/Fluent](https://github.com/dg/dibi/blob/master/src/Dibi/Fluent.php)...

After that, it is almost impossible to create understandable tests...

**Comment by danrod96-new** [comment]
Thank you, I was waiting for this.
