### ISSUE TITLE
Migration from `<coverage>` to `<source>` does not work

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#5324]
Hi, I'm currently on 07c279b and my suite is warning me with:

```
There was 1 PHPUnit test runner warning:

1) Test results may not be as expected because the XML configuration file did not pass validation:

  Line 14:
  - Element 'include': This element is not expected.
```

But I can't find the proper way to adapt the XML to the new required XSD.
The migration tool doesn't seem to be helpful either:

```
$ vendor/bin/phpunit --migrate-configuration
PHPUnit 10.1-dev by Sebastian Bergmann and contributors.

Created backup:         ./phpunit.xml.bak
Migration failed: "./phpunit.xml" is not a valid PHPUnit XML configuration file that can be migrated
```

Could be the changelog for 10.1 updated with some more details please?

_Originally posted by @Slamdunk in https://github.com/sebastianbergmann/phpunit/issues/5294#issuecomment-1506904338_

**Comment by Slamdunk** [comment]
@sebastianbergmann add `cacheDirectory=".phpunit.cache"` to the `<phpunit>` tag

**Comment by sebastianbergmann** [comment]
Thanks!
