### ISSUE TITLE
Silenced `E_USER_*` are ignored and triggers error/warning/notice/deprecation (display/failing)

### ISSUE THREAD

**Issue by sbuerk** [sebastianbergmann/phpunit#5325]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.0, 10.1-dev
| PHP version         | 8.1.x, 8.2.x
| Installation Method | Composer & PHAR

#### Summary

Basically, there are two ways to silence error levels:

* set error_reporting to a value, not containing the error levels which should be silenced/not displayed
* using the silence operator `@` to enforce silencing the error level, unrelated to the set error reporting  level

For example, it's possible that `E_ALL` has been set
as global error_level() and therefore triggering a
user deprecation/warning/error using the `trigger_error`
method will be displayed. If the `@` silence operator
is used before the `trigger_error()` call, the error
is silenced.  

```php
error_reporting(E_ALL);
trigger_error('', E_USER_DEPRECATED);  // will be shown
@trigger_error('', E_USER_DEPRECATED); // will not be shown
```

However, registered error handler will be called for all errors, despite it has been silenced or not for both possible ways to silence a error levels. ErrorHandler check the       
passed `$errorNumber` against the result of error_reporting() to determine if the errorNumber/errorLevel is supressed or not. That check will also detect a errorNumber as beeing
silenced if the `@` silence operator has been used, which could and should be taken as a intentional and enforced silencing of an error (knowing that it would fail).

There are multple use-cases, where for e.g. silenced user deprecation should not be taken as such, displayed and fail.

MockBuilder converts `@deprecated` method docblock annotations to silenced `@trigger_error('', E_USER_DEPRECATED)` calls. Having a `@deprecated` annonation does not mean, that the original method call would trigger an `E_USER_DEPRECATED` error - and it's arguable that it should be a hard enforcement by PHPUnit to decide this and doing the conversion.

Using the `<source>` configuration does not help here to let silenced error levels in third party code be ignored but in own code triggerd - or own user errors ignored but 3rd party code ignored. Beside this, it's not possible to silence the silenced E_USER_DEPRECATION triggered by the converted `@deprecected` annotations of mocked class methods.

#### Current behavior

Silence state of `E_USER_*` errors are ignored, regardless if the have been silenced by PHP error level configuration or the `@` silence operator before the `trigger_error()` call.

PHPUnit v9 instead respectes enforced silenced user error levels.

#### How to reproduce

Using one of these calls in a class method:

```php
<?php

@trigger_error('some message', E_USER_DEPRECATED);
@trigger_error('some message', E_USER_NOTICE);
@trigger_error('some message', E_USER_WARNING);
```

Having a class:

```php
<?php

class SomeClass {

  public function __construct()
  {
    $this->someMethod();
  }

  /**
   * @deprecated since 4.3, will be removed in 5. Not triggering an error.
   */
  public function someMethod(): void
  {}
}
```

and creating a mock of it:

```php
$mock = $this->createMock(SomeClass::class);
```

triggers a suppressed `E_USER_DEPRECATED` error. The suppressing is ignored,
and the deprecation is collected, displayed if selected and/or failing (exit
code > 0) if selected.

#### Expected behavior

* MockBuilder should not decide on its own to trigger a deprecation for a method having only a deprecation annotation

And/or

* A silenced/enforced silenced error/user error should not be ignored - or it should be configurable (per level/code place/etc).

As a intermediate solution ignoring a suppressed `E_USER_*` should be removed  again, until a workable solution can be found to distingush with all containing parts. This reverts to how it has worked in PHPUnit v9.

**Comment by sebastianbergmann** [comment]
> MockBuilder converts `@deprecated` method docblock annotations to silenced `@trigger_error('', E_USER_DEPRECATED)` calls. 

Neither PHPUnit's MockBuilder nor any other part of PHPUnit acts on `@deprecated` annotations.

**Comment by lolli42** [comment]
Thanks!

With this in place, we finished the migration to phpunit 10.1.

We're happy phpunit can exit non-zero again in case a test calls a method that contains trigger_error('message', E_USER_DEPRECATED):
Our deprecation policy requires we can only deprecate stuff when it's unused. This forces us to get rid of usages first, simplifies removal later, and helps us coming up with good migration documentation for 3rd party consumers. Tests of deprecated stuff is moved to a different test directory with the deprecation patch, that suite is configured to not fail on deprecation, while the main suite does fail when code directly or indirectly calls deprecated things. This strategy works out pretty well for us, and it's good phpunit keeps support for this.
