### ISSUE TITLE
Revisit triggering `E_USER_DEPRECATED` in doubled methods that are deprecated

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#5327]
The `MockBuilder` reads `@deprecated` docblocks for methods and adds a `@trigger_error($deprectedDocBlockMessage, E_USER_DEPRECATED)` to the mocked method code.

See:

https://github.com/sebastianbergmann/phpunit/blob/fcff1c55669c22708f0370133eaa60bc206fe3df/src/Framework/MockObject/MockMethod.php#L75

https://github.com/sebastianbergmann/phpunit/blob/fcff1c55669c22708f0370133eaa60bc206fe3df/src/Framework/MockObject/Generator/deprecation.tpl#L2

https://github.com/sebastianbergmann/phpunit/blob/fcff1c55669c22708f0370133eaa60bc206fe3df/src/Framework/MockObject/MockMethod.php#L182

_Originally posted by @sbuerk in https://github.com/sebastianbergmann/phpunit/issues/5325#issuecomment-1507490584_

**Comment by sebastianbergmann** [comment]
As mentioned in https://github.com/sebastianbergmann/phpunit/issues/5325#issuecomment-1507496891, I had totally forgotten about this.

This feature was implemented by @nicolas-grekas in 901a362dbe5e965facd360c2720089892720d594. So I would like ask him for his opinon on this.

I think that there is value in getting feedback from PHPUnit that you are doubling a method that is marked as `@deprecated`. However, I also think that @sbuerk has a point when he writes "MockBuilder should not decide on its own to trigger a deprecation for a method having only a deprecation annotation".

We can make this feature configurable (on by default) in PHPUnit 10.2 and change to off by default in PHPUnit 11, for instance.

Regardless, I think we should change the implementation of this feature to not use `trigger_error()` but instead emit a PHPUnit event directly (so we save the detour through PHPUnit's error handler).

**Comment by nicolas-grekas** [comment]
What matters is that this is hookable. An internal event looks good to me!

**Comment by nicolas-grekas** [comment]
Than all is fine, this is all we need :)

**Comment by sbuerk** [comment]
Would vote more for a dedicated event with stop/fail options. (Mocked class method contained deprecated docblock) or something like that.

Otherwise, I would transition it to a suppressed `E_USER_DEPRECATED` AND having a option in the mockbuilder if a docblock should be transformed magically or not.

The bare minimum would be to to it as:

```
@trigger_error('', E_USER_DEPRECATED);
```

That would still mean that PHPUnit decides to promote `@deprecated` docblock annotations to real deprecations. Something, which should not be enforced by PHPUnit.

**Comment by nicolas-grekas** [comment]
Why do you think so?
My experience is that all opportunities to tell end users that they're relying on deprecated code paths are important to report.
Making this optional would be just silencing something that code authors want their users to see.

**Comment by sbuerk** [comment]
@nicolas-grekas Generally, I'm with you, but not fully.

We have the policy in our own code base, that no deprecated functionality should be called itself. Therefore, usage must be resolved before deprecating something, and non-suppressed `trigger_error(E_USER_DEPRECTED)` are added.

However, in absolutly rare cases that is not possible, and the trigger_error() left out and only the docblock used. As the method/class is not tested directly, but other classes, this is mocked. Thus emitting this silenced deprecation. 

The "tested" class/method itself is not deprecated, therefor moving it to the "derpecated" tests is not the right way for us. Only the included call to another method which is deprecated will be removed in the next version.

This not only counts for own mocked services, but also for mocked 3rd party code.

This would enforce us to remove these tests which are basically needed or disable deprecation to fail (which would open the way that it would not be found were real trigger_error() calls are executed in our code base).

E.g. having some wrapping stuff, needing to mock deprecated `AbstractPlatform` from doctrine/dbal 3.x for the old LTS version of our application. Upgrading to doctrine/dbal or refactoring the code to avoid calls would mean to introduce breaking stuff which would be against our "non-breaking" policy after dot-zero releases for a major version/lts version.

The 3rd party code uses @trigger_error() which can be tested. 

DocBlock annotations are "comments" - and not executed code. PHPUnit cannot now if this should be really a deprecated error or not just from the docblock annotation.

**Comment by nicolas-grekas** [comment]
If you call a method with `@deprecated` annotation, you *are* running into a deprecated code path, so there should be a way to report in. This annotation is a comment that *should* accounted for.

I don't know if that could help but we insulate such test cases in a `@group legacy`, and our deprecation reporting mechanism know that it shouldn't yell for those. Is that something that'd make sense in your case?

**Comment by sebastianbergmann** [comment]
> We can make this feature configurable (on by default) in PHPUnit 10.2 and change to off by default in PHPUnit 11, for instance.

I no longer think it is a good idea to make it configurable whether or not PHPUnit's test double code generator generates code that emits an event in case a test double method is called where the respective original method is annotated with `@deprecated`. Such an event should always be emitted.

> Regardless, I think we should change the implementation of this feature to not use trigger_error() but instead emit a PHPUnit event directly (so we save the detour through PHPUnit's error handler).

I am leaning towards implementing a new separate event for "test double method is called where the respective original method is annotated with `@deprecated`". As said above, this event will always be emitted. But whether or not it is treated as "test triggered deprecation" can be configured.

This new event would, of course, have source location information for the original method. That way it can be restricted to the "source you are interested" (`<source>` configuration element introduced in PHPUnit 10.1).
