### ISSUE TITLE
Run only failed tests

### ISSUE THREAD

**Issue by thiago-figueredo** [sebastianbergmann/phpunit#5331]
I want to implement a feature to run only failed tests, but i'm new to the project and need to understand how the `run` method of `TestRunner` works.

To make this feature i'll follow these steps:

1. Generate the test report by using `--log-junit` option, something like `./phpunit --log-junit test-results.xml`
2. Apply a regex to find the name of the failed tests in test report file.
3. Run each failed test.

**Comment by sebastianbergmann** [comment]
This is outside the scope of this project.
