### ISSUE TITLE
IgnoreClassForCodeCoverage attribute does not work if no test are performed, while class should be ignored

### ISSUE THREAD

**Issue by niconoe-** [sebastianbergmann/phpunit#5333]
Hi and thank you very much for amazing PHPUnit features everyday!

As soon as PHPUnit 10.1 was rolled out, I wanted to try the `#[Ignore…ForCodeCoverage]` attributes, but it occurs to me that it did not went as I expected. Here is my situation:

On my projects, I mainly use a "mirrored-architecture" for testing, like 1 class = 1 associated test class. I know this is debatable, but that's another topic :smile:. On lots of my project, I have a `Kernel` class that I can't test for technical reasons, so I used to place a `/** @codeCoverageIgnore */` on PHPDoc of that class, but now, I want to use the `#[IgnoreClassForCodeCoverage]` attribute. The main problem I'm facing is that I don't have any `KernelTest` associated test-class because that's the point: I can't test my `Kernel` class. So I can't add the attribute in a relevant location.

I understand that there are no feasable way to ignore my class without any `KernelTest` class if I want to keep my "mirrored-architecture", so I created a `KernelTest` class, with only the attribute, but still, it does not work: the code coverage tells me the `Kernel` class is not covered, and **not ignored**. I discovered that's because my test class doesn't perform any tests, so I added a test method with a `#[DoesNotPerformAssertions]` attribute to remove the related warning.

The code looks like this:

```php
<?php
declare(strict_types=1);

namespace MyApp\Tests;

use MyApp\Kernel;
use PHPUnit\Framework\Attributes\DoesNotPerformAssertions;
use PHPUnit\Framework\Attributes\IgnoreClassForCodeCoverage;
use PHPUnit\Framework\TestCase;

#[IgnoreClassForCodeCoverage(Kernel::class)] // Kernel class is not testable.
final class KernelTest extends TestCase
{
    #[DoesNotPerformAssertions]
    public function test(): void
    {
    }
}
```

Is this the smallest code content required to ignore a class? This looks to me very verbose just to ignore a class in my situation. 
With the previous way to ignore class coverage, only a simple line `/** @codeCoverageIgnore */` was necessary and I expected something very similar to be applied. 

What I'm the most confused with is that `@codeCoverageIgnore` was internal (it applied on the class/method/function where it is defined) while `#[Ignore…ForCodeCoverage]` is external (it applies on the class/method/function given in argument). I think that deprecating the first in favor of the second is not relevant as they are not working the same way. Also, this new way of declaring coverage to ignore can lead to very weird and confusing patterns like adding the attribute on a test class which context is completly irrelevant regarding the class to ignore.

Do you think it would be OK to not deprecate `#[codeCoverageIgnore]` (I'm ok to deprecate the annotation usage) and to keep it so that when applied on a class/method/function, it acts like it did so well until PHPUnit 10.0 included?

In any other case, which advice could you give to me to easily ignore a class (I mean as easy as having only 1 line like it was done previously to PHPUnit 10.1 :smile:)?

Thanks a lot, your work on PHPUnit is astonishing! Thanks again!

**Comment by sebastianbergmann** [comment]
Probably unrelated: please note that [PHPUnit 10.1.1](https://github.com/sebastianbergmann/phpunit/blob/10.1/ChangeLog-10.1.md#1011---2023-mm-dd) will fix two bugs related to `#[DoesNotPerformAssertions]`.

**Comment by niconoe-** [comment]
Thanks a lot! I didn't know this was already on tracks!

Therefore, something like
```php
<?php
declare(strict_types=1);

namespace MyApp\Tests;

use MyApp\Kernel;
use PHPUnit\Framework\Attributes\DoesNotPerformAssertions;
use PHPUnit\Framework\Attributes\IgnoreClassForCodeCoverage;
use PHPUnit\Framework\TestCase;

#[DoesNotPerformAssertions]
#[IgnoreClassForCodeCoverage(Kernel::class)] // Kernel class is not testable.
final class KernelTest extends TestCase
{
}
```
could be OK.

Well, that's not as easy as `#[CodeCoverageIgnore]` but if you really want to avoid PHP Attributes in production code, I can hardly complain about this solution :slightly_smiling_face:.

_About Attributes in Production code:_
I read [the conversation you got with Larry Garfield and Ben Ramsey about the risk of dependencies](https://phpc.social/@ramsey/109911222910943137) and I really agree with them that having such "dependencies" via attributes only shouldn't be an issue, as long as no one is doing dumb auto instanciations. Therefore, I wonder what good points it could bring to deprecate them in favor of test-code attributes. IMO, having such attributes (especially about code coverage) in production code gives also the information that some class/method/function is not covered so probably untrustable; an information I think valuable on open source repositories for instance. I fear now that having those attributes on test-code level will mask that some snippets are untested and therefore untrustable.

**Comment by sebastianbergmann** [comment]
Superseded by https://github.com/sebastianbergmann/php-code-coverage/issues/994.

**Comment by niconoe-** [comment]
I just tried with v10.1.1 using the following snippet and it does not work: 

```php
<?php
declare(strict_types=1);

namespace MyApp\Tests;

use MyApp\Kernel;
use PHPUnit\Framework\Attributes\DoesNotPerformAssertions;
use PHPUnit\Framework\Attributes\IgnoreClassForCodeCoverage;
use PHPUnit\Framework\TestCase;

#[DoesNotPerformAssertions]
#[IgnoreClassForCodeCoverage(Kernel::class)] // Kernel class is not testable.
final class KernelTest extends TestCase
{
}
```

My `Kernel.php` file is still considered as uncovered while I expected it to be ignored. I believe that's because even with `#[DoesNotPerformAssertions]`, as the test-class does not contain any tests, there is a warning (`1) No tests found in class "MyApp\Tests\KernelTest".`) and because of that warning, the `#[IgnoreClassForCodeCoverage]` attribute has no effect on the code coverage.
