### ISSUE TITLE
Add option to allow empty data provider for test

### ISSUE THREAD

**Issue by jnoordsij** [sebastianbergmann/phpunit#5334]
When using an empty data provider for a test, a PHPUnitError `Empty data set provided by data provider` is thrown. This behavior is different to v9 and previous versions, where such a test would be marked as skipped (see also https://github.com/sebastianbergmann/phpunit/commit/6fa08ade49ea442bbdde1607dca00128111c1b7f).

Altough at first glance this sounds perfectly logical, I think there is some usecase for allowing empty data providers: when creating an abstract TestCase class, you might want to add a test method with a corresponding data provider that is empty by default. This allows the implementation of the test case to decide wether or not to use this particular test + data provider implementation, making it some kind of "optional test".

Currently I find that the easiest workaround for this in v10 is creating a trait implementing the test and naming the respective data provider, but I think this is quite ugly and has very many downsides, so I'm hoping to find a better alternative.

Possible implementations (open to suggestions!):
- add an additional `allowEmpty` argument to the `DataProvider` attribute
- add a `RequiresNonEmptyDataProvider` attribute that skips a test if the provided data provider is empty
- allow empty data providers only if they were declared on an abstract class (not sure if this is very useful and if this is practically viable at all)

*Note:* I'm also very open to any suggestions how such a thing can be already achieved using the current latest version, if anyone has an improvement to my current workaround!

**Comment by sebastianbergmann** [comment]
I do not think that PHPUnit should support empty data sets.
