### ISSUE TITLE
`#[DoesNotPerformAssertions]` attribute is still triggering a warning for empty test classes

### ISSUE THREAD

**Issue by niconoe-** [sebastianbergmann/phpunit#5336]
Hi again

After #5333 was closed, I wrote [a comment](https://github.com/sebastianbergmann/phpunit/issues/5333#issuecomment-1511271176) to explain that the usage of `#[DoesNotPerformAssertions]` at class-level on an empty class. Maybe you did not get notified because the issue was closed. 

The sum up was that  `#[DoesNotPerformAssertions]` at class-level, on an empty class:
* does not ignore the coverage to ignore when coupled with `#[IgnoreClassForCodeCoverage(…)]` (and probably true for other `#[Ignore…ForCodeCoverage]` attributes)
* still produces a warning telling that no tests were found in the class.

I know usage of empty classes is a very controversal topic but I do have the feeling that an empty class with attributes is not **that** empty actually, and should be considered, as well as its attributes.

To me, this is a bug as PHPUnit 10.1.1 (on which I tested) [tried to fix that](https://github.com/sebastianbergmann/phpunit/blob/10.1.1/ChangeLog-10.1.md#1011---2023-04-17) if I understand correctly.

Nevertheless, thank you very much for all your work :heart: !

**Comment by sebastianbergmann** [comment]
I think that warning about empty test classes is the right thing to do (and unrelated to `#[DoesNotPerformAssertions]`).

**Comment by niconoe-** [comment]
> I think that warning about empty test classes is the right thing to do (and unrelated to `#[DoesNotPerformAssertions]`).

Indeed, like I said, it's controversial and I understand your statement.

Nevertheless, why such snippet does not ignore the coverage on the class `Kernel` then?
```php
<?php
declare(strict_types=1);

namespace MyApp\Tests;

use MyApp\Kernel;
use PHPUnit\Framework\Attributes\DoesNotPerformAssertions;
use PHPUnit\Framework\Attributes\IgnoreClassForCodeCoverage;
use PHPUnit\Framework\TestCase;

#[DoesNotPerformAssertions]
#[IgnoreClassForCodeCoverage(Kernel::class)] // Kernel class is not testable.
final class KernelTest extends TestCase
{
}
?>
```

Is that because the test class is empty? Well, that's actually the point! **I can't test anything** on the `Kernel` class, so why would I declare a method in that class?

I actually don't mind about the warning, but looking at the PHP Attributes declared on `KernelTest`, to **not** ignore `Kernel` from the code coverage really looks like a bug to me, as I explicitly ask for it to be ignored, but it's not.
