### ISSUE TITLE
Use of mocks swallows output

### ISSUE THREAD

**Issue by Crell** [sebastianbergmann/phpunit#5338]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.1.1
| PHP version         | 8.2
| Installation Method | Composer

#### Summary

Similar to #5278, I'm getting the same problem still but only in test methods that make use of the mocking library *and* assertions.

#### Current behavior

I was making this test method for a tutorial (So it's not best practice-y):

```php
    public function testWithMockBuilder(): void
    {
        print __METHOD__;
        $mock_repository = $this
            ->getMockBuilder(ProductRepository::class)
            ->disableOriginalConstructor()
            ->getMock();

        $this->assertTrue(true);

        $obj1 = new Product('one', 50, 'blue');

        $obj2 = $this->getMockBuilder(Product::class)
            ->disableOriginalConstructor()
            ->getMock();
        $obj2->method('availableIn')->willReturn(false);
        $obj2->method('numberAvailable')->willReturn(70);

        $map = [ [1, $obj1], [2, $obj2] ];

        $mock_repository
            ->method('load')->will($this->returnValueMap($map));

        $subject = new ProductOperator($mock_repository);
        $result = $subject->find(40, 'green');

        //$this->assertCount(1, $result);
    }
```

If I uncomment the `assertCount()` statement, the output from `print __METHOD__` disappears.  If I comment that line out, print/var_dump/etc. generate the expected output.

Of note, in another test method in the same class I can generate output and run assertions at the same time, no  problem:

```php
    public function testStuff(): void
    {
        print __METHOD__;
        $this->assertTrue(true);
    }
```

#### How to reproduce

See above.

#### Expected behavior

Output should be printed to the screen regardless.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by sebastianbergmann** [comment]
I cannot reproduce this:
```php
<?php declare(strict_types=1);
use PHPUnit\Framework\TestCase;

interface I
{
    public function m(): bool;
}

final class Test extends TestCase
{
    public function testOne(): void
    {
        $i = $this->createStub(I::class);

        $i->method('m')->willReturn(true);

        $this->assertTrue($i->m());
        
        print __METHOD__;
    }
}
```
```
$ phpunit Test.php
PHPUnit 10.1.1-10-g05e360c789 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.2.5

Test::testOne.                                                                   1 / 1 (100%)

Time: 00:00.017, Memory: 4.00 MB

OK (1 test, 1 assertion)
```

**Comment by Crell** [comment]
Huh.  Well, now I can't reproduce it either.  I swear it was happening. 😄 

If I get this behavior again I'll try to submit a more contained example.  But for now I guess I'll close this.
