### ISSUE TITLE
Not all test-related events are emitted when a test fails or errors

### ISSUE THREAD

**Issue by Crell** [sebastianbergmann/phpunit#5340]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.1.1
| PHP version         | 8.1.14
| Installation Method | Composer

#### Summary

I have a breaking test case for debug output now!  The issue is test failure, not mocking, as I previously thought.  (Of course, failing tests is when I'd want debug output!)

Given this test class:

```php
class SampleTest extends TestCase
{
    public function testPass(): void
    {
        print "This is in the Passing test\n";

        self::assertTrue(true);
    }

    public function testFail(): void
    {
        print "This is in the Failing test\n";

        self::assertTrue(false);
    }
}
```

#### Current behavior

I get this output:

```
PHPUnit 10.1.1 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.1.14
Configuration: /app/phpunit.xml.dist

This is in the Passing test
.F                                                                  2 / 2 (100%)

Time: 00:00.013, Memory: 8.00 MB

There was 1 failure:

1) Crell\PGTools\SampleTest::testFail
Failed asserting that false is true.

/app/tests/SampleTest.php:22

FAILURES!
Tests: 2, Assertions: 2, Failures: 1.
```

The debug message from the passing test is shown.  But the output from the failing test is missing.

#### How to reproduce

See above sample code.

#### Expected behavior

Both print statements should be written to stdout.

**Comment by sebastianbergmann** [comment]
Thank you for bringing this to my attention! This is a lot more "interesting" than one would assume ...
