### ISSUE TITLE
The latest php version, php 8.2.5 and the latest phpunit version of 10.1.2, when used together, error on strict typed property $name.

### ISSUE THREAD

**Issue by tchalvak** [sebastianbergmann/phpunit#5350]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | PHPUnit 10.1.2 by Sebastian Bergmann and contributors.
| PHP version         | PHP 8.2.5 (cli) (built: Apr 14 2023 04:27:02) (NTS)
| Installation Method | Composer install of phpunit/phpunit

Note: I added the composer info | sort at the bottom due to it's verbosity.

#### Summary
Upgrading to the latest phpunit version of 10.1.2 (from phpunit 9.6) while using the latest version of php 8.2.5 throws unrecoverable errors when trying to run phpunit.  It seems to be erroring on use of the $name property of PHPUnit\Framework\TestCase in TestRunner where it cannot be accessed before initialization, the accessed before initialization errors being a new type of error coming with strictness in the later php 8.2 version.

#### Current behavior

Error is: 

./vendor/bin/phpunit --testsuite Unit

An error occurred inside PHPUnit.

Message:  Typed property PHPUnit\Framework\TestCase::$name must not be accessed before initialization
Location: /src/ninjawars/deploy/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:68

Full context of a run of the stack strace is:

```
./vendor/bin/phpunit --testsuite Unit
Runtime:       PHP 8.2.5
Configuration: /src/project/phpunit.xml



An error occurred inside PHPUnit.

Message:  Typed property PHPUnit\Framework\TestCase::$name must not be accessed before initialization
Location: /src/project/deploy/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:68

#0 /src/project/deploy/vendor/phpunit/phpunit/src/TextUI/Application.php(168): PHPUnit\TextUI\TestRunner->run()
#1 /src/project/deploy/vendor/phpunit/phpunit/phpunit(99): PHPUnit\TextUI\Application->run()
#2 /src/project/deploy/vendor/bin/phpunit(120): include('...')
#3 {main}

Caused by: /src/project/deploy/vendor/phpunit/phpunit/src/Framework/TestCase.php:967

#0 /src/project/deploy/vendor/phpunit/phpunit/src/Runner/TestSuiteSorter.php(333): PHPUnit\Framework\TestCase->sortId()
#1 /src/project/deploy/vendor/phpunit/phpunit/src/Runner/TestSuiteSorter.php(335): PHPUnit\Runner\TestSuiteSorter->calculateTestExecutionOrder()
#2 /src/project/deploy/vendor/phpunit/phpunit/src/Runner/TestSuiteSorter.php(335): PHPUnit\Runner\TestSuiteSorter->calculateTestExecutionOrder()
#3 /src/project/deploy/vendor/phpunit/phpunit/src/Runner/TestSuiteSorter.php(119): PHPUnit\Runner\TestSuiteSorter->calculateTestExecutionOrder()
#4 /src/project/deploy/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(43): PHPUnit\Runner\TestSuiteSorter->reorderTestsInSuite()
#5 /src/project/deploy/vendor/phpunit/phpunit/src/TextUI/Application.php(168): PHPUnit\TextUI\TestRunner->run()
#6 /src/project/deploy/vendor/phpunit/phpunit/phpunit(99): PHPUnit\TextUI\Application->run()
#7 /src/project/deploy/vendor/bin/phpunit(120): include('...')
#8 {main}
```

#### How to reproduce

I expect that it should work with any reduced test case that has a test file that inherits from the base TestCase class, then install php 8.2.5 and phpunit version 10.1.2  I'll try to create a repo with that reduced test case failure shortly after this. (repo pending...)

#### Expected behavior

Expectation is that phpunit will run with the latest php version without a (apparently) fatal error.
So running ./vendor/bin/phpunit --testsuite Unit should get through to the tests within.

#### Output of composer info | sort
brick/math                            0.11.0  Arbitrary-precision arithmetic library
clue/stdio-react                      v2.6.0  Async, event-driven console input & output (STDIN, STDOUT) for truly interactive CLI applications, built on top of ReactPHP
clue/term-react                       v1.3.0  Streaming terminal emulator, built on top of ReactPHP.
clue/utf8-react                       v1.2.0  Streaming UTF-8 parser, built on top of ReactPHP.
components/jquery                     2.2.4   jQuery JavaScript Library
composer/installers                   v2.2.0  A multi-framework Composer library installer
doctrine/deprecations                 v1.0.0  A small layer on top of trigger_error(E_USER_DEPRECATED) or PSR-3 logging with options to disable all deprecations or selectively for pa...
doctrine/inflector                    2.0.6   PHP Doctrine Inflector is a small library that can perform string manipulations with regard to upper/lowercase and singular/plural forms...
doctrine/lexer                        2.1.0   PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
egulias/email-validator               3.2.5   A library for validating emails against several RFCs
evenement/evenement                   v3.0.1  Événement is a very simple event dispatching library for PHP
illuminate/collections                v10.9.0 The Illuminate Collections package.
illuminate/conditionable              v10.9.0 The Illuminate Conditionable package.
illuminate/container                  v10.9.0 The Illuminate Container package.
illuminate/contracts                  v10.9.0 The Illuminate Contracts package.
illuminate/database                   v10.9.0 The Illuminate Database package.
illuminate/macroable                  v10.9.0 The Illuminate Macroable package.
illuminate/support                    v10.9.0 The Illuminate Support package.
jolicode/jolinotif                    v2.5.0  Send desktop notifications on Windows, Linux, MacOS.
myclabs/deep-copy                     1.11.1  Create deep copies (clones) of your objects
nesbot/carbon                         2.66.0  An API extension for DateTime that supports 281 different languages.
nikic/php-parser                      v4.15.4 A PHP parser written in PHP
ninjawars/jquery-linkify              2.1.1  
oomphinc/composer-installers-extender 2.0.1   Extend the composer/installers plugin to accept any arbitrary package type.
phar-io/manifest                      2.0.3   Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                       3.2.1   Library for handling version information and constraints
phpunit/php-code-coverage             10.1.1  Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator             4.0.1   FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-invoker                   4.0.0   Invoke callables with a timeout
phpunit/php-text-template             3.0.0   Simple template engine.
phpunit/php-timer                     6.0.0   Utility class for timing
phpunit/phpunit                       10.1.2  The PHP Unit Testing framework.
pimple/pimple                         v3.5.0  Pimple, a simple Dependency Injection Container
psr/container                         2.0.2   Common Container Interface (PHP FIG PSR-11)
psr/simple-cache                      3.0.0   Common interfaces for simple caching
react/event-loop                      v1.3.0  ReactPHP's core reactor event loop that libraries can use for evented I/O.
react/stream                          v1.2.0  Event-driven readable and writable streams for non-blocking I/O in ReactPHP
rmm5t/jquery-timeago                  1.4.3  
sebastian/cli-parser                  2.0.0   Library for parsing CLI options
sebastian/code-unit                   2.0.0   Collection of value objects that represent the PHP code units
sebastian/code-unit-reverse-lookup    3.0.0   Looks up which function or method a line of code belongs to
sebastian/comparator                  5.0.0   Provides the functionality to compare PHP values for equality
sebastian/complexity                  3.0.0   Library for calculating the complexity of PHP code units
sebastian/diff                        5.0.3   Diff implementation
sebastian/environment                 6.0.1   Provides functionality to handle HHVM/PHP environments
sebastian/exporter                    5.0.0   Provides the functionality to export PHP variables for visualization
sebastian/global-state                6.0.0   Snapshotting of global state
sebastian/lines-of-code               2.0.0   Library for counting the lines of code in PHP source code
sebastian/object-enumerator           5.0.0   Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector            3.0.0   Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context           5.0.0   Provides functionality to recursively process PHP variables
sebastian/type                        4.0.0   Collection of value objects that represent the types of the PHP type system
sebastian/version                     4.0.1   Library that helps with managing the version number of Git-hosted PHP projects
smarty/smarty                         v4.3.1  Smarty - the compiling PHP template engine
spatie/phpunit-watcher                1.23.6  Automatically rerun PHPUnit tests when source code changes
swiftmailer/swiftmailer               v6.3.0  Swiftmailer, free feature-rich PHP mailer
symfony/console                       v6.2.10 Eases the creation of beautiful and testable command line interfaces
symfony/deprecation-contracts         v3.2.1  A generic function and convention to trigger deprecation notices
symfony/finder                        v5.4.21 Finds files and directories via an intuitive fluent interface
symfony/http-foundation               v4.4.49 Defines an object-oriented layer for the HTTP specification
symfony/mime                          v5.4.23 Allows manipulating MIME messages
symfony/polyfill-ctype                v1.27.0 Symfony polyfill for ctype functions
symfony/polyfill-iconv                v1.27.0 Symfony polyfill for the Iconv extension
symfony/polyfill-intl-grapheme        v1.27.0 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-idn             v1.27.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer      v1.27.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring             v1.27.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72                v1.27.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php80                v1.27.0 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/process                       v6.2.10 Executes commands in sub-processes
symfony/service-contracts             v3.2.1  Generic abstractions related to writing services
symfony/string                        v6.2.8  Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/translation-contracts         v3.2.1  Generic abstractions related to translation
symfony/translation                   v6.2.8  Provides tools to internationalize your application
symfony/yaml                          v6.2.10 Loads and dumps YAML files
theseer/tokenizer                     1.2.1   A small library for converting tokenized PHP source code into XML and potentially other formats
twbs/bootstrap                        v3.4.1  The most popular front-end framework for developing responsive, mobile first projects on the web.
voku/portable-ascii                   2.0.1   Portable ASCII library - performance optimized (ascii) string functions for php.
yosymfony/resource-watcher            v3.0.0  A simple resource watcher using Symfony Finder

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by sebastianbergmann** [comment]
No feedback, closing.

**Comment by tchalvak** [comment]
Ah, thanks for closing, I am unable to replicate with in a reduced test case repo, and downgraded to phpunit 9.6 in the actual environment and that works with php 8.2

**Comment by tchalvak** [comment]
> Similar to #5370.
> 
> Remove `__construct()` if you have any, in your TestCase extends.

Thank you, sounds like that is my issue, I rolled back to v9, but this may allow me to upgrade further, so appreciate it.
