### ISSUE TITLE
Excluding directory from testsuite

### ISSUE THREAD

**Issue by llaville** [sebastianbergmann/phpunit#5352]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.1.2
| PHP version         | 8.1.18
| Installation Method | PHAR and Composer

#### Summary

Excluding directory from testsuite in the `phpunit.xml` config file

#### Current behavior

Results with PHAR version (but Composer install gave same error)

```
An error occurred inside PHPUnit.

Message:  str_starts_with(): Argument #1 ($haystack) must be of type string, bool given
Location: phar:///usr/local/bin/phpunit/php-file-iterator/ExcludeIterator.php:42

#0 phar:///usr/local/bin/phpunit/php-file-iterator/ExcludeIterator.php(42): str_starts_with(false, '/shared/backups...')
#1 [internal function]: PHPUnit\SebastianBergmann\FileIterator\ExcludeIterator->accept()
#2 [internal function]: FilterIterator->next()
#3 [internal function]: FilterIterator->next()
#4 phar:///usr/local/bin/phpunit/php-file-iterator/Facade.php(34): AppendIterator->next()
#5 phar:///usr/local/bin/phpunit/phpunit/TextUI/Configuration/Xml/TestSuiteMapper.php(61): PHPUnit\SebastianBergmann\FileIterator\Facade->getFilesAsArray('/shared/backups...', 'Test.php', '', Array)
#6 phar:///usr/local/bin/phpunit/phpunit/TextUI/Configuration/TestSuiteBuilder.php(48): PHPUnit\TextUI\XmlConfiguration\TestSuiteMapper->map(Object(PHPUnit\TextUI\Configuration\TestSuiteCollection), '', '')
#7 phar:///usr/local/bin/phpunit/phpunit/TextUI/Application.php(214): PHPUnit\TextUI\Configuration\TestSuiteBuilder->build(Object(PHPUnit\TextUI\Configuration\Configuration))
#8 phar:///usr/local/bin/phpunit/phpunit/TextUI/Application.php(92): PHPUnit\TextUI\Application->buildTestSuite(Object(PHPUnit\TextUI\Configuration\Configuration))
#9 /usr/local/bin/phpunit(2896): PHPUnit\TextUI\Application->run(Array)
#10 {main}
```

#### How to reproduce

With source code https://github.com/llaville/box-manifest/tree/3.x
See final (good declaration) at https://github.com/llaville/box-manifest/blob/3.x/phpunit.xml.dist#L20

I've begun first without to introduced the `<exclude>` setting in `<testsuite>`, but PHPUnit seems frozen. Certainly because my fixtures required `vendor` directories (and there are lot of files to discover).

So I've specify this setting 

```xml
    <testsuite name="Box Manifest Test Suite">
        <exclude>vendor</exclude>
        <directory>tests/</directory>
    </testsuite>
```
Without to notice that partial directory value is not allowed. (See error produced)

#### Expected behavior

![phpunit-10 1](https://user-images.githubusercontent.com/364342/235851944-c3bb9040-898e-4a22-82bd-b49ba6df3c7f.png)

**NOTE** I don't know if you'll still support `exclude` setting from `testsuite`, because it's not yet referenced in documentation at https://github.com/sebastianbergmann/phpunit-documentation-english/blob/main/src/configuration.rst#the-testsuite-element

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by sebastianbergmann** [comment]
> I don't know if you'll still support `exclude` setting from `testsuite`, because it's not yet referenced in documentation at https://github.com/sebastianbergmann/phpunit-documentation-english/blob/main/src/configuration.rst#the-testsuite-element

Was this supported in PHPUnit 9?

**Comment by sebastianbergmann** [comment]
AFAICS, the `<exclude>` element under the `<testsuite>` element only supports excluding files, not excluding directories.

**Comment by llaville** [comment]
> AFAICS, the `<exclude>` element under the `<testsuite>` element only supports excluding files, not excluding directories.

Really, because actually when I declare 
```
    <testsuite name="Box Manifest Test Suite">
        <exclude>tests/fixtures/plugin/**/vendor/</exclude>
        <directory>tests/</directory>
    </testsuite>
```
Vendor directories are excluded !

**Comment by llaville** [comment]
> Was this supported in PHPUnit 9?

Not supposed to be supported (in my use case) by PHPUnit 9

**Comment by llaville** [comment]
Found origin of issue. It did not come from PHPUnit but from https://github.com/sebastianbergmann/php-file-iterator/blob/4.0.1/src/ExcludeIterator.php#L44

When `SplFileInfo::getRealPath` return `false`, because file is a symbolic link !

In my case, it's `/shared/backups/bartlett/box-manifest/tests/fixtures/plugin/box-003/vendor/humbug/box/fixtures/build/dir000/unknown`
See online at https://github.com/box-project/box/tree/main/fixtures/build/dir000

So if you fix it with something like 

```
        $path = $current->getRealPath();

        if ($path === false) {
            return true;
        }
``` 
PHPUnit seems frozen, because lot of files to scan, but at least It works.

Best fix, and to speed up execution, is to avoid to specify a partial directory name like with `<exclude>vendor/</exclude>` but with `<exclude>tests/fixtures/plugin/**/vendor/</exclude>`

**Comment by sebastianbergmann** [comment]
@localheinz Can you have a look at this and see if/how we can/should handle this in php-file-iterator? Thanks!

**Comment by localheinz** [comment]
@llaville @sebastianbergmann 

I think I have reproduced (and fixed) the issue in https://github.com/sebastianbergmann/php-file-iterator/pull/80!
