### ISSUE TITLE
Implement a way to specify expected method call order across multiple mocks

### ISSUE THREAD

**Issue by elnur** [sebastianbergmann/phpunit#5357]
I have no idea why PHPUnit still doesn't have support for this feature given how old and mature the project is. Every other test library I've used has this feature:

- [jMock has it](http://jmock.org/sequences.html),
- [Mockito has it](https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#6),
- [Mockery has it](https://docs.mockery.io/en/latest/reference/expectations.html#expectation-declaration-utilities),
- etc...

Even before [`at()` got deprecated and removed](https://github.com/sebastianbergmann/phpunit/issues/4297), it's biggest problem was the fact that it only worked for a single mock.

Putting aside purist theoretical mind-numbing discussions that we should not be testing the order of method calls, it is obvious that there's a need for such a feature. Otherwise other test libraries wouldn't have implemented it.

I personally have been running into this problem for years. I hoped PHPUnit would eventually support it, but it never happened. So now I'm taking initiative and trying to push this forward.

So let's discuss the design of this feature and then implement it.

I'd say the jMock's way is kinda ugly. The Mockito's way is nicer, but thanks to Java it relies on the fact that mocks in Mockito are typed in such a way that you statically call methods being tested, which wouldn't work in PHPUnit. So maybe go with the Mockery's way? Or come up with something else/better?

Thoughts? Ideas?

**Comment by sebastianbergmann** [comment]
I do not think that relying on call order makes sense.

**Comment by elnur** [comment]
Care to elaborate, @sebastianbergmann?

**Comment by reecefowell** [comment]
I depend on the features you are removing (both `withConsecutive(...)` and `at(...)`, but I do not see any recommended alternative solutions to solving the problem that these now deprecated functions solved. \\

Just removing functionality we depend on without further elaboration and no provided alternative solutions (that I could find) is extremely unhelpful.

How do you anticipate us to work around this? 
What are the solutions you are promoting in favour of these deprecated functions?

**Comment by Xachman** [comment]
@reecefowell I agree with this. This seems rather dogmatic @sebastianbergmann. It also creates confusion and time lost. I can appreciate the reasoning but even a bad test is better than no test.

**Comment by siamskoi** [comment]
You can use something like this:

```php
        $matcher = $this->exactly(3);

        $this->dumper->expects($matcher)->method('dump')
            ->willReturnCallback(function ($value) use ($matcher) {
                print_r($matcher->getInvocationCount());
                switch ($matcher->getInvocationCount()) {
                    case 1:
                        $this->assertEquals('expected1', $value);
                    case 2:
                        $this->assertEquals('expected2', $value);
                        break;
                    case 3:
                        $this->assertEquals('expected3', $value);
                        break;
                }
            });
```

**Comment by datbunneh** [comment]
I do not think that @sebastianbergmann makes sense.

**Comment by TeoLefebvre** [comment]
I looked for a way to bypass the lack of implementation and this method seems to work for PHPUnit 11 so I post it here and maybe it can help others.

Let me explain why I wanted to do this first. I have an Emitter class on which you can register Listeners to listen for events and you can specify the importance of the listener so when an event is emitted, the listener's callback is launched before the others. The importance of the listener is specify in the third argument of the Emitter's method on, the greater the number is, the more important the listener is and the sooner it will be executed.

To test the execution order of two listeners listening for the same event, the trick is to use an array to track the order of the executions and to use the method `willReturnCallback` to fill this array when the execution happends. You then just have to assert the array.

Here is the test function:

```php
public function testListenerCalledInTheRightOrder(): void
{
  $emitter = new Emitter();
  $listener = $this->createMock(Listener::class);
  $emitter->on('event', [$listener, 'onEvent'], 1);
  $emitter->on('event', [$listener, 'onEventImportant'], 2);
  
  $callOrder = [];
  $listener->expects($this->once())->method('onEventImportant')
  ->willReturnCallback(function () use (&$callOrder) {
    $callOrder[] = 'important';
  });
  $listener->expects($this->once())->method('onEvent')
  ->willReturnCallback(function () use (&$callOrder) {
    $callOrder[] = 'normal';
  });
  
  $emitter->emit('event');
  $this->assertSame($callOrder, ['important', 'normal']);
}
```

To help you better understand what I am testing, here is the simplified code of the Emitter class and Listener class.

```php
class Emitter
{
  private array $listeners = [];

  public function emit(string $event, ...$args): void
  {
    if ($this->hasListeners($event)) {
      foreach ($this->listeners[$event] as $listener) {
        $callback = $listener[0];
        if (is_callable($callback)) {
          $callback(...$args);
        } elseif (is_array($callback) && count($callback) === 2) {
          call_user_method_array($callback[1], $callback[0], $args);
        }
      }
    }
  }

  public function on(string $event, callable | array $listener, int $importance = 1): void
  {
    if (!$this->hasListeners($event)) {
      $this->listeners[$event] = [];
    }
    $this->listeners[$event][] = [$listener, $importance];
    usort($this->listeners[$event], function ($a, $b) {
      return $b[1] - $a[1];
    });
  }

  private function hasListeners(string $event)
  {
    return key_exists($event, $this->listeners);
  }
}

class Listener {
  public function onEvent() {
    echo 'event';
  }

  public function onEventImportant() {
    return 'important event';
  }
}
```

I hope it can help someone!

**Comment by reppair** [comment]
What do you mean "I do not think that relying on call order makes sense."? I sure want to assert method A gets called before method B. 😅

**Comment by zluiten** [comment]
I think there is much value in having a way to assert that calls are made in a certain order. An obvious one

```php
public function handle(Envelope $envelope, StackInterface $stack): Envelope
{
    $this->connection->beginTransaction();

    $envelope = $stack->next()->handle($envelope, $stack);

    $this->connection->commit();

    return $envelope;
}
```

I want to assert that the transaction is started before the `stack->next()` call is made. I can do that with using callbacks, but it does feel hacky and not how it is supposed to be done.

**Comment by kkevindev** [comment]
> What do you mean "I do not think that relying on call order makes sense."? I sure want to assert method A gets called before method B. 😅

My thoughts exactly.

**Comment by alexchexes** [comment]
Well, given that there is obviously no community consensus around this, maybe we should reopen this issue?
