### ISSUE TITLE
Support the '**' pattern to match 'zero or more directory names' for testsuite file definition

### ISSUE THREAD

**Issue by pascallandau-ay** [sebastianbergmann/phpunit#5359]
When defining the files and directories for a test suite, it is not possible to use a `'**'` pattern to match 'zero or more directory names'. Depending on the structure of the source code, this leads to additional complexity and can introduce subtle bugs (e.g. by missing tests not covered by the used patterns). 

## Example

A monolithic code base that uses multiple independent sub folders to separate packages and sub-packages, e.g.

```
app/
├── Main
|   └── tests/
├── Package_1
|   ├── Sub_Package_1
|   |     └──  tests/
|   └── Sub_Package_2
|         └──  tests/
├── Package_2
|   └── tests/
└── phpunit.xml
```

To cover all `tests/` directories, the following config is required:

```xml
<testsuites>
  <testsuite name="Full Suite">
  <-- e.g. Main/tests/ >
   <directory>./*/tests/</directory>
  <-- e.g. Package_1/Sub_Package_1/tests/ >
   <directory>./*/*/tests/</directory>
</testsuite>
<testsuites>
```

(FYI: In our case the setup is even more complex, because each `tests/` directory has the three sub-directories [Unit, Integration, End2End] that are also defined as dedicated test suites)

If `phpunit` would support the `'**'` pattern, this could be simplified as follows

```xml
<testsuites>
  <testsuite name="Full Suite">
   <directory>./**/tests/</directory>
</testsuite>
<testsuites>
```

## Details
The [current implementation](https://github.com/sebastianbergmann/php-file-iterator/blob/5647d65443818959172645e7ed999217360654b6/src/Factory.php#L95) uses the native `glob` function to resolve the  test files for a testsuite, see `\SebastianBergmann\FileIterator\Factory::resolveWildcards()`; 

```php
    private function resolveWildcards(array $paths): array
    {
        $_paths = [[]];

        foreach ($paths as $path) {
            if ($locals = glob($path, GLOB_ONLYDIR)) {  // <---------
                $_paths[] = array_map('\realpath', $locals);
            } else {
                // @codeCoverageIgnoreStart
                $_paths[] = [realpath($path)];
                // @codeCoverageIgnoreEnd
            }
        }

        return array_values(array_filter(array_merge(...$_paths)));
    }
```

`glob` does not support the `'**'` pattern to match 'zero or more directory names' (I belive it is interpreted like a single '*'). 

FYI: This is also mentioned in https://github.com/webmozarts/glob as a distinction:

> Compared to PHP's native glob() function, this utility supports:
> - /**/ for matching zero or more directories

**Comment by sebastianbergmann** [comment]
Superseded by #5933.
