### ISSUE TITLE
Pointing to empty tests file results in non-zero exit but no errors printed

### ISSUE THREAD

**Issue by davwheat** [sebastianbergmann/phpunit#5361]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.1.3
| PHP version         | 8.1.18
| Installation Method | Composer

#### Summary

PHPUnit can exit with a non-zero status without any explanation provided.

#### Current behavior

If a `phpunit.xml` configuration points to a directory that contains a PHP file but has no tests, PHPUnit will exit with code 1, but not display any meaningful warnings or errors in its output.

#### How to reproduce

**Config:**

```xml
    <testsuites>
        <testsuite name="Unit">
            <directory suffix="Test.php">./tests/Unit</directory>
        </testsuite>
        <testsuite name="Feature">
            <directory suffix="Test.php">./tests/Feature</directory>
        </testsuite>
    </testsuites>
```

**`tests/Unit/ExampleTest.php`:**
```php
<?php

namespace Tests\Unit;

use PHPUnit\Framework\TestCase;

class ExampleTest extends TestCase
{
}
```

**Output:**

```
david@David-XPS15:~/cacombos-api$ php artisan test
$
   PASS  Tests\Feature\OtherTest
  ✓ other test passes                                            1.22s

  Tests:    1 passed (21 assertions)
  Duration: 1.22s

david@David-XPS15:~/cacombos-api$ $?
1: command not found
```

#### Expected behavior

Either:

1. PHPUnit should exit with code 0, as it does when *no files* are in the tests directory, or
2. PHPUnit should state why it is exiting with a non-zero status

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

"Minimal" means without third-party extensions for / wrappers around PHPUnit's test runner.

**Comment by davwheat** [comment]
Sorry, this is Collision's fault I think. My bad.
