### ISSUE TITLE
A method to mock a readonly class, such as ::createReadonlyMock()

### ISSUE THREAD

**Issue by CxDevLead** [sebastianbergmann/phpunit#5386]
It is a little silly that, it is acceptable to mock:

```
class Foo
{
   public function __construct(
       private readonly int $bar,
   ){}
}
```

But it is unacceptable to mock:

```
readonly class Foo
{
   public function __construct(
       private int $bar,
   ){}
}
```

While I understand the reasons that a readonly class should not be extended by a mutable class, especially in the context of a projects working code, from a test perspective that restriction is simply a hindrance.

My feature request is to implement a createReadonlyMock(), that adheres to the readonly PHP requirements.

**Comment by sebastianbergmann** [comment]
Please read https://github.com/sebastianbergmann/phpunit/issues/5353#issuecomment-1535696396.

**Comment by CxDevLead** [comment]
I already read that thread. It doesn't resolve the issue and this shouldn't be closed.
