### ISSUE TITLE
`PHPUnit\Framework\Exception` should extend `\Error`

### ISSUE THREAD

**Issue by mvorisek** [sebastianbergmann/phpunit#5396]
https://github.com/sebastianbergmann/phpunit/blob/9.6.8/src/Framework/Exception/Error.php#L15 should extend `\Error` instead of `\Exception`.

in 10.x it extends `RuntimeException` which still extends `\Exception` - https://github.com/sebastianbergmann/phpunit/blob/10.1.3/src/Framework/Exception/Exception.php#L42

`\Error` class represents an exception that should not be handled and the exceptions by phpunit should not be definitely handled by non-phpunit applications.

I found this during debugging a test inside which a php/phpunit notice exception (`PHPUnit\Framework\Error\Notice`) was emit and handled by https://github.com/atk4/ui/blob/db7e4336b521b0dc5403f6c8fe468c4fb0815014/src/Form.php#L465 which captured that (internal, not-to-be-handled) exception and supressed it wrongly.

**Comment by sebastianbergmann** [comment]
PHPUnit 9.6 is closed for changes that are not bug fixes.

**Comment by mvorisek** [comment]
In PHP 10.x this issue is still present.
