### ISSUE TITLE
To preserve behavior, configuration migration should set `displayDetailsOnTestsThatTrigger*` and `failOn*` when `convert*ToExceptions` was set

### ISSUE THREAD

**Issue by anomiex** [sebastianbergmann/phpunit#5406]
In earlier versions of PHPUnit, `convert*ToExceptions` settings could be used to cause tests to fail if PHP deprecations, notices, warnings, or errors were raised.

People who had these options set (explicitly or by default) probably still want the corresponding behavior in PHPUnit 10 even after the separation of test issues and test outcomes. If they didn't want the behavior, they'd probably have turned them off.

Thus I think the least surprising behavior for migrated configurations would be to have phpunit continue to display the messages and to exit with a non-zero exit code by setting the corresponding `displayDetailsOnTestsThatTrigger*` and `failOn*` settings in the migrated configuration.

I suspect you'll disagree and close this, but I may as well ask since it doesn't seem anyone has actually asked about this before.

**Comment by anomiex** [comment]
P.S. Even better would be to more closely preserve the past behavior by having `failOnDeprecation` and `failOnWarning` not apply to runner-triggered deprecations and warnings, but you already denied the latter in https://github.com/sebastianbergmann/phpunit/issues/5199#issuecomment-1437122132 so I certainly don't expect that one to change.

**Comment by sebastianbergmann** [comment]
This is out of scope for XML configuration file migration.
