### ISSUE TITLE
array_column is not working correctly with mocks

### ISSUE THREAD

**Issue by classicalguss** [sebastianbergmann/phpunit#5407]
PHPUnit version | 9.6.8
PHP version | 8.1.18
Installation method | Composer

Summary

If I created a mock and passed properties to it, array_column does not fetch these properties, despite the fact that any class in php is able to give array_column the properties that are required

#### How to reproduce

```
$myMock = $this->getMockBuilder('DbClass')
                ->disableOriginalConstructor()
                ->getMock();
        $myMock->conversation_id = 1;
        $myMockArray = [$myMock];
```
      
#### Expected behavior

  `print_r(array_column($myMockArray, 'conversation_id'));`
Should output 
```
Array
(
    [0] => 1
)
```

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by classicalguss** [comment]
Thank you for your reply @sebastianbergmann , although I tried for endless hours yesterday to fix it, it just occurred to me now that I needed to provide both __get and __isset expectations.

			$myMock->method('__get')->with('conversation_id')->willReturn($i);
			$myMock->method('__isset')->with('conversation_id')->willReturn(true);
