### ISSUE TITLE
Subscriber "PHPUnit\Event\Test\DataProviderMethodCalledSubscriber" does not exist or is not an interface

### ISSUE THREAD

**Issue by Mr-Leonerrr** [sebastianbergmann/phpunit#5408]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.2.2
| PHP version         | 8.2.5
| Installation Method | Composer

#### Summary

After installing version 10 of the dependency, this error appears when querying the version with the command `./vendor/bin/phpunit --version`

#### Current behavior

Dependency cannot be used in this version

#### How to reproduce

- Install `phpunit` via composer
```shell
composer require --dev phpunit/phpunit
```
- Run command
```shell
./vendor/bin/phpunit --version
```
- See the error

#### Expected behavior

To be able to use any dependency-related command without getting errors.

#### Optional  Screenshots
![image](https://github.com/sebastianbergmann/phpunit/assets/56647065/6f19206c-52ab-4818-a36f-f5f57f134940)

**Comment by sebastianbergmann** [comment]
It appears that you have different installations of PHPUnit mixed up.

For instance, you may have used Composer to install PHPUnit and have configured the autoloader generated by Composer as PHPUnit's bootstrap script but then you invoke PHPUnit using an executable other than `vendor/bin/phpunit`.
