### ISSUE TITLE
Handle silenced deprecations

### ISSUE THREAD

**Issue by ro0NL** [sebastianbergmann/phpunit#5410]
Hi,

Symfony always silence deprecations, it doesnt play well with `displayDetailsOnTestsThatTriggerDeprecations`

I was told it should be fixed in phpunit: https://github.com/symfony/symfony/pull/50678#issuecomment-1594289542

I dont really mind, i just like to see deprecations in tests :)

**Comment by sebastianbergmann** [comment]
Please see #5328.
