### ISSUE TITLE
Distribute phpunit phar using composer

### ISSUE THREAD

**Issue by ro0NL** [sebastianbergmann/phpunit#5414]
Hi,

Im contemplating on creating a composer package that distributes the phpunit phar, thus without dependencies.

Similar like https://github.com/psalm/phar

This allows to benefit from existing composer infrastructure, mainly dependabot :)

Before i begin, i need to ask:
- does this already exist? (i know i can wget the phar, but i need dependabot updates)
- would it be considerable making it an official package?
- is there a shorter route? :grimacing: 

My idea is:

composer require --dev phpunit/phpunit
let dependabot manage that version constraint
let github actions commit the phar and tag it
...
composer require phpunit/phar
profit :)

**Comment by sebastianbergmann** [comment]
> does this already exist?

Not that I know of.

> would it be considerable making it an official package?

No.

**Comment by ro0NL** [comment]
for those curious:

```
wget -qO vendor/bin/phpunit "https://phar.phpunit.de/phpunit-$(composer show --locked --self --format=json | jq -r '.requires."phpunit/phpunit"[1:]' | cut -d'.' -f1-2).phar"
```

**Comment by Wulfheart** [comment]
@ro0NL what does this snippet do? 

I created a shim package for my own purposes for this but I have the issue that it is not executable from the bin folder. See the corresponding issue here: https://stackoverflow.com/questions/76700299/troubleshooting-issue-phpunit-phar-file-not-executing-properly-from-bin-direc

**Comment by ro0NL** [comment]
@Wulfheart ive listed phpunit in our tools composer.json: https://github.com/etrias-nl/development-image/tree/main/tools/php-8.1

renovate manages the latest version

docker build downloads the phar as such: https://github.com/etrias-nl/development-image/blob/330b678ad1e1426f4bba4d9f8e3456ed98b92ad1/Dockerfile_81#L106

at this point we assume we're always at the latest patch release, since we can only download X.Y.phar

**Comment by Wulfheart** [comment]
@ro0NL Thanks for the explanation.

Would you mind to try the package `wulfheart/phpunit-shim` and help me find out why it does not run when executed from `vendor/bin/phpunit.phar`?

**Comment by ro0NL** [comment]
sounds like a chmod issue :shrug:

**Comment by Wulfheart** [comment]
@ro0NL Tried it out. They have the same permissions.
