### ISSUE TITLE
Comma in method argument without following argument leads to parse error

### ISSUE THREAD

**Issue by NORDCOMPCZ** [sebastianbergmann/phpunit#5418]
There is a trailing comma:
https://github.com/sebastianbergmann/phpunit/blob/6136d74691963e3c368e1e0ac5d0f251c084c940/src/Framework/Assert/Functions.php#L2586
which can/will lead to parsing error

**Comment by NORDCOMPCZ** [comment]
seems to be intentional: https://github.com/sebastianbergmann/phpunit/commit/2479058c9fc4325f88be2e1e8a2c8e5cb270b53e

**Comment by sebastianbergmann** [comment]
Support for trailing commas in function and method calls was added in PHP 7.3.

The tests for PHPUnit 9.6 are run against PHP >= 7.3, as you can see here: https://github.com/sebastianbergmann/phpunit/actions/runs/5308658904. They do not fail for PHP 7.3 and PHP 7.4.

I assume you are not using the version of PHP you think you are using.
