### ISSUE TITLE
Remove `MockBuilder::enableAutoReturnValueGeneration()` and `MockBuilder::disableAutoReturnValueGeneration()`

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#5422]
Follows  #5421.

**Comment by mattjanssen** [comment]
Oh no 😢 Is there an alternative way of disabling auto generation? Every now and then we write tests that pass only because the auto-generated values happened to function, but it is more or less random, and was certainly not intentional.

We would prefer that when a class has an external dependency, that we automatically fail oblivious tests that just _happen to pass_ due to this auto-gen behavior. Sometimes they _happen to fail_ too, and that's fine of course.

It's funny when tests pass with inappropriate dependency use. By always failing—and not sometimes passing—tests when a dependency is unexpectedly queried, we can be sure we're not getting undeserved PHPUnit blessings.

**Comment by sebastianbergmann** [comment]
No alternative is planned.

**Comment by mattjanssen** [comment]
The stated reason for removing this feature is to reduce complexity. But if a feature dissuades a bad practice—in this case unintentional dependency response—is the gain (decluttering) still worth the cost (false-positive tests)?

**Comment by sebastianbergmann** [comment]
Please do not conflate two issues. Of course, I do not think that reducing complexity may come at the cost of encouraging bad practice. However, I am not convinced that removing the option to disable the return value generator encourages bad practice and/or leads to false positive tests. If you can convince me of that, and maybe that only requires rephrasing what you wrote in https://github.com/sebastianbergmann/phpunit/issues/5422#issuecomment-1808201043 and/or showing me a real-world example, then I will be more than happy to 1) not remove the option to disable the return value generator encourages in PHPUnit 12 and 2) revert the deprecation of that option in PHPUnit 11.

**Comment by mattjanssen** [comment]
Here's a pattern that I've often seen. These two tests are nearly identical and both produce 100% coverage. The first (without `disableAutoReturnValueGeneration`) passes while the second (with `disableAutoReturnValueGeneration`) fails.

I think the first is a good example of a false-positve test that could have been detected by disabling the auto return generator. We've found this so useful that we've overridden `TestCase::getMockBuilder()` to do this on every test by default.

```php
class ExternalService {
    public function itemExists(string $title): bool
    {
        return true;
    }

    public function createItem(string $title): void
    {
    }
}

class InternalSerice {
    public function __construct(
        private readonly ExternalService $externalService,
    ) {
    }

    public function createItem(string $title): void
    {
        if (!$this->externalService->itemExists($title)) {
            $this->externalService->createItem($title);
        }
    }
}

class AutogenTest extends TestCase
{
    public function testAutogenOn(): void
    {
        $externalService = $this->getMockBuilder(ExternalService::class)
            ->getMock();
        $externalService->expects(self::exactly(1))->method('createItem')->with('My Item');

        $sut = new InternalSerice($externalService);

        $sut->createItem('My Item');
    }

    public function testAutogenOff(): void
    {
        $externalService = $this->getMockBuilder(ExternalService::class)
            ->disableAutoReturnValueGeneration()
            ->getMock();
        $externalService->expects(self::exactly(1))->method('createItem')->with('My Item');

        $sut = new InternalSerice($externalService);

        $sut->createItem('My Item');
    }
}

```

**Comment by sebastianbergmann** [comment]
I have reversed the deprecation.

**Comment by mattjanssen** [comment]
Thank you Sebastian 🙏

Looking forward to SymfonyCon in a few weeks!
