### ISSUE TITLE
Deprecate `InvocationMocker::willReturnOnConsecutiveCalls()`

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#5425]
To reduce complexity inside PHPUnit's test double functionality, `InvocationMocker::willReturnOnConsecutiveCalls()` will be deprecated and then removed:

- soft deprecation in PHPUnit 10.3 (add `@deprecated` annotation to the method declaration)
- deprecation in PHPUnit 11 (using the method will trigger a deprecation)
- removal in PHPUnit 12

**Comment by TechhDan** [comment]
Hi! If anyone is looking for a replacement for this method this one has helped me out.

```
$userCallCount = 0;
$this->user->expects($this->exactly(2))
    ->method('__get')
    ->willReturnCallback(function ($name) use (&$userCallCount) {
        $userCallCount++;
        switch ($userCallCount) {
            case 1:
                return 1;
            case 2:
                return 2;
        }
    });
```

**Comment by sebastianbergmann** [comment]
Apparently ...

![grafik](https://github.com/sebastianbergmann/phpunit/assets/25218/a333ece7-7e4a-48c8-bd69-d54f63a4aa23)

... was not enough and an explicit comment is needed: `InvocationStubber::willReturnOnConsecutiveCalls()` is no longer deprecated.

**Comment by nicolas-grekas** [comment]
Thank you, I missed it indeed :)

**Comment by m-strzalka** [comment]
So it is no longer deprecated and will stay as a feature for the foreseeable future?
