### ISSUE TITLE
Wrap deprecations in a group when running in GitHub actions

### ISSUE THREAD

**Issue by ro0NL** [sebastianbergmann/phpunit#5435]
Hi,

Would it be considerable to wrap the blob output below `N tests triggered N PHP deprecations:` in a group when env `GITHUB_ACTION` is set.

```
echo "::group::N tests triggered N PHP deprecations"
<blob>
echo "::endgroup::"
```

**Comment by sebastianbergmann** [comment]
I am not convinced that adding product-specific features such as this should be added. I think the way to go would be to implement an extension for PHPUnit's test runner that replaces the default progress and result output with something specific to GitHub actions.

**Comment by ro0NL** [comment]
we can argue deprecations are always 2nd-class-results (noise), and this is a product-specific implementation detail

or put different, IMHO it doesnt need be extensible

but then again, it's also just 'cosmetic details', it's not a blocker

feel free to reconsider ;)
