### ISSUE TITLE
`-v` should imply details for every kind (skipped, notices, deprecations, ...)

### ISSUE THREAD

**Issue by mvorisek** [sebastianbergmann/phpunit#5440]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.2.3
| PHP version         | 8.2
| Installation Method | Composer

#### Current behavior

In phpunit 9.x we used `-v` for CI which displayed every "non-fully-ok" test.

#### How to reproduce

run phpstan with `-v` option

#### Expected behavior

In phpunit 10.x I expect the same, when phpunit is run with `-v` option, I expect all problems, ie. tests not displayed as `.`, to be detailed.

Currently, even with `--fail-on-deprecation`, no details are displayed:
```
PHPUnit 10.2.3 by Sebastian Bergmann and contributors.
Runtime:       PHP 8.2.8
Configuration: /builds/xxx/test-project/prefix-phpunit.xml.dist
............D                                                     13 / 13 (100%)
Time: 00:03.243, Memory: 6.00 MB
There was 1 PHPUnit test runner deprecation:
1) Your XML configuration validates against a deprecated schema. Migrate your XML configuration using "--migrate-configuration"!
OK, but there are issues!
Tests: 13, Assertions: 222, Deprecations: 2.
```
which fails the CI correctly, but it is impossible to tell the problem (exact test which emit the deprecation warning).

**Comment by sebastianbergmann** [comment]
There is no bug here, everything works as intended.

**Comment by mvorisek** [comment]
So what `-v` does and why this was changed? So now I need to list all https://docs.phpunit.de/en/10.0/textui.html#details-about-issues options to do the same? Is this documented somewhere, what displays have been removed from `-v`?

In CI, I can use long command, but localy, do I really need to specify all these options too? Is there any short option how to display every problem like before?

**Comment by sebastianbergmann** [comment]
`-v` / `--verbose` were removed in PHPUnit 10.0.

**Comment by mvorisek** [comment]
In CI, I replaced it by `--display-notices --display-deprecations --display-warnings --display-errors --display-incomplete --display-skipped`. But I double every CI maintainer will. Also, when I run phpunit localy and I need to figure out what test emits a warning for example, `-v` was very handy. Can `-v` be introduced back as an alias for `--display-notices --display-deprecations --display-warnings --display-errors --display-incomplete --display-skipped`?

**Comment by sebastianbergmann** [comment]
> Can `-v` be introduced back as an alias for `--display-notices --display-deprecations --display-warnings --display-errors --display-incomplete --display-skipped` as a feature request?

No. Adding such "enable everything" options have been proven problematic in the past.
