### ISSUE TITLE
Restore behaviour that tests are not considered risky when they errored before an assertion was performed

### ISSUE THREAD

**Issue by stof** [sebastianbergmann/phpunit#5443]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.2.3
| PHP version         | 8.2.8
| Installation Method | Composer

#### Summary

When a test triggers an error instead of running until its end, it is properly marked as having an error outcome. However, as of PHPUnit 10, it also gets reported as a risky test due to not performing assertions

#### How to reproduce

Create a test which will trigger some unexpected error before the first assertion.

#### Expected behavior

To me, the check on assertion count should not be applied to tests in the error state, because those tests got interrupting before running fully.

**Comment by stof** [comment]
Note that older versions of PHPUnit were not marking such tests as risky.

**Comment by sebastianbergmann** [comment]
> Note that older versions of PHPUnit were not marking such tests as risky.

I know. This was an intentional change. But I no longer agree with myself from a couple of weeks ago :-) Sorry about that. And thanks for opening this ticket.
