### ISSUE TITLE
Decouple printing of unexpected output from progress printer

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#5445]
> PHPUnit uses PHP's output buffering to capture output made by test(ed) code. When the test does not perform assertions on captured output then the output is considered unexpected and an `PrintedUnexpectedOutput` event is emitted. The `ProgressPrinter` (which is controlled by the `--no-progress` CLI option) is currently not only responsible for printing progress (`.`, `E`, `F`, ...) but also for printing unexpected output.

_Originally posted by @sebastianbergmann in https://github.com/sebastianbergmann/phpunit/issues/5367#issuecomment-1635515098_

**Comment by SakiTakamachi** [comment]
@sebastianbergmann 
Thank you for your very quick fix!
