### ISSUE TITLE
Warnings are not shown

### ISSUE THREAD

**Issue by brendt** [sebastianbergmann/phpunit#5446]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.2.4
| PHP version         | 8.2
| Installation Method | Composer

#### Summary

Warnings and deprecation notices aren't shown

#### Current behavior

Warnings and deprecation notices aren't shown

#### How to reproduce

I think I have a pretty default phpunit.xml?

```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/10.2/phpunit.xsd" bootstrap="vendor/autoload.php" colors="true">
  <testsuites>
    <testsuite name="Unit">
      <directory suffix="Test.php">./tests</directory>
    </testsuite>
  </testsuites>
  <coverage/>
  <source>
    <include>
      <directory suffix=".php">./src</directory>
    </include>
  </source>
</phpunit>
```

And I run phpunit simply by calling `vendor/bin/phpunit`

#### Expected behavior

Warnings to be shown

**Comment by sebastianbergmann** [comment]
This is not a bug. You need to use `--display-warnings`, for instance, to see detailed information.

**Comment by brendt** [comment]
Thanks! I do wonder how this works with PhpStorm now? We don't have the option to pass in flags to the phpunit comment, and I don't see this option available in the phpunit.xml scheme? (https://phpunit.de/manual/6.5/en/appendixes.configuration.html)

**Comment by brendt** [comment]
Update, obvious in hindsight: I was looking at the wrong docs. [https://docs.phpunit.de/en/10.2/configuration.html this one ](https://docs.phpunit.de/en/10.0/configuration.html#the-displaydetailsonteststhattriggerwarnings-attribute) these are the up-to-date ones.

@sebastianbergmann I don't know if it's possible, but you might want to look at invalidating these google results via google search console: https://www.google.com/search?q=phpunit.xml&rlz=1C5CHFA_enBE940BE940&oq=phpunit.xml&aqs=chrome.0.69i59j0i512j69i64j0i512l4j69i60.3038j0j7&sourceid=chrome&ie=UTF-8
