### ISSUE TITLE
Error `assertSame()` fails with string equals.

### ISSUE THREAD

**Issue by terabytesoftw** [sebastianbergmann/phpunit#5449]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.6.10
| PHP version         | 8.1.13
| Installation Method | Composer 

#### Summary

```php
$result = $db->cache($function); // 'a:1:{s:13:"template";s:1:"1";}'
$this->assertSame('a:1:{s:13:"template";s:1:"1";}', $result);
```

Let the test pass.

#### Current behavior

```shell
1) mssql\CommandTest::testQueryCacheBlob
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'a:1:{s:13:"template";s:1:"1";}'
+'a:1:{s:13:"template";s:1:"1";}'
```

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by terabytesoftw** [comment]
Hi, reviewing in depth, we were able to detect the error that had hidden characters, the assertion works correctly, thanks for your work to open source.
