### ISSUE TITLE
[Feature] Pest Expectations style API

### ISSUE THREAD

**Issue by julien-boudry** [sebastianbergmann/phpunit#5450]
[PestPHP](https://github.com/pestphp/pest) is really trendy for various reasons. He undoubtedly has the qualities, and without getting into the debate, probably has as much reason to be loved as dismissed.

Personally, if I'm cautious about certain aspects, there's one I think is excellent: that's the Expectations API.
https://pestphp.com/docs/expectations

Pest also support the three PHPUnit API styles _($this, self::, function)_, perfectly compatible because it's built on top of PHPUnit with a lot of magic.

Could be great if PHPUnit supports natively, additionally to the existing API, the Pest style for Expectation.
For me, this would remove Pest's main argument for migration. All that would remain would be a stylistic and philosophical debate.

**Comment by sebastianbergmann** [comment]
Feel free to use Pest if you prefer its features such as the expectations API.

**Comment by julien-boudry** [comment]
But I prefer PHPUnit for many other things ;)

@sebastianbergmann 
I've just tested, successfully, and surprisingly, that Pest's expect() function is already functional in PHPunit, for tests with PHPUnit style an run with PHPUnit. If Pest is installed of course. And all of it seems to behave normally.

I don't know if it's a good idea to use this if this compatibility would be maintained in the long term.
