### ISSUE TITLE
Add attribute to <coverage> to remove assumptions of always wanting coverage reports

### ISSUE THREAD

**Issue by digiservnet** [sebastianbergmann/phpunit#5453]
If you have a `<coverage>` section defined in the config file, PHPUnit assumes that you always want to generate coverage and PHPUnit generates a warning:

```bash
There was 1 PHPUnit test runner warning:

1) XDEBUG_MODE=coverage or xdebug.mode=coverage has to be set
```

Generating code coverage while using TDD (and just running tests in general) is probably not the norm for most people(?) and will run a coverage report across the whole suite as a dedicated action.

Adding an option to disable this warning would be a nice DX addition IMO.

**Comment by sebastianbergmann** [comment]
There is nothing to improve (or fix) here.

When you have `<coverage><report><html outputDirectory="build/code-coverage/html" /></report></coverage>` in your XML configuration file then you are configuring PHPUnit's test runner to **always** collect code coverage data and to generate the configured report(s).

When you do not want PHPUnit's test runner to collect code coverage data and to generate the configured report(s) then you need to pass the `--no-coverage` CLI option. This instructs PHPUnit's test runner to ignore any code coverage reporting configured in the XML configuration file.
