### ISSUE TITLE
`assertStringMatchesFormat()` should allow `string` type (not `non-empty-string`) for `$actual` parameter

### ISSUE THREAD

**Issue by mpyw** [sebastianbergmann/phpunit#5459]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.3.0

#### Summary

I encountered an issue that was introduced with the commit 9f7422c labeled *"Narrow types"*. This change seems to have modified the expected type for certain arguments in the `assertStringMatchesFormat()` method, from `string` to `non-empty-string`.

```php
    /**
     * Asserts that a string matches a given format string.
     *
     * @psalm-param non-empty-string $format
     * @psalm-param non-empty-string $string
     *
     * @throws ExpectationFailedException
     */
    final public static function assertStringMatchesFormat(string $format, string $string, string $message = ''): void
    {
        static::assertThat($string, new StringMatchesFormatDescription($format), $message);
    }
```

This change has led to the issue where previously valid code now fails. An example of such a scenario is:

```php
$this->assertStringMatchesFormat(
    '%x-%x-%x-%x-%x',
    (new UuidGenerator())->generate(),
);
```

In this case, unless the `generate()` method explicitly returns a `non-empty-string`, this piece of code will fail due to the newly implemented type restriction.

While I understand the intention to ensure meaningful strings are passed into the method, requiring `non-empty-string` as the type for all `$actual` parameters might be too restrictive. This could potentially break a significant amount of code that previously ran without issues.

Could you please clarify whether this change was intentional and discuss the possibility of revisiting this requirement? The concept of a non-empty string being a subtype of a string suggests that this change could exclude valid use-cases, particularly when interfacing with methods that do not provide a non-empty-string guarantee but are nevertheless valid.

#### Current behavior

Fails

```
 ------ --------------------------------------------------------------- 
  Line   tests/Example.php                                  
 ------ --------------------------------------------------------------- 
  XX     Parameter #2 $string of method                                 
         PHPUnit\Framework\Assert::assertStringMatchesFormat() expects  
         non-empty-string, string given.                                
 ------ --------------------------------------------------------------- 
```

#### Expected behavior

Passes

**Comment by mpyw** [comment]
I am certain that the requirement for `$actual` to be a `non-empty-string` is a mistake. However, while I understand the reasoning for changing `$expected` to `non-empty-string`, I believe such a modification should not be made in a minor version upgrade (like from 10.2 to 10.3), but rather in a major one. This is unquestionably a breaking change.

**Comment by sebastianbergmann** [comment]
The changes have been reverted.
