### ISSUE TITLE
Please restore testdox output in PHPUnit 10

### ISSUE THREAD

**Issue by bilogic** [sebastianbergmann/phpunit#5463]
1. CI/CD on GitHub and Gitea print their outputs on a line by line basis
2. Using the `....FFEFF.F..III....I.II...`, there is no output as the tests are on-going until a line is full
3. If there are many tests and the tests are slow, it takes a while before we can tell what is going on
4. Please have a look at Laravel's `php artisan test` output, I think most will agree it is much more helpful than `....FFEFF.F..III....I.II...`

**Comment by sebastianbergmann** [comment]
You can implement your own progress and/or result printing that prints one line per test that is run.

**Comment by borys-p** [comment]
@sebastianbergmann why should we do that if it was already there and working perfectly fine?
