### ISSUE TITLE
PHP CGI file not found

### ISSUE THREAD

**Issue by LeonardoCor** [sebastianbergmann/phpunit#5465]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.1.3
| PHP version         | 8.2.7
| Installation Method | Composer

#### Summary

Using php-cgi instead of php results in test files not found

#### Current behavior

if I change `php` to `php-cgi` in command line, test files, normally found and regularly run with `php`, are not found anymore.

#### How to reproduce

Substitute `php` with `php-cgi` in command line to execute tests as usual.

#### Expected behavior

Test files usually found and run using `php` are no longer found using `php-cgi`

**Comment by sebastianbergmann** [comment]
`php-cgi` is not supported, you need to the PHP CLI interpreter.
