### ISSUE TITLE
Support --exclude-filter to exclude tests matching the exclude-filter expression

### ISSUE THREAD

**Issue by krchiper** [sebastianbergmann/phpunit#5467]
Make support to exclude certain tests by name, just like how `--exclude-groups` can exclude tests by group. The option could be called `--exclude-filter` and should run all tests except those matching the `--exclude-filter`, the expression should work like the inverse of `--filter`, just like `--exclude-group` is the inverse of `--group`

*Use case*
If you want to divide all your tests into seperate runners it is convient to analyze the output from last test run (e.g. junit.xml) and create a filter so you can get X seperate runners. If you use explicit filters for all runners, you won't discover new tests added.

Example:
Runner1 - Slice A: phpunit --filter /^testa|testb|testc$/
Runner2 - Slice B: phpunit --filter /^testd|teste|testf$/
Runner3 - Slice Rest: phpunit --exclude-filter /^testa|testb|testc|testd|teste|testf$/

Runner3 is supposed to run everything which is not part of Runner1 and 2.

**Comment by sebastianbergmann** [comment]
#5629 has been merged for PHPUnit 11.
