### ISSUE TITLE
testdox : sort output by test suite

### ISSUE THREAD

**Issue by IngeniozIT** [sebastianbergmann/phpunit#5468]
Currently, when using `--testdox` (or any `testdox-*`), the output is sorted by test class name.
However, since testdox can be used to generate some form of documentation, it would be more readable to first sort the output by test suite.

# Example

## Test structure

- testsuite1
  - a class (from testsuite 1)
  - c class (from testsuite 1)
- testsuite 2
  - b class (from testsuite 2)
  - d class (from testsuite 2)

## Current output
- a class (from testsuite 1)
  - a class tests
- b class (from testsuite 2)
  - b class tests
- c class (from testsuite 1)
  - c class tests
- d class (from testsuite 2)
  - d class tests

You can see that the test suites are mixed up.

## Desired output
- a class (from testsuite 1)
  - a class tests
- c class (from testsuite 1)
  - c class tests
- b class (from testsuite 2)
  - b class tests
- d class (from testsuite 2)
  - d class tests

All tests coming from a test suite are grouped together.

**Comment by sebastianbergmann** [comment]
This is outside the scope of this project, sorry.

My suggestion to achieve what you are looking for would be to implement your own report using a test runner extension. Subscribe to the relevant test suite and test events, collect the information you need while the tests are running, and then sort and print the TestDox output once all tests have been run.
