### ISSUE TITLE
`setUp` method counts towards codeCoverage regardless of `@coversNothing` annotation

### ISSUE THREAD

**Issue by bkdotcom** [sebastianbergmann/phpunit#5474]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.6.10
| PHP version         | 8.2.x
| Installation Method | Composer

#### Summary / Current behavior

Code executed in TestCase's `setUp` method is counting towards code coverage

#### Expected behavior

code executed in setUp should NOT count towards code coverage... certainly not when `@coversNothing`  is added  to `setUp`

_(I currently don't have an easy way to test this behavior with PhpUnit 10)_

**Comment by sebastianbergmann** [comment]
Please open a new ticket if this problem still exists in PHPUnit 10 or PHPUnit 11 and provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.
