### ISSUE TITLE
Add `assertObjectHasProperty()` and `assertObjectNotHasProperty()` to PHPUnit 9.6

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#5478]
The assertions `assertObjectHasAttribute()` and `assertObjectNotHasAttribute()` were removed in PHPUnit 10.0. When this decision was made and the change implemented, there was no replacement planned for these methods.

PHPUnit 9.6 was released alongside PHPUnit 10.0 to warn about functionality that was removed in PHPUnit 10.0. This is why PHPUnit 9.6.0 deprecated `assertObjectHasAttribute()` and `assertObjectNotHasAttribute()` without suggesting an alternative.

The functionality was reintroduced, using new methods names `assertObjectHasProperty()` and `assertObjectNotHasProperty()`, in PHPUnit 10.1 because users [convinced](https://github.com/sebastianbergmann/phpunit/issues/5220) me that it is useful (I never had to use it myself). As of PHPUnit 9.6.7, the deprecations suggest to use these new methods.

This series of events lead to a mess that was discussed in #5448 as well as [here](https://github.com/sebastianbergmann/phpunit/issues/5220#issuecomment-1650397079) and [here](https://phpc.social/@Crell/110855508146647896), for instance.

To fix this mess, I will add `assertObjectHasProperty()` and `assertObjectNotHasProperty()` to PHPUnit 9.6.

**Comment by dregad** [comment]
May I suggest to update the @deprected notices in 9.6 PHPDoc blocks referencing #4601, to point to this Issue instead (e.g. assertObjectHasAttribute(),  assertClassHasStaticAttribute(), etc) ?

Alternatively, edit #4601's description to add a link to here.
