### ISSUE TITLE
Details about tests that are considered risky are not displayed when the TestDox result printer is used

### ISSUE THREAD

**Issue by ghostwriter** [sebastianbergmann/phpunit#5488]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.x
| PHP version         | 8.2.9
| Installation Method | Composer & PHAR

#### Summary

When test's are marked risky , while using `--testdox` the error messages are not printed, even with `--display-*` set.

#### Current behavior

The error message is not printed.

#### How to reproduce

```
--TEST--
Testdox: Missing force-covers-annotation error messages "This test does not define a code coverage target but is expected to do so".
--FILE--
<?php declare(strict_types=1);
$_SERVER['argv'][] = '--do-not-cache-result';
$_SERVER['argv'][] = '--testdox';
$_SERVER['argv'][] = '--display-errors';
$_SERVER['argv'][] = '--display-notices';
$_SERVER['argv'][] = '--display-warnings';
$_SERVER['argv'][] = '--display-deprecations';
$_SERVER['argv'][] = '--strict-coverage';
$_SERVER['argv'][] = '--configuration';
$_SERVER['argv'][] = __DIR__ . '/../_files/force-covers-annotation/phpunit.xml';
$_SERVER['argv'][] = __DIR__ . '/../_files/force-covers-annotation/tests/Test.php';

require_once __DIR__ . '/../../bootstrap.php';

(new PHPUnit\TextUI\Application)->run($_SERVER['argv']);
--EXPECTF--
PHPUnit %s by Sebastian Bergmann and contributors.

Runtime: %s
Configuration: %s

R                                                                   1 / 1 (100%)

Time: %s, Memory: %s

Unnamed Tests (PHPUnit\TestFixture\UnnamedTests)
 ☢ One

OK, but there were issues!
Tests: 1, Assertions: 1, Risky: 1.
```

#### Expected behavior

I expect "This test does not define a code coverage target but is expected to do so" to be printed under the method name.

**Comment by ghostwriter** [comment]
Maybe Related #5437

**Comment by sebastianbergmann** [comment]
The fix for this requires the changes that will be made for #5518 (or at least will be easier after these changes).

**Comment by sebastianbergmann** [comment]
I will work on this immediately after https://github.com/sebastianbergmann/phpunit/issues/5518#issuecomment-1872492479.
