### ISSUE TITLE
Support for $database['pdo'][1009] 

### ISSUE THREAD

**Issue by Trigve-Hagen** [sebastianbergmann/phpunit#5491]
When you are using phpunit with Azure database and you are using a secure connection to the database with $database['pdo'][1009] = 'path/to/cetificate.file' you get an error asking for a certificate. Not sure if this is a new feature but I could not find any information on it after tons of searching. I can create a patch for Connection.php that accept the path via a query parameter.

`if(isset($url_components['query'])) {
    $parts = parse_url($url);
    parse_str($parts['query'], $query);
    if(isset($query['pdo_pem_path'])) {
      $database['pdo'] = array(
         \PDO::MYSQL_ATTR_SSL_CA => $query['pdo_pem_path'],
      );
    }
 }`

**Comment by sebastianbergmann** [comment]
I do not see how this has anything to do with PHPUnit.

**Comment by Trigve-Hagen** [comment]
Love you work!
