### ISSUE TITLE
PHP Fatal error: Maximum execution time exceeded

### ISSUE THREAD

**Issue by MauricioFauth** [sebastianbergmann/phpunit#5494]
I don't think this is a bug in PHPUnit, however I'm getting fatal errors like those in CI sometimes.

- https://github.com/phpmyadmin/phpmyadmin/actions/runs/6042689927/job/16398306791#step:6:653
```
PHP Fatal error:  Maximum execution time of 300 seconds exceeded in /app/vendor/sebastian/global-state/src/Snapshot.php on line 359
```
- https://github.com/phpmyadmin/phpmyadmin/actions/runs/6042689927/job/16398306660#step:6:659
```
PHP Fatal error:  Maximum execution time of 300 seconds exceeded in /app/vendor/sebastian/recursion-context/src/Context.php on line 123
```

I'm tracking down the slow tests to refactor them, but it's a little bit hard to replicate them outside the CI, but it's possible.

So my question is:
Is possible to fail the test that caused the fatal error?

PHP 8.1.22
phpunit/phpunit (10.3.2)
sebastian/global-state (6.0.1)
sebastian/recursion-context (5.0.0)

**Comment by sebastianbergmann** [comment]
You could try to run your tests in isolated processes. This will make them even slower, but they should survive a fatal error.
