### ISSUE TITLE
PHP 8.3 Reflection on getMockForTrait errors unexpectly

### ISSUE THREAD

**Issue by alexander-schranz** [sebastianbergmann/phpunit#5495]
I'm not sure if issues of PHP 8.3 are already relevant but as I stumble over it a tried to debug it down and put it into a reproducer which I wanted to share if it maybe helps somebody to check whats going wrong here.

| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.6.11 , 10.3.2
| PHP version         | 8.3-dev
| Installation Method | Composer

#### Summary

I did test the current state of @sulu against PHP 8.3 and stumble over an issue with `getMockForTrait`.

#### Current behavior

The specific tests uses `getMockForTrait` and errors with:

```
There were 2 errors:

1) Tests\DataProviderRepositoryTraitTest::testFindByFiltersIds
ReflectionException: Method Mock_Trait_DataProviderRepositoryTrait_f1c5dfdf_338756af::findByFiltersIds() does not exist

/home/runner/work/reproducer-trait-mock-phpunit/reproducer-trait-mock-phpunit/tests/DataProviderRepositoryTraitTest.php:66
```

#### How to reproduce

The full failing test case is this one: https://github.com/sulu/sulu/blob/2.5/src/Sulu/Component/SmartContent/Tests/Unit/Orm/DataProviderRepositoryTraitTest.php

But I isolated it into an own repository here:

https://github.com/alexander-schranz/reproducer-trait-mock-phpunit

The issue as seen is appearing only on PHP 8.3: https://github.com/alexander-schranz/reproducer-trait-mock-phpunit/actions/runs/6044382503/job/16402902447

The same error appears on PHPUnit 10: https://github.com/alexander-schranz/reproducer-trait-mock-phpunit/pull/2

#### Expected behavior

Not failing on PHP 8.3 or mark issues as won't fix as did see `getMockForTrait` already got deprecated after creating this issue.

**Comment by sebastianbergmann** [comment]
> I'm not sure if issues of PHP 8.3

Issues for PHP 8.4 are already relevant :)

However, I need a **minimal**, **self-contained**, reproducing test case that shows the problem. Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by sebastianbergmann** [comment]
Sorry, I was not fully awake yet.

**Comment by sebastianbergmann** [comment]
PHPUnit's test double code generator generates the same code using PHP 8.2 and PHP 8.3:

```php
abstract class Trait_DataProviderRepositoryTrait_44c8e5ec
{
    use App\DataProviderRepositoryTrait;
}

class Mock_Trait_DataProviderRepositoryTrait_44c8e5ec_6bd4ff3a
extends Trait_DataProviderRepositoryTrait_44c8e5ec
implements PHPUnit\Framework\MockObject\MockObject
{
    use \PHPUnit\Framework\MockObject\Api;
    use \PHPUnit\Framework\MockObject\Method;
    use \PHPUnit\Framework\MockObject\MockedCloneMethodWithVoidReturnType;
}
```

Your reproducing test case can be reduced to this:

```php
$dataProviderRepositoryTrait = $this->getMockForTrait(DataProviderRepositoryTrait::class);

$findByFiltersIdsReflection = new \ReflectionMethod(
    \get_class($dataProviderRepositoryTrait),
    'findByFiltersIds'
);
```

My initial analysis suggests that `$this->getMockForTrait(DataProviderRepositoryTrait::class)` works the same for PHP 8.2 and PHP 8.3. I only tested this using PHPUnit 8.5 as this is the oldest version that would need to be adapted for a change in PHP.

It appears that there's a change in PHP 8.3 that gets in the way of creating a `ReflectionMethod` object for the private method `DataProviderRepositoryTrait::findByFiltersIds` in the `Mock_Trait_DataProviderRepositoryTrait_44c8e5ec_6bd4ff3a` class.

I am tempted to say that this is not an issue that needs to be addressed in PHPUnit as you are performing that reflective operation in your code, outside of PHPUnit, but I want to understand what is going on here as much as you do. I am leaving this issue open for now.

**Comment by sebastianbergmann** [comment]
Here is a reproducing script that does not use PHPUnit or any other dependency:

```php
<?php declare(strict_types=1);
trait T
{
    private function m(): void
    {
    }
}

abstract class A
{
    use T;
}

class C extends A
{
}

var_dump(new ReflectionMethod(C::class, 'm'));
```

#### Output with PHP 8.2
```
object(ReflectionMethod)#1 (2) {
  ["name"]=>
  string(1) "m"
  ["class"]=>
  string(1) "A"
}
```

As you can see [here](https://3v4l.org/gSJoG), this is the output for 8.0.1 - 8.0.30, 8.1.0 - 8.1.23, 8.2.0 - 8.2.10.

#### Output with PHP 8.3
```
Fatal error: Uncaught ReflectionException: Method C::m() does not exist in /home/sb/test.php:18
Stack trace:
#0 /home/sb/test.php(18): ReflectionMethod->__construct('C', 'm')
#1 {main}
  thrown in /home/sb/test.php on line 18
```

**Comment by sebastianbergmann** [comment]
According to @nielsdos, this might be related to https://github.com/php/php-src/issues/9470.

**Comment by sebastianbergmann** [comment]
I will close this now as there is nothing in PHPUnit that needs to be changed.

**Comment by alexander-schranz** [comment]
Thx for investigate into this issue. Workaround works like expected: https://github.com/alexander-schranz/reproducer-trait-mock-phpunit/pull/3
