### ISSUE TITLE
failOnEmptyTestSuite not respecting each suite when running multiple

### ISSUE THREAD

**Issue by icanhazstring** [sebastianbergmann/phpunit#5497]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.x.x / 9.3.x
| PHP version         | doesn't matter (currenty 8.2)
| Installation Method | Composer / PHAR

#### Summary

When executing phpunit with multiple test suites (e.g. `--testsuite=Unit,Integration`) the tests are not failing with `failOnEmptyTestSuite=true` when either one of the suites does not contain tests.

#### Current behavior

The tests just runs like normal ignoring the empty suite

#### How to reproduce

Create two suites with one test each. Then mistype one of them in the cli option.

#### Expected behavior

- Either: The test run should fail when either one of the names suites has no tests
- Or: The test run should fail if given a suite which is not defined (probably easier but might introduce another option e.g. `failOnUnknownSuite`)

**Comment by sebastianbergmann** [comment]
This is expected behaviour as `failOnEmptyTestSuite` looks at the entire test suite, not at the individual test suites it might be comprised of.

**Comment by icanhazstring** [comment]
Ok weird, the docks should state that at least.

Any interest in a PR adding the mentioned solution to raise an exception if the given suite is not configured?
