### ISSUE TITLE
Tests running with process isolation are slow because `AssertionSucceeded` is always emitted

### ISSUE THREAD

**Issue by JanTvrdik** [sebastianbergmann/phpunit#5510]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.2.2
| PHP version         | 8.2.8
| Installation Method | Composer

#### Summary

Emitting `AssertionSucceeded` event is extremely slow if any of asserted values contain large object graphs. This has been already discussed in https://github.com/sebastianbergmann/phpunit/issues/5261 and it is fixed in most situations.

But when tests run with process isolation, they use `CollectingDispatcher`, which collects all events. This means that `AssertionSucceeded` event is always dispatched.

#### Current behavior

For tests running with process isolation, `AssertionSucceeded` event is always dispatched in the child process, regardless if it has any subscriber in the parent process. This causes extreme slowdown when any of the asserted values contain large object graph.

#### Expected behavior

The child process needs to collect only events that the parent process has subscriber for.

**Comment by sebastianbergmann** [comment]
Please note that PHPUnit 10.2.2 is no longer supported. In this case this is not an issue as the affected functionality has not been changed between PHPUnit 10.2 and PHPUnit 10.3.

**Comment by sebastianbergmann** [comment]
Superseded by #5515.
