### ISSUE TITLE
Support for @IgnoreClassForCodeCoverage, @IgnoreMethodForCodeCoverage

### ISSUE THREAD

**Issue by WhoLet2DogsOut** [sebastianbergmann/phpunit#5512]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 10.1.3
| PHP version               | 8.2.9
| Driver                    | Xdebug
| Xdebug version (if used)  | 3.2.2
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 10.3.2

Deprecated `@CodeCoverageIgnore` removes the class from coverage report, but new attributes don't.

### OK - Example with deprecated @CodeCoverageIgnore
```
<?php

declare(strict_types=1);

namespace App\Utils;

use PHPUnit\Framework\Attributes\CodeCoverageIgnore;

#[CodeCoverageIgnore]
class Email
{
    public static function normalize(string $email): string
    {
        return strtolower(trim($email));
    }
}
```

![image](https://github.com/sebastianbergmann/php-code-coverage/assets/105944679/6e3ff718-efdb-419f-9547-3ca35be6dfa1)

### ERROR - code coverage doesn't ignore attribute with @IgnoreClassForCodeCoverage
```
<?php

declare(strict_types=1);

namespace App\Utils;

use PHPUnit\Framework\Attributes\IgnoreClassForCodeCoverage;

#[IgnoreClassForCodeCoverage(Email::class)]
class Email
{
    public static function normalize(string $email): string
    {
        return strtolower(trim($email));
    }
}
```

![Snímek obrazovky z 2023-08-29 07-53-45](https://github.com/sebastianbergmann/php-code-coverage/assets/105944679/1706a1db-9d77-482b-8881-bfe86fcf84c2)

### ERROR - code coverage doesn't ignore attribute with @IgnoreClassForCodeCoverage

```
<?php

declare(strict_types=1);

namespace App\Utils;

use PHPUnit\Framework\Attributes\IgnoreMethodForCodeCoverage;

#[IgnoreMethodForCodeCoverage(Email::class, 'normalize')]
class Email
{
    public static function normalize(string $email): string
    {
        return strtolower(trim($email));
    }
}
```

![Snímek obrazovky z 2023-08-29 07-56-33](https://github.com/sebastianbergmann/php-code-coverage/assets/105944679/83e97c3d-2cab-4373-8faa-f75d9870f005)

### Using this command to generate code coverage
```
./vendor/bin/phpunit -c phpunit.xml --coverage-html .tmp/coverage-report di/tests
```

**Comment by sebastianbergmann** [comment]
Superseded by #5513.
