### ISSUE TITLE
Abstract classes treated as tests, even when they used to not be

### ISSUE THREAD

**Issue by Crell** [sebastianbergmann/phpunit#5523]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.3.5
| PHP version         | 8.1
| Installation Method | Composer

#### Summary

I have some abstract classes in my tests, as a test hierarchy.  The idea is that several different implementations of a thing all use the same tests in the base class, just providing an alternate implementation.  I had the abstract base classes named `FooTest`, with child classes `FooTypeATest`, `FooTypeBTest`, etc.  This worked fine in PHPUnit 9.

In 10.3, it still runs but I get a warning that the class is abstract.  Which... yes, it is, but why would PHPUnit 9 rightly just ignore it, while PHPUnit 10 is giving me a warning?  Is this deliberate?

**Comment by ghostwriter** [comment]
#5132

**Comment by sebastianbergmann** [comment]
Yes, this is deliberate.

**Comment by borgogelli** [comment]
> Yes, this is deliberate.

I think that it's counterintuitive and logically incorrect.
To solve the problem, the user is forced to transform the abstract class into a concrete one and must even create a dummy test method inside it to avoid other errors.

**Comment by ghostwriter** [comment]
If an abstract class name ends in `*Test` (`*Test.php`), rename the class and file.

eg. `Abstract*Test` to `Abstract*Testcase`

**Comment by borgogelli** [comment]
> If an abstract class name ends in `*Test` (`*Test.php`), rename the class and file.
> 
> eg. `Abstract*Test` to `Abstract*Testcase`

I know that, but problem persists with PHPUnit 10.4.2
