### ISSUE TITLE
Do not export data passed to test for `PHPUnit\Event\Code\TestMethod` value object by default

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#5524]
The data provided to a test by a data provider (or by another test methods through test dependencies) is exported to a string for the value object that represents the test for the event system. This export is performed using [sebastian/exporter](https://github.com/sebastianbergmann/exporter/).

PHPUnit's own event subscribers do not use this exported data, the export can therefore be made optional. This would be similar to what we did in #5515 for the `Test\AssertionSucceeded` and `Test\AssertionFailed` events.

Motivated by https://github.com/phpstan/phpstan/discussions/9914.

**Comment by gnutix** [comment]
@sebastianbergmann I'm wondering if there should be a mention in 10.4 changelog about this error ?

```
  PHP Fatal error:  Declaration of DMS\PHPUnitExtensions\ArraySubset\Constrai  
  nt\ArraySubset::toString(): string must be compatible with PHPUnit\Framewor  
  k\Constraint\Constraint::toString(bool $exportObjects = false): string in /  
  home/runner/work/tipee/tipee/vendor/dms/phpunit-arraysubset-asserts/src/Con  
  straint/ArraySubset.php on line 108  
```

(any class extending `PHPUnit\Framework\Constraint\Constraint` will encounter it ; I've had other examples in Symfony code)

**Comment by sebastianbergmann** [comment]
You would be correct if I planned to release PHPUnit 10.4 with this BC break :)

**Comment by gnutix** [comment]
Okay, good to know you were aware of it and it's not meant to stay.
