### ISSUE TITLE
Add command line switch to ignore @covers, CoversClass, CoversFunction and CoversNothing

### ISSUE THREAD

**Issue by InvisibleSmiley** [sebastianbergmann/phpunit#5528]
Given a project where @covers and its attribute counterparts have not been used (widely) yet, it is a bit tricky to add them and still keep coverage high without going full --strict-coverage. Also it would be nice to be able to see what the coverage would be if integration tests (annotated with CoversNothing) were also taken into account.

This would e.g. allow to set up CI/DI to require two kinds of coverage thresholds - one strictly for unit tests, and another one for overall tests.

**Comment by sebastianbergmann** [comment]
I am sorry, this is, at least for now, outside the scope of this project.

**Comment by InvisibleSmiley** [comment]
In case anyone else needs/wants it, here's a quick hack to enable this feature:
```sh
# disable
find test* -type f -name "*Test.php" -exec sed -i '' 's/\#\[Covers/#Covers/g' {} +
sed -i '' 's/requireCoverageMetadata="true"/requireCoverageMetadata="false"/' phpunit.xml*

# restore
find test* -type f -name "*Test.php" -exec sed -i '' 's/#Covers/#[Covers/g' {} +
sed -i '' 's/requireCoverageMetadata="false"/requireCoverageMetadata="true"/' phpunit.xml*
```
