### ISSUE TITLE
Access the name of testsuite 

### ISSUE THREAD

**Issue by mpoiriert** [sebastianbergmann/phpunit#5529]
Considering this testsuite configuration:
 
```
 <testsuite name="Test1">
             <directory>...</directory>
 </testsuite>
  <testsuite name="Test2">
            <directory>...</directory>
 </testsuite>
```
 
 I would like to acces the nam "Test1" or "Test2" for a extension.
 
 I am still using use PHPUnit\Framework\TestListener; Which are deprecated I know.
 
When receving PHPUnit\Framework\TestSuite the name is the name of the TestCase class an not the name mentionned above.

My use case is base on the fact that I might put the same TestCase in the different testsuite but I want to change the behaviour of it (changing a ENV variable for example).

**Comment by sebastianbergmann** [comment]
This is outside the scope of this project.
