### ISSUE TITLE
assertNull($this->data->nonexistent->nonexistent->nonexistent->nonexistent->nonexistent);

### ISSUE THREAD

**Issue by Vasiliy-Makogon** [sebastianbergmann/phpunit#5530]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.3.5
| PHP version         | 8.2.4
| Installation Method | Composer & PHAR

#### Summary
the expression does not trigger a warning
```
$this->data->nonexistent->nonexistent->nonexistent->nonexistent->nonexistent
```

#### Current behavior

I have a class 

```
class Foo {
    /**
     * @param string $key
     * @return mixed
     */
    public function __get(string $key): mixed
    {
        return $this->data[$key] ?? null;
    }
```

test

```
$this->assertNull($this->data->nonexistent->nonexistent->nonexistent->nonexistent->nonexistent);
```
does not generate errors (warnings)

#### Expected behavior

warning ` Attempt to read property "nonexistent" on null `

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by Vasiliy-Makogon** [comment]
> Thank you for your report.
> 
> Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.
> 
> Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

Problem solved. The warning was not shown due to the "restrictWarnings" parameter being set to "true".

Honestly, I don't understand why "restrictNotices", "restrictWarnings" and "restrictDeprecations" were set to "true" by default when auto-generated via the `phpunit --generate-configuration` command. It seems to me that it is not entirely logical to limit these error reports...
