### ISSUE TITLE
Cache for generated Test Double code was not updated for Test Stub and Mock Object distinction

### ISSUE THREAD

**Issue by frankdekker** [sebastianbergmann/phpunit#5534]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.4.0
| PHP version         | 8.1
| Installation Method | Composer

#### Summary

In PHPUnit 10.4.0 I occassionally get a TestStub class returned instead of a MockObject class as before. 

#### Current behavior

```php
// For any of the return objects another MockObject is created, allowing the following notation to work:
$myClass = $this->createMock(MyClass::class);
$myClass->getTransformer()->getModel()->getData();
```

#### How to reproduce

The chaining above fails if in some other test for one of the return objects a TestStub is created. The chained method will then return a TestStub for that class instead of a MockObject, which is not compatible with the method return type and crashes with a type error.

I don't quite understand why, where and how a TestStub is created, but I found the problem where the mix up happens. The problem is because there's a TestStub / MockObject cache, but the generated cache key doesn't differentiate between TestStub and MockObject. See:

Class: `PHPUnit\Framework\MockObject\Generator\Generator`
Method: `generate`

Code:
```php
$key = md5(
    $type .
    serialize($methods) .
    serialize($callOriginalClone) .
    serialize($cloneArguments) .
    serialize($callOriginalMethods),
);
```

My temp fix that seems to work. Add the $mockObject status into the cache key:
```php
$key = md5(
    $type .
    ($mockObject ? 'mock' : 'stub') .
    serialize($methods) .
    serialize($callOriginalClone) .
    serialize($cloneArguments) .
    serialize($callOriginalMethods),
);
```

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by frankdekker** [comment]
Could you give me a hint when a TestStub is created? If I know that, I can create an example reproduction.

**Comment by sebastianbergmann** [comment]
`createStub($type)` returns (and is documented to return) `Stub&$type` whereas `createMock($type)` returns (and is documented to return) `MockObject&$type`. The classes that are generated for the former are prefixed with `TestStub_` and the classes that are generated for the latter are prefixed with `MockObject_`.

However, and like you already noticed, the key for the cache for generated code did not distinguish between test stubs and mock objects.
