### ISSUE TITLE
Composing Test Suite using interfaces/abstracts

### ISSUE THREAD

**Issue by szymonmil** [sebastianbergmann/phpunit#5537]
Hi,
If i want to organize tests in directories by business functionalities, not by test type, i have to add every test file/directory separately in xml file - example:
```xml
<testsuites>
        <testsuite name="unit">
            <directory>./../tests/core/phpunit/</directory>
            <exclude>./../tests/core/phpunit/Module/A/</exclude>
            <exclude>./../tests/core/phpunit/Module/B/SomeFunctionalTest.php</exclude>
        </testsuite>
        <testsuite name="functional">
            <directory>./../tests/core/phpunit/Module/A/</directory>
            <file>./../tests/core/phpunit/Module/B/SomeFunctionalTest.php</file>
        </testsuite>
    </testsuites>
```

But in most cases, every type of test have their own abstract test case that is inheriting from.
For example in Symfony its `WebTestCase` for integration/functional tests, and pure `TestCase` from phpUnit, but I also can create [markers](https://en.wikipedia.org/wiki/Marker_interface_pattern) to define which type of test case is specific test.

So I propose, to add some kind of configuration method, to tell that every test class inheriting/implementing some specific test case class belongs to testsuite. Example:
```xml
<testsuites>
        <testsuite name="unit">
            <inherits class="Some\Namespace\UnitTestCase">
                <directory>./../tests/core/phpunit/</directory>
            </inherits>
        </testsuite>
        <testsuite name="functional">
            <implements class="Some\Namespace\FunctionalTestCaseMarker">
                <directory>./../tests/core/phpunit/</directory>
            </implements>
        </testsuite>
    </testsuites>
```

Thanks :)

**Comment by sebastianbergmann** [comment]
I think you are looking for [test groups](https://docs.phpunit.de/en/10.4/attributes.html#test-groups).

**Comment by szymonmil** [comment]
Indeed, thank you very much
