### ISSUE TITLE
Class which initialises static properties causes risky test: "Test executed code that is not listed to be covered"

### ISSUE THREAD

**Issue by BrentMeeusen** [sebastianbergmann/phpunit#5547]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.3.3
| PHP version         | 8.2.4
| Installation Method | Composer

#### Summary

I'm testing the class `Response` which has static properties. PHP doesn't allow class properties to have an initial value, they have to be set in the constructor. However, I want to be able to access these properties even if no instances of `Response` exist yet. I fixed this by defining the properties in the class, and defining them outside, but in the same file. When I started writing tests, I found out it's considered a risky test because the line is executed even though it's not been marked to be covered or used.

#### Current behavior

```PHP
// Response.php
class Response {
	public static Response $ok;

	private int $code;

	public function __construct(int $code) {
		$this->code = $code;
	}

	public function getCode(): int {
		return $this->code;
	}
// Irrelevant code omitted
}
Response::$ok = new Response(200);  // This is line 48, the line referred to in the error message
```
```PHP
// ResponseTest.php
#[CoversClass(Response::class)]
#[Small]
final class ResponseTest extends TestCase {
	public function testConstructorAndGetters() {
		$response = new Response(200);
		$this->assertEquals(200, $response->getCode());
	}
}
```

PHPUnit finds this test risky:
```
This test executed code that is not listed as code to be covered or used:
- path\to\Response.php:48
```

#### How to reproduce

1. Copy the `Response` class and the `ResponseTest` class as described above and put them in their own file.
2. Run PHPUnit.

#### Expected behavior

Should pass without warnings.

**Comment by sebastianbergmann** [comment]
This use case (code outside the scope of classes or functions) is outside the scope of PHPUnit's feature set that allows you to get more precise code coverage.
