### ISSUE TITLE
Use Github releases

### ISSUE THREAD

**Issue by simPod** [sebastianbergmann/phpunit#5548]
I wonder if we could use github releases for changelogs.

I use bot for dependency upgrades that fetches the changelog from github. But with phpunit, I don't know what I'm actually merging since there is no changelog

<img width="620" alt="image" src="https://github.com/sebastianbergmann/phpunit/assets/327717/5a06d0f8-42e7-408e-bee9-0f922ad734a1">

I would prefer it looked like the example here

<img width="620" alt="image" src="https://github.com/sebastianbergmann/phpunit/assets/327717/050571da-bda9-4416-bdf7-0c44adf236a8">

**Comment by sebastianbergmann** [comment]
There is a very detailed ChangeLog in the repository.

**Comment by simPod** [comment]
Exactly but that is not standardized and thus cannot be automated easily by bots. Also it's harder to find as one must first go through branches, find the relevant one and switch to it and then find the changelog doc file.
