### ISSUE TITLE
Combine filter options with test/group lists

### ISSUE THREAD

**Issue by Black-Mantha** [sebastianbergmann/phpunit#5552]
The options `--list-tests`, `--list-tests-xml` and `--list-groups` cannot be combined with most test-filtering options. I have not found why this was done, but possibly it was because `RecursiveIteratorIterator` could not work with PHPUnit's filter iterators*.

<details><summary>*) technical reason</summary>

PHPUnit filter iterators extend `RecursiveFilterIterator`. That class seems to make its child iterators like this: `$childIterator = new static($iterableMember);`. That fails when the child class adds parameters to the constructor, with an exception like this:

```
Message:  Too few arguments to function PHPUnit\Runner\Filter\NameFilterIterator::__construct(), 1 passed and exactly 2 expected
Location: src/Runner/Filter/NameFilterIterator.php:40

#0 [internal function]: PHPUnit\Runner\Filter\NameFilterIterator->__construct()
#1 src/TextUI/Command/Commands/ListTestsAsTextCommand.php(38): RecursiveFilterIterator->getChildren()
...
```
</details>

## Why

Allowing the filtering option to be combined with the listing functions has the following benefits:

- Outputting filtered lists can be useful for trying out filters.
- This will allow external tools to use phpunit's filtering functions.

**Comment by Black-Mantha** [comment]
Combining these options used to produce a warning, not an error. Does that mean this is technically a breaking change? If so, what would be the recommended method to allow these options to be combined? A new option `--allow-filtering` seems a bit clunky.

**Comment by sebastianbergmann** [comment]
It was done because (conceptually) it does not make sense (to me) to combine these options.
