### ISSUE TITLE
Too few arguments to function PHPUnit\Framework\TestCase::__construct(), 0 passed 

### ISSUE THREAD

**Issue by engrnand** [sebastianbergmann/phpunit#5554]
There is problem inside PHPUnit\Framework\TestCase __construct  b/c its paramter $name is not optional 

![image](https://github.com/sebastianbergmann/phpunit/assets/43038833/d1f0401f-fd3b-44bd-be89-e70f7579f1fc)
![image](https://github.com/sebastianbergmann/phpunit/assets/43038833/20356c96-b72d-43e9-a9a0-a137ba8dfe03)

| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10
| PHP version         | 8.1
| Installation Method | Composer / PHAR

#### Summary
I have created constructor inside my test class, got error b/c of $name params:

#### Current behavior
```
public function __construct(string $name)
{
        $this->setName($name);

        $this->status = TestStatus::unknown();
}
final public function setName(string $name): void
{
    $this->name = $name;

    if (is_callable($this->sortId(), true)) {
        $this->providedTests = [new ExecutionOrderDependency($this->sortId())];
    }
}
```
#### How to reproduce

I have seen previous version 9.6 it is $name is optional
```
public function __construct(?string $name = null, array $data = [], $dataName = '')
{
        if ($name !== null) {
            $this->setName($name);
        }

        $this->data     = $data;
        $this->dataName = $dataName;
 }
```

#### Expected behavior

there is no need of any required params

**Comment by sebastianbergmann** [comment]
The constructor is marked `@internal` and is not covered by the backward compatibility promise for PHPUnit. In other words: do not overwrite it in your test case class.
