### ISSUE TITLE
add `assertEquals`  equivalent for numeric-string using bccomp

### ISSUE THREAD

**Issue by allan-simon** [sebastianbergmann/phpunit#5555]
When comparing monetary value, using float is considered a bad practice, one way php can handle this is by using numeric string i.e `'7.12'`   , the php standard library come then with the `bccomp` to compare numeric-string and be able to say that `7.10` and `7.1` are equivalent

it would be great to have a `assertNumericStringEquals('7.10',  '7.1')` method

**Comment by sebastianbergmann** [comment]
I consider this to be outside the scope of this project. Feel free to implement a custom assertion if you need this.

**Comment by allan-simon** [comment]
@sebastianbergmann  I understand , my initial view was that phpunit has method such as  "StringContainsString" which feels as much niche and some issue here https://github.com/sebastianbergmann/phpunit/issues/3185 could have been solved elegantly which such a new assert.
