### ISSUE TITLE
assertEquals not fails comparing null and empty string

### ISSUE THREAD

**Issue by lozovoyv** [sebastianbergmann/phpunit#5557]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.4.2
| PHP version         | 8.1.22
| Installation Method | Composer

#### Summary

assertEquals not fails comparing null and empty string.

#### Current behavior
```
OK (1 test, 1 assertion)
```

#### How to reproduce

```
    public function test_case()
    {
        $this->assertEquals(null, '');
    }
```

#### Expected behavior

```
Failed asserting that '' matches expected null.
```

**Comment by sebastianbergmann** [comment]
This is expected behaviour:

```
php > var_dump(null == '');
bool(true)
```

If you want a type-safe comparison, then you need to use `assertSame()` instead of `assertEquals()`.
