### ISSUE TITLE
Reconsider supporting cover annotation at method-level

### ISSUE THREAD

**Issue by marcospassos** [sebastianbergmann/phpunit#5558]
I would like to bring further arguments to support the discussion in https://github.com/sebastianbergmann/phpunit/issues/4502 and https://github.com/sebastianbergmann/phpunit/issues/5175.

Specifying the covers at the method level is very useful as it helps ensure the coverage is intentionally targeted towards a specific method. This approach is particularly helpful in the case of public methods that are used by other internal methods, as it makes sure that we are not testing that method indirectly.

Consider the following example:

```php
class Example {
    public function execute(): void {
        if ($this->isReady()) {
             // do something
             return;
        }
        
        // do something else
    }

    public function isReady(): bool {
         // some logic
         return true;
    }
}
```

When testing the `isReady` method, I want to ensure that the indirect tests from `execute` are not accounted for in the coverage since it was not intentional. I could refactor the `execute` method at any time to no longer use the `isReady` method (while keeping the same behavior), and I would not want it to impact my coverage. Of course, I could manually check this myself, but it is error-prone and not automatable.

Furthermore, the `CoversFunction` already allows you to specify a method at the class level. However, requiring you to create one class per method is infeasible and requires full refactoring for no value at all.

Why not allow the `CoversFunction` to be used in methods too? 

I would be happy to create a pull request in case you agree. As far as I can see, it is just a matter of allowing it in the target attribute.

**Comment by sebastianbergmann** [comment]
I disagree.
