### ISSUE TITLE
Changelogs should be consolidated into a migration documentation

### ISSUE THREAD

**Issue by laurentj** [sebastianbergmann/phpunit#5571]
There is a at present a Changelog file for each medium version (for example : one for 8.5, one for 9.0, one for 9.1, 9.2 etc.), and to my knowledge, they exists only into the repository. And I didn't find a "migration documentation" for each major version of PHPUnit. Did I miss something? If yes, sorry for this ticket, you can forgot it :-). Else, here is my request.

The problem with these all changelogs, is that it is difficult to migrate from a major version to another one. For instance, I wanted to migrate from 8.5 to 10.4, and I had to **find** more than 12 changelogs files, so I had to switch to each git tags and read these files (hoping I haven't forgotten some of them). Moreover, there are not always explanations how to migrate our code when it uses deprecated features that have been removed. Sometimes we can find these information into github issues, but they are not always very clear (and reading dozen github issues are not really convenient)

In order to not spend hours to know what to migrate and how, and to ease migration, it would be great to create some files like `HowToMigrateTo-9.md`, `HowToMigrateTo-10.md`, `HowToMigrateTo-11.md` and so on, one for each major version (and not for each medium version), alongside `ChangeLog-X.Y.md` files. They could list all deprecated features, methods, properties etc, and explain for each of them what to do to migrate our code. A kind of migration manual.

And, why not, these files could be published into the documentation or the web site.

**Comment by sebastianbergmann** [comment]
The following exists and is IMO sufficient:

- https://phpunit.de/backward-compatibility.html
- https://github.com/sebastianbergmann/phpunit/blob/9.6/DEPRECATIONS.md
- https://github.com/sebastianbergmann/phpunit/blob/10.4/DEPRECATIONS.md
- https://github.com/sebastianbergmann/phpunit/blob/10.5/DEPRECATIONS.md
- https://github.com/sebastianbergmann/phpunit/blob/main/DEPRECATIONS.md

**Comment by laurentj** [comment]
Sorry for this ticket, I didn't see these DEPRECATIONS.md files. Thank you.
