### ISSUE TITLE
Put `composer.lock` under version control

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#5578]
This is not as simple as proposed in #5576 and also should to be done for the `8.5`, `9.6`, and `10.5` branches. At this point I do not expect another release from the `10.4` branch.

The PHAR build process for PHPUnit 8.5 and PHPUnit 9.6 performs `composer require` operations that, of course, modify the `composer.json` and `composer.lock` files. The build process needs to be adapter to also roll back the changes to `composer.lock`. (The `composer.lock` that is put into the PHAR for #5577 is the right one.)

- [x] `8.5`
- [x] `9.6`
- [X] `10.5`
- [X] `main`

**Comment by drupol** [comment]
Just excellent, thanks <3 !

**Comment by drupol** [comment]
I'm thinking about something to improve the CI and detect discrepancies between `composer.json` and `composer.lock`.

How about adding a step that does a `composer validate --strict` during the workflow?

**Comment by sebastianbergmann** [comment]
The build automation I use locally already has it (see https://github.com/sebastianbergmann/phpunit/blob/main/build.xml#L21). And yes, this will be added to GitHub Actions in due course.

**Comment by drupol** [comment]
Excellent! All good :) Looking forward for the next tag to provide it in Nix!

**Comment by sebastianbergmann** [comment]
Done :)

**Comment by sebastianbergmann** [comment]
The `composer.lock` that is used while building the PHAR is added to the PHAR and available for inspection through `php phpunit.phar --composer-lock`. For PHPUnit 8.5 and PHPUnit 9.6, this is the modified `composer.lock`.
