### ISSUE TITLE
10.4 XSD not available

### ISSUE THREAD

**Issue by lstrojny** [sebastianbergmann/phpunit#5585]
`phpunit --generate-configuration` references https://schema.phpunit.de/10.4/phpunit.xsd but `curl https://schema.phpunit.de/10.4/phpunit.xsd` leads to 404.

## Version

```
phpunit --version
PHPUnit 10.4.2 by Sebastian Bergmann and contributors.
```

**Comment by sebastianbergmann** [comment]
Fixed.
