### ISSUE TITLE
Return Value Generator fails to correctly create test stub for method with `static` return type declaration when used recursively

### ISSUE THREAD

**Issue by dkarlovi** [sebastianbergmann/phpunit#5593]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.4.2
| PHP version         | 8.3.0
| Installation Method | Composer

#### Summary

Given this code

```php
interface CacheItemInterface
{
    public function expiresAfter(int|\DateInterval|null $time): static;
}

interface CacheItemPoolInterface
{
    public function getItem(string $key): CacheItemInterface;
}
```

running 

```php
return $this->getMockBuilder(CacheItemPoolInterface::class)->getMock();
```

yields

```
PHPUnit\Framework\MockObject\RuntimeException: Return value for Psr\Cache\CacheItemInterface::expiresAfter() cannot be generated: PHPUnit\Framework\MockObject\ReturnValueGenerator::newInstanceOf(): Return value must be of type PHPUnit\Framework\MockObject\MockObject, TestStub_CacheItemInterface_b24f5332 returned
```

Changing `static` to `self` fixes it.

#### Current behavior

See above.

#### How to reproduce

See above.

#### Expected behavior

Mocking works.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by dkarlovi** [comment]
Why not add the simplified version as a test case?

**Comment by sebastianbergmann** [comment]
Rest assured, there will be a test case. But that one does not fit and I do not have the time right now to write the test I have in mind.
