### ISSUE TITLE
the the sequencing issue of test setup and dataProvider

### ISSUE THREAD

**Issue by thevikas** [sebastianbergmann/phpunit#5603]
This may not be a feature but a situation I face while writing tests. I am using factory classes to make fixture data. And then want to use that fixture data within the `@dataprovider`. But since dataProvider is called before the setup of the test, they all get `undefined`. 
I have been managing the fix by only using call count from dataProvider. And now preparing the actual data within the unit test method itself. I think this must be a common issue for many others and maybe even a easy fix.
Please suggest.

**Comment by sebastianbergmann** [comment]
This is not a discussion forum, sorry.
