### ISSUE TITLE
The path passed to `--log-events-text` or `--log-events-verbose-text` must be absolute

### ISSUE THREAD

**Issue by theofidry** [sebastianbergmann/phpunit#5608]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.5.2
| PHP version         | 8.3.0
| Installation Method | Composer

#### Summary

When executing PHPUnit with `--log-events-text` or `--log-events-verbose-text`, the configured path may not be absolute. In this case, if a test changes the working directory, the output file may inadvertently change.

#### Current behavior

In Box:

```
$ php -dphar.readonly=1 vendor/bin/phpunit --testsuite=Tests --colors=always tests/Console/Command --log-events-text=dist/log-phpunit

[...]

Warning: file_put_contents(dist/log2): Failed to open stream: No such file or directory in /Users/tfidry/Project/Humbug/box/vendor/phpunit/phpunit/src/Logging/EventLogger.php on line 43

Call Stack:
    0.0001     633832   1. {main}() /Users/tfidry/Project/Humbug/box/vendor/bin/phpunit:0
    0.0002     645504   2. include('/Users/tfidry/Project/Humbug/box/vendor/phpunit/phpunit/phpunit') /Users/tfidry/Project/Humbug/box/vendor/bin/phpunit:122
    0.0162    7193032   3. PHPUnit\TextUI\Application->run($argv = [0 => 'vendor/bin/phpunit', 1 => '--testsuite=Tests', 2 => '--colors=always', 3 => 'tests/Console/Command', 4 => '--log-events-text=dist/log2']) /Users/tfidry/Project/Humbug/box/vendor/phpunit/phpunit/phpunit:99

[...]
```

#### How to reproduce

- checkout https://github.com/box-project/box/pull/1252
- run `composer install`
- execute `php -dphar.readonly=1 vendor/bin/phpunit --testsuite=Tests --colors=always tests/Console/Command --log-events-text=$(pwd)/dist/log-phpunit`

#### Expected behavior

The path pased, e.g. `dist/log-phpunit`, should probably be evaluated as `$(pwd)/dist/log-phpunit` before any test is executed so that it may not change due to a test/extension changing the working directory in a weird place.

**Comment by sebastianbergmann** [comment]
> the configured path may not be absolute

You mean "the configured path may not be relative", right?

**Comment by theofidry** [comment]
>You mean "the configured path may not be relative", right?

No, if the path configured is absolute you would not have an issue as even if the working directory changes it will not change.

**Comment by marac19901990** [comment]
#5633
