### ISSUE TITLE
Infinite recursion when data provider provides recursive array

### ISSUE THREAD

**Issue by ptomulik** [sebastianbergmann/phpunit#5614]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | >=10.0.0
| PHP version         | 8.2.13
| Installation Method | Composer / PHAR

#### Summary

When @dataProvider method tries to return recursive array, it always fails with SEGFAULT.

#### Current behavior

Segmentation fault.

#### How to reproduce

```php
<?php declare(strict_types=1);

use PHPUnit\Framework\TestCase;

final class RecursiveArrayTest extends TestCase {
    public static function provideRecursiveArray(): iterable {
        $array = [];
        $array[0] = &$array;
        yield [$array];
    }

    /**
     * @dataProvider provideRecursiveArray
     */
    public function testRecursiveArray(array $array): void {
        $this->assertTrue(true);
    }
}
```

```console
ptomulik@tea:$ vendor/bin/phpunit tests/RecursiveArrayTest.php 
PHPUnit 10.0.0 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.2.13

Segmentation fault
```

#### Expected behavior

The test should pass

**Comment by sebastianbergmann** [comment]
You are testing with PHPUnit 10.0.0 which is not supported anymore. Do you encounter the same issue with PHPUnit 10.5.2?

**Comment by ptomulik** [comment]
> You are testing with PHPUnit 10.0.0 which is not supported anymore. Do you encounter the same issue with PHPUnit 10.5.2?

10.0 is the first version having this bug (9.6 seems working fine). From my experiments, it looks like all the versions ``>=10.0`` are vulnerable.

**Comment by ptomulik** [comment]
```
ptomulik@tea:$ vendor/bin/phpunit tests/RecursiveArrayTest.php 
PHPUnit 10.5.2 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.2.13

Segmentation fault
```

**Comment by sebastianbergmann** [comment]
This happens in `TestCase::registerMockObjectsFromTestArguments()`.

We do not need this code anymore in PHPUnit 11 as [data providers must be static in PHPUnit 11 and therefore can no longer create mock objects](https://github.com/sebastianbergmann/phpunit/issues/5100). So in PHPUnit 11 this problem will be gone.

As for PHPUnit 10, I do not considers recursive arrays important enough (IMO, they are an edge case) to spend time on fixing the implementation of `TestCase::registerMockObjectsFromTestArguments()`. I would consider a pull request that addresses this, of course, but I will not invest time in debugging this myself.

**Comment by ptomulik** [comment]
See #5615
