### ISSUE TITLE
Values from data provider are not shown for failed test

### ISSUE THREAD

**Issue by mvorisek** [sebastianbergmann/phpunit#5616]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.5.3
| PHP version         | any
| Installation Method | Composer

#### Summary

PHPUnit 10.x does currently shows only the data set # /wo dumping the data set values in the test header/output.

Currently, the developer has to go to the test code to even get a rough idea what the failed test is really about.

With a complex providers, it is even hard to tell by looking into the code what values were passed by a given data set # - example: https://github.com/atk4/ui/blob/5.0.0/tests/DemosTest.php#L305 - it is basically impossible.

I am reporting this as a bug, as PHPUnit 9.x output has/had the data set values dumped.

#### Current behavior

```
...
There were 2 failures:

1) Atk4\Ui\Tests\DemosHttpTest::testDemoJsonResponse with data set #3
Failed asserting that '{\n
,,,
```

#### How to reproduce

Any test with data provider.

#### Expected behavior

expected/PHPUnit 9.x output:

```
...
There were 2 failures:

1) Atk4\Ui\Tests\DemosHttpTest::testDemoJsonResponse with data set #3 ('_unit-test/exception.php?__at...json=1')
Failed asserting that '{\n
```

**Comment by sebastianbergmann** [comment]
#### `Test.php`
```php
<?php declare(strict_types=1);
use PHPUnit\Framework\TestCase;

final class Test extends TestCase
{
    public static function provider(): array
    {
        return [
            [1, '2', 3.0, true],
        ];
    }

    /**
     * @dataProvider provider
     */
    public function testOne(int $a, string $b, float $c, bool $d): void
    {
        $this->assertTrue(false);
    }
}
```
#### PHPUnit 10
```
1) Test::testOne with data set #0
Failed asserting that false is true.
```
#### PHPUnit 9
```
1) Test::testOne with data set #0 (1, '2', 3.0, true)
Failed asserting that false is true.
```
