### ISSUE TITLE
Mutate tests/test suite from an extension 

### ISSUE THREAD

**Issue by allan-simon** [sebastianbergmann/phpunit#5617]
I would like to be able to alter the test suite (filter more tests in my use case) from an extension

basically being able to do 

```
final class CleverFilteringExtension implements Extension, Tracer
{
    public function bootstrap(
        Configuration $configuration,
        Facade $facade,
        ParameterCollection $parameters
    ): void {
        if ($configuration->noOutput()) {
            return;
        }
        $facade->registerTracer($this);
    }                                                                                                                  
                                                       
    public function trace(Event $event): void          
    {  
         if ($event instance of PHPUnit\Event\TestSuite\Loaded) {
               // ⚠️ do some clever stuff  
               // 
         }

    }
}
```

Currently my understanding is that events can't alter the state.
An other alternative would be to able to inject my own Factory in the `TestSuiteFilterProcessor`

**Comment by sebastianbergmann** [comment]
This is, at least for the time being, out of scope for the extension system.

**Comment by allan-simon** [comment]
no problem I understand, is there a way to achieve this outside of the extension system  and without altering the project in which the code run ?  As I would like to make it distribuable

Currently the "hackish but it works"  I see would be to hotpatch /vendor to modify the Factory  to add my filtering system
