### ISSUE TITLE
PhpUnit 10 - Make exception handling extensible again

### ISSUE THREAD

**Issue by zeleznypa** [sebastianbergmann/phpunit#5630]
For my [extraordinary case](https://gitlab.com/interitty/utils#extended-and-translatable-exceptions) ([_implementation_](https://gitlab.com/interitty/utils/-/blob/main/src/Exceptions/ExtendedExceptionPhpunitTrait.php)), I really need to extend the method `verifyExceptionExpectations` which is impossible due to it being private. In PhpUnit 9, it was possible to overwrite the `assertThat` method to do so, but in Phpunit 10 is this method unfortunately final.

When there is a method `runTest` protected, it makes sense to allow also overwrite directly called methods.

Or please add an event directly after the catch in `runTest`

```php
try {
    $testResult = $this->{$this->name}(...array_values($testArguments));
} catch (Throwable $exception) {
    // Here
    if (!$this->shouldExceptionExpectationsBeVerified($exception)) {
```

Or please encapsulate the test execution into a separate method

```php
try {
    $testResult = $this->executeTest($this->name, $testArguments);
    //$testResult = $this->{$this->name}(...array_values($testArguments));
} catch (Throwable $exception) {
```

**Comment by sebastianbergmann** [comment]
This is outside the scope of this project.

**Comment by zeleznypa** [comment]
@sebastianbergmann Here in this project exactly in this file on this line:

https://github.com/sebastianbergmann/phpunit/blob/main/src/Framework/TestCase.php#L2336

just make it `protected` to make it extensible...

**Comment by sebastianbergmann** [comment]
Making this extensible it outside the scope of this project.

If your needs for testing exceptions is different than what PHPUnit provides out-of-the-box then, I am afraid, you have to run your own. Which basically means putting the code you expect to raise an exception in a `try` block and the verify the exception yourself in a `catch` block.
