### ISSUE TITLE
Unit test execution gives error of TextUI command not foujnd

### ISSUE THREAD

**Issue by Thejaswini-Rao-U** [sebastianbergmann/phpunit#5631]
Php unit which im using

| Q                            | A
| --------------------       | ---------------
| PHPUnit version     | ^9.0
| PHP version           |  7.3
codeception"          | ^4.2
| Installation Method | Composer require phpunit/phpunit ^9.0

#### Summary

I have installed phpunit 9.0 version and "codeception/phpunit-wrapper": "^9.0", when im executing test cases using command
vendor/bin/phpunit tests/unit/PdfImportServiceTest.php gives error below

**PHP Fatal error:  Uncaught Error: Class 'PHPUnit\TextUI\Command' not found in /var/www/html/amrod-supplymass-test/vendor/phpunit/phpunit/phpunit:107
Stack trace:
#0 {main}
  thrown in /var/www/html/amrod-supplymass-test/vendor/phpunit/phpunit/phpunit on line 107**

Please let me know how to resolve this.

Thanks in advance

**Comment by sebastianbergmann** [comment]
PHPUnit 9.0 has not been supported for years, the only supported version of PHPUnit 9 is PHPUnit 9.6.

Please open a new ticket if you can reproduce your issue with PHPUnit 9.6 and without having third-party extensions/wrappers such as codeception/phpunit-wrapper.
