### ISSUE TITLE
phpunit10 support testdox-xml format

### ISSUE THREAD

**Issue by anic** [sebastianbergmann/phpunit#5643]
Since phpunit 9 supports command line options `--testdox-xml <file>`  for writing agile documentation in XML format to file.  But in phpunit 10, testdox provides 2 types of format. 
--testdox-html <file>
--testdox-text <file>

We hope `--testdox-xml` can be used in phpunit 10.

**Comment by sebastianbergmann** [comment]
No, this functionality has been removed.

**Comment by linaori** [comment]
What's the recommended alternative? I can't find a PR or issue explaining why it's removed and what the alternatives to use.

https://github.com/sebastianbergmann/phpunit/commit/555fce1f44368926e612d0e887b47ee07cc471a0
