### ISSUE TITLE
Simple Syntax Error in Functions file

### ISSUE THREAD

**Issue by refatkhan93** [sebastianbergmann/phpunit#5646]
PHP Version : 7.2
Installation : Composer
Error file: phpunit\src\Framework\Assert\Functions.php ( Line : 2966 )

    function atLeast(int $requiredInvocations): InvokedAtLeastCountMatcher
    {
        return new InvokedAtLeastCountMatcher(
            $requiredInvocations, // Error here for this extra "," 
        );
    }

**Comment by sebastianbergmann** [comment]
I assume you have installed a version of PHPUnit newer than PHPUnit 8. Only PHPUnit 8 is still supported on PHP 7.2. Newer versions of PHP allow the syntax in question.
