### ISSUE TITLE
Event does not fire unless "hookMethod" method is defined in test class

### ISSUE THREAD

**Issue by ruskiyos** [sebastianbergmann/phpunit#5649]
Using phpunit 10, I'm creating an extension for myself that I would like to run BEFORE the the `setup` method is called in a test class, regardless of whether the `setup` method is defined or not.

I created an `extension` that registers a `subscriber` that implements the `BeforeTestMethodCalledSubscriber` interface. I noticed that the `BeforeTestMethodCalled` event fires ONLY IF the `setup` method exists on the test class and fires only AFTER executing the `setup` method on that class. I need the subscriber to fire BEFORE the `setup` method is called.

I  modified the `subscriber` to implement the `BeforeFirstTestMethodCalledSubscriber` interface. I again noticed that the `BeforeFirstTestMethodCalled` event fires ONLY IF the `setUpBeforeClass` method exists on the test class and fires only AFTER executing the `setUpBeforeClass` method on that class. 

I would like my subscription to fire for every test BEFORE the `setup` method is executed. As a workaround, I defined an empty `setUpBeforeClass` method on the parent test class that all tests in that suite extend.

The method `PHPUnit/Framework/TestCase::invokeHookMethods` is where the `BeforeTestMethodCalled` (and other TestCase specific) events are handled. The method `PHPUnit/Framework/TestSuite::invokeMethodsBeforeFirstTest` is where the `BeforeFirstTestMethodCalled` events are handled .

Was the event handling functionality described above implemented that way intentionally, and if so, what was the intent behind first checking if the methods exist before firing the events? I would assume that those events should fire regardless of the implementation of the corresponding method.

**Comment by sebastianbergmann** [comment]
The event system works as intended: it only emits events that actually happened. I do not understand your use case, but you probably want to subscribe to the `Test\PreparationStarted` or `Test\Prepared` event instead.
