### ISSUE TITLE
Data provider should not be executed when class/test requirements are not met

### ISSUE THREAD

**Issue by mvorisek** [sebastianbergmann/phpunit#5659]
```
<?php

/**
 * @requires OSFAMILY Windows
 */
final class ForWindowsOnlyTest extends TestCase
{
    /**
     * @dataProvider provideProcessCases
     */
    public function testProcess(array $expected, array $input = null): void
    {
    }

    public static function provideProcessCases(): iterable
    {
        // yield some cases
    }
}
```

Data providers should not be run at all if they are not needed, ie. if the requirements of whole test class or test method are not met.

This is important especially when the data providers depend on the test requirements like PHP or OSFAMILY and the data providers have otherwise to duplicate the requirements detection.

**Comment by sebastianbergmann** [comment]
While we made progress in recent years to improve the architecture of the test runner, it still requires all data providers to be run before the tests are filtered, sorted, and eventually run.

Eventually, and I know that I have been saying this for years, this will be addressed.

**Comment by mvorisek** [comment]
Can this feature request be, please, kept open so we can refer to it and someone can potentially implement it?

**Comment by mvorisek** [comment]
@sebastianbergmann can we please keep this issue open?

Also it should be possible to add `@requires` (or `RequiresXxx` attribute) to any provider method which will allow to specify multiple providers to one method with different requirements.
