### ISSUE TITLE
Working Laravel tests fail after upgrading to php 8.2 + Laravel 10 + PHPUnit 10 with message "Test was run in child process and ended unexpectedly" on Github Actions

### ISSUE THREAD

**Issue by prototorpedo** [sebastianbergmann/phpunit#5671]
| PHPUnit version     | 10.1.10
| PHP version         | 8.2.14
| Installation Method | Composer

#### Summary

After upgrading to php 8.2, PHPUnit 10 and Laravel 10, whenever tests are run on Github Actions, exactly half of them fail with the message "Test was run in child process and ended unexpectedly", even though they pass on local env.

#### Current behavior

Half of the tests always fail on Github Actions, but they do pass on local configuration. We use paratest to test them in parallel and if we don't and try to run them one by one with processIsolation="false", it only runs the first test and exits. It is unclear so far if it is an issue with PHPUnit or Laravel itself, as if we change the command "php artisan test" to " find tests/ -name '*Test.php' -exec php vendor/bin/phpunit {} \;" they eventually run (and pass).

#### How to reproduce

1. upgrade existing app with working tests to php 8.2, Laravel 10 and PHPUnit 10
2. exactly half the tests should fail onGithub Actions if you are using paratest and --parallel flag

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by prototorpedo** [comment]
There's no way of reproducing this per se as tests only fail on github actions and it's got me baffled why. Half the tests fail with  "Test was run in child process and ended unexpectedly" and they aren't always the same tests.

**Comment by sebastianbergmann** [comment]
No feedback, closing.
