### ISSUE TITLE
Remove sebastian/recursion-context from composer require

### ISSUE THREAD

**Issue by janedbal** [sebastianbergmann/phpunit#5679]
Currently, composer.json [lists](https://github.com/sebastianbergmann/phpunit/blob/578fc2b/composer.json#L49) `sebastian/recursion-context` in `require`, but it seems like it is [used only in](https://github.com/search?q=repo%3Asebastianbergmann%2Fphpunit%20RecursionContext&type=code) `src/Util/ExcludeList.php`. But this file contains multiple symbol references for dependencies which are not present in `require`, namingly:

```
  • nikic/php-parser
      PhpParser\Parser in src/Util/ExcludeList.php:63

  • sebastian/code-unit-reverse-lookup
      SebastianBergmann\CodeUnitReverseLookup\Wizard in src/Util/ExcludeList.php:96

  • sebastian/complexity
      SebastianBergmann\Complexity\Calculator in src/Util/ExcludeList.php:102

  • sebastian/lines-of-code
      SebastianBergmann\LinesOfCode\Counter in src/Util/ExcludeList.php:117

  • theseer/tokenizer
      TheSeer\Tokenizer\Tokenizer in src/Util/ExcludeList.php:132
```

So this feels like unintended dependency. Or is it not?

----

*Note: I found this while testing our [composer-dependency-analyser](https://github.com/shipmonk-rnd/composer-dependency-analyser)*

**Comment by sebastianbergmann** [comment]
It is used [here](https://github.com/sebastianbergmann/phpunit/blob/10.5.9/src/Framework/TestCase.php#L107) and [here](https://github.com/sebastianbergmann/phpunit/blob/10.5.9/src/Framework/TestCase.php#L1841), for instance.

**Comment by janedbal** [comment]
But that is [no longer true for main branch](https://github.com/sebastianbergmann/phpunit/blob/main/src/Framework/TestCase.php) (where I tested and also the GitHub link above shows that).

**Comment by sebastianbergmann** [comment]
> But that is [no longer true for main branch](https://github.com/sebastianbergmann/phpunit/blob/main/src/Framework/TestCase.php) (which I tested and also the GitHub link above shows that).

You are correct, sorry for missing that.
