### ISSUE TITLE
Other unknown classes to clean up

### ISSUE THREAD

**Issue by janedbal** [sebastianbergmann/phpunit#5681]
Followup of #5680. There are still few references to unknown classes. Few look intentional, but at least that `CliTestDoxPrinter` is imo cleanup candidate, here is an output to verify:

```
  • C
      tests/end-to-end/regression/4376/tests/Test.php:19

  • CoveredClass
      tests/_files/NamespaceCoverageMethodTest.php:24

  • FooBarHandler
      tests/_files/RouterTest.php:24

  • PHPUnit\Logging\TestDox\CliTestDoxPrinter
      tests/_files/TestableCliTestDoxPrinter.php:14

  • ThisClassDoesNotExist
      tests/unit/Metadata/Parser/Annotation/RegistryTest.php:85
```

**Comment by sebastianbergmann** [comment]
I am sorry, but this issue is not helpful. If you think that you have found a source file in the test fixture of PHPUnit's test suite (great! there are likely a few.) then please delete it and try to run the test suite. If it does not fail then please open a pull request.
