### ISSUE TITLE
PHPUnit 10: migrating getStatus / hasFailed

### ISSUE THREAD

**Issue by demiankatz** [sebastianbergmann/phpunit#5687]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.5.7
| PHP version         | 8.1.2-1ubuntu2.14
| Installation Method | Composer

#### Summary

I have several Mink-powered integration tests which rely on PHPUnit's TestCase::hasFailed() method in their tearDown methods -- for example, to take a screen shot of a failed test, or to perform HTML validation on the output of a successful run.

When I discovered that hasFailed() no longer works in PHPUnit 10, I also looked into using getStatus() instead, but that also did not work in PHPUnit 10.

These methods appear to have been removed in PHPUnit 10, but I have found no reference to this change in changelogs, migration articles or other issues here in GitHub. The methods are not marked as `@deprecated` or `@internal` in [the PHPUnit 9 source code](https://github.com/sebastianbergmann/phpunit/blob/9.6/src/Framework/TestCase.php#L783-L803), so I assumed that I could safely use them.

#### Current behavior

Tests including calls to hasFailed() or getStatus() will not run in PHPUnit 10, because these methods are no longer defined.

#### How to reproduce

Write a test that calls hasFailed() or getStatus() inside tearDown(). It will work in PHPUnit 9, but it will not run in PHPUnit 10.

#### Expected behavior

I understand that the significant refactoring in PHPUnit 10 may make it impossible to support these methods in their previous form. However, this breaking change should be documented somewhere, and an alternate course of action should be recommended. I believe that my use cases are valid, especially when using PHPUnit to drive integration tests. I would be grateful for advice on best practices for achieving these goals, and I think it would be helpful to update documentation to help others in my position. Thank you for your time!

**Comment by demiankatz** [comment]
I should also note that I've discovered the [status()](https://github.com/sebastianbergmann/phpunit/blob/10.5/src/Framework/TestCase.php#L458-L464) method in PHPUnit 10, but this is clearly marked as `@internal`, so it is obviously not a safe replacement for the previous functionality.

**Comment by demiankatz** [comment]
Thanks, @sebastianbergmann, that is helpful. Is it worth adding `@internal` annotations to these methods in PHPUnit 9 for future reference? I'd be happy to open a PR if there's any value in that.

**Comment by sebastianbergmann** [comment]
> Is it worth adding `@internal` annotations to these methods in PHPUnit 9 for future reference? I'd be happy to open a PR if there's any value in that.

Thank you for volunteering, but I do not think the effort would be worth it.

**Comment by demiankatz** [comment]
@sebastianbergmann, unfortunately, after attempting to refactor my code to use `onNotSuccessfulTest()`, I have discovered that I had originally avoided using this for a reason. The `tearDown()` method is called before `onNotSuccessfulTest()`. Since my `tearDown()` method cleans up the browser session, it is no longer possible to take a useful screen shot by the time `onNotSuccessfulTest()` has been called. This also explains why I could not use `onNotSuccessfulTest()` to set a flag for use by `tearDown()` to make useful decisions based on test status. Can you suggest any other alternatives? I don't see a way around needing a tearDown method, and needing to act on failure/success status PRIOR to the completion of the tearDown process.
