### ISSUE TITLE
PHPUnit 11 final changes result in inability to disable return value generation

### ISSUE THREAD

**Issue by ben-challis** [sebastianbergmann/phpunit#5688]
For our uses of PHPUnit, we want to disable return value generation always. We want all mocked methods to need to be explicitly configured, rather than false-y values stubbed in if omitted. We find this approach is safer when code is refactored and mocked methods being called may change. Enforcing this has found bugs in our test suite(s).

We achieve this via https://github.com/Lendable/phpunit-extensions/blob/main/src/StrictMocking.php#L27 and a PHPStan rule to ensure either this trait is used or an abstract test case is extended from which uses this trait.

In PHPUnit 11 `TestCase::createMock` has been made final, which entirely breaks this. I realise the approach of overriding the method as such is a bit of a cludge as it requires the implementation to stay in sync with the upstream implementation, however, there is no ability currently to hook into the creation of the mock via `MockGenerator`, as all the code is just inline. Therefore, limited options to achieve this 😅 

Can you consider having a hook point for creating the "default" double?

I.e. enable configurability to the options passed here:

```php
        $mock = (new MockGenerator)->testDouble(
            $originalClassName,
            true,
            callOriginalConstructor: false,
            callOriginalClone: false,
            cloneArguments: false,
            allowMockingUnknownTypes: false,
        );
```

Or simply a means to opt-out of return value auto-generation at the `TestCase` level?

```php
        $mock = (new MockGenerator)->testDouble(
            $originalClassName,
            true,
            callOriginalConstructor: false,
            callOriginalClone: false,
            cloneArguments: false,
            allowMockingUnknownTypes: false,
            returnValueGeneration: $this->returnValueGenerationEnabled(),
        );
```

**Comment by sebastianbergmann** [comment]
I am sorry that this change causes you problem, but overriding methods provided by PHPUnit is a bad idea, which is the reason why these methods should have been declared final all along.

You "only" need to find a new name for your custom methods that you use create test stubs and mock objects. The names `createStub()` and `createMock()` are owned by PHPUnit.

**Comment by sebastianbergmann** [comment]
> I understand and agree, this isn't a bug report.

I did not understand it as such.

> This is a feature request to enable configurability of how mocks are constructed

This already exists in the form `getMockBuilder()`. You can implement a method such as the one shown below to create mock objects the way you want to.

```php
/**
 * @psalm-template RealInstanceType of object
 * @psalm-param class-string<RealInstanceType> $originalClassName
 * @psalm-return MockObject&RealInstanceType
 */
private function createMockUsingOurDefaults(string $originalClassName): MockObject
{
    return $this->getMockBuilder($originalClassName)
                ->disableOriginalConstructor()
                ->disableOriginalClone()
                ->disableArgumentCloning()
                ->disallowMockingUnknownTypes()
                ->disableAutoReturnValueGeneration()
                ->getMock();
    }
}
```

Of course, `createMockUsingOurDefaults` is just a placeholder name.

Please note that `disableArgumentCloning()` and `disallowMockingUnknownTypes()` are deprecated in PHPUnit 11 and that PHPUnit 12 will no longer clone arguments and allow mocking unknown types.

**Comment by ben-challis** [comment]
> I did not understand it as such.

Just clarifying I was not suggesting the method override approach was a good idea or one I was frustrated had broken 😄 

I suppose we disagree that being able to enable/disable return value generation at the test case level has value then? If so, no worries.

Going with the route of a different method has drawbacks for enforcement. It's not as simple (as i'm sure you're aware) as forbidding usage and providing alternates for `createMock` / `createStub` but all API methods that eventually call into the `MockGenerator` to create a mock where we would be wanting to disable return value generation, at a glance there's quite a few. It's workable just I still hold the view that there's merit to being able to turn the feature entirely on or off at a higher level (without overriding any methods unintended to be overriden).
