### ISSUE TITLE
Backward Compatibility break in `PHPUnit\Framework\Constraint\Constraint`

### ISSUE THREAD

**Issue by stof** [sebastianbergmann/phpunit#5690]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 11.0
| PHP version         | 8.2.15
| Installation Method | Composer / PHAR

#### Summary

PHPUnit 11.0 has changed the `Constraint` class to mark it readonly. This is a BC break for all child class (i.e. all custom constraints) because PHP requires that child classes have the same readonly flag than their parent (so either both readonly or none).
This BC break is not mentioned anywhere in the changelog. And it will make it very hard to define custom constraints compatible with multiple PHPUnit versions as it will require using conditional class definitions.

#### How to reproduce

Install PHPUnit 11 and use custom constraints that were written against previous versions. See https://github.com/symfony/symfony/issues/53731

**Comment by stof** [comment]
As the change has been rejected in https://wiki.php.net/rfc/readonly_amendments, this `readonly` flag at the class level effectively splits the classes into 2 incompatible sets as far as inheritance is concerned.
Adding it or removing it on non-final classes is a BC break.

**Comment by derrabus** [comment]
FTR, the corresponding commit was d82f5adbe5392caa81d27f963c54c0496ec387c2. I didn't find any discussion around this change though.

As @stof said, this change is a huge pain for 3rd party PHPUnit extensions that maintain compatibility for multiple PHPUnit versions. It would be really helpful if we could remove the `readonly` flag from classes that are meant to be extended downstream and have existed in PHPUnit 10 already.

Then again, removing the `readonly` flag from abstract classes like `Constraint` is a BC break as well. Not sure, how many projects have migrated their constraints to the new `readonly`classes already. Maybe taking back that change is acceptable if we are quick. 😕

**Comment by stof** [comment]
Well, this makes it a huge pain for projects providing custom constraints. It would be great to be able to support the 2 major versions of PHPUnit at the same time (for a package that is dedicated to PHPUnit constraint, making a new major version 

> so I expected this to be fine

doing BC breaks in major version is indeed OK regarding semver. But to me, the fact that it was not announced (while being the most painful BC break of the release) is not. If this was known to be a BC break when doing it, it should have been announced..

Note that the commit included similar changes for some other non-final classes (TestData, TestSuite, etc...). As those are less common in third party code, it might be OK to keep them readonly in 11.x but I would still expect the changelog to be amended for them.

**Comment by stof** [comment]
Thanks for the decision to revert it. It will make things a lot easier.

**Comment by sebastianbergmann** [comment]
PHPUnit 11.0.1 has been released with this [fix](https://github.com/sebastianbergmann/phpunit/commit/f6a1f7cf2b636e5a3f0727494d5632939ae9a643).

**Comment by stof** [comment]
@sebastianbergmann what about the changelog amending for other non-internal non-final classes that were turned readonly ?

**Comment by sebastianbergmann** [comment]
> @sebastianbergmann what about the changelog amending for other non-internal non-final classes that were turned readonly ?

As far as I can see, this only affects value objects that are passed from PHPUnit's event system to subscribers. Please see the section titled "Event System: Value Objects" that I just added to https://phpunit.de/backward-compatibility.html.

**Comment by derrabus** [comment]
Thank you very much, @sebastianbergmann!
