### ISSUE TITLE
`--log-events-text` and `--log-events-verbose-text` require the destination file to exit

### ISSUE THREAD

**Issue by mfn** [sebastianbergmann/phpunit#5692]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 11.0.1
| PHP version         | 8.3.2
| Installation Method | Composer / ~PHAR~

#### Summary

When trying to use either `--log-events-text` or `--log-events-verbose-text` with a filename, the following error is shown:
```
 $ vendor/bin/phpunit --log-events-text events.txt
PHPUnit 11.0.1 by Sebastian Bergmann and contributors.

The path "events.txt" specified for the --log-events-text option could not be resolved
```

The docs at https://docs.phpunit.de/en/11.0/textui.html say

> Stream events as plain text to file.

Nowhere is mentioned that the destination file has to exist.

The following works:
```
 $ touch events.txt
 $ vendor/bin/phpunit --log-events-text events.txt
…
```

- I only found out after digging into the source code
- Although the file has to be present, any contents will be overwritten

It would be great if the docs would properly reflect that (maybe also that things like `php://stdout` are supported, which I found out via https://github.com/sebastianbergmann/phpunit/pull/5633).

At best, it would simply accept any file name like any of the other log options (like `--log-junit`, etc.)

Thanks!

**Comment by sebastianbergmann** [comment]
> Nowhere is mentioned that the destination file has to exist.

This behaviour is not intended.
