### ISSUE TITLE
Class AbstractTestCase declared in AbstractTestCase.php is abstract (redundant warning?)

### ISSUE THREAD

**Issue by VerifiedJoseph** [sebastianbergmann/phpunit#5694]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.5.10
| PHP version             | 8.1.27
| Installation Method | Composer

#### Summary

phpunit returns a warning that the AbstractTestCase class is abstract. Unless I'm missing something (which is totally possible) this warning seems redundant.

#### Current behavior

```
There was 1 PHPUnit test runner warning:

1) Class AbstractTestCase declared in F:\Web Development\example-test\tests\AbstractTestCase.php is abstract
```

phpunit returns a warning that the AbstractTestCase class is an abstract class when running a test that extends it.

#### How to reproduce

AbstractTestCase.php
```PHP
<?php declare(strict_types=1);
use PHPUnit\Framework\TestCase;

abstract class AbstractTestCase extends TestCase
{
    final protected function assertStringIsOrderId(string $value): void
    {
        $this->assertMatchesRegularExpression(
            '/^[a-z0-9]{8}-[a-z0-9]{4}$/',
            $value,
            sprintf(
                'Failed asserting that "%s" is a valid order ID.',
                $value,
            ),
        );
    }
}
```

OrderIdGeneratorExtendingAbstractTestCaseTest.php
```PHP
<?php declare(strict_types=1);

final class OrderIdGeneratorExtendingAbstractTestCaseTest extends AbstractTestCase
{
    public function testGenerateGeneratesId(): void
    {
        $this->assertStringIsOrderId('htyv4567-hg57');
    }
}
```

Using an edited version of [https://docs.phpunit.de/en/10.5/extending-phpunit.html#extracting-abstract-test-cases](https://docs.phpunit.de/en/10.5/extending-phpunit.html#extracting-abstract-test-cases)

#### Expected behavior
no warning is returned

**Comment by sebastianbergmann** [comment]
Thank you for your report, unfortunately I am not able to reproduce it:

```
$ cat tests/AbstractTestCase.php                        
```
```php
<?php declare(strict_types=1);
use PHPUnit\Framework\TestCase;

abstract class AbstractTestCase extends TestCase
{
    final protected function assertStringIsOrderId(string $value): void
    {
        $this->assertMatchesRegularExpression(
            '/^[a-z0-9]{8}-[a-z0-9]{4}$/',
            $value,
            sprintf(
                'Failed asserting that "%s" is a valid order ID.',
                $value,
            ),
        );
    }
}
```
```
$ cat tests/OrderIdGeneratorTest.php 
```
```php
<?php declare(strict_types=1);

final class OrderIdGeneratorTest extends AbstractTestCase
{
    public function testGenerateGeneratesId(): void
    {
        $this->assertStringIsOrderId('htyv4567-hg57');
    }
}
```
```
$ phpunit --bootstrap tests/AbstractTestCase.php tests
PHPUnit 10.5.10 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.3.2

.                                                                   1 / 1 (100%)

Time: 00:00.008, Memory: 4.00 MB

OK (1 test, 1 assertion)
```

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by VerifiedJoseph** [comment]
Hi @sebastianbergmann. 

I did some more digging and it looks my phpunit.xml file was the problem. Created a new one based on the output of `--generate-configuration` and the warning is gone. 

Old config: https://github.com/VerifiedJoseph/abstract-test-case
New config: https://github.com/VerifiedJoseph/abstract-test-case/tree/new-configuration
