### ISSUE TITLE
Ability to run a same test several times from different test suites

### ISSUE THREAD

**Issue by romm** [sebastianbergmann/phpunit#5699]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 11.0.0
| PHP version         | 8.2.0
| Installation Method | Composer

#### Summary

When #5670 was created, the commit 57e07eef9de8e016be8da0f53a35d5df1fa72ebd was pushed to 11.0 branch, this prevents a same test to run several times when it was registered in different test suites.

I found out about #5670 yesterday, but I actually made use of this "bug" with PHPUnit 10 in a library of mine, and I think my use case makes sense. In PHPUnit 10, I am able to run the same integration test suite twice (let's call them "integration-suite-1" and "integration-suite-1"); I use PHPUnit event subscribers to modify a behavior in the library when "integration-suite-2" runs, so although the same tests and assertions run, the actual code paths are not the same at all between the two suites. This allows me to focus on testing the features of the library without having to duplicate each and every test-case to test the library with **and** without the behavior enabled.

In my opinion, writing a configuration like the one below should make sense:

```xml
<testsuites>
    <testsuite name="unit">
        <directory>tests/Unit</directory>
    </testsuite>
   
    <testsuite name="integration-suite-1">
        <directory>tests/Integration</directory>
    </testsuite>
    <testsuite name="integration-suite-2">
        <directory>tests/Integration</directory>
    </testsuite>
</testsuites>
```

While I hope I can make you change your mind from what was discussed in #5670, I obviously will respect any decision call you make. If my suggestion is to be refused, do you see any other way I can easily re-run a test suite in the same runtime?

Also — thanks a lot for your work and commitment to the PHP community! ❤️ 

#### Current behavior

A same test cannot run several times even when the configuration includes it in several test suites.

#### Expected behavior

Being able to run a same test several times when included in several test suites in the configuration.

**Comment by sebastianbergmann** [comment]
This is not a bug and works as intended.
