### ISSUE TITLE
combine `--list-tests` with `--group`

### ISSUE THREAD

**Issue by staabm** [sebastianbergmann/phpunit#5702]
running `php vendor/bin/phpunit --group levels --list-tests` on the [PHPStan-src codebase](https://github.com/phpstan/phpstan-src) returns the same list of tests, as when not using `--group levels`: `php vendor/bin/phpunit --list-tests`

I would expect `--group levels` to apply the same filtering as then running phpunit itself with `--group levels`.

```
$ vendor/bin/phpunit --version
PHPUnit 9.5.23 #StandWithUkraine

$ php -v
PHP 8.2.12 (cli) (built: Oct 24 2023 21:15:35) (NTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.2.12, Copyright (c) Zend Technologies
```

what I want to achieve: I want to use phpunit test filtering capabilities to separate the huge PHPStan test-suite into groups which I can run in parallel in GitHub Actions. running it in several parallel GitHub Action jobs has the benefit of utilizing more CPUs and therefore a faster feedback loop

**Comment by staabm** [comment]
asked differently: maybe there is already a mechanism to determine a list of test-classes given a group-name?

**Comment by staabm** [comment]
just leaving a note for myself: the initial `--list-tests` feature was implemented in https://github.com/sebastianbergmann/phpunit/commit/ebc228036d0fd06d2d48b080657af2684634f7ee which can be taken as a source of inspiration to implement the request

**Comment by staabm** [comment]
> Grouping is a very manual / tedious process, I wanted something easier: give me all tests, split them up (aka: slice them) and feed a slice of test back to be run by phpunit.

implemented a similar thing for PHPStan in https://github.com/phpstan/phpstan-src/pull/2916 
(as no matter we will implement something in PHPUnit 11, it will take years before PHPStan can update to such a version ;))

**Comment by ondrejmirtes** [comment]
> it will take years before PHPStan can update to such a new PHPunit version

We run the expensive levels tests only for a single PHP version which can be the latest one, we can update PHPUnit in CI before running the (sliced) tests.

**Comment by staabm** [comment]
@ondrejmirtes I am not sure to run a portion of tests with a different PHPunit version, since it will emit different warnings/deprecations and it might be cumbersome to maintain tests in a way which works on several phpunit major versions

**Comment by ondrejmirtes** [comment]
@staabm We can definitely make it work ;)

**Comment by staabm** [comment]
I did my initial tests with phpunit 9.x therefore did not realize there is also a `--list-tests-xml` variant, which contains everything we need.

I would therefore close this issue here.

> I do see value in what you propose, in fact, I think it makes a lot of sense. However, I do not know whether applying `--filter`, `--group` etc. when using `--list-tests` etc. would be a backward compatibility break or not and if so, how we best deal with it.

if you still want to accept the PR, I am fine with finishing it of course.
IMO adding a option to a command which was not supported before is not a BC break, but of course you have to decide on this one.
