### ISSUE TITLE
--path-coverage CLI option does not work without phpunit.xml config file

### ISSUE THREAD

**Issue by n-peugnet** [sebastianbergmann/phpunit#5711]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.6.6
| PHP version         | 8.1.2-1ubuntu2.14
| Installation Method | Composer

#### Summary

When using phpunit without a config file and with only CLI options, the `--path-coverage` option does nothing.

#### Current behavior

The coverage is reported as if the `--path-coverage` option were not there.

#### How to reproduce

```sh
git clone https://github.com/club-1/sphinx-inventory-parser
cd sphinx-inventory-parser
PHPUNITFLAGS='--path-coverage --coverage-html=/tmp/coverage' make test
```

#### Expected behavior

The coverage report should include path and branch coverage.

#### Proposed fix

I checked the code quickly and managed to get it working with the following patch:

```diff
diff --git a/src/TextUI/TestRunner.php b/src/TextUI/TestRunner.php
index 3ba298e86..bc74d923b 100644
--- a/src/TextUI/TestRunner.php
+++ b/src/TextUI/TestRunner.php
@@ -440,8 +440,8 @@ public function run(TestSuite $suite, array $arguments = [], array $warnings = [
 
         if ($codeCoverageReports > 0) {
             try {
-                if (isset($codeCoverageConfiguration) &&
-                    ($codeCoverageConfiguration->pathCoverage() || (isset($arguments['pathCoverage']) && $arguments['pathCoverage'] === true))) {
+                if ((isset($codeCoverageConfiguration) && $codeCoverageConfiguration->pathCoverage()) ||
+                    (isset($arguments['pathCoverage']) && $arguments['pathCoverage'] === true)) {
                     $codeCoverageDriver = (new Selector)->forLineAndPathCoverage($this->codeCoverageFilter);
                 } else {
                     $codeCoverageDriver = (new Selector)->forLineCoverage($this->codeCoverageFilter);
```

**Comment by sebastianbergmann** [comment]
A configuration file is required for all code coverage operations, with or without path coverage.

**Comment by n-peugnet** [comment]
> A configuration file is required for all code coverage operations, with or without path coverage.

Hmm this is false. I do not need any configuration file currently to report line coverage. And it is not explained anywhere that a configuration file is required to analyse/report coverage. Did you even read that I managed to make it work with a very simple (granted, maybe incorrect) patch?

Also this is very disturbing to set the option and see that it changes nothing. And it was time consuming to find what was going wrong.
