### ISSUE TITLE
`#[UsesInterface]` attribute

### ISSUE THREAD

**Issue by spriebsch** [sebastianbergmann/phpunit#5734]
Code regularly depends on interfaces, e.g. when working with a collaborator. In the spirit of loose coupling, it should not really matter *which* implementation of an interface I'm using in a test.

Currently, however, I have to explicitly list the used implementation of an interface by a UsesClass annotation.

I am proposing a new annotation, namely UsesInterface. With this, I specify that the tested code unit depdends upon/uses *an* implementation of said interface. For the Uses part, we don't care too much which one that is, thus I should not be forced to list production code or hand-crafted stubs explicitly.

**Comment by sebastianbergmann** [comment]
Superseded by #5985.

**Comment by sebastianbergmann** [comment]
This has now been implemented in 67ae4d8f94660e2177d11d4f732e82ff42cecc2a for PHPUnit 12.
