### ISSUE TITLE
TestDox printer does not display details about exceptions raised in before-test methods

### ISSUE THREAD

**Issue by BladeMF** [sebastianbergmann/phpunit#5760]
Since PHPUnit 10, exceptions that are thrown in `setUp` (as opposed to the actual test body) are not displayed although the test is marked as "E", forcing you to write your own try/catch and see what they are. Since setting up _is_ part of the test I don't think why it should be treated differently. Saying there was an error but not explaining what the error was is most unhelpful.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by BladeMF** [comment]
There - https://github.com/BladeMF/phpunit-setup-exception. The interesting bit - the `--testdox` needs to be on.

# Case 1 - A throw in the test body

## command
`'/var/www/test-repo2/vendor/bin/phpunit' --colors=always --filter 'test_something_with_error' --testdox --display-deprecations --display-errors '/var/www/test-repo2/tests/MyTestWithNormalThrows.php'`

## output
```
PHPUnit 11.0.6 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.2.13

E                                                                   1 / 1 (100%)

Time: 00:00.009, Memory: 8.00 MB

My Test With Normal Throws (Tests\MyTestWithNormalThrows)
 ✘ Something with error
   ┐
   ├ Exception: An error in the test!
   │
   │ /var/www/test-repo2/tests/MyTestWithNormalThrows.php:11
   ┴
```

# Case 2 - A throw in the `setUp` method

## command
`'/var/www/test-repo2/vendor/bin/phpunit' --colors=always --filter 'test_something' --testdox --display-deprecations --display-errors '/var/www/test-repo2/tests/MyTestWithSetupThrows.php'`

## output
```
PHPUnit 11.0.6 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.2.13

E                                                                   1 / 1 (100%)

Time: 00:00.011, Memory: 8.00 MB

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```

**Comment by DanteB918** [comment]
@BladeMF thank you for the testing environment! after playing around with it, I have found the issue to be with the  `--testdox` flag. As seen in my screenshots below, without this flag, the exception is being shown.

<details><summary>With testdox flag</summary>

![image](https://github.com/sebastianbergmann/phpunit/assets/100642899/49897a1c-de70-445b-b368-59250a58475e)

</details>

<details><summary>Without testdox flag</summary>

![image](https://github.com/sebastianbergmann/phpunit/assets/100642899/36179283-7dcf-47c8-bafa-ce3e7ff57c4e)

</details>

**Comment by sebastianbergmann** [comment]
@DanteB918 Thank you for investigating.

**Comment by BladeMF** [comment]
@sebastianbergmann , thank you.
