### ISSUE TITLE
DeepCopy\Filter\Filter not found 

### ISSUE THREAD

**Issue by RobertEcker** [sebastianbergmann/phpunit#5767]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 11.0.8
| PHP version         | 8.2.11
| Installation Method | Composer / PHAR

#### Summary

"DeepCopy\Filter\Filter" not found 

#### Current behavior

Fatal error: Uncaught Error: Interface "PHPUnit\DeepCopy\Filter\Filter" not found in phar://C:/test/phpunit.phar/myclabs-deep-copy/DeepCopy/Filter/ChainableFilter.php on line 8

Error: Interface "PHPUnit\DeepCopy\Filter\Filter" not found in phar://C:/test/phpunit.phar/myclabs-deep-copy/DeepCopy/Filter/ChainableFilter.php on line 8

Call Stack:
    0.0366    8066048   1. {main}() C:\test\phpunit.phar:0
    0.0378    8089504   2. require_once('phar://C:/test/phpunit.phar/myclabs-deep-copy/DeepCopy/Filter/ChainableFilter.php') C:\test\phpunit.phar:2902

#### How to reproduce

php ..\test\phpunit.phar -d memory_limit=524M --stderr C:\test

**Comment by sebastianbergmann** [comment]
I cannot reproduce this.

Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by RobertEcker** [comment]
![grafik](https://github.com/sebastianbergmann/phpunit/assets/6156052/47fb2fb9-9c4e-44f3-8753-d12b261a0bc7)

it had something to do with the downloaded file itself

I downloaded the new file from https://phar.phpunit.de/ - file size is 4916

few minutes ago, I downloaded it again - it is 3 kb bigger now (maybe that's the reason for missing files)

**Comment by RobertEcker** [comment]
at least it works again :) thanks
