### ISSUE TITLE
Get access to the groups in the event system

### ISSUE THREAD

**Issue by dbu** [sebastianbergmann/phpunit#5769]
With the event system introduced in phpunit 10, i think it is no longer possible for listeners to know which groups are involved with tests. We used to check for a specific group to know if the listener needs to start a webserver in [FOSHttpCache](https://github.com/FriendsOfSymfony/FOSHttpCache/pull/565/files#r1538713152)

it looks to me like the conversion of models to event value objects collects the groups but then does not do anything with them: https://github.com/sebastianbergmann/phpunit/blob/10.5/src/Event/Value/TestSuite/TestSuiteBuilder.php#L34-L44

**Comment by sebastianbergmann** [comment]
A test method can be marked a belonging to one or more groups. In the context of the event system, information about which groups a test belongs to is made available using a `MetadataCollection` object that can be accessed using the `TestMethod::metadata()` method on the value object that represents a test. This value object is passed to all subscribers for events that are related to tests, for instance to subscribers of the `Test\Prepared` event.

A collection of all `TestMethod` objects representing all test methods scheduled for execution (ie. not filtered away, etc.) is passed to the `TestSuite\Started` event for the top-level test suite.

If I understand your use case correctly, you want to run custom code before the first test is run contingent on whether there is at least a single test scheduled for execution that belongs to a specific group. The code shown below shows an example of a subscriber for the `TestSuite\Started` event as well as how to query the groups of the tests in the test suite.

```php
<?php declare(strict_types=1);
namespace PHPUnit\TestFixture\Issue5769;

use PHPUnit\Event\Code\TestMethod;
use PHPUnit\Event\TestSuite\Started;
use PHPUnit\Event\TestSuite\StartedSubscriber as TestSuiteStartedSubscriber;
use PHPUnit\Metadata\Group;

final class Subscriber implements TestSuiteStartedSubscriber
{
    private bool $isTopLevel = true;

    public function notify(Started $event): void
    {
        if (!$this->isTopLevel) {
            return;
        }

        $this->isTopLevel = false;

        $groups = [];

        foreach ($event->testSuite()->tests() as $test) {
            if (!$test->isTestMethod()) {
                continue;
            }

            assert($test instanceof TestMethod);

            foreach ($test->metadata()->isGroup() as $group) {
                assert($group instanceof Group);

                $groups[] = $group->groupName();
            }
        }

        var_dump(array_unique($groups));
    }
}
```
Does this help?

**Comment by dbu** [comment]
thanks a lot for the detailed explanations :blue_heart: 

indeed, that works perfectly. i was only looking in the Event namespace and saw nothing about groups there, did not realize its all done in Metadata. 
the Started event does not have the test suite, i am using the ExecutionStarted: https://github.com/FriendsOfSymfony/FOSHttpCache/pull/570

just out of curiosity: https://github.com/sebastianbergmann/phpunit/blob/10.5/src/Event/Value/TestSuite/TestSuiteBuilder.php#L34-L44 is indeed dead code, or does it have some side effect i am missing?

**Comment by sebastianbergmann** [comment]
> thanks a lot for the detailed explanations 💙

Glad I could help!

> just out of curiosity: https://github.com/sebastianbergmann/phpunit/blob/10.5/src/Event/Value/TestSuite/TestSuiteBuilder.php#L34-L44 is indeed dead code, or does it have some side effect i am missing?

You have found dead code, thank you for that. It's now gone.
