### ISSUE TITLE
ReturnValueMap is invalid when trying to call with same arguments but different return

### ISSUE THREAD

**Issue by SidoniaVidican-eagleeye** [sebastianbergmann/phpunit#5794]
```
->willReturnMap([
    ['SELECT * from Cars limit 100', 100],
    ['SELECT * from Cars limit 100', 20],
]);
```
Trying this will always return 100, because the argument is the same in both invocations.
Could be easily fixed by changing public function invoke(Invocation $invocation): mixed inside ReturnValueMap to:

     foreach ($this->valueMap as **$key =>** $map) {
            if (!is_array($map) || $parameterCount !== (count($map) - 1)) {
                continue;
            }

            $return = array_pop($map);

            if ($invocation->parameters() === $map) {
                **unset($this->valueMap[$key]);**
                return $return;
            }
        }

**Comment by sebastianbergmann** [comment]
This is working as intended.
