### ISSUE TITLE
Best practices/recommendations on how to move from docblock to native annotations

### ISSUE THREAD

**Issue by kkmuffme** [sebastianbergmann/phpunit#5796]
https://phpunit.de/announcements/phpunit-11.html

>In PHPUnit 11, the annotations that can be used in special PHP comments to add metadata to test classes and test methods are deprecated. Support for these annotations will be removed in PHPUnit 12.

We have 10000s of phpunit tests using the docblock annotation and I guess lots of companies have probably even more.

Will phpunit provide a tool itself, a recommendation for a tool or at least some recommendations/best practices from experience how other codebases have migrated from the old docblock syntax to the new syntax?

Manually changing them all isn't possible and writing our own custom tool would most certainly reinvent the wheel.

**Comment by sebastianbergmann** [comment]
> Will phpunit provide a tool itself

No, PHPUnit does not and will not provide such a tool.

> a recommendation for a tool

I do not have first-hand experience, but I have heard from multiple developers/teams that they successfully used [rector-phpunit](https://github.com/rectorphp/rector-phpunit/blob/main/docs/rector_rules_overview.md) for this.
