### ISSUE TITLE
Newrelic causes error handlers loop to get stuck, tests run out of memory

### ISSUE THREAD

**Issue by janfejtek** [sebastianbergmann/phpunit#5808]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 11.1.0
| PHP version         | 8.2
| Installation Method | Composer

#### Summary
Library does not work on php with newrelic extension

#### Current behavior
When running test with php that contains newrelic extension, we get out of memory error. Loop here gets stuck https://github.com/sebastianbergmann/phpunit/blob/cef82dcdbead1dcda0a5af044640b13440c0f491/src/Framework/TestCase.php#L1901-L1922

#### Expected behavior

There was similar issue in Symfony - https://github.com/symfony/symfony/issues/25774 . Used fix is here https://github.com/symfony/symfony/pull/25755/files

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by mvorisek** [comment]
OP needs to provide minimal repro.

**Comment by sebastianbergmann** [comment]
No feedback, closing.
