### ISSUE TITLE
Duplicate CI pipeline jobs

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#5813]
When I push to a branch in this repository which is used in a pull request in this repository then the CI pipeline is run twice: once triggered by the `push` event and once triggered by the `pull_request` event:

![grafik](https://github.com/sebastianbergmann/phpunit/assets/25218/39c3e57d-bb58-4a66-88eb-ea8f313019cf)

It would be nice if the CI pipeline would only be run once in this case. If this is possible at all then we should only build for `pull_request` (so that the information in the pull request is updated) and not for `push`.

**Comment by talkinnl** [comment]
`on:
  push:
    branches:
      - 'main'
      - 'releases/**'`

Example syntax to restrict the push workflow.

I can make a PR for this. :)

**Comment by talkinnl** [comment]
I thought of this:

```
on:
  pull_request:
    branches:
      - main
      - "[0-9]*"
  push:
  schedule:
    - cron: "15 0 * * *"
```
i.e. add a branch restriction for main or any of your branches starting with version number.

But this won't work, as I see internal branches with arbitrary patterns.

I see a hack at https://stackoverflow.com/a/65946732 , but I don't like that.

So I guess it's actually not that easy? Not de-duplicating when the commit hash seens just wasteful of Github.
