### ISSUE TITLE
TestCase::createStubForIntersectionOfInterfaces returns a Stub without an expects() method, triggering an exception when calling ->method()

### ISSUE THREAD

**Issue by hugok96** [sebastianbergmann/phpunit#5817]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.5.18
| PHP version         | 8.1.27
| Installation Method | Composer

#### Summary

Trying to configure a method on a ``Stub`` created through the ``TestCase::createStubForIntersectionOfInterfaces`` method throws an unexpected exception: "Error: Call to undefined method TestStub_Intersection_AInterface_BInterface_f00d4e13_af77f05e::expects()".

#### Current behavior

It seems like this exception is triggered because the created ``Stub`` does not have the ``expects`` method, which is called in the ``PHPUnit\Framework\MockObject\Method`` trait. This method **does** get added when a ``Stub`` is created through the ``TestCase::createStub`` method.

#### How to reproduce

Create a ``Stub`` through the ``TestCase::createStubForIntersectionOfInterfaces`` method. Then attempt to configure a method using ``method``. See the example below, the line with ``$stub->method('testA')`` triggers the exception.
```php
<?php

declare(strict_types=1);

use PHPUnit\Framework\TestCase;

final class ExampleTest extends TestCase
{
    public function testMockIntersection(): void
    {
        $mock = $this->createMockForIntersectionOfInterfaces([AInterface::class, BInterface::class]);
        $mock->method('testA')->willReturn(1);
        $mock->method('testB')->willReturn('HelloWorld');

        self::assertEquals(1, $mock->testA());
        self::assertEquals(1, $mock->testA());
    }

    public function testStubIntersection(): void
    {
        $stub = self::createStubForIntersectionOfInterfaces([AInterface::class, BInterface::class]);
        $stub->method('testA')->willReturn(1);
        $stub->method('testB')->willReturn('HelloWorld');

        self::assertEquals(1, $stub->testA()); // triggers an exception
        self::assertEquals("HelloWorld", $stub->testB());
    }
}

interface AInterface
{
    public function testA(): int;
}

interface BInterface
{
    public function testB(): string;
}
```

Upon further inspection, the ``expects`` method does indeed not get added.
```php
$mock = $this->createMock(AInterface::class);
$intersectionMock = $this->createMockForIntersectionOfInterfaces([AInterface::class, BInterface::class]);

$stub = self::createStub(AInterface::class);
$intersectionStub = self::createStubForIntersectionOfInterfaces([AInterface::class, BInterface::class]);

var_dump(method_exists($mock, 'expects')); // returns true
var_dump(method_exists($stub, 'expects')); // returns true
var_dump(method_exists($intersectionMock, 'expects')); // returns true
var_dump(method_exists($intersectionStub, 'expects')); // returns false
```

#### Expected behavior

Configuring a method on a ``Stub`` created through the ``TestCase::createStubForIntersectionOfInterfaces`` should not trigger an exception.

#### Possible solution

Changing the following line in ``PHPUnit\Framework\TestCase::createStubForIntersectionOfInterfaces`` seems to fix the issue.
Current:
```php
$stub = (new MockGenerator)->testDoubleForInterfaceIntersection($interfaces, false);
```
Fixed:
```php
$stub = (new MockGenerator)->testDoubleForInterfaceIntersection($interfaces, true);
```

**Comment by sebastianbergmann** [comment]
As it was introduced after the decision was made to no longer add the `expects()` method to test doubles created using `createStub()`, `createStubForIntersectionOfInterfaces()` already behaves in PHPUnit 10 and PHPUnit 11 as `createStub()` will behave in PHPUnit 12.

Also note that calling `expects()` on an object created using `createStub()` in PHPUnit 11 triggers a deprecation warning (as the method will no longer be available in PHPUnit 12).

Also note that configuring expectations using `expects()` on test doubles created using `createStub()` does not have an effect anymore: expectations are not verified.

**Comment by sebastianbergmann** [comment]
I'm sorry, but this was not discernible for me from the original explanation, probably the reproducing example was too big and distracted from the actual problem.

Please open a new issue and provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.
