### ISSUE TITLE
[Question] returnCallback + willReturnOnConsecutiveCalls

### ISSUE THREAD

**Issue by ciltocruz** [sebastianbergmann/phpunit#5821]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 11.1.2
| PHP version         | 8.3.6
| Installation Method | Composer

#### Summary

Hi @sebastianbergmann .
The first thing I want to say is that this is not a bug. It's just a question about something that seems to be deprecated and will be eliminated in the future. I don't really know how to update. I am looking for a suggestion from you.

Thanks in advance.

This code is working without problem.

```
        $this->customerRepositoryMock = $this->getMockBuilder(CustomerRepositoryInterface::class)->getMock();
        $callback1 = $this->returnCallback(function (Customer $customer) {
            $this->assertSame('1', $customer->getSynchronize());
            $this->assertSame('api', $customer->getUserUpdate());

            return $this->customerMapper->toVO($customer);
        });

        $callback2 = $this->returnCallback(function (Customer $customer) {
            $this->assertSame('1', $customer->getBackUserId());

            return $this->customerMapper->toVO($customer);
        });

        $this->customerRepositoryMock->expects($this->exactly(2))->method('update')->willReturnOnConsecutiveCalls($callback1, $callback2);

        $this->customerService->processCustomer($mergedCustomer);
```

When my code runs `processCustomer`, this method internally makes 2 calls to the customerRepository's update method.

At this point willReturnOnConsecutiveCalls comes into play, passing 2 callbacks as a parameter, which I can assert in each call.

The `returnCallback` function is deprecated and the comment that appears to resolve it does not help me. Well, I lie. It has helped me in another test that only has one call to the "update" method. Here I have been able to migrate it without problem. But I don't know how to do it for this case where several consecutive calls are made.

I have seen this comment #5423 and this comment #5425, but it has not helped me.

Thank you very much again and sorry for opening this as a bug.

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.

**Comment by ciltocruz** [comment]
Good morning. 
As I said when creating the issue, I apologize for opening it as an issue. Where is the right place to ask you, the creator and maintainer and the one who can best know the answer, a question about a feature update when increasing the version of the PHPUnit project?
