### ISSUE TITLE
Too few arguments to function PHPUnit\Framework\TestCase::__construct(), 0 passed

### ISSUE THREAD

**Issue by JohnRDOrazio** [sebastianbergmann/phpunit#5824]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.5.19
| PHP version         | 8.1.27
| Installation Method | Composer

#### Summary

The TestCase constructor used to provide a default value for the `$name` parameter. After upgrading from PHPUnit 9 to PHPUnit 10, I started getting errors when instantiating a class that extends `TestClass`, because no parameter was provided. I am now forced to provide a `$name` parameter, even if it's an empty string.

#### Current behavior

`$name` parameter is required when instantiating a class that extends `TestCase`.

#### How to reproduce

```php
class MyTest extends TestCase {
  public function test() {
    //perform a test
  }
}

$mytest = new MyTest;
//ERROR: Too few arguments to function PHPUnit\Framework\TestCase::__construct(), 0 passed
//workaround: $mytest = new MyTest('');
```

#### Expected behavior

`$name` parameter should provide a default empty value if no parameter is provided.
```php
class MyTest extends TestCase {
  public function test() {
    //perform a test
  }
}

//the following should simply work
$mytest = new MyTest;
```

Perhaps there is a good reason why the `$name` parameter is required, however it is not documented anywhere.
Reading the documentation for [extending TestCase](https://docs.phpunit.de/en/11.1/extending-phpunit.html#enhancing-concrete-test-cases), even the examples provided never require a `$name` parameter (actually never instantiate the extended TestCase). If one were to try:

```php
$orderIdGeneratorTest = new OrderIdGeneratorTest;
```
This would generate the above mentioned error.

**Comment by JohnRDOrazio** [comment]
I'm pretty sure that's what @engrnand was trying to convey when he opened issue #5554...

**Comment by JohnRDOrazio** [comment]
as you can see in the source code, the `$name` parameter is required, no default value is provided:
https://github.com/sebastianbergmann/phpunit/blob/877f44b74d2563366f76e044d3fd710ebb94aeca/src/Framework/TestCase.php#L226

This should either be:
```php
public function __construct(string $name = '') 
```
or documentation should be updated to reflect the necessity of this parameter.

I must add, that I'm not using PHPUnit on the command line, I am using it together with [ratchetphp](https://github.com/ratchetphp/Ratchet) to send the results of tests over a websocket to a web UI.

**Comment by sebastianbergmann** [comment]
The necessity of this parameter is documented through the fact that it is not optional.

**Comment by JohnRDOrazio** [comment]
I'm really sorry @sebastianbergmann , but that seems to be a bit of an attitude there. If there is some use to the `$name` parameter (and I'm sure there is), please document the use of it. Otherwise if there is no real use, could you explain for what reason this is considered legal:
```php
class MyTest extends TestCase {
  public function test() {
    //perform a test
  }
}
$mytest = new MyTest('');
```

but this isn't:
```php
class MyTest extends TestCase {
  public function test() {
    //perform a test
  }
}
$mytest = new MyTest;
```

Is there any real difference? Other than to make life more complicated?

**Comment by sebastianbergmann** [comment]
`TestCase` objects are only supposed to be created and used by PHPUnit itself, not by third-party extensions for/wrappers around PHPUnit.
