### ISSUE TITLE
Is it possible to remove final declaration

### ISSUE THREAD

**Issue by huangdijia** [sebastianbergmann/phpunit#5830]
https://github.com/sebastianbergmann/phpunit/blob/654b6c6bbe3ff5fc99bb2643c1ed17c7feb39bce/src/Framework/TestCase.php#L441-L626

I want to override the runBare method in a subclass, runs in swoole croutine, for example:

```php
public function runBare(): void
    {
        $exception = null;

        \Swoole\Coroutine\run(function () use (&$exception) {
            try {
                parent::runBare();
            } catch (Throwable $e) {
                $exception = $e;
            } finally {
                // do something after run
                \Swoole\Timer::clearAll();
                \Hyperf\Coordinator\CoordinatorManager::until(\Hyperf\Coordinator\Constants::WORKER_EXIT)->resume();
            }
        });

        if ($exception) {
            throw $exception;
        }
    }
```

needs the change in phpunit 10.x and 11.x .

Hope to get your reply, Thanks!

**Comment by sebastianbergmann** [comment]
Sorry, but the answer is no.

**Comment by huangdijia** [comment]
> Sorry, but the answer is no.

Can you explain the reason for rejection?

The reason why I put forward this requirement is that I hope setUp/tearDown and testCase can run in the same environment.
