### ISSUE TITLE
advice on installing phpunit

### ISSUE THREAD

**Issue by rino1** [sebastianbergmann/phpunit#5835]
````
$ vendor/bin/phpunit
bash: vendor/bin/phpunit: File o directory non esistente
````

mmmhhh...
Let's do some checks

````
$ ls vendor/bin/phpunit
ls: impossibile accedere a 'vendor/bin/phpunit': File o directory non esistente

$ ls vendor
ls: impossibile accedere a 'vendor': File o directory non esistente

$ grep phpunit composer.json 
        "phpunit/phpunit": "^10.5"
````

OK! I got it. Just run the following command, and among other things, composer will download and install phpunit

````
$ composer update
````

However, this will logically create the vendor directory (with the related files and sub-directories, including vendor/bin/phpunit)

But here it https://github.com/composer/composer/discussions/11403#discussioncomment-5453127 says that this should not be done, to prevent the creation of duplicate vendor directories (which is what I want to do too). To understand the issue well, I recommend reading the entire discussion, which however, as you will see, turned out to be inconclusive.

So how do you reconcile the two? Run phpunit without including the vendor directory in the package?

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.
