### ISSUE TITLE
Unknown option "--ansi"

### ISSUE THREAD

**Issue by rhavin** [sebastianbergmann/phpunit#5836]
Installed phpunit with'

composer require --dev phpunit/phpunit for a netbeans project

composer.json looks like this
`  {
    "require": {
        "phpoffice/phpspreadsheet": "^2.1"
    },
    "require-dev": {
        "phpunit/phpunit": "^11.1"
    },
}
`
when creating a test for a class, i get the following error:

PHPUnit 11.1.3 by Sebastian Bergmann and contributors.

Unknown option "--ansi"
Done.

I have sadly after hours of googling still no clue ow to solve this.

**Comment by sebastianbergmann** [comment]
PHPUnit does not have an `--ansi` CLI option, correct. Could it be that your IDE wrongly invokes PHPUnit's test runner with that CLI option? Anyway: not a bug, closing.
