### ISSUE TITLE
Error handlers that are not callable outside the scope they were registered in are not handled correctly

### ISSUE THREAD

**Issue by kkmuffme** [sebastianbergmann/phpunit#5844]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 11.1.3
| PHP version         | 8.2.x
| Installation Method | both

#### Summary

`set_error_handler` and `set_exception_handler` do not necessarily return a callable - the PHP docs are wrong. See https://github.com/php/doc-en/issues/3421

Since phpunit uses both to store and then set them again in e.g. https://github.com/sebastianbergmann/phpunit/blob/main/src/Framework/TestCase.php#L1938 in conjunction with https://github.com/sebastianbergmann/phpunit/blob/main/src/Framework/TestCase.php#L1950 this leads to phpunit not working

In case this error handler originates from a dependency/outside of the project, that can't be changed and phpunit cannot be used at all

#### Current behavior

phpunit doesn't work/fatal

#### How to reproduce

See the php-doc issue for examples

#### Expected behavior

No fatal

EDIT: as a possible solution checking 
```
if (!is_callable($previousHandler) {
    // @todo report risky or something?
    break;
}
``` 

before the assignment https://github.com/sebastianbergmann/phpunit/blob/main/src/Framework/TestCase.php#L1944C17-L1944C39

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by mvorisek** [comment]
Here is an repro: https://3v4l.org/GFd18

The issue is the callback must be restored in rebound context.
