### ISSUE TITLE
return*() method for mocks allowing to specify call to parent method

### ISSUE THREAD

**Issue by smalyshev** [sebastianbergmann/phpunit#585]
I suggest adding a return*() method like returnCallback(), but that calls parent method (i.e. actual method of the class being mocked) of the class, with all the parameters. Example of use case for it is here:
http://stackoverflow.com/q/10924398/214196
and it looks like Phake framework has method that does exactly that: http://phake.digitalsandwich.com/docs/html/ch04s02.html

Maybe PHPUnit mocking framework should have one too? It should not be hard to do, all the information is there in $invocation object, just no return*() methods and implementing classes do exactly that.

**Comment by sebastianbergmann** [comment]
Looks to me like this should be possible with [test proxies](https://thephp.cc/news/2014/03/phpunit-4-0-test-proxies).
