### ISSUE TITLE
Missing extensions in php 8.2: `ctype` and `tokenizer`

### ISSUE THREAD

**Issue by halmai** [sebastianbergmann/phpunit#5850]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 11.1.3
| PHP version         |  8.2.19
| Installation Method | PHAR

#### Summary

phpunit reports missing ctype and tokenizer extensions but I cannot install them. `sudo apt-get install -y php8.2-ctype` reports:

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'php8.2-common' instead of 'php8.2-ctype'
php8.2-common is already the newest version (8.2.19-1+0~20240514.55+debian12~1.gbp166201).
The following packages were automatically installed and are no longer required:
  php8.2-cli php8.2-opcache php8.2-phpdbg php8.2-readline php8.2-xdebug
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 39 not upgraded.
```

#### Current behavior

```
$ ./phpunit-11.1.3.phar --version
PHPUnit requires the "ctype", "dom", "json", "libxml", "mbstring", "tokenizer", "xml", "xmlwriter" extensions, but the "ctype", "tokenizer" extensions are not available.
```

#### How to reproduce

Just issue the `./phpunit-11.1.3.phar --version` command.

#### Expected behavior

I expect to see the version number of phpunit, not an error message.

**Comment by kubawerlos** [comment]
I thought similar, but: https://github.com/sebastianbergmann/phpunit/pull/5661#issuecomment-1890946854.

**Comment by sebastianbergmann** [comment]
This is not actionable, sorry.
