### ISSUE TITLE
If setUpBeforeClass() fails, test failures are hidden in PHPUnit's JUnit XML output

### ISSUE THREAD

**Issue by meonkeys** [sebastianbergmann/phpunit#587]
If setUpBeforeClass() throws an exception, no failures or errors are reported in the PHPUnit's JUnit XML output.

Example test class:

    <?php
    
    class Test extends PHPUnit_Framework_TestCase
    {
      public static function setUpBeforeClass() {
        throw new \Exception('masks all failures in xml output');
      }
    
      public function testFoo() {
        $this->fail('failing');
      }
    }

Command line:

    phpunit --verbose --log-junit out.xml Test.php

Console output:

    PHPUnit 3.6.10 by Sebastian Bergmann.
    
    E
    
    Time: 0 seconds, Memory: 3.25Mb
    
    There was 1 error:
    
    1) Test
    Exception: masks all failures in xml output
    
    /tmp/pu/Test.php:6
    
    FAILURES!
    Tests: 0, Assertions: 0, Errors: 1.

JUnit XML output:

    <?xml version="1.0" encoding="UTF-8"?>
    <testsuites>
      <testsuite name="Test" file="/tmp/phpunit-broken/Test.php"/>
    </testsuites>

More info:

    $ php --version
    PHP 5.3.10-1ubuntu3.1 with Suhosin-Patch (cli) (built: May  4 2012 02:21:57) 
    Copyright (c) 1997-2012 The PHP Group
    Zend Engine v2.3.0, Copyright (c) 1998-2012 Zend Technologies
        with Xdebug v2.1.0, Copyright (c) 2002-2010, by Derick Rethans

Possibly related:

* http://stackoverflow.com/questions/8407626/is-there-a-way-to-tell-whether-there-are-failures-in-my-phpunit-test-case-from-t

Crosspost: http://stackoverflow.com/questions/10923302/if-setupbeforeclass-fails-test-failures-are-hidden-in-phpunits-junit-xml-out#comment14321031_10923302

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
