### ISSUE TITLE
Include hint in deprecation notice for `--group`, `--exclude-group`, `--covers`, `--uses`, and `--test-suffix CLI` options

### ISSUE THREAD

**Issue by gbirke** [sebastianbergmann/phpunit#5879]
The current message is `Using comma-separated values with --exclude-group is deprecated and will no longer work in PHPUnit 12`. I encountered the deprecation notice and wondered if the feature was removed completely and had to do a code and issue search to see what it was replaced with. Could we include the solution for the deprecation in the message (or maybe as a comment in the code) so people can find it faster? E.g. `Using comma-separated values with --exclude-group is deprecated and will no longer work in PHPUnit 12. You can specify --exclude-group multiple times instead.` If you agree that on that I could also create a pull request.

**Comment by sebastianbergmann** [comment]
Sure, go ahead.
