### ISSUE TITLE
No good upgrade path for `processUncoveredFiles`

### ISSUE THREAD

**Issue by Bilge** [sebastianbergmann/phpunit#5882]
In PHPUnit 9, we had the XML directive `<coverage processUncoveredFiles="true">`. This meant when (and only when) producing the coverage report, uncovered files would be included. Since PHPUnit 10 this is either deprecated or removed, and **there is no good analogue to replace it**.

In PHPUnit 10, the only alternative I have found is to specify the following:

```xml
  <coverage>
    <report>
      <text outputFile="" showUncoveredFiles="true"/>
    </report>
  </coverage>
```

Notwithstanding how verbose this is, this is **not semantically equivalent** to the original because this **implies we want to run code coverage**. There is no _command-line option_ to enable uncovered files reporting, there is only this XML configuration. The only way around this that I have found is to specify `--no-coverage` as the default PHPUnit test runner flag. Since I use Composer scripts that build on the base command, that means my coverage command now actually specifies both `--no-coverage` (inherited from the base command) in addition to `--coverage-text`. Fortunately, this actually works, but it's also true lunacy and probably undocumented behaviour.

I would suggest either:

* Provide a mechanism to specify `showUncoveredFiles` without implying we want to (always) generate code coverage.
* Add a command-line equivalent flag for reporting uncovered files.

Aside, notice we also had to specify `outputFile=""`. This is because `outputFile` is required in XML, even though the command-line equivalent flag `--coverage-text` specifies it as optional. 

>--coverage-text=<file>           Write code coverage report in text format to file [default: standard output]

Though only tangentially related to this issue, I might suggest also making it optional in XML for behavioural parity.

**Comment by sebastianbergmann** [comment]
This works as intended: uncovered files are now always processed (when code coverage reporting is requested).

**Comment by Bilge** [comment]
They are "processed" but they are NOT included in the report. That is not the same thing as being processed.

**Comment by Bilge** [comment]
To be clear:

* I am talking about [The `showUncoveredFiles` Attribute](https://docs.phpunit.de/en/10.5/configuration.html#the-showuncoveredfiles-attribute) (which must be configured because it defaults to `false`).
* You are talking about [The `includeUncoveredFiles` Attribute](https://docs.phpunit.de/en/10.5/configuration.html#the-includeuncoveredfiles-attribute) (which does not need to be configured because it defaults to `true`).

Please reopen and take care to read the issue I spent a decent amount of time carefully typing out instead of reflexively closing everything I submit.

**Comment by sebastianbergmann** [comment]
> You are talking about [The includeUncoveredFiles Attribute](https://docs.phpunit.de/en/10.5/configuration.html#the-includeuncoveredfiles-attribute)

No, I was talking about the `processUncoveredFiles` attribute which you referenced in this issue's title: "No good upgrade path for `processUncoveredFiles`". This option only had an effect on whether uncovered files were processed to detect which lines are executable.

> take care to read the issue I spent a decent amount of time carefully typing out

I am sorry that you got the impression that I did not read your problem description carefully. The mention of `processUncoveredFiles` threw me off.

I do not use PHPUnit in the way you do:

* I do not use the text-based code coverage report
* I do not configure code coverage reports in the XML configuration file (I configure `<source>`, of course) and only instruct PHPUnit to generate a code coverage report using CLI options

After reading this issue a couple of times now, I am almost certain that the problem you describe is a "really bad user experience" due to a conflict between the XML configuration and the CLI options where the text-based code coverage report is concerned.

Does this make sense to you? Can you help me understand your problem and proposed solution better? I am sorry that I have to ask this of you, but I need to better understand this problem in order to address it.

**Comment by Bilge** [comment]
>After reading this issue a couple of times now, I am almost certain that the problem you describe is a "really bad user experience" due to a conflict between the XML configuration and the CLI options where the text-based code coverage report is concerned.

Yes, pretty much, but there's a bit more to it than that.

>Does this make sense to you? Can you help me understand your problem and proposed solution better? I am sorry that I have to ask this of you, but I need to better understand this problem in order to address it.

Certainly, and thank you for asking: when upgrading, we are encouraged to run `--migrate-configuration`. Doing so converts:

```xml
  <coverage processUncoveredFiles="true">
    <include>
      <directory>../src</directory>
    </include>
  </coverage>
```

to

```xml
  <source>
    <include>
      <directory>../src</directory>
    </include>
  </source>
```

That would seem to suggest the migration tool believes these two configurations are equivalent. But they are not. How do we know? Because the behaviour changes. What changes? **About 20% of the classes from my coverage report went missing.**

I spent about an hour trying to figure out why "random" (but deterministic) files were missing from the report. The summary was correct, but some of the individual files were not listed. I eventually realised it was all the files with 0% coverage that were hidden, and there was a separate setting (`showUncoveredFiles`) to restore them. But, as has been already discussed, enabling this option has many (unwanted) side-effects that simply do not exist in the previous version and leave us with a very convoluted configuration/command line to get back to the equivalent behaviour of PHPUnit 9. This could (and should) be improved.

**Comment by sebastianbergmann** [comment]
Going through recent changes, I saw that PHPUnit 11.1 introduced the `--show-uncovered-for-coverage-text` CLI option "to expand the code coverage report in text format to include a list of uncovered files". Does this help?

**Comment by Bilge** [comment]
From the name alone, it sounds like it would, except for the fact that it only exists in the 11 branch. PHPUnit 11 is currently completely unusable for me because it is not compatible with Symfony, which registers its own error handler (incorrectly?) thus causing every test to fail. If it could be backported to 10, then yes, I think it would help 👍🏻

**Comment by sebastianbergmann** [comment]
I have backported this to PHPUnit 10.5 in 80e6b255b81f7583f0dc2c1b0e5f208f0b20527b. Can you try whether the current state of `10.5` solves this issue for you? Thanks!

**Comment by Bilge** [comment]
Confirmed `10.5.x-dev` working as expected: uncovered files are present in the report using `--coverage-text --show-uncovered-for-coverage-text`, even without a `<coverage>` section in the config. Please feel free to tag, and I hope we can continue to work through some of the other (erroneously closed) issues.
