### ISSUE TITLE
`durationSincePrevious()` does not yield time since previous event of same type

### ISSUE THREAD

**Issue by Bilge** [sebastianbergmann/phpunit#5894]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.5.27
| PHP version         | 8.2.15
| Installation Method | Composer

#### Summary

`PHPUnit\Event\Test\Finished->telemetryInfo()->durationSincePrevious()->asFloat() * 1_000` does not appear to yield the number of milliseconds since the previous `Finished` event. It is unclear what, exactly, `durationSincePrevious()` means (since previous _what_, _when?_). However, I assumed I should be able to call this on each test `Finished` event to get the duration since the previous test finished. That does not work. Even if I insert a `sleep()` or some heavy unit of work (calculating a million hashes) that takes several seconds, I still get `0 ms` for _every_ test except the first (which for some reason is always `3 ms`).

![image](https://github.com/sebastianbergmann/phpunit/assets/470626/ce1223d0-b549-4748-9d49-e8919249bdf3)

(Again, I know at least one of these tests takes at least ~1000ms)

#### Current behavior

Duration since previous is always ~0 ms, except for the first test.

#### How to reproduce

Write a whole-ass extension just to find out telemetry is totally bugged.

#### Expected behavior

`durationSincePrevious()` should be the duration since the previous event of the same type was fired.

**Comment by sebastianbergmann** [comment]
> `durationSincePrevious()` should be the duration since the previous event of the same type was fired

No, it should not.

This works as expected: this is intended to be the time since the previous event, not the time since a previous event of the same type.

**Comment by Bilge** [comment]
That explains why it doesn't work, but it doesn't explain what use-case this solves. In what circumstance is this a useful feature?
