### ISSUE TITLE
`Test\Passed` event is not emitted for PHPT tests

### ISSUE THREAD

**Issue by Bilge** [sebastianbergmann/phpunit#5898]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.5.27
| PHP version         | 8.2.15
| Installation Method | Composer

#### Summary

When a test succeeds, it usually emits the `PHPUnit\Event\Test\Passed` event. When it fails (an assertion), it emits `PHPUnit\Event\Test\Failed`. However, PHPT tests do not follow suit; they do correctly emit the `Failed` event, but the `Passed` event is not so emitted. They _do_ emit `AssertionSucceeded`, but as this is marked `@deprecated`, one supposes one cannot rely on this (and it is removed in v11).

#### Current behavior

PHPT tests do not emit the `PHPUnit\Event\Test\Passed` event when they pass.

#### How to reproduce

Write PHPT test with `--EXPECTF--` section that passes.

#### Expected behavior

`PHPUnit\Event\Test\Passed` event is emitted.

**Comment by sebastianbergmann** [comment]
Confirmed for both PHPUnit 10 and PHPUnit 11. Thank you for reporting this!

**Comment by sebastianbergmann** [comment]
This should be as simple as

```patch
diff --git a/src/Runner/PhptTestCase.php b/src/Runner/PhptTestCase.php
index 584de6151..f2c18ec86 100644
--- a/src/Runner/PhptTestCase.php
+++ b/src/Runner/PhptTestCase.php
@@ -199,6 +199,8 @@ public function run(): void
             );
         }
 
+        $passed = true;
+
         try {
             $this->assertPhptExpectation($sections, $this->output);
         } catch (AssertionFailedError $e) {
@@ -232,8 +234,16 @@ public function run(): void
             } else {
                 $emitter->testFailed($this->valueObjectForEvents(), ThrowableBuilder::from($failure), null);
             }
+
+            $passed = false;
         } catch (Throwable $t) {
             $emitter->testErrored($this->valueObjectForEvents(), ThrowableBuilder::from($t));
+
+            $passed = false;
+        }
+
+        if ($passed) {
+            $emitter->testPassed($this->valueObjectForEvents());
         }
 
         $this->runClean($sections, CodeCoverage::instance()->isActive());
```

**Comment by Bilge** [comment]
That does seem to work, yes.

**Comment by Bilge** [comment]
Actually, I'm not sure that is it. It seems we get both `Failed` and `Passed` for failing tests now.

**Comment by Bilge** [comment]
Thank you for the quick fix on this one.

**Comment by Bilge** [comment]
Looking forward to the tag for this.
