### ISSUE TITLE
Call `Extension::bootstrap()` before creating the test suite

### ISSUE THREAD

**Issue by nikophil** [sebastianbergmann/phpunit#5913]
Hello,

I'm wondering if it would be possible to call the `bootstrap()` methods of an extension before the test suite is created?

This would allow third-party libraries relying on PHPUnit to call some boostraping call way sooner, even sooner than calling the data providers.

I've naively tested to move the whole block where `bootstrapExtensions()` is called, before the call of `buildTestSuite()` in `\PHPUnit\TextUI\Application` and it worked in my current project. But I'm may not be aware of some PHPUnit internals which would be a good reason for things to happen in this! :sweat_smile:

**Comment by nikophil** [comment]
Bu the way, I ran the whole test suite with this change, and only one test did fail:

```
1) /home/nikophil/works/github.com/sebastianbergmann/phpunit/tests/end-to-end/extension-xml/phar-extension.phpt
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
 PHPUnit Started (PHPUnit 11.3.0-6-g220aee5a5 using PHP 8.3.9 (cli) on Linux)
 Test Runner Configured
-Test Suite Loaded (1 test)
 Extension Loaded from PHAR (phpunit/phpunit-test-extension 1.0.0)
 Extension Bootstrapped (PHPUnit\TestFixture\MyExtension\MyExtensionBootstrap)
+Test Suite Loaded (1 test)
 Event Facade Sealed
 Test Runner Started
 Test Suite Sorted
```

**Comment by sebastianbergmann** [comment]
Feel free to send a PR with these change for `main`. Thanks!

**Comment by sebastianbergmann** [comment]
Out of curiosity: what kind of bootstrapping do you need to perform "sooner than calling the data providers"?

**Comment by nikophil** [comment]
I'm a maintainer of [Foundry](https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html) which is a data fixture manager for Symfony.

It's not unusual to need those fixtures as provided data, such as:
```php
#[DataProvider('provide')]
public function testSomething(MyObject $object): void
{
    // ... 
}

public static function provide(): iterable
{
    yield MyObjectFactory::createOne();
    yield MyObjectFactory::createOne(['some' => 'attribute']);
}
```

but Foundry raises a `FoundryNotBooted` exception with such code, and we need to use [a workaround](https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#phpunit-data-providers) which is a little cumbersome in my opinion:

```php
#[DataProvider('provide')]
public function testSomething(MyObjectFactory $objectFactory); void
{
    $object = $objectFactory->create();
    // ... 
}

public static function provide(): iterable
{
    yield MyObjectFactory::new();
    yield MyObjectFactory::new([some' => 'attribute']);
}
```

Now, in PHPUnit 11.4, we will be able to boot Foundry before the data providers and use the first piece of code

**Comment by sebastianbergmann** [comment]
Thank you for elaborating!

**Comment by nikophil** [comment]
hey @sebastianbergmann, 

actually, I was diving a little bit more in this whole bootstrapping and what would be ideal for Foundry, seal the `EventFacade` before building the test suites. This would allow to dispatch the event `DataProviderMethodCalled` "directly" (ie: the event would not be deferred). This would actually be very useful for us, in order to fix another quirk in the DX of the lib.

I've tested this whole thing, and managed to make the whole test suites green with not too much efforts (the only thing that actually changes is the order of the event `Event Facade Sealed` in the phpt files.

WDYT?

**Comment by sebastianbergmann** [comment]
I would have to see a PR that implements this to form an opinion on this, I'm afraid.

**Comment by nikophil** [comment]
here it is! https://github.com/sebastianbergmann/phpunit/pull/5917
