### ISSUE TITLE
Display deprecation stacktrace

### ISSUE THREAD

**Issue by nikophil** [sebastianbergmann/phpunit#5921]
Hello,

sometimes finding where a deprecation comes from could be challenging. I think a mechanism in PHPUnit which displays the stack trace of deprecations would be helpful.

In Symfony, they've solved it by the following: if the `SYMFONY_DEPRECATIONS_HELPER` is a regex (I guess, they detect it if the var starts and ends with a `/`, or something like this), they break PHPUnit execution when the first deprecation resolving this regex is found, and the stack trace is printed.
see https://symfony.com/doc/current/components/phpunit_bridge.html#display-the-full-stack-trace

I'm not sure that breaking the execution is the best solution, but at least, it prevents for giant outputs if the test suite is full of deprecations.

I would be willing to contribute for this, but I'm not sure of how this should work. Do you see any other more elegant solution for this? Maybe we can add a new option which would display the stack traces, or at least write them in a file in order to not pollute the output?

thanks!

**Comment by soyuka** [comment]
Indeed, we see that there's the first line of the stack trace, for example:

```
1) src/GraphQl/Type/SchemaBuilder.php:38
blabla

Triggered by:

* ApiPlatform\Tests\Functional\BackedEnumPropertyTest::testGraphQl
  Functional/BackedEnumPropertyTest.php:55
``` 

But when using the `trigger_deprecation` helper from Symfony, all you see is `vendor/symfony/deprecation-contracts/function.php:25`. Not sure how to fix that on the PHPUnit TextUI as it has no verbose mode.

I'm not a huge fan of the `SYMFONY_DEPRECATIONS_HELPER` flag it's complicated to program and isn't quite user-friendly.

**Comment by nikophil** [comment]
maybe just a flag like `--display-deprecation-with-stack` would be enough

**Comment by sebastianbergmann** [comment]
Did you configure Symfony's `trigger_deprecation()` function as a deprecation trigger (see https://github.com/sebastianbergmann/phpunit/issues/5689#issuecomment-2006819389) with PHPUnit?

**Comment by nikophil** [comment]
nope, I didn't know about this configuration, and I think it will be the solution. Thanks!

what about to detect the existence of such triggers to automatically register it?

**Comment by nikophil** [comment]
hum, it seems that it does not work as I expected: `deprecationTriggers` seems to be only involved in the decision whether the deprecation is self/direct/indirect.

Something nice, would be to use these trigger deprecation in order to display the real place where the deprecation was triggered.

meaning, instead of having this:
```
1 tests triggered 1 deprecation:

1) /app/vendor/symfony/deprecation-contracts/function.php:25
some deprecations

Triggered by:

* Tests\SomeTest::testSomething duration
  /app/opa-v4/tests/SomeTest.php:xx
```
it would display:
```
1 tests triggered 1 deprecation:

1) /app/vendor/path/to/real/deprecation.php:xx
some deprecations

Triggered by:

* Tests\SomeTest::testSomething duration
  /app/opa-v4/tests/SomeTest.php:xx
```

**Comment by sebastianbergmann** [comment]
Makes sense, I guess. Do you want to send a PR for this?

**Comment by nikophil** [comment]
yes, let's do this :)
