### ISSUE TITLE
Regression in PHPUnit 8.5.39

### ISSUE THREAD

**Issue by Seldaek** [sebastianbergmann/phpunit#5930]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.5.39
| PHP version         | 7.4 - 8.3
| Installation Method | Composer 

#### Summary

8.5.39 errors out while 8.5.38 does not, I cannot make any sense of it though as literally only [one line of code](https://github.com/sebastianbergmann/phpunit/compare/8.5.38...8.5.39#diff-e0bdcd18ad85fdb9c822f153151d8f24f0320de10a0d02dd68269c7c4b528283L317) changed in that release, beyond dependency updates. I install both with Composer though with latest deps so the only version difference between the working run and failing run is that of phpunit/phpunit.

#### Current behavior

Here is a failing run https://github.com/Seldaek/signal-handler/actions/runs/10521944854/job/29153584072 which fails with:

```
1) Seld\Signal\SignalHandlerTest::testLoggingAndDefaultOnWindows
Error: Class "PHPUnit\Framework\MockObject\Invocation" not found

D:\a\signal-handler\signal-handler\src\SignalHandler.php:279
D:\a\signal-handler\signal-handler\src\SignalHandler.php:518
D:\a\signal-handler\signal-handler\src\SignalHandler.php:500
D:\a\signal-handler\signal-handler\src\SignalHandler.php:279
D:\a\signal-handler\signal-handler\src\SignalHandler.php:518
D:\a\signal-handler\signal-handler\src\SignalHandler.php:500
D:\a\signal-handler\signal-handler\tests\SignalHandlerTest.php:257
D:\a\signal-handler\signal-handler\tests\SignalHandlerTest.php:181
```

And a working run after pinning phpunit to 8.5.38 https://github.com/Seldaek/signal-handler/actions/runs/10522075942/job/29154103527

And FWIW 9.6.20 also works https://github.com/Seldaek/signal-handler/actions/runs/10522259595/job/29154540797

#### How to reproduce

The erroring test:

https://github.com/Seldaek/signal-handler/blob/fc27f191e02186f1a5504318fb9cdae0d6411fbb/tests/SignalHandlerTest.php#L168-L184

#### Expected behavior

No error.

**Comment by sebastianbergmann** [comment]
The test in question has a `@requires OSFAMILY Windows` annotation so I assume you can only reproduce this issue on Windows?

**Comment by Seldaek** [comment]
Unfortunately yes, it does signal handling which is very much OS specific.

**Comment by Seldaek** [comment]
Yeah maybe we just close this.. It works with v9 so I am not stuck. This is probably not going to be worth the time investment.
