### ISSUE TITLE
Allow file wildcards to also include subdirectories

### ISSUE THREAD

**Issue by Wulfheart** [sebastianbergmann/phpunit#5933]
Hello,

in the phpunit.xml file I would like to exclude all directories from the coverage which have e.g. `Foo` in them. Currently, there is no way, as `phpunit/php-file-iterator` uses `glob` which only supports wildcard like `*` and therefore do not allow such things.
However, I discovered, that two weeks ago @nicDamours created a [PR](https://github.com/sebastianbergmann/php-file-iterator/pull/83) and an [issue](https://github.com/sebastianbergmann/php-file-iterator/issues/82). I hope that this lands in PHPUnit soon.

```xml
 <source>
    <exclude>
        <directory>**/Foo/**</directory>
    </exclude>
 </source>
```

**Comment by sebastianbergmann** [comment]
This is similar to #5359, right?

@nicdamours Is there anything in PHPUnit that needs to be done in addition to using php-file-iterator >= 5.1.0?

**Comment by Wulfheart** [comment]
I am closing it as it has been added. Thanks @sebastianbergmann
