### ISSUE TITLE
Simple and concise. PHPUnit 11.x does not work

### ISSUE THREAD

**Issue by omegacms** [sebastianbergmann/phpunit#5938]
None of the configurations suggested in the official documentation allow for coverage testing of an entire project. For some inexplicable reason, there is always a missing filter even when it is passed via command line as illustrated in Chapter 7 of the documentation. Definitely disappointed.

Example

```php
vendor/bin/phpunit --coverage-html coverage-html --coverage-filter vendor/my_project/
```

or

```php
vendor/bin/phpunit --coverage-html coverage-html --coverage-filter src/
```

If putting my file intro a folder called `src`

Return this error

```php
There was 1 PHPUnit test runner warning:

1) Incorrect filter configuration, code coverage will not be processed
```

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by hollodotme** [comment]
I have the same problem when running the PHPUnit 11.3.3 as a PHAR file on an official `php:8.3-cli-alpine` docker image.

I assembled a small repo for reproduction.

Please `git clone` https://github.com/hollodotme/phpunit11

Then follow these steps to reproduce:

### 1. Install tools and dependencies

```bash
make install
```

### 2. Generate a default PHPUnit config

```bash
make phpunit-config
# just hit enter and accept all default values
```

### 3. Run tests locally 

(assumes you have PHP 8.3 or higher installed)

```bash
make phpunit-local
```

#### Output

```
./phpunit.phar -c ./phpunit.xml
PHPUnit 11.3.3 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.3.11
Configuration: /Users/hollodotme/Sites/hollodotme/phpunit-11/phpunit.xml

R                                                                   1 / 1 (100%)

Time: 00:00, Memory: 23.03 MB

There was 1 risky test:

1) hollodotme\phpunit11\Tests\FooTest::testBar
This test does not define a code coverage target but is expected to do so

/Users/hollodotme/Sites/hollodotme/phpunit-11/tests/FooTest.php:10

OK, but there were issues!
Tests: 1, Assertions: 1, Risky: 1.
make: *** [phpunit-local] Error 1
```

Don't know why this test is risky and why it asks for code coverage.

### 4. Run tests on docker image

```bash
make phpunit-docker
```

#### Output

```
docker run --rm -v "/Users/hollodotme/Sites/hollodotme/phpunit-11:/app" php:8.3-cli-alpine php /app/phpunit.phar -c /app/phpunit.xml
PHPUnit 11.3.3 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.3.2
Configuration: /app/phpunit.xml

No tests executed!
```

In my client projects also a `clover.xml` coverage is enabled in the config, which results in the following output:

```
PHPUnit 11.3.3 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.3.11
Configuration: /repo/tests/phpunit.xml

There was 1 PHPUnit test runner warning:

1) Incorrect filter configuration, code coverage will not be processed

No tests executed!
make: *** [phpunit] Error 1
```

The coverage config part is:

```xml
  <coverage>
    <report>
      <clover outputFile="clover.xml"/>
    </report>
  </coverage>
```

**Comment by sebastianbergmann** [comment]
> Don't know why this test is risky and why it asks for code coverage.

The XML configuration file generated using the `--generate-configuration` CLI option configures `requireCoverageMetadata="true"`. Because of this and since the test case class does not have a `[CoversClass]` attribute, for example, the test is considered to be risky. Tests that are considered do not contribute to code coverage.

**Comment by sebastianbergmann** [comment]
> The coverage config part is:
> 
> ```
>   <coverage>
>     <report>
>       <clover outputFile="clover.xml"/>
>     </report>
>   </coverage>
> ```

This only configures code coverage report generation, in this case that a report in Clover XML should be written to `clover.xml`.

This does not, however, configure which code you consider to be your code (which is the code that is considered for code coverage, for example). This is what the `<source>` section in the `phpunit.xml` configuration file is about:

```xml
<source>
    <include>
        <directory>src</directory>
    </include>
</source>
```

Unless you specify your code in the XML configuration file as shown above or using the `--coverage-filter` CLI option code coverage will not be processed.

**Comment by sebastianbergmann** [comment]
> ### 4. Run tests on docker image
> 
> ```shell
> make phpunit-docker
> ```

I do not have Docker installed and will not change that for reproducing this issue, sorry.

I tried using Podman, though:

```
❯ podman run --rm -v "/home/sb/phpunit11:/app:Z" php:8.3-cli-alpine php /app/phpunit.phar -c /app/phpunit.xml
PHPUnit 11.3.3 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.3.11
Configuration: /app/phpunit.xml

.                                                                   1 / 1 (100%)

Time: 00:00, Memory: 23.02 MB

OK (1 test, 1 assertion)
```

As you can see, I cannot reproduce your issue(s).

**Comment by hollodotme** [comment]
Thanks for the detailed and quick responses, @sebastianbergmann!

* The `requireCoverageMetadata="true"` was new to me and does not exist in my client projects, yet. Thanks for the pointer. It worked for me as well when disabled.

* The whole `phpunit.xml` of the client projects does contain the `<source>` part of course, The configs already worked with PHPUnit 11.1.3.

* Well, after restarting orbStack (my docker provider) the execution in the docker images worked again. 

So, all problems solved on my end of the screen. And sorry for not restarting the docker stuff earlier. There was no sign that something had crashed or was malfunctioning. 🤷 

Have a great weekend!

**Comment by omegacms** [comment]
Thank you for your responses, but the problem remains the same as before.

A brief preface. Personally, I am very resistant to the idea of using code designed by other developers, including the test suite, but I accepted it as I am aware of the importance of having well-tested and secure code. However, it's not working as it should and this has made me very bitter.

For now, I'm removing the tests from my project and all dependencies. In the future, I'll decide whether to make another attempt or go back to version 9.7 which worked well and fork it to continue on a parallel development line, adapting it to the specifics of my project.

No offense to the author of PHPUnit, to whom I have great respect and compliments, but I'm just too bitter.

Best of luck.
