### ISSUE TITLE
if run whit make phpunit in docker container dont throw exit 0

### ISSUE THREAD

**Issue by fxpw** [sebastianbergmann/phpunit#5953]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 11.3.5
| PHP version         | 8.3
| laravel        | 11
| Installation Method | Composer / PHAR

#### Summary

Provide a summary describing the problem you are experiencing.
command
```
phpunit_test_t:
	$(exec_in_cp_laravel_app_container_artisan) config:clear
	$(exec_in_cp_laravel_app_container_artisan) test $(t)
```
![image](https://github.com/user-attachments/assets/7ecdd543-2612-408e-8a2e-51bd79fb29a5)
give error 1 but all tests are ok

What is the current (buggy) behavior? 

give error 1 but all tests are ok

Provide steps to reproduce the bug.

run docker container whit php
run make command

#### Expected behavior

expect that be all ok

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by sebastianbergmann** [comment]
No feedback, closing.

**Comment by fxpw** [comment]
> No feedback, closing.

I'm sorry, I didn't see it, I'll make an example a little later, can I open it again?
