### ISSUE TITLE
Provide a way to stop execution at a particular deprecation

### ISSUE THREAD

**Issue by nicolas-grekas** [sebastianbergmann/phpunit#5954]
Deprecation are sometimes hard to track. Figuring the exact stack trace for one particular deprecation is really useful to understand how it comes up and fix it.

It would be awesome to have a command line option (or similar) to tell phpunit to stop and display its stacktrace when a specific deprecation occurs. The match would happen by checking the deprecation message.

For example:
```sh
phpunit --stop-on-deprecation="part of the deprecation message"
```

For sinpiration this capability exists when using Symfony's phpunit-brigde, as documented at https://symfony.com/doc/current/components/phpunit_bridge.html#configuration

**Comment by sebastianbergmann** [comment]
Is this not two separate things?

* Display full stack trace (without frames from PHPUnit and its dependencies) when a deprecation is triggered
* Support `--stop-on-deprecation="part of the deprecation message"`

**Comment by nicolas-grekas** [comment]
It could be, but displaying stacktraces for deprecations standalone is not useful nor actionable: deprecations are best reported grouped, which means without stacktraces. On the other side, stopping on one specific deprecation without the stacktrace just asking to run the command again to make it display the stacktrace. Thus combined behavior is the most useful and actionable.
