### ISSUE TITLE
Deprecation of the `E_STRICT` constant in PHP 8.4

### ISSUE THREAD

**Issue by derrabus** [sebastianbergmann/phpunit#5956]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.6.20, but the 8.5 branch seems to be affected too.
| PHP version         | 8.4-dev
| Installation Method | Composer

#### Summary

PHP 8.4 triggers a deprecation if we access the `E_STRICT` constant.

https://wiki.php.net/rfc/deprecations_php_8_4#remove_e_strict_error_level_and_deprecate_e_strict_constant

That error code is obsolete since PHP 7.0, but some core extensions did still use it in rare cases until PHP 7.4. The deprecation prepares a possible future removal of said constant.

The constant is used inside a `switch` block that triggers different behavior depending on the error level. This means that even if no `E_STRICT` errors are triggered, we get a deprecation notice because PHPUnit accesses a deprecated constant for comparison.

I'd volunteer to work on a fix, but I'm not sure about the way forward. Not handling the `E_STRICT` level at all feels wrong because as long as the level exists, some custom PHP extension could still trigger it. We could just use the plain value of the constant for comparison, assuming that the constant's value will never be changed or repurposed in future PHP releases.

#### Current behavior

```
PHP Deprecated:  Constant E_STRICT is deprecated in /path/to/phpunit/src/Util/ErrorHandler.php on line 99
```

#### How to reproduce

Run a test that triggers PHPUnit's error handler.

#### Expected behavior

No deprecation is triggered.

**Comment by sebastianbergmann** [comment]
PHPUnit 10 and PHPUnit 11 also use this constant.

**Comment by derrabus** [comment]
For reference: php/php-src#13053

**Comment by sebastianbergmann** [comment]
Could it be this simple?

```php
diff --git a/src/Runner/ErrorHandler.php b/src/Runner/ErrorHandler.php
index 9e51f98ba..34ff5f0a2 100644
--- a/src/Runner/ErrorHandler.php
+++ b/src/Runner/ErrorHandler.php
@@ -19,7 +19,6 @@
 use const E_NOTICE;
 use const E_PARSE;
 use const E_RECOVERABLE_ERROR;
-use const E_STRICT;
 use const E_USER_DEPRECATED;
 use const E_USER_ERROR;
 use const E_USER_NOTICE;
@@ -27,7 +26,9 @@
 use const E_WARNING;
 use function array_keys;
 use function array_values;
+use function constant;
 use function debug_backtrace;
+use function defined;
 use function error_reporting;
 use function restore_error_handler;
 use function set_error_handler;
@@ -90,9 +91,12 @@ public function __invoke(int $errorNumber, string $errorString, string $errorFil
         $ignoredByBaseline = $this->ignoredByBaseline($errorFile, $errorLine, $errorString);
         $ignoredByTest     = $test->metadata()->isIgnoreDeprecations()->isNotEmpty();

+        if (defined('E_STRICT') && $errorNumber === constant('E_STRICT')) {
+            $errorNumber = E_NOTICE;
+        }
+
         switch ($errorNumber) {
             case E_NOTICE:
-            case E_STRICT:
                 Event\Facade::emitter()->testTriggeredPhpNotice(
                     $test,
                     $errorString,
```

As I am currently travelling, I do not have access to a build of PHP 8.4-dev with https://github.com/php/php-src/pull/13053. Therefore I cannot check whether `defined('E_STRICT')` and/or `constant('E_STRICT')` also trigger the deprecation. But as these are function calls, we should be able to suppress any `E_DEPRECATED` raised by these using the `@` operator.

**Comment by sebastianbergmann** [comment]
@mvorisek Do you have any insight? Thanks!

**Comment by mvorisek** [comment]
I support the patch above but `@` is needed before `constant('E_STRICT')` - https://3v4l.org/qIUg9/rfc#vgit.master

you can also simplify `@constant('E_STRICT')` into `@E_STRICT` - https://3v4l.org/B60NO/rfc#vgit.master

**Comment by derrabus** [comment]
That was fast, thank you very much!

**Comment by trabrouss1** [comment]
.

**Comment by 4d4ch4u32** [comment]
The error is still present for me, in `/var/www/html/vendor/phpunit/phpunit/src/Runner/ErrorHandler.php` line 93. I'm using PHP 8.4.6.

**Comment by sebastianbergmann** [comment]
@4d4ch4u32 You are the only/first to report that the change implemented in d7d8e73cfc78788ff6c77575e2e7657401282bf2 does not work for them.

I do not understand why the change you propose should be required. Can you please share details about how the current implementation causes an issue for you? Thanks!

**Comment by 4d4ch4u32** [comment]
I have a PHPUnit (v12.1) test using `scandir()` (provided by thecodingmachine/safe) to test the behaviour of my code if the scanned folder does not exist. The test fails with an exception. An exception is expected here, but not with the message:

`Constant E_STRICT is deprecated`.

With my change, the error message is

`An error has occurred.`

I upgraded from phpunit 9 to 12.

<img width="1376" alt="Image" src="https://github.com/user-attachments/assets/b6c70496-3f1b-4e70-8bd7-31b9ff90b5b4" />

**Comment by mvorisek** [comment]
This is possible when the/your error handler does not handle `@` operator well - see https://github.com/atk4/ui/blob/5.2.0/src/App.php#L199.

https://github.com/sebastianbergmann/phpunit/commit/d7d8e73cfc78788ff6c77575e2e7657401282bf2 might be improved to access the constant using reflection instead of error suppression (`@`) operator.

**Comment by sebastianbergmann** [comment]
According to https://3v4l.org/18eA4, the value of `E_STRICT` is always `2048`. Therefore we should be fine to check against a literal `2048` instead of against `@E_STRICT`.

**Comment by mvorisek** [comment]
I am fine with that assumption.

https://3v4l.org/d9GHV solution might be cleaner, but it should be evaluated only once as it might be slow otherwise.
