### ISSUE TITLE
Deprecate support for `#[CoversTrait]` and `#[UsesTrait]` attributes

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#5958]
The `#[CoversTrait]` and `#[UsesTrait]` attributes were introduced in PHPUnit 11.2 while/after working on #5798.

Had I been aware at the time that `#[CoversClass]` and `#[UsesClass]` also target the traits used by the targeted classes, I would not have implemented the `#[CoversTrait]` and `#[UsesTrait]` attributes. As of 17bbefadc2ee94a4729ae8423751421d9decc24a, this behaviour is now documented in tests.

The `#[CoversTrait]` and `#[UsesTrait]` attributes are therefore not needed and will be deprecated in PHPUnit 11.4 and removed in PHPUnit 12.

If you currently use `#[CoversClass]` or `#[UsesClass]` to target traits: don't. Testing traits in isolation from their embedding classes is not useful.

If you currently use `#[CoversTrait]` or `#[UsesTrait]`  to target traits: don't. The traits used by the class(es) you target with `#[CoversClass]` or `#[UsesClass]` will be targeted as well.

**Comment by dshafik** [comment]
@sebastianbergmann I'd like to re-visit this change. It may be my miss-understanding, but I think there is value in this feature as it previously worked.

Specifically, I want to limit coverage counting to the code in a specific trait, to ensure I'm not accidentally marking other code in the class as covered when executing it without any assertions on its behavior.

It is a common pattern to group a feature into a single trait, and then have a test file for just that feature.

I believe the use of `#[CoversTrait]` is superior to `#[CoversClass]` in this instance and leads to more accurate code coverage numbers and no accidental coverage.

**Comment by sebastianbergmann** [comment]
I reverted the deprecation in `11.5` and the removal in `main`.

**Comment by zeleznypa** [comment]
Unfortunately, at this moment, it is not possible to `#[CoversMethod(...)]` for a method defined in a trait.
