### ISSUE TITLE
Deprecate support for targeting trait methods with the `#[CoversMethod]` and `#[UsesMethod]` attributes

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#5960]

**Comment by jrfnl** [comment]
For the next person who is wondering about the deprecation being reverted in PHPUnit 11.5.4 - there is a discussion in https://github.com/sebastianbergmann/phpunit/issues/5958#issuecomment-2614403806 which explains why this has been reverted and won't be removed in PHPUnit 12.
