### ISSUE TITLE
Remove support for targeting trait methods with the `#[CoversMethod]` and `#[UsesMethod]` attributes

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#5961]
Follows #5960.

**Comment by jrfnl** [comment]
For the next person coming upon this ticket - If I understood things correctly, this will no longer be removed in PHPUnit 12 - see the discussion in https://github.com/sebastianbergmann/phpunit/issues/5958#issuecomment-2614403806
