### ISSUE TITLE
Solution for not reporting E_* where their occurence is expected to happen in normal control flow

### ISSUE THREAD

**Issue by arnegroskurth** [sebastianbergmann/phpunit#5962]
Within our application we have a function that waits until a given network port on a given address has been opened. It is something simple like this:

```php
while (time() <= $timeout)
{
   usleep($interval);

    if($socket  = @fsockopen($address, $port))
    {
        @fclose($socket);
        break;
    }
}
```

This function is used in a variety of other functions which are integration-tested using phpunit. As the observed ports are expected to only become available after some duration of time, the `fsockopen()` call throws a couple of `E_WARNING`s (`Warning: fsockopen(): Unable to connect to 127.0.0.1:10001 (Connection refused)`) which are explicitly silenced as they are expected before eventually succeeding.

Now, there seems to be no way to prevent reporting of those warnings by phpunit apart from silencing all `E_*` for all integration-tests using that function via `#[WithoutErrorHandler]` which is obviously not ideal as it can hide other, unexpected warnings and is also not really specific to the targeting test-case but is related to an implementation-detail of that unit under test.

Is there something phpunit offers that I am missing here?

I think the best solution here would be to offer an annotation/attribute-based exclusion mechanism for those similar to what phpstan and other SCA-tools offer via e.g. `/* @phpstan-ignore variable.undefined */`. As attributes cannot be defined for individual lines or function calls, an annotation-based solution like `// @phpunit-ignore warning` is probably more adequate as it provides finer grained control over which statements to target without extracting single lines into functions just to provide that control via attributes.

refs #5686

**Comment by sebastianbergmann** [comment]
@theseer, @localheinz, @staabm, @Schrank, @sebastianheuer, @Tesla91, and I discussed this issue during the PHPUnit Code Sprint in Munich today and we cannot reproduce your problem with current PHPUnit versions.

#### `Issue5962Test.php`
```php
<?php declare(strict_types=1);
namespace PHPUnit\TestFixture;

use PHPUnit\Framework\TestCase;

final class Issue5962Test extends TestCase
{
    public function testOne(): void
    {
        $timeout  = time() + 1;
        $interval = 300000;

        while (time() <= $timeout)
        {
            usleep($interval);

            if($socket  = @fsockopen('127.0.0.1', 6666))
            {
                @fclose($socket);
                break;
            }
        }

        $this->assertTrue(true);
    }
}
```
#### PHPUnit 10.5 (default output)
```
❯ ./phpunit Issue5962Test.php
PHPUnit 10.5.36-16-g941d481a0 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.3.12
Configuration: /Users/sb/Work/OpenSource/phpunit/phpunit.xml

.                                                                   1 / 1 (100%)

Time: 00:01.231, Memory: 10.00 MB

OK (1 test, 1 assertion)
```
#### PHPUnit 10.5 (debug output)
```
./phpunit Issue5962Test.php --debug
PHPUnit Started (PHPUnit 10.5.36-16-g941d481a0 using PHP 8.3.12 (cli) on Darwin)
Test Runner Configured
Bootstrap Finished (/Users/sb/Work/OpenSource/phpunit/tests/bootstrap.php)
Test Suite Loaded (1 test)
Event Facade Sealed
Test Runner Started
Test Suite Sorted
Test Runner Execution Started (1 test)
Test Suite Started (PHPUnit\TestFixture\Issue5962Test, 1 test)
Test Preparation Started (PHPUnit\TestFixture\Issue5962Test::testOne)
Test Prepared (PHPUnit\TestFixture\Issue5962Test::testOne)
Test Triggered Suppressed PHP Warning (PHPUnit\TestFixture\Issue5962Test::testOne)
fsockopen(): Unable to connect to 127.0.0.1:6666 (Connection refused)
Test Triggered Suppressed PHP Warning (PHPUnit\TestFixture\Issue5962Test::testOne)
fsockopen(): Unable to connect to 127.0.0.1:6666 (Connection refused)
Test Triggered Suppressed PHP Warning (PHPUnit\TestFixture\Issue5962Test::testOne)
fsockopen(): Unable to connect to 127.0.0.1:6666 (Connection refused)
Test Triggered Suppressed PHP Warning (PHPUnit\TestFixture\Issue5962Test::testOne)
fsockopen(): Unable to connect to 127.0.0.1:6666 (Connection refused)
Test Triggered Suppressed PHP Warning (PHPUnit\TestFixture\Issue5962Test::testOne)
fsockopen(): Unable to connect to 127.0.0.1:6666 (Connection refused)
Test Triggered Suppressed PHP Warning (PHPUnit\TestFixture\Issue5962Test::testOne)
fsockopen(): Unable to connect to 127.0.0.1:6666 (Connection refused)
Test Triggered Suppressed PHP Warning (PHPUnit\TestFixture\Issue5962Test::testOne)
fsockopen(): Unable to connect to 127.0.0.1:6666 (Connection refused)
Assertion Succeeded (Constraint: is true, Value: true)
Test Passed (PHPUnit\TestFixture\Issue5962Test::testOne)
Test Finished (PHPUnit\TestFixture\Issue5962Test::testOne)
Test Suite Finished (PHPUnit\TestFixture\Issue5962Test, 1 test)
Test Runner Execution Finished
Test Runner Finished
PHPUnit Finished (Shell Exit Code: 0)
```
The (debugging) output looks similar for PHPUnit 11.4.

As you can see, current versions of PHPUnit do not report `@`-suppressed warnings by default.

If you configure `<source ignoreSuppressionOfWarnings="true">` in your [XML configuration](https://docs.phpunit.de/en/11.4/error-handling.html#ignoring-issue-suppression) file then `@`-suppressed warnings will be reported.

Alternatively and/or in addition to the aforementioned ignoring of error suppression, PHPUnit supports the [ignoring of previously reported issues using a baseline](https://docs.phpunit.de/en/11.4/error-handling.html#ignoring-previously-reported-issues).

Unfortunately, you did not provide information which version of PHPUnit you use and whether or not you use a custom error handler. We assume that you do use a custom error handler. If our assumption is correct then would like to suggest to change your production code's custom error handler to ignore `@`-suppressed warnings. You can see how this can be implemented here: https://github.com/sebastianbergmann/phpunit/blob/11.4.1/src/Runner/ErrorHandler.php#L83
