### ISSUE TITLE
Memory size exhaust when generating code coverage report

### ISSUE THREAD

**Issue by simkimsia** [sebastianbergmann/phpunit#597]
Somewhat similar issue with https://github.com/sebastianbergmann/phpunit/issues/353

PHPUnit 3.6.11 by Sebastian Bergmann.

.......................

Time: 6 seconds, Memory: 37.00Mb

OK (23 tests, 348 assertions)

Generating code coverage report in HTML format ...PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes) in /Users/simkimsia/pear/share/pear/PHP/Token/Stream.php on line 205

I have allocated 256M in php.ini

Apparently still not enough.

When I attempt to generate for 1 test, it works.

Please help.

Thank you.

**Comment by FabianPiconeDev** [comment]
@radeksimko your link does not work.
