### ISSUE TITLE
A specific extension for a group or a testsuite

### ISSUE THREAD

**Issue by dmitrach** [sebastianbergmann/phpunit#5975]
Hello!

I use this extension to speed up tests: https://github.com/dmaicher/doctrine-test-bundle 

But it doesn't work with some cases:
- There is no active transaction 
- https://github.com/dmaicher/doctrine-test-bundle/tree/v6.7.5?tab=readme-ov-file#troubleshooting

But these cases work without the extension. 

I would like to use the extension only for some test groups without an additional configuration file. 
Currently I use two configuration files:
- first one uses DAMA\DoctrineTestBundle\PHPUnit\PHPUnitExtension and excludes the failed tests 
- second one doesn't use DAMA\DoctrineTestBundle\PHPUnit\PHPUnitExtension and includes only failed tests.

I would like to set the extension in testsuite or groups something like this:
```xml
<testsuite name="integration">
  <directory>tests/integration</directory>
  <exclude>tests/PathToFailedTest.php</exclude>
  <extensions>
      <extension class="DAMA\DoctrineTestBundle\PHPUnit\PHPUnitExtension" />
  </extensions>
</testsuite>
```

Thanks!

**Comment by sebastianbergmann** [comment]
I would that this is outside the scope of PHPUnit itself and up to the extension to support configuration for which tests it is used.
