### ISSUE TITLE
@coversFile and @coversDirectory annotations

### ISSUE THREAD

**Issue by lukasbestle** [sebastianbergmann/phpunit#5983]
Sometimes a test covers code that is not a class, for example a template file or a configuration file. It is currently not possible to explicitly collect coverage data for such files, especially when the `forceCoversAnnotation` option is used.

I propose two new annotations `@coversFile` and `@coversDirectory` for that use-case.

Also see https://github.com/sebastianbergmann/phpunit/pull/18#issuecomment-679695. @dharkness

**Comment by sebastianbergmann** [comment]
Duplicate of #3794.
