### ISSUE TITLE
Don't block the main process when running a worker process

### ISSUE THREAD

**Issue by staabm** [sebastianbergmann/phpunit#5986]
As it stands atm, phpunit starts worker processes in several scenarios (e.g. in PHPT, but also for other process-isolation stuff).
When such a worker is running the phpunit main process is waiting for it to complete and resumes working after the worker finished.

I think we could make the phpunit overall runtime faster, if the main process would not wait for the worker process.
note: I don't suggest running several workers in parallel, but just prevent blocking the main process while a worker is running.
the main process could e.g. in the meantime run other non-isolated tests instead of waiting for the worker.

my thesis: in the end, we would spent less time waiting which in turn will reduce the overall runtime

**Comment by sebastianbergmann** [comment]
@theseer, @localheinz, @staabm, @Schrank, @sebastianheuer, @Tesla91, and I discussed this issue during the PHPUnit Code Sprint in Munich today and came to the conclusion this is outside the scope of this project.
