### ISSUE TITLE
Run PHPT tests with `-n` option

### ISSUE THREAD

**Issue by staabm** [sebastianbergmann/phpunit#5987]
Overhead of the `php` cli command highly depends on the the number of loaded extensions.
That means, when running it with `-n` option - which prevents automatic loading of extensions - reduces start-up time quite a bit.

example on my windows laptop:
```
mstaab@NB-COMPLEX-61 MINGW64 /c/dvl/Workspace/phpunit (10.5)
$ time php -r 'echo "hello";'
hello
real    0m0.087s
user    0m0.000s
sys     0m0.000s

mstaab@NB-COMPLEX-61 MINGW64 /c/dvl/Workspace/phpunit (10.5)
$ time php -n -r 'echo "hello";'
hello
real    0m0.052s
user    0m0.000s
sys     0m0.000s

$ php -v
PHP 8.2.12 (cli) (built: Oct 24 2023 21:15:35) (NTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.2.12, Copyright (c) Zend Technologies

```

when running tests in PHPT format there is a `--EXTENSIONS--` section.

I am thinking whether we should use `-n` per default in PHPT test-cases and require from the user to declare the required dependencies..?

---

its especially useful when high-overhead extensions like `xdebug`, `blackfire` or similar are loaded per default (e.g. on developer machines)

`blackfire` loaded:
```
mstaab@NB-COMPLEX-61 MINGW64 /c/dvl/Workspace/phpunit (10.5)
$ time php -r 'echo "hello";'
hello
real    0m0.316s
user    0m0.000s
sys     0m0.015s

mstaab@NB-COMPLEX-61 MINGW64 /c/dvl/Workspace/phpunit (10.5)
$ time php -n -r 'echo "hello";'
hello
real    0m0.128s
user    0m0.000s
sys     0m0.000s
```

`xdebug` loaded:
```
$ time php -n -r 'echo "hello";'
hello
real    0m0.128s
user    0m0.000s
sys     0m0.015s

mstaab@NB-COMPLEX-61 MINGW64 /c/dvl/Workspace/phpunit (10.5)
$ time php -r 'echo "hello";'
Xdebug: [Step Debug] Time-out connecting to debugging client, waited: 200 ms. Tr
ied: localhost:9003 (through xdebug.client_host/xdebug.client_port).
hello
real    0m0.537s
user    0m0.015s
sys     0m0.000s
```

**Comment by sebastianbergmann** [comment]
@theseer, @localheinz, @staabm, @Schrank, @sebastianheuer, @Tesla91, and I discussed this issue during the PHPUnit Code Sprint in Munich today and came to the conclusion a solution for this will be too complex for too little performance gain.
