### ISSUE TITLE
Data providers in excluded classes unexpectedly run

### ISSUE THREAD

**Issue by theodorejb** [sebastianbergmann/phpunit#5990]
| Q                          | A
| --------------------| ---------------
| PHPUnit version   | 11.4.1, 10.5.36
| PHP version          | 8.3.12
| Installation Method | Composer

#### Summary

Using PHPUnit 9, running `phpunit --exclude-group myGroup` completely skips testing classes with this group as expected. However, in PHPUnit 10 and 11, data providers in these classes still run, resulting in errors if the data provider depends on extensions or features not available on the current platform.

#### Current behavior

If a class is annotated with `@group myGroup`, and PHPUnit is executed with the `--exclude-group myGroup` command line option, data provider methods in excluded classes unexpectedly run, even though none of the tests in the excluded classes run.

If the data provider in an excluded class throws an exception (e.g. because it depends on an extension that isn't available), PHPUnit outputs the error, as well as the warning: No tests found in class "FooTest". This is very confusing since it was expected that the class would be skipped since it is in an excluded group.

#### How to reproduce

1. Add a data provider which throws an exception to a test class annotated with `@group myGroup`.
2. Add a test to the class that uses the data provider.
3. Run `phpunit --exclude-group myGroup`
4. Note the unexpected error in a class that is supposed to be excluded.

Minimal reproduction here: https://github.com/theodorejb/phpunit-exclude-group-bug

#### Expected behavior

Data provider methods should not run in classes that are in an excluded group.

This appears to be the same issue as #2922, which was fixed in 2017, but then the tests for it were inexplicably removed a few years later in #4570.

**Comment by sebastianbergmann** [comment]
These data providers are also run in PHPUnit 9 (and earlier versions). This is not a bug, but just the way the architecture currently is. Eventually this will be addressed.

**Comment by theodorejb** [comment]
@sebastianbergmann If these data providers also run in PHPUnit 9, why is there no error with that version?

I'm unsure as to how to upgrade past PHPUnit 9 with this issue. Should the data provider annotations be removed and instead every test method call the data provider manually? That seems really ugly when there are a lot of tests using the provider.

**Comment by sebastianbergmann** [comment]
> If these data providers also run in PHPUnit 9, why is there no error with that version?

I do not know your code, sorry.

**Comment by theodorejb** [comment]
@sebastianbergmann I created a minimal reproduction repository to verify the issue: https://github.com/theodorejb/phpunit-exclude-group-bug.

It seems that you are right that the data provider runs in PHPUnit 9 too, since if I put an `exit()` call in it it stops the tests. But for some reason without the `exit()` call, PHPUnit 9 runs the tests successfully, even though the provider throws an exception.
