### ISSUE TITLE
assertDirectoryExists and assertDirectoryDoesNotExist failed

### ISSUE THREAD

**Issue by drkaine** [sebastianbergmann/phpunit#5996]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 11.4
| PHP version         | 8.2
| Installation Method | Composer

```bash 
composer info | sort
myclabs/deep-copy                  1.12.0 Create deep copies (clones) of your...
nikic/php-parser                   v5.3.1 A PHP parser written in PHP
phar-io/manifest                   2.0.4  Component for reading phar.io manif...
phar-io/version                    3.2.1  Library for handling version inform...
phpunit/php-code-coverage          11.0.7 Library that provides collection, p...
phpunit/php-file-iterator          5.1.0  FilterIterator implementation that ...
phpunit/php-invoker                5.0.1  Invoke callables with a timeout
phpunit/php-text-template          4.0.1  Simple template engine.
phpunit/php-timer                  7.0.1  Utility class for timing
phpunit/phpunit                    11.4.1 The PHP Unit Testing framework.
sebastian/cli-parser               3.0.2  Library for parsing CLI options
sebastian/code-unit                3.0.1  Collection of value objects that re...
sebastian/code-unit-reverse-lookup 4.0.1  Looks up which function or method a...
sebastian/comparator               6.1.0  Provides the functionality to compa...
sebastian/complexity               4.0.1  Library for calculating the complex...
sebastian/diff                     6.0.2  Diff implementation
sebastian/environment              7.2.0  Provides functionality to handle HH...
sebastian/exporter                 6.1.3  Provides the functionality to expor...
sebastian/global-state             7.0.2  Snapshotting of global state
sebastian/lines-of-code            3.0.1  Library for counting the lines of c...
sebastian/object-enumerator        6.0.1  Traverses array structures and obje...
sebastian/object-reflector         4.0.1  Allows reflection of object attribu...
sebastian/recursion-context        6.0.2  Provides functionality to recursive...
sebastian/type                     5.1.0  Collection of value objects that re...
sebastian/version                  5.0.2  Library that helps with managing th...
theseer/tokenizer                  1.2.3  A small library for converting toke...
```
#### Summary

assertDirectoryExists pass with a non existant folder and assertDirectoryDoesNotExist failed with the same  folder.

#### Current behavior

I want to test a function who delete a folder, i create the folder and test hes creation, assertDirectoryExists pass.
After i delete  the directory and test if  he don't exist, but assertDirectoryExists pass and assertDirectoryDoesNotExist failed.
When i use a ls i see the folder don't exist, same with file_exist.

#### How to reproduce

```php
public function testDelete(): void
    {
       $packageDirectory = './test/test/1.0.0';

        mkdir($packageDirectory, 0755, true);

        $this->assertDirectoryExists($packageDirectory);

        exec("rm -rf {$packageDirectory}");

        $this->assertFalse(file_exists($packageDirectory)); // => pass
        $this->assertDirectoryExists($packageDirectory); // => pass
        $this->assertDirectoryDoesNotExist($packageDirectory); //  => don't pass
    }
```
 
#### Expected behavior

The expected behavior is that assertDirectoryDoesNotExist pass when the folder don't exist and assertDirectoryExists failed with the same folder

**Comment by sebastianbergmann** [comment]
This is expected behaviour of PHP itself which caches `stat()`, `lstat()`, `file_exists()`, `is_writable()`, `is_readable()`, `is_executable()`, `is_file()`, `is_dir()`, `is_link()`, `filectime()`, `fileatime()`, `filemtime()`, `fileinode()`, `filegroup()`, `fileowner()`, `filesize()`, `filetype()`, and `fileperms()`.

If you call [`clearstatcache`](https://www.php.net/manual/en/function.clearstatcache.php) before the assertions then you get the behaviour you expect.

However, you should call `clearstatcache()` in your production, not in your test code. Otherwise your production code would behave differently in production and during testing.

Alternatively, you can use `rmdir($packageDirectory)` instead of `exec("rm -rf {$packageDirectory}");`. The call to `rmdir()` will invalidate the cache.

**Comment by drkaine** [comment]
Ok thanks you
