### ISSUE TITLE
Please make the default implementation of __toString delegate to toString

### ISSUE THREAD

**Issue by anthonybishopric** [sebastianbergmann/phpunit#600]
I'm writing a tool that uses PHPUnit_Framework_Constraints to perform matching operations on array elements. I have a function that reads like this:

```php
<?php

public function add_constraint(PHPUnit_Framework_Constraint $constraint, $count=1) {
  $this->constraints[] = array('constraint' => $constraint, $count => $count, $matched => 0);
}

/* other functions to increment $matched here... */

public function verify() {
    foreach ($this->constraints as $constraint) {
      
      // This line throws a PHP error because it can't cast constraints to strings
      $this->test->assertEquals($constraint['count'], $constraint['matched'], 
        $constraint['constraint'] . " did not get hit the expected number of times");
    }
}

```

I'd like to be able to leverage all the good work that's been done to add `toString` to constraints - it'd be great if the default implementation of the magic method `__toString` in the parent class delegated directly to `toString`. 

Thank you!

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
