### ISSUE TITLE
Unused exception classes

### ISSUE THREAD

**Issue by staabm** [sebastianbergmann/phpunit#6007]
I was looking thru https://github.com/sebastianbergmann/phpunit/commit/68940184d33e9cc7aca13614438a49674b0d960f with a focus on possibly unused code which maybe can be dropped with a major release.

I found these unused `Exception` classes, which maybe can be deleted?
I did not find references to these files in the codebase.

----

- [X] `PHPUnit\Framework\MockObject\BadMethodCallException`
- [x] `PHPUnit\Framework\MockObject\ReflectionException`
- [x] `PHPUnit\Framework\MockObject\Generator\UnknownClassException`
- [x] `PHPUnit\Logging\Exception`
- [x] `PHPUnit\Metadata\ReflectionException`
- [x] `PHPUnit\Runner\NoIgnoredEventException`
- [x] `PHPUnit\Runner\ReflectionException`
- [x] `PHPUnit\TextUI\Configuration\ConfigurationCannotBeBuiltException`
- [x] `PHPUnit\TextUI\Configuration\IncludePathNotConfiguredException`
- [x] `PHPUnit\TextUI\Configuration\NoCliArgumentException`
- [x] `PHPUnit\TextUI\XmlConfiguration\MigrationBuilderException`
- [x] `PHPUnit\TextUI\ExtensionsNotConfiguredException`
- [x] `PHPUnit\TextUI\ReflectionException`

**Comment by sebastianbergmann** [comment]
`PHPUnit\TextUI\Configuration\ConfigurationCannotBeBuiltException` is thrown in https://github.com/sebastianbergmann/phpunit/blob/main/src/TextUI/Configuration/Builder.php#L47.

**Comment by staabm** [comment]
Awesome, thanks
