### ISSUE TITLE
All functions in standalone file are incorrectly marked as uncovered 

### ISSUE THREAD

**Issue by acelaya** [sebastianbergmann/phpunit#6009]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 11.4.2
| PHP version         | 8.3.8
| Installation Method | Composer

#### Summary

When I run my tests with code coverage enabled, the resulting report indicates all functions in a dedicated `functions/functions.php` file are uncovered, even though some of them have dedicated tests, and others are invoked from classes that are marked as covered.

My `phpunit.xml` config looks like this, with the corresponding `source` directive:

```xml
<?xml version="1.0"?>
<phpunit
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="vendor/phpunit/phpunit/phpunit.xsd"
    bootstrap="./vendor/autoload.php"
    colors="true"
    cacheDirectory="build/.phpunit.cache"
>
    <testsuites>
        <testsuite name="Config">
            <directory>./test</directory>
        </testsuite>
    </testsuites>

    <source>
        <include>
            <directory>./src</directory>
            <directory>./functions</directory>
        </include>
    </source>
</phpunit>
```

And PHPUnit seems to be picking that up correctly:

![image](https://github.com/user-attachments/assets/9c111f7f-7a27-42b6-813d-5e3411f452cd)

This is how my code is autoloaded. The `verndor/autoload.php` function is then used as the tests bootstrap file:

```json
"autoload": {
    "psr-4": {
        "Shlinkio\\Shlink\\Config\\": "src"
    },
    "files": [
        "functions/functions.php"
    ]
},
```

#### Current behavior

Running tests with code coverage marks all functions in a standalone file as uncovered.

#### How to reproduce

The issue can be reproduced in this very small project: https://github.com/shlinkio/shlink-config

1. Clone https://github.com/shlinkio/shlink-config
2. Run `composer install` in the project's root directory.
3. Run `composer test:pretty` (this runs phpunit with `--coverage-html build/coverage-html`).
4. Go to `build/coverage-html` and open the `index.html` file in your browser to see the coverage report.

#### Expected behavior

Functions that are invoked from tests, either directly or indirectly, get marked as covered in the code coverage report.

**Comment by sebastianbergmann** [comment]
I cannot reproduce this:
```
❯ XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-html /tmp/coverage
PHPUnit 11.4.2 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.3.12 with Xdebug 3.3.2
Configuration: /home/sb/shlink-config/phpunit.xml.dist

.................................                                 33 / 33 (100%)

Time: 00:00.160, Memory: 12.00 MB

OK (33 tests, 92 assertions)

Generating code coverage report in HTML format ... done [00:00.020]
```
![grafik](https://github.com/user-attachments/assets/8a9691b2-7566-4a95-88dd-151f69567d9c)

**Comment by acelaya** [comment]
I forgot to mention I use pcov. I haven't actually tried with XDebug, but that's the only difference I can see.

**Comment by sebastianbergmann** [comment]
Can you please try with Xdebug? If that "fixes" this for you then you have found a PCOV issue.

**Comment by acelaya** [comment]
> Can you please try with Xdebug?

Yep, I'll try this afternoon (need to set-up a few things)

> If that "fixes" this for you then you have found a PCOV issue.

Then I don't think that ever gets fixed 😅. I was pushing forward the decision to migrate from pcov to xdebug, this might be the time.

**Comment by acelaya** [comment]
> > Can you please try with Xdebug?
> 
> Yep, I'll try this afternoon (need to set-up a few things)

It was actually not that hard to test.

Yes, it reports the right coverage with xdebug. I'll close this.

Thanks for checking it so quickly!
