### ISSUE TITLE
Migrate configuration from 10.5 to 11.4

### ISSUE THREAD

**Issue by llaville** [sebastianbergmann/phpunit#6023]
Hello,

Working on my project BOX Manifest and [wanted](https://github.com/llaville/box-manifest/issues/14) to migrate from PHPUnit 10 to 11, I've noticed that [include uncovered files](https://docs.phpunit.de/en/11.4/code-coverage.html#including-files) option was not included during migration process.

After installing PHPUnit 11.4.3, I've checks for regressions with following command : 

```shell
vendor/bin/phpunit --display-phpunit-deprecations --no-coverage
```

And got this output : 

```text
[debug] Checking BOX_ALLOW_XDEBUG
[debug] The Xdebug extension is loaded (3.3.2) xdebug.mode=debug,develop
[debug] Process restarting (BOX_ALLOW_XDEBUG=internal|3.3.2|1|*|*)
[debug] Running: [/usr/local/bin/php, -n, -c, /tmp/nWkIvs, vendor/bin/phpunit, --display-phpunit-deprecations, --no-coverage]
[debug] Checking BOX_ALLOW_XDEBUG
[warning] Restarted (264 ms). The Xdebug extension is loaded (3.3.2) xdebug.mode=coverage
PHPUnit 11.4.3 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.2.25
Configuration: /shared/backups/bartlett/box-manifest/phpunit.xml.dist

................................................................. 65 / 91 ( 71%)
..........................                                        91 / 91 (100%)

Time: 00:03.492, Memory: 102.00 MB

There was 1 PHPUnit test runner deprecation:

1) Your XML configuration validates against a deprecated schema. Migrate your XML configuration using "--migrate-configuration"!

OK, but there were issues!
Tests: 91, Assertions: 120, PHPUnit Deprecations: 1.
[debug] Restarted process exited 0
```

So I've run migration process with following command : 

```shell
vendor/bin/phpunit --migrate-configuration
```

Anf got result : 

```text
PHPUnit 11.4.3 by Sebastian Bergmann and contributors.

Created backup:         /shared/backups/bartlett/box-manifest/phpunit.xml.dist.bak
Migrated configuration: /shared/backups/bartlett/box-manifest/phpunit.xml.dist
```

But when I compare versions, I was surprised on `coverage` section that missed previous attribute `includeUncoveredFiles`

Checks with command : 

```shell
diff phpunit.xml.dist.bak phpunit.xml.dist --ignore-space-change
```

That prints : 

```
2,18c2,3
< <phpunit
<     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
<     xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/10.5/phpunit.xsd"
<     backupGlobals="false"
<     backupStaticProperties="false"
<     bootstrap="bootstrap.php"
<     colors="true"
<     stopOnError="false"
<     stopOnFailure="false"
<     stopOnIncomplete="false"
<     stopOnRisky="false"
<     stopOnSkipped="false"
<     beStrictAboutTestsThatDoNotTestAnything="false"
<     processIsolation="false"
<     cacheDirectory=".phpunit.cache"
< >
<     <coverage includeUncoveredFiles="true">
---
> <phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/11.4/phpunit.xsd" backupGlobals="false" backupStaticProperties="false" bootstrap="bootstrap.php" colors="true" stopOnError="false" stopOnFailure="false" stopOnIncomplete="false" stopOnRisky="false" stopOnSkipped="false" beStrictAboutTestsThatDoNotTestAnything="false" processIsolation="false" cacheDirectory=".phpunit.cache">
>   <coverage>
```

BTW, it will be cool if we can same identation after migration. Even if my PHP editor is able to easily re-indent code !

**Comment by llaville** [comment]
FYI: related to my previous report https://github.com/sebastianbergmann/phpunit/issues/6019, when there is a change in configuration (even if it's not expected, like `includeUncoveredFiles` attribute missing), the schema change is well detected.

**Comment by sebastianbergmann** [comment]
> it will be cool if we can same identation after migration

While I agree that losing indentation is an inconvenience, it is annoying enough to invest time/effort in finding a solution to keep it.

**Comment by llaville** [comment]
I've noticed that documentation still identify the `includeUncoveredFiles` attribute, but not the schema [11.4](https://github.com/sebastianbergmann/phpunit/blob/main/schema/11.4.xsd#L58-L69) while schema [10.4](https://github.com/sebastianbergmann/phpunit/blob/main/schema/10.4.xsd#L65) did it.

So, after re-introduced the attribute missing in my `phpunit.xml.dist` config file, I got another (wrong/not expected) warning

```
There was 1 PHPUnit test runner deprecation:

1) Your XML configuration validates against a deprecated schema. Migrate your XML configuration using "--migrate-configuration"! 
```

I think it's an issue, because `includeUncoveredFiles` is not identify by v11.4

**Comment by llaville** [comment]
Oops, I've in mind schema 10.5 and I present schema 10.4, but both identify correctly the missing attribute.

@see https://github.com/sebastianbergmann/phpunit/blob/main/schema/10.5.xsd#L65

**Comment by llaville** [comment]
> While I agree that losing indentation is an inconvenience, it is annoying enough to invest time/effort in finding a solution to keep it.

Agree with you that it's time consuming. But I'll give you the solution, because I wanted to learn more about PHPUnit migration command.

With DOMDocument, when you set `preserveWhiteSpace` and `formatOutput` properties before loading file contents, it won't preserve indentation, and if you did it after it works.


Preserve indentation

```php
<?php
$filename = __DIR__ . DIRECTORY_SEPARATOR . 'phpunit.xml.dist';

$configurationDocument = new \DOMDocument();
// either
//$configurationDocument->load($filename);
// or
$configurationDocument->loadXML(file_get_contents($filename));

$configurationDocument->preserveWhiteSpace = false;
$configurationDocument->formatOutput = true;

var_export($configurationDocument->saveXML());
```

DO NOT preserve indentation

```php
<?php
$filename = __DIR__ . DIRECTORY_SEPARATOR . 'phpunit.xml.dist';

$configurationDocument = new \DOMDocument();

$configurationDocument->preserveWhiteSpace = false;
$configurationDocument->formatOutput = true;

// either
//$configurationDocument->load($filename);
// or
$configurationDocument->loadXML(file_get_contents($filename));

var_export($configurationDocument->saveXML());
```

In summary to fix PHPUnit, you have just to remove the line https://github.com/sebastianbergmann/phpunit/blob/11.4/src/Util/Xml/Loader.php#L67 because the good lines in right place are already defined at https://github.com/sebastianbergmann/phpunit/blob/11.4/src/TextUI/Configuration/Xml/Migration/Migrator.php#L47-L48

**Comment by nathan-de-pachtere** [comment]
@sebastianbergmann Not really sure if it's related to that thread but got warnings with many tags since migrating to 11.4

```
There was 1 PHPUnit test runner warning:

1) Test results may not be as expected because the XML configuration file did not pass validation:

  Line 14:
  - Element 'phpunit', attribute 'convertDeprecationsToExceptions': The attribute 'convertDeprecationsToExceptions' is not allowed.

  Line 31:
  - Element 'coverage', attribute 'includeUncoveredFiles': The attribute 'includeUncoveredFiles' is not allowed.

  Line 32:
  - Element 'include': This element is not expected.

  Line 37:
  - Element 'listeners': This element is not expected.
```

Here is my phpunit.xml.dist file
```xml
<?xml version="1.0" encoding="UTF-8"?>

<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="vendor/phpunit/phpunit/phpunit.xsd"
         backupGlobals="false"
         colors="true"
         bootstrap="tests/bootstrap.php"
         convertDeprecationsToExceptions="true"
         displayDetailsOnTestsThatTriggerDeprecations="true"
         displayDetailsOnTestsThatTriggerErrors="true"
         displayDetailsOnTestsThatTriggerNotices="true"
         displayDetailsOnTestsThatTriggerWarnings="true"
         displayDetailsOnPhpunitDeprecations="true"
>
    <php>
        <ini name="display_errors" value="1"/>
        <ini name="error_reporting" value="-1"/>
        <server name="APP_ENV" value="test" force="true"/>
        <server name="SHELL_VERBOSITY" value="-1"/>
        <server name="SYMFONY_PHPUNIT_REMOVE" value=""/>
        <server name="SYMFONY_PHPUNIT_VERSION" value="11.5"/>
        <!-- ###+ snc/redis-bundle ### -->
        <!-- passwords that contain special characters (@, %, :, +) must be urlencoded -->
        <env name="REDIS_URL" value="redis://localhost"/>
        <server name="SYMFONY_DEPRECATIONS_HELPER"
                value="max[self]=0&amp;max[direct]=0&amp;quiet[]=indirect&amp;quiet[]=other"/>
        <!-- ###- snc/redis-bundle ### -->
    </php>

    <testsuites>
        <testsuite name="Project Test Suite">
            <directory>tests</directory>
        </testsuite>
    </testsuites>

    <coverage includeUncoveredFiles="true">
        <include>
            <directory suffix=".php">src</directory>
        </include>
    </coverage>

    <listeners>
        <listener class="Symfony\Bridge\PhpUnit\SymfonyTestsListener"/>
    </listeners>

    <extensions>
        <bootstrap class="Zenstruck\Browser\Test\BrowserExtension"/>
        <bootstrap class="DAMA\DoctrineTestBundle\PHPUnit\PHPUnitExtension"/>
    </extensions>
</phpunit>
```

Here is the result of `./vendor/bin/phpunit --migrate-configuration`

```
PHPUnit 11.4.4 by Sebastian Bergmann and contributors.

Migration of /app/phpunit.xml.dist failed:
The file does not validate against any known schema
```

**Comment by sebastianbergmann** [comment]
I am sorry for not getting back to this earlier, but now (after working on #6087) that I try to work on this, I have a hard time understanding what exactly does not work for you.

Please provide a minimal XML configuration file that shows the problem you are reporting as well as information which version of PHPUnit accepts the configuration without deprecation warning and which version shows a deprecation warning, but does not correctly migrate the configuration file.

**Comment by sebastianbergmann** [comment]
@nathan-de-pachtere wrote in https://github.com/sebastianbergmann/phpunit/issues/6023#issuecomment-2518067874:

> Not really sure if it's related to that thread but got warnings with many tags since migrating to 11.4

It is not related to the issue reported by @llaville in https://github.com/sebastianbergmann/phpunit/issues/6023#issue-2630258801.

> xsi:noNamespaceSchemaLocation="vendor/phpunit/phpunit/phpunit.xsd"

In the snippet from your PHPUnit XML configuration file shown above, you claim specify that your PHPUnit XML configuration file is compatible with the XML schema definition located at `vendor/phpunit/phpunit/phpunit.xsd`.

Based on the PHPUnit output you included in your comment, I assume that you use PHPUnit 11.4.4. This would mean that `vendor/phpunit/phpunit/phpunit.xsd` is the schema for XML configuration files that are valid with PHPUnit 11.4.

However, your XML configuration file is not compatible with PHPUnit 11.4:

>   Line 14:
>   - Element 'phpunit', attribute 'convertDeprecationsToExceptions': The attribute 'convertDeprecationsToExceptions' is not allowed.
> 
>   Line 31:
>   - Element 'coverage', attribute 'includeUncoveredFiles': The attribute 'includeUncoveredFiles' is not allowed.
> 
>   Line 32:
>   - Element 'include': This element is not expected.
> 
>   Line 37:
>   - Element 'listeners': This element is not expected.
> ```

**Comment by sebastianbergmann** [comment]
I just checked and can report that in PHPUnit 11.5.1 `--migrate-configuration` correctly removes the `includeUncoveredFiles` attribute from the `<coverage>` element.

I am going to close this issue now as I assume that you wanted to report that `--migrate-configuration` does not remove the `includeUncoveredFiles` attribute from the `<coverage>` element.

Please open a new issue (see https://github.com/sebastianbergmann/phpunit/issues/6023#issuecomment-2556814983 for information I need) if that is not what you wanted to report.
