### ISSUE TITLE
assertCount() does not support generators

### ISSUE THREAD

**Issue by urbanecm** [sebastianbergmann/phpunit#6024]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 11.4.3
| PHP version         | 8.3.6
| Installation Method | Composer

#### Summary
`assertCount()` has the following signature:

```php
final public static function assertCount(int $expectedCount, Countable|iterable $haystack, string $message = ''): void
```

According to this signature, I would expect `assertCount()` to be able to process any `iterable` (ranging from arrays over iterators to generators). Specifically, I would expect it to support generators as well: according to [PHP docs on generators](https://www.php.net/manual/en/class.generator.php), a generator implements the `Iterator` interface and as such, it is considered to be an iterable.

However, passing a generator to `assertCount()` results in a `GeneratorNotSupportedException`. From an user's perspective, this is fairly surprising, as this can be only noticed in advance by reading the related PHPUnit's code (PHPUnit's documentation doesn't mention any limitations in this regard). 

Admittedly, I'm unsure why generators are rejected in `assertCount`; whether this is a temporary situation (because implementing support for generators would be eg. too costly or otherwise complicated), or whether expecting `assertCount` to be able to process generators is something PHPunit users should expect. As such, I'm not sure whether this issue should be filled in here, or whether this is something that needs a docs clarification (rather than a change in the code). 

#### How to reproduce

Create the following class:

```php
class Foo {
	private const DATA = [ 1, 2, 3 ];

	public function getData(): iterable {
		yield from self::DATA;
	}
}
```

Using this class, run the following test case:

```php
class FooTest extends TestCase {
	public function testCount() {
		$f = new Foo();
		$this->assertCount( 3, $f->getData() );
	}
}
```

#### Current behavior
Test fails with the `PHPUnit\Framework\GeneratorNotSupportedException` exception:

```
urbanecm@notebook test % ./vendor/bin/phpunit tests 
PHPUnit 11.4.3 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.3.6

E                                                                   1 / 1 (100%)

Time: 00:00.010, Memory: 8.00 MB

There was 1 error:

1) FooTest::testCount
PHPUnit\Framework\GeneratorNotSupportedException: Passing an argument of type Generator for the $haystack parameter is not supported

/Users/urbanecm/tmp/test/tests/FooTest.php:9

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
urbanecm@notebook test % 
```

#### Expected behavior

One of the following:

1. `assertCount()` evaluates the generator, calculates the number of items it generates and compares it with the first parameter (similar to what happens when passing an ordinary iterator)
2. Documentation clearly advises `Generators` are not accepted by `assertCount()`

**Comment by sebastianbergmann** [comment]
This is not a bug, but an intentional limitation: Generators can only be iterated over once and cannot be cloned. Passing a `Generator` object to `assertCount()` therefore changes the state of something that is supposed to be only verified.

See https://github.com/sebastianbergmann/phpunit/issues/4567 for details.

**Comment by sebastianbergmann** [comment]
> PHPUnit's documentation doesn't mention any limitations in this regard

This has now been addressed, thank you for bringing this to my attention.

**Comment by urbanecm** [comment]
Thanks for the quick response and for clarifying the docs! This makes a lot of sense.
