### ISSUE TITLE
`ignoreIndirectDeprecations=true` suppresses deprecations triggered in test code

### ISSUE THREAD

**Issue by ostrolucky** [sebastianbergmann/phpunit#6028]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 11.4.3
| PHP version         | 8.3.3
| Installation Method | Composer

#### Summary
`ignoreIndirectDeprecations="true"` in `source` section apparently also applies to deprecations triggered directly in test cases. I was surprised to find out, because this is a recommended setting, but I find it useful to know about direct deprecations in test files.

#### Current behavior

```
.                                                                   1 / 1 (100%)

Time: 00:00.016, Memory: 8.00 MB

OK (1 test, 1 assertion)
```

#### How to reproduce

composer.json
```json
{
    "require-dev": {
        "phpunit/phpunit": "^11.4"
    }
}
```

phpunit.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit failOnDeprecation="true"
>
    <testsuites>
        <testsuite name="Project Test Suite">
            <file>IssueXTest.php</file>
        </testsuite>
    </testsuites>
    <source ignoreIndirectDeprecations="true">
        <include>
            <directory>src</directory>
        </include>
    </source>
</phpunit>
```

IssueXTest.php
```php
<?php

class IssueXTest extends \PHPUnit\Framework\TestCase
{
    public function test()
    {
        $this->foo = 'bar';
        self::assertSame(true, true);
    }
}
```

#### Expected behavior

```
D                                                                   1 / 1 (100%)

Time: 00:00.017, Memory: 8.00 MB

1 test triggered 1 PHP deprecation:

1) /Users/gostrolucky/Documents/phpunit-repro/IssueXTest.php:7
Creation of dynamic property IssueXTest::$foo is deprecated

Triggered by:

* IssueXTest::test
  /Users/gostrolucky/Documents/phpunit-repro/IssueXTest.php:5

OK, but there were issues!
Tests: 1, Assertions: 1, Deprecations: 1.
```

**Comment by sebastianbergmann** [comment]
This works as intended: test code is always considered to be first-party code.

**Comment by ostrolucky** [comment]
This issue is about phpunit in fact, not doing that. I would expect phpunit report the deprecation, but it doesn't. Please reopen.

**Comment by LastDragon-ru** [comment]
@sebastianbergmann Looks like it is still actual (tested in v12.2.7, 11.5.27, v11.4.4): when `ignoreIndirectDeprecations="true"` the phpunit will not report about dynamic property change.

**Comment by ostrolucky** [comment]
That must be a different case. Issue I had is (and still is) fixed. So I suggest you create a new issue with your reproducer.

**Comment by LastDragon-ru** [comment]
@ostrolucky I'm using exact same code as in the first post and have

```
root@4f94f0d0fd95:/project/tmp/phpunit-test# ./vendor/bin/phpunit
PHPUnit 11.5.27 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.4.10
Configuration: /project/tmp/phpunit-test/phpunit.xml

.                                                                   1 / 1 (100%)

Time: 00:00.167, Memory: 4.00 MB

OK (1 test, 1 assertion)
```

If I set `ignoreIndirectDeprecations="false"` the output will be 

```
root@4f94f0d0fd95:/project/tmp/phpunit-test# ./vendor/bin/phpunit
PHPUnit 11.5.27 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.4.10
Configuration: /project/tmp/phpunit-test/phpunit.xml

D                                                                   1 / 1 (100%)

Time: 00:00.082, Memory: 4.00 MB

1 test triggered 1 PHP deprecation:

1) /project/tmp/phpunit-test/IssueXTest.php:7
Creation of dynamic property IssueXTest::$foo is deprecated

OK, but there were issues!
Tests: 1, Assertions: 1, Deprecations: 1.
```

So seems it was not fixed 🤷‍♂️

**Comment by ostrolucky** [comment]
Ok so for me the case was `ignoreIndirectDeprecations=true`, for you it seems it's `ignoreIndirectDeprecations=false`, so different case. You also seem to have different directory structure.

**Comment by sebastianbergmann** [comment]
@LastDragon-ru Please open a new issue.
