### ISSUE TITLE
--process-isolation causes "Test was run in child process and ended unexpectedly" 

### ISSUE THREAD

**Issue by calbro7** [sebastianbergmann/phpunit#6029]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.6.15
| PHP version         | 8.3.10
| Installation Method | Composer

#### Summary

Running with --process-isolation does not show the proper outcome of a failed test when the trace involves a closure, it displays the message "Test was run in child process and ended unexpectedly".

#### Current behavior

As above.

#### How to reproduce

Run the following:

```
<?php

namespace App\Tests;

use PHPUnit\Framework\TestCase;

class ExampleTest extends TestCase
{
	public static function assertClosureReturnsValue(\Closure $closure, mixed $value): void
	{
		static::assertEquals($value, $closure());
	}

	public function testExample(): void
	{
        static::assertClosureReturnsValue(fn () => 1, 2);
	}
}
```

with `phpunit --filter=ExampleTest --process-isolation`

and see the outcome:

![Screenshot from 2024-11-14 21-22-41](https://github.com/user-attachments/assets/9bb7fa6f-8d20-4cfa-91ee-b03662ee8949)

#### Expected behavior

It should produce the same outcome as running without --process-isolation:

![Screenshot from 2024-11-14 21-23-21](https://github.com/user-attachments/assets/adee61e9-8757-4eba-90c7-913effea22a6)

**Comment by sebastianbergmann** [comment]
**[PHPUnit 9 has reached the end of its bugfix support.](https://phpunit.de/supported-versions.html)**

Please open a new ticket in case you can reproduce this issue with a version of PHPUnit that still receives bugfixes.
