### ISSUE TITLE
Soft-Deprecate `assertContainsOnly()` and `assertNotContainsOnly()`

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#6055]

**Comment by GuySartorelli** [comment]
Is there a suggestion of what should be used instead?

**Comment by sebastianbergmann** [comment]
Sure: https://github.com/sebastianbergmann/phpunit/blob/11.5/DEPRECATIONS.md#soft-deprecations

**Comment by GuySartorelli** [comment]
Thanks. I got to this issue because the deprecation notice in my IDE linked here, so I assume others will also come here looking for answers ;p
