### ISSUE TITLE
Add option to disable coverage by default when <coverage><report> is defined in phpunit.xml (processUncoveredFiles="false" on v9)

### ISSUE THREAD

**Issue by pablorsk** [sebastianbergmann/phpunit#6069]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.5.38
| PHP version         | 8.3.14
| Installation Method | Composer 

#### Summary

If the `<coverage><report>...</report></coverage>` section is defined in phpunit.xml, code coverage is enabled by default, forcing the use of ph`punit --no-coverage` for every execution.

In PHPUnit 9, this behavior could be avoided by setting `<coverage processUncoveredFiles="false">`, but this option has been removed in PHPUnit 10 as part of 602370c.

#### Current behavior

```
$ phpunit 
PHPUnit 10.5.38 by Sebastian Bergmann and contributors.

There was 1 PHPUnit test runner warning:

1) No code coverage driver available

No tests executed!
```

#### How to reproduce

Add this on `phpunit.xml`:
```
    <coverage>
        <report>
            <clover outputFile="cache-dir/clover.xml"/>
            <html outputDirectory="reports-dir/coverage" lowUpperBound="55" highLowerBound="85"/>
        </report>
    </coverage>
```

And run `phpunit`

#### Expected behavior

```
$ phpunit 
PHPUnit 10.5.38 by Sebastian Bergmann and contributors.

..........................
```

**Comment by sebastianbergmann** [comment]
This works as intended.

**Comment by pablorsk** [comment]
Perfect, this might indeed be the intended new behavior.

However, in version 10, ### it seems impossible to define values for a potential `<coverage><report>` configuration without enabling coverage by default. Alternatively, it might be possible to achieve this behavior, but I have not been able to find information on how to do so.

In version 9, this was accomplished using `processUncoveredFiles`, which is no longer available in version 10.
