### ISSUE TITLE
PHP Archives (PHARs) of PHPUnit 8.5 and PHPUnit 9.6 bundle outdated versions of Prophecy

### ISSUE THREAD

**Issue by oleibman** [sebastianbergmann/phpunit#6071]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.6.21
| PHP version         | 8.4.1
| Installation Method | PHAR

#### Summary

Checking some old software for Php8.4 compatibility using 9.6.21 phar. This issue does not arise when I install phpunit 9.6.21 with composer and use it; it is only a problem when using the phar.

#### Current behavior

Many messages like the following, all pointing to Prophecy:
```
PHP Deprecated:  Prophecy\Argument\Token\ExactValueToken::__construct(): Implicitly marking parameter $util as nullable is deprecated, the explicit nullable type must be used instead in phar://C:/git/excel - Copy/unitTests/phpunit-9.6.21.phar/phpspec-prophecy/Prophecy/Argument/Token/ExactValueToken.php on line 36
```

#### How to reproduce

php8.4 phpunit-9.6.21.phar

#### Expected behavior

No deprecation messages.

**Comment by sebastianbergmann** [comment]
[PHPUnit 8.5.41](https://github.com/sebastianbergmann/phpunit/releases/tag/8.5.41) and [PHPUnit 9.6.22](https://github.com/sebastianbergmann/phpunit/releases/tag/9.6.22) have been released. The PHP Archives (PHARs) for these versions contain a version of Prophecy that is compatible with PHP 8.4.

**Comment by oleibman** [comment]
Thank you for taking care of this so quickly.
