### ISSUE TITLE
Make `DefaultResultCache` being able to merge another instance of itself

### ISSUE THREAD

**Issue by Slamdunk** [sebastianbergmann/phpunit#6078]
Hello, in ParaTest we need to be able to run subsets of the Test Suite and then merge the results in a single output.
`\PHPUnit\TestRunner\TestResult\TestResult` does this job flawlessly, but it only covers the tests' output.

The current `\PHPUnit\Runner\ResultCache\DefaultResultCache` doesn't allow ParaTest to run different jobs each with its own cache file and then merge them all together.

I'm here to ask you to implement a way to do that.

Few questions you may answer:

1. Q: What does the merge functionality should do if the `version` differs between the two instances?
    A: Don't care, I'm fine to raise an Exception
2. Q: What does the merge functionality should do if multiple `defects` or `times` exist for the same `$id`?
    A: Don't care, it won't happen in ParaTest, I'm fine to raise an Exception

**Comment by sebastianbergmann** [comment]
I am open to a pull request that implements this. I cannot say when I might be able to work on this.
