### ISSUE TITLE
Code from other traits used in trait not covered through class using trait

### ISSUE THREAD

**Issue by InvisibleSmiley** [sebastianbergmann/phpunit#6080]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 11.5.0
| PHP version         | 8.3.14
| Installation Method | Composer

#### Preface

There's been a lot of back-and-forth regarding trait coverage lately.
Coverage metadata attributes have been added, deprecated and removed, causing a lot of confusion.
We assume here that
1. You understand what you *should* do/use with PHPUnit 11.5.0: Cover traits through classes that use them.
2. The aim is to write tests with coverage metadata that produce no deprecations, warnings or risky tests.

The bug explained below occurs even if you tick all of the above.

#### Summary

Given:
1. A class using a trait using another trait
2. A test to cover code from the innermost trait via the class

#### Current behavior

Your test is marked as risky, because PHPUnit seems to in fact only cover traits directly used by a class.

#### How to reproduce

Assumption: Pick a namespace, put traits/classes/test in separate files, adapt composer autoloading etc.

```
trait T1
{
    public static function x(): int
    {
        return 1;
    }
}


trait T2
{
    use T1;
}


class C
{
    //use T1; // no issues if this is uncommented, but that's cheating
    use T2;
}


// TEST

#[CoversClass(C::class)]
class CTest extends TestCase
{
    public function test(): void
    {
        self::assertSame(1, C::x());
    }
}
```

#### Expected behavior

No risky test, no deprecations, nothing. Just a successful test when run with coverage.

**Comment by sebastianbergmann** [comment]
Thank you for bringing this to my attention, I did indeed forget about "inheritance" between traits.

**Comment by sebastianbergmann** [comment]
This has been moved to https://github.com/sebastianbergmann/code-unit/issues/8 for PHPUnit 11 and to https://github.com/sebastianbergmann/php-code-coverage/issues/1055 for PHPUnit 12.
