### ISSUE TITLE
phpunit command line mentions <directory> argument, but it doesn't run any test of the given dir.

### ISSUE THREAD

**Issue by tenzap** [sebastianbergmann/phpunit#6090]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.5.40
| PHP version         | 8.2.26
| Installation Method | Composer

#### Summary

I have a InstallTest.php file in <PATH>/application/tests/controllers/
If I launch phpunit with that dir, no test is run.
If I launch phpunit with the file in that dir, the tests are run.

#### Current behavior

phpunit doesn't run any test of the given directory.

#### How to reproduce
```
$ "/usr/bin/php" "<PATH>/vendor/bin/phpunit" "<PATH>/application/tests/controllers" --bootstrap <PATH>/application/tests/Bootstrap.php 
PHPUnit 10.5.40 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.2.26

No tests executed!
```

#### Expected behavior

That phpunit runs tests in all files of the directory, recursively

If I run towards a file of this dir, the tests are run.
```
<PATH>$ "/usr/bin/php" "<PATH>/vendor/bin/phpunit" "<PATH>/application/tests/controllers/Install_test.php" --bootstrap <PATH>/application/tests/Bootstrap.php PHPUnit 10.5.40 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.2.26

...                                                                 3 / 3 (100%)

Time: 00:00.074, Memory: 10.00 MB

OK (3 tests, 3 assertions)
```

I could reproduce also with phpunit 9.6.7.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by sebastianbergmann** [comment]
> I'm pretty sure you have a simple directory structure to run the two commands.

I cannot reproduce the problem you describe, hence my request for a reproducing example.

**Comment by sebastianbergmann** [comment]
`Install_test.php` is not a filename that will be recognized as a test by default when searching a directory.
