### ISSUE TITLE
Feature request: Add start() and end() methods to the TestListener interface

### ISSUE THREAD

**Issue by christeredvartsen** [sebastianbergmann/phpunit#610]
Currently there is no way to create a test listener that executes some code before the first test method runs, and after the last test is finished. I know this can be accomplished by adding a listener implementation with the logic in `__construct()` and `__destruct()` but then the listener won't execute the `__destruct()` logic until PHPUnit is finished with all logging and such.

Would it be possible to add two methods to the listener interface for this? For instance `start()` and `end()`, or `setUp()` and `tearDown()`?

Another option would be to let PHPUnit destroy the listeners after the last test method is finished, so that the `__destruct()` methods would get triggered before the logging is done. The cleanest solution IMHO is to add methods to the interface.

I can send a PR against master (3.7) if the feature request is accepted. Since this would break BC (already implemented test listeners will need to add the two new methods) I'm guessing it's a no go for 3.6.

**Comment by sam-at-github** [comment]
:+1:  for this specifically the duck typing version or a new interface. Just hit this issue too - 3 years later.  Has it been implemented??

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
