### ISSUE TITLE
Dependencies on functions which use data providers passed NULL parameter values

### ISSUE THREAD

**Issue by iainp999** [sebastianbergmann/phpunit#611]
When creating a test that depends upon a test which uses a data provider, I am receiving a null parameter.  Using phpunit 3.6.10 (not able to move to 3.6.11 yet).

The following code highlights the issue.

``` php
<?php

class MyTest extends PHPUnit_Framework_TestCase {

    /**
     * @dataProvider myFunc
     */
    public function testCanDoSomeStuff($value) {
        $this->assertNotNull($value);
        return $value;
    }

    /**
     * @depends testCanDoSomeStuff
     */
    public function testCanDoSomeMoreStuff($value) {
        $this->assertNotNull($value);
    }

    /**
     * Data provider function
     */
    public function myFunc() {
      $values = array('22');
      return array($values);
    }
}
```

**Comment by kittencoder** [comment]
It is still not working in PHPUnit version 6.
To provide a Testcase:
I am testing an "external" API. The api provides N sets of test-data.
Currently I am using a data-provider to provide the Requests (url's) and for the expected results to the tests.
my current streamline could looks like this:
1. testApiResponding (uses the dataProvider and saves the responses in a static array.)
2. validateValueOne (uses the dataProvider and gets the response from a static aray.)
3. validateValueTwo (see 2.)
4. validateValueThree (see 2.)
5. and so on...

currently I get multiple errors when there is only one response failure.

The correct (wished) behavoir would be, that the validation tests are only being executed if the response-test was successful per dataset.

this use case does not only apply to API's. I use a simmilar process on many other tests too. (eg. when testing stateful objects). I create N Objects in the provider and then test several transformations and check validity. Some transformations depend on eachother and I get a simmilar massive error-log when there is only a small error happening.

**Comment by sweiguny** [comment]
I have also a good scenario.

I am testing a ORM that has an IdentityMap.

**One test is to add entities to the map.**

This test expects an exception, if the entity was already added to the IdentityMap. If no exception is thrown and the entity was added to the IdentityMap, the test is successful.

**The next test should remove entities from the IdentityMap.**
And that can only work, if it checks for entities, that were added. So it depends on the first test.
Entities that were added and hence are in the IdentityMap are removed. For entities that are not in the IdentityMap an exception is thrown.
