### ISSUE TITLE
Allow custom CLI options

### ISSUE THREAD

**Issue by xrstf** [sebastianbergmann/phpunit#634]
I want to run some Selenium tests with PHPUnit. For this, I need to know what browser and what base-URL to use inside my tests. Since I boot-up phpunit with my own CLI runner wrapper script, I wanted to do something like this:

```php
<?php

define('PHPUnit_MAIN_METHOD', 'PHPUnit_TextUI_Command::main');

// gotta love Composer...
$loader = require __DIR__.'/../src/vendor/autoload.php';
$loader->add('', __DIR__.'/../tests/unit');

// get custom CLI params
$opts = getopt('', array(...));

// define constants based on the params
define('MYPROJECT_TEST_BASE_URL', ...);

// hide options
unset($_SERVER['argv'][5]);

// run PHPUNit
PHPUnit_TextUI_Command::main();
```

Unfortunately, PHPUnit does not allow any other paramters that its own. The "PHPUnit-way" would be to use ```<php>``` sections inside the XML config files (I use XML config files, by the way) to define env variables. But this would make me have a ton of config files (Firefox + http://domainA/, Firefox + Domain B, Chrome + Domain A, Chrome + Domain B, etc.)

I understand the reasoning behind not allowing unknown options. But it should be possible to allow all options starting with ```--custom-``` (or something like that). This would make the CLI runner much more useful and still be relatively safe against typos and deprecated/removed options.

Currently, as a extremely ugly hack, I remove my elements from ```$_SERVER['argv']``` to make PHPUnit work, but I would like to remove this hack some time in the future.

Maybe I'm missing something from the docs about how to run PHPUnit with custom options?

**Comment by oehlschl** [comment]
+1. Would be hugely helpful for us as well.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
