### ISSUE TITLE
$this->at($index); bug?

### ISSUE THREAD

**Issue by TRPB** [sebastianbergmann/phpunit#674]
I'm fairly sure this does not work as intended. 

Consider this:

```
class Foo {
    public function bar($a) {

    }

    public function test() {

    }
}
```

With a test that does:

```
    $mock = $this->getMock('Foo');

    $mock->expects($this->at(0))->method('bar')->with(1);
    $mock->expects($this->at(1))->method('bar')->with(2);
    $mock->bar(1);
    $mock->bar(2);
```

This works exactly as intended/documented. "Returns a matcher that matches when the method it is evaluated for is invoked at the given $index."

However, if another method is called on the mock. For instance:

```
    $mock = $this->getMock('Foo');

    $mock->expects($this->at(0))->method('bar')->with(1);
    $mock->expects($this->at(1))->method('bar')->with(2);
    $mock->bar(1);
    $mock->test();
    $mock->bar(2);
```

The test now fails with an unhelpful error "Mocked method does not exist". It does exist and it works perfectly until the call to $mock->test(). 

Either the documentation needs to be updated to say that $index is the running count of the total number of methods called on the mock or the code needs updating to count on a per method basis.

As it stands, the test will fail based on implementation changes to the code being tested in which it shouldn't fail the test. I don't see why my second test should fail. It's still being called with the right parameters in the correct order. The fact that $mock->test() has been called is irrelevant.

As a bare minimum the returned error "mocked method does not exist" needs to be updated. It's both incorrect and misleading.

**Comment by XedinUnknown** [comment]
Incredibly sorry to ping all of the honorable participants, but I still don't understand how to achieve this, 5 years later. If it was down to returning values every time, then maybe I could do with `withConsecutive()` and `returnValueMap()`. However, my method needs to throw on one of the invocations. @pscheit, was your fix ever incorporated, and if so - where?

**Comment by pscheit** [comment]
No, it wasn't incorporated. I implemented my own expectation in phpunit, but was never very happy with it.

Just use mockery/mockery for this
