### ISSUE TITLE
returnCallback() gets executed before assertions in with() are checked

### ISSUE THREAD

**Issue by ulrichsg** [sebastianbergmann/phpunit#695]
I am currently struggling with a test where I want to check that the argument passed to the mocked method is equal to what I expect. I also have to mutate that argument, which I do using returnCallback() with argument cloning disabled. Unfortunately, at the time the assertion is checked, the object already has been mutated, thus the assertion fails. This feels rather wrong to me.

(Rationale: the method I'm mocking takes a domain object, inserts it into the database and sets the inserted ID in the object. The method I'm testing needs that ID, so I have to make the mock set it, too. On the other hand, this call is also the only place where I can check that the object being inserted is actually correct, as it is not exposed by the method under test, so I have to do both the checking and the mutating in the same expects() call.)

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md) have been reported on the [phpunit-mock-objects](https://github.com/sebastianbergmann/phpunit-mock-objects) project instead.
