### ISSUE TITLE
Util/Printer causes PHP warnings when given an incorrect path

### ISSUE THREAD

**Issue by jurajseffer** [sebastianbergmann/phpunit#698]
PHPUnit v 3.7.8 installed via Composer

Printer class causes PHP to issue warnings on line 102 and 105 in Printer.php when the path to write to exists but as a file, not as a folder.

### How to replicate:

1. Configure testdox via XML or CLI params:
```
<log type="testdox-html" target="../logs/testdox/testdox.html"/>
<log type="testdox-text" target="../logs/testdox/testdox.txt"/>
```

2. Create an empty file "logs/testdox" and run phpunit.

3. Run phpunit:
```
vendor/bin/phpunit tests
```

I only stumbled upon this because I created a single HTML testfox file at first and then reconfigured to use the same path for both - HTML & text version.

### Fix

Printer seems to assume that if it's not a dir, it doesn't exist. Perhaps it would be better if an exception was thrown? E.g.:

```
if (strpos($out, 'php://') === FALSE &&
  !is_dir(dirname($out) && !is_file($out))) {
    mkdir(dirname($out), 0777, TRUE);
  }
  else {
    throw new PHPUnit_Framework_Exception("Unable to create a log directory");
}
```

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
