### ISSUE TITLE
--debug flag has no effect when using --stderr

### ISSUE THREAD

**Issue by wenslayer** [sebastianbergmann/phpunit#719]
In trying to work around the "headers already sent" problem, I'm using --stderr to get my tests to pass. Unfortunately, using --stderr seems to disable the --debug flag I'm also passing to see the details of which tests are running at a given point.

I couldn't find any mention that these flags were incompatible -- are they? If so, should the help be updated? If they should be compatible, perhaps this is a bug then?

Thanks for your help,
-Marc

**Comment by euoia** [comment]
@edorian perhaps we should consider reopening this?

**Comment by henriquemoody** [comment]
Which version are you using @euoia?  A lot of things changed after 302b465. Maybe this bug got back before ea1fea3.

Ps.: When #1550 get merged we can create PHPT tests to avoid this behaviour come back.

**Comment by euoia** [comment]
@henriquemoody 
```
phpunit --version
PHPUnit 4.4.1 by Sebastian Bergmann.
```

**Comment by whatthejeff** [comment]
@henriquemoody @euoia I think the original issue only concerned the CLI options. Feel free to open a new issue, though.
