### ISSUE TITLE
Cannot modify header information - headers already sent by ...

### ISSUE THREAD

**Issue by ph77** [sebastianbergmann/phpunit#720]
Sending header(s) in the test will cause an error:

Cannot modify header information - headers already sent by (output started at /usr/share/php/PHPUnit/Util/Printer.php:172)

There is a simple workaround for this issue by executing phpunit with '--stderr' switch, but I was wondering if there is more information about this problem and if its gonna be fixed.

Thanks!

Tested on PHPUnit 3.7.9 and PHP 5.4.8.

**Comment by paulocastroo** [comment]
In my case, I just added @ prefix to codes that are causing header errors

**Comment by victorbstan** [comment]
For my case, using Symfony, i had to add:

```
web_profiler:
    toolbar: false
```

**Comment by MarcioQuimbundo** [comment]
error_reporting(0) will not solve the problem, but it will clean the output error

**Comment by Yo1L** [comment]
Hi,

I know it's an old issue but I had this problem 2 times this year and I forgot what to do to fix it :)
This post is for my futur me 😄 

In my case, the DebugBar was the problem so just add in your phpunit.xml:
```
<php>
  <env name="APP_DEBUG" value="false"/>
  ...
</php>
```
