### ISSUE TITLE
Allow <php> block inside <testsuite> in phpunit.xml

### ISSUE THREAD

**Issue by vlucas** [sebastianbergmann/phpunit#733]
I am currently trying to wedge in some testing in an old Kohana 2 installation that has a different `<testsuite>` setup for each application it runs. I am using the `<php>` feature to set some required constants and server variables to be able to load the Kohana 2 framework and environment, but the issue is that the way Kohana 2 is setup, the same constant is required to be setup with different values depending on the application that is being tested.

I would like to be able to do this:
```
<?xml version="1.0" encoding="utf-8"?>
<phpunit>
  <!-- Variable setup -->
  <php>
    <const name="EXT" value=".php"/>
    <const name="DOCROOT" value="./"/>
    <const name="MODPATH" value="./modules/"/>
    <const name="SYSPATH" value="./system/"/>
  </php>

  <testsuites>
    <!-- API 2.x tests -->
    <testsuite name="api">
      <php>
        <const name="KOHANA" value="./applications/api/html/index.php"/>
        <const name="APPPATH" value="./applications/api/"/>
      </php>
      <directory suffix=".php">./tests/unit/api</directory>
    </testsuite>

    <!-- API 3.x tests -->
    <testsuite name="api_v3">
      <php>
        <const name="KOHANA" value="./applications/api_v3/html/index.php"/>
        <const name="APPPATH" value="./applications/api_v3/"/>
      </php>
      <directory suffix=".php">./tests/unit/api_v3</directory>
    </testsuite>
  </testsuites>
</phpunit>
```

But currently, PHPUnit does not seem to support the extra `<php>` blocks inside the `<testsuite>` blocks. Is there another way I should be doing this, or does this seem like something PHPUnit could support in the future?

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
