### ISSUE TITLE
"Not" constraints generate a confusing error message

### ISSUE THREAD

**Issue by jasonhinkle** [sebastianbergmann/phpunit#764]
This assertion:

```$this->assertNotContains('required', 'username is required');```

generates the following error message:

```Failed asserting that 'username is not required' does not contain "required"```

Note that 'username is required' has been changed to 'username is *not* required'

I tracked this down to Framework/Constraint/Not::failureDescription which calls the "negate" method.  I see the reason for this is to change the constraint error message appropriately, but it also changes the output that was being tested as well - which mystified me until I tracked this down.

I can see due to the way the message is already generated that Not.php may not be able to reliably figure out what is part of the PHPUnit error and what is the output being tested.  If I were to come up with something would a pull request be considered?

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
