### ISSUE TITLE
Mocking a method with a reference to an object will make argument matches fail

### ISSUE THREAD

**Issue by ghost** [sebastianbergmann/phpunit#796]
Hello,

It would seem that the string formatter changes the parameters of invocations when mocking a method with a reference object.

This issue was not present in 3.7.10 and i noticed it in 3.7.13. This is probably dued to the fix with the references.  Here's a test case showing the problem :

``` php
<?php

Class RandomClass { }

Class MockedClass
{
   public function methodWithoutReference(RandomClass $class) { }

   public function methodWithReference(RandomClass &$class) { }
}

class MyTest extends PHPUnit_Framework_TestCase
{
   public function testWithoutReferenceIsFine()
   {
      $mock = $this->getMockBuilder("MockedClass")->getMock();

      $mock->expects($this->once())->method("methodWithoutReference")->with($this->isInstanceOf("RandomClass"));

      $mock->methodWithoutReference(new RandomClass());
   }
   public function testWithReferenceFails()
   {
      $mock = $this->getMockBuilder("MockedClass")->getMock();

      $mock->expects($this->once())->method("methodWithReference")->with($this->isInstanceOf("RandomClass"));

      $mock->methodWithReference(new RandomClass());
   }
}
```

From the debugging i've done, when a mocked method has a reference parameter, when the code runs in
PHPUnit/Framework/MockObject/Matcher/Parameters.php:148
the call to the ->evaluate method has the $this->invocation->toString() in its parameters.

If you follow the execution inside the toString, you end up in the file
PHPUnit/Util/Type.php:221
Where the method shortenedExport receives the $value as a parameter and reassign that same paramter at line 230
$value = self::toArray($value);

And this, somehow, changes the parameter of the invocation to an array instead of the object it was.

I noticed by placing a breakpoint there, and while stopped, got back in the stack trace up to parameters.php and inspect the $this->invocation object, the first param is a type "RandomClass" and if i step over that line 230 the first param of the invocation object becomes an Array.

So i'm not usre exactly what is happenning here there's a reference somewhere that shouldn't be i suppose, but in any case, reassign a parameter of a method _may_ not be a best practice.

So i changed the code locally to use a local variable instead of the parameter and it fixes the test i wrote above, i don't know if it breaks anything else i haven't run your whole suite.  In any case here the code :

PHPUnit/Util/Type.php:221

``` php
    public static function shortenedExport($value)
    {
        $exportValue = $value;
        if (is_string($exportValue)) {
            return self::shortenedString($exportValue);
        }

        $origValue = $exportValue;

        if (is_object($exportValue)) {
            $exportValue = self::toArray($exportValue);
        }

        if (is_array($exportValue)) {
            return sprintf(
              "%s (%s)",

              is_object($origValue) ? get_class($origValue) . ' Object' : 'Array',
              count($exportValue) > 0 ? '...' : ''
            );
        }

        return self::export($exportValue);
    }
```

**Comment by fotografi** [comment]
>
