### ISSUE TITLE
Data Providers get executed before setupBeforeClass

### ISSUE THREAD

**Issue by vicb** [sebastianbergmann/phpunit#836]
The data providers get called before the static `setupBeforeClass` has been executed. If think it should be the other way around.

Use case:
- We have a list of adapters. Some adapters are only supported on some environment (ie Linux vs Win),
- I would like to initialize a list of supported adapters once and pass it to all the tests through a data provider,
- The cleanest way I can imagine is to initialize a static property in `setupBeforeClass` and have the provider returns that property

The problem is that the property is not initialized when the provider gets called. 

Version found: 3.7.14

**Comment by srosato** [comment]
I might be a bit late to the scene, but what I happen to do when I have dependencies that I need to initialize is to ditch the `@dataProvider` annotation and use `yield` instead.

**Comment by shawnpyle** [comment]
If your `@dataProvider` requires setup code and they aren't terribly large, you can specify them as strings and `eval` them in the test. For example:

```php
public function myProvider() {
    return [
        'new Klass("param 1", "param 2")',
        'new Klass("param 1", "param 2")',
    ];
}

/**
 * @dataProvider myProvider
 */
public testMyFunction($instance_str) {
    $klass = eval("return {$instance_str};");
    # continue testing $klass ...
}
```

**Comment by sweiguny** [comment]
my two cents:

Instead of a dataprovider relying on a static property (which we know isn't possible) I am setting the needed data/objects as class member(s) of the test class in `setUp()` method.
in `tearDown()` i set it/them to null, or when there are complex objects I implement a `clear()` method for it.

as long as there aren't too many test-class-wide dependencies, i feel comfortable with this approach.
but when there are more than one or two such dependencies, you might need to overthink your overall design.

specifically, i use a DB connection as static property which is set in `setUpBeforeClass()` and set `$queryBuilder`, which gets the connection injected, as a class-member in `setUp()` (instead of returning it in a dataprovider).

**Comment by MAChitgarha** [comment]
A solution would be defining a new private method do that. Inside the method, define as many variables as you need as `static` ones. Then, check if one of them is set, and if it is not, set it to the value you want. At last, return all of them (or yield them). This way, _the variables will be declared only once_, even if you have ten providers or whatever. Besides, you can use it in `setUpBeforeClass()` or `setUp()`.

See it in an example:

```php
private static function getData()
{
    static $data, $anotherData;

    if (!isset($data)) {
        $data = new TestClass();
        $anotherData = [];
    }

    return [
        $data,
        $anotherData,
    ];
}

public static function setUpBeforeClass()
{
    list(self::$sampleJson, self::$sampleData) = self::getData(); 
}

public function sampleProvider()
{
    $data = self::getData();

    return [
        $data
    ];
}
```

**Comment by epdenouden** [comment]
@MAChitgarha thanks to your comment yesterday I found out about this ticket. :)

I'm working on refactoring the data provider logic in #3736 which will solve some of the common issues:
- no longer have this huge spike in activity at the start of the run as all data providers get loaded
- data providers can run after the class and test fixtures
- non-static data providers become possible
- generators will be much more efficient

**Comment by MAChitgarha** [comment]
Happy hearing that! ;) The second item in your list is a good one. Waiting for that.

> Non-static data providers become possible

Can't you do that? I always use non-static data providers in my tests instead of static ones, and they work as expected with no issues. Am I wrong?

**Comment by MAChitgarha** [comment]
@epdenouden Happy hearing that! ;) The second item in your list is a good one. Waiting for that.

> Non-static data providers become possible

Isn't it currently possible? I always use non-static data providers in my tests instead of static ones, and they work as expected with no issues. Am I wrong?

**Comment by epdenouden** [comment]
> Isn't it currently possible? I always use non-static data providers in my tests instead of static ones, and they work as expected with no issues (using PHPUnit 7.5.6). Am I wrong?

No, you are correct! My phrasing wasn't precise enough, thanks for bringing this up. Deep down in the data provider handling code it currently reads:

```php
private static function getDataFromDataProviderAnnotation($allTheParameters): ?iterable
    // code for locating the data provider
    // [...]
                if ($dataProviderMethod->isStatic()) {
                    $object = null;
                } else {
                    $object = $dataProviderClass->newInstance();
                }

    // code for preparing returned data rows
    // [...]
}
```

So here's the dirty little secret:
- you can use non-static data providers and
- they will be called on an actual `instanceof` but...
- it's _not the same instance_ that is used for the fixtures and tests

You gave me something to think over and validate regarding the data provider refactoring! I need to add extra tests to make sure the object instances are the expected ones, not just the same type or a clone. ☕️  and 🍰  on me when you're in Amsterdam.

**Comment by epdenouden** [comment]
@MAChitgarha The instances are indeed different: https://github.com/epdenouden/phpunit/blob/4718e0bb470170b2da46bf0e05b7275110a2a29d/tests/_files/DataProviderInstanceTest.php#L14-L27

![image](https://user-images.githubusercontent.com/26651359/61159008-ea3a9d80-a4fa-11e9-940f-cfa4800922dd.png)

**Comment by MAChitgarha** [comment]
@epdenouden But I don't get any failures! In PHPUnit 7.5.13, the assertion doesn't generate any errors. How do you get this error? Backward-incompatibility, you mean?

**Comment by epdenouden** [comment]
This is in the lazy loading data provider branch I am working on. I will check 7.5.x now, thanks for the heads-up

**Comment by epdenouden** [comment]
And @MAChitgarha yes that would be a BC-break

**Comment by MAChitgarha** [comment]
@epdenouden I'll wait for that. For some reasons, in my project, I'm using PHPUnit 7.5.13; but I'm going to update it to 8.2.* soon. And good news, if the BC-break could be fixed. I don't know the structure of the PHPUnit itself, so I don't know what you changed, but I guess that it is possible to fix it. However, it's all up to you! :)

**Comment by epdenouden** [comment]
> And good news, if the BC-break could be fixed. I don't know the structure of the PHPUnit itself, so I don't know what you changed, but I guess that it is possible to fix it. However, it's all up to you! :)

Introducing a backward compatibility break without a very good reason is not something that @sebastianbergmann would allow, so it will be fixed before going into the next version. PHPUnit is a tool used to guard software quality in the PHP community and not my personal playground.

So yes, please tell us what you would like to see as an end-user/developer of tests. Just keep in mind projects like these do not have a large pool of volunteer developers.

**Comment by epdenouden** [comment]
Fun fact: the test above indeed works on both versions 7.x and 8.x and fails on the JIT prototype. 

The code I am working on is being much more like the the original code flow still. So it might be the result of a bug, some still logic I still need to refactor further, something low-level about objects and reflection in PHP I need to look up or  maybe just some naive testing on my part. 🔬

**Comment by MAChitgarha** [comment]
@epdenouden JIT? Are you testing with JIT for PHP, or there's something I don't know? Sorry, I'm a bit confused; are you talking about PHP7.x and PHP8.x or PHPUnit7.x and PHPUnit8.x?!

**Comment by epdenouden** [comment]
> @epdenouden JIT? Are you testing with JIT for PHP, or there's something I don't know? Sorry, I'm a bit confused; are you talking about PHP7.x and PHP8.x or PHPUnit7.x and PHPUnit8.x?!

@MAChitgarha ah yes, I understand your confusion as PHP8 is getting a just-in-time _compiler_, but I was using it for the new [data provider implementation](https://github.com/sebastianbergmann/phpunit/issues/3736) which is based on the same idea, getting a just-in-time _loader_ a.k.a. lazy-loading. Initialize only what you need, when you need it. 🚀 

This will work fine with the upcoming PHP version 8 JIT as it doesn't use any tricky use of the PHP language itself. All my work is deep inside PHPUnit redoing things configuration parsing, test loading and running, etc.

If it looks like I am not doing anything, I am doing it right. Except for that lowered  GCP/AWS invoice 💸
