### ISSUE TITLE
No stacktrace (location info) about test failure for TAP format

### ISSUE THREAD

**Issue by tmysik** [sebastianbergmann/phpunit#840]
If one uses TAP format and any test fails, the output is e.g.:

```
not ok 1 - Failure: Calculator2Test::testAdd
  ---
  message: 'Failed asserting that -5 matches expected 0.'
  severity: fail
  data:
      got: -5
      expected: 0
  ...
```

Woud it be possible to add information about the exact location of the test failure? I am not sure (I got 404 for the protocol description [1]) but it seems to me that it must be a comment, so e.g.:
```
# location: /home/gapon/NetBeansProjects/calc/test/Calculator2Test.php:37
```

Thanks a lot.
[1] http://podwiki.hexten.net/podwiki.pl?page=TAP

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
