### ISSUE TITLE
@dataprovider for another @dataprovider is this should working? 

### ISSUE THREAD

**Issue by mmuruev** [sebastianbergmann/phpunit#899]
I have chain data-provider A provide parameter for data-provider B and the last one provide for tests. But in second one I have test method name instead values from B, is this bug? Any chance have chained dataprovider? (For code reusable).

**Comment by bishopb** [comment]
I find myself using Cartesian product quite a bit in tests, so I use [this helper method](http://stackoverflow.com/a/15973172/2908724).  Would be nice to have it in PHP Unit, but certainly not necessary.

**Comment by cooper-walk** [comment]
@mmuruev https://evanexclusive39.github.io/wEPNwy7Ggedz5AHgIjtM4rQ7Jo5wWDu5xgjk9AqFkc4wNsyLBEhntj6JGsoJe8b--7t5L_b9QHYAIUM1s7gv/
