### ISSUE TITLE
Support namespaces or package annotations in @covers

### ISSUE THREAD

**Issue by JeroenDeDauw** [sebastianbergmann/phpunit#906]
Right now code coverage support obtained by a test can be limited to one or more specified classes using the @covers annotation. This is great for unit tests. However for integrations tests it would be nice if such limitation could be specified per component. This could be done by specifying a namespace or a group/package specified by @ingroup or @package

**Comment by iandunn** [comment]
xref https://github.com/sebastianbergmann/php-code-coverage/issues/166
