### ISSUE TITLE
interface error load

### ISSUE THREAD

**Issue by geniv** [sebastianbergmann/phpunit#915]
hi, I using unit test fot test my framework...
I have interface (in file icron):

``` php
interface ICron {
  public static function synchronizeCron();
}
```

...class loadinf with __autoload 
and class with this interface (in file tpl):

``` php
final class Tpl implements ICron {
...
  public static function synchronizeCron() {
    ....
  }
}
```

but if run test then I give this result:

$ phpunit --bootstrap classes/tpl.php TplTest
PHP Fatal error:  Interface 'classes\ICron' not found in /var/www/www/git/goodflow/phpcore/classes/tpl.php on line 20
PHP Stack trace:
PHP   1. {main}() /usr/bin/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /usr/bin/phpunit:46
PHP   3. PHPUnit_TextUI_Command->run() /usr/share/php/PHPUnit/TextUI/Command.php:129
PHP   4. PHPUnit_TextUI_Command->handleArguments() /usr/share/php/PHPUnit/TextUI/Command.php:138
PHP   5. PHPUnit_TextUI_Command->handleBootstrap() /usr/share/php/PHPUnit/TextUI/Command.php:548
PHP   6. PHPUnit_Util_Fileloader::checkAndLoad() /usr/share/php/PHPUnit/TextUI/Command.php:778
PHP   7. PHPUnit_Util_Fileloader::load() /usr/share/php/PHPUnit/Util/Fileloader.php:76
PHP   8. include_once() /usr/share/php/PHPUnit/Util/Fileloader.php:92

I dont understand... class ICron exist, icron exist, and include icron in test too...
andt this class structure is normaly function in apache2 ...

**Comment by daguigonz** [comment]
sape
