### ISSUE TITLE
Using throwException inside returnValueMap doesn't work

### ISSUE THREAD

**Issue by MTGap** [sebastianbergmann/phpunit#974]
I'm trying to use mocks to throw an exception if a method is called with specific arguments. It doesn't work when using a returnValueMap. However, it works fine when I call $this->throwException inside will()

Here's an example of this in code: https://gist.github.com/MTGap/6107547
And the result:

> There was 1 failure:
> 1) ThrowException::testCatchingExceptionWithMap
> Failed asserting that false is true.

**Comment by batusa** [comment]
would be nice if we had a method that would allow us to check for exceptions based on certain arguments. @whatthejeff will we have something like that in the near future?

**Comment by elboletaire** [comment]
> @whatthejeff will we have something like that in the near future?

Or a workaround for this?

**Comment by lezhnev74** [comment]
@elboletaire, @batusa, I believe you can set callback to decide which values to return:

```php
$callback = function($arg) {
            if($arg == "A") {
                return "Good response"
            }
            if($arg == "B") {
                throw new Exception("Bad response");
            }
};
$stub = $this->createMock(Some::class);
$stub->method('MOckingMethod')->will($this->returnCallback($callback));
```
